### PR TITLE
fix: cp-13.6.0 adding network does not update balance

### LINKED ISSUE #36806: [Bug]: Assets - USDC Ethereum token appears in repeated entries for the same network (Mainnet) and also appears on other networks
### Describe the bug

USDC Ethereum token appears in repeated entries for the same network (Mainnet) and also appears on other networks

[tokens-controller.js](https://github.com/user-attachments/files/22881961/tokens-controller.js)

### Expected behavior

_No response_

### Screenshots/Recordings

1. See 2 entries of USDC (Ethereum) token in Binance Chain

Image

2. See 3 entries of USDC (Ethereum) token in Ethereum Chain

Image

See

https://github.com/user-attachments/assets/c60aef3f-7561-4446-b961-19149a7b113b

### Steps to reproduce

1. I had Mainnet selected (no new networks added)
2. I went to uniswap https://app.uniswap.org/swap
3. Connected the wallet
4. Select BNB token for the Swap
5. This triggered a MetaMask popup for adding Binance chain
6. I accepted the modal
7. Selected USDC Binance as destination token
8. Perform the Swap and accepted
9. Went to the full view of the wallet
10. Started seeing USDC Mainnet tokens appearing as stated above

Not sure if related or not, but I also saw several logs for this error:  [Error: No metadata found for 'enabledNetworkMap'](https://github.com/MetaMask/metamask-extension/issues/36804)

Image

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #36845: [Bug]: When Network manager selection is Solana and a new popular network is added, the DeFi and NFTs tabs are missing
### Describe the bug

When the Network manager selection is Solana and a new popular network is added, the DeFi and NFT tabs are missing until swithcing to popular networks or that network again.

### Expected behavior

DeFi and NFTs tab not missing

### Screenshots/Recordings

https://github.com/user-attachments/assets/bdb8b8fe-0c57-4484-abdc-16525e5eb259

Image

### Steps to reproduce

1. Switch to Solana network in Network manager
2. Add a popular network
3. Notice DeFi and NFT tabs are missing
4. Switch to a different network or All popular networks
5. Notice DeFi and NFTs tabs are displayed again

### Error messages or log output

```shell
No error message
```

### Detection stage

During release testing

### Version

13.5.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

Sev2

### PR DESCRIPTION
**Pull request by juanmigdr**
## **Description**
When adding a network the `selectedNetworkClientId` was not being updated and many of our components still depend on it. That is why a refresh was needed after adding a network

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37062?quickstart=1)

## **Changelog**

CHANGELOG entry: when adding a network the `selectedNetworkClientId` was not being updated and many of our components still depend on it

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36845 & https://github.com/MetaMask/metamask-extension/issues/36752 & https://consensyssoftware.atlassian.net/browse/ASSETS-1482 & https://github.com/MetaMask/metamask-extension/issues/36775 & https://consensyssoftware.atlassian.net/browse/ASSETS-1546 & https://consensyssoftware.atlassian.net/browse/ASSETS-1416
Maybe also fixes: https://github.com/MetaMask/metamask-extension/issues/36806

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adding a network now automatically becomes the active network; UI no longer manually sets it active.
> 
> - **Background (controller)**:
>   - Add `_addNetworkAndSetActive(networkConfiguration)` to add a network then set it active via its default RPC endpoint `networkClientId`.
>   - Replace exposed `addNetwork` API usages to call `_addNetworkAndSetActive` (both general UI API and multichain provider API paths).
> - **UI (networks form)**:
>   - Remove manual `setActiveNetwork` after `addNetwork`; rely on background to activate the new network.
>   - Clean up related imports/types; still enables the network post-add.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 3b5c1cd87c760804f6d40e60e957d3bcadc9541d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by davidrentc — DISMISSED** [review]

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -6597,21 +6597,7 @@ export default class MetamaskController extends EventEmitter {
         this.networkController,
       ),
       setActiveNetwork: async (networkClientId) => {
-        // if the origin has the CAIP-25 permission
-        // we set per dapp network selection state
-        if (
-          this.permissionController.hasPermission(
```
Comment (salimtb) [inline app/scripts/metamask-controller.js:6603]: we have to be carefull here , removing this code can introduce a bug on the dapp connectivity , checking now

Comment (juanmigdr) [reply app/scripts/metamask-controller.js:6603]: Checking with them!

**Review by salimtb — DISMISSED** [review]

**Review by salimtb — APPROVED** [review]

File: ui/pages/settings/networks-tab/networks-form/networks-form.tsx [hunk 2]
```diff
@@ -312,16 +310,7 @@ export const NetworksForm = ({
...
-          const addedNetworkConfiguration = (await dispatch(
-            addNetwork(networkPayload),
-          )) as unknown as NetworkConfiguration;
-
-          const networkClientId =
-            addedNetworkConfiguration?.rpcEndpoints?.[
-              addedNetworkConfiguration.defaultRpcEndpointIndex
-            ]?.networkClientId;
-
-          await dispatch(setActiveNetwork(networkClientId));
```
Comment (sahar-fehri) [inline ui/pages/settings/networks-tab/networks-form/networks-form.tsx:324]: Curious why it was not being updated since it looks like we are calling the setActiveNetwork here;
Did we just remove this line and now we are calling the setActive inside _addNetworkAndSetActive ?

**Review by sahar-fehri — APPROVED** [review]

File: ui/pages/settings/networks-tab/networks-form/networks-form.tsx (hunk 2 above)
Comment (juanmigdr) [reply ui/pages/settings/networks-tab/networks-form/networks-form.tsx:324]: The issue is that it wasn't being updated from other places. That place was doing the job correctly but other werent, I just centralized the logic
