### PR TITLE
NFTs: Use Unknown Collection instead of first NFT name

### LINKED ISSUE #18362: [Bug]: Collection name for ERC1155 displays incorrect value
### Describe the bug

**Problem**: the collection name for ERC1155 is displaying an incorrect value (the name of the first NFT imported for that collection). We should display the collection name.

https://user-images.githubusercontent.com/54408225/228555134-6e5ae7b1-ceda-4764-82d8-d3a3f5793617.mp4

**Example**: on the [test dapp](https://metamask.github.io/test-dapp/), we are using the following contract with the collectio name `ERC1155`. This value should be expected as the Collection name for the NFTs we mint from the test-dapp

image

Here is what we see displayed on Opensea. The collection name here  is indeed `ERC1155` (screenshot provided by @PeterYinusa )

image

### Steps to reproduce

1. Go to test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Deploy ERC1155
4. Mint some NFTs
5. Import NFTs to MetaMask -- see collectio name takes the value of the first NFT that you imported (Rocks, Paper or Scissors)

### Error messages or log output

_No response_

### Version

10.26.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

Instead of using the first NFT in the collection as the collection name, when no name is available, we should use "Unknown collection"

* Fixes #18362

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/hooks/useNftsCollections.js [hunk 1]
```diff
@@ -5,10 +5,10 @@ import { getNfts, getNftContracts } from '../ducks/metamask/metamask';
 import { getCurrentChainId, getSelectedAddress } from '../selectors';
 import { usePrevious } from './usePrevious';
 
-export function useNftsCollections() {
+export function useNftsCollections(previouslyOwnedText, unknownCollectionText) {
```
Comment (danjm) [inline ui/hooks/useNftsCollections.js:8]: Instead of passing these in, you can call `useI18nContext` within this hook (see here: https://github.com/MetaMask/metamask-extension/pull/18389)

**Review by danjm — CHANGES_REQUESTED** [review]

File: ui/components/app/nfts-tab/nfts-tab.js [hunk 2]
```diff
@@ -34,7 +34,7 @@ export default function NftsTab({ onAddNFT }) {
   const dispatch = useDispatch();
 
   const { nftsLoading, collections, previouslyOwnedCollection } =
-    useNftsCollections();
+    useNftsCollections(t('nftsPreviouslyOwned'), t('unknownCollection'));
```
Comment (danjm) [inline ui/components/app/nfts-tab/nfts-tab.js:37]: I don't think we have a translation for `'nftsPreviouslyOwned'`

File: ui/hooks/useNftsCollections.js (hunk 1 above)
Comment (darkwing) [reply ui/hooks/useNftsCollections.js]: Done!

File: ui/components/app/nfts-tab/nfts-tab.js (hunk 2 above)
Comment (darkwing) [reply ui/components/app/nfts-tab/nfts-tab.js]: Fixed, that should've been in initial commit.

**Review by danjm — DISMISSED** [review]
LGTM

**Review by danjm — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]
