### PR TITLE
Fix slow web3 injection bug

### LINKED ISSUE #1340: Web3 Sometimes Injected Late
On Slack, user `murbard` reports web3 is injecting after the document `load` event.

Opening this issue to ask him to comment more with system + browser versions, and hopefully even a page for reproducing the issue.

### PR DESCRIPTION
**Pull request by danfinlay**
As long as MetaMask has been an extension, it has been plagued by a bug where web3 would sometimes be injected late.

I even have [a sample web app here](https://danfinlay.github.io/chrome-contentscript-bug-reproduction/) that allows you to confirm that this bug exists for you now!

With this PR, a change to the way the in-page provider is injected makes it now synchronous, appearing to fix this problem.

Fixes #1340 

Huge thanks to `agentm....` on [this Chromium thread](https://bugs.chromium.org/p/chromium/issues/detail?id=634381#c28) for the idea of how.

### CODE REVIEW

File: app/scripts/contentscript.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ const ObjectMultiplex = require('obj-multiplex')
 const extension = require('extensionizer')
 const PortStream = require('./lib/port-stream.js')
 
-const inpageText = fs.readFileSync(path.join(__dirname, 'inpage.js')).toString()
+const inpageText = fs.readFileSync(path.join(__dirname, '..', '..', 'dist', 'chrome', 'scripts', 'inpage.js')).toString() + '//# sourceURL=' + extension.extension.getURL('scripts/inpage.js') + '\n'
```
Comment (kumavis) [inline app/scripts/contentscript.js]: can we clean this up a bit?
maybe make it a couple lines

File: gulpfile.js [hunk 2]
```diff
@@ -186,8 +186,8 @@ jsFiles.forEach((jsFile) => {
   gulp.task(`build:js:${jsFile}`, bundleTask({ watch: false, label: jsFile, filename: `${jsFile}.js` }))
 })
 
-gulp.task('dev:js', gulp.parallel(...jsDevStrings))
-gulp.task('build:js',  gulp.parallel(...jsBuildStrings))
+gulp.task('dev:js', gulp.series(jsDevStrings.shift(), gulp.parallel(...jsDevStrings)))
```
Comment (kumavis) [inline gulpfile.js]: not clear whats going on here, lets make it more readable

Comment (danfinlay) [reply gulpfile.js]: Will change. Spoiler: `.shift()` returns the first element, and mutates the array to remove the first element. This way, we ensure the first element (inpage.js) is built before all the other scripts, which can be built in parallel, because we need to include it with `brfs` into the `contentscript`, needs to be built at that time.

File: app/scripts/contentscript.js [hunk 3]
```diff
@@ -7,7 +7,9 @@ const ObjectMultiplex = require('obj-multiplex')
 const extension = require('extensionizer')
 const PortStream = require('./lib/port-stream.js')
 
-const inpageText = fs.readFileSync(path.join(__dirname, 'inpage.js')).toString()
+const inpagePath = path.join(__dirname, '..', '..', 'dist', 'chrome', 'scripts', 'inpage.js')
+const inpageString = fs.readFileSync(inpagePath).toString()
```
Comment (kumavis) [inline app/scripts/contentscript.js]: does this still work? seems like it would break brfs, but maybe not

**Comment by kumavis** [comment]
im not sure how this is passing lint, `fs` is undefined

**Comment by kumavis** [comment]
i see, brfs strips the `require('fs')` line, but couldnt replace the `fs.readFileSync(inpagePath)`

**Comment by kumavis** [comment]
QA'd, works great

**Review by kumavis — APPROVED** [review]
