### PR TITLE
fix: fix snaps permission flow ui

### LINKED ISSUE #30087: Too much padding in permission flow
#29824 introduced a regression to the permission flow, where there's now too much padding around the content. See the screenshot below:

Image

This is what it looks like in production:

Image

### PR DESCRIPTION
**Pull request by ffmcgee725**
Issue described [here](https://github.com/MetaMask/metamask-extension/issues/30087)

This commit fixes the snaps permission flow UI bug detected after https://github.com/MetaMask/metamask-extension/pull/29824

Screenshots after fix:

Screenshot 2025-02-04 at 20 20 37
Screenshot 2025-02-04 at 20 20 53

## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30116?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30087

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/helpers/utils/permission.js [hunk 1]
```diff
@@ -56,14 +52,8 @@ function getSnapNameComponent(snapName) {
...
-    });
-    const requestedAccounts = getEthAccounts(caveatValue);
-    const isLegacySwitchChain = requestedAccounts.length === 0;
-
-    if (isLegacySwitchChain) {
+  [Caip25EndowmentPermissionName]: ({ t, isLegacySwitchEthereumChain }) => {
+    if (isLegacySwitchEthereumChain) {
       return {
         label: t('permission_walletSwitchEthereumChain'),
         leftIcon: IconName.Wifi,
```
Comment (ffmcgee725) [inline ui/helpers/utils/permission.js:59]: we are now pulling the flag directly from the request object provided by calling `approvalController.addAndShowApprovalRequest` for `wallet_switchEthereumChain` legacy request.

For all other flows, UI should remain untouched now with no unpredictable behaviour 👍🏾

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Review by FrederikBolding — APPROVED** [review]
