### PR TITLE
fix: Hex data should be cleared out during ERC20 Send

### LINKED ISSUE #19140: [Bug]: Changing an ERC20 Send to ETH Send, does not clear Hex Data on the UI Edit screen
### Describe the bug

**Problem**: whenever I am performing an ERC20 Send, if I change the asset to ETH, I can see how the Hex Data field is not empty, and it's displaying the data for the previous ERC20 Send. This should not be the case, and Hex Data should be cleared whenever the asset is changed to ETH.

Notice in practice, this hex data is not submited to the network (which is good) but the UI displays it as if there were Hex Data on the Edit screen.

https://github.com/MetaMask/metamask-extension/assets/54408225/3b0bba4f-3ee5-4609-a092-3a920fa4b10a

### Steps to reproduce

1. Enable Hex Data from Advanced Settings
2. Import an ERC20 toekn
3. Click Send ERC20 token
4. Add recipient
5. Add amount and click Next
6. Click Edit
7. Change asset for ETH
8. See how Hex data is not empty - it should be

### Error messages or log output

_No response_

### Version

10.30.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
whenever I am performing an ERC20 Send, if I change the asset to ETH, I can see how the Hex Data field is not empty, and it's displaying the data for the previous ERC20 Send. This should not be the case, and Hex Data should be cleared whenever the asset is changed to ETH.

Notice in practice, this hex data is not submited to the network (which is good) but the UI displays it as if there were Hex Data on the Edit screen.

solution: props are read-only , If you need to modify a value based on the props, you should create and manage state within the component.

## **Manual testing steps**

1 - Enable Hex Data from Advanced Settings
2 - Import an ERC20 toekn
3 - Click Send ERC20 token
4 - Add recipient
5 - Add amount and click Next
6 - Click Edit
7 - Change asset for ETH
8 - See how Hex data is not empty - it should be

### **Before**

https://user-images.githubusercontent.com/54408225/238333724-3b0bba4f-3ee5-4609-a092-3a920fa4b10a.mp4

## **Related issues**

_Fixes #19140

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js [hunk 1]
```diff
@@ -13,16 +13,36 @@ export default class SendHexDataRow extends Component {
...
+    this.setState({ hexValue: this.props.data });
+  }
+
+  componentDidUpdate(prevProps) {
+    const { data: prevPropsHexValue } = prevProps;
+    const { data: propsHexValue } = this.props;
+
+    if (prevPropsHexValue !== propsHexValue) {
+      this.setState({ hexValue: propsHexValue });
+    }
```
Comment (salimtb) [inline ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js:39]: In react , `props` are indeed intended to be read-only. That’s not possible to change the value of `props` directly within a react component . If you need to modify a value based on the `props`, you should create and manage `state` within the component.

the error we've had is due to the fact that we're trying to change the value of the `props` directly, so as long as we don't refresh we're always left with the value of the previous `props` which doesn't change.


the solution was to manage this through states within the component

File: ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js [hunk 2]
```diff
@@ -13,16 +13,36 @@ export default class SendHexDataRow extends Component {
...
+  componentDidMount() {
+    this.setState({ hexValue: this.props.data });
+  }
+
+  componentDidUpdate(prevProps) {
+    const { data: prevPropsHexValue } = prevProps;
+    const { data: propsHexValue } = this.props;
+
+    if (prevPropsHexValue !== propsHexValue) {
+      this.setState({ hexValue: propsHexValue });
```
Comment (salimtb) [inline ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js:38]: In react , `props` are indeed intended to be read-only. That’s not possible to change the value of `props` directly within a react component . If you need to modify a value based on the `props`, you should create and manage `state` within the component.

the error we've had is due to the fact that we're trying to change the value of the `props` directly, so as long as we don't refresh we're always left with the value of the previous `props` which doesn't change.

the solution was to manage this through states within the component

Comment (brad-decker) [reply ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js:41]: I'm not following. Where were we trying to change props directly in the old file? It looks like we were just passing data from props into the SendRowWrapper, whereas now we are saving the new value in state? 

Also just as an aside i'd prefer we convert this to a stateless functional component instead of adding deprecated methods to the component making it more difficult to upgrade the codebase in the future

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js (hunk 2 above)
Comment (salimtb) [reply ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js:41]: hey @brad-decker ,
i have he same idea to convert it to a functional component , but i thought it will be out of scope.
but i'll do it now.
the data are coming from the `props` ( check the data object ), then we are using it to init our state , when you click the edit button we are calling the function `updateUserInputHexData` with empty string ( file `/ui/ducks/send/send.js` line 2082 ) to change the state but this one took an immutable value ( initialised using props ) and that's why you'll always have the hex data.

so the bug was coming from the fact that the function `updateUserInputHexData` called when we trigger the edit button and switch token who was supposed to set the input as empty

Comment (brad-decker) [reply ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js:41]: The previous version of this component did not have local state, it used redux state. This is where I am getting confused because your PR is adding a local shallow copy of the redux state into the state of this component.

Comment (salimtb) [reply ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js:41]: I'll try to find out why the call to the function `updateUserInputHexData` is not setting the redux state to an empty string.
my assumption was , because this information have the same memory reference than the props.
i'm keen to convert it to functional component as well , i like the idea.
i'll ping you when i'll do all the changes , thnx for your comment @brad-decker  :)

Comment (salimtb) [reply ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js]: hey @brad-decker ,
i was able to find the origin of the error and fix it , there's no need to change any thing in the component level.
thnx for your comment this was helpful to go deeper and find a best way to fix it

**Review by brad-decker — APPROVED** [review]
awesome, looks good to me :)

**Review by DDDDDanica — APPROVED** [review]
