### PR TITLE
fix: asynchrous background password-sync check cp-13.0.0

### LINKED ISSUE #34528: [Bug]: When navigating to the Receive screen, users encounter an error message stating, "Unable to resolve enough promises..."
### Describe the bug

When navigating to the Receive screen, users encounter an error message stating, "Unable to resolve enough promises...".

### Expected behavior

Receive button should work as expected.

### Screenshots/Recordings

Image

### Steps to reproduce

1. Navigate to Receive

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lwin-kyaw**
## **Description**

In the social login flow, we do the periodic (5-minutes) password sync check in the background so that if the user wallet password is outdated in the current device, we can ask user to enter the new password again to stay updated.
Any failure in these periodic checks should not disturb the UI in the frontend.

This PR prevent background password sync check affecting the UI state.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34534?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34528

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by himanshuchawla009 — DISMISSED** [review]
lgtm

**Review by tuna1207 — DISMISSED** [review]

File: ui/store/actions.ts [hunk 1]
```diff
@@ -460,23 +460,22 @@ export function checkIsSeedlessPasswordOutdated(
...
-      return isPasswordOutdated;
     } catch (error) {
-      dispatch(displayWarning(error));
-      throw error;
-    } finally {
-      dispatch(hideLoadingIndication());
+      log.warn('checkIsSeedlessPasswordOutdated error', error);
     }
+
+    dispatch(hideLoadingIndication());
```
Comment (chaitanyapotti) [inline ui/store/actions.ts]: why this line? you're not starting the loading indication here.

Comment (lwin-kyaw) [reply ui/store/actions.ts]: ah, thanks. I missed to remove that.

Comment (lwin-kyaw) [reply ui/store/actions.ts]: removed here, https://github.com/MetaMask/metamask-extension/pull/34534/commits/40750ef37a6dfd472e559b637c4c04570cd9955c

**Review by chaitanyapotti — APPROVED** [review]

**Review by tuna1207 — APPROVED** [review]
