### PR TITLE
fix: cp-12.18.0 Fix test of alert displayed of selected currency is different from currency of confirmation

### LINKED ISSUE #32322: [Bug]: MultiChain API: eth_sendTransaction shows Network fee alert for wallet selected Solana account not connected to dapp
### Describe the bug
Using beta [build](https://github.com/MetaMask/metamask-extension/pull/32257#issuecomment-2829851780)

I am seeing an alert indicating selected account does not have enough SOL for transaction when invoking `eth_sendTransaction` in the MultiChain API test dapp when only EVM account is connected to test dapp and Solana account with alert is not connected.  I only have Ethereum network selected, Solana is not selected so there shouldn't be anything Solana related for the transaction.

### Expected behavior

- alerts from dapp transaction should reflect the currently connected account to the dapp, not the selected account in the wallet if the selected account is not connected to dapp
- alerts for EVM accounts should not be shown on Solana accounts
- alerts for Solana accounts should not be shown on EVM accounts

### Screenshots/Recordings

https://www.loom.com/share/fa89383cab4a43ccb47f8ab093f2fee0?sid=81209d10-b15e-4309-b896-7efdb0dedfed

### Steps to reproduce

```
Scenario: Insufficient Balance Network Alert for Dapp Connected Accounts
    Given user has a Solana account selected in the wallet
    And user has EVM account connected to dapp
    When user sends assets from dapp
    And user does not have enough assest balance for network fee
    Then Network fee alert is displayed
    When user opens Network fee alert
    Then Network fee alert indicates insufficient balance
    And Network fee alert shows correct asset insufficient balance (Failed: Network fee alert shows incorrect asset for selected wallet account)
    And Network fee alert is for the dapp connected account (Failed: Network fee alert is showning for selected wallet account)
```

### Error messages or log output

```shell

```

### Detection stage

In public beta

### Version

12.18.0 beta

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #32650: [Bug]: Gas info issues
### Describe the bug

1. Wrong ticker being shown in the insufficient funds modal
2. Gas station feature displays USDC image as a jazzicon instead of the token image
3. Wrong fiat conversion for USDC

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/67e813fe-6c13-4669-8580-9c841040c4df

### Steps to reproduce

1. Have the global network selector set to BNB
2. Go to Accounts details for a non-upgraded account 
3. Click on Switch to Smart Account on Ethereum
4. Notice the weird gas info

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix test of alert displayed of selected currency is different from currency of confirmation

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32322
Fixes: https://github.com/MetaMask/metamask-extension/issues/32650

## **Manual testing steps**

1. Select solana in extension
2. Go to test dapp and connect with a network where you have less balance
3. Check test of alert and ensure that it is correct

## **Screenshots/Recordings**
Screenshot 2025-05-08 at 5 27 20 PM

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by vinistevam — APPROVED** [review]

File: ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts [hunk 1]
```diff
@@ -48,7 +48,12 @@ export function useInsufficientBalanceAlerts(): Alert[] {
     selectTransactionFeeById(state, transactionId),
   );
 
-  const nativeCurrency = useSelector(getMultichainNativeCurrency);
+  const [multichainNetworks, evmNetworks] = useSelector(
+    getMultichainNetworkConfigurationsByChainId,
+  );
+  const nativeCurrency = (
+    multichainNetworks[chainId as CaipChainId] ?? evmNetworks[chainId]
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts:55]: Is this alert even used in Solana? Are these alerts not exclusive to EVM transactions? In which case should we use `selectNetworkConfigurationByChainId` instead?

**Review by matthewwalsh0 — APPROVED** [review]

File: ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts (hunk 1 above)
Comment (jpuri) [reply ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts:55]: yep good point, here we can use only evm chains, let me optimise this in following PR
