### PR TITLE
fix: Display correct native asset and its amount

### LINKED ISSUE #34762: [Bug]: SOL displayed as the token for a transaction on Polygon
### Describe the bug

In some scenarios, we're displaying SOL as the native asset instead of POL on Polygon. Also, we using the wrong decimals. See screenshot below. 

This might be happening due to relying on useUserPreferredCurrency which isn't ours and relies on the selected account to determine the native currency, rather than the transaction context.
[https://github.com/MetaMask/metamask-extension/blob/main/ui/pages/confirmations/co[…]confirm/info/shared/transaction-details/transaction-details.tsx](https://github.com/MetaMask/metamask-extension/blob/main/ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx#L120)

[Slack thread](https://consensys.slack.com/archives/C070G0RCX0T/p1753962231344089)

### Expected behavior

_No response_

### Screenshots/Recordings

Image

### Steps to reproduce

1. Go to https://app.1inch.io/swap?src=137:POL&dst=137:DEFIT
2. Connect with MM
3. Swap POL -> DEFIT
4. It'll ask you to wrap POL -> WPOL
5. Confirm
6. Click "Wrap POL to WPOL" button
7. See the MM popup

Above is how it was initially reproduced, but there might be some other steps needed like selecting a Solana account within the wallet before receiving the transaction request.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.23.0 (but probably long existing)

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by dan437**
## **Description**
Displays correct native asset and the right amount in the Amount row.

## **Changelog**

CHANGELOG entry: Displays correct native asset and the right amount in the Amount row on the Confirmation page.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34762

## **Manual testing steps**

0. In the MM wallet make sure to select Solana
1. Go to https://app.1inch.io/swap?src=137:POL&dst=137:DEFIT
2. Connect with MM
3. Swap POL -> DEFIT (Polygon transaction), it will open the extension
4. You will see the right native asset and amount in the Amount row

### **Before**
image

### **After**
image

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Use the transaction chainId to determine native currency symbol/formatting in the Amount row, plumbing chainId through CurrencyDisplay and useCurrencyDisplay with new tests.
> 
> - **Confirmations UI**:
>   - Amount row now derives currency via `useUserPreferencedCurrency(PRIMARY, {}, currentConfirmation?.chainId)` and passes `chainId` to `ConfirmInfoRowCurrency`.
> - **Components**:
>   - `ConfirmInfoRowCurrency`: accepts optional `chainId` and forwards it to `CurrencyDisplay`.
>   - `CurrencyDisplay`: adds `chainId` prop; passes it to `useCurrencyDisplay`.
> - **Hooks**:
>   - `useCurrencyDisplay`: now accepts `chainId`; uses `isEvmChainId(chainId)` to choose EVM vs non‑EVM formatting and resolves native ticker via `CHAIN_ID_TO_CURRENCY_SYMBOL_MAP`.
> - **Tests**:
>   - Add tests verifying formatting with `chainId` for Polygon and that `useUserPreferencedCurrency` is called with the transaction `chainId`.
>   - Update snapshots accordingly.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0a5792b05d5f9f8bb775a3a08e44df6057131042. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx [hunk 1]
```diff
@@ -118,7 +118,11 @@ export const MethodDataRow = () => {
 const AmountRow = () => {
   const t = useI18nContext();
   const { currentConfirmation } = useConfirmContext<TransactionMeta>();
-  const { currency } = useUserPreferencedCurrency(PRIMARY);
+  const { currency } = useUserPreferencedCurrency(
+    PRIMARY,
+    {},
+    currentConfirmation?.chainId,
+  );
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx:125]: I know this is not implemented in this PR but why we are trying to show a `userPreferredCurrency` here? 

Even if that's the case - I have "USD" selected in the settings and it never shows USD value. Shouldn't we get rid of this and pass native ticker of the transacted chain as `currency`?

File: ui/components/ui/currency-display/currency-display.component.test.js [hunk 2]
```diff
@@ -68,4 +68,19 @@ describe('CurrencyDisplay Component', () => {
...
+      currency: 'POL',
+      chainId: '0x89',
+    };
+
+    const { container } = renderWithProvider(
+      <CurrencyDisplay {...props} />,
+      mockStore,
+    );
+
+    expect(container).toMatchSnapshot();
```
Comment (OGPoyraz) [inline ui/components/ui/currency-display/currency-display.component.test.js]: Sorry Daniel - I know this is new to you but it's a team agreement that we are trying to get rid of the snapshot tests. Even a simple text check here will be enough.

**Review by jpuri — DISMISSED** [review]

File: ui/components/app/confirm/info/row/currency.test.tsx [hunk 3]
```diff
@@ -30,4 +30,9 @@ describe('ConfirmInfoRowCurrency', () => {
     const { container } = render({ currency: 'usd' });
     expect(container).toMatchSnapshot();
   });
+
+  it('should display with chainId prop', () => {
+    const { container } = render({ currency: 'POL', chainId: '0x89' });
+    expect(container).toMatchSnapshot();
```
Comment (OGPoyraz) [inline ui/components/app/confirm/info/row/currency.test.tsx]: Same here, a simple text check will be enough rather than snapshot.

File: ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx (hunk 1 above)
Comment (dan437) [reply ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx:125]: @matthewwalsh0 what do you think? Should I do this?
1. Remove the useUserPreferencedCurrency call
2. Pass the native currency ticker directly from CHAIN_ID_TO_CURRENCY_SYMBOL_MAP[chainId]

Comment (matthewwalsh0) [reply ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx:125]: We usually show fiat values rather than native values since it's more meaningful to the user, that's a UI design choice for Barbara.

But this hook is out of scope and the original cause of the issue as it assumed the selected chain ID.

Would it best to encapsulate this problem inside our `ConfirmInfoRowCurrency` and add an optional `isFiat` property?

So if `currency` isn't provided, it defaults to either the selected fiat (based on `isFiat`) or native as it tries to already?

Comment (dan437) [reply ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx:125]: So, the `useUserPreferencedCurrency` function is returning e.g. POL now (not fiat), since it's passing `PRIMARY` as the first param, which returns the native currency of the chain (ETH, POL, etc.). That's why I was suggesting my change.

Ideally changes related to this would be done in another PR since it's out of scope.

Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx:125]: I agree with you Daniel - approving as it's out of scope, I just wanted to raise it to collect feedback.

**Review by OGPoyraz — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
