### PR TITLE
fix: cp-12.18.0 fix currencyRateCheck setting for Solana

### LINKED ISSUE #32817: [Bug]: Solana - Assets - Fiat conversion is displayed despite disabling it from Settings
### Describe the bug

Whenever I disable the Fiat Conversion from the Privacy Settings, I still see the fiat amounts in Solana network.

### Expected behavior

We should do the same as we do for EVM networks: we should not convert to fiat, if the Fiat Conversion is disabled

### Screenshots/Recordings

https://github.com/user-attachments/assets/4f6c0cff-a34e-484b-813f-a67532f7dbbd

### Steps to reproduce

1. Go to Privacy Settings
2. Disable Fiat conversion rates
3. See how no fiat values are displayed in EVM networks
4. Switch to Solana
5. See how fiat values are displayed in Solana network

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix check for currencyRateCheck setting when user is on main page

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32822?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32817

## **Manual testing steps**

1. Go Settings
2. Go to Security and privacy
3. Disable Show balance and token price checker
4. Go back to home page
5. You should not see fiat values displayed
6. Click on account list item
7. You should see crypto balance displayed correctly

### **After**

https://github.com/user-attachments/assets/b653fef9-66b8-4a6c-909b-816625f5fa01

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/hooks/useTokenDisplayInfo.tsx [hunk 1]
```diff
@@ -122,7 +122,9 @@ export const useTokenDisplayInfo = ({
     title: token.title,
     tokenImage: token.image,
     primary: formattedPrimary,
-    secondary: token.secondary,
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-ignore
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/hooks/useTokenDisplayInfo.tsx:126]: Do we still need the ts-ignore comment?

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: ui/components/app/assets/hooks/useTokenDisplayInfo.tsx (hunk 1 above)
Comment (sahar-fehri) [reply ui/components/app/assets/hooks/useTokenDisplayInfo.tsx:126]: Actually, i think if i use null instead of undefined, i can then remove this ts ignore 🙏

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by darkwing** [comment]
I know it's an expert step but maybe if the toggle is off, we don't show the message and just leave it empty?  There's also a weird overlap case:  
SCR-20250512-iuvu

**Comment by sahar-fehri** [comment]
> I know it's an expert step but maybe if the toggle is off, we don't show the message and just leave it empty? There's also a weird overlap case: SCR-20250512-iuvu

Nice catch 👀 ; for EVMs we also show the same msg "No conversion rate available", do want to also show blank when the setting is off? 

Also i can't seem to repro this weird overlap when i hardcode very long token titles, 


Screenshot 2025-05-12 at 16 41 23

**Comment by alfeng6** [comment]
I'm ok with us just showing the empty state when an expert user has explicitly turned off the price toggle. Makes the screen less noisy.

**Review by darkwing — APPROVED** [review]

**Review by gambinish — APPROVED** [review]
