### PR TITLE
fix: activitylist fromtoken sourced from bridge controller

### LINKED ISSUE #32812: [Bug]: Solana bridge shows incorrect values in activity and details.
### Describe the bug

After performing a bridge from Solana to another Network, the information shown in the activity tab and in the details is not correct.

### Expected behavior

In the activity tab: It should display a negative value of the sent token

In the transaction details: It should display a sent value and the source network, and a received value and the destination network

### Screenshots/Recordings

I sent 3.5 SOL.USDC, but this is what's displayed in the activity tab:

Image

And this is the values displayed when checking the details (received is correct, but sent not):

Image

### Steps to reproduce

1. Have a Solana account
2. Go to bridge
3. Bridge SOL.USDC to Mainnet.USDC
4. Go to activity tab
5. Click on the transaction to check details

### Error messages or log output

```shell
Transaction ID: https://solscan.io/tx/65GxyGbQVRe77t11R2g1DP9iRTtsbPJfHf77eriAn2UGwxjDgCNX8ThSWVzyRCW2b6t9mbPjonaPNVSuZwwCzmmD

Destination TX ID:
https://etherscan.io/tx/0xf5b46eb2d0051878edb3dbe6bc05712290ac7fbbf4edf9bf354b445b25dce095
```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

Uses the source token from the bridge controller in order to display the correct source token for solana -> evm bridges. The reason behind this is that the multichain controller sometimes filters out the Solana source token due to rent payments causing issues with regular multichain transactions.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34521?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32812 & https://github.com/MetaMask/metamask-extension/issues/32982

## **Manual testing steps**

1. nagivate to the activity list after completing a cross-chain bridge.
2. the source and destination tokens should be correct for your transaction.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by micaelae — DISMISSED** [review]

**Review by micaelae — APPROVED** [review]

File: ui/hooks/bridge/useSolanaBridgeTransactionMapping.ts [hunk 1]
```diff
@@ -334,6 +334,20 @@ export default function useSolanaBridgeTransactionMapping(
...
       return {
         ...(tx as Transaction),
+        from: [
+          {
+            address: matchingBridgeTx.account,
+            asset: {
+              type: matchingBridgeTx.quote?.srcAsset?.assetId,
+              amount: (
+                Number(matchingBridgeTx.quote?.srcTokenAmount ?? 0) /
+                10 ** (matchingBridgeTx.quote?.srcAsset?.decimals ?? 9)
```
Comment (SteP-n-s) [inline ui/hooks/bridge/useSolanaBridgeTransactionMapping.ts:344]: Don't we have a utility that handles this type of formatting?

**Review by SteP-n-s — APPROVED** [review]
