### PR TITLE
Order accounts on connect page

### LINKED ISSUE #8710: Unordered Accounts on the Connect screen
**Describe the bug**
On the connect screen, the ordered list we show account-menu doesn't correlate with the order shown on the  connect screen on this instance.

**To Reproduce (REQUIRED)**
It is unclear if this happens consistently, or only in my instance. 

**Screenshots**
<details>
<summary>Unordered accounts on connect screen</summary>

</details>

**Browser details (please complete the following information):**
Virtualbox Ubuntu 18.04 Guest
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by rekmarks**
Fixes #8710 

- Accounts on connect page were unordered. This was fixed by updating the `getAccountsWithLabels` selector to depend on `getMetaMaskAccountsOrdered` instead of `accountsWithSendEtherInfoSelector`.
- `accountsWithSendEtherInfoSelector` and `getMetaMaskAccountsOrdered` were functionally equivalent, except that the latter returned the account objects in keyring controller order.
  - Non-functional changes were made to `accountsWithSendEtherInfoSelector` to make its implementation more closely match `getMetaMaskAccountsOrdered`.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This is meant to address #8710 I assume?

**Comment by rekmarks** [comment]
@Gudahtt ah yes, sorry.

File: ui/app/selectors/selectors.js [hunk 1]
```diff
@@ -177,17 +177,17 @@ export function getAddressBookEntryName (state, address) {
 
 export function accountsWithSendEtherInfoSelector (state) {
   const accounts = getMetaMaskAccounts(state)
-  const { identities } = state.metamask
+  const identities = getMetaMaskIdentities(state)
 
   const accountsWithSendEtherInfo = Object.entries(identities).map(([key, identity]) => {
-    return Object.assign({}, accounts[key], identity)
+    return Object.assign({}, identity, accounts[key])
```
Comment (rekmarks) [inline ui/app/selectors/selectors.js:183]: The only property that will be overwritten here is `address`. The overwrite order was updated to match `getMetaMaskAccountsOrdered`.

File: ui/app/selectors/selectors.js [hunk 2]
```diff
@@ -177,17 +177,17 @@ export function getAddressBookEntryName (state, address) {
 
 export function accountsWithSendEtherInfoSelector (state) {
   const accounts = getMetaMaskAccounts(state)
-  const { identities } = state.metamask
+  const identities = getMetaMaskIdentities(state)
```
Comment (rekmarks) [inline ui/app/selectors/selectors.js:180]: Let's use the selectors we have!

**Review by brad-decker — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!
