### PR TITLE
Flask devx fix

### LINKED ISSUE #13011: Code fence removal transforms fails in watch mode under some conditions
The code fence removal transform fails while running the build system in watch mode when reloading files that have at least one fence that **is not** removed. The transform will report that the fence structure in the file is invalid, even if it's not. The build system cannot recover from failures of this nature, and must be restarted.

See below for an example error.

My OS: macOS 11.3

<details><summary>Click for error</summary>
<pre>
<code>
scripts:core:dev:standardEntryPoints: Error: Invalid fence pair in file ".../metamask/metamask-extension/app/scripts/metamask-controller.js" due to line "        ///: BEGIN:ONLY_INCLUDE_IN(flask)":
The second directive of a pair must be an "END" directive. while parsing file: .../metamask/metamask-extension/app/scripts/metamask-controller.js
    at removeFencedCode (.../metamask/metamask-extension/development/build/transforms/remove-fenced-code.js:334:15)
    at RemoveFencedCodeTransform._flush (.../metamask/metamask-extension/development/build/transforms/remove-fenced-code.js:46:34)
    at RemoveFencedCodeTransform.prefinish (_stream_transform.js:147:10)
    at RemoveFencedCodeTransform.emit (events.js:315:20)
    at RemoveFencedCodeTransform.EventEmitter.emit (domain.js:486:12)
    at prefinish (_stream_writable.js:630:14)
    at finishMaybe (_stream_writable.js:638:5)
    at RemoveFencedCodeTransform.Writable.end (_stream_writable.js:582:5)
    at DuplexWrapper.onend (.../metamask/metamask-extension/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28) {
  filename: '.../metamask/metamask-extension/app/scripts/metamask-controller.js',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function (anonymous)],
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps], [Transform] ],
    length: 2,
    label: 'deps',
    [Symbol(kCapture)]: false
  }
}
</code>
</pre>
</details>

### PR DESCRIPTION
**Pull request by hmalik88**
Fixes: #13011 

Explanation:  This fixes a devx issue when running a build-type of 'flask' in dev mode. On reload, the build process would break if there were updates made to a file that had code fences. The reason was that the `removeFencedCode` transform stream was being called on twice, the first time it works fine and transforms properly, however the second time is done on a transpiled version of the same file and the code fencing regex does not sit well with this hence the various thrown errors. Regex was added to check for if file content had a source map inclusion and the function execution is halted at this point.

Manual testing steps:  
  -  Run `yarn start --build-type flask`
  -  Make changes in a file with code fencing and observe that the build process reloads properly.

### CODE REVIEW

File: development/build/transforms/remove-fenced-code.js [hunk 1]
```diff
@@ -200,6 +200,9 @@ const directiveParsingRegex = /^([A-Z]+):([A-Z_]+)(?:\(((?:\w+,)*\w+)\))?$/u;
  * a boolean indicating whether they were modified.
  */
 function removeFencedCode(filePath, typeOfCurrentBuild, fileContent) {
+  if (/^\/\/# sourceMappingURL=/gmu.test(fileContent)) {
+    return [fileContent, false];
+  }
   const matchedLines = [...fileContent.matchAll(linesWithFenceRegex)];
 
   // If we didn't match any lines, return the unmodified file contents.
```
Comment (rekmarks) [inline development/build/transforms/remove-fenced-code.js:208]:
```suggestion
  if (/^\/\/# sourceMappingURL=/gmu.test(fileContent)) {
    return [fileContent, false];
  }

  // If we didn't match any lines, return the unmodified file contents.
  const matchedLines = [...fileContent.matchAll(linesWithFenceRegex)];
```

File: development/build/transforms/remove-fenced-code.js [hunk 2]
```diff
@@ -200,9 +200,13 @@ const directiveParsingRegex = /^([A-Z]+):([A-Z_]+)(?:\(((?:\w+,)*\w+)\))?$/u;
  * a boolean indicating whether they were modified.
  */
 function removeFencedCode(filePath, typeOfCurrentBuild, fileContent) {
-  const matchedLines = [...fileContent.matchAll(linesWithFenceRegex)];
+  if (/^\/\/# sourceMappingURL=/gmu.test(fileContent)) {
```
Comment (rekmarks) [inline development/build/transforms/remove-fenced-code.js:203]:
```suggestion
  // Do not modify the file if we detect an inline sourcemap. For reasons
  // yet to be determined, the transform receives every file twice while in
  // watch mode, the second after Babel has transpiled the file. Babel adds
  // inline source maps to the file, something we will never do in our own
  // source files, so we use the existence of inline source maps to determine
  // whether we should ignore the file.
  if (/^\/\/# sourceMappingURL=/gmu.test(fileContent)) {
```

File: development/build/transforms/remove-fenced-code.test.js [hunk 3]
```diff
@@ -610,6 +610,17 @@ describe('build/transforms/remove-fenced-code', () => {
       });
     });
 
+    it('rejects files with sourceMap inclusion', () => {
```
Comment (rekmarks) [inline development/build/transforms/remove-fenced-code.test.js:613]:
```suggestion
    it('ignores files with inline source maps', () => {
```

**Review by rekmarks — DISMISSED** [review]
LGTM!

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by rekmarks — APPROVED** [review]
