### PR TITLE
fix: Gas station improvements

### LINKED ISSUE #37120: [Bug]: Issues with gas station
### Describe the bug

2 issues with gas station:
- Correct token icon not showing up
- Not defaulting to pay with token when user has insufficient ETH

[Slack thread](https://consensys.slack.com/archives/C070G0RCX0T/p1761218862218959?thread_ts=1761218766.059999&cid=C070G0RCX0T)

Image

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Have no ETH for gas but have enough USDC for gas
2. Trigger a transaction request
3. Gas should default to be paid with USDC and show the correct token icon

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Fixes the icons and the auto selection logic for the gas station modal.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37352?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37120

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Improve gas fee token icon rendering and refine auto-selection logic with expanded async tests; increase e2e toast close timeout.
> 
> - **UI**:
>   - `ui/pages/.../gas-fee-token-icon.tsx`: Display ERC-20 token icons from store (`selectERC20TokensByChain` `iconUrl`) when available; fallback to `PreferredAvatar`; keep native token rendering via `AvatarToken`; size mapping via `AvatarAccountSize`.
> - **Logic**:
>   - `useAutomaticGasFeeTokenSelect`: Only set `firstCheck` to `false` after successfully selecting the first eligible token; supports selection on rerender when eligibility changes (insufficient balance, gasless support, 7702/native handling).
> - **Tests**:
>   - `useAutomaticGasFeeTokenSelect.test.ts`: Convert to async with `flushPromises`, add assertions for `forceUpdateMetamaskState`, cover rerender/eligibility and 7702/native scenarios.
> - **E2E**:
>   - `transaction-confirmation.ts`: Increase toast close `clickElementSafe` timeout to `10000` for stability.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1b1e3828a13a01d57c9aed2c8f20e6ab9adff8d4. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by seaona — APPROVED** [review]
QA change LGTM 🙌

File: test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts [hunk 1]
```diff
@@ -304,7 +304,7 @@ class TransactionConfirmation extends Confirmation {
 
   async closeGasFeeToastMessage() {
     // the toast message automatically disappears after some seconds, so we need to use clickElementSafe to prevent race conditions
-    await this.driver.clickElementSafe(this.gasFeeCloseToastMessage, 5000);
```
Comment (OGPoyraz) [inline test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts:307]: Is this an intentional increase of timeout?

File: ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.tsx [hunk 2]
```diff
@@ -36,13 +40,30 @@ export function GasFeeTokenIcon({
     selectNetworkConfigurationByChainId(state, chainId),
   );
 
+  const erc20TokensByChain = useSelector(selectERC20TokensByChain);
+  const variation = chainId;
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.tsx:44]: Minor - unnecessary constant?

File: ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.tsx [hunk 3]
```diff
@@ -36,13 +40,30 @@ export function GasFeeTokenIcon({
...
     return (
       <Box data-testid="token-icon">
-        <Identicon
-          address={tokenAddress}
-          diameter={size === GasFeeTokenIconSize.Md ? 32 : 12}
-        />
+        {image ? (
+          <Identicon
+            address={tokenAddress}
+            diameter={size === GasFeeTokenIconSize.Md ? 32 : 12}
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.tsx:54]: Minor - `const isMdSize = size === GasFeeTokenIconSize.Md;`

**Review by OGPoyraz — APPROVED** [review]

File: test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts (hunk 1 above)
Comment (pedronfigueiredo) [reply test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts:307]: yes we had to increase it for this test to pass on firefox, as tests are slower for that build
