### PR TITLE
fix: fix selectedAddress and nftController instantiation

### LINKED ISSUE #22796: [Bug]: NFTs (both ERC-721 and ERC-1155) cannot be imported manually
### Describe the bug

Trying to import an NFT manually triggers flag for ownership rights although the NFT is owned by the respective address and thus cannot be imported. Not present in v11.9.0

### Expected behavior

The NFT is imported successfully. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/06c1c6d8-68f5-422c-9838-be560c2c9eb0

### Steps to reproduce

1. Load MetaMask and connect an account to https://metamask.github.io/test-dapp/
2. Deploy NFT
3. Mint NFT
4. Open transaction details and proceed to view on blockchain explorer
5. Fetch the NFT contract address and token ID 
6. Select "Import NFT" and enter the details
7. Notice the flag saying NFT can't be added as the ownership details do not match.

### Error messages or log output

```shell
No console error.
```

### Version

11.10.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

Prod build

### Severity

_No response_

### LINKED ISSUE #22798: [Bug]: Autodetect NFTs not working on Mainnet
### Describe the bug

Autodetecting NFTs is not working on Mainnet even after enabling the toggles in Settings - locking/unlocking isn't helping and refreshing the page doesn't do anything. Manually importing is not working in this context either (mentioned [here](https://github.com/MetaMask/metamask-extension/issues/22796)). 

### Expected behavior

NFT autodetection enabled displays the NFTs on Mainnet 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/d3048d80-4a98-44d4-94ed-6cd92d2fbdb2

### Steps to reproduce

1. Load MetaMask on Ethereum Mainnet and switch to an account that owns any NFTs
2. Switch to the NFT tab and see the the prop to enable autodetection in settings 
3. Enable autodetection and go back to the NFT tab
4. Notice the NFTs are not displayed

### Error messages or log output

_No response_

### Version

11.10.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

Prod build

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Noticed that when you freshly import the extension, usse testDapp to deploy and mint an NFT, then manually import the NFT.
you will be able to see the NFT. Then when you switch to another account and go back to the account that has the NFT;
1- you wont be able to see the NFTs you imported earlier
2- When you try to import them again you will get an error (fired from core when trying to verify ownership)

Noticed that this was due to core having the wrong userAddress to check ownership for, and then in metamask.js, the selectedAddress retrieved does not match the user's selected Address

This behavior is also reported to be on v11.10.0, on this issue: https://github.com/MetaMask/metamask-extension/issues/22796

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/22796
Fixes: https://github.com/MetaMask/metamask-extension/issues/22798

## **Manual testing steps**

1. Remove and reimport the extension
2. Use testDapp to deploy and mint the NFT
3. Add the NFT manually by clicking "import NFT"
4. You should be able to see your newly import NFT
5. Create new account
6. Go back to the account that has the NFT
7. You should be able to see the NFT you imported

### **Before**

https://github.com/MetaMask/metamask-extension/assets/10994169/a74cbf0b-014b-4e39-82ac-e8452941fc6e

### **After**

https://github.com/MetaMask/metamask-extension/assets/10994169/987dbb27-b938-4bce-9b43-4269d714ee33

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/ducks/metamask/metamask.js [hunk 1]
```diff
@@ -272,8 +273,10 @@ export function getNftsDropdownState(state) {
 
 export const getNfts = (state) => {
```
Comment (bergeron) [inline ui/ducks/metamask/metamask.js:274]: `getNftContracts` may need a similar fix?

File: ui/ducks/metamask/metamask.js [hunk 2]
```diff
@@ -272,8 +273,10 @@ export function getNftsDropdownState(state) {
...
   const {
-    metamask: { allNfts, selectedAddress },
```
Comment (bergeron) [inline ui/ducks/metamask/metamask.js:275]: If `state.metamask.selectedAddress` doesn't represent the current address, do we know why?

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -588,9 +588,14 @@ export default class MetamaskController extends EventEmitter {
       {
         messenger: nftControllerMessenger,
         chainId: this.networkController.state.providerConfig.chainId,
-        onPreferencesStateChange:
-          this.preferencesController.store.subscribe.bind(
-            this.preferencesController.store,
+        onPreferencesStateChange: (listener) =>
```
Comment (danjm) [inline app/scripts/metamask-controller.js:591]: Do we need to do this for `nftDetectionController` as well?

Comment (sahar-fehri) [reply app/scripts/metamask-controller.js:591]: I think we might, i was wondering if the detection was broken because of this too, i can test it 🙏

File: ui/ducks/metamask/metamask.js (hunk 1 above)
Comment (sahar-fehri) [reply ui/ducks/metamask/metamask.js:274]: that'r right, fixed 🙏

File: app/scripts/metamask-controller.js (hunk 3 above)
Comment (sahar-fehri) [reply app/scripts/metamask-controller.js:591]: I confirm that the detection is also broken because of the same problem (not getting the right address);

If i try to do same fix for DetectionController exp:

```
 onPreferencesStateChange: (listener) =>
        this.controllerMessenger.subscribe(
          `AccountsController:selectedAccountChange`,
          (newlySelectedInternalAccount) => {
            listener({
              selectedAddress: newlySelectedInternalAccount.address,
              useNftDetection:
                this.preferencesController.store.getState().useNftDetection,
            });
          },
        ), 
```

It will fix the detection but only when the user switches to another account because we are listening on this
`AccountsController:selectedAccountChange`
Which is not the behaviour we want, we want the user to enable the autoDetection in settings and once he is back to the same account he can see his detected NFTs.

Still looking into how to properly fix that and pass the correct account to the DetectionController

File: ui/ducks/metamask/metamask.js (hunk 2 above)
Comment (gantunesr) [reply ui/ducks/metamask/metamask.js:275]: Certainly a bug, while we have this transition from the `PreferencesController` to the `AccountsController`, the data should remain consistent

Comment (montelaidev) [reply ui/ducks/metamask/metamask.js:275]: Yes, its a bug they should still be in sync while the migration is happening.

File: ui/store/actions.ts [hunk 4]
```diff
@@ -1757,6 +1757,7 @@ export function setSelectedAccount(
       !currentTabIsConnectedToNextAddress;
 
     try {
+      await _setSelectedAddress(address);
```
Comment (jasonzhouu) [inline ui/store/actions.ts:1760]: `_setSelectedAddress` function will switch `preferencesController`'s selected address, even though account is not found in `accountsController`, 

it might cause inconsistent address state between `preferencesController` and `accountsController`.

Comment (sahar-fehri) [reply ui/store/actions.ts:1760]: To avoid this inconsistency, we will first check if the account is found first, then we will update the controllers.
If account was not found, no controllers will be updated.

**Review by danjm — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]
