### PR TITLE
fix: cp-13.2.0 Show error when background is unresponsive

### LINKED ISSUE #35327: [Bug]: Unresponsive service worker not caught by critical error page
### Describe the bug

The critical error page we show for initialization failures is not catching the "unresponsive service worker" bug that we keep getting reports of. When the extension enters this broken state, messages from the UI to the background never resolve but they also never throw an error, and our current error handling is only triggered when an error is thrown.

We should fix this problem by implementing a "handshake" when the UI initially connects to the background to verify that the connection is working, with a timeout error when we get no response (perhaps of 1 second? It should be very quick). The timeout error should trigger the critical error screen.

### Expected behavior

The critical error page should be shown promptly when the UI cannot communicate with the background.

### Screenshots/Recordings

_No response_

### Steps to reproduce

We cannot reliably reproduce this problem. It happens sporadically when using the manual "Update" button to update an extension installed from the Chrome Web Store.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

A handshake process with a timeout has been added to catch the scenario where the background connection is unresponsive.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35332?quickstart=1)

## **Changelog**

CHANGELOG entry: Show error when background unresponsive after update due to Chromium bug

## **Related issues**

Fixes #35327

## **Manual testing steps**

1. Test that the error is not shown during normal operation, particularly just after a reload
2. Comment out the changes to `background.js`, rebuild, then try again and ensure the error is shown after 10 seconds.

### **Before**

Before it would show the loading screen indefinitely when the background connection was unresponsive. I don't have a screenshot because we don't have a reliable reproduction for this problem.

### **After**

Screenshot 2025-08-22 at 13 06 18

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/ui.js [hunk 1]
```diff
@@ -62,6 +67,40 @@ class PhishingWarningPageTimeoutError extends Error {
...
+  try {
+    await Promise.race([handshake, timeoutPromise]);
+  } catch (error) {
+    await displayCriticalError(
+      container,
+      CriticalErrorTranslationKey.TroubleStarting,
+      error,
+    );
+  }
+}
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/scripts/ui.js]: >If the handshake times out, the ackHandler listener isn't removed from extensionPort, causing a memory leak

😅 But the process is dead at that point. One function allocation is the least of our worries.

[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/scripts/ui.js]: >calling connectionHandshake without await creates a race condition where PortStream initialization might intercept the ACK message

There is no way for "PortStream initialization" to intercept the message. All port messages get broadcast to all onMessage listeners.

**Comment by Gudahtt** [comment]
Moving into draft while I work on an E2E test. I had an idea on how to test it.

File: shared/lib/manifestFlags.ts [hunk 2]
```diff
@@ -83,6 +83,10 @@ export type ManifestFlags = {
      * Whether to disable all of the syncing features that get automatically enabled in migrations 158 and 167
      */
     disableSync?: boolean;
+    /**
+     * Whether to simulate an unresponsive background by ignoring connections from the UI
+     */
+    simulateUnresponsiveBackground: boolean;
```
Comment (Gudahtt) [inline shared/lib/manifestFlags.ts]: Whoops, this is optional
```suggestion
    simulateUnresponsiveBackground?: boolean;
```

**Comment by v-goyal** [comment]
@Gudahtt we might need some visual design changes to the restart button. I have pinged Jason.

**Comment by jakehaugen** [comment]
> @Gudahtt we might need some visual design changes to the restart button. I have pinged Jason.

The monochromatic button is good for this (assuming it flips colors in light mode).

File: app/scripts/ui.js (hunk 1 above)
Comment (davidmurdoch) [inline app/scripts/ui.js]: I think this should live in `CriticalStartupErrorHandler`; it is the only other place that listens directly to the port (and getting it to that point was hard haha).

You could modify the `install` method to send your message:

```
install() {
    this.#port.onMessage.addListener(this.#handler);
    try {
       this.#port.postMesage(SYN_MESSAGE);
    } catch(error) {
       // port doesn't work, show error to user
    }
}
```

Or maybe extend it with a `ping()` or `handshake()` method.

And in the `#handler` you could handle the `ACK` response.

In ui.js there is this comment and code:

```
    // this means we've received a message from the background, and so
    // background startup has succeed, so we don't need to listen for error
    // messages anymore
    criticalErrorHandler.uninstall();
```

Which seems to tie everything together nicely.

**Comment by davidmurdoch** [comment]
> > @Gudahtt we might need some visual design changes to the restart button. I have pinged Jason.
> 
> The monochromatic button is good for this (assuming it flips colors in light mode).

@v-goyal, @jakehaugen this is the exact same UI we talked about with @georgewrmarshall yesterday. The conclusion was `no changes needed`. This is an issue with the design tokens not adhering to the OS theme.

**Review by FrederikBolding — DISMISSED** [review]
Solid mitigation. LGTM

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -6992,6 +6992,7 @@ export default class MetamaskController extends EventEmitter {
   setupTrustedCommunication(connectionStream, sender) {
     // setup multiplexing
     const mux = setupMultiplex(connectionStream);
+    mux.ignoreStream('background-liveness');
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js]: It would be nice to use a constant for this as well, but if we're going to do that, I'd rather define all three stream names together in one place. We can do that in a follow-up PR, since that would expand the scope a bit farther than I'd like for this fix.

File: app/scripts/ui.js (hunk 1 above)
Comment (Gudahtt) [reply app/scripts/ui.js]: Good suggestion! Just refactored this logic to live in `CriticalStartupErrorHandler`, let me know what you think.

I also updated the nomenclature to call this a "liveness check" since it seemed more accurate, and used constants for the method names.

File: ui/helpers/utils/critical-startup-error-handler.ts [hunk 4]
```diff
@@ -105,22 +162,33 @@ export class CriticalStartupErrorHandler {
...
   }
 
   /**
-   * Uninstalls the error listeners from the port.
+   * Uninstall the error listeners from the port, and cancel any ongoing liveness check.
    */
   uninstall() {
     this.#port.onMessage.removeListener(this.#handler);
+    this.#onLivenessCheckCompleted = undefined;
+    clearTimeout(this.#livenessCheckTimeoutId);
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:185]: The first issue is a good catch. Fixed in the latest commit.

[the remark this answers is not in the document]
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:185]: I've just fixed the second issue as well. It _really_ doesn't seem important, but at least this should allow that Promise handler to be garbage collected I suppose 🤷

File: ui/helpers/utils/critical-startup-error-handler.ts [hunk 5]
```diff
@@ -38,6 +50,41 @@ export class CriticalStartupErrorHandler {
     this.#container = container;
   }
 
+  /**
+   * Verify that the background connection is operational.
+   */
+  async #startLivenessCheck() {
+    const { promise: livenessCheck, resolve: onLivenessCheckCompleted } =
```
Comment (davidmurdoch) [inline ui/helpers/utils/critical-startup-error-handler.ts:54]: I wonder if instead of sending then waiting, we can only do the waiting part. The background could just immediately `port.postMessage(connectedMessage); as the first thing it does as a part of `onConnect`.

The issue we've seen is that the `onConnect` event in the background doesn't fire -- we don't think we have any evidence that _sending a message_ after a _successful_ connection is set up has failed.

What do you think? It might greatly simplify the solution if we only need to send a message from the background to the UI.

File: ui/helpers/utils/critical-startup-error-handler.ts [hunk 6]
```diff
@@ -105,22 +162,38 @@ export class CriticalStartupErrorHandler {
...
    * Critical error messages are transferred over a raw browser `Port`, not with
    * `PortStream` wrapper. We want to be as close to the "metal" as possible here,
    * it minimize abstractions that could cause further issues.
    */
   install() {
     this.#port.onMessage.addListener(this.#handler);
+
+    // Called without `await` intentionally to ensure listeners for other messages are added as
+    // quickly as possible.
+    this.#startLivenessCheck();
```
Comment (davidmurdoch) [inline ui/helpers/utils/critical-startup-error-handler.ts:176]: nit: I wouldn't mind if we did `await` this (and awaiting `install`), for two _very small_ reasons.

1. We wouldn't have to call `ignoreStream("background-liveness")`, as that message will never been sent again, and the first time it gets sent nothing else would have been listening for it.
2. There is no question if other errors during initialization (things started after `install` might clobber or interfere with this liveliness error, since we never start initializing.

File: ui/helpers/utils/critical-startup-error-handler.ts [hunk 7]
```diff
@@ -56,9 +103,19 @@ export class CriticalStartupErrorHandler {
       return;
     }
     const { method } = data;
-    // Currently, we only handle RELOAD_WINDOW, and the state corruption error
-    // message, but we will be adding more in the future.
-    if (method === RELOAD_WINDOW) {
+    // Currently, we only handle BACKGROUND_LIVENESS_RESPONSE, RELOAD_WINDOW, and the state
+    // corruption error message, but we will be adding more in the future.
```
Comment (davidmurdoch) [inline ui/helpers/utils/critical-startup-error-handler.ts:100]: Love that you updated this comment. I wonder how many cases we will handle before someone just removes the "we only" comment 😆

File: ui/helpers/utils/critical-startup-error-handler.ts [hunk 8]
```diff
@@ -13,6 +17,10 @@ import {
   CriticalErrorTranslationKey,
 } from './display-critical-error';
 
+// This should be long enough that it doesn't trigger when the popup is opened soon after startup.
+// The extension can take a few seconds to start up after a reload.
+const BACKGROUND_CONNECTION_TIMEOUT = 10_000; // 10 Seconds
```
Comment (davidmurdoch) [inline ui/helpers/utils/critical-startup-error-handler.ts:19]: I like it.

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 5 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:54]: Hmm. That is true. Though if the messages from the UI weren't getting through, it would result in an infinite loader. I thought it might be safer to validate that the connection works both ways. Especially given that it doesn't significantly slow the process down.

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 6 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:176]: My worry was that if we `await` here, listeners that get synchronously attached later during initialization would not be attached in time. The `startUISync` message and the initial background state update for example. Those get sent from the background immediately.

If we wanted to `await` this without risking breaking initialization, we'd also have to pause the background connection initialization until the liveness check completed as well. Even then, we might be left with a race condition there the `startUISync` message gets dispatched before the liveness check response is fully processed, unless we make this a three-step process and delay first message from the background until the UI confirms that it's ready.

I was trying to avoid any possibility of UI initialization slowdown.

Could you elaborate on how things started after `install` might clobber or interfere with this liveness error? I wasn't sure what you had in mind there.

**Review by FrederikBolding — DISMISSED** [review]

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 5 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:54]: Oh, also, if the background sends the request without waiting, the UI might not have the handler set in time? I'm not certain how that timing works exactly. I know the listener is added synchronously after the Port is connected, so it _should_ be attached in time. But since the background is running in parallel in another process (and this liveness check is the _first thing_ it does upon a new connection), it seems theoretically possible that it would send the message first? And if it did, because this API crosses processes, I don't know how or when it would check for listeners.

Comment (davidmurdoch) [reply ui/helpers/utils/critical-startup-error-handler.ts:54]: >  I thought it might be safer to validate that the connection works both ways

Yeah, it is safer, technically. It would also be "safer" for us to verify that a lot of features we use do work the way they are supposed to; we just need to decide when we don't trust that the API will work as documented -- I don't think we've seen a message-sending issue -- only an `onConnect` issue.

> Especially given that it doesn't significantly slow the process down.

I'm not worried about the RTT with these PING/PONG messages -- I even think its fine to `await` them (as pointed out in my [other comment](https://github.com/MetaMask/metamask-extension/pull/35332#discussion_r2299029435) ). My concern is only in the added complexity if it turns out we don't actually need this two-way validation.

> If the background sends the request without waiting, the UI might not have the handler set in time

This is a good point. The UI's `runtime.connect` _is_ synchronous (it doesn't wait for the background to receive the `onConnect` event); and as long as we ensure `connectToBackground` in called in the same event loop as the call to `runtime.connect` all messages from the background will be queued until we have a break in the event loop. In other words, if we did this in UI:

```
const port = chrome.runtime.connect();
port.onMessage.addListener(console.log); // subscribe to messages; this will cause messages sent from the background to be internally queued until the event loop yields
while (true) {
    // never yield the event loop
}
```

the background process will never trigger our `onMessage.addListener` callback, though the messages _are_ still going to be internally queued.

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 6 above)
Comment (davidmurdoch) [reply ui/helpers/utils/critical-startup-error-handler.ts:176]: > listeners that get synchronously attached later during initialization would not be attached in time

Ah, true. I wonder if just reversing the PING/PONG flow would solve for this:

1. UI calls `runtime.connect`
2. UI _awaits_ for `PING` response from background
3. background receives `onConnect` event
4. background sends `PING`
5. background _awaits_ `PONG` response from UI
6. UI receives `PING`
7. UI continues initialization (_synchronously_ attaching new `onMessage` subscribers)
8. UI sends `PONG`
9. background receives `PONG`
10. background continues initialization

I think this makes it so that no other listeners will ever be attached until after PING/PONG initialization completes (we won't need any `ignoreStream()` calls anywhere, which is nice).

In UML form, if that's your things:

<a href="https://www.planttext.com?text=LP5HQiCm38RV3Rw3w5FBMFlUXr4oIXOOtM3a0C8ngMWg1qVfs0LsWfrm9vdSkAnviz3t__ebxmR1AEEviqP8EWzr1R_VFr2WExKnZDp04RaPZdZoiCJXYnqyG4_SRlh0xSeQQz19Y2gqfbSlSjGZ2ooASW4uG55cXYueFfSSz1akFbxhmC-1sJjPOzEyqY2UVRJ6w_049e76UdnIU0jnPA6pNxj9ibpDx5EAn2fSLriWrlsw3lOnQiGNtQHBpdS4VY89l5U7SfFXoR4e8HEfDzKvGPQy7SfRiang924UlOubcQU-qV-sryFNrOTUD3KQFplHNPbMicQdrz1l-WC0
">
image
</a>

> I was trying to avoid any possibility of UI initialization slowdown.

I'm usually all for that. But I don't think awaiting these calls will slow things down enough to be measurable above noise.

On the UI side the only difference is that we delay setting up the listener for `startUISync`, so it doesn't do any work until the notification is received anyway

On the BG side, we do incur an additional RTT delay (1-2 ms, probably?) before we send the `startUISync` message to the UI. I'll test RTT to be sure.

> Could you elaborate on how things started after install might clobber or interfere with this liveness error

This is mostly just some defensive programming, and probably too defensive. After thinking about it, I just realized it is actually already a potential _future_ problem with the _current_ `CriticalErrorHandler`; if we ever add global `uncaughtException`/`unhandledRejection` handlers that show a UI in response to these errors, then any uncaught/unhandled exceptions/rejections that occur _after_ a  "Critical Error" is displayed would take over the CriticalError UI, drawing its own error in its place.

And after thinking about it _even more_, this PR makes this "potential  _future_ problem" real:

1. PING/PONG takes more than 10 seconds
2. Startup Liveliness error is displayed
3. PONG is finally received later, because the background actually _is_ actually working
4. app starts up and draws over the Startup Liveliness Error UI _OR_ a Critical Start Up error is sent from the background (like a generic start up error, or a Vault Corruption error)

So 2 take aways from this:

1. Should `startLivenessCheck` call `this.uninstall()` on timeout/rejection to prevent other Critical Errors form being handled in the UI? (_might_ be good to "fix" in this PR)
2. After any "Critical Error" occurs, the rest of the UI should "quiesce"; this is easier if we can figure out a _good_ way to delay app initialization until after start up. (this PR is probably NOT a good time to fix this?)

---

In any case, I don't think this is a deal breaker for implementing the PR as is.

Comment (davidmurdoch) [reply ui/helpers/utils/critical-startup-error-handler.ts:176]: > I'll test RTT to be sure.

Update on the potential delay:

await PING/PONG runtime.connect() to startUISync received times:

(997.89+988+1000.89+964.89+1007)/5 = 991.734ms

not awaiting PING/PONG runtime.connect() to startUISync received times (this PR):

(978.1+995+1012+1010.3+1002.69)/5 = 999.618ms

Awaiting PING/PONG doesn't impart a measurable delay in startUISync initialization.

I actually think await DOES introduce a small delay, but there is so much variance in my test runs it didn't pick it up. ¯\_(ツ)_/¯

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 5 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:54]: I see, so you think it would queue up messages and attempt to deliver them without checking for listeners? i.e. that there is no out-of-process registry of port listeners. That was what I was unsure about.

It seemed possible to me that the act of adding a listener triggered an entry to be added in some registry that isn't a part of the JavaScript process, which would create a potential for tricky race conditions.

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 6 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:176]: >And after thinking about it even more, this PR makes this "potential future problem" real:
>
>1. PING/PONG takes more than 10 seconds
>2. Startup Liveliness error is displayed
>3. PONG is finally received later, because the background actually is actually working
>4. app starts up and draws over the Startup Liveliness Error UI OR a Critical Start Up error is sent from the background (like a generic start up error, or a Vault Corruption error)

True, good point. Arguably not an _awful_ result to have the error page disappear suddenly if the app is just slow, or to have one error replaced by another, but certainly not what we want.

That said, I still don't find this a _particularly_ compelling reason to delay initialization until this process has completed. I agree that we should prevent the critical error page from being overwritten, but if we rely upon the exact sequence of initialization steps to guarantee that, it would come with performance tradeoffs and would be challenging to maintain (we'd have to be wary of this with each future change to initialization). Whereas if we do something more drastic like.... use an alternative root and delete the "normal" app root upon error, it has no performance tradeoff and it's really difficult to "break" it accidentally. That approach would prevent critical errors from being overwritten in other cases too, not just this one.

All-in-all you raise a great point about the error screen being overwritten in some cases, which we don't want. But if we assume for a moment that we can fix that independently, then I don't see any obvious way in which this check being non-blocking would introduce further risks or maintenance burdens.

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 5 above)
Comment (davidmurdoch) [reply ui/helpers/utils/critical-startup-error-handler.ts:54]: I _think_ that if there _are_ listeners already installed _at the point in time that the message is sent_, but the event loop is blocked, the messages will be queued until the event loop yields, at which point they will be drained.

I can probably verify this behavior a little bit later.

Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:54]: To clarify, I was also thinking of the scenario where listeners _aren't_ installed at the point the message is sent (or at least not _known_ to be installed by some hypothetical registry). I know they're installed synchronously here, but it might still be too slow, hypothetically.

Practically speaking, probably not in this case because of how few operations there are.

But anyway, on second thought it would be rather ridiculous if it didn't act like you suggest here. Given that we "connect" to create this connection, and that we can explicitly disconnect, it seems unlikely that they would implement any "connected but dormant until a listener is attached" state. I can't imagine what that would achieve, and it would be a poor API design because of the race conditions we're discussing here. I'll assume it doesn't work this way for now.

I've just pushed a commit to remove some of the logic from the background. There is now just a single message sent to prove the connection is active.

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 6 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:176]: I'd prefer to address the "overwritten error screen" issue in a separate PR, but I will follow up on that with a suggested fix. Ideally one that we can land in the same release as this.

File: test/e2e/page-objects/pages/critical-error-page.ts [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+    }
+    console.log('Critical error page is loaded');
+  }
+
+  /**
+   * Validate that the description on the page is for the "trouble starting" scenario.
+   */
+  async validateTroubleStartingDescription(): Promise<void> {
+    await this.driver.waitForSelector({
+      text: 'This error could be intermittent, so try restarting the extension.',
```
Comment (seaona) [inline test/e2e/page-objects/pages/critical-error-page.ts]: small nit: maybe we could use a variable here, and move the selector on top with the rest

File: test/e2e/tests/critical-errors/critical-errors.spec.ts [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+
+        const criticalErrorPage = new CriticalErrorPage(driver);
+        await criticalErrorPage.checkPageIsLoaded();
+        await criticalErrorPage.validateTroubleStartingDescription();
+        await criticalErrorPage.validateErrorMessage(
+          'Background connection unresponsive',
+        );
+      },
+    );
+  });
```
Comment (seaona) [inline test/e2e/tests/critical-errors/critical-errors.spec.ts:34]: very nice test, and I love the use of the manifestFlags :heart_eyes:

**Review by seaona — DISMISSED** [review]
the e2e part looks good! Just added a small nit, but non-blocking

File: test/e2e/page-objects/pages/critical-error-page.ts (hunk 9 above)
Comment (Gudahtt) [reply test/e2e/page-objects/pages/critical-error-page.ts]: Thanks, good idea, done here: ef6cb088ad

**Review by davidmurdoch — APPROVED** [review]

File: ui/helpers/utils/critical-startup-error-handler.ts (hunk 6 above)
Comment (Gudahtt) [reply ui/helpers/utils/critical-startup-error-handler.ts:176]: I've created an issue to track this problem: https://github.com/MetaMask/metamask-extension/issues/35440

I have also prepared a draft PR with a first attempt at fixing this

**Review by seaona — APPROVED** [review]
The e2e part looks good!
