### PR TITLE
Keep memstore contents after service worker restarts

### LINKED ISSUE #15954: MV3: memstore state does not persist service worker restart

### LINKED ISSUE #16456: Send and Confirm Screens errors on SW restarts
### Describe the bug

When service worker restarts, the GasFeeController state is lost and the below behaviours are noticed on Extension

**If SW restarts on send page, you get error saying gas estimation failed.**
Screenshot 2022-11-09 at 17 28 09

**If SW Restarts on Confirm Page, Confirm button is disabled and you get a continuous flashing of gas fees**
https://user-images.githubusercontent.com/44811/201209317-1bcb96d9-f25d-440b-9e6d-8a3ae21444f2.mov

Similar issue during DAPP interraction
Screenshot 2022-11-09 at 17 42 44

And also sending tokens

### Steps to reproduce

1. Start a transaction on MetaMask. It could be any transaction (Send, Contract Interaction, etc)
2. Stop Service Worker on Send Page, You should see an error saying `Gas fee estimation failed` after service worker restart
3. Go to Confirm Page
4. Stop Service Worker, you should see the gas fees flashing and Continue button disabled.

### Error messages or log output

_No response_

### Version

develop

### Build type

_No response_

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by segun**
Fixes 

#15954 
#16456 

## Explanation

The memstore contents is usually lost when the MetaMask extension window is closed.
The problem however is that when Service Worker restarts, the memstore is also cleared. This should not be the case

This PR intends to solve this problem by copying the controllers in memtore to persistent store and adding a method to manually clear the store of the controllers when the MetaMask extension is closed.

## More Information

* See: #15828 
* 
Blocked By #15558 

## Manual Testing Steps

1. Open [test-dapp](https://metamask.github.io/test-dapp/)
2. Connect to MetaMask
3. Click on any of SIGN buttons
4. MetaMask window should open to the sign page
5. Open developer console and click on Application Tab
6. Stop service worker
7. Service worker should be restarted automatically 
8. The MetaMask sign window should still be open
9. Close the window.
10. Open the window again
11. The window should open to the home screen (not sign screen).

**NOTE**: This may be not fully testable until David's work on #15558 is fully completed. Because as of now, when service worker is restarted the user is logged out.

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -1070,21 +1104,14 @@ export default class MetamaskController extends EventEmitter {
       SnapController: this.snapController,
       NotificationController: this.notificationController,
       ///: END:ONLY_INCLUDE_IN
+      ...resetOnRestartConfig,
```
Comment (segun) [inline app/scripts/metamask-controller.js:1107]: @danjm This part of code is causing Confirm Screen to hang. if I added the controllers manually, it works. I'm not exactly sure why this is failing.

**Comment by jpuri** [comment]
Code changes look great, 2 feedbacks:

1. Can you plz check possibility of using global scope as discussed
2. Will be nice to have text coverage for metamask controller for reset flow

**Comment by segun** [comment]
> Code changes look great, 2 feedbacks:
> 
> 1. Can you plz check possibility of using global scope as discussed
> 2. Will be nice to have text coverage for metamask controller for reset flow

globalThis didn't work as it gets reset everytime I restart SW.

**Comment by jpuri** [comment]
> globalThis didn't work as it gets reset everytime I restart SW.

@segun : we can set it to true first time.

File: app/scripts/app-init.js [hunk 2]
```diff
@@ -127,6 +127,10 @@ chrome.runtime.onMessage.addListener(() => {
   return false;
 });
 
+chrome.runtime.onStartup.addListener(() => {
+  globalThis.isFirstTimeProfileLoaded = true;
+});
+
```
Comment (jpuri) [inline app/scripts/app-init.js:133]: 👍

File: app/scripts/metamask-controller.test.js [hunk 3]
```diff
@@ -193,6 +196,13 @@ describe('MetaMaskController', function () {
     await ganacheServer.quit();
   });
 
+  describe('should reset state on first time profile load', function () {
+    it('should reset state', function () {
+      assert(metamaskController.resetStates.calledOnce);
+      assert.equal(globalThis.isFirstTimeProfileLoaded, false);
+    });
+  });
+
```
Comment (jpuri) [inline app/scripts/metamask-controller.test.js:205]: Nit: will be nice to have other test also that reset does not run if `globalThis.isFirstTimeProfileLoaded` is false.

**Review by jpuri — DISMISSED** [review]

File: app/scripts/metamask-controller.js [hunk 4]
```diff
@@ -1082,11 +1093,31 @@ export default class MetamaskController extends EventEmitter {
...
+      this.swapsController.resetState,
+      this.ensController.resetState,
+      this.approvalController.clear.bind(this.approvalController),
+      // WE SHOULD ADD TokenListController.resetState here too. But it's not implemented yet.
+    ];
+
+    if (globalThis.isFirstTimeProfileLoaded === true) {
+      this.resetStates(resetMethods);
+    }
+
```
Comment (jpuri) [inline app/scripts/metamask-controller.js:1120]: @segun : should we restrict the above change to MV3 only ?

File: app/scripts/lib/local-store.js [hunk 5]
```diff
@@ -56,13 +56,19 @@ export default class ExtensionStore {
   /**
    * Returns all of the keys currently saved
    *
+   * This method originally gets all keys,
```
Comment (danjm) [inline app/scripts/lib/local-store.js:59]: Let's remove these changes because they are not used in this PR any more

File: app/scripts/metamask-controller.js [hunk 6]
```diff
@@ -1041,21 +1062,14 @@ export default class MetamaskController extends EventEmitter {
       SnapController: this.snapController,
       NotificationController: this.notificationController,
       ///: END:ONLY_INCLUDE_IN
+      ...resetOnRestartStore,
     });
```
Comment (danjm) [inline app/scripts/metamask-controller.js:1067]: Suggestion: investigate whether we can add a test that will catch mistakes of adding stores to this.memstore but not this.store

Maybe this doesn't make sense because some memstores need to persist service worker restarts and some do not

**Comment by segun** [comment]
My work on the [flashing gas fees after MV3 restart](https://github.com/MetaMask/metamask-extension/issues/16456) brought me back here. I noticed that even though `store` retains the values of all specified controllers, `memstore` only retains the values of the below attached controller.

Screenshot 2022-11-11 at 01 03 22

I couldn't figure out why. 

I tried setting the persistence: true key of ComposableObservableStore but it still didn't change, I went through the controllers one by one to see if anything in the controllers that didn't get stored differs from the ones that did, but I still couldn't find the reason why.

To fix the issue though, since the state is in `store`, I added the below code to getState()

```
    let persistAfterRestartState = {};
    for (const key of Object.keys(this.resetOnRestartStore)) {
      // get the state from store
      const state = this.store.getState()[key];
      persistAfterRestartState = { ...persistAfterRestartState, ...state };
    }

    return {
      isInitialized,
      ...this.memStore.getFlatState(),
      ...persistAfterRestartState,
    };
```

Every other part of the PR remains the same.

@danjm @Gudahtt @jpuri

**Comment by segun** [comment]
The fix for this (thanks to @Gudahtt) is to set initialState in GasFeeController.

I also took a look at all the controllers and these 3 controllers don't have initial state set

GasFeeController
TokenRatesController
RateLimitController

I have set their initial states also so that they don't lose value when SW restarts.

> My work on the [flashing gas fees after MV3 restart](https://github.com/MetaMask/metamask-extension/issues/16456) brought me back here. I noticed that even though `store` retains the values of all specified controllers, `memstore` only retains the values of the below attached controller.
> 
> Screenshot 2022-11-11 at 01 03 22
> 
> I couldn't figure out why.
> 
> I tried setting the persistence: true key of ComposableObservableStore but it still didn't change, I went through the controllers one by one to see if anything in the controllers that didn't get stored differs from the ones that did, but I still couldn't find the reason why.
> 
> To fix the issue though, since the state is in `store`, I added the below code to getState()
> 
> ```
>     let persistAfterRestartState = {};
>     for (const key of Object.keys(this.resetOnRestartStore)) {
>       // get the state from store
>       const state = this.store.getState()[key];
>       persistAfterRestartState = { ...persistAfterRestartState, ...state };
>     }
> 
>     return {
>       isInitialized,
>       ...this.memStore.getFlatState(),
>       ...persistAfterRestartState,
>     };
> ```
> 
> Every other part of the PR remains the same.
> 
> @danjm @Gudahtt @jpuri

File: app/scripts/metamask-controller.js (hunk 4 above)
Comment (segun) [reply app/scripts/metamask-controller.js:1150]: We can't move the code from app-init, because that's the only file where `chrome.runtime.onStartup.addListener(() => {` makes sense. It's the only file that's loaded when chrome starts

File: app/scripts/metamask-controller.js (hunk 6 above)
Comment (segun) [reply app/scripts/metamask-controller.js:1094]: I'm not really sure how to go about this. :(

File: app/scripts/metamask-controller.js [hunk 7]
```diff
@@ -1106,11 +1121,33 @@ export default class MetamaskController extends EventEmitter {
...
+      this.ensController.resetState,
+      this.approvalController.clear.bind(this.approvalController),
+      // WE SHOULD ADD TokenListController.resetState here too. But it's not implemented yet.
+    ];
+
+    if (isManifestV3) {
+      if (globalThis.isFirstTimeProfileLoaded === true) {
+        this.resetStates(resetMethods);
+      }
+    }
```
Comment (danjm) [inline app/scripts/metamask-controller.js:1149]: Let's make sure we reset the controllers that need to be reset under MV2 as well.

You could add
```
 else {
 this.resetState(resetMethods)
 ```
 onto the `if (isManifestV3) {` block

**Review by danjm — DISMISSED** [review]
LGTM

**Review by danjm — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
