### PR TITLE
Upgrading storybook from 6.3 to 6.5 fixing shell-quote vulnerability

### LINKED ISSUE #15683: Upgrade storybook to 6.5
### Description
Upgrade storybook rom `6.3` => `6.5` as well as [some super cool updates](https://storybook.js.org/blog/storybook-6-5/) it will also help with [shell-quote](https://github.com/advisories/GHSA-g4rg-993r-mgx7) vulnerabilities 

Related: https://github.com/MetaMask/metamask-extension/issues/15656
Related: https://github.com/MetaMask/metamask-extension/pull/15056

Shell-quote vunerabilities
https://github.com/advisories/GHSA-g4rg-993r-mgx7

Screen Shot 2022-08-23 at 2 39 15 PM

Storybook 6.5 features

Screen Shot 2022-08-23 at 2 34 56 PM

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## Explanation

Currently, there is a [shell-quote vulnerability](https://github.com/advisories/GHSA-g4rg-993r-mgx7) that is effecting many of the storybook `6.3` packages 

Not sure how big of an issues this is because it only effects our development builds. I suppose it could be used to attack our storybook PR builds and Github pages in some way? Nevertheless, it will clean up our yarn audit report(`yarn audit --level critical`) **AND** we get [storybook 6.5 which is full of goodies](https://storybook.js.org/blog/storybook-6-5/) that I am excited to try out 😁 

In order to solve this problem, this pull request upgrades storybook `6.3` => `6.5`. It also removes the "ws" package resolution that was made in https://github.com/MetaMask/metamask-extension/pull/11229 as I no longer believe it is needed.

## More Information

* Fixes #15683
* Related: #15656

## Screenshots/Screencaps
Run `yarn audit --level critical`

### Before

Screen Shot 2022-08-23 at 2 42 58 PM
Screen Shot 2022-08-23 at 2 43 17 PM
Screen Shot 2022-08-23 at 2 43 28 PM

### After
Screen Shot 2022-08-23 at 2 37 09 PM

## Manual Testing Steps
Checking yarn audit report
- Check out this branch
- Run `yarn audit --level critical`
- See reduced number of vulnerabilities compared to `develop`

Checking storybook
- Go to the latest storybook build of this PR
- Check stories are working as expected - controls work, MDX docs work, Prop tables are showing up

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] ~**IF** this PR fixes a bug, a test that _would have_ caught the bug has been added~ N/A
- [x] PR is linked to the appropriate GitHub issue
- [x] ~PR has been added to the appropriate release Milestone~ N/A

### + If there are functional changes:

- [x] ~Manual testing complete & passed~ N/A
- [x] ~"Extension QA Board" label has been applied~ N/A

### CODE REVIEW

File: .storybook/main.js [hunk 1]
```diff
@@ -16,14 +16,17 @@ module.exports = {
     './i18n-party-addon/register.js',
     'storybook-dark-mode',
   ],
+  staticDirs: ['../app', './images'],
```
Comment (georgewrmarshall) [inline .storybook/main.js:19]: Replaces static directory flags in `package.json`
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag

File: package.json [hunk 2]
```diff
@@ -64,9 +64,9 @@
     "devtools:redux": "remotedev --hostname=localhost --port=8000",
     "start:dev": "concurrently -k -n build,react,redux yarn:start yarn:devtools:react yarn:devtools:redux",
     "announce": "node development/announcer.js",
-    "storybook": "start-storybook -p 6006 -c .storybook -s ./app,./.storybook/images",
+    "storybook": "start-storybook -p 6006 -c .storybook",
     "storybook:test": "jest --config=./jest.stories.config.js",
-    "storybook:build": "build-storybook -c .storybook -o storybook-build -s ./app,./.storybook/images",
+    "storybook:build": "build-storybook -c .storybook -o storybook-build",
```
Comment (georgewrmarshall) [inline package.json:69]: Removing static directory flags in `package.json` in favour of `staticDirs` in `.storybook/main.js`
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag

File: package.json [hunk 3]
```diff
@@ -105,7 +105,6 @@
     "netmask": "^2.0.1",
     "pubnub/superagent-proxy": "^3.0.0",
     "pull-ws": "^3.3.2",
-    "ws": "^7.4.6",
```
Comment (georgewrmarshall) [inline package.json:108]: I'm not sure this is necessary anymore. Was added in https://github.com/MetaMask/metamask-extension/pull/11229. Tested by removing and running `yarn audit`

File: package.json [hunk 4]
```diff
@@ -471,7 +471,9 @@
       "@keystonehq/bc-ur-registry-eth>hdkey>secp256k1": false,
       "@metamask/rpc-methods>@metamask/key-tree>secp256k1": false,
       "eth-lattice-keyring>gridplus-sdk>secp256k1": false,
-      "eth-lattice-keyring>secp256k1": false
+      "eth-lattice-keyring>secp256k1": false,
+      "@storybook/react>@pmmmwh/react-refresh-webpack-plugin>core-js-pure": false,
+      "@testing-library/jest-dom>aria-query>@babel/runtime-corejs3>core-js-pure": false
     }
   }
 }
```
Comment (georgewrmarshall) [inline package.json:479]: Updating lavamoat with `yarn allow-scripts auto`

File: package.json [hunk 5]
```diff
@@ -327,6 +326,7 @@
     "eslint-plugin-prettier": "^4.2.1",
     "eslint-plugin-react": "^7.23.1",
     "eslint-plugin-react-hooks": "^4.2.0",
+    "eslint-plugin-storybook": "^0.6.4",
```
Comment (georgewrmarshall) [inline package.json:329]: Suggested addition by storybook

File: .eslintrc.js [hunk 6]
```diff
@@ -347,8 +362,15 @@ module.exports = {
...
+          'asc',
+          {
+            natural: true,
+          },
+        ],
       },
     },
   ],
+  extends: ['plugin:storybook/recommended'],
 };
```
Comment (georgewrmarshall) [inline .eslintrc.js:376]: Mostly lint fixes? But this is the added plugin from storybook

**Review by mcmire — COMMENTED** [review]
This is amazing! Thanks for doing this. Ran `yarn audit --level critical` and got 110 vulnerabilities, even lower than your 119, so that's neat. Just one suggestion!

File: .eslintrc.js (hunk 6 above)
Comment (georgewrmarshall) [reply .eslintrc.js]: Great suggestion have updated in https://github.com/MetaMask/metamask-extension/pull/15684/commits/6a7a0cc9987c354e0846bfbb3f298688a70e466b

**Comment by mcmire** [comment]
Tested storybook. Looks good after you update again and resolve the lavamoat failures.

File: lavamoat/build-system/policy-override.json [hunk 7]
```diff
@@ -142,6 +175,7 @@
         "typescript": true,
         "eslint-plugin-jest>@typescript-eslint/utils": true,
         "@typescript-eslint/eslint-plugin>@typescript-eslint/type-utils": true,
+        "@typescript-eslint/eslint-plugin>@typescript-eslint/utils": true,
         "@typescript-eslint/parser>@typescript-eslint/scope-manager": true,
         "@typescript-eslint/eslint-plugin>tsutils": true,
         "eslint>debug": true,
```
Comment (georgewrmarshall) [inline lavamoat/build-system/policy-override.json:181]: Overrides I had to add when running `yarn lavamoat:auto` I was going to add all the screenshots to validate this but there were A LOT. So will add some of the warning this fixes

Screen Shot 2022-08-24 at 4 26 12 PM
Screen Shot 2022-08-24 at 4 35 10 PM
Screen Shot 2022-08-24 at 4 35 18 PM
Screen Shot 2022-08-24 at 4 51 15 PM
Screen Shot 2022-08-24 at 4 57 16 PM
Screen Shot 2022-08-24 at 5 02 03 PM
Screen Shot 2022-08-24 at 5 13 20 PM

Comment (mcmire) [reply lavamoat/build-system/policy-override.json:181]: Ugh sorry to hear about this, I'm sure this took a long time to sort out 😖

**Comment by mcmire** [comment]
Looks like there is a conflict with the policy file 😓 but after that should be good to go

File: lavamoat/browserify/beta/policy.json [hunk 8]
```diff
@@ -4529,60 +4507,6 @@
...
-        "eth-lattice-keyring>gridplus-sdk>eth-eip712-util-browser>bn.js": true,
-        "eth-lattice-keyring>gridplus-sdk>eth-eip712-util-browser>buffer": true,
-        "ethers>@ethersproject/keccak256>js-sha3": true
-      }
-    },
-    "eth-lattice-keyring>gridplus-sdk>eth-eip712-util-browser>bn.js": {
-      "globals": {
-        "Buffer": true
-      },
-      "packages": {
```
Comment (georgewrmarshall) [inline lavamoat/browserify/beta/policy.json:4546]: This seems kinda strange to me why would a storybook update have anything to do with eth-lattice-keyring packages. @mcmire I think I need haaaaalp 😅

**Comment by mcmire** [comment]
@georgewrmarshall The `gridplus-sdk` package got updated very recently and this removed some sub-dependencies and changed a bunch of stuff in the LavaMoat policy files: https://github.com/MetaMask/metamask-extension/pull/15711. It seems like you might not be running `yarn lavamoat:auto` with the most up-to-date code.  Try merging `develop` and running `yarn lavamoat:auto` one more time. Sorry, I know this is painful 😞

File: lavamoat/browserify/beta/policy.json (hunk 8 above)
Comment (mcmire) [reply lavamoat/browserify/beta/policy.json:4546]: @georgewrmarshall The `gridplus-sdk` package got updated very recently and this removed some sub-dependencies and changed a bunch of stuff in the LavaMoat policy files: https://github.com/MetaMask/metamask-extension/pull/15711. It seems like you might not be running `yarn lavamoat:auto` with the most up-to-date code.  Try merging `develop` and running `yarn lavamoat:auto` one more time. Sorry, I know this is painful 😞

Comment (georgewrmarshall) [reply lavamoat/browserify/beta/policy.json:4546]: Ahh I see my issue I think it's because I had policy updates in this commit https://github.com/MetaMask/metamask-extension/pull/15684/commits/35c3e60fa1564687d101d5373fdbc97f69916704 I thought I had removed them in a rebase and then run `yarn lavamoat:auto` on just the storybook updates and the policy-overrides. Thanks for being so helpful and patient @mcmire I really appreciate it 🙏

**Comment by georgewrmarshall** [comment]
Hmm seem to be getting the same e2e test failure on `develop`

Screen Shot 2022-09-06 at 1 01 14 PM

**Comment by georgewrmarshall** [comment]
Build of storybook is currently broken but it has nothing to do with this PR. Fix is in here https://github.com/MetaMask/metamask-extension/pull/15749

**Review by mcmire — APPROVED** [review]
Merge it 😎😎😎

**Review by darkwing — APPROVED** [review]
