### PR TITLE
Ensure Metafox follows cursor on Fetching quotes screen

### LINKED ISSUE #14250: [Bug]: Metamask icon not following the mouse cursor on Fetching Quotes screen
### Describe the bug

**Problem**: Metamask icon is not following the mouse cursor movements like it used to do, on the Fetching Quotes screen, while performing a Swap

https://user-images.githubusercontent.com/54408225/160660895-713c9444-0a5b-483b-8c89-77a18592f45a.mp4

### Steps to reproduce

1. Unlock Metamask
2. Click Swap
3. Fill Swap info
4. Click Review Swap
5. Move mouse cursor on the screen

### Error messages or log output

_No response_

### Version

10.12.0

### Build type

_No response_

### Browser

Chrome, Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/14250

https://user-images.githubusercontent.com/8732757/160836715-1d702075-98e7-40da-9a43-4d9d9f1ba7fd.mov

### CODE REVIEW

File: ui/pages/swaps/loading-swaps-quotes/loading-swaps-quotes.js [hunk 1]
```diff
@@ -149,7 +149,6 @@ export default function LoadingSwapsQuotes({
               animationEventEmitter={animationEventEmitter.current}
               width="90"
               height="90"
-              followMouse={false}
               lookAtTarget={midPointTarget}
```
Comment (ryanml) [inline ui/pages/swaps/loading-swaps-quotes/loading-swaps-quotes.js:152]: I'm not sure if this is really needed anymore?

**Review by darkwing — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
