### PR TITLE
fix: network controller recovery

### LINKED ISSUE #31506: [Bug]: Metamask keeps loading and I can't put even the password
### Describe the bug

**Describe the bug**

When I open metamask it keeps loading and I can't enter my password

Versión de Metamask: 12.14.2

Expected behavior
Open window to put my password wallet

Screenshots/Recordings

Image

### Expected behavior

Open window to put my password wallet

### Screenshots/Recordings

Open metamask
It keeps loading

Service Worker

Image

offscreen.html

Image

### Steps to reproduce

Open metamask
It keeps loading

Image

### Error messages or log output

```shell
`
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills

sentry-install.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getSelf')

Uncaught (in promise) Error: NetworkController state is invalid: `selectedNetworkClientId` 'xxxxx' does not refer to an RPC endpoint within a network configuration

Refused to frame 'https://metamask.io/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://app.contentful.com".

Failed to load resource: the server responded with a status of 404 ()


Uncaught (in promise) Error: NetworkController state is invalid: `selectedNetworkClientId` 'xxxxxx' does not refer to an RPC endpoint within a network configuration

`
```

### Detection stage

In production (default)

### Version

12.14.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

https://metamask.io/ledger-iframe-bridge/8.0.3 Access returns 404

Your error log report returns 429,
https://sentry.io/api/xxx/envelope/?sentry_key=xxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.33.1

### Severity

Even you can't see your transactions, you will have to create a new wallet in another browser

Due to automatic updates, my current version is: 12.15.0, and the same problem still occurs

Update the progress. I have updated to 12.15.2 and still haven't fixed it.

### PR DESCRIPTION
**Pull request by bergarces**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31517?quickstart=1)

If `selectedNetworkClientId` is invalid, instead of crashing we should set it to the default one.

This does not fix the underlying cause of the issue, thus we still need to report to sentry.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/31506

## **Manual testing steps**

Can only be reproduced if that state is wrong. Added a test for it.

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -643,6 +643,31 @@ export default class MetamaskController extends EventEmitter {
         network.rpcEndpoints[network.defaultRpcEndpointIndex].networkClientId;
     }
 
+    // Fix the network controller state (selectedNetworkClientId) if it is invalid and report the error
+    if (
+      initialNetworkControllerState.networkConfigurationsByChainId &&
```
Comment (bergarces) [inline app/scripts/metamask-controller.js:648]: The previous block of code forces `initialNetworkControllerState` to be defined.

**Review by sahar-fehri — APPROVED** [review]

**Review by salimtb — APPROVED** [review]
lgtm

**Review by Prithpal-Sooriya — APPROVED** [review]
