### PR TITLE
fix: Prevent coercing small spending caps to zero

### LINKED ISSUE #28117: [Bug]: dapp initiated Approval is presented as Remove Permission for some tokens
### Describe the bug

When initiating an approval transaction from a dApp for certain tokens, it is unexpectedly presented not as the anticipated `Spending Cap request` but rather as a `Remove Permission` action. 
Possibly related - https://github.com/MetaMask/metamask-extension/issues/28096

### Expected behavior

- We should see the edit spending cap confirmation with the low decimal value.

### Screenshots/Recordings

https://github.com/user-attachments/assets/b0319ddf-b8aa-4180-b58d-d672c9e99deb

Screenshot 2024-10-27 at 21 57 48

### Steps to reproduce

1. Connect to a dApp
2. Start a transaction with the token that needs approval

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Previously there was a bug that affected the approve screen. When users had a small spending cap (between 0.001 and 0.0001 or smaller), it was coerced to 0.

This was caused by the method `new Intl.NumberFormat(locale).format(spendingCap)` that applied the `1,000` large number formatting, so the fix is to bypass it entirely for values smaller than 1.

Additionally, these unformatted small numbers are presented in scientific notation, so we leverage `toNonScientificString(spendingCap)` to prevent that.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28179?quickstart=1)

## **Related issues**

Fixes: [#28117](https://github.com/MetaMask/metamask-extension/issues/28117)

## **Manual testing steps**

See original bug report.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts [hunk 1]
```diff
@@ -46,8 +47,9 @@ export const useApproveTokenSimulation = (
   }, [value, decimals]);
 
   const formattedSpendingCap = useMemo(() => {
-    return isNFT
-      ? decodedSpendingCap
+    // formatting coerces small numbers to 0
+    return isNFT || decodedSpendingCap < 1
```
Comment (DDDDDanica) [inline ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts:51]: LGTM, Can we append a simple test?

**Review by DDDDDanica — DISMISSED** [review]

File: ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts (hunk 1 above)
Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts:51]: Good idea, I added one test.

**Review by DDDDDanica — APPROVED** [review]

**Comment by DDDDDanica** [comment]
LGTM !

**Review by matthewwalsh0 — APPROVED** [review]
