### PR TITLE
[FLASK] disable "Mark all as read button" when there are no notifications

### LINKED ISSUE #15327: Disable "Mark All As Read" button when no notifications
### Describe the bug

When the user has no notifications, we could disable the button since it would perform no action.

MarkRead

### Steps to reproduce

1.  Open Settings > Notifications

### Error messages or log output

_No response_

### Version

Dev

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/15327

### CODE REVIEW

**Review by digiwand — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

**Review by darkwing — DISMISSED** [review]

File: ui/pages/notifications/notifications.js [hunk 1]
```diff
@@ -99,6 +99,7 @@ export default function Notifications() {
           type="secondary"
           className="notifications__header_button"
           onClick={markAllAsRead}
+          disabled={notifications.length === 0}
```
Comment (GuillaumeRx) [inline ui/pages/notifications/notifications.js:102]: Can you use `unreadNotifications` rather than `notifications` please. Otherwise the button will not be disabled if all the notifications have been read.

**Review by GuillaumeRx — DISMISSED** [review]

File: ui/pages/notifications/notifications.js (hunk 1 above)
Comment (darkwing) [reply ui/pages/notifications/notifications.js:102]: Oh, great catch!

Comment (ryanml) [reply ui/pages/notifications/notifications.js]: @GuillaumeRx good suggestion! I've made this change.

**Review by FrederikBolding — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]
