### PR TITLE
fix: Add route protection when basic functionality toggle is off

### LINKED ISSUE #39866: [Bug]: Basic Functionality - Privacy - Clicking Deeplinks 'breaks' the Basic Functionality Off setting, as opens Swaps etc. making calls to 3rd party requests
### Describe the bug

Clicking Deeplinks 'breaks' the Basic Functionality Off setting, as opens Swaps etc. making calls to 3rd party requests.
Note that whenever I set the setting off, Swaps feature is disabled and I shouldn't be able to start a Swap as it makes 3rd party requests. However, while having Baisc Func Off, if I click a Deeplink (ie Bitcoin) this opens the Swap page and makes 3rd party requests, not respecting my privacy settings.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/00ea9486-e9f7-4a4b-bcca-9ffbc5121c17

### Steps to reproduce

1. Go to privacy settings
2. Set Basic Functionality Off
3. See Swaps feature is disabled
4. Click on Bitcoin announcement (Deeplink) or open a Swap deeplink (ie https://link.metamask.io/swap?from=eip155%3A1%2Ferc20%3A0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&to=eip155%3A1%2Ferc20%3A0xdAC17F958D2ee523a2206206994597C13D831ec7&value=0x38d7ea4c68000)
5. See Swap page is open and 3rd party requests happen

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

Found in 13.18.0 but it¡s also in prod

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gauthierpetetin**
## **Description**

When “Basic functionality” (use external services) is off, routes that depend on external services (e.g. swap, rewards, notifications, DeFi, perps) are now protected: the user is redirected to a dedicated “Basic functionality is off” page instead of the feature. That page offers an inline toggle to turn Basic functionality on and, when coming from a blocked route, a primary CTA to open the blocked feature (e.g. “Open the Swap page”) plus “Go to the home page.” This prevents users from landing on feature UIs that cannot work without external services and gives them a clear path to enable the setting or go home.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39975?quickstart=1)

## **Changelog**

CHANGELOG entry: When Basic functionality is off, protected routes now redirect to a “Basic functionality is off” page with an inline toggle and optional “Open the [feature] page” action instead of showing the feature.

## **Related issues**

Fixes: #39866

## **Manual testing steps**

1. Build and load the extension: `yarn start`.
2. Turn off Basic Functionality: Settings → Security and privacy → turn off “Basic functionality”.
3. From the home UI or address bar, open a gated route (e.g. Swap, Rewards, Notifications, DeFi, Shield plan, or a Perps route). Example:
  a. Direct route: chrome-extension://hebhblbkkdabgoldnojllkipeoacjioc/home.html#/cross-chain/swaps/prepare-bridge-page?swaps=true
  b. Deep link: https://link.metamask.io/swap?from=eip155%3A1%2Ferc20%3A0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&to=eip155%3A1%2Ferc20%3A0xdAC17F958D2ee523a2206206994597C13D831ec7&value=0x38d7ea4c68000
4. Confirm you are redirected to the “Basic functionality is off” page with description, inline toggle, and “Go to the home page.”
5. From that page, confirm the inline toggle turns Basic functionality on and that “Open the Swap page” (or equivalent) appears and navigates to the blocked route when clicked.
6. Confirm “Go to the home page” navigates to home.
7. Turn Basic functionality back on and confirm protected routes load normally.

## **Screenshots/Recordings**

Screenshot 2026-02-20 at 06 38 36

Or see [Loom video](https://www.loom.com/share/48587889a2804238b9ab55689876d04f)

### Routes that require Basic Functionality

When Basic functionality is off, these routes redirect to `/feature-unavailable`:

- `/notifications/settings`
- `/notifications/:uuid`
- `/notifications`
- `/cross-chain/tx-details/:srcTxMetaId`
- `/cross-chain/*`
- `/defi/:chainId/:protocolId`
- `/nonevm-balance-check`
- `/shield-plan`
- `/rewards`
- `/perps/home`
- `/perps/market/:symbol`
- `/perps/activity`
- `/perps/market-list`
- `/snaps`
- `/snaps/view/*`

### Routes that do not require Basic Functionality

These routes remain available when Basic functionality is off:

- `/` (Home)
- `/onboarding/*`
- `/lock`
- `/unlock`
- `/link` (deep link)
- `/feature-unavailable`
- `/restore-vault`
- `/smart-account-update`
- `/seed/:keyringId?`
- `/import-srp`
- `/settings/*`
- `/send/:page?`
- `/confirm-transaction/*` (all confirmation routes)
- `/confirm-add-suggested-token`
- `/confirm-add-suggested-nft`
- `/confirmation/:id?`
- `/new-account/*`
- `/connect/:id/*`
- `/asset/*` (all asset routes)
- `/permissions`
- `/gator-permissions`
- `/token-transfer/*`
- `/review-gator-permissions/*`
- `/review-permissions/:origin`
- `/account-list`
- `/multichain-account-address-list/:accountGroupId`
- `/multichain-account-private-key-list/:accountGroupId`
- `/add-wallet-page`
- `/multichain-account-details/:id`
- `/multichain-smart-account/:address`
- `/multichain-wallet-details-page/:id`

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches core routing/guard logic and adds a new redirect screen; misconfiguration could block access to key routes or create redirect loops, but changes are localized and well-tested.
> 
> **Overview**
> When `useExternalServices` ("Basic functionality") is off, routes that depend on external services now redirect to a dedicated `BASIC_FUNCTIONALITY_OFF_ROUTE` screen instead of rendering the feature.
> 
> Adds a `BasicFunctionalityRequired` route guard (wired into `createRouteWithLayout` by default) that passes the blocked URL + a per-feature i18n CTA key so the new page can show an inline toggle to re-enable basic functionality and optionally navigate back to the originally requested feature. Updates route config to opt *out* for allowed routes (e.g. home/settings/confirm flows) and to provide CTA keys for protected routes (swap/notifications/snaps/defi/rewards/perps/shield/etc.).
> 
> Includes new i18n strings, unit + e2e coverage for the redirect/toggle/CTA flow, plus small fixes (boolean `disableUnderline`, add `useExternalServices` to integration init state, minor settings container cleanup).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f37004ce28b1eeade57e45aa8cdac0843d2dcdc4. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/layouts/route-with-layout.tsx [hunk 1]
```diff
@@ -59,6 +64,11 @@ export const createRouteWithLayout = (
     content = <Authenticated>{content}</Authenticated>;
   }
 
+  // Then wrap with RequireBasicFunctionality when route depends on external services
+  if (requireBasicFunctionality && content) {
+    content = <RequireBasicFunctionality>{content}</RequireBasicFunctionality>;
+  }
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/layouts/route-with-layout.tsx:92]: We want `RequireBasicFunctionality` to run first so users see the feature-unavailable screen before the lock screen, which matches our deep-link flow (interstitial then lock). So the current guard order is intentional, not a bypass.

File: ui/components/ui/text-field/text-field.component.js [hunk 2]
```diff
@@ -208,7 +208,7 @@ const getBorderedThemeInputProps = ({
       max,
       autoComplete,
     },
-    disableUnderline: 'true',
+    disableUnderline: true,
```
Comment (gauthierpetetin) [inline ui/components/ui/text-field/text-field.component.js:211]: This is not directly related to the PR, but was added to silence warnings shown when running E2E tests.

File: ui/pages/settings/security-tab/security-tab.container.js [hunk 3]
```diff
@@ -64,6 +64,7 @@ const mapStateToProps = (state) => {
 
   return {
     networkConfigurations,
+    petnamesEnabled: Boolean(metamask.petnamesEnabled),
```
Comment (gauthierpetetin) [inline ui/pages/settings/security-tab/security-tab.container.js:67]: This is not directly related to the PR, but was added to silence warnings shown when running E2E tests.

File: ui/pages/settings/settings.container.js [hunk 4]
```diff
@@ -201,8 +201,9 @@ const mapStateToProps = (state, ownProps) => {
     name: snapNameGetter(snapId),
   }));
 
-  const snapSettingsTitle =
-    isSnapSettingsRoute && snapNameGetter(decodeSnapIdFromPathname(pathname));
+  const snapSettingsTitle = isSnapSettingsRoute
+    ? snapNameGetter(decodeSnapIdFromPathname(pathname))
+    : '';
```
Comment (gauthierpetetin) [inline ui/pages/settings/settings.container.js:206]: This is not directly related to the PR, but was added to silence warnings shown when running E2E tests.

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts [hunk 5]
```diff
@@ -0,0 +1,118 @@
+/**
+ * E2E tests for the "Basic functionality required" (feature-unavailable) flow.
+ * When useExternalServices is off, protected routes (e.g. swap, notifications)
+ * redirect to /feature-unavailable. Run `yarn build:test` before running these tests.
```
Comment (seaona) [inline test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: maybe this is redundant ?

` Run yarn build:test before running these tests.`?

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts [hunk 6]
```diff
@@ -0,0 +1,118 @@
+/**
```
Comment (seaona) [inline test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: maybe this spec can be placed inside the `tests/privacy` folder?

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+  it('navigates to home when clicking Go to the home page', async function () {
+    await withFixtures(
+      {
+        fixtures: new FixtureBuilder()
+          .withUseBasicFunctionalityDisabled()
+          .build(),
+        title: this.test?.fullTitle(),
+      },
+      async ({ driver }: { driver: Driver }) => {
+        await loginWithoutBalanceValidation(driver);
```
Comment (seaona) [inline test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: typically we want to validate balance to avoid flakiness with starting up with actions before the balance is loaded (can cause some undesired effects due to re-renders)

```suggestion
        await loginWithBalanceValidation(driver);
```

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+  it('navigates to Security settings when clicking Open Settings', async function () {
+    await withFixtures(
+      {
+        fixtures: new FixtureBuilder()
+          .withUseBasicFunctionalityDisabled()
+          .build(),
+        title: this.test?.fullTitle(),
+      },
+      async ({ driver }: { driver: Driver }) => {
+        await loginWithoutBalanceValidation(driver);
```
Comment (seaona) [inline test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]:
```suggestion
        await loginWithBalanceValidation(driver);
```

**Review by seaona — COMMENTED** [review]
QA changes LGTM! Nice additions! Just added a couple of small minor comments.

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts (hunk 5 above)
Comment (gauthierpetetin) [reply test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: yes, it's now removed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/a76dbca8a55965eb92ddd0e3eefc7ec67cd18d46

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts (hunk 6 above)
Comment (gauthierpetetin) [reply test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: Makes sense, it's now updated in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/a76dbca8a55965eb92ddd0e3eefc7ec67cd18d46

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts (hunk 7 above)
Comment (gauthierpetetin) [reply test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: Updated in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/a76dbca8a55965eb92ddd0e3eefc7ec67cd18d46

File: test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts (hunk 8 above)
Comment (gauthierpetetin) [reply test/e2e/tests/basic-functionality-required/basic-functionality-required.spec.ts]: Updated in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/a76dbca8a55965eb92ddd0e3eefc7ec67cd18d46

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.tsx [hunk 9]
```diff
@@ -0,0 +1,31 @@
...
+ * @param options0.children
+ */
+const RequireBasicFunctionality = ({
+  children,
+}: RequireBasicFunctionalityProps) => {
+  const useExternalServices = useSelector(getUseExternalServices);
+
+  if (!useExternalServices) {
+    return <Navigate to={BASIC_FUNCTIONALITY_REQUIRED_ROUTE} replace />;
+  }
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.tsx:45]: We’re intentionally treating `undefined` preference as disabled.
We want to be conservative: even during early state hydration or older persisted state shapes, when value is `undefined`, we don't know the user’s preference, and rather than allowing access and risking broken behavior, we prefer to redirect to the feature-unavailable page until we know Basic functionality is explicitly enabled.

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.tsx [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+  featureName,
+}: BasicFunctionalityRequiredProps) => {
+  const useExternalServices = useSelector(getUseExternalServices);
+  const location = useLocation();
+  const blockedRoutePath = location.pathname;
+
+  if (useExternalServices !== true) {
+    const state: BasicFunctionalityOffState = {
+      blockedRoutePath,
+      featureName: featureName ?? '',
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.tsx]: Fixed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/3bed0a3b34d58006b736ad907df0ff5376ea675f

File: ui/pages/basic-functionality-required/basic-functionality-required.tsx [hunk 11]
```diff
@@ -0,0 +1,153 @@
...
+              {t('basicFunctionalityRequired_openFeaturePage', [featureName])}
+            </Button>
+          )}
+          <TextButton
+            onClick={() => navigate(DEFAULT_ROUTE)}
+            data-testid="basic-functionality-off-go-home"
+          >
+            {t('basicFunctionalityRequired_goToHome')}
+          </TextButton>
+        </Box>
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/basic-functionality-required/basic-functionality-required.tsx:161]: Fixed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/162786738845c1eece5f08a1f1b87647b643021a

File: ui/pages/routes/routes.component.tsx [hunk 12]
```diff
@@ -521,6 +529,11 @@ export default function Routes() {
         component: DeepLink,
         layout: LegacyLayout,
       }),
+      createRouteWithLayout({
+        path: BASIC_FUNCTIONALITY_OFF_ROUTE,
+        component: BasicFunctionalityOff,
+        layout: LegacyLayout,
+      }),
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/routes/routes.component.tsx:569]: We're keeping BASIC_FUNCTIONALITY_OFF_ROUTE unauthenticated on purpose, to follow the pattern we have for DEEP_LINK_ROUTE.

File: test/e2e/tests/privacy/basic-functionality-required.spec.ts [hunk 13]
```diff
@@ -0,0 +1,127 @@
...
+      },
+      async ({ driver }: { driver: Driver }) => {
+        await loginWithBalanceValidation(driver);
+
+        await driver.openNewURL(
+          `${driver.extensionUrl}/home.html#${SWAP_URL_PATH}?swaps=true`,
+        );
+        await driver.waitForUrl({
+          url: `${driver.extensionUrl}/home.html#${BASIC_FUNCTIONALITY_OFF_PATH}`,
+        });
```
Comment (DDDDDanica) [inline test/e2e/tests/privacy/basic-functionality-required.spec.ts]: [Nit]: could we extract it as a util function in page-object since it is duplicated across tests. something like `await.openANewSwapsPage(driver)`

File: test/e2e/tests/privacy/basic-functionality-required.spec.ts [hunk 14]
```diff
@@ -0,0 +1,127 @@
...
+
+        const basicFunctionalityOffPage = new BasicFunctionalityOffPage(driver);
+        await basicFunctionalityOffPage.checkPageIsLoaded();
+
+        const openFeatureDisabledBeforeToggle =
+          await basicFunctionalityOffPage.isOpenFeaturePageButtonDisabled();
+        assert.ok(
+          openFeatureDisabledBeforeToggle,
+          'Open the feature page button should be disabled when Basic functionality is off',
+        );
```
Comment (DDDDDanica) [inline test/e2e/tests/privacy/basic-functionality-required.spec.ts]: Nit: Could we have this as a function on `basicFunctionalityOffPage` as well?

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx [hunk 15]
```diff
@@ -0,0 +1,156 @@
...
+jest.mock('react-router-dom', () => ({
+  useLocation: jest.fn(),
+  Navigate: jest.fn(({ to, state }) => (
+    <div
+      data-testid="navigate"
+      data-to={to}
+      data-state={JSON.stringify(state)}
+    />
+  )),
+}));
```
Comment (DDDDDanica) [inline ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx]: Could we declare the mock outside and simplify the mock process
```
const mockUseLocation = jest.fn();
jest.mock('react-router-dom', () => {
  return {
    ...jest.requireActual('react-router-dom'),
    useLocation: () => mockUseLocation,
  };
});
```

then 
```
  beforeEach(() => {
    jest.clearAllMocks();
    mockUseLocation.mockReturnValue({
      pathname: '/cross-chain/swaps/prepare-bridge-page',
      state: null,
      key: '',
      search: '',
      hash: '',
    } as ReturnType<typeof useLocation>);
  });
```

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx [hunk 16]
```diff
@@ -0,0 +1,156 @@
...
+      const { getByTestId } = render(
+        <BasicFunctionalityRequired featureName="Swap">
+          <span>Child content</span>
+        </BasicFunctionalityRequired>,
+      );
+
+      const stateJson = getByTestId('navigate').getAttribute('data-state');
+      const state = stateJson ? JSON.parse(stateJson) : undefined;
+      expect(state.blockedRoutePath).toBe(
+        '/cross-chain/swaps/prepare-bridge-page?swaps=true#section',
```
Comment (DDDDDanica) [inline ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx]: Nit: Could we use route const to replace this string, so if there's any change of route itself, we could have this in sync for free ~

File: ui/pages/routes/routes.component.tsx [hunk 17]
```diff
@@ -765,42 +790,56 @@ export default function Routes() {
...
         authenticated: true,
+        basicFunctionalityRequired: true,
+        basicFunctionalityFeatureName: 'Transaction Shield',
       }),
       createRouteWithLayout({
         path: REWARDS_ROUTE,
         component: RewardsPage,
         layout: RootLayout,
         authenticated: true,
+        basicFunctionalityRequired: true,
```
Comment (DDDDDanica) [inline ui/pages/routes/routes.component.tsx]: Nit: Do you want to make this attribute as default value `true` ? since we have it in each instance

**Comment by DDDDDanica** [comment]
- Left few comments above 💭 overall looks good !

- Tested locally with direct route and deep link, both worked as expected, also the toggle in pinned sidepanel has the state in sync as well ✅

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx [hunk 18]
```diff
@@ -0,0 +1,156 @@
...
+          <span>Child content</span>
+        </BasicFunctionalityRequired>,
+      );
+
+      expect(getByTestId('navigate')).toBeInTheDocument();
+      expect(getByTestId('navigate')).toHaveAttribute(
+        'data-to',
+        '/basic-functionality-off',
+      );
+      expect(queryByText('Child content')).not.toBeInTheDocument();
```
Comment (DDDDDanica) [inline ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx]: Suggestion: you might want to use the text from language file, or after [this PR](https://github.com/MetaMask/metamask-extension/pull/39859) is merged, this file would trigger a few fitness function check.

File: test/e2e/tests/privacy/basic-functionality-required.spec.ts (hunk 13 above)
Comment (gauthierpetetin) [reply test/e2e/tests/privacy/basic-functionality-required.spec.ts]: Definitely, it's now fixed here: https://github.com/MetaMask/metamask-extension/pull/39975/commits/88df49a390e82b1f411b320438261c2890e9dab5

File: test/e2e/tests/privacy/basic-functionality-required.spec.ts (hunk 14 above)
Comment (gauthierpetetin) [reply test/e2e/tests/privacy/basic-functionality-required.spec.ts]: Yes, fixed here: https://github.com/MetaMask/metamask-extension/pull/39975/changes/70b8e2bf7843396cb1d26ffd13f3e30ac703e731

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx (hunk 15 above)
Comment (gauthierpetetin) [reply ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx]: Makes sense, fixed here: https://github.com/MetaMask/metamask-extension/pull/39975/commits/d30dc886c10558a3ffd82121963d4594ea3eceda

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx (hunk 16 above)
Comment (gauthierpetetin) [reply ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx]: Yes, fixed here: https://github.com/MetaMask/metamask-extension/pull/39975/commits/0f133a7c0e8f2ea8e5458eb05217a4774b325849

File: ui/pages/routes/routes.component.tsx (hunk 17 above)
Comment (gauthierpetetin) [reply ui/pages/routes/routes.component.tsx]: It's now updated: https://github.com/MetaMask/metamask-extension/pull/39975/changes/936e2c51eb8601c8f7e91f66a4ff384e4dd691d4

File: ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx (hunk 18 above)
Comment (gauthierpetetin) [reply ui/helpers/higher-order-components/require-basic-functionality/require-basic-functionality.test.tsx]: It's updated here: https://github.com/MetaMask/metamask-extension/pull/39975/commits/71da73ac5b51f6eb9732c3c15f2f68c0f740b189

**Review by Mrtenz — COMMENTED** [review]
The Snaps Platform requires basic functionalities, so those routes should be protected too.

**Review by DDDDDanica — DISMISSED** [review]

**Comment by gauthierpetetin** [comment]
Thanks for flagging @Mrtenz , it's now updated in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/b43cbc4ca2a88e7184aa5a1daec6eb8e85e1812e

File: ui/pages/routes/routes.component.tsx [hunk 19]
```diff
@@ -504,309 +512,367 @@ export default function Routes() {
...
         layout: RootLayout,
         authenticated: true,
+        basicFunctionalityFeatureName: 'Snaps',
       }),
       createRouteWithLayout({
         path: `${SNAPS_VIEW_ROUTE}/*`,
         component: SnapView,
         layout: RootLayout,
         authenticated: true,
+        basicFunctionalityFeatureName: 'Snaps',
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/routes/routes.component.tsx]: PR description was outdated. It's updated now.

File: ui/pages/basic-functionality-required/basic-functionality-required.tsx [hunk 20]
```diff
@@ -0,0 +1,153 @@
...
+  const useExternalServices = useSelector(getUseExternalServices);
+
+  const state = location.state as BasicFunctionalityOffState | undefined;
+  const blockedRoutePath = state?.blockedRoutePath ?? '';
+  const featureName = state?.featureName ?? '';
+  const hasFeatureContext = Boolean(blockedRoutePath && featureName);
+
+  const handleToggleBasicFunctionality = (currentValue: boolean) => {
+    dispatch(toggleExternalServices(!currentValue));
+  };
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/basic-functionality-required/basic-functionality-required.tsx:55]: That's ok here, because the initial state for the toggle is "disabled" anyways.
This means no need to show the warning because if user toggles on then off, he just end up with settings in the same state as they were already.

File: test/e2e/page-objects/pages/basic-functionality-off-page.ts [hunk 21]
```diff
@@ -0,0 +1,113 @@
...
+        e,
+      );
+      throw e;
+    }
+    console.log('Basic Functionality Off page is loaded');
+  }
+
+  async getDescriptionText(): Promise<string> {
+    try {
+      const el = await this.driver.findElement(this.descriptionBox);
```
Comment (hjetpoluru) [inline test/e2e/page-objects/pages/basic-functionality-off-page.ts]: This is an anti-pattern—we should avoid finding the element and then retrieving the text. Instead, you can use `waitForSelector `and pass the locator along with the expected text.

File: test/e2e/page-objects/pages/basic-functionality-off-page.ts [hunk 22]
```diff
@@ -0,0 +1,113 @@
...
+        'Error clicking Open the feature page button on Basic Functionality Off page',
+        e,
+      );
+      throw e;
+    }
+  }
+
+  async isOpenFeaturePageButtonDisabled(): Promise<boolean> {
+    const el = await this.driver.findElement(this.openFeatureButton);
+    const disabled = await el.getAttribute('disabled');
```
Comment (hjetpoluru) [inline test/e2e/page-objects/pages/basic-functionality-off-page.ts]: Could you inspect the element and check whether `disabled `is part of the locator itself to avoid this anti-pattern? If that’s not possible, then it should be fine.

**Review by hjetpoluru — COMMENTED** [review]
@gauthierpetetin, added some nit for the testing. If the PR is priority you could address them later too. Let me know if you have any questions.

**Review by davidmurdoch — COMMENTED** [review]
Since toggling `Basic Functionality` back to on is a pretty big change in the privacy behavior of MM we may want give the user an easy way of learning more about what this will change. I don't think we want to put the whole Basic Functionality blurb here, so i wonder what we could do (if we should do anything at all).

File: test/e2e/page-objects/pages/basic-functionality-off-page.ts (hunk 21 above)
Comment (gauthierpetetin) [reply test/e2e/page-objects/pages/basic-functionality-off-page.ts]: Thanks for the suggestion, it's fixed here: https://github.com/MetaMask/metamask-extension/pull/39975/commits/486152cfb55e9fd9a4f87661aa38d7f453fd48ae

File: test/e2e/page-objects/pages/basic-functionality-off-page.ts (hunk 22 above)
Comment (gauthierpetetin) [reply test/e2e/page-objects/pages/basic-functionality-off-page.ts]: Fixed here: https://github.com/MetaMask/metamask-extension/pull/39975/commits/c959ef049fbd1939dd0f3b0b9ca17e6f047c669e

**Review by hjetpoluru — DISMISSED** [review]
e2e related changes lgtm.

File: app/_locales/en/messages.json [hunk 23]
```diff
@@ -875,6 +875,25 @@
...
     "message": "Turn on basic functionality"
   },
+  "basicFunctionalityRequired_description": {
+    "message": "This feature isn't available while basic functionality is turned off. Use the toggle below to turn it on."
+  },
+  "basicFunctionalityRequired_goToHome": {
+    "message": "Go to the home page"
+  },
+  "basicFunctionalityRequired_openFeaturePage": {
+    "message": "Open the $1 page",
```
Comment (davidmurdoch) [inline app/_locales/en/messages.json]: @copilot will i18n replacer pattern work across all languages? `$1` will be terms like "Settings", "Swaps"", "Notifications", etc.

File: ui/pages/basic-functionality-required/basic-functionality-required.test.tsx [hunk 24]
```diff
@@ -0,0 +1,222 @@
...
+    return ReactActual.createElement('input', {
+      type: 'checkbox',
+      checked: value,
+      'data-testid': passThroughInputProps?.['data-testid'],
+      onChange: () => onToggle(!value),
+      readOnly: true,
+    });
+  }
+  return mockToggle;
+});
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/basic-functionality-required/basic-functionality-required.test.tsx:36]: Fixed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/commits/32e4e6ed3e6db37e2848eaab98186f206d900c03

File: app/_locales/en/messages.json (hunk 23 above)
Comment (gauthierpetetin) [reply app/_locales/en/messages.json]: Good catch, the feature name was not localized. It's now fixed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/3bb65af78971fd77f79e3c15cdf881ab54cead9c

Comment (davidmurdoch) [reply app/_locales/en/messages.json]: ah, I didn't even notice that. Was I was referring to is more about word form and its usage in sentences like these.

The English version of our translation string is `Open the $1 page`, where `$1` would be a noun like `swaps`, `buy`, `settings`, `notifications`, `perps`, etc.

ChatGPT is telling me this won't work in languages like Russian, because a the replacer string would be `Откройте страницу $1`, but a word like `Settings` would be translated to `Настройки` on its own (and it _is_ in stored this way in our i18n files today), but that would be grammatically incorrect when used in `Откройте страницу $1`, where it should be `настроек`.

For the deep links interstitial UI, which is very similar, I require a larger part of the sentence to be translated for every deeplinked pages (the string in `en/message.json` is `the swaps page` -- instead of using `the $1 page` and another separate string for `swaps`).

Alexey says the mistranslation here in Russian is pretty normal, and he's used to it -- but it is technically incorrect, but not a huge problem. I don't know how true that is for other languages.

File: ui/layouts/route-with-layout.tsx [hunk 25]
```diff
@@ -15,6 +16,10 @@ export type RouteWithLayoutConfig = {
     | ComponentType<{ children: ReactNode }>;
   authenticated?: boolean;
   initialized?: boolean;
+  /** When true (default), redirects to the basic-functionality-off screen if Basic Functionality (useExternalServices) is off. Set to false to allow access without external services (e.g. Home, Settings). */
+  basicFunctionalityRequired?: boolean;
+  /** i18n message key for the feature name (e.g. "swap", "notifications"). Same keys as nav/tabs so "Open the [feature] page" CTA is localized. Required when basicFunctionalityRequired is true. */
+  basicFunctionalityLocalizedFeatureName?: string;
   children?: ReactNode;
 };
```
Comment (MajorLift) [inline ui/layouts/route-with-layout.tsx]: nit: We could enforce this constraint at type-level: "Required when `basicFunctionalityRequired` is true."

```suggestion
  children?: ReactNode;
} & (
  | {
      /** When true, redirects to the basic-functionality-off screen if Basic Functionality (useExternalServices) is off. */
      basicFunctionalityRequired: true;
      /** i18n message key for the feature name (e.g. "swap", "notifications"). Same keys as nav/tabs so "Open the [feature] page" CTA is localized. Required when `basicFunctionalityRequired` is true. */
      basicFunctionalityLocalizedFeatureName: string;
    }
  | {
      /** Set to false to allow access without external services (e.g. Home, Settings). */
      basicFunctionalityRequired: false;
      basicFunctionalityLocalizedFeatureName?: never;
    }
);
```

File: app/_locales/en/messages.json (hunk 23 above)
Comment (gauthierpetetin) [reply app/_locales/en/messages.json]: Ah, right, I misunderstood, here's a new fix in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/d5a114d992941f91d1b0a4f42be3a56bc571076f

File: ui/layouts/route-with-layout.tsx (hunk 25 above)
Comment (gauthierpetetin) [reply ui/layouts/route-with-layout.tsx]: Great suggestion, thanks, it's added in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/changes/0c1140e184156d2cc572335f9c25e168656fd296

**Review by DDDDDanica — DISMISSED** [review]

**Review by MajorLift — DISMISSED** [review]
LGTM!

**Review by sleepytanya — DISMISSED** [review]

File: ui/pages/basic-functionality-required/basic-functionality-required.tsx [hunk 26]
```diff
@@ -0,0 +1,165 @@
...
+  const useExternalServices = useSelector(getUseExternalServices);
+
+  const state = location.state as BasicFunctionalityOffState | undefined;
+  const blockedRoutePath = state?.blockedRoutePath ?? '';
+  const openPageCtaMessageKey = state?.openPageCtaMessageKey ?? '';
+  const hasFeatureContext = Boolean(blockedRoutePath && openPageCtaMessageKey);
+
+  const handleToggleBasicFunctionality = (currentValue: boolean) => {
+    dispatch(toggleExternalServices(!currentValue));
+  };
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/basic-functionality-required/basic-functionality-required.tsx:55]: That expected because basic funcion functionality is already off when landing of this new page, so if user toggles it on then off, they just end up in the same situation they already were.

File: ui/pages/routes/routes.component.tsx [hunk 27]
```diff
@@ -532,285 +540,352 @@ export default function Routes() {
...
+        basicFunctionalityOpenPageCtaKey:
+          'basicFunctionalityRequired_openPerpsPage',
       }),
       createRouteWithLayout({
         path: `${PERPS_MARKET_DETAIL_ROUTE}/:symbol`,
         component: WrappedPerpsMarketDetailPage,
         layout: RootLayout,
         authenticated: true,
+        basicFunctionalityOpenPageCtaKey:
+          'basicFunctionalityRequired_openPerpsPage',
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/routes/routes.component.tsx:888]: Fixed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/commits/29f7dc00ab980c550f9e93da948d9e5d6264d940

File: ui/pages/basic-functionality-required/basic-functionality-required.test.tsx [hunk 28]
```diff
@@ -0,0 +1,218 @@
...
+  });
+
+  it('renders inline Basic functionality toggle', () => {
+    renderWithStore(<BasicFunctionalityOff />);
+
+    expect(
+      screen.getByTestId('basic-functionality-off-toggle-row'),
+    ).toBeInTheDocument();
+    expect(
+      screen.getByText(messages.basicConfigurationLabel.message),
```
[the remark this answers is not in the document]
Comment (gauthierpetetin) [reply ui/pages/basic-functionality-required/basic-functionality-required.test.tsx]: Fixed in this commit: https://github.com/MetaMask/metamask-extension/pull/39975/commits/ed91c40c4741776631770c520206f2519135b894

**Review by HowardBraham — APPROVED** [review]

**Review by sleepytanya — APPROVED** [review]
