### PR TITLE
cp-12.18.0 feat: use @metamask/bridge-status-controller's submitTx handler

### LINKED ISSUE #32303: [Bug]: not able to in-app swap SOL, always getting route isn't available error for any token pair
### Describe the bug

Using beta [build](https://github.com/MetaMask/metamask-extension/pull/32257#issuecomment-2829851780)

Not able to swap on Solana network using in-app swaps.  Always getting an error route isn't available error for any token pair

### Expected behavior

I should be able to swap on Solana network using the app.

### Screenshots/Recordings

https://github.com/user-attachments/assets/bc9a87a4-4173-44ee-a710-112c8185093f

### Steps to reproduce

Scenario: In-app Swap on Solana Network
GIVEN I am Solana network
AND I have a Solana account with sufficient SOL balance
WHEN I swap within the app
THEN swap is successful (Failed: not able to swap, always getting route not available)

### Error messages or log output

```shell

```

### Detection stage

In public beta

### Version

12.18.0 beta

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**
- deprecates the extension's BridgeStatusController  implementation dand replaces it with @metamask/bridge-status-controller
- includes a migration script to make the existing BridgeStatusController state compatible with the new controller's state
- Replaces tx submission logic hooks with a call to `BridgeStatusController.submitTx`
- fixes missing Activity log fields

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31907?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32303 (follow-up needed) , https://consensyssoftware.atlassian.net/browse/MMS-2267

## **Manual testing steps**

1. Request Solana Bridge quotes
2. Submit the tx and verify Activity log details
3. Request Solana Swap quotes
2. Submit the tx and verify Activity log details
3. Request EVM Bridge quotes
2. Submit the tx and verify Activity log details
3. Transactions submitted before the 3 txs above should still be visible (migration)

### **Before**

N/A - there should be no functional changes

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts [hunk 1]
```diff
@@ -181,11 +183,25 @@ export default function useSubmitBridgeTransaction() {
 
     let bridgeTxMeta: TransactionMeta | undefined;
     try {
+      if (isSolanaChainId(quoteResponse.quote.srcChainId)) {
```
Comment (micaelae) [inline ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts:186]: @bfullam most changes in this PR are for migrating the extension to the core bridge-status-controller

to submit solana txs:
- update controller initialization
- add the submitTx call
- create a useSnapConfirmation hook that redirects to the confirmation page when a new approval is queued (happens in the background)
- status polling is auto started by the submitTx call

**Comment by micaelae** [comment]
@metamaskbot update-policies

**Review by ghgoodreau — DISMISSED** [review]

**Comment by micaelae** [comment]
@metamaskbot update-policies

**Comment by micaelae** [comment]
@metamaskbot update-policies

**Comment by micaelae** [comment]
@metamaskbot update-policies

**Review by ghgoodreau — DISMISSED** [review]

**Comment by micaelae** [comment]
@metamaskbot update-policies

**Review by ghgoodreau — DISMISSED** [review]

**Review by ghgoodreau — APPROVED** [review]

**Review by boneskull — APPROVED** [review]

**Review by GustavoRSSilva — APPROVED** [review]
