### PR TITLE
fix: fixed SRP syncs cp-13.5.0

### LINKED ISSUE #36561: [Bug]: Account sync is not working when open Account list
### Describe the bug

When user open Account list, there is no `get` request
When user open Manage Account in Setting, there is `get` request, so the accounts are synced when opening this Manage Account in Setting

### Expected behavior

Should sync account when opening the Account list

### Screenshots/Recordings

https://github.com/user-attachments/assets/141ac67c-d1f0-42f8-a58c-11df1f50d618

### Steps to reproduce

See the recording

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.5.0

### Build type

Beta

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lwin-kyaw**
## **Description**

Fixed multi-srp syncs on account-list menu.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36582?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed multi-srp syncs on account list menu

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36561

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Triggers SRP sync on opening the account list for social login and refines the `useSyncSRPs` hook guard/deps.
> 
> - **Frontend**
>   - **Account List (`ui/pages/multichain-accounts/account-list/account-list.tsx`)**:
>     - Invoke `useSyncSRPs()` to trigger SRP sync during social login when the account list opens.
>   - **Hook (`ui/hooks/social-sync/useSyncSRPs.ts`)**:
>     - Rename local selector var to `isSocialLoginFlow` and update effect deps.
>     - Move social-login guard into the effect's async block.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit ccb48bb4815ac7e201b0fd23d6ff74a568a507a3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by LeVinhGithub — DISMISSED** [review]
lgtm

File: ui/pages/multichain-accounts/account-list/account-list.tsx [hunk 1]
```diff
@@ -43,11 +43,14 @@ import {
...
 } from '../../../components/multichain/pages/page';
 import { useAssetsUpdateAllAccountBalances } from '../../../hooks/useAssetsUpdateAllAccountBalances';
+import { useSyncSRPs } from '../../../hooks/social-sync/useSyncSRPs';
 import { filterWalletsByGroupName } from './utils';
 
 export const AccountList = () => {
   const t = useI18nContext();
   const history = useHistory();
+  // sync SRPs for social login flow
+  useSyncSRPs();
```
Comment (ccharly) [inline ui/pages/multichain-accounts/account-list/account-list.tsx]: Would you mind moving this hook further down below, like before the `useAssetsUpdateAllAccountBalances` maybe, and also add a comment like:

```suggestion
  // Sync SRPs for social login flow
  // TODO: Move this logic on the background side, so we don't trigger this sync
  // every time the account list is being opened.
  // See: https://github.com/MetaMask/metamask-extension/issues/36639
  useSyncSRPs();
```

**Review by ccharly — APPROVED** [review]
LGTM (not tested)

As discussed internally, this kind of logic should probably live in the background side to avoid "over-loading" the UI with side-effects logics like this (which could slow down rendering potentially too).

There's a ticket to track this improvement + a `TODO` comment to keep track of this in the code too:
- https://github.com/MetaMask/metamask-extension/issues/36639

**Review by chaitanyapotti — APPROVED** [review]
