### PR TITLE
fix: remove extra header from confirmation pages in expanded view

### LINKED ISSUE #24044: [Bug]: Transactions and Signatures Extended view displays duplicated headers
### Describe the bug

Whenever we trigger a transaction or signature, if we open the extended MM view, we can see how 2 headers are displayed on the signature screen.

This has changed from the old design (though in the old design it does not seem ideal neither --see below)

### Expected behavior

Need design/product input @SayaGT @bschorchit 

### Screenshots/Recordings

Re-design:
Screenshot from 2024-04-16 09-21-49

Old design:
Screenshot from 2024-04-16 09-21-19

### Steps to reproduce

1. Trigger a Signature
2. Open MM width view
3. Click on the pending Signature
4. See screen

### Error messages or log output

_No response_

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Remove extra header from confirmation pages in expanded view

## **Related issues**

Fixes: MetaMask/metamask-extension#24044

## **Manual testing steps**

1. Submit a confirmation
2. Check it in expanded view
3. Note that only 1 header should be present

## **Screenshots/Recordings**

Screenshot 2024-04-29 at 5 51 38 PM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

File: ui/pages/routes/routes.component.js [hunk 1]
```diff
@@ -698,6 +699,13 @@ export default class Routes extends Component {
 
     let isLoadingShown = isLoading && completedOnboarding;
 
+    const isConfirmation = Boolean(
```
Comment (matthewwalsh0) [inline ui/pages/routes/routes.component.js:702]: Will this only ever be for transaction confirmations or all of them?

Should we be explicit and call this `isTransactionConfirmation`?

File: ui/pages/routes/routes.component.js [hunk 2]
```diff
@@ -730,7 +738,10 @@ export default class Routes extends Component {
         <QRHardwarePopover />
         <Modal />
         <Alert visible={this.props.alertOpen} msg={alertMessage} />
-        {!this.hideAppHeader() && <AppHeader location={location} />}
+        {!isConfirmation && !this.hideAppHeader() && (
```
Comment (matthewwalsh0) [inline ui/pages/routes/routes.component.js:741]: Since we already have the `hideAppHeader` to encapsulate these checks, should we include `isConfirmation` in there and maybe put it in it's own method so we can still add the logo below?

File: ui/components/multichain/app-header/app-header.js [hunk 3]
```diff
@@ -68,6 +65,7 @@ import { useCopyToClipboard } from '../../../hooks/useCopyToClipboard';
 import { MINUTE } from '../../../../shared/constants/time';
 import { shortenAddress } from '../../../helpers/utils/util';
 import { toChecksumHexAddress } from '../../../../shared/modules/hexstring-utils';
+import { MetaFoxLogo } from './meta-fox-logo';
```
Comment (matthewwalsh0) [inline ui/components/multichain/app-header/app-header.js:68]: We now import `MetaFoxLogo` and `MetafoxLogo`, should we rename one to be more explicit so it's clear what the difference is?

Comment (digiwand) [reply ui/components/multichain/app-header/app-header.js:68]: ++ 

thoughts on MetaFoxLogo → MultichainMetaFoxLogo?

File: ui/components/multichain/app-header/meta-fox-logo.js [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+  AlignItems,
+  Display,
+  JustifyContent,
+} from '../../../helpers/constants/design-system';
+import { Box } from '../../component-library';
+import {
+  ///: BEGIN:ONLY_INCLUDE_IF(build-mmi)
+  getTheme,
+  ///: END:ONLY_INCLUDE_IF
+} from '../../../selectors';
```
Comment (digiwand) [inline ui/components/multichain/app-header/meta-fox-logo.js:18]:
```suggestion
///: BEGIN:ONLY_INCLUDE_IF(build-mmi)
import { getTheme } from '../../../selectors';
///: END:ONLY_INCLUDE_IF
```

suggestion avoids blank import

File: ui/components/multichain/app-header/app-header.js (hunk 3 above)
Comment (jpuri) [reply ui/components/multichain/app-header/app-header.js]: make sense, I updated it to `MultichainMetaFoxLogo`

File: ui/pages/routes/routes.component.js (hunk 2 above)
Comment (jpuri) [reply ui/pages/routes/routes.component.js]: I implemented the change

File: ui/pages/routes/routes.component.js (hunk 1 above)
Comment (jpuri) [reply ui/pages/routes/routes.component.js]: I changed it to `isConfirmTransactionRoute`

**Review by matthewwalsh0 — APPROVED** [review]

File: ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts [hunk 5]
```diff
@@ -11,11 +11,11 @@ function useConfirmationRecipientInfo() {
   const currentConfirmation = useSelector(
     currentConfirmationSelector,
   ) as Confirmation;
+  const allAccounts = useSelector(accountsWithSendEtherInfoSelector);
```
Comment (digiwand) [inline ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts:14]: Sweet. looks like this fixes the `Rendered more hooks than during the previous render` bug 👍🏼 

ref: https://github.com/orgs/MetaMask/projects/78/views/1?pane=issue&itemId=61449112

**Review by digiwand — APPROVED** [review]
