### PR TITLE
Use specified gas limit when speeding up a transaction

### LINKED ISSUE #7977: Advanced tab does not allow me to change GasLimit on retry
**Describe the bug**
On a failed transaction, click "retry", the Gas Limit field allows me to edit but when I click SAVE, it reverts to its estimate.

**To Reproduce (REQUIRED)**
If the transaction is OOG, then click on retry, should allow me to increase gas.

**Expected behavior**
Save whatever value I enter

**Screenshots**
Screenshot 2020-02-03 at 13 28 00

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit)
 - MetaMask Version: 7.7.3

### LINKED ISSUE #8156: Editing GasLimit in Speed Up does not work
Version 7.7.2

I had a stream of transactions that were failing because of out of gas and I was unable to replace them with a higher gas limit.

### PR DESCRIPTION
**Pull request by Gudahtt**
The sidebar used to speed up a transaction while it's pending or after it has failed currently allows editing the gas limit, but that new limit is ignored. This is especially problematic for transactions that failed due to a low gas limit, as the problem becomes impossible to fix by retrying.

The gas limit specified by the user is now used in the speed up transaction.

Fixes #8156 and fixes #7977

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #8177, so it's marked as draft and pointed at that branch until it has been merged.

**Review by rickycodes — DISMISSED** [review]
code looks sound to me

**Review by rickycodes — APPROVED** [review]

File: app/scripts/controllers/transactions/index.js [hunk 1]
```diff
@@ -357,6 +367,10 @@ class TransactionController extends EventEmitter {
       type: TRANSACTION_TYPE_RETRY,
     })
 
+    if (customGasLimit) {
+      newTxMeta.txParams.gas = customGasLimit
```
Comment (whymarrh) [inline app/scripts/controllers/transactions/index.js]: Can we pass this in to `generateTxMeta` above?

Comment (Gudahtt) [reply app/scripts/controllers/transactions/index.js]: We could, but I thought this would be better. If I was to pass it into `generateTxMeta`, I'd have to create a fallback to handle the case where `customGasLimit` isn't passed in. This seemed more straightforward to me 🤷‍♂

**Review by tmashuang — APPROVED** [review]
LGTM

**Review by whymarrh — APPROVED** [review]
