### PR TITLE
Handle extension unloaded and reloaded error: "Extension context invalidated" during dapp use for chromium browsers

### LINKED ISSUE #15975: [MV2|MV3] Throw error when extension is refreshed or reinstalled during a dapp session (related to chromium browsers only)
### Describe the bug

Currently in MV2, when restarting the extension through chrome://extensions/, the dapp will stop working silently, with an error or warning in the browser console.

When the extension updates or a new version is installed during a dapp session, it will throw an error. `chrome.runtime.id` will no longer be found from `contentscript.js`. We could throw a new error. This error can be used to prompt a refresh. 

### Steps to reproduce

1. Launch extension
2. Open dapp
3. Open chrome://extensions/
4. Reinstall or update the MM extension
5. Observe that the dapp is not working

### Error messages or log output

`Extension context invalidated.`

### Version

10.19.x

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

If the extension is loaded or reloaded during a user session, the dapp will break, and when attempting to use the dapp, the error, `'Extension context invalidated.', will show in the console for chromium browsers. This PR provides a slightly more helpful error message by prompting the user to refresh the page.

This error occurs for both MV2 and MV3 builds.

Note: We are not yet handling this error on Firefox. This will be handled along with this issue - https://github.com/MetaMask/metamask-extension/issues/16909

## More Information

Fixes: #15975

### Before
Screenshot 2022-11-01 at 2 22 49 AM

### After

Screenshot 2022-10-29 at 1 22 21 AM

## Manual Testing Steps

- Start the extension using MV3 build (yarn start:mv3)
- View a dapp page
- Notice the dapp is working
- Go to chrome://extensions/
- Turn off the extension, or toggle the extension on and off
- Attempt to use the dapp and observe the error in the console

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

File: app/scripts/contentscript.js [hunk 1]
```diff
@@ -103,6 +104,23 @@ const IGNORE_INIT_METHODS_FOR_KEEP_ALIVE = [
...
+ */
+const sendMessageWorkerKeepAlive = () => {
+  browser.runtime
+    .sendMessage({ name: WORKER_KEEP_ALIVE_MESSAGE })
+    .then(null, (error) => {
+      error.message === 'Extension context invalidated.'
+        ? log.error(`Please refresh the page. MetaMask: ${error}`)
+        : log.error(`MetaMask: ${error}`);
+    });
+};
```
Comment (digiwand) [inline app/scripts/contentscript.js:122]: in case it helps, see how to handle `browser.runtime.sendMessage` errors here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage#examples

File: app/scripts/contentscript.js [hunk 2]
```diff
@@ -103,6 +104,23 @@ const IGNORE_INIT_METHODS_FOR_KEEP_ALIVE = [
...
+ *
+ * If the extension is unloaded or reloaded during a session and the user attempts to send a
+ * message to the extension, an "Extension context invalidated." error will occur.
+ * When this happens, prompt the user to reload the extension.
+ */
+const sendMessageWorkerKeepAlive = () => {
+  browser.runtime
+    .sendMessage({ name: WORKER_KEEP_ALIVE_MESSAGE })
+    .then(null, (error) => {
+      error.message === 'Extension context invalidated.'
```
Comment (legobeat) [inline app/scripts/contentscript.js:118]: Is this message stable across browsers and languages?

Comment (digiwand) [reply app/scripts/contentscript.js:118]: @legobeat great question! thanks for asking 

It appears so. 

It seems that chromium has the error message fixed to 'Extension context invalidated.' and does not send this error in other languages: https://github.com/chromium/chromium/blob/main/extensions/renderer/gin_port.cc#L31

Before checking the chromium repo, I did verify that the error remains the same here and on Opera Beta with Spanish as the default language
Screenshot 2022-10-31 at 8 54 51 PM

I went with checking the direct string because there is no error code provided with this error.

File: app/scripts/contentscript.js [hunk 3]
```diff
@@ -103,6 +104,23 @@ const IGNORE_INIT_METHODS_FOR_KEEP_ALIVE = [
...
+ * Sending a message to the extension to receive will keep the service worker alive.
+ *
+ * If the extension is unloaded or reloaded during a session and the user attempts to send a
+ * message to the extension, an "Extension context invalidated." error will occur.
+ * When this happens, prompt the user to reload the extension.
+ */
+const sendMessageWorkerKeepAlive = () => {
+  browser.runtime
+    .sendMessage({ name: WORKER_KEEP_ALIVE_MESSAGE })
+    .then(null, (error) => {
```
Comment (kumavis) [inline app/scripts/contentscript.js:117]: maybe easier to read as a `.catch`

File: app/scripts/contentscript.js (hunk 2 above)
Comment (kumavis) [reply app/scripts/contentscript.js:118]: is there an equivalent error on firefox?

File: app/scripts/contentscript.js (hunk 3 above)
Comment (digiwand) [reply app/scripts/contentscript.js:117]: I was following the semantics the [sendMessage doc uses](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage#examples). I think using `.catch` is easier to read as well. I plan to update this some time after I complete some MV3 work

File: app/scripts/contentscript.js (hunk 2 above)
Comment (digiwand) [reply app/scripts/contentscript.js]: I'm receiving a different warning/error when running these repro steps in firefox. Needs investigation 

Screen Shot 2022-11-22 at 17 30 10

Comment (digiwand) [reply app/scripts/contentscript.js]: Thanks for the callouts!

**Review by brad-decker — APPROVED** [review]

File: app/scripts/contentscript.js (hunk 2 above)
Comment (legobeat) [reply app/scripts/contentscript.js]: OK - is there a ticket for tracking FF support (perhaps alongside other FF MV3 items)? Just so it's followed up on appropriately.

**Review by legobeat — APPROVED** [review]

File: app/scripts/contentscript.js (hunk 2 above)
Comment (digiwand) [reply app/scripts/contentscript.js]: @legobeat Ok, I created a ticket here: https://github.com/MetaMask/metamask-extension/issues/16909. Thank you 🙏
