### PR TITLE
Use combineReducers in ducks

### LINKED ISSUE #7746: Use combineReducers in ducks
**Describe the bug**
on line 31 of `ducks/index.js`, `state.metamask` is overwritten, so the state that the `reduceApp` function receives on line 37 has a metamask property with the new/updated `selectedAddressTxList` property value

**Expected behavior**
we should leverage `combineReducers` so the redux state is never mutated.

### PR DESCRIPTION
**Pull request by whymarrh**
Resolves #7746 

This PR replaces the `rootReducer` with a call to [`combineReducers`](https://redux.js.org/api/combinereducers/).

The only real _change_ here is how we get the transaction ID/index to the `ConfTx` component, which is used to display signature requests. I have tested that signature confirmations continue to work with Dan's _[JS Ethereum Signature Example](https://danfinlay.github.io/js-eth-personal-sign-examples/)_ dapp. Removing the `currentView` property from `appState` is otherwise harmless as it was used solely in that one component (and but one of the three set properties).

**Bonus changes:**

- [x] Re-enabled linting on the actions spec file
- [x] Deleted extra unused test files
- [x] Moved the only-used-for-testing `GLOBAL_FORCE_UPDATE` action into `mock-dev.js`

### CODE REVIEW

File: app/scripts/ui.js [hunk 1]
```diff
@@ -43,7 +43,9 @@ async function start () {
   // provide app state to append to error logs
   function getState () {
     // get app state
-    const state = window.getCleanAppState()
+    const state = window.getCleanAppState
```
Comment (rickycodes) [inline app/scripts/ui.js]: I see what you're doing here, but I am left wondering why this is even on `window`?

If we're going to check the prop here maybe we should use `window.hasOwnProperty('getCleanAppState')`?

File: test/unit/ui/app/actions.spec.js [hunk 2]
```diff
@@ -534,7 +528,7 @@ describe('Actions', () => {
         { type: 'DISPLAY_WARNING', value: 'error' },
       ]
 
-      connectHardwareSpy.callsFake((deviceName, page, hdPath, callback) => {
+      connectHardwareSpy.callsFake((_, __, ___, callback) => {
```
Comment (rickycodes) [inline test/unit/ui/app/actions.spec.js]: Nit: I like using `_` to denote "this is not used, please ignore", but to have 3 variations seems... strange?

**Review by rickycodes — DISMISSED** [review]
I've noted a couple small nits, but otherwise seems fine

File: test/unit/ui/app/actions.spec.js (hunk 2 above)
Comment (whymarrh) [reply test/unit/ui/app/actions.spec.js]: Well we need to get to the 4th argument. I'd rather not have so many args straight up ignored but instead of rewriting this test to use them, I'm just ignoring them. (Also, as a side note, the only allowed name for a unused argument is `/[_]+/` in our ESLint config.)

File: app/scripts/ui.js (hunk 1 above)
Comment (whymarrh) [reply app/scripts/ui.js]: What cases would this handle?

Comment (rickycodes) [reply app/scripts/ui.js]: https://stackoverflow.com/questions/34128945/javascript-hasownproperty-vs-dot-syntax

for this it's probably fine? I was just thinking from a convention point of view

Comment (whymarrh) [reply app/scripts/ui.js]: I think for this it's fine, I don't quite see what benefit this change would bring

File: ui/app/ducks/metamask/metamask.js [hunk 3]
```diff
@@ -97,9 +90,9 @@ function reduceMetamask (state, action) {
         },
       }
 
-    case actions.COMPLETED_TX:
-      const stringId = String(action.id)
```
Comment (Gudahtt) [inline ui/app/ducks/metamask/metamask.js]: Huh - this was _completely broken_ beforehand. it literally never worked, as `action.id` was always undefined.

Comment (Gudahtt) [reply ui/app/ducks/metamask/metamask.js]: I see - this action had no effect upon the `metamask` store, but it still worked in the `app` store.

I'd suggest deleting this block instead of repairing it, as this could have unintended consequences. Deleting it seems fine - it's dead code.

Comment (whymarrh) [reply ui/app/ducks/metamask/metamask.js]: I like deleting code

File: ui/app/ducks/app/app.js [hunk 4]
```diff
@@ -266,44 +217,28 @@ export default function reduceApp (state, action) {
...
-        log.debug('reducer detected txs - rendering confTx view')
+      if (action.value.unconfirmedActionsCount > 0) {
         return {
           ...appState,
           transForward: false,
-          currentView: {
-            name: 'confTx',
-            context: 0,
-          },
+          txId: 0, // should this be null?
```
Comment (Gudahtt) [inline ui/app/ducks/app/app.js]: Yeah, probably.

File: ui/app/ducks/index.js [hunk 5]
```diff
@@ -1,90 +1,17 @@
...
+import { combineReducers } from 'redux'
+import metamaskReducer from './metamask/metamask'
+import localeMessagesReducer from './locale/locale'
+import sendReducer from './send/send.duck'
+import appStateReducer from './app/app'
+import confirmTransactionReducer from './confirm-transaction/confirm-transaction.duck'
+import gasReducer from './gas/gas.duck'
+
+export default combineReducers({
+  activeTab: (s) => (s === undefined ? null : s),
```
Comment (Gudahtt) [inline ui/app/ducks/index.js]: Hmm. This doesn't seem like it belongs in Redux in the first place. Ah well.

Comment (Gudahtt) [reply ui/app/ducks/index.js]: Why not do something like this instead? Or does it dislike being given `undefined`
```suggestion
  activeTab: (s) => s),
```

File: ui/app/pages/confirm-transaction/conf-tx.js [hunk 6]
```diff
@@ -13,20 +13,30 @@ import Loading from '../../components/ui/loading-screen'
...
 
   return {
     identities: state.metamask.identities,
     unapprovedTxs: state.metamask.unapprovedTxs,
     unapprovedMsgs: state.metamask.unapprovedMsgs,
     unapprovedPersonalMsgs: state.metamask.unapprovedPersonalMsgs,
     unapprovedTypedMessages: state.metamask.unapprovedTypedMessages,
-    index: state.appState.currentView.context,
+    index: txId
+      ? txHelper(unapprovedTxs, unapprovedMsgs, unapprovedPersonalMsgs, unapprovedTypedMessages, network).findIndex((tx) => tx.id === txId)
```
Comment (Gudahtt) [inline ui/app/pages/confirm-transaction/conf-tx.js]: This change seems unnecessary. Why not just use `txId`? That appears to be what it did before, functionally.

File: ui/index.js [hunk 7]
```diff
@@ -104,3 +101,34 @@ async function startApp (metamaskState, backgroundConnection, opts) {
...
+      return cb(err)
+    }
+    state.platform = platform
+    const stateString = JSON.stringify(state, null, 2)
+    cb(null, stateString)
+  })
+}
+
+window.logState = function () {
+  return window.logStateString((err, result) => {
```
Comment (Gudahtt) [inline ui/index.js]: This seems like a bad function in general - it's doing an `async` thing, but it neither accepts a callback nor returns a promise. Worse, it also returns a value.

What was wrong with the way it was before, with the boolean parameter for copying to the clipboard?

**Review by Gudahtt — CHANGES_REQUESTED** [review]

File: ui/app/ducks/index.js (hunk 5 above)
Comment (whymarrh) [reply ui/app/ducks/index.js]: It does dislike being given `undefined`.

Comment (whymarrh) [reply ui/app/ducks/index.js]: And specifically says that `null` should be used instead to "skip" an update.

File: docs/state_dump.md [hunk 8]
```diff
@@ -9,7 +9,7 @@ To take a state dump, follow these steps:
 1. Get the MetaMask popup to the point where it shows the bug (the developer will probably specify exactly where).
 2. Right click on the extension popup UI, and in the menu, click "Inspect". This will open the developer tools.
 3. In case it isn't already selected, click the "Console" tab in the new Developer Tools window.
-4. In the console, type this command exactly: `logState()`. This should print a bunch of JSON text into your console.
-5. Copy that printed JSON text
+4. In the console, type this command exactly: `copy(await logState())`
```
[the remark this answers is not in the document]
Comment (whymarrh) [reply docs/state_dump.md]: I'd temporarily switched it to using a promise, whoops

File: ui/app/pages/confirm-transaction/conf-tx.js (hunk 6 above)
Comment (whymarrh) [reply ui/app/pages/confirm-transaction/conf-tx.js]: I'll try this

File: ui/index.js (hunk 7 above)
Comment (whymarrh) [reply ui/index.js]: Sure, I'll leave it as it was

Comment (whymarrh) [reply ui/index.js]: > Worse, it also returns a value.

Yeah and the callback from `logStateString` doesn't return _its_ callback value, so... yeah. My bad.

**Review by Gudahtt — APPROVED** [review]
LGTM!
