### PR TITLE
fix: Remove old properties from state

### LINKED ISSUE #28289: [Sentry] Error: No metadata found for 'providerConfig'
Sentry Issue: [METAMASK-XCF5](https://metamask.sentry.io/issues/6011869130/?referrer=github_integration)

```
Error: No metadata found for 'providerConfig'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at addEthereumChain.implementation (app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js:168:32)
  at <anonymous> (app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js:56:11)
...
(6 additional frame(s) were not displayed)
```

### LINKED ISSUE #28290: [Sentry] Error: No metadata found for 'submitHistory'
Sentry Issue: [METAMASK-XCJD](https://metamask.sentry.io/issues/6034505530/?referrer=github_integration)

```
Error: No metadata found for 'submitHistory'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at r.addDappTransaction (app/scripts/lib/transaction/util.ts:114:3)
...
(9 additional frame(s) were not displayed)
```

### LINKED ISSUE #28300: [Sentry] Error: No metadata found for 'disabledRpcMethodPreferences'
Sentry Issue: [METAMASK-XCM1](https://metamask.sentry.io/issues/6041854680/?referrer=github_integration)

```
Error: No metadata found for 'disabledRpcMethodPreferences'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at PreferencesController.setPreference (app/scripts/controllers/preferences-controller.ts:881:10)
  at ReflectApply (app/scripts/lib/createMetaRPCHandler.js:23:31)
...
(20 additional frame(s) were not displayed)
```

### LINKED ISSUE #28302: [Sentry] Error: No metadata found for 'infuraBlocked'
Sentry Issue: [METAMASK-XCM1](https://metamask.sentry.io/issues/6041854680/?referrer=github_integration)

```
Error: No metadata found for 'infuraBlocked'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at PreferencesController.setPreference (app/scripts/controllers/preferences-controller.ts:881:10)
  at ReflectApply (app/scripts/lib/createMetaRPCHandler.js:23:31)
...
(20 additional frame(s) were not displayed)
```

### LINKED ISSUE #28344: [Sentry] Error: No metadata found for 'hasDismissedOpenSeaToBlockaidBanner'
Sentry Issue: [METAMASK-XCM4](https://metamask.sentry.io/issues/6041857935/?referrer=github_integration)

```
Error: No metadata found for 'hasDismissedOpenSeaToBlockaidBanner'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at PreferencesController.setPasswordForgotten (app/scripts/controllers/preferences-controller.ts:490:10)
  at MetamaskController.unMarkPasswordForgotten (app/scripts/metamask-controller.js:4918:32)
  at MetamaskController._onUnlock (app/scripts/metamask-controller.js:6016:10)
...
(15 additional frame(s) were not displayed)
```

### LINKED ISSUE #28608: Error: No metadata found for 'customNetworkListEnabled'
Sentry Issue: [METAMASK-XCNX](https://metamask.sentry.io/issues/6042560215/?referrer=github_integration)

```
Error: No metadata found for 'customNetworkListEnabled'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at _handleAccountsControllerSync2 (app/scripts/controllers/preferences-controller.ts:1032:10)
  at _getSnapProposedName2 (app/scripts/lib/SnapsNameProvider.ts:123:13)
  at async Promise.all (index 0)
...
(23 additional frame(s) were not displayed)
```

### LINKED ISSUE #29746: [Sentry] Error: No metadata found for 'serviceWorkerLastActiveTime'
Sentry Issue: [METAMASK-XEWQ](https://metamask.sentry.io/issues/6223008366/?referrer=github_integration)

```
Error: No metadata found for 'serviceWorkerLastActiveTime'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at _updatePollingTokens (app/scripts/controllers/app-state-controller.ts:749:10)
  at AppStateController.addPollingToken (app/scripts/controllers/app-state-controller.ts:734:34)
  at ReflectApply (app/scripts/lib/createMetaRPCHandler.js:23:31)
...
(21 additional frame(s) were not displayed)
```

### LINKED ISSUE #29780: [Sentry] Error: No metadata found for 'showPortfolioTooltip'
Sentry Issue: [METAMASK-XEX4](https://metamask.sentry.io/issues/6223268230/?referrer=github_integration)

```
Error: No metadata found for 'showPortfolioTooltip'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:70:30)
  at AppStateController.removePollingToken (app/scripts/controllers/app-state-controller.ts:770:14)
  at forEach (app/scripts/metamask-controller.js:6733:31)
  at Array.forEach (<anonymous>)
...
(19 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mcmire**
## **Description**

There are several kinds of errors in Sentry which indicate that there are properties in controller state we are attempting to persist that do not have corresponding metadata. This indicates that these properties were removed at some point from the controller's state but no migration was added that removed them from the persisted wallet state. In many cases, at the time of removal, such a migration was not needed because the controller in question inherited from BaseController v1. We have made a targeted effort over the past few years to migrate all controllers to BaseController v2, however, and so it matters now that every property have corresponding metadata or else are removed from state. We don't want these errors to show up in Sentry because they create noise, so this commit removes these properties from state.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29792?quickstart=1)

## **Related issues**

Fixes #28289.
Fixes #28290.
Fixes #28300.
Fixes #28302.
Fixes #28344.
Fixes #28608.
Fixes #29746.

## **Manual testing steps**

These changes should not affect users in any way since the errors we are trying to avoid occur out of band and should not crash anything. 

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/migrations/139.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+  if (
+    hasProperty(state, 'NetworkController') &&
+    isObject(state.NetworkController)
+  ) {
+    // Removed in 555d42b9ead0f4919356ff16e11c663c5e38639e
+    delete state.NetworkController.networkConfigurations;
+    // Removed in 800a9d3a177446ff2d05e3e95ec06b3658474207 with a migration, but
+    // still persists for some people for some reason
+    delete state.NetworkController.providerConfig;
```
Comment (mcmire) [inline app/scripts/migrations/139.ts:49]: I found this error in Sentry: https://metamask.sentry.io/issues/6011869130/events/039861ddb07f4b39b947edba3bbd710e/. I am not sure why it is occurring. We already have a migration that removes this property. So do we need this here? Kind of strange that some people still have this property.

File: app/scripts/migrations/139.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    // I could find references to this in the commit history, but don't know
+    // where it was removed
+    delete state.PreferencesController.hasMigratedFromOpenSeaToBlockaid;
+    // Removed in f988dc1c5ef98ec72212d1f58e736556273b68f7
+    delete state.PreferencesController.improvedTokenAllowanceEnabled;
+    // Removed in 315c043785cd5d7a4b0f7e974097ccac18a6b241
+    delete state.PreferencesController.infuraBlocked;
+    // Removed in 4f66dc948fee54b8491227414342ab0d373475f1 with a migration, but
+    // still persists for some people for some reason
+    delete state.PreferencesController.useCollectibleDetection;
```
Comment (mcmire) [inline app/scripts/migrations/139.ts:73]: I found this error in Sentry here: https://metamask.sentry.io/issues/6042074159/events/5711f95785d741739e5d0fa5ad19e7c0/. Again we already have a migration that should be removing this property, so I'm not sure if this is needed?

**Review by danjm — DISMISSED** [review]

**Review by cryptodev-2s — DISMISSED** [review]

File: app/scripts/migrations/139.ts (hunk 1 above)
Comment (danjm) [reply app/scripts/migrations/139.ts:58]: It must be due to some migration failure that we have not yet understood. I think it is good to attempt to delete again here, but we should investigate further if it continues to persist after this

**Comment by mcmire** [comment]
@cryptodev-2s @danjm Oops, had to fix merge conflicts. Can I get another review?

**Review by cryptodev-2s — APPROVED** [review]

**Review by danjm — APPROVED** [review]
