### PR TITLE
Save Brave Fixes #4270

### LINKED ISSUE #4270: Brave handles i18n API differently and sometimes cannot open until fixed
Some time after version 4.3, MetaMask's view size seems to have changed, and broken with the Brave browser:
https://github.com/brave/browser-laptop/issues/14122

To reproduce, we will need to build a local version of Brave with the extension installed. The last time I went through that process I produced this guide to doing it:
https://medium.com/metamask/building-metamask-into-brave-838d616dd93f

The Brave team cannot update MetaMask on their platform until we resolve this.

### PR DESCRIPTION
**Pull request by jennypollack**
In Brave Browser extension.i18n.getAcceptLanguages throws:
"Unchecked runtime.lastError while running i18n.getAcceptLanguages: Access to extension API denied."

Once Brave Browser implementation lands for locale support, no further change will be needed in MM to support language preferences.

Meanwhile this check should allow MetaMask to load on Brave.

### CODE REVIEW

File: app/scripts/lib/get-first-preferred-lang-code.js [hunk 1]
```diff
@@ -18,7 +17,14 @@ const existingLocaleCodes = allLocales.map(locale => locale.code.toLowerCase().r
  *
  */
 async function getFirstPreferredLangCode () {
-  const userPreferredLocaleCodes = await getPreferredLocales()
+  let userPreferredLocaleCodes = await getPreferredLocales()
+  
+  // safeguard for Brave Browser until they implement chrome.i18n.getAcceptLanguages
+  // https://github.com/MetaMask/metamask-extension/issues/4270
+  if(!userPreferredLocaleCodes){
```
Comment (jennypollack) [inline app/scripts/lib/get-first-preferred-lang-code.js]: Can I catch it? Not really; it's not raised by your code, but the cleanup code that handles async tasks in Chrome API; therefore using try ... catch in your callback won't help. Since it's asynchronous, using try around the original API call won't help either.

shoutouts to: https://stackoverflow.com/questions/28431505/unchecked-runtime-lasterror-when-using-chrome-api

File: app/scripts/lib/get-first-preferred-lang-code.js [hunk 2]
```diff
@@ -2,8 +2,7 @@ const extension = require('extensionizer')
 const promisify = require('pify')
 const allLocales = require('../../_locales/index.json')
 
-const isSupported = extension.i18n && extension.i18n.getAcceptLanguages
-const getPreferredLocales = isSupported ? promisify(
+const getPreferredLocales = extension.i18n ? promisify(
```
Comment (danfinlay) [inline app/scripts/lib/get-first-preferred-lang-code.js]: My understanding is that Brave _does_ expose a `extension.i18n` object, and even a `getAcceptLanguages` method on it, so they would pass this test.

From what they reported and I relayed [in this comment](https://github.com/MetaMask/metamask-extension/issues/4270#issuecomment-395154557) is that the only way to check their failure right now is to check `chrome.runtime.lastError` within the callback, and if there's an error, _then_ fall back.

**Review by danfinlay — COMMENTED** [review]
I think this leaves out part of the fix that Brave recommended, could you verify? Had this fixed the problem after you'd reproduced it?

**Comment by jennypollack** [comment]
Without evaluating the runtime.lastError, Brave returns undefined so the proposed change does fix the issue.

**Review by danfinlay — DISMISSED** [review]
Sounds like this works, and it shouldn't break any normally compatible browsers, so this is safe to merge.

**Comment by danfinlay** [comment]
@jennypollack Would you mind adding a user-facing entry to the `CHANGELOG.md` file?

**Review by kumavis — DISMISSED** [review]

**Review by kumavis — DISMISSED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -3,6 +3,7 @@
 ## Current Master
 
 - Fix bug where account reset did not work with custom RPC providers.
+- Fix for Brave i18n getAcceptLanguages [#4270](https://github.com/MetaMask/metamask-extension/issues/4270)
```
Comment (kumavis) [inline CHANGELOG.md]: @jennypollack we add changelog entries under "current master" and then move that to a version number of release

**Review by kumavis — DISMISSED** [review]

**Comment by danfinlay** [comment]
From Brave Sampson:

`chrome.i18n` will return _truthy_ in Brave. But calling the `getAcceptLanguage` method will _throw_. We do support `chrome.i18n.getUILanguage` at the moment (with `getAcceptLanguage` support coming very soon). A test today would need to fingerprint Brave, or wrap a call to `getAcceptLanguage` in a _try...catch_.

**Review by danfinlay — DISMISSED** [review]
Left a comment from Brave, I'd like us to adjust to their specifications.

**Review by kumavis — DISMISSED** [review]

File: app/scripts/lib/get-first-preferred-lang-code.js (hunk 2 above)
Comment (danfinlay) [reply app/scripts/lib/get-first-preferred-lang-code.js]: Per feedback from Brave, we are now handling errors from this function, because Brave currently throws for this.

**Review by kumavis — APPROVED** [review]
