### PR TITLE
fix: hide testnet amounts if user opt out in the settings

### LINKED ISSUE #25169: Hide amount in simulations for testnets if it's opted out by user
**Background**

The extension displays simulation fiat values in testnets regardless of the user preference in advance settings.

**Goal**

Currently it displays NaN US$ and the goal is to remove fiat values completely if user opt out.

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to hide testnet fiat values if user opt out in the settings.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25167?quickstart=1)

## **Related issues**

- Fixes: https://github.com/MetaMask/metamask-extension/issues/25169

## **Manual testing steps**

1. Change current network to any testnet
2. Go to setting, turn on "Show conversion on test networks"
3. Try simple send - see fiat values displayed in simulations
4. Go to setting, turn off "Show conversion on test networks"
5. Try simple send - see no fiat values displayed in simulations
6. Change current network to mainnet or any other network which is not testnet
7. Try simple send - see fiat values displayed in simulations

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: shared/constants/network.ts [hunk 1]
```diff
@@ -1116,3 +1116,10 @@ export const TEST_NETWORKS = [
   LINEA_GOERLI_DISPLAY_NAME,
   LINEA_SEPOLIA_DISPLAY_NAME,
 ];
+
+export const TEST_NETWORK_IDS = [
```
Comment (OGPoyraz) [inline shared/constants/network.ts:1120]: I didn't want to compare `nickname` as previous selectors do it hence adding testnet ids here.

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/components/simulation-details/fiat-display.tsx [hunk 2]
```diff
@@ -55,6 +61,11 @@ export const IndividualFiatDisplay: React.FC<{ fiatAmount: FiatAmount }> = ({
 export const TotalFiatDisplay: React.FC<{
   fiatAmounts: FiatAmount[];
 }> = ({ fiatAmounts }) => {
+  const hideFiatForTestnet = useHideFiatForTestnet();
+  if (hideFiatForTestnet) {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/simulation-details/fiat-display.tsx:65]: Do we need to move this below all the other hooks to ensure they are always run per render?

Same in the above component also.

File: ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx [hunk 3]
```diff
@@ -10,38 +11,70 @@ import { FIAT_UNAVAILABLE } from './types';
...
-        <IndividualFiatDisplay fiatAmount={fiatAmount} />,
+jest.mock('../../../../hooks/useHideFiatForTestnet');
+
+describe('FiatDisplay', () => {
+  const mockUseHideFiatForTestnet = jest.mocked(useHideFiatForTestnet);
+  const mockUseFiatFormatter = jest.mocked(useFiatFormatter);
+
+  beforeEach(() => {
+    jest.resetAllMocks();
+    mockUseHideFiatForTestnet.mockReturnValue(false);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx:22]: Since we're already using `renderWithProvider`, should we instead be mocking the preference state as opposed to mocking selectors as recommended by Redux?

File: ui/hooks/useHideFiatForTestnet.ts [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+import { TEST_NETWORK_IDS } from '../../shared/constants/network';
+
+/**
+ * Returns true if the fiat value should be hidden for testnet networks.
+ *
+ * @returns boolean
+ */
+export const useHideFiatForTestnet = (): boolean => {
+  const showFiatInTestnets = useSelector(getShowFiatInTestnets);
+  const chainId = useSelector(getCurrentChainId);
```
Comment (matthewwalsh0) [inline ui/hooks/useHideFiatForTestnet.ts:12]: To support multi-chain, should we at least optionally accept the `chainId` as a property rather than adding more reliance on the global network?

File: shared/constants/network.ts (hunk 1 above)
Comment (matthewwalsh0) [reply shared/constants/network.ts:1120]: To clarify, are you saying there is no existing constant of test chain IDs, only the above names?

Comment (OGPoyraz) [reply shared/constants/network.ts:1120]: Exactly, I couldn't find any map or an array in the extension code.

File: ui/hooks/useHideFiatForTestnet.ts (hunk 4 above)
Comment (OGPoyraz) [reply ui/hooks/useHideFiatForTestnet.ts]: Good call, added this as a parameter to respect the given `chainId`

Comment (OGPoyraz) [reply ui/hooks/useHideFiatForTestnet.ts]: Done in https://github.com/MetaMask/metamask-extension/pull/25167/commits/07411341fe588535c04301befa1bc358135e0ced

File: ui/pages/confirmations/components/simulation-details/fiat-display.tsx (hunk 2 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/simulation-details/fiat-display.tsx]: Done in https://github.com/MetaMask/metamask-extension/pull/25167/commits/c6c0ddbe73f24d1bfdf7fe30af01a6cd025ef837

File: ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx (hunk 3 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx]: For sure, changed approach in https://github.com/MetaMask/metamask-extension/pull/25167/commits/07411341fe588535c04301befa1bc358135e0ced

File: ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx [hunk 5]
```diff
@@ -1,47 +1,104 @@
...
 import mockState from '../../../../../test/data/mock-state.json';
+import { CHAIN_IDS } from '../../../../../shared/constants/network';
 import { IndividualFiatDisplay, TotalFiatDisplay } from './fiat-display';
 import { FIAT_UNAVAILABLE } from './types';
 
-const store = configureStore()(mockState);
+const mockStateWithTestnet = merge({}, mockState, {
+  metamask: {
+    providerConfig: {
+      chainId: CHAIN_IDS.SEPOLIA,
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx:15]: If we are going with this approach, I believe it's crucial to set some state props like this for the branch of these tests. 

Even if `mockState` is set as using Goerli chain id which is fine for this test, I believe we should still set the stage for only our test. This is the reason of I am creating `mockStateWithTestnet`

File: ui/hooks/useHideFiatForTestnet.ts [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+
+/**
+ * Returns true if the fiat value should be hidden for testnet networks.
+ *
+ * @param providedChainId
+ * @returns boolean
+ */
+export const useHideFiatForTestnet = (providedChainId?: Hex): boolean => {
+  const showFiatInTestnets = useSelector(getShowFiatInTestnets);
+  const chainId = providedChainId ?? useSelector(getCurrentChainId);
```
[the remark this answers is not in the document]
Comment (OGPoyraz) [reply ui/hooks/useHideFiatForTestnet.ts]: Done

**Review by jpuri — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
