### PR TITLE
fix(39724): fix QR infinite loader on firefox

### LINKED ISSUE #39724: [Bug]: [Firefox] QR - Infinite loader is presented after a successful swap in pop up mode
**Describe the bug**

In MM pop up mode, ssing QR wallet, after signing the transaction, infinite loader is presented even though the swap is successful.

**Expected result:**
After the successful swap the user should be taken to the main MM screen.

**Actual result:**
Infinite loader is presented with message "Confirm with you hardware wallet", even though the user already signed the transaction and the swap was successful.

**Environment:**

Device: MacBook Pro M4 ; macOS Tahoe 26.2
Firefox version: 147.0.2
MM prod v13.11.2

**Hardware wallet:**
Device: Keystone 3 Pro
Firmware: v2.3.2

**Screenshots/Recordings**

https://github.com/user-attachments/assets/048efeba-3d33-4fad-bc8b-f406cd578ab3

**Steps to reproduce**

- open MM on Firefox in pop up mode
- connect MM with QR wallet using Keystone 3 pro
- swap
- after clicking "Get signature" notice the user is taken to full screen mode in new tab
- proceed with the swap in full screen mode and sign the transaction
- notice the infinite loader even though the transaction is successful

**Error messages or log output**

```shell

```

**Where was this bug found?**

Live version (from official store)

**Version**

13.11.2

**Build type**

None

**Browser**

Firefox

**Operating system**

MacOS

**Hardware wallet**

Keystone

**Severity**

sev3

### PR DESCRIPTION
**Pull request by Olivier-BB**
## **Description**

This PR fixes an issue where users using QR hardware wallets in popup mode would encounter an infinite loader after successfully signing a bridge/swap transaction. The problem occurred because when the user clicked "Get signature", MetaMask would transition from popup mode to fullscreen mode, causing the popup state to be lost. The `AwaitingSignatures` component could no longer track the active quote, leaving users stuck on the loading screen even after the transaction was successfully submitted.

**The solution:**
1. **Preserve requestId in URL**: When navigating to the awaiting signatures page for hardware wallets, we now include the `requestId` as a URL query parameter. This allows the component to track the transaction even when popup state is lost during the popup-to-fullscreen transition.
2. **Detect completed transactions**: The component now checks the bridge history to determine if a transaction with the matching `requestId` has been submitted. It uses the `requestId` from either the active quote (when available) or from the URL parameters (when popup state is lost).
3. **Auto-navigate on completion**: Once the transaction is detected in the bridge history, the component automatically navigates the user to the home page with the activity tab, providing a smooth user experience.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/40014?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed infinite loader when using QR hardware wallets in popup mode after signing bridge transactions

## **Related issues**

Fixes: #39724

## **Manual testing steps**

1. Open MetaMask in Firefox in popup mode
2. Connect MetaMask with a QR hardware wallet
3. Initiate a bridge/swap transaction
4. Click "Get signature" and notice the transition to fullscreen mode in a new tab
5. Proceed with signing the transaction on the hardware wallet
6. Verify that after the transaction is successfully signed, the user is automatically taken to the main MetaMask screen (home page with activity tab) instead of being stuck on an infinite loader
7. Verify that the transaction appears in the activity tab

### **Before**

https://github.com/user-attachments/assets/96988011-5533-4f3d-87d4-988f8ff365f5
User would see infinite loader with "Confirm with your hardware wallet" message even after successful transaction.

### **After**

https://github.com/user-attachments/assets/04372124-46f2-40d6-842d-8e4e4e1dd20c
User is automatically navigated to home page with activity tab showing the completed transaction.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Changes bridge/swaps hardware-wallet navigation and auto-redirect logic based on URL params, QR scan state, and bridge history; regressions could mis-route users during two-step flows or on failure/cancel paths.
> 
> **Overview**
> Fixes the QR hardware-wallet popup→fullscreen transition getting stuck on the `AwaitingSignatures` loader by **persisting `requestId` in the awaiting-signatures URL** and using it to recover state when the popup store is lost.
> 
> Adds `useBridgeTransactionNavigation` to `AwaitingSignatures` to auto-navigate to `home?tab=activity` when the matching bridge tx appears in history, and to also navigate away on QR cancellation/failure while avoiding false positives between approval and bridge steps. Updates `useSubmitBridgeTransaction` to include `requestId` in the HW-wallet awaiting URL and to use `replace: true` on activity/prepare redirects, with new unit tests and console baseline updates.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 74a1c07ce4281a386a4ec6d71e79d8889af4389a. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by dawnseeker8 — DISMISSED** [review]
LGTM

**Comment by nikolastoimenovski-consensys** [comment]
Tested on build e15d6d0, the issue https://github.com/MetaMask/metamask-extension/issues/40088 is reproducible, video attached.

https://github.com/user-attachments/assets/bda15a1d-57d9-4d19-9a6d-5e4f46295298

File: ui/pages/bridge/awaiting-signatures/awaiting-signatures.tsx [hunk 1]
```diff
@@ -32,24 +40,178 @@ import {
...
   const hardwareWalletType = useSelector(getHardwareWalletType);
+  const activeQrCodeScanRequest = useSelector(getActiveQrCodeScanRequest);
   const needsTwoConfirmations = Boolean(activeQuote?.approval);
   const { trackEvent } = useContext(MetaMetricsContext);
+  // Refs to track state transitions for navigation logic
+  const prevQrScanRequestRef = useRef<typeof activeQrCodeScanRequest>(null);
+  const hasTrackedEventRef = useRef(false);
+  const hasSeenQrScanActiveRef = useRef<boolean>(false);
+  const hasSeenRequestIdRef = useRef<boolean>(false);
+  const hasSeenActiveQuoteRef = useRef<boolean>(false);
```
Comment (gantunesr) [inline ui/pages/bridge/awaiting-signatures/awaiting-signatures.tsx]: Any way we can encapsulate the logic added to this file in a new hook?

**Review by dawnseeker8 — APPROVED** [review]
LGTM

**Review by ghgoodreau — APPROVED** [review]

**Review by owencraston — CHANGES_REQUESTED** [review]
I am unable to complete a swap with my keystone. This occurred after a failed swap and then I cleared the transaction history. Before this, I was brought to the get signature screen but I was still unable to complete the swap.

https://github.com/user-attachments/assets/c26194b0-8395-4c7b-9d3e-773c09249aba

**Review by owencraston — APPROVED** [review]
