### PR TITLE
Fixed issues in onboarding flow

### LINKED ISSUE #13447: Overall Onboarding Flow Issues
- [ ] **Bug to investigate/fix**: Sometimes when I press "back", I end up on the wrong page. For example when I press "Back" on the "Secure your wallet" page, it drops me in the "import" flow.

- [ ] The progress bar text across many of the Onboarding screens should not be all caps:

 Screen Shot 2022-01-28 at 9 49 36 AM
Screen Shot 2022-01-28 at 9 49 39 AM

Should be normal casing: "Confirm secret recovery phrase" & "Create password"

- [ ] Enhance logic for the highlighting of progress bar.*

Mark's review: 
Page 1
Screen Shot 2022-01-28 at 9 55 14 AM

Page 2
Screen Shot 2022-01-28 at 9 55 44 AM

> I didn't understand what the highlighting was meant to indicate. On the first page I wasn't sure whether it was telling me I was on page 1 or 2 - the bubble around "1" was highlighted, but so was the line between 1 and 2, so I thought it might have meant I had finished with page 1 and was working on page 2.
> Then on page 2, I immediately thought "Oh, I guess it's broken because it's definitely saying I'm on page 1 now".

*requires design input (cc @rachelcope)

### PR DESCRIPTION
**Pull request by filipsekulic**
Fixes: https://github.com/MetaMask/metamask-extension/issues/13447

Sreenshot:

Screenshot 2022-03-03 at 10 52 26

Screencast:

https://user-images.githubusercontent.com/92310504/156544059-59cff462-e145-4f0c-8e85-fc4bd8cd8bb8.mov

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Review by darkwing — DISMISSED** [review]
This looks excellent @filipsekulic !

File: ui/pages/onboarding-flow/create-password/create-password.js [hunk 1]
```diff
@@ -126,7 +129,7 @@ export default function CreatePassword({
       return;
     }
     // If secretRecoveryPhrase is defined we are in import wallet flow
-    if (secretRecoveryPhrase) {
+    if (secretRecoveryPhrase && firstTimeFlowType === 'import') {
```
Comment (adonesky1) [inline ui/pages/onboarding-flow/create-password/create-password.js:132]: [nit] we could create an enum style object for `firstTimeFlowTypes`:

```
const firstTimeFlowTypes = {
IMPORT = 'import',
CREATE = 'create'
}
```

Comment (adonesky1) [reply ui/pages/onboarding-flow/create-password/create-password.js:132]: This could be added on `onboarding-flow.js` and imported and used all the spots where we use `firstTimeFlowType === 'import'` here.

**Review by adonesky1 — COMMENTED** [review]
Just one thing that I think we might as well handle in this PR (comment above) but otherwise LGTM!

File: ui/pages/onboarding-flow/create-password/create-password.js (hunk 1 above)
Comment (filipsekulic) [reply ui/pages/onboarding-flow/create-password/create-password.js]: I did this, but in a different way. I created a new file called `onboarding.js` within the `ui/helpers/constants` folder, as there are the other constants, and there I put this newly created object and exported it from there.
You can see the changes I made here: d3aaacb8d1e620485355883185ba645e858a63e1

**Review by adonesky1 — APPROVED** [review]
LGTM

**Review by darkwing — APPROVED** [review]

**Comment by darkwing** [comment]
Merging with 2 approvals.
