### PR TITLE
fix: carousel slide improved validation for zero balance

### LINKED ISSUE #33234: [Bug]: Fund carousel banner dismissible when balance is zero
### Describe the bug

Some carousel banners have local logic to fit the user context. Fund banner is expected to have logic that makes the banner non-dismissible until the user has funds. Starting 12.17.0, the fund banner is dismissable at all times.

### Expected behavior

Fund banner is non-dismissable until any account holds funds on any popular network

#### Expected behavior

https://github.com/user-attachments/assets/dac631e0-f5b0-42ae-85b4-f4405dd4c0bf

#### Current behavior

https://github.com/user-attachments/assets/72b0980b-3e00-43e8-90c2-81c172aab715

### Steps to reproduce

1. Fresh install with new wallet created
2. See `X` on banner
3. Close banner
4. Close Extension
5. Reopen and see fund banner no longer shown

Confirmed that Fund banner behaved as expected (set to `undismissable`:true) on 12.16.0

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.17.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

I'm not sure of the root cause, but the account tracker controller balance hex was `0x00`, because of this the default string check for `0x0` fails.

We have now improved this by using a BigNumber hex validation for zero balance.

Screenshot 2025-05-28 at 16 17 41

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33243?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33234

## **Manual testing steps**

See issue.
1. Select account with zero balance, see carousel is undismissible
2. Select account with balance, see carousel is dismissible

### **After**

https://www.loom.com/share/ae353487843c4625a21b5999348ab03f?sid=0aba9b26-d291-49cb-814b-6efe5ad6a864

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/hooks/useCarouselManagement/useCarouselManagement.ts [hunk 1]
```diff
@@ -129,8 +132,7 @@ export const useCarouselManagement = ({
     }
     // Handle Contentful Data
     const maybeFetchContentful = async () => {
-      const contentfulEnabled =
-        remoteFeatureFlags?.contentfulCarouselEnabled ?? false;
+      const contentfulEnabled = false;
```
Comment (bergarces) [inline ui/hooks/useCarouselManagement/useCarouselManagement.ts:135]: Any reason not to remove the content that is no longer accessible after setting this to `false`?

Comment (Prithpal-Sooriya) [reply ui/hooks/useCarouselManagement/useCarouselManagement.ts:135]: LOOOL good catch! I was disabling this for debugging purposes.
Will revert

Comment (Prithpal-Sooriya) [reply ui/hooks/useCarouselManagement/useCarouselManagement.ts]: https://github.com/MetaMask/metamask-extension/pull/33243/commits/a75f8f09f06015dbc90662a980d2a1f583290f70

**Review by bergarces — APPROVED** [review]

File: ui/hooks/useCarouselManagement/useCarouselManagement.ts (hunk 1 above)
Comment (bergarces) [reply ui/hooks/useCarouselManagement/useCarouselManagement.ts]: ☠️

**Review by mcbridemarci — APPROVED** [review]
