### PR TITLE
fix(snaps): cp-13.5.0 Write a custom number input for `SnapUIInput`

### LINKED ISSUE #35941: [Bug]: Firefox send flow - Solana - unable to send decimal amount if the symbol `,` is used instead of `.`
View issue in GitHub: https://github.com/MetaMask/metamask-extension/issues/35941

**Describe the bug**

When sending an amount with decimals on Firefox, if the symbol `,` is used instead of `.`, then the amount is not visible.

Similar for Solana send: unable to send decimal amount if the symbol `,` is used instead of `.` The _Continue_ button is greyed out.

Unable to reproduce on Chrome.

**Expected behavior**

Sending amount to be visible when it's typed with `,` same as for Chrome.

**Screenshots/Recordings**

https://github.com/user-attachments/assets/45f030f1-f80d-473d-9c50-f36eae6d958c

https://github.com/user-attachments/assets/74716721-2fe0-4526-b29b-d3fda4c1ec02

**Steps to reproduce**

1. Go to send flow
2. Type decimal sending amount with the symbol `,` instead of `.`
3. Notice it's not fully visible

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.4.0

**Build type**

None

**Browser**

Firefox

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

This PR writes a custom implementation for number inputs based on a text input to fix the firefox handling of number inputs.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36842?quickstart=1)

## **Changelog**

CHANGELOG entry:null

## **Related issues**

Fixes: #35941 

## **Manual testing steps**

1. Go test-snaps
2. use the send flow example snap

### **Before**

https://github.com/user-attachments/assets/5cca28e0-6fdd-4ccd-82d3-3ebfebef4959

### **After**

https://github.com/user-attachments/assets/90703760-3dc2-4726-a261-4fd7e3f13098

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Replaces native number input with a custom text-based implementation that supports min/max/step, input filtering, and arrow/wheel increments.
> 
> - **SnapUIInput**:
>   - Implement custom number input: render as text, normalize commas, restrict characters (`.` `,` `-`), and clamp using `min`/`max` with `step` (Shift x10).
>   - Add arrow up/down and mouse wheel increment/decrement; keep focus on interaction.
>   - Expose new props: `min`, `max`, `step`; factor `applyChange`; add `memo`.
> - **Renderer (`snap-ui-renderer/components/input.ts`)**:
>   - For `type: 'number'`, pass `min`/`max`/`step` to `SnapUIInput` and set `textFieldProps.type` to `text` (no longer using `inputProps` for these).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e79c88180358ebce27f8ae69f454548cca894050. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx [hunk 1]
```diff
@@ -10,113 +11,277 @@ import classnames from 'classnames';
...
   name: string;
   form?: string;
   label?: string | React.ReactNode;
+  min?: number;
+  max?: number;
+  step?: number;
+};
+
+/**
+ * Clamps a number between optional minimum and maximum values.
```
Comment (Mrtenz) [inline ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx]:
```suggestion
 * Clamp a number between optional minimum and maximum values.
```

File: ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx [hunk 2]
```diff
@@ -10,113 +11,277 @@ import classnames from 'classnames';
...
+      <FormTextField
+        ref={inputRef}
+        onFocus={handleFocus}
+        onBlur={handleBlur}
+        className={classnames('snap-ui-renderer__input', {
+          'snap-ui-renderer__field': label !== undefined,
+        })}
+        id={name}
+        value={value}
+        textFieldProps={{
```
Comment (Mrtenz) [inline ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:250]: Do we not want to spread `textFieldProps` here?

File: ui/components/app/snaps/snap-ui-renderer/components/input.ts [hunk 3]
```diff
@@ -19,13 +19,11 @@ export const constructInputProps = (props: InputElement['props']) => {
...
+        min,
+        max,
         textFieldProps: {
-          type,
-          inputProps: {
-            step: step?.toString(),
-            min: min?.toString(),
-            max: max?.toString(),
-          },
+          type: 'text',
```
Comment (Mrtenz) [inline ui/components/app/snaps/snap-ui-renderer/components/input.ts:26]: Is it intentional to use `text` here? Wouldn't we want to use `number` inputs in case the browser supports it?

**Review by Mrtenz — CHANGES_REQUESTED** [review]

File: ui/components/app/snaps/snap-ui-renderer/components/input.ts (hunk 3 above)
Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-renderer/components/input.ts:26]: We can't use `number` since Firefox does weird validation with this type and returns `undefined` if it isn't happy with the value

File: ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx (hunk 2 above)
Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:250]: I did not spread `textFieldProps` as there's no props passed to it right now

Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:250]: Do you want me to still spread this prop ?

**Review by Mrtenz — APPROVED** [review]

**Review by cryptodev-2s — APPROVED** [review]
LGTM!
