### PR TITLE
fix: Display mailto links properly in Snaps link warning

### LINKED ISSUE #29977: [Bug]: Email id is not displayed in the dialog
### Describe the bug

Email id is not displayed in the dialog

### Expected behavior

Email id should appear in the dialog

### Screenshots/Recordings

Image

### Steps to reproduce

1. Add PolkaGate snap from the directory.
2. Navigate to the extension app and select on the PolkaGate snap
3. Click on the More button and Contact Us
4. Observe the email id in the dialog

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.11.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by FrederikBolding**
## **Description**

Fixes a formatting issue when displaying mailto links in the `SnapLinkWarning`. This was broken due to parsing the `mailto:` link in the same way as HTTPS and assumptions made about the output of that parsing.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30000?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/29977

## **Manual testing steps**

See the attached ticket

### **Before**

See the attached ticket

### **After**

image

### CODE REVIEW

**Review by GuillaumeRx — DISMISSED** [review]

File: ui/components/app/snaps/snap-link-warning/snap-link-warning.js [hunk 1]
```diff
@@ -35,8 +35,10 @@ import { useI18nContext } from '../../../../hooks/useI18nContext';
 export default function SnapLinkWarning({ isOpen, onClose, url }) {
   const t = useI18nContext();
 
-  const parsedUrl = url && new URL(url);
-  const urlParts = parsedUrl && url.split(parsedUrl.host);
+  const parsedUrl = new URL(url);
+  const isHTTPS = parsedUrl.protocol === 'https:';
+  const urlParts = url.split(parsedUrl.host);
```
Comment (Mrtenz) [inline ui/components/app/snaps/snap-link-warning/snap-link-warning.js:40]: What do you think about moving this to a util function, together with the conditional below?

```ts
function getUrl(...) {
  // Do the thing
  if (isHttps) {
    return <>...</>;
  }

  return url;
}

Comment (FrederikBolding) [reply ui/components/app/snaps/snap-link-warning/snap-link-warning.js]: Refactored to move to a small sub component

**Review by Mrtenz — DISMISSED** [review]

**Review by GuillaumeRx — DISMISSED** [review]

**Review by GuillaumeRx — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]
