### PR TITLE
Identify token transactions by method names token data, and not just …

### LINKED ISSUE #3554: When edit transaction in Beta Metamask, it creates wrong tx
Bug Reports:

 Editing a tx completely messes with tx data.
Example: 
```js
return token.methods['approve(address,uint256)'](this.tokenStore.proxyMultiSenderAddress, this.tokenStore.totalBalanceWithDecimals)
      .send({from: this.web3Store.defaultAccount, gasPrice: this.gasPriceStore.standardInHex})
```
If I do click send -> it would send a normal tx like it should.
If I do click Edit in metamask BEFORE sending, it actually, overwrites data, to, value fields:
### Scenario#1: if token address was added to metamask 
Instead of making original `approve` call, it now turns it into token transfer.

### Scenario#2:
IF token address is not known to metamask(if you haven't added that token address to metamask)
when EDIT button was clicked, it turns into simple ETH transfer with the VALUE put into ETH(even if it was simple approve call) to the recipient.
Very dangerous! 

So, Please don't use EDIT button in new metamask, it completely messes the data

URL to check on any network:
https://poanetwork.github.io/multisender/#/
1. Just select any token address (make sure you have some balance)
2. Provide JSON [{"0xa35c9Af9e78B90B7217e1262cBd3638075A14CEe": "1"}]
3. click next, next
When metamask pops up for 1st tx, click edit
Now your pregenerated `approve` call turned into token transfer.

### PR DESCRIPTION
**Pull request by danjm**
Fixes #3554

Previous to this PR, we were failing to identify token transactions as **_token_** transactions if the token was not known to metamask. This PR ensures we correctly identify token transactions by basing the decision on decoded transaction data.

### CODE REVIEW

**Comment by kumavis** [comment]
Fixes #3617

File: ui/app/components/pending-tx/index.js [hunk 1]
```diff
@@ -63,14 +63,17 @@ PendingTx.prototype.componentWillMount = async function () {
       isFetching: false,
     })
   }
+  const tokenData = txParams && abiDecoder.decodeMethod(txParams.data)
+  const { name: tokenMethodName } = tokenData || {}
+  const isTokenTransaction = ['transfer', 'approve', 'transferFrom']
+    .find(possibleName => tokenMethodName === possibleName)
```
Comment (kumavis) [inline ui/app/components/pending-tx/index.js]: can do `isTokenTransaction.includes(tokenMethodName)`
