### PR TITLE
Various NFT UI fixes

### LINKED ISSUE #17139: NFTs: Group title is too close to circle, not vertically centered
### Describe the bug

The group title is flush up against the circle icon within NFT listings.  We need to add some spacing.  Additionally the text is not vertically centered.

### Steps to reproduce

1. Import an NFT
2. Look at the NFT grouping

### Error messages or log output

_No response_

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #17143: NFTs: Thumbnails are not accessible via keyboard
### Describe the bug

When tabbing through the NFT area, the thumbnails aren't selectable by keyboard, so a user cannot get to the NFT detail page without mouse.  

### Steps to reproduce

1.  Press tab to get to the NFT section of the home screen.  
2. Keep tabbing and you'll see that the NFT thumbnails aren't selectable

### Error messages or log output

_No response_

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #17144: NFTs: Data URI NFTs shouldn't have their URL as a link
### Describe the bug

Clicking the Data URI link result in a blank window being opened, so we shouldn't have DATA URIs be links.

DataUrl

### Steps to reproduce

1.  Import the following NFT (`0x932Ca55B9Ef0b3094E8Fa82435b3b4c50d713043` / `926`
2. Click into its detail page
3. Click the Data URI link

### Error messages or log output

_No response_

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #17148: NFTs: Info icon is misaligned
### Describe the bug

The "info" icon on the Import NFT page is vertically misaligned:

NFTInfoIcon

### Steps to reproduce

1.  Go to the Import NFTs screen
2. See that the info icons are too low

### Error messages or log output

_No response_

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
## Explanation
Fixes: https://github.com/MetaMask/metamask-extension/issues/17148
Fixes: https://github.com/MetaMask/metamask-extension/issues/17144
Fixes: https://github.com/MetaMask/metamask-extension/issues/17143
Fixes: https://github.com/MetaMask/metamask-extension/issues/17139

Additional adjustments outside of tagged issues:

- A copy button has been added for the data URI in the NFT detail view, alignment of copy buttons fixed
- As a result of fixing the info icon alignment issue in the 'Import NFT' screen, this issue has also been fixed in several other areas throughout the UI that were using `<FormField/>` with an info tooltip.

## Screenshots

(https://github.com/MetaMask/metamask-extension/issues/17139):
Screen Shot 2023-01-11 at 3 50 39 PM

(https://github.com/MetaMask/metamask-extension/issues/17144):
Screen Shot 2023-01-13 at 3 23 29 PM
Screen Shot 2023-01-13 at 3 23 33 PM
Screen Shot 2023-01-13 at 3 23 09 PM
Screen Shot 2023-01-13 at 3 23 16 PM

(https://github.com/MetaMask/metamask-extension/issues/17148):
Screen Shot 2023-01-11 at 10 28 49 PM
Screen Shot 2023-01-11 at 10 29 03 PM
Screen Shot 2023-01-11 at 10 29 28 PM

## Manual Testing Steps
1. Verify the static UI fixes in the given screens
2. On the NFT's tab, ensure that you can tab through the NFT thumbnails and access their respective detail pages via the keyboard.

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/app/collectible-details/collectible-details.js [hunk 1]
```diff
@@ -236,23 +237,28 @@ export default function CollectibleDetails({ collectible }) {
...
+              onClick={() => {
+                handleSourceCopy(collectibleImageURL);
+              }}
+            >
+              {sourceCopied ? (
+                t('copiedExclamation')
+              ) : (
+                <Copy size={15} color="var(--color-icon-alternative)" />
+              )}
+            </button>
```
Comment (brad-decker) [inline ui/components/app/collectible-details/collectible-details.js:261]: @georgewrmarshall / @garrettbear  / @NidhiKJha  do we have a "Icon button" component in the design system?

**Review by brad-decker — DISMISSED** [review]
I have a question regarding design system usage, but otherwise this is good to go.

**Comment by adonesky1** [comment]
Hey Ryan thanks for these cleanups! I'm not seeing the changes that fix https://github.com/MetaMask/metamask-extension/issues/17144 but in any case this image depicts an IPFS string being no longer as a link, but the issue is asking that only data uri image sources no longer be links:

211985573-9e9e2663-907a-4586-b4b3-8bdea23efdb0

**Comment by ryanml** [comment]
@adonesky1 ah this was an oversight on my part, thanks for catching!

when you say you’re not seeing the changes, do you just mean you can’t see them via perusing the code, or that when you build from this branch that the “source” field value still links out?

**Comment by adonesky1** [comment]
I meant I wasn't seeing the code change, but I see it now. Yeah so you'll only want it to be a non-link string when it starts with `data:`

File: ui/components/app/collectible-default-image/collectible-default-image.js [hunk 2]
```diff
@@ -9,14 +9,17 @@ export default function CollectibleDefaultImage({
...
   const t = useI18nContext();
   return (
     <div
+      tabIndex={0}
       className={classnames('collectible-default', {
         'collectible-default--clickable': handleImageClick,
       })}
       onClick={handleImageClick}
+      onKeyPress={handleImageKeyPress}
     >
```
Comment (jpuri) [inline ui/components/app/collectible-default-image/collectible-default-image.js:23]: @georgewrmarshall , @darkwing : plz share your suggestion on above keyPress handler. I am not sure of it is ok to have this on div ?

File: ui/components/app/collectible-default-image/collectible-default-image.js [hunk 3]
```diff
@@ -9,14 +9,17 @@ export default function CollectibleDefaultImage({
   name,
   tokenId,
   handleImageClick,
+  handleImageKeyPress,
 }) {
   const t = useI18nContext();
   return (
     <div
```
Comment (darkwing) [inline ui/components/app/collectible-default-image/collectible-default-image.js:16]: We should instead make this a `<button>`  so that `onClick` triggers the move.

File: ui/components/app/collectible-default-image/collectible-default-image.stories.js [hunk 4]
```diff
@@ -39,4 +43,7 @@ export const HandleImageClick = (args) => (
 HandleImageClick.args = {
   // eslint-disable-next-line no-alert
   handleImageClick: () => window.alert('CollectibleDefaultImage clicked!'),
+  handleImageKeyPress: () =>
```
Comment (darkwing) [inline ui/components/app/collectible-default-image/collectible-default-image.stories.js:46]: We wont need this when we switch to button.

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/components/ui/form-field/index.scss [hunk 5]
```diff
@@ -7,6 +7,7 @@
 
   .info-tooltip {
     display: inline-block;
+    margin-top: -6px;
```
Comment (darkwing) [inline ui/components/ui/form-field/index.scss:10]: We'll want to check all the places this is used.  Also, could this be achieved with `flexbox` / `align-items` so that we can count on content being centered when on multiple lines?

File: ui/components/app/collectible-default-image/collectible-default-image.js (hunk 2 above)
Comment (georgewrmarshall) [reply ui/components/app/collectible-default-image/collectible-default-image.js:23]: Hmm this is an interesting one. If I was going to look at it from a semantic html point of view in this context I believe the wrapping element should be an `<a/>` tag because it is navigating to another page or route in the application. The `react-router` `Link` component would be suitable but I see we don't use it in our codebase? Without complicating things too much I think `button` makes sense

File: ui/components/app/collectible-details/collectible-details.js (hunk 1 above)
Comment (georgewrmarshall) [reply ui/components/app/collectible-details/collectible-details.js:261]: Yes, docs here https://metamask.github.io/metamask-storybook/?path=/docs/ui-components-component-library-button-icon-button-icon-stories-js--default-story#buttonicon

File: ui/components/app/collectible-default-image/collectible-default-image.js (hunk 2 above)
Comment (georgewrmarshall) [reply ui/components/app/collectible-default-image/collectible-default-image.js:23]: Actually I think conditional tag rendering might make sense here because there are use cases for it to be static. So something like 
```
  handleImageClick,
}) {
  const t = useI18nContext();
  const Tag = handleImageClick ? 'a' : 'div';
  return (
    <Tag
```

Comment (ryanml) [reply ui/components/app/collectible-default-image/collectible-default-image.js]: This has been updated to use a `button` tag with conditional tag rendering

File: ui/components/app/collectible-default-image/collectible-default-image.js (hunk 3 above)
Comment (ryanml) [reply ui/components/app/collectible-default-image/collectible-default-image.js]: Updated

File: ui/components/app/collectible-default-image/collectible-default-image.stories.js (hunk 4 above)
Comment (ryanml) [reply ui/components/app/collectible-default-image/collectible-default-image.stories.js]: Removed

File: ui/components/ui/form-field/index.scss (hunk 5 above)
Comment (ryanml) [reply ui/components/ui/form-field/index.scss]: I've achieved this with `align-items: baseline` - this line has been removed

**Comment by ryanml** [comment]
@adonesky1 - I've updated the linking behavior on the details page, screenshots in the PR description have been updated to reflect this

File: ui/components/ui/form-field/index.scss (hunk 5 above)
Comment (ryanml) [reply ui/components/ui/form-field/index.scss]: Screenshots are in the PR of other places this is used

File: ui/components/app/collectible-details/collectible-details.js (hunk 1 above)
Comment (adonesky1) [reply ui/components/app/collectible-details/collectible-details.js:273]: @ryanml do you plan to use this button instead?

Comment (ryanml) [reply ui/components/app/collectible-details/collectible-details.js]: @adonesky1 I've updated this to use the `<ButtonIcon/>` component. Screenshots in the PR description have been updated, thanks!

**Review by adonesky1 — DISMISSED** [review]
LGTM! Thanks Ryan!

File: ui/components/app/collectibles-items/collectibles-items.js [hunk 6]
```diff
@@ -210,9 +214,11 @@ export default function CollectiblesItems({
                         }}
                       >
                         <img
+                          tabIndex={0}
```
Comment (darkwing) [inline ui/components/app/collectibles-items/collectibles-items.js:217]: The parent element to this should be a `<button>` so we can avoid `tabIndex` and `keypress` shims to accomplish what `<button>` gives us.

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/components/app/collectibles-items/collectibles-items.js (hunk 6 above)
Comment (ryanml) [reply ui/components/app/collectibles-items/collectibles-items.js]: @darkwing Ive made this change, thanks!

**Review by darkwing — APPROVED** [review]
Thank you @ryanml !  Let's try to keep this in separate PRs from now on so we can insta merge!  Well done!

**Review by brad-decker — APPROVED** [review]
