### PR TITLE
fix script for linting changed files

### LINKED ISSUE #17022: yarn lint:changed:fix stopped working
I've noticed that at some point within the past 2 weeks, the `yarn lint:changed:fix` command stopped working. `yarn lint:fix` still works, but I rely on `yarn lint:changed:fix` a lot while developing because it is a lot faster.

### PR DESCRIPTION
**Pull request by brad-decker**
## Explanation
Fixes #17022 

The `{ }` around the `diff-index` and `ls-files` git commands seems to not work for concatenating output of two commands in yarn 2+. All i had to do was elevate these two commands to their own script file. 

## Manual Testing Steps
1. start a new branch from this one
2. change a file and save without formatting to get a lint error
3. run `yarn lint:changed` to get the output of lint on that file.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes

### CODE REVIEW

File: development/get-changed-file-names.sh [hunk 1]
```diff
@@ -0,0 +1,2 @@
+#! /bin/bash
+git ls-files --others --exclude-standard ; git diff-index --name-only --diff-filter=d HEAD ;
```
Comment (darkwing) [inline development/get-changed-file-names.sh:2]: Does this need a new line?

**Review by rickycodes — APPROVED** [review]
lgtm

**Review by danjm — APPROVED** [review]
