### PR TITLE
fix: check if metametrics is done before redirecting to page on social cp-13.0.0

### LINKED ISSUE #34444: [Bug]: Should not show the metametric screen if user already finished it
### Describe the bug

When the user start the onboarding and finish the MetaMetric screen but not finish the whole flow yet
User close and open again
user see this screen again

### Expected behavior

Should not show this screen if the user complete it

### Screenshots/Recordings

https://github.com/user-attachments/assets/4ba95260-36aa-4e37-af5b-2ac93a76cf9a

### Steps to reproduce

See the video

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

12.23.0

### Build type

Beta

### Browser

Firefox, Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lionellbriones**
## **Description**
This fixes some cases where the app is redirected to metametrics screen, even if user has set metametrics preference already.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34438?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed app redirecting to metametrics page even if the user is done setting it.

## **Related issues**

Fixes:
https://github.com/MetaMask/metamask-extension/issues/34444

## **Manual testing steps**

1. Create a new wallet using social login
2. Continue onboarding and set metametrics preference
3. Open a new metamask instance (shown on attached video)
4. Unlock the app
5. App should not redirect to metametrics page, instead app should go to Completion page

### **Before**

https://github.com/user-attachments/assets/4ba95260-36aa-4e37-af5b-2ac93a76cf9a

### **After**

https://github.com/user-attachments/assets/9c624abe-7089-4b2c-b469-de2f87ec6394

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/first-time-flow.js [hunk 1]
```diff
@@ -38,7 +38,8 @@ export const getIsSocialLoginFlow = (state) => {
  * @returns {string} Route to redirect the user to
  */
 export function getFirstTimeFlowTypeRouteAfterUnlock(state) {
-  const { firstTimeFlowType } = state.metamask;
+  const { firstTimeFlowType, participateInMetaMetrics } = state.metamask;
+  const hasSetMetaMetrics = participateInMetaMetrics !== null;
```
Comment (lwin-kyaw) [inline ui/selectors/first-time-flow.js:42]: should use `getParticipateInMetaMetrics` from the selector

**Review by lwin-kyaw — APPROVED** [review]
lgtm

**Review by chaitanyapotti — APPROVED** [review]
