### PR TITLE
fix: missing Shield Metrics cp-13.13.0

### LINKED ISSUE #38728: [Bug]: Incorrect metrics value for Shield Subscription Request
### Describe the bug

Incorrect values were provided to the Segment API for Shield Subscription Request. This impacts analytic and marketing.

### Expected behavior

Correct property values should be provided to the Segment API as defined in the [schema](https://github.com/Consensys/segment-schema/blob/main/libraries/events/metamask-shield/shield-subscription-request.yaml). 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Start subscription to shield.
2. Pay attention to the segment API calls in the chrome dev tool.
3. Incorrect values were passed to `subscription_state` property of `Shield Subscription Request` event.

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.13.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lwin-kyaw**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38729?quickstart=1)

## **Changelog**

CHANGELOG entry: fixed shield subscription request metrics
CHANGELOG entry: added metrics for Subscription Payment Change

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38728

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds Shield payment-method-change metrics and refines subscription request tracking using New/Renew state and previous subscription context.
> 
> - **Metrics (background/services)**:
>   - Add `#trackPaymentMethodChangeRequestEvent` and emit `ShieldPaymentMethodChange` during crypto approval when an active subscription exists.
>   - Refactor `#trackSubscriptionRequestEvent` to include previous subscription context; use new `subscription_state` = `new|renew`.
>   - Use current subscription lookup (`#getCurrentShieldSubscription`) and route success/failure between subscription request vs. payment-method-change.
> - **Shared metrics utils/types**:
>   - Introduce `ShieldSubscriptionRequestSubscriptionStateEnum` (`new|renew`).
>   - Add `formatExistingSubscriptionEventProps` and `formatCaptureShieldPaymentMethodChangeEventProps`; derive old/new payment details from `Subscription` and `TransactionMeta`.
>   - Export `ExistingSubscriptionEventParams` and `CaptureShieldPaymentMethodChangeEventParams` to shared types; remove UI duplicates.
>   - Minor fix in `getSubscriptionDurationInDays` variable naming.
> - **UI**:
>   - Compute subscription request state via presence of `lastSubscription`; propagate to metrics.
>   - Switch CTA source to actual entry modal source in `shield-entry-modal` and learn-more click.
>   - Include `defaultPaymentChain` in Shield plan default options.
>   - Use shared formatting helpers; adjust `error` property name for payment-method-change event.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 94e6ad0a725a1131c8c4fd7fa03ab3c543a30984. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/scripts/services/subscription/subscription-service.ts [hunk 1]
```diff
@@ -699,4 +804,28 @@ export class SubscriptionService {
       },
     });
   }
+
+  async #getCurrentActiveSubscription(): Promise<Subscription | undefined> {
```
Comment (tuna1207) [inline app/scripts/services/subscription/subscription-service.ts]: i don't see this being used

**Review by lionellbriones — DISMISSED** [review]

File: app/scripts/services/subscription/subscription-service.ts [hunk 2]
```diff
@@ -664,6 +671,104 @@ export class SubscriptionService {
...
 
+  /**
+   * Track the subscription request event.
+   *
+   * @param requestStatus - The request status.
+   * @param currentShieldSubscription - The current Shield subscription (before making new subscription request).
+   * @param transactionMeta - The transaction meta (for crypto subscription requests).
+   * @param extrasProps - The extra properties.
+   */
+  #trackSubscriptionRequestEvent(
```
Comment (tuna1207) [inline app/scripts/services/subscription/subscription-service.ts:682]: nit `#getCurrentShieldSubscription` can be handled inside this method so we don't need a new parameter every call

Comment (lwin-kyaw) [reply app/scripts/services/subscription/subscription-service.ts:682]: `#trackSubscriptionRequestEvent` is called before/after the subscription requests where the state changes. So, need to provide the subscription before the state changes.

**Review by tuna1207 — DISMISSED** [review]

**Review by lionellbriones — DISMISSED** [review]

File: shared/modules/shield/metrics.ts [hunk 3]
```diff
@@ -197,8 +217,9 @@ export function getSubscriptionRequestTrackingProps(
   );
   const paymentChain = transactionMeta?.chainId;
 
-  const latestSubscriptionStatus =
-    getLatestSubscriptionStatus(subscriptions, lastSubscription) || 'none';
+  const subscriptionRequestState = previousShieldSubscription
+    ? ShieldSubscriptionRequestSubscriptionStateEnum.Renew
+    : ShieldSubscriptionRequestSubscriptionStateEnum.New;
```
[the remark this answers is not in the document]
Comment (lwin-kyaw) [reply shared/modules/shield/metrics.ts:222]: Addressed here, https://github.com/MetaMask/metamask-extension/pull/38729/commits/477d1180d49ed0d0dc7b438717fa167af871bcb2

**Review by tanguyenvn — APPROVED** [review]

**Review by lionellbriones — APPROVED** [review]
