### PR TITLE
fix: fix token details percentage

### LINKED ISSUE #33188: [Remove GNS]: Refine patterns for unavailable and zero changes on the home page and asset details
### Describe the bug

The patterns for zero changes and unavailable changes should be updated on the home page and asset details.

### Expected behavior

[Figma file](https://www.figma.com/design/9e6RSJCvezaLqDQ3mtE5wB/MaWaSB?node-id=4858-11176&t=cwjx5OsssCU418xq-4) with to suggested changes
Image

### Screenshots/Recordings

_No response_

### Steps to reproduce

- Add a token where we can't fetch the % change (eg. `USDFreeLiquidity`)
- Add a token where we can't fetch the conversion (eg. `LineaETH`)
- Switch to a network where you don't have a balance (eg. `Linea`)

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

- Ping @amandaye0h for design specs
- Ping @gambinish for more context about `TokenListItem` ie. how we compute zero/unavailable changes

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34354?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: #33188 #33187 

## **Manual testing steps**

1. Go to the token detail page
2. Check the 24h percentage change

### **After**

Screenshot 2025-07-17 at 13 09 05

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/asset/components/asset-page.tsx [hunk 1]
```diff
@@ -64,7 +64,10 @@ import {
   getMultichainNetworkConfigurationsByChainId,
   getMultichainShouldShowFiat,
 } from '../../../selectors/multichain';
-import { type TokenWithFiatAmount } from '../../../components/app/assets/types';
+import {
+  TokenFiatDisplayInfo,
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/components/asset-page.tsx:68]: nit - should we import this as a type?

File: ui/pages/asset/components/chart/asset-chart.tsx [hunk 2]
```diff
@@ -32,6 +32,7 @@ import {
   ButtonBase,
   ButtonBaseSize,
 } from '../../../../components/component-library';
+import { TokenFiatDisplayInfo } from '../../../../components/app/assets/types';
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/components/chart/asset-chart.tsx:35]: nit - should we import this as a type?

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
