### PR TITLE
fix: flaky test `Metrics Sends a contract interaction type 2 transaction (EIP1559) with the right properties in the metric events`

### LINKED ISSUE #30770: Fix "Metrics Sends a contract interaction type 2 transact..." flaky tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/128282/workflows/57cc56ad-ebf5-49b7-9064-d7aa4fc491f3/jobs/4603542/tests

### PR DESCRIPTION
**Pull request by seaona**
## **Description**

This PR fixes the [flaky test](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/128282/workflows/57cc56ad-ebf5-49b7-9064-d7aa4fc491f3/jobs/4603542/tests) `Metrics Sends a contract interaction type 2 transaction (EIP1559) with the right properties in the metric events`.

The problem is  that the global mock for the Blockaid API was incorrect, so we were sending a request to the live server. In some occasions the response failed, causing the metametrics event customization to display a blockaid error, making the metrics assertions to fail.

Screenshot from 2025-03-05 10-46-50

See the chainId we get from global mocks is `1337` but the API request uses the hex value of the chainId `0x539`

Screenshot from 2025-03-05 10-35-58

Screenshot from 2025-03-05 11-09-53

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30769?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30770

## **Manual testing steps**

1. Check ci, tests should be passing

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: test/e2e/mock-e2e.js [hunk 1]
```diff
@@ -161,7 +161,9 @@ async function setupMocking(
   });
 
   await server
-    .forPost(`${SECURITY_ALERTS_PROD_API_BASE_URL}/validate/${chainId}`)
+    .forPost(
+      `${SECURITY_ALERTS_PROD_API_BASE_URL}/validate/0x${chainId.toString(16)}`,
+    )
```
Comment (seaona) [inline test/e2e/mock-e2e.js:166]: this fixes the mock, as now we use the hex value of the chainId, which is what the API call uses

**Review by vinistevam — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]
