### PR TITLE
Fix 9435 - Allow speeding up of underpriced transactions

### LINKED ISSUE #9435: Underpriced speed-up can cause confusing error state
Steps to reproduce:
1. Submit a tx at a low gas price
2. Click "speed up" on the tx
3. Select the "slow" gas price of the available options.

Result:
- The RPC returned an error with the message `"replacement transaction underpriced"`
- This transitions the replacement tx to a "failed" state.
- The transaction history now shows "failed", implying to the user this tx has failed (this failure is indistinguishable from an on-chain failure), even though there is still a valid "submitted" transaction before that failed one.
- Upon retrying, the new transaction has the NEXT nonce (probably because of the valid "submitted" one with the lower nonce).

Expected result:
- Ideally, the user is not shown gas options that will result in "tx underpriced" errors.
- If a speed up attempt does fail with an RPC error, the user should stay on the confirmation screen, be shown this as an error, and have a chance to select a new gas price.

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #9435

This patch shows the "Pending" status transaction instead of a FAILED transaction that prevents any further transactions.

One remaining problem is possibly our speed up mechanism:

First, if the price is set very low, we only allow bumping up by an increment of 1, and that's not going to help very much:

SpeedUp

Second, pressing "Yes, let's try" doesn't do anything

### CODE REVIEW

File: ui/app/selectors/transactions.js [hunk 1]
```diff
@@ -251,11 +256,26 @@ export const nonceSortedTransactionsSelector = createSelector(
...
+          {
+            message: "Error: [ethjs-rpc] rpc error with payload {\"id\":428016472614,\"jsonrpc\":\"2.0\",\"params\":[\"0xf8650a843b9aca00843b9aca00940bd88c9c99be119dbbcd493699bfbffab0904d6980802ca0f511cd1297503b5a670e9459a174eceb4a2b7786df212821873eb2302727a49ba05ac22d6732af3e21539a2cbb738f53ccac2477de1e5a2d2a389f46b88693432f\"],\"method\":\"eth_sendRawTransaction\"} [object Object]",
+​​​            rpc: {
+              code: -32000
+              message: "exceeds block gas limit"
+            }
+          }
+        */
+        let primaryTransaction = transaction
+        if(transaction.status === FAILED_STATUS && Boolean(transaction?.err?.message)) {
```
Comment (brad-decker) [inline ui/app/selectors/transactions.js:270]: David pointed out something on a call we had where he went over some of his findings. the status 'failed' is not in the PRIORITY_STATUS_HASH.

The only way for a failed transaction to be the primary transaction is simply it being the latest transaction for a nonce. The `transactionSelector` that is a predicate of this selector, returns a list of transactions sorted by time. Therefore cancellations, retries, and transactions submitted with custom nonce equal to an existing transaction nonce will always be the `primaryTransaction` for a group.

`initialTransaction` gets set appropriately due to the comparison of time

I don't know if only network failures have this error object, but if that's true then that seems like a pretty good way to draw the distinction.

**Comment by Gudahtt** [comment]
Side-note about this comment:

>One remaining problem is possibly our speed up mechanism:

>First, if the price is set very low, we only allow bumping up by an increment of 1, and that's not going to help very much:

For cancellations, we always increase the gas price by 10%. This is not _nearly_ enough in many cases, such as for very low initial gas prices, or during times of high network volatility.

The fix we had in mind was to allow the user to customize the price. This is tracked in #8011

Though now that you mention it, our default here is also not great :thinking: Independent of allowing custom gas prices on cancellations, we should also consider current gas estimates. e.g. something like `Math.max(updatedGasPriceEstimate, oldPrice * 1.1)`. Maybe that could be a separate ticket.

File: ui/app/selectors/transactions.js [hunk 2]
```diff
@@ -251,11 +253,16 @@ export const nonceSortedTransactionsSelector = createSelector(
           nonceProps.hasCancelled = true
         }
       } else {
+        let primaryTransaction = transaction
+        if (transaction.status === FAILED_STATUS && Boolean(transaction?.err?.message)) {
```
Comment (brad-decker) [inline ui/app/selectors/transactions.js:257]: The only place where `transaction.err` is set is in the `tx-state-manager`'s `setTxStatusFailed` method. 

this method is only called inside of the main transaction controller. It's set when a transaction fails to transition from an unapproved transaction to an approved one (the user has confirmed the transaction, which queues it up to be sent to the network).

There are two more cases where this method is called, though, both of which are in the `_onBootCleanUp` method of the transaction controller. This method operates on two distinct categories of transactions: approved transactions and unapproved ones that have the 'loadingDefaults' flag. In the latter case, the intent is to add default gas estimations to the unapproved transactions so that they can be sent to the user for approval. In the former case, these transactions are automatically moved to the failed state. It appears we might not be able to effectively transition approved transactions that do not immediately get moved to the submitted status if the background process somehow terminates/restarts. 

Those cases don't appear to me to be things that we'd want to reassign `primaryTransaction` for, either. So I think this change is safe. I'd like @Gudahtt, @rekmarks, or @whymarrh to double-check me on this though.

**Review by brad-decker — DISMISSED** [review]

**Review by Gudahtt — CHANGES_REQUESTED** [review]
Wouldn't this fail for a "group of 1", if the transaction had failed? We do still want to assign a failed transaction as primary (either a network or on-chain failure, _any_ failure really) if it's the sole transaction in the group.

**Comment by brad-decker** [comment]
@darkwing I hate it when @Gudahtt is right. 

Instead, while we are iterating the transactions, what we could do is check if the assigned primaryTransaction is in a failed state. If that's true, OR the transaction has a higher (later) time, we reassign the primaryTransaction.

I *think* that would resolve the problem still without introducing the issue with groups of 1 failed transactions.

File: ui/app/selectors/transactions.js (hunk 2 above)
Comment (Gudahtt) [reply ui/app/selectors/transactions.js:257]: Either way I think this is the wrong property to check. See here: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L283

An on-chain failure might also be represented by a "confirmed" transaction with an error status on the transaction receipt. There would be no `err` property in that case. In the MetaMask Controller, we check for a status of either "failed" or "confirmed", and we look for this zero status on the receipt. [A status of zero denotes an on-chain failure.](https://eth.wiki/json-rpc/API#eth_gettransactionreceipt)

Comment (Gudahtt) [reply ui/app/selectors/transactions.js:257]: I actually don't fully understand the case where a transaction has a status of "failed" _and_ a transaction receipt. Maybe that's not possible? It is probably safe to assume that _if_ it has a transaction receipt with a status of zero, then it must be an on-chain failure though.

Comment (brad-decker) [reply ui/app/selectors/transactions.js:257]: Would that confirmed transaction with an on-chain failure be a 'failed' or 'confirmed' status in our state?

Comment (brad-decker) [reply ui/app/selectors/transactions.js:257]: Also, just to make sure I understand fully, are you suggesting that we look at `txReceipt` to determine failure?

Comment (Gudahtt) [reply ui/app/selectors/transactions.js:257]: This status check is here as well: https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/helpers/utils/transactions.util.js#L172
This is how the UI differentiates between confirmed successful transactions and on-chain failures.

Comment (Gudahtt) [reply ui/app/selectors/transactions.js:257]: In the background, an on-chain failure _should_ have a status of "confirmed" with a `txReceipt` status of `0x0`. But I don't understand all of the potential failure cases, so I can't say what might happen if an error is thrown somewhere. It's possible we have on-chain failures on transactions with a "failed" status as well.

Comment (Gudahtt) [reply ui/app/selectors/transactions.js:257]: >Also, just to make sure I understand fully, are you suggesting that we look at `txReceipt` to determine failure?

`txMeta.txReceipt.status` is the sole way we should be checking for on-chain failures. I think you're correct about `txMeta.err` being the best way to check for _other_ error states.

Comment (Gudahtt) [reply ui/app/selectors/transactions.js:257]: Oops. When I said "Either way I think this is the wrong property to check", I was confused and thinking we were trying to detect on-chain failures. Really we're trying to detect failures that _aren't_ on-chain. Sorry :sweat_smile:

I still think we should check the `txReceipt.status` to filter out on-chain failures though, just on the off chance that they _somehow_ got a status of "failed" instead of "confirmed".

Comment (brad-decker) [reply ui/app/selectors/transactions.js:257]: Seems like we should be checking for on chain failures in the controller instead of having many different branches of failure that have to be checked in the UI.

Comment (brad-decker) [reply ui/app/selectors/transactions.js:257]: With that said we'd need to check the primaryTransaction `status === FAILED && transaction.err` or `status === CONFIRMED && transaction.txReceipt.status === '0x0'` if that's true, override `primaryTransaction` with current pending/confirmed transaction (as long as it also is not an on-chain failure)

Comment (brad-decker) [reply ui/app/selectors/transactions.js:257]: @darkwing and @Gudahtt lets jump on a call on Monday to talk through this? It'd be helpful for me at least as I continue working on activity list refactor.

File: ui/app/selectors/transactions.js [hunk 3]
```diff
@@ -227,14 +231,25 @@ export const nonceSortedTransactionsSelector = createSelector(
...
-          const { primaryTransaction: { time: primaryTxTime = 0 } = {} } = nonceProps
-
           if (status === CONFIRMED_STATUS || txTime > primaryTxTime) {
             nonceProps.primaryTransaction = transaction
           }
         }
 
+        // If the primary transaction is failed or this transaction newer, assign as primary
+        if (
+          (nonceProps.primaryTransaction.status === FAILED_STATUS && nonceProps.primaryTransaction?.txReceipt?.status === '0x0' && transaction.status !== FAILED_STATUS) ||
```
Comment (brad-decker) [inline ui/app/selectors/transactions.js:243]: There are two failure states we'd want to catch here:

```primaryTransaction.status === FAILED``` and ```primaryTransaction.txReceipt.status === '0x0'``` these are two separate failure states. The latter could be `primaryTransaction.status === CONFIRMED```

additionally you don't want to drop the CONFIRMED check, here..so a stab at the logic might be:

```js
const previousPrimaryIsFailed = nonceProps.primaryTransaction.status === FAILED_STATUS || nonceProps.primaryTransaction?.txReceipt?.status === '0x0';

if (status === CONFIRMED_STATUS || previousPrimaryIsFailed || txTime > primaryTxTime) {
  // do stuff
}
```

Comment (Gudahtt) [reply ui/app/selectors/transactions.js]: Hmm. That doesn't seem _quite_ right either. We want to treat the two types of failure (on-chain and network) in _opposite_ ways, not in the same way.

e.g. something like this:

```
const previousPrimaryIsNetworkFailure= nonceProps.primaryTransaction.status === FAILED_STATUS && nonceProps.primaryTransaction?.txReceipt?.status !== '0x0';
const currentTransactionIsOnChainFailure = transaction.txReceipt?.status === '0x0'

if (status === CONFIRMED_STATUS || currentTransactionIsOnChainFailure || previousPrimaryIsNetworkFailure || txTime > primaryTxTime) {
  // do stuff
}
```

So there are three priorities here. _Anything_ should be prioritized over a network failure, but a status of `confirmed` or an on-chain failure should be prioritized above `pending`, because they both represent a "final" state for the transaction that can't change from there on.

Comment (Gudahtt) [reply ui/app/selectors/transactions.js]: Though, we may be able to assume that on-chain failures have a status of `confirmed`. I was unable to confirm that it was possible for an on-chain failure to get assigned a `failed` status.

Comment (darkwing) [reply ui/app/selectors/transactions.js]: We're off on something because, per my PR's console statements, the primary transaction is being replaced *every time*.

Comment (Gudahtt) [reply ui/app/selectors/transactions.js]: Oh! Sorry I was imagining my snippet as being _inside_ the `if (status in  PRIORITY_STATUS_HASH)` block. Though that wouldn't have made sense either because `FAILED` isn't in that object.

So maybe something like this:

```
f (status === CONFIRMED_STATUS || currentTransactionIsOnChainFailure || previousPrimaryIsNetworkFailure || (txTime > primaryTxTime && status in PRIORITY_STATUS_HASH)) {
```

File: ui/app/selectors/transactions.js [hunk 4]
```diff
@@ -227,12 +231,17 @@ export const nonceSortedTransactionsSelector = createSelector(
...
         insertTransactionByTime(nonceProps.transactions, transaction)
 
-        if (status in PRIORITY_STATUS_HASH) {
-          const { primaryTransaction: { time: primaryTxTime = 0 } = {} } = nonceProps
+        const { primaryTransaction: { time: primaryTxTime = 0 } = {} } = nonceProps
 
-          if (status === CONFIRMED_STATUS || txTime > primaryTxTime) {
-            nonceProps.primaryTransaction = transaction
-          }
+        const previousPrimaryIsNetworkFailure = nonceProps.primaryTransaction.status === FAILED_STATUS && nonceProps.primaryTransaction?.txReceipt?.status !== '0x0';
```
Comment (brad-decker) [inline ui/app/selectors/transactions.js:236]: So I have tested our usual workflow for triggering the bug reported in #9435, and this fix resolves that issue, for sure;

I have also tested what happens if a user submits a custom nonce transaction with the same nonce as a group of transactions in the state described in #9435 👍 
1. submit tx on Rinkeby with 0.6 `gasPrice.`
2. Speed up tx with `gasPrice` 1 and extremely high `gasLimit` (above network tolerance)
3. --on develop this tx would now show as failed, on this PR it shows as pending (correct)--
4. Submit a new transaction with the same nonce as the prior two, with a different value to be able to distinguish in UI
5. TX in UI updates to reflect new value in the pending state
6. TX is confirmed and continues to reflect the appropriate custom nonce tx.

The only thing I haven't yet been able to test is on-chain failures because I don't know how to replicate them -- however, the logic looks good, and it would follow the same trajectory as network failures, so I think I'm 👍 on this. I have a couple of nits/thoughts.

```js
const previousPrimaryIsNetworkFailure = nonceProps.primaryTransaction.status === FAILED_STATUS && nonceProps.primaryTransaction?.txReceipt?.status !== '0x0';
```

I'm not sure that the latter half of the check is necessary; we'd want to handle on-chain failures as the primary transaction in the same way as network failures. Any TX that is failed should be superseded with a non-failed tx of the same nonce, regardless of failure reason.

```js
const currentTransactionIsOnChainFailure = transaction?.txReceipt?.status === '0x0'
```

So, previously if an on-chain failure were in the 'confirmed' status, it would have been appropriately marked as the `primaryTransaction.` However, transactions that were in a 'failed' status would have been skipped and potentially not set as the `primaryTransaction.` So I think this logic in the if block makes sense to make sure that on-chain failures are properly identified in the UI. However, if the previous `primaryTransaction` is still pending, we wouldn't want the on-chain failure to supersede it, which would result in a similar scenario like the one mentioned in #9435. It should be noted that I'm running through a mental model here and haven't tested with real or synthetic on-chain failures.

Comment (brad-decker) [reply ui/app/selectors/transactions.js:236]: Example Scenario:

3 transactions, oldest to newest
1 - Pending transaction
2 - On-chain failure
3 - Network failure

1. on evaluating the first transaction 1 is set as both primary and initial.
2. on evaluating the second transaction, transaction 2 would be set at the primary transaction due to the `|| currentTransactionIsOnChainFailure` check
3. on evaluating the third transaction it is skipped due to it not being confirmed, the current transaction is not an on-chain failure, the previous `primaryTransaction` is not a network failure and its status is not in the `PRIORITY_STATUS_HASH`.

The logic does seem to work the same regardless of the order of transactions:

1. On evaluating the third transaction (now first) it is set as both primary and initial
2. On evaluating the second transaction it is set as the primary transaction due to being an on-chain failure.
3. On evaluating the third transaction it is skipped because it's an older transaction.

Comment (Gudahtt) [reply ui/app/selectors/transactions.js:236]: >However, if the previous primaryTransaction is still pending, we wouldn't want the on-chain failure to supersede it, which would result in a similar scenario like the one mentioned in #9435. 

If a transaction has been confirmed or failed on-chain, it should not be possible for it to still be "pending" as well. That's... kinda what it means for it to be confirmed. Or that was my understanding anyway. That's why the `confirmed` status was treated as a higher priority than the others.

Comment (brad-decker) [reply ui/app/selectors/transactions.js]: At least to my understanding, you're right that an on-chain failure would prevent any transaction with the same nonce from being accepted -- an on-chain failure most likely means we should display a failed transaction to the user. I think that might make my other feedback counterproductive as well, we'd want to override a failed transaction as primary only if it *was not* an on-chain failure. Protecting us from accidentally overriding a transaction that was, in reality, confirmed but then failed on-chain. 

I think I might be taking back my feedback -- meaning this would be good as is?

Comment (brad-decker) [reply ui/app/selectors/transactions.js]: I should have seen https://github.com/MetaMask/metamask-extension/pull/9687#discussion_r513056467 and the subsequent conversation. My apologies for leading this astray and countering your advice, @Gudahtt

Comment (Gudahtt) [reply ui/app/selectors/transactions.js]: No problem! I agree that this seems correct as-is.

Comment (brad-decker) [reply ui/app/selectors/transactions.js]: Sorry for the confusion @darkwing!

File: ui/app/selectors/transactions.js [hunk 5]
```diff
@@ -251,6 +253,13 @@ export const nonceSortedTransactionsSelector = createSelector(
           nonceProps.hasCancelled = true
         }
       } else {
+
+        /*
+        if (transaction.status === FAILED_STATUS && Boolean(transaction?.err?.message)) {
```
Comment (brad-decker) [inline ui/app/selectors/transactions.js:258]: We can remove this logic now

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/app/selectors/transactions.js (hunk 5 above)
Comment (darkwing) [reply ui/app/selectors/transactions.js]: d'oh!  Sorry!

**Review by brad-decker — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!
