### PR TITLE
Fixing incorrectly typed token decimal attribute

### LINKED ISSUE #10665: Warning: Failed prop type: Invalid prop `token.decimals` of type `string` supplied to `TokenAsset`, expected `number`
```
backend.js:32 Warning: Failed prop type: Invalid prop `token.decimals` of type `string` supplied to `TokenAsset`, expected `number`.
    in TokenAsset (created by Asset)
    in Asset (created by Context.Consumer)
    in Route (created by Authenticated)
    in Authenticated (created by ConnectFunction)
    in ConnectFunction (created by Routes)
    in Switch (created by Routes)
```
1. Go to Add A custom token
2. Enter an NFT, such as `CX` (Cryptokitties) - `0x06012c8cf97bead5deae237070f9587f8e7a266d`
3. Note that the decimals are set to 0 and cannot be changed.
4. Finish adding, click in to the detail view for the asset and observe the error

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/10665

Essentially if you are to add an NFT, or something with a 0 decimal value that does not allow for override, that gets saved to the state as `"0"` as opposed to 0, so we causing some component issues. Migrations added to back-fix the issue.

Manual testing steps:  
Defined in issue

### CODE REVIEW

File: app/scripts/migrations/054.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    const state = versionedData.data;
+    const newState = transformState(state);
+    versionedData.data = newState;
+    return versionedData;
+  },
+};
+
+function transformState(state) {
+  const newState = state;
+
```
Comment (danjm) [inline app/scripts/migrations/054.js:22]: A migration of `accountTokens` will also be needed. Check out this PR which is also about to migrate `tokens` and `accountTokens`: https://github.com/MetaMask/metamask-extension/pull/10593/files#diff-0ee44923cc3a183d3803fea2022e1b17f127940f603909b954588cc7c7aa2439R47

And for reference on what those are, see this thread: https://consensys.slack.com/archives/GTQAGKY5V/p1615395521395500?thread_ts=1615332992.380200&cid=GTQAGKY5V

**Review by danjm — CHANGES_REQUESTED** [review]
I left one comment that needs to be addressed

File: app/scripts/migrations/054.js (hunk 1 above)
Comment (ryanml) [reply app/scripts/migrations/054.js:22]: Good catch here 👍 I believe having these incorrectly typed in part of `accountTokens` does not produce the UI error in question, but for structural parity they should absolutely be the same.

File: app/scripts/migrations/054.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+  if (Array.isArray(tokens)) {
+    for (const token of tokens) {
+      if (token.decimals === '0') {
+        token.decimals = Number('0');
+      }
+    }
+  }
+  newState.PreferencesController.tokens = tokens;
+
+  const { accountTokens } = newState.PreferencesController || {};
```
Comment (ryanml) [inline app/scripts/migrations/054.js:37]: I tried to clean up this pyramid but the linter wasn't having it ;)

File: app/scripts/migrations/054.js (hunk 1 above)
Comment (Gudahtt) [reply app/scripts/migrations/054.js:22]: I see that this is addressed now, but for future reference: it does end up indirectly causing the problem, because `tokens` gets derived from `accountTokens` whenever the user switches accounts or networks.

Comment (ryanml) [reply app/scripts/migrations/054.js:22]: @Gudahtt - ah, thank you for pointing this out

**Review by danjm — DISMISSED** [review]
LGTM

File: app/scripts/migrations/054.js [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+};
+
+function transformState(state) {
+  const newState = state;
+
+  if (!newState.PreferencesController) {
+    return newState;
+  }
+
+  const { tokens } = newState.PreferencesController || [];
```
Comment (Gudahtt) [inline app/scripts/migrations/054.js:27]: Nit: The `[]` fallback is unreachable, and isn't the correct type anyway

```suggestion
  const { tokens } = newState.PreferencesController;
```

File: app/scripts/migrations/054.js [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+  if (Array.isArray(tokens)) {
+    for (const token of tokens) {
+      if (token.decimals === '0') {
```
Comment (Gudahtt) [inline app/scripts/migrations/054.js:30]: Are you sure that `0` was the only possible string? :thinking:  We could check the type here instead.

File: app/scripts/migrations/054.js (hunk 2 above)
Comment (Gudahtt) [inline app/scripts/migrations/054.js:37]: Nit: the fallback is the correct type here, but it's unreachable due to the earlier `!newState.PreferencesController`` condition.
```suggestion
  const { accountTokens } = newState.PreferencesController;
```

File: app/scripts/migrations/054.js (hunk 4 above)
Comment (ryanml) [reply app/scripts/migrations/054.js:30]: @Gudahtt - `0` was the only default decimal value I had seen occur during testing of numerous NFT's, but I think you're right that things should extend to check for strings in general. I can make needed updates here

File: app/scripts/migrations/054.js (hunk 3 above)
Comment (ryanml) [reply app/scripts/migrations/054.js:27]: woops! good catch here, I originally had this has `const tokens = newState.preferencesController.tokens || []` but had incorrectly fixed it.

Comment (ryanml) [reply app/scripts/migrations/054.js]: fixed

File: app/scripts/migrations/054.js (hunk 2 above)
Comment (ryanml) [reply app/scripts/migrations/054.js]: fixed

File: app/scripts/migrations/054.js (hunk 4 above)
Comment (ryanml) [reply app/scripts/migrations/054.js]: per our conversation, we are now doing general string primitive checks, as well as looking for an potential corruption that could result in being unable to perform a numerical conversion.

File: app/scripts/migrations/054.js [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+
+  const tokens = newState.PreferencesController.tokens || [];
+  // Filter out any tokens with corrupted decimal values
+  const validTokens = tokens.filter(({ decimals }) =>
+    isValidDecimals(decimals),
+  );
+  for (const token of validTokens) {
+    // In the case of a decimal value type string, set to 0.
+    if (typeof token.decimals === 'string') {
+      // eslint-disable-next-line radix
```
Comment (ryanml) [inline app/scripts/migrations/054.js:39]: note, per discussion with @Gudahtt we'll let the radix be inferred

File: app/scripts/migrations/054.js [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+    for (const address of Object.keys(accountTokens)) {
+      const networkTokens = accountTokens[address];
+      if (networkTokens && typeof networkTokens === 'object') {
+        for (const network of Object.keys(networkTokens)) {
+          const tokensOnNetwork = networkTokens[network] || [];
+          // Filter out any tokens with corrupted decimal values
+          const validTokensOnNetwork = tokensOnNetwork.filter(({ decimals }) =>
+            isValidDecimals(decimals),
+          );
+          // In the case of a decimal value type string, set to 0.
```
Comment (Gudahtt) [inline app/scripts/migrations/054.js:56]: Nit: This comment is no longer accurate

```suggestion
          // In the case of a decimal value type string, convert to a number.
```

File: app/scripts/migrations/054.js [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+    return newState;
+  }
+
+  const tokens = newState.PreferencesController.tokens || [];
+  // Filter out any tokens with corrupted decimal values
+  const validTokens = tokens.filter(({ decimals }) =>
+    isValidDecimals(decimals),
+  );
+  for (const token of validTokens) {
+    // In the case of a decimal value type string, set to 0.
```
Comment (Gudahtt) [inline app/scripts/migrations/054.js:37]:
```suggestion
    // In the case of a decimal value type string, convert to a number.
```

File: app/scripts/migrations/054.js [hunk 8]
```diff
@@ -0,0 +1,71 @@
+import { cloneDeep } from 'lodash';
+
+const version = 54;
+
+function isValidDecimals(decimals) {
+  return decimals !== '' && !isNaN(Number(decimals));
```
Comment (Gudahtt) [inline app/scripts/migrations/054.js:6]: Nit: This will still coerce floats into integers. Using a regex might be safer, e.g.
```suggestion
  return typeof decimals === 'number' || (typeof decimals === 'string' && decimals.match(/^(0x)?\d+$/))
```

**Review by Gudahtt — DISMISSED** [review]
LGTM! Couple of comment issues and one suggestion, but looks good otherwise.

File: app/scripts/migrations/054.js (hunk 8 above)
Comment (ryanml) [reply app/scripts/migrations/054.js]: Good thought, fixed

File: app/scripts/migrations/054.js [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+
+function isValidDecimals(decimals) {
+  return (
+    typeof decimals === 'number' ||
+    (typeof decimals === 'string' && decimals.match(/^(0x)?\d+$/u))
+  );
+}
+
+/**
+ * Migrates preference tokens with 0 decimals typed as 'string' to 'number'
```
Comment (Gudahtt) [inline app/scripts/migrations/054.js:13]: Nit: Just noticed this comment was out of date too!

Comment (ryanml) [reply app/scripts/migrations/054.js]: fixed!

**Review by Gudahtt — APPROVED** [review]
LGTM!
