### PR TITLE
fix: fix token detection modal stuck on firefox

### LINKED ISSUE #25256: [Bug]: Can not access wallet after unlock
### Describe the bug

After unlocking the wallet and dismissing the call-to-action for enabling token autodetection, the wallet UI is perpetually blocked behind a loading-spinner.

### Expected behavior

Can interact with wallet UI

### Screenshots/Recordings

scrot1-2
scrot2-2

### Steps to reproduce

1. Build: `rm -rf dist && yarn && yarn build:dev dev --build-type main --lockdown false --snow false --apply-lavamoat false`
2. Load build in Firefox
3. Unlock wallet
4. Dismiss token-autodetection modal

### Error messages or log output

_No response_

### Version

develop

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

Reverting #24281 makes the UI load as expected and resolves the issue.

### Severity

- Makes wallet completely inaccessible

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Token detection modal seems to stay stuck on firefox

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25279?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25256

## **Manual testing steps**
To run locally use: 
`rm -rf dist && ENABLE_MV3=false yarn && ENABLE_MV3=false yarn build:dev dev --build-type main --lockdown false --snow false --apply-lavamoat false`

1. Import wallet on firefox
2. Got to settings => security and privacy and disable token auto detection
3. Go back to home page and you should see the token detection modal
4. Clicking on allow should dismiss the modal and enable the token detection

### **Before**

https://github.com/MetaMask/metamask-extension/assets/10994169/e23f59d6-7bc9-4707-872d-436c1a56e7cf

### **After**

https://github.com/MetaMask/metamask-extension/assets/10994169/cf47e04c-e5bc-4898-92f1-c80c87988fdb

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/auto-detect-token/auto-detect-token-modal.tsx [hunk 1]
```diff
@@ -55,7 +54,6 @@ function AutoDetectTokenModal({
         category: MetaMetricsEventCategory.Navigation,
         properties: {
           chain_id: chainId,
-          locale: getCurrentLocale,
```
Comment (sahar-fehri) [inline ui/components/app/auto-detect-token/auto-detect-token-modal.tsx:58]: Hey @salimtb 👋  any idea why this was needed in the first place?

Comment (darkwing) [reply ui/components/app/auto-detect-token/auto-detect-token-modal.tsx:58]: Ohhhh, we're trying to set a value of a function instead of the locale itself.  So assuming we need the locale, we could do:

```
const locale = useSelector(getCurrentLocale)
```

Is this correct?

Comment (sahar-fehri) [reply ui/components/app/auto-detect-token/auto-detect-token-modal.tsx:58]: Right that fixes it, i haven't seen any trackEvent passing the `locale`, so i removed, i guess i can put it back just in case and merge 🙏  thanks!

**Review by bergeron — APPROVED** [review]

**Comment by bergeron** [comment]
nice find 😎

File: ui/components/app/auto-detect-token/auto-detect-token-modal.tsx (hunk 1 above)
Comment (bergeron) [reply ui/components/app/auto-detect-token/auto-detect-token-modal.tsx:58]: I think selecting the locale here is fine, although it looks like the events may automatically get locale added.  May not end up being necessary.

https://github.com/MetaMask/metamask-extension/blob/92e6b945eb54fafba491d9a84ca95c2e5fbaf932/app/scripts/controllers/metametrics.js#L761

**Review by legobeat — APPROVED** [review]
Fix works for me.

Should this also have some failing e2e test associated with it?

**Comment by bergeron** [comment]
I expect this would need to be cherry picked to 12.0.0

**Review by salimtb — APPROVED** [review]

**Comment by sahar-fehri** [comment]
> Fix works for me.
> 
> Should this also have some failing e2e test associated with it?

Hey @legobeat , i started creating the e2e test for this case, then realized that the modal can't be shown in the test because  `process.env.IN_TEST`  is equal true in the tests.

In the code, the  `showAutoDetectionModal` depends on `canSeeModals` which also depends on `process.env.IN_TEST`
`    const canSeeModals =
      completedOnboarding &&
      (!onboardedInThisUISession ||
        firstTimeFlowType === FirstTimeFlowType.import) &&
      !process.env.IN_TEST &&
      !newNetworkAddedConfigurationId;`

and

```
const showAutoDetectionModal =
      canSeeModals &&
      isShowTokenAutodetectModal &&
      !showSmartTransactionsOptInModal &&
      !showWhatsNew;
```

I wasn't sure what was the context of having the `!process.env.IN_TEST` check in the canSeeModals, and mocking it in the test seemed to be tricky ..
