### PR TITLE
fix: display gas details section for legacy transactions

### LINKED ISSUE #21140: [Bug]: No `Fee details` and ''MetaMask Gas fees` displayed on legacy tx's
### Describe the bug

**Problem**: there is no Fee details section and no MetaMask Gas fees displayed on Legacy transactions.

This issue will be introduced when https://github.com/MetaMask/metamask-extension/pull/19960 get's merged.

### Expected behavior

We should see those sections too, in the same way it's done on the EIP1559 transactions.

### Screenshots

image

I.e. fee details section

image

### Steps to reproduce

1. Go to the test dapp
2. Trigger a Send Legacy transaction
3. See there is no fees details section

### Error messages or log output

_No response_

### Version

develop - when this get's merged #19960

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Display gas details section for legacy transactions.

## **Related issues**
Fixes: #21140

## **Manual testing steps**

1. Go to test dapp
2. Submit a legacy transaction and check transaction page
3. It should display gas details section

## **Screenshots/Recordings**

Screenshot 2024-01-03 at 4 36 22 PM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by digiwand — COMMENTED** [review]
looks like the existing storybook page is broken. we could fix this here or a follow-up PR. 

Screenshot 2024-01-09 at 12 08 39 PM

---
edit: I've fixed the page on my local machine. is it okay to push the commit into this PR? 
@jpuri

File: ui/components/app/fee-details-component/fee-details-component.js [hunk 1]
```diff
@@ -29,9 +29,8 @@ import { useGasFeeContext } from '../../../contexts/gasFee';
 
 export default function FeeDetailsComponent({
   txData,
-  supportsEIP1559,
   useCurrencyRateCheck,
-  shouldShow = true,
+  hideGasDetails = false,
```
Comment (digiwand) [inline ui/components/app/fee-details-component/fee-details-component.js:33]: is there a reason we are renaming this to `hideGasDetails` instead of `shouldShow` or `showFeeDetails`?

File: ui/components/app/fee-details-component/fee-details-component.js [hunk 2]
```diff
@@ -107,7 +106,7 @@ export default function FeeDetailsComponent({
         justifyContent={JustifyContent.center}
         flexDirection={FlexDirection.Column}
       >
-        {supportsEIP1559 && shouldShow && (
+        {!hideGasDetails && (
```
Comment (digiwand) [inline ui/components/app/fee-details-component/fee-details-component.js:109]: I think we can cleanup the preexisting code related to `hideGasDetails`. 

We can:
- rename `hideGasDetails` → `isHidden`
  this will help devs understand its true use, which is either hide or show everything
- remove checks in template and place this code above line 86 (current `return` line)
  ```
    if (hideGasDetails) {
      return null;
    }
  ```
  
  I don't believe there is a need to show the empty 
  ```
  <Box
        display={Display.Flex}
        alignItems={AlignItems.center}
        justifyContent={JustifyContent.center}
        flexDirection={FlexDirection.Column}
      >
  </>
  ```
  I checked with storybook + background color and there is no visible element in these cases

File: ui/components/app/fee-details-component/fee-details-component.js [hunk 3]
```diff
@@ -29,9 +29,8 @@ import { useGasFeeContext } from '../../../contexts/gasFee';
```
Comment (digiwand) [inline ui/components/app/fee-details-component/fee-details-component.js:29]: [nit][out of scope] 
we can remove the empty tag <></> around the template

File: ui/components/app/fee-details-component/fee-details-component.test.js [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+  addPollingTokenToAppState: jest.fn(),
+}));
+
+const render = (state = {}) => {
+  const store = configureStore()({ ...mockState, ...state });
+  return renderWithProvider(<FeeDetailsComponent />, store);
+};
+
+describe('FeeDetailsComponent', () => {
+  it('should render correctly', () => {
```
Comment (digiwand) [inline ui/components/app/fee-details-component/fee-details-component.test.js:22]:
```suggestion
  it('renders "Fee details"', () => {
```

I've been having to remind myself that the contributor docs have requested us not to prepend tests with "should" too 

ref: https://github.com/MetaMask/contributor-docs/blob/main/docs/unit-testing.md#use-it-to-specify-the-desired-behavior-for-the-code-under-test
> Do not use "should" at the beginning of the test name. The official Jest documentation [omits this word from their examples](https://jestjs.io/docs/next/getting-started), and it creates noise when reviewing the list of tests printed after a run.

this would also apply to the other tests below

File: ui/components/app/fee-details-component/fee-details-component.test.js [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+        networkDetails: {
+          EIPS: {
+            1559: false,
+          },
+        },
+      },
+    });
+    expect(screen.queryByText('Fee details')).toBeInTheDocument();
+  });
+});
```
Comment (digiwand) [inline ui/components/app/fee-details-component/fee-details-component.test.js:48]: we could add coverage, e.g. for `hideGasDetails`

File: ui/components/app/fee-details-component/fee-details-component.js (hunk 3 above)
Comment (jpuri) [reply ui/components/app/fee-details-component/fee-details-component.js:29]: I would avoid changing existing code.

File: ui/components/app/fee-details-component/fee-details-component.js (hunk 2 above)
Comment (jpuri) [reply ui/components/app/fee-details-component/fee-details-component.js:109]: @digiwand : I would avoid putting effort in changing current code executing. Change here is limited in scope to remove `supportsEIP1559` from `if` condition.

File: ui/components/app/fee-details-component/fee-details-component.test.js (hunk 5 above)
Comment (jpuri) [reply ui/components/app/fee-details-component/fee-details-component.test.js:48]: I added test cases to cover changes in this PR which is making gas details visible for legacy transactions. Actually many other scenario are possible but probably out of scope for this bug fix.

File: ui/components/app/fee-details-component/fee-details-component.js (hunk 3 above)
Comment (digiwand) [reply ui/components/app/fee-details-component/fee-details-component.js:29]: ah right, this is a bug not a feature. would be nice to follow up on this

**Review by digiwand — APPROVED** [review]

**Comment by digiwand** [comment]
we can create a follow-up PR to address the other concerns and fix the related storybook page

File: ui/components/app/fee-details-component/fee-details-component.js (hunk 2 above)
Comment (digiwand) [reply ui/components/app/fee-details-component/fee-details-component.js:109]: ok this is fine. agreed we should limit scope with bug changes. I do think the readability of the code can be improved with these changes in a future PR

**Review by segun — APPROVED** [review]
