### PR TITLE
fix(snaps): Catch `handleSnapRequest` error in `SnapInterfaceContext`

### LINKED ISSUE #22286: Error: The method does not exist / is not available.
Sentry Issue: [METAMASK-X7W2](https://metamask.sentry.io/issues/4700356812/?referrer=github_integration)

```
Error: The method does not exist / is not available.
  at new JsonRpcError (node_modules/@metamask/rpc-errors/dist/classes.js:24:1)
  at getJsonRpcError (node_modules/@metamask/rpc-errors/dist/errors.js:176:1)
  at exports.rpcErrors.methodNotFound (node_modules/@metamask/rpc-errors/dist/errors.js:35:1)
  at checkForHttpErrors (node_modules/@metamask/eth-json-rpc-middleware/dist/fetch.js:80:1)
  at <anonymous> (node_modules/@metamask/eth-json-rpc-middleware/dist/fetch.js:47:1)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

Handle errors thrown by `handleSnapRequest` in `SnapInterfaceContext` to avoid unhandled errors caught by Sentry.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34857?quickstart=1)

## **Changelog**

CHANGELOG entry:null

## **Related issues**

Fixes: #22286

## **Manual testing steps**

1. Have a test snap that triggers an error when clicking a button in a home-page
2. Click the button
3. Look at the UI console to ensure the good error is thrown

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/contexts/snaps/snap-interface.tsx [hunk 1]
```diff
@@ -111,7 +111,14 @@ export const SnapInterfaceContextProvider: FunctionComponent<
           id: interfaceId,
         },
       },
-    }).then(() => forceUpdateMetamaskState(dispatch));
+    })
+      .then(() => forceUpdateMetamaskState(dispatch))
+      .catch((error) => {
+        console.error(
+          `Failed to handle snap request for event "${event}" with name "${name}":`,
```
Comment (FrederikBolding) [inline ui/contexts/snaps/snap-interface.tsx]:
```suggestion
          `Failed to handle Snap request for event "${event}" with name "${name}":`,
```

Comment (Mrtenz) [inline ui/contexts/snaps/snap-interface.tsx]:
```suggestion
          `Failed to handle Snap request to "${snapId}" for event "${event}" with name "${name}":`,
```

File: ui/contexts/snaps/snap-interface.tsx
Comment (FrederikBolding) [inline ui/contexts/snaps/snap-interface.tsx:1]: We should port this change to mobile too

File: ui/contexts/snaps/snap-interface.tsx (hunk 1 above)
Comment (Mrtenz) [reply ui/contexts/snaps/snap-interface.tsx]: Wondering if it's safe to log `event`, since it may contain secrets?

**Review by FrederikBolding — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]

File: ui/contexts/snaps/snap-interface.tsx (hunk 1 above)
Comment (FrederikBolding) [reply ui/contexts/snaps/snap-interface.tsx]: We're just logging the event enum type
