### PR TITLE
fix: fix fiat values in testnet visibility

### LINKED ISSUE #24945: [Bug]: Fiat values continue to show despite "Show conversion on test networks" (Advanced Settings) being disabled
### Describe the bug

Fiat values continue to show despite "Show conversion on test networks" (Advanced Settings) being disabled

Discovered in https://github.com/MetaMask/metamask-extension/pull/24854#issuecomment-2136464701

### Expected behavior

Fiat conversion values should not show on test networks when  "Show conversion on test networks" (Advanced Settings) being disabled

### Screenshots/Recordings

334642377-bd2eec03-02da-4f56-a2b0-5a3f39abbef9

### Steps to reproduce

1. Turn off "Show conversion on test networks" setting in Advanced Settings
2. Use L2 test network
3. Go to test dapp
4. Click on "Create a token"
5. Observe fiat value is shown

### Error messages or log output

_No response_

### Version

11.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR goal is to fix visibility issue of viat values in testnet. For more info please visit task here https://github.com/MetaMask/metamask-extension/issues/24945

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26273?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Turn off "Show conversion on test networks" setting in Advanced Settings
2. Use L2 test network (Arbitrum Sepolia could be added from here https://chainlist.org/chain/421614)
3. Go to test dapp
4. Click on "Create a token"
5. Observe fiat value is hidden (it was shown before)

### **Before**

Screenshot 2024-08-01 at 11 43 58

### **After**

Screenshot 2024-08-01 at 11 44 05

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm-subtitle/confirm-subtitle.js [hunk 1]
```diff
@@ -1,28 +1,31 @@
...
   txData,
   hexTransactionAmount,
   subtitleComponent,
   assetStandard,
 }) => {
-  const shouldShowFiat = useSelector(getShouldShowFiat);
   const { isNftTransfer } = useTransactionInfo(txData);
+  const hideFiatForTestNet = useHideFiatForTestnet();
 
-  if (!shouldShowFiat && !isNftTransfer && !isNFTAssetStandard(assetStandard)) {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm-subtitle/confirm-subtitle.js:25]: Do we not want to still check that fiat is enabled at all? Otherwise we will always show fiat if not on a testnet?

Also, if we've updated the `getShouldShowFiat` to check testnets, could we leave this code unchanged?

File: ui/pages/confirmations/components/confirm-subtitle/confirm-subtitle.test.js [hunk 2]
```diff
@@ -6,6 +6,7 @@ import { renderWithProvider } from '../../../../../test/lib/render-helpers';
 import configureStore from '../../../../store/store';
 import { getSelectedInternalAccountFromMockState } from '../../../../../test/jest/mocks';
 import ConfirmSubTitle from './confirm-subtitle';
+// import { CHAIN_IDS } from '../../../../../shared/constants/network';
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm-subtitle/confirm-subtitle.test.js:9]: Debugging? Can we remove this?

File: ui/pages/confirmations/components/fee-details-component/fee-details-component.js [hunk 3]
```diff
@@ -50,20 +52,22 @@ export default function FeeDetailsComponent({
...
-              color: TextColor.textAlternative,
-              variant: TextVariant.bodySmBold,
-            }}
-            textProps={{
-              color: TextColor.textAlternative,
-              variant: TextVariant.bodySmBold,
-            }}
-            hideLabel={Boolean(useNativeCurrencyAsPrimaryCurrency)}
-          />
+          {!hideFiatForTestNet && (
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/fee-details-component/fee-details-component.js:55]: Same here, can we just use the updated selector?

File: ui/selectors/selectors.js [hunk 4]
```diff
@@ -950,17 +951,17 @@ export function getDisabledRpcMethodPreferences(state) {
...
 
 export function getShouldShowFiat(state) {
-  const isMainNet = getIsMainnet(state);
-  const isLineaMainNet = getIsLineaMainnet(state);
-  const isCustomNetwork = getIsCustomNetwork(state);
+  const currentChainId = getCurrentChainId(state);
+  const isTestnet = TEST_NETWORK_IDS.includes(currentChainId);
+  const { showFiatInTestnets } = getPreferences(state);
+
+  if (isTestnet && !showFiatInTestnets) {
```
Comment (matthewwalsh0) [inline ui/selectors/selectors.js:958]: If we check this in the selector, can we remove the `useHideFiatForTestnet` hook entirely?

File: ui/selectors/selectors.js [hunk 5]
```diff
@@ -950,17 +951,17 @@ export function getDisabledRpcMethodPreferences(state) {
 }
 
 export function getShouldShowFiat(state) {
-  const isMainNet = getIsMainnet(state);
-  const isLineaMainNet = getIsLineaMainnet(state);
-  const isCustomNetwork = getIsCustomNetwork(state);
+  const currentChainId = getCurrentChainId(state);
```
Comment (matthewwalsh0) [inline ui/selectors/selectors.js:954]: Perhaps a future enhancement is to support a chain ID argument so we're less coupled to the global network?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/components/fee-details-component/fee-details-component.js [hunk 6]
```diff
@@ -168,18 +173,15 @@ export default function FeeDetailsComponent({
                   {t('layer1Fees')}
                 </Text>
               }
-              detailText={
-                useCurrencyRateCheck && renderTotalDetailText(layer1GasFee)
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/fee-details-component/fee-details-component.js:172]: `useCurrencyRateCheck` is already checked in `getShouldShowFiat` selector hence am removing this.

File: ui/selectors/selectors.js (hunk 5 above)
Comment (OGPoyraz) [reply ui/selectors/selectors.js:966]: That's right, better be handled standalone PR since it will require lot of prop drilling and test file changes.

File: test/e2e/tests/settings/localization.spec.js
Comment (OGPoyraz) [inline test/e2e/tests/settings/localization.spec.js:1]: This removed for the exact same reason here https://github.com/MetaMask/metamask-extension/pull/26273#discussion_r1742060883

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
