### PR TITLE
fix: updated add network icon in networks modal

### LINKED ISSUE #38822: [Bug]: Adding network from network picker and networks in hamburger menu is different
**Describe the bug**

Network picker and hamburger menu network views are different. Particularly `Add` vs `+`

**Expected behavior**

Should be aligned to `+`

**Screenshots/Recordings**

https://github.com/user-attachments/assets/93f56f35-b52d-4bdb-a1f1-93f61a291acb

**Steps to reproduce**

See video

**Error messages or log output**

```shell

```

**Where was this bug found?**

Live version (from official store)

**Version**

13.13

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR ensures that for both Network picker and hamburger menu network, add network icon is same

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39096?quickstart=1)

## **Changelog**

CHANGELOG entry: Updated add button to + icon

## **Related issues**

Fixes: #38822

## **Manual testing steps**

1. Check the + icon in networks modal for portfolio view and global menu

### **After**

https://github.com/user-attachments/assets/38eeca16-0017-46e8-a06a-332c7b4b7111

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Aligns the networks modal with the design-system iconography and updates tests accordingly.
> 
> - In `popular-network-list.tsx`, replace `Button` label "Add" with `ButtonIcon` (`IconName.Add`) and switch the info indicator to design-system `Icon` with muted color
> - Adjust DOM structure/aria for the add button; update Jest snapshots to reflect icon-only buttons and new info icon markup
> - E2E: update selector in `SelectNetwork` to target the nested icon `button`; change test to add Avalanche (`0xa86a`) via the popular networks list
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 247d426e30078f18056eda5be4363e563fdc2741. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by n3ps — DISMISSED** [review]
I think we'd want to follow this up with refactoring such that there's one consistent network picker modal

**Review by ameliejyc — DISMISSED** [review]

**Review by ameliejyc — DISMISSED** [review]

File: test/e2e/page-objects/pages/dialog/select-network.ts [hunk 1]
```diff
@@ -99,13 +99,9 @@ class SelectNetwork {
...
     console.log('Click Add Button for Popular Network');
-    await this.driver.clickElementAndWaitToDisappear({
-      text: 'Add',
-      css: `[data-testid="test-add-button"]`,
-      parent: {
-        css: `[data-testid="popular-network-${chainId}"]`,
-      },
-    });
+    await this.driver.clickElementAndWaitToDisappear(
+      `[data-testid="popular-network-${chainId}"] [data-testid="test-add-button"]`,
```
Comment (seaona) [inline test/e2e/page-objects/pages/dialog/select-network.ts]: small nit: instead of hardcoding the selector here, could we move the selector on top with the rest, and here just reference it?

Something like this:

```
private readonly addPopularNetworkByChainIdIcon = (chainId: string) => (
`[data-testid="popular-network-${chainId}"] [data-testid="test-add-button"]`
);

```
(whichever name you think it's appropiate)

**Review by n3ps — DISMISSED** [review]

File: test/e2e/page-objects/pages/dialog/select-network.ts (hunk 1 above)
Comment (NidhiKJha) [reply test/e2e/page-objects/pages/dialog/select-network.ts]: Updated here https://github.com/MetaMask/metamask-extension/pull/39096/commits/247d426e30078f18056eda5be4363e563fdc2741

**Review by seaona — APPROVED** [review]
QA changes LGTM

**Review by n3ps — APPROVED** [review]
