### PR TITLE
fix: hackily wait longer for linea swap approval tx to increase chance of success

### LINKED ISSUE #27804: [Bug]: Swap of unapproved token fails on Linea
### Describe the bug

When swapping any unapproved token on Linea, only the approval transaction succeeds. However the actual swap transaction - that happens after that - fails. I tried to submit the same swap a second time, and since the approval is already there the transaction goes through. So the user can somehow still recover, but we might lose the transaction if the user doesn’t retry.

I checked and this is also in production
I checked on Mainnet and doesn't happen

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/343ab5ee-1bcb-45cb-9d42-c753b80c1fea

### Steps to reproduce

1. Change Network to Linea
2. Swap ETH to unapproved token
3. Swap unapproved token to any token
4. Notice that the transaction fails

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by martahj**
## **Description**

Linea seems to be taking longer than other chains to process the approve transaction after it is submitted, so the trade transaction is erroring. This PR adds a hacky workaround where we artificially delay if we're on Linea to give the trade transaction more time. In the future, we'd want to avoid this hack, but for now it should increase the swap success rate on Linea.

With the delay, the token symbol also wasn't immediately populating on the awaiting swap page, so this PR also updates how it's retrieved.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27810?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27804

## **Manual testing steps**

1. Start a swap on Linea with a token that you have not granted approval for
2. Observe that the swap does not fail

### **Before**

https://github.com/user-attachments/assets/57cdc5e5-cea7-48ad-ba13-38820ecc9155

### **After**

https://github.com/user-attachments/assets/91bbfbf4-8392-41ea-bfe8-d54813758f5c

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/swaps/awaiting-swap/awaiting-swap.js [hunk 1]
```diff
@@ -107,7 +110,7 @@ export default function AwaitingSwap({
       currentCurrency,
       conversionRate: usdConversionRate,
       tradeValue: usedQuote?.trade?.value,
-      sourceSymbol: swapMetaData?.token_from,
+      sourceSymbol: usedQuote?.sourceTokenInfo?.symbol,
```
Comment (jclancy93) [inline ui/pages/swaps/awaiting-swap/awaiting-swap.js:113]: Why did we switch out swapMetadata here and in a few other places?

**Review by jclancy93 — APPROVED** [review]

**Review by infiniteflower — APPROVED** [review]
