### PR TITLE
Add rounding to large exponential numbers. Fix overflows

### LINKED ISSUE #4886: Wrong token balance on Approve screen
screen shot 2018-07-25 at 4 47 42 pm

only seeing on `Approve` function calls so far, haven't seen it elsewhere. airswap or etherdelta both work for testing if you try to swap / deposit a token. @alextsg

### PR DESCRIPTION
**Pull request by alextsg**
Fixes #4886

<details>
<summary>Screenshot</summary>

</details>

### CODE REVIEW

**Comment by danjm** [comment]
Maybe we should show more precise values in the "Total" row, where there is more space?

File: ui/app/selectors/confirm-transaction.js [hunk 1]
```diff
@@ -133,7 +134,8 @@ export const tokenAmountAndToAddressSelector = createSelector(
       const toParam = params.find(param => param.name === TOKEN_PARAM_TO)
       const valueParam = params.find(param => param.name === TOKEN_PARAM_VALUE)
       toAddress = toParam ? toParam.value : params[0].value
-      tokenAmount = valueParam ? Number(valueParam.value) : Number(params[1].value)
+      const value = valueParam ? Number(valueParam.value) : Number(params[1].value)
+      tokenAmount = roundExponential(value)
```
Comment (danjm) [inline ui/app/selectors/confirm-transaction.js]: `roundExponential` seems out of place in selectors. It is an operation done just to modify the way the value is presented in the view. The calls of `roundExponential` in `confirm-token-transaction-base.component.js` seem to be in the right place.

I like the idea of keeping selectors (as much as possible) focused on "selecting": getting the needed data out of state. And then doing manipulation or transformation on data elsewhere.

Alternatively, I could easily be convinced to do it this way: treat selectors methods that are meant to both get data from state AND transform it to exactly what is needed by the view. In this scenario, there would be no operations on data in components. A component might decide which of two variables to render, but would render the variable as it was received.

So, as long we consistently do it one way or the other, I am good.

Now, what I've described above is likely inconsistent with a good chunk of the codebase. If the code in this PR can easily be refactored to the above changes, then we can do it now. Otherwise, if it is more complicated, we can merge this PR as is and make an issue for a larger refactor along these lines.

File: ui/app/helpers/confirm-transaction/util.js [hunk 2]
```diff
@@ -137,3 +138,11 @@ export function convertTokenToFiat ({
 export function hasUnconfirmedTransactions (state) {
   return unconfirmedTransactionsCountSelector(state) > 0
 }
+
+export function roundExponential (value) {
+  const PRECISION = 4
+  const valueBN = new BigNumber(value)
```
Comment (danjm) [inline ui/app/helpers/confirm-transaction/util.js]: nit: can `valueBN` be renamed so that it's clear it is not a `BN.js` object (which is used much more in the old-ui but behaves differently, especially with respect to decimals)

File: ui/app/helpers/confirm-transaction/util.js [hunk 3]
```diff
@@ -137,3 +138,11 @@ export function convertTokenToFiat ({
...
+
+  // In JS, numbers with exponentials greater than 20 get displayed as an exponential.
+  return valueBN.e > 20 ? Number(valueBN.toPrecision(PRECISION)) : value
```
Comment (danjm) [inline ui/app/helpers/confirm-transaction/util.js]: If `valueBN.e` is less than twenty, but great than (for instance) 16, will we still run into overflow issues? Has rounding been properly handled elsewhere for all cases where `valueBN.e < 20`?

**Comment by danjm** [comment]
_This is a non-blocking comment about a possible future improvement to a problem that is not caused by this PR. Just making it here because reviewing this made me think about it. FEEL FREE TO READ AND CONSIDER AFTER YOU MERGE._

We are going to forever have issues with needing to render numbers in different ways in different places.

It would be nice if we could make these transformations - of data from some value of cryptocurrency to some nicely formatted string for rendering - simpler, DRYer and less error prone.

For instance, after this PR we have:

```
      const fiatTransactionAmount = this.getFiatTransactionAmount()
      const roundedFiatTransactionAmount = roundExponential(fiatTransactionAmount)
      return formatCurrency(roundedFiatTransactionAmount, currentCurrency)
```
The three functions called here require 4 inputs: `tokenAmount, currentCurrency, conversionRate, contractExchangeRate`. `this.getFiatTransactionAmount()` passes these for inputs to a util which in turn calls the conversion util, which in turn calls a series of operations on a Bignumber. `roundExponential` the does some operations with Bignumber, conditional on the passed values size, and `currencyFormatter` with some other library. In the same component we have to do the same three function calls plus a function call to do some addition, which uses a util which uses the conversion util...

I guess it would be nice if we could get the desired result by passing the four params to one utility method (or maybe a component). And that utility be something that can be used everywhere we need to render currencies.

I suppose that was what I was aiming for with the conversion-util. However, apart from the issue of the code being obscure and inaccessible, it also seems that we still need a separation of concerns between operations on values for the sake of getting a correct value and operations on values for the sake of getting a string to be rendered in a desired format.

So probably some combination of an improvement of the conversion-util and then creating a new generalized utility, or maybe component, for the sake of correct rendering.

I think when we aim to make this improvement, we should aim to create an API that would be desirable and easily used by other developers. We should even think beyond the Metamask project... this is an issues that all sorts of wallet and dapps will face. So, before we begin designing the solution, we should probably research other open source projects that have to solve this issue in their UIs and see what there solution is.

**Review by danjm — CHANGES_REQUESTED** [review]
Made a number of comments, but only a couple small ones NEED to be fixed before I will approve (which these are should be clear by the comments).

**Comment by Maayu2415** [comment]
Please tell him to teach me about working .Adam Ho your langage
I understand because how to taķe
As same as my country.
.


ในวันที่ ศ. 27 ก.ค. 2018 21:58 Dan J Miller <notifications@github.com>
เขียนว่า:

File: ui/app/helpers/confirm-transaction/util.js (hunk 3 above)
Comment (alextsg) [reply ui/app/helpers/confirm-transaction/util.js]: If `valueBN.e < 20`, the number isn't represented as a decimal so I don't think rounding is appropriate, since you have the exact number of tokens being sent. The purpose of this check is to round only when the number is being represented as an exponential.

**Comment by alextsg** [comment]
@danjm I think having the number in the Total row being more precise would be confusing, since it looks like more is being transferred in Total. It would look inconsistent.

File: ui/app/selectors/confirm-transaction.js (hunk 1 above)
Comment (alextsg) [reply ui/app/selectors/confirm-transaction.js]: That can be a good approach. I've been thinking of selectors as methods to get usable data from state, ie your alternate proposal. I don't think it's bad practice to modify data within selectors, as seen [here](https://github.com/reduxjs/reselect#api) in the `reselect` library docs, since it could lead to less duplication if you're always doing the same transformation wherever the selector is used.

File: ui/app/helpers/confirm-transaction/util.js (hunk 2 above)
Comment (whymarrh) [reply ui/app/helpers/confirm-transaction/util.js]: > so that it's clear it is not a `BN.js` object

It's not?

**Comment by Maayu2415** [comment]
What happen?

ส่งจากสมาร์ทโฟน Samsung Galaxy ของฉัน
-------- ข้อความดั้งเดิม --------จาก: Whymarrh Whitby <notifications@github.com> วัน​ที่: 28/7/18  00:35  (GMT+07:00) ถึง: MetaMask/metamask-extension <metamask-extension@noreply.github.com> Cc: mjaniam2415@gmail.com, Comment <comment@noreply.github.com> เรื่อง: Re: [MetaMask/metamask-extension] Add rounding to large exponential numbers. Fix overflows (#4895) 
@whymarrh commented on this pull request.



In ui/app/helpers/confirm-transaction/util.js:
> @@ -137,3 +138,11 @@ export function convertTokenToFiat ({
 export function hasUnconfirmedTransactions (state) {
   return unconfirmedTransactionsCountSelector(state) > 0
 }
+
+export function roundExponential (value) {
+  const PRECISION = 4
+  const valueBN = new BigNumber(value)


so that it's clear it is not a BN.js object

It's not?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/metamask-extension","title":"MetaMask/metamask-extension","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/metamask-extension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whymarrh commented on #4895"}],"action":{"name":"View Pull Request","url":"https://github.com/MetaMask/metamask-extension/pull/4895#discussion_r205847442"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MetaMask/metamask-extension/pull/4895#discussion_r205847442",
"url": "https://github.com/MetaMask/metamask-extension/pull/4895#discussion_r205847442",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "@whymarrh commented on 4895",
"sections": [
{
"text": "",
"activityTitle": "**Whymarrh Whitby**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@whymarrh",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MetaMask/metamask-extension/pull/4895#discussion_r205847442"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361342167\n}"
}
],
"themeColor": "26292E"
}
]

File: ui/app/helpers/confirm-transaction/util.js (hunk 2 above)
Comment (danjm) [reply ui/app/helpers/confirm-transaction/util.js]: > It's not?

I suppose my issue with this is that, at least in the old-ui, and probably in some utilities still in the new ui, there are bunch of variables with `BN` in their name to indicate it is a `BN.js` object. So, for instance, if I was to grep for all BNs, this would have been confusing. Or, at least, reading this code and then reading. Maybe that is a minor concern, and I'd just like us to not pollute something of a convention in the codebase (e.g. see metamask-extension/ui/app/util.js)

But you are right that reading these few lines of code it should be clear.

File: ui/app/helpers/confirm-transaction/util.js (hunk 3 above)
Comment (danjm) [reply ui/app/helpers/confirm-transaction/util.js]: So what do you do with the overflow?

**Review by danjm — APPROVED** [review]

File: ui/app/helpers/confirm-transaction/util.js (hunk 2 above)
Comment (whymarrh) [reply ui/app/helpers/confirm-transaction/util.js]: `BN.js` being different from `BigNumber`?

**Comment by nandubatchu** [comment]
@alextsg for a test token with precision 18, while the balance was 30,000.000000011117116443 tokens, I tried to send max token balance to another account. When I click 'max' button, the value is rounded up to 30000.000000011118 tokens. This is not noticed by people. The transactions are failing with bad-instruction or no-event errors. Is this relevant to your commits?

**Comment by alextsg** [comment]
@nandubatchu Thanks for catching that. I'll create an issue for this.
