### PR TITLE
Ensure one and only one localhost option appears in network list

### LINKED ISSUE #12754: Two localhost:8545 in MetaMask 10.6.0, second does not work
There are now two `Localhost 8545` with MetaMask 10.6.0.  The first is selectable, the last is not.  

image

### PR DESCRIPTION
**Pull request by danjm**
Fixes: #12754

That issue applies to people who had MetaMask installed prior to v10.6.0

It fixes another issue with the localhost option in the network dropdown on v10.6.0: upon freshly installing MetaMask, and then switching on the display of test nets, the localhost option does not work

https://github.com/MetaMask/metamask-extension/pull/12260 removed localhost from the `first-time-state` `frequentRpcListDetail`, and also used `renderNetworkEntry` in `network-dropdown` to render it in the network list. `renderNetworkEntry` is meant for use with test networks, but we add localhost as a custom rpc. This change was likely made to ensure that localhost only appears once in the network dropdown and that it is at the bottom of the network list (in accordance with designs).

This PR corrects that by re-adding localhost to first-time-state, and using the correct render method for localhost in `network-dropdown`

With this PR, localhost is behaving correctly in the the network dropdown list.

### CODE REVIEW

**Review by segun — DISMISSED** [review]
LGTM!

File: ui/components/app/dropdowns/network-dropdown.js [hunk 1]
```diff
@@ -149,14 +152,22 @@ class NetworkDropdown extends Component {
...
       const { rpcUrl, chainId, ticker = 'ETH', nickname = '' } = entry;
       const isCurrentRpcTarget =
         provider.type === NETWORK_TYPE_RPC && rpcUrl === provider.rpcUrl;
 
+      let borderColor = COLORS.UI2;
+      if (isCurrentRpcTarget) {
+        borderColor = COLORS.WHITE;
+      }
+      if (opts.isLocalHost) {
+        borderColor = 'localhost';
```
Comment (adonesky1) [inline ui/components/app/dropdowns/network-dropdown.js:168]: [nit] non-blocking question. Should we use a different color for `$localhost`? Its the same as mainnet.

**Review by adonesky1 — DISMISSED** [review]
LGTM!

**Review by segun — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
