### PR TITLE
fix(webpack): align manifest transform behavior

### LINKED ISSUE #41097: [Bug]: Upgrade from RC to Webpack version launches fresh extension instead of migrating existing data
### Describe the bug

When upgrading from the RC version to the Webpack version, a new extension instance is launched that behaves like a fresh installation. Existing user data, settings, and state are not retained.

### Expected behavior

The extension should retain existing user data and settings, seamlessly migrating state from the RC version.

### Screenshots/Recordings

https://github.com/user-attachments/assets/e7047e7a-1a7a-4c5c-8f07-719ab4b27344

### Steps to reproduce

1. Install and set up the RC version of the extension.
2. Configure accounts, settings, and data.
3. Upgrade to the Webpack version of the extension.
4. Launch the updated extension.

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.24.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by davidmurdoch**
## **Description**

Refactor some manifest transforms so that the prerelease build key for chrome builds is correct.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: #41097, #41089

## **Manual testing steps**

1. install an actual release candidate build from a release channel, then onboard.
2. run `yarn webpack --env release-candidate` on this branch
3. install this `webpack` build into the same browser that contains the release-candidate build from step 1. It should automatically replace the release-candidate build from step 1, instead of adding another MetaMask extension installation.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> <sup>[Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) is generating a summary for commit 51d6397485ef2c55a72db01a1cd511296a52d21a. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: development/webpack/utils/plugins/ManifestPlugin/helpers.ts [hunk 1]
```diff
@@ -1,37 +1,101 @@
...
+    browserManifest: chrome.runtime.Manifest,
+    browser: Browser,
+  ) {
+    if (browser === 'firefox') {
+      // firefox uses a different key generation method and does not need this
+      // fixed Chrome manifest key.
+      return;
+    }
+
+    browserManifest.key = manifestKey;
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply development/webpack/utils/plugins/ManifestPlugin/helpers.ts]: I think this was a mistake in the old way of doing it. Or maybe it was a way of handling the fact that `addManifestFlags` used to run first (now it doesn't).

The browserify build didn't check this condition before just overwriting the property. Also, the `manifestKey` at this point is always defined, since the transform is only added if the `manifestKey` is truthy.

File: development/webpack/test/webpack.config.test.ts [hunk 2]
```diff
@@ -180,6 +180,9 @@ ${Object.entries(env)
       [
         '--mode',
         'production',
+        '--env',
+        'production',
+        '--no-validateEnv',
```
Comment (davidmurdoch) [inline development/webpack/test/webpack.config.test.ts:185]: this test checks that `transform` is undefined, and the only way is to set `--env production`. and since env is prod now, it wants to validate the env, so I had to turn that off too.

File: development/webpack/utils/plugins/ManifestPlugin/helpers.ts [hunk 3]
```diff
@@ -1,39 +1,103 @@
...
+ * release-candidate manifest key, otherwise sets the default non-production
+ * manifest key.
+ * - If `isDevelopment` is `true`, merges manifest override flags from the file
+ * specified by `MANIFEST_OVERRIDES`
+ * - If `test` is `true`, adds the "tabs" permission to the manifest
  *
  * @param args
+ * @param args.env
  * @param args.test
- * @param args.manifest_version
```
Comment (davidmurdoch) [inline development/webpack/utils/plugins/ManifestPlugin/helpers.ts:13]: this isn't used anymore, since we just check the `browser`

File: development/webpack/utils/constants.ts [hunk 4]
```diff
@@ -16,6 +16,15 @@ export const ENVIRONMENTS = {
   TESTING: 'testing',
 } as const;
 
+// Manifest key used for non-production Chrome builds to keep a stable
+// extension ID for OAuth flows.
+export const CHROME_MANIFEST_KEY_NON_PRODUCTION =
```
Comment (davidmurdoch) [inline development/webpack/utils/constants.ts:21]: these were copied from the other build system.

File: development/webpack/utils/plugins/ManifestPlugin/helpers.ts [hunk 5]
```diff
@@ -87,20 +151,10 @@ export function transformManifest(
     transforms.push(addTabsPermission);
   }
 
-  function addManifestKey(browserManifest: chrome.runtime.Manifest) {
-    if (!browserManifest.key) {
```
Comment (davidmurdoch) [inline development/webpack/utils/plugins/ManifestPlugin/helpers.ts:91]: this check was removed because we now add the key before the manifestOverrides, so the manifestOverrides are free to override it.

File: development/webpack/utils/plugins/ManifestPlugin/helpers.ts [hunk 6]
```diff
@@ -87,20 +151,10 @@ export function transformManifest(
...
-      browserManifest.key = MANIFEST_DEV_KEY;
-    }
-  }
-
-  if (isDevelopment || args.test) {
```
Comment (davidmurdoch) [inline development/webpack/utils/plugins/ManifestPlugin/helpers.ts:96]: this is the real bug. this should have been just a prod check.

**Review by itsyoboieltr — APPROVED** [review]

**Review by lwin-kyaw — APPROVED** [review]
