### PR TITLE
fix: Address  NameDisplay component to show full address display name

### LINKED ISSUE #34105: [Bug]: When the contract name a user is interacting with is too long to fit within the contract name pill, the full name is not visible anywhere on the Confirmation screen.
### Describe the bug

When the contract name a user is interacting with is too long to fit within the contract name pill, the full name is not visible anywhere on the Confirmation screen.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/644c5cae-e668-4e3f-a8fb-0ce26e9df60e

Image

### Steps to reproduce

1. Submit swap / bridge
2. Try to see full contract name on the Confirmation screen

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.23.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by AugmentedMode**
## **Description**

This PR fixes a bug where within the address NameDisplay modal we were not showing the full address petname / trust signal name. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34188?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**
Screenshot 2025-07-09 at 10 49 40 PM
Screenshot 2025-07-10 at 11 14 44 AM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by cryptotavares — CHANGES_REQUESTED** [review]
This change will break the UI if the name is too long.. We will always need to eventually display a formatted name. I feel that the solution be a hybrid one where we can extend the the MAX_PET_NAME_LENGTH depending on where we are rendering the petname and having a tooltip for when the petname is truncated. We probably want to loop design here.

**Review by mindofmar — APPROVED** [review]

File: ui/components/app/name/name-details/name-details.tsx [hunk 1]
```diff
@@ -383,7 +383,12 @@ export default function NameDetails({
             <div
               style={{ textAlign: 'center', marginBottom: 16, marginTop: 8 }}
             >
-              <NameDisplay value={value} type={type} variation={variation} />
+              <NameDisplay
+                value={value}
+                type={type}
+                variation={variation}
+                showFullName
```
Comment (cryptotavares) [inline ui/components/app/name/name-details/name-details.tsx:390]: [nit]: this is more personal than anything but I feel that being explicit on the props value increases readability. So my suggestion is to use `showFullName={true}` instead of just `showFullName`.

**Review by cryptotavares — APPROVED** [review]
Approved! As we have discussed, this PR will be followed up with another one to handle the tooltip avenue. 
(Also left a minor nit)
