### PR TITLE
fix: mv2 firefox csp header

### LINKED ISSUE #3133: Inpage injection fails in Firefox under some CSP settings
Hey, as far as I can tell, my content security policy is preventing MetaMask from injecting its scripts. This is only happening in Firefox. It works correctly in Chrome, Safari, Opera, and Brave. My `script-src` directive looks like this:
```
script-src 'self';
```
and I'm seeing this csp violation in the js console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at self. Source: (function e(t,n,r){function s(o,u){if(!n ....
```

Unfortunately Firefox only shows a preview of the blocked script. I've tried sha256 hashing each of the scripts in the latest Metamask release and adding them to the CSP, but that did not work. If you have any ideas that would be great!

<b>Browser:</b> Firefox 58.0.1
<b>Operating System:</b> Mac OSX 10.13.2

### PR DESCRIPTION
**Pull request by itsyoboieltr**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27770?quickstart=1)

This PR implements a workaround for a long-standing Firefox MV2 bug where the content-security-policy header is not bypassed, triggering an error.

The solution is simple: we check if the extension is MV2 running in Firefox. If yes, we override the header to prevent the error from raising.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/3133, https://github.com/MetaMask/MetaMask-planning/issues/3342

## **Manual testing steps**

1. Opening github.com should not trigger the CSP error

### **Before**

csp-toggle-off

reprod

### **After**

csp-toggle-on

fixed

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/background.js [hunk 1]
```diff
@@ -327,6 +327,24 @@ function maybeDetectPhishing(theController) {
...
 
+/**
+ * Overrides the Content-Security-Policy Header, acting as a workaround for an MV2 Firefox Bug.
+ */
+function overrideContentSecurityPolicyHeader() {
+  browser.webRequest.onHeadersReceived.addListener(
+    ({ responseHeaders }) => {
+      for (const header of responseHeaders) {
+        if (header.name.toLowerCase() === 'content-security-policy') {
+          header.value = '';
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/background.js:338]: I think we'll want to "surgically" allow our by adding our inpage.js's integrity hash to it.

File: app/scripts/background.js [hunk 2]
```diff
@@ -327,6 +327,27 @@ function maybeDetectPhishing(theController) {
...
+/**
+ * Overrides the Content-Security-Policy Header, acting as a workaround for an MV2 Firefox Bug.
+ */
+function overrideContentSecurityPolicyHeader() {
+  browser.webRequest.onHeadersReceived.addListener(
+    ({ responseHeaders }) => {
+      for (const header of responseHeaders) {
+        if (header.name.toLowerCase() === 'content-security-policy') {
+          header.value = header.value.replace(
+            /(^|;\s*)script-src([^;]*)/u,
```
Comment (davidmurdoch) [inline app/scripts/background.js:339]: `\s` matches too many characters. it should be limited to `\t\n\f\r `.

Additionally, "script-src" matching should be case-insensitive while maintaining the original directive name's case in the finally output (incase the dapp's own JavaScript depends on the casing)

Comment (davidmurdoch) [reply app/scripts/background.js:339]: I also worry about the backtracking in this regular expression.

File: app/scripts/background.js [hunk 3]
```diff
@@ -327,6 +327,27 @@ function maybeDetectPhishing(theController) {
...
+            (match) => `${match} 'nonce-${btoa(browser.runtime.getURL('/'))}'`,
+          );
+        }
+      }
+      return { responseHeaders };
+    },
+    { urls: ['http://*/*', 'https://*/*'] },
+    ['blocking', 'responseHeaders'],
```
Comment (davidmurdoch) [inline app/scripts/background.js:347]: We probably want to limit the matching to: `types: ['main_frame', 'sub_frame'],`. Can you think of any reasons we'd want to match any and all requests?

Comment (davidmurdoch) [reply app/scripts/background.js:348]: You should use `urls` and `types`.

File: app/scripts/background.js [hunk 4]
```diff
@@ -473,6 +495,10 @@ async function initialize() {
 
     if (!isManifestV3) {
       await loadPhishingWarningPage();
+      const { name } = await browser.runtime.getBrowserInfo();
```
Comment (davidmurdoch) [inline app/scripts/background.js:498]: According to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo, chrome doesn't support `runtime.getBrowserInfo`, so you'll probably need to find another way to get this information. You might want to look into using `appStateController.store.getState().browserEnvironment.browser`

File: shared/modules/add-nonce-to-csp.ts [hunk 5]
```diff
@@ -0,0 +1,13 @@
+/**
+ * Adds a nonce value to the script-src directive of the Content-Security-Policy Header.
+ *
+ * @param header - the Content-Security-Policy Header
+ * @param nonce - the nonce value to add
+ * @returns the Content-Security-Policy Header with the nonce value added
+ */
+export const addNonceToCsp = (header: string, nonce: string) => {
+  return header.replace(
+    /(^|;[\t\n\f\r ]*)script-src([^;]*)/iu,
```
Comment (davidmurdoch) [inline shared/modules/add-nonce-to-csp.ts:10]: What would happen if the entire policy is just `default-src 'none'`, or something equally restrictive? I _think_ we'd still be blocked in that case, as `default-src` is a fallback for absent directives. We might need to add some more logic here.

---

We _might_ need to expand on this even further by expanding/adding directives to allow for `img-src data:;` in order for our provider's `icon` to be allowed. Wallet connectors can use this icon when providing the user with their connection options.

Example of the icon in use from [our test-dapp](https://metamask.github.io/test-dapp/):

image

I haven't tested if this CSP policy is broken in FF or not. Actually, I haven't tested if this is already broken in Chrome either!

Comment (davidmurdoch) [reply shared/modules/add-nonce-to-csp.ts:10]: Note: I still worry about potential regex backtracking and self-inflicted DoS.

File: shared/modules/content-security-policy.ts [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+        .replace(ASCII_WHITESPACE_AT_END, '');
+
+      // If strippedToken is an empty string, or if strippedToken is not an ASCII string, continue.
+      if (!strippedToken || !ASCII.test(strippedToken)) continue;
+
+      // Directive name is the result of collecting a sequence of code points from token which are not ASCII whitespace.
+      // Directive values are the result of splitting token on ASCII whitespace.
+      const [name, ...values] = strippedToken.split(ASCII_WHITESPACE);
+
+      contentSecurityPolicy[name] = values;
```
Comment (davidmurdoch) [inline shared/modules/content-security-policy.ts:46]: If a server sends a directive name like `__proto__` in their CSP header this will break.

Additionally, if the CSP directive has duplicate directives (e.g., `script-src` appears twice), this will only keep the _second_ one. We want to keep all directives (and keep them in order).

I think an Array might your best bet here, something like `type Directive: {name: string, values: string[] }[]`.

File: app/scripts/background.js [hunk 7]
```diff
@@ -331,6 +332,34 @@ function maybeDetectPhishing(theController) {
...
+          const contentSecurityPolicy = CSP.parse(header.value);
+          const nonce = `'nonce-${btoa(browser.runtime.getURL('/'))}'`;
+          const scriptSrc = Object.keys(contentSecurityPolicy).find(
+            (directive) => directive.toLowerCase() === 'script-src',
+          );
+          if (scriptSrc) {
+            contentSecurityPolicy[scriptSrc].push(nonce);
+          } else {
+            contentSecurityPolicy['script-src'] = [nonce];
+          }
```
Comment (davidmurdoch) [inline app/scripts/background.js:352]: _Ideally_ we'd only ever modify the CSP if we absolutely must. I think trying to do that will be very difficult to do correctly/perfectly, so maybe we can limit the checks to cases where there is already a `script-src` or a `default-src` directive present?

That said, it is likely that 99% of all CSP headers already contain a `default-src` directive, so maybe adding checks here will be unnecessary. I'll let you decide.

File: app/scripts/background.js [hunk 8]
```diff
@@ -331,6 +332,34 @@ function maybeDetectPhishing(theController) {
   );
 }
 
+/**
+ * Overrides the Content-Security-Policy Header, acting as a workaround for an MV2 Firefox Bug.
```
Comment (davidmurdoch) [inline app/scripts/background.js:336]: Can you add a link to the firefox CSP issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1446231, here?

File: app/scripts/background.js [hunk 9]
```diff
@@ -477,6 +506,10 @@ async function initialize() {
 
     if (!isManifestV3) {
       await loadPhishingWarningPage();
+      const platform = getPlatform();
+      if (platform === PLATFORM_FIREFOX) {
+        overrideContentSecurityPolicyHeader();
+      }
```
Comment (davidmurdoch) [inline app/scripts/background.js:512]: Can you add a comment about pointing to the CSP issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1446231, here.

File: shared/modules/content-security-policy.ts [hunk 10]
```diff
@@ -0,0 +1,65 @@
+// ASCII whitespace is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE.
+// See <https://infra.spec.whatwg.org/#ascii-whitespace>.
+const ASCII_WHITESPACE_CHARS = '\t\n\f\r ';
+const ASCII_WHITESPACE = RegExp(`[${ASCII_WHITESPACE_CHARS}]+`);
+const ASCII_WHITESPACE_AT_START = RegExp(`^[${ASCII_WHITESPACE_CHARS}]+`);
+const ASCII_WHITESPACE_AT_END = RegExp(`[${ASCII_WHITESPACE_CHARS}]+$`);
```
Comment (davidmurdoch) [inline shared/modules/content-security-policy.ts:6]: minor nit, feel free to ignore: for consistency with other parts of our codebase these should probably use `new RegExp` (not just `RegExp`). (I'm surprised we don't have an eslint rule that automatically fixes this)

File: shared/modules/content-security-policy.ts [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+      const strippedToken = token
+        .replace(ASCII_WHITESPACE_AT_START, '')
+        .replace(ASCII_WHITESPACE_AT_END, '');
+
+      // If strippedToken is an empty string, or if strippedToken is not an ASCII string, continue.
+      if (!strippedToken || !ASCII.test(strippedToken)) continue;
+
+      // Directive name is the result of collecting a sequence of code points from token which are not ASCII whitespace.
+      // Directive values are the result of splitting token on ASCII whitespace.
+      const [name, ...values] = strippedToken.split(ASCII_WHITESPACE);
```
Comment (davidmurdoch) [inline shared/modules/content-security-policy.ts:44]: I just realized that this won't preserve the original whitespace when we `stringify` it back together. I'd like to say we can safely ignore it, and we probably can, but it'd be nice if we could rebuild the original stringy _exactly_ as it originally was (plus our own additions, of course).

File: development/webpack/utils/plugins/SelfInjectPlugin/index.ts [hunk 12]
```diff
@@ -142,6 +142,7 @@ export class SelfInjectPlugin {
       `\`\\n//# sourceURL=\${${this.options.sourceUrlExpression(file)}};\``,
     );
     newSource.add(`;`);
+    newSource.add(`s.nonce=btoa(browser.runtime.getURL('/'));`);
```
Comment (davidmurdoch) [inline development/webpack/utils/plugins/SelfInjectPlugin/index.ts:145]: I think the `SelfInjectPlugin`'s options should be extended to accept a `nonceExpression` option, similar to its existing `sourceURLExpression` option, that _defaults_ to the string `"(globalThis.browser||chrome).runtime.getURL('/')"`.

So this line here would become something like:

```typescript
newSource.add(`s.nonce=${this.options.nonceExpression(file)}`);
```

File: shared/modules/add-nonce-to-csp.ts [hunk 13]
```diff
@@ -0,0 +1,38 @@
+// ASCII whitespace is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE.
```
Comment (davidmurdoch) [inline shared/modules/add-nonce-to-csp.ts:1]: Wow. I love how simple this ended up being in the end! Quite the journey you went on to get here! Great work!

**Review by davidmurdoch — CHANGES_REQUESTED** [review]
Looks great!

Can you add an E2E test that shows that this works?

The webpack e2e tests don't currently run in FireFox, and that's fine... if we ever switch to using only the webpack builds (and thus run them in FireFox), and they end up failing for whatever reason, we'll just have to fix it at that time :-)

A note for those unlucky enough to have to read this PR review way in the future: we are aware this code may fail in the unlikely scenario where a CSP header contains a valid directive, followed by invalid CSP characters (like `é`), followed by the string`; script-src`. e.g. `Content-Security-Policy: default-src none; éééé<invalid>ééé; script-src self`. Fully parsing a CSP directive, determining which parts will be accepted by the browser, _and_ extending the directive is just too complex to warrant solving it right now.

File: app/scripts/background.js [hunk 14]
```diff
@@ -333,6 +335,32 @@ function maybeDetectPhishing(theController) {
...
+ * which involves overriding the page CSP for inline script nodes injected by extension content scripts.
+ */
+function overrideContentSecurityPolicyHeader() {
+  // The extension url is unique per install on Firefox, so we can safely add it as a nonce to the CSP header
+  const nonce = btoa(browser.runtime.getURL('/'));
+  browser.webRequest.onHeadersReceived.addListener(
+    ({ responseHeaders, url }) => {
+      // Check whether inpage.js is going to be injected into the page or not.
+      // There is no reason to modify the headers if we are not injecting inpage.js.
+      if (checkURLForProviderInjection(new URL(url))) {
```
Comment (davidmurdoch) [inline app/scripts/background.js:350]: nit: naming of this function could be improved per our developer guidelines on function names: https://github.com/MetaMask/contributor-docs/blob/main/docs/javascript.md#use-a-verb-phrase-for-functionmethod-names

File: development/webpack/utils/helpers.ts [hunk 15]
```diff
@@ -232,3 +232,16 @@ export function logStats(err?: Error | null, stats?: Stats) {
...
+ * Generates a runtime URL expression for a given path.
+ *
+ * This function constructs a URL string using the `runtime.getURL` method
+ * from either the `globalThis.browser` or `chrome` object, depending on
+ * which one is available in the global scope.
+ *
+ * @param path - The path of the runtime URL.
+ * @returns The constructed runtime URL string.
+ */
+export const getRuntimeURLExpression = (path: string) =>
```
Comment (davidmurdoch) [inline development/webpack/utils/helpers.ts:246]: Can we put this function in the `SelfInjectPlugin` directory? I think putting it in the `index.ts` file is fine, since there aren't any helpers there. The reason is that I'd like to try to keep the plugin's logic isolated.

**Review by davidmurdoch — CHANGES_REQUESTED** [review]
Looks like some tests are currently failing

File: development/webpack/utils/plugins/SelfInjectPlugin/types.ts [hunk 16]
```diff
@@ -39,11 +39,22 @@ export type SelfInjectPluginOptions = {
...
+   *   sourceUrlExpression: (filename) => `(globalThis.browser||chrome).runtime.getURL("${filename}")`
    * }
    * ```
    * @param filename - the chunk's relative filename as it will exist in the output directory
    * @returns
    */
   sourceUrlExpression?: (filename: string) => string;
+  /**
+   * A function that returns a JavaScript expression escaped as a string which
+   * will be injected into matched file to provide a nonceExpression for the self
```
Comment (davidmurdoch) [inline development/webpack/utils/plugins/SelfInjectPlugin/types.ts:51]:
```suggestion
   * will be injected into matched file to set a nonce for the self
```

File: development/create-static-server.js [hunk 17]
```diff
@@ -4,18 +4,36 @@ const path = require('path');
...
+ * @param {boolean|string[]} [options.cleanUrls] - Disable `.html` extension stripping, or restrict it to specific paths.
+ * @param {{source: string, destination: string}[]} [options.rewrites] - Array of rewrite rules to map certain paths to different ones.
+ * @param {{source: string, destination: string}[]} [options.redirects] - Array of redirect rules to forward paths to different paths or external URLs.
+ * @param {{source: string, headers: {key: string, value: string}[]}[]} [options.headers] - Array of custom headers to set for specific paths.
+ * @param {boolean|string[]} [options.directoryListing] - Disable directory listing, or restrict it to specific paths.
+ * @param {string[]} [options.unlisted] - List of paths to exclude from the directory listing.
+ * @param {boolean} [options.trailingSlash] - Whether to enforce trailing slashes on paths.
+ * @param {boolean} [options.renderSingle] - If a directory contains only one file, render it.
+ * @param {boolean} [options.symlinks] - Whether to resolve symlinks instead of serving a 404 error.
+ * @param {boolean} [options.etag] - Whether to calculate and use an ETag response header instead of Last-Modified.
```
Comment (davidmurdoch) [inline development/create-static-server.js:22]: You can probably replace all this by installing the types package `@types/serve-handler` as a dev dependency and then using `@param { NonNullable<Parameters<typeof import("serve-handler")>[2]> } options - Configuration options for serve-handler. Documentation can be found here: https://github.com/vercel/serve-handler` as the type

**Review by davidmurdoch — DISMISSED** [review]

**Review by davidmurdoch — DISMISSED** [review]

**Review by DDDDDanica — DISMISSED** [review]

File: development/create-static-server.js [hunk 18]
```diff
@@ -4,18 +4,25 @@ const path = require('path');
...
 
-const createStaticServer = (rootDirectory) => {
+/**
+ * Creates an HTTP server that serves static files from a directory using serve-handler.
+ * If a request URL starts with `/node_modules/`, it rewrites the URL and serves files from the `node_modules` directory.
+ *
+ * @param { NonNullable<Parameters<typeof import("serve-handler")>[2]> } options - Configuration options for serve-handler. Documentation can be found here: https://github.com/vercel/serve-handler
+ * @returns {http.Server} An instance of an HTTP server configured with the specified options.
+ */
+const createStaticServer = (options) => {
```
Comment (seaona) [inline development/create-static-server.js:14]: nice :raised_hands:

File: app/_locales/en/messages.json [hunk 19]
```diff
@@ -3764,6 +3764,12 @@
   "outdatedBrowserNotification": {
     "message": "Your browser is out of date. If you don't update your browser, you won't be able to get security patches and new features from MetaMask."
   },
+  "overrideContentSecurityPolicyHeader": {
+    "message": "Override Content-Security-Policy header"
+  },
+  "overrideContentSecurityPolicyHeaderDescription": {
+    "message": "This option is a workaround for a known issue in Firefox, where the Content-Security-Policy header may not be bypassed, causing the extension to fail to load properly. Disabling this option is not recommended unless required for specific web page compatibility."
```
Comment (davidmurdoch) [inline app/_locales/en/messages.json:3771]:
```suggestion
    "message": "This option is a workaround for a known issue in Firefox, where a dapp's Content-Security-Policy header may prevent the the extension from loading properly. Disabling this option is not recommended unless required for specific web page compatibility."
```

File: app/scripts/controllers/preferences-controller.ts [hunk 20]
```diff
@@ -300,6 +302,10 @@ const controllerMetadata = {
     persist: true,
     anonymous: true,
   },
+  overrideContentSecurityPolicyHeader: {
+    persist: true,
+    anonymous: true,
```
Comment (davidmurdoch) [inline app/scripts/controllers/preferences-controller.ts:307]: I'm new to this controller. What does the `anonymous` flag do?

File: ui/pages/settings/advanced-tab/advanced-tab.component.js [hunk 21]
```diff
@@ -592,6 +630,7 @@ export default class AdvancedTab extends PureComponent {
         {this.renderAutoLockTimeLimit()}
         {this.renderUserDataBackup()}
         {this.renderDismissSeedBackupReminderControl()}
+        {this.renderOverrideContentSecurityPolicyHeader()}
```
Comment (davidmurdoch) [inline ui/pages/settings/advanced-tab/advanced-tab.component.js:633]: Should this option should only be displayed for FireFox users?

Comment (danjm) [reply ui/pages/settings/advanced-tab/advanced-tab.component.js:633]: Yes, firefox only makes sense

File: app/scripts/background.js [hunk 22]
```diff
@@ -56,6 +56,8 @@ import {
 // TODO: Remove restricted import
```
Comment (danjm) [inline app/scripts/background.js:56]: This file LGTM :+1:

**Review by danjm — COMMENTED** [review]
This looks good to me overall. Has anyone manually tested with a prod-like build?

File: app/scripts/controllers/preferences-controller.ts (hunk 20 above)
Comment (davidmurdoch) [reply app/scripts/controllers/preferences-controller.ts:307]: Any reason not to track it? I'm guessing `anonymous: true` means _don't_ send to sentry?

Comment (Gudahtt) [reply app/scripts/controllers/preferences-controller.ts:311]: Confusingly, `anonymous: true` means that it's already anonymized.

It makes a little more sense if you consider that you can also specify a function here to transform the state into something anonymized, e.g. `anonymous: (address) => hash(address)`

We do have an issue for renaming the field to something less confusing though 😅 Suggestions on which name to use are welcome: https://github.com/MetaMask/core/issues/643

**Comment by DDDDDanica** [comment]
Hey @itsyoboieltr I used the build from bot above and tested locally the zip in firefox. I noticed that in firefox page we won't receive any errors, while in extension log we still have it, is this expected?
截屏2024-11-07 11 26 46

**Comment by DDDDDanica** [comment]
@itsyoboieltr thanks for the explanation, just to make sure it is not related, approve now !

**Review by DDDDDanica — APPROVED** [review]

**Review by danjm — APPROVED** [review]

**Review by davidmurdoch — APPROVED** [review]
