### PR TITLE
Do not show failed off-chain transactions details when grouped with another valid transaction of same nonce

### LINKED ISSUE #14430: [Bug]: Metamask displays a Transaction with Ledger as a Contract Deployment
### Describe the bug

**Problem**: after rejecting deploying a contract, when I perform a regular transaction using Ledger, I see that the transaction appears as a "Contract Deployment" on the activity logs

https://user-images.githubusercontent.com/54408225/163143417-4c80f425-c544-428c-9e70-df268fec26d4.mp4

 

### Steps to reproduce

1. Unlock Metamask
2. Import Ledger account
3. Go to Dapp
4. Click deploy contract, and when the tx is trigger on Ledger, cancel it on Ledger
5. Go to Metamask
6. Send ETH to another account
7. Check the activity logs

### Error messages or log output

_No response_

### Version

10.13.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #14472: Error: useTransactionDisplayData does not recognize transaction type. Type received is: cancel_Last 30 Days: 2.1K
Sentry Issue: [METAMASK-J9QX](https://sentry.io/organizations/metamask/issues/2407526716/?project=273505&query=is%3Aunresolved+type+received&statsPeriod=14d)

```
Error: useTransactionDisplayData does not recognize transaction type. Type received is: cancel
  at action (ui/store/actions.js:3045:24)
  at useTransactionDisplayData (ui/hooks/useTransactionDisplayData.js:251:5)
  at c (ui/components/app/transaction-list-item/transaction-list-item.component.js:124:7)
  at None (ui/index.js:157:3)
...
(11 additional frame(s) were not displayed)
```
Last 30 Days: 2.1K

### PR DESCRIPTION
**Pull request by brad-decker**
## Explanation
Work towards #11677 
Fixes #14430 

This PR:
1. attempts to make the logic of the selector more understandable
2. prevents failed off chain transactions from becoming the initial transaction of a group
3. reassigns a failed off chain transaction as initial in the case that the transaction group contains a retry transaction (its valid to retry a failed off chain transaction with higher gas to overcome a transaction underpriced network failure)
4. Prevents marking failed off chain transactions as dropped when a transaction of the same nonce if confirmed

### CODE REVIEW

File: app/scripts/controllers/transactions/index.js [hunk 1]
```diff
@@ -1779,7 +1779,10 @@ export default class TransactionController extends EventEmitter {
         txMeta,
         'transactions/pending-tx-tracker#event: tx:confirmed reference to confirmed txHash with same nonce',
       );
```
Comment (danjm) [inline app/scripts/controllers/transactions/index.js:1781]: Change in this file makes sense, looks good

File: ui/selectors/nonce-sorted-transactions-selector.test.js [hunk 2]
```diff
@@ -292,7 +313,7 @@ describe('nonceSortedTransactionsSelector', () => {
       {
         nonce: '0x0',
         transactions: txList,
```
Comment (danjm) [inline ui/selectors/nonce-sorted-transactions-selector.test.js:315]: Why is the result of this test different than the one added above? The inputs look the same to me, so there is something I am not seeing

Comment (brad-decker) [reply ui/selectors/nonce-sorted-transactions-selector.test.js:315]: The one above is a legitimate retry of a failed off chain transaction.

this one is a failed off chain followed by a simple send completely new transaction.

Comment (danjm) [reply ui/selectors/nonce-sorted-transactions-selector.test.js:315]: oh, okay, thanks

File: ui/selectors/transactions.js [hunk 3]
```diff
@@ -341,7 +460,31 @@ export const nonceSortedTransactionsSelector = createSelector(
       orderedTransactionGroups,
       incomingTransactionGroups,
     );
-    return unapprovedTransactionGroups.concat(orderedTransactionGroups);
+    return unapprovedTransactionGroups
+      .concat(orderedTransactionGroups)
+      .map((txGroup) => {
+        // In the caes that we have a cancel or retry as initial transaction
```
Comment (danjm) [inline ui/selectors/transactions.js:466]: typo "caes" -> "case"

File: ui/selectors/transactions.js [hunk 4]
```diff
@@ -271,47 +277,160 @@ export const nonceSortedTransactionsSelector = createSelector(
...
+        // completely different transactions of the same nonce and they will be
+        // bundled together by this selector as the same activity entry.
+        const previousInitialTransaction = {
+          // As we loop through the transactions in state we may temporarily
+          // assign a initialTransaction that is an "Ephemeral" transaction,
+          // which is one that failed before being broadcast for inclusion in a
+          // block. When this happens, and we have another transaction to
+          // consider in a nonce group, we should use the new transaction.
+          isEphemeral:
             TRANSACTION_STATUSES.FAILED &&
```
Comment (danjm) [inline ui/selectors/transactions.js:403]: @brad-decker Looks like line 403 needs fixing.

Should it be `nonceProps.initialTransaction.status === TRANSACTION_STATUSES.FAILED &&`?

Comment (brad-decker) [reply ui/selectors/transactions.js:403]: WOOPS good catch!

**Review by danjm — CHANGES_REQUESTED** [review]
I found one issue. This generally looks good to me. I need to run the code and play around with some breakpoints in the browser to verify my understanding, but I should be able to approve after my next 20-30 minute review session (and once the issue I found is fixed)

File: ui/selectors/transactions.js (hunk 4 above)
Comment (brad-decker) [reply ui/selectors/transactions.js]: @danjm done in latest.

File: app/scripts/controllers/transactions/index.js [hunk 5]
```diff
@@ -1779,7 +1779,10 @@ export default class TransactionController extends EventEmitter {
...
-      this._dropTransaction(otherTxMeta.id);
+      // Drop any transaction that wasn't previously failed (off chain failure)
+      if (otherTxMeta.status !== TRANSACTION_STATUSES.FAILED) {
```
Comment (darkwing) [inline app/scripts/controllers/transactions/index.js:1783]: Unrelated but in the future I'd love a more meaningful var name than `otherTxMeta`.

**Comment by danjm** [comment]
For QA:

To repro the bug this fixes on develop:

1. Turn on "Show Hex Data" in advanced settings
2. Go through the MetaMask send flow to create a transction to address A
3. enter 0x123456789 in the hex data field, and anything in the amount field (or zero)
4. Click "Next" to go to the confirm screen
5. Edit the gas limit. It should be above 30000, edit it to 21000
6. Save the edited gas and then submit the transaction.
7. The transaction should immediately fail. You should see the failed transaction in the MetaMask "Activity" list
8. Now create a new transaction, to address B. Setting hex data and amount is optional. Don't edit the gas limit on the confirm screen.
9. Once the transaction is confirmed and succeeds, the MetaMask "Activity" list will say address A, but in fact it was sent to address B, which can be seen on etherscan. Also note that only the transaction created in step 8 will be shown in the MetaMask Activity list, the transaction from steps 1-7 will no longer be shown.

On this branch this bug should not occur

**Comment by danjm** [comment]
This looks good to me, but I'd like a QA approval too

**Comment by seaona** [comment]
This looks good to me. Actually, I've realized this fix also solves another bug related to "cached tx's" history. In this case, it involved cancelling a contract deployment from a device (i.e. Ledger) and performing a subsequent tx https://github.com/MetaMask/metamask-extension/issues/14430 . Issue can be closed with this PR too.

**Review by seaona — APPROVED** [review]

**Review by danjm — APPROVED** [review]
