### PR TITLE
Fix EIP-55 support on confirmation screens

### LINKED ISSUE #3514: Make all addresses EIP-55 compliant
Bounty: make all instances of account addresses in MetaMask compliant with EIP-55. Many instances of account addresses already are compliant, and successful completion of this bounty will require finding and updating all non-compliant addresses throughout the extension.

---
The correct mixed-case address is shown (truncated, but shown) on the main MetaMask screen.

But the address shown on the QR screen is all lower case.

### PR DESCRIPTION
**Pull request by whymarrh**
Fixes #3514

This PR updates our `ConfirmTransactionBase` container to checksum `to` addresses before truncating them for display purposes.

### CODE REVIEW

File: ui/app/components/sender-to-recipient/sender-to-recipient.component.js [hunk 1]
```diff
@@ -38,11 +38,17 @@ export default class SenderToRecipient extends PureComponent {
     recipientAddressCopied: false,
   }
```
Comment (danjm) [inline ui/app/components/sender-to-recipient/sender-to-recipient.component.js]: Are any of the changes in this file required for the fix? Or is this just a refactor?

File: ui/app/components/sender-to-recipient/sender-to-recipient.component.js [hunk 2]
```diff
@@ -38,11 +38,17 @@ export default class SenderToRecipient extends PureComponent {
...
 
+  recipientAddress = this.props.recipientAddress
+    ? checksumAddress(this.props.recipientAddress)
+    : this.props.recipientAddress
+
+  senderAddress = checksumAddress(this.props.senderAddress)
```
Comment (danjm) [inline ui/app/components/sender-to-recipient/sender-to-recipient.component.js]: Using a class property for this would be a new pattern for us. Do you see any benefit to this over just applying the `checksumAddress` call in the parent?

File: ui/app/components/sender-to-recipient/sender-to-recipient.component.js (hunk 1 above)
Comment (whymarrh) [reply ui/app/components/sender-to-recipient/sender-to-recipient.component.js]: The two separate commits here are independent, yup. The changes to this file (the first commit) aren't needed per se, but do improve the component. The 2nd commit with the fix doesn't touch this file, no.

File: ui/app/components/sender-to-recipient/sender-to-recipient.component.js (hunk 2 above)
Comment (whymarrh) [reply ui/app/components/sender-to-recipient/sender-to-recipient.component.js]: The benefit would be that we don't currently have a way for a component to document/verify/express that it requires a pre-checksummed addressed (e.g. a custom prop type validator). It makes sense to me that we would checksum the address for display purposes.

That said, we could cache this result in a bunch of other ways—would keeping it in the component state be more conventional?

Comment (danjm) [reply ui/app/components/sender-to-recipient/sender-to-recipient.component.js]: Depends on the convention :stuck_out_tongue: 

I like, and have recently been trying to follow, the convention of not manipulating data to be rendered in components. So the data the component receives is what it renders. In this case, this would require checksumming the address in `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-transaction-base/confirm-transaction-base.container.js`

Why do we need to cache the result?

Comment (whymarrh) [reply ui/app/components/sender-to-recipient/sender-to-recipient.component.js]: > Why do we need to cache the result?

If we checksum the address at all it's better to that once?

**Comment by whymarrh** [comment]
@danjm dropped de0ea5812 from this PR, we can address that separately (no pun intended)

**Comment by whymarrh** [comment]
> **ci/circleci: test-deps** — Your tests failed on CircleCI

I'm seeing `ENOAUDIT` which is a npm registry issue I think we can safely ignore

**Review by danjm — APPROVED** [review]

**Comment by damster7** [comment]
la sécurité est primordial pour l avancement
