### PR TITLE
Fix Sign-in With Ethereum (SIWE) metametric, add tests, and clean RPC method middleware event logic

### LINKED ISSUE #17974: [Bug]: When `eth_sign` is disabled we fire a `Signature Approved` event everytime we call the RPC method
### Describe the bug

**Problem**: when `eth_sign` is disabled from Advanced settings, we fire a `Signature Approved` event everytime we call the RPC method. This should not be the case.

This issue was introduced in 10.25.0, by this PR https://github.com/MetaMask/metamask-extension/pull/17308

https://user-images.githubusercontent.com/54408225/222666667-07b91fba-798c-4daf-8f95-ab64391ba351.mp4

### Steps to reproduce

1. Open Segment or open background console for check the network requests to Segment
2. Disable the functionality of `eth_sign` from MetaMask Advanced Settings
3. On another window, go to test dapp
4. Connect to test dapp
5. Click Eth Sign
6. See how the `Signature Approved` event is fired

### Error messages or log output

_No response_

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #18474: Sign-in With Ethereum (SIWE) Cleanup

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

Fixes: #18474
See: #18007
Progresses #17974

Fix SIWE event and clean createRPCMethodTrackingMiddleware logic

Fix SIWE event that was introduced in https://github.com/MetaMask/metamask-extension/pull/17688:
(while adding a test, I found a bug with the metametric event)
- fix SIWE (sign-in with ethereum) event (returning number of array length instead of string) 
- add SIWE test

Clean: 
- condense tests
- only need to build event properties once
- no need to pass null event property (`ui_customizations`)
- add `ui_customizations` event props to metametrics const
- use `errorCodes` and `TransactionStatus` const

## Manual Testing Steps

1.  send RPC transaction through test Dapp
2. with metametrics turned on, observe metametrics still send
3. observe SIWE 

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

**Comment by digiwand** [comment]
@jpuri thanks for the review! I updated the cleanup following the merge of #17688 (OpenSea security provider metrics). Looks like this PR introduced a bug to the tracked SIWE event, so I fixed it in this PR as well

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js [hunk 1]
```diff
@@ -193,25 +189,21 @@ export default function createRPCMethodTrackingMiddleware({
...
             if (isSIWEMessage) {
-              properties.ui_customizations === null
-                ? (properties.ui_customizations = [
-                    METAMETRIC_KEY_OPTIONS[METAMETRIC_KEY.UI_CUSTOMIZATIONS]
-                      .SIWE,
-                  ])
-                : properties.ui_customizations.push(
-                    METAMETRIC_KEY_OPTIONS[METAMETRIC_KEY.UI_CUSTOMIZATIONS]
-                      .SIWE,
-                  );
```
Comment (digiwand) [inline app/scripts/lib/createRPCMethodTrackingMiddleware.js:214]: turns out Array.push returns the length of the mutated array. this is a JS gotchya. fixed by using Array.concat

bug introduced #17688

Comment (digiwand) [inline app/scripts/lib/createRPCMethodTrackingMiddleware.js:214]: turns out Array.push returns the length of the mutated array. this is a JS gotchya. fixed by using Array.concat

**Review by jpuri — APPROVED** [review]
LGTM

**Comment by seaona** [comment]
From QA looks good @digiwand ! Nice work! I've just discovered some other issue regarding metametrics and signatures, but this time related to Hardware Wallets. I've opened a separate issue, as I think it was already there before your changes. Just FYI
https://github.com/MetaMask/metamask-extension/issues/18361

**Review by darkwing — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js [hunk 2]
```diff
@@ -254,79 +244,20 @@ export default function createRPCMethodTrackingMiddleware({
...
-            }
-          }
-        } catch (e) {
-          console.warn(
-            `createRPCMethodTrackingMiddleware: Error calling securityProviderRequest - ${e}`,
-          );
-        }
-      } else {
-        properties.method = method;
```
Comment (brad-decker) [inline app/scripts/lib/createRPCMethodTrackingMiddleware.js:320]: Not fully understanding why this was all removed, could you elaborate?

Comment (brad-decker) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js:320]: Did this turn out to be a wasteful duplication?

Comment (digiwand) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js:320]: yep! exactly. It's the same code verbatim from line 167. They live in the same scope of `function rpcMethodTrackingMiddleware`. no need to redefined :)

Comment (digiwand) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js:320]: @brad-decker
