### PR TITLE
Fix #20140 - Ensure only one network displays as selected in the network picker when chain IDs collide

### LINKED ISSUE #20140: [Bug]: Two networks selected in network menu with the same chain id.
### Describe the bug

While having two networks with the same chain id, such as two Ethereum mainnets, will show both networks selected under the network menu.

https://github.com/MetaMask/metamask-extension/assets/13376180/88996bdd-5b0f-4b66-a1dd-8b6f08900079

### Steps to reproduce

1. Add two networks with the same chain id, Ethereum/BNB/Matic/etc
2. Click the network menu
3. See that both networks with the same chain id are selected

### Error messages or log output

_No response_

### Version

10.35.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

This issue should have been fixed with https://github.com/MetaMask/metamask-extension/pull/19947 but was errantly reverted in https://github.com/MetaMask/metamask-extension/pull/19951 .

* Fixes [#12345](https://github.com/MetaMask/metamask-extension/issues/20140)

## Screenshots/Screencaps

SCR-20230724-mnkb

## Manual Testing Steps

1.  Add the following custom network:

```
Network Name: Ethereum Alt
RPC URL: https://ethereum.publicnode.com
Chain Id: 1
```

2.  Switch between Mainnet and this new custom network using the network picker
3.  Ensure the correct network is selected each time

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/multichain/network-list-menu/network-list-menu.js [hunk 1]
```diff
@@ -85,7 +87,8 @@ export const NetworkListMenu = ({ onClose }) => {
         return null;
       }
 
-      const isCurrentNetwork = currentChainId === network.chainId;
+      const isCurrentNetwork = currentNetwork.id === network.id;
```
Comment (danjm) [inline ui/components/multichain/network-list-menu/network-list-menu.js:90]: @darkwing Can you explain how/why this works to solve the issue? I assume that part of the problem is the `selected={isCurrentNetwork}` line below. If two networks within our state have the same `chainId`, wouldn't they have the same `id` property as well?

**Review by danjm — CHANGES_REQUESTED** [review]
Looking for clarification on my question before approving?

File: ui/components/multichain/network-list-menu/network-list-menu.js (hunk 1 above)
Comment (darkwing) [reply ui/components/multichain/network-list-menu/network-list-menu.js:90]: Because every custom and built-in network is given an `id` property.  

Built-in networks: https://github.com/MetaMask/metamask-extension/blob/24c9db588385e9ddb2b41234b27de49f5dcf32fb/ui/selectors/selectors.js#L1241-L1273

Custom networks are all given an `id` as well, which you can see in state's `networkConfigurations` property.  For example, I went to https://chainlist.org/chain/1 and added alternate Mainnets (chain ID 1):

SCR-20230724-nqdc

Every network `id` is unique, so we don't need to compare chain IDs, which is why my patch works:

https://github.com/MetaMask/metamask-extension/assets/46655/1a042c3c-10d3-4f1f-9c41-acf0f65b800a

Comment (danjm) [reply ui/components/multichain/network-list-menu/network-list-menu.js:90]: oh, of coure. I was thinking this was the old `networkId` property, buts its the new unique id per network. Thanks for clarifying that!

**Review by danjm — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!
