### PR TITLE
Fixing hex address display bug when editing transaction

### LINKED ISSUE #15841: [Bug]: When I click Edit on confirmation send screen it shows hex address instead of account name
### Describe the bug

**Problem**: When I go to Send form from MM extension and clicking on Edit button on next screen it does not show me account name anymore. Instead of account name it shows hex address which is now shown twice.

https://user-images.githubusercontent.com/94608179/190404196-69642e08-9881-4253-aa6a-50238ae8ab54.mov

### Steps to reproduce

1. Unlock MM
2. Go to Send flow/click Send button
3. Choose to send on one of saved accounts
4. Check input field at top if account name is shown and hex address below
5. Click Next
6. Click Edit
7. Check again input field at top and there are now two duplicate hex address (one is instead of account name)

### Error messages or log output

_No response_

### Version

10.18.4

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/15841

## Test plan
Defined in issue

## Explanation
When updating a draft transaction, the function `getAddressBookEntryOrAccountName` was being incorrectly used, as a `name` property was expected to be returned. The function returns a string that is either the name if available, or the address:

https://github.com/MetaMask/metamask-extension/blob/789c06a5b7aaa477b25ccce966d2aebd5eb25118/ui/selectors/selectors.js#L394

## Video
https://user-images.githubusercontent.com/8732757/190955514-1617c482-c976-4aac-a213-5508105cc7d2.mov

### CODE REVIEW

File: ui/pages/send/send-content/add-recipient/add-recipient.component.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ export default class AddRecipient extends Component {
     isUsingMyAccountsForRecipientSearch: PropTypes.bool,
     recipient: PropTypes.shape({
       address: PropTypes.string,
-      nickname: PropTypes.nickname,
+      nickname: PropTypes.string,
```
Comment (ryanml) [inline ui/pages/send/send-content/add-recipient/add-recipient.component.js:31]: Noticed this invalid `PropType` was causing:
Screen Shot 2022-09-18 at 8 45 55 PM

**Review by NiranjanaBinoy — APPROVED** [review]
lgtm

**Review by adonesky1 — APPROVED** [review]
LGTM
