### PR TITLE
fix: speedup cancellation

### LINKED ISSUE #7305: Speeding up cancelled transactions resends the transaction you wanted to cancel
I sent 5 ETH to an address, then clicked cancel. Then I wanted to speed up the cancellation, but instead it resent the prior transaction. The transaction confirmed.
Screen Shot 2019-10-22 at 9 43 16 PM

See the dropped transactions for https://etherscan.io/tx/0x4d6f83ccde8dd4affedd9a97e06b808f5f7531406a734860c4e0a217c4667e6d

### PR DESCRIPTION
**Pull request by shanejonas**
fixes #7305

Explanation:  
Speeding up cancelled transactions would send the original transaction.

Manual testing steps:  
  - need latest ganache run separately from dev env:
      - `npm install -g ganache@internal`
      -  `ganache --mnemonic "phrase upgrade clock rough situate wedding elder clever doctor stamp excess tent" --blockTime 50`
  - send tx to another account
  - hit cancel button
  - need to customize gas to be > 10% for ganache testing speedup/cancellation
  - hit `speedup this cancellation button`
  - need to customize gas to be > 10% for ganache testing speedup/cancellation

### CODE REVIEW

File: ui/app/components/app/sidebars/sidebar.component.js [hunk 1]
```diff
@@ -30,12 +30,12 @@ export default class Sidebar extends Component {
 
   renderSidebarContent() {
     const { type, sidebarProps = {} } = this.props;
-    const { transaction = {} } = sidebarProps;
+    const { transaction = {}, onSubmit } = sidebarProps;
```
Comment (Gudahtt) [inline ui/app/components/app/sidebars/sidebar.component.js:33]: I'm having trouble following where `onSubmit` is set :thinking: 

It looks like the `sidebarProps` are only set in one place: `useRetryTransaction.js` on line 46, which does not specify an `onSubmit` prop.

Comment (Gudahtt) [reply ui/app/components/app/sidebars/sidebar.component.js:33]: Nevermind, I see now. One more call was introduced in `useCancelTransaction`. Nevermind!

File: ui/app/hooks/useRetryTransaction.js [hunk 2]
```diff
@@ -34,7 +34,7 @@ export function useRetryTransaction(transactionGroup) {
 
       trackMetricsEvent();
       await dispatch(fetchBasicGasEstimates);
-      const transaction = initialTransaction;
+      const transaction = primaryTransaction;
```
Comment (Gudahtt) [inline ui/app/hooks/useRetryTransaction.js:37]: Just making sure I understand the impact of this change: it looks like this will ensure that when you retry a failed cancellation, it retries the _cancellation_ and not the original?

File: ui/app/hooks/useCancelTransaction.js [hunk 3]
```diff
@@ -19,27 +25,60 @@ import { getConversionRate, getSelectedAccount } from '../selectors';
...
   const gasPrice = primaryTransaction.txParams?.gasPrice?.startsWith('-')
     ? '0x0'
     : primaryTransaction.txParams?.gasPrice;
-  const { id } = initialTransaction;
+  const transaction = primaryTransaction;
   const dispatch = useDispatch();
   const selectedAccount = useSelector(getSelectedAccount);
   const conversionRate = useSelector(getConversionRate);
+  const defaultNewGasPrice = addHexPrefix(
+    multiplyCurrencies(gasPrice, 1.2, {
```
Comment (Gudahtt) [inline ui/app/hooks/useCancelTransaction.js:37]: Was this change left in from testing? This used to be 1.1

```suggestion
    multiplyCurrencies(gasPrice, 1.1, {
```

File: ui/app/hooks/useCancelTransaction.js [hunk 4]
```diff
@@ -19,27 +25,60 @@ import { getConversionRate, getSelectedAccount } from '../selectors';
...
     (event) => {
       event.stopPropagation();
-
+      dispatch(setCustomGasLimit('0x5208'));
+      dispatch(setCustomGasPriceForRetry(defaultNewGasPrice));
+      const tx = {
+        ...transaction,
+        txParams: {
+          ...transaction.txParams,
+          gas: '0x5208',
```
Comment (Gudahtt) [inline ui/app/hooks/useCancelTransaction.js:53]: What was the reason for overriding the `gas` and `value` here?

File: ui/app/hooks/useCancelTransaction.js [hunk 5]
```diff
@@ -19,27 +25,60 @@ import { getConversionRate, getSelectedAccount } from '../selectors';
...
-          originalGasPrice: gasPrice,
+        showSidebar({
+          transitionName: 'sidebar-left',
+          type: 'customize-gas',
+          props: {
+            transaction: tx,
+            onSubmit: (gl, gp) => {
+              const userCustomizedGasTotal = getHexGasTotal({
+                gasPrice: gp,
+                gasLimit: gl || '0x5208',
```
Comment (Gudahtt) [inline ui/app/hooks/useCancelTransaction.js:66]: Is it possible for `gl` to be falsey here? It didn't seem possible when I traced it down, because this value comes from `customModalGasLimitInHex` which is always set to something (it has a fallback of `0x5208` in `gas-modal-page-container.container.js`).

Comment (brad-decker) [reply ui/app/hooks/useCancelTransaction.js:66]: could we use `newGasLimiit`/`newGasPrice` here for readability?

File: ui/app/hooks/useCancelTransaction.js (hunk 4 above)
Comment (shanejonas) [reply ui/app/hooks/useCancelTransaction.js:53]: I moved the code from here and preserved the `gas`:

image

for `value`, this is passed in now to ensure that when cancelling and merging the params, that for a cancellation, the `value` is 0. If not, then it would put the value of the transaction you want to cancel in the gas modal.

Comment (Gudahtt) [reply ui/app/hooks/useCancelTransaction.js:53]: I don't think setting the value to zero is necessary here, since it's set to zero here as well: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/index.js#L405

Now that I'm looking at this.... it looks like the limit is set here too! Overridden to be '0x5208' each time. Huh. Yet we show it in the UI despite ignoring it. That's unfortunate. Maybe a problem to solve in another PR though :shrug:

Comment (Gudahtt) [reply ui/app/hooks/useCancelTransaction.js:53]: Actually this does seem problematic :thinking: If the user enters an alternate gas limit, they'll be shown a different fee than they end up paying.

This is less concerning if they _raise_ the gas limit, because... why would a user do that? And at least they'd pay _less_ than they confirmed in that case.

But if they lower the gas limit below 0x5208, we'd be claiming it costs _less_ than it does. That seems bad.

It looks like it'd be relatively straightforward to pass the gas limit through here too though? Just add another parameter to `createCancelTransaction`. At least it looks like it'd be that simple :thinking:

Comment (shanejonas) [reply ui/app/hooks/useCancelTransaction.js:53]: @Gudahtt updated `createCancelTransaction` and the CancelTransaction modal to handle custom gas limit

**Review by Gudahtt — APPROVED** [review]
LGTM!
