### PR TITLE
fix: fix aggregated balances

### LINKED ISSUE #34111: [Bug]: Show native token as main balance inconsistencies when disabling a default network or adding a custom network manually
### Describe the bug

When the general setting _Show native token as main balance_ is enabled, the following issues are present:

1. Disabling a default network still displays the native token of that network
2. Adding a custom network still displays the native token of the previously enabled network 

### Expected behavior

Display the correct native token of the enabled network
If all the default networks are enabled, what should be the native token displayed in the total balance?

### Screenshots/Recordings

https://github.com/user-attachments/assets/8add16c5-a5b0-454d-98cd-c7e5d58577c9

https://github.com/user-attachments/assets/cb105c83-4cc9-4b94-9a85-327491330c7c

https://github.com/user-attachments/assets/c2c3cf7b-cc8b-4d0a-9789-2241d1b513a6

### Steps to reproduce

Issue 1:

1. Enable Show native token as main balance in general settings
2. Enable all default networks
3. Disable them one by one
4. Notice the native token of the total balance changes to the disabled network native token

Issue 2:
1. Enable Show native token as main balance in general settings
2. Add a custom network
3. Add another custom network manually
4. Notice the native token of the total balance does not update

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

12.20.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34134?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: #34111 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

File: app/scripts/controllers/network-order.ts [hunk 1]
```diff
@@ -207,5 +215,47 @@ export class NetworkOrderController extends BaseController<
...
+    this._switchToEnabledNetworkIfNeeded(ids);
+  }
+
+  /**
+   * Switches to an enabled network if the currently selected network is not in the enabled list.
+   * This is a private helper method that handles the network switching logic.
+   *
+   * @param chainIds - Array of enabled chain IDs
+   */
+  private _switchToEnabledNetworkIfNeeded(chainIds: string[]) {
```
Comment (Prithpal-Sooriya) [inline app/scripts/controllers/network-order.ts]: Good method with JSDoc comments. Unsure if extension uses JS private hash (`#`) methods.
```ts
#switchToEnabledNetworkIfNeeded(...) { ... }
```

Comment (salimtb) [reply app/scripts/controllers/network-order.ts]: oooh yes good callout

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by bergarces — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
