### PR TITLE
Use ActionableMessage for ConfirmAddSuggestionToken warnings

### LINKED ISSUE #13068: ConfirmAddSuggestedToken story: convert knobs and actions to controls / args
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `ConfirmAddSuggestedToken` story in `ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [x] Story has `argTypes` that align with component api / props
- [x] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [x] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**

Screen Shot 2021-12-12 at 6 06 47 PM

### LINKED ISSUE #13347: Replace deprecated warning styles with actionable message components
**Description**
Replace deprecated warning styles and replace instances with `Actionable Message` components.

**Screenshots**

Replace these warnings styles(but keep the same copy*)

Screen Shot 2022-01-19 at 2 28 33 PM

With this `ActionableMessage` component

Screen Shot 2022-01-19 at 2 29 51 PM

**Tasks**

1. [Remove deprecated css](https://github.com/MetaMask/metamask-extension/blob/develop/ui/css/base-styles.scss#L46-L53) and warning styles.

2. Replace [instances of `warning` className](https://github.com/MetaMask/metamask-extension/blob/d0efb923808bbc43e7f955fd8ce3e95f6a124c1f/ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js#L74-L81) with correct [ActionableMessage](https://metamask.github.io/metamask-storybook/index.html?path=/story/ui-components-ui-actionable-message-actionable-message-stories-js--default-story) component and type

3. Update [ActionableMessage](https://metamask.github.io/metamask-storybook/index.html?path=/story/ui-components-ui-actionable-message-actionable-message-stories-js--default-story) component so if no actions are provided buttons should not appear

Screen Shot 2022-01-19 at 2 21 26 PM

4. Bonus point! Be able to show the warnings in the [storybook story]() through controls

Screen Shot 2022-01-19 at 2 26 13 PM

Reach out to @georgewrmarshall if you have any questions!

### PR DESCRIPTION
**Pull request by digiwand**
**Fixes:** #13347

**Explanation:**  Deprecate the last instances of the global `.warning` class used in the ConfirmAddSuggestionToken component. We replaced these instances using our ActionableMessage component. 

Additionally: 
- We also brought over the "Learn more about scams and security risks." link from the "Import Tokens" page, here to the "Add Suggested Tokens" page.
- Updated the symbol detection logic by treating symbols as case-insensitive
- Updated storybook to include controls and different warning states

**Manual testing steps (For EtherScan. Can replicate on another platform, e.g., CoinGecko):**  
  1. View an ERC20 token on EtherScan ([example](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7))
  2. Click on the "More" dropdown in "Profile Summary"
  3. Click on "Add Token to MetaMask (Web3)"
  4. Add token using MetaMask
  5. Repeat step 3
  6. Observe the "already listed" warning message. This should appear when the user is attempting to re-add a token with a token address already in their wallet.

To reproduce the reused symbol warning message, add a token with the same token name, e.g., "USDT," and a different address.

**Before:**
add-suggested-tokens-old

**Screenshot showing both warning messages:** 
Screenshot 2022-01-25 at 6 40 57 PM

**Updated Storybook:**
Screenshot 2022-01-29 at 12 34 59 AM

### CODE REVIEW

File: ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js [hunk 1]
```diff
@@ -10,6 +11,45 @@ import { isEqualCaseInsensitive } from '../../helpers/utils/util';
 function getTokenName(name, symbol) {
   return typeof name === 'undefined' ? symbol : `${name} (${symbol})`;
 }
+
+/**
+ * @param {Array} suggestedAssets
+ * @param {Array} tokens
```
Comment (adonesky1) [inline ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js:17]:
```suggestion
 * @param {Array} suggestedAssets - an array of assets suggested to add to the user's wallet via RPC method `wallet_watchAsset` 
 * @param {Array} tokens - the list of tokens currently tracked in state
```

File: ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js [hunk 2]
```diff
@@ -10,6 +11,45 @@ import { isEqualCaseInsensitive } from '../../helpers/utils/util';
...
+}
+
+/**
+ * Returns true if any suggestedAssets both:
+ * - Share a symbol with an existing `tokens` member.
+ * - Does not share an address with that same `tokens` member.
+ * This should be flagged as possibly deceptive or confusing.
+ *
+ * @param {Array} suggestedAssets
+ * @param {Array} tokens
```
Comment (adonesky1) [inline ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js:37]:
```suggestion
 * @param {Array} suggestedAssets - an array of assets suggested to add to the user's wallet via RPC method `wallet_watchAsset` 
 * @param {Array} tokens - the list of tokens currently tracked in state
```

File: ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js [hunk 3]
```diff
@@ -10,6 +11,45 @@ import { isEqualCaseInsensitive } from '../../helpers/utils/util';
 function getTokenName(name, symbol) {
   return typeof name === 'undefined' ? symbol : `${name} (${symbol})`;
 }
+
+/**
+ * @param {Array} suggestedAssets
+ * @param {Array} tokens
+ * @returns {boolean}
```
Comment (adonesky1) [inline ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js:18]:
```suggestion
 * @returns {boolean} - whether the list of suggestedAssets contains an entry with the an address that matches one already found in the token list.
```

File: ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js [hunk 4]
```diff
@@ -10,6 +11,45 @@ import { isEqualCaseInsensitive } from '../../helpers/utils/util';
...
+
+/**
+ * Returns true if any suggestedAssets both:
+ * - Share a symbol with an existing `tokens` member.
+ * - Does not share an address with that same `tokens` member.
+ * This should be flagged as possibly deceptive or confusing.
+ *
+ * @param {Array} suggestedAssets
+ * @param {Array} tokens
+ * @returns {boolean}
```
Comment (adonesky1) [inline ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js:38]:
```suggestion
 * @returns {boolean} - whether the list of suggestedAssets contains an entry with 1. a symbol that matches and 2. an address that does not match an entry in the token list.
```

File: app/_locales/el/messages.json [hunk 5]
```diff
@@ -1453,7 +1453,7 @@
     "message": "Γνωστή διεύθυνση συμβολαίου."
   },
   "knownTokenWarning": {
-    "message": "Αυτή η ενέργεια θα επεξεργαστεί tokens που είναι ήδη εισηγμένα στο πορτοφόλι σας, τα οποίαο μπορεί να χρησιμοποιηθούν για να σας κλέψουν στοιχεία. Αποδεχθείτε μόνο αν είστε σίγουροι ότι θέλετε να αλλάξετε αυτό που αντιπροσωπεύουν αυτά τα νομίσματα."
+    "message": "Αυτή η ενέργεια θα επεξεργαστεί tokens που είναι ήδη εισηγμένα στο πορτοφόλι σας, τα οποίαο μπορεί να χρησιμοποιηθούν για να σας κλέψουν στοιχεία. Αποδεχθείτε μόνο αν είστε σίγουροι ότι θέλετε να αλλάξετε αυτό που αντιπροσωπεύουν αυτά τα νομίσματα. Μάθετε περισσότερά γι'αυτό $1"
```
Comment (digiwand) [inline app/_locales/el/messages.json:1456]: This morning @adonesky1 met with our translations vendor and shared in [Slack](https://consensys.slack.com/archives/GTQAGKY5V/p1643210642285800):
> they are recommending that we not include translated strings until they've completed their proof-reading step

I think it's worth mentioning here that because this is a recommendation and not a strict rule, and because these translations are a verbatim copy and paste from the fakeTokenWarning.message translation, I think it's okay to add the translations for "Learn more about scams and security risks." in this PR.

Open to removing these translations if others feel otherwise.

**Review by darkwing — DISMISSED** [review]
My only nit could be to change `ZENDESK_URL` to `ZENDESK_URLS`, since it's going to be a dictionary of URLs, but not a big deal.

Nicely done!

**Comment by digiwand** [comment]
@darkwing Works with me! Thanks for the review 😄

**Comment by digiwand** [comment]
Heads up, I believe we should be comparing symbols with a case-insensitive check. Last commit updates this logic to support this f6c62f5

**Comment by digiwand** [comment]
gm, made a couple of small updates. another round of review please @darkwing @adonesky1?

File: ui/helpers/constants/zendesk-url.js [hunk 6]
```diff
@@ -0,0 +1,6 @@
+const ZENDESK_URLS = {
```
Comment (brad-decker) [inline ui/helpers/constants/zendesk-url.js:1]: ⭐

**Review by brad-decker — APPROVED** [review]

**Review by adonesky1 — CHANGES_REQUESTED** [review]
A couple of general things:
 - since in you're [previous PR](https://github.com/MetaMask/metamask-extension/pull/13377) you converted this into a functional component, would you mind stripping out the "container" wrapper component and pull in the state and redux methods via `useSelector` and `useDispatch`?
- It seems a bit weird that the css for this component is now fragmented across its own scss file and confirm-import-token/index.scss file... Can we consolidate this somehow?

**Comment by digiwand** [comment]
@adonesky1 

Sweet. I can get on board with this. 

I like the idea of updating the code to the latest patterns, utilizing redux, and updating the CSS. Would it work for you if I created a follow-up PR to keep the cleanup work separate? As you mentioned, it would have been nice to add to the [previous PR](https://github.com/MetaMask/metamask-extension/pull/13377). I do have some follow-up questions about this container you speak of as well 👀

Thanks for bringing this up!

**Review by adonesky1 — APPROVED** [review]
