### PR TITLE
Autofilling new issue link with url and domain (Phishing detect page)

### LINKED ISSUE #11997: Ethereum Phishing Detection Page - Add Title and Body to GH Issue Link
On the [Ethereum Phishing Detection Page](chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=metamassk.com&href=http%3A%2F%2Fmetamassk.com%2F), there is a `please file an issue` CTA that points to `github.com/metamask/eth-phishing-detect/issues/new`. Users often create issues without the URL in the Title nor in the Body of the issue, making the issue hard to reproduce.

Could we add more structure to the CTA link and autofill the domain and full URL that the user visited? 

A proposed format:
Title: `[Legitimate Site Blocked] {domain}`
Body: `{full URL}`
New URL: https://github.com/MetaMask/eth-phishing-detect/issues/new?title=[Legitimate%20Site%20Blocked]%20{autofill%20domain%20here}&body={autofill%20URL%20here}

Thanks,
David Grossman
[eth-phishing-detect](https://github.com/MetaMask/eth-phishing-detect) maintainer

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/11997

Example:
https://github.com/MetaMask/eth-phishing-detect/issues/new?title=[Legitimate%20Site%20Blocked]%20altus.finance&body=https://altus.finance/
Screen Shot 2021-09-01 at 8 52 23 PM

### CODE REVIEW

File: app/scripts/phishing-detect.js [hunk 1]
```diff
@@ -11,8 +11,11 @@ document.addEventListener('DOMContentLoaded', start);
 function start() {
   const hash = window.location.hash.substring(1);
   const suspect = querystring.parse(hash);
+  const newIssueLink = document.getElementById('new-issue-link');
+  const csdbLink = document.getElementById('csdbLink');
 
-  document.getElementById('csdbLink').href = `https://cryptoscamdb.org/search`;
+  csdbLink.href = `https://cryptoscamdb.org/search`;
+  newIssueLink.href = `https://github.com/MetaMask/eth-phishing-detect/issues/new?title=[Legitimate%20Site%20Blocked]%20${suspect.hostname}&body=${suspect.href}`;
```
Comment (Gudahtt) [inline app/scripts/phishing-detect.js:18]: We should escape the hostname and href here, just to be safe. I'm not sure whether anything screwy can happen here since the character set allowed in hostnames is limited, but why take chances. It is untrusted user input after all.

**Review by Gudahtt — DISMISSED** [review]

File: app/scripts/phishing-detect.js (hunk 1 above)
Comment (ryanml) [reply app/scripts/phishing-detect.js]: good call, done!

**Review by Gudahtt — DISMISSED** [review]
LGTM!

File: app/scripts/phishing-detect.js [hunk 2]
```diff
@@ -11,8 +11,15 @@ document.addEventListener('DOMContentLoaded', start);
...
   const suspect = querystring.parse(hash);
+  const newIssueLink = document.getElementById('new-issue-link');
+  const csdbLink = document.getElementById('csdbLink');
+  const newIssueUrl = `https://github.com/MetaMask/eth-phishing-detect/issues/new`;
+  const newIssueParams = `?title=[Legitimate%20Site%20Blocked]%20${encodeURIComponent(
+    suspect.hostname,
+  )}&body=${encodeURIComponent(suspect.href)}`;
 
-  document.getElementById('csdbLink').href = `https://cryptoscamdb.org/search`;
+  csdbLink.href = `https://cryptoscamdb.org/search`;
```
Comment (mcmire) [inline app/scripts/phishing-detect.js:21]: Is there a reason why this URL can't be included directly in the HTML?

Comment (ryanml) [reply app/scripts/phishing-detect.js]: yep, no reason to do it this way at this time. updated

**Review by mcmire — APPROVED** [review]
Looks good!

**Review by Gudahtt — APPROVED** [review]
LGTM!
