### PR TITLE
fix: duplicate key import error msg

### LINKED ISSUE #37338: [Bug]: Wrong error message when importing the duplicated private key
### Describe the bug

When user import the duplicated PK, it showed the error message but the error message contains the code
"KeyringController"

### Expected behavior

Should only show "The account you are trying to import is a duplicate"

### Screenshots/Recordings

Image

### Steps to reproduce

1. Login to MM
2. Use existing account's PK or use new PK
3. Import the PK (import 2 times if use new PK)
4. Check the error message

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

13.7.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39006?quickstart=1)

Fix duplicate key import error message

## **Changelog**

CHANGELOG entry: Fix duplicate key import error message

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37338
Fixes: https://consensyssoftware.atlassian.net/browse/MUL-1364

## **Manual testing steps**

1. Import a private key account
2. Try to import the same account again
3. Notice that the error message does not contain the `KeyringController` prefix

### **Before**

Check linked issue

### **After**

Screenshot 2025-12-31 at 11 20 27 AM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Improves error handling in account import and adds tests.
> 
> - In `import-account.js`, adds `handleKeyringControllerError` to strip `KeyringController -` prefix and route the remaining message through `translateWarning`; invoked in `importAccount` catch flow before generic translation
> - Keeps existing i18n handling via `translateWarning` for both plain strings and `t('...')` keys
> - Introduces `import-account.test.tsx` with coverage for rendering, import type switching, private key import success/failure, cancel action, and new KeyringController-specific error cases (including i18n-formatted messages)
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 781631680a4ec79548c9c11b63cfa672ac2382eb. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/multichain/import-account/import-account.js [hunk 1]
```diff
@@ -132,6 +137,22 @@ export const ImportAccount = ({ onActionComplete }) => {
...
+    // the rest of the message.
+    const errorPrefix = 'KeyringController -';
+    if (error.message.startsWith(errorPrefix)) {
+      const trimmedMessage = error.message.slice(errorPrefix.length).trim();
+      translateWarning(trimmedMessage);
+      return true;
+    }
+
+    return false;
+  }
```
[the remark this answers is not in the document]
Comment (gantunesr) [reply ui/components/multichain/import-account/import-account.js:154]: It's a different prefix

**Review by owencraston — APPROVED** [review]

File: ui/components/multichain/import-account/import-account.js [hunk 2]
```diff
@@ -132,6 +137,22 @@ export const ImportAccount = ({ onActionComplete }) => {
     }
   }
 
+  function handleKeyringControllerError(error) {
+    // This is not the best way to handle error messages coming from the KeyringController.
+    // We should have a mapping that allows us to map error codes to i18n messages.
+    // However, for now, we will just check if the error message starts with
```
Comment (vinnyhoward) [inline ui/components/multichain/import-account/import-account.js:143]: We should probably create a ticket for this right? So it doesn't get lost in the void

**Review by vinnyhoward — APPROVED** [review]
LGTM left a comment

File: ui/components/multichain/import-account/import-account.js (hunk 2 above)
Comment (gantunesr) [reply ui/components/multichain/import-account/import-account.js:143]: https://consensyssoftware.atlassian.net/browse/MUL-1374
