### PR TITLE
fix: Consistent confirmation navigation

### LINKED ISSUE #27252: [Bug]: Signatures - Navigation displays inconsistent order jumping from the first to the last alternatively, when having several signatures pending
### Describe the bug

When I trigger several signatures in batch, I see that after I accept/reject a single one, it keeps alternating the order of the singatures display: first it displays the last one, then the first one, then the last one, and so on.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/ed48a573-8bc2-4aa1-8421-b723eac643de

### Steps to reproduce

1. Go to the test dapp
2. Trigger Batch x10 signatures
3. See you are at the last signature
4. Reject
5. See you are at the first signature
6. Reject
7. See you are at the last signature
8. Reject
9. See you are at the first signature
10. and so on

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.2.4

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

As per the way the old confirmation navigation works, when submitting multiple confirmation requests to the wallet, we want to select the oldest confirmation by default (1 of X).

If `paramsTransactionId` is undefined in `ui/pages/confirmations/hooks/syncConfirmPath.ts`, the default confirmation id comes from `currentConfirmation`. As such, the first `currentConfirmation` selected in `useCurrentConfirmation` will determine the default position in the array of X sorted confirmations.

Instead of using latestPendingApproval, we want to use the oldest (first to be created) one.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27326?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27252

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/selectors/confirm.ts [hunk 1]
```diff
@@ -28,15 +28,9 @@ export function pendingConfirmationsSortedSelector(
     .sort((a1, a2) => a1.time - a2.time);
 }
 
-const internalLatestPendingConfirmationSelector = createSelector(
+export const oldestPendingConfirmationSelector = createSelector(
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/selectors/confirm.ts:31]: Do we definitely to keep the `createDeepEqualSelector` here?

The recent Redux state PR should only update `pendingApprovals` when it actually changes, but if it does, then we'll get a fresh object reference and re-render here unnecessarily?

These renders are critical since they can impact everything using `useConfirmContext`.

File: ui/pages/confirmations/selectors/confirm.ts [hunk 2]
```diff
@@ -28,15 +28,9 @@ export function pendingConfirmationsSortedSelector(
     .sort((a1, a2) => a1.time - a2.time);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/selectors/confirm.ts:28]: Not introduced by this PR, but perhaps worth some refactor here in future.

`getPendingApprovals` returns a fresh array on every call since it uses `Object.values`.

Then we `filter` which also returns a fresh array.

Ideally, we'd use `createSelector` with the underlying `state.metamask.pendingApprovals` then use `Object.values` and `filter` and `sort` inside a result function.

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/selectors/confirm.ts [hunk 3]
```diff
@@ -21,22 +20,16 @@ export function pendingConfirmationsSelector(state: ConfirmMetamaskState) {
...
+export const oldestPendingConfirmationSelector = createDeepEqualSelector(
   pendingConfirmationsSortedSelector,
-  (pendingConfirmations) =>
-    pendingConfirmations.sort((a1, a2) => a2.time - a1.time)[0],
-);
-
-export const latestPendingConfirmationSelector = createDeepEqualSelector(
-  internalLatestPendingConfirmationSelector,
-  (latestPendingConfirmation) => latestPendingConfirmation,
+  (pendingConfirmations) => pendingConfirmations[0],
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/selectors/confirm.ts:32]: Since the deep equal selector does the comparison on the dependencies, then this will still fire each time any of the confirmations change.

Ideally, we'd wrap the entire selector in a `createDeepEqualSelector`, or use `isEqual` as the second argument when we call `useSelector`.

File: ui/pages/confirmations/selectors/confirm.ts [hunk 4]
```diff
@@ -21,22 +20,16 @@ export function pendingConfirmationsSelector(state: ConfirmMetamaskState) {
 export function pendingConfirmationsSortedSelector(
   state: ConfirmMetamaskState,
 ) {
-  return getPendingApprovals(state)
+  return Object.values(state.metamask.pendingApprovals ?? {})
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/selectors/confirm.ts:23]: There's no value in doing this yet as we're not using `createSelector` so we'll always generate a new reference anyway, but at least we can re-use `getPendingApprovals`.

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
