### PR TITLE
fix: fix check for undefined marketData

### LINKED ISSUE #28019: [Sentry] TypeError: Cannot convert undefined or null to object [553K events]
Sentry Issue: [METAMASK-XCEB](https://metamask.sentry.io/issues/6010234875/?referrer=github_integration)

```
TypeError: Cannot convert undefined or null to object
  at Function.values (<anonymous>)
  at exports.getProviderConfig (ui/ducks/metamask/metamask.js:286:34)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
...
(28 additional frame(s) were not displayed)
```

### LINKED ISSUE #28864: [Bug]: MetaMask crash when try to import token after onboarding with basic functionality off
### Describe the bug

Onboarding MM by importing a wallet which have ERC20 token asset, toggle off basic functionality on manage privacy settings page during onboarding, click import token on homepage after onboarding makes MM crashes.

Note: not reproducible on production

### Expected behavior

MM should not crash

### Screenshots/Recordings

https://github.com/user-attachments/assets/305cafab-5350-4977-b30b-c189bed80796

### Steps to reproduce

1. Onboarding to MM by importing wallet with ERC20 asset
2. Toggle off basic functionality on privacy settings during onboarding
3. Click import token on homepage

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #28882: [Bug]: TypeError: Cannot convert undefined or null to object (AssetListControlBar)
### Describe the bug

Uncaught TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at asset-list-control-bar.tsx:102:16

I have found this bug to be present in the MetaMask Extension main branch (currently @ v12.7.2)
It occurred for me when I was testing an unrelated feature and switching from v12.5.0 => 12.7.2 in order to trigger migrations.

Upon swapping out the extension code and re-enabling the extension, refreshing and logging in, this error is encountered and a dialogue is displayed:
image

### Expected behavior

When logging in I should not see this dialogue as a user.

### Screenshots/Recordings

https://github.com/user-attachments/assets/6b0ccd96-a807-419c-9ad5-d64f93de3bb9

### Steps to reproduce

1. Load v12.5.0 and run yarn & yarn webpack:
```
git checkout tags/v12.5.0
yarn 
yarn webpack
```
2. Load Unpacked from the `/dist/chrome` and log into MetaMask
(It should not matter if you choose to enable STX or NOT (unrelated))
3. Toggle off MetaMask in Extension Manager
4. Delete the `/dist` directory and run:
```
git checkout main 
git pull
yarn 
yarn webpack
```
5. Open Extension Details
6. Toggle on MetaMask Extension
7. Refresh Extension
8. Launch MetaMask Extension
9. Log In and you will see “MetaMask Encountered an Error” dialogue
10. Right click and inspect on the error 

You will see the associated error related to `asset-list-control-bar.tsx`:102
Click on the link in the top right to be taken to line 102 in that component’s code where the issue originated from

### Error messages or log output

```shell
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at asset-list-control-bar.tsx:102:16
    at commitHookEffectList (react-dom.development.js:22030:26)
    at commitPassiveHookEffects (react-dom.development.js:22064:11)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385:16)
    at invokeGuardedCallback (react-dom.development.js:440:31)
    at flushPassiveEffectsImpl (react-dom.development.js:25392:7)
    at unstable_runWithPriority (scheduler.development.js:697:12)
    at runWithPriority$2 (react-dom.development.js:12149:10)
```

### Detection stage

On the development branch

### Version

12.7.2

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

I ensured that it was not related to my own changes by checking out the main branch and trying to reproduce and had success in encountering the error again.

The repro steps are only the way I found the bug and I feel that it could be encountered in other ways  also, but have not tested any other repro steps.

### Severity

- I believe that this bug could be encountered outside of my repro steps and could potentially impact  many users that are receiving an updated version and I have noticed it when switching from various older versions to `12.7.1` and `12.7.2`

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

This PR fixes app crash after user removes a network then adds it back and clicks on import token banner

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28870?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28019#issuecomment-2513839152
Fixes: https://github.com/MetaMask/metamask-extension/issues/28882
Fixes: https://github.com/MetaMask/metamask-extension/issues/28864

## **Manual testing steps**
Manual steps are also described in the github [issue](https://github.com/MetaMask/metamask-extension/issues/28019#issuecomment-2513839152). However; I do not think that the Show native token as main balance needs to be ONt o repro the initial issue. Also no need to add new RPC from chainList;

Settings:
1. Show balance and token price OFF
2. Token autodetect ON

On main view

1. Select an account which has some ERC20 tokens in Polygon
2. Add Polygon default network
3. See tokens are autodetected and you can open the modal -> but don't import the tokens!
4. Switch to another network
5. Delete Polygon network
6. Re-add Polygon default network
7. Click Import tokens --> Wallet should not crash

12. ## **Screenshots/Recordings**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/hooks/useTokenFiatAmount.js [hunk 1]
```diff
@@ -42,15 +42,16 @@ export function useTokenFiatAmount(
...
-    ? Object.entries(allMarketData[chainId]).reduce(
-        (acc, [address, marketData]) => {
-          acc[address] = marketData?.price ?? null;
-          return acc;
-        },
-        {},
-      )
-    : null;
+  const contractMarketData =
+    chainId && allMarketData[chainId]
```
Comment (sahar-fehri) [inline ui/hooks/useTokenFiatAmount.js:46]: After the user removed the network and added it back while having the setting  `Show balance and token price checker` OFF, the `allMarketData[chainId] `for the chainId was `undefined`, making `Object.entries(allMarketData[chainId])` throw the error we see in the issue `Cannot convert undefined or null to object `
Once the user turns the setting back on, it will populate the market data with the values again.

**Review by gambinish — DISMISSED** [review]

**Comment by gambinish** [comment]
Also fixes this bug release-blocker on 12.9: https://github.com/MetaMask/metamask-extension/issues/28864

**Comment by seaona** [comment]
hi there :wave: I confirm this fixes the issue I was seeing as well as [Chloe's issue](https://github.com/MetaMask/metamask-extension/issues/28864)

Side: we should keep the sentry issue open, since the stack traces point to a different root cause, that's unrelated to this error, despite having the same message. But Chloe's issue can be closed with this PR

https://github.com/MetaMask/metamask-extension/issues/28019#issuecomment-2516014174

**Review by gambinish — APPROVED** [review]

**Review by danjm — APPROVED** [review]
