### PR TITLE
Fixing activity title text truncation

### LINKED ISSUE #9997: Activity title overlaps amount if too long
**Description**
In the "Activity" tab, a longer title overlaps the amount. 

**Steps to reproduce**
Increase length of activity title.

**Expected behavior**
Expect title to wrap (or truncate) before overlapping with the amount. 

**Screenshots**
Screen Shot 2020-12-03 at 4 33 55 PM

**Browser details (please complete the following information):**
 - OS: OS X 10.15.7
 - Browser: Brave Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
 - MetaMask Version: 8.1.5

### PR DESCRIPTION
**Pull request by ryanml**
Fixes MetaMask/metamask-extension#9997

Screen Shot 2021-03-07 at 11 31 21 PM

Manual testing steps:  
  - Access an account with activity
  - Via another transaction (or the inspector tool), create a long activity title
  - Ensure that the title text truncates appropriately
  - Edit balance amount title so it truncates
  - Ensure that there is no overlap when both titles are truncated

### CODE REVIEW

File: ui/app/components/ui/list-item/list-item.component.js [hunk 1]
```diff
@@ -27,9 +27,7 @@ export default function ListItem({
         {React.isValidElement(title) ? (
           title
         ) : (
-          <button onClick={onClick}>
```
Comment (ryanml) [inline ui/app/components/ui/list-item/list-item.component.js:30]: There were existing rules for `list-item__title` regarding text truncation, but being the direct child of a button tag was blocking them taking effect. This button element and associated `onClick` value are actually redundant, as the  list item wrapper handles the `onClick` event for all of its contents: https://github.com/MetaMask/metamask-extension/blob/187c7828cfe1402e2e905924f2c29304ccee14d4/ui/app/components/ui/list-item/list-item.component.js#L22

Comment (Gudahtt) [reply ui/app/components/ui/list-item/list-item.component.js:30]: Huh, interesting find!

The use of `button` here was important though - it allowed keyboard navigation. Though... now that I'm testing it... it seems to have made it focusable, but pressing "Enter" did nothing :disappointed:.

Well, given that this already wasn't keyboard-friendly, this doesn't need to block here. But that's something we'll want to do. I'd suggest changing the `div` with the `onClick` set to a button.

**Review by Gudahtt — DISMISSED** [review]
LGTM!

As noted in a comment, this does impact accessibility, but this list already had issues there.

**Comment by darkwing** [comment]
Awesome work @ryanml !

File: ui/app/components/ui/list-item/list-item.component.js (hunk 1 above)
Comment (ryanml) [reply ui/app/components/ui/list-item/list-item.component.js:30]: Suggestion makes sense here 👍  Updated the outer container to be of type `button`:

Screen Shot 2021-03-08 at 10 26 53 AM

**Review by Gudahtt — APPROVED** [review]
LGTM!
