### PR TITLE
fix: Recreate offscreen document if it already exists

### LINKED ISSUE #27503: Error: The Snaps execution environment failed to start.
Sentry Issue: [METAMASK-XB8R](https://metamask.sentry.io/issues/5661010497/?referrer=github_integration)

```
Error: The Snaps execution environment failed to start.
  at exports.AbstractExecutionServiceinitStreams (node_modules/@metamask/snaps-controllers/dist/chunk-S775IABY.js:175:1)
  at exports.AbstractExecutionServiceinitJob (node_modules/@metamask/snaps-controllers/dist/chunk-S775IABY.js:140:1)
  at exports.AbstractExecutionServiceexecuteSnap (node_modules/@metamask/snaps-controllers/dist/chunk-S775IABY.js:272:1)
  at startSnap_fn (node_modules/@metamask/snaps-controllers/dist/chunk-E52MHHG4.js:2008:1)
  at SnapController.startSnap (node_modules/@metamask/snaps-controllers/dist/chunk-E52MHHG4.js:593:1)
```

### PR DESCRIPTION
**Pull request by FrederikBolding**
## **Description**

When the service worker is stopped it doesn't seem to guarantee that the offscreen document is closed as well. Our current initialization logic assumes this and thus once the service worker is spun back up, all communication with the offscreen document fails due to initialization failure.

This PR proposes fixing this problem by recreating the offscreen document when an existing document is found during boot. This guarantees a fresh offscreen document that we can await initialization of before using it.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27596?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27503

## **Manual testing steps**

1. Go to `chrome://serviceworker-internals/?devtools` and click stop on the MetaMask service worker
2. Go to https://metamask.github.io/snaps/test-snaps/latest/
3. Try to install any Snap
4. See that it works!

### CODE REVIEW

File: app/scripts/offscreen.js [hunk 1]
```diff
@@ -5,6 +5,30 @@ import {
...
+    const contexts = await chrome.runtime.getContexts({
+      contextTypes: ['OFFSCREEN_DOCUMENT'],
+    });
+    return contexts.length > 0;
+  }
+  const matchedClients = await clients.matchAll();
+  return matchedClients.some(
+    (client) =>
+      client.url.includes(chrome.runtime.id) &&
+      client.url.endsWith('offscreen.html'),
```
Comment (ccharly) [inline app/scripts/offscreen.js:28]: Might not be relevant here, but if any of the `client` here uses an URL with GET parameters like:

```
https://foobar.com?fake=offscreen.html
```

This might also return `true` in this case.

I have 0 context in this code, so this might not be relevant/possible. 😅

If that's a potential problem, then we could probably use `URL.origin` instead?

Comment (FrederikBolding) [reply app/scripts/offscreen.js:28]: As far as I can tell it only returns clients "owned" by the service worker. So it'll strictly be windows owned by the extension, which just seems to be `chrome-extension://id/something.html`. I modified the example from the Google docs slightly for more safety.

Regardless, 99.9% of users will use the if-clause assuming they aren't on an ancient browser.

Comment (FrederikBolding) [reply app/scripts/offscreen.js]: Simplified this a bit now, should be more safe like this.

**Review by Mrtenz — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!

File: app/scripts/offscreen.js (hunk 1 above)
Comment (ccharly) [reply app/scripts/offscreen.js]: Thanks, looks great!

**Review by ccharly — APPROVED** [review]
