### PR TITLE
fix: bridge asset picker and input component performance cp-12.20.0

### LINKED ISSUE #33466: [Bug]: The extension exhibits performance degradation, then crashes with the "MetaMask Lavamoat snow has crashed." error
### Describe the bug

I'm experiencing very similar behavior to what was described here for Firefox https://github.com/MetaMask/metamask-extension/issues/33403. The extension exhibits performance degradation, particularly during quote fetching for swap/bridge txs, and eventually becomes unresponsive. However, instead of simply stopping (as seen in Firefox), the extension crashes with the error "MetaMask Lavamoat snow has crashed."

While reloading the extension temporarily resolves the crash, the performance issues persist and the extension continues to experience reduced functionality. 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/713591c6-dbf0-418f-932e-03f3fbc5ac96

### Steps to reproduce

1. Install 12.20.0
2. Start swaps / bridge

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.20.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**
This PR fixes performance and memory leak issues in the bridge amount input field and asset picker components
  - Memoized debouncedSetSearchQuery with useCallback to prevent recreation on every render
  - Added cleanup calls when users select assets or close modals to cancel pending operations, which were preventing token list data from being GC after the Bridge page unloads
  - Replaced render prop pattern in NFT search with direct component composition to prevent unnecessary re-renders and stale references
  - Removed complex children render prop pattern from AssetPicker, which sets a custom button for the bridge page
  - Simplified component interfaces by removing unnecessary props (autoFocus, renderSearch)

The changes above improves performance when opening asset pickers, searching tokens, and switching assets, while preventing memory retention during extended bridge usage.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33507?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33466 (partially)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx [hunk 1]
```diff
@@ -158,7 +158,13 @@ export function AssetPickerModal({
...
-  const debouncedSetSearchQuery = debounce(setDebouncedSearchQuery, 200);
+  const debouncedSetSearchQuery = useCallback(
+    debounce((value) => {
+      setDebouncedSearchQuery(value);
+    }, 200),
+    [],
+  );
+
   useEffect(() => {
     debouncedSetSearchQuery(searchQuery);
```
Comment (davidmurdoch) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: untested, but for clean up, it'd be something like
```suggestion
    debouncedSetSearchQuery(searchQuery);
    
    // clean up the debounced function on unmount or when `searchQuery` changes
    return () => {
      debouncedSetSearchQuery.cancel();
    };
```

**Review by davidmurdoch — DISMISSED** [review]
left a comment suggesting a *possible* (untested) fix for some cleanup. I actually think it might be more necessary than I originally said, as it will also cancel the request when `searchQuery` changes, which we do want.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 1 above)
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: Updated the PR with this and also cancellation for the abortController

**Review by GustavoRSSilva — DISMISSED** [review]

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 1 above)
Comment (davidmurdoch) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: I think debouncedSetSearchQuery.cancel() also needs to happen after the searchQuery changes, which is why I thought to add it here and not in a dependency-less use effect hook.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx [hunk 2]
```diff
@@ -158,11 +158,27 @@ export function AssetPickerModal({
...
   const [debouncedSearchQuery, setDebouncedSearchQuery] = useState(searchQuery);
-  const debouncedSetSearchQuery = debounce(setDebouncedSearchQuery, 200);
+  const debouncedSetSearchQuery = useCallback(
+    debounce((value) => {
+      setDebouncedSearchQuery(value);
+    }, 200),
+    [],
+  );
+
+  const abortControllerRef = useRef<AbortController | null>(null);
```
Comment (MajorLift) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:168]: Should an abort controller instance be created here? Unless it's being passed in as a prop or supplied elsewhere? At least within this file, `abortControllerRef.current` is never set to any value other than `null`.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
Comment (MajorLift) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:1]: Nit: The extra state variable and state update using useEffect seem unnecessary.

> When something can be calculated from the existing props or state, [don’t put it in state.](https://react.dev/learn/choosing-the-state-structure#avoid-redundant-state) Instead, calculate it during rendering. This makes your code faster (you avoid the extra “cascading” updates), simpler (you remove some code), and less error-prone (you avoid bugs caused by different state variables getting out of sync with each other).
> 
> -- https://react.dev/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state

```diff
diff --git a/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx b/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
index 7778e01d30..222e10f93f 100644
--- a/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
+++ b/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
@@ -157,28 +157,27 @@ export function AssetPickerModal({
   const prevNeedsSolanaAccountRef = useRef(false);
 
   const [searchQuery, setSearchQuery] = useState('');
-  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState(searchQuery);
   const debouncedSetSearchQuery = useCallback(
-    debounce((value) => {
-      setDebouncedSearchQuery(value);
-    }, 200),
+    debounce((value) => value, 200),
     [],
   );
+  const debouncedSearchQuery =
+    debouncedSetSearchQuery(searchQuery) ?? searchQuery;
 
   const abortControllerRef = useRef<AbortController | null>(null);
 
-  // Cleanup abort controller and debounce on unmount
+  // Cleanup abort controller on unmount
   useEffect(() => {
     return () => {
       abortControllerRef.current?.abort();
       abortControllerRef.current = null;
-      debouncedSetSearchQuery.cancel();
     };
   }, []);
 
+  // clean up the debounced function on unmount or when `searchQuery` changes
   useEffect(() => {
-    debouncedSetSearchQuery(searchQuery);
-  }, [searchQuery, debouncedSetSearchQuery]);
+    return () => debouncedSetSearchQuery.cancel();
+  }, [searchQuery]);
 
   const swapsBlockedTokens = useSelector(getSwapsBlockedTokens);
   const memoizedSwapsBlockedTokens = useMemo(() => {

```

Comment (MajorLift) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:1]: Should we be passing the debounced value elsewhere in the file as well? There might be some performance gains to be had from reducing the frequency of child component props changes.

```diff
diff --git a/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx b/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
index 7778e01d30..f895896b99 100644
--- a/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
+++ b/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
@@ -516,7 +514,7 @@ export function AssetPickerModal({
 
   // This fetches the metadata for the asset if it is not already in the filteredTokenList
   const unlistedAssetMetadata = useAssetMetadata(
-    searchQuery,
+    debouncedSearchQuery,
     filteredTokenList.length === 0,
     abortControllerRef,
     selectedNetwork?.chainId,
@@ -666,7 +664,7 @@ export function AssetPickerModal({
             <AssetPickerModalTabs {...tabProps}>
               <React.Fragment key={TabName.TOKENS}>
                 <Search
-                  searchQuery={searchQuery}
+                  searchQuery={debouncedSearchQuery}
                   onChange={(value) => {
                     // Cancel previous asset metadata fetch
                     abortControllerRef.current?.abort();
@@ -696,12 +694,12 @@ export function AssetPickerModal({
               </React.Fragment>
               <AssetPickerModalNftTab
                 key={TabName.NFTS}
-                searchQuery={searchQuery}
+                searchQuery={debouncedSearchQuery}
                 onClose={onClose}
                 renderSearch={() => (
                   <Search
                     isNFTSearch
-                    searchQuery={searchQuery}
+                    searchQuery={debouncedSearchQuery}
                     onChange={(value) => setSearchQuery(value)}
                   />
                 )}

```

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 1 above)
Comment (MajorLift) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: Wouldn't this cause `debouncedSetSearchQuery.cancel()` to run before every `debouncedSetSearchQuery` call that is triggered by `useEffect` via a `searchQuery` update? I think that might interfere with the debounce operation.

Comment (MajorLift) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: Ah I think I misunderstood the intention. If we want to prevent `.cancel()` from being called unless `searchQuery` has changed the suggestion above would work.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 2 above)
Comment (MajorLift) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:168]: Nvm I just found that it's set in `useAssetMetadata`: https://github.com/MetaMask/metamask-extension/blob/342f06b3bc648801c74ba8c3565022fedc07e7df/ui/components/multichain/asset-picker-amount/asset-picker-modal/hooks/useAssetMetadata.ts#L52

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 1 above)
Comment (davidmurdoch) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: I'll defer to @MajorLift's expertise on all of this. @micaelae you don't need a review approval from me before merging, @MajorLift knows better than me!

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:1]: We pass the searchQuery instead of the debounced value here so that the input fields render the typed value right away. If we used the debounced value, it would look like the ui takes some time after typing to update the input field

**Comment by MajorLift** [comment]
@Gudahtt I attempted to optimize the expensive for loop in `filteredTokenList`. There wasn't a good way to leverage early exits, so I did the following:

- Reduce the overhead of recreating some functions and data structures
  - Better for maintainability and minimal performance improvement might be possible, but it shouldn't reduce re-renders.
- Cache the result of the most expensive operation in each loop (creating `tokenWithBalanceData`). 
  - I've included a cleanup fn for clearing the cache on unmount, so it might not help for our scenario here where we're switching between networks frequently. 
  - Memory usage might actually increase, although if there's a memory leak coming from fetch calls the caching might help mitigate it.
  
Haven't benchmarked this yet, but it doesn't seem to break functionality at least.

```diff
diff --git a/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx b/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
index 7778e01d30..5cad0ee345 100644
--- a/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
+++ b/ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
@@ -157,28 +157,31 @@ export function AssetPickerModal({
   const prevNeedsSolanaAccountRef = useRef(false);
 
   const [searchQuery, setSearchQuery] = useState('');
-  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState(searchQuery);
   const debouncedSetSearchQuery = useCallback(
-    debounce((value) => {
-      setDebouncedSearchQuery(value);
-    }, 200),
+    debounce((value) => value, 200),
+    [],
+  );
+  const debouncedSearchQuery =
+    debouncedSetSearchQuery(searchQuery) ?? searchQuery;
+
+  const tokensWithBalanceDataCache = useMemo(
+    () => new Map<`${string}:${string}`, AssetWithDisplayData<ERC20Asset>>(),
     [],
   );
-
   const abortControllerRef = useRef<AbortController | null>(null);
 
-  // Cleanup abort controller and debounce on unmount
+  // Cleanup abort controller on unmount
   useEffect(() => {
     return () => {
       abortControllerRef.current?.abort();
       abortControllerRef.current = null;
-      debouncedSetSearchQuery.cancel();
+      tokensWithBalanceDataCache.clear();
     };
   }, []);
 
+  // clean up the debounced function on unmount or when `searchQuery` changes
   useEffect(() => {
-    debouncedSetSearchQuery(searchQuery);
-  }, [searchQuery, debouncedSetSearchQuery]);
+    return () => debouncedSetSearchQuery.cancel();
+  }, [searchQuery]);
 
   const swapsBlockedTokens = useSelector(getSwapsBlockedTokens);
   const memoizedSwapsBlockedTokens = useMemo(() => {
@@ -416,24 +419,23 @@ export function AssetPickerModal({
     ],
   );
 
-  const filteredTokenList = useMemo(() => {
-    const filteredTokens: (
-      | AssetWithDisplayData<ERC20Asset>
-      | AssetWithDisplayData<NativeAsset>
-    )[] = [];
-    // List of token identifiers formatted like `chainId:address`
-    const filteredTokensAddresses = new Set<string | undefined>();
-    const getTokenKey = (address?: string | null, tokenChainId?: string) =>
+  // List of token identifiers formatted like `chainId:address`
+  const filteredTokensAddresses = useMemo(
+    () => new Set<string | undefined>(),
+    [],
+  );
+
+  const getTokenKey = useCallback(
+    (address?: string | null, tokenChainId?: string) =>
       `${address?.toLowerCase() ?? zeroAddress()}:${
         tokenChainId ?? currentChainId
-      }`;
+      }` as `${string}:${string}`,
+    [currentChainId],
+  );
 
-    // Default filter predicate for whether a token should be included in displayed list
-    const shouldAddToken = (
-      symbol: string,
-      address?: string | null,
-      tokenChainId?: string,
-    ) => {
+  // Default filter predicate for whether a token should be included in displayed list
+  const defaultShowAddToken = useCallback(
+    (symbol: string, address?: string | null, tokenChainId?: string) => {
       const trimmedSearchQuery = debouncedSearchQuery.trim().toLowerCase();
       const isMatchedBySearchQuery = Boolean(
         !trimmedSearchQuery ||
@@ -449,12 +451,27 @@ export function AssetPickerModal({
           isMatchedBySearchQuery &&
           !filteredTokensAddresses.has(getTokenKey(address, tokenChainId)),
       );
-    };
+    },
+    [
+      debouncedSearchQuery,
+      filteredTokensAddresses,
+      getTokenKey,
+      isMultiselectEnabled,
+      selectedChainIds,
+      selectedNetwork?.chainId,
+    ],
+  );
+
+  const filteredTokenList = useMemo(() => {
+    const filteredTokens: (
+      | AssetWithDisplayData<ERC20Asset>
+      | AssetWithDisplayData<NativeAsset>
+    )[] = [];
 
     // If filteredTokensGenerator is passed in, use it to generate the filtered tokens
     // Otherwise use the default tokenGenerator
     const tokenGenerator = (customTokenListGenerator ?? tokenListGenerator)(
-      shouldAddToken,
+      defaultShowAddToken,
     );
 
     for (const token of tokenGenerator) {
@@ -462,25 +479,33 @@ export function AssetPickerModal({
         continue;
       }
 
-      filteredTokensAddresses.add(getTokenKey(token.address, token.chainId));
-
-      const tokenWithBalanceData =
-        !customTokenListGenerator && isStrictHexString(token.address)
-          ? getRenderableTokenData(
-              token.address
-                ? ({
-                    ...token,
-                    ...evmTokenMetadataByAddress[token.address.toLowerCase()],
-                    type: AssetType.token,
-                  } as AssetWithDisplayData<ERC20Asset>)
-                : token,
-              tokenConversionRates,
-              conversionRate,
-              currentCurrency,
-              token.chainId,
-              evmTokenMetadataByAddress,
-            )
-          : (token as unknown as AssetWithDisplayData<ERC20Asset>);
+      const tokenKey = getTokenKey(token.address, token.chainId);
+      filteredTokensAddresses.add(tokenKey);
+
+      let tokenWithBalanceData;
+      if (tokensWithBalanceDataCache.has(tokenKey)) {
+        tokenWithBalanceData = tokensWithBalanceDataCache.get(tokenKey);
+      } else {
+        tokenWithBalanceData =
+          !customTokenListGenerator && isStrictHexString(token.address)
+            ? getRenderableTokenData(
+                token.address
+                  ? ({
+                      ...token,
+                      ...evmTokenMetadataByAddress[token.address.toLowerCase()],
+                      type: AssetType.token,
+                    } as AssetWithDisplayData<ERC20Asset>)
+                  : token,
+                tokenConversionRates,
+                conversionRate,
+                currentCurrency,
+                token.chainId,
+                evmTokenMetadataByAddress,
+              )
+            : (token as unknown as AssetWithDisplayData<ERC20Asset>);
+
+        tokensWithBalanceDataCache.set(tokenKey, tokenWithBalanceData);
+      }
 
       // Add selected asset to the top of the list if it is the selected asset
       if (
@@ -497,12 +522,14 @@ export function AssetPickerModal({
       }
     }
 
+    filteredTokensAddresses.clear();
+
     return filteredTokens;
   }, [
-    currentChainId,
-    debouncedSearchQuery,
-    isMultiselectEnabled,
-    selectedChainIds,
+    tokensWithBalanceDataCache,
+    filteredTokensAddresses,
+    getTokenKey,
+    defaultShowAddToken,
     selectedNetwork?.chainId,
     customTokenListGenerator,
     tokenListGenerator,

```

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 1 above)
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: Thanks @davidmurdoch , I will sync with @MajorLift 

> If we want to prevent .cancel() from being called unless searchQuery has changed the suggestion above would work.

This is what we want so I think the suggestion works. Implemented this in the latest commit

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:1]: Good call - will try this out

Comment (MajorLift) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:1]: Thanks for the explanation! Makes sense to keep the ui responsive, and it shouldn't affect memory usage either way, so lgtm to keep it as is.

**Comment by Gudahtt** [comment]
Neat! Maybe we can try that in a subequent PR @MajorLift ?

File: ui/hooks/bridge/useTokensWithFiltering.ts [hunk 3]
```diff
@@ -130,58 +130,6 @@ export const useTokensWithFiltering = (
...
-  ):
-    | AssetWithDisplayData<NativeAsset>
-    | AssetWithDisplayData<ERC20Asset>
-    | undefined => {
-    if (!chainId || !token) {
-      return undefined;
-    }
-    // Only tokens on the active chain are processed here here
-    const sharedFields = {
-      ...token,
```
Comment (micaelae) [inline ui/hooks/bridge/useTokensWithFiltering.ts:145]: Moved this to outside the hook to remove the closure that was retaining references to the token data

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-search.tsx
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-search.tsx:1]: Is this change performance related? It looks like this might just be fixing a prop type mismatch warning in some parent components, but I might be missing something.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx [hunk 4]
```diff
@@ -547,8 +570,10 @@ export function AssetPickerModal({
       <ModalContent modalDialogProps={{ padding: 0 }}>
         <ModalHeader
           onClose={() => {
-            setSearchQuery('');
+            debouncedSetSearchQuery.cancel();
+            abortControllerRef.current?.abort();
             onClose();
+            // setSearchQuery('');
```
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx]: Was this a mistake? I'm guessing that we want this `onClose` handler to do the same as the `onClose` handler for the overall modal.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 1 above)
Comment (Gudahtt) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: I see that the latest commit _wasn't_ updated according to this suggestion (i.e. we aren't calling `debouncedSetSearchQuery.cancel();` when `searchQuery` is called, we're only calling it on unmount). But this seems OK to me. When `searchQuery` changes, there should be no need to cancel the previous call because either it's already done, or it'll get replaced by the new search query anyway.

Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:180]: This is correct ^. Also I didn't copy the suggestion exactly, but added the cancellation as needed to change/close handlers + unmount as David recommended

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx [hunk 5]
```diff
@@ -158,18 +156,41 @@ export function AssetPickerModal({
...
   const swapsBlockedTokens = useSelector(getSwapsBlockedTokens);
   const memoizedSwapsBlockedTokens = useMemo(() => {
     return new Set<string>(swapsBlockedTokens);
   }, [swapsBlockedTokens]);
 
-  const handleAssetChange = useCallback(onAssetChange, [onAssetChange]);
+  const handleAssetChange = useCallback(
+    (newAsset) => {
+      onAssetChange(newAsset);
+      debouncedSetSearchQuery.cancel();
```
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx]: Canceling this might be counter-productive. I see that `handleAssetChange` is called immediately after calling `setSearchQuery('')`.

By cancelling the debounced query here we're effectively desychronizing `searchQuery` and `debouncedSearchQuery`, and I'm not sure why we'd want to do that.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx [hunk 6]
```diff
@@ -547,8 +570,10 @@ export function AssetPickerModal({
       <ModalContent modalDialogProps={{ padding: 0 }}>
         <ModalHeader
           onClose={() => {
-            setSearchQuery('');
+            debouncedSetSearchQuery.cancel();
```
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx]: These two additions seem redundant because `onClose` will result in the modal being unmounted, and these are already called upon unmount.

File: ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx [hunk 7]
```diff
@@ -107,7 +103,7 @@ export function AssetPicker({
   customTokenListGenerator,
   isTokenListLoading = false,
   isMultiselectEnabled = false,
-  autoFocus = true,
+  dataTestId = 'asset-picker-button',
```
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx]: Nit: This is an unconventional way to use `dataTestId`. Typically this prop represents the test ID for the component, but here it's used for a sub-component (the asset picker button specifically).

Maybe it could be called `buttonDataTestId` instead? Or we could take a `dataTestId` here, but use `${dataTestId}-button` for the button?

File: ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Comment (Gudahtt) [inline ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx:1]: What was the reason for these changes? At first I thought that maybe these removed hooks were causing unnecessary re-renders, but I don't think that is the case.  All of the selectors used _inside_ these removed hooks appear to be present directly in this component, so it's re-rendering regardless in each case.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 4 above)
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx]: Yes, adding this back for now. I might remove both cleanups on close due to redundancy (per your comment above), will test locally

File: ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Comment (Gudahtt) [reply ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx:1]: Same question for the metric event removals in `prepare-bridge-page` as well

File: ui/pages/bridge/prepare/bridge-input-group.tsx [hunk 8]
```diff
@@ -70,14 +67,13 @@ export const BridgeInputGroup = ({
   onMaxButtonClick,
   isMultiselectEnabled,
   onBlockExplorerClick,
-  buttonProps,
+  dataTestId,
```
Comment (Gudahtt) [inline ui/pages/bridge/prepare/bridge-input-group.tsx]: Nit: This is another misleading `dataTestId` prop, where a user would think it's for _this_ component but it's really applied to a subcomponent

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx [hunk 9]
```diff
@@ -654,16 +676,14 @@ export function AssetPickerModal({
                   onChange={(value) => {
                     // Cancel previous asset metadata fetch
                     abortControllerRef.current?.abort();
+                    debouncedSetSearchQuery.cancel();
```
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx]: Nit: I don't think this cancellation is helpful, since the `setSearchQuery` call will trigger a `debouncedSetSearchQuery ` call, which will effectively replace whatever the pending update was (if there was one). If I'm understanding this correctly at least. Shouldn't hurt significantly, but seems like a no-op essentially.

File: ui/pages/bridge/prepare/bridge-input-group.tsx [hunk 10]
```diff
@@ -117,11 +117,17 @@ export const BridgeInputGroup = ({
     amountFieldProps?.readOnly || amountFieldProps?.disabled;
 
   useEffect(() => {
-    if (!isAmountReadOnly && inputRef.current) {
+    if (!amountFieldProps?.disabled && inputRef.current) {
```
Comment (Gudahtt) [inline ui/pages/bridge/prepare/bridge-input-group.tsx]: Interesting - what was the purpose of this change?

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx [hunk 11]
```diff
@@ -411,6 +396,25 @@ const PrepareBridgePage = () => {
...
+        token_symbol_source: fromToken?.symbol ?? '',
+        token_address_source: fromToken?.address ?? '',
+        chain_id_destination: formatChainIdToCaip(toChain?.chainId ?? ''),
+        token_symbol_destination: toToken?.symbol ?? '',
+        token_address_destination: toToken?.address ?? '',
+      },
+    });
+
+    return () => {
+      debouncedUpdateQuoteRequestInController.cancel();
```
Comment (Gudahtt) [inline ui/pages/bridge/prepare/prepare-bridge-page.tsx:414]: Hmm. This `debouncedUpdateQuoteRequestInController` function is another case where it's not really being debounced, because it's re-run every render.

Whereas this cleanup function only runs on _unmount_, so it's only going to cancel the debounce from the _first render_.

I expect this change to not have a significant impact, unless we update `debouncedUpdateQuoteRequestInController` to use `useCallback` like with the `asset-picker-modal` debounced search query.

File: ui/pages/bridge/prepare/bridge-input-group.tsx [hunk 12]
```diff
@@ -117,11 +117,17 @@ export const BridgeInputGroup = ({
...
       inputRef.current.value = amountFieldProps?.value?.toString() ?? '';
       inputRef.current.focus();
     }
-  }, [amountFieldProps?.value, isAmountReadOnly, token]);
+  }, [amountFieldProps?.value, amountFieldProps?.disabled, token]);
+
+  useEffect(() => {
```
Comment (Gudahtt) [inline ui/pages/bridge/prepare/bridge-input-group.tsx:126]: Hmm. I'm guessing that we were leaking this element somehow.

I thought refs were tied to the component lifecycle, so after unmount, nothing should be referencing it anymore? Unless we had another closure in this component that was keeping it alive somehow.

Ah well. Doesn't hurt to explicitly set it to null either way.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx (hunk 9 above)
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx]: You're right - removing this line

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx (hunk 11 above)
Comment (micaelae) [reply ui/pages/bridge/prepare/prepare-bridge-page.tsx:414]: Wrapped it in useCallback!

File: ui/pages/bridge/prepare/bridge-input-group.tsx (hunk 10 above)
Comment (micaelae) [reply ui/pages/bridge/prepare/bridge-input-group.tsx]: This doesn't change anything, it was an intermediate change that should've been undone but I reverted the commit that does that. Will revert these lines back

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx [hunk 13]
```diff
@@ -426,7 +430,6 @@ describe('AssetPickerModal token filtering', () => {
     isOpen: true,
     onClose: jest.fn(),
     onAssetChange: onAssetChangeMock,
-    autoFocus: true,
```
Comment (Gudahtt) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx:429]: This is causing the lint error I think

**Review by Gudahtt — COMMENTED** [review]
LGTM once the lint error is fixed! I was no longer able to reproduce the out-of-memory error I was seeing before

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
Comment (micaelae) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx:1]: Will include this in a separate PR to keep this one small enough for cherry-picking

**Review by ejwessel — APPROVED** [review]

**Review by ghgoodreau — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
