### PR TITLE
fix: update useHistoricalPrices getShouldShowFiat selector

### LINKED ISSUE #38298: [Bug]: Could not fetch historical data in EVM token details after adding additional network HyperEVM
**Describe the bug**

After adding additional network HyperEVM, the graph in the token details of any EVM token cannot be displayed and message is `We could not fetch any historical data`

**Expected behavior**

Display token graphs

**Screenshots/Recordings**

Image

https://github.com/user-attachments/assets/c6bb14db-1c62-4e08-97e2-c52ce72a1032

**Steps to reproduce**

1. Go to Network manager
2. Add network HyperEVM
3. Click on any EVM token from the tokens list
4. Notice graph is not loading

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.11.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38730?quickstart=1)

## **Changelog**

CHANGELOG entry: show token charts when adding new network

## **Related issues**

Fixes: #38298

## **Manual testing steps**

See issue repro steps.

### **After**

https://www.loom.com/share/6e784a56eece47c185d7fc15c3ce5818

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Update useHistoricalPrices to pass a hex chainId to getShouldShowFiat by converting CAIP IDs when needed.
> 
> - **UI Hooks** (`ui/pages/asset/hooks/useHistoricalPrices.ts`):
>   - **Selector update**: Call `getShouldShowFiat(state, hexChainId)` instead of a global selector.
>   - **Chain ID handling**: Add `toHexChainId` helper and import `convertCaipToHexChainId` to convert CAIP chain IDs to hex before selector use.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9f8fffec0d348d5fa4d32d99752f3b0be003a2d8. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by sahar-fehri — APPROVED** [review]

File: ui/pages/asset/hooks/useHistoricalPrices.ts [hunk 1]
```diff
@@ -53,6 +54,21 @@ export const DEFAULT_USE_HISTORICAL_PRICES_METADATA: HistoricalPrices['metadata'
...
   };
 
+/**
+ * Converts a chain ID to hex format. If the chain ID is already in hex format, returns it as-is.
+ * If it's a CAIP chain ID, converts it to hex. Returns null if conversion fails.
+ *
+ * @param chainId - The chain ID to convert (Hex or CaipChainId).
+ * @returns The hex chain ID, or null if conversion fails.
+ */
+const toHexChainId = (chainId: Hex | CaipChainId): Hex | null => {
```
Comment (juanmigdr) [inline ui/pages/asset/hooks/useHistoricalPrices.ts:64]: Should this ever console log or error something like `provided format is not caip`

**Review by juanmigdr — APPROVED** [review]

File: ui/pages/asset/hooks/useHistoricalPrices.ts (hunk 1 above)
Comment (Prithpal-Sooriya) [reply ui/pages/asset/hooks/useHistoricalPrices.ts:64]: I think this is okay for now. But will keep an eye out if needed in future.
