### PR TITLE
I1966 ignore invalid pending nonces

### LINKED ISSUE #1966: Incorrectly high pending nonces can prevent any valid txs from being composed
If nonces are non-sequentially higher than the network confirmed nonce, we should ignore them when composing new transactions.

Really, they should fail in that case when composed.

### PR DESCRIPTION
**Pull request by danfinlay**
Fixes #1966 

Also fixes network nonce parsing.

### CODE REVIEW

File: app/scripts/lib/nonce-tracker.js [hunk 1]
```diff
@@ -74,38 +88,18 @@ class NonceTracker {
     // and pending count are from the same block
     const currentBlock = await this._getCurrentBlock()
     const blockNumber = currentBlock.blockNumber
-    const baseCountHex = await this.ethQuery.getTransactionCount(address, blockNumber)
-    const baseCount = parseInt(baseCountHex, 16)
+    const baseCountBN = await this.ethQuery.getTransactionCount(address, blockNumber)
+    const baseString = baseCountBN.toString()
+    const baseCount = parseInt(baseString)
```
Comment (kumavis) [inline app/scripts/lib/nonce-tracker.js]: Always specify base for parseInt

File: app/scripts/lib/nonce-tracker.js [hunk 2]
```diff
@@ -74,38 +88,18 @@ class NonceTracker {
     // and pending count are from the same block
     const currentBlock = await this._getCurrentBlock()
     const blockNumber = currentBlock.blockNumber
-    const baseCountHex = await this.ethQuery.getTransactionCount(address, blockNumber)
-    const baseCount = parseInt(baseCountHex, 16)
+    const baseCountBN = await this.ethQuery.getTransactionCount(address, blockNumber)
+    const baseString = baseCountBN.toString()
```
Comment (kumavis) [inline app/scripts/lib/nonce-tracker.js]: FYI there's a to number method

File: app/scripts/lib/nonce-tracker.js [hunk 3]
```diff
@@ -127,6 +121,17 @@ class NonceTracker {
     return highestNonce
   }
 
+  _getHighestContinuousFrom (txList, startPoint) {
+    const nonces = txList.map((txMeta) => parseInt(txMeta.txParams.nonce, 16))
```
Comment (kumavis) [inline app/scripts/lib/nonce-tracker.js]: This does assume nonce on txParams is always hex 
Not sure if that's enforced anywhere

**Review by kumavis — CHANGES_REQUESTED** [review]

**Comment by kumavis** [comment]
I like the highest continuous, that's a good idea

**Review by kumavis — APPROVED** [review]
