### PR TITLE
fix: Use `toUnicode` function to normalize ens domains in the UI

### LINKED ISSUE #28610: [Bug]: Send to ENS emojis domain - Wrong handling of emojis ENS domains
### Describe the bug

Whenever we try to perform a send tx to an address with an ENS domain which uses emojis, like 😉️😉️😉️.eth with Nicknames disabled, we can see in 2 places how this is not correctly handled:
- in the case of old transactions screens, we can see this value in the recipient `xn-n28haa.eth` for the last confirmation page
- in both redesigned and non redesigned, after performing the transaction, we can see the recipient `xn-n28haa.eth`  in the tx receipt

### Expected behavior

I think for the old transaction screens, that could be left unfixed, since this will be fixed in the new redesigned screens.
For the transactions details, once that tx has been send, the recipient should be fixed.

### Screenshots/Recordings

In the Transaction receipt, I can see the wrong "parsing" of that ENS domain:

Screenshot from 2024-11-21 13-25-35

In the non redesign transactions, I can also see the wrong parsing in the last Confirmation screen:

https://github.com/user-attachments/assets/c64e7b9e-43d5-4b8a-aa52-e032c6aaafd2

### Steps to reproduce

1. Disable allow nicknames from experimental settings
2. Disable Improved Transaction Requests from experimental settings
3. Start a send to this account `0x02d8B596130Fc2d8263d32F4f08a92d1761f2e86
4. See how in the last confirmation page is displayed `xn-n28haa.eth`
5. Enable Improved Transaction REquests
6. Perform a complete send flow
7. Wait until tx is confirmed
8. Check tx receipt info --> see how recipient is `xn-n28haa.eth`

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.6.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

In `ENSController`(https://github.com/MetaMask/core/blob/main/packages/ens-controller/src/EnsController.ts#L375) right before saving the ens domain in the state we use `toASCII`. This function is typically used to convert a domain name from its Unicode representation to ASCII, specifically using the `Punycode` package encoding. This is necessary because the Domain Name System (DNS) operates with ASCII characters, and internationalized domain names (IDNs) need to be converted to a format that DNS can understand.

On the other side, in the client, we are not converting/normalizing this domain value. That is causing that unwanted ASCII coded domain in the UI when using smileys in the ENS domain.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29231?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28610

## **Manual testing steps**

See https://github.com/MetaMask/metamask-extension/issues/28610 for repro steps

### **Before**

Screenshot 2024-12-16 at 13 37 04

### **After**

Screenshot 2024-12-16 at 13 36 32

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/ui/sender-to-recipient/sender-to-recipient.component.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ import PropTypes from 'prop-types';
 import classnames from 'classnames';
 import copyToClipboard from 'copy-to-clipboard';
 import { NameType } from '@metamask/name-controller';
+import { toUnicode } from 'punycode';
```
Comment (jpuri) [inline ui/components/ui/sender-to-recipient/sender-to-recipient.component.js:6]: `punycode` lib I think is deprecated, we should avoid using it

File: ui/components/ui/sender-to-recipient/sender-to-recipient.component.js [hunk 2]
```diff
@@ -129,11 +130,13 @@ export function RecipientWithAddress({
...
   }
 
+  const normalizedEnsRecipientName = toUnicode(recipientEns);
+
   const displayName =
     (recipientName ||
       recipientNickname ||
       recipientMetadataName ||
-      recipientEns ||
+      normalizedEnsRecipientName ||
```
Comment (matthewwalsh0) [inline ui/components/ui/sender-to-recipient/sender-to-recipient.component.js:139]: Will we have this issue rendering ENS proposed names in petnames, and anywhere the ENS controller state is used?

Could we fix this deeper in the `getEnsResolutionByAddress` selector perhaps so we don't have to manually do this for each usage?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/components/ui/sender-to-recipient/sender-to-recipient.component.js (hunk 1 above)
Comment (OGPoyraz) [reply ui/components/ui/sender-to-recipient/sender-to-recipient.component.js:6]: I don't think we should rely on any other package before removing the `toASCII` util from `ENSController` - these utils match each other since both using same encoding from `punycode` package

File: ui/components/ui/sender-to-recipient/sender-to-recipient.component.js (hunk 2 above)
Comment (OGPoyraz) [reply ui/components/ui/sender-to-recipient/sender-to-recipient.component.js]: Make sense to do that casting on deeper, done.

File: ui/components/ui/sender-to-recipient/sender-to-recipient.component.js (hunk 1 above)
Comment (jpuri) [reply ui/components/ui/sender-to-recipient/sender-to-recipient.component.js]: In that case, will be nice to mention that as a comment here.

Comment (OGPoyraz) [reply ui/components/ui/sender-to-recipient/sender-to-recipient.component.js]: Good call, added a comment.

File: ui/components/ui/sender-to-recipient/sender-to-recipient.component.js [hunk 3]
```diff
@@ -129,11 +130,13 @@ export function RecipientWithAddress({
...
       shortenAddress(checksummedRecipientAddress)) ??
     (!addressOnly && t('newContract'));
```
[the remark this answers is not in the document]
Comment (OGPoyraz) [reply ui/components/ui/sender-to-recipient/sender-to-recipient.component.js]: Since it's moved in to selector and we are not adding any test on them, I will skip and won't add it.

**Review by jpuri — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by ZbrancaI** [comment]
Hey @OGPoyraz! I just tested it on the Chrome build for 12.11.0, and it didn't work. It doesn't display the ENS domain for this address: 0x02d8B596130Fc2d8263d32F4f08a92d1761f2e86

Uploading Screen Recording 2025-01-29 at 9.58.18 PM.mov…

**Comment by sleepytanya** [comment]
I can't reproduce the bug in 12.11.0 (we don't have the option to Disable improved transaction requests in 12.11.0):


https://github.com/user-attachments/assets/992e1db6-eefb-40dd-beb4-b290686a05ed

**Comment by seaona** [comment]
> I just tested it on the Chrome build for 12.11.0, and it didn't work. It doesn't display the ENS domain for this address: 0x02d8B596130Fc2d8263d32F4f08a92d1761f2e86

hi there :wave: I'm not able to see the video you attached above :thinking: Could you review it?
From my end, I see the issue the domain resolving correctly in the tx receipt (instead of the wrong parsing) and as Tanya mentions above, we cannot follow the repro steps 100% anymore as Disable improved transaction requests is not available in recent versions

https://github.com/user-attachments/assets/80520109-6c75-4e59-8831-f41ded967502

Let me know if this makes sense!
