### PR TITLE
fix: extension update prompt in popup cp-12.23.1

### LINKED ISSUE #34334: [Bug]: Extension update prompt does not work in popup
### Describe the bug

The "Update extension to the latest version" button in the update prompt does not work correctly in the browser-action popup. The button opens the "updating" page, but the extension does not actually update.

It works correctly in the fullscreen view, just not the browser-action popup.

### Expected behavior

The button should reload the extension, triggering the update.

### Screenshots/Recordings

There was a recording shared on Slack: https://consensys.slack.com/archives/CTQAGKY5V/p1752674641552489?thread_ts=1752090932.760239&cid=CTQAGKY5V

### Steps to reproduce

* Install the extension from the store, leaving the browser window open
* Publish a new extension release to 100%
* Set the minimum extension version remote feature flag to the new version
* Wait for the prompt to appear locally
  * I'm not yet sure how to trigger this reliably
* Click the "Update extension to the latest version" button on the prompt when it appears

This should be possible to test locally using this tool: https://github.com/GoogleChromeLabs/extension-update-testing-tool but I am not 100% sure of the steps yet.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.22.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by itsyoboieltr**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34372?quickstart=1)

This PR fixes the "Update extension to the latest version" button in the update prompt to make it work correctly in the browser-action popup. 

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34334

## **Manual testing steps**

1. Extension should be reloaded when the button is clicked in the browser-action popup.

### **Before**

https://github.com/user-attachments/assets/e9d25c25-2ede-4bff-800f-bca9cb69d9a6

### **After**

https://github.com/user-attachments/assets/bcbd1248-0674-4c96-98a5-b5b254e043a6

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by itsyoboieltr** [comment]
> ### Bug: Update Button Stuck Due to Missing Error Handling
> Missing error handling for `openUpdateTabAndReload()` causes the `isLoading` state to remain `true` if the function throws an error. This leaves the update button permanently disabled and unresponsive, as `setIsLoading(false)` is not reached. Unlike the previous implementation which allowed users to retry, this prevents any further interaction. The call should be wrapped in a `try-finally` block to ensure the loading state is always reset.
> 
> `ui/components/app/update-modal/update-modal.tsx#L71-L76`
> [Fix in Cursor](https://cursor.com/open?data=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJ1Z2JvdC12MSJ9.eyJ2ZXJzaW9uIjoxLCJ0eXBlIjoiQlVHQk9UX0ZJWF9JTl9DVVJTT1IiLCJkYXRhIjp7InJlZGlzS2V5IjoiYnVnYm90OjFkNWJmMzBkLWEwMjUtNGE0My05YWVhLTgzNTMyMmEwYzBmNCIsImVuY3J5cHRpb25LZXkiOiIwazVfckdrYTJ6aGpRdkJxeWFXcDNTSWQwVDhuU05hV3k0VEpmaTdMUHZZIiwiYnJhbmNoIjoiZml4L2V4dGVuc2lvbi11cGRhdGUtcHJvbXB0LWluLXBvcHVwIn0sImlhdCI6MTc1Mjc4Mjc0NSwiZXhwIjoxNzUzMzg3NTQ1fQ.YbEqztGZ7bZvsbgPISBgH4AoZ0NMyizOHeTACjwgKJE0VNEAzFoZPug1rm_AmEpuKJAxR0N__5hDo5ORSDcFeSC8u3aI5ACKMqbfv_mP21uA3S4Xc-cGcDmVZaRu2OvUdyIkzdMq9Av3f44jUf8uhzaTKvoEoyZnpkBuExgIQorbZfr8YU3eH_D-xRkqEbSpDvTdQ9RlX3s4cAMkFlXKI5YUWcPO0INOBTQyjOtmNfjift7dTei_wyNoWo9qnJj2ZkCi2TfKZe26iRWl05Q6n6h0GhC2WKrZ7KLwt38LEu8D0LINzwfxRHqDetKI7AZKP_bCdeZi_LC1c44kVk90mA) • [Fix in Web](https://cursor.com/agents?data=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJ1Z2JvdC12MSJ9.eyJ2ZXJzaW9uIjoxLCJ0eXBlIjoiQlVHQk9UX0ZJWF9JTl9XRUIiLCJkYXRhIjp7InJlZGlzS2V5IjoiYnVnYm90OjFkNWJmMzBkLWEwMjUtNGE0My05YWVhLTgzNTMyMmEwYzBmNCIsImVuY3J5cHRpb25LZXkiOiIwazVfckdrYTJ6aGpRdkJxeWFXcDNTSWQwVDhuU05hV3k0VEpmaTdMUHZZIiwiYnJhbmNoIjoiZml4L2V4dGVuc2lvbi11cGRhdGUtcHJvbXB0LWluLXBvcHVwIiwicmVwb093bmVyIjoiTWV0YU1hc2siLCJyZXBvTmFtZSI6Im1ldGFtYXNrLWV4dGVuc2lvbiIsInByTnVtYmVyIjozNDM3MiwiY29tbWl0U2hhIjoiOTQyZDIyZTc1YTExMDViMTM5YzM4NjczM2IzMDY0ZTExZGI0NzVhOSJ9LCJpYXQiOjE3NTI3ODI3NDUsImV4cCI6MTc1MzM4NzU0NX0.UyRIBI0VzTfRV8M9jsCl9Uhndu1MF50g1D1qq62CQIzHn3iPVXl5217AGn1MdZ7yTOr97AEDplRjrAuG2cwsgcAvZgEMTQ5wYWWmD913Jdnp5lXoI5wj0-WQPnIlL61R6Fmg9bOJiEaRPuBL8KsBiUMzZHXcbjkTM611TWZy9QKaALTHSxktN33KaCMhLISJa7vad22z3oMQ_DEm1_Pu36UjhunCgWHaOG5EOMHrMfDZqPV_hkeV-DzGl7WKcBEwJcgleJaVHCqtlIB2erCHMabvqrhx1K8jbzQ2QLs50TiMwR1AEp7y9_HbdBpxCbFO1aK_gO6kD-m7r-0016zV6g)
> 
> _Was this report helpful? Give feedback by reacting with 👍 or 👎_

There is already a try catch inside `openUpdateTabAndReload()` to handle any errors. `setIsLoading(false)` should never be reached anyway, as the extension reloads, closing the app before that line of code is reached. I don't believe this is a real issue.

File: app/scripts/lib/open-update-tab-and-reload.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import browser from 'webextension-polyfill';
+import type MetamaskController from '../metamask-controller';
+
+export async function openUpdateTabAndReload(
```
Comment (davidmurdoch) [inline app/scripts/lib/open-update-tab-and-reload.ts:14]: JSDoc comment pls. :-0

File: ui/components/app/update-modal/update-modal.tsx [hunk 2]
```diff
@@ -70,18 +70,14 @@ function UpdateModal() {
...
-                url: 'https://metamask.io/updating',
-                active: true,
-              });
-            } catch (error) {
-              console.error(error);
-            }
-            await requestSafeReload();
+            setIsLoading(true);
+            await openUpdateTabAndReload();
+            setIsLoading(false);
```
Comment (davidmurdoch) [inline ui/components/app/update-modal/update-modal.tsx]: Not requesting a change here, since I'd much rather ship this sooner, rather than polish an error experience no one is likely to ever see! But its good to know:

The general pattern for loading -> await doThingForAWhile() -> notLoading is to do the "notLoading" part in a `finally` block, and add error handling in the `catch` block if the `await doThingForAWhile()` step rejects.

Again, I don't think you should make changes here to this (as it was technically already a "problem"). Just something I noticed and thought i'd mention.

File: ui/store/actions.ts [hunk 3]
```diff
@@ -7043,6 +7043,10 @@ export async function requestSafeReload() {
   return await submitRequestToBackground('requestSafeReload');
 }
 
+export async function openUpdateTabAndReload() {
```
Comment (davidmurdoch) [inline ui/store/actions.ts:7053]: JSDoc, pls. :-)

**Review by davidmurdoch — CHANGES_REQUESTED** [review]

File: app/scripts/lib/open-update-tab-and-reload.ts [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+  metamaskController: MetamaskController,
```
Comment (Gudahtt) [inline app/scripts/lib/open-update-tab-and-reload.ts]: We should only be passing in `requestSafeReload` here. Passing in the controller instance itself grants too many capabilities to this little function, it doesn't align with the principle of least privilege. And it'll make it much harder to write a unit test for.

File: app/scripts/lib/open-update-tab-and-reload.ts (hunk 1 above)
Comment (Gudahtt) [inline app/scripts/lib/open-update-tab-and-reload.ts:14]: Nit: Could use a TSDoc block here. e.g.

```suggestion
/**
 * Open the "Updating" page in a new tab, then reload the browser.
 *
 * This is called to initiate an update when one is available.
 */
export async function openUpdateTabAndReload(
```

It needs `@param` as well, but I left it out because I just suggested a param change in another comment

File: app/scripts/lib/open-update-tab-and-reload.ts
Comment (Gudahtt) [inline app/scripts/lib/open-update-tab-and-reload.ts:1]: Nit: We should write unit tests for this (e.g. to test that the reload still happens when opening a tab fails, and to test that both functions are called by the time it resolves).

File: ui/components/app/update-modal/update-modal.tsx (hunk 2 above)
Comment (itsyoboieltr) [reply ui/components/app/update-modal/update-modal.tsx]: fixed

File: app/scripts/lib/open-update-tab-and-reload.ts (hunk 4 above)
Comment (itsyoboieltr) [reply app/scripts/lib/open-update-tab-and-reload.ts]: fixed

File: app/scripts/lib/open-update-tab-and-reload.ts (hunk 1 above)
Comment (itsyoboieltr) [reply app/scripts/lib/open-update-tab-and-reload.ts:14]: fixed

**Review by davidmurdoch — DISMISSED** [review]

**Comment by Gudahtt** [comment]
I have updated the title to remove `cp-13.0.0` because we are considering including this in v12.23.0 instead, which isn't open as an RC right now. We can manually bring it into whichever release we decide to put it in.

**Review by Gudahtt — DISMISSED** [review]
LGTM! I tested that the button still works when clicked from the popup.

File: app/scripts/lib/open-update-tab-and-reload.ts
Comment (itsyoboieltr) [reply app/scripts/lib/open-update-tab-and-reload.ts:1]: added

File: app/scripts/lib/open-update-tab-and-reload.test.ts [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+
+describe('openUpdateTabAndReload', () => {
+  const mockRequestSafeReload = jest.fn();
+
+  beforeEach(() => {
+    jest.clearAllMocks();
+  });
+  afterEach(() => {
+    jest.restoreAllMocks();
+  });
```
Comment (Gudahtt) [inline app/scripts/lib/open-update-tab-and-reload.test.ts]: Nit: This happens automatically after each test already, so we shouldn't need this (see the `restoreMocks` option in our jest config)

```suggestion
```

Comment (itsyoboieltr) [reply app/scripts/lib/open-update-tab-and-reload.test.ts]: fixed

**Review by Gudahtt — DISMISSED** [review]

File: app/scripts/lib/open-update-tab-and-reload.test.ts [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+  tabs: {
+    create: jest.fn(),
+  },
+}));
+
+describe('openUpdateTabAndReload', () => {
+  const mockRequestSafeReload = jest.fn();
+
+  beforeEach(() => {
+    jest.clearAllMocks();
```
Comment (Gudahtt) [inline app/scripts/lib/open-update-tab-and-reload.test.ts]: Generally we should be using `resetAllMocks` over `clearAllMocks` - it does the same as clear but _also_ resets mock implementations, helping to avoid accidentally influencing one test from another. We have a ticket for enabling `resetMocks` in the Jest config, but we've been working towards that slowly by manually adding `resetAllMocks` to each test suite, to avoid having to fix dozens of test suites in one go.

But w/e, we can deal with this in a later PR, and we already have a ticket tracking this anyway. Just mentioning for future reference.

Comment (itsyoboieltr) [reply app/scripts/lib/open-update-tab-and-reload.test.ts]: fixed

**Review by Gudahtt — APPROVED** [review]

**Review by davidmurdoch — APPROVED** [review]
