### PR TITLE
fix: handle low numbers when saving default advanced gas fees

### LINKED ISSUE #22605: [Bug]: VM410:1 MetaMask - RPC Error: while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+).
### Describe the bug

I was saving default values to Advance Settings gas ettings for my Besu-based private network with zero gas fee.

The fees was set to 0.0000000001 and "saved to remember"

The next transactions then are failing for that network.

### Expected behavior

Should work as usual

### Screenshots/Recordings

_No response_

### Steps to reproduce

I was saving default values to Advance Settings gas ettings for my Besu-based private network with zero gas fee.

The fees was set to 0.0000000001 and "saved to remember"

The next transactions then are failing for that network.

### Error messages or log output

```shell
main.06f2c52bf3ee3881.js:1 ERROR Error: Uncaught (in promise): Error: while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+).
{
  "originalError": {}
}
Error: while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+).
{
  "originalError": {}
}

---

code
: 
-32603
data
: 
"{\n  \"originalError\": {}\n}"
message
: 
"while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+)."
```

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

Very needed for testing out free gas network (besu) interaction with metamask

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**
This PR aims to fix a bug when a user saves very low default values, in the example `0.000000001` number was turned into `1e-9` string and thrown when converting it down the line in the next transaction.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/22605

## **Manual testing steps**

1. Go to send flow
2. Edit gas fee > Advanced
3. Change `Max Base Fee` `1` and `Priority Fee` to `0.000000001`
4. Check `Save these values as my default for the <chain name> network.`

I was able to reproduce the issue using Ganache with default gas zero.

### **Before**

[before_fix_gas.webm](https://github.com/MetaMask/metamask-extension/assets/45455812/59728401-bac2-468b-a82c-2e577df32718)

### **After**

[advance-gas.webm](https://github.com/MetaMask/metamask-extension/assets/45455812/dd6b09c9-d1c6-4cff-9efc-5cc7da452fb4)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by DDDDDanica — DISMISSED** [review]

**Comment by DDDDDanica** [comment]
LGTM!

**Comment by sleepytanya** [comment]
@vinistevam Build from https://github.com/MetaMask/metamask-extension/commit/38d63f8a9cf05be24c39d1495a0236b0b7e71b96] - it won't let me type 0 after decimal point:


https://github.com/MetaMask/metamask-extension/assets/104780023/bf32a906-91f2-4b00-8574-6b5cb9a7d052

I can cut and paste 0.000000001 but it results in Failed transaction.

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ import { bnGreaterThan, bnLessThan } from '../../../../../helpers/utils/util';
 import { useAdvancedGasFeePopoverContext } from '../../context';
 import AdvancedGasFeeInputSubtext from '../../advanced-gas-fee-input-subtext';
 import { decGWEIToHexWEI } from '../../../../../../shared/modules/conversion.utils';
+import { Numeric } from '../../../../../../shared/modules/Numeric';
 
 const validatePriorityFee = (value, gasFeeEstimates) => {
   if (value < 0) {
```
[the remark this answers is not in the document]
Comment (vinistevam) [reply ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js]: Yeap apart from the `FormField`  setting the `value` as `number` the rest of the code treating as a `string`. I'm pushing the changes to treat it as `Numeric` in both of the components for consistency as you suggested and remove the  `bnGreaterThan, bnLessThan`.

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js [hunk 2]
```diff
@@ -81,7 +82,7 @@ const BaseFeeInput = () => {
 
   const updateBaseFee = useCallback(
     (value) => {
-      setBaseFee(value);
+      setBaseFee(new Numeric(value, 10)?.toString());
```
Comment (matthewwalsh0) [inline ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js:85]: Is the core fix here that `toString` from `Numeric` doesn't use scientific notation?

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.test.js [hunk 3]
```diff
@@ -147,4 +175,23 @@ describe('BaseFeeInput', () => {
...
+  describe('updateBaseFee', () => {
+    it('updates base fee correctly', () => {
+      const { getByTestId } = render(<BaseFeeInput />);
+      const input = getByTestId('base-fee-input');
+
+      fireEvent.change(input, { target: { value: '1' } });
+
+      expect(input.value).toBe('1');
+    });
+    it('handles low numbers', () => {
```
Comment (matthewwalsh0) [inline ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.test.js:188]: Minor, but line break?

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js (hunk 2 above)
Comment (vinistevam) [reply ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js:85]: Yes, converting using `Numeric` properly saves as `string`. 
The underlying issue is that the `value` is coming from the `FormField` component as `number` and it saves as `string` with scientific notation (when using more than 6 decimal places) as a result it gets stuck the next time you try to send a transaction.

Ideally, it should always be `string`, I will open a ticket apart, maybe refactor the component or use `FormTextField` with type `string`, if necessary preventing non-decimals, but all of it will also involve layout changes.

**Comment by sleepytanya** [comment]
Low values can be entered and saved correctly.
Chrome 121.0.6167.139 

https://github.com/MetaMask/metamask-extension/assets/104780023/5556ff20-02b5-4c6e-bd98-49d39d1f14c7

Firefox 122.0 



https://github.com/MetaMask/metamask-extension/assets/104780023/10c4f4da-6a60-4b00-b1ac-edd34e8e2509

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (vinistevam) [reply ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js]: We should be ok with rounding numbers up to 1 Wei (0.000000001 Gwei).
I agree this is relevant for every piece that uses this component with decimals. I need to check maybe the `FormTextField` component doesn't have this limitation. The only issue I saw when changing to `string` in the component is the visual, so UX would also need to be involved.
Here is [the ticket to track the precision issue](https://github.com/MetaMask/metamask-extension/issues/21470).  
This fix ensures that we can handle low numbers when checking the "Save these values as my default..." option.

**Review by dbrans — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
