### PR TITLE
fix: fix network switch on dapp

### LINKED ISSUE #30149: [Bug]:When a network switch is initiated from within a dApp, the wallet transitions to the correct network, the token list remains reflective of the previously selected network, the network selector switches to the "Popular Networks" view
### Describe the bug

When a network switch is initiated from within a dApp, the wallet transitions to the correct network, the token list remains reflective of the previously selected network, the network selector switches to the "Popular Networks" view.

### Expected behavior

 The token list and network view accurately align with the newly selected network. 

### Screenshots/Recordings

Netwotk selected from SushiSwap:

https://github.com/user-attachments/assets/ee586472-e2cd-4c2e-93fd-1ae9b94d833a

Network selected from OpenSea:

https://github.com/user-attachments/assets/222a54ac-c909-44a4-adb2-e25490f3a261

### Steps to reproduce

1. Connect to a dapp
2. From within the dapp select the network other than the currently selected one
3. Navigate back to the wallet

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.12.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30211?quickstart=1)

## **Related issues**

Fixes: #30149 

## **Manual testing steps**

1. Go to dapp ( sushi swap for instance )
2. switch network
3. check the list of tokens

### **After**

https://github.com/user-attachments/assets/14760fbf-f8ad-4753-867b-478822a37bd0

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -6120,6 +6120,15 @@ export default class MetamaskController extends EventEmitter {
...
             this.networkController,
           ),
+        setTokenNetworkFilter: (chainId) => {
+          const { tokenNetworkFilter } =
+            this.preferencesController.getPreferences();
+          if (chainId && Object.keys(tokenNetworkFilter).length === 1) {
+            this.preferencesController.setPreference('tokenNetworkFilter', {
+              [chainId]: true,
+            });
+          }
```
Comment (Prithpal-Sooriya) [inline app/scripts/metamask-controller.js:6130]: Hmmm what is this condition doing here?

```
Object.keys(tokenNetworkFilter).length === 1
```
this related to portfolio view (you are only viewing tokens from 1 network).

```
this.preferencesController.setPreference(... {[chainId]: true})
```
this is to swap to the other network?

Comment (Prithpal-Sooriya) [reply app/scripts/metamask-controller.js:6130]: So if I am in portfolio view, and I switch networks from a dapp, I stay in portfolio view?
But what if it is a not popular network?

Comment (salimtb) [reply app/scripts/metamask-controller.js:6130]: what we're doing is checking if the chainId is defined and whether the tokenNetworkFilter corresponds to the current network—something like { '0x1': true }. Then, if we switch from Ethereum to BNB in the dapp, we would update this to { '0x38': true }.

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]

File: app/scripts/metamask-controller.js (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/scripts/metamask-controller.js:6130]: Yep nice. I've ran the branch and validated the fix.

This is a little confusing though, in the future do you think it would be worth moving this (token filter list) logic in a shared location/module/utilities? We can discuss this later.
