### PR TITLE
fix: add try catch to _addSolanaAccount cp-12.18.0

### LINKED ISSUE #32413: [Bug]: error when Basic Functionality is turned off during onboarding flow due to snaps
Image
Image

### Describe the bug

If Basic Functionality turned off during onboarding flow (i.e Privacy Settings)
this causes the app to hang when onboarding is complete. 

This is due to Snaps needing Basic Functionality. (error shown in screenshot)

### Expected behavior

I should be able to use the wallet and connect to the mainnet

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go through IMPORT onboarding flow (until Your Wallet is ready screen)
2. Click `Manager default privacy settings`
3. Click `General`
4. Toggle off `Basic Functionality`
5. Go back to main screen
6. Click `Done` and continue to finish onboarding

### Error messages or log output

```shell
sentry-install.js:1 Error#8: The Snaps platform requires basic functionality to be used. Enable basic functionality in the settings to use the Snaps platform.
```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This adds a try catch to `_addSolanaAccount` to not block the onboarding flow if it fails. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32421?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32413

## **Manual testing steps**

1. Go through IMPORT onboarding flow (until Your Wallet is ready screen)
2. Click Manager default privacy settings
3. Click General
4. Toggle off Basic Functionality
5. Go back to main screen
6. Click Done and continue to finish onboarding
7. See that you are able to go to the wallet overview.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by FrederikBolding — DISMISSED** [review]

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -4989,28 +4989,33 @@ export default class MetamaskController extends EventEmitter {
...
+          async ({ metadata }) => {
+            return metadata.id;
+          },
+        );
+        entropySource = id;
+      }
+
+      const client = await this._getSolanaWalletSnapClient();
+      return await keyring.createAccount(
+        snapId,
```
Comment (FrederikBolding) [inline app/scripts/metamask-controller.js:5006]:
```suggestion
      const client = await this._getSolanaWalletSnapClient();
      return await client.createAccount(
```
Typos?

**Review by FrederikBolding — APPROVED** [review]

**Review by darioAnongba — APPROVED** [review]
