### PR TITLE
Configure smart transactions controller to support goerli

### LINKED ISSUE #16477: [Bug]: Cannot perform a Swap with STX. TypeError: Cannot read properties of undefined (reading `findIndex`)
### Describe the bug

**Problem**: I cannot perform a Swap with Smart Transaction on **Goerli**, and I get the console error `TypeError: Cannot read properties of undefined (reading 'findIndex')` when `signAndSendSwapsSmartTransaction` is called.

https://user-images.githubusercontent.com/54408225/201640112-728da1eb-bb9e-42c1-b651-b6e8e6aa97a4.mp4

This then causes [this behaviour.](https://github.com/MetaMask/metamask-extension/issues/16479)

### Steps to reproduce

1. Unlock MM
2. Click Swap
3. Enable Smart Transaction
4. Confirm Swap
5. Check Ui console

### Error messages or log output

_No response_

### Version

develop b2e621b5f9ab67cdf50c6f8fe8e7c0bf19440e96

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #16479: [Bug]: Cannot perform a Send on Sepolia network. MM stays loading indefinitely
### Describe the bug

**Problem**: I cannot perform a Send on Sepolia network. MM stays loading. If I refresh the browser, I see that tx stays stuck on a  Pending state.

https://user-images.githubusercontent.com/54408225/201647673-fe2ae450-b191-4f70-ada0-2966c4e63023.mp4

### Steps to reproduce

1. Unlock MM
2. Change to Sepolia network
3. Click Send
4. Add recipient and input amounts
5. Confirm tx -- see MM stays loading indefinitely
6. Refresh the browser -- see tx stays Pending

### Error messages or log output

_No response_

### Version

10.23.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes #16477
Fixes #16479

An error was occuring on this line of the smart transactions controller https://github.com/MetaMask/smart-transactions-controller/blob/main/src/SmartTransactionsController.ts#L282. This was because the smart transaction state was not getting initialized on the goerli network (https://github.com/MetaMask/smart-transactions-controller/blob/main/src/SmartTransactionsController.ts#L169) because Goerli was not a "supported network"

This PR ensures the controller is properly configured to support the network, avoiding the undefined bug described in the two linked issues.

We should also make appropriate changes in the smart transaction controller (put Goerli in the default config, and prevent the type error), but this PR prevents the user from hitting this issue

### CODE REVIEW

**Comment by seaona** [comment]
There is some strange behaviour after submitting a Goerli Swap. Basically, the Swap tx appears on all the accounts, and even if I change the network,  I see the Swap tx on the other network.

https://user-images.githubusercontent.com/54408225/201894301-6a1e12d3-a2b0-4c5c-b06c-674850d1bbd3.mp4


If I then click for the tx details on this other network, I land on the MM error page, with the message `Cannot read properties of undefined (reading 'nonce')`

Screenshot from 2022-11-15 11-16-04


Another observation, when I check the Swap details on Goerli, I can see that `Gas price` has a value of `?` (see below). Is this expected?

image

**Review by dan437 — APPROVED** [review]

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -1014,7 +1014,9 @@ export default class MetamaskController extends EventEmitter {
           this.metaMetricsController,
         ),
       },
-      undefined,
+      {
+        supportedChainIds: [CHAIN_IDS.MAINNET, CHAIN_IDS.GOERLI],
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js:1018]: Should Rinkeby be in this list as well?

**Comment by Gudahtt** [comment]
The smart transactions controller update has been done in https://github.com/MetaMask/metamask-extension/pull/16511

File: app/scripts/metamask-controller.js (hunk 1 above)
Comment (danjm) [reply app/scripts/metamask-controller.js:1018]: Rinkeby isn't supported by the swap api any more, right @dan437?

(And infura doesn't support it anymore either. And its removed from our custom network list.)

**Comment by seaona** [comment]
:information_source: The issues I mentioned above are due to a number of different problems interacting with each other and will be handled in separate PRs, as @Gudahtt identified, they are:
- The nonce isn't released in some cases.
- The smart transaction controller crashes when a transaction is submitted on a network that is not supported.
- Goerli is not supported -- solved in this PR
- Pending smart transactions are being shown on the wrong networks.

**Review by Gudahtt — APPROVED** [review]
LGTM!
