### PR TITLE
fix button text props

### LINKED ISSUE #17477: Can't overwrite ButtonLink `textProps`
### Description
`ButtonLink` textProps doesn't work because `...props` are being spread before the `textProps` are being manipulated.

Move the `{...props}` to before the closing bracket

This doesn't work
Screenshot 2023-01-27 at 2 51 19 PM

Because spreading props is before the textProps manipulation
Screenshot 2023-01-27 at 2 51 36 PM

### PR DESCRIPTION
**Pull request by garrettbear**
## Explanation

textProps aren't properly working when being passed down

Fixes: #17477 

### After
Screenshot 2023-01-27 at 4 34 00 PM
Screenshot 2023-01-27 at 4 33 48 PM

## Manual Testing Steps

`yarn jest ui/components/component-library`

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by darkwing — DISMISSED** [review]

File: ui/components/component-library/button-link/button-link.js [hunk 1]
```diff
@@ -54,6 +57,10 @@ ButtonLink.propTypes = {
    * Default value is 'SIZES.AUTO'.
    */
   size: PropTypes.oneOf(Object.values(BUTTON_LINK_SIZES)),
+  /**
+   * textProps accepts all the props from Icon
```
Comment (georgewrmarshall) [inline ui/components/component-library/button-link/button-link.js:61]: Update prop type description to align with prop
```suggestion
   * textProps accepts all the props from Text component
```

**Review by georgewrmarshall — COMMENTED** [review]
Nice work! One small suggestion

**Review by georgewrmarshall — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
LGTM
