### PR TITLE
fix: reset to native asset on account change

### LINKED ISSUE #24391: [Bug]: Switching Account During NFT Send Doesn't Clear NFT as Send Asset
### Describe the bug

Presently the Account Picker is enabled during the Send flow.   When sending a NFT and switching account mid-send-flow, the asset picker still shows the NFT as the asset to send.  Thus, the user appears to be able to send an NFT from another account.

### Expected behavior

The NFT should be cleared from the AssetPicker and probably the native currency should become the asset to send, with a value of `0`

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/46655/021c71aa-6221-48bc-bc43-309b5573e147

### Steps to reproduce

1.  Choose account 1 which has an NFT
2. Choose the NFTs tab, click on the NFT 
3. Click on the Send button
4. Choose a recipient 
5. Switch to account 2
6. BUG:  see the NFT still in the account picker

### Error messages or log output

_No response_

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bergeron**
## **Description**

Fixes an issue when you changed accounts while sending an NFT.  It would keep the NFT asset, even though the new account doesn't own it.  Reset to the native asset instead.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24398?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24391

## **Manual testing steps**

1. Prepare a transaction to send an NFT
2. Before clicking Next, change accounts
3. It should reset to ETH/native token. 

### **Before**

https://github.com/MetaMask/metamask-extension/assets/3500406/7628c507-a694-4bf9-8d1b-e828f7a8cdc7

### **After**

https://github.com/MetaMask/metamask-extension/assets/3500406/1ac60586-cf97-47bc-9f4e-1e518b8a053b

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sahar-fehri** [comment]
Thnx for the fix! 🙏

**Review by sahar-fehri — APPROVED** [review]

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -1664,9 +1664,11 @@ const slice = createSlice({
               draftTransaction.asset.balance = action.payload.account.balance;
             }
 
-            // If selected account was changed and selected asset is a token then
-            // reset asset to native asset
-            if (draftTransaction?.asset.type === AssetType.token) {
+            // Reset to the native asset when the account is changed
+            if (
+              draftTransaction?.asset.type === AssetType.token ||
+              draftTransaction?.asset.type === AssetType.NFT
```
Comment (salimtb) [inline ui/ducks/send/send.js:1670]: i suggest adding an e2e test for this case to avoid such behavior in the future.

**Review by salimtb — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
Thank you so much!
