### PR TITLE
fix: clicking back multiple times from metametrics page cp-13.0.0

### LINKED ISSUE #34543: [Bug]: Should not skip the metametric screen by click BACK on browser
### Describe the bug

When user in 2 flow:
- Import SRP
- Rehydrate login with social account
At the metametric screen, user click BACK many times on browser and it brings to Wallet is ready screen
User click Done to go ahead and skip the metametric screen

### Expected behavior

Should not skip the metametric screen when click BACK, and should not show Wallet is ready screen

### Screenshots/Recordings

https://github.com/user-attachments/assets/15549d1e-79ca-42a7-8c3d-df615b28ed7f

https://github.com/user-attachments/assets/07d5565f-0d19-4492-bdb7-249edd8483f4

### Steps to reproduce

See the video

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lionellbriones**
## **Description**
While on metametrics page, if user clicks on browser back button multiple times, he ends up on welcome route in the end. welcome routes redirects the user to completion page when it detects that a wallet has been created which is wrong.

It should first check if metametrics has been set. if it's been set redirect to metametrics else redirect to completion page.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34576?quickstart=1)

## **Changelog**

CHANGELOG entry: Fix incorrect redirection when clicking back multiple times from metametrics page

## **Related issues**

Fixes:
https://github.com/MetaMask/metamask-extension/issues/34543

## **Manual testing steps**

**Import SRP flow**
1. Install metamask
2. Import account using SRP
3. Continue onboarding upto metametrics page - don't submit the form
4. Click browser button multiple times
5. User should stay at metametrics page

**Social login flow**
1. Install metamask
2. Login with new or existing social account
3. Continue onboarding upto metametrics page
4. Click browser button multiple times
5. User should stay at metametrics page

### **Before**
https://github.com/user-attachments/assets/15549d1e-79ca-42a7-8c3d-df615b28ed7f

https://github.com/user-attachments/assets/07d5565f-0d19-4492-bdb7-249edd8483f4

### **After**
https://github.com/user-attachments/assets/ddc44802-d903-408b-9c74-0da13cee3f5d

https://github.com/user-attachments/assets/95e8e845-308b-44cc-8804-79d17a86984c

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/onboarding-flow/welcome/welcome.js [hunk 1]
```diff
@@ -61,9 +68,17 @@ export default function OnboardingWelcome({
...
       ) {
-        history.replace(ONBOARDING_COMPLETION_ROUTE);
+        history.replace(
+          isParticipateInMetaMetricsSet
+            ? ONBOARDING_COMPLETION_ROUTE
+            : ONBOARDING_METAMETRICS,
+        );
       } else if (firstTimeFlowType === FirstTimeFlowType.restore) {
-        history.replace(ONBOARDING_COMPLETION_ROUTE);
+        history.replace(
```
Comment (lwin-kyaw) [inline ui/pages/onboarding-flow/welcome/welcome.js]: just wanna check, there's a similar code in `ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js`, shouldn't it be working the same?

Comment (lionellbriones) [reply ui/pages/onboarding-flow/welcome/welcome.js]: no. onboarding board switch only triggers when user redirects to any route which is not part of **Onboarding** routes. one scenario where onboarding-switch is triggered is when user opens metamask from extension pin, it loads DEFAULT route by default

for this issue where user is just click back and forward between onboarding routes. onboard-switch is not triggered

File: ui/pages/onboarding-flow/welcome/welcome.js [hunk 2]
```diff
@@ -61,9 +68,17 @@ export default function OnboardingWelcome({
         firstTimeFlowType === FirstTimeFlowType.import ||
         firstTimeFlowType === FirstTimeFlowType.socialImport
       ) {
-        history.replace(ONBOARDING_COMPLETION_ROUTE);
+        history.replace(
+          isParticipateInMetaMetricsSet
+            ? ONBOARDING_COMPLETION_ROUTE
+            : ONBOARDING_METAMETRICS,
+        );
       } else if (firstTimeFlowType === FirstTimeFlowType.restore) {
```
Comment (tuna1207) [inline ui/pages/onboarding-flow/welcome/welcome.js]: seems like this case
```typescript
firstTimeFlowType === FirstTimeFlowType.import ||
firstTimeFlowType === FirstTimeFlowType.socialImport
```
and this case is similar, could we merge them
```typescript
        } else if (firstTimeFlowType === FirstTimeFlowType.restore) {
```

**Review by tuna1207 — DISMISSED** [review]

File: ui/pages/onboarding-flow/welcome/welcome.js (hunk 2 above)
Comment (lionellbriones) [reply ui/pages/onboarding-flow/welcome/welcome.js]: ah yes.. i updated the code.. thanks

File: ui/pages/onboarding-flow/welcome/welcome.js (hunk 1 above)
Comment (lwin-kyaw) [reply ui/pages/onboarding-flow/welcome/welcome.js]: ah I see. Thank you.

**Review by lwin-kyaw — APPROVED** [review]

**Comment by LeVinhGithub** [comment]
lgtm

**Review by tuna1207 — APPROVED** [review]
