### PR TITLE
fix: Do not throw an error when switching between queued dapp transactions

### LINKED ISSUE #29191: [Bug]: -  Queuing - MM breaks with the error `Minified React error` after queuing tx's and signatures from 2 different dapps
### Describe the bug

After queuing transactions and signatures from 2 different dapps, the wallet broke with the error ` MM breaks with the error `Minified React error`.
I don't know when this issue started happening, so cannot guarantee it's not in prod, until I find repro steps. I was testing 12.10.0

### Expected behavior

_No response_

### Screenshots/Recordings

Image

### Steps to reproduce

(investigating)

### Error messages or log output

```
Message: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Code: Error

Stack:

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  at ua (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:59982)
  at Object.Pa [as useMemo] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:64032)
  at n.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:184827)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-9.js:1:301976)
  at n.useFourByte (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-12.js:1:252393)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-12.js:1:263005
  at Array.map (<anonymous>)
  at n.useNestedTransactionLabels (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-12.js:1:262953)
  at n.QuotedSwapTransactionData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-12.js:1:361299)
  at sa (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:59431)
  at qa (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:68913)
  at Ys (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:112305)
  at Al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:98675)
  at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:98603)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:98466)
  at vl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:95463)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:45359
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:123741)
  at Hi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:45137)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:45305)
  at Ki (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:45240)
  at Fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:104502)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:123741)
  at Hi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:45137)
  at Ll (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:103788)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:103700
  at D (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:122801)
  at _.port1.onmessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-10.js:1:121526)

```

### Detection stage

During release testing

### Version

12.10.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by dan437**
## **Description**
Do not throw an error when switching between queued dapp transactions.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39128?quickstart=1)

## **Changelog**

CHANGELOG entry: Do not throw an error when switching between queued dapp transactions

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/29191

## **Manual testing steps**

1. Connect to dapp 1 (https://www.sushi.com/fantom/swap)
2. Connect to dapp 2 (https://app.uniswap.org/swap)
3. Add a new network from dapp1 and do not submit the transaction
4. Enter details for a swap on dapp 2, submit it
5. Switch between confirmations, it will no longer throw an error

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Prevents React hook-order errors when switching between confirmations from different dapps.
> 
> - Split `QuotedSwapTransactionData` into guarded wrapper + `...Content`; render only when `isQuotedSwapDisplayedInInfo` and `selectedQuote` are set, key by `selectedQuote.quote.requestId`, and pass empty arrays to `useNestedTransactionLabels` when `approval`/`trade` are absent
> - Update `AdvancedDetails` to always include `QuotedSwapTransactionData` (internal guard handles visibility)
> - Refactor `NestedTransactionTag` into wrapper + `...Content`; render only for valid batch with `> 1` items and key by `currentConfirmation.id`
> - Add tests covering transitions: defined→undefined quote, approval presence changes, batch→non-batch, and varying nested counts without throwing
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit c2d9bdc5b861464458055aebaf869731a3854aff. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

File: ui/pages/confirmations/components/confirm/info/shared/quote-transaction-data/quoted-transaction-data.tsx [hunk 1]
```diff
@@ -67,3 +73,24 @@ export const QuotedSwapTransactionData = () => {
...
+    return null;
+  }
+
+  return (
+    <QuotedSwapTransactionDataContent
+      key={selectedQuote.quote.requestId}
+      selectedQuote={selectedQuote}
+    />
+  );
+};
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/info/shared/quote-transaction-data/quoted-transaction-data.tsx:96]: Above change should not be needed as we are already doing these check in AdvanceDetailsSection.

Comment (dan437) [reply ui/pages/confirmations/components/confirm/info/shared/quote-transaction-data/quoted-transaction-data.tsx:96]: You're right that there was duplication. I've moved all the checks into QuotedSwapTransactionData itself and removed the conditional from AdvancedDetails. This makes the component self-contained - if it's used elsewhere, the guards are built-in.

**Review by jpuri — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
