### PR TITLE
fix: exclude smart transaction status page from rate limiting

### LINKED ISSUE #30387: [Bug]: Getting error - Request of type 'smartTransaction:showSmartTransactionStatusPage already pending for origin chrome extension://nkbihfbeogeaeaoehlefnkodbefgpgknn. Please wait."
### Describe the bug

Getting the issue in version 12.11.0

Encounter this problem when executing multiple transactions sequentially—specifically when a second transaction is triggered immediately after the successful completion of the first transaction.

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

In this version, the first MetaMask pop-up functions correctly, but the second pop-up may indicate a failure, even though the transaction will eventually be confirmed on the blockchain.

My observation is that if you do not close the extension—something you might do after the first transaction by clicking the "Close Extension" button—the next transaction loads within the same pop-up. This causes it to use outdated values from the initial load, leading to a simulated failure. However, the transaction does not fail in reality, as the previous transaction on the blockchain has already been completed.

### Error messages or log output

```shell
Request of type 'smartTransaction:showSmartTransactionStatusPage already pending for origin chrome extension://nkbihfbeogeaeaoehlefnkodbefgpgknn. Please wait."
```

### Detection stage

In production (default)

### Version

12.11.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

FYI, this issue does not occur if you close the extension after the first transaction and allow a new pop-up to open for the next transaction.

### Severity

_No response_

### PR DESCRIPTION
**Pull request by httpJunkie**
This change adds `smartTransaction:showSmartTransactionStatusPage` to the `typesExcludedFromRateLimiting` array when initializing the **ApprovalController**.

This prevents the **"Request of type 'smartTransaction:showSmartTransactionStatusPage' already pending"** error that was occurring when users executed sequential transactions in quick succession.

## **Description**

MetaMask's **ApprovalController** was rate-limiting `smartTransaction:showSmartTransactionStatusPage` requests, preventing users from viewing status pages for multiple sequential transactions.

The Issue:

Internal "request types" (string identifiers for operations) were being rate-limited
How: **ApprovalController** blocks multiple identical requests from the same source in a short period.

When users initiated sequential transactions, only the first transaction's status page appeared

The Fix:

Added smartTransaction:showSmartTransactionStatusPage to the `typesExcludedFromRateLimiting` array, exempting these requests from rate limiting.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30537?quickstart=1)

## **Related issues**

Fixes: #30387

## **Manual testing steps**

Repro Setup:

1. Run the following command to [clone and run the test dapp](https://github.com/httpJunkie/metamask-sequential-tx-repro) that reproduces this error:
```
git clone https://github.com/httpJunkie/metamask-sequential-tx-repro.git && / 
cd metamask-sequential-tx-repro && / 
yarn && / 
yarn dev
```
2. Cmd+Click on the localhost URL in terminal to run the dapp

Manually Test the Extension:

1. Load a version 12.13.0 or earlier version of MetaMask
2. Connect to Ethereum Mainnet (testnet seems harder to repro this bug)
3. Navigate to the test dapp
4. Connect your MetaMask wallet to the dapp
5. Click the "Send 3 Sequential Transactions" button
6. Approve transactions as prompted by MetaMask
7. Verify console errors containing 
```
Request of type 'smartTransaction:showSmartTransactionStatusPage' already pending
```
8. Install the updated MetaMask extension build containing the fix
9. Connect to Ethereum Mainnet
10. Navigate to the test dapp
11. Connect your MetaMask wallet to the dapp
12. Click the "Send 3 Sequential Transactions" button
13. Approve each transaction when prompted by MetaMask
14. Verify no console errors containing 
```
Request of type 'smartTransaction:showSmartTransactionStatusPage' already pending
```
15. Confirm that each transaction is processed correctly
16. Verify that the status page for each transaction is displayed properly
17. Ensure all three transactions complete successfully

Expected Results

- All transactions should execute without errors
- Each transaction should display its status page
- No errors should appear in the console

### **Before**

https://github.com/user-attachments/assets/efb9c501-835c-4259-a3ec-20400a80cf53

### **After**

https://github.com/user-attachments/assets/92772ca7-7da5-4a3e-8cee-46fd16784ea4

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by httpJunkie** [comment]
I have read the CLA Document and I hereby sign the CLA

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -522,6 +522,8 @@ export default class MetamaskController extends EventEmitter {
         ApprovalType.WatchAsset,
         ApprovalType.EthGetEncryptionPublicKey,
         ApprovalType.EthDecrypt,
+        // Exclude Smart TX Status Page from rate limiting to allow sequential transactions
+        'smartTransaction:showSmartTransactionStatusPage',
```
Comment (dan437) [inline app/scripts/metamask-controller.js:526]: Nice job with the fix and detailed description.

nit: can you move this into ApprovalType, so it's consistent with the rest of the list?

Comment (httpJunkie) [reply app/scripts/metamask-controller.js:526]: Well, I thought about this, but quickly realized that, this isn't actually an `ApprovalType` - it's a custom string identifier for the Smart TX status page. The `typesExcludedFromRateLimiting` array accepts both `ApprovalType` enum values and "custom string identifiers".

It's just a UI notification we want to exclude from rate limiting.

Keeping it as a string with a clear comment I think is all we need.

Comment (httpJunkie) [reply app/scripts/metamask-controller.js]: I should have searched for the string. Good catch!

**Review by dan437 — DISMISSED** [review]

**Review by dan437 — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]
