### PR TITLE
fix: Permit DataTree token decimals

### LINKED ISSUE #27243: [Bug]: Fix Permit token decimal amounts
### Describe the bug

If no contract was found within the Permit DataTree component, we should use the verifiedContract tokenDecimals. Passing the verifiedContract's tokenDecimals, when no decimals are found for this contract, will apply the default 18 token decimals. This is missing. Notice in the screenshot that Spending Cap displays "< 0.000001", while Message > Value displays "3,000". Value should also display "< 0.000001".

### Details of applying default 18 token decimals to Redesigned Permit

When we adopted `fetchErc20Decimals` for Permit Simulation, we enforced a default of 18 token decimals to be used when no token decimals were found in the details. `fetchErc20Decimals` is the same method used in `ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts` which is why we adopted it.

Previously, clicking on test-dapp > Permit would display 3,000. Now, it displays 0 < 0.000001. 

@dbrans: 

> 18 is the common convention for ERC20 tokens, largely due to OpenZeppelin's widely-used [implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L21-L22). Vitalik [proposed](https://github.com/ethereum/EIPs/issues/724) making it a required standard, though it didn’t gain momentum. [EIP-1046](https://eips.ethereum.org/EIPS/eip-1046) also suggests 18 as the default if decimals() isn’t implemented.
>
> That said, some platforms, like Etherscan and certain wallets, default to zero when decimals() isn't defined, so there's a lot of inconsistency out there. 

### Expected behavior

_No response_

### Screenshots/Recordings

Notice that Simulation > Spending Cap value does not match Message > Value

CleanShot 2024-09-18 at 17 53 09@2x

### Steps to reproduce

1. Go to test-dapp
2. Click Permit button
3. Observe Spending Cap and Message > Value

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

12.2.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

When no token detail decimals are found in the DataTree showing an amount, we should use the verifiedContract token details passed from TypedSignInfo component. This PR applies this and adds an "Incomplete Asset Displayed" when getTokenStandardAndDetails fails to return details of a token. 

also adds support for passing null decimals to fetchErc20Decimals

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27328?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27243

## **Manual testing steps**

1. Go to test-dapp
2. Test Permit

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: shared/lib/transactions-controller-utils.js [hunk 1]
```diff
@@ -36,11 +36,11 @@ export function toPrecisionWithoutTrailingZeros(n, precision) {
 
 /**
  * @param {number|string|BigNumber} value
- * @param {number} decimals
+ * @param {number=} decimals
```
Comment (pedronfigueiredo) [inline shared/lib/transactions-controller-utils.js:39]: Is the `=` a typo?

**Review by pedronfigueiredo — APPROVED** [review]
LGTM, left one comment

File: shared/lib/transactions-controller-utils.js (hunk 1 above)
Comment (digiwand) [reply shared/lib/transactions-controller-utils.js:39]: It indicates an optional param via jsdoc 
https://jsdoc.app/tags-param

**Review by jpuri — APPROVED** [review]
