### PR TITLE
fix: Fall back to token list for the token symbol

### LINKED ISSUE #27970: [Bug]: Known token being displayed as unknown on the redesigned erc20 transfer
### Describe the bug

If a user doesn't have a token added to their wallet, we display unknown even if it's a known token (e.g. USDC on Ethereum).

### Expected behavior

_No response_

### Screenshots/Recordings

Before adding USDC to the wallet:
Screenshot 2024-10-18 at 17 51 33

After adding USDC to the wallet:
Screenshot 2024-10-18 at 17 54 33

### Steps to reproduce

1. Fresh install from this build https://github.com/MetaMask/metamask-extension/pull/27875#issuecomment-2421985678
2. Go to test dapp
3. Click on malicius erc20 transfer while on Ethereum
4. See Unknown on the top of the confirmation
5. Reject the transaction
6. Import the usdc token to the wallet
7. Repeat steps 3 & 4
8. See USDC on the top of the confirmation instead of Unknown

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

12.8

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28003?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27970

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

Screenshot 2024-10-22 at 11 19 10

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/hooks/useTokenDetails.ts [hunk 1]
```diff
@@ -1,20 +1,27 @@
...
-  // TODO: Add support for NFT images in one of the following tasks
   const tokenImage =
     selectedToken?.iconUrl ||
     selectedToken?.image ||
     tokenList[transactionMeta?.txParams?.to as string]?.iconUrl;
 
-  return { tokenImage };
+  const tokenSymbol =
+    selectedToken?.symbol ||
+    tokenList[transactionMeta?.txParams?.to as string]?.symbol ||
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/hooks/useTokenDetails.ts:23]: Minor, worth extracting the `to` into a `contractAddress` variable?

File: ui/pages/confirmations/components/confirm/info/hooks/useTokenDetails.ts [hunk 2]
```diff
@@ -1,20 +1,27 @@
...
 import { SelectedToken } from '../shared/selected-token';
 
-export const useTokenImage = (
+export const useTokenDetails = (
   transactionMeta: TransactionMeta,
   selectedToken: SelectedToken,
 ) => {
+  const t = useI18nContext();
+
   const tokenList = useSelector(getTokenList) as TokenListMap;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/hooks/useTokenDetails.ts:14]: One for future note but `getTokenList` is derived from the global network where as I just added a selector to use `tokensChainsCache` which is multi-chain compatible as it's a map of data per chain.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
