### PR TITLE
fix: Prevent critical error screen from being replaced

### LINKED ISSUE #35440: [Bug]: Critical error screen can be overwritten
### Describe the bug

The critical error screen can sometimes be overwritten by another critical error, or by a regular app render (if the app recovers for example).

It would be jarring for users if a critical error screen briefly flashed then vanished, and would reduce confidence that the app is working correctly. It would also potentially prevent users from reporting these errors. Given that critical errors happen in situations _we_ believe to be unrecoverable without a restart, we should prevent the error message from being replaced once they are triggered.

### Expected behavior

The error screen should not disappear, even if the app recovers or another critical error occurs

### Screenshots/Recordings

_No response_

### Steps to reproduce

I am not aware of a way to reproduce this with a normal build. This can be simulated by slowing down the background response by 10 seconds though (10 seconds is our background connection timeout).

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.1.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section), Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

This problem was first raised here: https://github.com/MetaMask/metamask-extension/pull/35332#discussion_r2301740979

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

Previously the critical error screen could get overwritten by React, or replaced with another critical error screen. This would be jarring and confusing for users, and might obscure important errors from being reported to us.

The critical error screen has been updated to use an alternative root element, deleting the original root app element the first time it's rendered. Later critical error screens will only render if the app root is still present. This ensures the error screen will remain even if the app somehow recovers, or if another error occurs.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35441?quickstart=1)

## **Changelog**

CHANGELOG entry: null

We could say something like "Ensure critical errors cannot be overwritten", but I don't think it's necessary given that we don't know for sure users _would_ experience this issue, particularly not on older versions. And it's a bit confusing to explain anyway.

## **Related issues**

Fixes #35440

## **Manual testing steps**

We don't know of any manual reproduction steps. But the E2E test that has been added does simulate a scenario where this problem would occur.

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Strengthens critical error handling and testability.
> 
> - Introduces `displayCriticalErrorPage` and switches to `displayCriticalErrorMessage`, rendering errors into a new `#critical-error-content` container and removing `#app-content` to prevent overwrite; updates imports/usages across UI and startup handler
> - Styles `#critical-error-content` alongside `#app-content` in base CSS
> - Replaces manifest flag `simulateUnresponsiveBackground` with `testing.simulateDelayedBackgroundResponse` (number | true) and handles delays in `background.js` `handleOnConnect`
> - Adds/updates E2E and unit tests for unresponsive/slow background scenarios and error page behavior (including 15s timeout persistence)
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0640919a4692219731deb4f13730258a88c58136. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/helpers/utils/display-critical-error.ts [hunk 1]
```diff
@@ -24,26 +24,51 @@ export enum CriticalErrorTranslationKey {
  * @throws {ErrorLike} Throws the error after displaying the message.
  * @returns A promise that resolves to never, as it always throws an error.
  */
-export async function displayCriticalError(
```
Comment (Gudahtt) [inline ui/helpers/utils/display-critical-error.ts:153]: I could have left the name alone, but I thought it was too ambiguous to have both `displayCriticalError` and `displayCriticalErrorPage`. I renamed it to make it a bit more clear that the purpose and parameters were different.

File: ui/helpers/utils/display-critical-error.ts [hunk 2]
```diff
@@ -24,26 +24,51 @@ export enum CriticalErrorTranslationKey {
...
+export async function displayCriticalErrorMessage(
   container: HTMLElement,
   errorKey: CriticalErrorTranslationKey,
   error: ErrorLike,
   currentLocale?: string,
-): Promise<never> {
+) {
```
Comment (Gudahtt) [inline ui/helpers/utils/display-critical-error.ts]: I didn't mean to remove this
```suggestion
): Promise<never> {
```

**Review by davidmurdoch — DISMISSED** [review]

File: ui/helpers/utils/display-critical-error.ts [hunk 3]
```diff
@@ -150,33 +150,59 @@ async function handleRestartAction(
...
+    );
+    const reportCheckbox = container.querySelector<HTMLInputElement>(
+      '#critical-error-checkbox',
+    );
+
+    // Restart button: report error and restart MetaMask
+    restartButton?.addEventListener('click', async () => {
+      const shouldReport = reportCheckbox?.checked ?? false;
+      await handleRestartAction(error, shouldReport);
+    });
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply ui/helpers/utils/display-critical-error.ts:177]: Fixed: https://github.com/MetaMask/metamask-extension/pull/35441/commits/1c9bef3b70bc3e515f9ad68d3a23fe19fec07e79

**Comment by Gudahtt** [comment]
Rebased to resolve two conflicts. One was a simple one in `manifestFlags.ts`, no notable changes from resolving it.

But the second was a little more involved, it was from this recent PR: https://github.com/MetaMask/metamask-extension/pull/35619
It impacted `displayCriticalErrorMessage`; previously there was just a button, but after the PR there was a button and checkbox. I've moved the changes into the `if (criticalErrorContainer)` block. Additionally, the DOM element we're querying has changed here.

**Comment by ngalee8311** [comment]
> <details><summary>Builds ready [76ae5fd]</summary><ul><li>builds: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-dist-browserify/builds/metamask-chrome-13.5.0.zip">chrome</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-dist-mv2-browserify/builds/metamask-firefox-13.5.0.zip">firefox</a></li>
> <li>builds (beta): <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-beta-browserify/builds/metamask-beta-chrome-13.5.0-beta.0.zip">chrome</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-beta-mv2-browserify/builds/metamask-beta-firefox-13.5.0-beta.0.zip">firefox</a></li>
> <li>builds (flask): <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-flask-browserify/builds/metamask-flask-chrome-13.5.0-flask.0.zip">chrome</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-flask-mv2-browserify/builds/metamask-flask-firefox-13.5.0-flask.0.zip">firefox</a></li>
> <li>builds (test): <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-test-browserify/builds/metamask-chrome-13.5.0.zip">chrome</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-test-mv2-browserify/builds/metamask-firefox-13.5.0.zip">firefox</a></li>
> <li>builds (test-flask): <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-test-flask-browserify/builds/metamask-flask-chrome-13.5.0-flask.0.zip">chrome</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/build-test-flask-mv2-browserify/builds/metamask-flask-firefox-13.5.0-flask.0.zip">firefox</a></li>
> <li>build viz: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/lavamoat-viz/index.html">Build System</a></li>
> <li>bundle size: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/bundle-size/bundle_size.json">Bundle Size Stats</a></li>
> <li>user-actions-benchmark: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/benchmarks/benchmark-chrome-browserify-userActions.json">User Actions Stats</a></li>
> <li>storybook: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/storybook-build/index.html">Storybook</a></li>
> <li>typescript migration: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/ts-migration-dashboard/index.html">Dashboard</a></li>
> <li><a href="https://github.com/MetaMask/metamask-extension/actions/runs/17778801336#artifacts">all artifacts</a></li>
> <li><details>
>        <summary>bundle viz:</summary>
>        <ul><li>background: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-0.html">0</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-1.html">1</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-2.html">2</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-3.html">3</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-4.html">4</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-5.html">5</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-6.html">6</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-7.html">7</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/background-8.html">8</a></li><li>common: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-0.html">0</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-1.html">1</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-2.html">2</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-3.html">3</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-4.html">4</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-5.html">5</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-6.html">6</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-7.html">7</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-8.html">8</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-9.html">9</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-10.html">10</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-11.html">11</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/common-12.html">12</a></li><li>ui: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-0.html">0</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-1.html">1</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-2.html">2</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-3.html">3</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-4.html">4</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-5.html">5</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-6.html">6</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-7.html">7</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-8.html">8</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-9.html">9</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-10.html">10</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-11.html">11</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-12.html">12</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-13.html">13</a>, <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/ui-14.html">14</a></li><li>content-script: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/content-script-0.html">0</a></li><li>offscreen: <a href="https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/17778801336/source-map-explorer/offscreen-0.html">0</a></li></ul>
>      </details></li></ul></details>
> 
> <details><summary>UI Startup Metrics (1211 ± 68 ms)</summary><table><thead><tr><th>Platform</th><th>BuildType</th><th>Page</th><th>Metric</th><th>Mean (ms)</th><th>Min (ms)</th><th>Max (ms)</th><th>Std Dev (ms)</th><th>P 75 (ms)</th><th>P 95 (ms)</th></tr></thead><tbody><tr><td rowspan="22">Chrome</td><td rowspan="11">Browserify</td><td rowspan="11">Home</td><td>uiStartup</td><td align="right">1211</td><td align="right">1098</td><td align="right">1479</td><td align="right">68</td><td align="right">1246</td><td align="right">1325</td></tr><tr><td>load</td><td align="right">1047</td><td align="right">949</td><td align="right">1286</td><td align="right">58</td><td align="right">1074</td><td align="right">1144</td></tr><tr><td>domContentLoaded</td><td align="right">1039</td><td align="right">937</td><td align="right">1278</td><td align="right">58</td><td align="right">1068</td><td align="right">1139</td></tr><tr><td>domInteractive</td><td align="right">17</td><td align="right">13</td><td align="right">50</td><td align="right">6</td><td align="right">16</td><td align="right">30</td></tr><tr><td>firstPaint</td><td align="right">623</td><td align="right">95</td><td align="right">1175</td><td align="right">416</td><td align="right">1038</td><td align="right">1127</td></tr><tr><td>backgroundConnect</td><td align="right">249</td><td align="right">236</td><td align="right">279</td><td align="right">8</td><td align="right">253</td><td align="right">265</td></tr><tr><td>firstReactRender</td><td align="right">25</td><td align="right">17</td><td align="right">72</td><td align="right">8</td><td align="right">28</td><td align="right">40</td></tr><tr><td>getState</td><td align="right">14</td><td align="right">5</td><td align="right">68</td><td align="right">9</td><td align="right">17</td><td align="right">31</td></tr><tr><td>initialActions</td><td align="right">5</td><td align="right">1</td><td align="right">33</td><td align="right">5</td><td align="right">6</td><td align="right">14</td></tr><tr><td>loadScripts</td><td align="right">798</td><td align="right">701</td><td align="right">1037</td><td align="right">57</td><td align="right">824</td><td align="right">891</td></tr><tr><td>setupStore</td><td align="right">10</td><td align="right">6</td><td align="right">23</td><td align="right">4</td><td align="right">11</td><td align="right">19</td></tr><tr><td rowspan="11">Webpack</td><td rowspan="11">Home</td><td>uiStartup</td><td align="right">1093</td><td align="right">907</td><td align="right">1355</td><td align="right">94</td><td align="right">1139</td><td align="right">1267</td></tr><tr><td>load</td><td align="right">904</td><td align="right">741</td><td align="right">1088</td><td align="right">84</td><td align="right">959</td><td align="right">1053</td></tr><tr><td>domContentLoaded</td><td align="right">899</td><td align="right">738</td><td align="right">1081</td><td align="right">83</td><td align="right">952</td><td align="right">1041</td></tr><tr><td>domInteractive</td><td align="right">16</td><td align="right">12</td><td align="right">53</td><td align="right">10</td><td align="right">14</td><td align="right">45</td></tr><tr><td>firstPaint</td><td align="right">158</td><td align="right">65</td><td align="right">431</td><td align="right">62</td><td align="right">180</td><td align="right">285</td></tr><tr><td>backgroundConnect</td><td align="right">17</td><td align="right">11</td><td align="right">66</td><td align="right">10</td><td align="right">16</td><td align="right">42</td></tr><tr><td>firstReactRender</td><td align="right">36</td><td align="right">33</td><td align="right">88</td><td align="right">6</td><td align="right">36</td><td align="right">42</td></tr><tr><td>getState</td><td align="right">7</td><td align="right">4</td><td align="right">26</td><td align="right">4</td><td align="right">9</td><td align="right">15</td></tr><tr><td>initialActions</td><td align="right">6</td><td align="right">2</td><td align="right">14</td><td align="right">4</td><td align="right">10</td><td align="right">13</td></tr><tr><td>loadScripts</td><td align="right">896</td><td align="right">736</td><td align="right">1071</td><td align="right">82</td><td align="right">950</td><td align="right">1031</td></tr><tr><td>setupStore</td><td align="right">9</td><td align="right">6</td><td align="right">40</td><td align="right">4</td><td align="right">9</td><td align="right">13</td></tr><tr><td rowspan="22">Firefox</td><td rowspan="11">Browserify</td><td rowspan="11">Home</td><td>uiStartup</td><td align="right">1418</td><td align="right">1266</td><td align="right">1735</td><td align="right">97</td><td align="right">1482</td><td align="right">1572</td></tr><tr><td>load</td><td align="right">1233</td><td align="right">1107</td><td align="right">1400</td><td align="right">77</td><td align="right">1287</td><td align="right">1380</td></tr><tr><td>domContentLoaded</td><td align="right">1233</td><td align="right">1107</td><td align="right">1399</td><td align="right">77</td><td align="right">1287</td><td align="right">1379</td></tr><tr><td>domInteractive</td><td align="right">111</td><td align="right">32</td><td align="right">329</td><td align="right">63</td><td align="right">114</td><td align="right">297</td></tr><tr><td>firstPaint</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td></tr><tr><td>backgroundConnect</td><td align="right">38</td><td align="right">19</td><td align="right">120</td><td align="right">22</td><td align="right">38</td><td align="right">98</td></tr><tr><td>firstReactRender</td><td align="right">28</td><td align="right">24</td><td align="right">61</td><td align="right">4</td><td align="right">30</td><td align="right">33</td></tr><tr><td>getState</td><td align="right">7</td><td align="right">3</td><td align="right">82</td><td align="right">9</td><td align="right">6</td><td align="right">11</td></tr><tr><td>initialActions</td><td align="right">6</td><td align="right">1</td><td align="right">185</td><td align="right">22</td><td align="right">3</td><td align="right">8</td></tr><tr><td>loadScripts</td><td align="right">1203</td><td align="right">1083</td><td align="right">1381</td><td align="right">75</td><td align="right">1261</td><td align="right">1335</td></tr><tr><td>setupStore</td><td align="right">9</td><td align="right">5</td><td align="right">66</td><td align="right">8</td><td align="right">9</td><td align="right">14</td></tr><tr><td rowspan="11">Webpack</td><td rowspan="11">Home</td><td>uiStartup</td><td align="right">1553</td><td align="right">1357</td><td align="right">2195</td><td align="right">167</td><td align="right">1634</td><td align="right">1948</td></tr><tr><td>load</td><td align="right">1332</td><td align="right">1140</td><td align="right">1820</td><td align="right">138</td><td align="right">1426</td><td align="right">1573</td></tr><tr><td>domContentLoaded</td><td align="right">1331</td><td align="right">1140</td><td align="right">1819</td><td align="right">138</td><td align="right">1426</td><td align="right">1573</td></tr><tr><td>domInteractive</td><td align="right">104</td><td align="right">32</td><td align="right">312</td><td align="right">62</td><td align="right">99</td><td align="right">267</td></tr><tr><td>firstPaint</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td><td align="right">NaN</td></tr><tr><td>backgroundConnect</td><td align="right">31</td><td align="right">21</td><td align="right">50</td><td align="right">7</td><td align="right">36</td><td align="right">44</td></tr><tr><td>firstReactRender</td><td align="right">43</td><td align="right">37</td><td align="right">55</td><td align="right">4</td><td align="right">46</td><td align="right">49</td></tr><tr><td>getState</td><td align="right">10</td><td align="right">3</td><td align="right">170</td><td align="right">26</td><td align="right">6</td><td align="right">13</td></tr><tr><td>initialActions</td><td align="right">3</td><td align="right">1</td><td align="right">87</td><td align="right">9</td><td align="right">3</td><td align="right">7</td></tr><tr><td>loadScripts</td><td align="right">1309</td><td align="right">1119</td><td align="right">1800</td><td align="right">139</td><td align="right">1405</td><td align="right">1539</td></tr><tr><td>setupStore</td><td align="right">9</td><td align="right">5</td><td align="right">33</td><td align="right">4</td><td align="right">9</td><td align="right">21</td></tr></tbody></table>Benchmark value 249 exceeds gate value 10 for chrome browserify home mean backgroundConnect<br>
> Benchmark value 26 exceeds gate value 23 for chrome browserify home mean firstReactRender<br>
> Benchmark value 5 exceeds gate value 1 for chrome browserify home mean initialActions<br>
> Benchmark value 265 exceeds gate value 18 for chrome browserify home p95 backgroundConnect<br>
> Benchmark value 14 exceeds gate value 1.2 for chrome browserify home p95 initialActions<br>
> Benchmark value 19 exceeds gate value 17 for chrome browserify home p95 setupStore<br>
> Benchmark value 13 exceeds gate value 7 for chrome webpack home p95 initialActions<br>
> Benchmark value 1419 exceeds gate value 1405 for firefox browserify home mean uiStartup<br>
> Benchmark value 111 exceeds gate value 110 for firefox browserify home mean domInteractive<br>
> Benchmark value 39 exceeds gate value 25 for firefox browserify home mean backgroundConnect<br>
> Benchmark value 29 exceeds gate value 25 for firefox browserify home mean firstReactRender<br>
> Benchmark value 6 exceeds gate value 1 for firefox browserify home mean initialActions<br>
> Benchmark value 10 exceeds gate value 9 for firefox browserify home mean setupStore<br>
> Benchmark value 297 exceeds gate value 195 for firefox browserify home p95 domInteractive<br>
> Benchmark value 98 exceeds gate value 70 for firefox browserify home p95 backgroundConnect<br>
> Benchmark value 8 exceeds gate value 2 for firefox browserify home p95 initialActions<br>
> Benchmark value 105 exceeds gate value 100 for firefox webpack home mean domInteractive<br>
> Benchmark value 31 exceeds gate value 26 for firefox webpack home mean backgroundConnect<br>
> Benchmark value 43 exceeds gate value 38 for firefox webpack home mean firstReactRender<br>
> Benchmark value 4 exceeds gate value 1 for firefox webpack home mean initialActions<br>
> Benchmark value 1948 exceeds gate value 1935 for firefox webpack home p95 uiStartup<br>
> Benchmark value 267 exceeds gate value 156 for firefox webpack home p95 domInteractive<br>
> Benchmark value 7 exceeds gate value 2 for firefox webpack home p95 initialActions<br>
> <b>Sum of mean exceeds: 303ms | Sum of p95 exceeds: 532.8ms<br>
> Sum of all benchmark exceeds: 835.8ms</b><br>
> </details>
> 
> <details><summary>Bundle size diffs [🚨 Warning! Bundle size has increased!]</summary><ul><li>background: 43 Bytes (0%)</li>
> <li>ui: 937 Bytes (0.01%)</li>
> <li>common: 10 Bytes (0%)</li></ul></details>
> 
>

File: test/e2e/tests/critical-errors/critical-errors.spec.ts [hunk 4]
```diff
@@ -14,16 +16,49 @@ describe('Critical errors', function (this: Suite) {
...
+            simulateDelayedBackgroundResponse: true,
+          },
+        },
+        title: this.test?.fullTitle(),
+      },
+      async ({ driver }) => {
+        await driver.navigate(PAGES.HOME, { waitForControllers: false });
+
+        // Wait until timeout expires
+        await driver.delay(BACKGROUND_CONNECTION_TIMEOUT);
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply test/e2e/tests/critical-errors/critical-errors.spec.ts:29]: The thing we're waiting for here is literally a timer, so it makes sense in this case

File: shared/lib/manifestFlags.ts [hunk 5]
```diff
@@ -96,9 +96,10 @@ export type ManifestFlags = {
      */
     disableSync?: boolean;
     /**
-     * Whether to simulate an unresponsive background by ignoring connections from the UI
+     * Simulate a delay to how quickly the background responds to the UI. Set this to `true` to
+     * make the background completely unresponsive.
      */
-    simulateUnresponsiveBackground?: boolean;
+    simulateDelayedBackgroundResponse?: number | boolean;
```
Comment (Gudahtt) [inline shared/lib/manifestFlags.ts]: Improve accuracy of type, and avoid confusing handling of `false` that Cursor pointed out

```suggestion
    simulateDelayedBackgroundResponse?: number | true;
```

File: app/scripts/background.js [hunk 6]
```diff
@@ -510,11 +510,18 @@ const corruptionHandler = new CorruptionHandler();
...
+      getManifestFlags().testing?.simulateDelayedBackgroundResponse;
+    if (simulatedDelay === true) {
+      return;
+    } else if (typeof simulatedDelay === 'number') {
+      await new Promise((resolve) => setTimeout(resolve, simulatedDelay));
+    } else {
+      log.error(
+        `Unrecognized value for 'simulateDelayedBackgroundResponse': '${simulatedDelay}'`,
+      );
+    }
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/scripts/background.js:524]: Good point, fixed here: ba259953b1

**Review by seaona — APPROVED** [review]
e2e changes look good, nice tests 😍

**Review by davidmurdoch — APPROVED** [review]

File: ui/helpers/utils/display-critical-error.ts [hunk 7]
```diff
@@ -150,33 +150,61 @@ async function handleRestartAction(
...
+  const appContainerParent = container.parentElement;
+  if (!appContainerParent) {
+    console.warn(
+      'Cannot display critical error. Another critical error may already be shown.',
+    );
+    return undefined;
+  }
+
+  const criticalErrorContainer = document.createElement('div');
+  criticalErrorContainer.setAttribute('id', 'critical-error-content');
```
Comment (n3ps) [inline ui/helpers/utils/display-critical-error.ts:203]: Question: if id `#critical-error-content` is newly introduced in this PR and its styles are the same as `#app-content` can't we just use app-content here?

**Review by n3ps — APPROVED** [review]
Just had a question re: the css

File: ui/helpers/utils/display-critical-error.ts (hunk 7 above)
Comment (Gudahtt) [reply ui/helpers/utils/display-critical-error.ts:203]: They do briefly co-exist, so I didn't want to introduce a duplicate ID (they are supposed to be unique).

Admittedly I was just copying how the styles were done previously here, I wouldn't have used an ID if I was writing this from scratch.
