### PR TITLE
Ensure native asset icon does not display incorrectly when switching networks and balance is loading

### LINKED ISSUE #15080: [Bug]: Incorrect asset icon and balance when switching network
### Describe the bug

The asset icon and balance shown whilst switching from a custom network to Mainnet is incorrect

https://user-images.githubusercontent.com/53189696/176450652-f8f7f6f6-ee50-48fb-8a7d-959517280570.mov

### Steps to reproduce

1. Login to the extension
2. Switch network from Ethereum Mainnet to Avalanche
3. Switch network from Avalanche to Ethereum Mainnet

Actual result (See Image below- screenshot from video at 00:11):

1. Incorrect asset icon shown in the wallet overview
2. Incorrect asset icon shown in the asset list
3. Incorrect asset balance shown in the asset list

switching network

### Error messages or log output

_No response_

### Version

10.17.0

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/15080

Fixes this by just hiding the network icon while balance is loading during the network switch

### CODE REVIEW

**Review by ryanml — APPROVED** [review]
Works well!

**Review by PeterYinusa — APPROVED** [review]

**Review by PeterYinusa — APPROVED** [review]

File: ui/components/app/asset-list/asset-list.js [hunk 1]
```diff
@@ -76,7 +78,7 @@ const AssetList = ({ onClickAsset }) => {
         }
         tokenSymbol={primaryCurrencyProperties.suffix}
         secondary={showFiat ? secondaryCurrencyDisplay : undefined}
-        tokenImage={primaryTokenImage}
+        tokenImage={balanceIsLoading ? null : primaryTokenImage}
```
Comment (PeterYinusa) [inline ui/components/app/asset-list/asset-list.js:81]: Looks good to me!

Should we go a little further and hide the asset?
```
      {balanceIsLoading ? null : (
        <AssetListItem
          onClick={() => onClickAsset(nativeCurrency)}
          data-testid="wallet-balance"
          primary={
            primaryCurrencyProperties.value ?? secondaryCurrencyProperties.value
          }
          tokenSymbol={primaryCurrencyProperties.suffix}
          secondary={showFiat ? secondaryCurrencyDisplay : undefined}
          tokenImage={primaryTokenImage}
          identiconBorder
        />
      )}
```
