### PR TITLE
fix: (import-tokens) validate duplicate token checks by selected network

### LINKED ISSUE #38954: [Bug]: Can't import multi-chain tokens (Printr)
**Describe the bug**

I can't import multichain tokens in MetaMask. This kind of token has the same address on every chain. MetaMask currently allows me to add a token per chain (like Base), and when I try to add that token for another chain, I get an error stating that the token has already been added.

Example:
https://app.printr.money/trade/0x4dab04c0f3e346c8932056ecb4a957277f102e8904da53e7963221b3ed3562ee
https://etherscan.io/token/0xbc0a08a3b560327ec16842b5f3bf46fa029366b1
https://basescan.org/token/0xbc0a08a3b560327ec16842b5f3bf46fa029366b1
https://arbiscan.io/token/0xbc0a08a3b560327ec16842b5f3bf46fa029366b1
https://bscscan.com/token/0xbc0a08a3b560327ec16842b5f3bf46fa029366b1
https://avascan.info/blockchain/c/token/0xbc0a08a3b560327Ec16842B5f3bF46FA029366b1

**Expected behavior**

Token import should be universal and not per chain. When I import token `0xbc0a08a3b560327Ec16842B5f3bF46FA029366b1` it should be automatically imported for all the chains.

**Screenshots/Recordings**

Image

**Steps to reproduce**

Go to import token
Import token on one chain
Then import the same token address on another chain

**Error messages or log output**

```shell
Token has already been added
```

**Where was this bug found?**

Live version (from official store)

**Version**

13.12.2

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

Fixes a false "Token has already been added" validation in the multichain import token modal.

The duplicate-token check was reading tokens from the home network selector (`chainId`) instead of the network currently selected inside the import modal (`selectedNetwork`). This caused cross-network false positives when users imported the same token address on another chain.

This change keeps scope minimal:
- Use `selectedNetwork` for duplicate address validation
- Add a regression test that reproduces the mismatch scenario and asserts that `tokenAlreadyAdded` is not shown

## **Changelog**

CHANGELOG entry: fix: (import-tokens) validate duplicate token checks by selected network

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38954 https://consensyssoftware.atlassian.net/browse/ASSETS-2177

## **Manual testing steps**

1. Open Import tokens modal.
2. Ensure a token is already imported on network A.
3. In the import modal, switch to network B and input the same token address.
4. Verify "Token has already been added" is not shown for network B.

### **After**
https://www.loom.com/share/dce5af505797496da9532d936b6e4715

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

<div><a href="https://cursor.com/agents/bc-34abf75e-7064-4a50-b0b1-db37f145bf02"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-web-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-web-light.png">Open in Web</picture></a>&nbsp;<a href="https://cursor.com/background-agent?bcId=bc-34abf75e-7064-4a50-b0b1-db37f145bf02"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-cursor-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-cursor-light.png">Open in Cursor</picture></a>&nbsp;</div>

### CODE REVIEW

**Review by bergarces — APPROVED** [review]

File: ui/components/multichain/import-tokens-modal/import-tokens-modal.js [hunk 1]
```diff
@@ -211,7 +211,7 @@ export const ImportTokensModal = ({ onClose }) => {
   const selectedAccount = useSelector(getSelectedInternalAccount);
   const accounts = useSelector(getInternalAccounts);
   const allTokens = useSelector(getAllTokens);
-  const tokens = allTokens?.[chainId]?.[selectedAccount.address] || [];
+  const tokens = allTokens?.[selectedNetwork]?.[selectedAccount.address] || [];
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/import-tokens-modal/import-tokens-modal.js:214]: the 1 liner fix.

When we want to dermine tokens to add, we shouldn't evaluate to the current global chain id (selector which is deprecated), instead use the chain ID from the form.

**Review by NidhiKJha — APPROVED** [review]
