### PR TITLE
fix: (cp-12.18.0) solana devnet non-native asset view should disable swap and bridge

### LINKED ISSUE #32619: [Bug]: Solana - Starting a Swap or a Bridge with a specific token breaks MM with`Error: Token with fiat amount not found`
### Describe the bug

Starting a Swap or a Bridge with a specific token breaks MM with`Error: Token with fiat amount not found`

### Expected behavior

_No response_

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/f7dba41f-0e31-462b-919b-e9a4228815c9

### Steps to reproduce

1. Select Solana devnet
2. Get some WSOL (ie from the test dapp)
3. Now go to the wallet
4. Click the WSOL token
5. Click Swap or Bridge
6. See wallet breaks

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

We were using a selector that relied on a hack that only returns Solana mainnet chainID.

https://github.com/MetaMask/metamask-extension/blob/2d96e51c13844590d80e0fb422b7f1828dc4f0a5/ui/selectors/multichain.ts#L206-L216

Replacing this selector with a different selector to get multichain chainId succeeded.

NOTE - we can probably add another fix on the original selector and remove the hack.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32679?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32619

## **Manual testing steps**

1. Select Solana DevNet
2. Select an ERC/non-native token from this devnet
3. EXPECTED - see swap and bridge disabled

### **After**

https://www.loom.com/share/9a532c02dabf4f34a4114a9ed17bf14e?sid=0035bdc6-5ed9-47c7-a47e-d1cdb76289ef

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/asset/components/token-buttons.tsx [hunk 1]
```diff
@@ -327,40 +329,39 @@ const TokenButtons = ({
         disabled={token.isERC721}
         tooltipRender={null}
       />
-      {isSwapsChain && (
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/components/token-buttons.tsx:330]: Instead of hiding the buttons, we are instead disabling them similar to other areas in the UI.

File: ui/pages/asset/components/token-buttons.tsx [hunk 2]
```diff
@@ -95,8 +93,10 @@ const TokenButtons = ({
 
   const account = useSelector(getSelectedInternalAccount, isEqual);
 
-  const { chainId: multichainChainId } =
-    useMultichainSelector(getMultichainNetwork);
+  // This is only returning solana mainnet, not solana devnet?
+  const { chainId: multichainChainId } = useSelector(
+    getSelectedMultichainNetworkConfiguration,
+  );
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/components/token-buttons.tsx:99]: Should I create a separate fix for the original selector?
As mentioned in the PR description, it uses a hack that doesn't work well with non-evm dev/testnets.
https://github.com/MetaMask/metamask-extension/blob/2d96e51c13844590d80e0fb422b7f1828dc4f0a5/ui/selectors/multichain.ts#L206-L216

Comment (Prithpal-Sooriya) [reply ui/pages/asset/components/token-buttons.tsx:99]: Hmmm unfortunately this isn't easy to fix the types do not match and the `MultichainNetworkController` doesn't seem to have some fields that this selector requires (ticker, isAddressCompatible, decimals, etc)

**Review by gambinish — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]

File: ui/pages/asset/components/token-buttons.tsx [hunk 3]
```diff
@@ -95,8 +93,10 @@ const TokenButtons = ({
 
   const account = useSelector(getSelectedInternalAccount, isEqual);
 
-  const { chainId: multichainChainId } =
-    useMultichainSelector(getMultichainNetwork);
+  // This is only returning solana mainnet, not solana devnet?
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/components/token-buttons.tsx:96]: Dummy, I forgot to remove this comment 🙊 

I'll do a cleanup PR on this with the PR below.

Comment (Prithpal-Sooriya) [reply ui/pages/asset/components/token-buttons.tsx:96]: Fixed in https://github.com/MetaMask/metamask-extension/pull/32720
