### PR TITLE
fix/18577: Add title back for approving ERC20 token

### LINKED ISSUE #18577: [Bug]: ERC20 Token symbol displays 'undefined' in send confirmation screen, amount also displays 0
### Describe the bug

https://user-images.githubusercontent.com/53189696/231795314-f75d9090-f9c6-41c4-bc3c-6b3e3320af12.mov

### Steps to reproduce

1. Log in to the extension
2. navigate to the test dapp
3. create TST token
4. add TST token to the wallet
5. Send Token

### Error messages or log output

```shell
token-util.js:260 Error: Unable to determine contract standard
  at p.<anonymous> (AssetsContractController.js:170:1)
  at Generator.throw (<anonymous>)
  at a (AssetsContractController.js:6:1)
a
```

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DDDDDanica**
## Explanation

Introduced in this [MR](https://github.com/MetaMask/metamask-extension/pull/18269/files#diff-dd61de4ea1c1b71d20a1bde48a140622a055dd3ababaaa271af30e3645e240f8).

Fixes: https://github.com/MetaMask/metamask-extension/issues/18577

### After

https://user-images.githubusercontent.com/12678455/232454721-bc2061e8-0c91-4faa-910a-f31d9def67e0.mov

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js [hunk 1]
```diff
@@ -70,6 +70,7 @@ export default function ConfirmTokenTransactionBase({
       (collection) =>
         collection.address.toLowerCase() === tokenAddress.toLowerCase(),
     );
+    console.log({ tokenSymbol, nftCollection })
```
Comment (NidhiKJha) [inline ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js:73]: Nit: Please remove the console statement
```suggestion
```

**Review by NidhiKJha — COMMENTED** [review]
LGTM! Just a small nit

**Review by danjm — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
