### PR TITLE
fix: update `@metamask/selected-network-controller` version + add migration to remove Snaps from `SelectedNetworkController` `domains` state

### LINKED ISSUE #24410: Bring SelectedNetworkController update to Extension
Bring https://github.com/MetaMask/core/pull/4259 changes to Extension. Includes migration to remove stale state.

Issue created for tracking purposes close to Amon Hen V1 release cut on Extension.

### PR DESCRIPTION
**Pull request by adonesky1**
## **Description**

Currently Snaps should not be included in the `SelectedNetworkController`'s `domains` state since they have no way of changing their network (they cannot call `wallet_switchEthereumChain` and have no UI exposed to manually switch their connected chain). This means that with the `useRequestQueue` toggle on they are stuck permanently connected to whatever chain is selected when they are installed.

This PR adds a migration to remove the Snaps domains that made it into this state previously and pulls in changes to the `SelectedNetworkController` that:
- Modifies its `getProviderAndBlockTracker` method to return the `NetworkController`'s globally selected network client proxy if the domain arg is either `metamask` or a snap (identified by if prefixed by npm: or local:)
- Adds logic to exclude connecting Snaps from setting selected network state and proxies in the `SelectedNetworkController`

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24409?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24410

See [this thread](https://consensys.slack.com/archives/C02GENU377A/p1715007955642199?thread_ts=1714501325.186459&cid=C02GENU377A) for more details

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

### **Before**

N/A

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/migrations/118.ts
Comment (Gudahtt) [inline app/scripts/migrations/118.ts:1]: We'll need to import this in the migrations index file as well

File: app/scripts/migrations/118.ts [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+
+/**
+ * Removes all domains starting with 'npm:' or 'local:' from the SelectedNetworkController's domains state.
+ *
+ * @param state - The entire state object of the MetaMask extension.
+ */
+function transformState(state: Record<string, unknown>) {
+  const selectedNetworkControllerState = state.SelectedNetworkController;
+  if (!selectedNetworkControllerState) {
+    global.sentry?.captureException?.(
```
Comment (Gudahtt) [inline app/scripts/migrations/118.ts:39]: We would expect this state to be missing for users updating from older versions, before we introduced this controller. I think this should be a warning rather than an error

File: app/scripts/migrations/118.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+  const domains = selectedNetworkControllerState.domains as Record<
+    Domain,
+    NetworkClientId
+  >;
+  const filteredDomains = Object.keys(domains).reduce((acc, domain) => {
+    if (!domain.startsWith('npm:') && !domain.startsWith('local:')) {
+      acc[domain] = domains[domain];
+    }
+    return acc;
+  }, {} as Record<Domain, NetworkClientId>);
```
Comment (Gudahtt) [inline app/scripts/migrations/118.ts:75]: We don't need any type casts here. I'd recommend typing `domains` as `Record<string, unknown>` here, as that doesn't require any casting (the only assumption it makes is that keys are strings, which is guaranteed by JavaScript, all keys can be expressed as strings). This is enough to perform the operations we want here.

```suggestion
  const domains = selectedNetworkControllerState.domains;
  const filteredDomains = Object.keys(domains).reduce<Record<string, unknown>>((acc, domain) => {
    if (!domain.startsWith('npm:') && !domain.startsWith('local:')) {
      acc[domain] = domains[domain];
    }
    return acc;
  }, {});
```

Comment (Gudahtt) [reply app/scripts/migrations/118.ts:75]: See here for more about avoiding type assertions: https://github.com/MetaMask/contributor-docs/blob/main/docs/typescript.md#prefer-type-inference-over-annotations-and-assertions

Comment (adonesky1) [reply app/scripts/migrations/118.ts]: done here: https://github.com/MetaMask/metamask-extension/pull/24409/commits/3e231b1204ba97c60a9f3b2b4518cbc6e517e977

File: app/scripts/migrations/118.ts (hunk 1 above)
Comment (adonesky1) [reply app/scripts/migrations/118.ts:37]: What does throwing a warning instead of an error in migrations look like? Not seeing any examples? Or are you saying a console warning? I'm guessing not that...

Comment (Gudahtt) [reply app/scripts/migrations/118.ts:37]: Yep, a console warning is what I meant. Or `log.warn` at least. Here's one example: https://github.com/MetaMask/metamask-extension/blob/ea7a5374c4db8a628e348b4b3fc01f87d0211ae3/app/scripts/migrations/077.js#L45

Comment (adonesky1) [reply app/scripts/migrations/118.ts]: Oh ok. Done here: https://github.com/MetaMask/metamask-extension/pull/24409/commits/c55c61e9ebe8b7eefb873467e8b0853511caec73

**Review by mcmire — APPROVED** [review]
Looks good!

**Review by NidhiKJha — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!
