### PR TITLE
fix: cp-12.18.0 fixes quotes still being usable after switching token

### LINKED ISSUE #32866: [Bug]: Solana - Swap can go to the wrong token if quote is entered quickly
### Describe the bug

As shown in the video below, when the user attempted to swap SOL to AI (or any other token), the transaction instead swapped SOL to USDC. It appears that if the quote is requested too quickly, the system defaults to swapping to USDC or the first token in the list, regardless of the destination token selected. That indicates that this is probably a race condition

Looking in the network tab, it appears that getQuote is called twice: first for SOL-USDC and then for SOL-AI. However, the quote for SOL-USDC is the one used for the swap, instead of the intended SOL-AI quote.

### Expected behavior

The Swap is executed to the correct token

### Screenshots/Recordings

https://github.com/user-attachments/assets/14b54a9b-bbb6-44f6-8ed2-4e023d21111f

### Steps to reproduce

1. Select Solana as a network and make sure you have funds
2. Go to Swap
3. Now execute steps 4-6 below very quickly
4. Enter .001 in the amount
5. Select AI from the destination drop down list
6. Click on Submit
7. Notice in the transaction details that it's showing USDC as the receiving token instead of AI

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

A bug was surfaced where you could accept a previous quote before a new one was present, if you changed the destination asset and clicked continue before it loaded. This fixes that issue by invalidating the previous quote by checking if the destination asset still matches. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32878?quickstart=1)

## **Related issues**

Fixes: #32866 

## **Manual testing steps**

1. Go to a Solana swap
2. Start fetching a quote, and change the destination token
3. The first quote should be invalidated since the destination token changed

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx [hunk 1]
```diff
@@ -180,15 +180,50 @@ const PrepareBridgePage = () => {
...
-      // insufficientBal is always true for solana
-      (fromChain && isSolanaChainId(fromChain.chainId)))
-      ? undefined
-      : activeQuote_;
+
+  // A quote is considered invalid if it is expired or if its destination token/chain
+  // no longer matches the current user selection. This prevents a race condition
+  // where a stale quote (e.g., for SOL→USDC) could be used after the user has
+  // already switched the destination token (e.g., to SOL→AI).
+  const isQuoteExpiredOrInvalid = () => {
```
Comment (micaelae) [inline ui/pages/bridge/prepare/prepare-bridge-page.tsx:188]: Can you move this to the quote.ts util file? This component is getting too long

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx [hunk 2]
```diff
@@ -180,15 +180,50 @@ const PrepareBridgePage = () => {
...
+        ? formatChainIdToCaip(toChain.chainId)
+        : '';
+
+      if (
+        quoteDestAddress !== selectedDestAddress ||
+        quoteDestChainIdCaip !== selectedDestChainIdCaip
+      ) {
+        return true;
+      }
+    }
```
Comment (micaelae) [inline ui/pages/bridge/prepare/prepare-bridge-page.tsx:221]: Minor: this can be simplified to this
```suggestion
      return !(
        quoteDestAddress === selectedDestAddress &&
        quoteDestChainIdCaip === selectedDestChainIdCaip
      )
    }
```

**Comment by dylanbutler1** [comment]
approved for 12.18.10

**Review by micaelae — DISMISSED** [review]

File: .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch
Comment (amitabh94) [inline .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch:1]: Why do we need a patch ? Are we not able to make changes in the core and bump it ?

Comment (micaelae) [reply .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch:1]: 12.18.0's bridge-controller is a few versions behind the latest core. bumping the controller version would require migrating the feature flags as well, which has not been tested in 12.18.0. Will undo this patch in a separate PR to bump the controller version

**Review by GustavoRSSilva — APPROVED** [review]

File: .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch
Comment (amitabh94) [reply .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch:1]: Can we add a comment in the codebase for other devs ?

**Review by micaelae — APPROVED** [review]

File: .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch
Comment (micaelae) [reply .yarn/patches/@metamask-bridge-controller-npm-20.0.0-ddd6003340.patch:1]: Created a JIRA ticket instead for this sprint instead and the bump will be done as a fast-follow: https://consensyssoftware.atlassian.net/browse/MMS-2446
