### PR TITLE
fix: cp-12.18.0 fix metrics event capturing for advance setting dismissSmartAccountSuggestionEnabled

### LINKED ISSUE #32286: [Bug]: EIP7702 - Changing the setting: `Dismiss "Switch to Smart Account" suggestion` doesn't have a metric event associated
### Describe the bug

Changing the setting: `Dismiss "Switch to Smart Account" suggestion` doesn't have a metric event associated

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/32a0e4aa-0179-46dd-a1c7-c2b9fcbfcd02

### Steps to reproduce

1. Go to Settings
2. Enable/disable switch to smart account
3. See no metrics event is sent

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix metrics event capturing for advance setting dismissSmartAccountSuggestionEnabled

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32286

## **Manual testing steps**

1. Go to extension
2. Toggle advance setting - `Dismiss "Switch to Smart Account" suggestion`
3. Check that metrics event is recorded

## **Screenshots/Recordings**

https://github.com/user-attachments/assets/7c724715-0353-47a6-a426-afb5c041de98

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.tsx [hunk 1]
```diff
@@ -42,11 +42,7 @@ export function TransactionAccountDetails() {
...
             alertKey={RowAlertKey.AccountTypeUpgrade}
-            label={
-              isBatch
-                ? t('confirmInfoAccountType')
-                : t('confirmInfoAccountCurrentType')
-            }
+            label={t('confirmInfoAccountCurrentType')}
             ownerId={id}
           >
             <ConfirmInfoRowText
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.tsx:48]: PR also includes label change as discussed here: https://consensys.slack.com/archives/C070G0RCX0T/p1745854922254759

**Review by OGPoyraz — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
