### PR TITLE
fix: log migration error

### LINKED ISSUE #33314: Error: Migration #156: newState.NftController must be present
Sentry Issue: [METAMASK-XKBE](https://metamask.sentry.io/issues/6619999470/?referrer=github_integration)

```
Error: Migration #156: newState.NftController must be present
  at r.migrate (app/scripts/migrations/156.ts:32:7)
  at Migrator.migrateData (app/scripts/lib/migrator/index.js:43:46)
  at loadStateFromPersistence (app/scripts/background.js:693:9)
  at initialize (app/scripts/background.js:509:11)
  at <anonymous> (app/scripts/background.js:1406:3)
```

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Log the error in migration instead of captureException

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33315?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33314

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

File: app/scripts/migrations/156.ts [hunk 1]
```diff
@@ -39,7 +39,8 @@ function transformState(state: Record<string, unknown>) {
   const newState = cloneDeep(state);
 
   if (!hasProperty(newState, 'NftController')) {
-    throw new Error(`newState.NftController must be present`);
+    console.error(`newState.NftController must be present`);
```
Comment (Gudahtt) [inline app/scripts/migrations/156.ts:42]: Nit: I know I didn't differentiate in our earlier discussion, but maybe `console.warn` is more appropriate here since this isn't really an error case?

Not a big deal though, it solves the bug either way

```suggestion
    console.warn(`newState.NftController must be present`);
```

**Review by Gudahtt — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
