### PR TITLE
UX: Multichain: Account Details Fixes

### LINKED ISSUE #18992: Account details UI fixes
### Edit Account name

-Error state state should be shown with the border of the inout in red and the help text left aligned. 

Build

Design

### Password for Private Key 

-Password is not hidden when typing it.
-Ideally we would have an input with a hide/unhide icon, but in the mean time, we can default to hiding the password like we do currently. 
-Label of the input would in medium weight and not bold  

Build

-When the password is incorrect, we show the error copy two times. We should show only the help text in the input. 

-When the password is incorrect and user goes back to the account details we show a "incorrect password" alert that is not related to that screen.

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

Fixes #18992 

The following Account Details issues were fixed:

1.  Rewrote the Editable label completely to show correct state and not duplicate errors
2. Fixed the font-weight of the password label
3. Removed the duplicate error message on the authentication page
4. Hide the bad password message on the first detail screen, autofocus the password field

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by vthomas13 — DISMISSED** [review]

File: ui/components/ui/editable-label/editable-label.js [hunk 1]
```diff
@@ -40,48 +49,44 @@ export default class EditableLabel extends Component {
...
-      </div>
+      </Box>
     );
   }
 
   renderReadonly() {
     return (
-      <div className={classnames('editable-label', this.props.className)}>
-        <div className="editable-label__value">{this.state.value}</div>
+      <Box display={DISPLAY.FLEX} alignItems={AlignItems.center} gap={3}>
```
Comment (NidhiKJha) [inline ui/components/ui/editable-label/editable-label.js:80]: Let's not remove the className since the EditableLabel has been used as a child component in AccountDetailsModal as well and className has been passed as a prop. 
```suggestion
      <Box className={classnames('editable-label', this.props.className)} display={DISPLAY.FLEX} gap={3}>
```

Comment (NidhiKJha) [inline ui/components/ui/editable-label/editable-label.js:80]:
```suggestion
      <Box className={classnames('editable-label', this.props.className)} display={DISPLAY.FLEX} gap={3}>
```

**Review by NidhiKJha — DISMISSED** [review]
Let's not remove the className since the EditableLabel has been used as a child component in AccountDetailsModal as well and className has been passed as a prop.

File: ui/components/ui/editable-label/editable-label.js (hunk 1 above)
Comment (darkwing) [reply ui/components/ui/editable-label/editable-label.js:86]: Good shout!

**Review by vthomas13 — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
