### PR TITLE
fix: account list in SRP reveal flow

### LINKED ISSUE #35731: [Bug]: Wrong amount showing in SRP account detail list on settings
### Describe the bug

I am seeing a wrong amount of balance in my SRP account details on settings compared to my homepage. I have $16.04 in my account but I'm seeing only $1 on my account details in SRP settings. 

### Expected behavior

The amount should be the same for both. I believe there's an issue with the one in Settings > SRP > accounts

### Screenshots/Recordings

Image

Image

https://github.com/user-attachments/assets/24f73c3b-2c29-4a4e-b901-a276af60cd97

### Steps to reproduce

1. Go to settings
2. Click on 'Secret Recovery Phrase'
3. Click on 'Show x accounts'
4. The balance within those details does not tally with my actual balance

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.1.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #38115: [Bug]: Backup SRP - Clicking on `Show accounts` in the backup page displays incorrect Account icon (jazzicons instead of my current selection) as well as all names cut and incorrect spacing
### Describe the bug

Clicking on `Show accounts` in the backup page displays a list of accounts with several issues:
- Account icons are incorrect -> I don't see my current icon selection (Polycons) but Jazzicons
- The Account names are all cut
- The spacing between columns is not ideal -> lot of space on the right

### Expected behavior

_No response_

### Screenshots/Recordings

Image

Image

### Steps to reproduce

1. Go to Privacy Settings
2. Click Backup SRP
3. Click Show Accounts

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39005?quickstart=1)

The account list displayed on the SRP reveal flow was outdated by showing the UI pre-BIP44. This PR updates the UI to show the correct multichain account list.

## **Changelog**

CHANGELOG entry: Update SRP flow to display multichain accounts

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/35731
Fixes: https://github.com/MetaMask/metamask-extension/issues/38115
Fixes: https://consensyssoftware.atlassian.net/browse/MUL-1363

## **Manual testing steps**

1. Import 2 or more SRPs
2. Create multiple accounts for each SRP (3 or more)
3. Go to the reveal SRP flow
4. Check that the account name, icon, and balance is correct when toggling the "Show X accounts" option
5. Check that the revealed SRP is the correct one

### **Before**

Review linked issues for before screenshots

### **After**

https://github.com/user-attachments/assets/a1980e71-11b3-4174-8112-e981355c0e28

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Modernizes the SRP reveal flow to correctly display multichain accounts and balances.
> 
> - Introduces `SrpCard` and simplifies `SrpList` to source wallet IDs via `getWalletIdsByType(AccountWalletType.Entropy)` and render accounts from `useWalletInfo`
> - Simplifies `SrpListItem` API to `accountId/accountName/balance`, uses `PreferredAvatar` seeded by `getIconSeedAddressByAccountGroupId`, and displays provided fiat balance
> - Adds selector `getWalletIdsByType` in `selectors/multichain-accounts/account-tree`
> - Updates/adds tests: `srp-list.test.tsx`, `srp-card.test.tsx`, and `srp-list-item.test.tsx` to match new data flow and UI
> - E2E: stabilizes multichain account creation by waiting for "Adding account..." to clear; fixes SRP ownership check and expected account label
> - Minor UI tweak: increases `srp-list__account-name` max width to 120px and exports `SrpListItem`
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e09bda0a817a72df55f95aa0f49c92163b1e39e8. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/multichain/multi-srp/srp-list/srp-card.tsx [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+        ? t('SrpListHideSingleAccount', [numberOfAccounts])
+        : t('SrpListShowSingleAccount', [numberOfAccounts]);
+    },
+    [showAccounts, t],
+  );
+
+  return (
+    <Card
+      key={`srp-${keyringId}`}
+      data-testid={`hd-keyring-${keyringId}`}
```
[the remark this answers is not in the document]
Comment (gantunesr) [reply ui/components/multichain/multi-srp/srp-list/srp-card.tsx:76]: https://github.com/MetaMask/metamask-extension/pull/39005/commits/23e30cfded67ef2174f6d16763b5888823422537

**Review by vinnyhoward — DISMISSED** [review]

**Review by chloeYue — APPROVED** [review]

File: ui/components/multichain/multi-srp/srp-list/srp-list.tsx [hunk 2]
```diff
@@ -40,38 +17,14 @@ export const SrpList = ({
...
-    useSelector(getMetaMaskAccounts);
-
-  const showAccountsInitState = useMemo(
-    () => new Array(hdKeyringsWithSnapAccounts.length).fill(hideShowAccounts),
-    [hdKeyringsWithSnapAccounts, hideShowAccounts],
-  );
-
-  const [showAccounts, setShowAccounts] = useState<boolean[]>(
-    showAccountsInitState,
+  const walletIdsFromStore = useSelector((state) =>
```
Comment (ccharly) [inline ui/components/multichain/multi-srp/srp-list/srp-list.tsx:24]: Very nit: Could have been named `entropyWalletIds` instead?

File: ui/components/multichain/multi-srp/srp-list/srp-card.tsx [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+        trackEvent({
+          category: MetaMetricsEventCategory.Accounts,
+          event: MetaMetricsEventName.SecretRecoveryPhrasePickerClicked,
+          properties: {
+            // TODO: Fix in https://github.com/MetaMask/metamask-extension/issues/31860
+            // eslint-disable-next-line @typescript-eslint/naming-convention
+            button_type: 'srp_select',
+          },
+        });
+        keyringId && onActionComplete(keyringId, shouldTriggerBackup);
```
Comment (ccharly) [inline ui/components/multichain/multi-srp/srp-list/srp-card.tsx:87]: Nit: But we're not using this kind of notation often for actual callback code, maybe `if (keyringId) { onActionComplete(... ) }` would have been slightly better?

**Review by vinnyhoward — APPROVED** [review]

**Review by ccharly — APPROVED** [review]
LGTM + tested

File: ui/components/multichain/multi-srp/srp-list/srp-list.tsx (hunk 2 above)
Comment (gantunesr) [reply ui/components/multichain/multi-srp/srp-list/srp-list.tsx:24]: https://github.com/MetaMask/metamask-extension/pull/39077

File: ui/components/multichain/multi-srp/srp-list/srp-card.tsx (hunk 3 above)
Comment (gantunesr) [reply ui/components/multichain/multi-srp/srp-list/srp-card.tsx:87]: https://github.com/MetaMask/metamask-extension/pull/39077
