### PR TITLE
fix: add missing metrics to import SRP flow and grouped Import SRP events

### LINKED ISSUE #37612: [Bug]: Add missing metrics to import SRP flow
### Describe the bug

In a recent PR, the Social Login team replaced the old import SRP component with the new one from onboarding. This is a great change that fixes several bugs. That being said, this new component is missing the metrics that the Accounts team was relying on. These metrics need to be added back. 

### Expected behavior

Here are the details:

**Metrics**

**Import Secret Recovery Phrase Clicked:**  

This event needs to be added

It should fire when the user clicks the import wallet button on the account list.

**Import Secret Recovery Phrase Completed**  

This event is firing but is missing the following properties.

Properties:

hd_entropy_index: int

Represents the number of SRPs in the wallet. 

[This](https://github.com/MetaMask/metamask-extension/blob/db25338767e1db8d57b8fd4a10c841728679a4ec/ui/selectors/selectors.js#L647-L648) is the util function we are using on extension to calculate this.

It should fire when the user finishes importing an SRP (they click continue)

### Screenshots/Recordings

n/a

### Steps to reproduce

n/a

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

13.9.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by smgv**
## **Description**

In this PR, added missing track event for SRP import: click event in Add Wallet modal and completion event with hd_entropy_index on import.

- Metrics

  - Import Secret Recovery Phrase Clicked:  
        This event needs to be added
        It should fire when the user clicks the import wallet button on the account list.

  - Import Secret Recovery Phrase Continue Button Clicked:  
        It should fire when the user finishes importing an SRP (they click continue)
        
Also we've enhanced our tracking by grouping the Import Secret Recovery Phrase event with specific status properties: 'started', 'continue_button_clicked', and 'completed', along with location data. This provides visibility into the full workflow timeline from initiation to completion.

Jira Link: https://consensyssoftware.atlassian.net/browse/SL-277

Segment Schema PR: https://github.com/Consensys/segment-schema/pull/367/files

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37567?quickstart=1)

## **Changelog**

CHANGELOG entry: added missing metrics to import SRP flow

## **Related issues**

Fixes:

## **Manual testing steps**

1. Open extesnion.
2. Create Wallet.
3. Add wallet and track event when user clicks on 'Import a wallet' and when user successfully import the SRP.

### **After**

Screenshot 2025-11-06 at 3 20 25 PM
Screenshot 2025-11-06 at 3 21 04 PM

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Unifies SRP import tracking into a single event with start/continue/completed statuses and adds hd_entropy_index and discovered account counts on completion.
> 
> - **Metrics**:
>   - Consolidate `ImportSecretRecoveryPhraseClicked`/`Completed` into `ImportSecretRecoveryPhrase` with status-based phases (`started`, `continue_button_clicked`, `completed`).
> - **Background** (`app/scripts/metamask-controller.js`):
>   - On SRP import completion, track `ImportSecretRecoveryPhrase` with `hd_entropy_index`, `number_of_solana_accounts_discovered`, and `number_of_bitcoin_accounts_discovered`.
> - **UI**:
>   - `ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx`: Track `ImportSecretRecoveryPhrase` with `status: 'started'` when selecting "Import a wallet" (location: Add Wallet Modal).
>   - `ui/components/multichain/account-menu/account-menu.tsx`: Track `ImportSecretRecoveryPhrase` with `status: 'started'` when clicking SRP import (location: Account Menu).
>   - `ui/pages/multi-srp/import-srp/import-srp.tsx`: Track `ImportSecretRecoveryPhrase` with `status: 'continue_button_clicked'` on continue (location: Multi SRP Import).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit b1ca69dc9e726d0dd3818a04cb3a0aedc3d3c17b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by lwin-kyaw — DISMISSED** [review]
LGTM!

**Review by chaitanyapotti — DISMISSED** [review]

**Comment by owencraston** [comment]
Not related to the metrics at all but I noticed the paste button is not working as expected. Manually pasting works though.

https://github.com/user-attachments/assets/f789c5de-37db-4279-ab22-af31a5cad907

**Comment by owencraston** [comment]
This is the sequence of events I see when I click on the import flow and then import and SRP....

```
[mock-segment]: Events received: Account Menu Opened
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Account List Page
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Import Secret Recovery Phrase Clicked
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Import Secret Recovery Phrase Page
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Import Secret Recovery Phrase Completed
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Home
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: DeFi Stats
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: [Unrecognized event type: identify]
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Token Detected
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Token Detected
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Token Detected
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Account Added
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: [Unrecognized event type: identify]
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Account Added
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Account Added
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Account Added
[mock-segment]: POST /v1/batch
[mock-segment]: Events received: Import Secret Recovery Phrase Completed
```

https://github.com/user-attachments/assets/2ce6765d-2738-4d03-aa89-bb50305f2570

Given that the event `Events received: Import Secret Recovery Phrase Completed` gets triggered twice, one when the user clicks continue, and one when the import is complete. This makes me think that we need an intermediate step to capture the difference. My suggestion would be `Import Secret Recovery Phrase Continue Button Clicked`. This event would need to be added to the segment schema.

File: ui/pages/multi-srp/import-srp/import-srp.tsx [hunk 1]
```diff
@@ -73,20 +72,13 @@ export const ImportSrp = () => {
...
+      // As we already track that in the ImportSecretRecoveryPhraseCompleted event i.e. (dispatch(importMnemonicToVault(secretRecoveryPhrase))) above.
       trackEvent({
         category: MetaMetricsEventCategory.Wallet,
-        event: MetaMetricsEventName.ImportSecretRecoveryPhraseCompleted,
-        properties: {
-          // eslint-disable-next-line @typescript-eslint/naming-convention
-          hd_entropy_index: freshHdEntropyIndex,
-        },
+        event:
+          MetaMetricsEventName.ImportSecretRecoveryPhraseContinueButtonClicked,
```
Comment (owencraston) [inline ui/pages/multi-srp/import-srp/import-srp.tsx]: can you add the hd_entropy_index back to this property and add link a PR to the segment schema where you added it?

Comment (smgv) [reply ui/pages/multi-srp/import-srp/import-srp.tsx]: Removed the hd_entropy_index property because it is not needed for this event. As we already track that in the ImportSecretRecoveryPhraseCompleted event i.e. (dispatch(importMnemonicToVault(secretRecoveryPhrase))) above.

**Review by owencraston — DISMISSED** [review]

File: ui/pages/multi-srp/import-srp/import-srp.tsx (hunk 1 above)
Comment (smgv) [reply ui/pages/multi-srp/import-srp/import-srp.tsx]: Looking at the [referenced changes](https://github.com/MetaMask/metamask-extension/pull/37207/files#diff-0f1e6fb7372435bdba43218a4ab45befc1217a16cc72162f1d2e488365ba2936L93), I noticed there wasn’t an event for the "Continue" button click before. After reviewing, we'll proceed without adding a new event.

Thank You

**Review by chaitanyapotti — DISMISSED** [review]

File: ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx [hunk 2]
```diff
@@ -127,6 +127,20 @@ export const AddWalletModal: React.FC<AddWalletModalProps> = ({
...
+    if (option.id === 'import-wallet') {
+      // Track the event for the selected option.
+      trackEvent({
+        category: MetaMetricsEventCategory.Navigation,
+        event: MetaMetricsEventName.ImportSecretRecoveryPhraseClicked,
+        properties: {
+          location: 'Main Menu',
+          // TODO: Fix in https://github.com/MetaMask/metamask-extension/issues/31860
+          // eslint-disable-next-line @typescript-eslint/naming-convention
+          hd_entropy_index: null,
```
Comment (lwin-kyaw) [inline ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx]: Should this be zero?

**Review by lwin-kyaw — DISMISSED** [review]

File: ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx (hunk 2 above)
Comment (owencraston) [reply ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx]: why is this null here?

Comment (smgv) [reply ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx]: Removed not required

**Review by chaitanyapotti — APPROVED** [review]

**Review by owencraston — APPROVED** [review]
