### PR TITLE
Swap : Fix undefined icon url

### LINKED ISSUE #14388: [Bug]: Swap redirects me to Error page: cannot read properties of undefined (iconUrl)
### Describe the bug

**Problem**: when I go to Swap, I land on an error page saying `cannot read properties of undefined (iconUrl)`

https://user-images.githubusercontent.com/54408225/162182338-afde69ec-5f8c-4934-ba3b-6f2cc5f6c3d2.mp4

### Steps to reproduce

1. Unlock Metamask
2. Click Swap icon

### Error messages or log output

_No response_

### Version

develop branch

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context
Seems that the changes implemented here broke the flow
https://github.com/MetaMask/metamask-extension/commit/07231e42b23c4c2e1c2c3634235412ba67267318
Reported by @dan437

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## Explanation

Fix undefined icon url on the swap flow with token detection V1

## More information

* Fixes #14388

## Manual testing steps

- Go to the swap flow
- You should be able to load it and see token icons

### CODE REVIEW

File: ui/hooks/useTokensToSearch.js [hunk 1]
```diff
@@ -71,9 +71,12 @@ export function getRenderableTokenData(
...
     tokenAddress = useTokenDetection ? address?.toLowerCase() : address;
-    tokenIconUrl = useTokenDetection
-      ? tokenList[tokenAddress]?.iconUrl
-      : `images/contract/${tokenList[tokenAddress].iconUrl}`;
+
+    if (useTokenDetection) {
+      tokenIconUrl =
+        tokenList[tokenAddress]?.iconUrl ||
+        `images/contract/${tokenList[tokenAddress]?.iconUrl}`;
+    }
```
Comment (digiwand) [inline ui/hooks/useTokensToSearch.js:79]: in the previous code, if useTokenDetection was false, then 
```
tokenIconUrl = `images/contract/${tokenList[tokenAddress]?.iconUrl}`
```

should we preserve this behavior?

Comment (FrederikBolding) [reply ui/hooks/useTokensToSearch.js:79]: I'm wondering if it's supposed to be `undefined` when `iconUrl` is not present though. Because I imagine `images/contract/undefined` is not a valid icon?

Comment (FrederikBolding) [reply ui/hooks/useTokensToSearch.js:79]: Perhaps
```
tokenIconUrl = tokenList[tokenAddress]?.iconUrl
if(!useTokenDetection){
    tokenIconUrl = `images/contract/${tokenIconUrl}`
}
```

Comment (GuillaumeRx) [reply ui/hooks/useTokensToSearch.js:79]: Oh yes you're right @digiwand, I mistakenly changed the behavior. Correction that right now

Comment (GuillaumeRx) [reply ui/hooks/useTokensToSearch.js:79]: Yes that's a good catch @FrederikBolding

Comment (FrederikBolding) [reply ui/hooks/useTokensToSearch.js:78]: This may be a problem elsewhere too from looking at the commit

Comment (digiwand) [reply ui/hooks/useTokensToSearch.js:78]: Oh, good catch @FrederikBolding

**Review by digiwand — DISMISSED** [review]

File: ui/hooks/useTokensToSearch.js [hunk 2]
```diff
@@ -71,9 +71,11 @@ export function getRenderableTokenData(
     // And since the token.address from allTokens is checksumaddress
     // token Address have to be changed to lowercase when we are using dynamic list
     tokenAddress = useTokenDetection ? address?.toLowerCase() : address;
-    tokenIconUrl = useTokenDetection
-      ? tokenList[tokenAddress]?.iconUrl
-      : `images/contract/${tokenList[tokenAddress].iconUrl}`;
+
+    tokenIconUrl = tokenList[tokenAddress]?.iconUrl;
```
Comment (digiwand) [inline ui/hooks/useTokensToSearch.js:75]: It seems that we can also set this on line 65 as
```let tokenIconUrl = tokenList[tokenAddress]?.iconUrl;```

Then can then remove this line and line 68

Comment (digiwand) [inline ui/hooks/useTokensToSearch.js:75]: It seems that we can also set this on line 65 as
```
let tokenIconUrl = tokenList[tokenAddress]?.iconUrl;
```

Then we can remove this line and line 68.

Comment (GuillaumeRx) [reply ui/hooks/useTokensToSearch.js]: By tweaking the logic I was able to achive it

Comment (digiwand) [reply ui/hooks/useTokensToSearch.js]: ah sorry. Now that this has been done, I see the other way was nice as well. Thank you @GuillaumeRx!

**Review by digiwand — APPROVED** [review]

File: ui/hooks/useTokensToSearch.js (hunk 2 above)
Comment (digiwand) [reply ui/hooks/useTokensToSearch.js]: Now that this has been done, I see the other way was nice as well. My apologies for missing the `tokenAddress` logic update with this suggestion. Please feel free to revert as either work with me. Thank you @GuillaumeRx!

**Comment by FrederikBolding** [comment]
@GuillaumeRx did you verify that we don't need this change elsewhere? It seemed to me from the commit that introduced this that the same problem may exist in other places

**Comment by dan437** [comment]
Thanks for the fix, @GuillaumeRx. I've tried Swaps with this PR and it's working now.

**Review by dan437 — APPROVED** [review]

**Comment by dan437** [comment]
Can we please merge it, since Swaps don't work without this?

**Comment by GuillaumeRx** [comment]
> Can we please merge it, since Swaps don't work without this?

Merging now, will do further testing to see if the error is present somewhere else
