### PR TITLE
fix: Remove sentry warning on `undefined` `TokenListController`

### LINKED ISSUE #20548: [Sentry] Error: typeof state.TokenListController is undefined
Sentry Issue: [METAMASK-X6KH](https://metamask.sentry.io/issues/4410065546/?referrer=github_integration)

```
Error: typeof state.TokenListController is undefined
  at migrateData (app/scripts/migrations/088.ts:168:7)
  at n.migrate (app/scripts/migrations/088.ts:37:3)
  at Migrator.migrateData (app/scripts/lib/migrator/index.js:43:46)
  at loadStateFromPersistence (app/scripts/background.js:397:3)
  at initialize (app/scripts/background.js:256:11)
```

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## Explanation

Prior to #20495, it was impossible for TokenListController to be undefined. But that PR added additional validation that skips over that property being initialized to an empty object.

The fix is to convert this `captureException` call to a `log.warn` call.

Fixes Sentry issue reported [here](https://metamask.sentry.io/issues/4410065546/?project=273505).

### CODE REVIEW

File: app/scripts/migrations/088.ts [hunk 1]
```diff
@@ -252,12 +252,6 @@ function migrateData(state: Record<string, unknown>): void {
         allDetectedTokens,
         (_, chainId: string) => toHex(chainId),
       );
-    } else if (hasProperty(tokensControllerState, 'allDetectedTokens')) {
-      global.sentry?.captureException?.(
```
Comment (Gudahtt) [inline app/scripts/migrations/088.ts:256]: I think this is the wrong error. The one in the Sentry report is on line 167

Comment (pedronfigueiredo) [reply app/scripts/migrations/088.ts]: Absolutely, Mark, thanks for pointing it out

File: app/scripts/migrations/088.test.ts [hunk 2]
```diff
@@ -724,7 +725,12 @@ describe('migration #88', () => {
     expect(newStorage.data).toStrictEqual(oldData);
   });
 
-  it('captures an exception if it has no TokenListController property', async () => {
+  it('Logs a warning if it has no TokenListController property', async () => {
```
Comment (Gudahtt) [inline app/scripts/migrations/088.test.ts:728]: In the other branches we hadn't bothered testing the warnings, since they're just meant for debugging purposes and it's less important to maintain this functionality over time. So I think it would be OK to delete these tests.

If we did want to test them though, I'd recommend finding an alternative approach for mocking here. At the moment if one test fails, it can leave `console.warn` mocked causing confusion for later tests (which would be very confusing if you investigate test failures in your console output from bottom-to-top)

We want any mocks to be automatically restored in any circumstances, success or failure. The easiest way to do that is probably to use Jest to apply the mock, because they we can rely on `restoreMocks`/`resetMocks` to reset it for us (we haven't enabled `resetMocks` in this repo yet, but `resetAllMocks` is already manually called in `beforeEach` in this test suite so we're covered here).

We can do this using the Jest `spyOn` method: https://jestjs.io/docs/jest-object#jestspyonobject-methodname

Contrary to what the name might suggest, it's not just for spying. `spyOn` returns a mock function that you can give a mock implementation as well, just like we can for `jest.fn()`. Though in this case, it seems that the spying is all we need anyway. Using `spyOn` here rather than setting `console.warn` directly to the mock function removes the need for the tear down phase.

In more complex cases like this, where we need a tear down phase and the built-in functionality of Jest isn't sufficient, I'd recommend the `with___` helper function pattern that Elliot describes here: https://github.com/MetaMask/contributor-docs/blob/add-more-testing-guidelines/guides/unit-testing.md#avoid-beforeeach-and-aftereach
We've used it extensively in the network controller tests to abstract away setup and teardown and ensure it runs reliably even upon failure. But that would be overkill here.

Comment (pedronfigueiredo) [reply app/scripts/migrations/088.test.ts]: Thanks for the detailed explanation, Mark. I've switched to using `spyOn` and noted the `with__` pattern you linked for future use.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by DDDDDanica — APPROVED** [review]

**Comment by gauthierpetetin** [comment]
Hi,
As this issue is still present in `v10.35.1`, despite the fix added in this PR, shall we consider handling scenario where state is undefined and scenario where state.TokenListController is undefined?
````
    console.warn(
      new Error(
        state ? (state.TokenListController ? `typeof state.TokenListController is ${typeof state.TokenListController}` : "state.TokenListController is undefined") : "state is undefined",
      ),
````

**Comment by Gudahtt** [comment]
`typeof state.TokenListController` will already return `undefined` in the case where `state.TokenListController` is `undefined`, so that should be equivalent to what we have already

**Comment by gauthierpetetin** [comment]
It seems the fix in this PR was not included in 10.35.1, because when looking a the [Sentry error](https://metamask.sentry.io/issues/4410065546/events/46a631cc384943a1b8af0be187ad4f19/?project=273505), we still have `global.sentry?.captureException` at line 167 from the [app/scripts/migrations/088.ts file](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/migrations/088.ts#L167), while we wanted to replace it with `console.warn` with this PR.

**Comment by gauthierpetetin** [comment]
Also is it on purpose that we have:
````
console.warn(
      new Error(
        `typeof state.TokenListController is ${typeof state.TokenListController}`,
      ),
    );
````
I'm surprised that we throw an error inside `console.warn`.
Shall we replace it with:
````
console.warn(`typeof state.TokenListController is ${typeof state.TokenListController}`);
````
