### PR TITLE
Fix details when transferring NFT not added to wallet

### LINKED ISSUE #18915: [Bug]: Sending an ERC721 token from a Dapp does not display token id and the Edit screen is incorrect, if the token is not previously added on the Wallet
### Describe the bug

**Problem**: whenever we are trying to send an ERC721 token from a dapp, we see 2 problems arise if the token is not previously added on the dapp:

- On the Send token screen, we do not see the token id
- If we click Edit, we see as if we were sending ETH - not a token

https://user-images.githubusercontent.com/54408225/235636645-b90fa125-753d-470f-bb04-4e50e75e2192.mp4

### Steps to reproduce

1. Go to test dapp
2. Click Deploy Collectibles and accept
3. Click Mint and accept
4. Click Transfer From -- see how no token id is shown
5. Click Edit -- see how no token is displayed, it looks like a regular send

### Error messages or log output

_No response_

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #18915

Display NFT details correctly while transferring NFT, even if NFT is not previously added to Metamask:

https://user-images.githubusercontent.com/2182307/236742743-bde0ca14-73bb-4866-b600-b23949c2bbcd.mov

### CODE REVIEW

File: ui/components/app/confirm-subtitle/confirm-subtitle.js [hunk 1]
```diff
@@ -1,27 +1,34 @@
...
+  assetStandard,
 }) => {
   const shouldShowFiat = useSelector(getShouldShowFiat);
   const { isNftTransfer } = useTransactionInfo(txData);
 
-  if (!shouldShowFiat && !isNftTransfer) {
+  if (
+    !shouldShowFiat &&
+    !isNftTransfer &&
+    assetStandard !== ERC1155 &&
```
Comment (darkwing) [inline ui/components/app/confirm-subtitle/confirm-subtitle.js:29]: Should we make the `assetStandard !== ERC1155 && && assetStandard !== ERC721` a helper function?  I think we use this multiple times in the codebase.  Maybe a helper function called `isNftStandard`?

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js [hunk 2]
```diff
@@ -204,11 +212,15 @@ export default class SendAssetRow extends Component {
         onClick={() => this.selectToken(AssetType.native)}
       >
         <div className="send-v2__asset-dropdown__asset-icon">
-          <Identicon
-            diameter={36}
-            image={nativeCurrencyImage}
-            address={nativeCurrency}
-          />
+          {sendAsset?.type === AssetType.NFT && sendAsset?.details?.image ? (
+            <img width={36} src={sendAsset?.details?.image} />
```
Comment (darkwing) [inline ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:216]: Since we checked for `sendAsset?.details?.image` in line 215, I don't think we need the optional chaining here.

**Review by darkwing — DISMISSED** [review]

File: ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js [hunk 3]
```diff
@@ -120,7 +123,18 @@ export default function ConfirmTokenTransactionBase({
...
-    title = assetName || getTitleTokenDescription();
+    if (assetName) {
+      const isExistingNft = nfts?.find(
+        ({ address, tokenId: _tokenId }) =>
+          isEqualCaseInsensitive(tokenAddress, address) && _tokenId === tokenId,
+      );
+      title = assetName;
+      if (!isExistingNft && assetStandard === TokenStandard.ERC721) {
+        title = `${title} #${tokenId}`;
+      }
```
Comment (digiwand) [inline ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js:134]: maybe 
```suggestion
      title = !isExistingNft && assetStandard === TokenStandard.ERC721
        ? `${title} #${tokenId}`
        : assetName;
```

File: ui/components/app/confirm-subtitle/confirm-subtitle.js (hunk 1 above)
Comment (jpuri) [reply ui/components/app/confirm-subtitle/confirm-subtitle.js:29]: Done

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js (hunk 2 above)
Comment (jpuri) [reply ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:216]: fixed

File: ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js (hunk 3 above)
Comment (digiwand) [reply ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js]: Screen Shot 2023-05-12 at 3 07 35 PM

oh no, I think my suggestion was not lint-free. sorry about that

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js [hunk 4]
```diff
@@ -157,6 +157,9 @@ export default class SendAssetRow extends Component {
       if (nft) {
         return this.renderNft(nft);
       }
+      if (details) {
+        return this.renderNft(details);
+      }
```
Comment (segun) [inline ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:162]: Thinking we could combine these two conditions

```suggestion
      if (nft || details) {
         return this.renderNft(nft ?? details);
      }
```

**Review by segun — DISMISSED** [review]

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js (hunk 4 above)
Comment (digiwand) [reply ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:162]: __unresolving this__

now that they are combined, there is still a redundant 
```
if (nft) {
        return this.renderNft(nft);
}
```
check above

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js [hunk 5]
```diff
@@ -157,6 +157,9 @@ export default class SendAssetRow extends Component {
       if (nft) {
         return this.renderNft(nft);
       }
```
Comment (digiwand) [inline ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:159]:
```suggestion
```

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js (hunk 4 above)
Comment (jpuri) [reply ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:162]: This change is already added to code.

File: ui/helpers/utils/transactions.util.js [hunk 6]
```diff
@@ -215,3 +216,12 @@ export function getTransactionTypeTitle(t, type, nativeCurrency = 'ETH') {
     }
   }
 }
+
+/**
+ * Method to check if asset standard passed is NFT
+ *
+ * @param {*} assetStandard - string
```
Comment (digiwand) [inline ui/helpers/utils/transactions.util.js:223]:
```suggestion
 * @param {string} assetStandard
```

File: ui/helpers/utils/transactions.util.js [hunk 7]
```diff
@@ -215,3 +216,12 @@ export function getTransactionTypeTitle(t, type, nativeCurrency = 'ETH') {
...
+ * @returns boolean
```
Comment (digiwand) [inline ui/helpers/utils/transactions.util.js:224]:
```suggestion
 * @returns {boolean}
```

ref: https://jsdoc.app/tags-returns.html

**Review by digiwand — APPROVED** [review]
LGTM! 

minor jsdoc suggestions above

**Review by segun — APPROVED** [review]
LGTM
