### PR TITLE
Fixing ENS input styling for confusable chars

### LINKED ISSUE #15886: [Bug]: ENS recipient styling in send flow
### Describe the bug

The ens recipient styling wraps onto multiple lines 

### Steps to reproduce

1. Login to MM
2. Click the Send button
3. Enter the following ENS name `1.offchainexample.eth`

Actual:
actual

Expected:
expected

### Error messages or log output

_No response_

### Version

10.19.0

### Build type

_No response_

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/15886

## Test Plan
Defined in issue

By designating the `<Tooltip/>` wrapper tag as a `span` we get inline behavior for confusable chars.

Screen Shot 2022-09-20 at 9 03 40 AM

Screen Shot 2022-09-20 at 9 04 44 AM

### CODE REVIEW

File: ui/components/ui/confusable/confusable.component.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ const Confusable = ({ input }) => {
     return (
       <Tooltip
         key={index.toString()}
-        as="span"
```
Comment (ryanml) [inline ui/components/ui/confusable/confusable.component.js:21]: No `as` prop exists for `Tooltip`

**Review by PeterYinusa — APPROVED** [review]

File: ui/components/ui/confusable/confusable.component.js (hunk 1 above)
Comment (brad-decker) [reply ui/components/ui/confusable/confusable.component.js:21]: @georgewrmarshall the underlying component, ReactTippy, takes tag. We may want an issue to change our Tooltip component to use 'as' but pass 'props.as' as 'tag' to ReactTippy so our surface area API for components is roughly the same.

**Review by brad-decker — APPROVED** [review]
