### PR TITLE
fix: cp-13.2.0 network manager GNS removal update

### LINKED ISSUE #35363: [Bug]: Clicking on cancel during adding a new network results in invalid state
### Describe the bug

When adding a new network if you click on cancel instead of Approve on the confirmation in the portfolio view the dropdown has selection as current network and no tokens are shown

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/8cd328a2-5ca6-4ba0-9f0a-64fbeb44484f

### Steps to reproduce

1. Login to MM
2. On the home page select the dropdown in the tokens tab
3. Click on Add on any of the networks
4. In the modal click on cancel

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

13.2.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

- [x] Update Network Dropdown button. (DONE)
  - [x] Shows "All Networks", and single network
  - [x] Updates UI to match new designs in [figma](https://www.figma.com/design/1wlWc8q6KxijWsqeUuDs5O/Network-selector-tweaks?node-id=15-2695&t=MCQF20rXVpGofDfD-0)
  
- [x] Update Network Manager Modal (DONE)
  - [x] Converts checkboxes into single select networks
  - [x] Adds a "All Networks" Item to match [figma](https://www.figma.com/design/1wlWc8q6KxijWsqeUuDs5O/Network-selector-tweaks?node-id=15-2695&t=MCQF20rXVpGofDfD-0)
  - [x] Selecting a single network updated NetworkEnabledMap to only have 1 item.
  - [x] Selecting "add network" will either update UI with selectAll or change to that selected network.

- [x] Audit Network Manager usage & prevent weird states (DONE)
  - [x] Add migration or ensure on startup that only 1 network is selected (if >1 but not all popular networks selected, then network enabled map needs to be reset).
  - [x] Audit areas that update NetworkEnabledMap to either only update 1 item, or update all items (cannot "add" network to enabled map).

<details><summary>Dev Logs</summary>

https://www.loom.com/share/5e8acf1524f041df88a7744164086d4e?sid=c08ac409-781e-4096-9d1f-6e270ad6f703

https://www.loom.com/share/4a37a8af78c94c10819b29f7b9d503ff?sid=5f2b3bcc-faaf-4f6f-ad9d-0bd36ae4f44f

https://www.loom.com/share/43319525e3984493a3b6e418f150df97?sid=288dd44e-88ed-4caa-8e3e-a8ccbffb0905

https://www.loom.com/share/967bace7454a4a2a849ed1baa09506f0?sid=823b21fa-4670-4aa8-9d39-474d60e83a9b

https://www.loom.com/share/f9384a11a6a841d4aa26738208143ac3?sid=66a111d9-e6ef-49de-9e25-97ced3a0fd08
</details> 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35264?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/35363

## **Manual testing steps**

**Network Dropdown**
1. Open dropdown
2. Select "All popular networks" view, EXPECTED - shows all popular networks
3. Select a single popular network, EXPECTED - shows content for single network
4. Select custom tab > testnet, EXPECTED - shows content for single network
5. Select custom tab > custom network, EXPECTED - shows content for single network

**Send**
1. Send tokens on a different network that what you previously had selected, EXPECTED - will change to that network.

**Swap/Bridge**
1. Swap/bridge to networks that you have not selected in the home view, EXPECTED - will change to "all popular networks view" as we need to show the transaction activity page for multichain swaps.

### **After**

https://www.loom.com/share/304ed4687a3e4437aad1399b467b1660?sid=6958f3e9-3f51-4df7-97b3-dda56b6665a4

Figma Designs:
https://www.figma.com/design/1wlWc8q6KxijWsqeUuDs5O/Network-selector-tweaks?node-id=0-1&p=f&t=QnbSaceWDpjwXgPx-0
https://www.figma.com/design/1wlWc8q6KxijWsqeUuDs5O/Network-selector-tweaks?node-id=212-6362&p=f&t=K4vKju0X2faDowlp-0

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 1]
```diff
@@ -281,11 +286,13 @@ const AssetListControlBar = ({
         : (currentMultichainNetwork.network.nickname ?? t('currentNetwork'));
     }
 
+    // NOTE - a little lazy here with this evalution
+    // We could have: enabledNetworks if selected > 1; allNetworks if equal to all active popular networks
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx]: We can remove this, I think it is relatively safe to assume >1 networks should show 'all networks' text

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 2]
```diff
@@ -281,11 +286,13 @@ const AssetListControlBar = ({
...
     if (
       isGlobalNetworkSelectorRemoved &&
       Object.keys(enabledNetworksByNamespace).length > 1
     ) {
-      return t('enabledNetworks');
+      return t('allNetworks');
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx]: Discuss if this needs to be "All networks" or "All popular networks"

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 3]
```diff
@@ -303,13 +310,38 @@ const AssetListControlBar = ({
...
+    enabledNetworksByNamespace,
+    isTokenNetworkFilterEqualCurrentNetwork,
+    currentMultichainNetwork.isEvmNetwork,
+    currentMultichainNetwork.network.nickname,
+    currentMultichainNetwork?.nickname,
+    t,
+    allNetworks,
+  ]);
+
+  const singleNetworkIconUrl = useMemo(() => {
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:322]: memo val to validate and grab network image for the network dropdown.

Screenshot 2025-08-20 at 21 59 53
Screenshot 2025-08-20 at 21 59 58

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 4]
```diff
@@ -303,13 +310,38 @@ const AssetListControlBar = ({
...
+    enabledNetworksByNamespace,
+  ]);
 
   return (
     <Box
       className="asset-list-control-bar"
-      marginLeft={2}
-      marginRight={2}
+      marginLeft={4}
+      marginRight={4}
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:343]: Modified padding so the network dropdown is inline with other content.

Screenshot 2025-08-20 at 22 01 44

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 5]
```diff
@@ -323,7 +355,7 @@ const AssetListControlBar = ({
               : toggleNetworkFilterPopover
           }
           disabled={isGlobalNetworkSelectorRemoved ? false : isDisabled}
-          size={ButtonBaseSize.Sm}
+          size={ButtonBaseSize.Md}
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:357]: icon sizes are increased to match figma.

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 6]
```diff
@@ -332,9 +364,20 @@ const AssetListControlBar = ({
...
+            {singleNetworkIconUrl && (
+              <AvatarNetwork
+                name={currentMultichainNetwork.nickname}
+                src={singleNetworkIconUrl}
+                size={AvatarNetworkSize.Sm}
+                borderWidth={0}
+              />
+            )}
+            <Text ellipsis>{networkButtonText}</Text>
+          </Box>
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:379]: optional image for when a single network is selected.
Ensured that the text ellipsis still functions if network name is very large.

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 7]
```diff
@@ -348,9 +391,9 @@ const AssetListControlBar = ({
                 data-testid="sort-by-popover-toggle"
                 className="asset-list-control-bar__button"
                 onClick={toggleTokenSortPopover}
-                size={ButtonBaseSize.Sm}
+                size={ButtonBaseSize.Md}
                 startIconName={IconName.Filter}
-                startIconProps={{ marginInlineEnd: 0 }}
+                startIconProps={{ marginInlineEnd: 0, size: IconSize.Md }}
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:395]: Increase icon sized to match figma.

File: ui/components/app/assets/asset-list/asset-list-control-bar/index.scss [hunk 8]
```diff
@@ -1,6 +1,6 @@
 .asset-list-control-bar {
-  padding-top: 4px;
-  padding-bottom: 4px;
+  padding-top: 24px;
+  padding-bottom: 8px;
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/index.scss:3]: Added padding to match figma

Screenshot 2025-08-20 at 22 04 49

File: ui/components/app/assets/asset-list/import-control/import-control.tsx [hunk 9]
```diff
@@ -30,9 +31,9 @@ const AssetListControlBar = ({
       className="asset-list-control-bar__button"
       data-testid="asset-list-control-bar-action-button"
       disabled={!shouldShowTokensLinks}
-      size={ButtonBaseSize.Sm}
+      size={ButtonBaseSize.Md}
       startIconName={IconName.MoreVertical}
-      startIconProps={{ marginInlineEnd: 0 }}
+      startIconProps={{ marginInlineEnd: 0, size: IconSize.Md }}
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/import-control/import-control.tsx:36]: increased icon size to match figma

File: ui/components/app/assets/nfts/nfts-tab/nfts-tab.tsx [hunk 10]
```diff
@@ -127,7 +127,7 @@ export default function NftsTab() {
 
   return (
     <>
-      <Box marginTop={2}>
+      <Box>
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/nfts/nfts-tab/nfts-tab.tsx:130]: Removed margins so control bar paddings match across tabs (token tab, nft tab, etc)

File: ui/components/app/transaction-list/index.scss [hunk 11]
```diff
@@ -4,7 +4,6 @@
   display: flex;
   flex-direction: column;
   flex: 1;
-  padding-top: 8px;
```
Comment (Prithpal-Sooriya) [inline ui/components/app/transaction-list/index.scss:7]: Removed padding on activity tab so the activity bar is aligned on all tabs.

File: ui/components/component-library/avatar-network/avatar-network.tsx [hunk 12]
```diff
@@ -77,16 +81,20 @@ export const AvatarNetwork: AvatarNetworkComponent = React.forwardRef(
...
-                  ? 'mm-avatar-network__network-image--size-reduced'
-                  : 'mm-avatar-network__network-image'
-              }
-              onError={handleOnError}
-              src={src}
-              alt={(name && `${name} logo`) || 'network logo'}
-            />
+            {isIconSrc(src) ? (
+              <Icon name={src} />
+            ) : (
```
Comment (Prithpal-Sooriya) [inline ui/components/component-library/avatar-network/avatar-network.tsx]: Added support for the Avatars to take in our Icons and not just remote images.

File: ui/components/multichain/account-overview/account-overview-tabs.tsx [hunk 13]
```diff
@@ -112,7 +112,7 @@ export const AccountOverviewTabs = ({
             data-testid="account-overview__asset-tab"
             {...tabProps}
           >
-            <Box marginTop={2} marginBottom={2}>
+            <Box marginBottom={2}>
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/account-overview/account-overview-tabs.tsx:115]: Modified padding and margin on this page so that the activity bar is aligned across pages without any extra hacks.

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx [hunk 14]
```diff
@@ -305,7 +303,7 @@ export const AppHeaderUnlockedContent = ({
               onClick={() => {
                 handleMainMenuOpened();
               }}
-              size={ButtonIconSize.Sm}
+              size={ButtonIconSize.Lg}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/app-header/app-header-unlocked-content.tsx:313]: Increased menu icon size to match figma

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx [hunk 15]
```diff
@@ -289,12 +289,10 @@ export const AppHeaderUnlockedContent = ({
             display={Display.Flex}
             justifyContent={JustifyContent.flexEnd}
             width={BlockSize.Full}
+            style={{ position: 'relative' }}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/app-header/app-header-unlocked-content.tsx:299]: Moved and fixed notification icon positioning on the larger menu icon.

Screenshot 2025-08-20 at 22 08 50

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx [hunk 16]
```diff
@@ -96,6 +86,31 @@ const DefaultNetworks = memo(() => {
...
+  );
+
+  const isSingleNetworkSelected = useCallback(
+    (chainId: Hex) => {
+      return (
+        !isAllPopularNetworksSelected && chainId in enabledNetworksByNamespace
+      );
+    },
+    [enabledNetworksByNamespace, isAllPopularNetworksSelected],
+  );
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:113]: New network manager logic to determine when "All popular networks" vs a single network are selected.
Screenshot 2025-08-20 at 22 10 34
Screenshot 2025-08-20 at 22 10 38

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx [hunk 17]
```diff
@@ -116,14 +127,12 @@ const DefaultNetworks = memo(() => {
     );
     const finalNetworkClientId = defaultRpcEndpoint.networkClientId;
 
-    dispatch(setEnabledNetworks(evmChainIds, namespace));
+    dispatch(enableAllPopularNetworks());
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:131]: Replaced `setEnabledNetworks` with a more strict `enableAllPopularNetworks`

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx [hunk 18]
```diff
@@ -274,21 +270,15 @@ const DefaultNetworks = memo(() => {
...
-        </Box>
+        {isEvmNetworkSelected ? (
+          <NetworkListItem
+            name={t('allPopularNetworks')}
+            onClick={selectAllDefaultNetworks}
+            iconSrc={IconName.Global}
+            iconSize={AvatarNetworkSize.Md}
+            selected={isAllPopularNetworksSelected}
+          />
+        ) : null}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/default-networks/default-networks.tsx]: "All Popular Networks" button (previously was a link style)

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx [hunk 19]
```diff
@@ -266,6 +254,14 @@ const DefaultNetworks = memo(() => {
...
             {network.name}
           </Text>
+          <ButtonIcon
+            size={ButtonIconSize.Md}
+            color={IconColor.iconDefault}
+            iconName={IconName.Add}
+            padding={0}
+            marginLeft={'auto'}
+            ariaLabel={t('addNetwork')}
+          />
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:267]: Move the "+" icon for additional networks to the right.

Screenshot 2025-08-20 at 22 13 09

File: ui/components/multichain/network-manager/hooks/useAdditionalNetworkHandlers.ts [hunk 20]
```diff
@@ -60,18 +44,9 @@ export const useAdditionalNetworkHandlers = () => {
...
-      const filteredPopularNetworks = enabledNetworksArray.filter((key) =>
-        FEATURED_NETWORK_CHAIN_IDS.includes(key as `0x${string}`),
-      );
-      await dispatch(
-        setEnabledNetworks(
-          [...filteredPopularNetworks, network.chainId],
-          namespace,
-        ),
-      );
+      await dispatch(enableSingleNetwork(network.chainId));
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/hooks/useAdditionalNetworkHandlers.ts]: Large cleanup, we use a stricter action `enableSingleNetwork`

File: ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts [hunk 21]
```diff
@@ -84,51 +84,31 @@ export const useNetworkChangeHandlers = () => {
...
 
       const isPopularNetwork = FEATURED_NETWORK_CHAIN_IDS.includes(hexChainId);
 
       const enabledNetworkKeys = Object.keys(enabledNetworksByNamespace ?? {});
 
       if (!isPopularNetwork) {
-        // if custom network is enabled, select the new network and disable the custom network
-        dispatch(setEnabledNetworks([hexChainId], namespace));
+        // custom network - select single
+        dispatch(enableSingleNetwork(hexChainId));
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts:95]: Replaced the deprecated and complex `setEnabledNetworks` action with the more strict `enableSingleNetwork` action

File: ui/components/multichain/notifications-tag-counter/notifications-tag-counter.tsx [hunk 22]
```diff
@@ -32,8 +32,8 @@ export const NotificationsTagCounter = ({
         style={{
           position: 'absolute',
           cursor: 'pointer',
-          top: '-5px',
-          left: '10px',
+          top: 0,
+          left: '50%',
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/notifications-tag-counter/notifications-tag-counter.tsx:36]: Improve notification counter positioning for the menu icon.
(this is more accurate than magic pixel numbers)

File: ui/store/actions.ts [hunk 23]
```diff
@@ -4831,6 +4831,9 @@ export function updateAccountsList(
  * This method updates the enabledNetworkMap to mark specified networks as enabled.
  * It can handle both a single chain ID or an array of chain IDs.
  *
+ * @deprecated - this unsafely sets the EnabledNetworkMap,
+ * - we want to have better control on how we enable networks (either single network or all, not in between)
+ * Please use controller-actions/network-order-controller.ts actions
```
Comment (Prithpal-Sooriya) [inline ui/store/actions.ts:4847]: Deprecated the `setEnabledNetworks` action.
This should also help us track and audit existing usage for this and replace with the more stricter actions.

File: ui/store/controller-actions/network-order-controller.ts [hunk 24]
```diff
@@ -0,0 +1,54 @@
...
+      getMultichainNetworkConfigurationsByChainId(state);
+
+    const evmPopularNetworkChainIds = FEATURED_NETWORK_CHAIN_IDS.filter(
+      (chainId) => toEvmCaipChainId(chainId) in caipNetworkConfigMap,
+    );
+    dispatch(
+      setEnabledNetworks(evmPopularNetworkChainIds, KnownCaipNamespace.Eip155),
+    );
+  };
+}
```
Comment (Prithpal-Sooriya) [inline ui/store/controller-actions/network-order-controller.ts]: A more strict action to update all popular networks in the `enabledNetworkMap`.

Comment (Prithpal-Sooriya) [reply ui/store/controller-actions/network-order-controller.ts]: NOTE - I think I really like this pattern.

Since we are using thunks, we can grab the store/state from `getState()`.
Then we can execute selectors in here, and then perform the dispatch to update.

This is reusable both in react level, and can also be lifted and used outside of react.

File: ui/store/controller-actions/network-order-controller.ts [hunk 25]
```diff
@@ -0,0 +1,54 @@
...
+    // EVM
+    if (namespace === KnownCaipNamespace.Eip155) {
+      dispatch(setEnabledNetworks([chainId], KnownCaipNamespace.Eip155));
+      return;
+    }
+
+    // Non-EVM
+    dispatch(setEnabledNetworks([caipChainId], namespace));
+  };
+}
```
Comment (Prithpal-Sooriya) [inline ui/store/controller-actions/network-order-controller.ts]: A more strict action to update a single network in the `EnabledNetworkMap`

**Comment by Prithpal-Sooriya** [comment]
Will fast follow fix on unit test and linting. I have a commit ready but waiting for CI to finish to see how many e2e failures are left

**Comment by Prithpal-Sooriya** [comment]
Pretty confident with E2E tests now 🤞🏾 

Waiting for CI to start up the GHA.

**Comment by Prithpal-Sooriya** [comment]
Requested style changes complete
https://www.loom.com/share/f9384a11a6a841d4aa26738208143ac3?sid=92f5a502-2e24-4397-b68f-05902f8a93f7

**Comment by Prithpal-Sooriya** [comment]
Ugh, there are 2 e2e tests that keep failing, both related to dapp request queueing.
Will investigate tomorrow.

**Comment by Prithpal-Sooriya** [comment]
CI IS GREEN!

File: app/scripts/controller-init/assets/index.ts [hunk 26]
```diff
@@ -2,3 +2,4 @@ export { TokenRatesControllerInit } from './token-rates-controller-init';
 export { NftControllerInit } from './nft-controller-init';
 export { NftDetectionControllerInit } from './nft-detection-controller-init';
 export { AssetsContractControllerInit } from './assets-contract-controller-init';
+export { NetworkOrderControllerInit } from './network-order-controller-init';
```
Comment (Prithpal-Sooriya) [inline app/scripts/controller-init/assets/index.ts:5]: Moved this controller to follow the init pattern.

File: app/scripts/controllers/network-order.ts [hunk 27]
```diff
@@ -54,21 +54,23 @@ export type NetworkOrderControllerupdateNetworksListAction = {
...
-  | NetworkOrderStateChange
-  | NetworkControllerStateChangeEvent
-  | NetworkControllerNetworkRemovedEvent,
+  NetworkOrderControllerMessengerEvents | AllowedEvents,
   AllowedActions['type'],
-  | NetworkOrderStateChange['type']
-  | NetworkControllerStateChangeEvent['type']
-  | NetworkControllerNetworkRemovedEvent['type']
+  AllowedEvents['type']
 >;
```
Comment (Prithpal-Sooriya) [inline app/scripts/controllers/network-order.ts:74]: Fixed types so we can use the init pattern correctly.

File: app/scripts/controllers/network-order.ts [hunk 28]
```diff
@@ -240,11 +242,11 @@ export class NetworkOrderController extends BaseController<
...
    * to be enabled. All other networks will be implicitly disabled.
-   * @param networkId - The CaipChainId of the currently selected network
+   * @param namespace - The caip-2 namespace of the currently selected network *(e.g. 'eip155' or 'solana')
    */
-  setEnabledNetworks(chainIds: string | string[], networkId: CaipChainId) {
-    if (!networkId) {
-      throw new Error('networkId is required to set enabled networks');
+  setEnabledNetworks(chainIds: string | string[], namespace: CaipNamespace) {
+    if (!namespace) {
+      throw new Error('namespace is required to set enabled networks');
```
Comment (Prithpal-Sooriya) [inline app/scripts/controllers/network-order.ts:249]: Update to use the correct parameter type - this takes the caip-2 namespace.

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js [hunk 29]
```diff
@@ -266,28 +265,15 @@ export async function switchChain(
...
-            FEATURED_NETWORK_CHAIN_IDS.includes(id),
-          );
-          setEnabledNetworks(
-            [...featuredExistingChainIds, chainId],
-            KnownCaipNamespace.Eip155,
-          );
-        } else {
-          setEnabledNetworks([chainId], KnownCaipNamespace.Eip155);
-        }
+        setEnabledNetworks([chainId], KnownCaipNamespace.Eip155);
```
Comment (Prithpal-Sooriya) [inline app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js:269]: Dapp switch chain will update filter to a single network as we do not support multiple networks now.

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js [hunk 30]
```diff
@@ -266,28 +265,15 @@ export async function switchChain(
...
       }
     } else {
       const { namespace } = parseCaipChainId(chainId);
       const existingEnabledNetworks = getEnabledNetworks(namespace);
       const existingChainIds = Object.keys(existingEnabledNetworks);
       if (!existingChainIds.includes(chainId)) {
-        setEnabledNetworks([...existingChainIds, chainId], namespace);
+        setEnabledNetworks([chainId], namespace);
```
Comment (Prithpal-Sooriya) [inline app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js:276]: Dapp switch chain will update filter to a single network as we do not support multiple networks now.

File: test/e2e/default-fixture.js [hunk 31]
```diff
@@ -86,7 +86,7 @@ function defaultFixture(inputChainId = CHAIN_IDS.LOCALHOST) {
               'https://linea-mainnet.infura.io/v3/00000000000000000000000000000000',
           },
           {
-            networkId: '0x539',
+            networkId: inputChainId,
```
Comment (Prithpal-Sooriya) [inline test/e2e/default-fixture.js:89]: `inputChainId` is `0x539`, so there is no functional change here, just reusing variables.

File: test/e2e/page-objects/pages/network-manager.ts [hunk 32]
```diff
@@ -66,40 +68,47 @@ class NetworkManager {
...
-  // Method to select/click on a network item
-  async selectNetwork(networkName: string): Promise<void> {
-    console.log(`Selecting network: ${networkName}`);
-    await this.driver.delay(regularDelayMs);
-    await this.checkNetworkIsDeselected(networkName);
-    await this.driver.delay(regularDelayMs);
-    await this.driver.clickElementSafe(this.networkListItem(networkName));
-    await this.driver.delay(regularDelayMs);
-    await this.checkNetworkIsSelected(networkName);
+  async checkAllPopularNetworksIsSelected(): Promise<void> {
```
Comment (Prithpal-Sooriya) [inline test/e2e/page-objects/pages/network-manager.ts:71]: Update NetworkManager page object. We cannot select multiple networks now and we do not render checkboxes.

File: test/e2e/tests/bridge/bridge-positive-cases.spec.ts [hunk 33]
```diff
@@ -104,17 +102,7 @@ describe('Bridge tests', function (this: Suite) {
       ),
       async ({ driver }) => {
         await unlockWallet(driver);
-
-        // disable Linea network
         const networkManager = new NetworkManager(driver);
-        await networkManager.openNetworkManager();
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/bridge/bridge-positive-cases.spec.ts:110]: Cleanup test as network manager logic has changed.

File: test/e2e/tests/multichain/aggregated-balances.spec.ts [hunk 34]
```diff
@@ -34,7 +34,6 @@ describe('Multichain Aggregated Balances', function (this: Suite) {
           .withEnabledNetworks({
             eip155: {
               [CHAIN_IDS.MAINNET]: true,
-              [CHAIN_IDS.SEPOLIA]: true,
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/multichain/aggregated-balances.spec.ts:37]: Test mocks have changed to be more realistic - we now only show 1 network at a time (unless if "all popular networks" is selected)

File: test/e2e/tests/multichain/asset-list.spec.ts [hunk 35]
```diff
@@ -41,7 +41,6 @@ function buildFixtures(title: string, chainId: number = 137) {
       .withTokensControllerERC20({ chainId })
       .withEnabledNetworks({
         eip155: {
-          [CHAIN_IDS.MAINNET]: true,
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/multichain/asset-list.spec.ts:44]: Test mocks have changed to be more realistic - we now only show 1 network at a time (unless if "all popular networks" is selected)

File: test/e2e/tests/multichain/asset-list.spec.ts [hunk 36]
```diff
@@ -75,7 +74,8 @@ describe('Multichain Asset List', function (this: Suite) {
         await loginWithoutBalanceValidation(driver);
         const assetListPage = new AssetListPage(driver);
         await switchToNetworkFromSendFlow(driver, NETWORK_NAME_MAINNET);
-        await assetListPage.checkTokenItemNumber(3);
+        // Only Ethereum network is selected so only 1 token visible
+        await assetListPage.checkTokenItemNumber(1);
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/multichain/asset-list.spec.ts:78]: Cleanup test as network manager logic has changed.
We do not support selecting multiple networks now.

File: test/e2e/tests/network/network-connection.spec.ts [hunk 37]
```diff
@@ -63,9 +68,7 @@ networkConfigs.forEach((config) => {
             .withPermissionControllerConnectedToTestDapp()
             .withEnabledNetworks({
               eip155: {
-                [CHAIN_IDS.MONAD_TESTNET]: true,
-                [CHAIN_IDS.MEGAETH_TESTNET]: true,
-                [CHAIN_IDS.SEI]: true,
+                [config.chainId]: true,
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/network/network-connection.spec.ts:71]: Update test state to better reflect real world state - we only show 1 network custom network/testnet at a time.

File: test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js [hunk 38]
```diff
@@ -79,11 +83,9 @@ describe('Request Queuing Dapp 1, Switch Tx -> Dapp 2 Send Tx', function () {
...
 
         // Network Selector
-        await driver.clickElement('[data-testid="sort-by-networks"]');
-        await driver.clickElement({
-          text: 'Custom',
-          tag: 'button',
-        });
+        const networkManager = new NetworkManager(driver);
+        await networkManager.openNetworkManager();
+        await networkManager.selectTab('Custom');
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js:88]: Cleanup test as network manager logic has changed.
Also reusing the networkManager instead of custom driver calls.

File: test/e2e/tests/request-queuing/ui.spec.js [hunk 39]
```diff
@@ -199,13 +204,10 @@ describe('Request-queue UI changes', function () {
           WINDOW_TITLES.ExtensionInFullScreenView,
         );
 
-        await driver.clickElement('[data-testid="sort-by-networks"]');
-        await driver.clickElement({
-          text: 'Custom',
-          tag: 'button',
-        });
+        const networkManager = new NetworkManager(driver);
```
Comment (Prithpal-Sooriya) [inline test/e2e/tests/request-queuing/ui.spec.js:207]: Cleanup test as network manager logic has changed.
Also using NetworkManager page object instead of custom driver calls.

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx [hunk 40]
```diff
@@ -281,11 +286,12 @@ const AssetListControlBar = ({
         : (currentMultichainNetwork.network.nickname ?? t('currentNetwork'));
     }
 
+    // > 1 network selected, show "all networks"
     if (
       isGlobalNetworkSelectorRemoved &&
       Object.keys(enabledNetworksByNamespace).length > 1
     ) {
-      return t('enabledNetworks');
+      return t('allPopularNetworks');
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:294]: Copy change.
Screenshot 2025-08-22 at 20 53 58

File: ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx (hunk 6 above)
Comment (Prithpal-Sooriya) [reply ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx:379]: Screenshot 2025-08-22 at 20 54 48

File: ui/components/app/assets/asset-list/network-filter/network-filter.tsx [hunk 41]
```diff
@@ -103,7 +101,7 @@ const NetworkFilter = ({
       handleFilterNetwork(chainFilters);
     } else {
       isGlobalNetworkSelectorRemoved
-        ? dispatch(setEnabledNetworks(Object.keys(chainFilters), chainId))
+        ? dispatch(enableSingleNetwork(chainId))
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/network-filter/network-filter.tsx:104]: We only support showing single networks or all popular networks now.

File: ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js [hunk 42]
```diff
@@ -11,17 +11,32 @@ export default class ConfirmDeleteNetwork extends PureComponent {
...
+      switchToEthereumNetwork,
+    } = this.props;
 
     // NOTE: We only support EVM networks removal, so the conversion is safe here.
     const caipChainId = toEvmCaipChainId(chainId);
+
+    // NOTE: ensure that we are not deleting a selected evm chain
+    if (isChainToDeleteSelected) {
+      await switchToEthereumNetwork?.();
+    }
```
Comment (Prithpal-Sooriya) [inline ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js:38]: Fix solana e2e edge case, ensures that we do not delete a selected network.

File: ui/components/multichain/account-overview/account-overview-tabs.tsx [hunk 43]
```diff
@@ -156,7 +156,7 @@ export const AccountOverviewTabs = ({
             data-testid="account-overview__activity-tab"
             {...tabProps}
           >
-            <TransactionList boxProps={{ paddingTop: 3 }} />
+            <TransactionList />
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/account-overview/account-overview-tabs.tsx:159]: Removed extra padding so that the activity bar is aligned across pages without any extra hacks.

File: ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx [hunk 44]
```diff
@@ -297,30 +294,10 @@ export const AssetPickerAmount = ({
...
-                          dispatch(
-                            setEnabledNetworks(
-                              [
-                                networkConfig.chainId,
-                                ...filteredPopularNetworks,
-                              ],
-                              namespace,
-                            ),
-                          );
+                          dispatch(enableSingleNetwork(networkConfig.chainId));
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx:297]: We only support updating single network or all popular networks

File: ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx [hunk 45]
```diff
@@ -297,30 +294,10 @@ export const AssetPickerAmount = ({
...
                         }
                       } else {
-                        dispatch(
-                          setEnabledNetworks(
-                            [networkConfig.chainId],
-                            namespace,
-                          ),
-                        );
+                        dispatch(enableSingleNetwork(networkConfig.chainId));
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx:300]: We only support updating single network or all popular networks

File: ui/components/multichain/connected-site-menu/connected-site-menu.js [hunk 46]
```diff
@@ -41,7 +41,7 @@ export const ConnectedSiteMenu = ({ className, disabled, onClick, status }) => {
   const iconElement = currentTabHasNoAccounts ? (
     <Icon
       name={IconName.Global}
-      size={IconSize.Sm}
+      size={IconSize.Lg}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/connected-site-menu/connected-site-menu.js:44]: Update globe icon to match updated hamburger menu.
Screenshot 2025-08-22 at 21 00 30

File: ui/components/multichain/network-list-item/network-list-item.tsx [hunk 47]
```diff
@@ -145,6 +145,7 @@ export const NetworkListItem = ({
       }
       className={classnames('multichain-network-list-item', {
         'multichain-network-list-item--selected': selected,
+        'multichain-network-list-item--deselected': !selected,
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-list-item/network-list-item.tsx:151]: Added this class to help indicate in e2e tests items that are deselected (as we do not render the checkbox now)

File: ui/components/multichain/network-manager/components/custom-networks/custom-networks.tsx [hunk 48]
```diff
@@ -130,20 +133,19 @@ export const CustomNetworks = React.memo(() => {
     });
 
     return filteredNetworks.length > 0 ? (
-      <>
+      <Box paddingBottom={2}>
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/custom-networks/custom-networks.tsx:136]: Added padding so that the custom networks, and testnets have some breathing room to match figma.

Comment (Prithpal-Sooriya) [reply ui/components/multichain/network-manager/components/custom-networks/custom-networks.tsx:136]: Screenshot 2025-08-22 at 21 02 36

File: ui/components/multichain/network-manager/index.scss [hunk 49]
```diff
@@ -17,6 +17,7 @@
 }
 
 .network-manager__tab-content {
+  padding-top: 16px;
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/index.scss:20]: Adds padding to top of tab content so there is breathing room between the tab header. Matches figma.

Screenshot 2025-08-22 at 21 02 36

File: ui/components/multichain/network-manager/index.scss [hunk 50]
```diff
@@ -38,6 +39,17 @@
...
+.network-manager__all-popular-networks {
+  .mm-avatar-base {
+    background-color: transparent;
+    border-color: transparent;
+
+    .mm-icon {
+      --icon-size: 30px;
+    }
+  }
+}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/index.scss]: The globe icon in the NetworkManager uses the an existing component that uses Avatars. This tweaks the Avatar so that the icon does not render a background and also ensures height match the other avatar heights (in figma)

Screenshot 2025-08-22 at 21 06 09

File: ui/components/multichain/network-manager/network-tabs.tsx [hunk 51]
```diff
@@ -17,11 +18,10 @@ export const NetworkTabs = ({ initialTab }: { initialTab: string }) => {
   return (
     <Box>
       <ModalHeader
-        onBack={handleClose}
         onClose={handleClose}
         closeButtonProps={{ 'data-testid': 'modal-header-close-button' }}
       >
-        Networks
+        {t('bridgeSelectNetwork') ?? 'Select network'}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/network-tabs.tsx:24]: Copy change to match figma.
Screenshot 2025-08-22 at 21 02 36

File: ui/components/multichain/network-manager/network-tabs.tsx [hunk 52]
```diff
@@ -37,12 +37,12 @@ export const NetworkTabs = ({ initialTab }: { initialTab: string }) => {
             className: 'network-manager__tab-content',
           }}
         >
-          <Tab tabKey="networks" name="Default">
+          <Tab tabKey="networks" name={t('networkTabPopular') ?? 'Popular'}>
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/network-tabs.tsx:40]: Copy change to match figma (see image above)

File: ui/components/multichain/network-manager/network-tabs.tsx [hunk 53]
```diff
@@ -37,12 +37,12 @@ export const NetworkTabs = ({ initialTab }: { initialTab: string }) => {
...
             <DefaultNetworks />
           </Tab>
           <Tab
             tabKey="custom-networks"
-            name="Custom"
+            name={t('networkTabCustom') ?? 'Custom'}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/network-tabs.tsx:45]: Not a copy change! But ensures we use our translations.

File: ui/components/multichain/notifications-tag-counter/notifications-tag-counter.tsx (hunk 22 above)
Comment (Prithpal-Sooriya) [reply ui/components/multichain/notifications-tag-counter/notifications-tag-counter.tsx:36]: Screenshot 2025-08-22 at 21 07 48

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx [hunk 54]
```diff
@@ -148,16 +148,9 @@ export const useEnableMissingNetwork = () => {
...
-            const newNetworkEnabledEvmNetworks = [
-              chainId,
-              ...enabledEvmNetworks,
-            ];
-            dispatch(
-              setEnabledNetworks(newNetworkEnabledEvmNetworks, namespace),
-            );
+            // Bridging between popular networks indicates we want the 'select all' enabled
+            // This way users can see their full briding tx activity
+            dispatch(enableAllPopularNetworks());
```
Comment (Prithpal-Sooriya) [inline ui/pages/bridge/prepare/prepare-bridge-page.tsx:153]: Bridging to tokens that you have not selected in the network manager won't show up in token list/TX Activity.

So we ensure that we change the token filters so that you can see the new tokens you've swapped to inside the token list and activity tabs.

File: ui/store/actions.ts (hunk 23 above)
Comment (Prithpal-Sooriya) [reply ui/store/actions.ts:4847]: Long term, this will be removed when we use the shared controller in CORE which exposes new methods we can use.

File: ui/components/multichain/network-manager/network-tabs.tsx (hunk 51 above)
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply ui/components/multichain/network-manager/network-tabs.tsx:24]: This is realistically a minor issue. Even if a user changes languages, when they open the modal the text will change.
It can be revisited at a later date if this actually needs refactoring.

File: ui/components/app/assets/asset-list/network-filter/network-filter.tsx (hunk 41 above)
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply ui/components/app/assets/asset-list/network-filter/network-filter.tsx:104]: This is intentional, we now only show a single network or all popular networks.

File: ui/components/component-library/avatar-network/avatar-network.tsx (hunk 12 above)
Comment (georgewrmarshall) [reply ui/components/component-library/avatar-network/avatar-network.tsx]: I think this is what `<AvatarIcon />` is for?

**Review by salimtb — DISMISSED** [review]
Assets changes lgtm

**Review by amitabh94 — DISMISSED** [review]
LGTM ! Approving on behalf of assets and swaps.
Although swaps changes make sense to me ,but @micaelae to double check.

File: ui/components/component-library/avatar-network/avatar-network.tsx (hunk 12 above)
Comment (Prithpal-Sooriya) [reply ui/components/component-library/avatar-network/avatar-network.tsx]: Great callout! After discussing, we don't need a change at this DS component level, reverting this file change and will handle the icon elsewhere.

**Review by ghgoodreau — DISMISSED** [review]

**Review by micaelae — DISMISSED** [review]

File: ui/components/component-library/avatar-network/avatar-network.tsx (hunk 12 above)
Comment (Prithpal-Sooriya) [reply ui/components/component-library/avatar-network/avatar-network.tsx]: reverted here https://github.com/MetaMask/metamask-extension/pull/35264/commits/4993a6e7d890fd545e91d0ef9495430c906b4330

Thanks, turns out no DS change required 🙌🏾

File: ui/components/multichain/network-manager/network-tabs.tsx (hunk 51 above)
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply ui/components/multichain/network-manager/network-tabs.tsx:24]: This is realistically a minor issue. Even if a user changes languages, when they open the modal the text will change.
It can be revisited at a later date if this actually needs refactoring.

File: ui/components/multichain/network-list-item/network-list-item.tsx [hunk 55]
```diff
@@ -163,13 +166,17 @@ export const NetworkListItem = ({
...
+        <Icon name={iconSrc} size={iconSize as IconSize} />
+      ) : (
+        <AvatarNetwork
+          borderColor={BorderColor.backgroundDefault}
+          backgroundColor={getAvatarNetworkColor(name)}
+          name={name}
+          src={iconSrc}
+          size={iconSize as AvatarNetworkSize}
+        />
+      )}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-list-item/network-list-item.tsx:179]: Allows this component to render either a network image, or an icon (required for the new design in figma)

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx [hunk 56]
```diff
@@ -281,7 +282,7 @@ const DefaultNetworks = memo(() => {
               name={t('allPopularNetworks')}
               onClick={selectAllDefaultNetworks}
               iconSrc={IconName.Global}
-              iconSize={AvatarNetworkSize.Md}
+              iconSize={IconSize.Xl}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:285]: NOTE
- Icon size XL = 32px
- Avatar network images are supposed to be 32px, but contain a 1px border that reduces the image size to 30px.

Screenshot 2025-08-22 at 22 38 53
Screenshot 2025-08-22 at 22 37 43

Comment (Prithpal-Sooriya) [reply ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:285]: We can follow up in a separate PR.

File: ui/components/multichain/network-manager/network-tabs.tsx (hunk 51 above)
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply ui/components/multichain/network-manager/network-tabs.tsx:24]: mentioned before, this should be okay. We also have a fallback which should be fine.

**Review by salimtb — DISMISSED** [review]
tested, works as expected , lgtm

**Review by NidhiKJha — CHANGES_REQUESTED** [review]
Adding a additional network and cancelling it, makes it buggy
https://github.com/user-attachments/assets/9a7fec34-cd67-4b05-bc44-30d04154b61c

**Comment by Prithpal-Sooriya** [comment]
> Adding a additional network and cancelling it, makes it buggy https://github.com/user-attachments/assets/9a7fec34-cd67-4b05-bc44-30d04154b61c

@NidhiKJha fixed in [77140e9](https://github.com/MetaMask/metamask-extension/pull/35264/commits/77140e9aea2ce5552885516bb96c6751bdc84208)

https://www.loom.com/share/9b5a33e4729741199bc40661b06a9dc7?sid=729f0b1c-c0f0-4272-8743-10246fbfb214

**Review by micaelae — DISMISSED** [review]

**Review by salimtb — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]

**Review by seaona — APPROVED** [review]
e2e changes look good overall

**Review by NidhiKJha — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
There are no longer any Design System changes that need code owner review but I tested the latest build and everything seems to be working as expected. Nice work on this fast turnaround 🔥 💯 

Non-blocking: In a subsequent PR we could add a `16px` `gap` between the network selector and filter buttons when the network name is really long

Screenshot 2025-08-26 at 9 58 35 AM

**Review by amitabh94 — APPROVED** [review]
