### PR TITLE
Ensure that if max is selected in send flow, the correct value is set after network switch

### LINKED ISSUE #15405: [Bug]: Incorrect max amount displayed in send flow
### Describe the bug

Scenario A: Incorrect max amount displayed when switching networks
https://user-images.githubusercontent.com/53189696/182223277-c1831f0b-2ce7-43c2-8061-482b462a15af.mov

Scenario B : Incorrect max amount displayed when switching assets
https://user-images.githubusercontent.com/53189696/182223307-f510d6bb-e690-441d-8689-7f6da1c4e4c1.mov

### Steps to reproduce

Scenario A (see video above):
1. Click the send button on the home page
2. enter a recipient address
3. click the Max amount button
4. Switch networks

Scenario B (see video above):
1. Click the send button on the home page
2. enter a recipient address
3. click the Max amount button
4. Switch assets from Native currency to an ERC20

### Error messages or log output

_No response_

### Version

10.18.0

### Build type

_No response_

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/15405

Explanation:

After switching networks, if max amount is selected on the send flow, the amount needs to be updated to reflect the new balance.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

**Review by digiwand — DISMISSED** [review]

**Review by brad-decker — APPROVED** [review]

File: ui/store/actions.js [hunk 1]
```diff
@@ -1455,10 +1459,6 @@ export function updateMetamaskState(newState) {
       // progress.
       dispatch(initializeSendState({ chainHasChanged: true }));
     }
-    dispatch({
```
Comment (danjm) [inline ui/store/actions.js:1458]: For future reference: this change was needed so that the correct balance is used in the send state when recalculating the max. This ensures that `initializeSendState` has been called after the metamask state has been updated

**Review by digiwand — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Review by NiranjanaBinoy — APPROVED** [review]
