### PR TITLE
fix(18709): fix error when switching to linea testnet using wallet_sw…

### LINKED ISSUE #18709: [Bug]: Cannot switch to linea testnet network using "wallet_switchEthereumChain"
### Describe the bug

 I got the following error when I want to use the MM API `wallet_switchEthereumChain` endpoint to switch to linea testnet network.

image

### Steps to reproduce

1. Open this website : https://testnet.cashmere.exchange/swap
2. Connect your metamask wallet.
3. Select the Linea zkEVM testnet in the `from` dropdown.
4. Click on the `Switch network` button at the bottom of the page.

### Error messages or log output

```shell
MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration Objectcode: -32603data: originalError: [[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()[[Prototype]]: Objectmessage: "networkConfigurationId undefined does not match a configured networkConfiguration"[[Prototype]]: Object
(anonymous)


Uncaught (in promise) SwitchChainError: Error switching chain
    at AY.switchChain
```

### Version

10.28.3

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by VGau**
## Explanation

Fixed the error when we use the MM API wallet_switchEthereumChain endpoint to switch to linea testnet network.
image

A new condition has been added in `app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js` file in `findExistingNetwork` function. 

* Fixes #18709

## Manual Testing Steps

- Open this website : https://testnet.cashmere.exchange/swap
- Connect your metamask wallet.
- Select the Linea zkEVM testnet in the from dropdown.
- Click on the Switch network button at the bottom of the page.
- Check if the network switching worked

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by mcmire** [comment]
This error message is coming from a change we made recently where we moved custom networks from PreferencesController to NetworkController: https://github.com/MetaMask/metamask-extension/pull/17421

I'm trying to understand why this bug exists. Is Linea testnet a network we regard as "built-in", or is something that users need to add themselves?

**Comment by VGau** [comment]
> This error message is coming from a change we made recently where we moved custom networks from PreferencesController to NetworkController: #17421
> 
> I'm trying to understand why this bug exists. Is Linea testnet a network we regard as "built-in", or is something that users need to add themselves?

This bug exits because we are not getting the network info using this function `findNetworkConfigurationBy` in this file `app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js`.

We regard Linea testnet as "built-in" as "Sepolia" and "Goerli". The difference is that we use the network type `RPC` for the linea testnet. That's why we need to use `findNetworkConfigurationBy` function to get the linea testnet information and then get the `networkconfigurationId`.

My PR fixed this issue :)

File: app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ const switchEthereumChain = {
 export default switchEthereumChain;
 
 function findExistingNetwork(chainId, findNetworkConfigurationBy) {
-  if (chainId in CHAIN_ID_TO_TYPE_MAP) {
+  if (chainId in CHAIN_ID_TO_TYPE_MAP && chainId !== CHAIN_IDS.LINEA_TESTNET) {
```
Comment (Gudahtt) [inline app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js:30]: This condition is meant to select for the built-in Infura Mainnet network, and any other built-in Ethereum testnets. It would be better to update this condition to better reflect that requirement, rather than adding an exception for Linea.

We have shared constants for these networks already: `INFURA_PROVIDER_TYPES` and `BUILT_IN_INFURA_NETWORKS`. But none that have a chain ID as the key.

Maybe we could do something like this instead:

```suggestion
  if (Object.values(BUILT_IN_INFURA_NETWORKS).map(({ chainId }) => chainId).includes(chainId)) {
```

Comment (Gudahtt) [reply app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js:30]: The same condition seems appropriate for the below change as well

**Comment by Gudahtt** [comment]
>I'm trying to understand why this bug exists. Is Linea testnet a network we regard as "built-in", or is something that users need to add themselves?

>We regard Linea testnet as "built-in" as "Sepolia" and "Goerli". The difference is that we use the network type `RPC` for the linea testnet.

This conversation is highlighting why "built-in network" is not a great term :sweat_smile: 

We have this unfortunate split between certain built-in Infura networks and all other networks that affects how we interact with the network controller. Built-in Infura networks require calling `setProviderType` whereas other networks require using `setActiveNetwork`).

Ideally we'd remove this split at some point, but that's the purpose of these conditions that are being changed in this PR.

**Review by danjm — APPROVED** [review]
LGTM

**Review by Gudahtt — APPROVED** [review]
LGTM!
