### PR TITLE
fix: handles rewards deeplink with referral code cp-13.11.0

### LINKED ISSUE #38171: [Bug]:  Rewards deeplink does not trigger onboarding or populate referral code
### Describe the bug

Deeplinks do not trigger onboarding or populate referral code

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

Use in browser:

https://link.metamask.io/rewards
https://link.metamask.io/rewards?referral=DAB123

Do not open onboarding modal or show rewards QR code modal right now.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.11

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by VGR-GIT**
## **Description**
https://consensyssoftware.atlassian.net/browse/RWDS-548
Handles rewards deeplink such as:
- https://link.metamask.io/rewards
- https://link.metamask.io/rewards?referral=DAB123

If user has a rewards profile --> redirect to homepage 
If use has not opted in yet --> open the rewards onboarding modal

To test locally:
chrome-extension://hebhblbkkdabgoldnojllkipeoacjioc/home.html#link?u=/rewards
chrome-extension://hebhblbkkdabgoldnojllkipeoacjioc/home.html#link?u=/rewards?referral=DAB123

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38072?quickstart=1)

## **Changelog**

CHANGELOG entry: null

### **After**

https://github.com/user-attachments/assets/b27a37ac-e9c7-4e2c-8481-6f57b63edfed

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Introduce a first-class `/rewards` deep link that opens the Rewards onboarding (with referral support), add referral state/UI, switch non‑prod Rewards API to UAT, update tests, and extend locales.
> 
> - **Deep link & UI**
>   - Add `REWARDS_ROUTE` (`/rewards`) and new `ui/pages/rewards/index.tsx` to handle MetaMask deep links; parse `?referral=` and open `rewards` onboarding modal, then redirect to `DEFAULT_ROUTE`.
>   - Update `shared/lib/deep-links/routes/rewards.ts` to return internal `{ path: '/rewards', query }` instead of external redirect.
>   - Introduce `test/e2e/page-objects/pages/rewards/rewards-page.ts` and extend `test/e2e/tests/deep-link/deep-link.spec.ts` to cover `/rewards` (signed/unsigned) and remove old dedicated tests.
>   - Enhance `ui/components/app/reports/onboarding`:
>     - `OnboardingModal`: accept `onClose`, reset referral on close, dynamic height and QR-code state handling.
>     - `OnboardingIntroStep`: show contextual `loadingText` for region/eligibility checks.
>     - `OnboardingStep4`: seed referral from store (trim + uppercase), show "Verifying referral code..." during validation.
> - **State management**
>   - Add `onboardingReferralCode` to `ui/ducks/rewards` state, new action `setOnboardingReferralCode`, selector `selectOnboardingReferralCode`, and update `state-logs.json`; include tests.
> - **Rewards data service + tests**
>   - `rewards-data-service.ts`: use `REWARDS_API_URL.UAT` for non‑production; improve locale handling; adjust `fetchGeoLocation` URL; tweak error messages; keep PRD for production/RC.
>   - Update `rewards-data-service.test.ts` and expectations for UAT endpoints; add assertion for referral validation, opt‑in/status, season status; adjust test names.
> - **Localization**
>   - Add messages: `rewardsOnboardingIntroStepConfirm{LoadingEligibility,LoadingRegion}`, `rewardsOptInVerifyingReferralCode`, and `deepLink_theRewardsPage`; update en and en_GB locales.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit c8dade41663ab69db9de50aae4d8b03015d4e154. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by Unik0rnMaggie — DISMISSED** [review]

File: shared/lib/deep-links/routes/rewards.ts [hunk 1]
```diff
@@ -1,14 +1,13 @@
...
 export default new Route({
   pathname: '/rewards',
   getTitle: (_: URLSearchParams) => 'deepLink_theRewardsPage',
   handler: function handler(params: URLSearchParams) {
-    const rewardsUrl = new URL('/rewards', BaseUrl.MetaMask);
-    params.forEach((value, key) => rewardsUrl.searchParams.append(key, value));
+    const query = new URLSearchParams(params);
     return {
-      redirectTo: rewardsUrl,
+      path: '/rewards',
```
Comment (DDDDDanica) [inline shared/lib/deep-links/routes/rewards.ts:9]: Could you use path from `ui/helpers/constants/routes.ts`

File: test/e2e/tests/deep-link/deep-link.spec.ts [hunk 2]
```diff
@@ -291,59 +295,6 @@ and we'll take you to the right place.`
     );
   });
 
-  it('handles /rewards route redirect', async function () {
```
Comment (DDDDDanica) [inline test/e2e/tests/deep-link/deep-link.spec.ts:294]: Could you add a reason for removing this e2e test just to clarify? thx

File: ui/components/app/rewards/onboarding/OnboardingModal.tsx [hunk 3]
```diff
@@ -91,7 +103,14 @@ export default function OnboardingModal() {
           paddingTop: 0,
           paddingBottom: 0,
           style: {
-            height: '740px',
+            height:
+              rewardActiveAccountSubscriptionId ||
+              (candidateSubscriptionId &&
+                candidateSubscriptionId !== 'error' &&
+                candidateSubscriptionId !== 'pending' &&
+                candidateSubscriptionId !== 'retry')
```
Comment (DDDDDanica) [inline ui/components/app/rewards/onboarding/OnboardingModal.tsx]: Nit: Can be extracted to a const and memorize it with useMemo

File: shared/lib/deep-links/routes/rewards.ts (hunk 1 above)
Comment (VGR-GIT) [reply shared/lib/deep-links/routes/rewards.ts:9]: @DDDDDanica this would violate a constraint:

`Unexpected path "../../../../ui/helpers/constants/routes" imported in restricted zone. Should not import from UI in shared`

File: ui/pages/routes/routes.component.tsx [hunk 4]
```diff
@@ -1132,6 +1134,12 @@ export default function Routes() {
             component={ShieldPlan}
             layout={LegacyLayout}
           />
+          <RouteWithLayout
+            authenticated
+            path={REWARDS_ROUTE}
+            component={RewardsPage}
```
Comment (DDDDDanica) [inline ui/pages/routes/routes.component.tsx]: You would need to pass in props as well to access location
```
            {createV5CompatRoute(UnlockPage, {
              wrapper: RewardsPage,
              includeNavigate: true,
              includeLocation: true,
            })}
```

Comment (VGR-GIT) [reply ui/pages/routes/routes.component.tsx]: Great! Switched over to this type of route definition

File: test/e2e/tests/deep-link/deep-link.spec.ts (hunk 2 above)
Comment (Montoya) [reply test/e2e/tests/deep-link/deep-link.spec.ts:294]: This was a custom test for the custom deeplink that went to a webpage URL. The test is now covered by a scenario in the set of scenarios for page deeplinks.

**Review by Unik0rnMaggie — DISMISSED** [review]

**Review by Unik0rnMaggie — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Review by Unik0rnMaggie — APPROVED** [review]
