### PR TITLE
UX: updated placeholder for erc-1155 image

### LINKED ISSUE #20849: [Bug]: ERC1155 token image is not displayed
### Describe the bug

When import an ERC1155 NFT, the image is not displayed.

### Steps to reproduce

1. Enable ipfs gateway toggle and display NFT media toggle in privacy setting page.
2. Go to testdapp, deploy an ERC1155 contract and batch mint tokens.
3. Go to MM and import the minted token.

Expected: image should be displayed.

https://github.com/MetaMask/metamask-extension/assets/105063779/b98fe777-010d-4fb0-be8a-018062b6a79f

### Error messages or log output

_No response_

### Version

v11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
Update placeholder image for ERC-1155 Nft when src of image is null. 

Note: When Src is null, we are going to display the Default image without show button

* Fixes #20849 

### After

1. When importing ERC-1155 image and src is null
Screenshot 2023-09-18 at 2 39 48 PM

## Manual Testing Steps

1. Enable ipfs gateway toggle and display NFT media toggle in privacy setting page.
2. Go to testdapp, deploy an ERC1155 contract and batch mint tokens.
3. Go to MM and import the minted token.
4. If src is null, the default image should be shown without the show button.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/multichain/nft-item/nft-item.js [hunk 1]
```diff
@@ -85,15 +96,26 @@ export const NftItem = ({
...
+                  />
+                ) : (
+                  <NftDefaultImage
+                    className="nft-item__default-image"
+                    data-testid="nft-default-image"
+                    name={name}
+                    tokenId={tokenId}
+                  />
+                )}
+              </>
```
Comment (DDDDDanica) [inline ui/components/multichain/nft-item/nft-item.js:118]: This block of code seems to be duplicated with the one above. Can we extract to a separate `renderERC155Image` function to reduce duplicity?

**Review by vthomas13 — DISMISSED** [review]

**Comment by danjm** [comment]
Fixes https://github.com/MetaMask/MetaMask-planning/issues/1330

**Review by DDDDDanica — DISMISSED** [review]

**Review by DDDDDanica — DISMISSED** [review]

**Review by vthomas13 — DISMISSED** [review]

**Review by darkwing — DISMISSED** [review]

**Review by vthomas13 — DISMISSED** [review]

**Review by zone-live — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]
