### PR TITLE
fix: handle network change to fix custom RPC selection

### LINKED ISSUE #32164: [Bug]: Can't change RPC using selector, send_rawTransaction request is being submitted to last used RPC
### Describe the bug

The RPC selector does not work in the case of `send_rawTransaction`. Adding/selecting custom RPCs seem to work up to the point of submitting a transaction, at which point the previously selected RPC (on bootup) is used, very similar to https://github.com/MetaMask/metamask-extension/issues/30061

### Expected behavior

1. Start metamask up
2. Send transaction -> `send_rawTransaction` using selected RPC (infura)
3. Select different rpc (gashawk)
4. Send transaction -> `send_rawTransaction` using previous RPC (gashawk)

### Screenshots/Recordings

https://github.com/user-attachments/assets/444a8e38-6c02-4795-b1ad-c4828b8d2133

### Steps to reproduce

1. Start metamask up
2. Send transaction -> `send_rawTransaction` using selected RPC (infura)
3. Select different rpc (gashawk)
4. Send transaction -> `send_rawTransaction` using previous RPC (infura)

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.16.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

pair to support ticket #206075: Issue with RPC selection and `eth_sendRawTransaction` command

versions:
- 12.15.2
- 12.16.0
- 12.16.1

### Severity

_No response_

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**

This PR addresses a race condition in `select-rpc-url-modal.tsx` that occurs when selecting a custom RPC from the network list.

**Issue:**
When a user selects a network, the component:
1. Calls `updateNetwork`, which updates `defaultRpcEndpointIndex`.
2. Then calls `onNetworkChange`, passed from `network-list-menu.tsx`.

Inside `handleEvmNetworkChange`, `getRpcDataByChainId` retrieves the `defaultRpcEndpoint` based on `defaultRpcEndpointIndex`. However, due to the async nature of state updates, it uses the previous index, causing a mismatch between the selected network and the returned RPC URL.

**Resulting behavior:**
- Selecting Infura returns the custom RPC URL.
- Selecting the custom RPC returns the previous one (e.g., Infura).

**Fix:**
This PR ensures the RPC data is resolved correctly after the `defaultRpcEndpointIndex` has been updated.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32365?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32164

## **Manual testing steps**

1. Go to metamask change the RPC selecting infura
2. Send transaction -> `send_rawTransaction` using selected RPC (infura)
3. Verify on Chrome tools > network the RPC used (should be infura)
4. Select different rpc (gashawk/tenderly)
5. Send transaction -> `send_rawTransaction` using custom RPC
6. Verify on Chrome tools > network the RPC used (should be the custom RPC selected)

## **Screenshots/Recordings**

**Using Infura**

[send-tx-infura.webm](https://github.com/user-attachments/assets/1a000dbd-1759-4949-a061-0d41db8e210b)

**Using custom RPC**

[send-tx-tenderly.webm](https://github.com/user-attachments/assets/09cefe37-f8e3-4ad8-8e64-6a56b23d3e4d)

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/network-list-menu/network-list-menu.tsx [hunk 1]
```diff
@@ -318,11 +318,16 @@ export const NetworkListMenu = ({ onClose }: { onClose: () => void }) => {
...
-  const handleEvmNetworkChange = (chainId: CaipChainId) => {
+  const handleEvmNetworkChange = (
+    chainId: CaipChainId,
+    networkClientId?: string,
+  ) => {
     const hexChainId = convertCaipToHexChainId(chainId);
     const { defaultRpcEndpoint } = getRpcDataByChainId(chainId, evmNetworks);
-    const { networkClientId } = defaultRpcEndpoint;
-    dispatch(setActiveNetwork(networkClientId));
+    const defaultNetworkClientId =
```
Comment (OGPoyraz) [inline ui/components/multichain/network-list-menu/network-list-menu.tsx:327]: Minor: maybe renaming this into `finalNetworkClientId` would be better since `defaultNetworkId` sounds like `defaultRpcEndpoint.networkClientId`

**Review by OGPoyraz — DISMISSED** [review]

File: ui/components/multichain/network-list-menu/network-list-menu.tsx (hunk 1 above)
Comment (vinistevam) [reply ui/components/multichain/network-list-menu/network-list-menu.tsx]: true, pushed the suggested change.

**Review by OGPoyraz — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]
