### PR TITLE
fix: for realease blocker bugs

### LINKED ISSUE #22840: [Bug]: PPOM - Metrics: Transactions and Signatures are not capturing ppom requests to Infura
### Describe the bug

**Problem:** with the new async ppom changes, we are now missing the ppom request count to Infura for Transactions and Signatures.

### Expected behavior

I think we should not expect them on `Transaction/Signature Added` but we should see it in `Transaction/Signature Confirmed/Rejected`

### Screenshots/Recordings

image

Expected:

image

### Steps to reproduce

1. Enable Blockaid
2. Trigger any Signature/Transaction
3. See Metrics
4. Accept/Reject the Signature/Transaction
5. See Metrics -- no requests to Infura counting info

### Error messages or log output

_No response_

### Version

11.9.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by segun**
## **Description**
With the new async ppom changes, we don't see any more the metrics information for any Signature (eth_sign, typed signature) and we are now also missing the ppom request count to Infura for Transactions and Signatures. We should see it in Transaction/Signature Confirmed/Rejected.

## **Related issues**

Fixes: #22840 #22841 

## **Manual testing steps**

1. Enable Blockaid
2. Trigger any Signature/Transaction
3. See Metrics
4. Accept/Reject the Signature/Transaction
5. See Metrics in network info

### **Before**

302900276-b316bcdc-a574-4a60-92db-dc0e4692fc9e-2

302901962-355ce267-f234-4373-abe3-17310724618d-2

### **After**

Screenshot 2024-02-08 at 14 08 51
Screenshot 2024-02-08 at 14 08 28

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/lib/ppom/ppom-middleware.ts [hunk 1]
```diff
@@ -69,23 +69,27 @@ export function createPPOMMiddleware(
         // eslint-disable-next-line require-atomic-updates
         const securityAlertId = uuid();
 
-        ppomController.usePPOM(async (ppom: PPOM) => {
```
Comment (danjm) [inline app/scripts/lib/ppom/ppom-middleware.ts:72]: Why was this change needed?

Comment (segun) [reply app/scripts/lib/ppom/ppom-middleware.ts:72]: Even though `ppom.validateJsonRpc(req)` returns  `securityAlertResponse` we need to return it to PPOM controller, because inside PPOM controller, we need to add the infura rpc calls and the number of times they were called for the request (`providerRequestsCount`) to `securityAlertResponse` and then return the updated object. Otherwise `securityAlertResponse` won't have the `providerRequestsCount` objects.

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js [hunk 2]
```diff
@@ -310,13 +314,30 @@ export default function createRPCMethodTrackingMiddleware({
         event = eventType.APPROVED;
       }
 
+      let blockaidMetricProps = {};
```
Comment (segun) [inline app/scripts/lib/createRPCMethodTrackingMiddleware.js:317]: This code needs to be code-fenced, which means we need to add code fencing on line 137 as well and also code fence the jsdoc on line 126. The issue is I'm not sure how to code-fence inside jsdoc (or if that's even possible) cc @jpuri @danjm

File: app/scripts/controllers/app-state.js [hunk 3]
```diff
@@ -470,6 +470,14 @@ export default class AppStateController extends EventEmitter {
     });
   }
 
+  ///: BEGIN:ONLY_INCLUDE_IF(blockaid)
```
Comment (danjm) [inline app/scripts/controllers/app-state.js:473]: We don't need this function, instead in the ppom middleware we can just do `appStateController.store.getState().signatureSecurityAlertResponses[securityAlertId]`

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js (hunk 2 above)
Comment (danjm) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js:317]: I think it is okay if we don't codefence the jsdoc code. Unless that breaks the build?

**Review by danjm — DISMISSED** [review]
This looks good to me if it passes QA

File: app/scripts/lib/ppom/ppom-middleware.ts (hunk 1 above)
Comment (danjm) [reply app/scripts/lib/ppom/ppom-middleware.ts:72]: :+1:

**Review by digiwand — DISMISSED** [review]

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js (hunk 2 above)
Comment (segun) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js:317]: It breaks the code if we don't code fence it.

**Review by jpuri — DISMISSED** [review]

**Review by danjm — DISMISSED** [review]

**Comment by seaona** [comment]
- :green_circle: I see that the ppom request count is now added in the transactions/signatures
Screenshot from 2024-02-09 10-46-43

- :yellow_circle:  I still see some issues with Signatures

1. When a Signature is added, the event displays

```
security_alert_reason: 'NotApplicable',
security_alert_response: 'NotApplicable',
```
instead of validation_in progress (like we do with transactions).

2. In the case of a Malicious Signature, when it is Rejected/Accepted, we do see the malicious result in the `ui_customization` (expected), but we continue to see
```
security_alert_reason: 'NotApplicable',
security_alert_response: 'NotApplicable',
```

https://github.com/MetaMask/metamask-extension/assets/54408225/55a3eabf-3513-457e-9dce-9666122aee9a

3. In the case of a Benign Signature, we don't see the `ui_customization` (expected) but we continue to see:
```
security_alert_reason: 'NotApplicable',
security_alert_response: 'NotApplicable',
```

https://github.com/MetaMask/metamask-extension/assets/54408225/96770e21-3d37-4abf-922c-c7169d5390b0

**Comment by seaona** [comment]
Pending issues about Signatures:
1. :green_circle: this is fixed
2. :yellow_circle:  In the case of a Malicious Signature, when it is Rejected/Accepted, now we see `validation in progress` and `loading` , however, the validation has ended with malicious result

Screenshot from 2024-02-13 11-23-24

3. :yellow_circle:  In the case of a Benign Signature, when it is Rejected/Accepted, now we see `validation in progress` and `loading` , however, the validation has ended with benign result

Screenshot from 2024-02-13 11-25-01

**Comment by seaona** [comment]
hi there, after the changes I see:

- :green_circle: the Benign signature looks good

- :yellow_circle: for the Malicious signatures, it seems that we are not displaying the reason, but duplicating the result in both fields
On the `security_alert_reason` we should be displaying the reason, i.e. `transfer_farming`

image

**Comment by seaona** [comment]
- :green_circle:  for the Malicious signatures, (..) - I see this fixed too now (there's been a new commit that fixed it while I was testing it in the previous comment)

**Review by jpuri — APPROVED** [review]

**Review by danjm — APPROVED** [review]
