### PR TITLE
[RFC] fix(popup): popup window relative to last focused window

### LINKED ISSUE #7314: Transaction confirmations/popups shown on primary instead of current monitor / display
**Describe the bug**
In a multi-monitor setup, when a MetaMask popup is triggered (e.g. for transaction confirmation or to connect accounts with a dapp), that confirmation popup appears in the upper left corner of the primary monitor, regardless of which monitor the browser is on.

**To Reproduce**
1. Set up multiple monitors, with the primary on the left.
2. Open a MetaMask enabled browser and drag it to the far right screen.
3. Browse to a dapp and interact, e.g. trigger the sending of a transaction.
4. Wait for a few minutes, because of #6813.  
5. Keep watching the screen where the browser is, expecting a MetaMask popup for confirmation of the transaction.

**Expected behavior**
6. The popup appears on the same screen the user is watching, ideally aligned with the upper left corner of the dapp browser window, or alternatively aligned with the upper-left corner of the same monitor.

**Actual behavior**
6. The popup appears in the upper left corner of the far left monitor, where the user may not be looking.
7. If the user is watching, they may see a small number in the MetaMask icon.
8. Click the MetaMask icon to get the drop-down to confirm the transaction.

**Browser details (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - MetaMask Version: 7.3.1

### PR DESCRIPTION
**Pull request by brad-decker**
Fixes #7314

### Cause of bug
- The popup window is triggered from the background chrome process for the extension which has no height, width, left or top position (actually all are 0)
- The original logic attempted to use these to compute a good position for the popup.
- The result is that on dual displays, the popup always opened in the top left most pixel of the leftmost display 

### Suggested resolution
- use the browser extension API to grab the latest focused window
- check the left and top values for that window
- ???

I have defaulted to opening the popup perfectly aligned with the top left most pixel of the last focused window. This could end up being wonky. I would love to get an idea of what the best-case scenario would be from the product team @jacobcantele and of course would love input from the engineers on the approach here.

### CODE REVIEW

**Comment by brad-decker** [comment]
Screen Shot 2020-04-17 at 1 32 28 PM

File: app/scripts/lib/notification-manager.js [hunk 1]
```diff
@@ -3,6 +3,18 @@ import ExtensionPlatform from '../platforms/extension'
 const NOTIFICATION_HEIGHT = 620
 const NOTIFICATION_WIDTH = 360
 
+function getLeftTop() {
+  var a = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
```
Comment (brad-decker) [inline app/scripts/lib/notification-manager.js:7]: This function was grabbed from stackoverflow and was a dud, I'll remove it and its not a part of the solution.

**Comment by rachelcope** [comment]
I've always felt that the confirmation window appearing on the upper left corner is disorienting since all other MetaMask interactions appear in the upper right corner window (near the fox in the browser bar). 

This decision (I believe) was made so it would be harder to fake a MetaMask popup. Does the left side position not have the same risks? Is there any other reason for the upper left popup location?

I'd propose instead that the MetaMask window always appear on the upper right corner. These UX principles apply here: 

1) **consistency** and **principle of least surprise** - (https://en.wikipedia.org/wiki/Principle_of_least_astonishment)
Users should be able to anticipate that the MetaMask window will consistently show up in the same location. This would minimize surprise to where it might appear on their screen and reduce the learning time to get familiar with the product.

2) **proximity principle** (https://www.nngroup.com/articles/closeness-of-actions-and-objects-gui/) - things that appear close together on the screen are seen as related. Having the MetaMask window appear near the fox extension icon will help users mentally connect the two.

Any thoughts on this? @brad-decker @jacobcantele @danfinlay @cjeria @omnat

**Comment by brad-decker** [comment]
upper left is just easiest with the information the API returns, we can use other info to get the width of the browser and move the popup to the top-right if that is the desired effect.

**Comment by brad-decker** [comment]
Screen Shot 2020-04-17 at 4 11 35 PM

Moved to top right corner with latest push.

File: .nvmrc [hunk 2]
```diff
@@ -1 +1 @@
-v10.18.1
+lts/dubnium
```
Comment (brad-decker) [inline .nvmrc:1]: @whymarrh tagging you on this as you were the latest to update. Are we good with this to support all versions of node 10 with nvm (whichever version of 10 the dev has installed with nvm)? I tried finding a way to do `^v10.18.1` but came up empty.

File: app/scripts/lib/notification-manager.js [hunk 3]
```diff
@@ -29,17 +29,20 @@ class NotificationManager {
       // bring focus to existing chrome popup
       await this.platform.focusWindow(popup.id)
     } else {
-      const { screenX, screenY, outerWidth, outerHeight } = window
-      const notificationTop = Math.round(screenY + (outerHeight / 2) - (NOTIFICATION_HEIGHT / 2))
-      const notificationLeft = Math.round(screenX + (outerWidth / 2) - (NOTIFICATION_WIDTH / 2))
+      const lastFocused = await this.platform.getLastFocusedWindow()
+      const { outerWidth } = window
```
Comment (brad-decker) [inline app/scripts/lib/notification-manager.js:33]: outerWidth is no longer used and can be removed.

File: .nvmrc (hunk 2 above)
Comment (Gudahtt) [reply .nvmrc:1]: We do need to ensure that v10.12.0 at minimum is used, because we use the `recursive` flag for `mkdir` in a few places (which was added in `v10.12.0`). That's why this repo is more specific than just `v10`.

But it looks like specifying `lts/dubnium` ensures the latest version is always used? That sounds convenient! I didn't know that.

Could you submit this change as a separate PR? I like the idea of always asking for the latest, so we don't need to keep bumping this. At least until we get v12 working anyway.

File: app/scripts/lib/notification-manager.js [hunk 4]
```diff
@@ -29,17 +29,20 @@ class NotificationManager {
       // bring focus to existing chrome popup
       await this.platform.focusWindow(popup.id)
     } else {
-      const { screenX, screenY, outerWidth, outerHeight } = window
-      const notificationTop = Math.round(screenY + (outerHeight / 2) - (NOTIFICATION_HEIGHT / 2))
-      const notificationLeft = Math.round(screenX + (outerWidth / 2) - (NOTIFICATION_WIDTH / 2))
+      const lastFocused = await this.platform.getLastFocusedWindow()
```
Comment (Gudahtt) [inline app/scripts/lib/notification-manager.js:32]: Could you add a fallback for when this fails? The `getLastFocused` API isn't available on Firefox for Android, which... does technically work with the extension right now (although not very well, and not for very much longer). But still... might as well not break it?

A `try / catch` block with some fallback position should do the trick.

**Review by Gudahtt — COMMENTED** [review]
Thanks, this looks like a great solution!

File: app/scripts/lib/notification-manager.js (hunk 4 above)
Comment (brad-decker) [reply app/scripts/lib/notification-manager.js:32]: Any advice on how to test this locally for someone who bleeds apple? (Aka I own 0 android devices ;p) @Gudahtt Would like to make sure that the fallback actually works. I suppose I could like modify the global object in the console before triggering the popup.

Comment (Gudahtt) [reply app/scripts/lib/notification-manager.js:32]: Yep, that sounds like it'd work! You could also try throwing an error in `getLastFocusedWIndow` directly, as I would expect that function to throw an exception on Firefox for Android (since `window.getLastFocused` would be undefined)

File: .nvmrc (hunk 2 above)
Comment (brad-decker) [reply .nvmrc:1]: I think if the dev only had v10.11.x it would use that rather than forcing them to install the latest, so I think we might wanna hold on changing it at atm. I'll drop this change from the PR and open a separate for discussion.

Comment (Gudahtt) [reply .nvmrc:1]: Hmm - I tried it locally and `v10` would use the latest v10.x.x I had installed locally, but `lts/dubnium` forced me to install the latest. But I don't know how `nvm` works, or how it knows what the latest is :thinking: (maybe it checks each time, or periodically? :man_shrugging: ). I don't see any clear documentation about this behaviour.

File: app/scripts/lib/notification-manager.js (hunk 4 above)
Comment (brad-decker) [reply app/scripts/lib/notification-manager.js]: Added the try/catch, and did `delete chrome.windows.getLastFocused` to confirm the behavior. This will open the popup in the top left corner on devices that don't support it -- unless the originating window in android chrome is not a background process like it is on desktop chrome. In which case it should position it in the top right corner.

**Review by Gudahtt — APPROVED** [review]
LGTM!

File: app/scripts/lib/notification-manager.js [hunk 5]
```diff
@@ -29,17 +29,30 @@ class NotificationManager {
...
-      const notificationTop = Math.round(screenY + (outerHeight / 2) - (NOTIFICATION_HEIGHT / 2))
-      const notificationLeft = Math.round(screenX + (outerWidth / 2) - (NOTIFICATION_WIDTH / 2))
+      let left = 0
+      let top = 0
+      try {
+        const lastFocused = await this.platform.getLastFocusedWindow()
+        // Position window in top right corner of lastFocused window.
+        top = lastFocused.top
+        left = lastFocused.left + (lastFocused.width - NOTIFICATION_WIDTH)
+      } catch (_) {
```
Comment (whymarrh) [inline app/scripts/lib/notification-manager.js:39]: What error would we be catching here? Is it possible that there isn't a last focused window?

Comment (whymarrh) [reply app/scripts/lib/notification-manager.js:39]: If we know that the window in the background doesn't have a size, we could forgo the calculations below.

**Review by whymarrh — COMMENTED** [review]
I agree that this is a good solution. I had one question about it.

File: app/scripts/lib/notification-manager.js (hunk 5 above)
Comment (brad-decker) [reply app/scripts/lib/notification-manager.js:39]: > What error would we be catching here? Is it possible that there isn't a last focused window?

Per @Gudahtt , android chrome doesn’t yet support getLastFocused on the windows api. This is an effort to have a fallback that behaved like the previous iteration.

Comment (brad-decker) [reply app/scripts/lib/notification-manager.js:39]: > If we know that the window in the background doesn't have a size, we could forgo the calculations below.

True, though I’d need to test my assumption on chrome android to be sure that it behaves that way as well.

Comment (whymarrh) [reply app/scripts/lib/notification-manager.js:39]: Gotcha! (My bad, I didn't look at the existing resolved convos. 😅)

**Review by whymarrh — APPROVED** [review]
LGTM!
