### PR TITLE
fix: additional network permission request view shows all networks

### LINKED ISSUE #34529: [Bug]: Additional Network Permission request view shows all networks
### Describe the bug

When a dapp requires additional network permissions a Permission request is prompted. The request shows all enabled networks.

https://github.com/user-attachments/assets/27565824-c8f6-4689-9792-45c18def263f

### Expected behavior

Permission request only shows additional network.

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Wallet: Add Base to Network list
2. Dapp: Connect to Pancake Swap
3. Wallet: Go to Connection Menu > Enabled Networks > Edit > Deselect Base
4. Dapp: In Pancake Swap select asset on Base as from token to trigger Network Switch
5. Result 
     a. 12.14.2 Wallet requests permission for Base
     b. 12.15 Wallet requests permission, listing all enabled networks

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.15.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

12.14.2 works as expected. Issue is introduced in 12.15.

### Severity

Impact: Shows unnecessary complexity, causes bad UX

### PR DESCRIPTION
**Pull request by ffmcgee725**
## **Description**

When a dapp requires additional network permissions a Permission request is prompted. The request shows all enabled networks. The proposed fix makes sure that we only show additional network instead.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34651?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed a bug that was causing all enabled networks to show on an additional network permission request prompted by a dapp

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34529

## **Manual testing steps**

1. Make sure Base is added to Network list
2. Connect to [Pancake Swap](https://pancakeswap.finance/swap) (With Base as one of the selected networks)
3. Wallet: Go to Connection Menu > Enabled Networks > Edit > Deselect Base
4. Dapp: In Pancake Swap select asset on Base as from token to trigger Network Switch
5. Wallet requests should show permission for Base only (not all enabled networks)

### **Before**

https://github.com/user-attachments/assets/27565824-c8f6-4689-9792-45c18def263f

### **After**

https://github.com/user-attachments/assets/2885fe7a-b43a-4fab-b732-ac2d5ed9ced4

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/permissions-connect/permissions-connect.component.js [hunk 1]
```diff
@@ -45,9 +46,16 @@ function getDefaultSelectedAccounts(currentAddress, permissions) {
...
-    getCaip25CaveatValueFromPermissions(permissions);
+function getRequestedChainIds(permissionRequest) {
+  const permissions = permissionRequest?.permissions;
+  const permissionDiffMap = permissionRequest?.diff?.permissionDiffMap;
+
+  const permissionsDiff = getPermissionsFromDiffMap(permissionDiffMap);
+
+  const requestedCaip25CaveatValue = getCaip25CaveatValueFromPermissions(
+    permissionDiffMap ? permissionsDiff : permissions,
+  );
```
Comment (ffmcgee725) [inline ui/pages/permissions-connect/permissions-connect.component.js]: The problem: the permission object now contains all the chain ids, both the newly requested ones and the already permitted ones. So when we retrieve the chain ids from the permission object, we get everything (ex.: Dapp has Ethereum Mainnet and Linea permitted, and dapp now sends `wallet_switchEthereumChain` with request for Base, permission object contains all 3 of these)

The solution: we have access to a `diffMap` after implementing `caip25SpecificationBuilder` merger function in the [following PR](https://github.com/MetaMask/core/pull/5283), so we can check if a `diffMap` does exist, we get the chain IDs from that, making sure downstream the component only renders the newly requested chains on a `wallet_switchEthereumChain`. Otherwise, if it does not exist, we default to the previously existing logic.

I previously "bandaid" patched it downstream in the [following commit](https://github.com/MetaMask/metamask-extension/pull/34651/commits/a0d931a24ec08e532063b7dcfd8701809362dd79), but I chose this approach to have one single set of `requestedChainIds` and not make logic confusing downstream. Open to suggestion for further improvements.

File: ui/pages/permissions-connect/permissions-connect.component.js [hunk 2]
```diff
@@ -45,9 +46,16 @@ function getDefaultSelectedAccounts(currentAddress, permissions) {
...
+
```
[the remark this answers is not in the document]
Comment (ffmcgee725) [reply ui/pages/permissions-connect/permissions-connect.component.js]: https://github.com/MetaMask/metamask-extension/pull/34651/commits/aa7d0aee9152bec22b3638efa053a1b06eaa9f11

**Comment by adonesky1** [comment]
@ffmcgee725 unfortunately this is now fully overwriting chain permissions instead of adding them:

https://drive.google.com/file/d/15BZboKqnbxzXwZm59aH3Kcnv3m9zj5Fx/view?usp=sharing

**Comment by ffmcgee725** [comment]
@adonesky1 as I had predicted [here](https://consensys.slack.com/archives/C03FSJKA509/p1753726529047799?thread_ts=1753724403.421919&cid=C03FSJKA509), reverting the solution back to what it was originally on this [commit](https://github.com/MetaMask/metamask-extension/pull/34651/commits/a0d931a24ec08e532063b7dcfd8701809362dd79) fixes said issue. Even though it's not as elegant as a solution, it gets the job done without fully overwriting chain permissions.

https://github.com/user-attachments/assets/043fb001-5d9c-4eb1-a067-25c31dfd9c80

File: test/e2e/tests/network/switch-custom-network.spec.ts [hunk 3]
```diff
@@ -48,4 +48,53 @@ describe('Switch ethereum chain', function (this: Suite) {
       },
     );
   });
+
+  it('should only show additional network requested when multiple network permissions already exist', async function () {
```
Comment (adonesky1) [inline test/e2e/tests/network/switch-custom-network.spec.ts:54]: I'm a bit disturbed that our e2e tests didn't catch [this bug](https://github.com/MetaMask/metamask-extension/pull/34651#issuecomment-3128307387) which you have since fixed, could you add a test making sure that permissions granted in the switch chain flow are additive and don't overwrite previous permissions so we can catch it next time?

Comment (adonesky1) [reply test/e2e/tests/network/switch-custom-network.spec.ts:54]: I'm surprised this test doesn't already exist. Maybe there is a test in there that isn't making the right assertions?

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js [hunk 4]
```diff
@@ -114,7 +126,11 @@ export default class PermissionPageContainerContent extends PureComponent {
             permissions={selectedPermissions}
             subjectName={subjectMetadata.origin}
             accounts={accounts}
-            requestedChainIds={requestedChainIds}
+            requestedChainIds={
+              permissionDiffRequestedChainIds.length > 0
+                ? permissionDiffRequestedChainIds
+                : requestedChainIds
+            }
```
Comment (adonesky1) [inline ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js:143]: Can we add an inline comment explaining this for future readers/refactors?

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js [hunk 5]
```diff
@@ -63,6 +67,14 @@ export default class PermissionPageContainerContent extends PureComponent {
...
     const displayOrigin =
       subjectType === SubjectType.Website ? getURLHost(origin) : origin;
+
+    const permissionDiffMap = request.diff?.permissionDiffMap;
+    const permissionDiffRequestedChainIds = getPermittedEthChainIds(
+      permissionDiffMap?.[Caip25EndowmentPermissionName]?.authorizedScopes ?? {
+        requiredScopes: {},
+        optionalScopes: {},
+      },
+    );
```
Comment (adonesky1) [inline ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js]: I think it would be nice to have an inline comment explaining when we expect this diff to be present

File: test/e2e/tests/network/switch-custom-network.spec.ts (hunk 3 above)
Comment (ffmcgee725) [reply test/e2e/tests/network/switch-custom-network.spec.ts:54]: It makes sense that this existing test does not catch the previously existing bug, as it's only confirming the UI rendered is the correct one, and does not ACTUALLY proceed with confirming the request and checking the permissions.

Added this new test case making sure that permissions granted in the switch chain flow are additive and don't overwrite previous permissions [here](https://github.com/MetaMask/metamask-extension/pull/34651/commits/315db454f8bf5a993ac6e39027addf60bbed4698). Good call!

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js (hunk 5 above)
Comment (ffmcgee725) [reply ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js]: https://github.com/MetaMask/metamask-extension/pull/34651/commits/5ed9d484ad56f4ca3352fe4eceba692032fba63a

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js (hunk 4 above)
Comment (ffmcgee725) [reply ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js:143]: https://github.com/MetaMask/metamask-extension/pull/34651/commits/5ed9d484ad56f4ca3352fe4eceba692032fba63a

**Review by adonesky1 — DISMISSED** [review]
LGTM!

File: CHANGELOG.md [hunk 6]
```diff
@@ -5,6 +5,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 ## [Unreleased]
+### Fixed
+- fix: make sure permission request only shows additional networks (#34651)
```
Comment (jiexi) [inline CHANGELOG.md]: i don't think we are supposed to manually update the CHANGELOG like this anymore. I believe another engineer that is cutting the release will review the changelog line in the PR description and update the CHANGELOG themselves

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js [hunk 7]
```diff
@@ -63,6 +67,18 @@ export default class PermissionPageContainerContent extends PureComponent {
...
     const displayOrigin =
       subjectType === SubjectType.Website ? getURLHost(origin) : origin;
+
+    // permissionDiffMap is expected to be present when an incremental permission request is made
+    // This occurs when a "wallet_switchEthereumChain" request comes in and we already have a set of permissions
+    const permissionDiffMap = request.diff?.permissionDiffMap;
+    // Extract the requested chain IDs from the permission diff, specifically from the CAIP-25 endowment permission
+    // This represents the new chains being requested in addition to existing permissions
+    const permissionDiffRequestedChainIds = getPermittedEthChainIds(
+      permissionDiffMap?.[Caip25EndowmentPermissionName]?.authorizedScopes ?? {
```
Comment (jiexi) [inline ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js]: authorizedScopes should come from a the caveat type constant https://github.com/MetaMask/core/blob/main/packages/chain-agnostic-permission/src/caip25Permission.ts#L56

**Review by jiexi — DISMISSED** [review]

**Review by adonesky1 — APPROVED** [review]

**Review by jiexi — APPROVED** [review]
