### PR TITLE
disabled save button on add contact form if input fields are empty

### LINKED ISSUE #16015: [Bug]: Save button on add contact form should be disabled if input fields are empty
### Describe the bug

**Problem**: 
 1. when I want to create new contact and even if I don't enter anything in input fields Save button is enabled
 2. when I enter just username in form (without entering public address) it allows me to save but it just closes modal without saving

https://user-images.githubusercontent.com/94608179/192776372-43842ec8-12cf-4466-b2fe-a87870819c35.mov

### Steps to reproduce

1. Unlock MM
3. Go to Settings -> Contacts -> Add contact
4. Don't populate input fields and click Save
5. Enter just Username and click Save

### Error messages or log output

_No response_

### Version

10.19.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adnansahovic**
## Explanation
Disabled save button on add contact form if input field(address) are empty.

## More Information

* Fixes #16015

### Before

https://user-images.githubusercontent.com/63151811/196678907-7b3e8bb5-fee0-4855-9491-8a64ebacaba0.mov

### After

https://user-images.githubusercontent.com/63151811/196678850-8055d05a-a287-4f37-93e1-97e3ca76ffd8.mov

## Manual Testing Steps

1. Unlock MM
2. Go to Settings -> Contacts -> Add contact
3. Don't populate address field and try click Save

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

File: ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js [hunk 1]
```diff
@@ -142,7 +142,7 @@ export default class AddContact extends PureComponent {
         </div>
         <PageContainerFooter
           cancelText={this.context.t('cancel')}
-          disabled={Boolean(this.state.error)}
+          disabled={Boolean(this.state.error || !this.state.ethAddress)}
```
Comment (darkwing) [inline ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js:145]: I think we may want to move this `ethAddress` check to the `validate` method so all validation/errors are set in the same place.

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js (hunk 1 above)
Comment (adnansahovic) [reply ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js:145]: Hi @darkwing, I've tried that solution, but it didn't work well. The function `validate` checks only when we enter a value. In the task the button should be disabled when the field is empty. You can see the following video (when it is added in `validate` function)

https://user-images.githubusercontent.com/63151811/198064966-a3a6c1b0-f40d-41f4-ab59-85af61a140e8.mov

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Review by darkwing — APPROVED** [review]
This will work @adnansahovic !  Thank you so much!
