### PR TITLE
do not display extension id in connection modal

### LINKED ISSUE #8685: [develop] Improve extension origin representation on "Not Connected" menu
Reproduction steps:

- Install develop branch
- Visit a page provided by an extension (like the MetaMask full-screen wallet view)
- Click the fox
- Click the "Not connected" indicator

Current behavior:
- The current origin (extension identifier) is shown to the user.
- This identifier is basically always useless to the user.

Preferred behavior:
- Show text like "Current extension page" instead of the origin when the origin is on an extension prefix. (Need to define this copy)

### PR DESCRIPTION
**Pull request by brad-decker**
fixes #8685 

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

### CODE REVIEW

File: ui/app/pages/connected-accounts/connected-accounts.component.js [hunk 1]
```diff
@@ -50,7 +51,7 @@ export default class ConnectedAccounts extends PureComponent {
 
     return (
       <Popover
-        title={activeTabOrigin}
+        title={activeTabOrigin === extension.runtime.id ? t('currentExtension') : activeTabOrigin}
```
Comment (rekmarks) [inline ui/app/pages/connected-accounts/connected-accounts.component.js:54]: Hm, this will only do it for the MetaMask extension itself, no? I'm just realizing, that's probably a bad idea. We should _probably_ prevent the extension UI from initiating an external permissions request to itself 😅 

That's a different issue. Meanwhile, is there any platform-agnostic way of detecting an extension ID here?

**Review by rekmarks — CHANGES_REQUESTED** [review]
See inline comment.

_Edit:_ I would **really, really** love it if GitHub was better at highlighting whether a PR is a draft or not 😑

File: ui/app/pages/connected-accounts/connected-accounts.component.js (hunk 1 above)
Comment (brad-decker) [reply ui/app/pages/connected-accounts/connected-accounts.component.js:54]: hmm good point lol.

Comment (brad-decker) [reply ui/app/pages/connected-accounts/connected-accounts.component.js:54]: window.location.protocol seems promising... 'chrome-extension' 'moz-extension' etc

**Review by rekmarks — APPROVED** [review]
LGTM!
