### PR TITLE
fix: Remove multiple overlapping spinners

### LINKED ISSUE #27972: [Bug]: Multiple overlapping spinners while loading redesigned confirmations
### Describe the bug

An user can see multiple while the confirmation is loading. Could we reduce it? E.g. combine the two that show up on the top of the page and remove the big and different one that shows in the middle of the confirmation?

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot 2024-10-18 at 18 11 08

### Steps to reproduce

1. Go to test dapp
2. Click on malicious erc20 transfer to see the 2 spinners on top and the different one in the middle
3. Click on malicious erc20 approve to see the different spinner in the middle

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

12.8

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

We were previously using a UI blocking, whole page spinner while loading the redesigned confirmations. This overlapped with the individual component spinners we use on some components that decode transaction data. That second pattern is preferable because the spinner is contained and doesn't block the user from taking action.

The global spinner comes from `routes.component`. The first part of this fix is to bypass it in that file for redesigned confirmations.

The second aspect of this fix is to not condense two component spinners into one. Since the transaction flow section always loads before the send heading component, we can omit the spinner for that first component.

Finally, this PR fixes the loading behaviour on the send heading component so that if the decimals amount coming from `useAssetDetails` hasn't been received yet, the heading is not shown, preventing undesireable flickering in the hero value.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28301?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27972

## **Manual testing steps**

1. Go to test dapp
2. Click on malicious erc20 transfer to see the 2 spinners on top and the different one in the middle
3. Click on malicious erc20 approve to see the different spinner in the middle

### **Before**

Screenshot 2024-10-18 at 18 11 08

### **After**

https://github.com/user-attachments/assets/2f5dd8c2-3b9b-405d-b9b5-0eb8bf793fcb

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

**Comment by HowardBraham** [comment]
@pedronfigueiredo are we going to have a direct merge conflict, or maybe even a functional merge conflict?
#28172

**Comment by pedronfigueiredo** [comment]
Thanks for flagging this @HowardBraham, excited for your PR!

However, I checked out your branch and we still see the three issues my PR aims to solve:

1. The global spinner that blocks the UI
2. The multiple loading spinners for each component
3. The flickering amount in the send heading component

https://github.com/user-attachments/assets/bdca7e5d-d974-4555-8e9d-feeb659495b1

So I think we need both PRs.

File: ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts [hunk 1]
```diff
@@ -22,26 +22,42 @@ export const useTokenValues = (transactionMeta: TransactionMeta) => {
...
+          isDecodedTransferValuePending: false,
+        };
+      }
+
+      return {
+        decodedTransferValue: new BigNumber(
+          value.data[0].params[paramIndex].value.toString(),
+        )
+          .dividedBy(new BigNumber(10).pow(Number(decimals)))
+          .toNumber(),
```
Comment (digiwand) [inline ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts:57]: [nit] could use calcTokenAmount here. Then, we could return `toFixed` to ensure precision is preserved. Then there would be no need for `toNonScientificString` below

**Review by digiwand — DISMISSED** [review]
It appears `toNonScientificString` is a newly added method in our repo as of a week ago. I think we can remove the need fo `toNonScientificString` by avoiding the scientific notation conversion that can be applied when JavaScript handles lengthy digits. This could be done by passing values as strings to BigNumber directly and using `toFixed` or `toString` instead of `toNumber` to display numbers

File: ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts (hunk 1 above)
Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts:57]: Thanks for the comment. Let's address that after feedback from the team on a single PR (https://github.com/MetaMask/metamask-extension/pull/28212) instead of blocking both.

**Comment by pedronfigueiredo** [comment]
I addressed removing the `toNonScientificNotation` function as well as the precision issue mentioned https://github.com/MetaMask/metamask-extension/pull/28212 on this PR

File: ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts [hunk 2]
```diff
@@ -38,23 +37,24 @@ export const useApproveTokenSimulation = (
...
   }, [value, decimals]);
 
   const formattedSpendingCap = useMemo(() => {
     // formatting coerces small numbers to 0
-    return isNFT || decodedSpendingCap < 1
-      ? toNonScientificString(decodedSpendingCap)
-      : new Intl.NumberFormat(locale).format(decodedSpendingCap);
+    return isNFT || parseInt(decodedSpendingCap, 10) < 1
+      ? decodedSpendingCap
+      : new Intl.NumberFormat(locale).format(parseInt(decodedSpendingCap, 10));
```
Comment (digiwand) [inline ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts:53]: This might cause some precision issues with parseInt here. Examples of supporting precision passing BN to Intl.NumberFormat can be found here
ui/pages/confirmations/components/simulation-details/formatAmount.ts

**Review by digiwand — DISMISSED** [review]
nice! left one minor comment above

**Review by vinistevam — DISMISSED** [review]

**Review by jpuri — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
