### PR TITLE
fix: Show Active Badge for Connected Solana Account

### LINKED ISSUE #32057: [Bug]:  Account connection status indicator is not reflecting the active Solana account properly
### Describe the bug

Solana accounts are never indicated as being active even when they are selected in MetaMask and connected to the dapp.

### Expected behavior

GIVEN a Solana account is connected to a dapp
AND MetaMask is opened over a Solana dapp
WHEN the Solana account is selected in MetaMask 
THEN the indicator for the account should display as "Active"

(Similar to the behavior for Ethereum accounts)

### Screenshots/Recordings

Image

Even when a Solana account is selected, it shows as just "connected" not "active"

Image

### Steps to reproduce

1. Connect a Solana account to a dapp
2. Ensure that this Solana account is in focus in the account selector while over the dapp it's connected to
3. Check status indicator for the Solana account

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

12.17.0-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR ensures that active badge is shown for correct account. Previously, active badge was not shown for any Solana account even though it is connected and active

With the `getPermittedEVMAccountsForCurrentTab` selector update it was showing only EVM accounts and accounts were filtered based on that. I have changed the selector to use `getAllPermittedAccountsForCurrentTab` to get all the accounts and filter based on that 

## **Related issues**

Fixes: #32057 

## **Manual testing steps**

1. Connect a Solana account to a dapp
2. Ensure that this Solana account is in focus in the account selector while over the dapp it's connected to
3. Check status indicator for the Solana account

### **Before**
Screenshot 2025-04-22 at 1 29 15 PM

### **After**

https://github.com/user-attachments/assets/394db1e2-27ad-4c52-92e4-9ed104c72c3d

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by darkwing — COMMENTED** [review]
@jiexi @adonesky1 Is there a better way than the `.split(':')`?

A few things:
1.  A test would be good
2. There's a lot of work being done in this selector; we should use `createDeepEqualSelector` to memoize its return results.

File: ui/selectors/selectors.js [hunk 1]
```diff
@@ -3579,11 +3579,14 @@ export function getOrderedConnectedAccountsForActiveTab(state) {
     // eslint-disable-next-line camelcase
     permissionHistory[activeTab.origin]?.eth_accounts?.accounts;
   const orderedAccounts = getMetaMaskAccountsOrdered(state);
-  const connectedAccounts = getPermittedEVMAccountsForCurrentTab(state);
+  const connectedAccounts = getAllPermittedAccountsForCurrentTab(state);
+  const connectedAccountsAddresses = connectedAccounts.map((acc) => {
+    const split = acc.split(':');
+    return split[split.length - 1];
+  });
```
Comment (adonesky1) [inline ui/selectors/selectors.js:3586]: we should use `parseCaipAccountId` here instead.

This would looks something like
```suggestion
  const connectedAccounts = getAllPermittedAccountsForCurrentTab(state);
  const connectedAccountsAddresses = connectedAccounts.map((caipAccountId) => {
   const { address } = parseCaipAccountId(caipAccountId)
   return address
  });
```

**Review by darkwing — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]

**Review by jiexi — APPROVED** [review]

File: ui/selectors/selectors.js [hunk 2]
```diff
@@ -2996,6 +3000,47 @@ export function getUnconnectedAccounts(state, activeTab) {
...
+  (state) => state.metamask.permissionHistory,
+  getMetaMaskAccountsOrdered,
+  getAllPermittedAccountsForCurrentTab,
+  (activeTab, permissionHistory, orderedAccounts, connectedAccounts) => {
+    const permissionHistoryByAccount =
+      permissionHistory[activeTab.origin]?.eth_accounts?.accounts || {};
+
+    const connectedAccountsAddresses = connectedAccounts.map(
+      (caipAccountId) => {
+        const { address } = parseCaipAccountId(caipAccountId);
```
Comment (NidhiKJha) [inline ui/selectors/selectors.js:3014]: @adonesky1 do you think I should add an extra check here for BTC accounts or does this handle it?
