### PR TITLE
Fix snaps confirmation page's textarea height to fit into min-height …

### LINKED ISSUE #13415: Fix custom confirmation box scroll overflow / min-height
How it looks

Screen Shot 2022-01-20 at 16 29 18

How it should look

Screen Shot 2022-01-20 at 16 29 11

### PR DESCRIPTION
**Pull request by ritave**
Fixes #13415

Screenshot 2022-02-10 at 18 11 54

### CODE REVIEW

File: ui/pages/confirmation/templates/flask/snap-confirm/snap-confirm.js [hunk 1]
```diff
@@ -45,7 +45,11 @@ function getValues(pendingApproval, t, actions) {
               children: {
                 element: 'TextArea',
                 props: {
-                  height: '400px',
+                  // TODO(ritave): Terrible hard-coded height hack. Fixing this to adjust automatically to current window height would
+                  //               mean allowing template compoments to change global css, and since the intended use of the template
+                  //               renderer was to allow users to build their own UIs, this would be a big no-no. We probably should
+                  //               deprecate the renderer altogether anyways
+                  height: '238px',
```
Comment (rekmarks) [inline ui/pages/confirmation/templates/flask/snap-confirm/snap-confirm.js:52]:
```suggestion
                  // TODO(ritave): Terrible hard-coded height hack. Fixing this to adjust automatically to current window height would
                  //               mean allowing template compoments to change global css, and since the intended use of the template
                  //               renderer was to allow users to build their own UIs, this would be a big no-no.
                  height: '238px',
```

**Review by brad-decker — APPROVED** [review]

File: ui/pages/confirmation/templates/flask/snap-confirm/snap-confirm.js [hunk 2]
```diff
@@ -45,7 +45,10 @@ function getValues(pendingApproval, t, actions) {
               children: {
                 element: 'TextArea',
                 props: {
-                  height: '400px',
+                  // TODO(ritave): Terrible hard-coded height hack. Fixing this to adjust automatically to current window height would
+                  //               mean allowing template compoments to change global css, and since the intended use of the template
+                  //               renderer was to allow users to build their own UIs, this would be a big no-no.
+                  height: '238px',
```
Comment (rekmarks) [inline ui/pages/confirmation/templates/flask/snap-confirm/snap-confirm.js:51]: For transparency: this comment previously included a recommendation to deprecate the template renderer, but that's a discussion that will be carried out elsewhere.
