### PR TITLE
fix: Update minimum browser warning version, and gracefully fail if chrome.offscreen does not exist

### LINKED ISSUE #25116: TypeError: Cannot read properties of undefined (reading 'hasDocument')
Sentry Issue: [METAMASK-XA58](https://metamask.sentry.io/issues/5455569133/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'hasDocument')
  at None (/metamask/scripts/app-init.js:1:1818)
  at Object.<anonymous> (/metamask/scripts/app-init.js:1:2058)
  at s (/metamask/scripts/app-init.js:1:254)
  at e (/metamask/scripts/app-init.js:1:414)
  at None (/metamask/scripts/app-init.js:1:431)
```

### PR DESCRIPTION
**Pull request by danjm**
## **Description**

With the update to manifest v3, users on versions older than chrome 109 would have errors thrown from app-init about chrome.offscreen being undefined. Snaps and hardware wallets would be broken for these users.

We need to update our minimum supported browser version to 109, but before we do that we need to warn users that there current browser version is out of date.

This PR:
1. Handles the of chrome.offscreen being undefined in app-init.js, by simple not attempting to create the offscreen document of chrome.offscreen is undefined
2. Updates the `OUTDATED_BROWSER_VERSIONS` const so that users on chromium versions older than 109 will see a warning about their browser version
3. Adds an additional note to the outdated browser warning to tell users that snaps and hardware wallets won't work on the current version (but only for users on a MV3 version, where there is no offscreen document api)

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25142?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25116

## **Manual testing steps**

1. Install a chromium version earlier than 109 (https://www.chromium.org/getting-involved/download-chromium/#downloading-old-builds-of-chrome-chromium)
2. Build, install and onboard on this branch
3. You should see a warning about the browser being out of date, and that snaps and most hardware wallets won't work with this version

### **After**

Screenshot from 2024-06-07 10-26-34
Screenshot from 2024-06-07 10-25-59

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/helpers/constants/common.ts [hunk 1]
```diff
@@ -15,13 +15,13 @@ export const CONTRACT_ADDRESS_LINK = _contractAddressLink;
 export const PASSWORD_MIN_LENGTH = 8;
 export const OUTDATED_BROWSER_VERSIONS = {
   // Chrome and Edge should match the latest Chrome version released ~2 years ago
```
Comment (Gudahtt) [inline ui/helpers/constants/common.ts:17]: This comment should be updated

File: ui/helpers/constants/common.ts [hunk 2]
```diff
@@ -15,13 +15,13 @@ export const CONTRACT_ADDRESS_LINK = _contractAddressLink;
...
-  chrome: '<90',
-  edge: '<90',
+  chrome: '<109',
+  edge: '<109',
   // Firefox should match the most recent end-of-life extended support release
   firefox: '<91',
   // Opera should be set to the equivalent of the Chrome version set
   // See https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser
-  opera: '<76',
+  opera: '<109',
```
Comment (Gudahtt) [inline ui/helpers/constants/common.ts:24]: The linked article shows that Opera 95 is based on Chromium 109

File: shared/modules/mv3.utils.js [hunk 3]
```diff
@@ -2,3 +2,8 @@ import browser from 'webextension-polyfill';
 
 export const isManifestV3 =
   browser.runtime.getManifest().manifest_version === 3;
+
+export const isOffscreenAvailable = Boolean(browser.offscreen);
```
Comment (Gudahtt) [inline shared/modules/mv3.utils.js:6]: Nit: Missing JSDoc comments for these

File: app/_locales/en/messages.json [hunk 4]
```diff
@@ -2734,6 +2734,9 @@
   "mismatchedRpcUrl": {
     "message": "According to our records the submitted RPC URL value does not match a known provider for this chain ID."
   },
+  "browserDoesntSupportHWandSnaps": {
```
Comment (Gudahtt) [inline app/_locales/en/messages.json:2737]: Hmm, this is a strange choice in name (not exactly camel case). Maybe this would be better:

```suggestion
  "noHardwareWalletsOrSnapsSupport": {
```

File: ui/helpers/constants/common.ts (hunk 1 above)
Comment (danjm) [reply ui/helpers/constants/common.ts]: Done in 4734e50f79

File: app/_locales/en/messages.json (hunk 4 above)
Comment (danjm) [reply app/_locales/en/messages.json]: changed in 19326715bb

File: ui/helpers/constants/common.ts (hunk 2 above)
Comment (danjm) [reply ui/helpers/constants/common.ts]: fixed in acfab6cdc0

File: ui/pages/home/home.component.js [hunk 5]
```diff
@@ -469,6 +470,16 @@ export default class Home extends PureComponent {
 
     const autoHideDelay = 5 * SECOND;
 
+    const outdatedBrowserNotificationDescriptionText =
+      isMv3ButOffscreenDocIsMissing ? (
+        <div>
+          <p>{t('outdatedBrowserNotification')}</p>
+          <p>{t('browserDoesntSupportHWandSnaps')}</p>
```
[the remark this answers is not in the document]
Comment (danjm) [reply ui/pages/home/home.component.js]: Updated in bfe2ef4c98

I used bold weight and a warning message color

Screenshot from 2024-06-07 11-15-34
Screenshot from 2024-06-07 11-14-52

[the remark this answers is not in the document]
Comment (Gudahtt) [reply ui/pages/home/home.component.js]: Nice, yeah that looks better I think

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by Gudahtt — APPROVED** [review]

**Review by NiranjanaBinoy — APPROVED** [review]
lgtm
