### PR TITLE
fix: handle long nft ids in simulation amount pill

### LINKED ISSUE #24178: [Bug]: Not ellipsing long NFT ID within simulations
### Describe the bug

We show too many numbers for long NFT ids causing the name component to be very small.

### Expected behavior

We should show less numbers for long NFT ID within simulations and allow users to see the full id with the tooltip. 

### Screenshots/Recordings

Screenshot 2024-04-22 at 14 03 10

### Steps to reproduce

Go to ENS on Sepolia test network and purchase an ENS name

### Error messages or log output

_No response_

### Version

11.14.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to fix styling `AmountPill` component used in the `SimulationDetails`. When there is a long NFT id given it overflows and shrinks the `AssetPill`. If there is a long id given, now we want to shorten it. 

Also the fixes the tooltip text which is currently overflowing the container.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25252?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24178

## **Manual testing steps**

1. Any transaction with long NFT id. (Any https://app.ens.domains/ will trigger a long NFT Id)

### **Before**

image

### **After**

Screenshot 2024-06-12 at 11 56 38

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/simulation-details/amount-pill.tsx [hunk 1]
```diff
@@ -78,6 +87,7 @@ export const AmountPill: React.FC<{
         position="bottom"
         title={tooltipParts.join(' ')}
         wrapperStyle={{ minWidth: 0 }}
+        theme="word-break-all"
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/simulation-details/amount-pill.tsx:90]: Unfortunately `Tooltip` ignores `style` property hence this is the only proper solution that I find.

File: ui/helpers/utils/util.js [hunk 2]
```diff
@@ -209,24 +209,29 @@ export function getRandomFileName() {
...
- * @param {string} address - The address to shorten.
- * @returns {string} The shortened address, or the original if it was no longer
- * than 10 characters.
+ * @param {string} stringToShorten - The string to shorten.
+ * @param {number} truncatedCharLimit - The maximum length of the string.
+ * @param {number} truncatedStartChars - The number of characters to preserve at the beginning.
+ * @param {number} truncatedEndChars - The number of characters to preserve at the end.
+ * @returns {string} The shortened string.
  */
-export function shortenAddress(address = '') {
```
Comment (matthewwalsh0) [inline ui/helpers/utils/util.js:222]: Rather than replacing the existing method, would it be simpler to create a more configurable `shortenString` function that the existing `shortenAddress` function can now use but with fixed arguments?

File: ui/helpers/utils/util.js [hunk 3]
```diff
@@ -209,24 +209,29 @@ export function getRandomFileName() {
...
-  if (address.length < TRUNCATED_NAME_CHAR_LIMIT) {
-    return address;
+export function shortenAddress(
+  stringToShorten = '',
+  truncatedCharLimit = TRUNCATED_NAME_CHAR_LIMIT,
```
Comment (matthewwalsh0) [inline ui/helpers/utils/util.js:223]: Given there is many positional arguments with the same type, would it be more usable if we use an object for the optional properties (other than the string itself)?

File: ui/helpers/utils/util.js [hunk 4]
```diff
@@ -209,24 +209,29 @@ export function getRandomFileName() {
...
+  truncatedStartChars = TRUNCATED_ADDRESS_START_CHARS,
+  truncatedEndChars = TRUNCATED_ADDRESS_END_CHARS,
```
Comment (matthewwalsh0) [inline ui/helpers/utils/util.js:225]: Is it worth having unit tests for this new function / arguments?

File: ui/pages/confirmations/components/simulation-details/amount-pill.tsx [hunk 5]
```diff
@@ -53,10 +54,18 @@ export const AmountPill: React.FC<{
...
   if (asset.tokenId) {
-    const tokenIdPart = `#${hexToDecimal(asset.tokenId)}`;
+    const decimalTokenId = hexToDecimal(asset.tokenId);
+    const shortenedDecimalTokenId = shortenAssetId(decimalTokenId, 11, 4, 4);
 
-    amountParts.push(tokenIdPart);
-    tooltipParts.push(tokenIdPart);
+    const shortenedTokenIdPart = `#${shortenedDecimalTokenId}`;
+    const tooltipIdPart = `#${
+      shortenedDecimalTokenId === decimalTokenId
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/simulation-details/amount-pill.tsx:62]: Is this ternary doing anything? If they're the same, then it shouldn't matter which value we use?

File: ui/pages/confirmations/components/simulation-details/amount-pill.tsx [hunk 6]
```diff
@@ -53,10 +54,18 @@ export const AmountPill: React.FC<{
   }
 
   if (asset.tokenId) {
-    const tokenIdPart = `#${hexToDecimal(asset.tokenId)}`;
+    const decimalTokenId = hexToDecimal(asset.tokenId);
+    const shortenedDecimalTokenId = shortenAssetId(decimalTokenId, 11, 4, 4);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/simulation-details/amount-pill.tsx:58]: These numbers would have more readability if we use object arguments as suggested.

Comment (OGPoyraz) [reply ui/pages/confirmations/components/simulation-details/amount-pill.tsx]: Good call done in https://github.com/MetaMask/metamask-extension/pull/25252/commits/7ae1d604fc3c9c559b2c4f32b62ad0e085184ea1

File: ui/helpers/utils/util.js (hunk 3 above)
Comment (OGPoyraz) [reply ui/helpers/utils/util.js]: Right, I was tryign to simplify the first working version but missed this one removed in
https://github.com/MetaMask/metamask-extension/pull/25252/commits/7ae1d604fc3c9c559b2c4f32b62ad0e085184ea1

File: ui/helpers/utils/util.js (hunk 4 above)
Comment (OGPoyraz) [reply ui/helpers/utils/util.js]: Done

File: ui/pages/confirmations/components/simulation-details/amount-pill.tsx (hunk 5 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/simulation-details/amount-pill.tsx]: Right, I was tryign to simplify the first working version but missed this one removed in
https://github.com/MetaMask/metamask-extension/commit/7ae1d604fc3c9c559b2c4f32b62ad0e085184ea1

File: ui/helpers/utils/util.js (hunk 2 above)
Comment (OGPoyraz) [reply ui/helpers/utils/util.js:222]: Added `shortenString`, which primarily used in the `shortenAddress`

**Review by jpuri — APPROVED** [review]
🚀

**Review by matthewwalsh0 — APPROVED** [review]
