### PR TITLE
fix: fixed Metametrics tracking for Social-login cp-13.4.0

### LINKED ISSUE #36069: [Bug]: Didn't send sentry error when login failed
### Describe the bug

When log in failed, there is no sentry request to log this error

### Expected behavior

Should have sentry request to log the error 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Before login, block the request
2. Login
3. Get the error
4. Check Devtool > Network
5. There is no sentry request

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.4.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #36070: [Bug]: Onboarding - Metametrics page sometimes appear on Chrome browser for Social login
### Describe the bug

 Metametrics page sometimes appear on Chrome browser for Social login.
This shouldn't be the case, as per this PR:

https://github.com/MetaMask/metamask-extension/pull/35583

This makes our tests flaky because of the intermittent behaviour from the app, so a fix for this should be prioritized soon.
For now, a delay in the spec side mitigates the issue.

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Run spec or check ci/ flaky test report

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

main

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #36107: [Bug]: Should not show Metametric screen when clicking BACK on browser
### Describe the bug

When user rehydrate, after input password successfully, user click BACK on browser, it show Metametric screen

### Expected behavior

Should not show Metametric screen in social login flow

### Screenshots/Recordings

https://github.com/user-attachments/assets/6b2d0b2e-cd0e-4dcb-9be5-4c44815ac5c7

### Steps to reproduce

1. Rehydrate
2. Input password
3. Click BACK on browser
4. Check metametric screen

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.4.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lwin-kyaw**
## **Description**
This PR fixes the sentry error tracing and segment tracking for Social-login users.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36086?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed sentry error reporting and segment tracking for Social-login flow.
CHANGELOG entry: Fixed flaky UI for metametric screen in chrome
CHANGELOG entry: Removed `isSocialLoginFlowEnabledForMetrics` from Metametrics Controller.
CHANGELOG entry: Fixed security tab Metametrics toggle UI.
CHANGELOG entry: Added syncing for Marketing consent for Social login users.

## **Related issues**

Fixes: 
- https://github.com/MetaMask/metamask-extension/issues/36069
- https://github.com/MetaMask/metamask-extension/issues/36070
- https://github.com/MetaMask/metamask-extension/issues/36107

### Segment/Sentry events ~ Social Login flow

https://github.com/user-attachments/assets/c6802e10-ee56-487f-b8b4-122f0456dca3

1. Install a fresh wallet
2. On the welcome page, open the Network inspector tab in Chrome dev tools.
3. Create new wallet or import with Social login.
4. After Successful login, you should be able to see the `Segment API requests` due to metametrics event tracking in the network inspector tab.
5. On the side note, if there're any errors, you should be seeing the `Sentry requests` in the network inspector tab too.

### Segment/Sentry events ~ SRP Flow

https://github.com/user-attachments/assets/2c262e52-ef6c-4484-8a44-42875e857d2e

1. Install a fresh wallet
2. On the welcome page, open the Network inspector tab in Chrome dev tools.
3. Create new wallet or import SRP (no social login)
4. During the onboarding at Metametric page, do not `AGREE` to metametrics.
5. Inspect the network tab, you should not see any segment api calls or sentry calls, since user did not opt in for metametrics.
6. After onboarding, go to the security & privacy settings, enable the Metametrics, you should see Segment API calls in the network inspector tab.

### Metametrics Page Show/Hide during onboarding (Chrome - Social Login)
1. Create or import wallet with social login
2. Create password or login based on the step 1
3. During onboarding, you should not see the metametrics page at all.
4. Try refreshing, navigating back-and-forth during onboarding.
5. Additionally, open multiple onboarding tabs

### Metametrics Page Show/Hide during onboarding (Firefox)
1. For SRP flow (or any flow in firefox), the onboarding steps are the same as previous version.
2. During onboarding, you should see the metametrics page.
3. Try refreshing, navigating back-and-forth during onboarding.
4. Additionally, open multiple onboarding tabs

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by LeVinhGithub** [comment]
@lwin-kyaw 

There are 2 issues in the recording:
- Took to long for rehydration
- Show "Wallet is ready" screen if click BACK on browser

https://github.com/user-attachments/assets/c3986964-4bde-4dec-9b18-adfb4afac0d2



Please help me check
thanks much

**Comment by lwin-kyaw** [comment]
> @lwin-kyaw
> 
> There are 2 issues in the recording:
> 
> * Took to long for rehydration
> * Show "Wallet is ready" screen if click BACK on browser
> 
>  Screenshare.-.2025-09-19.12_14_07.PM.mp4 
> Please help me check thanks much

Hi @LeVinhGithub, this happens because your account have lots of SRPs, it's taking long for rehydration due to the account discovery. 

We have [separate ticket](https://github.com/MetaMask/metamask-extension/issues/35385) to resolve this, and will improve this in the another PR.

File: test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts [hunk 1]
```diff
@@ -89,31 +88,10 @@ class OnboardingCompletePage {
...
-        await this.driver.clickElementAndWaitToDisappear(
-          this.downloadAppContinueButton,
-        );
-        await this.driver.waitForSelector(this.installCompleteMessage);
-        await this.driver.waitForSelector(this.pinExtensionMessage);
-      } catch (_) {
-        // If MetaMetrics is also not present, rethrow the original error
-        throw e;
-      }
-    }
```
Comment (seaona) [inline test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts:116]: thanks for removing the temp code 🙌 
I'm trying to better understand the fix. Is it that we now rely on this API call, to know if the user has opted in to Metametrics?
And given that we mock it, we always get a stable response now? 

Or is it something else?

Thank you in advance 🙇‍♀️

Comment (lwin-kyaw) [reply test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts:116]: Hi @seaona, the API calls added in this PR, is just to sync the marketing opt in status. (Both the actual API calls and mocks are added just in this PR and not related to the fix).

The root cause for the flaky UI issue is as below, 
In [the previous PR](https://github.com/MetaMask/metamask-extension/pull/35583), we added [a new metametrics state](https://github.com/MetaMask/metamask-extension/blob/main/app/scripts/controllers/metametrics-controller.ts#L309) for the social login, to track the Metametrics state for the social-login users. The motive is to enable Metametric (set the new state to `true`) for all social-login users since the login, by default.

However, we made a mistake [here](https://github.com/MetaMask/metamask-extension/blob/main/ui/pages/onboarding-flow/welcome/welcome.js#L356) in the login, setting the state to `false`. That affects [the Metametrics page logic](https://github.com/MetaMask/metamask-extension/blob/main/ui/selectors/metametrics.js#L20), causing the flaky UI in some places. 

Please see the below selector which is used to check whether user has selected the Metametrics Opt in.
Since, we wrongly set the `getIsSocialLoginFlowEnabledForMetrics` to `false` in [login](https://github.com/MetaMask/metamask-extension/blob/main/ui/pages/onboarding-flow/welcome/welcome.js#L356), the selector falsely returns the wrong logic.
```ts
// Selector to check if user has selected the Metametrics opt in 
export const getIsParticipateInMetaMetricsSet = (state) =>
  Boolean(getIsSocialLoginFlowEnabledForMetrics(state)) || // <== this can return false
  state.metamask.participateInMetaMetrics !== null;
```

Comment (lwin-kyaw) [reply test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts:116]: In this PR, I have removed the `isSocialLoginFlowEnabledForMetrics` from the metametrics-controller. As I think we don't really need an extra state value to track the Metametrics for social-login user.  It's easier and simpler to utilize with the existing state, `participateInMetaMetrics`. 

And also fixed the incorrect logic in the login, https://github.com/MetaMask/metamask-extension/pull/36086/files#diff-34e54ee79620159041feb6e00ed678089dc1e7fb3c14ea46448baa3a41e77d9eR349-R357.

File: ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js [hunk 2]
```diff
@@ -55,7 +56,7 @@ export default function OnboardingFlowSwitch() {
     return (
       <Navigate
         to={
-          isParticipateInMetaMetricsSet || !isFirefox
+          isParticipateInMetaMetricsSet
```
Comment (himanshuchawla009) [inline ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js:59]: why firefox case is removed ?

**Review by himanshuchawla009 — CHANGES_REQUESTED** [review]

File: ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js (hunk 2 above)
Comment (lwin-kyaw) [reply ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js:59]: Hi, coz we don't really need it. Here, we are only checking if the participateInMetaMetricsSet is not null, i.e. user has not selected anything yet.

In case of firefox, (even for social login), we don't set anything to the metametrics default state.
Ref: https://github.com/MetaMask/metamask-extension/pull/36086/files#diff-34e54ee79620159041feb6e00ed678089dc1e7fb3c14ea46448baa3a41e77d9eR357

**Review by himanshuchawla009 — APPROVED** [review]

File: ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js [hunk 3]
```diff
@@ -21,8 +21,10 @@ import {
   getIsUnlocked,
   getSeedPhraseBackedUp,
 } from '../../../ducks/metamask/metamask';
+///: BEGIN:ONLY_INCLUDE_IF(build-main,build-beta)
```
Comment (chaitanyapotti) [inline ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js:24]: why import only if main, beta?

File: ui/pages/onboarding-flow/welcome/welcome.js [hunk 4]
```diff
@@ -349,11 +348,13 @@ export default function OnboardingWelcome() {
...
-          // if firefox, set isSocialLoginFlowEnabledForMetrics to false, otherwise set to true
-          dispatch(setIsSocialLoginFlowEnabledForMetrics(!isFireFox));
         } else if (loginOption === LOGIN_OPTION.EXISTING) {
           await onSocialLoginImportClick(loginType);
-          dispatch(setIsSocialLoginFlowEnabledForMetrics(false));
+        }
+
+        if (!isFireFox) {
+          // sent queued events
+          dispatch(setParticipateInMetaMetrics(true));
```
Comment (chaitanyapotti) [inline ui/pages/onboarding-flow/welcome/welcome.js:357]: so, on rehydration of social login on a new device, we make metametrics mandatory irrespective of their previous choice here?

Comment (chaitanyapotti) [reply ui/pages/onboarding-flow/welcome/welcome.js:357]: This is intended according to @nakulmk

File: ui/pages/settings/security-tab/security-tab.component.js [hunk 5]
```diff
@@ -179,6 +174,32 @@ export default class SecurityTab extends PureComponent {
...
+        event: MetaMetricsEventName.AnalyticsPreferenceSelected,
+        properties: {
+          is_metrics_opted_in: true,
+          has_marketing_consent: Boolean(value),
+          location: 'Settings',
+        },
+      });
+    } else if (!this.props.socialLoginEnabled) {
+      // for non-social login users, we need to set the participate in meta metrics to true if they have data collection for marketing
+      this.props.setParticipateInMetaMetrics(true);
```
Comment (chaitanyapotti) [inline ui/pages/settings/security-tab/security-tab.component.js:199]: this logic needs to be fixed

Comment (lwin-kyaw) [reply ui/pages/settings/security-tab/security-tab.component.js:199]: Will fix in the new PR.

File: ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js (hunk 3 above)
Comment (chaitanyapotti) [reply ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js:24]: This is because of the removed code logic and is intended

File: ui/pages/settings/security-tab/security-tab.component.js (hunk 5 above)
Comment (lwin-kyaw) [reply ui/pages/settings/security-tab/security-tab.component.js:199]: ref: https://github.com/MetaMask/metamask-extension/pull/36063

Comment (chaitanyapotti) [reply ui/pages/settings/security-tab/security-tab.component.js:199]: Will be fixed in https://github.com/MetaMask/metamask-extension/pull/36063

**Review by chaitanyapotti — APPROVED** [review]

**Review by LeVinhGithub — APPROVED** [review]
lgtm

**Review by seaona — APPROVED** [review]
QA changes look good! thank you for the fix 🙏

File: test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts (hunk 1 above)
Comment (seaona) [reply test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts:116]: thank you v much for the explanation @lwin-kyaw Changes LGTM!
