### PR TITLE
fix: logic for displaying Interacting With detail on confirmation page

### LINKED ISSUE #36785: [Bug]: Showing "Interacting with" row for token transfers outside of advanced view
### Describe the bug

We're always showing "Interacting with" row for wallet initiated token sends. We should only show this within advanced view.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/b33eafff-e442-4547-b006-290612ce201d

### Steps to reproduce

1. Start a send for a token
2. Get to the confirmation 
3. Notice how you'll always see the "Interacting with" row

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.5.0

### Build type

None

### Browser

Brave, Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Change in logic around when interacting with row is displayed as detailed [here](https://github.com/MetaMask/metamask-extension/issues/36785#issuecomment-3482117785).

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36785

## **Manual testing steps**

1. Submit different confirmations
2. Check that Interacting With row is displayed according to logic in task

## **Screenshots/Recordings**
Screenshot 2026-01-05 at 5 43 00 PM
Screenshot 2026-01-05 at 5 42 43 PM

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Refines confirmation UI to consistently show or hide `Interacting with` based on transaction context.
> 
> - Centralizes `RecipientRow` logic: do not render for batch transactions (`to === from`), upgrade/downgrade flows, or invalid addresses; otherwise render by default
> - `ApproveDetails`: always renders `RecipientRow`; keeps `MethodDataRow` behind advanced details
> - `TokenDetailsSection`: shows `Interacting with` for non-`simpleSend` when advanced details are enabled or origin is not `ORIGIN_METAMASK`; origin row is hidden for MetaMask-originated actions
> - Removes `SmartContractWithLogo` path and related assertions; simplifies ownerId usage
> - Updates e2e tests to drop wallet-initiated `Interacting with` checks where it no longer applies; adjusts batch tests to expect no recipient row; refreshes snapshots and tooltip IDs
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2bbc3866e9530327115fadde2d0075552f2d2599. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/token-transfer/token-details-section.tsx [hunk 1]
```diff
@@ -35,22 +28,10 @@ export const TokenDetailsSection = () => {
...
-  const balanceChanges = balanceChangesResult.value;
-  const isSimulationEmpty = balanceChanges.length === 0;
 
   const shouldShowTokenRow =
     transactionType !== TransactionType.simpleSend &&
-    (showAdvancedDetails ||
-      isSimulationEmpty ||
-      nonNativeSendTransactionTypes.includes(transactionType) ||
-      isSimulationError);
+    (showAdvancedDetails || transactionMeta?.origin !== ORIGIN_METAMASK);
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/info/token-transfer/token-details-section.tsx:34]: For transfers the rule for showing Interacting With row is:

1. don't display for native send
2. display only if either of:
    * advanced details is visible
    * origin is not metamask

File: ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx [hunk 2]
```diff
@@ -69,25 +69,20 @@ export const RecipientRow = ({ recipient }: { recipient?: Hex } = {}) => {
...
       data-testid="transaction-details-recipient-row"
       label={t('interactingWith')}
       tooltip={t('interactingWithTransactionDescription')}
     >
-      {showContractLogo ? (
-        <SmartContractWithLogo />
-      ) : (
-        <ConfirmInfoRowAddress address={to} chainId={chainId} />
-      )}
+      <ConfirmInfoRowAddress address={to} chainId={chainId} />
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx:84]: If confirmation is not transfer we show Interacting With row
> unless it is batched transaction, or upgrade / downgrade 7702

**Review by matthewwalsh0 — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]
