### PR TITLE
fix: `gasFeeEstimates` property undefined

### LINKED ISSUE #27501: [Sentry] TypeError: Cannot read properties of undefined (reading 'medium')
Sentry Issue: [METAMASK-XC12](https://metamask.sentry.io/issues/5918765135/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'medium')
  at updateTransactionUsingEstimate (ui/pages/confirmations/hooks/useTransactionFunctions.js:204:12)
  at <object>.onClick (ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js:111:9)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
...
(16 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**
This PR fixes an issue created by Sentry where the property `gasFeeEstimates` is `undefined`.
Added an early return when the property is `undefined` and covered the scenario with unit tests.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29312?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27501 https://github.com/MetaMask/metamask-extension/issues/27241

## **Manual testing steps**

1. Go to this test dapp
2. Block requests against gas-api
3. Start a send or contract interaction 
4. Verify the console

## **Screenshots/Recordings**

[block-gas-api.webm](https://github.com/user-attachments/assets/1c3cf638-905e-4df9-b875-84f0056979b1)

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/hooks/useTransactionFunctions.js [hunk 1]
```diff
@@ -201,9 +201,14 @@ export const useTransactionFunctions = ({
 
   const updateTransactionUsingEstimate = useCallback(
     (gasFeeEstimateToUse) => {
+      if (!gasFeeEstimates) {
+        return;
+      }
+
       if (!gasFeeEstimates[gasFeeEstimateToUse]) {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useTransactionFunctions.js:208]: Could we achieve the same with optional chaining here?

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/pages/confirmations/hooks/useTransactionFunctions.js (hunk 1 above)
Comment (vinistevam) [reply ui/pages/confirmations/hooks/useTransactionFunctions.js]: True, pushed [here](https://github.com/MetaMask/metamask-extension/pull/29312/commits/18f8b8e79c74f5a00b38a8fdac06ad64ac15d0b1).

**Review by jpuri — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by cryptotavares — APPROVED** [review]
