### PR TITLE
Fixing unlocalized strings

### LINKED ISSUE #11094: Localize 'View More' button on transaction list
The "View More" button on the transaction list should be localized.

It is here: https://github.com/MetaMask/metamask-extension/blob/85eb62e8cf887e3de6179342fcd15dcfd909148f/ui/components/app/transaction-list/transaction-list.component.js#L162

### PR DESCRIPTION
**Pull request by ryanml**
Fixes MetaMask/metamask-extension#11094

### CODE REVIEW

File: ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js [hunk 1]
```diff
@@ -27,76 +27,87 @@ export default class MetaMetricsOptInModal extends Component {
...
                   <i className="fa fa-check" />
                   <div className="metametrics-opt-in__row-description">
-                    Send anonymized click & pageview events
+                    {t('metametricsCommitmentsSendAnonymizedEvents')}
                   </div>
                 </div>
                 <div className="metametrics-opt-in__row">
                   <i className="fa fa-check" />
                   <div className="metametrics-opt-in__row-description">
-                    Maintain a public aggregate dashboard to educate the
```
Comment (Gudahtt) [inline ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:59]: Ah, I was wondering what was going on here - I thought we localized this already! We did, but only during onboarding. This second copy of the metametrics agreement was forgotten.

This is intended to match the onboarding metrics agreement exactly, which has had this bullet removed (since we didn't actually deliver on this commitment, and had no immediate plans to). This should be compared with the onboarding page to ensure no other differences exist either.

Comment (Gudahtt) [reply ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:59]: I'm not even entirely sure we need this modal still :thinking: It was used to catch an edge case where a user might bypass the metrics screen. I don't recall how that might occur.

Comment (ryanml) [reply ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:59]: I can remove this bullet to match the full page metrics component.

I was able to get the modal to appear like so:

1. Setup MetaMask, select import
2. On the metrics opt-in tab, navigate to `initialize/create-password/import-with-seed-phrase`
3. Enter seed phrase + new password
4. Logout once your on the home screen
5. Log back in
6. See the modal

Comment (Gudahtt) [reply ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:59]: Ah cool, nice job! Probably best to keep it anyway as a safeguard.

Comment (ryanml) [reply ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:59]: This bullet has been removed from the modal for consistency

File: ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js [hunk 2]
```diff
@@ -27,76 +27,81 @@ export default class MetaMetricsOptInModal extends Component {
...
                 </div>
                 <div className="metametrics-opt-in__row">
                   <i className="fa fa-times" />
                   <div className="metametrics-opt-in__row-description">
-                    <span className="metametrics-opt-in__bold">Never</span>{' '}
-                    collect your full IP address
+                    {t('metametricsCommitmentsNeverCollectIP', [
+                      <span
+                        className="metametrics-opt-in__bold"
+                        key="neverCollectKeys"
```
Comment (Gudahtt) [inline ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:72]: Nit: probably better to use a different `key` name here, just so it doesn't confuse readers

```suggestion
                        key="neverCollectIP"
```

File: ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js [hunk 3]
```diff
@@ -27,76 +27,81 @@ export default class MetaMetricsOptInModal extends Component {
...
                 </div>
                 <div className="metametrics-opt-in__row">
                   <i className="fa fa-times" />
                   <div className="metametrics-opt-in__row-description">
-                    <span className="metametrics-opt-in__bold">Never</span> sell
-                    data for profit. Ever!
+                    {t('metametricsCommitmentsNeverSellDataForProfit', [
+                      <span
+                        className="metametrics-opt-in__bold"
+                        key="neverCollectKeys"
```
Comment (Gudahtt) [inline ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js:85]: Nit: probably better to use a different `key` name here, just so it doesn't confuse readers

```suggestion
                        key="neverSellData"
```

**Review by Gudahtt — DISMISSED** [review]
LGTM!

File: ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js (hunk 3 above)
Comment (ryanml) [reply ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js]: Updated both here and in the full page component

File: ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js (hunk 2 above)
Comment (ryanml) [reply ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js]: Updated both here and in the full page component

**Review by Gudahtt — APPROVED** [review]
LGTM!
