### PR TITLE
fix: add alert when selected account is different from signing account in confirmation

### LINKED ISSUE #28015: [Bug]: When an account is selected in the wallet but hasn't been connected to a dApp in the Permissions, any transaction initiated from this dApp defaults to using a different ( connected) account
### Describe the bug

- The user has `Account 1` connected to the dApp
- the user switches to another account in MetaMask but does not connect it in the `Permissions`
- user initiates transaction from the dApp

    
1. When the` Improved transactions requests` toggle is enabled (which is the default setting), there currently isn't a clear notification within the Confirmation process indicating that the transaction is being created for an account different from the one actively selected in the wallet. 
  This situation results in transactions being initiated with a nonce that incorrectly matches the value of the account selected in the wallet. However, the transaction is ultimately submitted with the correct nonce, leading to a successful transaction being executed on an unintended account. [fix for the nonce issue](https://github.com/MetaMask/metamask-extension/pull/28272)

2. In the legacy Confirmations, there is a notification on the Confirmation screen that hints the account being used for the transaction is not the one currently selected in the wallet. 
    ******Transaction is created AND submitted with the incorrect nonce on a wrong account which results in the Failed low nonce or Pending hign nonce tx.***** - this nonce issue is fixed

    Given that` Permissions` is a relatively recent addition, enhancing the visibility of prompts or notifications that guide users to activate their chosen account via `Permissions` could decrease the chances of transactions being inadvertently conducted with the wrong account, thereby elevating the overall user experience.

### Expected behavior

-

### Screenshots/Recordings

RC 12.7.0

Redesigned Confirmation:

https://github.com/user-attachments/assets/bea00713-c41b-429b-8cc4-7db6b76fe2ef

 
Legacy Confirmation:

https://github.com/user-attachments/assets/94d979a6-49dd-4ced-95cf-36869d635b84

Screenshot 2024-10-22 at 12 44 35

Screenshot 2024-10-22 at 12 44 45

### Steps to reproduce

1. Switch to the account that is not connected to the dAPP
2. Switch to the dApp
4. Start a transaction

### Error messages or log output

```shell
No errors
```

### Detection stage

On the development branch, RC 12.6.0, RC 12.7.0

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Show warning when signing account in confirmation is different from currently selected account in MM.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28015

## **Manual testing steps**

1. Go to test dapp and connect with an account
2. Switch to a different account
3. Submit a confirmation and check warning next to signing account

## **Screenshots/Recordings**
Signature Request:
Screenshot 2024-11-20 at 6 12 02 PM

Contract Interaction:
Screenshot 2024-11-20 at 6 12 16 PM

Send token:
Screenshot 2024-11-20 at 6 47 29 PM

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.tsx [hunk 1]
```diff
@@ -50,24 +56,40 @@ export const TransactionFlowSection = () => {
...
-          value={transactionMeta.txParams.from}
-          type={NameType.ETHEREUM_ADDRESS}
-          variation={chainId}
-        />
+        <ConfirmInfoAlertRow
+          alertKey={RowAlertKey.SigningInWith}
+          label={t('from')}
+          ownerId={transactionMeta.id}
+        >
+          <Box marginTop={1}>
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.tsx:65]: Frustrating we can't use `SigningInWithRow` here but it seems the `label` and this `Box` are unique.

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx [hunk 2]
```diff
@@ -81,6 +82,13 @@ const TypedSignInfo: React.FC = () => {
             />
           </ConfirmInfoRow>
         )}
+        <ConfirmInfoAlertRow
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx:85]: Minor, could we create a single definition of this row for signatures to avoid the duplication?

Similar to transactions where we re-use standard row components.

File: ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+        reason: t('selectedAccountMismatch'),
+        field: RowAlertKey.SigningInWith,
+        severity: Severity.Warning,
+        message: t('alertSelectedAccountWarning'),
+      },
+    ];
+  }, [confirmationAccountSameAsSelectedAccount, t]);
+};
+
+export default useSelectedAccountAlerts;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts:42]: Minor, do we try and avoid `default` exports to allow for future extensibility and help auto-complete?

File: ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+  const t = useI18nContext();
+
+  const { currentConfirmation } = useConfirmContext();
+  const selectedAccount = useSelector(getSelectedAccount);
+
+  const fromAccount =
+    (currentConfirmation as SignatureRequestType)?.msgParams?.from ??
+    (currentConfirmation as TransactionMeta)?.txParams?.from;
+  const confirmationAccountSameAsSelectedAccount =
+    !fromAccount || fromAccount === selectedAccount?.address;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts:23]: Minor, do we have to worry about different case here or are they normalized elsewhere?

File: ui/pages/confirmations/hooks/useConfirmationAlerts.ts [hunk 5]
```diff
@@ -40,6 +41,7 @@ function useTransactionAlerts(): Alert[] {
   const signingOrSubmittingAlerts = useSigningOrSubmittingAlerts();
   ///: END:ONLY_INCLUDE_IF
   const queuedConfirmationsAlerts = useQueuedConfirmationsAlerts();
+  const selectedAccountAlerts = useSelectedAccountAlerts();
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useConfirmationAlerts.ts:44]: Minor, should this go in `useConfirmationAlerts` below as it applies to signatures and transactions?

File: ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.test.ts [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+        msgParams: {
+          ...unapprovedPersonalSignMsg.msgParams,
+          from: '0x0',
+        },
+      } as SignatureRequestType),
+    );
+    expect(result.current).toEqual(expectedAlert);
+  });
+
+  it('returns an alert for transaction if signing account is different from selected account', () => {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.test.ts:48]: Do we also need unit tests for when the address is the same and missing?

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.test.ts (hunk 6 above)
Comment (jpuri) [reply ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.test.ts:48]: I added more tests to it.

File: ui/pages/confirmations/hooks/useConfirmationAlerts.ts (hunk 5 above)
Comment (jpuri) [reply ui/pages/confirmations/hooks/useConfirmationAlerts.ts:44]: I updated the PR.

File: ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts (hunk 4 above)
Comment (jpuri) [reply ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts:23]: Good point, I fixed it.

File: ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts (hunk 3 above)
Comment (jpuri) [reply ui/pages/confirmations/hooks/alerts/useSelectedAccountAlerts.ts:42]: Fixed.

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx (hunk 2 above)
Comment (jpuri) [reply ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx]: I did this re-factor

**Review by matthewwalsh0 — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
