### PR TITLE
fix: Blockaid disable disclosure scrollToBottom

### LINKED ISSUE #21187: [Bug]: PPOM scrolling down function with incorrect behaviour in See details
### Describe the bug

**Problem**: whenever a transaction is flagged as malicious, we see an incorrect scrolling behaviour in the following ways:
- when I click See details for the first time -- no scroll happens
- when I double click any text from the details -- it scrolls me down everytime
- when I click See details again (for hiding them) and then click See details again to show them -- scrolls me down

https://github.com/MetaMask/metamask-extension/assets/54408225/3706ca24-fecd-4536-9497-790983bb0e4b

### Expected behavior

Proposal, not 100% sure to expect though:
- anytime click See details for revealing them, should auto scroll you down?
- double clicking the text, should not scroll you down?

OR:
- never auto scroll down

cc @bschorchit 

### Screenshots

_No response_

### Steps to reproduce

1. Select mainnet
2. Trigger a malicious signature from the test dapp
3. Click See details -- see no auto scroll happens
4. Double click details text -- see auto scroll happens
5. Click Hide details and See details again -- see now auto scroll happens

### Error messages or log output

_No response_

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

Replaces default Disclosure scrollToBottom behavior to fix issue where opening Blockaid Banner Alert "See Details" would scroll to the bottom

Adds tests for Disclosure component 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/21187

### **Before**

sdlg5Rty3W

### **After**

ZHn0VM0UwG

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/ui/disclosure/disclosure.js [hunk 1]
```diff
@@ -47,24 +47,32 @@ const renderSummaryByType = (variant, title, size) => {
   }
 };
 
-const Disclosure = ({ children, title, size, variant }) => {
+const Disclosure = ({
+  children,
+  isScrollToBottomOnOpen,
```
Comment (jpuri) [inline ui/components/ui/disclosure/disclosure.js:52]: Should we default `isScrollToBottomOnOpen` to true to keep it enabled by default ?

**Review by segun — APPROVED** [review]

File: ui/components/ui/disclosure/disclosure.js (hunk 1 above)
Comment (digiwand) [reply ui/components/ui/disclosure/disclosure.js:52]: hi @jpuri, we should not since there is no need to open the Disclosure with scroll. Also, there is a potential bug with the initial implementation with scrollToBottom on. It scrolls to the bottom of the Disclosure component with no buffer. This means, if there is plenty of space below the Disclosure component, it may scroll underneath the component and skip over the entirety of the Disclosure content. Luckily, for the initial instance and only other instance of Disclosure, transaction-list-item-details.component.js, there is not much content below. Thus, when it scrolls down, the Disclosure component still can be seen.

Comment (digiwand) [reply ui/components/ui/disclosure/disclosure.js:52]: hi @jpuri, we should not since opening the Disclosure with scroll is unnecessary. 

Also, there is a potential bug with the initial implementation with scrollToBottom turned on. It scrolls to the bottom of the Disclosure component with no buffer. This means that if there is plenty of space below the Disclosure component, it may scroll underneath the component and skip over the entirety of the Disclosure content. This bug can be seen as reported by this issue. 

Luckily, for the initial instance and only other instance of Disclosure, transaction-list-item-details.component.js, there is little content below. Thus, the Disclosure component can still be seen when it scrolls down and seemingly works fine. I question why the original UI desired to scroll down to begin with.

**Review by jpuri — APPROVED** [review]
