### PR TITLE
test: Re-enable tests that were failing with BIP44 FF

### LINKED ISSUE #37677: [Bug]:  transaction confirmation dialog does not show fee is paid with different token or by Metamask when BIP44 is enabled
### Describe the bug

The following two e2e tests:
   test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702.spec.ts
   test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702-sponsed.spec.ts
will fail with BIPP44 enabled. 

When`eth_sendTransaction` request is sent and the gas fee are paid in USDC or by Metamask, it's not showing on the confirmation dialog. See videos/screenshot below 

### Expected behavior

User is able to confirm to pay with USDC

### Screenshots/Recordings

Paid in USDC before BIP44

https://github.com/user-attachments/assets/71e913fe-d269-4ab8-a5db-cb6a1917a3bf

Paid in USDC with BIP44 

https://github.com/user-attachments/assets/208c614a-de32-4cc0-addf-c702c67a5443

Paid by Metamask before

Image

Paid by Metamask with BIP44

Image

### Steps to reproduce

1. Run script test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702.spec.ts
2. Notice that with BIPP44 turned ON it will fail

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #38077: [Bug]: After restoring account from state persistence failure Metamask unlock is not working
### Describe the bug

There is a test for restoring the account from state persistence failure `test/e2e/tests/onboarding/onboarding.spec.ts`

when running the script with BIP44 turned on the Extension gets stuck when unlocking Metamask

Image

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Run `test/e2e/tests/onboarding/onboarding.spec.ts`

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

13.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #38080: [Bug]: Reactivate vault corruption test after BIP44 is turned on with FF
### Describe the bug

The tests `test/e2e/tests/vault-corruption/vault-corruption.spec.ts` had to be skipped temporarily until BIP44 is turned on using FF because with the mocking of the FF response to turn on BIP44 by default, when the extension is reset the mocks will be lost

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1.  Run `test/e2e/tests/vault-corruption/vault-corruption.spec.ts`

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

13.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by davibroc**
## **Description**

This PR re-enables 4 tests that were previously skipped because they were failing with BIP44 FF turned on. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39097?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Restores coverage for BIP44-affected scenarios and stabilizes flaky waits across e2e flows.
> 
> - Re-enables: `Gas Fee Tokens - EIP-7702` (regular and sponsored), onboarding recovery-from-state-persistence, and `Vault Corruption` suites
> - Adds explicit timeouts and waits: `waitForMultipleSelectors` with timeouts in `account-list-page.ts` and `start-onboarding-page.ts`; increased wait on `termsOfUseAgreeButton`; extra delay and non-empty check for address in `account-address-modal.ts`
> - Vault recovery flow hardening: wait for `#critical-error-button`, use `until.alertIsPresent()` before accepting/dismissing alert, and stabilize post-dismiss behavior
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4cab5f4b8771124e1621bdb6ee1010d5e5063a2b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by hjetpoluru — DISMISSED** [review]

File: test/e2e/page-objects/pages/multichain/account-address-modal.ts [hunk 1]
```diff
@@ -41,7 +41,11 @@ class AccountAddressModal {
    */
   async getAccountAddress(): Promise<string> {
     console.log('Getting the address from the modal');
+    // Wait for animation to complete
+    await this.driver.delay(3000);
```
Comment (ccharly) [inline test/e2e/page-objects/pages/multichain/account-address-modal.ts]: If we have a `waitForSelector` right after, do we really need this delay? 🤔

Maybe we can just tweak this call and adapt the `timeout` there?

File: test/e2e/tests/onboarding/onboarding.spec.ts [hunk 2]
```diff
@@ -313,10 +313,7 @@ describe('MetaMask onboarding', function () {
       },
     );
   });
-
-  // But #38077 - After estoring account from state persistence failure Metamask unlock is not working
-  // eslint-disable-next-line mocha/no-skipped-tests
-  it.skip('Provides an onboarding path for a user who has restored their account from state persistence failure', async function () {
+  it('Provides an onboarding path for a user who has restored their account from state persistence failure', async function () {
```
Comment (ccharly) [inline test/e2e/tests/onboarding/onboarding.spec.ts:317]: Nit: But there used to have an empty line before

```suggestion

  it('Provides an onboarding path for a user who has restored their account from state persistence failure', async function () {
```

File: test/e2e/tests/vault-corruption/vault-corruption.spec.ts [hunk 3]
```diff
@@ -199,14 +196,16 @@ describe.skip('Vault Corruption', function () {
     confirm: boolean;
   }) {
     // click the Recovery/Reset button
+    await driver.waitForSelector('#critical-error-button');
     await driver.clickElement('#critical-error-button');
 
-    // Confirm we want to recover/reset.
-    const prompt = await driver.driver.switchTo().alert();
+    // Wait for the confirmation alert to appear and handle it immediately
+    await driver.driver.wait(until.alertIsPresent(), 20000);
```
[the remark this answers is not in the document]
Comment (ccharly) [reply test/e2e/tests/vault-corruption/vault-corruption.spec.ts:203]: Why are we dismissing this review? That seems completely valid and we already are using `waitForBrowserAlert` in other areas. (and that seems pretty similar to the logic we're using it here too).

Also, is that expected to have a 20s timeout?

File: test/e2e/page-objects/pages/account-list-page.ts [hunk 4]
```diff
@@ -226,13 +226,16 @@ class AccountListPage {
...
-      ]);
+      await this.driver.waitForMultipleSelectors(
+        [
+          {
+            css: this.addMultichainAccountButton,
+            text: 'Add account',
+          },
+          this.multichainAccountOptionsMenuButton,
+        ],
+        { timeout: 30000 },
```
Comment (ccharly) [inline test/e2e/page-objects/pages/account-list-page.ts]: This is a pretty big timeout, is that expected? Why do we need this now?

File: test/e2e/page-objects/pages/onboarding/start-onboarding-page.ts [hunk 5]
```diff
@@ -75,15 +75,16 @@ class StartOnboardingPage {
...
 
   async checkLoginPageIsLoaded(): Promise<void> {
     try {
-      await this.driver.waitForMultipleSelectors([
-        this.createWalletButton,
-        this.importWalletButton,
-      ]);
+      await this.driver.waitForMultipleSelectors(
+        [this.createWalletButton, this.importWalletButton],
+        { timeout: 20000 },
```
Comment (ccharly) [inline test/e2e/page-objects/pages/onboarding/start-onboarding-page.ts:86]: Same question, why do we need this now?

**Review by racitores — DISMISSED** [review]

File: test/e2e/tests/onboarding/onboarding.spec.ts (hunk 2 above)
Comment (davibroc) [reply test/e2e/tests/onboarding/onboarding.spec.ts:317]: Done

File: test/e2e/tests/vault-corruption/vault-corruption.spec.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (davibroc) [reply test/e2e/tests/vault-corruption/vault-corruption.spec.ts:203]: I am dismissing the review because of the following reasons
- the script was already using Raw Selenium access: driver.driver and was working fine. All I did was to increase the timeout out because 10 seconds wasn't enough for Firefox and would cause the test to be flaky. With 20 secs timeout we are just playing safe and we are not increasing the time execution.
- waitForBrowserAlert()  doens't work as you see in the screenshot below

Screenshot 2026-01-12 at 11 55 19 AM
Screenshot 2026-01-12 at 11 55 09 AM

File: test/e2e/page-objects/pages/onboarding/start-onboarding-page.ts (hunk 5 above)
Comment (davibroc) [reply test/e2e/page-objects/pages/onboarding/start-onboarding-page.ts:86]: We need it to reduce flakiness. This has nothing to do with my changes. But in the pipeline this test would often timeout because 10 seconds wasn't enough. Not sure what is the problem to increasing to 20 seconds just to reduce flakiness

File: test/e2e/page-objects/pages/multichain/account-address-modal.ts (hunk 1 above)
Comment (davibroc) [reply test/e2e/page-objects/pages/multichain/account-address-modal.ts]: I have reduced it to 1 sec. There is an animation on the dialog, and we need to wait the animation to complete otherwise when we try to get the address from the screen it will be empty.  I have added the `waitForSelector` but doesn't help. I have no way to check if the animation has completed.

File: test/e2e/page-objects/pages/account-list-page.ts (hunk 4 above)
Comment (davibroc) [reply test/e2e/page-objects/pages/account-list-page.ts]: I have reduced it to 15 secs. In the pipeline I have see occasional timeout failure with just 10secs.

**Review by ccharly — APPROVED** [review]

**Review by racitores — APPROVED** [review]
