### PR TITLE
fix: handle null and undefined accountId in multichain account selectors

### LINKED ISSUE #36504: [Sentry] TypeError: Cannot read properties of undefined (reading 'startsWith')
Sentry Issue: [METAMASK-XRXA](https://metamask.sentry.io/issues/6909852242/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
  at exports.extractWalletIdFromGroupId (ui/selectors/multichain-accounts/utils.ts:26:22)
  at exports.getMultichainAccountGroupById (ui/selectors/multichain-accounts/account-tree.ts:285:22)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by fabiobozzo**
## **Description**

Fixes a TypeError crash that occurred during UI startup when `selectedAccountGroup` is `null` or `undefined`, particularly during permission requests and onboarding flows.

**Root cause:** `extractWalletIdFromGroupId` attempted to call `.startsWith()` on an undefined/null `accountGroupId`, and the component tried to access `.metadata` on an undefined account object.

It's a bit hard to reproduce in normal conditions because the race condition only happens when:
- the notification window opens
- the UI starts rendering before the Redux state fully initialized
- `selectedAccountGroup` is temporarily null during the initialization sequence

**Solution:** Added defensive null checks in the selector and optional chaining in the component to handle undefined values gracefully.

## **Changelog**

CHANGELOG entry: Fixed a crash that could occur during wallet initialization when connecting to dapps

## **Related issues**

[MUL-1201](https://consensyssoftware.atlassian.net/browse/MUL-1201)

Fixes: https://github.com/MetaMask/metamask-extension/issues/36504, https://github.com/MetaMask/metamask-extension/issues/37081

## **Manual testing steps**

1. Build the extension and load it in Chrome
2. Complete onboarding or unlock the wallet
3. Connect to a test dapp (e.g., test-dapp.metamask.io)
4. Trigger a permission request: `ethereum.request({ method: 'wallet_requestPermissions', params: [{ eth_accounts: {} }] })`
5. Verify no errors appear in console or error boundary
6. Navigate through the UI to confirm account information displays correctly
---
Alternatively: 
```
// In ui/components/multichain/app-header/app-header-unlocked-content.tsx
const selectedMultichainAccountId = useSelector(getSelectedAccountGroup);

// Force null to test the bug, temporarily
const testWithNull = null; 

const selectedMultichainAccount = useSelector((state) =>
  getMultichainAccountGroupById(state, testWithNull), // instead of selectedMultichainAccountId
);
```

### **Before**

Screenshot 2025-10-27 at 16 30 19

### **After**

No errors - UI loads and displays account information correctly even when `selectedAccountGroup` is temporarily null

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

[MUL-1201]: https://consensyssoftware.atlassian.net/browse/MUL-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---

> [!NOTE]
> Adds defensive checks in selectors and UI, validates route params, and updates tests to handle null/undefined account IDs and missing groups safely.
> 
> - **UI**
>   - `ui/components/multichain/app-header/app-header-unlocked-content.tsx`:
>     - Safely read account names with optional chaining; render `PreferredAvatar` only if `internalAccount` exists.
>     - Wrap networks link in a check for `selectedMultichainAccountId`.
>   - `ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx`:
>     - Validate `id` from URL; redirect to `DEFAULT_ROUTE` when missing or when account group not found.
> - **Selectors/Utils**
>   - `ui/selectors/multichain-accounts/account-tree.ts`: `getMultichainAccountGroupById` returns `undefined` when passed a falsy `accountId`.
>   - `ui/selectors/multichain-accounts/utils.ts`: `extractWalletIdFromGroupId` throws on falsy `accountGroupId`.
> - **Tests**
>   - `ui/selectors/multichain-accounts/account-tree.test.ts`: Add cases for `null`/`undefined`/empty group IDs.
>   - `ui/selectors/multichain-accounts/utils.test.ts`: Add invalid input tests for `extractWalletIdFromGroupId`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6da73d5ef2b78fee49797a2070eb7504e23b8153. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/selectors/multichain-accounts/account-tree.ts [hunk 1]
```diff
@@ -313,6 +313,10 @@ export const getMultichainAccountGroupById = createDeepEqualSelector(
   getAccountTree,
   (_, accountId: AccountGroupId) => accountId,
   (accountTree: AccountTreeState, accountId: AccountGroupId) => {
+    if (!accountId) {
+      return undefined;
+    }
+
```
[the remark this answers is not in the document]
Comment (fabiobozzo) [reply ui/selectors/multichain-accounts/account-tree.ts:319]: The `!accountId` check alone is sufficient because:
- It handles null and undefined at runtime (which can occur during state initialization)
- TS prevents empty strings at compile time
- If an empty string somehow passes at runtime (type system violation), `extractWalletIdFromGroupId` will throw an error with the message "_Account group ID is required_"
---
`if (!accountId || accountId === '')` results in another issue: 
```
This comparison appears to be unintentional because the types '`entropy:${string}/${string}` | `keyring:${string}/${string}` | `snap:${string}/${string}`' and '""' have no overlap.ts(2367)
```

As far as I know, that means the comparison is impossible given the type constraints, making the check redundant.

File: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx [hunk 2]
```diff
@@ -89,6 +89,12 @@ export const MultichainAccountDetailsPage = () => {
   const [isAccountRemoveModalOpen, setIsAccountRemoveModalOpen] =
     useState(false);
 
+  // Redirect if account doesn't exist
+  if (!multichainAccount) {
+    history.push(DEFAULT_ROUTE);
+    return null;
+  }
+
```
Comment (fabiobozzo) [inline ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx]: To address eslint who said: 
```
Error: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx(163,10): error TS18048: 'multichainAccount' is possibly 'undefined'.
Error: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx(180,20): error TS18048: 'multichainAccount' is possibly 'undefined'.
Error: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx(292,29): error TS18048: 'multichainAccount' is possibly 'undefined'.
Error: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx(300,26): error TS18048: 'multichainAccount' is possibly 'undefined'.
```

File: ui/selectors/multichain-accounts/utils.test.ts [hunk 3]
```diff
@@ -52,5 +52,25 @@ describe('Account tree selectors utils', () => {
...
+        expect(() =>
+          extractWalletIdFromGroupId(undefined as unknown as AccountGroupId),
+        ).toThrow('Account group ID is required');
+      });
+
+      it('throws an error when accountGroupId is an empty string', () => {
+        expect(() => extractWalletIdFromGroupId('' as AccountGroupId)).toThrow(
+          'Account group ID is required',
+        );
+      });
```
[the remark this answers is not in the document]
Comment (fabiobozzo) [reply ui/selectors/multichain-accounts/utils.test.ts:73]: Imho, the test is correct as-is! Here's why:

```
const accountName =
  (isMultichainAccountsState2Enabled
    ? selectedMultichainAccount?.metadata.name ??
      internalAccount?.metadata.name
    : internalAccount?.metadata.name) ?? '';
```
So `if (!accountGroupId)` already catches empty strings. Adding `|| accountGroupId === ''` would be redundant!!

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx [hunk 4]
```diff
@@ -120,9 +120,11 @@ export const AppHeaderUnlockedContent = ({
   const shortenedAddress =
     internalAccount &&
     shortenAddress(normalizeSafeAddress(internalAccount.address));
-  const accountName = isMultichainAccountsState2Enabled
-    ? selectedMultichainAccount.metadata.name
-    : internalAccount.metadata.name;
+  const accountName =
+    (isMultichainAccountsState2Enabled
+      ? (selectedMultichainAccount?.metadata.name ??
+        internalAccount?.metadata.name)
```
Comment (gantunesr) [inline ui/components/multichain/app-header/app-header-unlocked-content.tsx]: Not sure if we should use `internalAccount?.metadata.name` since it can create confusion, maybe just an empty string?

Comment (fabiobozzo) [reply ui/components/multichain/app-header/app-header-unlocked-content.tsx]: That's right now that I think about it 👁️‍🗨️  the fallback to `internalAccount?.metadata.name` is confusing when multichain accounts are enabled. 

The empty string `''` should be clearer, it indicates "no account name is available" rather than showing maybe incorrect data, was that your reasoning too?

**Review by hmalik88 — DISMISSED** [review]

**Review by montelaidev — DISMISSED** [review]

File: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx [hunk 5]
```diff
@@ -61,10 +61,24 @@ export const MultichainAccountDetailsPage = () => {
   const dispatch = useDispatch();
   const trackEvent = useContext(MetaMetricsContext);
   const { id } = useParams();
-  const accountGroupId = decodeURIComponent(id as string) as AccountGroupId;
+
+  // Validate URL parameter early
+  if (!id) {
+    history.push(DEFAULT_ROUTE);
+    return null;
+  }
```
Comment (gantunesr) [inline ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx:69]: So if there isn't an id will the user be direct to the wallet view?

File: ui/selectors/multichain-accounts/account-tree.test.ts [hunk 6]
```diff
@@ -722,6 +722,24 @@ describe('Multichain Accounts Selectors', () => {
...
+    });
+
+    it('returns undefined when accountId is undefined', () => {
+      const result = getMultichainAccountGroupById(
+        typedMockState,
+        undefined as unknown as AccountGroupId,
+      );
+
+      expect(result).toBeUndefined();
+    });
```
Comment (gantunesr) [inline ui/selectors/multichain-accounts/account-tree.test.ts:742]: can you add another test for the case of empty string?

**Review by vinnyhoward — DISMISSED** [review]

File: ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx (hunk 5 above)
Comment (fabiobozzo) [reply ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx:69]: Yep! `DEFAULT_ROUTE = '/'` 

Missing URL param | Invalid account ID | Account doesn't exist -> home page.  
The user lands safely on the home/wallet view instead of seeing a broken page. Makes sense?

File: ui/selectors/multichain-accounts/account-tree.test.ts (hunk 6 above)
Comment (fabiobozzo) [reply ui/selectors/multichain-accounts/account-tree.test.ts:742]: Added ✔️

**Review by vinnyhoward — APPROVED** [review]

**Review by hmalik88 — APPROVED** [review]
