### PR TITLE
Fix #19548 - Increase address copy to clipboard time

### LINKED ISSUE #19548: [Bug]: Copying addresses to clipboard is not working
### Describe the bug

**Problem**: whenever I am using the function to copy to clipboard any address, I can see how they are actually not copied.

https://github.com/MetaMask/metamask-extension/assets/54408225/08dd8b7b-791c-446c-853e-4139face7c4b

### Steps to reproduce

1. Deploy a contract
2. Interact with the contract
3. Go to Activity tab
4. Click on the transaction
5. Click on the recipient
6. Click Copy to Clipboard
7. Paste the value somewhere else -- see how only an empty space is pasted

### Error messages or log output

_No response_

### Version

10.31.1 (older issue since a couple of releases at least)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

* Fixes #19548

Increases the time before clipboard gets cleared after copying a wallet address.

## Manual Testing Steps

1.  From the home screen, click the address button
2. Command-V several times to a new document until the clipboard eventually gets cleared

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/multichain/address-copy-button/address-copy-button.js [hunk 1]
```diff
@@ -14,15 +14,17 @@ import { useCopyToClipboard } from '../../../hooks/useCopyToClipboard';
...
 import Tooltip from '../../ui/tooltip/tooltip';
 import { useI18nContext } from '../../../hooks/useI18nContext';
+import { SECOND } from '../../../../shared/constants/time';
 
 export const AddressCopyButton = ({
   address,
   shorten = false,
   wrap = false,
   onClick,
+  delay = SECOND * 60,
```
Comment (DDDDDanica) [inline ui/components/multichain/address-copy-button/address-copy-button.js:24]: We can directly use `MINUTE` :)

**Comment by HowardBraham** [comment]
Is the default time really only 3 seconds?  I expect there's a lot more places where this will be a problem.

Also, what happens if you copy from one place, wait 55 seconds, and then copy from another?  Will the clipboard clear in 5 seconds?

**Comment by NidhiKJha** [comment]
I like this solution but if I copy address from account 1 then it stays copied and even I switch to account 2 the tooltip and icon is still in copied state even though the copied text is address from account 1. Functionality wise it's working fine and if I copy the address from account 2, it's updated.


https://github.com/MetaMask/metamask-extension/assets/39872794/f112ab4e-0ce4-4000-b6fc-4af6808e0f5e

**Comment by plasmacorral** [comment]
On the IOS mobile client there is an expectation set for the user by including the following text "stored for 1 minute" when an SRP or private key is copied.  Unfortunately, there was not an effective way to enforce the clipboard purge on Android. 

Should we inform the user within the UI that the clipboard will be cleared after 1 minute? 
Is the plan to purge all clipboard entries after 1 minute, or can we limit that purge just to Private Keys or SRP to be aligned with the mobile iOS client?

**Review by danjm — APPROVED** [review]
LGTM

**Comment by kevinghim** [comment]
Resolves https://github.com/MetaMask/metamask-extension/pull/19948

**Comment by danjm** [comment]
> On the IOS mobile client there is an expectation set for the user by including the following text "stored for 1 minute" when an SRP or private key is copied. Unfortunately, there was not an effective way to enforce the clipboard purge on Android.

> Should we inform the user within the UI that the clipboard will be cleared after 1 minute?
Is the plan to purge all clipboard entries after 1 minute, or can we limit that purge just to Private Keys or SRP to be aligned with the mobile iOS client?

Extension product and design are going to look into these as future improvements, but we are going to just change the delay in this PR as an MVP, so we can get it into the v10.34.0 release.

**Review by adonesky1 — APPROVED** [review]
