### PR TITLE
fix: Add default value to custom nonce modal

### LINKED ISSUE #28033: [Bug]: The increment button for the custom nonce field on redesigned confirmations is not functioning as anticipated
### Describe the bug

The increment button for the custom nonce field on redesigned confirmations is not functioning as anticipated. Rather than adjusting the nonce value by increments of 1, it defaults to 0 and 1 for decreasing and increasing actions, respectively. 

### Expected behavior

-

### Screenshots/Recordings

Redesigned transaction request:

https://github.com/user-attachments/assets/1cb15c41-4db4-4fb1-95f3-ccea488d0682

Legacy transaction request working as expected:

https://github.com/user-attachments/assets/0c740335-7677-4f98-a6fe-8726daa9737d

### Steps to reproduce

1. Enable nonce customization in the` Advanced Settings`
2. Start Send transaction
3. Try to adjust the nonce using increment buttons

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

See original bug ticket.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28659?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28033

## **Manual testing steps**

See original bug ticket.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/modals/customize-nonce/customize-nonce.component.js [hunk 1]
```diff
@@ -27,7 +27,9 @@ const CustomizeNonce = ({
   updateCustomNonce,
   getNextNonce,
 }) => {
-  const [customNonce, setCustomNonce] = useState('');
+  const defaultNonce =
```
Comment (matthewwalsh0) [inline ui/components/app/modals/customize-nonce/customize-nonce.component.js:30]: Minor, but if there's no `customNonceValue` and `nextNonce` isn't a number, then will the `defaultNonce` be set to `false`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/components/app/modals/customize-nonce/customize-nonce.component.js [hunk 2]
```diff
@@ -107,10 +109,7 @@ const CustomizeNonce = ({
               type="number"
               data-testid="custom-nonce-input"
               min="0"
-              placeholder={
-                customNonceValue ||
-                (typeof nextNonce === 'number' && nextNonce.toString())
-              }
+              placeholder={defaultNonce}
```
[the remark this answers is not in the document]
Comment (pedronfigueiredo) [reply ui/components/app/modals/customize-nonce/customize-nonce.component.js:112]: Perhaps there's still value in showing the next nonce as a placeholder if the user clears the input field.

File: ui/components/app/modals/customize-nonce/customize-nonce.component.js (hunk 1 above)
Comment (pedronfigueiredo) [reply ui/components/app/modals/customize-nonce/customize-nonce.component.js:30]: Yes, although since I only moved and didn't change this expression, I don't expect that to happen. Even though we don't specifically type check that, `nextNonce` seems to be a number everywhere in the codebase.

I am not sure which default nonce number would improve this expression, so unless we discover a bug I would keep this as it is for now.

**Review by digiwand — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
