### PR TITLE
fix: prioritize smart transaction status confirmation

### LINKED ISSUE #25349: [Bug]: Attempt to submit another transaction while having transaction in 'Pending' state, Smart Transactions toggle is ON
### Describe the bug

I have limited knowledge around Smart Transactions feature and expected behavior so I will just write down steps.

When attempting to initiate a new transaction while another is in a 'Pending' state, with the Smart Transactions feature enabled, a series of chaotic behaviors have been observed:

1. A transaction is set to 'Pending' state using low gas for a direct **ETH->ETH** send (**nonce 1579**). 
2. Another direct send **ETH->ETH** transaction is created.
3. A red warning on the confirmation screen indicates 'A previous tx is still being signed or submitted,' and the 'Confirm' button is disabled.
4. After rejection and creation of a new transaction (**ETH->USDT**), the 'Confirm' button becomes available without warnings.
5. Clicking 'Confirm' creates 'Unapproved' transaction.
6. The user can edit recipient and destination token fields for the 'Unapproved' transaction, but the 'Confirm' button is inactive, and rejection does not function.
7. Modifying the 'Unapproved' transaction activates the 'Confirm' button, but clicking it generates another 'Unapproved' transaction.
8. I created 1 'Pending' and 3 'Unapproved' transactions. Once the transactions were confirmed, only two Failed transactions can be seen within the Activity tab:  **nonce 1579** and **1580**, marked as **ETH->USDC**. Popup notifying that the transaction was cancelled was displayed after some time.
9. Notice that the popup and Smart Transactions screen are only displayed for the first and for the last transaction.

Related bug: https://github.com/MetaMask/metamask-extension/issues/25356
### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/e59a7274-5c17-44cf-b242-004bcbf73e7f

https://github.com/MetaMask/metamask-extension/assets/104780023/5845bbc3-5763-426a-9b24-45ba3adeaa71

Screenshot 2024-06-14 at 23 43 53

Screenshot 2024-06-14 at 23 43 25

Screenshot 2024-06-14 at 23 44 10

Screenshot 2024-06-14 at 23 29 23

Screenshot 2024-06-14 at 23 29 09

Screenshot 2024-06-14 at 23 30 05

### Steps to reproduce

1. See the description

### Error messages or log output

_No response_

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #25415: [Bug]: Smart Transactions - If I trigger 2 tx from a dapp, and accept the first one, MM stays loading for >30s until the 1st tx is confirmed
### Describe the bug

If I trigger 2 tx from a dapp, and accept the first one, MM stays loading until the 1st tx is confirmed. This results in blocking the popup for >30seconds, without any feedback for the user

### Expected behavior

If STX doesn't support to send another tx while the first one hasn't been confirmed, we should at least give some visual feedback to the user, instead of leaving the popup loading for >30 seconds

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/e6c9db84-fd9d-472b-b432-f4c607c0ca80

### Steps to reproduce

1. Enable Smart Transactions from settings
2. Go to the test dapp
3. Trigger 2 transactions
4. Accept the first one
5. See how MM stays loading for several seconds without any user feedback, until the 1st tx is confirmed

### Error messages or log output

_No response_

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Prioritize routing to specific template confirmations, ahead of transactions and signatures confirmations, using the new `PRIORITY_APPROVAL_TEMPLATE_TYPES` constant.

Update the `ConfirmTransactionBase` component to route back to the `Home` component if a smart transaction status approval request is added and smart transactions are in use.

Note that the smart transaction status confirmation still includes the `Close extension` button despite this returning to the next queued transaction confirmation. This is a UX enhancement and can be addressed in an alternate PR.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25478?quickstart=1)

## **Related issues**

Fixes: #25415

## **Manual testing steps**

See issue.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js [hunk 1]
```diff
@@ -717,11 +732,8 @@ export default class ConfirmTransactionBase extends Component {
       ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
       fromInternalAccount,
       ///: END:ONLY_INCLUDE_IF
-      isSmartTransaction,
     } = this.props;
 
-    const hideLoadingIndicator = isSmartTransaction;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:723]: The `isSmartTransaction` property wasn't previously defined in the container so the spinner was always shown.

This still seems desirable as it means a spinner is briefly shown before redirecting to the status confirmation.

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js [hunk 2]
```diff
@@ -826,7 +838,7 @@ export default class ConfirmTransactionBase extends Component {
       toAddress,
       showCustodianDeepLink,
       clearConfirmTransaction,
-      isSmartTransactionsEnabled,
+      isSmartTransaction,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:841]: Given the `isSmartTransaction` property was already in the `PropTypes` and it feels a more accurate name given the many conditions included in addition to enablement, I've removed the duplicate `isSmartTransactionsEnabled`.

Comment (Manialimani) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:841]: Thanks

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js [hunk 3]
```diff
@@ -268,6 +273,11 @@ export default class ConfirmTransactionBase extends Component {
     ) {
       this.updateValueToMax();
     }
+
+    if (hasPriorityApprovalRequest && !prevHasPriorityApprovalRequest) {
+      // Redirect to home which will redirect to the priority confirmation.
+      history.push(mostRecentOverviewPage);
+    }
```
Comment (jpuri) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:280]: Can you stop the routing to this component in the first place for PriorityApprovalRequest so that we do not have to route back.

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js [hunk 4]
```diff
@@ -838,7 +845,7 @@ export default class ConfirmTransactionBase extends Component {
         txData.metadata.note = noteText;
       }
 
-      if (isSmartTransactionsEnabled) {
+      if (isSmartTransaction) {
         txData.origin += '#smartTransaction';
       }
```
Comment (jpuri) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:850]: Can we now get rid of `isSmartTransaction` related code from here ?

Comment (matthewwalsh0) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:850]: This is still needed by MMI, I've just used an existing variable with a more explicit name.

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js (hunk 3 above)
Comment (matthewwalsh0) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:280]: Unfortunately not, as the scenario in this bug is when you have two transactions queued, then accept one.

At this point, there is a small delay while the background prepares and submits the smart transaction, before creating the approval request that we can then redirect to.

But the spinner is shown throughout so it's not too jarring for the user.

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js [hunk 5]
```diff
@@ -343,13 +351,14 @@ const mapStateToProps = (state, ownProps) => {
     maxValue,
     smartTransactionsOptInStatus,
     currentChainSupportsSmartTransactions,
+    isSmartTransaction: getSmartTransactionsEnabled(state),
```
Comment (dan437) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js:354]: So, there is a slight difference between `getSmartTransactionsEnabled` and `getIsSmartTransaction`: https://github.com/MetaMask/metamask-extension/blob/develop/shared/modules/selectors/smart-transactions.ts#L121

You should likely do this: 
```
isSmartTransaction: getIsSmartTransaction(state)
```

File: ui/pages/home/home.component.js [hunk 6]
```diff
@@ -332,6 +335,8 @@ export default class Home extends PureComponent {
       history.push(BUILD_QUOTE_ROUTE);
     } else if (firstPermissionsRequestId) {
       history.push(`${CONNECT_ROUTE}/${firstPermissionsRequestId}`);
+    } else if (pendingConfirmationsPrioritized.length > 0) {
```
Comment (dan437) [inline ui/pages/home/home.component.js:338]: I've tried this branch locally and I can't see the STX status page if I do a dapp transaction on Sepolia or just a Send transaction. STX is enabled in Settings.

Comment (matthewwalsh0) [reply ui/pages/home/home.component.js:338]: I've just tested locally and encountered the same, after some debug it seems to be a remote issue since `state.metamask.smartTransactionsState?.liveness` is `false`.

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js (hunk 5 above)
Comment (matthewwalsh0) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js]: Since these changes aren't required for the fix, I've reverted the rename and just removed `isSmartTransaction` since it was never set and is no longer used.

**Comment by sleepytanya** [comment]
The issue with the spinner is fixed.
Points below are related to other bugs, I'm just making notes for visibility.
- User is still able to send STX while having Pending tx
- User can't  edit unapproved tx but it can be rejected. It takes the wallet to the STX screen and there is no way to close this screen until STX is completed.
- MM icon shows '...' instead of numbers


https://github.com/MetaMask/metamask-extension/assets/104780023/25822412-4b3e-4626-afbf-90219a579990


Screenshot 2024-06-25 at 20 32 10

File: ui/pages/home/home.component.js (hunk 6 above)
Comment (dan437) [reply ui/pages/home/home.component.js:338]: It looks like Sepolia was disabled for STX this week. Working with the team to enable it again for testing purposes. On Ethereum mainnet it works.

**Review by dan437 — APPROVED** [review]
It seems it's working on Ethereum Mainnet with and without STX. Great job!

**Review by pedronfigueiredo — APPROVED** [review]
