### PR TITLE
Convert token input to BigNumber to handle decimals better.

### LINKED ISSUE #12762: Decimals broken
**Describe the bug**
5.55 has precision errors

**Steps to reproduce (REQUIRED)**
Send a token using 5.55

**Expected behavior**
That shows 5.55

**Screenshots**
image

**Browser details (please complete the following information):**
 - OS: Windows
 - Hardware Wallet: no
 - Browser: Chrome latest
 - MetaMask Version: latest

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #12762

<strike>Adds a decimal length check for inputs and drops excess fractional part.</strike>

Convert token input to BigNumber to handle decimals.
Another edgecase not accounted for is when a token's decimal precision is 0 and attempting sending decimals will result in omitting the fractional part.

Manual testing steps:  
  - Note a token's decimal precision and initiate a transaction with that token, the amount having more fractional parts than the token precision.
  - For instance if a token's precision is `4` and setting the transaction amount to `0.12345` will omit the `5`.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

File: ui/components/ui/token-input/token-input.component.js [hunk 1]
```diff
@@ -80,8 +80,12 @@ export default class TokenInput extends PureComponent {
...
     let newDecimalValue = decimalValue;
 
-    if (decimals && applyDecimals) {
-      newDecimalValue = parseFloat(decimalValue).toFixed(decimals);
+    if (newDecimalValue.split('.').length > 1) {
+      const decimalsPlaces = newDecimalValue.split('.')[1].length;
+
+      if (decimals && applyDecimals && decimalsPlaces > decimals) {
+        newDecimalValue = parseFloat(decimalValue).toFixed(decimals);
+      }
```
Comment (jpuri) [inline ui/components/ui/token-input/token-input.component.js:88]: @tmashuang : could you replicate the issue and test fix with this PR. `hexValue` does not change input value it changes only value in transaction.

Comment (tmashuang) [reply ui/components/ui/token-input/token-input.component.js:88]: Does this test case clarify? https://github.com/MetaMask/metamask-extension/pull/12773/commits/cfe86346e419f8ec89c1c1f13b1cc798b52ed5fa

Comment (darkwing) [reply ui/components/ui/token-input/token-input.component.js:88]: Can we assign `newDecimalValue.split('.')` to a variable so we aren't doing it twice?

Comment (tmashuang) [reply ui/components/ui/token-input/token-input.component.js:90]: Done in 5bd45a4, lmk if you figure out a better var name 😅 e

**Review by danjm — APPROVED** [review]

**Review by mcmire — APPROVED** [review]
This makes sense to me. Thank you for doing this 🙇🏻
