### PR TITLE
fix: shield change payment method crypto don't show coverage footer cp-13.13.0

### LINKED ISSUE #38842: [Bug]: Shield crypto approval confirmation show not covered in change payment method confirmation screen
### Describe the bug

Current change payment method crypto to crypto transaction confirmation screen show not covered in shield footer since rule engine hasn't covered this yet

### Expected behavior

Should show covered or hide shield footer

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. subscribe to shield using crypto
2. change payment method to another crypto
3. confirmation screen shield footer coverage show not covered

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.13.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by tuna1207**
## **Description**

This PR hide shield coverage footer when user change payment method crypto to crypto transaction confirmation screen since currently rule engine doesn't cover this tx yet.
Also refactor `useEnableShieldCoverageChecks` to handle hide/show coverage footer

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38754?quickstart=1)

## **Changelog**

CHANGELOG entry: hide shield coverage footer in shield approval transaction

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38842

## **Manual testing steps**

1. Subscribe to shield with crypto
2. go to shield settings screen and change payment method to other crypto
3. shield approval confirmation screen should not show footer coverage indicator

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Hides the shield coverage footer for shield approval transactions and refactors visibility into `useEnableShieldCoverageChecks`, updating related components and tests.
> 
> - **Confirmations UI**
>   - **Hook `useEnableShieldCoverageChecks`**:
>     - Adds `isShowCoverageIndicator` derived from subscription status, basic functionality, and confirmation type; excludes `TransactionType.shieldSubscriptionApprove`.
>     - Continues to expose `isEnabled` and `isPaused`.
>   - **Footer `footer.tsx`**:
>     - Uses `isShowCoverageIndicator` to conditionally apply footer shadow.
>   - **`ShieldFooterCoverageIndicator`**:
>     - Renders based on `isShowCoverageIndicator`; removes local transaction-type checks; adjusts animation severity using `isPaused`.
> - **Tests**
>   - Update mocks to include `isShowCoverageIndicator` and switch to `renderHookWithConfirmContextProvider` helpers.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 3635dcc688cbf85754543a8f6dc41ac3fbe55b02. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/hooks/transactions/useEnableShieldCoverageChecks.ts [hunk 1]
```diff
@@ -20,8 +35,16 @@ export const useEnableShieldCoverageChecks = () => {
     return getIsShieldSubscriptionPaused(subscriptions);
   }, [subscriptions]);
 
+  const isEnabled = isBasicFunctionalityEnabled && isShieldSubscriptionActive;
+
+  const isShowCoverageIndicator =
+    (isEnabled || isShieldSubscriptionPaused) &&
```
Comment (lwin-kyaw) [inline ui/pages/confirmations/hooks/transactions/useEnableShieldCoverageChecks.ts:41]: Do we show the coverage status even f shield subscription is paused?

Comment (tuna1207) [reply ui/pages/confirmations/hooks/transactions/useEnableShieldCoverageChecks.ts:41]: yes, we show an alert that it's paused, not a coverage

Comment (lwin-kyaw) [reply ui/pages/confirmations/hooks/transactions/useEnableShieldCoverageChecks.ts:41]: Oki. Thank you.

**Review by lwin-kyaw — APPROVED** [review]
LGTM!

**Review by lionellbriones — APPROVED** [review]
