### PR TITLE
Fix for where fiat conversion does not persist when switching networks

### LINKED ISSUE #688: dApp does not remember currency settings
Just switched to Morder Testnet and played around. Whe i went back to the main net the currency setting had reverted to USD.

### PR DESCRIPTION
**Pull request by frankiebee**
fixes #688

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -22,7 +22,8 @@ module.exports = class MetamaskController {
     this.idStore.setStore(this.ethStore)
     this.messageManager = messageManager
     this.publicConfigStore = this.initPublicConfigStore()
-    this.configManager.setCurrentFiat('USD')
+    var currentFiat = this.configManager.getCurrentFiat() ? this.configManager.getCurrentFiat() : 'USD'
```
Comment (flyswatter) [inline app/scripts/metamask-controller.js]: Lines like this can be written more tersely without teranry operators, since any falsy value would be default to USD:
```
var currentFiat = this.configManager.getCurrentFiat() || 'USD'
```

**Comment by flyswatter** [comment]
Frankie back at it again!  I'm just waking up too, clearly we are both still very jetlagged.

I had a little readability nitpick, you can do it or just merge for now, but wanted to mention it b/c I've seen you use ternaries in a few places where this would work.
