### PR TITLE
fix: comparison fix for tron dest amount cp-13.11.0

### LINKED ISSUE #38271: [Bug]: Destination amount not showing for Tron swaps
### Describe the bug

In some cases, whenever user tries to swap their Tron assets, the destination amount is not being displayed even though a quote is returned. There are few other cases where even though the destination amount is returned, there’s no corresponding fiat value below it.

### Expected behavior

Destination amount should be displayed at all times whenever a quote is returned.

### Screenshots/Recordings

Image

### Steps to reproduce

1. Go to swaps
2. Select a tron swap
3. See destination amount not being displayed

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.11

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

When swapping Tron assets, the destination amount and fiat value were not displayed even when a valid quote was returned. This was caused by an address format mismatch in quote validation.
Root cause: The UI sometimes stores token addresses in CAIP-19 format (tron:728126428/trc20:TR7NHqje...) while the bridge API returns plain addresses (TR7NHqje...). The comparison in isQuoteExpiredOrInvalid failed, causing valid quotes to be incorrectly rejected.

Changes:
- Use formatAddressToCaipReference to normalize addresses before comparison
- Preserve case-sensitivity for non-EVM chains (base58 addresses)
- Fix || → ?? for valueInCurrency to handle edge cases

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38266?quickstart=1)

## **Changelog**

CHANGELOG entry: fixes tron quote display issue

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38271

## **Manual testing steps**

Tron → Tron swap (TRX → USDT)
1. Select Tron network, enter amount of TRX
2. Select USDT as destination token
3. Verify destination amount displays (not "0")
4. Verify fiat value displays below amount
Tron → Tron swap (USDT → TRX)
1. Reverse direction swap
2. Verify destination amount and fiat value display

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Fixes quote validation by normalizing CAIP/non-EVM addresses and ensures destination fiat amount uses nullish coalescing.
> 
> - **Quote validation (`ui/pages/bridge/utils/quote.ts`)**:
>   - Normalize destination asset addresses using `formatAddressToCaipReference` to compare CAIP-19 vs plain addresses.
>   - Preserve case for non-EVM chains; lowercase only for EVM before comparison.
>   - Compare CAIP chain IDs via `formatChainIdToCaip`; compute `addressMatch` and `chainMatch` to determine invalid quotes.
> - **UI (`ui/pages/bridge/prepare/prepare-bridge-page.tsx`)**:
>   - Use `??` for `amountInFiat` (`activeQuote?.toTokenAmount?.valueInCurrency ?? undefined`).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 8ca29b8a11b26488945da9f6dfaa03c722cf0e8d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/bridge/utils/quote.ts [hunk 1]
```diff
@@ -9,11 +9,32 @@ import type {
...
+): string => {
+  if (!addressOrAssetId) {
+    return '';
+  }
+  if (isCaipAssetType(addressOrAssetId)) {
+    return parseCaipAssetType(addressOrAssetId).assetReference;
+  }
+  return addressOrAssetId;
+};
+
```
Comment (micaelae) [inline ui/pages/bridge/utils/quote.ts]: We have a controller util `formatAddressToCaipReference` that does something similar. Can it handle this usecase?

Comment (ghgoodreau) [reply ui/pages/bridge/utils/quote.ts]: good catch, yes, just updated

**Review by micaelae — DISMISSED** [review]

**Review by micaelae — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]
