### PR TITLE
fix: potential undefined dereference of sessionProperties during Solana accountChanged flow

### LINKED ISSUE #33412: [Sentry] TypeError: Cannot read properties of undefined (reading 'solana_accountChanged_notifications')
Sentry Issue: [METAMASK-XK9T](https://metamask.sentry.io/issues/6617936203/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'solana_accountChanged_notifications')
  at MetamaskController.notifySolanaAccountChangedForCurrentAccount (app/scripts/metamask-controller.js:5724:26)
  at <anonymous> (app/scripts/metamask-controller.js:6359:18)
  at obj[prop] (/metamask/scripts/sentry-install.js:24:1)
```

### PR DESCRIPTION
**Pull request by jiexi**
## **Description**

Fixes a potential undefined dereference of `sessionProperties` during Solana accountChanged flow. We're unsure why this is happening as `sessionProperties` is a property that must exist on the `endowment:caip-25` permission, but we are seeing cases of this not being true from Sentry. This is likely caused by state corruption, but we do not have any state logs to confirm. This PR patches this by adding a safe optional chain to the dereference.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34643?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33412

## **Manual testing steps**
Honestly not that easy to test, but the change is simple enough that manual testing isn't needed.

1. Make a connection to https://metamask.github.io/test-dapp-multichain/latest/
1. Modify the `initialState` passed into `PermissionController` in `MetaMaskController` to have a `endowment:caip-25` permission without `sessionProperties` property for the multichain test dapp entry
2. Restart extension
3. Open background console
4. Visit the multichain test dapp again
5. See no errors like `TypeError: Cannot read properties of undefined (reading 'solana_accountChanged_notifications')`

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -6732,8 +6732,15 @@ export default class MetamaskController extends EventEmitter {
     if (!caip25Caveat) {
       return;
     }
+
+    // The optional chain operator below shouldn't be needed as
+    // the existence of sessionProperties is enforced by the caveat
+    // validator, but we are still seeing some instances where it
+    // isn't defined in production. This suggests state corruption,
+    // but we can't find definitive proof that. For now we are using
+    // this patch which is harmless and silences the error in Sentry.
```
Comment (adonesky1) [inline app/scripts/metamask-controller.js]: [nit] could we reference the sentry issue
```suggestion
    // The optional chain operator below shouldn't be needed as
    // the existence of sessionProperties is enforced by the caveat
    // validator, but we are still seeing some instances where it
    // isn't defined in production:
    // https://github.com/MetaMask/metamask-extension/issues/33412 
    // This suggests state corruption, but we can't find definitive proof that. 
    // For now we are using this patch which is harmless and silences the error in Sentry.
```

**Review by adonesky1 — DISMISSED** [review]
one nit otherwise LGTM

**Review by adonesky1 — APPROVED** [review]

**Review by ffmcgee725 — APPROVED** [review]
