### PR TITLE
fix grid repositioning on label change

### LINKED ISSUE #8687: Settings > Alerts toggles grid shifting
Issue with grid layout shifting on Alerts page when toggling multiple ON/OFF switches

<details>
<summary>Alerts page grid toggle shifting</summary>

</details>

### PR DESCRIPTION
**Pull request by brad-decker**
resolves #8687 

Takes advantage of visibility: hidden/visible which does not remove the space the element takes up on the screen from the dom... as well as a single column/row grid to overlap both off/on labels in the toggle button. I'm not used to BEM syntax so I'm sure the class naming could use some work. 

This works for the alert screen because max-content will include visibility: hidden items. 

For this demo i modified the HTML content to a longer off statement: 
<details>
<summary>Mixed toggles</summary>

</details>
	
<details>
<summary>Both on</summary>

</details>

### CODE REVIEW

**Comment by Gudahtt** [comment]
This seems promising!

File: ui/app/components/ui/toggle-button/toggle-button.component.js [hunk 1]
```diff
@@ -60,7 +60,10 @@ const ToggleButton = (props) => {
         thumbAnimateRange={[3, 18]}
         colors={colors}
       />
-      <div className="toggle-button__status-label">{ value ? onLabel : offLabel }</div>
+      <div className="toggle-button__status-container">
+        <span className="toggle-button__status-label toggle-button__status-label--off">{offLabel}</span>
```
Comment (brad-decker) [inline ui/app/components/ui/toggle-button/toggle-button.component.js:64]: I could probably greatly reduce the complexity of this by...
1. `__status-container` -> `__status`
2. `__status-label __status-label--off` -> `__off-label` (and `__on-label`) respectively

in this way the modifier is only at the top level instead of there being two modifiers. it's definitely incorrect now and needs to change. Let me know your thoughts as you review.

Comment (Gudahtt) [reply ui/app/components/ui/toggle-button/toggle-button.component.js:64]: That suggestion seems pretty reasonable to me

File: ui/app/components/ui/toggle-button/index.scss [hunk 2]
```diff
@@ -1,7 +1,8 @@
 .toggle-button {
   display: flex;
+  $self: &;
```
Comment (Gudahtt) [inline ui/app/components/ui/toggle-button/index.scss:3]: Huh... I didn't know you could assign `&` to a variable! That's neat.

**Review by Gudahtt — APPROVED** [review]
LGTM!
