### PR TITLE
fix: Token details should not display zero balance for tokens without marketData

### LINKED ISSUE #29244: [Bug]: $0 balance amount not shown on some assets in Extension asset list
### Describe the bug

Some assets with $0 balance in the token details page don't show the $0 balance line in the main extension assets view

### Expected behavior

Given: I am viewing the extension main asset view
When: I tokens have a $0 balance
Then: I want to see the $0 line appear in the asset list

### Screenshots/Recordings

Image
Image

### Steps to reproduce

This only happens with some tokens so not sure how to reproduce. See screenshot for token examples 

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

On main asset list, if a token doesn't have marketData, we do not display the fiat value. On tokenDetails we were falling back to zero balance (this is incorrect)

This PR adds a fix to not fallback to zero balance, and to instead simply omit the value.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29299?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/29244

## **Manual testing steps**

1. Add a memcoin without marketData
2. Validate that no fiat value is shown on main asset list
3. Validate that no fiat value is shown on token details (should not display zero value)
4. Ensure nothing results in `NaN` value.

### **Before**

Screenshot 2024-12-17 at 1 39 10 PM

Screenshot 2024-12-17 at 1 39 26 PM

### **After**

Screenshot 2024-12-17 at 1 34 09 PM

Screenshot 2024-12-17 at 1 34 26 PM

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/wallet-overview/coin-buttons.tsx [hunk 1]
```diff
@@ -332,6 +332,7 @@ const CoinButtons = ({
   const setCorrectChain = useCallback(async () => {
     if (currentChainId !== chainId) {
       try {
+        throw new Error('test error');
```
Comment (bergeron) [inline ui/components/app/wallet-overview/coin-buttons.tsx:335]: delete?

**Comment by bergeron** [comment]
I was trying to follow testing steps, but for some reason I'm seeing $0.00 on the main token list  🤔

Screenshot 2024-12-17 at 2 29 40 PM

File: ui/components/app/wallet-overview/coin-buttons.tsx (hunk 1 above)
Comment (gambinish) [reply ui/components/app/wallet-overview/coin-buttons.tsx:335]: oops. yep

Comment (gambinish) [reply ui/components/app/wallet-overview/coin-buttons.tsx]: https://github.com/MetaMask/metamask-extension/pull/29299/commits/4823423b5b3ae93106aeffd0e5890ab18af8cae3

**Review by salimtb — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
