### PR TITLE
fix: Add origin pill to wallet_addEthereumChain confirmation

### LINKED ISSUE #26656: [Bug]: Lack of origin display on wallet_addEthereumChain
### Describe the bug

Fix https://github.com/MetaMask/MetaMask-planning/issues/3471

todo add details to address fix 

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Open https://pkeshkamat.github.io/poc15 in a browser with the MetaMask extension installed.
2. Within 5 seconds, switch to another tab, for example, https://www.gnosis.io/.
3. The addEthereumChain request will appear as though it came from gnosis.io

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.0.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Adds Origin Pill component and references it on the confirmation template.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29317?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26656

## **Manual testing steps**

1. Go to the test dApp
2. Add a custom chain

### **After**

Screenshot 2024-12-18 at 12 08 31
Screenshot 2024-12-18 at 11 58 38

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/metamask-template-renderer/safe-component-list.js [hunk 1]
```diff
@@ -86,6 +87,7 @@ export const safeComponentList = {
   Typography,
   SmartTransactionStatusPage,
   UrlIcon,
+  OriginPill,
```
Comment (matthewwalsh0) [inline ui/components/app/metamask-template-renderer/safe-component-list.js:90]: You can see the moment we lost our beautiful alphabetical order 😄

File: ui/components/ui/origin-pill/origin-pill.js
Comment (matthewwalsh0) [inline ui/components/ui/origin-pill/origin-pill.js:1]: Does this not already exist elsewhere that we can reuse, or is it part of another component?

Comment (matthewwalsh0) [inline ui/components/ui/origin-pill/origin-pill.js:1]: TypeScript for all new components?

File: ui/components/ui/origin-pill/origin-pill.test.js [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+      dataTestId: 'test-data-test-id',
+    };
+
+    const store = configureMockStore()(mockState);
+    const { container } = renderWithProvider(
+      <OriginPill {...defaultProps} />,
+      store,
+    );
+
+    expect(container).toMatchSnapshot();
```
Comment (matthewwalsh0) [inline ui/components/ui/origin-pill/origin-pill.test.js:20]: Did we say we were going to avoid adding new snapshot tests?

Could we verify just the text itself for example?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/components/app/metamask-template-renderer/safe-component-list.js (hunk 1 above)
Comment (pedronfigueiredo) [reply ui/components/app/metamask-template-renderer/safe-component-list.js]: Reordered!

File: ui/components/ui/origin-pill/origin-pill.js
Comment (pedronfigueiredo) [reply ui/components/ui/origin-pill/origin-pill.js:1]: This does not exist in this configuration. UrlIcon with a Text component exists elsewhere but it's not wrapped in its own component and has been deprecated.

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Review by jpuri — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
