### PR TITLE
fix: `wallet_addEthereumChain` does not attach a `result` under certain conditions

### LINKED ISSUE #26706: [Bug]: Dapp Connect - Triggering a dapp connection displays wrong screen and cannot connect.
### Describe the bug

Triggering a dapp connection displays wrong screen and cannot connect.
 The pending requests remain in MM indicator but cannot clear them.
The behaviour happens consistently, if I refresh the dapp and try again. The requests keep adding up in the indicator, but cannot connect nor clear them.
No errors in the console.

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot from 2024-08-28 12-45-58

https://github.com/user-attachments/assets/77afd5b9-9412-4350-9268-dbfe0157c662

### Steps to reproduce

1. Go to Chainlist https://chainlist.org/?testnets=true&search=blast
2. Import Blast
3. Accept
4. Switch networks
5. Click Import again
6. See error in the console `inpage.js:1 MetaMask - RPC Error: JsonRpcEngine: Response has no error or result for request:` 
7. Go to a dapp and try to connect https://faucet.quicknode.com/blast/sepolia
8. I saw the above screen

### Error messages or log output

_No response_

### Detection stage

In beta

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by adonesky1**
## **Description**

Fix issue where `wallet_addEthereumChain` does not attach a result to the response object when the currently selected rpcUrl matches the request.

This would cause the request to get "stuck" in the `QueuedRequestController` queue, preventing the queue from progressing and causing confusing behavior.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26726?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26706

## **Manual testing steps**

1. Go to https://chainlist.org/?chain=56&search=blast
2. Connect the wallet and add Blast Mainnet 
(For other chains it appears Chainlist cycles to the next rpcUrl you don't have which avoids this bug, so use Blast)
3. After successfully adding the network, attempt to add Blast again. Nothing should happen.
4. Then go to https://faucet.quicknode.com/blast/sepolia (or any dapp where your wallet isn't already connected) and attempt to connect
5. You should be able to connect as usual

### **Before**

https://github.com/user-attachments/assets/b997027f-1c62-4279-87c6-0fe70989abb3

### **After**

https://github.com/user-attachments/assets/08307a88-8f6f-44cd-9b75-877aadb1805a

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This change looks correct to me, but I am curious how it might have caused this problem. Wouldn't `end()` have triggered the `QueuedRequestController` to consider this as resolved? Why do we need `result` to be set for it to be resolved there.

**Comment by adonesky1** [comment]
> This change looks correct to me, but I am curious how it might have caused this problem. Wouldn't end() have triggered the QueuedRequestController to consider this as resolved? Why do we need result to be set for it to be resolved there.

I would have thought so too... which is certainly why this bug was introduced and unnoticed. And even when debugging I stared at it for a while thinking this should resolve the request. But apparently the rpc engine needs a result if an error is not specified in the end function... something to probably look into modifying in the JSON RPC Engine

**Comment by Gudahtt** [comment]
Oh I see, I recall that now. Makes sense.

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Comment by adonesky1** [comment]
seems like the chrome e2e test failure might relate to these brownouts? All the tests seem to be passing...

Screenshot 2024-08-28 at 1 55 50 PM

File: app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js [hunk 1]
```diff
@@ -139,6 +139,7 @@ async function addEthereumChainHandler(
       currentChainIdForDomain === chainId &&
       currentRpcUrl === firstValidRPCUrl
     ) {
+      res.result = null;
```
Comment (FrederikBolding) [inline app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js:142]: Not a blocker, but curious how the JsonRpcEngine didn't end up throwing for this. AFAIK if we process all middlewares without a result we end up throwing an error?

**Comment by Gudahtt** [comment]
Possibly; the initial failure is one we've always seen occasionally on CircleCI. The "Rerun failed tests" button always fails unless test artifacts have been uploaded during the failed run, so "Rerun failed workflows" needs to be used instead. I've just triggered that.

File: app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js (hunk 1 above)
Comment (Gudahtt) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js:142]: It did throw an error in this case, and it was returned to the dapp. But the QueuedRequestController missed it for some reason.

But yeah, good point, how was this missed 🤔

Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js:142]: It actually did throw an error to the dapp as you can see in the after video

Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js:142]: > But the QueuedRequestController missed it for some reason.

Yeah... we should investigate this. I can create a ticket

Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js:142]: https://app.zenhub.com/workspaces/wallet-api-platform-63bee08a4e3b9d001108416e/issues/gh/metamask/metamask-planning/3096

File: app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js [hunk 2]
```diff
@@ -541,4 +542,42 @@ describe('addEthereumChainHandler', () => {
       }),
     );
   });
+
+  it('should add result set to null to response object if the requested rpcUrl (and chainId) is currently selected', async () => {
+    jest.spyOn(chainUtils, 'findExistingNetwork').mockReturnValue({
+      chainId: '0x1',
+      rpcUrl: 'https://mainnet.infura.io/v3/',
+      ticker: 'ETH',
+    });
```
Comment (jiexi) [inline app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js:551]: guessing you can just modify the `findNetworkConfigurationBy` mock result because `findExistingNetwork` also checks the built in networks constant?

if so, can we modify this test to use a non-built-in network instead?

Comment (jiexi) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js:551]: if it was clear, this is a nit and totally ignorable. I'm mainly asking so we can avoid having to import and mock chainutils

**Review by jiexi — DISMISSED** [review]
approving to avoid being a blocker. feel free to ignore nit

File: app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js (hunk 2 above)
Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js]: addressed here: https://github.com/MetaMask/metamask-extension/pull/26726/commits/4c9364078ea8975b1a02189a36559b78eceaf23e

**Review by jiexi — DISMISSED** [review]

**Review by Gudahtt — DISMISSED** [review]

**Review by Gudahtt — APPROVED** [review]

**Review by jiexi — APPROVED** [review]
