### PR TITLE
fix: reset prefilled dest token when reopening Swap page cp-13.0.0

### LINKED ISSUE #34484: [Bug]: Pre-filled dest token persists after reopening Swap page
### Describe the bug

The Swap dest token is prefilled the first time the page loads, but is not pre-filled with the correct token the next time the user navigates to the Swap page.

### Expected behavior

The dest token should be set to the src network's default token

### Screenshots/Recordings

https://github.com/user-attachments/assets/fe2b2c73-2d93-4538-a361-1edbddfaf77c

### Steps to reproduce

1. Enable ethereum and BSC
2. Click eth:ETH then Swap
3. Note selected tokens
4. Click back button
5. Click bsc:USDC then Swap
6. Destination token is not set to BSC's default dest token

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

Changes
- move default toToken hook logic to the bridge selectors so it evaluates each time the page loads
- minor: undo gasless label change to fix text wrapping issues in the quote card

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34485?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34484

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/ducks/bridge/bridge.ts [hunk 1]
```diff
@@ -80,23 +75,6 @@ const getTokenImage = (payload: TokenPayload['payload']) => {
...
 };
 
-export const toBridgeToken = (
-  payload: TokenPayload['payload'],
-): BridgeToken | null => {
-  if (!payload) {
-    return null;
-  }
-  const caipChainId = formatChainIdToCaip(payload.chainId);
-  return {
```
Comment (micaelae) [inline ui/ducks/bridge/bridge.ts:90]: moved this to the bridge/utils file

File: ui/ducks/bridge/utils.ts [hunk 2]
```diff
@@ -192,3 +197,73 @@ export const isNetworkAdded = (
...
+  const commonPair =
+    BRIDGE_CHAINID_COMMON_TOKEN_PAIR[
+      targetChainId as keyof typeof BRIDGE_CHAINID_COMMON_TOKEN_PAIR
+    ];
+
+  if (commonPair) {
+    // If source is native token, default to USDC on same chain
+    if (isNativeAddress(fromToken.address)) {
+      return createBridgeTokenPayload(commonPair, targetChainId);
+    }
```
Comment (micaelae) [inline ui/ducks/bridge/utils.ts:275]: copied from old `useBridgeDefaultToToken` hook. the default token will be returned by getToToken before any hooks can override the toToken

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx [hunk 3]
```diff
@@ -362,35 +359,6 @@ const PrepareBridgePage = () => {
...
-  useEffect(() => {
-    // If there's an active quote, assume that the user is returning to the page
-    if (activeQuote) {
-      // Get input data from active quote
-      const { srcAsset, destAsset, destChainId, srcChainId } =
-        activeQuote.quote;
-
-      if (srcAsset && destAsset && destChainId) {
-        // Set inputs to values from active quote
-        dispatch(setToChainId(destChainId));
```
Comment (micaelae) [inline ui/pages/bridge/prepare/prepare-bridge-page.tsx:374]: combined this with another useEffect that runs on page load

File: ui/pages/bridge/prepare/prepare-bridge-page.tsx [hunk 4]
```diff
@@ -556,59 +527,37 @@ const PrepareBridgePage = () => {
       name: isSwap ? TraceName.SwapViewLoaded : TraceName.BridgeViewLoaded,
       timestamp: Date.now(),
     });
-  }, []);
 
-  const { defaultToChainId, defaultToToken } = useBridgeDefaultToToken();
-
-  // Track whether defaults have been applied separately for chain and token
-  const [defaultChainApplied, setDefaultChainApplied] = useState(false);
-  const [defaultTokenApplied, setDefaultTokenApplied] = useState(false);
```
Comment (micaelae) [inline ui/pages/bridge/prepare/prepare-bridge-page.tsx:565]: refactored this logic and the 2 useEffects to be evaluated in the `getToToken` and `getToChain` selectors, which accomplishes the same thing but earlier in the component lifecycle

**Review by ghgoodreau — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]
