### PR TITLE
Convert transaction activity conversion's currency to ETH

### LINKED ISSUE #8933: Issue with TransactionActivityLog on custom rpc networks
**Describe the bug**
When the `nativeCurrency` is set to anything other than `ETH`/`GWEI`/`ETH` the TransactionActivityLog will error with `t is not a function`. 
[Sentry report](https://sentry.io/organizations/metamask/issues/1098542288/?project=273505&query=is%3Aunresolved+t+is+not+a+function&statsPeriod=14d). 
Stackish trace  [TransactionActivityLog ](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/app/transaction-activity-log/transaction-activity-log.component.js#L82-L87) -> [getEthConversionFromWeiHex](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/helpers/utils/conversions.util.js#L23-L45) [(problem line)](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/helpers/utils/conversions.util.js#L35) -> [toSpecifiedDenomination](https://github.com/MetaMask/metamask-extension/blob/a78cf0ef3a463c5d9d56453e2f777e08cc2dcce7/ui/app/helpers/utils/conversion-util.js#L52)

**To Reproduce (REQUIRED)**

1. Set a Custom RPC network (ETC/xDai/etc)

- ETC - https://www.ethercluster.com/etc // chainid - 61
- xDai - https://xdai.poanetwork.dev // chainid - 100

2. Send a tx
3. Click the tx-list-item to show the tx-details that has the activity log

**Screenshot**
<details>
<summary>Error Gif</summary>

</details>

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #8933 where custom fromCurrency would crash the convertion utility and the UI.

This fixes in the mean time, but there still a separate issue with the nativeCurrency persisting in the background, it will reset to ETH upon background refresh.

See issue for before gif
<details>
<summary>Fix After Gif</summary>

</details>

### CODE REVIEW

File: ui/app/components/app/transaction-activity-log/transaction-activity-log.component.js [hunk 1]
```diff
@@ -71,20 +71,13 @@ export default class TransactionActivityLog extends PureComponent {
...
     const { eventKey, value, timestamp, hash } = activity
-    const ethValue = index === 0
-      ? `${getValueFromWeiHex({
-        value,
-        fromCurrency: nativeCurrency,
-        toCurrency: nativeCurrency,
-        conversionRate,
-        numberOfDecimals: 6,
-      })} ${nativeCurrency}`
-      : getEthConversionFromWeiHex({
```
Comment (Gudahtt) [inline ui/app/components/app/transaction-activity-log/transaction-activity-log.component.js:82]: Why remove this condition? Now all of the activity log entries are shown in GWEI instead of ETH.

I don't really understand the decision to show ETH for the first one and GWEI for the rest, but best to keep design changes separate from the bug fix either way. Swapping out `nativeCurrency` for `ETH` in both of these `getValueFromWeiHex` calls seems to fix the problem.

**Review by Gudahtt — APPROVED** [review]
LGTM!

I noticed we're passing in `nativeCurrency` as `fromCurrency` or `toCurrency` in other places as well, so similar bugs may still exist elsewhere.
