### PR TITLE
[FLASK] Fix key management permission copy

### LINKED ISSUE #14429: Fix key management permission checkbox prompt copy
We should fix the following copy issues in the below screenshot:

- "check all" should only be displayed if there are multiple checkboxes on display in the prompt
  - In other words, we should have one message with "check all" and one without, and conditionally use them.
  - We may also want to consider rewording it to "check all boxes". "check all" comes across as weird / ungrammatical to me.
- The long-form warning text should reiterate which protocol's keys are being exposed so that the user is not made to wonder about this.

image (6)

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## Explanation

* Add possibility to add multiple checkboxes to the modal

* Singularize copy if there is only one check box

* Add protocol name in message

## More Informations

* Fixes #14429

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js [hunk 1]
```diff
@@ -37,15 +38,19 @@ export default function SnapInstall({
...
-          ),
-      ),
-    [request.permissions],
+  const findBip44EntropyPermission =
+    request.permissions &&
+    Object.keys(request.permissions).find((v) =>
+      v.startsWith('snap_getBip44Entropy_'),
+    );
+
+  const shouldShowWarning = useMemo(() => Boolean(findBip44EntropyPermission), [
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/flask/snap-install/snap-install.js:47]: Does this need `useMemo`? These operations shouldn't be that expensive, but I am not aware of the standards for the MM extension in general.

File: app/_locales/en/messages.json [hunk 2]
```diff
@@ -2966,11 +2966,14 @@
...
+    "message": "To confirm you understand, check the box."
+  },
+  "snapInstallWarningCheckPlural": {
+    "message": "To confirm you understand, check all the boxes."
   },
   "snapInstallWarningKeyAccess": {
-    "message": "You are granting key access to the snap \"$1\". This is irrevocable and grants \"$1\" control of your accounts and assets. Make sure you trust \"$1\" before proceeding.",
-    "description": "The parameter is the name of the snap"
+    "message": "You are granting $2 key access to the snap \"$1\". This is irrevocable and grants \"$1\" control of your $2 accounts and assets. Make sure you trust \"$1\" before proceeding.",
+    "description": "The first parameter is the name of the snap and the second one is the protocol"
```
Comment (FrederikBolding) [inline app/_locales/en/messages.json:2976]: Do we need to remove the localized versions of this message since you've changed the parameters? Otherwise the localized messages will be outdated.

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js [hunk 3]
```diff
@@ -37,15 +38,19 @@ export default function SnapInstall({
...
-  const shouldShowWarning = useMemo(
-    () =>
-      Boolean(
-        request.permissions &&
-          Object.keys(request.permissions).find((v) =>
-            v.startsWith('snap_getBip44Entropy_'),
-          ),
-      ),
-    [request.permissions],
+  const findBip44EntropyPermission =
```
[the remark this answers is not in the document]
Comment (GuillaumeRx) [reply ui/pages/permissions-connect/flask/snap-install/snap-install.js:41]: I assumed it wasn't in the scope of this PR, and wanted to avoid breaking too much things. If you want I can do it in this PR.

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js (hunk 1 above)
Comment (GuillaumeRx) [reply ui/pages/permissions-connect/flask/snap-install/snap-install.js:47]: It was already like this before, I don't know why it's using a memorised value.

Comment (FrederikBolding) [reply ui/pages/permissions-connect/flask/snap-install/snap-install.js:47]: Okay, I don't see a reason for it to be memoized though.

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (FrederikBolding) [reply ui/pages/permissions-connect/flask/snap-install/snap-install.js:41]: I think it would be fine to add to this PR 👍

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js [hunk 4]
```diff
@@ -37,17 +38,19 @@ export default function SnapInstall({
...
-      ),
-    [request.permissions],
+  const bip44EntropyPermissions =
+    request.permissions &&
+    Object.keys(request.permissions).filter((v) =>
+      v.startsWith('snap_getBip44Entropy_'),
+    );
+
+  const shouldShowWarning = Boolean(
+    bip44EntropyPermissions && bip44EntropyPermissions.length,
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/flask/snap-install/snap-install.js:48]: Would it be clearer if this was `bip44EntropyPermissions.length > 0`?

File: ui/components/app/flask/snap-install-warning/index.scss [hunk 5]
```diff
@@ -5,6 +5,7 @@
     display: flex;
     align-items: flex-start;
     gap: 0 16px;
+    margin-bottom: 16px;
```
Comment (FrederikBolding) [inline ui/components/app/flask/snap-install-warning/index.scss:8]: Is this needed when having just one warning?

File: ui/components/app/flask/snap-install-warning/snap-install-warning.js [hunk 6]
```diff
@@ -1,20 +1,41 @@
...
 
-export default function SnapInstallWarning({ onCancel, onSubmit, snapName }) {
+/**
+ * a very simple reducer using produce from Immer to keep checkboxes state manipulation
+ * immutable and painless.
+ */
+const checkboxStateReducer = produce((state, action) => {
+  switch (action.type) {
+    case 'check':
+      state[action.checkboxId] = state[action.checkboxId]
```
Comment (FrederikBolding) [inline ui/components/app/flask/snap-install-warning/snap-install-warning.js:18]: Not sure if cleaner, but `!state[action.checkboxId]` should be enough here?

**Review by FrederikBolding — DISMISSED** [review]

File: ui/components/app/flask/snap-install-warning/snap-install-warning.js (hunk 6 above)
Comment (GuillaumeRx) [reply ui/components/app/flask/snap-install-warning/snap-install-warning.js:18]: state[action.checkboxId] can be undefined, I don't think it will work in this case

Comment (FrederikBolding) [reply ui/components/app/flask/snap-install-warning/snap-install-warning.js:18]: `!undefined === true`
`!null === true`

File: ui/components/app/flask/snap-install-warning/index.scss (hunk 5 above)
Comment (GuillaumeRx) [reply ui/components/app/flask/snap-install-warning/index.scss:8]: Nope, changing that

**Review by FrederikBolding — DISMISSED** [review]

**Review by FrederikBolding — DISMISSED** [review]

**Review by darkwing — DISMISSED** [review]

**Review by FrederikBolding — DISMISSED** [review]

File: app/_locales/en/messages.json [hunk 7]
```diff
@@ -2975,11 +2975,14 @@
     "message": "Install Snap"
   },
   "snapInstallWarningCheck": {
-    "message": "To confirm you understand, check all."
+    "message": "To confirm you understand, check the box."
+  },
+  "snapInstallWarningCheckPlural": {
+    "message": "To confirm you understand, check all the boxes."
```
Comment (rekmarks) [inline app/_locales/en/messages.json:2981]:
```suggestion
    "message": "To confirm that you understand, check the box."
  },
  "snapInstallWarningCheckPlural": {
    "message": "To confirm that you understand, check all the boxes."
```

**Review by rekmarks — DISMISSED** [review]
Small copy change.

**Review by FrederikBolding — DISMISSED** [review]

File: ui/components/app/flask/snap-install-warning/index.scss [hunk 8]
```diff
@@ -5,6 +5,10 @@
     display: flex;
     align-items: flex-start;
     gap: 0 16px;
+
+    &:nth-child(n+3) {
```
Comment (darkwing) [inline ui/components/app/flask/snap-install-warning/index.scss:9]: Can we use a `className`  here instead?  How sure are we that `n+3` is always going to be this element?  If we need to keep this, I'd love a comment as to what this element represents.

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js [hunk 9]
```diff
@@ -128,7 +130,14 @@ export default function SnapInstall({
         <SnapInstallWarning
           onCancel={() => setIsShowingWarning(false)}
           onSubmit={onSubmit}
-          snapName={targetSubjectMetadata.name}
+          warnings={bip44EntropyPermissions.map((permission, i) => ({
+            id: `key-access-${i}`,
+            message: t('snapInstallWarningKeyAccess', [
+              targetSubjectMetadata.name,
+              coinTypeToProtocolName(getCoinType(permission)) ||
+                `${getCoinType(permission)} (Unrecognized protocol)`,
```
[the remark this answers is not in the document]
Comment (GuillaumeRx) [reply ui/pages/permissions-connect/flask/snap-install/snap-install.js:138]: Yes, will add :)

File: app/_locales/en/messages.json [hunk 10]
```diff
@@ -3043,11 +3043,14 @@
     "message": "Install Snap"
   },
   "snapInstallWarningCheck": {
-    "message": "To confirm you understand, check all."
+    "message": "To confirm you understand, check the box."
+  },
+  "snapInstallWarningCheckPlural": {
+    "message": "To confirm that you understand, check the box."
```
Comment (FrederikBolding) [inline app/_locales/en/messages.json:3049]: Ì think you might have had a regression in the copy here with all the rebases?

**Review by FrederikBolding — CHANGES_REQUESTED** [review]

File: app/_locales/en/messages.json (hunk 10 above)
Comment (FrederikBolding) [reply app/_locales/en/messages.json:3049]: Otherwise this should be good to go finally.

Comment (GuillaumeRx) [reply app/_locales/en/messages.json]: Fixed :) This might have regressed because of the merge fail I had couple of days ago

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js [hunk 11]
```diff
@@ -128,7 +130,14 @@ export default function SnapInstall({
         <SnapInstallWarning
           onCancel={() => setIsShowingWarning(false)}
           onSubmit={onSubmit}
-          snapName={targetSubjectMetadata.name}
+          warnings={bip44EntropyPermissions.map((permission, i) => ({
+            id: `key-access-${i}`,
+            message: t('snapInstallWarningKeyAccess', [
+              targetSubjectMetadata.name,
+              coinTypeToProtocolName(getCoinType(permission)) ||
```
Comment (darkwing) [inline ui/pages/permissions-connect/flask/snap-install/snap-install.js:137]: We're calling `getCoinType(permission)` twice, could probably just be a var

File: ui/pages/permissions-connect/flask/snap-install/snap-install.js [hunk 12]
```diff
@@ -37,16 +38,17 @@ export default function SnapInstall({
...
-    [request.permissions],
-  );
+  const bip44EntropyPermissions =
+    request.permissions &&
+    Object.keys(request.permissions).filter((v) =>
+      v.startsWith('snap_getBip44Entropy_'),
+    );
+
+  const shouldShowWarning =
+    bip44EntropyPermissions && bip44EntropyPermissions.length > 0;
```
Comment (darkwing) [inline ui/pages/permissions-connect/flask/snap-install/snap-install.js:48]: I think this could be `bip44EntropyPermissions?.length > 0`

**Review by darkwing — CHANGES_REQUESTED** [review]
Two tiny nits

**Review by FrederikBolding — DISMISSED** [review]

**Review by darkwing — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]
