### PR TITLE
fix: issue where queued request counts were not included in logic to reroute from home screen and close notification

### LINKED ISSUE #25412: [Bug]: Multichain - The MM popup keeps opening and closing in an infinite loop when I had a ledger tx unapproved, trigger another tx from another dapp and account and then approve the ledger one
### Describe the bug

I had a ledger account connected to dapp 1 (linea sepolia) and a regular MM account connected to dapp 2 (mainnet).
Whenever I trigger a ledger tx and leave it unapproved, if then I trigger a tx from dapp 2, and Accept the first ledger tx (on MM), MM starts opening and closing the popup indefinelty.

This is similar to this [other issue](https://github.com/MetaMask/metamask-extension/issues/25408), but it has different repro steps, hence it's a separate ticket, though it might have the same fix.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/0234d3f9-3ac4-45c4-a614-27ffb6e96bfd

### Steps to reproduce

1. Import a ledger account
2. Connect ledger account to dapp 1 with linea sepolia
3. Connect a MM account to dapp 2 with mainnet
4. Trigger a tx from dapp 1 with ledger
5. Trigger a tx from dapp 2 with MM account
6. Confirm tx 1
7. See MM keeps opening and closing the popup indefinetly

### Error messages or log output

_No response_

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by adonesky1**
## **Description**

We introduced logic to add queued requests (pending requests not yet in the `ApprovalController`) [to the trayIcon badge number](https://github.com/MetaMask/metamask-extension/blob/b8bd980b1c47b64f855cc599d1ee8ef3e961edcd/app/scripts/background.js#L853), but failed to account for these requests in two other crucial spots:
- [Where we determine whether to reroute the homescreen for a pending transaction](https://github.com/MetaMask/metamask-extension/blob/b8bd980b1c47b64f855cc599d1ee8ef3e961edcd/ui/pages/home/home.component.js#L331)
- [Where we determine whether to close the notification](https://github.com/MetaMask/metamask-extension/blob/b8bd980b1c47b64f855cc599d1ee8ef3e961edcd/ui/pages/home/home.component.js#L102)

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25454?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25412
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/2677

## **Manual testing steps**

1. Import a ledger account
2. Connect ledger account to dapp 1 with sepolia (or any network)
3. Connect a MM account to dapp 2 with mainnet (or any network)
4. Trigger a tx from dapp 1 with ledger
5. Trigger a tx from dapp 2 with MM account
6. Confirm tx 1
7.  You should see a loading screen in the pop up waiting for you to confirm on your hardware wallet
8. Confirm in your hardware wallet
9. You should now see the transaction from dapp 2 on mainnet

### **Before**

https://github.com/MetaMask/metamask-extension/assets/34557516/ede5873c-18a8-45d3-8f38-ba10df496d2b

### **After**

https://github.com/MetaMask/metamask-extension/assets/34557516/879074b4-a028-4c9e-9a88-ba23603e032a

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jiexi** [comment]
Verified that this resolves the issue for me

File: ui/selectors/transactions.js [hunk 1]
```diff
@@ -643,8 +627,12 @@ const TRANSACTION_APPROVAL_TYPES = [
 ];
 
 export function hasTransactionPendingApprovals(state) {
+  const unapprovedTxRequests = getApprovalRequestsByType(
+    state,
+    ApprovalType.Transaction,
+  );
   return (
-    hasUnapprovedTransactionsInCurrentNetwork(state) ||
+    unapprovedTxRequests.length > 0 ||
```
Comment (adonesky1) [inline ui/selectors/transactions.js:635]: since we queue requests on different dapps which can be on different networks now we don't want to restrict this boolean check to only transactions that match the currently selected network. I'm not actually sure how there could have been pending transactions on different networks previously that necessitated this check 🤔... but I might be forgetting something

**Review by jiexi — DISMISSED** [review]

**Review by shanejonas — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
