### PR TITLE
Using parsed seed phrase for restore vault input validation

### LINKED ISSUE #12225: Odd behavior around newlines when importing seed phrase
**Describe the bug**
I was playing around with the "Restore your Account" screen today and noticed some odd behavior around newlines in the text box.  If you enter a space in front of the first word after a newline, it takes 2 backspaces to go back to a valid seed.  There's some kind of extra character being injected here.

**Steps to reproduce (REQUIRED)**
1. Paste a valid seed phrase into the text box (selecting "show secret recovery phrase" so you can see what you're doing).
2. put your cursor to the left of the first word after the newline
3. press space
4. press backspace.

Expected behavior: Seed phrase should be valid again
Actual behavior: Seed phrase remains invalid until backspace is pressed again.

**Screenshots**
https://user-images.githubusercontent.com/11167066/134999334-d478968f-a462-421f-bd62-a914d4b574b4.mov
(don't worry, this is a burner seed phrase that I generated just for the purposes of this bug report)

**Browser details (please complete the following information):**
 - OS: MacOS Big Sur
 - Hardware Wallet: N/A
 - Browser: Brave Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)
 - MetaMask Version: 10.1.1

### PR DESCRIPTION
**Pull request by ryanml**
Fixes MetaMask/metamask-extension#12225

Manual testing steps:  
  -  See issue

### CODE REVIEW

File: ui/pages/keychains/restore-vault.js [hunk 1]
```diff
@@ -44,13 +44,14 @@ class RestoreVaultPage extends Component {
...
+    const parseSeedPhrase = this.parseSeedPhrase(seedPhrase);
+    const wordCount = parseSeedPhrase.split(/\s/u).length;
     if (
-      seedPhrase &&
+      parseSeedPhrase &&
       (wordCount % 3 !== 0 || wordCount < 12 || wordCount > 24)
     ) {
       seedPhraseError = t('seedPhraseReq');
-    } else if (!isValidMnemonic(seedPhrase)) {
+    } else if (!isValidMnemonic(parseSeedPhrase)) {
```
Comment (Gudahtt) [inline ui/pages/keychains/restore-vault.js:54]: It seems like we're now validating the "parsed seed phrase" rather than the actual seed phrase that gets used for the vault restoration. This might result in the validation passing here, but failing when the vault gets restored. This seems bad.

Comment (ryanml) [reply ui/pages/keychains/restore-vault.js:54]: https://github.com/MetaMask/metamask-extension/blob/401a081445834c9bb255509501238b04869d9bef/ui/pages/keychains/restore-vault.js#L100

Comment (Gudahtt) [reply ui/pages/keychains/restore-vault.js:54]: Right, just discovered that myself too! Thanks.

**Review by Gudahtt — APPROVED** [review]
LGTM!

We really ought to consolidate the shared parts of `ui/pages/keychains/restore-vault.js` and `ui/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js` at some point. This same fix was implemented years ago in the other location (in #5827), but it was missed here where the same functionality is duplicated.

**Review by jpuri — APPROVED** [review]
