### PR TITLE
fix: fix showNativeTokenAsMainBalance setting

### LINKED ISSUE #37123: [Bug]: Show native token as main balance does not work
**Describe the bug**

While being on any single popular network, if the setting `Show native token as main balance` is enabled, there is no difference in the balance: it is still displayed in fiat value

**Expected behavior**

Show native token as main balance to work

**Screenshots/Recordings**

https://github.com/user-attachments/assets/da4a4bca-6617-488f-a21f-f74c97f28a67

**Steps to reproduce**

1.  Select one single network in the Network manager
2. Go to General settings and enable Show native token as main balance
3. notice balance is still displayed in fiat

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.6.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix the display of the main user when the setting showNativeTokenAsMainBalance changes.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37233?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed a bug causing the setting showNativeTokenAsMainBalance to not display native user balance when ON.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37123

## **Manual testing steps**

1. Go Settings
2. Turn On the setting: Show native token as main balance
3. Go back to home page
4. Make sure you have a single network selected
5. Notice that the main balance displayed is now your native token balance

### **Before**

https://github.com/user-attachments/assets/379d4692-eae8-4a76-aac2-820e833c62c0

### **After**

https://github.com/user-attachments/assets/92c923fe-df96-4a4a-aeeb-c72430fbc826

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Shows native token as the primary balance for single-network setups when the setting is enabled, with EVM/non‑EVM handling and updated tests.
> 
> - **Wallet Overview**
>   - `coin-overview.tsx`: Passes `balance` and `chainId` to `AccountGroupBalance` when multichain accounts state 2 is enabled.
> - **Account Group Balance**
>   - `account-group-balance.tsx`:
>     - Adds props `balance` and `chainId` (supports `CaipChainId | Hex`), converts to CAIP, derives selected account.
>     - Computes native token balance (EVM via `hexWEIToDecETH`, non‑EVM via `getMultichainNativeTokenBalance`) and formats with `formatTokenQuantity`.
>     - Shows native balance when `showNativeTokenAsMainBalance` is on and exactly one network is enabled; otherwise formats fiat with `formatCurrency`.
>     - Uses `useMemo` for `formattedTotal`; integrates selectors for enabled networks, preferences, and native currency.
> - **Tests**
>   - `account-group-balance.test.tsx`: Updates helpers and mocks; adds assertions for native balance rendering when the setting is enabled; passes `balance`/`chainId` to component.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1f610549d4d27fee6a9ae5dc69e2ceeecca428ba. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/assets/account-group-balance/account-group-balance.tsx [hunk 1]
```diff
@@ -11,34 +16,89 @@ import {
...
+
+  const multichainNativeTokenBalance = useSelector((state) =>
+    getMultichainNativeTokenBalance(state, selectedAccount),
+  );
+
+  const isEvm = isEvmChainId(chainId);
+
+  const showNativeTokenAsMain = isGlobalNetworkSelectorRemoved
+    ? showNativeTokenAsMainBalance && Object.keys(enabledNetworks).length === 1
+    : showNativeTokenAsMainBalance;
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/account-group-balance/account-group-balance.tsx]: 🌶️  - since the feature is released and we aren't reverting, can we skip the `isGlobalNetworkSelectorRemoved` feature flag check?

File: ui/components/app/assets/account-group-balance/account-group-balance.tsx [hunk 2]
```diff
@@ -11,34 +16,89 @@ import {
...
+    getMultichainNativeCurrency,
+    selectedAccount,
+  );
+
+  let formattedNativeBalance = null;
+  if (showNativeTokenAsMain) {
+    if (isEvm) {
+      const decimalBalance = new Numeric(balance, 16, EtherDenomination.WEI)
+        .toDenomination(EtherDenomination.ETH)
+        .toBase(10);
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/account-group-balance/account-group-balance.tsx]: Is it worth using the `hexWEIToDecETH(...)` util? Hmm it does return a string instead of a number tho...

File: ui/components/app/assets/account-group-balance/account-group-balance.tsx [hunk 3]
```diff
@@ -70,7 +130,16 @@ export const AccountGroupBalance: React.FC<AccountGroupBalanceProps> = ({
...
+
+          {(() => {
+            if (showNativeTokenAsMain) {
+              return formattedNativeBalance;
+            }
+            if (total === undefined) {
+              return null;
+            }
+            return formatCurrency(total, currency);
+          })()}
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/account-group-balance/account-group-balance.tsx]: Hmmm, thoughts on moving this into a `useMemo()`, not a blocker.

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by salimtb** [comment]
is it intentional to exclude the accountList from this fix ? they can probably report this as a bug

https://github.com/user-attachments/assets/5b5785ea-6aa4-4fe8-b7dd-3ea603fd17dd

**Comment by sahar-fehri** [comment]
> is it intentional to exclude the accountList from this fix ? they can probably report this as a bug
> 
>  account-list.mov

I think he setting only affects the main balance view; the account view is not supposed to change.

File: ui/components/app/assets/account-group-balance/account-group-balance.tsx (hunk 1 above)
Comment (sahar-fehri) [reply ui/components/app/assets/account-group-balance/account-group-balance.tsx]: Totally! I think that check still exists in other places of the code, perhaps we still plan to totally remove it in future

File: ui/components/app/assets/account-group-balance/account-group-balance.tsx (hunk 2 above)
Comment (sahar-fehri) [reply ui/components/app/assets/account-group-balance/account-group-balance.tsx]: Totally 🙏

**Review by salimtb — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by bergarces — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
