### PR TITLE
fix: cp-13.5.0 Fix account icons in send flow

### LINKED ISSUE #36657: [Bug]: Maskicon is different for the same account in the send flow
**Describe the bug**

The account icon is different for the same account in the send flow

Related [slack thread]([https://consensys.slack.com/archives/C09GL168BQU/p1758556948002099|https://consensys.slack.com/archives/C09GL168BQU/p1758556948002099])

**Expected behavior**

Account icon should to be the same for the same account on all flows

**Screenshots/Recordings**

https://github.com/user-attachments/assets/1083a546-c41c-4962-9e09-23b438b7f2f3

**Steps to reproduce**

1. Check Account list icon versus Account Details
2. Check the icon in the send flow

**Error messages or log output**

None

**Detection stage**

During release testing

**Version**

13.5.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to centralise seed account icon map in a hook and use it in send flow.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36877?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36657

## **Manual testing steps**

Account icon should be consistent as other parts of the wallet.

### **After**

https://github.com/user-attachments/assets/466421d4-e7bc-4a35-98e9-236c7d85d558

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Introduces a hook to map account addresses to seed-icon addresses and integrates it across send flow to render consistent avatars, updating recipient types and tests.
> 
> - **Hooks**:
>   - Add `useAccountAddressSeedIconMap` to build a map of account addresses -> seed icon address from account groups.
>   - Use in `useAccountRecipients` and `useContactRecipients` to attach `seedIcon` to each `Recipient`.
> - **Components**:
>   - `Recipient`: pass `recipient.seedIcon ?? address` to `PreferredAvatar`.
>   - `RecipientInput`: compute avatar seed address from the map and use it in `PreferredAvatar` when a recipient is resolved.
> - **Types**:
>   - Extend `Recipient` with optional `seedIcon`.
> - **Tests**:
>   - Add tests for `useAccountAddressSeedIconMap`.
>   - Update/mocks in `recipient-input.test.tsx`, `recipient.test.tsx`, `useAccountRecipients.test.ts`, and `useContactRecipients.test.ts` to account for the new hook and `seedIcon`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 596eb604dbdbbf4086856a2a7fb371f09c637b6c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/components/send/recipient-input/recipient-input.tsx [hunk 1]
```diff
@@ -105,7 +107,11 @@ export const RecipientInput = ({
         >
           <Box alignItems={AlignItems.center} display={Display.Flex}>
             <PreferredAvatar
-              address={resolvedAddress}
```
Comment (jpuri) [inline ui/pages/confirmations/components/send/recipient-input/recipient-input.tsx:108]: It is bit big piece of code inline.

**Review by pedronfigueiredo — DISMISSED** [review]

File: ui/pages/confirmations/hooks/send/useAccountAddressSeedIconMap.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+      accounts.forEach((account) => {
+        map.set(account.address.toLowerCase(), seedAddress);
+      });
+    });
+
+    return map;
+  }, [accountGroupsWithAddresses]);
+
+  return { accountAddressSeedIconMap };
+};
```
Comment (jpuri) [inline ui/pages/confirmations/hooks/send/useAccountAddressSeedIconMap.ts:31]: Here we are creating this map for all accounts, can we optimise this for only the concerned account ?

Comment (OGPoyraz) [reply ui/pages/confirmations/hooks/send/useAccountAddressSeedIconMap.ts:31]: The current map-based approach is already optimized for the actual usage patterns where we need seed icons for many/all addresses simultaneously. The only case where per-address lookup would be better is if we only had the single lookup in `recipient-input.tsx`, but since the other hooks process bulk addresses, the current design is more performant.

File: ui/pages/confirmations/components/send/recipient-input/recipient-input.tsx (hunk 1 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/send/recipient-input/recipient-input.tsx:108]: Done

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Comment by gauthierpetetin** [comment]
Hi @OGPoyraz, is this PR user-facing? If yes, what would be the user-facing CHANGELOG entry? If not, can you please set CHANGELOG entry to "null"?

**Comment by OGPoyraz** [comment]
Hey @gauthierpetetin, the feature is not yet released in the previous versions hence I didn't put any changelog on that.

**Comment by gauthierpetetin** [comment]
ok thanks
