### PR TITLE
fix: toast message after wallet import

### LINKED ISSUE #40944: [Bug]: Accounts - Importing an SRP displays incorrect toast message until the keyring updates
### Describe the bug

Importing an SRP displays incorrect toast message (Wallet 1 imported) until the keyring updates.
When we first show the toast the keyring length is still 1. Then it takes some seconds until the keyring is updated, and the toast is updated, but given there is an auto hide function, and if the toast is hidden while we have 1, then the test will fail

This issue was catched by @itsyoboieltr in the work of migrating to webpack

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/aa521869-3fd5-4291-97bb-38ebdd28efba

### Steps to reproduce

1. Import an SRP
2. Toast with Wallet 1 imported appears
3. After some seconds, the toast re-renders with the value Wallet 2 imported  --> this is the one we look for
4. Then the toast automatically auto-hides

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

main

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by hmalik88**
## **Description**

When importing an SRP, the toast message briefly shows "Wallet 1 imported" before updating to the correct number (e.g. "Wallet 2 imported"). This happens because background state updates are debounced (200ms, max 1s), so `hdKeyrings.length` is stale when the toast first renders.

- Changed `showNewSrpAddedToast` from a `boolean` to `number | false`, storing the wallet number directly
- The import component now computes `hdKeyrings.length + 1` before the import and passes it to the toast state
- The toast reads the number from state instead of deriving it from the (lagging) keyrings selector
- Removed a duplicate `setShowNewSrpAddedToast` dispatch from `importMnemonicToVault`

## **Changelog**

CHANGELOG entry: Fixed a bug that was causing the wallet imported toast to momentarily show the wrong wallet added.

## **Related issues**

Fixes #40944 

## **Manual testing steps**

1. Build from this branch
2. Import an SRP, the toast should immediately show the correct wallet number (e.g. "Wallet 2 imported")

### **Before**

See issue: https://github.com/MetaMask/metamask-extension/issues/40944

### **After**

https://github.com/user-attachments/assets/52978cc1-053c-496a-965b-b4b9bc8a988f

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Changes the Redux `appState.showNewSrpAddedToast` type from boolean to `number | false` and updates dispatch/selector usage; any remaining call sites assuming a boolean could break or hide the toast incorrectly.
> 
> **Overview**
> Fixes the “New SRP Added” toast briefly showing the wrong wallet number after importing an SRP by **storing the wallet number in Redux** instead of a boolean.
> 
> `selectNewSrpAdded`/`setShowNewSrpAddedToast` now use `number | false`, the import flow dispatches the computed next wallet number (`hdKeyrings.length + 1`), and `ToastMaster` renders the message directly from that stored number. A redundant `setShowNewSrpAddedToast(true)` dispatch inside `importMnemonicToVault` was removed, and related unit tests were updated.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 0d9bad21184fd5062e0eeeab1c44312b11e9cc79. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Review by david0xd — APPROVED** [review]

File: ui/pages/multi-srp/import-srp/import-srp.tsx [hunk 1]
```diff
@@ -71,7 +75,7 @@ export const ImportSrp = () => {
       await dispatch(importMnemonicToVault(secretRecoveryPhrase));
 
       navigate(DEFAULT_ROUTE);
-      dispatch(setShowNewSrpAddedToast(true));
+      dispatch(setShowNewSrpAddedToast(hdKeyrings.length + 1));
```
Comment (ccharly) [inline ui/pages/multi-srp/import-srp/import-srp.tsx:78]: Nit: But that could have been nice to use a named variable here to add a bit more context about the number we use here:

```ts
...
      const walletNumber = hdKeyrings.length + 1;
      await dispatch(importMnemonicToVault(secretRecoveryPhrase));

      navigate(DEFAULT_ROUTE);
      dispatch(setShowNewSrpAddedToast(walletNumber));
...
```

**Review by ccharly — APPROVED** [review]
LGTM, left a small nit, but the logic is good. (not tested, I'm relying on the recording here)
