### PR TITLE
fix: transactions from multiple different networks not correctly displayed in activity tab

### LINKED ISSUE #34704: [Bug]: Transactions on Linea don't show up when more than 1 network is selected within activity
### Describe the bug

Transactions on Linea don't show up when more than 1 network is selected within activity. If you only select Linea, you can see the transaction, but it disappears if you enable more networks. 

It doesn't seem related with the date of the Linea transaction nor the nonce. 

### Expected behavior

Transactions would be shown ordered by date.

### Screenshots/Recordings

https://github.com/user-attachments/assets/668fe725-bcae-4d25-8a8a-fdc12ccc0be7

### Steps to reproduce

1. Do a transaction on Linea
2. Check activity with multiple networks selected under "Enabled network"
3. Notice no Linea transaction
4. Edit "Enabled network" to select Linea only 
5. Notice how the Linea transaction shows up

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix: transactions from multiple different networks not correctly displayed in activity tab

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34704

## **Manual testing steps**

1. Submit transaction from different networks
2. Select a few networks in homepage to see transactions from in activity tab
3. Ensure that transactions from all the networks are visible

## **Screenshots/Recordings**
Screenshot 2025-08-20 at 3 06 37 PM

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/transactions.js [hunk 1]
```diff
@@ -561,7 +565,7 @@ export const groupAndSortTransactionsByNonce = (transactions) => {
           (status in PRIORITY_STATUS_HASH ||
             status === TransactionStatus.dropped),
       };
-      insertOrderedNonce(orderedNonces, nonce);
+      insertOrderedNonce(orderedNonces, `${nonce}-${networkClientId}`);
```
Comment (jpuri) [inline ui/selectors/transactions.js]: Grouping by nonce was causing issue if multiple networks have same nonce value and transaction from different network are part of the group. I have changes grouping here to use `nonce-networkClientId`.

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
