### PR TITLE
fix: Address design review for NFT token send

### LINKED ISSUE #28370: [Bug]: Wallet and dApp initiated Send NFT confirmations
### Describe the bug

There are discrepancies between some of the `Send NFT` confirmation screens and their corresponding Figma designs.

Related:
https://github.com/MetaMask/MetaMask-planning/issues/3018
https://github.com/MetaMask/MetaMask-planning/issues/3019

### Expected behavior

-

### Screenshots/Recordings

Screenshot 2024-11-07 at 17 38 31

Screenshot 2024-11-07 at 17 39 06

Screenshot 2024-11-07 at 17 39 43

Screenshot 2024-11-07 at 17 37 51

Screenshot 2024-11-07 at 17 41 09

### Steps to reproduce

1. Enable Confirmations redesign
2. Transfer NFT

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

A few changes were made, namely:
- Leverage `NftItem` component to display a square thumbnail of the Nft image
- Update spending cap indicators to abbreviate long decimal numbers and show complete numbers on a tooltip
- Center align token name
- Add # to the token id
- Change background color for native token fallback thumbnail

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28433?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28370

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx [hunk 1]
```diff
@@ -13,7 +13,8 @@ const NFTTokenTransferInfo = () => {
   const { currentConfirmation: transactionMeta } =
     useConfirmContext<TransactionMeta>();
 
-  const isWalletInitiated = transactionMeta.origin === 'metamask';
+  // const isWalletInitiated = transactionMeta.origin === 'metamask';
```
Comment (vinistevam) [inline ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx:16]: should we uncomment this line and remove line 17?

Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx]: Good catch!

**Review by vinistevam — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
