### PR TITLE
Fix/14230 dark mode fixes

### LINKED ISSUE #14230: Dark mode: Some other catches

### LINKED ISSUE #14299: [Bug]: Some warnings are now displayed yellow instead of red
### Describe the bug

**Problem**: some warnings are now displayed yellow instead of red

**Affected**:
- Sync mobile
   - Result:
image
   - Expected:
image

- Secret recovery phrase
   - Result:
image

   - Expected:
image

### Steps to reproduce

1. Unlock Metamask
2. Click on Settings
3. Click on Advance
4. Click on Sync with mobile --- first screen
5. Click on Security
6. Click on Reveal security phrase -- second screen

### Error messages or log output

```shell
n/a
```

### Version

10.13.0

### Build type

_No response_

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #14301: [Bug]: Dark Mode - Reveal Secret Recovery Phrase input font colour
### Describe the bug

Incorrect password font colour 

password

Highlighted to show a password has been entered
password highlighted

### Steps to reproduce

1. Settings -> Security & Privacy -> Reveal Secret Recovery Phrase
2. Enter password

### Error messages or log output

_No response_

### Version

10.13.0

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## Explanation

Some fixes for release and dark mode as well as adding some stories

Fixes: https://github.com/MetaMask/metamask-extension/issues/14230
Fixes: https://github.com/MetaMask/metamask-extension/issues/14299
Fixes: https://github.com/MetaMask/metamask-extension/issues/14301

### Before
There was a psuedo element that is no longer a different color so I removed it. 
Screen Shot 2022-03-31 at 9 31 09 AM

### After (no changes)
Screen Shot 2022-03-31 at 9 40 44 AM
Screen Shot 2022-03-31 at 9 40 57 AM

Added a story for the component 
Screen Shot 2022-03-31 at 9 41 14 AM
Screen Shot 2022-03-31 at 9 41 19 AM

### Before
danger/critical message was yellow
Screen Shot 2022-03-31 at 9 48 57 AM

### After 
danger/critical message is red also fixing input color in dark mode 
Screen Shot 2022-03-31 at 9 51 05 AM
Screen Shot 2022-03-31 at 9 51 14 AM
Screen Shot 2022-03-31 at 9 51 38 AM
Screen Shot 2022-03-31 at 9 52 12 AM
Screen Shot 2022-03-31 at 9 52 29 AM

Adding stories for RevealSeedPage component for easier future updates to UI

Screen Shot 2022-03-31 at 9 52 39 AM
Screen Shot 2022-03-31 at 9 52 45 AM

## Manual testing steps

**Show RevealSeedPage in dev build**
- Go to Settings > Security & Privacy > Reveal Secret Recovery Phrase > See page

https://user-images.githubusercontent.com/8112138/161110193-9e6c4515-23ae-4591-a54b-9e38f3ea216d.mov

**Sync with mobile in dev build**
- Go to Settings > Advanced > Sync with mobile > See page

https://user-images.githubusercontent.com/8112138/161110576-5f0ffbaf-47c7-4ac2-8373-a11b1aabe622.mov

**Storybook stories**

RevealSeedPage
- Go to latest build of storybook in this PR and search `RevealSeedPage`

AppHeader
- Go to latest build of storybook in this PR and search `AppHeader`

### CODE REVIEW

File: ui/components/app/app-header/app-header.component.js [hunk 1]
```diff
@@ -97,19 +97,14 @@ export default class AppHeader extends PureComponent {
...
     return (
-      <div
-        className={classnames('app-header', {
-          'app-header--back-drop': isUnlocked,
-        })}
-      >
+      <div className="app-header">
         <div className="app-header__contents">
           <MetaFoxLogo
             unsetIconHeight
```
Comment (georgewrmarshall) [inline ui/components/app/app-header/app-header.component.js:110]: Prop is no longer used in this render method

File: ui/components/app/app-header/app-header.stories.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    },
+    onClick: {
+      action: 'onClick',
+    },
+  },
+};
+
+export const DefaultStory = (args) => <AppHeader {...args} />;
+
+DefaultStory.storyName = 'Default';
```
Comment (georgewrmarshall) [inline ui/components/app/app-header/app-header.stories.js:49]: Adding story for app header for easy future UI updates

File: ui/components/app/app-header/index.scss [hunk 3]
```diff
@@ -16,17 +16,6 @@
...
-        position: absolute;
-        width: 100%;
-        height: 32px;
-        background: var(--color-background-alternative);
-        bottom: -32px;
-      }
-    }
   }
 
   &__metafox-logo {
```
Comment (georgewrmarshall) [inline ui/components/app/app-header/index.scss:21]: Removing unused styles

File: ui/css/base-styles.scss [hunk 4]
```diff
@@ -89,29 +89,30 @@ input.form-control {
...
+    color: var(--color-text-muted);
   }
 
   &:-moz-placeholder {
     font-weight: 100;
-    color: var(--color-text-alternative);
+    color: var(--color-text-muted);
   }
 
   &--error {
```
Comment (georgewrmarshall) [inline ui/css/base-styles.scss:118]: Updates for inputs the placeholder text should be lighter and the border of the input should be darker

**Review by darkwing — APPROVED** [review]

**Review by NiranjanaBinoy — APPROVED** [review]
