### PR TITLE
Fix migration 88 to handle the case where chainId keys can be undefined

### LINKED ISSUE #20297: [Bug]: Migration networks broke initialization
### Describe the bug

I updated metamask to the new versión and I think it migrated like the config networks but left one on a bad format.

On the image I attach you can see all the other network configurations have the chainId and rpcPerfs but this one just missed completly the migration and its breaking the extension, it cant initiate.

yY9TPG4

Is there a way I can modify the file where metamask is retrieving this network configuration?

### Steps to reproduce

1.
Open Metamask
2.
Breaks

### Error messages or log output

```shell
sentry-install.js:1 Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN
sentry-install.js:1 Removing intrinsics.JSON.rawJSON
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.JSON.isRawJSON
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.toSorted
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.toSpliced
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.with
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%FunctionPrototype%.apply.prototype
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Tolerating undeletable intrinsics.%FunctionPrototype%.apply.prototype === undefined
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9289
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%FunctionPrototype%.bind.prototype
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Tolerating undeletable intrinsics.%FunctionPrototype%.bind.prototype === undefined
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9289
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
visitProperties @ runtime-lavamoat.js:9279
isAllowedPropertyValue @ runtime-lavamoat.js:9155
isAllowedProperty @ runtime-lavamoat.js:9218
visitProperties @ runtime-lavamoat.js:9265
whitelistIntrinsics @ runtime-lavamoat.js:9308
repairIntrinsics @ runtime-lavamoat.js:9643
lockdown @ runtime-lavamoat.js:9718
createKernel @ runtime-lavamoat.js:10939
(anonymous) @ runtime-lavamoat.js:12023
(anonymous) @ runtime-lavamoat.js:12129
use-snow.js:23 Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. Window {window: Window, self: Window, document: document, name: '', location: Location, …}
use-snow.js:23 Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. Window {window: Window, document: document, location: Location, …}
sentry-install.js:1 Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more.
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
warn @ runtime-lavamoat.js:7114
(anonymous) @ lockdown-more.js:74
protectIntrinsics @ lockdown-more.js:44
(anonymous) @ lockdown-more.js:97
sentry-install.js:1 missing dep: ethjs>ethjs-unit>bn.js requested buffer
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
getRelativeModuleId @ runtime-lavamoat.js:12060
requireRelative @ runtime-lavamoat.js:11731
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-0.js:1
(anonymous) @ common-0.js:1
(anonymous) @ common-0.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-0.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-0.js:7
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-1.js:11
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-5.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
runModule @ runtime-lavamoat.js:12118
(anonymous) @ runtime-lavamoat.js:12108
loadBundle @ runtime-lavamoat.js:12107
(anonymous) @ background-5.js:1
sentry-install.js:1 missing dep: ethjs>number-to-bn>bn.js requested buffer
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
getRelativeModuleId @ runtime-lavamoat.js:12060
requireRelative @ runtime-lavamoat.js:11731
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-3.js:26
(anonymous) @ common-3.js:26
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-3.js:26
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-0.js:1
(anonymous) @ common-0.js:1
(anonymous) @ common-0.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-0.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-0.js:7
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-1.js:11
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-5.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
runModule @ runtime-lavamoat.js:12118
(anonymous) @ runtime-lavamoat.js:12108
loadBundle @ runtime-lavamoat.js:12107
(anonymous) @ background-5.js:1
sentry-install.js:1 WARNING: Missing strong random number source
sentry-install.js:1 missing dep: ethjs-contract>ethjs-abi>bn.js requested buffer
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
getRelativeModuleId @ runtime-lavamoat.js:12060
requireRelative @ runtime-lavamoat.js:11731
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
(anonymous) @ common-2.js:16
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
(anonymous) @ common-2.js:16
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ common-2.js:16
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-4.js:12
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-4.js:12
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
requireRelative @ runtime-lavamoat.js:11745
requireRelativeWithContext @ runtime-lavamoat.js:11714
(anonymous) @ background-5.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
runModule @ runtime-lavamoat.js:12118
(anonymous) @ runtime-lavamoat.js:12108
loadBundle @ runtime-lavamoat.js:12107
(anonymous) @ background-5.js:1
sentry-install.js:1 (Error#1)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
warn @ runtime-lavamoat.js:7114
(anonymous) @ common-2.js:7
s.emit @ common-2.js:7
migrateData @ background-4.js:12
await in migrateData (async)
ie @ background-5.js:1
await in ie (async)
oe @ background-5.js:1
(anonymous) @ background-5.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
runModule @ runtime-lavamoat.js:12118
(anonymous) @ runtime-lavamoat.js:12108
loadBundle @ runtime-lavamoat.js:12107
(anonymous) @ background-5.js:1
sentry-install.js:1 Error#1: MetaMask Migration Error #88: Invalid character
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7075
logSubErrors @ runtime-lavamoat.js:7018
warn @ runtime-lavamoat.js:7116
(anonymous) @ common-2.js:7
s.emit @ common-2.js:7
migrateData @ background-4.js:12
await in migrateData (async)
ie @ background-5.js:1
await in ie (async)
oe @ background-5.js:1
(anonymous) @ background-5.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
runModule @ runtime-lavamoat.js:12118
(anonymous) @ runtime-lavamoat.js:12108
loadBundle @ runtime-lavamoat.js:12107
(anonymous) @ background-5.js:1
sentry-install.js:1   at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:101284)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:102106)
  at o._parseBase (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:104384)
  at o._init (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:102766)
  at new o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:101578)
  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:11:22850)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:11:22285
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:148418
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:124203
  at wr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:113795)
  at Fn.mapKeys (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:148391)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:11:22274
  at n.migrate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:11:22634)
  at i.migrateData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:295107)
  at ie (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:88729)
  at async oe (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:87156)

e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7097
logSubErrors @ runtime-lavamoat.js:7018
warn @ runtime-lavamoat.js:7116
(anonymous) @ common-2.js:7
s.emit @ common-2.js:7
migrateData @ background-4.js:12
await in migrateData (async)
ie @ background-5.js:1
await in ie (async)
oe @ background-5.js:1
(anonymous) @ background-5.js:1
e.<computed> @ sentry-install.js:1
internalRequire @ runtime-lavamoat.js:11702
runModule @ runtime-lavamoat.js:12118
(anonymous) @ runtime-lavamoat.js:12108
loadBundle @ runtime-lavamoat.js:12107
(anonymous) @ background-5.js:1
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 Error#2: missing provider (argument="provider", value=undefined, code=INVALID_ARGUMENT, version=providers/5.7.2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7075
logSubErrors @ runtime-lavamoat.js:7018
error @ runtime-lavamoat.js:7116
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1   at e.makeError (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:10:13393)
  at e.throwError (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:10:13535)
  at e.throwArgumentError (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:10:13612)
  at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:10:148736)
  at new n.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:66267)
  at new n.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:5:159185)
  at new De (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:17325)
  at ae (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:88884)
  at oe (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:87431)

e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7097
logSubErrors @ runtime-lavamoat.js:7018
error @ runtime-lavamoat.js:7116
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#3)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 Error#3: chainId must be provided for custom RPC endpoints
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7075
logSubErrors @ runtime-lavamoat.js:7018
error @ runtime-lavamoat.js:7116
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:186008
  at Array.map (<anonymous>)
  at z.b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:185962)
  at z.y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:185421)
  at z.g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:185315)
  at z.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:178621)
  at Generator.next (<anonymous>)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:175028
  at new Promise (<anonymous>)
  at k (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:174773)
  at z.initializeProvider (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:13:178571)
  at new De (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:9885)
  at ae (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:88884)
  at oe (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:87431)

e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7097
logSubErrors @ runtime-lavamoat.js:7018
error @ runtime-lavamoat.js:7116
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
```

### Version

10.34.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
## Explanation

Fixes https://github.com/MetaMask/metamask-extension/issues/20297

At a certain point in history, it was possible to add networks without giving them a chainId. Then, in v10.34.0, we shipped an update to the network controller that would throw an error if a `networkConfiguration` did not have a chain id. This could cause metamask to crash on startup and land users on the error screen.

A fix to this problem is added in this PR in migration 91. It deletes network configurations if they do not have a chain id. There is no risk of hurting user experience here, as these networks have not been usable for a long time.

That fix on its own is insufficient however, because the lack of a chainId in network properties also could have led to a situation where migration 88 errors due to its attempt to validate whether each chainId property key in the various token controllers is hex. This validation ends up passing these keys to bn.js. If a user had once had a network without a chainId, it is possible that they have a string `'undefined'` key in some of the token controllers (where a decimal or hex chainId would have been expected). Passing this key to bn.js results in a thrown error, which results in migrations >= 88 not to run.

So to fix the originally described problem, in addition to migration 91, we need a fix to migration 88. This PR does this by adding logic to migration 88 which will just delete any entries in the tokens controllers that are keyed by `'undefined'` or `undefined`.

## Manual Testing Steps

1. Install v8.0.0
2. Onboard with the new seed phrase option, but select "Remind me later"
3. Manually add a custom network, but only add the network name and rpc url. Do not add the chainId
4. Update to v10.34.0. MetaMask should not load and you should see the error screen
5. `yarn dist` on this branch. MetaMask should load successfull

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: app/scripts/migrations/091.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
+import { hasProperty, isObject } from '@metamask/utils';
+import { cloneDeep } from 'lodash';
+
+export const version = 89;
+
+/**
+ * Add an `id` to the `providerConfig` object.
```
Comment (brad-decker) [inline app/scripts/migrations/091.ts:7]: Is this an accurate description of the migration?

File: app/scripts/migrations/091.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
+import { hasProperty, isObject } from '@metamask/utils';
+import { cloneDeep } from 'lodash';
+
+export const version = 89;
```
Comment (brad-decker) [inline app/scripts/migrations/091.ts:4]: version 89?

File: app/scripts/migrations/091.test.js [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+  };
+});
+
+describe('migration #91', () => {
+  it('should update the version metadata', async () => {
+    const oldStorage = {
+      meta: {
+        version: 90,
+      },
+      data: {},
```
Comment (brad-decker) [inline app/scripts/migrations/091.test.js:18]: Should probably audit this file to ensure the right version is being applied throughout. in some cases version is 90 and in others its 88 in old data and we aren't validating that 91 is used anywhere (we use the exported version which is currently 89)

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: app/scripts/migrations/091.ts (hunk 1 above)
Comment (danjm) [reply app/scripts/migrations/091.ts]: fixed in 4f53b4cb10

File: app/scripts/migrations/091.ts (hunk 2 above)
Comment (danjm) [reply app/scripts/migrations/091.ts]: fixed in bf8f215da1

File: app/scripts/migrations/091.test.js (hunk 3 above)
Comment (danjm) [reply app/scripts/migrations/091.test.js:18]: fixed in 5c93be014c

**Review by tmashuang — DISMISSED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by brad-decker — DISMISSED** [review]

File: app/scripts/migrations/088.test.ts [hunk 4]
```diff
@@ -156,6 +156,65 @@ describe('migration #88', () => {
...
+        NftController: {
+          allNftContracts: {
+            '0x111': {
+              '16': [
+                {
+                  name: 'Contract 1',
+                  address: '0xaaa',
+                },
+              ],
+              'undefined': [
```
Comment (tmashuang) [inline app/scripts/migrations/088.test.ts:172]: Lint:
```suggestion
              undefined: [
```

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by tmashuang — DISMISSED** [review]

**Review by Ameralameri — APPROVED** [review]
Approv

File: app/scripts/migrations/091.ts [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+    hasProperty(state, 'NetworkController') &&
+    isObject(state.NetworkController) &&
+    hasProperty(state.NetworkController, 'networkConfigurations') &&
+    isObject(state.NetworkController.networkConfigurations)
+  ) {
+    const { networkConfigurations } = state.NetworkController;
+
+    for (const networkConfigurationId of Object.keys(networkConfigurations)) {
+      const networkConfiguration =
+        networkConfigurations[networkConfigurationId];
```
Comment (Gudahtt) [inline app/scripts/migrations/091.ts:36]: Nit: small improvement:
```suggestion
    for (const [networkConfigurationId, networkConfiguration] of Object.entries(networkConfigurations)) {
```

File: app/scripts/migrations/091.test.js
Comment (Gudahtt) [inline app/scripts/migrations/091.test.js:1]: Nit: We could use TypeScript for this test as well. A few of the recent migration tests are in TypeScript.

File: app/scripts/migrations/091.test.js [hunk 6]
```diff
@@ -0,0 +1,149 @@
...
+      other: 'data',
+    };
+    const oldStorage = {
+      meta: {
+        version: 90,
+      },
+      data: oldData,
+    };
+
+    const newStorage = await migrate(oldStorage);
```
Comment (Gudahtt) [inline app/scripts/migrations/091.test.js:38]: If we're comparing the new state to the old state later, we should clone it before passing it in:

```suggestion
    const newStorage = await migrate(cloneDeep(oldStorage));
```

Otherwise the test would fail to notice if the state was changed by mutation.

Comment (Gudahtt) [reply app/scripts/migrations/091.test.js:38]: The same applies for the other examples of this as well.

I think in practice this won't be a problem here because the data is cloned as part of our migration template, but it's still something that could be removed/missed in theory.

Comment (danjm) [reply app/scripts/migrations/091.test.js]: done in 6cb2644fdb

File: app/scripts/migrations/091.test.js
Comment (danjm) [reply app/scripts/migrations/091.test.js:1]: done in b2a3490998

**Review by Gudahtt — COMMENTED** [review]
Looks good aside from the one missing test case! Which should be easy to add.

**Review by brad-decker — APPROVED** [review]

**Review by tmashuang — DISMISSED** [review]

**Review by brad-decker — CHANGES_REQUESTED** [review]
blocking for marks' changes

File: app/scripts/migrations/088.ts [hunk 7]
```diff
@@ -143,6 +178,12 @@ function migrateData(state: Record<string, unknown>): void {
     ) {
       const { allDetectedTokens } = tokensControllerState;
 
+      for (const chainId of Object.keys(allDetectedTokens)) {
```
[the remark this answers is not in the document]
Comment (danjm) [reply app/scripts/migrations/088.ts:181]: added in e1803de9fd

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by brad-decker — APPROVED** [review]
