### PR TITLE
fix: clear transaction data after submission or cancellation

### LINKED ISSUE #29374: [Bug]: After sending a transaction on Polygon, send and swap transactions are being created with exceptionally high gas fees
### Describe the bug

After initiating a transaction on Polygon, send and swap transactions are being created with exceptionally high gas fees.  I noticed the issue on Base and Optimism but further investigation needed.
This issue with elevated gas fees persists until a standard send transaction is executed. Following this, subsequent transactions are created with gas fees that fall within a typical range.

Actual transactions is submitted with the normal gas fee so this looks like UI issue. 

Note: the expected High Gas Fees alert is not being displayed, and the Confirm button remains active, despite the situation typically warranting it to be disabled due to insufficient funds.

(This is build from the latest RC https://github.com/MetaMask/metamask-extension/pull/29330)

### Expected behavior

-

### Screenshots/Recordings

Base:

https://github.com/user-attachments/assets/97208ea9-bdd9-4f4d-96f3-27c32befbc27

Image

Optimism:

https://github.com/user-attachments/assets/3b93cf5d-c8e6-40bf-bdc9-1fb1b3f3fd7d

Image

### Steps to reproduce

1. Send a transaction on Polygon
2. Switch to Base or Optimism
3. Start send+swap transaction
4. Note gas fees

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30546?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/29374

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 1]
```diff
@@ -225,6 +226,7 @@ const Footer = () => {
     }
     dispatch(updateCustomNonce(''));
     dispatch(setNextNonce(''));
+    dispatch(clearConfirmTransaction());
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx:229]: Minor, but could we create a local function to remove the duplication such as `resetTransactionState`?

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 2]
```diff
@@ -178,6 +178,12 @@ const Footer = () => {
     (!isScrollToBottomCompleted && !isSignature) ||
     hardwareWalletRequiresConnection;
 
+  const resetTransactionState = () => {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx:181]: Minor, unit tests would be nice but I appreciate this is high priority.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Comment by sleepytanya** [comment]
Tested on `main`:

https://github.com/user-attachments/assets/4bcb469e-c752-4f11-9758-9c2a30790845
