### PR TITLE
Ensure chainId is defined in validateRecipientUserInput in send-duck

### LINKED ISSUE #15467: [Bug]: Uncaught (in promise) TypeError: Cannot destructure property 'chainId' of 't.payload' as it is undefined.
### Describe the bug

Unhandled exception is thrown after clearing the public address in the send flow

### Steps to reproduce

These steps only occasionally reproduce the issue;
1. Click the send button
2. Select an address
3. Enter an amount
4. Click the `x` button to clear the address 

### Error messages or log output

```shell
Uncaught (in promise) TypeError: Cannot destructure property 'chainId' of 't.payload' as it is undefined.
  at validateRecipientUserInput (common-8.js:1:92565)
  at common-1.js:1:13536
  at produce (common-5.js:3:34153)
  at common-1.js:1:13513
  at Array.reduce (<anonymous>)
  at common-1.js:1:13382
  at common-7.js:1:72047
  at y (common-7.js:1:72966)
  at common-7.js:1:69593
  at dispatch (common-7.js:1:71193)
  at common-8.js:1:75504
```

### Version

10.18.0

### Build type

_No response_

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/15467

### CODE REVIEW

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -2190,12 +2190,14 @@ export function useMyAccountsForRecipientSearch() {
...
-  return async (dispatch) => {
+  return async (dispatch, getState) => {
+    const state = getState();
+    const chainId = getCurrentChainId(state);
     await dispatch(addHistoryEntry(`sendFlow - user cleared recipient input`));
     await dispatch(updateRecipientUserInput(''));
     await dispatch(updateRecipient({ address: '', nickname: '' }));
     await dispatch(resetEnsResolution());
-    await dispatch(validateRecipientUserInput());
+    await dispatch(validateRecipientUserInput({ chainId }));
```
Comment (segun) [inline ui/ducks/send/send.js:2200]: I looked at the implementation of validateRecipientUserInput [here](https://github.com/MetaMask/metamask-extension/blob/0cddaa9098d17dd161fafcea53699228e45fcac9/ui/ducks/send/send.js#L1339) and I'm not sure how the chainId is used in that definition.

**Review by darkwing — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]

File: ui/ducks/send/send.js (hunk 1 above)
Comment (brad-decker) [reply ui/ducks/send/send.js:2200]: Its used to determine if the current chain is one of the default metamask chains, which changes what error message is shown. I think its used one more time in that definition but thats the first usage making it required.
