### PR TITLE
fix: Add opensea security alert deprecation warning in typed signatures

### LINKED ISSUE #23766: [Bug]: Opensea deprecation warning missing in Typed Signatures
### Describe the bug

The Opensea deprecation warning is  missing in Typed Signatures

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/9d5a68a8-890b-4a22-9391-76deadaec090

### Steps to reproduce

1. Go to the test dapp https://metamask.github.io/test-dapp/
2. Select Celo network
3. Trigger a typed signature

### Error messages or log output

_No response_

### Version

11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

This PR continues the work of #23743, adding the BannerAlert component to typed signature confirmations. The end to end tests were updated to cover more cases.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23767?quickstart=1)

## **Related issues**

Fixes: #23766

## **Manual testing steps**

See #23743

### **After**

Screenshot 2024-03-27 at 17 43 54

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/signature-request/signature-request.js [hunk 1]
```diff
@@ -208,6 +214,25 @@ const SignatureRequest = ({
...
+  );
+
+  const showOpenSeaToBlockaidBannerAlert =
+    hasMigratedFromOpenSeaToBlockaid &&
+    !isNetworkSupportedByBlockaid &&
+    !hasDismissedOpenSeaToBlockaidBanner;
+
+  const handleCloseOpenSeaToBlockaidBannerAlert = () => {
+    dispatch(dismissOpenSeaToBlockaidBanner());
+  };
```
Comment (digiwand) [inline ui/pages/confirmations/components/signature-request/signature-request.js:234]: Q: have we considered moving this logic into BlockaidBannerAlert itself? 

we could return null if !showOpenSeaToBlockaidBannerAlert

File: ui/pages/confirmations/components/signature-request/signature-request.js [hunk 2]
```diff
@@ -224,6 +249,23 @@ const SignatureRequest = ({
...
+              description={t('openSeaToBlockaidDescription')}
+              actionButtonLabel={t('openSeaToBlockaidBtnLabel')}
+              actionButtonProps={{
+                href: 'https://snaps.metamask.io/transaction-insights',
+                externalLink: true,
+              }}
+              marginBottom={4}
+              marginLeft={4}
+              marginTop={4}
+              marginRight={4}
```
Comment (digiwand) [inline ui/pages/confirmations/components/signature-request/signature-request.js:265]:
```suggestion
              margin={4}
```
I believe this would work but would be good to double-check

**Review by digiwand — APPROVED** [review]
no blockers though left some suggestions above

File: ui/pages/confirmations/components/signature-request/signature-request.js (hunk 1 above)
Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/signature-request/signature-request.js:234]: That's a great suggestion, but perhaps we can consider this improvement separately from this PR since it's a release blocker. Thanks!

File: ui/pages/confirmations/components/signature-request/signature-request.js (hunk 2 above)
Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/signature-request/signature-request.js:265]: That's a great suggestion, but perhaps we can consider this improvement separately from this PR since it's a release blocker. Thanks!

**Review by jpuri — APPROVED** [review]
