### PR TITLE
fix: capture Asset image URL fallback errors

### LINKED ISSUE #39743: Error: No XChain Swaps native asset found for chainId: eip155:73571
Sentry Issue: [METAMASK-YH96](https://metamask.sentry.io/issues/7236584283/?referrer=github_integration)

```
Error: No XChain Swaps native asset found for chainId: eip155:73571
  at toAssetId (shared/lib/asset-utils.ts:54:12)
  at getAssetImageUrl (shared/lib/asset-utils.ts:83:25)
  at TokenHero (ui/pages/confirmations/components/UI/send-hero/send-hero.tsx:142:31)
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

https://consensys.slack.com/archives/C0AA1T3BD2T/p1770118966868099?thread_ts=1769712946.739669&cid=C0AA1T3BD2T

Catch and log errors in `getAssetImageUrl` to prevent `getNativeAssetForChainId` errors from propagating, as observed in Sentry.

An underlying bridge util to fetch native asset Ids will throw an error for unsupported asset Ids.
We use util as part of the asset image fallback utility.

Now we capture this error instead of propagating.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39742?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: capture Asset image URL fallback errors

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/39743

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots. 

---
<a href="https://cursor.com/background-agent?bcId=bc-9e81b3f5-cd0b-422c-9b0a-5dae13460a2b"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-cursor-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-cursor-light.png">Open in Cursor</picture></a>&nbsp;<a href="https://cursor.com/agents?id=bc-9e81b3f5-cd0b-422c-9b0a-5dae13460a2b"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-web-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-web-light.png">Open in Web</picture></a>

---

> [!NOTE]
> **Low Risk**
> Small, defensive change limited to asset icon URL construction; it only adds error handling/logging and keeps returning `undefined` on failure.
> 
> **Overview**
> `getAssetImageUrl` is now wrapped in a `try/catch` so failures while converting to a CAIP `assetId` (e.g., from `getNativeAssetForChainId` on unsupported/custom chains) no longer propagate and break callers.
> 
> On error it logs a structured message via `loglevel` (including `assetId` and `chainId`) and returns `undefined`, preserving the existing fallback behavior when the URL cannot be constructed.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0af59a5983155978df3f66734237ff2c1d770076. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: shared/lib/asset-utils.ts [hunk 1]
```diff
@@ -80,17 +81,25 @@ export const getAssetImageUrl = (
...
+    return `${STATIC_METAMASK_BASE_URL}/api/v2/tokenIcons/assets/${
+      normalizedAssetId
+    }.png`;
+  } catch (error) {
+    log.error('Failed to get asset image URL', {
+      error: error instanceof Error ? error.message : String(error),
+      assetId,
+      chainId,
+    });
     return undefined;
```
Comment (Prithpal-Sooriya) [inline shared/lib/asset-utils.ts:109]: Safely capturing error and returning undefined.
Keeping some error logs for now.

**Review by sahar-fehri — APPROVED** [review]

**Review by juanmigdr — APPROVED** [review]
