### PR TITLE
Fixing tooltip theming by enforcing default theme

### LINKED ISSUE #14990: Fix tooltip theming
### Description
Fix tooltip theming so theme state doesn't need to be passed to the tooltip every time it is used

Currently theming is being passed to the tooltip.

Screen Shot 2022-06-20 at 12 35 04 PM
Screen Shot 2022-06-20 at 12 35 21 PM

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## Explanation

Currently, theme has to be passed to the tooltip to allow for darkmode.

This is a problem because every time an engineer uses a Tooltip component they have to pass it the theme logic. It would be much more convenient if the Tooltip component handled this logic itself.

In order to solve this problem, this pull request enforces some styling that includes the design tokens to handle the theme logic.
- It also removes the `arrow` prop functionality as all of our tooltips should use an arrow.
- Updates the `InfoTooltip` component and removes duplicate styles
- Removes unused themes in other instances of the tooltip component throughout the codebase
- Created Tooltip story
- Removes `wide` prop form InfoTooltip as did a search and it's only used in one instance that probably isn't needed

## More Information

* Fixes #14990 
* See PR with theme logic https://github.com/MetaMask/metamask-extension/pull/14557/files#r896059292

### After
Tooltip story in storybook

Screen Shot 2022-06-20 at 1 20 49 PM
Screen Shot 2022-06-20 at 1 21 35 PM

InfoTooltip in storybook

Screen Shot 2022-06-20 at 1 22 13 PM
Screen Shot 2022-06-20 at 1 22 36 PM

## Manual Testing Steps
- Go to this screen
- Do this
- Then do this

## Pre-Merge Checklist

- [x] PR template is filled out
- ~[x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added~ N/A
- [x] PR is linked to the appropriate GitHub issue
- ~[x] PR has been added to the appropriate release Milestone~ N/A

### + If there are functional changes:

- ~[x] Manual testing complete & passed~ N/A
- [ ] "Extension QA Board" label has been applied - Not sure?? May need some visual testing

### CODE REVIEW

File: ui/components/app/edit-gas-fee-popover/network-statistics/tooltips.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ import {
 } from '../../../../helpers/constants/design-system';
 
 const NetworkStatusTooltip = ({ children, html, title }) => (
-  <Tooltip position="top" html={html} title={title} theme="tippy-tooltip-info">
+  <Tooltip position="top" html={html} title={title}>
     <Box display={DISPLAY.FLEX} flexDirection={FLEX_DIRECTION.COLUMN}>
       {children}
     </Box>
```
Comment (georgewrmarshall) [inline ui/components/app/edit-gas-fee-popover/network-statistics/tooltips.js:17]: Updated default theme to include styles from `tippy-tooltip-info` so this theme is not needed

File: ui/components/ui/info-tooltip/index.scss [hunk 2]
```diff
@@ -11,58 +11,10 @@
...
-        }
-      }
-    }
-  }
-
-  &#{&}-wideInfo-theme {
-    max-width: 260px;
+    padding-bottom: 16px;
   }
 }
```
Comment (georgewrmarshall) [inline ui/components/ui/info-tooltip/index.scss:20]: Updated default Tooltip theme with many of the styles from info-tooltip including the link color and paragraph spacing so these styles are no longer needed

File: ui/components/ui/info-tooltip/info-tooltip.js [hunk 3]
```diff
@@ -49,10 +48,6 @@ InfoTooltip.propTypes = {
    * Shows position of the tooltip
    */
   position: PropTypes.oneOf(['top', 'left', 'bottom', 'right']),
-  /**
-   * Set if the tooltip wide
-   */
-  wide: PropTypes.bool,
   /**
    * Add custom CSS class for container
    */
```
Comment (georgewrmarshall) [inline ui/components/ui/info-tooltip/info-tooltip.js:53]: Did a search for `wide` prop and its only used in one instance that probably can be the same width as the other InfoTooltips

Screen Shot 2022-06-20 at 1 37 59 PM


Screen Shot 2022-06-20 at 1 24 42 PM

File: ui/components/ui/info-tooltip/info-tooltip.stories.js [hunk 4]
```diff
@@ -17,7 +17,6 @@ export default {
       control: 'select',
       options: ['top', 'left', 'bottom', 'right'],
     },
-    wide: { control: 'boolean' },
     containerClassName: { control: 'text' },
     wrapperClassName: { control: 'text' },
     iconFillColor: { control: 'text' },
```
Comment (georgewrmarshall) [inline ui/components/ui/info-tooltip/info-tooltip.stories.js:22]: Used once and removed. See comment on `ui/components/ui/info-tooltip/info-tooltip.js`

File: ui/components/ui/tooltip/index.scss [hunk 5]
```diff
@@ -1,30 +1,44 @@
...
+  &[x-placement^=left] .tippy-tooltip.tippy-tooltip--mm-custom-theme [x-arrow] {
+    border-left-color: var(--color-background-default);
+  }
 
-.tippy-popper[x-placement^=bottom] .white-theme [x-arrow] {
-  border-bottom-color: var(--color-background-default);
+  &[x-placement^=bottom] .tippy-tooltip.tippy-tooltip--mm-custom-theme [x-arrow] {
+    border-bottom-color: var(--color-background-default);
+  }
 }
```
Comment (georgewrmarshall) [inline ui/components/ui/tooltip/index.scss:44]: The meat and potatoes of this PR. Updating the Tooltip styles and custom theme name

File: ui/components/ui/tooltip/tooltip.js [hunk 6]
```diff
@@ -82,7 +82,7 @@ export default class Tooltip extends PureComponent {
         style={style}
         title={disabled ? '' : title}
         trigger={trigger}
-        theme={theme}
+        theme={`tippy-tooltip--mm-custom ${theme}`} // Required for correct theming
         tabIndex={tabIndex || 0}
         tag={tag}
       >
```
Comment (georgewrmarshall) [inline ui/components/ui/tooltip/tooltip.js:88]: Adding default theme that handles light/dark mode colors but allowing for custom theme functionality if more customization is needed e.g. InfoTooltip max width

File: ui/components/ui/tooltip/tooltip.stories.js [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+);
+
+HTML.args = {
+  interactive: true,
+  html: (
+    <Box>
+      And includes a <a href="#">link</a>
+    </Box>
+  ),
+};
```
Comment (georgewrmarshall) [inline ui/components/ui/tooltip/tooltip.stories.js:92]: Adding Tooltip stories.

File: ui/pages/swaps/fee-card/fee-card.js [hunk 8]
```diff
@@ -109,7 +109,6 @@ export default function FeeCard({
                     }
                     containerClassName="fee-card__info-tooltip-content-container"
                     wrapperClassName="fee-card__row-label fee-card__info-tooltip-container"
-                    wide
                   />
                 </>
               }
```
Comment (georgewrmarshall) [inline ui/pages/swaps/fee-card/fee-card.js:114]: Removing the once instance of the `wide` prop

Screen Shot 2022-06-20 at 1 37 59 PM

Looks fine with same width as all the other InfoTooltips

Screen Shot 2022-06-20 at 1 23 15 PM

File: ui/pages/swaps/main-quote-summary/main-quote-summary.js [hunk 9]
```diff
@@ -93,7 +93,6 @@ export default function MainQuoteSummary({
               position="bottom"
               html={amountToDisplay}
               disabled={ellipsedAmountToDisplay === amountToDisplay}
-              theme="white"
             >
               <span
                 className="main-quote-summary__quote-large-number"
```
Comment (georgewrmarshall) [inline ui/pages/swaps/main-quote-summary/main-quote-summary.js:98]: Removing other unneeded theme props in favour of default theme: `tippy-tooltip--mm-custom-theme`

File: ui/pages/swaps/view-quote/view-quote-price-difference.js [hunk 10]
```diff
@@ -73,11 +73,7 @@ export default function ViewQuotePriceDifference(props) {
...
                 </div>
-                <Tooltip
-                  position="bottom"
-                  theme="white"
-                  title={t('swapPriceImpactTooltip')}
-                >
+                <Tooltip position="bottom" title={t('swapPriceImpactTooltip')}>
                   <i className="fa fa-info-circle" />
                 </Tooltip>
               </Box>
```
Comment (georgewrmarshall) [inline ui/pages/swaps/view-quote/view-quote-price-difference.js:79]: Removing other unneeded theme props in favour of default theme: `tippy-tooltip--mm-custom-theme`

**Review by jpuri — APPROVED** [review]
Thanks for the code cleanup 👍

**Review by darkwing — APPROVED** [review]
Awesome work!  Approved.

In the future, from a design perspective, we should really find a way to make the "layers" easier for users to see.  For example:

Layers

Here we have 3 layers with the same background, so it's kinda difficult to see their definitions.

**Comment by georgewrmarshall** [comment]
@darkwing completely agree! I think a darker shadow should help here. Hoping to get shadows into the design tokens library this week. I'll create a ticket for it.
