### PR TITLE
fix: pass safeChains prop from parent components to TokenCell cp-12.20.0

### LINKED ISSUE #33466: [Bug]: The extension exhibits performance degradation, then crashes with the "MetaMask Lavamoat snow has crashed." error
### Describe the bug

I'm experiencing very similar behavior to what was described here for Firefox https://github.com/MetaMask/metamask-extension/issues/33403. The extension exhibits performance degradation, particularly during quote fetching for swap/bridge txs, and eventually becomes unresponsive. However, instead of simply stopping (as seen in Firefox), the extension crashes with the error "MetaMask Lavamoat snow has crashed."

While reloading the extension temporarily resolves the crash, the performance issues persist and the extension continues to experience reduced functionality. 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/713591c6-dbf0-418f-932e-03f3fbc5ac96

### Steps to reproduce

1. Install 12.20.0
2. Start swaps / bridge

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.20.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

Changes:
- Extracts native currency symbol logic into a reusable `getSafeNativeCurrencySymbol` util function, which looks up the symbol by chainId from a list of SafeChains
- Remove `useSafeChains` call from TokenCell and move it to parent components to minimize instances of `safeChains` in memory
- Pass `safeChains` prop down from parent components until it is propagated to TokenCell

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33579?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33466

## **Manual testing steps**

1. Load extension and flip back and forth betweeen Token tab, Activity tab and asset pages
2. Take a memory snapshot
3. Verify that retained objects don't include `{ safeChains }`

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/hooks/useSafeNativeCurrencySymbol.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ */
+export const useSafeNativeCurrencySymbol = (
+  chainId: string,
+): string | undefined => {
+  const { safeChains } = useSafeChains();
+
+  const safeChainsRef = useRef(safeChains);
+
+  useEffect(() => {
+    safeChainsRef.current = safeChains;
```
Comment (Gudahtt) [inline ui/hooks/useSafeNativeCurrencySymbol.ts]: What is the purpose of using a ref here? This doesn't seem to be doing anything different from using `safeChains` directly below

Comment (micaelae) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: `safeChains` is a new object during each render so this prevents the useMemo from recalculating unnecessarily. Now that you point this out, I think `useSafeChains` needs to memoize the safeChains object instead of using a ref here. Trying this out locally

Comment (Gudahtt) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: Given that `useSafeChains` internally keeps the safe chain data in state, and that state only changes _once_ (it has an initial value, then gets updated with the fetch result), I'd expect the `safeChains` data here to only have those two values as well.

`useSafeChains` will execute each render, but the value returned won't change each render.

If I'm understanding this correctly at least.

Comment (micaelae) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: I decided to keep the current ref in `useSafeNativeCurrencySymbol` and leave `useSafeChains` as it is. I would've needed to do a deep-equal check on each safeChains result in order to memoize it, which reintroduces some of the performance issues we had before.

I added comments to explain why useRef is needed in this useSafeChains consumer

Comment (Gudahtt) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: >I would've needed to do a deep-equal check on each safeChains result in order to memoize it

Sorry I'm still not following. Why would this be needed?

I see that you added a comment saying that `safeChains` changes each render, but I don't think it does. At least I see no reason why it would. State doesn't change each render, not unless `setState` is called.

Comment (Gudahtt) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: I just tested this locally to confirm:

```typescript
/**
 * Custom hook to get the native currency symbol for a given chain ID
 *
 * @param chainId - The chain ID to get the native currency symbol for
 * @returns The native currency symbol or undefined if not found
 */
export const useSafeNativeCurrencySymbol = (
  chainId: string,
): string | undefined => {
  const { safeChains } = useSafeChains();

  return useMemo(() => {
    if (!safeChains || !chainId) {
      return undefined;
    }

    const decimalChainId =
      isStrictHexString(chainId) && parseInt(hexToDecimal(chainId), 10);

    if (typeof decimalChainId !== 'number') {
      return undefined;
    }

    return safeChains.find(
      (chain) => chain.chainId === decimalChainId.toString(),
    )?.nativeCurrency?.symbol;
  }, [safeChains, chainId]);
};
```

As expected, the memoized function ran twice upon mount (once before the fetch call resolved, once after). Not once per render. No deep equals call needed

Comment (micaelae) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: Without useRef this is what happens:
1. Each TokenCell in the asset list uses `useSafeNativeCurrencySymbol`, which calls `useSafeChains`
2. `useSafeChains` fetches the safeChains data (this gets cached so there is only 1 network call) each time the Overview page's Tokens tab mounts and calls setState with a new object each time 
3. This causes `useSafeNativeCurrencySymbol` to recalculate the symbol for every token every time the tab renders, because each token has its own `safeChains` object
4. I also see multiple safeChains objects added to retained memory after switching Tokens<>Activity with this approach

Comment (micaelae) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: Since we know useSafeChains will always return the latest safeChains, I set it to a ref to prevent the recalculation from happening. So now the symbol logic only runs based on chainId

Comment (Gudahtt) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: In point 3, if by "each time the tab renders" you mean "each time the tab is _mounted_", then that does match what I'm seeing.

Sharing the same chain dataset between each token cell is something we could achieve by lifting this state up to the parent component, or putting it in Redux or the background state. You lifted the state up to the parent in the other PR for example.

But using a ref doesn't achieve that. There is still a separate copy of this state per cell. Refs are per-component-instance. It's still unclear to me what you are trying to achieve by using a ref here.

Comment (Gudahtt) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: Additionally, this appears to be broken because we're not re-rendeirng when the ref changes, so we're always using the initial value (an empty array). i.e. we could replace the entire hook with a hard-coded `undefined`, as it is currently implemented.

Comment (micaelae) [reply ui/hooks/useSafeNativeCurrencySymbol.ts]: Good points. I reverted the PR back to a version that prop-drills `safeChains` - can you take a look please?

File: ui/components/app/assets/asset-list/asset-list.tsx [hunk 2]
```diff
@@ -53,7 +62,7 @@ const AssetList = ({ onClickAsset, showTokensLinks }: AssetListProps) => {
   return (
     <>
       <AssetListControlBar showTokensLinks={shouldShowTokensLinks} />
-      <TokenListContainer onClickAsset={onClickAsset} />
+      <TokenListContainer onClickAsset={onClickAsset} safeChains={safeChains} />
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/asset-list/asset-list.tsx:65]: Very nice pulling out the safeChains from each individual list item!

**Review by Prithpal-Sooriya — APPROVED** [review]

File: ui/pages/settings/networks-tab/networks-form/use-safe-chains.ts [hunk 3]
```diff
@@ -43,6 +45,25 @@ export const useSafeChains = () => {
   return safeChains;
 };
 
+export const getSafeNativeCurrencySymbol = (
```
Comment (Gudahtt) [inline ui/pages/settings/networks-tab/networks-form/use-safe-chains.ts:48]: Nit: A TSDoc block here would be helpful for explaining what this is for.

Also maybe this should be refactored so it's no longer sitting here in the "Settings -> Networks form" directory? It's used well outside of that scope now. But that's a pre-existing issue

Maybe later as a follow-up PR, after we get this release out

**Review by gambinish — APPROVED** [review]

File: ui/components/multichain/account-overview/account-overview-tabs.tsx [hunk 4]
```diff
@@ -125,6 +129,7 @@ export const AccountOverviewTabs = ({
               <DeFiTab
                 showTokensLinks={showTokensLinks ?? true}
                 onClickAsset={onClickDeFi}
+                safeChains={safeChains}
```
Comment (Gudahtt) [inline ui/components/multichain/account-overview/account-overview-tabs.tsx:132]: Is this getting passed down through? I see that `DeFiTab` uses `AssetListProps` for its prop type, but in practice it's destructuring it and only using `onClickAsset`.

File: ui/components/app/assets/token-list/token-list.tsx [hunk 5]
```diff
@@ -26,12 +26,14 @@ import {
   MetaMetricsEventName,
 } from '../../../../../shared/constants/metametrics';
 import { MetaMetricsContext } from '../../../../contexts/metametrics';
+import { SafeChain } from '../../../../pages/settings/networks-tab/networks-form/use-safe-chains';
 
 type TokenListProps = {
   onTokenClick: (chainId: string, address: string) => void;
+  safeChains?: SafeChain[];
```
Comment (Gudahtt) [inline ui/components/app/assets/token-list/token-list.tsx:33]: I see that this is declared as optional. There is at least one place where it's not being passed in right now, in `ui/components/multichain/import-tokens-modal/import-tokens-modal.js`. Is this OK - is this really OK to omit? It seems like the component won't work correctly if this is omitted, but maybe I'm missing something.

If it is indeed required, maybe we should make it required here.

File: ui/components/multichain/account-overview/account-overview-tabs.tsx (hunk 4 above)
Comment (Gudahtt) [reply ui/components/multichain/account-overview/account-overview-tabs.tsx:132]: Maybe it's not actually needed here, but you just passed it in because the prop type expected it? If so, consider this as a non-blocking suggestion, but perhaps it would be better to update the prop type to better represent what's passed in instead (e.g. `Pick<AssetListProps, 'onClickAsset'>` instead of `AssetListProps`)

File: ui/components/app/assets/token-list/token-list.tsx (hunk 5 above)
Comment (Gudahtt) [reply ui/components/app/assets/token-list/token-list.tsx:33]: Oh wait, that other instance is a separate component that just happens to have the same name, nevermind!

Comment (Gudahtt) [reply ui/components/app/assets/token-list/token-list.tsx:33]: Well, the question about whether this should be a required prop is still valid. But consider it a non-blocking suggestion.

```suggestion
  safeChains: SafeChain[];
```

**Review by Gudahtt — APPROVED** [review]
LGTM! Just a couple of minor suggestions that we can consider addressing separately.

**Review by vinnyhoward — APPROVED** [review]
