### PR TITLE
fix: change in number format to fix loss of precision for very big values

### LINKED ISSUE #25755: [Bug]: Precision is lost displaying Permit value in simulation and data tree
### Describe the bug

formatAmount in `ui/pages/confirmations/components/simulation-details/formatAmount.ts` utilizes Intl.NumberFormat, which requires a BigInt or number passed to it causing a loss in precision when computing large numbers. It does not accept strings. Currently, it will display 0s for the digits after 15 digits.

we should update the logic to preserve the precision

Example:
- 30001231231212312138768 → 30,001,231,231,212,312,000,000
- 115792089237316195423570985008687907853269984665640564039457584007913129639935 → 115,792,089,237,316,200,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000

Related: https://github.com/MetaMask/metamask-extension/pull/25741
Related: https://github.com/MetaMask/metamask-extension/pull/25438

### Expected behavior

_No response_

### Steps to reproduce

1. run `yarn storybook`
2. go to http://localhost:6006/?path=/story/pages-confirmations-confirm-signatures-signedtypeddatav3orv4--permit-story&args=msgParams.data:3.0001231231212312e+22
3. copy and paste the following into data
```
"{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Permit\":[{\"name\":\"owner\",\"type\":\"address\"},{\"name\":\"spender\",\"type\":\"address\"},{\"name\":\"value\",\"type\":\"uint256\"},{\"name\":\"nonce\",\"type\":\"uint256\"},{\"name\":\"deadline\",\"type\":\"uint256\"}]},\"primaryType\":\"Permit\",\"domain\":{\"name\":\"MyToken\",\"version\":\"1\",\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\",\"chainId\":1},\"message\":{\"owner\":\"0x935e73edb9ff52e23bac7f7e043a1ecd06d05477\",\"spender\":\"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4\",\"value\":30001231231212312138768,\"nonce\":0,\"deadline\":50000000000}}"
```

### Error messages or log output

_No response_

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

fix loss of precision for very big values in signature simulations

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25755

## **Manual testing steps**

1. Create a permit request of arbitrary high value like `115792089237316195423570985008687907853269984665640564039457584007913129639935`
2. As you submit the request ensure that precision is not lost

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/simulation-details/formatAmount.ts [hunk 1]
```diff
@@ -80,7 +80,8 @@ export function formatAmount(locale: string, amount: BigNumber): string {
     MAX_SIGNIFICANT_DECIMAL_PLACES - digitsLeftOfDecimal + 1,
   );
 
-  return new Intl.NumberFormat(locale, {
-    maximumFractionDigits,
-  } as Intl.NumberFormatOptions).format(amount.toNumber());
+  return amount.toFormat(maximumFractionDigits);
```
Comment (dbrans) [inline ui/pages/confirmations/components/simulation-details/formatAmount.ts:83]: Hi @jpuri! To preserve the internationalization but still show all decimals, you could use BigInt.toLocaleString:

```js
if (maximumFractionDigits === 0) {
  // No decimals to display – we can use BigInt to localize without loss of precision.
  return BigInt(amount.toFixed());
} else {
  // At most 4 (MAX_SIGNIFICANT_DECIMAL_PLACES + 1) significant digits – Use Intl.NumberFormat to localize
  return new Intl.NumberFormat(locale, {
      maximumFractionDigits,
    } as Intl.NumberFormatOptions).format(amount.toNumber());
}
```

Here's an example:
```js
  const bigNum = BigNumber(
    "115792089237316195423570985008687907853269984665640564039457584007913129639935"
  );
  const bigInt = BigInt(bigNum.toFixed());
  console.log(bigInt.toLocaleString());
  // 115,792,089,237,316,195,423,570,985,008,687,907,853,269,984,665,640,564,039,457,584,007,913,129,639,935

```

Comment (jpuri) [reply ui/pages/confirmations/components/simulation-details/formatAmount.ts:83]: Hey @dbrans : we still lose precision for long values with decimals.

Comment (dbrans) [reply ui/pages/confirmations/components/simulation-details/formatAmount.ts:83]: Hey Jyoti, the loss of decimal places for large numbers is [intentional](https://github.com/MetaMask/metamask-extension/blob/694ecf8d583041d391e4028e65f6092eaa5369c3/ui/pages/confirmations/components/simulation-details/formatAmount.ts#L28-L31). This was decisionwas made  by @bschorchit and Saya [here](https://www.notion.so/Simulation-Release-Candidate-Testing-Feedback-7dd07ced652f4a2b8dc2ae96cedc69a4?d=15202499537e4404bdaf38f67c4803dd&pvs=4#930c7e1aef8049caa203953fa88dd23a).

Comment (jpuri) [reply ui/pages/confirmations/components/simulation-details/formatAmount.ts:83]: for instance this number:

`1157920892373161954235709850086879078532699846656405640394575.84007913129639935`

formats as `1,157,920,892,373,162,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000`

Comment (dbrans) [reply ui/pages/confirmations/components/simulation-details/formatAmount.ts:83]: Jyoti, you may have to play with it since we use a different version on BigNumber, but here is a [sandbox where it is working](https://codesandbox.io/p/sandbox/bignumber-js-forked-3nvlft?file=%2Fsrc%2Findex.js).
```js
  const bigNum = BigNumber(
    "1157920892373161954235709850086879078532699846656405640394575.84007913129639935"
  );
  const bigInt = BigInt(bigNum.toFixed(0));
  console.log(bigInt.toLocaleString("fr"));
  // 1 157 920 892 373 161 954 235 709 850 086 879 078 532 699 846 656 405 640 394 576
```

Comment (jpuri) [reply ui/pages/confirmations/components/simulation-details/formatAmount.ts]: I see ur point, I updated the PR. Please review.

Comment (jpuri) [reply ui/pages/confirmations/components/simulation-details/formatAmount.ts]: Hey @dbrans : I found that this fix is working in jest but for reason blowing up in extension.

File: ui/pages/confirmations/components/simulation-details/formatAmount.ts [hunk 2]
```diff
@@ -80,6 +80,18 @@ export function formatAmount(locale: string, amount: BigNumber): string {
...
   );
 
+  if (maximumFractionDigits === 0) {
+    return new Intl.NumberFormat(locale, {
+      maximumFractionDigits,
+    } as Intl.NumberFormatOptions).format(
+      // string is valid parameter for format function
+      // for some reason it gives TS issue
+      // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format#number
+      amount.toFixed(0) as unknown as number,
```
Comment (dbrans) [inline ui/pages/confirmations/components/simulation-details/formatAmount.ts:90]: Awesome find!

In that case, we don't need the `if (maximumFractionDigits === 0) {` above... we can have the same code path for all amounts here.

**Review by digiwand — APPROVED** [review]
Great fix!

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by digiwand** [comment]
Cherry-pick to V12.1.0 https://github.com/MetaMask/metamask-extension/pull/26496
