### PR TITLE
Show warning when network request for fee market estimates fails

### LINKED ISSUE #11708: EIP-1559 - does not fall back to gas limit and gas price when estimates are not available
**Steps to reproduce**

1. Login to the extension
2. Switch networks to Rinkeby Testnet 
3. Click the Send button on the Home page
4. Select a recipient on the Add Recipient page
5. Click the Max amount button on the Send page, then click Next
6. Click the Edit link in the Estimate gas fee section
7. Wait for new estimates to be returned from `/suggestedGasFee` endpoint
8. Block `/suggestedGasFee` request, and wait for the request to be made again

**Expected behavior**
Fall back to Gas Limit and Gas Price

**Screenshots**

https://user-images.githubusercontent.com/53189696/127740404-3c904087-5c1a-4056-a087-a398bc9a29da.mov

### PR DESCRIPTION
**Pull request by danjm**
Fixes #11708

If the user is on an EIP-1559 network, and opens the popover, but the fetch for low, medium and high gas estimates has failed, we show a warning.

https://user-images.githubusercontent.com/7499938/127905073-0bc4fc80-3714-418f-834a-b69c1f52a364.mp4

### CODE REVIEW

File: ui/components/app/edit-gas-display/edit-gas-display.component.js [hunk 1]
```diff
@@ -78,16 +80,19 @@ export default function EditGasDisplay({
   );
 
   const networkSupports1559 = useSelector(isEIP1559Network);
-  const showTopError = balanceError;
+  const showTopError = balanceError || estimatesUnavailableWarning;
```
Comment (adonesky1) [inline ui/components/app/edit-gas-display/edit-gas-display.component.js:83]: @danjm is there a scenario in which we want to show both of these errors?

**Review by adonesky1 — APPROVED** [review]
One small question but otherwise LGTM!

**Review by darkwing — APPROVED** [review]
