### PR TITLE
use etherscan-link customBlockExplorer methods with customNetwork usage tracking

### LINKED ISSUE #10041: Custom rpc block explorer links are broken
all assets under all custom RPCs go to broken link on Metamask when trying to "view on etherscan"

**Steps to reproduce**
1. add a custom RPC network, such as [binance](https://docs.binance.org/smart-chain/wallet/metamask.html)
2. add a custom asset
3. Click the asset to go to the asset page
4. Click the three-dot menu and select 'view on etherscan'
5. See a 500 error page on etherscan

### PR DESCRIPTION
**Pull request by adonesky1**
Fixes: #10041, #7864

Explanation:  Makes use of the blockExplorer functionality that was lifted and adapted from local util methods to the etherscan-link library that we maintain. 
Per @Gudahtt's comment in the [issue](https://github.com/MetaMask/metamask-extension/issues/10041#issuecomment-742949233), I added segment tracking events everywhere these methods are called so that we can gain some insight into the custom network block explorers that are being used. 

As a part of this PR I delved a bit into our use of Segment and feel like we should consider making a file with Segment constants (containing reusable consts for types of "Category", "Event" atleast) to make the schema more unified and accessible to those adding new segment event calls.

I expect that the segment event portion of this PR will require some discussion.

Manual testing steps:  
Check that block explorer links are working on custom (and non-custom) networks in the following places:
1. Account hamburger menu
2. Asset Hamburger menu
3. Token Hamburger menu
4. Swaps quote page
5. Transaction Activity Log and List items
6. Browser confirmation notifications

Segment testing may require some discussion.

### CODE REVIEW

File: ui/components/app/menu-bar/account-options-menu.js [hunk 1]
```diff
@@ -51,10 +60,14 @@ export default function AccountOptionsMenu({ anchorElement, onClose }) {
     },
   });
 
-  const keyring = useSelector(getCurrentKeyring);
-  const chainId = useSelector(getCurrentChainId);
-  const rpcPrefs = useSelector(getRpcPrefsForCurrentProvider);
-  const selectedIdentity = useSelector(getSelectedIdentity);
+  const customBlockExplorerLinkClickedEvent = useNewMetricEvent({
```
Comment (brad-decker) [inline ui/components/app/menu-bar/account-options-menu.js:63]: Do we think this is the correct way to do this ? clicked view on etherscan vs block explorer? OR should we do 'clicked view on block explorer' and put the blockexplorer domain name in the event details?

Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:63]: Fair point. I wasn't sure how we wanted this to fit into our segment schema / analytics. But you're probably right? Is there someone in specific that handles the segment analytics and might have thoughts/preferences here?

Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:63]: @brad-decker ^

Comment (brad-decker) [reply ui/components/app/menu-bar/account-options-menu.js:63]: Sorry about the delay. Lorenzo is the one to talk to, lets start a conversation with him in slack.

Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js]: @brad-decker made changes consolidate segment events.

File: ui/components/app/menu-bar/account-options-menu.js [hunk 2]
```diff
@@ -51,10 +54,14 @@ export default function AccountOptionsMenu({ anchorElement, onClose }) {
...
 
-  const keyring = useSelector(getCurrentKeyring);
-  const chainId = useSelector(getCurrentChainId);
-  const rpcPrefs = useSelector(getRpcPrefsForCurrentProvider);
-  const selectedIdentity = useSelector(getSelectedIdentity);
+  const blockExplorerLinkClickedEvent = useNewMetricEvent({
+    category: 'Navigation',
+    event: 'Clicked Block Explorer Link',
+    properties: {
+      link_type: 'Account Tracker',
```
Comment (brad-decker) [inline ui/components/app/menu-bar/account-options-menu.js:61]: We still would want the domain here, so that we could segment the charts out by domain, yeah?

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/components/app/menu-bar/account-options-menu.js (hunk 2 above)
Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:61]: We add the network as a property higher up:
Screen Shot 2021-05-14 at 6 05 27 PM

Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:61]: Though perhaps we want the block explorer url in addition? What do you think?

Comment (brad-decker) [reply ui/components/app/menu-bar/account-options-menu.js:61]: Sorry I meant the domain of the block explorer -- if possible we should do domain and then the rest of the path as separate properties I think

Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:70]: @brad-decker added `block_explorer_domain `!

File: ui/components/app/menu-bar/account-options-menu.js [hunk 3]
```diff
@@ -2,26 +2,44 @@ import React from 'react';
...
   const history = useHistory();
+
+  const keyring = useSelector(getCurrentKeyring);
+  const chainId = useSelector(getCurrentChainId);
+  const rpcPrefs = useSelector(getRpcPrefsForCurrentProvider);
+  const selectedIdentity = useSelector(getSelectedIdentity);
+
+  const getBlockExplorerDomain = () => {
+    if (rpcPrefs?.blockExplorerUrl) {
+      return new URL(rpcPrefs?.blockExplorerUrl)?.hostname;
```
Comment (brad-decker) [inline ui/components/app/menu-bar/account-options-menu.js:36]: why not just run this new URL() code on the result of `getAccountLink` to avoid extra logic checks and potential mismatches if implementations change in etherscan-link?

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/components/app/menu-bar/account-options-menu.js (hunk 3 above)
Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:36]: Good point. I'll make this change.

File: ui/components/app/menu-bar/account-options-menu.js [hunk 4]
```diff
@@ -2,26 +2,46 @@ import React from 'react';
...
+  const addressLink = getAccountLink(address, chainId, rpcPrefs);
+
+  const getBlockExplorerDomain = () => {
+    if (rpcPrefs?.blockExplorerUrl) {
+      return new URL(addressLink)?.hostname;
+    } else if (['0x1', '0x3', '0x4', '0x5', '0x2a'].includes(chainId)) {
+      return 'etherscan.io';
+    }
+    return '';
+  };
```
Comment (brad-decker) [inline ui/components/app/menu-bar/account-options-menu.js:43]:
```suggest
const blockExplorerUrl = new URL(addressLink)?.hostname;
```

This is what I meant, the logic duplicated extends to the '0x1'...etc checks. Sorry if I wasn't clear enough.

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/components/app/menu-bar/account-options-menu.js (hunk 4 above)
Comment (brad-decker) [reply ui/components/app/menu-bar/account-options-menu.js:43]: this is what I kind of meant, you don't need any of this logic just use the hostname. Its even fine if we get rinkeby.etherscan.io that's valuable information to include in the events doesn't have to be normalized so that all testnets say 'etherscan.io'

Comment (brad-decker) [reply ui/components/app/menu-bar/account-options-menu.js:43]: Sorry for not being clear enough in my original feedback @adonesky1

Comment (adonesky1) [reply ui/components/app/menu-bar/account-options-menu.js:43]: Yup 😬   my bad. This makes more sense 👍

**Review by brad-decker — COMMENTED** [review]
Code looks good. I'm going to take this for a spin and make sure I don't run into any issues across many chains. Sorry for the delay I'll try and get final review in before noon tomorrow.

**Comment by adonesky1** [comment]
> Code looks good. I'm going to take this for a spin and make sure I don't run into any issues across many chains. Sorry for the delay I'll try and get final review in before noon tomorrow.

no worries! Sorry I kept pushing stupid commits. Going to push a small one with the lint fix.

**Review by brad-decker — APPROVED** [review]
LGTM!
