### PR TITLE
fix: cp-12.18.0 Updated address in Receive Modal

### LINKED ISSUE #32518: [Bug]: Wallet Address missing from QR Code Screen
### Describe the bug

The receive QR code screen does not contain the wallet address on EVM or Solana account (2nd screenshot), whereas in the current GA version it does.

Copy address link + icon is also in GA version and missing in beta

### Expected behavior

Add:

- Wallet Address to the QR Code Screen
- Add `Copy Address` and Icon to screen

### Screenshots/Recordings

Image 
** Current GA release

Image
** Beta Version

### Steps to reproduce

1. Go to the QR Code Screen

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.18.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR is to show address in Receive Modal

## **Related issues**

Fixes: #32518 

## **Manual testing steps**

1. Run extension
2. Click on Receive button
3. address should show up below QR code

### **Before**
Screenshot 2025-05-09 at 2 34 44 PM

### **After**
Screenshot 2025-05-09 at 2 33 59 PM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/ui/qr-code-view/qr-code-view.tsx [hunk 1]
```diff
@@ -82,6 +102,47 @@ function QrCodeView({
...
+        color={TextColor.primaryDefault}
+        className="qr-code__copy-button"
+        data-testid="address-copy-button-text"
+        onClick={() => {
+          handleCopy(checksummedAddress);
+          trackEvent({
+            category: MetaMetricsEventCategory.Accounts,
+            event: MetaMetricsEventName.PublicAddressCopied,
+            properties: {
+              location: 'Account Details Modal',
```
Comment (darkwing) [inline ui/components/ui/qr-code-view/qr-code-view.tsx:134]: We should change this to "Receive Modal"

Comment (darkwing) [reply ui/components/ui/qr-code-view/qr-code-view.tsx:134]: Nevermind, I see this is a deeper component.

**Review by darkwing — APPROVED** [review]

File: ui/components/ui/qr-code-view/qr-code-view.tsx [hunk 2]
```diff
@@ -82,6 +102,47 @@ function QrCodeView({
...
+      <Box
+        display={Display.Flex}
+        marginBottom={4}
+        gap={2}
+        alignItems={AlignItems.center}
+        color={TextColor.primaryDefault}
+        className="qr-code__copy-button"
+        data-testid="address-copy-button-text"
+        onClick={() => {
+          handleCopy(checksummedAddress);
```
Comment (gambinish) [inline ui/components/ui/qr-code-view/qr-code-view.tsx:129]: We're confident that this is case sensitive?

**Review by gambinish — APPROVED** [review]
Looks good to me. I noticed that when scanning the QR code from my MM Mobile app on Prod, that it was not recognizing the Non-evm account as a valid QR code.

I think this is probably expected? Evm still works as expected.
