### PR TITLE
fix: cp-13.9.0 cannot read properties of undefined (allIgnoredTokens)

### LINKED ISSUE #37659: TypeError: Cannot read properties of undefined (reading 'a3711955-392d-410c-b4d6-aa064b9f3fb3')
Sentry Issue: [METAMASK-XZP1](https://metamask.sentry.io/issues/7012682395/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'a3711955-392d-410c-b4d6-aa064b9f3fb3')
  at Array.map (<anonymous>)
  at exports.selectBalanceForAllWallets (ui/selectors/assets.ts:739:5)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
...
(36 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by juanmigdr**
## **Description**
Fix sentry error saying alIgnoredTokens is undefined. I could not repro but believe this is the fix

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37660?quickstart=1)

## **Changelog**

CHANGELOG entry: fix cannot read properties of undefined (allIgnoredTokens)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37659 & https://consensyssoftware.atlassian.net/browse/ASSETS-1767

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Defaults `getAllIgnoredAssets` to `EMPTY_OBJECT` to prevent undefined access errors.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0230527f81bea701d72e89369f0f20eebb185264. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by sahar-fehri — APPROVED** [review]

File: ui/selectors/assets.ts [hunk 1]
```diff
@@ -111,7 +111,7 @@ export function getAssetsMetadata(state: AssetsState) {
  * @returns An object containing all ignored assets.
  */
 export function getAllIgnoredAssets(state: AssetsState) {
-  return state.metamask.allIgnoredAssets;
+  return state.metamask.allIgnoredAssets ?? EMPTY_OBJECT;
```
Comment (bergarces) [inline ui/selectors/assets.ts:114]: Ok with this as it solves the issue for now, but we either need to:
- Ensure that a newly created instance of the controller holding this state creates `allIgnoredAssets` if it's not present.
- Create a migration so that state is created as well (I don't like this one as I believe that controller is behind code fencing)

**Review by bergarces — APPROVED** [review]

File: ui/selectors/assets.ts (hunk 1 above)
Comment (juanmigdr) [reply ui/selectors/assets.ts:114]: I have tested updating from 13.7.0 to 13.8.0 and I do see the field being created thats why I cannot really repro. I have fixed it this way due to seeing this kind of implementation here:
image
