### PR TITLE
fix: cp-13.4.0 nft full image close crash

### LINKED ISSUE #36130: [Bug]: Crash with error Value is not a safe integer. Use `hexToBigInt` instead when clicking X to close NFT image
View issue in GitHub: https://github.com/MetaMask/metamask-extension/issues/36130

**Describe the bug**

When clicking on the `X` symbol to close the NFT image, the extension crashes with error:

`Value is not a safe integer. Use hexToBigInt`

**Expected behavior**

No crash

**Screenshots/Recordings**

https://github.com/user-attachments/assets/3449b515-a3b7-4637-9fdc-10e88e04f488

Image

**Steps to reproduce**

1. Go to NFT tab
2. Click on NFT
3. Cick on NFT image to enlarge
4. Close from `X`
5. Notice crash

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.4.0

**Build type**

None

**Browser**

Chrome, Firefox

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

we were routing to the wrong path. Also improved by using a history back functionality

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36162?quickstart=1)

## **Changelog**

CHANGELOG entry: fix crash when closing a full nft image

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36130

## **Manual testing steps**

See GH issue repro steps.

### **After**

https://www.loom.com/share/b9a7e3d1816c4007aa58110d4ee2e7dc?sid=391143a7-cdbc-4b94-ab08-8dd83ffe68b9

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/nfts/nft-details/nft-full-image.tsx [hunk 1]
```diff
@@ -94,7 +107,7 @@ export default function NftFullImage() {
               size={ButtonIconSize.Sm}
               ariaLabel={t('back')}
               iconName={IconName.Close}
-              onClick={() => history.push(`${ASSET_ROUTE}/${asset}/${id}`)}
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/nfts/nft-details/nft-full-image.tsx:97]: Key fix: we were missing the chainId on the path, so now that the details page uses it (and attempt to convert to CAIP/HEX) it crashes if it is missing.

**Review by salimtb — APPROVED** [review]

**Review by bergarces — APPROVED** [review]
