### PR TITLE
fix: fix duplicate token import from search

### LINKED ISSUE #36726: [Bug]: Duplicate token in asset list
### Describe the bug

A user is able to import the same token twice.

### Expected behavior

A user should not be able to import the same token twice.

### Screenshots/Recordings

https://github.com/user-attachments/assets/b7054fcd-f08e-4a85-bc4a-c9e94f743afc

### Steps to reproduce

1. Click on "import tokens"
2. Choose any token.
3. Notice the token is added successfully to the asset list
4. Re-import the same token
5. Notice the token is imported again to the list

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

13.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix the ability to add the same token twice from search.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36727?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed a bug that was causing the same token to be added twice from search

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36726

## **Manual testing steps**

1. Click on import tokens
2. Import any token from search
3. Notice the token is added successfully to list
4. Re-import the same token
5. The token should already be selected and you should not be able to re-select it

### **After**

https://github.com/user-attachments/assets/0e4e0913-e5b8-4bca-8edf-9130c08a4db7

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Unifies token existence checks to always use `checkExistingAllTokens` and removes `tokens` prop usage to prevent duplicate imports from search.
> 
> - **Import Token UI** (`ui/components/app/import-token/token-list`):
>   - **Duplicate Prevention Logic**: Always use `checkExistingAllTokens(address, chainId, accountAddress, allTokens)` to determine if a token is already added; remove `checkExistingAddresses` path.
>   - **Props Cleanup**: Remove `tokens` prop and related destructuring/usage.
>   - **Imports**: Drop `checkExistingAddresses` import; keep `checkExistingAllTokens`.
>   - **Behavior**: When filter matches current network, continue setting `results[i].chainId = currentNetwork?.chainId`.
> - **Container** (`token-list.container.js`):
>   - Stop mapping `state.metamask.tokens`; retain `allTokens` and `accountAddress`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 8decdaa5faaa01223000f72b921085138da95816. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by Unik0rnMaggie** [comment]
Using the build from [above](https://github.com/MetaMask/metamask-extension/pull/36727#issuecomment-3386428155): 

1. The token _cannot be added twice by using the token name_ in the Search bar

2. The token _can be added twice by using the contract address_ in the Search bar 

3. When clicking Setting, Import, buttons the dropdown appears to the left

After it is added, adding new networks makes the token display multiple times, in the tokens tab and DeFi tab:


https://github.com/user-attachments/assets/4ebee823-9d0b-4740-a884-6ec42e114b1f


https://github.com/user-attachments/assets/b549a6c5-e249-4872-ab22-2e81161a124a

Screenshot 2025-10-14 at 12 29 25


Screenshot 2025-10-14 at 12 44 12

Screenshot 2025-10-14 at 12 44 18

Screenshot 2025-10-14 at 12 44 38

File: ui/components/app/import-token/token-list/token-list.container.js [hunk 1]
```diff
@@ -3,11 +3,9 @@ import { getSelectedInternalAccount } from '../../../../selectors';
 import TokenList from './token-list.component';
 
 const mapStateToProps = (state) => {
-  const { tokens } = state.metamask;
   const { allTokens } = state.metamask;
   const { address } = getSelectedInternalAccount(state);
   return {
```
Comment (juanmigdr) [inline ui/components/app/import-token/token-list/token-list.container.js:8]: why did we remove tokens from the return statement? (For future reference)

**Review by juanmigdr — APPROVED** [review]

File: ui/components/app/import-token/token-list/token-list.container.js (hunk 1 above)
Comment (sahar-fehri) [reply ui/components/app/import-token/token-list/token-list.container.js:8]: The `tokens` has been removed from state and we now rely on `allTokens`

**Review by bergarces — APPROVED** [review]
