### PR TITLE
Remove global transaction state from send flow

### LINKED ISSUE #11677: Extension sends random cached addressed instead of the one entered
**Describe the bug**
1. Used the send function from my wallet to my other wallet
2. Transfer address was checked 2-3 times and was deemed to be correct
3. Wallet history show it was sent to the correct address but opening the linked block explorer transaction, it was sent to a different account

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Metamask extension
2. Click on send
3. Enter recipient
4. Click on Next
5. Click on Confirm

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
image
Failed to save the expanded view of this transaction but all values were consistent including the nonceswith the block explorer except the address

Block explorer: https://bscscan.com/tx/0x9766e7d7f6724b82c41a72f289d6bbb08c5adc8607c37447250371cdb6c9f12a

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: NA
 - Browser: Chrome
 - MetaMask Version: 9.8.2

**Additional context (Error Messages, etc.)**
Most likely it is related to how the extension handles the caching or idk. Luckily, I knew the owner of the wallet and had my little funds sent back to me. I suspect it is closely related to the "Contacts" feature of the extension

### PR DESCRIPTION
**Pull request by brad-decker**
## Explanation

As part of exploring possible causes of #11677 and came to the conclusion that, even though I could not reproduce the bug, that it was possible for the send slice to get polluted with bad data. There were two main problems with the structure of the send slice:

1. Upon every update to the transaction state we generated the txParams and kept them in the slice as well. txParams are a derivative of the other state tree values but under certain scenarios it was plausible that the txParams in state would become stale and not be an accurate representation of the rest of the state tree. To resolve this issue I removed the derivative state from the slice in #14701 
2. The transaction state in the send slice is global to the slice, meaning that the slice is "initiated" when navigating to the send page and the send page would clear the send slice state after the send flow ended...but it was plausible that a new send flow could be kicked off in some way while there was lingering state from the previous send in the tree. This would cause an issue where the transaction would get corrupted with the previous transaction's intent. 

This PR aims to alleviate the second point.

Send flow before this change:
1. User clicks send in the extension main screen.
2. If the user was on an asset page or clicked send from a token  asset, we'd dispatch `updateSendAsset` with the token details before routing the user to the send page.
3. The send page had a `useEffect` that would dispatch `initializeSendState` this would do things like fetch gas price estimations, set the validity of the state, etc. 
4. The transaction values such as recipient, amount, from and to were stored in a global state tree.
5. Upon leaving the send flow the send page would dispatch the `resetSendState` action that would set the tree back to default.

The same basic flow would happen upon editing a transaction, except that in addition to setting some global values the editTransaction method would be dispatched that also set the details of the edited transaction into the global state.

Send flow after this change:
1. user clicks send in the extension main screen
2. we dispatch `startNewTransaction` and include asset details in that call.
3. The send slice clears all previous draft transactions from state, which are now stored in an object in state that is no longer global. 
4. The send slice generates a new UUID and sets as the `currentTransactionUUID` in state, then creates a blank transaction in the `draftTransactions` object that is keyed by UUID.
5. The `initializeSendState` thunk is dispatched.
6. Once complete the user is routed to the send page. 
7. Upon leaving the send flow the state is cleared.

if editing a transaction a new 'editExistingTransaction' method is dispatched with the asset type and id of the transaction, but the rest of the flow is the same. 

### How does this help? 
1. All transaction values are kept inside an object that is keyed by a non deterministic UUID generated at the time the draft is created.  
2. When a new draft is created, all previous drafts are discarded as an additional fail safe to make sure that the new transaction has no chance to be confused with an older, stale one. 
3. We no longer manipulate the send state ahead of kicking off the send flow which makes the send flow less reliant upon side effects and makes it idempotent, in that it is less likely to have a different outcome based on the order of operations.

### Related Changes
1. A new 'getCurrentDraftTransaction' selector was added as a tool for all other selectors. Most selectors now call this selector to get either an empty object or the current draftTransaciton.
2. A lot of selectors have been updated to reflect the possibility that a draftTransaction does not exist. 
3. For some reason in some of our confirmation components we use the send slice selectors, I did not change this but we can be reasonably assured now that they aren't grabbing unrelated send state. 
4. The send slice has been reorganized a great deal to try and keep things alphabetical where possible. It is not always possible, especially in the selectors area, due to things being used before they are declared. 
5. More types and safer types have been added.
6. A number of helper methods were extracted from the send slice file to a helpers.js file in the send slice folder. This is to make the send slice less difficult to read.

## More Information
Fixes #11677 

### Before & After
The functionality and flow of the send page is unchanged, no E2E tests needed to be modified to make this work. 

## Manual Testing Steps
1. Test sending ETH, Tokens, Collectibles.
2. Test changing accounts, networks, and assets on the send flow.
3. Test changing the send amount in the send flow.
4. Test editing transactions.
5. Ensure that every transaction you create through the send flow results in a confirmation with matching details.
7. Check ENS, copy and paste, and manual address entry in the recipient fielld.
8. Test adding nicknames to addresses and see that the nickname is reflected in the send flow. 
9. Any other details related to the send flow.

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] Manual testing complete & passed
- [x] ~**IF** this PR fixes a bug, a test that _would have_ caught the bug has been added~
- [x] PR is linked to the appropriate GitHub issue
- [x] **IF** QA attention is required, "QA Board" label has been applied
- [ ] PR has been added to the appropriate release Milestone

### CODE REVIEW

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -280,164 +281,181 @@ export const RECIPIENT_SEARCH_MODES = {
...
-  }
+/**
+ * @type {DraftTransaction}
+ */
+export const draftTransactionInitialState = {
+  id: null,
+  status: SEND_STATUSES.VALID,
+  transactionType: TRANSACTION_ENVELOPE_TYPES.LEGACY,
+  userInputHexData: null,
+  editAccount: null,
```
Comment (brad-decker) [inline ui/ducks/send/send.js:362]: [self review] remove editAccount in favor of 'fromAccount'

File: ui/ducks/send/send.js [hunk 2]
```diff
@@ -513,27 +533,145 @@ export const computeEstimatedGasLimit = createAsyncThunk(
...
-    numberOfDecimals: 9,
-    toDenomination: GWEI,
-    fromNumericBase: 'dec',
-    toNumericBase: 'dec',
-    fromCurrency: ETH,
-    fromDenomination: GWEI,
-  });
-  const gasPriceAsNumber = Number(gasPriceInDecGwei);
-  return getGasPriceInHexWei(gasPriceAsNumber);
+function getAssetDetailsAndBalance(
```
Comment (brad-decker) [inline ui/ducks/send/send.js:565]: [self review] I would love for this function to be non side effect producing (currently it opens modals, shows loading indication, etc)... The only way I thought to do that was to interpret the error message in the consumer... but then not only are we using errors for control flow, we're also requiring duplication of that flow in multiple places (every callsite). @adonesky1 if you get a minute could you tell me if the logic in here matches the old upsetSendAsset flow?  You did most of the work on collectibles which is where i'm the least confident.

File: ui/ducks/send/send.js [hunk 3]
```diff
@@ -549,27 +687,23 @@ function getRoundedGasPrice(gasPriceEstimate) {
...
   async (_, thunkApi) => {
+    /**
+     * @typedef {Object} ReduxState
+     * @property {Object} metamask - Half baked type for the MetaMask object
+     * @property {SendState} send - the send state
+     */
+
+    /**
+     * @type {ReduxState}
+     */
```
Comment (brad-decker) [inline ui/ducks/send/send.js:698]: This can be typed using the AsyncThunk type from redux toolkit

**Review by joani24 — DISMISSED** [review]
Mto bom

File: lavamoat/build-system/policy-override.json [hunk 4]
```diff
@@ -55,6 +55,793 @@
         "eslint-plugin-jest>@typescript-eslint/experimental-utils>eslint-utils>eslint-visitor-keys": true
       }
     },
+    "gulp-watch>chokidar": {
```
Comment (brad-decker) [inline lavamoat/build-system/policy-override.json:58]: this stuff was needed for my local e2e, but not necessary here. I'll remove this file.

File: test/e2e/helpers.js [hunk 5]
```diff
@@ -110,7 +110,10 @@ async function withFixtures(options, testSuite) {
           '\n',
         )}`;
         if (failOnConsoleError) {
-          throw new Error(errorMessage);
+          errors.forEach((err) => {
```
Comment (brad-decker) [inline test/e2e/helpers.js:113]: this change was not helpful for debugging e2e console errors so i'll remove

File: ui/pages/send/send.js [hunk 6]
```diff
@@ -49,11 +47,8 @@ export default function SendTransactionScreen() {
   }, [dispatch]);
 
   useEffect(() => {
-    if (chainId !== undefined) {
-      dispatch(initializeSendState());
```
Comment (brad-decker) [inline ui/pages/send/send.js:53]: This is now handled in the actions file instead of here.

File: ui/ducks/send/helpers.js [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+ * after receiving a gasPrice from eth_gasPrice. First, the returned gasPrice
+ * was converted to GWEI, then it was converted to a Number, then in the send
+ * duck (here) we would use getGasPriceInHexWei to get back to hexWei. Now that
+ * we receive a GWEI estimate from the controller, we still need to do this
+ * weird conversion to get the proper rounding.
+ *
+ * @param {string} gasPriceEstimate
+ * @returns {string}
+ */
+export function getRoundedGasPrice(gasPriceEstimate) {
```
Comment (brad-decker) [inline ui/ducks/send/helpers.js:31]: This file contains helpers that were previously in the send duck file, these do not directly modify state or interact with redux.

File: ui/ducks/send/send.js (hunk 3 above)
Comment (brad-decker) [reply ui/ducks/send/send.js:579]: still true, Brad.

File: ui/ducks/send/send.js [hunk 8]
```diff
@@ -587,43 +615,49 @@ export const initializeSendState = createAsyncThunk(
...
-      gasPrice = getRoundedGasPrice(gasFeeEstimates.gasPrice);
-    } else if (gasEstimateType === GAS_ESTIMATE_TYPES.FEE_MARKET) {
-      gasPrice = getGasPriceInHexWei(
-        gasFeeEstimates.medium.suggestedMaxFeePerGas,
-      );
-    } else {
-      gasPrice = gasFeeEstimates.gasPrice
-        ? getRoundedGasPrice(gasFeeEstimates.gasPrice)
-        : '0x0';
+    if (sendState.stage !== SEND_STAGES.EDIT) {
```
Comment (brad-decker) [inline ui/ducks/send/send.js:618]: This logic prevents the gasPrice ans gasLimit from an edit transaction from being ovewritten immediately on initialization.

File: ui/ducks/send/send.js [hunk 9]
```diff
@@ -587,43 +615,49 @@ export const initializeSendState = createAsyncThunk(
...
+          : '0x0';
+      }
     }
 
     // Set a basic gasLimit in the event that other estimation fails
-    let gasLimit =
-      asset.type === ASSET_TYPES.TOKEN || asset.type === ASSET_TYPES.COLLECTIBLE
-        ? GAS_LIMITS.BASE_TOKEN_ESTIMATE
-        : GAS_LIMITS.SIMPLE;
+    let { gasLimit } = draftTransaction.gas;
```
Comment (brad-decker) [inline ui/ducks/send/send.js:638]: default to the gasLimit set on the draftTransaction, which is either '0x0' or an actual limit from an edit tx

File: ui/ducks/send/send.js [hunk 10]
```diff
@@ -632,36 +666,8 @@ export const initializeSendState = createAsyncThunk(
...
-    if (asset.type === ASSET_TYPES.COLLECTIBLE) {
-      if (asset.details === null) {
-        // If we're sending a collectible but details have not been provided we must
-        // abort and set the send slice into invalid status.
-        throw new Error(
-          'Send slice initialized as collectibles send without token details',
-        );
-      }
-      balance = '0x1';
-    }
```
Comment (brad-decker) [inline ui/ducks/send/send.js:660]: this portion is now handled in the updateSendAsset, which now is never called from outside the send flow (it was previously called before routing to the send page to set the asset to be sent)

File: ui/ducks/send/helpers.js [hunk 11]
```diff
@@ -0,0 +1,295 @@
...
+  }
+
+  // The parameters below will be sent to our background process to estimate
+  // how much gas will be used for a transaction. That background process is
+  // located in tx-gas-utils.js in the transaction controller folder.
+  const paramsForGasEstimate = { from: selectedAddress, value, gasPrice };
+
+  if (sendToken) {
+    if (!to) {
+      // if no to address is provided, we cannot generate the token transfer
```
Comment (darkwing) [inline ui/ducks/send/helpers.js:61]:
```suggestion
      // If no to address is provided, we cannot generate the token transfer
```

File: ui/ducks/send/helpers.js [hunk 12]
```diff
@@ -0,0 +1,295 @@
...
+  } else {
+    if (!data) {
+      // eth.getCode will return the compiled smart contract code at the
+      // address. If this returns 0x, 0x0 or a nullish value then the address
+      // is an externally owned account (NOT a contract account). For these
+      // types of transactions the gasLimit will always be 21,000 or 0x5208
+      const { isContractAddress } = to
+        ? await readAddressAsContract(global.eth, to)
+        : {};
+      if (!isContractAddress && !isNonStandardEthChain) {
```
Comment (darkwing) [inline ui/ducks/send/helpers.js:88]: Is something like this better?

```suggestion
      if (!isContractAddress) {
        if(isNonStandardEthChain) {
          isSimpleSendOnNonStandardNetwork = true;
        }
        else {
          return GAS_LIMITS.SIMPLE;
        }
      }
```

File: ui/ducks/send/helpers.test.js [hunk 13]
```diff
@@ -0,0 +1,160 @@
...
+          sendToken: tokenDetails,
+        }),
+        to: '0xToken',
+        type: '0x0',
+        value: '0x0',
+        gas: '0x0',
+        gasPrice: '0x0',
+      });
+    });
+    it('should generate a txParams for a collectible transfer', () => {
```
Comment (darkwing) [inline ui/ducks/send/helpers.test.js:56]: Many of our test files have empty lines before each `it` test.

File: ui/pages/confirm-send-token/confirm-send-token.container.js [hunk 14]
```diff
@@ -18,18 +18,11 @@ const mapStateToProps = (state) => {
...
-        editTransaction(
-          ASSET_TYPES.TOKEN,
-          id.toString(),
-          tokenData,
-          assetDetails,
-        ),
-      );
-      dispatch(clearConfirmTransaction());
-      dispatch(showSendTokenPage());
+      await dispatch(editExistingTransaction(ASSET_TYPES.TOKEN, id.toString()));
```
Comment (darkwing) [inline ui/pages/confirm-send-token/confirm-send-token.container.js:23]: Out of curiosity, I know this wasn't changed, but what could `id` be that we need to typecast it to string?

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/ducks/send/helpers.js (hunk 12 above)
Comment (brad-decker) [reply ui/ducks/send/helpers.js:88]: I like what you have, but i'm hesitant to change it as this function simply moved unchanged from its previous location.

File: ui/pages/confirm-send-token/confirm-send-token.container.js (hunk 14 above)
Comment (brad-decker) [reply ui/pages/confirm-send-token/confirm-send-token.container.js:23]: I honestly have no clue... it should be a string and is a string in the state tree. i'm not sure if there is some higher level area where it is manipulated away from being a JavaScript string object. The .toString() was copied from the confirmation base when the id is manipulated.

**Comment by tmashuang** [comment]
One minor thing I found was that no matter what I couldn't get the `send.recipientMode` to change from `CONTACT_LIST` to `MY_ACCOUNTS`. I don't know if that matters somewhere, but I was able to send the txs with no issues.

File: lavamoat/build-system/policy-override.json (hunk 4 above)
Comment (Nunnaphat1234) [reply lavamoat/build-system/policy-override.json]: Hello, brothers and sisters. From the bottom of my heart. I haven't replied to many things. Yes, what should I do, the brothers who have been helping me all this time come to my account and replace them? I give you the right to do every action with autonomy.

**Comment by Nunnaphat1234** [comment]
1/ No, I only have one wallet.0xC8eac206a4e511BA244531C01C91Df5B1BD967e1

File: ui/ducks/send/helpers.js [hunk 15]
```diff
@@ -0,0 +1,295 @@
...
+    }
+
+    paramsForGasEstimate.data = data;
+
+    if (to) {
+      paramsForGasEstimate.to = to;
+    }
+
+    if (!value || value === '0') {
+      // TODO: Figure out what's going on here. According to eth_estimateGas
```
Comment (darkwing) [inline ui/ducks/send/helpers.js:102]: Is this ToDo blocking?

Comment (brad-decker) [reply ui/ducks/send/helpers.js:102]: Nah, this function just got relocated. It has been a To do since my last refacotr. 😭

**Review by tmashuang — DISMISSED** [review]

File: ui/ducks/send/helpers.js [hunk 16]
```diff
@@ -0,0 +1,295 @@
...
+      // When sending a token the to address is the contract address of
+      // the token being sent. The value is set to '0x0' and the data
+      // is generated from the recipient address, token being sent and
+      // amount.
+      txParams.to = draftTransaction.asset.details.address;
+      txParams.value = '0x0';
+      txParams.data = generateERC721TransferData({
+        toAddress: draftTransaction.recipient.address,
+        fromAddress:
+          draftTransaction.fromAccount.address ??
```
Comment (adonesky1) [inline ui/ducks/send/helpers.js:218]:
```suggestion
          draftTransaction.fromAccount?.address ??
```

**Comment by adonesky1** [comment]
I'm not all the way through, but I want to note this thought: I'm not entirely clear on why `draftTransactions` should be an object keyed by a `UUID`. It should only ever contain one transaction at a time right? Couldn't it just be 

```
draftTransaction: {
  amount: {
    error: null,
    value: '0x0',
  },
  asset: {
    balance: '0x0',
    details: null,
    error: null,
    type: ASSET_TYPES.NATIVE,
  },
  fromAccount: null,
  gas: {
    error: null,
    gasLimit: '0x0',
    gasPrice: '0x0',
    gasTotal: '0x0',
    maxFeePerGas: '0x0',
    maxPriorityFeePerGas: '0x0',
  },
  history: [],
  id: null,
  recipient: {
    address: '',
    error: null,
    nickname: '',
    warning: null,
  },
  status: SEND_STATUSES.VALID,
  transactionType: TRANSACTION_ENVELOPE_TYPES.LEGACY,
  userInputHexData: null,
};
``` ?

**Comment by adonesky1** [comment]
Seeing a pretty funny bug:

So if you try to change the network in the middle of a token send you get an error in the `tokenInput` component because it's trying to find token data in the `tokenExchangeRates` object. I've created [an issue for this bug](https://github.com/MetaMask/metamask-extension/issues/15036)(which exists on develop too). 

But so if you do a naive fix for that bug: 
`const tokenExchangeRate = tokenExchangeRates?.[existingToken.address] || 0;`
 -> 
 `const tokenExchangeRate = tokenExchangeRates?.[existingToken**?**.address] || 0;`
 
 you get this funny scenario:

https://user-images.githubusercontent.com/34557516/175351058-92d96467-4e7a-44f7-8c00-c0a5ba941846.mov

where the send state asset is not cleared and instead we just get a token that is associated with the same address on the new network. I'm guessing this is not the behavior we want...

**Comment by brad-decker** [comment]
> I'm not all the way through, but I want to note this thought: I'm not entirely clear on why draftTransactions should be an object keyed by a UUID. It should only ever contain one transaction at a time right? Couldn't it just be?:

This same assumption occurs in the current send state, that there will only ever be one "in flight" transaction in the send flow at a time, we do clear this state when the user closes the window, etc but still we saw possibility of being corrupted. The idea of the UUID here is to generate it during the send flow being triggered, such that anytime the send flow is entered a new UUID is created and thus we will never accidentally reference the state of a different transaction as the previous UUID is replaced and can no longer be recalled.

So to answer your question -- it is simply another layer of safety in case the clearing of a draft out of the object is partial, or doesn't happen, as we expect it to. I realize that it might not be immediately clear how that could happen, but that sort of quality applies to the current send state as well.

**Comment by brad-decker** [comment]
> But so if you do a naive fix for that bug:
const tokenExchangeRate = tokenExchangeRates?.[existingToken.address] || 0;
->
const tokenExchangeRate = tokenExchangeRates?.[existingToken**?**.address] || 0;
you get this funny scenario:

I'm unclear on this feedback if it needs to be addressed here ... if the bug you are outlining exists in this PR's current state?

**Comment by adonesky1** [comment]
> I'm unclear on this feedback if it needs to be addressed here ... if the bug you are outlining exists in this PR's current state?

I think the critical bug - which is relevant to the implementation here - is that when a user changes networks during the send flow we don't appear to be clearing/reset the `asset` value in the `draftTransaction` so you end up with strange situations (like the video linked above) where, after changing networks, `asset` is pointing to a different token (while the name in the input remains unchanged).

**Comment by brad-decker** [comment]
We should set the asset back to the native asset on a network change. I'll make that change.

File: ui/ducks/send/send.js [hunk 17]
```diff
@@ -278,168 +259,216 @@ export const AMOUNT_MODES = {
...
-  // deterministic behaviour.
-  //
-  // Gas estimation of simple sends should, however, be deterministic. As such
-  // no buffer is needed in those cases.
-  let bufferMultiplier = 1.5;
-  if (isSimpleSendOnNonStandardNetwork) {
-    bufferMultiplier = 1;
-  } else if (CHAIN_ID_TO_GAS_LIMIT_BUFFER_MAP[chainId]) {
-    bufferMultiplier = CHAIN_ID_TO_GAS_LIMIT_BUFFER_MAP[chainId];
-  }
```
Comment (adonesky1) [inline ui/ducks/send/send.js:399]: Did you intend to fully remove buffering for the gas limit? If so why?

Comment (adonesky1) [reply ui/ducks/send/send.js:399]: Oh nvm I see this whole method was moved to helpers 🤦

**Review by adonesky1 — COMMENTED** [review]
Amazing (and ambitious) work as always Brad! I've left comments on everything that caught my eye after going through the whole thing 😌

File: ui/pages/confirm-send-token/confirm-send-token.component.js [hunk 18]
```diff
@@ -12,8 +12,9 @@ export default class ConfirmSendToken extends Component {
 
   handleEdit(confirmTransactionData) {
     const { editTransaction, history } = this.props;
-    editTransaction(confirmTransactionData);
-    history.push(SEND_ROUTE);
+    editTransaction(confirmTransactionData).then(() => {
```
Comment (danjm) [inline ui/pages/confirm-send-token/confirm-send-token.component.js:15]: In `ui/pages/confirm-send-ether/confirm-send-ether.container.js` we made a change to use `editExistingTransaction` instead of `editTransaction`. but not here

was that intentional?

File: ui/components/app/wallet-overview/token-overview.js [hunk 19]
```diff
@@ -93,7 +93,7 @@ const TokenOverview = ({ className, token }) => {
               });
               try {
                 await dispatch(
-                  updateSendAsset({
+                  startNewDraftTransaction({
```
[the remark this answers is not in the document]
Comment (brad-decker) [reply ui/components/app/wallet-overview/token-overview.js:96]: we are `await`'ing it here, so we do wait.

File: ui/pages/confirm-send-token/confirm-send-token.component.js (hunk 18 above)
Comment (brad-decker) [reply ui/pages/confirm-send-token/confirm-send-token.component.js:15]: the container wraps editExistingTransaction and calls it 'editTransaction' i'm changing this to avoid confusion and making debugging better.

File: ui/components/app/wallet-overview/token-overview.js (hunk 19 above)
[the remark this answers is not in the document]
Comment (danjm) [reply ui/components/app/wallet-overview/token-overview.js:96]: oh yes

**Comment by PeterYinusa** [comment]
Hey @brad-decker, I'm seeing some weird behaviour with the `max amount` button in the send flow for ERC20 tokens, it seems to work as expected for the native currency. See below:

https://user-images.githubusercontent.com/53189696/175666453-b5f9a294-3d72-4a14-a92b-5bf8264b4e50.mov

**Comment by brad-decker** [comment]
@PeterYinusa omg good catch, sir! I changed how we got the asset balance to avoid multiple calls to the client but the result wasn't formatted the same way. This should be functionally equivalent now. Please test with several ERC20's

**Review by adonesky1 — DISMISSED** [review]
🥳 Great work Brad!

**Review by tmashuang — DISMISSED** [review]

**Comment by seaona** [comment]
Just wondering if these changes facilitate the fix for the "`Undefined`" value when editing a Send tx, or it's totally unrelated topic /  must be fixed separately. @brad-decker this bug appears both in this branch and in develop/master, but since it's related to the Send flow, thought I might share here just in case it's related. See [more](https://github.com/MetaMask/metamask-extension/issues/15047).

image

**Comment by brad-decker** [comment]
> Just wondering if these changes facilitate the fix for the "Undefined" value when editing a Send tx, or it's totally unrelated topic / must be fixed separately. @brad-decker this bug appears both in this branch and in develop/master, but since it's related to the Send flow, thought I might share here just in case it's related. See https://github.com/MetaMask/metamask-extension/issues/15047.

@seaona if they appear in both places lets keep it as a new bug to deal with after this lands just to avoid holding this PR up for longer.

**Review by darkwing — DISMISSED** [review]

**Comment by PeterYinusa** [comment]
> @PeterYinusa omg good catch, sir! I changed how we got the asset balance to avoid multiple calls to the client but the result wasn't formatted the same way. This should be functionally equivalent now. Please test with several ERC20's

Looking good 🙌

**Review by tmashuang — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
