### PR TITLE
fix: fix gas station payment tx in tx details

### LINKED ISSUE #35565: [Bug]: Gas Station - When using gas for paying for the tx, we see the 3 tx's in the Activity list (primary tx, gas one and received). The Gas one has no title when its USDT (Binance)
**Describe the bug**

When using gas for paying for the tx, we see the 3 tx's in the Activity list (primary tx, gas related one) and received. The Gas one has no title if it's using USDT Binance, and recipient is the ERC20 token (which makes sense but might be confusing).

I'm unsure if we really want to display the "secondary" gas tx in the Activity list 🤔
- if not, remove from the list
- if yes, add title and clarifying information .. ie the details with recipient might be confusing, despite correct

Also unsure about the Received one.
I guess it's a major change to consolidate the 3 in just 1 entry in the Activity list..but to consider.

**Screenshots/Recordings**

Image

Image

Image

https://github.com/user-attachments/assets/63b49ac2-29e0-4181-8712-c4c78f3cc07c

**Steps to reproduce**

1. Start a Send with an account with 0 BNB but with USDT balance -- **note: it must be USDT**
2. Add recipient
3. Add amount 0 BNB
4. See gas is defaulting to be payed with token
5. Confirm
6. See Activity List - tx has no title

**Error messages or log output**

```shell

```

**Detection stage**

In Production

**Version**

12.3.0

**Build type**

None

**Browser**

Chrome

**Operating system**

Linux

### PR DESCRIPTION
**Pull request by ameliejyc**
## **Description**

When using another token for gas payment, we see the 3 transactions in the Activity list (primary Send, gas transfer, and Received native token). The gas one had no title or icon when using Binance and incorrect transaction values.

image

This is because the transaction is marked as a `gas_payment` type when the batch transaction is created but there was no support for this type in how it should be displayed. 

The fix is to filter out the `gas_payment` type and use the underlying ERC-20 token transfer transaction for the gas token which comes from the Transactions API. This is also how the transaction would look like for any imported wallet, as the `gas_payment` type isn't used in the API. Now the transaction shows the correct details and has parity with how it looks when completed in the wallet and when viewed as an imported wallet. 

The `gas_payment` type is meanwhile preserved when submitting the transaction as it is being used in metrics.

## **Changelog**

CHANGELOG entry: Fix gas station gas transfer transaction details in Activity list

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/35565

## **Manual testing steps**

1. Start a Send with an account with 0 BNB but with USDT or USDC balance
2. Add recipient
3. Add amount 0 BNB
4. See gas defaults to be paid with USDT or USDC
5. Confirm
6. See Activity List: 3 transactions show and the middle one is a 'Sent USDC (or USDT)' transaction with correct values in fiat and non-fiat currency, with correct transaction details when clicked
7. Open MM on a non-development build and see that the transaction is displayed in exactly the same way

### **Before**

See video here https://github.com/MetaMask/metamask-extension/issues/35565

### **After**

image

image

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> - **Filter updates:** Introduces `EXCLUDED_TRANSACTION_TYPES` (includes `gasPayment` and `incoming`) and applies it in `unified-transaction-list.component.js` and selectors to exclude these from pending/completed and selected-address lists.
> - **Display fix:** Passes `chainId` to `useTokenFiatAmount` in `useTransactionDisplayData` to compute correct fiat values for gas-fee token transactions.
> - **Tests:** E2E smart transaction specs now expect 1 confirmed/failed tx and correct amounts; selector unit tests added/updated to verify filtering of `gasPayment` and `incoming` types.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 795f07b84fc0ab775362afed316218c8be2eff7c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/transaction-list/unified-transaction-list.component.js
Comment (ameliejyc) [inline ui/components/app/transaction-list/unified-transaction-list.component.js:1]: Filtering is done on the component side as well as the selector side. This is to support recent changes made to ensure all transactions show correctly when a non-EVM account is selected (see [here](https://github.com/MetaMask/metamask-extension/pull/38529)) as the transactions values used here aren't the same as the ones returned from the selectors.

File: ui/hooks/useTransactionDisplayData.js [hunk 1]
```diff
@@ -247,6 +247,7 @@ export function useTransactionDisplayData(transactionGroup) {
     token?.symbol,
     undefined,
     true,
+    initialTransaction?.chainId,
```
Comment (ameliejyc) [inline ui/hooks/useTransactionDisplayData.js:250]: Adding this provides the fiat conversion rate value on the transaction line. Without this, no fiat conversion is shown for the gas transaction.

Image

File: ui/components/app/transaction-list/unified-transaction-list.component.js [hunk 2]
```diff
@@ -510,6 +508,7 @@ export default function UnifiedTransactionList({
       const evmTxs = [...allTransactions, ...(smartTransactions ?? [])]
         .filter((tx) => tx.txParams?.from?.toLowerCase() === groupEvmAddress)
         .filter((tx) => tx.type !== TransactionType.incoming)
+        .filter((tx) => tx.type !== TransactionType.gasPayment)
```
Comment (n3ps) [inline ui/components/app/transaction-list/unified-transaction-list.component.js]: With the increase in filters here, wdyt about combining them, at least the `.type` ones?

Something like
```
.filter(({ type }) =>
  type !== TransactionType.incoming &&
  type !== TransactionType.gasPayment
)
```

or  maybe
```
const excludedTypes = new Set([
  TransactionType.incoming,
  TransactionType.gasPayment,
]);
```

Comment (ameliejyc) [reply ui/components/app/transaction-list/unified-transaction-list.component.js]: Good shout, updated

**Comment by NidhiKJha** [comment]
@ameliejyc I am not able to run it. It's not taking USDC as fee for me. Am I missing something here?



https://github.com/user-attachments/assets/2fccdd0f-26b2-4e99-97e0-90e1411a618f

**Review by n3ps — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
