### PR TITLE
fix: Fix send max on gas value changes

### LINKED ISSUE #30269: [Bug]: Send max not working on v12.11 although a fix was cherry picked to the RC
### Describe the bug

Original issue: https://github.com/MetaMask/metamask-extension/issues/29903

Original fix PR: https://github.com/MetaMask/metamask-extension/pull/29960

Cherry-pick PR: https://github.com/MetaMask/metamask-extension/pull/29998

[Slack thread](https://consensys.slack.com/archives/C8RSKCNCD/p1739371117036149)

Goal of this issue: understand why the issue persisted on v12.11 after the cherry-pick and confirm that the issue is not present on v12.12

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Start a send transaction for the native asset
2. Click Max
3. Confirm the transaction

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.11.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #30462: [Bug]: Sending all ETH with `Max` feature always gives error
### Describe the bug

I have already reported to your support team but not sure whether you got noticed.

Whenever I try to send out all ETH with the `Max` button present right below the amount input box and on the right side, it always gives `This transaction would have cost you extra fees, so we stopped it. Your money is still in your wallet.` error.

### Expected behavior

Transaction not get stopped and all ETH be sent out.

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. `Send`
2. Input destination address
3. `Max`
4. `Continue`
5. `Confirm`
6. Transaction fails with the error message.

### Error messages or log output

```shell
This transaction would have cost you extra fees, so we stopped it. Your money is still in your wallet.
```

### Detection stage

In production (default)

### Version

12.12.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Trezor

### Additional context

# Workaround

1. Balance is `1` ETH
2. `Max` auto fills amount with `0.9999901234567891`
3. Remove the last decimal, i.e. `0.999990123456789`
4. Transaction not longer fails

This bug is first seen after I updated MetaMask extension from `12.10.3` to `12.11.0`.

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to fix send max feature gas issues. 

It also adds e2e tests that cover: 
- correct amount
- gas modal changes (on picking 'low', 'medium', 'high'
- adjusting manual values on gas modal
- reacting gas estimation changes in network level

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30523?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30269

## **Manual testing steps**

Usual send flow should work properly

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts [hunk 1]
```diff
@@ -22,11 +50,34 @@ export const useMaxValueRefresher = () => {
...
+  useEffect(() => {
+    updateTransactionEventFragment(
+      {
+        properties: {
+          is_send_max: isMaxAmountMode,
+        },
+      },
+      transactionId,
+    );
+  }, [isMaxAmountMode, transactionId]);
```
Comment (pedronfigueiredo) [inline ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: If the user clicks on max, and then overwrites on the maxFeePerGas or gasPrice inputs, does isMaxAmountMode change to false?

Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: No it doesn't change `isMaxAmountMode` to `false`, it remains `true`. But depending on the new `maxFeePerGas` we re-calculate the transaction value. 

This cases are considered in `gas modal changes` e2e spec

Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: This is a limitation then, because the metric event will still consider those cases as if the user has submitted the transaction after setting is max, when it's not technically true anymore. It's probably not a great deal, and an edge case, but something to keep in mind.

Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: But `isMaxAmountMode` is reflecting the user choice that they picked in the previous step. 
Users could change gas but it shouldn't change the value they picked in the amount screen no?

Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: Apologies, I now realize I confused the two concepts in my initial question, so let me try again. If the user clicks on max value, and overwrites the amount to a lower one, does isMaxAmountMode change to false?

Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: Ah I see what you mean, good question, that is not possible thorugh any UX flow today, once user go to the confirmation, they can't transaction value manually anymore.

Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: If they go back and edit the value?

**Comment by sleepytanya** [comment]
Fix looks great @OGPoyraz 

Sending Max on Sepolia:


https://github.com/user-attachments/assets/c575d657-53c7-418b-a78a-a4839546265d

Sending Eth Max on mainnet:


https://github.com/user-attachments/assets/5af482be-4408-4b81-91ee-9fd7d025b2f9

Sending USDC Max on Polygon:


https://github.com/user-attachments/assets/46f01e3e-0985-4420-83f3-8e3dcf1ba401


Sending Eth Max using Advanced gas settings:


https://github.com/user-attachments/assets/71c4ec15-2f3c-4c99-951a-b4ec43fba2cc

File: ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts (hunk 1 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: Good call @pedronfigueiredo, it was not scope of the task but I just checked if send flow was handling it. Unfortunately they are not, you caught a bug here. I will quickly fix this and also add e2e for this scenario.

Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts:80]: Added this e2e case in https://github.com/MetaMask/metamask-extension/pull/30523/commits/547bd3b934a76ba6e05fd8b452f952d1b5705c20

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by vinistevam — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
