### PR TITLE
fix: #32045 - Show connect account toast for Solana networks

### LINKED ISSUE #32045: [Bug]:  Missing toast when switching to a Solana account that is not connected to the current dapp
### Describe the bug

The toast message to prompt the user to connect a disconnected Solana account is missing when the account is in-focus over a Solana dapp.

### Expected behavior

A toast message similar to what we do for Ethereum accounts should appear.

### Screenshots/Recordings

Image

### Steps to reproduce

1. Create multiple Solana accounts
2. Only connect one of the Solana accounts to a Solana dapp
3. Switch to a disconnected Solana account in MetaMask while over the Solana dapp

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

12.17.0-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## **Description**

Ensures that the toast to connect to the currently selected Solana account displays

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32107?quickstart=1)

## **Related issues**

Fixes: #32045

## **Manual testing steps**

1. Create two Solana accounts
2. Connect to a dapp with one account
3. Switch to the second account
4. Open the extension popup
5. See the connect message
6. Click "connect" to connect the account

### **After**
SCR-20250417-npvj

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by darkwing** [comment]
The toast is always displaying because the address of the Solana account does not match the representation in that connectedAccounts array:
SCR-20250417-nvbi

File: ui/components/app/toast-master/selectors.ts [hunk 1]
```diff
@@ -86,17 +86,16 @@ export function selectShowConnectAccountToast(
...
-  return (
+  const showConnectAccountToast =
     allowShowAccountSetting &&
     account &&
     state.activeTab?.origin &&
-    isEvmAccount &&
     connectedAccounts.length > 0 &&
-    !connectedAccounts.some((address) => address === account.address)
-  );
+    !connectedAccounts.some((address) => address === account.address);
```
Comment (jiexi) [inline ui/components/app/toast-master/selectors.ts:96]: i think this is comparing caip-10 account addresses to hex references. I can push a fix for this

Comment (jiexi) [reply ui/components/app/toast-master/selectors.ts:96]: right. what you said in your screenshot

Comment (jiexi) [reply ui/components/app/toast-master/selectors.ts:96]: Try this
```
  const showConnectAccountToast =
    allowShowAccountSetting &&
    account &&
    state.activeTab?.origin &&
    !isInternalAccountInPermittedAccountIds(account, connectedAccounts)
```

**Review by jiexi — DISMISSED** [review]

**Review by adonesky1 — DISMISSED** [review]
LGTM!

**Review by jiexi — DISMISSED** [review]

**Review by gambinish — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
LGTM
