### PR TITLE
fix: fix button disabled for long tokenId

### LINKED ISSUE #30047: [Bug]:  Transaction confirmation for NFT with the long ID displays ID in scientific notation, 'Continue' button is disabled
### Describe the bug

When initiating a transaction for an n NFT with a long ID from the token details page, the transaction confirmation displays the ID in scientific notation (when the transaction is initiated from the `Send flow`, the ID is correctly truncated on the first Confirmation screen), `Continue` button is disabled.

When NFT transaction initiated form the`Send flow`, the scientific notation is shown on the second Confirmation screen.

### Expected behavior

Consistent display format of long NFT IDs in transaction confirmations.

### Screenshots/Recordings

https://github.com/user-attachments/assets/9f9df10a-2d30-4ba6-b403-627ea79a1de1

https://github.com/user-attachments/assets/10778735-3d73-4057-bf6d-49d9a9aec19d

Image

Image

### Steps to reproduce

1. Send an NFT with the long ID from the token details page

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.10.3

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR fixes the disbaled send button when the user tries to send an NFT with a long tokenId
And updates the display of the tokenId in the confirmation screen from scientific value to original tokenId value and truncate it when its very long.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31359?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30047

## **Manual testing steps**

1. Go to NFT details page
2. Choose an NFT with a long tokenId
3. click on send
4. You should be able to see "confirm" button enabled
5. Confirmation screen should have the tokenId match the original format you have seen on the NFT details page.

### **Before**

Screenshot 2025-03-28 at 12 26 37

https://github.com/user-attachments/assets/1e2f3f46-9a2f-45c5-89bd-16ee61d8dd7f

### **After**

Screenshot 2025-03-28 at 12 17 43

https://github.com/user-attachments/assets/1cf61e54-b912-49a2-8326-4cbf08241c19

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/nfts/nft-details/nft-details.tsx [hunk 1]
```diff
@@ -292,7 +293,7 @@ export function NftDetailsComponent({
         type: AssetType.NFT,
         details: {
           ...nft,
-          tokenId: Number(nft.tokenId),
```
Comment (sahar-fehri) [inline ui/components/app/assets/nfts/nft-details/nft-details.tsx:295]: For long token IDs, this led to incorrectly encoded parameters for the `eth_estimateGas` query, ultimately causing the button to send the NFT to be disabled.

File: app/scripts/lib/transaction/decode/util.ts [hunk 2]
```diff
@@ -121,7 +121,7 @@ function normalizeDecodedParamValue(value: any): any {
   const hexValue = value._hex;
 
   if (hexValue) {
-    return parseInt(hexValue, 16);
+    return BigInt(hexValue).toString();
```
Comment (sahar-fehri) [inline app/scripts/lib/transaction/decode/util.ts:124]: The tokenId value returned by `useDecodedTransactionData` was in scientific format and different from the tokenId format displayed in NFT details page.

`parseInt(hexValue, 16)` converted the hexadecimal string to a base-10 number.
`parseInt("0x681bd29732282184a07b713b2e79b2c439f6daaeb5c008bd4ad4ac889d4a4687", 16);`

instead using:
`BigInt(hexValue) `correctly converts the large hexadecimal number into a BigInt.

**Comment by sleepytanya** [comment]
@sahar-fehri 

Long ID looks great, thank you!

'Continue' is still disabled for ERC 721 when Send is initiated from the NFT details, ERC 1155 send is working as expected:



https://github.com/user-attachments/assets/1944223d-e10b-41a7-8201-9d9aae356d8f

'Continue' is active if tx started from the Send flow, but tx always fails with intrinsic gas too low error (with STX enabled and disabled):



https://github.com/user-attachments/assets/6f80b4fb-e466-4880-a9dd-620b2938e94b

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by sleepytanya — DISMISSED** [review]

**Review by sleepytanya — DISMISSED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by sleepytanya — APPROVED** [review]

File: ui/components/app/assets/nfts/nft-details/nft-details.tsx (hunk 1 above)
Comment (Prithpal-Sooriya) [reply ui/components/app/assets/nfts/nft-details/nft-details.tsx:296]: Nice find!!

(future) - It would be nice if this type was corrected (instead of a `number` we keep it as a `string`. Or maybe make this a `string | number`?)

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
