### PR TITLE
fix: ERC20 Custom Token shows incorrect name

### LINKED ISSUE #20776: [Bug]: When I import the gold token by token address in custom token section it showed me the name of another token which is listed on coingecko
### Describe the bug

In custom token section, by inputing token address it showed the correct token name but after clicking on import and land on main wallet screen, token name changed to some other token name.

### Steps to reproduce

1. Enter the following address 0x57c88ed53d53fDc6B41D57463E6C405dE162843e in custom token, first it detects the correct name and then import token.
2. After importing it will replace the name with some dragoneum token which is listed on coingecko

### Error messages or log output

_No response_

### Version

10.35.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS, Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
In custom token section, by inputing token address it showed the correct token name but after clicking on import and land on main wallet screen, token name changed to some other token name.

the problem comes from the fact that we filter only on the symbol, so this error occurs for two tokens with the same symbol but two different addresses, we always take the first in the list.
the solution is to add the filter with the address

## **Manual testing steps**

1 - Enter the following address `0x57c88ed53d53fDc6B41D57463E6C405dE162843e` in custom token, first it detects the correct name and then import token.
2 - After importing it will replace the name with some dragoneum token

### **Before**

https://drive.google.com/file/d/1ZALuCmmtQf1Nquvxmsem4_ADSp685Tnn/view

### **After**

https://drive.google.com/file/d/1WKZbFwQkO22dclg4vw6GA3F0nXH4xm5y/view?usp=drive_link

## **Related issues**

_Fixes #20776

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/token-cell/token-cell.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { TokenListItem } from '../../multichain';
 export default function TokenCell({ address, image, symbol, string, onClick }) {
   const tokenList = useSelector(getTokenList);
   const tokenData = Object.values(tokenList).find(
-    (token) => token.symbol === symbol,
+    (token) => token.symbol === symbol && token.address === address,
```
Comment (salimtb) [inline ui/components/app/token-cell/token-cell.js:11]: the problem comes from the fact that we filter only on the `symbol`, so this error occurs for two tokens with the same `symbol` but two different addresses, we always take the first in the list of the `getTokenList` result.
the solution is to add the filter with the `address`

**Review by DDDDDanica — DISMISSED** [review]

**Comment by Ashok1927** [comment]
I don't like as a type of this mail??😢

I like only official mail with  "official logo"😢😢

AshokDubey.

Thanks.
please do the needful.

File: ui/components/app/token-cell/token-cell.test.js [hunk 2]
```diff
@@ -23,6 +40,28 @@ describe('Token Cell', () => {
...
+    },
+    '0xAddress': {
+      name: 'TEST-2',
+      erc20: true,
+      symbol: 'TEST',
+      decimals: 18,
+      address: '0xAddress',
+      iconUrl: './images/test_1_image.svg',
+      aggregators: [],
+    },
```
Comment (bergeron) [inline ui/components/app/token-cell/token-cell.test.js:62]: I think the order of these tokens should be swapped.  That way we're testing it skips over the first symbol match, and lands on the correct symbol + address match.  Otherwise this test passes on the old code, because it picks the first one which happens to be correct.

**Review by bergeron — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]
