### PR TITLE
Fix currency symbol in insufficient balance warning

### LINKED ISSUE #17371: [Bug]: Insufficient balance Warning for paying fees points to the incorrect token
### Describe the bug

**Problem**: when I don't have enough gas for paying fees, if I try to send a token in that network, I get a warning, saying I don't have enough of that Token for paying fees, instead of the protocol token (in this case ETH), which is the one used to pay gas. And it also recommends buying that token, instead of the protocol token (ETH).

image

https://user-images.githubusercontent.com/54408225/214274484-9cb6c1f0-d578-4bd4-998b-15ea52820dcf.mp4

### Steps to reproduce

1. Select an Account with no ETH and with a Token 
2. Click the Token
3. Click Send
4. Add recipient -- see how warning appears, and it mentions you don't have enough of that Token, instead of ETH

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/17371

## Explanation
Introduced in https://github.com/MetaMask/metamask-extension/pull/17450 - I do not believe it is the case we always want to use `provider.ticker`. However, changing to use `getNativeCurrency` for `nativeCurrency` will do so when appropriately (when `useCurrencyRateCheck` is false)

## Screenshots/Screencaps
Screen Shot 2023-02-19 at 9 15 57 PM

## Manual Testing Steps
1. Select an Account with no ETH and with a Token 
2. Click the Token
3. Click Send
4. Add recipient -- confirm warning shows the native network currency in its copy

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/pages/send/gas-display/gas-display.js [hunk 1]
```diff
@@ -359,12 +360,9 @@ export default function GasDisplay({ gasError }) {
                 ) : (
                   <Typography variant={TypographyVariant.H7} align="left">
                     {t('insufficientCurrencyBuyOrReceive', [
-                      draftTransaction.asset.details?.symbol ?? nativeCurrency,
+                      nativeCurrency,
                       currentNetworkName,
-                      `${t('buyAsset', [
-                        draftTransaction.asset.details?.symbol ??
```
Comment (ryanml) [inline ui/pages/send/gas-display/gas-display.js:365]: In token transfer transactions we should still show the native currency always here

**Review by pedronfigueiredo — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]
