### PR TITLE
_checkIfTxWasDropped nextworkNextNonce type correction

### LINKED ISSUE #8688: Issue with Txs being labeled as dropped but still pending
**Describe the bug**
(Needs addtional verification)

At the time of tx submission the "Safe Low" gas price from EthGasStation was 30gwei. Sent a tx with 25gwei to ensure a fairly moderate wait time, but the tx status was updated to dropped after losing focus in the extension view and reopening and/or after some time.

**Screenshots**
<details>
<summary>Screenshot of Etherscan and tx</summary>

</details>

**Additional context (Error Messages, etc.)**
Possibly widened the errors that can allow the tx status to update to dropped. 
Will updated in the comments with additional info on the issue.

Looks `eth_sendRawTransaction` is calling twice. The first will respond with the tx hash, and the second will respond with a `known transaction` error and thus will proceed to set the tx status to dropped. In prod, it seems the known transaction error does not update the status to dropped.

### PR DESCRIPTION
**Pull request by tmashuang**
~~No radix-16 needed for nonce, already done,. NextNetworkNonce BN doesn't need it either, returns number when parsed.~~

~~Stringify on networkNonce before parseInt.~~

~~Just remove radix-16 on nextNetworkNonce.~~

~~Radix-10 on nextworkNextNonce BN.~~

networkNextNonce.toNumber()

Fixes #8688.

### CODE REVIEW

**Comment by whymarrh** [comment]
I don't understand, why isn't this needed/correct?

**Comment by tmashuang** [comment]
parseInt()

**Comment by Gudahtt** [comment]
I think the problem here is that `networkNextNonce` is a BigNumber, which gets `.toString`'d by `parseInt` implicitly, giving a base-10 string representation. Parsing that base-10 string representation of the number using a radix of 16 would give the wrong answer sometimes.

This also explains why I wasn't able to reproduce the problem - my transaction count was below 10, so the base-10 and base-16 numbers were equivalent.

File: app/scripts/controllers/transactions/pending-tx-tracker.js [hunk 1]
```diff
@@ -211,7 +211,7 @@ export default class PendingTransactionTracker extends EventEmitter {
     const { hash: txHash, txParams: { nonce, from } } = txMeta
     const networkNextNonce = await this.query.getTransactionCount(from)
 
-    if (parseInt(nonce, 16) >= parseInt(networkNextNonce, 16)) {
+    if (parseInt(nonce) >= parseInt(networkNextNonce)) {
```
Comment (Gudahtt) [inline app/scripts/controllers/transactions/pending-tx-tracker.js:214]: [To quote the MDN article for `parseInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt):
>**always specify a _`radix`_ when using `parseInt`.**

We should continue to use a radix for the `nonce` since it is a hex string.

Perhaps we could do something like this instead?

```suggestion
    if (parseInt(nonce) >= networkNextNonce.toNumber()) {
```

File: app/scripts/controllers/transactions/pending-tx-tracker.js [hunk 2]
```diff
@@ -211,7 +211,7 @@ export default class PendingTransactionTracker extends EventEmitter {
     const { hash: txHash, txParams: { nonce, from } } = txMeta
     const networkNextNonce = await this.query.getTransactionCount(from)
 
-    if (parseInt(nonce, 16) >= parseInt(networkNextNonce, 16)) {
+    if (parseInt(nonce, 16) >= parseInt(networkNextNonce) {
```
Comment (Gudahtt) [inline app/scripts/controllers/transactions/pending-tx-tracker.js:214]: I would at least appreciate the radix being made explicit here, so this doesn't come as a surprise to future readers. The fact that `networkNextNonce` is in base-10 seems fairly unexpected, considering that the Ethereum JSON-RPC protocol uses hex for everything.

As a general rule it's better to be explicit about the radix whenever possible (unless the input truly is unknown, and could be either decimal or hex or octal). In this case it seems especially useful to be explicit.

```suggestion
    if (parseInt(nonce, 16) >= parseInt(networkNextNonce, 10) {
```

**Review by Gudahtt — DISMISSED** [review]
LGTM!

File: test/unit/app/controllers/transactions/pending-tx-tracker-test.js [hunk 3]
```diff
@@ -19,7 +20,7 @@ describe('PendingTransactionTracker', function () {
         getCompletedTransactions: sinon.stub().returns([]),
         approveTransaction: sinon.spy(),
         publishTransaction: sinon.spy(),
-        confirmTransaction: sinon.spy(),
+      confirmTransaction: sinon.spy(),
```
Comment (Gudahtt) [inline test/unit/app/controllers/transactions/pending-tx-tracker-test.js:23]: Nit: the indentation is off here
```suggestion
        confirmTransaction: sinon.spy(),
```

File: app/scripts/controllers/transactions/pending-tx-tracker.js [hunk 4]
```diff
@@ -211,7 +211,7 @@ export default class PendingTransactionTracker extends EventEmitter {
     const { hash: txHash, txParams: { nonce, from } } = txMeta
     const networkNextNonce = await this.query.getTransactionCount(from)
 
-    if (parseInt(nonce, 16) >= parseInt(networkNextNonce, 16)) {
+    if (parseInt(nonce, 16) >= parseInt(networkNextNonce, 10)) {
```
Comment (whymarrh) [inline app/scripts/controllers/transactions/pending-tx-tracker.js:214]: If this is always a BN, we could call `.toNumber()`:

```suggestion
    if (parseInt(nonce, 16) >=networkNextNonce.toNumber()) {
```

This might be clearer (and possibly faster?).

Comment (tmashuang) [reply app/scripts/controllers/transactions/pending-tx-tracker.js:214]: I'm fine with either one.

**Review by Gudahtt — DISMISSED** [review]
LGTM! (though I do agree that using `.toNumber()` is marginally better)

**Review by Gudahtt — DISMISSED** [review]

**Review by Gudahtt — APPROVED** [review]
