### PR TITLE
Fix etherscan redirect on notification click

### LINKED ISSUE #9087: Clicking tx completion notification no longer redirects to etherscan
As [reported by two users on reddit here](https://www.reddit.com/r/Metamask/comments/hy39hn/cant_click_on_chrome_notification_to_view/?utm_source=share&utm_medium=ios_app&utm_name=iossmf).

I don't believe this was a deliberate choice.

### PR DESCRIPTION
**Pull request by PatrykLucka**
This PR adds handling for clicking on notifications with url starting with https://
Fixes #9087

### CODE REVIEW

File: app/scripts/platforms/extension.js [hunk 1]
```diff
@@ -223,7 +223,7 @@ export default class ExtensionPlatform {
   }
 
   _viewOnEtherscan (txId) {
-    if (txId.startsWith('http://')) {
+    if (txId.startsWith('http://') || txId.startsWith('https://')) {
```
Comment (whymarrh) [inline app/scripts/platforms/extension.js:226]: We could probably check only for HTTPS, we shouldn't be using non-TLS links anywhere:

```suggestion
    if (txId.startsWith('https://')) {
```

**Review by whymarrh — CHANGES_REQUESTED** [review]

**Review by whymarrh — APPROVED** [review]
LGTM, thanks!
