### PR TITLE
fix(24732): fix error when sending txn from dapp and editing the gas

### LINKED ISSUE #24732: [Bug]: Gas - MV3 - Editting a gas from a dapp tx breaks with `Cannot read properties of undefined (reading 'low')`
### Describe the bug

Whenever I am trying to edit the gas from a transaction that comes from a dapp, MetaMask breaks with the error `Cannot read properties of undefined (reading 'low')`.

Note: it feels like this should be captured by a test, so we should probably add one [here](https://github.com/MetaMask/metamask-extension/blob/develop/test/e2e/tests/transaction/edit-gas-fee.spec.js) alongside with the fix

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot from 2024-05-23 08-45-16

https://github.com/MetaMask/metamask-extension/assets/54408225/3ec848b3-28b6-4a23-b604-b30663587031

### Steps to reproduce

1. Go to the test dapp
2. Trigger any tx
3. Click the Edit gas button
4. See MM breaks with the error `Cannot read properties of undefined (reading 'low')`

### Error messages or log output

_No response_

### Version

develop MV3 build

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by DDDDDanica**
## **Description**
There is a racing condition captured in MV3 build. When sending transaction from dapp directly, if user chooses to edit the gas fee, and when `suggestedGasFees ` request is processing slow, `gasFeeEstimates` could be undefined within hook `useCustomTimeEstimate.js`. The fix is to add a condition for accessing this object before forwarding to UI.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24810?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24732

## **Manual testing steps**

1. Build in MV3
2. Trigger a txn from dapp
3. Open network panel, and trigger edit gas button before `suggestedGasFees` is finished fetching
4. You should see the network edition panel

### **Before**
 by @seaona 

https://github.com/MetaMask/metamask-extension/assets/12678455/f3e660a8-2d7b-4d1d-be31-69d5cd66d374

## **Pre-merge author checklist**

https://github.com/MetaMask/metamask-extension/assets/12678455/42b2df9d-a861-41ec-914e-89229493e276

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useCustomTimeEstimate.js [hunk 1]
```diff
@@ -73,12 +72,19 @@ export const useCustomTimeEstimate = ({
...
   ) {
-    waitTimeEstimate = high.minWaitTimeEstimate;
-  } else {
-    waitTimeEstimate = low.maxWaitTimeEstimate;
+    waitTimeEstimate = gasFeeEstimates.high?.minWaitTimeEstimate;
+  } else if (gasFeeEstimates) {
+    waitTimeEstimate = gasFeeEstimates.low?.maxWaitTimeEstimate;
   }
 
+  console.log({
```
Comment (pedronfigueiredo) [inline ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useCustomTimeEstimate.js:84]: [typo] remove `console.log`?

File: ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useCustomTimeEstimate.js [hunk 2]
```diff
@@ -73,12 +72,19 @@ export const useCustomTimeEstimate = ({
...
   } else if (
-    Number(maxPriorityFeePerGas) >= Number(medium.suggestedMaxPriorityFeePerGas)
+    gasFeeEstimates &&
+    Number(maxPriorityFeePerGas) >=
+      Number(gasFeeEstimates.medium?.suggestedMaxPriorityFeePerGas)
   ) {
-    waitTimeEstimate = high.minWaitTimeEstimate;
-  } else {
-    waitTimeEstimate = low.maxWaitTimeEstimate;
+    waitTimeEstimate = gasFeeEstimates.high?.minWaitTimeEstimate;
```
Comment (pedronfigueiredo) [inline ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useCustomTimeEstimate.js:79]: does this and the next condition not need `gasFeeEstimates &&` as well? Alternatively, perhaps `gasFeeEstimates?.` could work on all of them

**Review by pedronfigueiredo — APPROVED** [review]

File: ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useCustomTimeEstimate.js (hunk 2 above)
Comment (DDDDDanica) [reply ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useCustomTimeEstimate.js]: good suggestion ! added optional chaining in the equation

**Review by zone-live — APPROVED** [review]
