### PR TITLE
fix: updated permissions header to be consistent

### LINKED ISSUE #29785: [Bug]: Dapp url displayed as "Unkown origin" in the connection flow
### Describe the bug

See the recording below.

### Expected behavior

The connection flow should continue to display the dapp info throughout the flow.

### Screenshots/Recordings

https://github.com/user-attachments/assets/60256b44-59b6-47ec-9c0f-aeeec0ef2b45

### Steps to reproduce

1. Go to test dapp
2. Click connect

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.10.1

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR is to update the title of the Dapp in all the connection steps

## **Related issues**

Fixes: #29785 

## **Manual testing steps**

1. Connect MM to a Dapp
2. Check the correct Dapp Url is shown through all screens while connecting

### **Before**

https://github.com/user-attachments/assets/bedde663-5546-45cf-8d41-bc09441844d4

#### Dapp Connection 

https://github.com/user-attachments/assets/03a85c6a-942e-420e-bb46-bd5d252ddfc9

#### Snap Connection 

https://github.com/user-attachments/assets/28ee358c-fd2c-4476-ad75-41a55e1b0efd

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by vinnyhoward — DISMISSED** [review]

**Review by vinnyhoward — DISMISSED** [review]

File: ui/pages/permissions-connect/snaps/snap-install/snap-install.js [hunk 1]
```diff
@@ -116,7 +114,7 @@ export default function SnapInstall({
       backgroundColor={BackgroundColor.backgroundAlternative}
     >
       {(isLoading || hasError) && !isOriginSnap ? (
-        <PermissionConnectHeader origin={origin} iconUrl={iconUrl} />
+        <PermissionConnectHeader subjectMetadata={targetSubjectMetadata} />
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/snaps/snap-install/snap-install.js:117]: Since we only cache the subject metadata inside this component, this fix won't work for Snaps.

I'm assuming this bug can be reproduced using the Ethereum provider example Snap

File: ui/pages/permissions-connect/permissions-connect.component.js [hunk 2]
```diff
@@ -283,8 +283,7 @@ export default class PermissionConnect extends Component {
         ) : (
           <PermissionConnectHeader
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/permissions-connect.component.js:284]: Since we only cache the subject metadata inside this component, this fix won't work for Snaps.

I'm assuming this bug can be reproduced using the Ethereum provider example Snap

**Comment by hmalik88** [comment]
This breaks currently intended functionality for snaps installation. In your recording, the header changes to the solflare wallet as the origin making the connection request, it should remain the metamask.github.io origin until the installation screen.

File: ui/pages/permissions-connect/permissions-connect.component.js (hunk 2 above)
Comment (NidhiKJha) [reply ui/pages/permissions-connect/permissions-connect.component.js:284]: Do you mean the title here?
https://github.com/user-attachments/assets/edb8f7a4-9fae-4426-a60a-9376a09c5795

**Comment by NidhiKJha** [comment]
> This breaks currently intended functionality for snaps installation. In your recording, the header changes to the solflare wallet as the origin making the connection request, it should remain the `snap.metamask.io` origin until the installation screen.

Aah! I see. the npm title shouldn't be there. In this case, should I revert the props for snaps?

File: ui/pages/permissions-connect/permissions-connect.component.js (hunk 2 above)
Comment (FrederikBolding) [reply ui/pages/permissions-connect/permissions-connect.component.js:284]: No, notice "Unknown Origin" here: 

https://github.com/user-attachments/assets/d7b265cd-8aaa-43e8-bbbb-9d0daeb65463

**Comment by NidhiKJha** [comment]
> Aah! I see. the npm title shouldn't be there. In this case, should I revert the props for snaps?

I updated the prop value to use siteMetaData, I think it should resolve the issue.


https://github.com/user-attachments/assets/d5095b45-7aa8-468c-81b3-ec0960da4ee1

**Review by vinnyhoward — DISMISSED** [review]

File: ui/pages/permissions-connect/permissions-connect.component.js [hunk 3]
```diff
@@ -153,7 +156,14 @@ export default class PermissionConnect extends Component {
       history.replace(DEFAULT_ROUTE);
       return;
     }
-
+    // if this is an incremental permission request for permitted chains, skip the account selection
+    if (
+      permissionsRequest?.diff?.permissionDiffMap?.[
+        PermissionNames.permittedChains
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/permissions-connect.component.js:162]: This permission doesn't exist on `main`

Comment (NidhiKJha) [reply ui/pages/permissions-connect/permissions-connect.component.js]: Nice catch! Updated

File: ui/pages/permissions-connect/permissions-connect.component.js
Comment (FrederikBolding) [inline ui/pages/permissions-connect/permissions-connect.component.js:1]: This PR seems to reintroduce https://github.com/MetaMask/metamask-extension/issues/29594

File: ui/pages/permissions-connect/permissions-connect.component.js [hunk 4]
```diff
@@ -175,8 +177,8 @@ export default class PermissionConnect extends Component {
   }
 
   componentDidUpdate(prevProps) {
-    const { permissionsRequest, lastConnectedInfo, origin } = this.props;
-    const { redirecting } = this.state;
+    const { permissionsRequest, lastConnectedInfo } = this.props;
+    const { redirecting, origin } = this.state;
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/permissions-connect.component.js:181]:
```suggestion
    const { permissionsRequest, lastConnectedInfo, targetSubjectMetadata } = this.props;
    const { redirecting, origin } = this.state;
    
    if (targetSubjectMetadata && targetSubjectMetadata.origin) {
      this.setState({ targetSubjectMetadata });
    }
```

What if we do something like this?

Comment (danjm) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: I was thinking that as well, but that change reintroduces the display of "unknown origin" :thinking:

Comment (danjm) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: maybe it is that change plus something else...

Comment (FrederikBolding) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: Ah. You're right. So this caching breaks the Snaps connection flow 🤔

Comment (danjm) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: I think this works:
```
    const { permissionsRequest, lastConnectedInfo, targetSubjectMetadata } = this.props;
    const { redirecting, origin } = this.state;

    if (prevProps.targetSubjectMetadata?.origin !== targetSubjectMetadata?.origin && 
         targetSubjectMetadata?.origin) {
      this.setState({ targetSubjectMetadata });
    }
```

I tested it and the unknown origin bug and #29594 are fixed. Just need  to confirm that the snaps case is still working as well

Comment (FrederikBolding) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: Yep, I was just updating my suggestion to a similar thing as well

Comment (danjm) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: I believe that the headers on snaps connect request are still working as well

Comment (FrederikBolding) [reply ui/pages/permissions-connect/permissions-connect.component.js:181]: Yeah, from my testing the snippet above seems to do the trick

Comment (NidhiKJha) [reply ui/pages/permissions-connect/permissions-connect.component.js]: Updated here https://github.com/MetaMask/metamask-extension/pull/29880/commits/56c81e263c0c502d9349b4a94ab21aa847b30ac2

File: ui/pages/permissions-connect/permissions-connect.component.js [hunk 5]
```diff
@@ -175,8 +177,16 @@ export default class PermissionConnect extends Component {
   }
 
   componentDidUpdate(prevProps) {
-    const { permissionsRequest, lastConnectedInfo, origin } = this.props;
-    const { redirecting } = this.state;
+    const { permissionsRequest, lastConnectedInfo, targetSubjectMetadata } =
+      this.props;
+    const { redirecting, origin } = this.state;
+
+    if (
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/permissions-connect.component.js:184]:
```suggestion
    // We cache the last known good targetSubjectMetadata since it may be null when the approval is cleared
    if (
```
IMO this deserves a comment

Comment (NidhiKJha) [reply ui/pages/permissions-connect/permissions-connect.component.js:185]: Updated here https://github.com/MetaMask/metamask-extension/pull/29880/commits/4f47a967f20c391723947160800bb612a1b9505b

**Review by FrederikBolding — APPROVED** [review]

**Review by jonybur — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

**Review by danjm — APPROVED** [review]

**Comment by darkwing** [comment]
## :one: What was the issue?
.

## :two: Why did it happen and why wasn’t it caught earlier?
.

## :three: What actions are we taking to prevent this in the future?
.

## :four: Any related tickets and ETAs for follow-up actions?
.
