### PR TITLE
fix: Fix #28097 - Prevent redirect after adding network in Onboarding Settings

### LINKED ISSUE #28097: [Bug]: Onboarding - After adding a network while in the Onboarding Settings page, I land into the Password screen and when Iog in I land again into the Onboarding page
### Describe the bug

When I am performing the Onboarding flow, if I go to General Settings and I add a network, I see how I land automatically to the Password page.
This seems wrong. After I add my newly created password, I land back again into the Onboarding page Your Wallet is Ready.

### Expected behavior

After adding a network, I should remain into the Onbording General Settings page

### Screenshots/Recordings

https://github.com/user-attachments/assets/961920a6-40e5-4910-9c3e-ffe2be1a3517

### Steps to reproduce

1. Start the onboarding
2. Click Manage Settings
3. Go to General Settings
4. Click Add network
5. Click Arrow back
6. Add any popular network
7. See how you land into the Password page
8. Log in
9. See how you land back to the Your wallet is ready page

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## **Description**

Prevents the post-add-network redirect from happening if the user is on the onboarding screen.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28097

## **Manual testing steps**

STR's are in https://github.com/MetaMask/metamask-extension/issues/28097

### **After**

https://github.com/user-attachments/assets/ed136a3f-e06c-4c78-a76f-fd08a9865390

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [X] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js [hunk 1]
```diff
@@ -381,7 +384,13 @@ function getValues(pendingApproval, t, actions, history, data) {
           nickname: pendingApproval.requestData.chainName,
         });
 
-        history.push(DEFAULT_ROUTE);
+        const locationPath = document.location.hash.replace('#', '/');
```
Comment (bergeron) [inline ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js:387]: Good fix.  I noticed this too but wasn't sure how to fix it.  I was trying use `state.metamask.completedOnboarding` to determine whether to redirect, but didn't know how to access it here.  document.location seems like it'll work

**Review by bergeron — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
