### PR TITLE
fix: undefined market data selector

### LINKED ISSUE #26243: [Bug]: Cannot convert undefined or null to object
### Describe the bug

Sending USDT on BSC to an address crashes MetaMask and makes it unusable even after the restart. I have sent USDT countless times on BSC before so that's a regression of v12. 

The way to reset MetaMask is to restart chrome, switch MetaMask to another network, Reset activity, then back to BSC and again Reset activity and only after that I can use MetaMask again. 

Bug is 100% repeatable.

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot 2024-07-31 at 11 25 39

### Steps to reproduce

1. Open metamask, enter password
2. Go to Tokens tab
3. Select USDT
4. Click Send
5. Choose address in Contacts
6. Enter a positive amount
7. Click Continue

Boom, `Cannot convert undefined or null to object`

### Error messages or log output

```shell
MetaMask encountered an error
Try again by closing and reopening the popup, or contact support here.
Error details
Message: Cannot convert undefined or null to object

Code: TypeError

Stack:
TypeError: Cannot convert undefined or null to object
  at Function.entries (<anonymous>)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-9.js:1:204169
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/sentry-install.js:1:681)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:252205
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/sentry-install.js:1:681)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:251529
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:180624
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:181223
  at g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:108263)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:61316)
  at Cs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:106147)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:92055)
  at Ou (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:91980)
  at Tu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:89328)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47726
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:13158)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47435)
  at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47671)
  at Ji (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47606)
  at $u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:104354)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:13158)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47435)
  at Bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:104005)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:103916
  at B (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:12540)
  at T.port1.onmessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:11284)
```
```


### Detection stage

In production (default)

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bergeron**
## **Description**

Fixes an issue when `Show balance and token price checker` is turned off in settings, certain actions like sending, importing, or swapping a token crash metamask.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26264?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26243

## **Manual testing steps**

1. Go into settings > security and privacy
2. Turn off `Show balance and token price checker`
3. Switch chains
4. Click import tokens on the tokens tab. Modal should popup without error
5. Click swap and enter tokens + amount.  Swap rate should fetch successfully.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/confirm-transaction.js [hunk 1]
```diff
@@ -153,19 +154,6 @@ export const txDataSelector = (state) => state.confirmTransaction.txData;
...
-  const contractMarketData = state.metamask.marketData?.[chainId];
-
-  return Object.entries(contractMarketData).reduce(
-    (acc, [address, marketData]) => {
-      acc[address] = marketData?.price ?? null;
-      return acc;
-    },
-    {},
-  );
-};
```
Comment (bergeron) [inline ui/selectors/confirm-transaction.js:167]: This chunk was identical to the `getTokenExchangeRates` selector, except it did not include a `?? {}` to handle the undefined case.  So I just made it re-use that selector instead.

File: ui/selectors/confirm-transaction.js [hunk 2]
```diff
@@ -218,7 +206,7 @@ export const sendTokenTokenAmountAndToAddressSelector = createSelector(
 );
 
 export const contractExchangeRateSelector = createSelector(
-  contractExchangeRatesSelector,
+  (state) => getTokenExchangeRates(state),
```
Comment (bergeron) [inline ui/selectors/confirm-transaction.js:209]: You'd think `getTokenExchangeRates` would work here instead of a lambda, but the tests don't like it.  I suspect that's why the original code duplicated the selector.

```
 FAIL  app/scripts/metamask-controller.actions.test.js
  ● Test suite failed to run

    Selector creators expect all input-selectors to be functions, instead received the following types: [undefined, function]

      206 | );
      207 |
    > 208 | export const contractExchangeRateSelector = createSelector(
          |                                                           ^
      209 |   getTokenExchangeRates,
```


I've encountered this situation a few times, and never discovered why it happens.  I think you can also fix it by stubbing the selector in the tests.  But the lambda seems to work too.

**Review by gambinish — DISMISSED** [review]

File: ui/selectors/confirm-transaction.js [hunk 3]
```diff
@@ -218,7 +206,7 @@ export const sendTokenTokenAmountAndToAddressSelector = createSelector(
...
   tokenAddressSelector,
   (contractExchangeRates, tokenAddress) => {
     return contractExchangeRates[
```
Comment (bergeron) [inline ui/selectors/confirm-transaction.js:212]: Code below could probably look up via the checksummed address instead of the O(n) case insensitive search

**Comment by bergeron** [comment]
Something fishier may be going on.  This selector should run when there's a pending transaction, not when importing a token.

**Review by salimtb — DISMISSED** [review]

**Comment by sleepytanya** [comment]
@bergeron I still the 'Cannot convert undefined or null to object' error

File: ui/components/multichain/import-tokens-modal/import-tokens-modal.js [hunk 4]
```diff
@@ -137,7 +137,7 @@ export const ImportTokensModal = ({ onClose }) => {
   const accounts = useSelector(getInternalAccounts);
   const tokens = useSelector((state) => state.metamask.tokens);
   const rpcPrefs = useSelector(getRpcPrefsForCurrentProvider);
-  const contractExchangeRates = useSelector(contractExchangeRateSelector);
+  const contractExchangeRates = useSelector(getTokenExchangeRates);
```
Comment (bergeron) [inline ui/components/multichain/import-tokens-modal/import-tokens-modal.js:140]: I don't think the previous selector made sense.  It only returned the exchange rate of the current token being transacted.  Whereas the variable is accessed like an object containing rates for multiple tokens.

**Comment by bergeron** [comment]
> @bergeron I still the 'Cannot convert undefined or null to object' error

With what repro steps

**Comment by sleepytanya** [comment]
@bergeron 
Go into settings > security and privacy
Turn off Show balance and token price checker
Switch chains
Click import tokens on the tokens tab
Swap - error fetching quotes / Cannot convert undefined or null to object

I'm using this build https://github.com/MetaMask/metamask-extension/pull/26264#issuecomment-2261298719

**Comment by bergeron** [comment]
I can't reproduce with those steps on that build

**Comment by sleepytanya** [comment]
@bergeron  Fixed!
build commit https://github.com/MetaMask/metamask-extension/pull/26264/commits/e5c9a7513e721aa5db8469585adf4b7299f28e85


https://github.com/user-attachments/assets/51b06ac5-f738-460a-bded-b464e48b7c05

**Review by gambinish — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]

**Review by danjm — APPROVED** [review]

File: ui/selectors/confirm-transaction.js (hunk 2 above)
Comment (Gudahtt) [reply ui/selectors/confirm-transaction.js:209]: This error is caused by the function being `undefined` at the point in time this is executed. This could happen because the function is defined later in the module (as a variable, so not hoisted to the top like function declarations are), but more often I've seen this happen due to a circular dependency between the current file and the file we're importing the selector from.

One of the tech debt tasks in-progress now is an effort to remove all circular dependencies in our codebase and implement a lint rule preventing their re-introduction, so hopefully we can resolve this soon. But in the meantime this solution works.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by martahj — APPROVED** [review]

**Review by klejeune — APPROVED** [review]
Approved on behalf of @martahj
