### PR TITLE
fix: cp-12.17.0 clamp search token results that don't exist

### LINKED ISSUE #32212: [Bug]: Application crashes when searching for tokens in import dialog for Ethereum Network
### Describe the bug

When users attempt to search for tokens in the import dialog for the Ethereum network, the application crashes. This issue disrupts the user experience and prevents users from successfully importing tokens. The crash occurs consistently when performing a search operation within the import dialog.

### Expected behavior

When the search is unable to fetch the token then message should appear

### Screenshots/Recordings

https://github.com/user-attachments/assets/0fc88968-4e83-4150-a66b-c09dd6cab8da

### Steps to reproduce

1. Open the application. 
2. Navigate to the import dialog and the select the Ethereum network. 
3. In the search dialog type letter ddd. 
4. Observe the application errors out. 

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.17.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32213?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32212

## **Manual testing steps**

See repro steps in issue.

### **Before**

See issue.

### **After**

https://www.loom.com/share/4ff57c7e01714bcfa514aadd8df79e8e?sid=03a7dc9e-ea4c-4e2c-800f-86108623b0bc

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/import-token/token-list/token-list.component.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ export default class TokenList extends Component {
             display={Display.Flex}
             flexDirection={FlexDirection.Column}
           >
-            {Array(12)
+            {Array(Math.min(12, results.length))
```
Comment (Prithpal-Sooriya) [inline ui/components/app/import-token/token-list/token-list.component.js:77]: We clamp the number of items we are processing.

This is because our results we get back might be less than 12.

File: ui/components/app/import-token/token-list/token-list.component.js
Comment (Prithpal-Sooriya) [inline ui/components/app/import-token/token-list/token-list.component.js:1]: (side note) looking at the recording, is seems this component renders quite frequently. Maybe we can improve the performance of this or the parent component in a future PR.

**Review by salimtb — APPROVED** [review]
lgtm

File: ui/components/app/import-token/token-list/token-list.component.js
Comment (gambinish) [reply ui/components/app/import-token/token-list/token-list.component.js:1]: This is definitely a component that's worth refactoring. Moving to TS would probably also be a good idea

**Review by gambinish — APPROVED** [review]
