### PR TITLE
Track when token balance is changed to update value on approval screen

### LINKED ISSUE #16718: [Bug]: Improved Approval screen does not show updated balance if a tx is confirmed while screen is open
### Describe the bug

**Problem**: if I have triggered the Approve function while I have a pending transaction, I will see that the Balance and max Spending Cap always refers to the balance I had prior that transaction is confirmed.
This means that once the transaction is confirmed, I have less balance in my account but I am still able to see the old balance and the max Spending Cap referring to that old balance.

https://user-images.githubusercontent.com/54408225/204507303-acedb53d-0cf8-41c3-95d2-ea5b66515dff.mp4

### Steps to reproduce

1. Go to test Dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token
4. Accept transaction on MM
5. Click Add Token to the Wallet
6. Accept prompt on MM
7. Click Transfer tokens
8. Accept transaction on MM
9. Click Approve tokens (before transaction on step 8 has been confirmed)
10. See Balance and max spending cap
11. Wait until transaction of step 8 has been confirmed
12. See Balance and max spending cap is not updated

### Error messages or log output

_No response_

### Version

10.23.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amerkadicE**
## Explanation

The token balance is not updated on the approval screen when a transaction is made in the background. Currently, we only track token address, user address, and transaction data to the re-render approval screen using the useAssetDetails hook.

This PR solution will track when the token balance is updated and get asset details data updated.

Fixes #16718 

### After

https://user-images.githubusercontent.com/97883527/207816464-802f134a-7e2f-4597-a82a-c45efff4d2c8.mov

## Manual Testing Steps

1. Go to test Dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token
4. Accept transaction on MM
5. Click Add Token to the Wallet
6. Accept prompt on MM
7. Click Transfer tokens
8. Accept transaction on MM
9. Click Approve tokens (before transaction on step 8 has been confirmed)
10. See Balance and max spending cap
11. Wait until transaction of step 8 has been confirmed
12. See Balance and max spending cap is updated

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by fejzic** [comment]
Verified by QA

**Comment by WalletSupportt** [comment]
> ## Explanation
> 
> The token balance is not updated on the approval screen when a transaction is made in the background. Currently, we only track token address, user address, and transaction data to the re-render approval screen using the useAssetDetails hook.
> 
> This PR solution will track when the token balance is updated and get asset details data updated.
> 
> 
> 
> Fixes #16718 
> 
> ## Screenshots/Screencaps
> 
> 
> 
> ### Before
> 
> 
> 
> ### After
> 
> 
> 
> https://user-images.githubusercontent.com/97883527/207816464-802f134a-7e2f-4597-a82a-c45efff4d2c8.mov
> 
> 
> ## Manual Testing Steps
> 
> 
> 
> 1. Go to test Dapp https://metamask.github.io/test-dapp/
> 2. Connect MM
> 3. Click Create Token
> 4. Accept transaction on MM
> 5. Click Add Token to the Wallet
> 6. Accept prompt on MM
> 7. Click Transfer tokens
> 8. Accept transaction on MM
> 9. Click Approve tokens (before transaction on step 8 has been confirmed)
> 10. See Balance and max spending cap
> 11. Wait until transaction of step 8 has been confirmed
> 12. See Balance and max spending cap is updated
> 
> ## Pre-merge author checklist
> 
> - [ ] I've clearly explained:
>   - [ ] What problem this PR is solving
>   - [ ] How this problem was solved
>   - [ ] How reviewers can test my changes
> - [ ] Sufficient automated test coverage has been added
> 
> ## Pre-merge reviewer checklist
> 
> - [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
> - [ ] PR is linked to the appropriate GitHub issue
> - [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone
> 
> If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.
> 
> In this case, a QA Engineer approval will be be required.
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

File: ui/hooks/useAssetDetails.js [hunk 1]
```diff
@@ -1,22 +1,37 @@
...
+  const currentToken = tokens.find((token) =>
+    isEqualCaseInsensitive(token.address, tokenAddress),
+  );
 
   // in-hook state
   const [currentAsset, setCurrentAsset] = useState(null);
 
+  let tokensWithBalance;
+  if (currentToken) {
+    // eslint-disable-next-line react-hooks/rules-of-hooks
```
Comment (digiwand) [inline ui/hooks/useAssetDetails.js:25]: thinking of ways to avoid disabling eslint on this line.

what if we did
```
  const { tokensWithBalances } = useTokenTracker(
    currentToken ? [currentToken] : null,
  );
```

with an added null check in `useTokenTracker`? I think this works assuming `state.metamask.tokens` is always an array even when it's loading. I'm assuming this is also true based on the logic from line 16 above

Comment (danjm) [reply ui/hooks/useAssetDetails.js:25]: I think we should be able to achieve the same effect by just passing `useTokenTracker` an empty array? (and then the `useTokenTracker` hook would not have to be modified

```
  const { tokensWithBalances } = useTokenTracker(
    currentToken ? [currentToken] : [],
  );
 ```
 
 I agree that we should not disable eslint rules for hooks

Comment (amerkadicE) [reply ui/hooks/useAssetDetails.js]: Thank you for suggestion, I updated my PR

**Review by danjm — APPROVED** [review]
LGTM

**Review by jpuri — APPROVED** [review]
LGTM
