### PR TITLE
fix: Hide fiat values on test networks

### LINKED ISSUE #27814: [Bug]: Despite the "Show conversion on test networks" option being disabled in Advanced Settings, fiat values are still displayed on redesigned transaction requests
### Describe the bug

Despite the `Show conversion on test networks` option being disabled in `Advanced Settings`, fiat values are still displayed on redesigned transaction requests

### Expected behavior

`Show conversion on test networks` setting effectively controls the display of fiat values according to user preferences.

### Screenshots/Recordings

https://github.com/user-attachments/assets/e2b36c3a-8278-4871-bacd-7f8fb4344ff3

### Steps to reproduce

1. Connect to test network Sepolia or L2 test network [Arbitrum Sepolia](https://chainlist.org/chain/421614))
2. Disable `Show conversion on test networks` option in `Settings -> Advanced`
3. Go to [test dapp](https://metamask.github.io/test-dapp/)
4. Click `Create token`

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.4.0, 12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Hides fiat values by default unless "Show conversion on test networks" is toggled on in the settings. Includes changes to the gas fees components, and the send heading components for native and erc20 tokens.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28219?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27814

## **Manual testing steps**

1. Toggle off "Show conversion on test networks" in the settings
2. Initiate a SepoliaETH or any erc20 token transfer from the wallet on Sepolia network
3. Check the gas fees components and the heading component.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx [hunk 1]
```diff
@@ -31,6 +33,9 @@ export const EditGasFeesRow = ({
   const { currentConfirmation: transactionMeta } =
     useConfirmContext<TransactionMeta>();
 
+  const isTestnet = useSelector(getIsTestnet);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx:36]: Can we do this in a multi-chain way without coupling to the global network?

**Review by matthewwalsh0 — APPROVED** [review]

File: ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx [hunk 2]
```diff
@@ -75,11 +78,12 @@ const SendHeading = () => {
       >{`${displayTransferValue} ${tokenSymbol}`}</Text>
     );
 
-  const TokenFiatValue = fiatDisplayValue && (
-    <Text variant={TextVariant.bodyMd} color={TextColor.textAlternative}>
-      {fiatDisplayValue}
-    </Text>
-  );
+  const TokenFiatValue = Boolean(fiatDisplayValue) &&
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx:81]: As we duplicate this and the hook usage in three places, is it worth a `FiatValue` component that encapsulates this?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx (hunk 2 above)
Comment (pedronfigueiredo) [reply ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx:81]: I think this is only used in two places, and since calculations for fiatDisplayValue are already encapsulated in the `useTokenValues` hook, creating a separate component seems a bit premature or at least optional at this point.

The parent SendHeading and NativeSendHeading components would still rely on the same useTokenValues if we created a FiatDisplay component, so it doesn't seem like a big gain in modularity.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
