### PR TITLE
fix cached detected token results

### LINKED ISSUE #16349: [Bug]: [MV3] Token detection is caching results between accounts when terminating service worker
### Describe the bug

**Problem**: when I terminate the service worker and I change accounts, I see that the tokens detected are cached.

https://user-images.githubusercontent.com/54408225/199470301-596396d3-e524-4097-9a1e-faaa98421993.mp4

### Steps to reproduce

1. Unlock MM
2. Get some tokens on the first account, so they are detected
3. Create a fresh new account
4. Change back to the account from step 2
5. Terminate service worker
6. Change back to the account from step 3 -- see that token detected are cached

### Error messages or log output

_No response_

### Version

Tested on top of this PR https://github.com/MetaMask/metamask-extension/pull/15558

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

There is another caching issue with Token Detection which might also be related? See this comment and issue on MV2
https://github.com/MetaMask/metamask-extension/issues/16057#issuecomment-1291129607

### PR DESCRIPTION
**Pull request by adonesky1**
~Blocked by https://github.com/MetaMask/controllers/pull/956 (and subsequent release of `@metamask/controllers`)~

Context (from https://github.com/MetaMask/controllers/pull/956):

_Currently there exists an issue (exposed by https://github.com/MetaMask/metamask-extension/issues/16349) where if a user changes accounts (account x to account y) or (changes from network a to network b) right as a detectTokens() call is occuring, the results of the getBalancesInSingleCall() call (withindetectTokens()) made against address x or network acan get incorrectly misattributed to accountyornetwork b. This can happen because currently detectTokens() simply calls this.addDetectedTokens() on the TokensController with the detected tokensToAdd assuming that when this call occurs in the TokensController the selectedAddress or chainId [used to store these detected assets](https://github.com/MetaMask/controllers/blob/9b82201b4c99059a7ab35942febdba840adce5ee/packages/assets-controllers/src/TokensController.ts#L709) will be the same as the one used to detect them. With sufficiently unfortunate timing this expectation can be broken, and so this PR introduces a pattern ([already used in the analogous flow between the NftDetectionController and the NftController](https://github.com/MetaMask/controllers/blob/main/packages/assets-controllers/src/NftDetectionController.ts#L397), whereby the address and network data are passed along with the detectedToken data to ensure they are stored correctly._

This PR leverages the changes made in https://github.com/MetaMask/controllers/pull/956, and additionally fixes a race condition that occurs where even if the detection data is stored correctly, the `detectedTokens` value does not get updated to reflect the correct chainId/network combo if/when the network/account is changed while the service worker is being restarted.

* Fixes https://github.com/MetaMask/metamask-extension/issues/16349

### Before

https://user-images.githubusercontent.com/34557516/206777046-4fbabb91-bcba-4bb9-9ffe-d380a0665238.mov

### After

https://user-images.githubusercontent.com/34557516/206775291-19339d64-232c-4271-99ad-7839165f3b76.mov

## Manual Testing Steps

1. Unlock MM
2. Get some tokens on the first account, so they are detected
3. Create a fresh new account
4. Change back to the account from step 2
5. Terminate service worker
6. Change back to the account from step 3 -- see that no detected tokens are cached

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes

### CODE REVIEW

File: app/scripts/controllers/detect-tokens.js [hunk 1]
```diff
@@ -182,12 +188,26 @@ export default class DetectTokensController {
...
-  restartTokenDetection() {
-    if (!(this.isActive && this.selectedAddress)) {
+  restartTokenDetection({ selectedAddress, chainId } = {}) {
+    const addressAgainstWhichToDetect = selectedAddress ?? this.selectedAddress;
+    const chainIdAgainstWhichToDetect = chainId ?? this.chainId;
+    if (
+      !(
+        this.isActive ||
+        !addressAgainstWhichToDetect ||
+        chainIdAgainstWhichToDetect !== CHAIN_IDS.MAINNET
```
Comment (NiranjanaBinoy) [inline app/scripts/controllers/detect-tokens.js:202]: Currently, token detection is enabled for only MAINNET but on Binance, Polygon, and Avalanche. We are checking for the same in line 97 as well.

**Comment by NiranjanaBinoy** [comment]
This PR is showing some issues with the display of the detected tokens link in the overview page, this is because `allDetectedTokens` is not getting cleared properly when the tokens are imported, and then we are using data from `allDetectedTokens[chainIs][selectedAddress]` to get the detectedTokens on the front end.  We already have a [ticket](https://github.com/MetaMask/metamask-extension/issues/16854) for this issue related to [balance and token price checking PR](https://github.com/MetaMask/metamask-extension/pull/16772)

File: app/scripts/controllers/detect-tokens.js (hunk 1 above)
Comment (jpuri) [reply app/scripts/controllers/detect-tokens.js:202]: May be use=ing method `isTokenDetectionEnabledForNetwork` will be better here than this comparison.

Comment (adonesky1) [reply app/scripts/controllers/detect-tokens.js:202]: true I suppose we can just remove this check since it takes place in `detectNewTokens` which is called below.

Comment (adonesky1) [reply app/scripts/controllers/detect-tokens.js]: updated [here](https://github.com/MetaMask/metamask-extension/pull/16866/commits/34af9a7e31b45602662c3b1f802f3022cc1f99b2) @NiranjanaBinoy

File: app/scripts/controllers/detect-tokens.js [hunk 2]
```diff
@@ -219,8 +233,9 @@ export default class DetectTokensController {
     this._network = network;
     this._network.store.subscribe(() => {
       if (this.chainId !== this.getChainIdFromNetworkStore(network)) {
-        this.restartTokenDetection();
-        this.chainId = this.getChainIdFromNetworkStore(network);
+        const chainId = this.getChainIdFromNetworkStore(network);
+        this.chainId = chainId;
+        this.restartTokenDetection({ chainId: this.chainId });
```
Comment (NiranjanaBinoy) [inline app/scripts/controllers/detect-tokens.js:238]: Shouldn't we update the `this.restartTokenDetection()` with params with selectedAddress  in line 69 where it is called when the preference state changes with selectedAddress change as well?

Comment (adonesky1) [reply app/scripts/controllers/detect-tokens.js:238]: yes! I think that change must have gotten lost in a rebase!

Comment (adonesky1) [reply app/scripts/controllers/detect-tokens.js:238]: Great catch!

Comment (adonesky1) [reply app/scripts/controllers/detect-tokens.js:238]: Done [here](https://github.com/MetaMask/metamask-extension/pull/16866/commits/02b67c3cf8b6a357ec81213bf162b5585e716ca1)

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Review by jpuri — APPROVED** [review]
