### PR TITLE
fix: exclude non evm tokens and chains if BFT is off

### LINKED ISSUE #38111: [Bug]: Basic Functionality - When disabled, I can still start a Send and select Non-EVM networks, leading to being blocked in the Recipient screen with an error
### Describe the bug

When Basic Functionality disabled, I can still start a Send and select Non-EVM networks, leading to being blocked in the Recipient screen

### Expected behavior

We shouldn't see nonEVM networks in the assets list, if we have Basic Functionality off.
We already see the Send button disabled, if I have any of the non-EVM netowrk selected (Expected)

[HB] Send asset list and network filter excludes non-EVM networks when Basic Functionality is disabled.

### Screenshots/Recordings

https://github.com/user-attachments/assets/b095a976-1432-469a-aa17-fc3426383055

### Steps to reproduce

1. Go toSettings
2. Disable Basic Functionality
3. Select All networks
4. Click Send
5. Click Asset --> see you can select non-EVM assets
6. Select one
7. Add amount
8. See 'invalid value' error and not able to proceed

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

This PR ensures that non-EVM tokens and chains are excluded from the UI when the Basic Functionality Toggle (BFT) is turned OFF.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38914?quickstart=1)

## **Changelog**

CHANGELOG entry: Makes sure UI filters out non-evm chains and tokens when BFT is OFF.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38111

## **Manual testing steps**

Scenario 1:

1. Make sure you have "all networks" selected
2. Go to settings and turn OFF BFT setting
3. Go back to home page
4. Make sure the non-evm assets are filtered out from asset list
5. Click on network filter and make sure non evm chains are filtered out
6. The swap button should be disabled
7. Click on send button and make sure non-evm assets are filtered out of the send asset list
8. Click on network filter and make sure non-evm chains are filtered out
9. Make sure you cannot search for non evm assets

Scenario 2:

1. Make sure you have Solana selected
2. Go to settings and turn off BFT
3. Go back to home page; you should still see non-evm assets since you already have solana selected
4. Network filter should only contain that specific chain (Solana)
5. Swap button is disabled
6. Click on send button
7. non-evm assets should be filtered out
8. non-evm chains should be filtered out from the network filter
9. You should not be able to search for non evm chains

### **After**

https://github.com/user-attachments/assets/e47e7475-952c-4927-a058-e5b3f527ae1c

https://github.com/user-attachments/assets/35101b9a-2ba7-4652-a88d-29a853758e4a

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Enforces EVM-only experience when `getUseExternalServices` is false, with an exception to keep the currently selected non‑EVM chain visible.
> 
> - Asset list (`token-list.tsx`): Filters non‑EVM assets when BFT is OFF; still shows assets for the selected non‑EVM chain; includes zero-balance and TRX resource checks; preserves sorting
> - Network manager (`default-networks.tsx`): Hides non‑EVM networks in default and featured lists when BFT is OFF, except the selected non‑EVM chain; updates network item filtering logic accordingly
> - Send flow (`useSendAssets.ts`): Filters out non‑EVM tokens and NFTs when BFT is OFF so non‑EVM chains don’t appear in the send asset/network selectors; adds tests
> - Buttons: Adds `disableSendForNonEvm` to `CoinButtons`/`TokenButtons` and disables Send on asset pages for non‑EVM when BFT is OFF; keeps Swap disabled when external services are off; updates `non-evm-overview.test.tsx` expectations
> - Asset page: Passes `disableSendForNonEvm` to native/token buttons
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 15ced273a70eaa14c3a75a767795bedd18713b94. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: ui/components/app/assets/token-list/token-list.tsx [hunk 1]
```diff
@@ -102,9 +105,18 @@ function TokenList({ onTokenClick, safeChains }: TokenListProps) {
         },
       ]);
 
-      return sortAssets([...filteredAssets], tokenSortConfig);
-    }
+      // Filter out non-EVM assets when basic functionality toggle is OFF
+      // Exception: Keep assets for the currently selected non-EVM chain
+      const finalAssets = useExternalServices
+        ? filteredAssets
+        : filteredAssets.filter(
```
Comment (bergarces) [inline ui/components/app/assets/token-list/token-list.tsx:102]: This will only exclude them from the token list itself. They will probably still show in the send flow list and other features.

I think the basic functionality toggle is an extension-only thing, so no point on adding this filter to the core selectors, but if we want this to be extended to other features of the app, we should filter them inside `getAssetsBySelectedAccountGroup`.

**Review by bergarces — DISMISSED** [review]

File: ui/components/app/assets/token-list/token-list.tsx (hunk 1 above)
Comment (sahar-fehri) [reply ui/components/app/assets/token-list/token-list.tsx:102]: I have also excluded them from the send flow list. You should not be able to search for them and non-evm chains are also excluded from the send flow network filter

Comment (OGPoyraz) [reply ui/components/app/assets/token-list/token-list.tsx:102]: Afraid I agree with @bergarces here.

Rather than fixing every case on wallet-wide, we must filter it on high level `getAssetsBySelectedAccountGroup` selector. Because this still doesn't change the fact that nonEVM tokens are responded from the selector, which shouldn't. (This is still not the ideal solution but quickest - all these BF cases should've signaled by the network snaps to controllers tbh)

We have few cases today (send/tokens etc) but we can't guarantee new features will always cover that. Also if BF is off - results, assets will not have correct information like balances/fiat values etc. 

Also on the technical side - it will be less code, logic to maintain. Probably you will end up with no confirmation code changes if this is done on selector.

**Review by OGPoyraz — CHANGES_REQUESTED** [review]

File: ui/components/app/assets/token-list/token-list.tsx (hunk 1 above)
Comment (sahar-fehri) [reply ui/components/app/assets/token-list/token-list.tsx:102]: After looking more into this; doing this on the core selector would mean that selector would not return non-EVM assets when BFT is OFF (impl attempt https://github.com/MetaMask/core/pull/7545)
The behavior we are looking for on the client does not exactly match this. If the user is already on a non-EVM chain exp Solana and he has assets on that chain, we would still want him to be able to see those assets; just that he wont be able to swap; and if he attempts to send he should not be able to see any of those assets/ non evm chains.

I think the current client impl makes sense for the user experience we want to have.
If we want to offload everything to core; i think core selector would also need to be aware of the user's current selected chain and even when we do that; we would need to know if we are on the main asset list, in which case we want to still show his assets; and if he is on the send flow assets list, we want to filter them out.

Comment (OGPoyraz) [reply ui/components/app/assets/token-list/token-list.tsx:102]: > The behavior we are looking for on the client does not exactly match this. 

I just saw the comments under the task here: https://github.com/MetaMask/metamask-extension/issues/38111#issuecomment-3631358211 . However I am not convinced with the solution yet.

> we would still want him to be able to see those assets; just that he wont be able to swap

Initially we discussed in the Confirmations and the aim was - MM should get rid off all nonEVM functionality if BF is off - not only filtering assets from send or swap. Because this will be a patchy solution. Users will keep seeing the unsynced balances, tokens, activity and all that. Basically leaving the wallet inconsistent state, without any notification to user. 

There must be a generic solution that Wallet UX should define when BF is off. We shouldn't apply filter every spot where we use nonEVM components.

I will open a separate thread for this after prod0.

Comment (sahar-fehri) [reply ui/components/app/assets/token-list/token-list.tsx:102]: I dnt mind waiting for another round of discussion around this;
I have a thread with @hesterbruikman around this in the github issue.
The final user experience we agreed on is to still show non-evm tokens on the main page when BFT is off and user has a non-evm network selected. We want to filter them out on send flow.

If we want to change this to filtering out non-evm assets even on tokens tab; then i think solution with this core [PR](https://github.com/MetaMask/core/pull/7545) makes sense;

File: ui/pages/confirmations/hooks/send/useSendAssets.ts [hunk 2]
```diff
@@ -11,12 +15,28 @@ type SendAssets = {
...
-  return useMemo(
-    () => ({
+  return useMemo(() => {
+    // When BFT is OFF, filter out non-EVM tokens
+    if (!useExternalServices) {
+      const filteredTokens = tokens.filter((token) => {
+        // Skip tokens without a chainId
+        if (!token.chainId) {
+          return false;
+        }
```
Comment (OGPoyraz) [inline ui/pages/confirmations/hooks/send/useSendAssets.ts]: This will never be a case as "tokens" are collected with map of `chainId` inside `useSendTokens` hence we can remove it.

Image

File: ui/pages/confirmations/components/send/network-filter/network-filter.tsx
Comment (OGPoyraz) [inline ui/pages/confirmations/components/send/network-filter/network-filter.tsx:1]: We can revert the changes in this file and tests. Because `<NetworkFilter />` component deriving "networks" from the "tokens" returned from `useSendAssets` https://github.com/MetaMask/metamask-extension/blob/main/ui/pages/confirmations/components/send/asset/asset.tsx#L63

Since we filter tokens - there won't be any nonEVM networks at all.

**Review by OGPoyraz — CHANGES_REQUESTED** [review]
We should also disable the token detail "Send" button if BFT is off. Because that will navigate into `AmountRecipient` which means it will bypass the send asset page.

Image

File: ui/components/app/assets/token-list/token-list.tsx (hunk 1 above)
Comment (OGPoyraz) [reply ui/components/app/assets/token-list/token-list.tsx:102]: As discussed with the team, we will accept this filtering from send flow as an temporary solution. Hence I am resolving this thread.

File: ui/components/app/wallet-overview/non-evm-overview.test.tsx [hunk 3]
```diff
@@ -467,7 +467,8 @@ describe('NonEvmOverview', () => {
     const sendButton = queryByTestId(BTC_OVERVIEW_SEND);
     const bridgeButton = queryByTestId(BTC_OVERVIEW_BRIDGE);
     expect(sendButton).toBeInTheDocument();
-    expect(sendButton).toBeDisabled();
+    // Send button is no longer disabled - non-EVM filtering happens upstream in token/network lists
+    expect(sendButton).not.toBeDisabled();
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply ui/components/app/wallet-overview/non-evm-overview.test.tsx:471]: Non-EVM NFTs (like Solana NFTs) are not currently supported, so the bug is theoretical - it can't manifest in practice today. will add the fix as defensive measure [f598a17](https://github.com/MetaMask/metamask-extension/pull/38914/commits/f598a17bc2e6b9999aba9d9f3e2f832f6335da43)

File: ui/pages/confirmations/hooks/send/useSendAssets.ts [hunk 4]
```diff
@@ -11,12 +15,24 @@ type SendAssets = {
...
+    // When BFT is OFF, filter out non-EVM tokens
+    if (!useExternalServices) {
+      const filteredTokens = tokens.filter((token) => {
+        // chainId is Hex for EVM chains or CaipChainId for non-EVM chains
+        return isEvmChainId(token.chainId as CaipChainId | Hex);
+      });
+      return {
+        tokens: filteredTokens,
+        nfts,
+      };
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply ui/pages/confirmations/hooks/send/useSendAssets.ts:35]: [f598a17](https://github.com/MetaMask/metamask-extension/pull/38914/commits/f598a17bc2e6b9999aba9d9f3e2f832f6335da43)

**Review by OGPoyraz — DISMISSED** [review]
Tested locally - confirmation changes LGTM.

When BFT is off - nonEVM tokens are filtered as well as the nonEVM asset page send button is also disabled as expected.

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by juanmigdr — APPROVED** [review]

**Review by NidhiKJha — COMMENTED** [review]
LGTM! Followed the manual testing steps and it looks good.

Before I approve quick question< 
even if BF is off and I try to connect with a dapp. The dapp can add and access all networks (evm and non evem) right?

**Review by NidhiKJha — APPROVED** [review]
