### PR TITLE
Fix spinner issue on seed word request

### LINKED ISSUE #1033: Spinner doesn't disappear when wrong password submitted on seed reveal
As said in the title: expected behavior is for loading spinner to disappear and an error rendered.

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Fixes #1033 by adding an action to hide the spinner within an error conditional.

### CODE REVIEW

File: ui/app/actions.js [hunk 1]
```diff
@@ -269,7 +269,10 @@ function requestRevealSeed (password) {
...
     log.debug(`background.submitPassword`)
     background.submitPassword(password, (err) => {
-      if (err) return dispatch(actions.displayWarning(err.message))
+      if (err) {
+        dispatch(actions.hideLoadingIndication())
+        return dispatch(actions.displayWarning(err.message))
+      }
       log.debug(`background.placeSeedWords`)
       background.placeSeedWords((err) => {
         if (err) return dispatch(actions.displayWarning(err.message))
```
Comment (flyswatter) [inline ui/app/actions.js]: Could this line cause the same sort of bug?

**Review by danfinlay — APPROVED** [review]
LGTM, caught another possible instance of the same bug.

File: ui/app/actions.js (hunk 1 above)
Comment (Zanibas) [inline ui/app/actions.js]: Should we just have default behavior for when we display a warning to hide the loading indicator?

Comment (Zanibas) [inline ui/app/actions.js]: I don't see any cases where this would be a problem--we always want to return user control as soon as we have the need to display a warning...right?

Comment (flyswatter) [inline ui/app/actions.js]: I agree, that would help mitigate this. Could add it to the showWarning reducer.

**Comment by Zanibas** [comment]
Check dis out

File: ui/app/actions.js [hunk 2]
```diff
@@ -231,7 +231,7 @@ function createNewVaultAndRestore (password, seed) {
     dispatch(actions.showLoadingIndication())
     log.debug(`background.createNewVaultAndRestore`)
     background.createNewVaultAndRestore(password, seed, (err) => {
-      dispatch(actions.hideLoadingIndication())
+      // dispatch(actions.hideLoadingIndication())
```
Comment (flyswatter) [inline ui/app/actions.js]: Do we really want to comment this out?  What if there is not an error?  Does `showAccountsPage` also hide loading indication?

File: ui/app/actions.js [hunk 3]
```diff
@@ -215,7 +215,7 @@ function confirmSeedWords () {
     dispatch(actions.showLoadingIndication())
     log.debug(`background.clearSeedWordCache`)
     background.clearSeedWordCache((err, account) => {
-      dispatch(actions.hideLoadingIndication())
+      // dispatch(actions.hideLoadingIndication())
```
Comment (flyswatter) [inline ui/app/actions.js]: Do we really want to comment this out?  What if there is not an error?  Does `showAccountDetail` also hide loading indication?

**Review by danfinlay — CHANGES_REQUESTED** [review]
I think that last commit may have reintroduced bugs by not hiding loading indication on success.  Please clarify?

File: ui/app/actions.js (hunk 2 above)
Comment (Zanibas) [inline ui/app/actions.js]: Whoops I just missed this one.

File: ui/app/actions.js [hunk 4]
```diff
@@ -296,7 +297,6 @@ function importNewAccount (strategy, args) {
     dispatch(actions.showLoadingIndication('This may take a while, be patient.'))
     log.debug(`background.importAccountWithStrategy`)
     background.importAccountWithStrategy(strategy, args, (err) => {
-      dispatch(actions.hideLoadingIndication())
```
Comment (flyswatter) [inline ui/app/actions.js]: Here again, probably removed it but need it for success case.

**Review by danfinlay — CHANGES_REQUESTED** [review]
One more possible bug spot.

**Review by danfinlay — APPROVED** [review]
Yay!
