### PR TITLE
Using  NetworkAccountBalanceHeader component  on SIWE screen

### LINKED ISSUE #17812: New header is not shown on SIWE screen
## Background 
A new signature screen has been introduced for SIWE in https://github.com/MetaMask/metamask-extension/issues/17461, but it's missing the new header that we included in all signature requests here https://github.com/MetaMask/metamask-extension/issues/15705 . We should replace the PermissionsConnectHeader usage on this custom signature screen with the new header

## Steps to Reproduce
1. Go to https://metamask.github.io/test-dapp/
2. Under Sign In With Ethereum, click on Sign In With Ethereum

## Screenshot
Screenshot 2023-02-17 at 17 56 08

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
## Explanation
NetworkAccountBalanceHeader is now being shown on the SIWE screen.

Fixes https://github.com/MetaMask/metamask-extension/issues/17812

### Before

Screenshot 2023-05-31 at 4 32 40 PM

### After

Screenshot 2023-05-31 at 4 30 12 PM

## Manual Testing Steps

- Go to https://metamask.github.io/test-dapp/
- Under Sign In With Ethereum, click on Sign In With Ethereum

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/hooks/useSignatureRequestHeaderData.js [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+      accountName={fromAccount.name}
+      accountBalance={balanceInBaseAsset}
+      tokenName={
+        conversionRate ? currentCurrency?.toUpperCase() : nativeCurrency
+      }
+      accountAddress={fromAccount.address}
+      chainId={currentChainId}
+    />
+  );
+};
```
Comment (jpuri) [inline ui/hooks/useSignatureRequestHeaderData.js:79]: @NiranjanaBinoy : for returning `JSX` functional component is preferable over hook.

File: ui/components/app/signature-requests-common-header/signature-requests-common-header.js [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+  getAccountByAddress,
+  getNetworkNameFromProviderType,
+} from '../../../helpers/utils/util';
+import { EtherDenomination } from '../../../../shared/constants/common';
+import { Numeric } from '../../../../shared/modules/Numeric';
+import { getValueFromWeiHex } from '../../../../shared/modules/conversion.utils';
+
+import NetworkAccountBalanceHeader from '../network-account-balance-header';
+
+const SignatureRequestsCommonHeader = ({ txData }) => {
```
Comment (NiranjanaBinoy) [inline ui/components/app/signature-requests-common-header/signature-requests-common-header.js:28]: In this PR, I have updated <SignatureRequestOriginal/> and <SignatureRequestSIWE/> to use this new component. This can also be used in <SignatureRequest/>, which I will be updating in https://github.com/MetaMask/metamask-extension/pull/19104  to reduce redundant work as I am refactoring the <SignatureRequest/> component to a functional component in that PR.

File: ui/components/app/signature-request-original/signature-request-original.component.js [hunk 3]
```diff
@@ -64,13 +58,13 @@ export default class SignatureRequestOriginal extends Component {
     subjectMetadata: PropTypes.object,
     hardwareWalletRequiresConnection: PropTypes.bool,
     isLedgerWallet: PropTypes.bool,
-    nativeCurrency: PropTypes.string.isRequired,
-    currentCurrency: PropTypes.string.isRequired,
-    conversionRate: PropTypes.number,
+    // nativeCurrency: PropTypes.string.isRequired,
```
Comment (segun) [inline ui/components/app/signature-request-original/signature-request-original.component.js:61]: We can remove these if they're not being used.

File: ui/components/app/signature-request-original/signature-request-original.component.js [hunk 4]
```diff
@@ -64,13 +58,13 @@ export default class SignatureRequestOriginal extends Component {
...
+    // currentCurrency: PropTypes.string.isRequired,
+    // conversionRate: PropTypes.number,
     messagesCount: PropTypes.number,
     showRejectTransactionsConfirmationModal: PropTypes.func.isRequired,
     cancelAll: PropTypes.func.isRequired,
-    providerConfig: PropTypes.object,
+    // providerConfig: PropTypes.object,
```
Comment (jpuri) [inline ui/components/app/signature-request-original/signature-request-original.component.js:67]: Will be useful to remove above commented props.

File: ui/components/app/signature-requests-common-header/index.js [hunk 5]
```diff
@@ -0,0 +1 @@
+export { default } from './signature-requests-common-header';
```
Comment (jpuri) [inline ui/components/app/signature-requests-common-header/index.js:1]: This can be named `SignatureRequestHeader`, word `common` is not needed I think.

File: ui/components/app/signature-requests-common-header/signature-requests-common-header.js [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+import { formatCurrency } from '../../../helpers/utils/confirm-tx.util';
+import {
+  getAccountByAddress,
+  getNetworkNameFromProviderType,
+} from '../../../helpers/utils/util';
+import { EtherDenomination } from '../../../../shared/constants/common';
+import { Numeric } from '../../../../shared/modules/Numeric';
+import { getValueFromWeiHex } from '../../../../shared/modules/conversion.utils';
+
+import NetworkAccountBalanceHeader from '../network-account-balance-header';
```
Comment (jpuri) [inline ui/components/app/signature-requests-common-header/signature-requests-common-header.js:26]: Imports can be organised better.

**Review by jpuri — DISMISSED** [review]
Some small feedbacks, looks good otherwise 👍

**Review by jpuri — APPROVED** [review]

**Review by segun — APPROVED** [review]
