### PR TITLE
fix(snaps): Prevent address input crash on invalid CAIP account ID

### LINKED ISSUE #3318: Address Input component is crashing extension
When pasting something into AddressInput component that is not valid CAIP address, extension is crashing.

Image

Steps to reproduce:
- Use custom Snap with an Address Input component or Send Flow Snap.
- Try pasting something that is not valid CAIP address (e.g. `https://metamask.github.io/snaps/test-snaps/latest/`)
- Observe and investigate the outcome

Affects:
- Extension stability
- DAPP functionality (extension needs to be reopened and page refreshed)

Code snippet for Snap UI JSX:
```xml
<Field label="To account" error="This field is required">
  <AddressInput
    name="to"
    chainId="eip155:0"
    placeholder="Enter receiving address"
    displayAvatar={true}
  />
</Field>
```

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

This PR fixes an issue where we tried to parse a CAIP Account ID from an invalid value.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31934?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/snaps/issues/3318

## **Manual testing steps**

1. Go to test snaps
2. Use the send form example snap
3. paste a URL

### **Before**

https://github.com/user-attachments/assets/4b00780f-f7d6-462c-912f-49ccaafa566f

### **After**

https://github.com/user-attachments/assets/34583809-ac13-495d-87cb-6b0a4e1ba562

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx [hunk 1]
```diff
@@ -37,6 +38,80 @@ import {
...
+        name={IconName.Close}
+        color={IconColor.infoDefault}
+        style={{
+          cursor: 'pointer',
+          flexShrink: 0,
+        }}
+      />
+    </Box>
+  </Box>
+);
```
Comment (GuillaumeRx) [inline ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:113]: Moved this outside of the component for readability

File: ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx [hunk 2]
```diff
@@ -183,7 +232,7 @@ export const SnapUIAddressInput: FunctionComponent<
         borderRadius: BorderRadius.LG,
       }}
       startAccessory={
-        displayAvatar && value ? (
+        displayAvatar && value && isCaipAccountId(`${chainId}:${value}`) ? (
```
Comment (GuillaumeRx) [inline ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:235]: Same here

**Review by david0xd — APPROVED** [review]

**Review by hmalik88 — APPROVED** [review]
