### PR TITLE
Verify identities state after restoring new accounts

### LINKED ISSUE #3566: Clear addresses and wallet nickname from walletNicknames from state.
Currently we do not clear walletNickames from local storage. 
Reproduction steps: 
1. MetaMask vault loaded.
2. Logout and restore a different seed phrase.
3. View localStorage 
4. See that the original seed phrase is still in walletNicknames.

### PR DESCRIPTION
**Pull request by bitpshr**
This PR adds tests to verify that identity-related information (like an account label) is cleared from state when a new account is restored using a different seed phrase. Note that these tests will need to be updated after #4034 is merged, since the public API methods for setting account labels will now live in the `PreferenceController`.

Resolves #3566

### CODE REVIEW

File: test/unit/metamask-controller-test.js [hunk 1]
```diff
@@ -87,17 +93,28 @@ describe('MetaMaskController', function () {
...
-      await metamaskController.createNewVaultAndRestore(password, rightSeed)
+      await metamaskController.createNewVaultAndRestore(password, TEST_SEED.slice(0, -1)).catch((e) => null)
+      await metamaskController.createNewVaultAndRestore(password, TEST_SEED)
 
       assert(metamaskController.keyringController.createNewVaultAndRestore.calledTwice)
     })
+
+    it('should clear previous identities after vault restoration', async () => {
+      await metamaskController.createNewVaultAndRestore('foobar1337', TEST_SEED)
+      assert.deepEqual(metamaskController.keyringController.memStore.getState().identities, {
```
Comment (whymarrh) [inline test/unit/metamask-controller-test.js]: We should be able to get away with using `metamaskController.getState().identities` here to abstract from where this state is kept (similarly for the additions below)

Comment (whymarrh) [reply test/unit/metamask-controller-test.js]: This would allow us to not have to worry about changes like #4034

**Comment by bitpshr** [comment]
Thanks @whymarrh. @danfinlay, we should be able to merge this now regardless of the status of #4034.

**Review by whymarrh — APPROVED** [review]
