### PR TITLE
Replace toNumber calls on BigNumbers with toString

### LINKED ISSUE #9356: Bignumber error on develop when sending a token
This error is on develop but not on production. It was introduced with https://github.com/MetaMask/metamask-extension/commit/3aaa41ef44cd2d751cd41278f0ba0ece7dca79db and has to do with the attempt to convert the BN's from the ethers util to numbers.

To reproduce:
- get ropsten eth
- go to https://vittominacori.github.io/erc20-generator/ and create a token with total supply of 100,000,000 and 18 decimals, and an initial amount/supply of 1,000,000
- try to send 1000 of these tokens to another address

You will see something like:
token-failure

Screenshot from 2020-09-04 19-47-11

Screenshot from 2020-09-04 19-46-36

Here is a quick, naive patch that solves this particular instance of this bug:

Screenshot from 2020-09-04 19-13-42

### PR DESCRIPTION
**Pull request by rekmarks**
Fixes #9356 

Replaces calls of the form `someBigNumber.toNumber()` with `someBigNumber.toString()`. Calling `toNumber()` on a `BigNumber` is, of course, unsafe in the general case since the `BigNumber` can be larger than `MAX_SAFE_INTEGER`. `ethers` [throws an error in this case](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--BigNumber--methods--conversion), which is why #9356 is occurring on `develop` following #9290.

All `BigNumber` implementations we use (_edit:_ at least in this PR) support a `toString()` method where the default representation is decimal. All cases where `toNumber()` was replaced could function equally well with `toString()`, with minimal or no modifications.

We still use `someBigNumber.toNumber()` in [gas.ducks.js](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/ducks/gas/gas.duck.js/). That's probably safe, because the gas price is denominated in gwei, and if the gas price ever exceeds `MAX_SAFE_INTEGER` in gwei on any platform we're on, we have bigger problems.

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]

File: ui/app/pages/confirm-token-transaction-base/confirm-token-transaction-base.component.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ export default class ConfirmTokenTransactionBase extends Component {
   renderSubtitleComponent () {
     const { contractExchangeRate, tokenAmount } = this.props
 
-    const decimalEthValue = (tokenAmount * contractExchangeRate) || 0
+    const decimalEthValue = (tokenAmount * contractExchangeRate) || '0'
```
Comment (Gudahtt) [inline ui/app/pages/confirm-token-transaction-base/confirm-token-transaction-base.component.js:49]: This seems wrong :thinking: We're multuiplying a string here by `contractExchangeRate`

File: ui/app/pages/confirm-token-transaction-base/confirm-token-transaction-base.container.js [hunk 2]
```diff
@@ -44,7 +44,7 @@ const mapStateToProps = (state, ownProps) => {
   const tokenData = getTokenData(data)
   const tokenValue = getTokenValueParam(tokenData)
   const toAddress = getTokenAddressParam(tokenData)
-  const tokenAmount = tokenData && calcTokenAmount(tokenValue, decimals).toNumber()
+  const tokenAmount = tokenData && calcTokenAmount(tokenValue, decimals).toString()
```
Comment (Gudahtt) [inline ui/app/pages/confirm-token-transaction-base/confirm-token-transaction-base.container.js:47]: We should be explicitly declaring a base here, to prevent exponentiation. Apparently `bignumber.js` will use base 10 by default  with exponential notation for large and small values, but will use base 10 without exponential notation if it's specified explicitly.

The same goes for the other places where `.toString` was called on the return value of `calcTokenAmount` in this PR
