### PR TITLE
fix: fix missing notification services controller selectors

### LINKED ISSUE #28047: [Sentry] TypeError: Cannot read properties of undefined (reading 'length')
Sentry Issue: [METAMASK-XCED](https://metamask.sentry.io/issues/6010243560/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'length')
  at n.getStartupTraceTags (ui/helpers/utils/tags.ts:26:54)
  at store (ui/index.js:186:16)
  at n.default (ui/index.js:76:23)
  at store (app/scripts/ui.js:313:3)
  at updateUiStreams (app/scripts/ui.js:241:11)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

Our notification selectors did not respect that they might be used before migrations & controller initialisation has filled state.
For example in the attached Sentry Issue: [METAMASK-XCED](https://metamask.sentry.io/issues/6010243560/?referrer=github_integration), this user was starting the app from `12.10.3` and did not have any `NotificationServicesController` state.

Now we ensure that our selectors correctly fallback to the default controller state it not initialised.

DEV NOTE - I'm unsure how this user managed to have missing notification state. 12.10.3 should have had notifications. And when the controller is initialised it has a default state.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33708?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28047

## **Manual testing steps**

I have not been able to test this, as I'm unsure how Sentry Issue: [METAMASK-XCED](https://metamask.sentry.io/issues/6010243560/?referrer=github_integration) managed to have this missing controller state (notifications were released, and should have had some default state).

However unit tests provide some safety here.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/metamask-notifications/metamask-notifications.ts [hunk 1]
```diff
@@ -20,7 +25,7 @@ const getMetamask = (state: AppState) => state.metamask;
  */
 export const getMetamaskNotifications = createSelector(
   [getMetamask],
-  (metamask) => metamask.metamaskNotificationsList,
+  (metamask): Notification[] => metamask.metamaskNotificationsList,
```
Comment (Prithpal-Sooriya) [inline ui/selectors/metamask-notifications/metamask-notifications.ts:28]: We were using JSDoc, but no explicit return types. Added some return types for some additional safety.

File: ui/selectors/metamask-notifications/metamask-notifications.ts [hunk 2]
```diff
@@ -1,16 +1,21 @@
...
 type AppState = {
-  metamask: NotificationServicesController.NotificationServicesControllerState;
+  metamask: Partial<NotificationServicesControllerState>;
 };
 
-const getMetamask = (state: AppState) => state.metamask;
+const getMetamask = (state: AppState) => ({
+  ...defaultState,
+  ...state.metamask,
+});
```
Comment (Prithpal-Sooriya) [inline ui/selectors/metamask-notifications/metamask-notifications.ts:18]: If selectors are called before engine is initialised, we can gracefully fill in properties with the controllers default state.

**Review by mathieuartu — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

File: ui/selectors/metamask-notifications/metamask-notifications.ts (hunk 2 above)
Comment (Gudahtt) [reply ui/selectors/metamask-notifications/metamask-notifications.ts:18]: This is impossible though isn't it? The UI doesn't even start to render until after engines are initialized
