### PR TITLE
Use verifyPassword instead of submitPassword when exporting priv key

### LINKED ISSUE #9230: Cannot read property 'type' of undefined
**Describe the bug**
Trying to reveal private key and encountered this error when entering my password. It keeps crashing now and wont stop.
I was trying to port some keys over to firefox if that helps.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Install MM in firefox
2. Paste in a previous seed phrase
3. Success
4. Go to import a specific key pair
5. Go to chrome
6. Try to reveal a private key
7. Crash
8. Try to access options for a an address - crash - restart chrome and try again - still crash

**Expected behavior**
For this not to happen.

**Screenshots**
N/A

**Browser details (please complete the following information):**
 - OS: Lastest OSX - Latest Chrome
 - MetaMask Version Latest

**Additional context (Error Messages, etc.)**
I was typing very fast - copy pasted my password twice I think. Overflow bug? Race condition? Etc

### LINKED ISSUE #9287: Accounts not listed when a wrong password is entered for private key
**Describe the bug**
Accounts not listed when a wrong password is entered for `Export Private Key`

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

- Clean install MM extension
- Go to Menu and click on `Account details`
- Click on `Export Private Key`
- Enter incorrect password, shows incorrect password message
- Close and click on profile menu, no accounts listed
- Click account menu, throws error page
- Reload page brings back account details 
- Click account menu, throws error page
- Lock account and log back in
- Click on account menu, no error page is shown

**Expected behavior**
Should show created accounts

**Screenshots**
https://youtu.be/iYdvkf7GyTo

**Browser details (please complete the following information):**
 - OS: OSX/Windows/Linux
 - Hardware Wallet: Not verified
 - Browser: Brave Browser
 - MetaMask Version: 8.0.8

**Additional context (Error Messages, etc.)**
Related issues: 
https://github.com/MetaMask/metamask-extension/issues/8626
https://github.com/brave/brave-browser/issues/10957

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #9287
Fixes #9230
Which was when submitPassword is called will fully clear the keyring state

https://github.com/MetaMask/KeyringController/blob/master/index.js#L155

Also, pass hideWarning action prop so it will clear the appState.warning if a correct password is never provided on componentWillUnmount

### CODE REVIEW

File: ui/app/store/actions.js [hunk 1]
```diff
@@ -1709,7 +1709,7 @@ export function exportAccount (password, address) {
 
     log.debug(`background.submitPassword`)
```
Comment (Gudahtt) [inline ui/app/store/actions.js:1710]: Nit: This message is outdated

```suggestion
    log.debug(`background.verifyPassword`)
```

File: ui/app/store/actions.js [hunk 2]
```diff
@@ -1709,7 +1709,7 @@ export function exportAccount (password, address) {
...
     return new Promise((resolve, reject) => {
-      background.submitPassword(password, function (err) {
+      background.verifyPassword(password, function (err) {
         if (err) {
           log.error('Error in submitting password.')
```
Comment (Gudahtt) [inline ui/app/store/actions.js:1714]: Nit: this message is outdated

```suggestion
          log.error('Error in verifying password.')
```

**Review by Gudahtt — COMMENTED** [review]
Looks good! Just a couple of debug message updates needed

**Review by Gudahtt — APPROVED** [review]
LGTM!
