### PR TITLE
fix: snap address input component states

### LINKED ISSUE #3320: Address Input disabled state is not applied when address value is preset
When `AddressInput` component has preset value for an address and is in disabled state, then the disabled state is not properly applied.

https://github.com/user-attachments/assets/284ca1c0-70e5-45fa-8bef-d6e87639b53f

Snap UI JSX for testing:
```xml
<Field label="To account" error="This field is required">
  <AddressInput
    name="to"
    chainId="eip155:0"
    placeholder="Enter receiving address"
    disabled={true}
    value="0xaa3881C0B6CaeB0fdCBA5284cE4d25E0EAC2551B"
  />
</Field>
```

### PR DESCRIPTION
**Pull request by hmalik88**
## **Description**

Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:
1. What is the reason for the change? Matched account info did not have a disabled state and it was also being rendered even in the event that a snap was passing an `error` prop.
2. What is the improvement/solution? Add a disabled state and logic to prevent rendering of matched account info in the presence of an error.

## **Related issues**

Fixes: https://github.com/MetaMask/snaps/issues/3320

## **Manual testing steps**

1. Build from this branch.
2. Write a snap that triggers a dialog with the following code:

**Error & Disabled**

```ts
<Field label="To account" error="This field is required">
  <AddressInput
    name="to"
    chainId="eip155:0"
    placeholder="Enter receiving address"
    disabled={true}
    value="0xBc641D258aA0e90F70AaDbcC4dE2D58d88029713" // this should be one of your own addresses
  />
</Field>
```
**Disabled**

```ts
<Field label="To account">
  <AddressInput
    name="to"
    chainId="eip155:0"
    placeholder="Enter receiving address"
    disabled={true}
    value="0xBc641D258aA0e90F70AaDbcC4dE2D58d88029713" // this should be one of your own addresses
  />
</Field>
```
3. Observe the results.

### **Before**

https://github.com/user-attachments/assets/668d7f4b-e2ae-4505-a43e-6df54a6c7cbb

### **After**

https://github.com/user-attachments/assets/45ca34ab-db5d-4bac-aa45-48a7ee7594b6

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx [hunk 1]
```diff
@@ -196,11 +211,13 @@ export const SnapUIAddressInput: FunctionComponent<
...
-    setValue('');
-    handleInputChange(name, '', form);
+    if (!disabled) {
+      setValue('');
+      handleInputChange(name, '', form);
+    }
   };
 
-  if (displayName) {
+  if (displayName && !error) {
```
Comment (Mrtenz) [inline ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:220]: Why do we not want to show the matched name if there's an error?

Comment (hmalik88) [reply ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:220]: When something is matched imo it represents a successful operation, allowing the matched component to render when there's an error present feels counterintuitive.

Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:220]: My issue with this is that we could match an address before the snap sends the error meaning that for a short time we will display the matched address and then remove it due to the error :thinking:

Comment (Mrtenz) [reply ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:220]: I think both should be shown regardless tbh.

Comment (hmalik88) [reply ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:220]: Hmm yeah it's almost impossible to time that, maybe it's easier to just display regardless.

File: ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx [hunk 2]
```diff
@@ -71,6 +74,8 @@ const MatchedAccountInfo: FunctionComponent<MatchedAccountInfoProps> = ({
       gap={2}
       style={{
         height: '48px',
+        opacity: disabled ? 0.5 : 1,
```
[the remark this answers is not in the document]
Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:81]: I don't think we reduce the opacity of the label in the other components :thinking:

**Review by GuillaumeRx — APPROVED** [review]

File: ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-address-input/snap-ui-address-input.tsx:81]: Sorry I got confused by the collapsed code, I though this was applied to the label

**Review by david0xd — APPROVED** [review]
