### PR TITLE
fix: cp-12.17.0 fix clean up fiat conversion logic

### LINKED ISSUE #31920: [Bug]: Fiat conversion not displayed
### Describe the bug

Fiat conversion is not displayed on the assets list and in the aggregated balance

### Expected behavior

USD conversion should be displayed 

### Screenshots/Recordings

https://www.loom.com/share/f1d5ab64e7d047e2b0c49dd863efe53d

### Steps to reproduce

Check homescreen

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.17.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
fiat conversion should be displayed for new created wallet, the native balance should show 0$ as well

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31938?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/31920

## **Manual testing steps**

1. Create new Metamask wallet ( import SRP )
2. Go to assets list
3. fiat conversion should be displayed for erc20
4. fiat conversion should be displayed for 0 balance native balance

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controller-init/assets/token-rates-controller-init.ts [hunk 1]
```diff
@@ -16,12 +16,15 @@ import { TokenRatesControllerMessenger } from '../messengers/assets';
...
+> = (request) => {
+  const { controllerMessenger, getController, persistedState } = request;
+  const preferencesController = () => getController('PreferencesController');
+
   const controller = new TokenRatesController({
     messenger: controllerMessenger,
     state: persistedState.TokenRatesController,
     tokenPricesService: new CodefiTokenPricesServiceV2(),
-    disabled: !persistedState.PreferencesController?.useCurrencyRateCheck,
+    disabled: !preferencesController().state?.useCurrencyRateCheck,
```
Comment (Prithpal-Sooriya) [inline app/scripts/controller-init/assets/token-rates-controller-init.ts:27]: Interesting. Could you expand on why we are reading for controller.state instead of persistedState?

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]

File: app/scripts/controller-init/assets/token-rates-controller-init.ts (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/scripts/controller-init/assets/token-rates-controller-init.ts:27]: Yeah interesting.

The preferenceController is not using the init pattern yet, but has been passed as an existing controller.
https://github.com/MetaMask/metamask-extension/blob/4691f2f080220b266cace8c505e0b5a9ef2ad8ad/app/scripts/metamask-controller.js#L1838-L1878

I wonder if the `persistedState` does not contain the preferencesController state?
