### PR TITLE
Fix unknown processing time not showing in warning color

### LINKED ISSUE #19305: [Bug]: `Unknown processing time` is displayed in green instead of warning color
### Describe the bug

**Problem**: whenever we are sending a transaction with an `Unknown processing time` we see the text displayed green instead of in the Warning color.

image

### Steps to reproduce

1. Go to the test dapp
2. Connect MM
3. Click Send EIP1159
4. See `Unknown processing time` in green

### Error messages or log output

_No response_

### Version

10.30.4 but it's an old issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by segun**
## Explanation
Problem: whenever we are sending a transaction with an Unknown processing time we see the text displayed green instead of in the Warning color.

Fixes: #19305 

### After

Screenshot 2023-06-08 at 22 15 36

## Manual Testing Steps

1. Start a transaction
2. Click to edit the gas fees
3. Click on advanced
4. Set Priority Fee to 0
5. Click Save
6. Unknown processing time should be shown in warning colour.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/app/gas-timing/gas-timing.component.js [hunk 1]
```diff
@@ -163,6 +164,9 @@ export default function GasTiming({
     }
   }
 
+  console.log('attitude', attitude);
+  console.log('estimateUsed', estimateUsed);
```
Comment (brad-decker) [inline ui/components/app/gas-timing/gas-timing.component.js:168]: Console.logs need removed

**Review by brad-decker — CHANGES_REQUESTED** [review]

**Review by jpuri — APPROVED** [review]
LGTM 👍

**Comment by jpuri** [comment]
Will be nice to have test coverage if possible.

**Review by danjm — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]
