### PR TITLE
fix: cp-12.18.0 No conversion rate fallback text should not wrap

### LINKED ISSUE #32991: [Bug]: Long Token Name/Price Unavailable creates Overflow out of UI Element
### Describe the bug

In the account when a token has a long name and the price of the token is "Conversion Rate Not Available" the text flows outside of the UI Element and is cut off. 

### Expected behavior

All text should fit inside its Element 

### Screenshots/Recordings

Image

### Steps to reproduce

1. View assets with a long name and no price

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32996?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32991

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

Screenshot 2025-05-15 at 4 18 47 PM

### **After**

Screenshot 2025-05-15 at 4 16 37 PM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/token-cell/cells/token-cell-secondary-display.tsx [hunk 1]
```diff
@@ -80,6 +80,7 @@ export const TokenCellSecondaryDisplay = React.memo(
         ellipsis={token.isStakeable}
         isHidden={privacyMode}
         length={SensitiveTextLength.Medium}
+        style={{ whiteSpace: 'nowrap', paddingInlineStart: 8 }}
```
Comment (darkwing) [inline ui/components/app/assets/token-cell/cells/token-cell-secondary-display.tsx:83]: I think we need to `useMemo` this because the new object in the past has triggered re-renders

**Review by darkwing — APPROVED** [review]

**Review by hjetpoluru — APPROVED** [review]
