### PR TITLE
fix: enable multiple networks when added via dapp cp-13.0.0

### LINKED ISSUE #34454: [Bug]: Adding a new network via dapp deselects all selected networks in the enabled networks
### Describe the bug

When adding a new network via a dapp, the network gets added and selected but all other selected networks get deselected. 

### Expected behavior

The new network must be added an enabled but other networks should not get deselected

### Screenshots/Recordings

https://github.com/user-attachments/assets/1f098b97-129d-460e-8c6d-637b37e4c595

### Steps to reproduce

1. Login to metamask
2. Add a few networks to the enabled networks list
3. Go to a dapp like chainlist.org
4. Add a network from the list to metamask 
5. Observe the 

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
When adding a new network via a dapp, the network gets added and selected and all pre selected networks should stay selected.

## **Related issues**

Fixes: #34454 

## **Manual testing steps**

1. Run extension
2. conect to dapp, 
3. check enabled networks in MM
4. trying adding new network via dapp
5. New network should be added and selected in network manager along with previously selected network

### **Before**

NA
### **After**

https://github.com/user-attachments/assets/1db122e3-511b-4df8-b6ee-aa4830b90814

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js [hunk 1]
```diff
@@ -252,10 +255,33 @@ export async function switchChain(
...
 
     if (isPrefixedFormattedHexString(chainId)) {
-      setEnabledNetworks(chainId, KnownCaipNamespace.Eip155);
+      const existingEnabledNetworks = getEnabledNetworks(
+        KnownCaipNamespace.Eip155,
+      );
+      const existingChainIds = Object.keys(existingEnabledNetworks);
+
+      if (!existingChainIds.includes(chainId)) {
+        const isFeaturedNetwork = FEATURED_NETWORK_CHAIN_IDS.includes(chainId);
```
Comment (vinnyhoward) [inline app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js:264]: Not a big deal or a blocker, but I think we should consider using a `Set` instead of an array for `FEATURED_NETWORK_CHAIN_IDS`. Since all chain IDs are unique, `Set` would provide O(1) lookup time compared to O(n)

Current:
```javascript
export const FEATURED_NETWORK_CHAIN_IDS = [
  CHAIN_IDS.MAINNET,
  ...FEATURED_RPCS.map((rpc) => rpc.chainId),
];
```

Suggested:
```javascript
export const FEATURED_NETWORK_CHAIN_IDS = new Set([
  CHAIN_IDS.MAINNET,
  ...FEATURED_RPCS.map((rpc) => rpc.chainId),
]);
```

This would change usage from `FEATURED_NETWORK_CHAIN_IDS.includes(chainId)` to `FEATURED_NETWORK_CHAIN_IDS.has(chainId)`, which isn't that big of a change and is much faster. I've started doing this in mobile recently

**Review by vinnyhoward — DISMISSED** [review]
LGTM and left a comment

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js:264]: Totally agree, we do this `includes` lookup in a few places. Maybe we can create a fast follow PR on this?

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
