### PR TITLE
Consider HW Wallets for signTypedMessage

### LINKED ISSUE #5319: Error when signing messages using a Ledger-connected wallet
**Describe the bug**

When you use personal_sign, eth_signTypedData, or eth_signTypedData_v3 with a Ledger Nano S wallet connected to MetaMask, this error shows up in the console:

```
inpage.js:1 MetaMask - RPC Error: Error: MetaMask Message Signature: TypeError: a._getWalletForAccount is not a function
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:124951)
    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:607322)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608886
    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608956)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127814)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127537)
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:154138)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592069)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1591857)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592248)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413929)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414025 
{code: -32603, message: "Error: MetaMask Message Signature: TypeError: a._g…beogaeaoehlefnkodbefgpgknn/background.js:1:414025"}
code: -32603
message: "Error: MetaMask Message Signature: TypeError: a._getWalletForAccount is not a function↵    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:124951)↵    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:607322)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608886↵    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608956)↵    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127814)↵    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127537)↵    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:154138)↵    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592069)↵    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1591857)↵    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592248)↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413929)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414025"
__proto__: Object
```

**To Reproduce**
1. Go to [https://danfinlay.github.io/js-eth-personal-sign-examples/](https://danfinlay.github.io/js-eth-personal-sign-examples/)
2. Connect your Ledger to MetaMask
2. Have the browser console open
3. Click on personal_sign and/or "sign typed data"
4. See errors

**Expected behavior**
It should behave the same way as it does with a non-Ledger MetaMask wallet.

**Browser details (please complete the following information):**
 - Kubuntu Linux
 - MetaMask Version 4.10.0
 - New UI

### PR DESCRIPTION
**Pull request by brunobar79**
That feature it's not currently supported on Ledger or Trezor but the current implementation of signedTypedData was reading private keys from the keyring, which is a private method and not supported on the HW wallet keyrings.

This PR handles both scenarios separately and at least now we will fail with the right error message:
- `Not supported in this device`

Once the hw wallets gets support, we should have to just update the keyring without need of touching the extension.

Fixes #5319 

BEFORE: 
screen shot 2018-11-20 at 12 48 04 pm

AFTER:
screen shot 2018-11-20 at 12 45 01 pm

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -1021,20 +1021,27 @@ module.exports = class MetamaskController extends EventEmitter {
...
-      switch (version) {
-        case 'V1':
-          signature = sigUtil.signTypedDataLegacy(privKey, { data: cleanMsgParams.data })
-          break
-        case 'V3':
-          signature = sigUtil.signTypedData(privKey, { data: JSON.parse(cleanMsgParams.data) })
-          break
+      // HW Wallet keyrings don't expose private keys so
+      // we need to handle it separately
+      if (HW_WALLETS_KEYRINGS.indexOf(keyring.type) === -1) {
```
Comment (whymarrh) [inline app/scripts/metamask-controller.js]: Can we use `Array#includes` here and switch the branches? That might read a little better.

Comment (whymarrh) [reply app/scripts/metamask-controller.js]: Or move this into its own constant e.g. `isHardwareWallet`

**Review by bitpshr — DISMISSED** [review]

**Comment by brunobar79** [comment]
@bitpshr  @whymarrh  Thanks for the review! Just addressed the comment, so you can take a look again whenever you have a chance.

**Review by bitpshr — APPROVED** [review]
