### PR TITLE
fix: fixed ENS Resolution for selected chain in contacts

### LINKED ISSUE #34994: [Bug]: ENS Resolution - ENS resolves to mainnet address despite selecting another network on the Contacts page
### Describe the bug

Whenever I am adding a new contact, no matter which network I select, if I enter an ENS domain, it always resolves to the corresponding address for mainnet.
This can lead to FLI.

### Expected behavior

If ENS is supported on that network, it should resolve to their corresponding address in that network.
IF ENS is not supported on that network, we should display a message saying ENS resolution is not supported there.

### Screenshots/Recordings

https://github.com/user-attachments/assets/fa9581f7-c937-4c8f-ba38-e7093e102703

### Steps to reproduce

1. Click Contacts
2. Select Mainnet
3. Add `seaona.eth` see address
4. Select Sepolia
5. Add `seaona.eth` see address is the same as 3, but it should be a different one

### Error messages or log output

```shell

```

### Detection stage

Prod

### Version

13.0.0

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR is to ensure if ENS is supported on that network, it should resolve to their corresponding address in that network

## **Changelog**

CHANGELOG entry:null

## **Related issues**

Fixes: #34994 

## **Manual testing steps**

1. Click Contacts
2. Select Mainnet
3. Add seaona.eth see address
4. Select Sepolia
5. Add seaona.eth see address is different

### **Before**

NA
### **After**

https://github.com/user-attachments/assets/15d851b1-7617-4208-9672-2ce73aa9ac93

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Re-resolves ENS/domain names on network change in Add Contact by tracking the entered domain and invoking `lookupDomainName` with the selected chain, with container wiring and minor fixes.
> 
> - **Contacts UI (`ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js`)**:
>   - Add re-resolution logic on network change:
>     - Track original domain via `enteredDomainName` and previous chain via `useRef`.
>     - On `selectedChainId` change, reset resolutions and call `lookupDomainName(domain, selectedChainId)`.
>   - Update domain resolution selection:
>     - On selecting a resolution, set `enteredDomainName` and clear existing resolutions.
>   - Reset flow: clear `enteredDomainName` on input reset.
>   - Network picker: normalize `onSelect` param to `chainId`.
>   - Props: add `lookupDomainName` to `PropTypes`.
> - **Container (`add-contact.container.js`)**:
>   - Wire `lookupDomainName(domainName, chainId)` from `ducks/domains` into component props.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit c44b0b4531ba5957648cce2646d7d75d392af7b9. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js [hunk 1]
```diff
@@ -242,7 +269,7 @@ const AddContact = ({
               isOpen
               onClose={() => setShowModal(false)}
               selectedChainId={selectedChainId}
-              onSelect={(chainname) => setSelectedChainId(chainname)}
+              onSelect={(chainId) => setSelectedChainId(chainId)}
```
Comment (n3ps) [inline ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js:272]: nit: can be simplified to 

```
onSelect={setSelectedChainId}
```

**Review by n3ps — APPROVED** [review]

**Review by ameliejyc — APPROVED** [review]
