### PR TITLE
fix: bump accounts controller and migration to fix undefined selectedAccount

### LINKED ISSUE #26377: Error: Account Id [UUID] not found
Sentry Issue: [METAMASK-X8QE](https://metamask.sentry.io/issues/4968221434/?referrer=github_integration)

```
Error: Account Id eb211bb2-16eb-4054-8595-17bd83bc8847 not found
  at new MetamaskController (app/scripts/metamask-controller.js:878:50)
  at setupController (app/scripts/background.js:516:16)
  at initialize (app/scripts/background.js:294:5)
```

This is still happening in v12.0.1.

Duplicate issue with interesting context: https://github.com/MetaMask/metamask-extension/issues/26623

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR bumps the `AccountsController` and introduces a new migration. The `updateAccounts` methods from the `AccountsController` now checks if the selectedAccount is undefined and recovers from this. The migration updates the selectedAccount values that are not defined. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26573?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26377

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by montelaidev** [comment]
@metamask-bot update-policies

File: ui/components/multichain/pages/connections/connections.tsx [hunk 1]
```diff
@@ -175,15 +178,19 @@ export const Connections = () => {
         mergedAccounts.reduce(
           (
             acc: number,
-            cur: { metadata: { lastSelected: number } },
+            cur: AccountType,
```
Comment (gantunesr) [inline ui/components/multichain/pages/connections/connections.tsx:181]: Any chance we can improve the name of these variables? Are they account and current?

File: ui/pages/remove-snap-account/snap-account-card.tsx [hunk 2]
```diff
@@ -24,7 +25,7 @@ export const SnapAccountCard = ({
   const account = mergedAccounts.find(
     (internalAccount: { address: string }) =>
       internalAccount.address === address,
-  );
+  ) as MergedInternalAccount;
```
Comment (gantunesr) [inline ui/pages/remove-snap-account/snap-account-card.tsx:28]: Can we just set the type on the variable declaration like this instead of casting it?

```ts
const account: MergedInternalAccount = mergedAccounts.find(...);
```

File: ui/selectors/selectors.types.ts [hunk 3]
```diff
@@ -6,6 +6,10 @@ export type InternalAccountWithBalance = InternalAccount & {
   balance: string;
 };
 
+export type InternalAccountWithBalanceLabel = InternalAccountWithBalance & {
+  label: string;
+};
```
Comment (gantunesr) [inline ui/selectors/selectors.types.ts:11]: Where is this being used?

**Review by gantunesr — COMMENTED** [review]
Looks like, left some minor comments

File: ui/pages/remove-snap-account/snap-account-card.tsx (hunk 2 above)
Comment (montelaidev) [reply ui/pages/remove-snap-account/snap-account-card.tsx:28]: The `find` method can result in an undefined account thats why i need to cast it, but since this is a remove snap account card, it is always defined.

File: ui/selectors/selectors.types.ts (hunk 3 above)
Comment (montelaidev) [reply ui/selectors/selectors.types.ts:11]: This can be removed.

**Review by gantunesr — APPROVED** [review]

File: ui/pages/remove-snap-account/snap-account-card.tsx [hunk 4]
```diff
@@ -24,7 +25,7 @@ export const SnapAccountCard = ({
   const account = mergedAccounts.find(
```
Comment (k-g-j) [inline ui/pages/remove-snap-account/snap-account-card.tsx:25]: Adding a note here as a TODO for us to remove the need of `mergeAccounts`

**Review by k-g-j — APPROVED** [review]
