### PR TITLE
fix:  cp-13.0.0 show solana connected state

### LINKED ISSUE #34239: [Bug]:[Remove GNS] Solana dapps displayed as not connected in MM
### Describe the bug

After connecting to a Solana dapp, the connection is not displayed as active in MetaMask

### Expected behavior

Connection to be displayed in MM, as it happens when connecting to dapps using EVM accounts

### Screenshots/Recordings

https://github.com/user-attachments/assets/066f022f-f542-4beb-9b10-9a76c7fd7656

Image

### Steps to reproduce

1. Connect to any Solana dapp
2. Click on the dap connection button in the upper right side of the header
3. Notice the message `Not connected`

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

12.22.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR ensures that when Solana account is connected, it should render connected state in the dapp view

## **Related issues**

Fixes: #34239 

## **Manual testing steps**

1. Connect extension to Solana Dapp, check the connected popover renders correct network icon and connected state
2. Connect extension to Uniswap, check the connected popover renders correct network icon and connected state

### **Before**

NA
### **After**

https://github.com/user-attachments/assets/5f7a47b4-7f06-4272-8af7-add101d8be66

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/connected-site-popover/connected-site-popover.tsx [hunk 1]
```diff
@@ -38,15 +45,33 @@ export const ConnectedSitePopover = ({
...
   // const activeDomain = useSelector(getAllDomains);
   // const networkClientId = activeDomain?.[activeTabOrigin];
-  const currentNetwork = useSelector(getCurrentNetwork);
+  const currentChainId = useSelector(getSelectedMultichainNetworkChainId);
+  const permittedChainIds = useSelector((state) =>
+    getAllPermittedChainsForSelectedTab(state, connectedOrigin),
+  );
+  const currentNetwork = useSelector(getSelectedMultichainNetworkConfiguration);
   const dispatch = useDispatch();
+  console.log(currentNetwork);
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/connected-site-popover/connected-site-popover.tsx]: remove log.

Comment (NidhiKJha) [reply ui/components/multichain/connected-site-popover/connected-site-popover.tsx]: Updated here https://github.com/MetaMask/metamask-extension/pull/34375/commits/e7787c464f77017f2ed64747ece2e932cf444147

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
