### PR TITLE
fix(metrics): add missing mm_pay metrics properties cp-13.29.0

### LINKED ISSUE #42233: [Bug]: Missing metrics for MM Pay (musd conversion and perps deposits)
**Describe the bug**

We’re missing “mm_pay_ sending_value_usd”, “mm_pay_receiving_value_usd”, “mm_pay_amount_input_type”, “mm_pay_quote_loaded”, “mm_pay_quote_requested”, “mm_pay_quotes_latency”, “mm_pay_time_to_complete_s” on extension.
We have these properties on mobile. (Can we check all mm_pay_ properties on mobile and replicate them on extension?)

Additionally, for transaction_type we should use “perps_deposit” instead of “perpsDeposit” and “musd_conversion” instead of “musdConversion” to comply with our data schema guideline and matches mobile.

**Steps to reproduce**

1. Do a musd conversion and perps deposit and check metrics fired

**Error messages or log output**

```shell

```

**Where was this bug found?**

Internal release testing

**Version**

13.29.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**

Extension was missing several `mm_pay_*` analytics properties that mobile already tracks, and was emitting `transaction_type` values in camelCase (`perpsDeposit`, `musdConversion`) instead of the schema-required snake_case (`perps_deposit`, `musd_conversion`).

### Changes:

- **Fixed `transaction_type` values** in `metrics-context.ts` to emit snake_case (`perps_deposit`, `musd_conversion`, `perps_withdraw`, `musd_claim`) matching mobile and the Segment schema
- **Aligned `mm_pay_use_case`** values to specific values (`perps_deposit`, `perps_withdraw`, `musd_conversion`, `musd_claim`) matching mobile's `USE_CASE_MAP`
- **Created background metrics builder** (`metamask-pay.ts`) to derive controller-level properties: `mm_pay_sending_value_usd`, `mm_pay_receiving_value_usd`, `mm_pay_metamask_fee_usd`, `mm_pay_quotes_latency`, `mm_pay_quotes_attempts`, `mm_pay_quotes_buffer_size`, `mm_pay_bridge_provider`, `mm_pay_time_to_complete_s`, `mm_pay_use_case`, strategy, fees, and step tracking
- **Retained quote-derived properties in UI hook** (`useTransactionPayMetrics`) to ensure they survive through `Transaction Finalized` events, since `TransactionPayController` clears `transactionData` before Finalized fires. These include: `mm_pay_strategy`, `mm_pay_dust_usd`, `mm_pay_network_fee_usd`, `mm_pay_provider_fee_usd`, `mm_pay_token_selected`, `mm_pay_transaction_step_total`, `mm_pay_transaction_step`, `simulation_sending_assets_total_value`
- **Added UI-level properties** to `useTransactionPayMetrics`: `mm_pay_quote_loaded`
- **Added metrics tracking** to `useTransactionCustomAmount`: `mm_pay_amount_input_type` (manual vs percentage) and `mm_pay_quote_requested` — set via event handlers to avoid overwrite by `useMemo` recomputation
- **Extended `TransactionMetricsRequest`** with `getTransactionPayData` and `getAllTransactions` getters

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/42233 https://consensyssoftware.atlassian.net/browse/CONF-1298

## **Manual testing steps**

1. Enable MetaMetrics opt-in
2. Trigger a perps deposit or mUSD conversion transaction
3. Open the confirmation screen and verify MM Pay flow activates
4. Approve or reject the transaction
5. Inspect Segment events (via Segment debugger) for:
   - `transaction_type` uses snake_case (`perps_deposit`, `musd_conversion`)
   - `mm_pay_*` properties are present on Transaction Added/Approved/Submitted/Finalized events
   - `mm_pay_time_to_complete_s` appears only on Transaction Finalized
   - `mm_pay_amount_input_type` reflects manual typing or percentage selection
   - `mm_pay_quote_loaded` / `mm_pay_quote_requested` reflect UI state
   - `mm_pay_strategy`, `mm_pay_dust_usd`, fees, and step properties persist through Finalized
   - `simulation_sending_assets_total_value` is set for perps/musd transaction types

## **Screenshots/Recordings**

[musd_convert.webm](https://github.com/user-attachments/assets/29f9ee13-6d16-4afb-afeb-945c1e90cc19)

[metrics.webm](https://github.com/user-attachments/assets/8136fe51-c58a-4d54-bdc3-c5dfdc1db585)

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches the shared transaction metrics pipeline and controller adapters, changing emitted analytics properties and `transaction_type` values across multiple transaction flows. Main risk is incorrect/missing metrics or step/parent-child attribution, not user funds or security.
> 
> **Overview**
> Adds a new `getMetaMaskPayProperties` transaction metrics builder and wires it into the background metrics pipeline, deriving `mm_pay_*` properties from Transaction Pay controller data (token/chain selection, use-case, USD amounts/fees, strategy, dust, quote performance metrics, step tracking, and `mm_pay_time_to_complete_s` on `finalized`).
> 
> Updates `TransactionMetricsRequest` and `metamask-controller` to expose `getTransactionPayData`/`getAllTransactions`, and normalizes `transaction_type` output in `metrics-context` to snake_case for several types.
> 
> Refactors UI Pay metrics (`useTransactionPayMetrics`) to focus on UI-state signals like `mm_pay_quote_loaded`, and adds amount-input/quote-request tracking in `useTransactionCustomAmount` (`mm_pay_amount_input_type`, `mm_pay_quote_requested`), with expanded unit tests for the new analytics behavior.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit d9cbe8c60f931597e044dc878e4bfeefdd71d15a. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: app/scripts/lib/transaction/metrics-context.ts [hunk 1]
```diff
@@ -97,22 +97,22 @@ function determineTransactionTypeAndContractInteraction(
...
+    musdConversion: 'musd_conversion',
+    musdClaim: 'musd_claim',
+    perpsDeposit: 'perps_deposit',
+    perpsWithdraw: 'perps_withdraw',
+  };
+
+  if (type in directTypeMappings) {
     return {
-      transactionType: type,
+      transactionType: directTypeMappings[type],
```
[the remark this answers is not in the document]
Comment (bschorchit) [reply app/scripts/lib/transaction/metrics-context.ts:115]: Confirming we want these changes to comply with our metrics schema guidelines

File: ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts [hunk 2]
```diff
@@ -1,117 +1,52 @@
...
-    availableTokens.length,
-    nonGasQuote,
-    payToken,
-    quotes?.length,
-    sendingValue,
-    strategy,
-    totals,
-    transactionMeta,
-  ]);
+  }, [availableTokens.length, payToken]);
```
[the remark this answers is not in the document]
Comment (vinistevam) [reply ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts]: fixed https://github.com/MetaMask/metamask-extension/pull/42251/commits/ee2151eda8a53bb1c2599073ebfddfc289f298b1

File: ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts [hunk 3]
```diff
@@ -1,117 +1,52 @@
...
-    if (totals) {
-      props.mm_pay_network_fee_usd = new BigNumber(
-        totals.fees.sourceNetwork.estimate.usd,
-      )
-        .plus(totals.fees.targetNetwork.usd)
-        .toString(10);
-
-      props.mm_pay_provider_fee_usd = totals.fees.provider.usd;
+      props.mm_pay_quote_loaded = hasQuotes || hasLoadedQuoteRef.current;
+      props.mm_pay_quote_requested = false;
```
[the remark this answers is not in the document]
Comment (vinistevam) [reply ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts]: fixed https://github.com/MetaMask/metamask-extension/pull/42251/commits/cdbe3ffe6fb24ac08558948b9f0899a1750bd316

File: shared/types/metametrics.ts [hunk 4]
```diff
@@ -17,6 +18,9 @@ import type { SnapAndHardwareMessenger } from '../../app/scripts/lib/snap-keyrin
 import { ShieldMetricsSourceEnum } from '../constants/subscriptions';
 import type { ScanAddressResponse } from '../lib/trust-signals';
 
+// TODO: Replace with direct `TransactionData` import once exported from @metamask/transaction-pay-controller
+type TransactionData = TransactionPayControllerState['transactionData'][string];
```
Comment (vinistevam) [inline shared/types/metametrics.ts:22]: PR exporting the type https://github.com/MetaMask/core/pull/8630

**Review by OGPoyraz — APPROVED** [review]

File: ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts [hunk 5]
```diff
@@ -25,10 +25,16 @@ export function useTransactionPayMetrics() {
   const { payToken } = useTransactionPayToken();
   const primaryRequiredToken = useTransactionPayPrimaryRequiredToken();
   const automaticPayToken = useRef<TransactionPaymentToken>();
+  const hasLoadedQuoteRef = useRef(false);
   const quotes = useTransactionPayQuotes();
   const totals = useTransactionPayTotals();
   const tokens = useTransactionPayAvailableTokens();
 
+  const hasQuotes = (quotes?.length ?? 0) > 0;
```
Comment (cryptotavares) [inline ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts:33]: [nit] This condition could probably be simplified. A simple `!!quotes?.length` or `Bolean(quotes?.length)` should be enough.

File: app/scripts/lib/transaction/metrics-context.ts [hunk 6]
```diff
@@ -97,22 +97,22 @@ function determineTransactionTypeAndContractInteraction(
...
+    gasPayment: 'gas_payment',
+    batch: 'batch',
+    shieldSubscriptionApprove: 'shield_subscription_approve',
+    musdConversion: 'musd_conversion',
+    musdClaim: 'musd_claim',
+    perpsDeposit: 'perps_deposit',
+    perpsWithdraw: 'perps_withdraw',
+  };
+
+  if (type in directTypeMappings) {
```
Comment (cryptotavares) [inline app/scripts/lib/transaction/metrics-context.ts:113]: This should probably also apply to the `retry` branch (`if (type === 'retry' && originalType)`). Otherwise for retry transactions we will be capturing the camelCase type in metrics instead of the snake_case

File: app/scripts/lib/transaction/metrics-builders/metamask-pay.ts [hunk 7]
```diff
@@ -0,0 +1,228 @@
...
+    properties.mm_pay_sending_value_usd = Number(
+      primaryRequiredToken.amountUsd ?? '0',
+    );
+  }
+
+  if (totals) {
+    properties.mm_pay_receiving_value_usd = Number(totals.targetAmount.usd);
+    properties.mm_pay_metamask_fee_usd = Number(totals.fees.metaMask.usd);
+    properties.mm_pay_provider_fee_usd = totals.fees.provider.usd;
+    properties.mm_pay_network_fee_usd = new BigNumber(
```
Comment (cryptotavares) [inline app/scripts/lib/transaction/metrics-builders/metamask-pay.ts:211]: Any reason for `mm_pay_metamask_fee_usd` to be a Number, but `mm_pay_provider_fee_usd` and `mm_pay_network_fee_usd` to be strings?

File: ui/pages/confirmations/hooks/transactions/useTransactionCustomAmount.ts [hunk 8]
```diff
@@ -142,9 +143,20 @@ export function useTransactionCustomAmount({
         setIsMax(false);
       }
 
+      if (transactionId) {
+        upsertTransactionUIMetricsFragment(transactionId, {
+          properties: {
+            // eslint-disable-next-line @typescript-eslint/naming-convention
+            mm_pay_amount_input_type: 'manual',
+            // eslint-disable-next-line @typescript-eslint/naming-convention
+            mm_pay_quote_requested: false,
```
Comment (cryptotavares) [inline ui/pages/confirmations/hooks/transactions/useTransactionCustomAmount.ts:152]: mm_pay_quote_requested: false might be inaccurate for manual input.
The call chain is:
1. User types a manual amount → updatePendingAmount('50') is called
2. updatePendingAmount immediately fires mm_pay_quote_requested: false (line 146-154)
3. updatePendingAmount calls setAmountFiat(newAmount) (line 157)
4. setAmountFiat triggers React state update → amountFiat recalculates via useMemo (line 76-86) → amountHuman recalculates via useMemo (line 88-94)
5. amountHuman change triggers the useEffect on line 96-109
6. That useEffect calls debounceRef.current(amountHuman) — the debounced function (lines 52-57)
7. After the 500ms debounce delay, the debounced function calls updateTokenAmountCallback(value) (line 55) — unless disableUpdate is true
8. updateTokenAmountCallback (from useUpdateTokenAmount) calls updateEditableParams which modifies txParams.data on the TransactionController
9. The TransactionPayController listens to TransactionController:stateChange (messenger line 49) and restarts the quote cycle

(Indentified by GPT5.4)

**Review by cryptotavares — APPROVED** [review]

File: ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts (hunk 5 above)
Comment (vinistevam) [reply ui/pages/confirmations/hooks/pay/useTransactionPayMetrics.ts:33]: Thanks @cryptotavares  for review and merge it. I've opened a ticket to tackle your suggestions https://consensyssoftware.atlassian.net/browse/CONF-1335

File: app/scripts/lib/transaction/metrics-builders/metamask-pay.ts (hunk 7 above)
Comment (vinistevam) [reply app/scripts/lib/transaction/metrics-builders/metamask-pay.ts:211]: I was following the schema https://github.com/Consensys/segment-schema/blob/6ff13e7e5a7012bc83f8b8355e83f105ca64677d/libraries/properties/metamask-transactions.yaml#L304
