### PR TITLE
Fixing ENS input entry in send flow

### LINKED ISSUE #10691: 'Recipient address is invalid' error when resolving ENS name set to a valid Ethereum address
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Metamask, select "Mainnet"
2. Click on 'Send', type "deathbeach.eth", and pick the address which comes up.

**Expected behavior**

There should be no error message, but instead, it shows `Recipient address is invalid`.
However, if you copy&paste the resolved address (0x28efaf6cab2b5b848778647c95bf256ce3ba3b8d) then it does not show any error.

Screenshot 2021-03-22 at 16 01 21

**Screenshots**

Screenshot 2021-03-22 at 15 30 13

**Browser details (please complete the following information):**
 - OS: [e.g. OS X]
 - Browser: Version 89.0.4389.90 
 - MetaMask Version: 9.2.0

**Additional context (Error Messages, etc.)**

I am a Dev at ENS team and this is based on the report raised by our user and I was able to replicate the same issue.

### PR DESCRIPTION
**Pull request by ryanml**
Fixes MetaMask/metamask-extension#10691

Explanation:  
With recent updates to `isValidAddress` as provided by `ethereumjs-util`, it is not accepting of invalid hex strings.
This adds an `isHex` validation check to our shared utility for `isValidAddress` to address the regression. With regards to MetaMask/metamask-extension#10691, we additionally check domain validity so as to not throw an invalid recipient error.

Manual testing steps:  
Steps for MetaMask/metamask-extension#10691 are defined in the issue. A general regression test should be performed with sending to ENS and hex addresses.

With fix:
Screen Shot 2021-04-24 at 8 24 08 PM
Screen Shot 2021-04-24 at 8 22 21 PM
Screen Shot 2021-04-24 at 8 21 47 PM
Screen Shot 2021-04-24 at 8 21 35 PM
Screen Shot 2021-04-24 at 8 21 29 PM

### CODE REVIEW

File: ui/app/pages/send/send-content/add-recipient/ens-input.component.js [hunk 1]
```diff
@@ -314,7 +314,7 @@ export default class EnsInput extends Component {
     }
 
     if (ensFailure) {
-      return <i className="fa fa-warning fa-lg warning'" />;
+      return <i className="fa fa-warning fa-lg warning" />;
```
Comment (ryanml) [inline ui/app/pages/send/send-content/add-recipient/ens-input.component.js:317]: this just seemed to be a typo

File: ui/app/pages/send/send-content/add-recipient/add-recipient.js [hunk 2]
```diff
@@ -22,7 +22,7 @@ export function getToErrorObject(to, sendTokenAddress, chainId) {
   let toError = null;
   if (!to) {
     toError = REQUIRED_ERROR;
-  } else if (!isValidAddress(to)) {
+  } else if (!isValidAddress(to) && !isValidDomainName(to)) {
```
Comment (ryanml) [inline ui/app/pages/send/send-content/add-recipient/add-recipient.js:25]: I see we use `isValidDomainName` throughout the codebase to support ENS checks: ui/app/pages/settings/contact-list-tab/add-contact/add-contact.component.js

In this case, it has no improper fall through as part of `add-recipient.js`. It allows ENS names to move forward, and in the case of a valid domain name, not an ENS name, (ex: `brantly.com`) it will just default to the address book lookup, as domain names are fine there.

**Review by brad-decker — APPROVED** [review]

**Comment by brad-decker** [comment]
Great work, @ryanml
