### PR TITLE
fix: Add onboarding completion waiting mechanism for services and controllers

### LINKED ISSUE #40114: [Bug]: `Error#481: Snap platform cannot be used now` appears when logging into MetaMask after wallet reset
### Describe the bug

An error message is logged when logging into a MetaMask wallet after resetting the wallet. The error originates 
`Error#481: Snap platform cannot be used now.`

### Expected behavior

Verify if this error is expected and if so update the code to not throw it and be managed in a different way, for example, a new MixPanel event in case we want to track it. As the result, wallet reset should complete without errors, and the Snap platform should initialize correctly or fail gracefully without logging errors.

### Screenshots/Recordings

https://github.com/user-attachments/assets/a0287760-1dca-4d07-8349-b15d2dcbf73f

### Steps to reproduce

1. Open MetaMask.
2. Reset the wallet.
3. Log in to MetaMask using the reset wallet.
4. Observe the console/log output during login.

### Error messages or log output

```shell
runtime-lavamoat.js:9217 Nested error under Error#480
sentry-install.js:1 Error#481: Snap platform cannot be used now.
```

### Where was this bug found?

Internal release testing

### Version

13.19.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by david0xd**
## **Description**
This PR adds onboarding completion mechanism for controllers and services. 
Controller or a service can use this to wait for the onboarding process to be completed before taking certain steps.

Related Core PR: https://github.com/MetaMask/core/pull/8124

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/40707?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**
Fixes: https://github.com/MetaMask/metamask-extension/issues/40114

## **Manual testing steps**
1. Open MetaMask.
2. Open background console.
3. Reset the wallet.
4. Re-create the wallet.
5. Observe the console/log output during login. Make sure there is no `` error anymore.

### **Before**
No UI changes.

### **After**
No UI changes.

## **Pre-merge author checklist**
- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**
- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches controller initialization wiring and adds a new async onboarding gate used by `MultichainAccountService`, which could affect startup timing/order if the messenger events differ from expectations. Changes are localized but run on every boot.
> 
> **Overview**
> Introduces a shared `createEnsureOnboardingCompleteCallback` helper (with new `OnboardingControllerState` type) that returns a promise resolving once `completedOnboarding` becomes true, using a single shared `stateChange` subscription for concurrent callers.
> 
> Threads a new `ensureOnboardingComplete` function through `ControllerInitRequest`, constructs it in `MetaMaskController` during `#initControllers`, and passes it into `MultichainAccountService` during init; updates mocks and adds unit/integration tests to cover this wiring and the callback behavior.
> 
> Migrates `getTokenValueParam` from `shared/lib/metamask-controller-utils.js` to TypeScript alongside the new onboarding helper.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 71cc4ad2d70e455d7ddf4a2b0921dd0ff8c06902. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: shared/lib/metamask-controller-utils.ts [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    return promise;
+  };
+}
+
+type TokenDataParam = {
+  name?: string;
+  args?: { increment?: unknown; _value?: unknown };
+};
+
+export function getTokenValueParam(
```
Comment (david0xd) [inline shared/lib/metamask-controller-utils.ts:69]: These utils are just ported to TypeScript file from `metamask-controller-utils.js`. I'm not adding any of it.

File: shared/constants/onboarding.ts [hunk 2]
```diff
@@ -37,3 +37,13 @@ export enum FirstTimeFlowType {
...
+
+/**
+ * State shape for the OnboardingController.
+ */
+export type OnboardingControllerState = {
+  seedPhraseBackedUp: boolean | null;
+  firstTimeFlowType: FirstTimeFlowType | null;
+  completedOnboarding: boolean;
+  onboardingTabs?: Record<string, string>;
+};
```
Comment (ccharly) [inline shared/constants/onboarding.ts]: Maybe this should go in `shared/types/onboarding.ts` instead?

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -9050,10 +9053,15 @@ export default class MetamaskController extends EventEmitter {
     return isDisabled;
   }
 
+  #createEnsureOnboardingComplete() {
+    return createEnsureOnboardingComplete(this.controllerMessenger);
```
Comment (ccharly) [inline app/scripts/metamask-controller.js]: Maybe we should append `*Callback` here, just to add a bit more context around this function, WDYT?

```suggestion
  #createEnsureOnboardingCompleteCallback() {
    return createEnsureOnboardingCompleteCallback(this.controllerMessenger);
```

File: shared/constants/onboarding.ts (hunk 2 above)
Comment (david0xd) [reply shared/constants/onboarding.ts]: Updated. Moved.

File: app/scripts/metamask-controller.js (hunk 3 above)
Comment (david0xd) [reply app/scripts/metamask-controller.js]: Updated/renamed.

File: shared/types/onboarding.ts [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+/**
+ * State shape for the OnboardingController.
+ */
+export type OnboardingControllerState = {
+  seedPhraseBackedUp: boolean | null;
+  firstTimeFlowType: FirstTimeFlowType | null;
+  completedOnboarding: boolean;
+  onboardingTabs?: Record<string, string>;
+};
```
[the remark this answers is not in the document]
Comment (david0xd) [reply shared/types/onboarding.ts:11]: I cannot import that type from the `/scripts/` folder because of the ESLint restrictions. I wanted to respect the restrictions and avoid mixing things. This should be refactored at some point, and we should probably have all of these types in `shared` folder, exactly where I've added this type's duplicate. If the `metamask-controller` is ported to TypeScript and refactored, we would notice these issues and have to refactor types, move things to `shared` folder or some other packages, etc.

**Review by ccharly — APPROVED** [review]
LGTM 💪

**Review by montelaidev — APPROVED** [review]
