### PR TITLE
fix(20853): improve the logic to handle fetch

### LINKED ISSUE #20853: Error: Fetch failed with status '403': '' in new-network-info
https://metamask.sentry.io/issues/3404840685/?referrer=github_plugin

```
Error: Fetch failed with status '403': ''
  at _default (shared/lib/fetch-with-cache.js:42:11)
  at checkTokenDetection (ui/components/ui/new-network-info/new-network-info.js:52:40)
  at checkTokenDetection (ui/components/ui/new-network-info/new-network-info.js:61:11)
```

### PR DESCRIPTION
**Pull request by DDDDDanica**
## **Description**
Fix: https://github.com/MetaMask/metamask-extension/issues/20853
For sentry error: 
https://metamask.sentry.io/issues/3404840685/events/a304e0a6b9784a7780254191cdb0dc59/?project=273505
Screenshot 2023-09-20 at 21 37 05

In UI level, the error should be captured and contribute to a state that renders the <add token manually> link. Therefore, we do not need extra UI element to deal with the error. When the error shows up, we want to capture in the `catch` and set that state again just in case.

## **Manual testing steps**
1.  change `{shouldShowNetworkInfo && <NewNetworkInfo />}` to `<NewNetworkInfo />` in `ui/pages/routes/routes.component.js` for testing purpose
2. Enable auto token detection
3. go to network and block the request starting from `0x`
4. You should see the <add link> in the new token information pop up.
 
### **Before**

_[screenshot]_

### **After**

[_[screenshot]_](https://github.com/MetaMask/metamask-extension/assets/12678455/c050e9ad-4918-4656-8625-ade2068fbfa7)

## **Related issues**

_Fixes https://github.com/MetaMask/metamask-extension/issues/20853

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by albertolive — DISMISSED** [review]

File: ui/components/ui/new-network-info/new-network-info.js [hunk 1]
```diff
@@ -48,189 +49,197 @@ const NewNetworkInfo = () => {
...
-
-    setTokenDetectionSupported(fetchedData);
-  };
+  const checkTokenDetection = useCallback(async () => {
+    try {
+      const fetchedTokenData = await fetchWithCache({
+        url: `${TOKEN_API_METASWAP_CODEFI_URL}${providerConfig.chainId}`,
+        functionName: 'getIsTokenDetectionSupported',
+      });
+      const IsTokenDetectionSupported = !fetchedTokenData?.error;
```
Comment (pedronfigueiredo) [inline ui/components/ui/new-network-info/new-network-info.js:58]: camelCase?

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]
