### PR TITLE
fix: Remove scroll to bottom requirement for signatures

### LINKED ISSUE #29779: Fix "Test Snap ethereum_provider can use the ethereum_pro..." flaky tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/119759/workflows/ea8af554-8fb1-4132-89dd-fb5e7bfc8808/jobs/4464355/tests

### PR DESCRIPTION
**Pull request by pnarayanaswamy**
## **Description**

Removes scroll to bottom requirement on signatures
Improves the clickElementSafe function

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29784?quickstart=1)

## **Related issues**

Fixes: [#29779](https://github.com/MetaMask/metamask-extension/issues/29779)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by OGPoyraz — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

File: test/e2e/webdriver/driver.js [hunk 1]
```diff
@@ -707,12 +707,15 @@ class Driver {
...
     try {
       const locator = this.buildLocator(rawLocator);
-
       const elements = await this.driver.wait(
         until.elementsLocated(locator),
         timeout,
       );
 
+      await Promise.all([
+        this.driver.wait(until.elementIsVisible(elements[0]), timeout),
```
Comment (FrederikBolding) [inline test/e2e/webdriver/driver.js:716]: Do we need to remove the scroll to bottom requirement if we do this?

Comment (pnarayanaswamy) [reply test/e2e/webdriver/driver.js:716]: The scroll to bottom was removed on the transaction confirmations a while ago so now we decided to remove it on signatures too.

**Review by FrederikBolding — APPROVED** [review]

**Comment by danjm** [comment]
This PR addresses an issue of a flaky test. To do so, it removes the scroll to bottom requirement on signatures. In the past, the scroll to bottom requirement was accidentally removed and that was regarded as a regression, which was fixed: https://github.com/MetaMask/metamask-planning/issues/2458

Can you link to the ticket where it says that scroll to bottom requirement should be removed? Or can @bschorchit confirm the desired behaviour?

**Comment by danjm** [comment]
Here is the ticket that requests that we no longer disable the button: https://github.com/MetaMask/MetaMask-planning/issues/3467
