### PR TITLE
fix: #30115: Hide import key error

### LINKED ISSUE #30115: [Bug]: "Invalid private key" message persists after an attempt to import an incorrect key, and continues to display after closing and reopening the account selection modal
### Describe the bug

"Invalid private key" message persists after an attempt to import an incorrect key, and continues to display after closing and reopening the account selection modal.
(probably the bug was introduced even before 12.10.3)

### Expected behavior

When the user reopens the modal, it should not retain the state or errors from the previous interaction.

### Screenshots/Recordings

https://github.com/user-attachments/assets/80a85c7e-9b53-428c-8b23-80ce4644fbe3

### Steps to reproduce

1. Open account selection modal
2. Try to import incorrect private key
3. Navigate back using arrows or close and re-open the modal
4. Error message persists

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.10.3

### Build type

None

### Browser

Firefox, Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## **Description**

Some parts of the extension still use a gross global warning state that persists throughout the app.  Ugh.  This removes the state warning when importing a key and backing out of the import.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31129?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30115

## **Manual testing steps**

1. Go to the Account Menu -> choose Import
2. Enter a bad key -> see error
3. Press "Cancel", then choose Import again
4. Don't see error.

### **After**

https://github.com/user-attachments/assets/d8d87015-4212-46a5-8abe-ec34462f9ace

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by vinnyhoward — DISMISSED** [review]

File: ui/components/multichain/import-account/private-key.js [hunk 1]
```diff
@@ -16,9 +17,18 @@ export default function PrivateKeyImportView({
...
   const [privateKey, setPrivateKey] = useState('');
   const [showPrivateKey, setShowPrivateKey] = useState(false);
 
+  // Since MetaMask still uses a global warning state,
+  // hide the "invalid" warning when the private key import view is unmounted
+  useEffect(() => {
+    return () => {
+      dispatch(hideWarning());
+    };
+  }, [dispatch]);
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/import-account/private-key.js:30]: Yeah, honestly, fair enough.

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by gambinish — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
