### PR TITLE
fix: prevent phishing redirect when still on google.com

### LINKED ISSUE #36802: [Bug]: Phishing Detectioon - Google page is flagged when doing a specific search (without trying to go outside Google)
### Describe the bug

Google page is flagged when doing a specific search (without trying to go outside Google).
Only by entering some words in the search bar and pressing enter, the MM phishing page is loaded, but I'm not trying to go outside google, so that shouldn't be flagged.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/17321c92-546e-4816-91b5-47bd48104d5c

### Steps to reproduce

1. Go to google
2. Paste this `srp generator bip44`
3. Press enter
4. Wait -> see how you are redirected to the Phishing page, without clicking on any link

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.4.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by mindofmar**
## **Description**

Fixes an issue where Googling a site on the eth-phishing-detect blocklist could result in blocking google.com before the user navigated to the URL. This is a result of Google pre-fetching the top URL, causing it to be caught by our phishing detection.

## Changelog
CHANGELOG entry: Fixed pre-emptive phishing page redirect on Google search results.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36802

## **Manual testing steps**

1. Google "tornado cash"
2. Observe phishing page being displayed (assuming it is the top search result). This is now fixed so that the phishing page will **not** be displayed until the user actually navigates there.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Prevents phishing warning from triggering during Google search prefetches and emits metrics only when a real redirect occurs.
> 
> - **Phishing detection (background.js)**:
>   - `redirectTab` now checks the current tab URL and skips redirects for `https://www.google.com/search*` prefetches; returns boolean success and captures errors via Sentry.
>   - Introduces `trackPhishingMetrics()` and calls it only when a redirect actually occurs (including async tab redirects for non-`main_frame` and MV3 paths).
>   - MV2 `main_frame` requests still use blocking redirect; non-`main_frame`/MV3 use async tab redirect with conditional metrics.
>   - Adds JSDoc for `redirectTab` and refactors metric emission to avoid duplicate/false positives.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit ac7c6b44228d30ecf58e9ea4ce482774ebef4e6b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/scripts/background.js
Comment (imblue-dabadee) [inline app/scripts/background.js:1]: To be honest, I don't think this logic should be contained within `redirectTab` and perhaps after `.test` is called instead (reset the `phishingTestResponse` value). This helps with the fact that we return `{ cancel: true }` for manifest V2s and also prevents metrics tracking if there's a hit on `google.com`.

**Review by imblue-dabadee — CHANGES_REQUESTED** [review]

File: app/scripts/background.js
Comment (mindofmar) [reply app/scripts/background.js:1]: I can look into this, but there is one important reason it's in the `redirectTab` function. In order to use async/await on the `const tab = await browser.tabs.get(tabId);` check, we have to do it within the async function. `redirectTab` is the only async function here. Obviously we can do `.then + .catch` but the way it's currently implemented seems way cleaner to me.

Comment (imblue-dabadee) [reply app/scripts/background.js:1]:
```javascript
      // blocking is better than tab redirection, as blocking will prevent
      // the browser from loading the page at all
      if (isManifestV2) {
        // We can redirect `main_frame` requests directly to the warning page.
        // For non-`main_frame` requests (e.g. `sub_frame` or WebSocket), we cancel them
        // and redirect the whole tab asynchronously so that the user sees the warning.
        if (details.type === 'main_frame') {
          return { redirectUrl: redirectHref };
        }
        redirectTab(details.tabId, redirectHref);
        return { cancel: true };
      }
 ```
It's probably unlikely this `sub_frame` case would happen, but it is a potential edgecase that's now being introduced.
 
Maybe problematic to introduce an async func and make `maybeDetectPhishing` async but I doubt `await browser.tabs.get()` is slow and introducing an await is only possibly problematic for mv2 since the listener is only blocking for mv2.

Would be down to see @AugmentedMode's perspective.

File: app/scripts/background.js [hunk 1]
```diff
@@ -274,10 +274,19 @@ const sendReadyMessageToTabs = async () => {
 function maybeDetectPhishing(theController) {
```
Comment (imblue-dabadee) [inline app/scripts/background.js:274]: Should have `redirectTab` return a boolean value which can be caught in the callback otherwise this will still fire the metrics regardless of a redirect or not.

File: app/scripts/background.js [hunk 2]
```diff
@@ -354,47 +363,57 @@ function maybeDetectPhishing(theController) {
...
-          },
-        );
-      }
       const querystring = new URLSearchParams({ hostname, href });
       const redirectUrl = new URL(phishingPageHref);
       redirectUrl.hash = querystring.toString();
       const redirectHref = redirectUrl.toString();
 
+      // Helper function to track phishing page metrics
+      const trackPhishingMetrics = () => {
```
Comment (imblue-dabadee) [inline app/scripts/background.js:380]: maybe clearer to make this a function w/ variables or assign the payload as a const and fire the metrics accordingly? But not a big deal either way

File: app/scripts/background.js (hunk 1 above)
Comment (mindofmar) [reply app/scripts/background.js:274]: Good call. Fixed

File: app/scripts/background.js (hunk 2 above)
Comment (mindofmar) [reply app/scripts/background.js:380]: I think I prefer the current method better

**Review by imblue-dabadee — APPROVED** [review]

**Review by AugmentedMode — APPROVED** [review]
Tested both on firefox and chrome and seems to solve the issue!
