### PR TITLE
fix: hide account menu in dapp connection flow

### LINKED ISSUE #37604: [Bug]: Connect Account - Clicking on the Account Details does nothing in the Connect to a dapp screen
### Describe the bug

Clicking on the Account Details does nothing in the Connect to a dapp screen

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/123e5f38-ae37-45a4-ae5d-a6a3b77ea7f0

### Steps to reproduce

1. Go to the test dapp
2. Click Connect
3. Click Edit Accounts
4. Click the 3 dots for opening Account details
5. See nothing happens

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by fabiobozzo**
## **Description**

Fixes a bug where clicking the account details menu (3 dots) in the Connect to dapp screen does nothing. The menu should not be displayed in this flow since users are selecting accounts via checkboxes, not accessing account details.

**Changes:**
- Hide the account menu (`MultichainAccountMenu`) in `MultichainAccountList` when in account selection mode (`showAccountCheckbox` is true)
- Added test coverage to verify the menu is properly hidden during account selection

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37704?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed account details menu appearing in dapp connection account selection

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37604

## **Manual testing steps**

1. Go to the test dapp (https://metamask.github.io/test-dapp/)
2. Click "Connect" button
3. Click "Edit Accounts" in the connection modal
4. Verify that the 3 dots menu is **NOT** visible next to each account
5. Close the edit accounts modal
6. Open the main account menu from the extension
7. Verify that the 3 dots menu IS visible in the normal account list

### **Before**

Account menu (3 dots) was visible but non-functional in the edit accounts flow during dapp connection ([see bug](https://github.com/MetaMask/metamask-extension/issues/37604)).

### **After**

Account menu (3 dots) is now hidden in the edit accounts flow, only checkboxes are shown for account selection:

Screenshot 2025-11-11 at 13 28 08

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Hide the per-account menu when `showAccountCheckbox` is true in `MultichainAccountList`, with tests verifying the menu is not rendered.
> 
> - **Frontend**
>   - **`ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx`**:
>     - Conditionally render `MultichainAccountMenu` only when `showAccountCheckbox` is false (`showAccountMenu = !showAccountCheckbox`).
> - **Tests**
>   - **`multichain-account-list.test.tsx`**:
>     - Add test to assert the 3-dots account menu is hidden when `showAccountCheckbox` is true.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 40b264c95eea728fe12f9c01102c381ea1b1f980. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx [hunk 1]
```diff
@@ -293,13 +293,15 @@ export const MultichainAccountList = ({
...
             }
             endAccessory={
-              <MultichainAccountMenu
-                accountGroupId={groupId as AccountGroupId}
-                isRemovable={isRemovable}
-                handleAccountRenameAction={handleAccountRenameAction}
-                isOpen={openMenuAccountId === groupId}
-                onToggle={() => handleMenuToggle(groupId as AccountGroupId)}
-              />
+              showAccountCheckbox ? undefined : (
```
Comment (montelaidev) [inline ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx]: Maybe we can create a new variable and use it here

`showAccountMenu = !showAccountCheckbox`

Comment (gantunesr) [inline ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx]: Why are you using this variable? should we have a new variable like `showAccountMenu`?

Comment (fabiobozzo) [reply ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx]: Good catch! Updated ✔️

Comment (fabiobozzo) [reply ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx]: You're right! Changed it to use a `showAccountMenu` variable for clarity, as @montelaidev suggested too 👍

**Review by gantunesr — APPROVED** [review]

**Review by montelaidev — APPROVED** [review]
