### PR TITLE
Ensure the seed phrase reminder is displayed with precedence over the network deprecation warning

### LINKED ISSUE #15859: [Bug]: Protocol warning overlaps Backup seed phrase warning
### Describe the bug

**Problem**: with the new Protocol warning, we get an overlap with the Backup your seed phrase warning on the popup view of MetaMask. It looks a bit strange as the Backup your seed gets seen just partially under the Network popup.

image

### Steps to reproduce

1. Import MM
2. Create a new Wallet
3. Do not backup your seed
4. Open MM popup view

### Error messages or log output

_No response_

### Version

10.19.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #15872: [Bug]: Portfolio notification overlaps with Network deprecation warning
### Describe the bug

**Problem**: when I open MM for the first time, if I open the popup view I can see that Portfolio notification is overlapping with the Network deprecation warning.

Screenshot from 2022-09-17 09-48-44

### Steps to reproduce

1. Unlock MM for the first time
2. Open MM popup
3. See how warning are overlapping

### Error messages or log output

_No response_

### Version

10.19.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/15859
Fixes https://github.com/MetaMask/metamask-extension/issues/15872

If the seed phrase backup reminder is shown, we shouldn't show the network deprecation warning or the portfolio tooltip, and the portfolio tooltip will take precedence over the network deprecation warning (because it is permanently dismissible, but the network deprecation warning is not). This PR updates the logic controlling the display of these notifications accordingly

### CODE REVIEW

**Comment by seaona** [comment]
@danjm  I'm seeing this when I load the extension with yarn start
image

File: ui/pages/home/home.container.js [hunk 1]
```diff
@@ -3,7 +3,6 @@ import { connect } from 'react-redux';
 import { withRouter } from 'react-router-dom';
 import {
   activeTabHasPermissions,
-  getCurrentEthBalance,
```
Comment (seaona) [inline ui/pages/home/home.container.js:6]: I believe this is causing an error

**Comment by danjm** [comment]
I am going to update this so that is also fixes https://github.com/MetaMask/metamask-extension/issues/15872

**Comment by danjm** [comment]
This PR now also fixes https://github.com/MetaMask/metamask-extension/issues/15872

**Comment by seaona** [comment]
looks good from QA @danjm

**Review by adonesky1 — DISMISSED** [review]
Tested LGTM!

**Review by adonesky1 — DISMISSED** [review]

**Review by ryanml — DISMISSED** [review]

**Comment by adonesky1** [comment]
looks like e2e test failure might be legit

**Review by ryanml — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
