### PR TITLE
fix(snaps): Restore confirmation switching on routed confirmation

### LINKED ISSUE #27695: Restore the ability to switch between confirmations when routing to a specific one.
Right now when we route to a specific confirmation and there is multiple confirmation queued the navigation header that allows to switch between them is not working. Fix it so that we can switch between the confirmations.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUF1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5807dfd4312a8fd3d70d8348831c22deecc3649a/Screen%20Recording%202024-10-08%20at%2016.51.33.mov)

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

This PR fixes the inability to switch between pending confirmations when routing to a specific confirmation.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27753?quickstart=1)

## **Related issues**

Fixes: #27695

## **Manual testing steps**

1. Redirect to a confirmation
2. Trigger another confirmation after
3. try to switch between the two

### **Before**

https://github.com/user-attachments/assets/95b002fd-c4d2-4521-8e21-ac2f6f42e1d8

### **After**

https://github.com/user-attachments/assets/72e95e8d-a2d9-4024-8ba5-e3b91d409078

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/confirmation/confirmation.js [hunk 1]
```diff
@@ -217,16 +217,19 @@ export default function ConfirmationPage({
...
     (confirmation) => confirmation.id === id,
   );
+
+  const isRoutedConfirmation = id && pendingRoutedConfirmation !== -1;
+
+  const [currentPendingConfirmation, setCurrentPendingConfirmation] = useState(
+    isRoutedConfirmation ? pendingRoutedConfirmation : 0,
+  );
+
   // Confirmations that are directly routed to get priority and will be shown above the current queue.
```
Comment (FrederikBolding) [inline ui/pages/confirmations/confirmation/confirmation.js:231]: We should adjust this comment

File: ui/pages/confirmations/confirmation/confirmation.js [hunk 2]
```diff
@@ -217,16 +217,19 @@ export default function ConfirmationPage({
...
   );
-  // Confirmations that are directly routed to get priority and will be shown above the current queue.
-  const pendingConfirmation =
-    pendingRoutedConfirmation ??
-    pendingConfirmations[currentPendingConfirmation];
+
+  const isRoutedConfirmation = id && pendingRoutedConfirmation !== -1;
+
+  const [currentPendingConfirmation, setCurrentPendingConfirmation] = useState(
+    // Confirmations that are directly routed to get priority and will be shown above the current queue.
```
Comment (FrederikBolding) [inline ui/pages/confirmations/confirmation/confirmation.js:228]:
```suggestion
    // Confirmations that are directly routed to get priority and will be initially shown above the current queue.
```
Like this perhaps 😅

**Review by FrederikBolding — APPROVED** [review]

**Review by david0xd — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]
