### PR TITLE
fix: cp-12.18.0 discard duplicate accounts on unlock

### LINKED ISSUE #32935: [Bug]: Duplicate accounts in the vault break some user actions
### Describe the bug

After https://github.com/MetaMask/metamask-extension/issues/32097 has been fixed, users with duplicates can log in again. However, they can't take any action that requires the vault to be updated, as they still have duplicates.

### Expected behavior

Users with duplicates in the vault should be able to add new accounts and sign transactions. Also, duplicates shouldn't be visible in the account list.

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Switch to the v11.7.3 branch, build locally, and install the extension from chrome://extensions
2. Onboard with an SRP of which we know the second account (child guilt hollow arrive average popular nasty soon summer like scheme diary pill country rapid)
3. Import an account that is part of the mnemonic ( 0x80842b7e3cfb1118e86a427cdec418e3b4179ef5bbbfd71c02a76349831c8a8b which is the account at index 2 of the above SRP)
4. Add a new account on the main HD
5. Switch to Version-v12.17.1 branch, and refresh the extension in chrome://extensions
6. Unlock the wallet, you should see duplicates in your accounts list and you won't be able to add new accounts

### Error messages or log output

May be visible in the console:
```shell
KeyringController - The account you are trying to import is a duplicate
```

### Detection stage

In production (default)

### Version

`>=12.17.1`

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Linux, Windows, MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by mikesposito**
## **Description**

Updating `@metamask/keyring-controller` to `^22.0.0`:

```markdown
## [22.0.0]

### Changed

- **BREAKING** `keyringsMetadata` has been removed from the controller state ([#5725](https://github.com/MetaMask/core/pull/5725))
  - The metadata is now stored in each keyring object in the `state.keyrings` array.
  - When updating to this version, we recommend removing the `keyringsMetadata` state and all state referencing a keyring ID with a migration. New metadata will be generated for each keyring automatically after the update.
### Fixed
- Keyrings with duplicate accounts are skipped as unsupported on unlock ([#5775](https://github.com/MetaMask/core/pull/5775))

## [21.0.6]

### Changed

- Prevent emitting `:stateChange` from `withKeyring` unnecessarily ([#5732](https://github.com/MetaMask/core/pull/5732))

```

and `@metamask/accounts-controller` to `^29.0.0`:

```markdown
## [29.0.0]

### Changed

- **BREAKING:** bump `@metamask/keyring-controller` peer dependency to `^22.0.0` ([#5802](https://github.com/MetaMask/core/pull/5802))

## [28.0.0]

### Added
- Add new `setAccountNameAndSelectAccount` action ([#5714](https://github.com/MetaMask/core/pull/5714))
- Add `entropySource` and `derivationPath` to EVM HD account options ([#5618](https://github.com/MetaMask/core/pull/5618))
### Changed
- **BREAKING:** Bump `@metamask/snaps-controllers` peer dependency from `^9.19.0` to `^11.0.0` ([#5639](https://github.com/MetaMask/core/pull/5639))
- **BREAKING:** Bump `@metamask/providers` peer dependency from `^18.1.0` to `^21.0.0` ([#5639](https://github.com/MetaMask/core/pull/5639))
- Bump `@metamask/base-controller` from `^8.0.0` to `^8.0.1` ([#5722](https://github.com/MetaMask/core/pull/5722))
- Bump `@metamask/snaps-sdk` from `^6.17.1` to `^6.22.0` ([#5639](https://github.com/MetaMask/core/pull/5639))
- Bump `@metamask/snaps-utils` from `^8.10.0` to `^9.2.0` ([#5639](https://github.com/MetaMask/core/pull/5639))
- Bump `@metamask/eth-snap-keyring` from `^12.0.0` to `^12.1.1` ([#5565](https://github.com/MetaMask/core/pull/5565))
- Bump `@metamask/keyring-api` from `^17.2.0` to `^17.4.0` ([#5565](https://github.com/MetaMask/core/pull/5565))
- Bump `@metamask/keyring-internal-api` from `^6.0.0` to `^6.0.1` ([#5565](https://github.com/MetaMask/core/pull/5565))
### Fixed
- Do not fire events during `update` blocks ([#5555](https://github.com/MetaMask/core/pull/5555))
- Prevent unnecessary state updates when updating `InternalAccount.metadata.snap` ([#5735](https://github.com/MetaMask/core/pull/5735))
```

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32621?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32935

### 1. Add duplicate to the wallet state
1.1. Switch to the `v11.7.3` branch, build locally, and install the extension from `chrome://extensions`
1.2. Onboard with an SRP of which we know the second account (`child guilt hollow arrive average popular nasty soon summer like scheme diary pill country rapid`)
1.3. Import an account that is part of the mnemonic ( `0x80842b7e3cfb1118e86a427cdec418e3b4179ef5bbbfd71c02a76349831c8a8b` which is the account at index 2 of the above SRP)
1.4. Add a new account on the main HD
1.5. Switch to `Version-v12.17.1` branch, and refresh the extension in `chrome://extensions`
1.6. Unlock the wallet, you should see duplicates in your accounts list and you won't be able to add new accounts

### 2. Test the fix
2.1. Switch to this branch, build locally, and refresh the extension in `chrome://extensions`
2.2 Unlock the wallet, you shouldn't see duplicate accounts anymore, and you should be able to add new accounts

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/selectors.js [hunk 1]
```diff
@@ -595,21 +595,13 @@ export function getNumberOfTokens(state) {
...
 
 export function getMetaMaskKeyrings(state) {
-  return state.metamask.keyrings.map((keyring, index) => ({
-    ...keyring,
-    metadata: state.metamask.keyringsMetadata?.[index] ?? {},
-  }));
+  return state.metamask.keyrings;
 }
 
-export const getMetaMaskHdKeyrings = createSelector(
```
Comment (mikesposito) [inline ui/selectors/selectors.js:604]: This `createSelector` used here is troublesome for unit tests, as the memoized value makes them interdependent

Comment (mikesposito) [reply ui/selectors/selectors.js:604]: Though I see that this pattern is used for several other selectors as well. Not sure why I started seeing this failing after these changes, but removing `createSelector` is still the only solution I found to be working

File: app/scripts/migrations/159.test.ts
Comment (Gudahtt) [inline app/scripts/migrations/159.test.ts:1]: The latest migration on v12.18.0 is 156. To ensure we don't skip any migrations, we should rename this to 156.1

File: app/scripts/migrations/159.ts
Comment (Gudahtt) [inline app/scripts/migrations/159.ts:1]: Should we remove `state.AccountsController.internalAccounts.accounts[*].options.entropySource` here as well? It references the old keyring IDs that we're removing here.

Likewise for `state.AccountsController.internalAccounts.accounts[*].options.derivationPath`. That one should remain valid AFAIK, but there might be some code that assumes `entropySource` and `derivationPath` are either both present or both missing. Hard to tell because this `options` property is not strictly typed.

cc @MetaMask/accounts-engineers @MetaMask/multi-srp

File: app/scripts/migrations/159.test.ts
Comment (Gudahtt) [reply app/scripts/migrations/159.test.ts:1]: Sorry, make that 156.2. 156.1 was added in v12.17.3

File: app/scripts/migrations/159.ts
Comment (mikesposito) [reply app/scripts/migrations/159.ts:1]: Good point. I see that `internalAccounts` are persisted, but `AccountsController` is subscribed to `KeyringController:stateChange` and runs this method everytime the event is fired - accounts would be updated, although I'm not sure `accounts[i].options` is updated as well

Comment (ccharly) [reply app/scripts/migrations/159.ts:1]: Good point indeed 🙈 AFAIK, we do use the `options.entropySource` for:
1. Solana accounts
2. HD accounts (might not be in-use yet), see:
  - https://github.com/MetaMask/core/pull/5618

For point 2, we should be good, since the `AccountsController` re-creates the internal list of accounts based on each keyring's accounts, so the `entropySource` will be "re-set" properly.

For point 1 though, that's a bit more tricky... 😬 the `AccountsController` will get the Snap accounts from the Snap keyring too, so we cannot modify/migrate `options.entropySource` on a normal migration, as this would get overriden later once the `AccountsController` re-creates the internal account lists.

We faced that issue when we introduced the `account.scopes`, and we had to run a "runtime migration logic" on the Snap keyring itself (since its state is encrypted and cannot be updated during normal migrations):
- https://github.com/MetaMask/accounts/blob/v47.0.0/packages/keyring-snap-bridge/src/SnapKeyring.ts#L667-L685

Some time ago, I tried to solve that issue by combining the existing state (potentially migrated) with the state getting re-constructed on the `AccountsController.{updateAccounts,#handleOnKeyringStateChange}`:
- https://github.com/MetaMask/core/pull/5161

So maybe, we could resurrect this kind of logic on the `AccountsController`, but that's not complete yet, we would also need to let the Solana Snap know that the `entropySource` got changed and use the (Keyring API) `updateAccount`method  to update the account itself on the Snap...

We can discuss this internally if you guys want

---

>  Hard to tell because this options property is not strictly typed.

^ We are working on a ADR with @danroc to try to type the `account.options`, since it's getting really messy now, I agree...

Comment (ccharly) [reply app/scripts/migrations/159.ts:1]: But after thinking about this, this might be a non-issue for Solana for now... But existing Solana accounts will hold an invalid `entropySource` and those accounts would have to be deleted.

Also, worth noting that we do re-create the `internalAccounts` every time we unlock the wallet, so the `options` should automatically be re-populated for EVM HD accounts.

**So we don't need to delete the `accounts.options.entropySource`**:
- This will be automatically re-created for HD accounts ✅
- We don't need to fix up the Solana accounts for now ✅

I will just run a sanity check to confirm this ^, but we should be ok.

File: app/scripts/migrations/159.test.ts
Comment (mikesposito) [reply app/scripts/migrations/159.test.ts:1]: Done in https://github.com/MetaMask/metamask-extension/pull/32621/commits/cb228918fbda8aa5740f3be76c9e02f8cd57610b and https://github.com/MetaMask/metamask-extension/pull/32621/commits/cb228918fbda8aa5740f3be76c9e02f8cd57610b

**Review by naugtur — DISMISSED** [review]
The changes to policy.json look safe.
Approving on behalf of supply-chain and policy-reviewers

**Review by zone-live — DISMISSED** [review]

**Review by OGPoyraz — DISMISSED** [review]

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

File: app/scripts/migrations/159.test.ts
Comment (Gudahtt) [reply app/scripts/migrations/159.test.ts:1]: Darn, sorry I was wrong about the number, it should be 156.1 not 156.2. I was mixing it up with 152.

File: app/scripts/migrations/159.ts
Comment (Gudahtt) [reply app/scripts/migrations/159.ts:1]: Excellent, thanks @ccharly !

Just to confirm, are you sure this won't be a problem for pre-existing snap keyrings that are already being used in production? Is this metadata exposed to them in any way?

**Review by OGPoyraz — APPROVED** [review]

**Review by javiergarciavera — APPROVED** [review]

**Review by naugtur — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]

File: app/scripts/migrations/159.ts
Comment (ccharly) [reply app/scripts/migrations/159.ts:1]: Yes, I can confirm that.

I did a test with the [SSK](https://metamask.github.io/snap-simple-keyring/latest/) and the account was still there after the migration.

The only accounts that are affected are the Solana accounts.

I also confirm that we only use the metadata (`entropySource` only) for 1st party Snaps (Solana for now, Bitcoin is not yet available).

So we are good! 💪

**Review by ccharly — APPROVED** [review]
LGTM.

Regarding the [discussion here](https://github.com/MetaMask/metamask-extension/pull/32621#discussion_r2089525859) about `account.options.entropySource`, here are some technical details and logs on why we will need to re-onboard the wallet (for internal users/QA):

- Solana accounts set the `entropySource` in their `account.options`
- We have no easy way to migrate those `account.options` for now, because the `AccountsController` re-create the `InternalAccount`s list based on keyring's accounts
- Keyring's state (here, the Snap keyring), cannot be migrated, since it's part of the vault (encrypted)
- Thus making it impossible to update the `account.options.entropySource` with the new generated entropy source ID

This means, that, after this PR gets merged, existing Solana accounts won't be usable (and they cannot be fixed). Also, we cannot remove Solana accounts anymore, leaving us with only one option, re-onboard the wallet.

This will make sure that the new Solana accounts will be using the proper `entropySource`, thus fixing the initial problem.

**Review by zone-live — APPROVED** [review]
