### PR TITLE
fix: reset authentication session data upon wallet lock and reset - cp-13.17.0

### LINKED ISSUE #39627: [Bug]: Should remove the subscription state when reset the wallet
### Describe the bug

When I logged in to an account with Shield subscription, then I use the feature Reset wallet to reset the wallet and login or create new account (make sure this account is new or doesn't have the subscription before)

Then when finish the login process, this account will have the Shield subscription from previous account
I tried to do some transaction and it work with Shield cover

### Expected behavior

Should remove the subscription state when reset the wallet

### Screenshots/Recordings

https://github.com/user-attachments/assets/e60e3dd9-63d9-4d39-9ed0-cf99ec111ea4

### Steps to reproduce

1. Login to first account already subscribed the Shield
2. Lock wallet and reset wallet
3. Create new account or Import existing wallet (no Shield sub before)
4. After ob process, go to Setting > Transaction
5. Check will have same subscription with previous account
6. It will be a cheat to use Shield for multiple account 

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

main

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lwin-kyaw**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/39665?quickstart=1)

Explicitly sign out from profile-service when `Reset Wallet` is started.

## **Changelog**

CHANGELOG entry: purge profile service on resetting wallet.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/39627

## **Manual testing steps**

1. Login to first account already subscribed the Shield
2. Lock wallet and reset wallet
3. Create new account or Import existing wallet (no Shield sub before)
4. After ob process, go to Setting > Transaction
5. Assert that shield subscription is not active anymore as the profile id changes.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Medium risk because it changes wallet lock/reset behavior and introduces unconditional auth sign-out plus extra state clearing/polling stops, which could affect session continuity and onboarding flows if misused.
> 
> **Overview**
> Ensures authentication session data is purged when the wallet is locked or reset by explicitly calling `authenticationController.performSignOut()` (guarded on lock, unconditional on reset).
> 
> Extends `resetWallet` to accept a `restoreOnly` flag used by the SRP restore flow to clear subscription/shield/claims state and stop polling while *skipping onboarding reset*; wires this through the Redux action and `RestoreVaultPage` (with updated test coverage).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 325d8f164bdde4e9442c9076a80a35440de97f73. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -3702,12 +3702,18 @@ export default class MetamaskController extends EventEmitter {
   }
 
   async resetWallet() {
+    // sign out from Authentication service and clear the Session Data
+    this.authenticationController.performSignOut();
```
[the remark this answers is not in the document]
Comment (lwin-kyaw) [reply app/scripts/metamask-controller.js:3715]: No, it's not async function.
Ref: https://github.com/MetaMask/core/blob/main/packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts#L330

**Review by LeVinhGithub — DISMISSED** [review]
lgtm QA

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -8580,6 +8598,9 @@ export default class MetamaskController extends EventEmitter {
 
       // stop polling for the subscriptions when the wallet is locked manually and window/side-panel is still open
       this.subscriptionController.stopAllPolling();
+
+      // sign out from Authentication service and clear the Session Data
+      this.authenticationController.performSignOut();
```
Comment (tuna1207) [inline app/scripts/metamask-controller.js]: do we need to signout when locking the wallet, could we add some more comments explaining here

Comment (lwin-kyaw) [reply app/scripts/metamask-controller.js]: This is an expected action, but somehow it doesn't work in the UI side, so, had to do from the background.
Ref: https://github.com/MetaMask/metamask-extension/blob/main/ui/hooks/identity/useAuthentication/useAutoSignOut.ts#L29

Also, we should do the `performSignOut` just to clear the sensitive data (AuthToken) from the extension local storage.

Comment (tuna1207) [reply app/scripts/metamask-controller.js]: I think we should comment this in the code to make it clear about the not working auto signout and add TODO to check the UI side auto signout

Comment (lwin-kyaw) [reply app/scripts/metamask-controller.js]: I added the comment though, the motive is to clear the session data
```
// sign out from Authentication service and clear the Session Data
```

Comment (tuna1207) [reply app/scripts/metamask-controller.js]: Ah i mean the auto signout not working

**Review by tuna1207 — DISMISSED** [review]

**Review by lionellbriones — DISMISSED** [review]

**Review by chaitanyapotti — APPROVED** [review]

**Review by LeVinhGithub — APPROVED** [review]
