### PR TITLE
fix: Fix in label displayed for state change in signature decoding section

### LINKED ISSUE #28944: [Bug]: Displaying multiple "You list" when multiple assets are being listed
### Describe the bug

We currently displaying multiple "You list" and "Spending cap" for multiple assets. We should be displaying the copy only once similar to how we do it for simulations. 

### Expected behavior

Displaying "You list" only once for the first asset - similar to how we do on simulations when multiple assets are being received or sent.

### Screenshots/Recordings

image

Image

### Steps to reproduce

1. Go to test dapp
2. Click on Malicious Seaport 
3. See the Estimated changes section

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.9.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

We currently displaying multiple "You list" and "Spending cap" for multiple assets. We should be displaying the copy only once similar to how we do it for simulations.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28944

## **Manual testing steps**

1. Submit a typed sign v4 request with multiple NFT listed
2. Check simulation section on page displayed

## **Screenshots/Recordings**
Screenshot 2024-12-09 at 6 05 46 PM

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx [hunk 1]
```diff
@@ -104,19 +106,39 @@ const DecodedSimulation: React.FC<object> = () => {
...
-  const stateChangeFragment = useMemo(
-    () =>
-      (decodingData?.stateChanges ?? []).map(
-        (change: DecodingDataStateChange) => (
+  const stateChangeFragment = useMemo(() => {
+    const stateChangesGrouped: Record<string, DecodingDataStateChange[]> = (
+      decodingData?.stateChanges ?? []
+    ).reduce(
+      (
+        result: Record<string, DecodingDataStateChange[]>,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx:114]: Minor, you can pass the target type as a template on `reduce` and you won't need to cast the output and `result` variable.

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx [hunk 2]
```diff
@@ -60,18 +60,20 @@ const StateChangeRow = ({
   stateChangeList,
   stateChange,
   chainId,
+  displayLabel,
 }: {
   stateChangeList: DecodingDataStateChanges | null;
   stateChange: DecodingDataStateChange;
   chainId: Hex;
+  displayLabel: boolean;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx:68]: Minor, should this be `shouldDisplayLabel` to make it clear it's a boolean?

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx [hunk 3]
```diff
@@ -104,19 +106,39 @@ const DecodedSimulation: React.FC<object> = () => {
...
             chainId={chainId}
+            displayLabel={index === 0}
           />
-        ),
-      ),
-    [decodingData?.stateChanges],
-  );
+        )),
+      )
+      .reduce(
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx:137]: Minor, rather than reducing, could we just use `flatMap` above?

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx (hunk 3 above)
Comment (jpuri) [reply ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx]: updated

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx (hunk 2 above)
Comment (jpuri) [reply ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx]: updated

**Review by matthewwalsh0 — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
