### PR TITLE
fix: added support link to unlock page cp-13.10.0

### LINKED ISSUE #37996: [Bug]:  Keep “Contact Support” link on the unlock screen
### Describe the bug

We should retain the Contact Support link on the extension’s unlock screen.

This link remains heavily used — we see ~1,000 unique users clicking it every day. Removing a well-used support path to simplify the UI isn’t ideal.

### Expected behavior

Image

### Screenshots/Recordings

_No response_

### Steps to reproduce

Unlock screen on extension is missing contact support

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.10

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by smgv**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37967?quickstart=1)

In this PR, we have enabled the MetaMask Support link in unlock page.

Jira Link: https://consensyssoftware.atlassian.net/browse/SL-329

Figma Link: https://www.figma.com/design/pViOUcmjwhEzFsdrwknpNc/Onboarding-Redesign?node-id=18656-27472&m=dev

## **Changelog**

CHANGELOG entry: added the support link back in unlock page.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Open Extension
2. Create Wallet
3. Lock the app
4. Validate changes in unlock page.
5.

### **Before**

Screenshot 2025-11-19 at 1 06 31 PM

### **After**

Screenshot 2025-11-19 at 12 51 52 PM
Screenshot 2025-11-19 at 12 52 07 PM
Screenshot 2025-11-19 at 12 52 37 PM
Screenshot 2025-11-19 at 12 53 04 PM
Screenshot 2025-11-19 at 12 53 20 PM
Screenshot 2025-11-19 at 12 53 38 PM

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds a support link with tracking to the unlock page, introduces popup-specific logo spacing via a new isPopup prop, and tweaks margins/spacing.
> 
> - **Unlock Page UI**:
>   - **Support link**: Adds “Need help? Contact MetaMask support” with external link and metrics tracking (`SupportLinkClicked`).
>   - **Spacing tweaks**: Reduces `Forgot password?` margin (`marginBottom` 6→4); adjusts `unlock-page__mascot-container__horizontal-logo` default margin (60px→24px); adds popup modifier `--popup` to remove bottom margin.
> - **Logic/Props**:
>   - Passes new `isPopup` prop from container (via `getEnvironmentType() === ENVIRONMENT_TYPE_POPUP`) to component; applies conditional class to `MetaFoxHorizontalLogo`.
> - **Styles**:
>   - Updates `index.scss` to add `&--popup` modifier and new margins.
> - **Tests**:
>   - Updates snapshot to reflect new support link and spacing changes.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1001a7e412c583d38d075c066f4085e82447c224. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by LeVinhGithub — APPROVED** [review]
lgtm QA

File: ui/pages/unlock-page/unlock-page.component.js [hunk 1]
```diff
@@ -638,38 +644,37 @@ class UnlockPage extends Component {
...
-                    key="need-help-link"
-                    onClick={() => {
-                      this.context.trackEvent(
-                        {
-                          category: MetaMetricsEventCategory.Navigation,
-                          event: MetaMetricsEventName.SupportLinkClicked,
-                          properties: {
-                            url: SUPPORT_LINK,
-                          },
+            <Text variant={TextVariant.bodyMd} color={TextColor.textDefault}>
```
Comment (chaitanyapotti) [inline ui/pages/unlock-page/unlock-page.component.js:647]: do we want to show this always instead of just rehydration flow?

Comment (smgv) [reply ui/pages/unlock-page/unlock-page.component.js:647]: While this feature existed previously, the UX team requested its removal during the unlock page redesign. Since it's still needed for rehydration, I've implemented a conditional check to maintain this functionality where required.

cc: @nakulmk @valantia-chang

File: ui/pages/unlock-page/unlock-page.component.js [hunk 2]
```diff
@@ -638,38 +644,37 @@ class UnlockPage extends Component {
...
+                          MetaMetricsContextProp.PageTitle,
+                        ],
+                      },
+                    );
+                  }}
+                >
+                  {needHelpText}
+                </Button>,
+              ])}
+            </Text>
```
[the remark this answers is not in the document]
Comment (smgv) [reply ui/pages/unlock-page/unlock-page.component.js:677]: While this feature existed previously, the UX team requested its removal during the unlock page redesign. Since it's still needed for rehydration, I've implemented a conditional check to maintain this functionality where required.

**Review by lwin-kyaw — APPROVED** [review]
