### PR TITLE
fix: prevent status update while updating max value

### LINKED ISSUE #23401: [Bug]: Unapproved transaction stuck, settings and other buttons disabled
### Describe the bug

As I was trying to run a transaction earlier, I had approved it but when I checked metamask said that it was unapproved and when I try to reject it nothing happens. Now I have network, settings, and connected sites buttons greyed out. Metamask currently unusable.

### Expected behavior

_No response_

### Screenshots/Recordings

image
image
image

### Steps to reproduce

Not sure how to reproduce

### Error messages or log output

_No response_

### Version

11.11.4

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

When user approves the transaction, `ConfirmTransactionBase` component is getting new props which will lead it to `updateToMax` value before leaving page. When `updateToMax` resolves it makes the transaction status as `unapproved` but already `signed`

This PR is aiming to prevent `updateToMax` value to update transaction status. Rather just update the value.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23647?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23401

## **Manual testing steps**

https://www.youtube.com/watch?v=bjI8x1zcB5o

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js [hunk 1]
```diff
@@ -370,6 +370,9 @@ export default class ConfirmTransactionBase extends Component {
   updateValueToMax() {
     const { maxValue: value, txData, updateTransaction } = this.props;
 
+    // Remove status from txData to avoid overwriting the txData.status
+    delete txData.status;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:374]: My understanding was that `updateTransaction` assigns the entire property in the state array meaning we always have to provide the full transaction data? Would this not result in a missing status?

Would it be safer to instead use `updateEditableParams` so we can update only the `value` and nothing else?

Comment (OGPoyraz) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js:374]: I thought we were merging with previous one on update, I was totally wrong, now it raises some question on my head that what if we send partial `TransactionMeta` to `updateTransaction`. We always wanted to make atomic updates with different update methods but this made me feel a bit concerned now. 

I didn't even see an error (losing status) while doing manual tests too which is weird, if I followed properly it's not merged in redux either. 

Anyway, you're right, it would make sense to make it smallest update. I added a method to it's container just to update it's value.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by dbrans — APPROVED** [review]
Looks great!
