### PR TITLE
fix: disable unsupported swap+send networks

### LINKED ISSUE #25107: [Bug]: Send and swap flow for unsupported networks
### Describe the bug

  In the context of the send+swap flow on unsupported networks, considering the substantial user base operating within these networks, introducing a notification system or potentially disabling this feature for networks beyond the mainnet and BNB might significantly improve the user experience. 
      Currently, when users on unsupported networks attempt to use the send+swap feature, they are allowed to select a destination token, only to encounter 'No quotes available' for the native token and 'Error fetching quotes' for other tokens.
       A more user-friendly approach could involve defaulting to the regular send flow for non-supported networks (removing the option to select a destination token). 

### Expected behavior

-

### Screenshots/Recordings

Screenshot 2024-06-05 at 23 39 13

Screenshot 2024-06-05 at 23 40 47

### Steps to reproduce

1. Connect to unsupported network (e.g., Polygon, Arbitrum, etc.)
2. Start send+swap flow
3. Select native token as an origin token and any other token for the destination
4. See 'No quotes available' message
5. Select non-native token as an origin
6. Select any token as a destination token
7.  'Error fetching quotes' is shown

### Error messages or log output

_No response_

### Version

develop branch

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by BZahory**
## **Description**

Swap+Send relies on a function in the newest swap+send contracts (i.e. once Swap+Send is deployed on all current swap networks, Swap+Send network support should be 1-to-1 with that of Swaps). However, we are still waiting on the API to be updated for these new contracts so we cannot operate under the assumption that all of these networks will be deployed by the time Swap+Send begins rolling out in production.

To mitigate this concern, we can utilize a property in Swaps' feature flag endpoint (see: https://swap.dev-api.cx.metamask.io/featureFlags) when the send flow is initialized to determine if that network should be disabled despite having swaps support.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25474?quickstart=1)

## **Related issues**

Fixes: #25107 

## **Manual testing steps**

1. Set `SWAPS_USE_DEV_APIS=true` in `.metamaskrc` (the endpoint update hasn't been deployed to prod as of writing)
2. Switch to an unsupported network (e.g., zkSync)
3. Verify that, when entering the swaps flow, that network is disabled (i.e., the destination asset picker is disabled)
4. Switch to a supported network (e.g., BNB)
5. Verify that the network is not disabled in the send flow

#### zkSync (network enabled despite no support)

Screenshot 2024-06-21 at 2 01 27 PM

#### BNB (network enabled)

Screenshot 2024-06-21 at 2 00 48 PM

#### zkSync (network disabled)

Screenshot 2024-06-21 at 1 59 48 PM

#### BNB (network enabled)

Screenshot 2024-06-21 at 2 00 11 PM

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/ducks/send/swap-and-send-utils.ts [hunk 1]
```diff
@@ -208,3 +210,50 @@ export async function getSwapAndSendQuotes(request: Request): Promise<Quote[]> {
...
+    const featureFlagResponse = await fetchWithCache({
+      url,
+      fetchOptions: {
+        method: 'GET',
+        headers: { 'X-Client-Id': SWAPS_CLIENT_ID },
+      },
+      cacheOptions: { cacheRefreshTime: 0, timeout: MINUTE * 5 },
+      functionName: 'getDisabledSwapAndSendNetworks',
+    });
+
```
Comment (micaelae) [inline ui/ducks/send/swap-and-send-utils.ts:243]: Why not reuse `fetchSwapsFeatureFlags` here?

File: ui/ducks/send/swap-and-send-utils.ts [hunk 2]
```diff
@@ -208,3 +210,50 @@ export async function getSwapAndSendQuotes(request: Request): Promise<Quote[]> {
...
+  [CHAIN_IDS.MAINNET]: 'ethereum',
+  [CHAIN_IDS.BSC]: 'bsc',
+  [CHAIN_IDS.POLYGON]: 'polygon',
+  [CHAIN_IDS.AVALANCHE]: 'avalanche',
+  [CHAIN_IDS.ARBITRUM]: 'arbitrum',
+  [CHAIN_IDS.OPTIMISM]: 'optimism',
+  [CHAIN_IDS.ZKSYNC_ERA]: 'zksync',
+  [CHAIN_IDS.LINEA_MAINNET]: 'linea',
+  [CHAIN_IDS.BASE]: 'base',
+};
```
Comment (micaelae) [inline ui/ducks/send/swap-and-send-utils.ts:224]: I'd recommend reusing swaps util `getNetworkNameByChainId` here to keep things consistent and avoid duplication

File: ui/ducks/send/swap-and-send-utils.ts [hunk 3]
```diff
@@ -208,3 +210,50 @@ export async function getSwapAndSendQuotes(request: Request): Promise<Quote[]> {
...
+      url,
+      fetchOptions: {
+        method: 'GET',
+        headers: { 'X-Client-Id': SWAPS_CLIENT_ID },
+      },
+      cacheOptions: { cacheRefreshTime: 0, timeout: MINUTE * 5 },
+      functionName: 'getDisabledSwapAndSendNetworks',
+    });
+
+    ALLOWED_PROD_SWAPS_CHAIN_IDS.forEach((chainId) => {
```
Comment (micaelae) [inline ui/ducks/send/swap-and-send-utils.ts:244]: Do you know if using this constant is preferrable over the `swapsFeatureIsLive` state? This one is hardcoded while the latter is dynamic

File: ui/ducks/send/swap-and-send-utils.ts [hunk 4]
```diff
@@ -208,3 +210,50 @@ export async function getSwapAndSendQuotes(request: Request): Promise<Quote[]> {
...
+
+    const featureFlagResponse = await fetchWithCache({
+      url,
+      fetchOptions: {
+        method: 'GET',
+        headers: { 'X-Client-Id': SWAPS_CLIENT_ID },
+      },
+      cacheOptions: { cacheRefreshTime: 0, timeout: MINUTE * 5 },
+      functionName: 'getDisabledSwapAndSendNetworks',
+    });
```
Comment (micaelae) [inline ui/ducks/send/swap-and-send-utils.ts:242]: Actually, would it be possible to reuse `state.metamask.swapsState.swapsFeatureFlags` background state here? I'm thinking the fetch call can be added to `useUpdateSwapsState`

File: ui/ducks/send/swap-and-send-utils.ts (hunk 2 above)
Comment (BZahory) [reply ui/ducks/send/swap-and-send-utils.ts]: Good call

File: ui/ducks/send/swap-and-send-utils.ts (hunk 1 above)
Comment (BZahory) [reply ui/ducks/send/swap-and-send-utils.ts]: Good call

File: ui/ducks/send/swap-and-send-utils.ts (hunk 3 above)
Comment (BZahory) [reply ui/ducks/send/swap-and-send-utils.ts:225]: The goal is to iterate through the supported Swaps chain IDs and find all the ones that aren't supported by swap+send. We handle chain by chain booleans with the `getIsSwapAndSendDisabledForNetwork` selector

File: ui/ducks/send/swap-and-send-utils.ts (hunk 4 above)
Comment (BZahory) [reply ui/ducks/send/swap-and-send-utils.ts]: Would prefer not to since it decouples the logic (i.e., we have to reference the swap state, and rely on said state getting updated through another couple) and prevents us from just getting the flags whenever the send flow is initialized

Comment (micaelae) [reply ui/ducks/send/swap-and-send-utils.ts]: aren't we already doing that in the hook though?

Comment (BZahory) [reply ui/ducks/send/swap-and-send-utils.ts]: Yeah, I'm not a fan of the pattern though honestly. It was just the easiest way to ensure the swap state is ready (I just copied a bunch of stuff over). I worry that going through the swaps state too much will make our logic more likely to break when something in swaps is changed – we got burnt when a selector for non-1559 gas was refactored during #23703

Comment (micaelae) [reply ui/ducks/send/swap-and-send-utils.ts]: Fair point, lgtm. Although this may become a more common pattern as we introduce more combined experiences, like Swap+Bridge and Swap+Send

> going through the swaps state too much will make our logic more likely to break when something in swaps is changed

Fwiw I think this could be framed as a benefit as well - if there's a breaking swaps change it would be more ideal to break Swap+Send at PR or QA time, rather than failing silently when we start getting unexpected data

Comment (BZahory) [reply ui/ducks/send/swap-and-send-utils.ts]: All valid points, but without TypeScript things could easily slip through the gaps.

**Review by sleepytanya — APPROVED** [review]

**Comment by sleepytanya** [comment]
Send+swap works on supported networks:
Screenshot 2024-06-21 at 17 52 50

**Review by micaelae — APPROVED** [review]
