### PR TITLE
Fix: eth_sign does not validate input

### LINKED ISSUE #5039: bug: eth_sign does not validate input
i was seeing the metamask approval window and approving it but not seeing the callback called from the dapp

invocation method:
```js
web3.eth.sign(web3.eth.accounts[0], 'yo', console.log)
```

### PR DESCRIPTION
**Pull request by ritave**
Fixes: #5039

### CODE REVIEW

File: app/scripts/lib/message-manager.js [hunk 1]
```diff
@@ -79,8 +79,8 @@ export default class MessageManager extends EventEmitter {
    *
    */
   addUnapprovedMessageAsync(msgParams, req) {
+    const msgId = this.addUnapprovedMessage(msgParams, req);
```
Comment (ritave) [inline app/scripts/lib/message-manager.js:82]: Tests were failing due to race condition, trying to access unapproved list before the Promise even started

Comment (Gudahtt) [reply app/scripts/lib/message-manager.js:82]: Huh, interesting. So this situation isn't ideal because if `addUnapprovedMessage` throws, it'll do so synchronously, but if anything inside the Promise throws, it'll reject. This might be confusing if anyone tries to handle errors with `.catch` and this throws and slips past that attempt.

Could you remove the `Promise` wrapper altogether and make this function `async`? Or would that trigger the same issue you encountered here I wonder. Which test was it that was failing?

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -1826,12 +1827,18 @@ export default class MetamaskController extends EventEmitter {
    * @param {Function} cb - The callback function called with the signature.
    */
   newUnsignedMessage(msgParams, req) {
-    const promise = this.messageManager.addUnapprovedMessageAsync(
-      msgParams,
-      req,
-    );
-    this.sendUpdate();
-    this.opts.showUserConfirmation();
+    const data = normalizeMsgData(msgParams.data);
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js:1830]: Just as with the other comment, I think having two styles of throwing errors in this function is confusing and should be avoided. Making this `async` would ensure errors are thrown in a single way.

This was an issue that I had known about for a while, and haven't gotten around to fixing yet.

File: app/scripts/lib/message-manager.js (hunk 1 above)
Comment (ritave) [reply app/scripts/lib/message-manager.js:82]: It failed here - https://github.com/MetaMask/metamask-extension/blob/6309d51e359aa0d1788f180fb410e39a1e2bd0d8/app/scripts/metamask-controller.test.js#L857-L864
With `messages` returned being empty.

I don't think this promise can be easily converted into async, since it waits on EventEmitter

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -1825,14 +1826,20 @@ export default class MetamaskController extends EventEmitter {
...
-  newUnsignedMessage(msgParams, req) {
-    const promise = this.messageManager.addUnapprovedMessageAsync(
-      msgParams,
-      req,
-    );
-    this.sendUpdate();
-    this.opts.showUserConfirmation();
-    return promise;
+  async newUnsignedMessage(msgParams, req) {
+    const data = normalizeMsgData(msgParams.data);
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js:1830]: It looks like this `normalizeMsgData` function is being called twice now - once here, and once in `addUnapprovedMessage` in `message-manager-.js`.

I don't really follow why it was moved to be honest. Also, does it need to be called twice?

File: app/scripts/metamask-controller.js [hunk 4]
```diff
@@ -1825,14 +1826,20 @@ export default class MetamaskController extends EventEmitter {
...
+    let promise;
+    // 64 hex + "0x" at the beginning
+    if (data.length === 66) {
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js:1833]: Why require messages to be 64 hex characters?

Comment (ritave) [reply app/scripts/metamask-controller.js:1833]: This is the requirement of ECSign we use behind the scenes, it only works for 32 byte numbers

File: app/scripts/metamask-controller.js (hunk 3 above)
Comment (ritave) [reply app/scripts/metamask-controller.js:1830]: We need to check the 32 byte length somehow, and data can be either a Buffer or a hex string. Without this function we would need to check for both types of incoming data. Normalising it is simpler

File: app/scripts/metamask-controller.js (hunk 4 above)
Comment (ritave) [reply app/scripts/metamask-controller.js:1833]: I'll add more explicit documentation

File: app/scripts/metamask-controller.js (hunk 3 above)
Comment (Gudahtt) [reply app/scripts/metamask-controller.js:1830]: Gotcha. I hadn't realized a length of 32 was a requirement. Testing with prod confirms that it is the case though. Mostly anyway.

I noticed one odd exception: if the message contains an odd number of digits, the last digit is ignored. I see how that would happen, as that would be 32 and a half bytes. I guess it interprets the string as bytes and ignores any remainder.

But imposing this new restriction could break sites that are unintentionally relying on their signatures working even when they add an extra byte. Perhaps we should allow the extra character for this reason, just to make this non-breaking.

**Comment by Gudahtt** [comment]
It's great that we've prevented this case from happening with added validation, but it's still concerning that any failure during signing results in no error being returned to the site. If some other case also resulted in throwing, we'd see the same behaviour of the request staying as pending forever.

I think the reason the request remains pending is that we don't handle the error properly in `signMessage`. We don't handle it in `signPersonalMessage` either. If the signing fails, we bubble the error up to the UI (which is good), but we don't set the state of that message to "failed". You can see this is done with some of the other signatures types, like `decruptMessage` and `signTypedMessage`. Rather than let it bubble up directly, we should be catching the error, setting the status of the signature request as failed, _then_ re-throwing it so the UI knows that it failed.

This would ensure that if something breaks again in the future, at least the site knows it failed.

**Review by Gudahtt — COMMENTED** [review]
LGTM! I can approve after the lint error is fixed.

**Review by Gudahtt — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
