### PR TITLE
fix: Add scuttle exception for fetch because it is used by chromium image util code when creating notifications

### LINKED ISSUE #24518: [Bug]: MV3 - Transactions - Sending a tx from a dapp triggers errors `failed to create transaction notification` and `Lavamoat: property fetch of globalThis is inaccessible`
### Describe the bug

Whenever I send a transaction with a lower nonce, I see that MM popup stays loading for more than usual time, and the following background console errors appear:
- `failed to create transaction notification` and 
- `Lavamoat: property fetch of globalThis is inaccessible`

Update: it seems this only happens with MV3 build
Update2: the errors seem to appear to all type of tx's (successful and not successful)

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot from 2024-05-14 15-04-43

https://github.com/MetaMask/metamask-extension/assets/54408225/414d7880-e1f4-4296-80de-ad591a2a7371

The video below shows what is currently happening in prod: tx fails immediately, popup is closed and no errors above:

https://github.com/MetaMask/metamask-extension/assets/54408225/61382a76-2248-4d20-b7f0-f6a462593b50

### Steps to reproduce

1. Enable custom nonce from settings
2. Trigger a tx from a dapp
3. Set a nonce with lower value
4. Accept the tx
5. See how MM popup stays loading for several seconds
6. See console errors

### Error messages or log output

_No response_

### Version

develop with MV3 build

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by danjm**
## **Description**

MV3 bug that we needto fix: https://github.com/MetaMask/metamask-extension/issues/24518

In particular, we've got:
```
LavaMoat - property "fetch" of globalThis is inaccessible under scuttling mode.
at get (chrome-extension://lbnhnppncgilfagdfbanifbfolodkdaf/scripts/runtime-lavamoat.js:13190:11)
  at loadImageDataForServiceWorker (extensions::imageUtil:24:22)
  at loadImageData (extensions::imageUtil:111:5)
  at Object.loadAllImages (extensions::imageUtil:134:5)
  at replaceNotificationOptionURLs (extensions::notifications:89:13)
  at extensions::notifications:116:5
  at chrome-extension://lbnhnppncgilfagdfbanifbfolodkdaf/common-6.js:3:431145
  at new Promise (<anonymous>)
  at Proxy.<anonymous> (chrome-extension://lbnhnppncgilfagdfbanifbfolodkdaf/common-6.js:3:430825)
  at Object.apply (chrome-extension://lbnhnppncgilfagdfbanifbfolodkdaf/common-6.js:3:430244)
  at Object._showNotification (chrome-extension://lbnhnppncgilfagdfbanifbfolodkdaf/common-2.js:1:455026)
```

The problematic code is in not in our codebase but in chromium, here: https://github.com/chromium/chromium/blob/main/extensions/renderer/resources/image_util.js#L23-L25

You can see that function is named loadImageDataForServiceWorker and it is only used in mv3.

This breaks the browser notification feature.

As can be seen from the commit history and the comments in this PR, we attemtped some solutions that would allow us to provide a modified and tamed fetch to be used for this image fetching. However, there are unknown problems - related to how sentry uses fetch and how sentry is initialized - that interfere with the solutions we attempted. So for now, as discussed with @weizman, the latest commit on the PR just adds a scuttling exception for fetch (and for Offscreen Canvas, which is also needed for the browser notification feature).

We will return to the root problem later, and aim to remove these scuttling exceptions.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24518

## **Manual testing steps**

1. `yarn dist:mv3`
2. install, onboard
3. send a transaction
4. verify that a browser notification is shown once the transaction is confirmed

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/use-snow.js [hunk 1]
```diff
@@ -12,16 +12,45 @@ Changing this code must be done cautiously to avoid breaking the app!
...
+    throw new Error(
+      'Unscuttled fetch can only be used on images within the extension',
+    );
+  };
+
   // eslint-disable-next-line no-undef
   Object.defineProperty(self, 'SCUTTLER', {
     value: (realm, scuttle) => {
+      const scuttleWithRestrictedException = (_ref, restrictedExceptions) => {
+        const ref = _ref;
```
Comment (weizman) [inline app/scripts/use-snow.js:35]: What's this for?

File: app/scripts/use-snow.js [hunk 2]
```diff
@@ -12,16 +12,45 @@ Changing this code must be done cautiously to avoid breaking the app!
...
+    }
+    throw new Error(
+      'Unscuttled fetch can only be used on images within the extension',
+    );
+  };
+
   // eslint-disable-next-line no-undef
   Object.defineProperty(self, 'SCUTTLER', {
     value: (realm, scuttle) => {
+      const scuttleWithRestrictedException = (_ref, restrictedExceptions) => {
```
Comment (weizman) [inline app/scripts/use-snow.js:34]: I'd move this function to the upper scope (same as tamedFetch)

File: app/scripts/use-snow.js [hunk 3]
```diff
@@ -12,16 +12,45 @@ Changing this code must be done cautiously to avoid breaking the app!
...
+  const tamedFetch = (path) => {
+    const regex = new RegExp(
+      `^chrome-extension://${chromeExtensionId}/.*?/images/.*`,
+      'u',
+    );
+    if (regex.test(path)) {
+      return fetch(path);
+    }
+    throw new Error(
+      'Unscuttled fetch can only be used on images within the extension',
```
Comment (weizman) [inline app/scripts/use-snow.js:27]: Unscuttled -> tamed

File: app/scripts/use-snow.js [hunk 4]
```diff
@@ -12,16 +12,45 @@ Changing this code must be done cautiously to avoid breaking the app!
...
+  };
+
   // eslint-disable-next-line no-undef
   Object.defineProperty(self, 'SCUTTLER', {
     value: (realm, scuttle) => {
+      const scuttleWithRestrictedException = (_ref, restrictedExceptions) => {
+        const ref = _ref;
+        for (const key in restrictedExceptions) {
+          if (Object.hasOwn(restrictedExceptions, key)) {
+            ref[key] = restrictedExceptions[key];
```
Comment (weizman) [inline app/scripts/use-snow.js:38]: We must use defineProperty and set configurable and writable to false. This will instruct the scuttling process to skip `fetch`, which would allow you to remove the exception from `development/build/index.js`

File: app/scripts/use-snow.js [hunk 5]
```diff
@@ -12,16 +12,45 @@ Changing this code must be done cautiously to avoid breaking the app!
   const isWorker = !self.document;
   const msg =
     'Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm.';
+
+  // eslint-disable-next-line no-undef
+  const chromeExtensionId = chrome && chrome.runtime && chrome.runtime.id;
```
Comment (weizman) [inline app/scripts/use-snow.js:17]: What's the importance of the `chromeExtensionId` below really? I think we can allow fetching images from the `chrome-extension` scheme for all types of browser extension entities we create

**Review by weizman — COMMENTED** [review]
Looks great,

Some important comments.

Also, a more general (yet very important) comment:

We must cache the APIs we're using as part of this feature in order to not trust they aren't being modified later on. SES assures that in practice, but it's still a more secure approach in case we extend this to use APIs that aren't strictly SES protected intrinsics.

So cache and use the `test` property of RegExp and Error and fetch and Object.hasOwn and so on.

I can help with that part 👍

File: development/build/index.js [hunk 6]
```diff
@@ -114,6 +114,7 @@ async function defineAndRunBuildTasks() {
       'WeakSet',
       'Event',
       'Image', // Used by browser to generate notifications
+      'fetch', // Used by browser to generate notifications
```
Comment (weizman) [inline development/build/index.js:117]: remove this line once https://github.com/MetaMask/metamask-extension/pull/24631#discussion_r1610277269 is fixed

Comment (weizman) [reply development/build/index.js:117]: ACTUALLY - applying the idea behind this PR to the `Image` exception as well could be very beneficial, as Image is also a very strong capability

File: app/scripts/use-snow.js (hunk 3 above)
Comment (danjm) [reply app/scripts/use-snow.js:27]: Will do. Can you explain that suggestion a bit? I am still building up my understanding of how scuttiling works, and I suspect your suggestion here is meaningful and I could learn something by hearing your thoughts on this suggestion

Comment (weizman) [reply app/scripts/use-snow.js:27]: Yes of course, gladly.
"Unscuttled" is correct, because it is in fact going to be exempt from the scuttling process.
But it's not accurate enough, because "Unscuttled" really reminds something that is being completely over looked, which isn't the case here.
`fetch` is going to be "Unscuttled" only because we promise to tame it - that is the only legitimate excuse for excepting it from being scuttled.
That is why I think referring to it as tamed rather than unscuttled is important here - so it's clear that we mutated it in order to justify it from not being scuttled.

File: app/scripts/use-snow.js (hunk 1 above)
Comment (danjm) [reply app/scripts/use-snow.js]: removed with 1dd34f9af5

File: app/scripts/use-snow.js (hunk 2 above)
Comment (danjm) [reply app/scripts/use-snow.js]: done in 1dd34f9af5

File: app/scripts/use-snow.js (hunk 3 above)
Comment (danjm) [reply app/scripts/use-snow.js]: done in 1dd34f9af5

File: app/scripts/use-snow.js (hunk 4 above)
Comment (danjm) [reply app/scripts/use-snow.js]: done in 1dd34f9af5

File: app/scripts/use-snow.js (hunk 5 above)
Comment (danjm) [reply app/scripts/use-snow.js]: addressed in b769e71328

**Review by DDDDDanica — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]

**Comment by danjm** [comment]
An issue for further investigation into the root cause of the problem this PR addresses is here https://github.com/MetaMask/metamask-extension/issues/24759

**Review by weizman — APPROVED** [review]
