### PR TITLE
Fix permissions connect close and redirect behavior

### LINKED ISSUE #8741: The connect screen indicates failure if identical permissions are approved
If a domain already has permissions, and those same permissions are re-approved in the connect screen, the redirect view of that screen indicates failure (`Cancelling...`).

This can happen if a consumer calls `wallet_requestPermissions`, and the user approves the same accounts that are already permitted.

`wallet_requestPermissions` does not take existing permissions into account when it is received, and will overwrite any existing permissions if they are re-approved. This is by design.

### PR DESCRIPTION
**Pull request by rekmarks**
This PR fixes two issues with the `permissions-connect` page behavior:
- Correctly display `Connecting...` and `Cancelling...` in the redirect flow, depending on whether permissions were rejected or approved
  - If a dapp connected with `wallet_requestPermissions` and approved the same accounts, the redirect flow would display the `Cancelling...` message
  - This would happen for two reasons:
    - The `redirecting` component state was incorrectly used as a `prop`
    - If multiple UI instances displayed the confirmation, the logic computing whether permissions were approved or rejected didn't anticipate that the same permissions could be re-approved
- Stop closing the fullscreen UI after rejecting or approving a permissions confirmation
  - If the fullscreen UI displayed a permissions confirmation, it would close when the confirmation was removed (i.e. rejected or approved)
  - Since the fullscreen UI currently as always opened by direct user action, it should _never_ close due to confirmations

Additional changes:
- A bunch of permissions selectors had been put in `selectors/selectors`. They've been moved to `selectors/permissions`.

Fixes #8741

### CODE REVIEW

File: ui/app/pages/permissions-connect/permissions-connect.component.js [hunk 1]
```diff
@@ -135,19 +135,22 @@ export default class PermissionConnect extends Component {
...
     if (requestId) {
-      await rejectPermissionsRequest(requestId)
-
-      if (getEnvironmentType() === ENVIRONMENT_TYPE_FULLSCREEN || getEnvironmentType() === ENVIRONMENT_TYPE_NOTIFICATION) {
+      rejectPermissionsRequest(requestId)
+      if (getEnvironmentType() === ENVIRONMENT_TYPE_NOTIFICATION) {
         window.close()
-      } else if (getEnvironmentType() === ENVIRONMENT_TYPE_POPUP) {
+      } else {
         history.push(DEFAULT_ROUTE)
```
Comment (rekmarks) [inline ui/app/pages/permissions-connect/permissions-connect.component.js:154]: There's no reason to `await` any work in this function, nor for it to be `async`. It makes the fullscreen behavior more responsive, and it doesn't affect the popup.

File: ui/app/pages/permissions-connect/permissions-connect.component.js [hunk 2]
```diff
@@ -99,24 +100,23 @@ export default class PermissionConnect extends Component {
...
+    if (getEnvironmentType() === ENVIRONMENT_TYPE_NOTIFICATION) {
       setTimeout(async () => {
         global.platform.closeCurrentWindow()
-      }, 2000)
-    } else if (getEnvironmentType() === ENVIRONMENT_TYPE_POPUP) {
+      }, 1500)
+    } else if (location.pathname === confirmPermissionPath) {
+      setTimeout(async () => {
+        history.push(DEFAULT_ROUTE)
+      }, 1500)
```
Comment (rekmarks) [inline ui/app/pages/permissions-connect/permissions-connect.component.js:118]: Without this, the fullscreen does not show the redirect flow, and instead just sits on the account selection page until it disappears.

File: ui/app/pages/permissions-connect/permissions-connect.component.js [hunk 3]
```diff
@@ -99,24 +100,23 @@ export default class PermissionConnect extends Component {
...
-        const currentTab = await global.platform.currentTab()
-        global.platform.closeTab(currentTab.id)
-      }, 2000)
-    } else if (getEnvironmentType() === ENVIRONMENT_TYPE_NOTIFICATION) {
+    if (getEnvironmentType() === ENVIRONMENT_TYPE_NOTIFICATION) {
       setTimeout(async () => {
         global.platform.closeCurrentWindow()
-      }, 2000)
-    } else if (getEnvironmentType() === ENVIRONMENT_TYPE_POPUP) {
+      }, 1500)
```
Comment (rekmarks) [inline ui/app/pages/permissions-connect/permissions-connect.component.js:114]: Timeout changed to 1.5s, because 2s feels sluggish.

File: ui/app/pages/permissions-connect/permissions-connect.component.js (hunk 1 above)
Comment (rekmarks) [reply ui/app/pages/permissions-connect/permissions-connect.component.js]: Yeah, that's a scary thought, and it didn't actually make much difference for the fullscreen behavior with the other changes I've made. Reverted.

**Review by Gudahtt — APPROVED** [review]
LGTM!
