### PR TITLE
fix: Fix left-aligned fullscreen UI

### LINKED ISSUE #27593: [Bug]: Main screen top section with currency display component and button icons misaligned
### Describe the bug

The main screen's top section, which includes the currency display component and button icons, appears to be misaligned from the center

### Expected behavior

-

### Screenshots/Recordings

Screenshot 2024-10-02 at 22 33 51

### Steps to reproduce

1. Install extension

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

The Home screen was recently updated to make the overview left-aligned. However the fullscreen UI was not considered, and it ended up looking ugly/broken.

The fullscreen UI has been updated to be centered, as it was before. The Home screen remains left-aligned in the popup.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28218?quickstart=1)

## **Related issues**

Fixes #27593

## **Manual testing steps**

Compare how the Home screen overview looks on the fullscreen UI and the popup. It should be centered on the fullscreen UI, left-aligned on the popup.

### **Before**

Screenshot 2024-10-31 at 11 32 12

### **After**

Screenshot 2024-10-31 at 11 28 35

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/wallet-overview/wallet-overview.js [hunk 1]
```diff
@@ -2,9 +2,19 @@ import React from 'react';
...
+
 const WalletOverview = ({ balance, buttons, className }) => {
+  const overviewClasses = ['wallet-overview'];
+  if (getEnvironmentType() === ENVIRONMENT_TYPE_FULLSCREEN) {
+    overviewClasses.push('wallet-overview-fullscreen');
+  }
+
   return (
-    <div className={classnames('wallet-overview', className)}>
+    <div className={classnames(...overviewClasses, className)}>
```
Comment (DDDDDanica) [inline ui/components/app/wallet-overview/wallet-overview.js:17]: Nit: and optional: we can inline the className as well, unless this is international 🙏🏻 
```
className={classnames(
      'wallet-overview',
      { 'wallet-overview-fullscreen': getEnvironmentType() === ENVIRONMENT_TYPE_FULLSCREEN },
      className
    )}
```

Comment (Gudahtt) [reply ui/components/app/wallet-overview/wallet-overview.js:17]: Good suggestion, that is nicer

Comment (Gudahtt) [reply ui/components/app/wallet-overview/wallet-overview.js]: Done: cf9adf0be7

File: ui/components/app/wallet-overview/wallet-overview.js [hunk 2]
```diff
@@ -2,9 +2,23 @@ import React from 'react';
 import PropTypes from 'prop-types';
 import classnames from 'classnames';
 
+// TODO: Move this function to shared
+// eslint-disable-next-line import/no-restricted-paths
```
Comment (Gudahtt) [inline ui/components/app/wallet-overview/wallet-overview.js:6]: Left this as a TODO to make this easier to back port

**Review by darkwing — APPROVED** [review]
Looks great; thank you for the attention to detail here @Gudahtt !

**Comment by sahar-fehri** [comment]
Thank you @Gudahtt ! 🙏  Looks good!
Sharing for visibility that the left alignment in the extended view was part of the [design](https://www.figma.com/design/aMYisczaJyEsYl1TYdcPUL/Portfolio-View?node-id=4186-130770&node-type=frame&t=47D0nnl5syrJ4pe1-0)

CC @amandaye0h @alfeng6

**Review by sahar-fehri — APPROVED** [review]

**Comment by amandaye0h** [comment]
Am ok with this!
