### PR TITLE
fix: use correct property name for redesign

### LINKED ISSUE #24578: [Bug] Metrics do not show the ui_customization property

### PR DESCRIPTION
**Pull request by pnarayanaswamy**
## **Description**

Fixes the bug where the ui_customization property does not show up in the metrics event.
Also fixed the mapping such that the ui_customization property shows up for the eth_signTypedData as well.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24579?quickstart=1)

## **Related issues**

Fixes: [#24578](https://github.com/MetaMask/metamask-extension/issues/24578)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js [hunk 1]
```diff
@@ -60,6 +60,8 @@ const ETH_METHOD_TO_APPROVAL_TYPE = {
   [EthMethod.PersonalSign]: ApprovalType.PersonalSign,
   [EthMethod.Sign]: ApprovalType.Sign,
   [EthMethod.SignTransaction]: ApprovalType.SignTransaction,
+  // This method does not seem to be available in the EthMethod but supported by the test dapp
+  eth_signTypedData: ApprovalType.EthSignTypedData,
```
Comment (OGPoyraz) [inline app/scripts/lib/createRPCMethodTrackingMiddleware.js:64]: I know it's not introduced your PR but can we use `MESSAGE_TYPE` from `shared/constants/app.ts` and remove `EthMethod` from this file?
In order to do that we must add `eth_signTypedData_v1` into `MESSAGE_TYPE` as well which is totally fine.

Comment (pnarayanaswamy) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js:64]: Also the MESSAGE_TYPE misses eth_signTransaction and eth_signTypedData_v1

Comment (pnarayanaswamy) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js]: done @OGPoyraz

**Review by OGPoyraz — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
Lgtm!

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js (hunk 1 above)
Comment (digiwand) [reply app/scripts/lib/createRPCMethodTrackingMiddleware.js]: Nice! I was confused with what this type in this middleware represented.

I assumed ETH_METHODS since these are coming from the JSON_RPC request and it seems I assumed incorrectly. Thanks for the catch and the fix! cc: @pnarayanaswamy @OGPoyraz 

--- 

side note, though related: I have in my notes to understand more the differences and use-cases for our various transaction-related types. If anyone has more intel into any specifics of these, please share 

Eth Methods - EthMethod
Signatures - SIGNING_METHODS 
Transactions - TransactionType

Approvals - ApprovalType
Confirmations - CONFIRMATION_METHODS
Message - MESSAGE_TYPE

**Review by vinistevam — APPROVED** [review]
