### PR TITLE
fix: Fix types associated with auto lock timer call

### LINKED ISSUE #25119: TypeError: Error in invocation of alarms.create(optional string name, alarms.AlarmCreateInfo alarmInfo, opti...
Sentry Issue: [METAMASK-XA5N](https://metamask.sentry.io/issues/5456488853/?referrer=github_integration)

```
TypeError: Error in invocation of alarms.create(optional string name, alarms.AlarmCreateInfo alarmInfo, optional function callback): Error at parameter 'alarmInfo': Error at property 'delayInMinutes': Invalid type: expected number, found string.
  at AppStateController._resetTimer (app/scripts/controllers/app-state.js:292:29)
  at AppStateController._setInactiveTimeout (app/scripts/controllers/app-state.js:266:10)
  at new AppStateController (app/scripts/controllers/app-state.js:98:10)
  at new MetamaskController (app/scripts/metamask-controller.js:739:31)
  at setupController (app/scripts/background.js:516:16)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by danjm**
## **Description**

We see the following error in sentry
Screenshot from 2024-06-06 15-09-39

The problem occurs when the user sets this field in advanced settings
Screenshot from 2024-06-06 15-24-40

If that field is set to empty, then this code in `/ui/pages/settings/advanced-tab/advanced-tab.component.test.js` would result in setting the background state property to the string `'0'`:
```
 if (autoLockTimeLimitBeforeNormalization === '') {
      this.setState({
        autoLockTimeLimitBeforeNormalization,
        autoLockTimeLimit: DEFAULT_AUTO_LOCK_TIME_LIMIT.toString(),
        lockTimeError: '',
      });
```

This `toString` call was introduced in https://github.com/MetaMask/metamask-extension/pull/19653, but it doesn't seem to be necessary. It also conflicts with the type of the prop that is passed in to initially set this component state property. Also, the `_resetTimer` function in the app-state controller clearly expects this value to be a number.

The fix is to not set this component state value as a string. There are a couple of other type related fixes that are not strictly necessary for fixing the bug, but improve the code.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25109?quickstart=1)

## **Manual testing steps**

1. Go to the page Advanced Settings
2. Set the "Auto-lock timer (minutes)" field to a non-zero integer (1 is best)
3. Wait that many minutes without interacting with MetaMask, you will automatically be locked out
4. Enter your password to unlock MetaMask
5. Go to Advanced Settings
6. Set  the "Auto-lock timer (minutes)" field to empty (delete the number in the field but don't enter anything else) and save it
7. Wait more than a minute, you won't be locked out.
8. Check the service worker console, there will not be an error.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controllers/app-state.js [hunk 1]
```diff
@@ -288,10 +288,12 @@ export default class AppStateController extends EventEmitter {
       return;
     }
 
+    const timeoutToSet = Number(timeoutMinutes);
```
Comment (Gudahtt) [inline app/scripts/controllers/app-state.js:291]: It looks like we're converting this to a number here. But the changes elsewhere in the PR suggest that it should now be expected to be a number already. Could you clarify what type we'd expect this to be?

Comment (Gudahtt) [reply app/scripts/controllers/app-state.js:291]: I'm guessing (based on some further discussion in Slack) that this value could be a number or a string, because we haven't yet written a migration to handle the malformed string values that were persisted in state.

We should add a comment explaining that this is a temporary solution until we can implement a migration, assuming that is correct

Comment (danjm) [reply app/scripts/controllers/app-state.js:298]: comment added in c6614f86cc

File: ui/store/actions.ts [hunk 2]
```diff
@@ -3119,7 +3119,7 @@ export function setShowTokenAutodetectModal(value: boolean) {
   return setPreference('showTokenAutodetectModal', value);
 }
 
-export function setAutoLockTimeLimit(value: boolean) {
+export function setAutoLockTimeLimit(value: number) {
```
Comment (Gudahtt) [inline ui/store/actions.ts:3122]: It looks like this could be invoked with `null` as well

```suggestion
export function setAutoLockTimeLimit(value: number | null) {
```

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by NiranjanaBinoy — APPROVED** [review]

**Review by davidmurdoch — APPROVED** [review]

File: app/scripts/controllers/app-state.js [hunk 3]
```diff
@@ -288,10 +288,19 @@ export default class AppStateController extends EventEmitter {
...
     }
 
+    // This is a temporary fix until we add a state migration.
+    // Due to a bug in ui/pages/settings/advanced-tab/advanced-tab.component.js,
+    // it was possible for timeoutMinutes to be saved as a string, as explained
+    // in PR 25109. `alarms.create` will fail in that case. We are
+    // converting this to a number here to prevent that failure. Once
+    // we add a migration to update the malformed state to the right type,
+    // we will remove this conversion.
+    const timeoutToSet = Number(timeoutMinutes);
```
Comment (davidmurdoch) [inline app/scripts/controllers/app-state.js:298]: Do we have an issue # for the migration task? I want to add a comment to it that this cast should be removed when the migration work is done.

Comment (Gudahtt) [reply app/scripts/controllers/app-state.js:298]: I do not think we have created one yet
