### PR TITLE
fix: activity list improvements when selecting nonevm

### LINKED ISSUE #36361: [EXTENSION] Investigate activity list disappearance on Swap page with Solana
Investigate and fix the issue where the activity list disappears after selecting Solana as the source token on the Swap page. This issue occurs on the Extension in Chrome. The network filter appears incorrect, and no activity items show up. However, if 'All popular networks' is clicked again, the list gets populated.

_Issue created in Slack from a_ [_message_|https://consensys.slack.com/archives/C09GL168BQU/p1758558776164269]_._

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

When a Solana account is selected, EVM swap transactions from the same account group were not showing in the activity list. Additionally, swap transactions were displaying incomplete information like "Swap to" instead of "Swap ETH to USDC".

This PR fixes both issues by:
- Fetching EVM transactions for the account group's EVM address when a non-EVM account is selected
- Using `initialTransaction` instead of `primaryTransaction` for bridge history lookups (matching the behavior of `useTransactionDisplayData`)
- Using `getAllNetworkTransactions` in the swap details page so transactions can be found regardless of which account is selected

## **Changelog**

CHANGELOG entry: Fixed swap transactions not appearing in activity list when Solana account is selected

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36361

## **Manual testing steps**

1. Create or use an account group that has both an EVM account and a Solana account
2. Do a swap from the EVM account (e.g. ETH to USDC on Base)
3. Switch to the Solana account in the same group
4. Go to the Activity tab
5. Verify the swap transaction appears with correct info (e.g. "Swap ETH to USDC")
6. Click on the swap transaction
7. Verify the swap details page shows all information (status, timestamp, amounts, gas fee, nonce)

### **Before**

https://github.com/user-attachments/assets/b514adc4-1054-4541-a481-b865f602d5b5

### **After**

https://github.com/user-attachments/assets/3e65c6eb-bb5c-4b4d-8134-1ca2dc6fa06e

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Shows EVM swap/smart transactions from the account group when a non‑EVM account is selected and fixes bridge/swap details by using initialTransaction and querying all-network transactions.
> 
> - **Activity list (unified)**:
>   - Fetch and display EVM swaps/smart txs for the account group's EVM address when a non‑EVM account is selected, using `getAllNetworkTransactions` and `smartTransactions` with nonce grouping via `groupAndSortTransactionsByNonce` and `PENDING_STATUS_HASH` filtering.
>   - Exclude `incoming` type, dedupe against smart tx nonces, and filter by enabled networks across namespaces.
>   - Maintain unified list with non‑EVM items; render smart transactions via `SmartTransactionListItem`.
> - **Bridge/Swap display data**:
>   - Switch bridge history lookups and token display fields to `initialTransaction`.
> - **Tx details page**:
>   - Use `getAllNetworkTransactions` to locate `src`/approval txs so details load regardless of selected account.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit d31df264748ab9322f45b123c0e902dfa62a444c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by micaelae — DISMISSED** [review]

**Review by micaelae — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]

**Review by micaelae — APPROVED** [review]

File: ui/components/app/transaction-list/unified-transaction-list.component.js [hunk 1]
```diff
@@ -429,18 +437,115 @@ export default function UnifiedTransactionList({
...
+
+  const unfilteredCompletedTransactionsAllChains = useMemo(() => {
+    if (needsGroupEvmTransactions) {
+      const smartTxs = smartTransactions ?? [];
+      const smartTxNonces = new Set(
+        smartTxs.map((tx) => tx.txParams?.nonce).filter((n) => n !== undefined),
+      );
+
+      const evmTxs = [...allTransactions, ...smartTxs]
+        .filter((tx) => tx.txParams?.from?.toLowerCase() === groupEvmAddress)
```
Comment (n3ps) [inline ui/components/app/transaction-list/unified-transaction-list.component.js:529]: nit: maybe this should be just one `.filter`

**Comment by n3ps** [comment]
Will all these filtering and massaging of data, ideally should be done at the API level

**Review by n3ps — APPROVED** [review]
