### PR TITLE
fix: prevents unintended second redirection to activity tab

### LINKED ISSUE #31341: [Bug]: Every time when tx is confirmed the extension switches to the Activity tab
### Describe the bug

Every time when tx is confirmed (probably any tx status update) the extension automatically switches to the Activity tab

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/d847900b-d605-45bf-83fc-a8fb078583c8

### Steps to reproduce

1. Submit tx
2. Start another transaction / stay on token list 

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

12.15.0-beta.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

Users reported that 'every time when tx is confirmed (probably any tx status update) the extension automatically switches to the Activity tab'. The bridge experience + snap flow is redirecting users to the activity tab twice, so we avoid navigation at the end of the bridge hook if it is within the Solana experience, to avoid this behavior. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31822?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/31341

## **Manual testing steps**

1. Swap on Solana
2. Get redirected to the activity tab
3. Before the transaction shows up, navigate away
4. Observe that you are not pulled back to the Activity tab.

### **Before**

https://github.com/user-attachments/assets/e61c07c8-22d1-43b5-b0ed-ac5c8fd642d6

### **After**

https://github.com/user-attachments/assets/709ee0e0-515a-45d6-aa03-c42927325b41

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by micaelae — APPROVED** [review]

File: ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts [hunk 1]
```diff
@@ -241,10 +241,15 @@ export default function useSubmitBridgeTransaction() {
...
     // Route user to activity tab on Home page
     await dispatch(setDefaultHomeActiveTabName('activity'));
-    history.push({
-      pathname: DEFAULT_ROUTE,
-      state: { stayOnHomePage: true },
-    });
+    // Only redirect to activity tab if not on Solana
+    // This avoids an unintended side effect where the user is redirected to the activity tab
+    // after already being redirected from a different flow.
+    if (!isSolana) {
```
Comment (GustavoRSSilva) [inline ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts:247]: We should also add the `await dispatch(setDefaultHomeActiveTabName('activity'));` to the if condition

**Review by GustavoRSSilva — APPROVED** [review]
