### PR TITLE
fix: Redesign Signature Message date values

### LINKED ISSUE #27137: [Bug]: Expiration and deadline dates in redesigned signatures
### Describe the bug

In Redesigned Signatures:
- Expiration and deadline dates are set to 1970
- Non-expiration dates are not supported. When value is -1 per EIP-2612 spec, date shows as 31 December 1969 
- No support for 'expiry' param dates

### Expected behavior

- Dates should represent dates as inputted 
- Date should handle non-expiry date
- We should display date for 'expiry' params date 

### Screenshots/Recordings

Screenshot 2024-09-12 at 20 00 21

https://github.com/user-attachments/assets/c48c59d5-1e7c-41a6-82bb-b0b65dec927f

### Steps to reproduce

1. Trigger signature permit

### Error messages or log output

```shell
No errors
```

### Detection stage

During release testing

### Version

v12.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

Fix date values:
- Formerly, conversations were converting values as if they were milliseconds. However, these values come from Solidity where these timestamps are unix timestamps in seconds. 
- Support -1 (no expiration) value 
- Display "expiry" as a date instead of a unix timestamp

This PR fixes the conversion.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27249?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27137

## **Manual testing steps**

1. Go to test-dapp
2. Request Permit or another TypedSign request
3. Observe deadlines and dates

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/helpers/utils/util.js [hunk 1]
```diff
@@ -39,13 +39,17 @@ export function formatDate(date, format = "M/d/y 'at' T") {
...
+ */
+export const formatUTCDateFromUnixTimestamp = (unixTimestamp) => {
+  if (!unixTimestamp) {
+    return unixTimestamp;
   }
 
-  return DateTime.fromMillis(dateInMillis)
-    .setZone('utc')
+  return DateTime.fromSeconds(unixTimestamp)
+    .toUTC()
```
Comment (digiwand) [inline ui/helpers/utils/util.js:52]: `.toUTC()` is equivalent to `.setZone('utc')`

**Review by pedronfigueiredo — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
