### PR TITLE
fix: token name sort 

### LINKED ISSUE #31235: [Bug]: Firefox Sort Alphabetically does not work as expected and is not aligned with Chrome
### Describe the bug

When using the _Sort Alphabetically_  option on Firefox, the token list is not sorted alphabetically in the Current network or Popular networks view and it is not aligned with Chrome.

### Expected behavior

_Sort Alphabetically_  option on Firefox to sort the tokens alphabetically, as it does on Chrome.

_Sort by Declining balance_ option on Firefox works as expected.

### Screenshots/Recordings

https://github.com/user-attachments/assets/3bf2356e-47b2-4409-ba21-a60eca23bb69

https://github.com/user-attachments/assets/951c11e7-81ab-40ae-8acf-9e7f2b4dbc8a

Image
Image
Image
Image

### Steps to reproduce

1. Install MM on Firefox
2. Click on _Sort by Alphabetically (A-Z)_
3. Notice tokens are not sorted

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.15.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

We recently decided that we wanted to sort by token name, rather than symbol. The problem is that native tokens for several chains display `Ethereum` when in actuality the name we get from the token API is something like `Linea`. This would cause native tokens on some EVM chains to be miscategorized in sort.

This PR overrides the token name for this scenario. It also consolidates the `name` and `title` fields to support both EVM and nonEVM chains.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31302?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/31235

## **Manual testing steps**

1. Please test on both flask and non flask builds.
2. EVM and Solana tokens should now be sorted by their display name (not symbol)
3. Check on both firefox and chrome

### **Before**

Before scenarios in bug ticket linked.

### **After**

Chrome:

Screenshot 2025-03-25 at 12 58 45 PM
Screenshot 2025-03-25 at 1 01 00 PM

Firefox:

Screenshot 2025-03-25 at 1 07 11 PM

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/token-list/token-list.tsx [hunk 1]
```diff
@@ -58,24 +58,17 @@ function TokenList({ onTokenClick }: TokenListProps) {
...
     return sortAssets([...filteredAssets], tokenSortConfig);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [
     isEvm,
     evmBalances,
     multichainAssets,
     networkFilter,
     currentNetwork.chainId,
     tokenSortConfig,
+    // newTokensImported included in deps, but not in hook's logic
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/token-list/token-list.tsx:71]: TY for this comment. Interesting we still need this for the useMemo

File: ui/selectors/assets.ts [hunk 2]
```diff
@@ -138,6 +139,14 @@ export const getTokenBalancesEvm = createDeepEqualSelector(
             balance !== '0' ||
             (token.isNative && isOnCurrentNetwork)
           ) {
+            // title is used for sorting. We override native ETH to Ethereum
```
Comment (Prithpal-Sooriya) [inline ui/selectors/assets.ts:142]: TY for comment.
Gosh all these small edge cases feel really prickly - I don't know of a nice way immediately to improve this.

**Review by Prithpal-Sooriya — APPROVED** [review]

File: ui/components/app/assets/token-list/token-list.tsx (hunk 1 above)
Comment (gambinish) [reply ui/components/app/assets/token-list/token-list.tsx:71]: We might not. I just left it but it as it might be worth it to check if this is actually doing anything

File: ui/selectors/assets.ts (hunk 2 above)
Comment (gambinish) [reply ui/selectors/assets.ts:142]: A few steps I've considered:

1. Ask Token API team to handle this override at the API layer (shouldn't it actually be `Ether` anyway?)
2. Eventually migrate the evm token data to the multichain state. This sounds hard, but would make things way more consistent

Comment (Prithpal-Sooriya) [reply ui/selectors/assets.ts:142]: Nice ideas, I really vibe with the 1st point (override or additional properties at the API layer).
The second point is a bit of a unknown to me, I might catchup with you to explain this to me 😄

**Comment by Prithpal-Sooriya** [comment]
Tested solana accounts, happy with this change

File: ui/components/app/assets/asset-list/sort-control/sort-control.tsx [hunk 3]
```diff
@@ -113,7 +109,7 @@ const SortControl = ({ handleClose }: SortControlProps) => {
         }
         onClick={() =>
           // TODO: consolidate name and title fields in token to avoid this switch
-          handleSort(isEvmSelected ? 'name' : 'title', 'alphaNumeric', 'asc')
+          handleSort('title', 'alphaNumeric', 'asc')
```
Comment (bergarces) [inline ui/components/app/assets/asset-list/sort-control/sort-control.tsx:112]: nit: That TODO comment no longer applies.

**Review by bergarces — APPROVED** [review]
