### PR TITLE
EIP-1559 v2 - small fixes

### LINKED ISSUE #13383: [Bug]: Confirm transaction and edit gas fee popover should not show loader when loading gas estimates for DAPP suggested or advance estimates
### Describe the bug

Confirm transaction screen has loading effect implemented to be shown when gas estimates are loading, this can be avoided if estimate used by the user is not one if - low / medium / high.

This can be removed from advance gas option on edit gas fee modal also.

### Steps to reproduce

1. Go to confirm transaction page for a transaction with DAPP suggested gas values
2. Loader will be visible on the modal when estimates are loading

### Error messages or log output

_No response_

### Version

10.8.2

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #13383

Explanation:  PR has small fixes for 1559 V2 implementation

1. Loader to show up only for low / medium / high estimates
2. Correction in cancel / speedup gas calculation on edit gas fee popover

### CODE REVIEW

File: ui/components/app/gas-details-item/gas-details-item.js [hunk 1]
```diff
@@ -32,14 +32,16 @@ const GasDetailsItem = ({ userAcknowledgedGasMissing = false }) => {
     return null;
   }
 
+  const loader = <LoadingHeartBeat estimateUsed={estimateUsed} />;
```
Comment (brad-decker) [inline ui/components/app/gas-details-item/gas-details-item.js:35]: [Q] What benefit does it serve assigning this to a variable vs having 3 instances of the component? genuinely curious, no changes are required.

**Review by brad-decker — DISMISSED** [review]

File: ui/components/app/gas-details-item/gas-details-item.js (hunk 1 above)
Comment (jpuri) [reply ui/components/app/gas-details-item/gas-details-item.js]: Done 👍

**Review by NiranjanaBinoy — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]

**Comment by brad-decker** [comment]
:shipit:
