### PR TITLE
fix:  Show correct origins when snaps use `wallet_requestSnaps`

### LINKED ISSUE #2611: Unblock `wallet_requestSnaps`
Unblock `wallet_requestSnaps` and fix any issues on the extension frontend with showing Snaps as the install origin.

From quick testing we need to address a couple things to handle gracefully showing Snap IDs (and icons) instead of strictly dapp origins. 
image

image

### PR DESCRIPTION
**Pull request by hmalik88**
## **Description**

Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:
1. What is the reason for the change? We are allowing `wallet_requestSnaps` to be called by other snaps and needed to update the UI to correctly show the snap origin.
2. What is the improvement/solution? There needed to be some UI changes to accommodate the above.

## **Related issues**

Fixes https://github.com/MetaMask/snaps/issues/2611

### **Before**

image
image

### **After**

https://github.com/user-attachments/assets/e47a092b-7f66-4cb8-9039-8600821475da

**NOTE:** The copy was updated to "Connected Snaps" and "Connected sites and Snaps".

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js [hunk 1]
```diff
@@ -57,7 +57,11 @@ export default function SnapsConnect({
   const snaps = getDedupedSnaps(request, currentPermissions);
 
   const SnapsConnectContent = () => {
-    const { hostname: trimmedOrigin } = useOriginMetadata(origin) || {};
+    let trimmedOrigin = (useOriginMetadata(origin) || {})?.name;
+
+    if (origin?.startsWith('local:') || origin?.startsWith('npm:')) {
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js:62]: Feels like we should have a utility function for this in `snaps-utils`, Maarten was adding one here: https://github.com/MetaMask/snaps/pull/2634/files#diff-ef92bcefb67c52b36ad3e20af33cd46bcbd08d2ab94fd2bc6421ea2838634366R317-R319

Comment (hmalik88) [reply ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js:62]: I can duplicate that function here in the extension and we can replace it once we get that into a release

Comment (FrederikBolding) [reply ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js:62]: Makes sense 👍

Comment (hmalik88) [reply ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js]: Done: [7aef11b](https://github.com/MetaMask/metamask-extension/pull/26715/commits/7aef11b5b8a61a3dd5f96a37ee9071409f739c05)

File: ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js [hunk 2]
```diff
@@ -57,7 +58,11 @@ export default function SnapsConnect({
   const snaps = getDedupedSnaps(request, currentPermissions);
 
   const SnapsConnectContent = () => {
-    const { hostname: trimmedOrigin } = useOriginMetadata(origin) || {};
+    let trimmedOrigin = (useOriginMetadata(origin) || {})?.name;
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js:61]:
```suggestion
    let trimmedOrigin = (useOriginMetadata(origin) || {})?.hostname;
```

We used hostname before, should we not keep that?

Comment (hmalik88) [reply ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js]: Good catch, that was unintended. Fixed here: [19e8182](https://github.com/MetaMask/metamask-extension/pull/26715/commits/19e8182ef6a0e7f597547c40799d825b47ab3de1)

**Review by FrederikBolding — DISMISSED** [review]
LGTM - but please update the PR title to be more accurate to the changes in the PR!

File: ui/pages/snaps/snap-view/snap-settings.js [hunk 3]
```diff
@@ -52,6 +52,7 @@ import SnapUpdateAlert from '../../../components/app/snaps/snap-update-alert';
 import { CONNECT_ROUTE } from '../../../helpers/constants/routes';
 import { ShowMore } from '../../../components/app/snaps/show-more';
 ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
+import { isSnapId } from '../../../helpers/utils/snaps';
```
Comment (FrederikBolding) [inline ui/pages/snaps/snap-view/snap-settings.js:55]: Oop, looks like a fencing problem here is preventing green CI

File: ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js [hunk 4]
```diff
@@ -57,7 +58,11 @@ export default function SnapsConnect({
   const snaps = getDedupedSnaps(request, currentPermissions);
 
   const SnapsConnectContent = () => {
-    const { hostname: trimmedOrigin } = useOriginMetadata(origin) || {};
+    let trimmedOrigin = (useOriginMetadata(origin) || {})?.hostname;
+
+    if (isSnapId(origin)) {
+      trimmedOrigin = targetSubjectMetadata.name;
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js:64]: Hmm, should this be using the localized Snaps metadata name instead?

File: ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js [hunk 5]
```diff
@@ -161,7 +163,11 @@ export const SnapMetadataModal = ({ snapId, isOpen, onClose }) => {
                   </Tooltip>
                 )}
               </Box>
-              <Text ellipsis>{installOrigin.host}</Text>
+              <Text ellipsis>
+                {isSnapRequesting
+                  ? stripSnapPrefix(installInfo.origin)
```
Comment (FrederikBolding) [inline ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js:168]: Hmm, should this be using the localized Snaps metadata name instead?

File: ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js (hunk 4 above)
Comment (hmalik88) [reply ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js]: Makes sense, done: [3ed97f6](https://github.com/MetaMask/metamask-extension/pull/26715/commits/3ed97f6012dd19dd40833da80444eb980477c12c)

**Review by FrederikBolding — APPROVED** [review]

File: ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js [hunk 6]
```diff
@@ -57,7 +58,12 @@ export default function SnapsConnect({
   const snaps = getDedupedSnaps(request, currentPermissions);
 
   const SnapsConnectContent = () => {
-    const { hostname: trimmedOrigin } = useOriginMetadata(origin) || {};
+    let trimmedOrigin = (useOriginMetadata(origin) || {})?.hostname;
+    const { name } = useSelector((state) => getSnapMetadata(state, origin));
```
Comment (FrederikBolding) [inline ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js:62]: Hmm, this hook is a bit problematic since it'll crash when `origin` is not a Snap.

File: ui/pages/snaps/snap-view/snap-settings.js [hunk 7]
```diff
@@ -129,6 +130,15 @@ function SnapSettings({ snapId, initRemove, resetInitRemove }) {
     }
   };
 
+  const connectedTitle = () => {
```
Comment (FrederikBolding) [inline ui/pages/snaps/snap-view/snap-settings.js:133]: We still aren't showing icons or the proper names for Snaps in this list.

image

**Review by FrederikBolding — CHANGES_REQUESTED** [review]

File: ui/pages/snaps/snap-view/snap-settings.js (hunk 7 above)
Comment (hmalik88) [reply ui/pages/snaps/snap-view/snap-settings.js:133]: Oh I didn't realize we wanted to show the snap name, I thought it was supposed to be just the id? As far as the icon, is this supposed to be a snap provided icon and fallback is the snaps logo?

File: ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js (hunk 6 above)
Comment (hmalik88) [reply ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js]: [736aebd](https://github.com/MetaMask/metamask-extension/pull/26715/commits/736aebd8d8930f97f908ffcd0c51c44e35bd2852)

File: ui/pages/snaps/snap-view/snap-settings.js (hunk 7 above)
Comment (FrederikBolding) [reply ui/pages/snaps/snap-view/snap-settings.js:133]: Lets just use `SnapIcon` which has a fallback already!

Comment (hmalik88) [reply ui/pages/snaps/snap-view/snap-settings.js:133]: Done!

**Review by FrederikBolding — APPROVED** [review]

**Review by david0xd — APPROVED** [review]
