### PR TITLE
fix: fix contact case

### LINKED ISSUE #32086: [Bug]: GNS UI DEPENDENCY testing plan: Selecting a contact during the Send flow does not clear when switching networks
### Describe the bug

During the Send flow, if I select a contact as recipient and:

- switch networks to a network with different contacts, I can still see the original contact as recipient
- switch networks to a network without contacts, I can still see the original contact as recipient (in the TO field).

### Expected behavior

The recipient field be reset when switching networks, and not show the initially selected contact.

### Screenshots/Recordings

[Loom video](https://www.loom.com/share/a09c04251d94486186551af0471bc471) 

### Steps to reproduce

1. Add contacts on various networks
2. Start send flow
3. Select a contact 
4. Switch networks
5. Notice the recipient field is always displaying the initial contact 

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

12.15.2

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

QA Build

### Severity

_No response_

### LINKED ISSUE #33738: [Bug]: [Remove GNS] Send flow shows Select network instead of custom network name
### Describe the bug

During the send flow, if the network is switched to a custom network, the network picker is indicating Select Network instead of the actual network name.
On some custom networks, assets show as `null`

### Expected behavior

Network name instead of Select Network and `0` instead of `null`

### Screenshots/Recordings

https://www.loom.com/share/98383a767d794e74b488d0d832c9434c?sid=acfeb6ef-ee26-4847-bf22-686cb9776be5

### Steps to reproduce

1. Add some custom networks
2. Click Send
3. Switch networks to a custom network

### Error messages or log output

```shell
https://www.loom.com/share/98383a767d794e74b488d0d832c9434c?sid=1dbe480f-d271-4a18-8b1a-50a21a7b1c9d
```

### Detection stage

On a feature branch

### Version

12.18.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

this PR is a bug fix for the the 2 bugs below

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34234?quickstart=1)

## **Related issues**

Fixes: #32086 #33738 

## **Manual testing steps**

1. Go to send flow
2. select contact
3. switch network

### **After**

https://github.com/user-attachments/assets/5204f365-b263-489f-a741-0ffcd126444d

https://github.com/user-attachments/assets/5bdd9705-d715-4e54-a8e6-b9c5f63a45ae

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx [hunk 1]
```diff
@@ -265,6 +278,14 @@ export const AssetPickerAmount = ({
                           : networkConfig.chainId,
                       ),
                     );
+
+                    const contact = contacts.find((item) => {
+                      return item.address === recipient.address;
+                    });
+
+                    if (contact && contact.chainId !== networkConfig.chainId) {
```
Comment (darkwing) [inline ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx]: Can this check be added to the `find` above?

Comment (Prithpal-Sooriya) [reply ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx]: 2 nits/comments:

1. Can shove the `contact.chainId !== networkConfig.chainId` inside our `.find`? (I think we can stick with a `.some` to reduce it to a boolean primitive)
2. Debating if we should move this out of JSX... What is nice about keeping it in here is that we only compute when `onNetworkChange` is called.

```tsx
// Feel free to rename this, or we can add a comment on why this condition is important.
// A unit test would be nice if poss.
const shouldUpdateRecipient: boolean = useMemo(() => {
  return contacts.some(item => {
    return item.address === recipient.address && item.chainId !== networkConfig.chainId
  })
}, [...])

...

if(shouldUpdateRecipient) {
  dispatch(updateRecipient({ address: '', nickname: '' }));
}
```

**Review by NidhiKJha — DISMISSED** [review]

**Comment by darkwing** [comment]
Functionally this worked well

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
