### PR TITLE
Fix #19829: UX: Multichain: Move "Import Tokens" to Modal

### LINKED ISSUE #19829: UX: Convert Import Tokens from Page to Modal
### Describe the bug

At present the Import Tokens functionality is a "page", but within the new UI, it should be a new Design System `Modal`.

### Steps to reproduce

N/A

### Error messages or log output

_No response_

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

To make the Import process more visually appealing, we're moving this functionality into a popover.

* Depends on: https://github.com/MetaMask/metamask-extension/pull/19857
* Fixes: https://github.com/MetaMask/metamask-extension/issues/19829
* Fixes: https://github.com/MetaMask/MetaMask-planning/issues/703

## Screenshots/Screencaps
Coming soon.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/multichain/import-tokens-popover/import-tokens-popover.js [hunk 1]
```diff
@@ -0,0 +1,697 @@
...
+      onClose={() => {
+        dispatch(clearPendingTokens());
+        onClose();
+      }}
+      centerTitle
+      title={t('importTokensCamelCase')}
+      className="import-tokens-popover"
+    >
+      {isConfirming ? (
+        <Box padding={[0, 6, 6, 6]}>
```
Comment (georgewrmarshall) [inline ui/components/multichain/import-tokens-popover/import-tokens-popover.js:427]: Is this intended to be responsive padding? If it's each side it will need to be listed out as `paddingTop={4} paddingRight={6} paddingBottom={4} paddingLeft={4}`. Array props syntax were updated to be used for responsive props so you could change the padding at different viewports without need the mixins or media queries

File: ui/components/multichain/import-tokens-popover/import-tokens-popover.scss [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+      border-bottom: 0;
+    }
+
+    li {
+      width: 50%;
+    }
+  }
+
+  &__search-list {
+    max-width: 260px;
```
Comment (georgewrmarshall) [inline ui/components/multichain/import-tokens-popover/import-tokens-popover.scss:15]: static pixel values are a red flag for me because it prevents responsiveness in some cases, does this still work if it's 
```suggestion
    max-width: 100%;
```

File: ui/components/multichain/import-tokens-popover/import-tokens-popover.stories.js [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+  title: 'Components/Multichain/ImportTokensPopover',
+  component: ImportTokensPopover,
+  argTypes: {
+    onClose: {
+      action: 'onClose',
+    },
+  },
+  args: {
+    closeMenu: () => console.log('Closing popover!'),
+  },
```
Comment (georgewrmarshall) [inline ui/components/multichain/import-tokens-popover/import-tokens-popover.stories.js:29]: I think this can be removed? onClose is covered in the actions tab


Screenshot 2023-06-26 at 1 36 11 PM

File: ui/components/multichain/import-tokens-popover/import-tokens-popover.stories.js [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+export const DefaultStory = (args) => <ImportTokensPopover {...args} />;
+DefaultStory.decorators = [
+  (Story) => (
+    <Provider store={store}>
+      <Story />
+    </Provider>
+  ),
+];
+
+DefaultStory.storyName = 'Default';
```
Comment (georgewrmarshall) [inline ui/components/multichain/import-tokens-popover/import-tokens-popover.stories.js:41]: Some really valuable stories here would be to mock state so it shows the confirmations state and that we get a mock list of tokens to import?

**Review by georgewrmarshall — COMMENTED** [review]
Looking really good! Made a few small suggestions. Would it be possible to change the file name and component to `import-token-modal` ImportTokenModal. I think we want to start moving away from the popover terminology and use `Modal` Take these requests with a grain of salt because I don't have full understanding of your resources and timeframe but it would be cool if all UI PRs could
- Replace deprecated code and components to help reduce tech debt
- Have stories for all states of the component so they are easy to review

File: ui/components/multichain/import-tokens-popover/import-tokens-popover.js [hunk 5]
```diff
@@ -0,0 +1,695 @@
...
+    <Popover
+      onBack={isConfirming ? () => setMode('') : null}
+      onClose={() => {
+        dispatch(clearPendingTokens());
+        onClose();
+      }}
+      centerTitle
+      title={t('importTokensCamelCase')}
+      className="import-tokens-popover"
+    >
```
[the remark this answers is not in the document]
Comment (darkwing) [reply ui/components/multichain/import-tokens-popover/import-tokens-popover.js]: Done!

**Review by NidhiKJha — COMMENTED** [review]
Looking really great. 
Just a question. Are we removing the icon?
### Before
Screenshot 2023-06-28 at 6 44 29 PM
### After
Screenshot 2023-06-28 at 6 44 10 PM

**Comment by NidhiKJha** [comment]
Do we want the header to be fixed while scroll, I think in that case it should be fixed in the top, wdyt?

https://github.com/MetaMask/metamask-extension/assets/39872794/9ba906ce-6d8e-4983-8d85-0fbfb13fd4ca

File: ui/components/multichain/import-tokens-modal/import-tokens-modal.js [hunk 6]
```diff
@@ -0,0 +1,633 @@
...
+              setMode('');
+            }}
+            onImportClick={async () => {
+              await handleAddTokens();
+              onClose();
+            }}
+          />
+        ) : (
+          <>
+            <Tabs t={t}>
```
Comment (NidhiKJha) [inline ui/components/multichain/import-tokens-modal/import-tokens-modal.js:439]: We need to have a margin-top here. As per design, I think it should be 24px
Screenshot 2023-08-01 at 10 29 46 PM

File: ui/components/multichain/import-tokens-modal/import-tokens-modal.js [hunk 7]
```diff
@@ -0,0 +1,633 @@
...
+                            <ButtonLink
+                              key="token-detection-announcement"
+                              onClick={() => {
+                                history.push(
+                                  `${SECURITY_ROUTE}#token-description`,
+                                );
+                                onClose();
+                              }}
+                            >
+                              {t('enableFromSettings')}
```
Comment (NidhiKJha) [inline ui/components/multichain/import-tokens-modal/import-tokens-modal.js:457]: Seems like this link is not working properly
https://github.com/MetaMask/metamask-extension/assets/39872794/8ef2b801-656a-446c-9d92-74a519062bd1

File: ui/components/multichain/import-tokens-modal/import-tokens-modal.js [hunk 8]
```diff
@@ -0,0 +1,633 @@
...
+              </Tab>
+            </Tabs>
+            <Box padding={6}>
+              <ButtonPrimary
+                onClick={() => handleNext()}
+                disabled={Boolean(hasError()) || !hasSelected()}
+                block
+              >
+                {t('next')}
+              </ButtonPrimary>
```
Comment (NidhiKJha) [inline ui/components/multichain/import-tokens-modal/import-tokens-modal.js:622]: Button size should be LG for modals right @SaraCheikh ?
```suggestion
              <ButtonPrimary
                size={Size.LG}
                onClick={() => handleNext()}
                disabled={Boolean(hasError()) || !hasSelected()}
                block
              >
                {t('next')}
              </ButtonPrimary>
```

**Review by NidhiKJha — COMMENTED** [review]
Looks really good. Just left some comments

**Comment by darkwing** [comment]
Addressed all feedback @NidhiKJha !

File: ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.js [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+import Identicon from '../../ui/identicon';
+import { useI18nContext } from '../../../hooks/useI18nContext';
+import { getPendingTokens } from '../../../ducks/metamask/metamask';
+
+export const ImportTokensModalConfirm = ({ onBackClick, onImportClick }) => {
+  const t = useI18nContext();
+  const pendingTokens = useSelector(getPendingTokens);
+
+  return (
+    <Box padding={4}>
```
Comment (NidhiKJha) [inline ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.js:27]: We need to change it to only padding top and bottom. Since, paddingLeft and paddingRight is extra padding to the box
```suggestion
    <Box paddingTop={4} paddingBottom={4}>
```
Screenshot 2023-08-02 at 5 43 10 PM

**Review by NidhiKJha — COMMENTED** [review]
Looking great! Just need to fix a couple of padding issues and we are good to go.

**Review by Ameralameri — APPROVED** [review]
Approv

File: ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.js (hunk 9 above)
Comment (darkwing) [reply ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.js:27]: Set!

File: ui/components/multichain/import-tokens-modal/import-tokens-modal.js [hunk 10]
```diff
@@ -0,0 +1,637 @@
...
+              await handleAddTokens();
+              onClose();
+            }}
+          />
+        ) : (
+          <>
+            <Tabs t={t} marginTop={6}>
+              {showSearchTab ? (
+                <Tab tabKey="search" name={t('search')}>
+                  <Box padding={4}>
```
[the remark this answers is not in the document]
Comment (darkwing) [reply ui/components/multichain/import-tokens-modal/import-tokens-modal.js:443]: Good find!

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by NidhiKJha — CHANGES_REQUESTED** [review]
The import Token screen looks beautiful. Just two suggestions:

1. I think there is a little shift between the line-height of the text and the link. The link looks slightly lower

Screenshot 2023-08-03 at 5 29 41 PM

2. For confirm import Tokens, if the name of the token is too long, it overflows.

Screenshot 2023-08-03 at 5 25 23 PM

**Review by NidhiKJha — DISMISSED** [review]
LGTM!

**Review by vthomas13 — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

**Review by NidhiKJha — COMMENTED** [review]
Nit: We should add a padding of 24px between modal title Import Tokens and the tabs and same for confirm import token 

Screenshot 2023-08-04 at 12 18 39 AM

**Review by NidhiKJha — DISMISSED** [review]

**Review by NidhiKJha — APPROVED** [review]
Looks great! Just a nonblocking nit. We need to remove extra padding-left and padding-right on the custom-import tab.



https://github.com/MetaMask/metamask-extension/assets/39872794/324997ef-daab-45f9-af91-abcbfe08ee10

**Review by vthomas13 — APPROVED** [review]

File: test/e2e/tests/add-hide-token.spec.js [hunk 11]
```diff
@@ -108,13 +108,15 @@ describe('Add existing token using search', function () {
         await driver.press('#password', driver.Key.ENTER);
 
         await driver.clickElement({ text: 'Import tokens', tag: 'button' });
-        await driver.fill('#search-tokens', 'BAT');
+        await driver.fill('input[placeholder="Search"]', 'BAT');
```
[the remark this answers is not in the document]
Comment (georgewrmarshall) [reply test/e2e/tests/add-hide-token.spec.js:111]: Missed the cut. Disregard
