### PR TITLE
fix: `Cannot destructure property 'balance' of 'K[Z]' as it is undefined` fromAddress error when no transaction is loaded in ConfirmTransactionBase

### LINKED ISSUE #25406: [Bug]: Multichain - `Cannot destructure property 'balance' of 'K[Z]' as it is undefined.` and  `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`
### Describe the bug

Triggering a transaction on one chain, and without approving it, triggering a signature in another chain, whenever I reject/accept the first transaction, MM breaks with the error `Cannot destructure property 'balance' of 'K[Z]' as it is undefined.`

I've also seen it fail with this other message `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/08d09f66-7072-4847-823b-12c8d76d23aa

https://github.com/MetaMask/metamask-extension/assets/54408225/8a14acda-5864-4da9-aa3c-a48327121142

### Steps to reproduce

1. Connect to the test dapp with Sepolia
2. Connect to pancakeswap with Ethereum
3. Trigger a swap in pancakeswap https://pancakeswap.finance/swap?chain=eth
4. Without accepting/rejecting, go to the test dapp and trigger a signature
5. Reject the first tx
6. See how MM breaks

### Error messages or log output

_No response_

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

In `confirm-transaction-base.container.js`, while the transaction is switching, the component may be in a state without transaction data. In this case, we can handle the empty transaction data appropriately until the expected data comes in to allow the user flow to continue without breaking. 

**note:** I was unable to reproduce this in `develop` after some time, but I successfully repro'd this in `Version-v12.0.0` which allowed me to verify the fix works. Possibly the underlying empty transaction data state was fixed by other code in `develop`

This PR is planned to be cherry-picked for Version-v12.0.0

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25406

## **Manual testing steps**

See [Issue](https://github.com/MetaMask/metamask-extension/issues/25406) for repro steps 

#### Possible, occasional state in `confirm-transaction-base.container.js`
CleanShot 2024-06-25 at 15 58 13@2x

### **Before**

See error in [Issue](https://github.com/MetaMask/metamask-extension/issues/25406) screenshots

### **After**

No error message is shown and app works as expected

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js [hunk 1]
```diff
@@ -173,7 +173,7 @@ const mapStateToProps = (state, ownProps) => {
   const transactionData = parseStandardTokenTransactionData(data);
   const tokenToAddress = getTokenAddressParam(transactionData);
 
-  const { balance } = accounts[fromAddress];
+  const { balance } = accounts[fromAddress] || {};
```
Comment (davidmurdoch) [inline ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js:176]: The defined type for a `Numeric`, where this `balance` value ends up does not allow `undefined`. Can you fix the type or this value?

**Review by davidmurdoch — CHANGES_REQUESTED** [review]

**Comment by sleepytanya** [comment]
@digiwand 
MetaMask now doesn't break with an error but the subsequent transaction is created on the same chain as the previous one.
First scenario from [the bug ticket](https://github.com/MetaMask/metamask-extension/issues/25406):
- Connect to the test dapp with Sepolia
- Connect to dapp with Ethereum
- Trigger a swap in dapp 
- Without accepting/rejecting, go to the test dapp and trigger a signature - _signature request from the test dapp is created on mainnet_


 

https://github.com/MetaMask/metamask-extension/assets/104780023/dbfe256f-350a-4365-9abf-0ece37ec08fd

Error also doesn't appear for this scenario, Connect request is lost, instead of blue numbers there is '...' on the MM icon.
- Connect to test-dapp
- Click button to start legacy send transaction; popup comes up, I see a "1" in the extension icon, I ignore the popup window
- Open new tab, go to Uniswap
- Click "Connect" button, click MetaMask; I see a "2" in the extension icon, no popup occurs
- Click "Connect" button again, click MetaMask; I see a "3" in the extension icon, no popup occurs
- After the first request is rejected and the subsequent request can be accessed MM can break with an error


https://github.com/MetaMask/metamask-extension/assets/104780023/a50eb905-d799-4bdf-b72c-0253e28f08df

Error also doesn't happen for these steps:
- Start send+swap txs with low gas
- Send another (approve) tx from a dapp
- Confirmation is stuck on the spinner
- Activity tab has two txs - Pending and Unapproved
- Unapprovedtxs can't be rejected
- If user rejects first tx MM displays an error Cannot destructure property 'balance' of 'Q[z]' as it is undefined.

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js (hunk 1 above)
Comment (digiwand) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js:176]: thanks David! 

This appears to be a multichain issue after reading what @sleepytanya reported below. And following your comment, I think we should aim to preserve the type here and restore this behavior which expects transaction data

Looking into this some more and will ping the multichain team to see if they have any leads

Comment (darkwing) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js:176]: I don't think anything specific to multichain would cause a `fromAddress` or `transactionData` to go missing.  If those don't exist, I would think the transaction confirmation should just not be rendered.  Could this have something to do with transaction simulation?  Multichain really shouldn't affect anything here.

**Comment by digiwand** [comment]
@sleepytanya I have repro'd the issue on `develop`. We will need to further investigate a fix for this

**Comment by sleepytanya** [comment]
@digiwand @darkwing @bschorchit 
This issue is now resolved across all scenarios we have identified. I will create a separate ticket for the issue with the signature generated on the wrong network.

File: ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js (hunk 1 above)
Comment (digiwand) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js]: interesting. This is something to consider. Ty @darkwing!

as @sleepytanya mentioned below, we will create a separate ticket to investigate this issue further. 

In the meantime, in case we'd like to merge this, I've updated the PR to preserve the `Numeric` state and send an error to Sentry when this issue occurs

Comment (digiwand) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js]: to follow up here, the Wallet UX team found the lingering issue reported below was an expected behavior by how the code was written. Only eth_signTypedData_v4 and personal_sign signatures were set to update to the selected network. Other signature types do not need to enforce the chainId / network in order for the signature to be signed. The plan is to allow other signatures to behave the same as eth_signTypedData_v4 and personal_sign during network switches to adopt consistent UI behavior

Comment (danjm) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js]: has @davidmurdoch's comment regarding the type been addressed?

Comment (digiwand) [reply ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js]: hmm sorry for the confusion and thanks for the comment here! I meant to double-check this.

so the `subtractHexes` and `isBalanceSufficient` methods below expect balance to be a string type. I think setting the value in these cases to `0x0` should be what we expect

**Review by davidmurdoch — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
