### PR TITLE
Disabled button for Import Tokens Modal when no token is selected

### LINKED ISSUE #18392: Import Tokens Modal Allows Importing 0
### Describe the bug

When a new token is detected for a given user, they can click an "Import" link to add them to MetaMask.  The modal allows the user to import 0 tokens if none are selected:

Import

If 0 tokens are selected, the "Import" button should be disabled.

### Steps to reproduce

N/A

### Error messages or log output

_No response_

### Version

10.27

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR fixes #18392 

Currently, When a new token is detected for a given user, they can click an "Import" link to add them to MetaMask. The modal allows the user to import 0 tokens if none are selected. This PR is to disable the Import Button when no token is selected.

### Before 

Screenshot 2023-03-31 at 3 56 12 PM

### After

https://user-images.githubusercontent.com/39872794/229095539-dfa48354-9e93-4031-b28d-62af3761aa5f.mov

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js [hunk 1]
```diff
@@ -62,6 +62,7 @@ const DetectedTokenSelectionPopover = ({
         className="detected-token-selection-popover__import-button"
         type="primary"
         onClick={onImport}
+        disabled={numOfTokensImporting === '(0)'}
```
Comment (darkwing) [inline ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js:65]:
```suggestion
        disabled={selectedTokens.length === 0}
```

**Review by darkwing — DISMISSED** [review]

File: ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js (hunk 1 above)
Comment (NidhiKJha) [reply ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js]: Updated

**Review by vthomas13 — APPROVED** [review]

**Review by arimallick — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
fix looks good to me! Would be nice to add a test for this

**Comment by NidhiKJha** [comment]
> fix looks good to me! Would be nice to add a test for this

Thanks, @digiwand Will do in follow-up PR
