### PR TITLE
fix: set swap src chain based on selected asset cp-13.0.0

### LINKED ISSUE #34483: [Bug]: Swap source network is not set when navigating from other network's asset page
### Describe the bug

When clicking the Swap button from the homepage or asset-page, the Swap page sets the native asset of the previously selected network as the srcToken

### Expected behavior

Src token should be set to the asset navigated from. The chain should be updated as well

### Screenshots/Recordings

https://github.com/user-attachments/assets/eab4eae7-955d-4493-875b-ba6c1c5c8cfd

### Steps to reproduce

1. Go to Swap page and note src network
2. Go back to home page
3. Click on native asset of other network
4. Click Swap
5. The previous network's native asset is set as the src token

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

The Asset overview pages and the useBridging hook use the current selected network to set the native asset when navigating to the Swap page. When the user navigates to the Swap page from portfolio view, the src network is not set correctly if the selected asset is not in the current selected network

Changes
- Remove `defaultSwapsToken` prop from asset/account overview components and only retrieve the value from state as needed (`CoinButtons` and `useBridging`)
- Deprecate `getSwapsDefaultToken` selector since it only supports EVM networks
- `CoinButtons` uses the `getNativeAssetForChainId` util to get the native asset when loading the Swap page
- `useBridging` defaults to the selected network's native asset if not passed in as a parameter

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34385?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34483

## **Manual testing steps**

1. Go to Swap page and note src network
2. Go back to home page
3. Click on native asset of other network
4. Click Swap
5. The asset from step 3 should be set as the src token

## **Screenshots/Recordings**

See recording in linked issue

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/wallet-overview/coin-buttons.tsx [hunk 1]
```diff
@@ -102,6 +101,15 @@ const CoinButtons = ({
   const currentChainId = useSelector(getCurrentChainId);
   const displayNewIconButtons = process.env.REMOVE_GNS;
 
+  const defaultSwapsToken = useSelector((state) =>
+    getSwapsDefaultToken(state, chainId.toString()),
+  );
+
+  // Pre-conditions
+  if (isSwapsChain && defaultSwapsToken === undefined) {
+    throw new Error('defaultSwapsToken is required');
```
Comment (SteP-n-s) [inline ui/components/app/wallet-overview/coin-buttons.tsx:110]: How do we capture this exception from the component? Do we have some sort of `ErrorBoundary`?

Comment (micaelae) [reply ui/components/app/wallet-overview/coin-buttons.tsx:110]: This bubbles up to the extension's ErrorBoundary and shows the default "crash" page. I moved this exception down from the parent component so this doesn't change current behavior

**Review by SteP-n-s — APPROVED** [review]

**Review by ghgoodreau — APPROVED** [review]

**Review by owencraston — APPROVED** [review]
Did not test but the code looks good to me.
