### PR TITLE
fix: Contract interactions cannot confirm a contract interaction with `Ledger` with the new redesign

### LINKED ISSUE #27240: [Bug]: Contract Interactions - Cannot confirm a contract interaction with Ledger with the new redesign
### Describe the bug

Cannot confirm a contract interaction with a ledger account when the redesign is ON. The confirm button is always disabled

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/49fab628-4d51-447c-afb2-e1d0ad6ffca9

### Steps to reproduce

1. Import a ledger account
2. Make sure contract interaction redesign is ON in experimental features
3. Trigger a contract interaction
4. See Confirm button is always disabled

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR fixes the issue where confirm button is always disabled when contract interactions with Ledger account 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27331?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27240

## **Manual testing steps**

1. Activate Ledger account in MM
2. Go to uniswap
3. Try swapping from Sepolia eth to Weth
4. See confirmation "Confirm" button is not disabled

## **Screenshots/Recordings**

https://github.com/user-attachments/assets/aba4e44c-049e-4d64-b14a-9bdc4c25a9cb

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/hooks/useLedgerConnection.ts [hunk 1]
```diff
@@ -22,15 +23,18 @@ import { useConfirmContext } from '../context/confirm';
...
   const transportStatus = useSelector(getLedgerTransportStatus);
   const webHidConnectedStatus = useSelector(getLedgerWebHidConnectedStatus);
 
   let from: string | undefined;
-  // todo: extend to other confirmation types
-  if (currentConfirmation?.msgParams) {
-    from = currentConfirmation.msgParams.from;
+  const confirmationParams =
+    currentConfirmation?.msgParams || currentConfirmation?.txParams;
+  if (confirmationParams) {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useLedgerConnection.ts:36]: Minor, could we avoid the `let` and this `if` and just use two optional chains such as:

`currentConfirmation?.msgParams?.from ?? currentConfirmation?.txParams?.from`

File: ui/pages/confirmations/hooks/useLedgerConnection.ts [hunk 2]
```diff
@@ -22,15 +23,18 @@ import { useConfirmContext } from '../context/confirm';
 
 const useLedgerConnection = () => {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useLedgerConnection.ts:24]: Do these changes warrant a quick unit test?

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/pages/confirmations/hooks/useLedgerConnection.ts (hunk 1 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/hooks/useLedgerConnection.ts]: Done 👍

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Comment by sleepytanya** [comment]
'Confirm' button is active on redesigned transaction confirmations.

Mint ERC20:


https://github.com/user-attachments/assets/5105966d-ce4a-415d-9d7b-1282f5f48640



Deploy Piggy Bank contract:


https://github.com/user-attachments/assets/8cedb51d-bd75-4d44-96bd-6e81c4be550c

File: ui/pages/confirmations/hooks/useLedgerConnection.ts (hunk 2 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/hooks/useLedgerConnection.ts:24]: As this is [rushed into RC](https://consensys.slack.com/archives/C029JG63136/p1727100953238569?thread_ts=1721989273.481959&cid=C029JG63136) I will merge this and handle tests on different PR
