### PR TITLE
Fix batch transaction UX

### LINKED ISSUE #5852: batch transactions appear in wrong order and fail my transactions
**Describe the bug**
when trying to sign a batched transaction, it actually appear in the wrong order on metamask and force nonce that sends the transactions in the wrong order to the blockchain, resulting in a fail transaction due to that.

**To Reproduce**
1. Go to 'https://www.bancor.network/tokens'
2. Click on 'convert'
3. select to execute the transaction using metamask
4. select any pair of tokens to convert (select erc20, not ETH or BNT)
image

5. view the transaction on metamask
image

**Expected behavior**
expected: 1st transaction is "approve", 2nd is the quickconvert 
actual: 1st transaction is quickconvert (should be 2nd), 2nd is "approve" (should be 1st)

**Screenshots**
metamask interface display the transactions in the wrong order (notice order and nonce)
image
image

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - MetaMask Version 5.0.3

**Additional context**
old UI handle the transactions incorrectly as well, where it orders them correctly but let the user sign the 2nd transaction first.
this is the popup you will see
image

### PR DESCRIPTION
**Pull request by rekmarks**
**Pending**
- [x] https://github.com/MetaMask/json-rpc-engine/pull/21

Fixes batch transaction UX by addressing long-standing errors in batch transaction handling in the UI, and modifying `json-rpc-engine`'s ordered batch request handling. Transactions are now ordered _from oldest to newest_ in the background and in the UI. Users can still freely navigate back and forth.

Fixes #5852

### CODE REVIEW

File: app/scripts/controllers/transactions/index.js [hunk 1]
```diff
@@ -193,12 +193,12 @@ class TransactionController extends EventEmitter {
     }
     txUtils.validateTxParams(normalizedTxParams)
     // construct txMeta
-    const { transactionCategory, getCodeResponse } = await this._determineTransactionCategory(txParams)
     let txMeta = this.txStateManager.generateTxMeta({
       txParams: normalizedTxParams,
       type: TRANSACTION_TYPE_STANDARD,
-      transactionCategory,
     })
+    const { transactionCategory, getCodeResponse } = await this._determineTransactionCategory(txParams)
```
Comment (Gudahtt) [inline app/scripts/controllers/transactions/index.js]: Interesting - was this change incidental, or is there a subtle change in behaviour here?

Comment (whymarrh) [reply app/scripts/controllers/transactions/index.js]: In that the line has been reordered? I too am curious about this.

File: app/scripts/controllers/transactions/index.js [hunk 2]
```diff
@@ -193,12 +193,12 @@ class TransactionController extends EventEmitter {
...
+    txMeta.transactionCategory = transactionCategory
```
Comment (whymarrh) [inline app/scripts/controllers/transactions/index.js]: Similarly, what is the difference between passing the `transactionCategory` to the method that generates the txMeta and setting the property on the `txMeta` directly?

File: package.json [hunk 3]
```diff
@@ -93,7 +93,7 @@
     "eth-json-rpc-errors": "^1.1.0",
     "eth-json-rpc-filters": "^4.1.1",
     "eth-json-rpc-infura": "^4.0.1",
-    "eth-json-rpc-middleware": "^4.2.0",
+    "eth-json-rpc-middleware": "rekmarks/eth-json-rpc-middleware#update-rpc-engine",
```
Comment (whymarrh) [inline package.json]: This needs to be merged into the main repo and published.

File: package.json [hunk 4]
```diff
@@ -118,7 +118,7 @@
     "gaba": "^1.9.0",
     "human-standard-token-abi": "^2.0.0",
     "jazzicon": "^1.2.0",
-    "json-rpc-engine": "^5.1.5",
+    "json-rpc-engine": "rekmarks/json-rpc-engine#ordered-batch",
```
Comment (whymarrh) [inline package.json]: This also needs to be merged into the main repo and published

**Review by whymarrh — CHANGES_REQUESTED** [review]

File: package.json (hunk 3 above)
Comment (rekmarks) [reply package.json]: This one we can actually leave be; I was getting paranoid about package resolutions in `yarn.lock` not working while testing.

File: package.json (hunk 4 above)
Comment (rekmarks) [reply package.json]: Yeah, waiting for this to be merged: MetaMask/json-rpc-engine#21

File: app/scripts/controllers/transactions/index.js (hunk 1 above)
Comment (danjm) [reply app/scripts/controllers/transactions/index.js]: This change causes the `id` of the transaction to be set before the async call to `this._determineTransactionCategory(txParams)`. This `id` is added with the call to `generateTxMeta`

These `id`s are generated with an increment, so that each successive call to `generateTxMeta` will assign an id that is 1 greater than the previous call.

If we make the async call to `this._determineTransactionCategory` before the id is assigned, the following can occur:
- `addUnapprovedTransaction` called multiple times in short succession
- user or developer expects transactions to be ordered as they are received by `addUnapprovedTransaction`
- the wait time for `await this._determineTransactionCategory` differes for each of these different transactions
- the ids get assigned to the transactions in order of the completion of the async call, not the order with which they were received by `addUnapprovedTransaction`
- the transactions have an unexpected order in the tx-state-manager

File: app/scripts/controllers/transactions/index.js (hunk 2 above)
Comment (danjm) [reply app/scripts/controllers/transactions/index.js]: see https://github.com/MetaMask/metamask-extension/pull/7473/files#r348870296

no difference, but we can only get `transactionCategory` from the async call, which needs to happen after `generateTxMeta`

File: app/scripts/controllers/transactions/index.js (hunk 1 above)
Comment (Gudahtt) [reply app/scripts/controllers/transactions/index.js]: Oof. Didn't realize that `_determineTransactionCategory` was async. That makes sense.

**Comment by rekmarks** [comment]
Just re-requested reviews, some tests are failing but unclear if due to my changes. Help appreciated.

**Comment by rekmarks** [comment]
Just re-requested reviews, some tests are failing but unclear if due to my changes. Help appreciated.

File: test/e2e/metamask-ui.spec.js [hunk 5]
```diff
@@ -853,9 +853,9 @@ describe('MetaMask', function () {
     it('renders the correct ETH balance', async () => {
       const balance = await findElement(driver, By.css('.transaction-view-balance__primary-balance'))
       await delay(regularDelayMs)
-      await driver.wait(until.elementTextMatches(balance, /^87.*\s*ETH.*$/), 10000)
+      await driver.wait(until.elementTextMatches(balance, /^90.*\s*ETH.*$/), 10000)
       const tokenAmount = await balance.getText()
-      assert.ok(/^87.*\s*ETH.*$/.test(tokenAmount))
+      assert.ok(/^90.*\s*ETH.*$/.test(tokenAmount))
```
Comment (rekmarks) [inline test/e2e/metamask-ui.spec.js]: These changes are due to a send of 3 ETH now being rejected instead of approved due to the updated UI transaction order. An equivalent solution would be to ensure that transaction is approved, this was just easier.

**Review by Gudahtt — APPROVED** [review]
Looks good to me!

File: ui/app/components/ui/button/button.component.js [hunk 6]
```diff
@@ -26,7 +26,7 @@ const typeHash = {
 
 const Button = ({ type, submit, large, children, className, ...buttonProps }) => (
   <button
-    type={submit && 'submit'}
+    type={submit ? 'submit' : undefined}
```
Comment (whymarrh) [inline ui/app/components/ui/button/button.component.js]: 🙏

**Review by whymarrh — APPROVED** [review]
LGTM
