### PR TITLE
fix: add logic to revert state for smart contract account toggle if there is a blockchain state mismatch cp-13.0.0

### LINKED ISSUE #34742: [Bug]: 7702 Upgrade/Downgrade from account details state does not match onchain state
### Describe the bug

The account details toggle triggers the upgrade/downgrade confirmation. However it persists the new state even if the user does not confirm the upgrade/downgrade confirmation.
That new state also seems to persist in time, as if I close the account details view and then open it again, the toggle still has the wrong state.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/0fd17b09-1fd4-4649-9814-c20f9249a3c8

### Steps to reproduce

1. Go to Account details
2. toggle the upgrade/downgrade account in any given network
3. cancel the transaction
4. see that the toggle changed state

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by hmalik88**
## **Description**

Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:
1. What is the reason for the change? The sca toggle component did not consider a cancelation or failure of  upgrade/downgrade transaction and resulted in a mismatched state.
2. What is the improvement/solution? Add logic to ensure that a mismatch is detected and the state is reverted to what it should be.

## **Related issues**

Fixes: #34742 

## **Manual testing steps**

1. Build from this branch.
2. Navigate to account details (of an account that has funds).
3. Initiate an upgrade/downgrade via toggle.
4. Cancel the transaction.
5. Observe that the toggle reverts to its correct state.

### **Before**

https://github.com/user-attachments/assets/f2676d40-dac6-45e3-a379-60607b23e3ac

### **After**

https://github.com/user-attachments/assets/597fd465-408a-476e-a355-8997ae081429

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by gantunesr — DISMISSED** [review]

**Review by owencraston — DISMISSED** [review]

File: ui/components/multichain-accounts/smart-contract-account-toggle/smart-contract-account-toggle.tsx [hunk 1]
```diff
@@ -75,14 +75,44 @@ export const SmartContractAccountToggle = ({
       const checkUpgradeStatus = async () => {
         try {
           const upgraded = await isUpgraded(address);
```
Comment (mathieuartu) [inline ui/components/multichain-accounts/smart-contract-account-toggle/smart-contract-account-toggle.tsx]: Nit, not related to the PR scope since it fixes the issue, but question:
Could it be possible that dispatching `setToggleState` re-triggers this effect since `toggleState` is part of its dependencies, thus in turn executing (maybe unnecessarily) twice: 
- `isUpgraded` (this seems costly, triggers [this](https://github.com/MetaMask/metamask-extension/blob/main/app/scripts/metamask-controller.js#L8927-L8930) down the line)
- `setAddressSupportSmartAccount`

Comment (hmalik88) [reply ui/components/multichain-accounts/smart-contract-account-toggle/smart-contract-account-toggle.tsx]: Hmm I think so, I can separate out the useEffects in a different PR for sure. I'll make a note of this.

**Review by gantunesr — APPROVED** [review]

**Review by owencraston — APPROVED** [review]
