### PR TITLE
fix: confirmation redesign type sign data layout and values

### LINKED ISSUE #23689: [Bug]: Confirmations Re-design - Signature message is not correct. Missing fields and incorrect identation
### Describe the bug

The signature message is not correct, since we are loosing some information, as well as there are identation issues. See for example signed typed 4. We have the fields `from` and `to` which were visible before, but now they are hidden, and we just display the nested info, but not the `from` and `to` title names

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot from 2024-03-25 10-51-29

### Steps to reproduce

1. Build the re-design
2. Trigger a typed 4 signature
3. Look for `from` and `to` fields -- see they are not displayed

### Error messages or log output

_No response_

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #23692: [Bug]: Confirmations Re-design - Signatures Navigation problems when mixing with Transactions
### Describe the bug

Whenever I trigger a couple of signatures, together with a transaction, I can see how
- the navigation displays the total of Signatures + Transactions
- I cannot navigate to the Transaction, only Signatures --> I think this should be possible. However, in current develop the behaviour is different: we don't mix tx with signatures and they popup in a "different window", meaning when you reject all, you affect all signatures and then tx appear
- If I reject the first Signature, I see that the navigation number is set to 0 incorrectly --> I think this should be fixed
- Reject all, reject both the Tx and Signatures

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/7e52aa4e-c043-4e72-ae34-c2e54d2a17c4

### Steps to reproduce

1. Trigger a couple of signatures
2. Trigger a couple of tx
3. Go to the page 1
4. Reject signature
5. See  you are in the page `0` in the navigation -- this shouldn't be the case
6. Navigate
7. See how page 0 disappears
8. Try to navigate to the transactions -- this is not possible

### Error messages or log output

_No response_

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Fix confirmation redesign type sign data layout and values.

## **Related issues**

Fixes: MetaMask/metamask-extension#23689
Fixes: MetaMask/metamask-extension#23692

## **Manual testing steps**

1. Enable re-designs on confirmations
2. Go to test dapp and submit typed sign data requests
3. Check message layouts

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-extension/assets/2182307/1d4454db-c88e-4ff7-ad7b-e231acfb2249

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.tsx [hunk 1]
```diff
@@ -27,11 +27,14 @@ export const ConfirmInfoRowTypedSignData = ({ data }: { data: string }) => {
...
+        label={`${t('primaryType')}:`}
+        style={{ paddingLeft: 0, paddingRight: 0 }}
+      >
         <ConfirmInfoRowText text={primaryType} />
       </ConfirmInfoRow>
-      <Box style={{ margin: '0 -8px' }}>
+      <Box style={{ marginLeft: -8 }}>
         <DataTree data={sanitizedMessage.value} />
       </Box>
     </Box>
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.tsx:40]: `ConfirmInfoRow` applies padding on `8px` to the row on each side, thus I had to do some style tweaks to achieve tree structure as in the designs.

**Review by pedronfigueiredo — DISMISSED** [review]
LGTM!

**Review by pedronfigueiredo — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
lgtm! 

It would probably be a good idea to readdress your comment above
> ConfirmInfoRow applies padding on 8px to the row on each side, thus I had to do some style tweaks to achieve tree structure as in the designs.

in a future PR
