### PR TITLE
Centre all notification popups

### LINKED ISSUE #6269: Center all popups
**Describe the bug**
Currently, all popups appear on the top left of the screen.

**To Reproduce**
Any transaction that initiates a popup.

**Expected behavior**
Center popups on the screen for easier interaction.

**Screenshots**
Not centered 👎 
screen shot 2019-03-08 at 2 43 08 pm

**Additional context**

Resource with code and demo showing it is possible to center popups http://www.nigraphic.com/blog/java-script/how-open-new-window-popup-center-screen

Gif of user centering popup.
user centering the pop up screen1

### PR DESCRIPTION
**Pull request by whymarrh**
Closes #6269

This PR centres all the notification popups based on the screen size.

The support for `window.screen.height` and `window.screen.width` seem good, according to MDN.<sup>[\[1\]][1]</sup>

  [1]:https://developer.mozilla.org/en-US/docs/Web/API/Screen

### CODE REVIEW

File: app/scripts/lib/notification-manager.js [hunk 1]
```diff
@@ -1,7 +1,10 @@
 const extension = require('extensionizer')
-const height = 620
-const width = 360
-
+const SCREEN_WIDTH = window.screen.width
+const SCREEN_HEIGHT = window.screen.height
```
Comment (danfinlay) [inline app/scripts/lib/notification-manager.js]: Since a screen's resolution can be adjusted at run-time, we should maybe re-compute this at popup creation time.

**Review by danfinlay — CHANGES_REQUESTED** [review]
One small easy change!

File: app/scripts/lib/notification-manager.js (hunk 1 above)
Comment (whymarrh) [reply app/scripts/lib/notification-manager.js]: Good idea! I'll fix this right up.

**Review by danfinlay — DISMISSED** [review]
Awesome. I'm super embarrassed that we hadn't realized this was possible yet!

**Comment by whymarrh** [comment]
@danfinlay I had to rebase this on the latest `develop` to fix the build. Should be good, no changes.

**Comment by whymarrh** [comment]
cc @cjeria

**Review by kumavis — APPROVED** [review]
