### PR TITLE
fix: unified swaps activity list items cp-13.21.0

### LINKED ISSUE #40539: [Bug]: Incorrect networks in activity list
### Describe the bug

Currently, whenever a user submits a bridge tx, the activity list shows incorrectly 'Bridge to Polygon' label. This might create confusion to the users thinking they bridged their assets over to the wrong network.

Below is a POL -> SOL with no confirmation on the SOL txid and it currently only shows 'Bridged to Polygon' rather than 'Bridged to Solana'.

### Expected behavior

It should mention 'Bridged to ' the correct destination network.

### Screenshots/Recordings

Image

### Steps to reproduce

1. Go to swaps screen
2. Bridge Polygon to Solana
3. Go to activity list
4. See ;Bridged to Polygon'

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.20.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

This restores the activity list and details for Bridge and Swap transactions

Changes
- Introduce `useBridgeActivityData` hook that wraps different bridge hooks for deriving bridge/swap tx data from local state
- Add selectors for looking up local tx history by tx hash instead of txId. The new activity list items only contain txHash, but local ones have txId
- Add adapters from Activity list v2 to the working Unified swap/bridge components

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/40459?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: unified swaps activity list items are displayed incorrectly

## **Related issues**

Fixes: #40539

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before/After**

||BEFORE|AFTER|
|-|-|-|
| Transactions submitted locally |Screenshot 2026-02-27 at 6 06 48 PM| Screenshot 2026-02-27 at 6 04 11 PM | 
| Transactions submitted on other clients |Screenshot 2026-02-27 at 6 07 20 PM|Screenshot 2026-02-27 at 6 04 35 PM | 
| Bridge details (other client) | Screenshot 2026-02-27 at 6 07 35 PM|Screenshot 2026-02-27 at 6 04 44 PM | 
|Bridge details (local) |Screenshot 2026-02-27 at 6 07 58 PM| Screenshot 2026-02-27 at 6 04 55 PM| 
|Swap details (other client) |Screenshot 2026-02-27 at 6 08 17 PM| Screenshot 2026-02-27 at 6 05 11 PM| 
|Swap details (local)|Screenshot 2026-02-27 at 6 08 43 PM |Screenshot 2026-02-27 at 6 05 26 PM | 

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Updates bridge/swap activity rendering and navigation to rely on `txHash` and new state selectors; mistakes could break transaction detail links or show incorrect status/token/chain info. Changes are UI/state-selection focused and don’t touch signing or on-chain transaction creation.
> 
> **Overview**
> Restores unified swap/bridge behavior across Activity v2 and legacy activity by introducing `useBridgeActivityData` to derive chain/token/status data and detail-page navigation from local bridge history.
> 
> Bridge history lookup is reworked to be **hash-based** (`selectBridgeHistoryItemByHash`, `selectLocalTxForTxHash`) so Activity v2 items that only have a `txHash` can resolve local `txMetaId`/`actionId` and approval-linked history entries.
> 
> Unified swap/bridge detail navigation is switched from `:srcTxMetaId` to `:txHash`, passing the transaction via router state; the cross-chain tx details page and list items/adapters are updated accordingly, with tests adjusted and minor bridge page styling tweaks.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 025076b4e18f7507896463b6f19634db5a23674b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/multichain/activity-v2/activity-details-modal-adapter.tsx [hunk 1]
```diff
@@ -16,57 +16,13 @@ import LegacyTransactionListItemDetails from '../../app/transaction-list-item-de
...
 import { getSelectedAddress } from '../../../selectors/selectors';
 import { formatUnits } from '../../../../shared/lib/unit';
+import { useBridgeActivityData } from '../../../hooks/bridge/useBridgeActivityData';
 import { useGetTitle } from './hooks';
+import { resolveTransactionType } from './helpers';
 
 // eslint-disable-next-line no-empty-function
 const noop = () => {};
 
-// Map API transactionCategory to TransactionType for legacy modal
```
Comment (micaelae) [inline ui/components/multichain/activity-v2/activity-details-modal-adapter.tsx:24]: Moved this to the helpers module because the bridge hooks depend on the resolved type

**Review by ghgoodreau — DISMISSED** [review]

**Review by n3ps — DISMISSED** [review]

**Review by ghgoodreau — DISMISSED** [review]

**Review by ghgoodreau — APPROVED** [review]

**Review by n3ps — APPROVED** [review]
