### PR TITLE
fix: should not auto-close notification window if loaded in a tab

### LINKED ISSUE #29821: [Bug]: browser-wide crash
### Describe the bug

# **Do not try this if you have important stuff open. This will crash all tabs and profiles, not just the one tab you're testing with.**

# Notes
This can be triggered programmatically by doing `window.open("<url>", "_blank");`

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Install MetaMask and set up a wallet
2. Open `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/notification.html` or `moz-extension://a0b28803-be23-4c3d-81d2-9735449f7d26/notification.html` as a new tab

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.10.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by dbrans**
## **Description**
This PR fixes a rare issue when a user, usually a developer, manually opens notification.html in a browser tab. 

We avoid using `browser.windows.remove(id)` to prevent closing all tabs in a window.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30970?quickstart=1)

## **Related issues**

* Fixes: https://github.com/MetaMask/metamask-extension/issues/29821

## **Manual testing steps**
Test that browser tab does not auto-close:
1. Open MM in a browser tab
2. Change url path from /home.html => /notification.html
3. Browser tab should stay open (previously the entire window was closed)

Test that notification popup auto-closes:
4. Open notification popup by visiting a dapp and doing something (like connecting) that requires permission
5. Cancel/Decline the request in the notification popup
6. Notification popup should auto-close.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: shared/lib/canSafelyAutoCloseThisPopup.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ *
+ * @returns A Promise that resolves to `true` if the window is a popup
+ * or if the window type cannot be determined – and `false` only if the
+ * window is confirmed to not be a popup.
+ */
+export const canSafelyAutoCloseThisPopup = async (): Promise<boolean> => {
+  try {
+    const currentWindow = await browser.windows.getCurrent();
+    // Only return false if we know for sure it's not a popup
+    if (currentWindow?.type && currentWindow.type !== 'popup') {
```
Comment (davidmurdoch) [inline shared/lib/canSafelyAutoCloseThisPopup.ts:18]: oh wow, it's so simple! how did we miss this for so long?

Comment (davidmurdoch) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:18]: According to the return type of https://developer.chrome.com/docs/extensions/reference/api/windows#method-getCurrent this method will always return a window, so we shouldn't need to `?` check first. The "current" window is the window running the code that is calling `browser.windows.getCurrent()`, so it must always exist, right? Are the types saying claiming something different?

File: shared/lib/canSafelyAutoCloseThisPopup.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+      console.warn('Not safe to close a window likely running in a tab.');
+      return false;
+    }
+    // In all other cases (no window found, error, or is popup), consider it safe
+    return true;
+  } catch (error) {
+    console.error('Error getting current window:', error);
+    return true; // Default to safe in case of errors
```
Comment (davidmurdoch) [inline shared/lib/canSafelyAutoCloseThisPopup.ts:26]: Probably best to default to `unsafe` in the case of an error?

File: shared/lib/canSafelyAutoCloseThisPopup.test.ts [hunk 3]
```diff
@@ -0,0 +1,63 @@
+import browser from 'webextension-polyfill';
+import { canSafelyAutoCloseThisPopup } from './canSafelyAutoCloseThisPopup';
+
+const it = global.it as unknown as jest.It;
```
Comment (davidmurdoch) [inline shared/lib/canSafelyAutoCloseThisPopup.test.ts:4]: hm, why is this necessary?  I don' think we don't use this logic anywhere else.

File: ui/store/actions.ts [hunk 4]
```diff
@@ -4827,6 +4828,9 @@ export function getGasFeeTimeEstimate(
 }
 
 export async function closeNotificationPopup() {
+  if (!(await canSafelyAutoCloseThisPopup())) {
+    return;
+  }
```
Comment (davidmurdoch) [inline ui/store/actions.ts:4833]: Since the surrounding function is named `closeNotificationPopup`, and this logic here ensures that it _doesn't_, I think the logic should either be moved elsewhere, or the function name should be changed.

File: shared/lib/canSafelyAutoCloseThisPopup.ts (hunk 1 above)
Comment (davidmurdoch) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:18]: nit: I noticed there is a `browser.windows.WindowType.POPUP` property thath returns the "popup" string.

Comment (davidmurdoch) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:18]: Additionally, I just learned of `browser.tabs.getCurrent()`. Do you know of any reason we can't use this to close only the _`tab`_ and not the `window` when we detect that the window is not a `"popup"`?

```javascript
const tab = await browser.tabs.getCurrent();
await browser.tabs.remove(tab.id);
```

File: shared/lib/canSafelyAutoCloseThisPopup.test.ts (hunk 3 above)
Comment (dbrans) [reply shared/lib/canSafelyAutoCloseThisPopup.test.ts]: Replaced with explicit type reference at top of file.

File: shared/lib/canSafelyAutoCloseThisPopup.ts (hunk 1 above)
Comment (dbrans) [reply shared/lib/canSafelyAutoCloseThisPopup.ts]: I added that to the call in actions.ts.

File: shared/lib/canSafelyAutoCloseThisPopup.ts (hunk 2 above)
Comment (dbrans) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:26]: Since the bug only occurs when a user manually pastes the notification.html URL into a browser tab—a rare scenario—I think we should stick with the current behavior and default to 'it's safe' to auto-close the popup.

if this runs in a browser that doesn’t fully support the WebExtension API as expected, the notification popup might stop auto-closing properly. 

Given that browser support for this API is relatively new and evolving, I’m hesitant to assume it will work across all browsers.

What do you think?

File: ui/store/actions.ts (hunk 4 above)
Comment (dbrans) [reply ui/store/actions.ts]: Renamed to attemptCloseNotificationPopup

File: shared/lib/canSafelyAutoCloseThisPopup.ts (hunk 2 above)
Comment (davidmurdoch) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:26]: > browser support for this API is relatively new and evolving

Have any links of support history?

Comment (dbrans) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:26]: Here's a concrete example of inconsistent WebExtension API browser support using `extension.getBackgroundPage()`:

According to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage), Chrome supports this API. But we've found several problems:

1. The WebExtension polyfill types [define the return type as `Window`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webextension-polyfill/namespaces/extension.d.ts#L48) (non-nullable), but the documentation right above it [states the return can be null](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webextension-polyfill/namespaces/extension.d.ts#L46).

2. Chrome's docs say `getBackgroundPage` is [only available in the foreground](https://developer.chrome.com/docs/extensions/reference/api/extension#method-getBackgroundPage). If you try calling it from a service worker, you get a type error because the function doesn't exist.

3. When calling `getBackgroundPage` from the MetaMask UI in Chrome, we get `null` even though our extension has an active background page.

These gaps between types, documentation, and actual behavior make it risky to assume the WebExtension API will work consistently across browsers.

Comment (davidmurdoch) [reply shared/lib/canSafelyAutoCloseThisPopup.ts:26]: > if this runs in a browser that doesn’t fully support the WebExtension API as expected, the notification popup might stop auto-closing properly.

I think this is a better outcome than closing the whole browser, no?

File: ui/store/actions.ts [hunk 5]
```diff
@@ -4851,9 +4852,41 @@ export function getGasFeeTimeEstimate(
...
+      console.warn(
+        `Not safe to close a window that is not a popup: It is of type: ${currentWindow.type}`,
+      );
+      // We've confirmed this is not a popup window, so it's not safe to close.
+      return;
+    }
+  } catch (error) {
+    // Error occurred while checking window type - we cannot confirm it's not a popup, so continue
+    // with the closing attempt as we haven't ruled out that it might be a popup
+  }
```
Comment (dbrans) [inline ui/store/actions.ts:4869]: @davidmurdoch, I made the changes we spoke about. But in addition, added this check:

// Check if the current window is NOT a popup - if confirmed, we should not close it.

... since there's no point in closing a window that is not a popup.

File: ui/store/actions.ts [hunk 6]
```diff
@@ -4851,9 +4852,41 @@ export function getGasFeeTimeEstimate(
   ]);
 }
 
-export async function closeNotificationPopup() {
+export async function attemptCloseNotificationPopup() {
+  // Check if the current window is NOT a popup - if confirmed, we should not close it
+  try {
```
Comment (davidmurdoch) [inline ui/store/actions.ts:4857]: I think `attemptCloseNotificationPopup`  was only problematic before is because `global.platform.closeCurrentWindow();` actually closes the entire window (all tabs), not just the one tab. Since `window.close()` only closes its own tab it _is_ safe to try it first.

HOWEVER, the problem with calling `window.close()` right away is that we can't do `await submitRequestToBackground('markNotificationPopupAsAutomaticallyClosed');` if `window.close()` does manage to  close the tab. And from some quick searching it looks like this event really must happen.

But!...

The `await submitRequestToBackground('markNotificationPopupAsAutomaticallyClosed');` call seems to carry some pretty important logic related to `rejectUnapprovedNotifications`:

```
notificationManager.on(
    NOTIFICATION_MANAGER_EVENTS.POPUP_CLOSED,
    ({ automaticallyClosed }) => {
      if (!automaticallyClosed) {         // <---- this is set via `await submitRequestToBackground('markNotificationPopupAsAutomaticallyClosed');`
        rejectUnapprovedNotifications();
      } else if (getPendingApprovalCount() > 0) {
        triggerUi();
      }

      updateBadge();
    },
  );
```

I haven't followed all of the logic that gets here, as it looks like it is pretty tangled.

Questions I have:

1. We call `await submitRequestToBackground('markNotificationPopupAsAutomaticallyClosed');`, and then we _try_ to close the tab. If these attempts don't work will this break any of the `automaticallyClosed`-related logic?

2. do we actually care if the window type is a popup or not? Can we drop that logic completely? We now know we will always close _only_ the tab, not the entire window (with all other tabs in it). Is there a reason we should keep the `notification.html` page open just because it is not in a popup?

3. what if when notification is manually opened we immediately close it and force it into a popup

--- 

sorry I keep drilling down into this. I'm not sure there is even a right answer.

Comment (dbrans) [reply ui/store/actions.ts:4857]: Hey, I appreciate your drilling down!

Regarding your questions:

1.  **`await` and failed close:** `await` ensures `markNotificationPopupAsAutomaticallyClosed` finishes before we try `window.close()`. If closing fails later (which could happen in a regular tab), the `automaticallyClosed` state is still correctly set in the background. The main downside is the tab awkwardly remaining open, but the related logic should function as intended. This mainly affects the dev edge case of manually opening `notification.html` in a regular tab, so thankfully it is rare.
2.  **Popup check:** we should probably keep the `type !== 'popup'` check. Auto-closing a regular browser tab feels like unexpected UX. It makes sense not to close a tab someone might have opened deliberately, even if it's `notification.html`.
3.  **Force into popup:** That's an interesting alternative to consider, though it might add complexity we want to avoid for this edge case.

Overall, the current approach seems like a reasonable balance, ensuring the state is correct without being too disruptive in this non-standard scenario. What do you think?

Comment (davidmurdoch) [reply ui/store/actions.ts:4857]: Just deleted a a bunch of paragraphs responding to your points.

I think the approach here is probably fine because:

1. the "bug" is developers opening a popup in a main window. that's not supposed to happen.
2. If the `browser.windows` and/or `browser.tabs` fail, we _may close a tab within a regular window_, BUT I don't think it is a real UX problem only because I think these two APIs are solid.

---

Now I fun observations:

There is an _existing_ race condition where a `markNotificationPopupAsAutomaticallyClosed` message is in flight and the user _manually_ closes the popup window in the meantime. I _think_ this means the UI should tell the background it wants to be closed, and then the _background_ takes care of closing it; this should prevent the race condition.

File: ui/store/actions.ts [hunk 7]
```diff
@@ -4851,9 +4852,41 @@ export function getGasFeeTimeEstimate(
...
+    const currentWindow = await browser.windows.getCurrent();
+    if (currentWindow.type && currentWindow.type !== 'popup') {
```
Comment (davidmurdoch) [inline ui/store/actions.ts:4859]: Nit: `browser.windows.WindowType.popup` returns `"popup"`, if you're into using that sort of thing. haha

File: ui/store/actions.ts [hunk 8]
```diff
@@ -4851,9 +4852,41 @@ export function getGasFeeTimeEstimate(
...
+  } catch (error) {
+    // Error occurred while checking window type - we cannot confirm it's not a popup, so continue
+    // with the closing attempt as we haven't ruled out that it might be a popup
+  }
+
   await submitRequestToBackground('markNotificationPopupAsAutomaticallyClosed');
-  global.platform.closeCurrentWindow();
+
+  // First attempt: Try window.close()
+  // This has limitations according to MDN:
```
Comment (davidmurdoch) [inline ui/store/actions.ts:4874]: Maybe add a comment about why this way is being preferred over the `async` way?

File: ui/store/actions.ts [hunk 9]
```diff
@@ -4851,9 +4852,44 @@ export function getGasFeeTimeEstimate(
...
+    const currentWindow = await browser.windows.getCurrent();
+    if (currentWindow.type && currentWindow.type !== 'popup') {
+      console.warn(
+        `Not safe to close a window that is not a popup: It is of type: ${currentWindow.type}`,
+      );
+      // We've confirmed this is not a popup window, so it's not safe to close.
+      return;
+    }
+  } catch (error) {
+    // Error occurred while checking window type - we cannot confirm it's not a popup, so continue
```
Comment (Gudahtt) [inline ui/store/actions.ts:4867]: For the sake of making debugging easier, lets not completely suppress this error. We can use `console.debug` if it's not something we want logged in production, or `console.log` if it's something we might want to see in logs from support tickets.

I'd recommend `console.warn`, so that if a window stays open when it shouldn't, we'll see this hint in the logs as to why. Even if it's encountered on a production build by an end-user.

Comment (Gudahtt) [reply ui/store/actions.ts:4867]: Er... sorry, I misunderstood at first. We're assuming it _is_ a popup if this fails.

Still seems potentially useful to log here, and not disruptive give that nobody would see it. But maybe less helpful than I originally thought.

**Comment by Gudahtt** [comment]
Looks reasonable to me! Not approving only because I haven't had time to review in detail, but I understand the solution broadly I think.

File: ui/store/actions.ts (hunk 7 above)
Comment (davidmurdoch) [reply ui/store/actions.ts:4859]: Oh, typo in the casing there.

Interesting that the types and docs don't match up. I'm good with using the string here.

File: ui/store/actions.ts (hunk 9 above)
Comment (dbrans) [reply ui/store/actions.ts:4867]: Added a warn.

File: test/e2e/tests/safe-window-close.spec.ts [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+        const requestPermissionsRequest = JSON.stringify({
+          jsonrpc: '2.0',
+          method: 'wallet_requestPermissions',
+          params: [{ eth_accounts: {} }],
+        });
+        await driver.executeScript(
+          `window.ethereum.request(${requestPermissionsRequest})`,
+        );
+
+        // await driver.delay(30000);
```
Comment (vinnyhoward) [inline test/e2e/tests/safe-window-close.spec.ts:31]: We can remove this right?

**Review by darkwing — DISMISSED** [review]

**Review by vinnyhoward — DISMISSED** [review]

**Review by HowardBraham — APPROVED** [review]

**Review by davidmurdoch — APPROVED** [review]
⭐ ⭐ ⭐ ⭐ ⭐ 
5 Stars! Would review again!

**Review by vinnyhoward — APPROVED** [review]
