### PR TITLE
network.js: convert rpc protocol to lower case.

### LINKED ISSUE #4253: Custom RPC URL fails with uppercase HTTP
Bounty: MetaMask should connect to Ganache (or any custom RPC) reliably whether the user inputs `HTTP` or `http`. 

---
I found this bug while testing on a private network with Ganache.
If you start Ganache and copy-paste the RPC Server address "HTTP://127.0.0.1:7545" (note the uppercase HTTP) then you will get a balance of 0 in Metamask for the accounts.
Change the server address to **lowercase** http://127.0.0.1:7545 then it works.

### PR DESCRIPTION
**Pull request by pinkiebell**
Fixes #4253

### CODE REVIEW

**Comment by whymarrh** [comment]
Hey @pinkiebell, thanks for this! Two comments:

1. Our `test-e2e-beta-firefox` CI check is currently a bit flaky, don't mind that failure. I don't think there's anything in here that should cause issues.
1. I see you're using substring to parse the scheme out of the URL, would it make more sense to use the URL module `require('url')` instead? (I'll leave this inline as well.)

File: app/scripts/controllers/network/network.js [hunk 1]
```diff
@@ -155,6 +155,11 @@ module.exports = class NetworkController extends EventEmitter {
   }
 
   _configureStandardProvider ({ rpcUrl }) {
+    const colon = rpcUrl.indexOf(':')
+    if (colon !== -1) {
+      const proto = rpcUrl.substring(0, colon)
```
Comment (whymarrh) [inline app/scripts/controllers/network/network.js]: Instead of using indexOf and substring here, can we use the URL module to pick the scheme out of the URL. We should be able to create a [`URL`](https://nodejs.org/docs/latest-v8.x/api/url.html#url_constructor_new_url_input_base) instance and mutate the protocol.

**Comment by pinkiebell** [comment]
@whymarrh Should be good now 👍

**Review by whymarrh — APPROVED** [review]
LGTM, thanks!
