### PR TITLE
fix: fixed memoisation issue

### LINKED ISSUE #35602: Error: Minified Redux error #7; visit ** for the full message or use the non-minified dev environment for full errors.
Sentry Issue: [METAMASK-XQ9T](https://metamask.sentry.io/issues/6851345496/?referrer=github_integration)

```
Error: Minified Redux error #7; visit ** for the full message or use the non-minified dev environment for full errors. 
  at handleEvmNetworkChange (ui/components/multichain/network-list-menu/network-list-menu.tsx:367:9)
  at handleNetworkChange (ui/components/multichain/network-list-menu/network-list-menu.tsx:416:15)
  at <object>.onClick (ui/components/multichain/network-list-menu/network-list-menu.tsx:593:15)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR fixes the memoistion issue by introducing the for...in loop which doesn't create new array references, so memoization works properly, components don't constantly re-render, and Redux dispatches work correctly.

## **Related issues**

Fixes: #35602

## **Manual testing steps**

1. Network Switching Via Dapp should work

### **Before**

NA
### **After**

NA
## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/dapp.ts [hunk 1]
```diff
@@ -16,14 +16,18 @@ export const getDappActiveNetwork = createDeepEqualSelector(
...
 
-    const networkConfiguration = Object.values(
-      networkConfigurationsByChainId,
-    ).find((network) => {
-      return network.rpcEndpoints.some(
-        (rpcEndpoint) => rpcEndpoint.networkClientId === networkClientId,
-      );
-    });
+    for (const chainId in networkConfigurationsByChainId) {
+      if (Object.prototype.hasOwnProperty.call(networkConfigurationsByChainId, chainId)) {
```
Comment (Prithpal-Sooriya) [inline ui/selectors/dapp.ts]: nit (we don't need to impl): I think this could be replaced with
```ts
if (chainId in networkConfigurationsByChainId) {
  ...
}
```

File: ui/selectors/dapp.ts [hunk 2]
```diff
@@ -16,14 +16,18 @@ export const getDappActiveNetwork = createDeepEqualSelector(
...
+        const network = networkConfigurationsByChainId[chainId as keyof typeof networkConfigurationsByChainId];
+        const hasMatchingEndpoint = network.rpcEndpoints.some(
+          (rpcEndpoint: any) => rpcEndpoint.networkClientId === networkClientId,
```
Comment (Prithpal-Sooriya) [inline ui/selectors/dapp.ts]: Do we need the `any` type?

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: ui/selectors/dapp.ts (hunk 2 above)
Comment (NidhiKJha) [reply ui/selectors/dapp.ts]: Good catch, updated here https://github.com/MetaMask/metamask-extension/pull/35624/commits/51ab87b13d8e705a6060efd6c861d4f0f3589319

**Review by salimtb — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
