### PR TITLE
Fix: PetNamesBridge to use InternalAccounts

### LINKED ISSUE #22933: [Bug]: Incorrect account name in receive flow
### Describe the bug

Pr [22844](https://github.com/MetaMask/metamask-extension/pull/22844) is described as bringing updated account names to both receive flow and account details.  Account details are showing as expected within the 11.11.0 RC commit 6d34630bb78be87da26ee45efad4fcf29d332b87, however the snap accounts are still showing with an incorrect name when they are receiving.  While the PR description indicates that receive flow should be updated, the manual testing steps included in the PR omit testing for receive flow.

Expected: `Snap Account x`
Observed: `Account x`

Tested with Chrome 117.0.5938.92
Mac Sonoma 14.2.1
Snap Simple Keyring v1.1.1

### Expected behavior

Given that a snap account was created successfully
And was named `Snap Account x`
When I send to that account from another account within the wallet
Then the snap account as the recipient should appear with the correct and consistent name `Snap Account x` 

### Screenshots/Recordings

Recording: https://recordit.co/WG5Pq1361p

Snap Account 7

### Steps to reproduce

1. Setup wallet
2. Install [SSK snap](https://metamask.github.io/snap-simple-keyring/latest/) 
3. Create an account
4. Attempt to send to newly created snap account from another account in the wallet

### Error messages or log output

_No response_

### Version

11.11.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR updates the PeNamesBridge to use InternalAccounts from the AccountsController instead of using identities. 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/22933

## **Manual testing steps**

1. Create a snap account
2. Open extension and click on send
3. Select a snap account as a recipient
4. See that the name is correct. 

### **Before**

Screenshot 2024-02-19 at 21 48 00

### **After**

Screenshot 2024-02-19 at 21 36 48

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/lib/AbstractPetnamesBridge.ts [hunk 1]
```diff
@@ -28,13 +32,14 @@ enum SyncDirection {
 // A list of changes, grouped by type.
 type ChangeList = Record<ChangeType, PetnameEntry[]>;
 
-type AllowedEvents = NameStateChange;
+type AllowedEvents = NameStateChange | AccountsControllerChangeEvent;
+type AllowedActions = AccountsControllerListAccountsAction;
```
Comment (dbrans) [inline app/scripts/lib/AbstractPetnamesBridge.ts:36]: Let's try not to mix account events and actions and actions in this file. It makes our abstract class too aware of its subclasses' details. How about we fix this by:

1. Letting AbstractPetnamesBridge work with a more generic messenger.
2. Allowing PetnamesBridgeMessenger to use template parameters for actions.
3. Using a different messenger for the subclass.

Or, is there another approach we could consider?

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts [hunk 2]
```diff
@@ -75,48 +92,54 @@ function createNameStateWithPetname(
...
-    identities: {
-      [address]: {
-        address,
-        name,
-      },
-    },
-  };
+function setupAccountsController(
+  messenger,
+  state = EMPTY_ACCOUNTS_CONTROLLER_STATE,
```
Comment (dbrans) [inline app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts:101]:
```suggestion
  messenger: AccountsControllerMessenger,
```

File: app/scripts/lib/AbstractPetnamesBridge.ts (hunk 1 above)
Comment (montelaidev) [reply app/scripts/lib/AbstractPetnamesBridge.ts]: Sure, we can make it work with a more generic messenger

**Review by dbrans — COMMENTED** [review]
Hi @montelaidev, nice work on the changes. I have a few suggestions, so I put together a PR which you can merge into your branch if you choose: https://github.com/MetaMask/metamask-extension/pull/23088.

The key change is not exporting PetnamesBridgeAllowedEvents/Actions and instead to pass in the events/actions that the subclasses need directly to AbstractPetnamesBridge and PetnamesBridgeMessenger.

**Review by dbrans — DISMISSED** [review]
Monte, looks good to me!

I'll ask @matthewwalsh0 for another pair of eyes.

File: app/scripts/lib/AbstractPetnamesBridge.ts [hunk 3]
```diff
@@ -28,14 +32,17 @@ enum SyncDirection {
 // A list of changes, grouped by type.
 type ChangeList = Record<ChangeType, PetnameEntry[]>;
 
-type AllowedEvents = NameStateChange;
+type PetnamesBridgeAllowedEvents = NameStateChange;
 
-export type PetnamesBridgeMessenger = RestrictedControllerMessenger<
+export type PetnamesBridgeMessenger<
+  Event extends EventConstraint,
```
Comment (matthewwalsh0) [inline app/scripts/lib/AbstractPetnamesBridge.ts:38]: Depending on our TypeScript version, can we use defaults here to assign these both to `never` if not provided, so it's not required on every bridge implementation such as the address book?

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts [hunk 4]
```diff
@@ -129,51 +162,80 @@ function createNameControllerMock(
...
 describe('AccountIdentitiesPetnamesBridge', () => {
+  let messenger;
+  let accountsControllerMessenger: AccountsControllerMessenger;
+  let petnamesBridgeMessenger: PetnamesBridgeMessenger<
+    AccountIdentitiesPetnamesBridgeEvents,
+    AccountIdentitiesPetnamesBridgeActions
+  >;
+
   beforeEach(() => {
+    messenger = new ControllerMessenger();
```
Comment (matthewwalsh0) [inline app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts:173]: I'm a big fan of isolating unit tests as much as possible by mocking anything we don't want to test.

We're using a real instances of the controller messenger meaning if that code fails, these tests now fail also.

In this scenario, we can simulate the messenger events by provided an entirely mocked `messenger` object to the constructor and then just invoking the first argument passed to the `subscribe` method as that's the limit of our interaction in the implementation.

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.ts [hunk 5]
```diff
@@ -4,44 +4,52 @@ import {
...
 
   /**
    * @override
    */
   protected getSourceEntries(): PetnameEntry[] {
-    const { identities } = this.#preferencesController.store.getState();
-    return Object.values(identities).map((identity: AccountIdentityEntry) => ({
-      value: identity.address,
+    const internalAccounts = this.messenger.call(
+      'AccountsController:listAccounts',
```
Comment (matthewwalsh0) [inline app/scripts/lib/AccountIdentitiesPetnamesBridge.ts:47]: Just confirming for audit sake this will still include all the standard account identities, but now also the snap account names?

File: test/jest/mocks.js [hunk 6]
```diff
@@ -148,3 +152,39 @@ export const getInitialSendStateWithExistingTxState = (draftTxState) => ({
     },
   },
 });
+
+export function createMockInternalAccount({
+  address = '0xd5e099c71b797516c10ed0f0d895f429c2781111',
```
Comment (matthewwalsh0) [inline test/jest/mocks.js:157]: If the intent is to centralise these mocks to avoid duplication, is it worth putting this address in a constant such as `ACCOUNT_MOCK` so we can assert against it later?

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts (hunk 4 above)
Comment (dbrans) [reply app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts:173]: @montelaidev – check out the way the messenger is mocked in AddressBookPetnamesBridge.test.ts – and how the first argument, the listener callback, is invoked:
https://github.com/MetaMask/metamask-extension/blob/b16ad3171e7c2b36d611f23c43b5ebb532fdfadd/app/scripts/lib/AddressBookPetnamesBridge.test.ts#L138-L140

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.ts (hunk 5 above)
Comment (montelaidev) [reply app/scripts/lib/AccountIdentitiesPetnamesBridge.ts:47]: Yes, the accounts controller will have all the same accounts that the preference controller has.

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts (hunk 4 above)
Comment (montelaidev) [reply app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts:173]: That makes sense, i've changed the tests to use a mocked messenger

File: app/scripts/lib/AbstractPetnamesBridge.ts [hunk 7]
```diff
@@ -35,8 +35,8 @@ type ChangeList = Record<ChangeType, PetnameEntry[]>;
 type PetnamesBridgeAllowedEvents = NameStateChange;
 
 export type PetnamesBridgeMessenger<
-  Event extends EventConstraint,
-  Action extends ActionConstraint,
+  Event extends EventConstraint = PetnamesBridgeAllowedEvents,
```
Comment (dbrans) [inline app/scripts/lib/AbstractPetnamesBridge.ts:38]: You want this to be `never`. The reason being that we are already taking the union of Event with PetnamesBridgeAllowedEvents on line 43, so this default is confusing.

File: app/scripts/lib/AbstractPetnamesBridge.ts [hunk 8]
```diff
@@ -64,8 +64,8 @@ function getKey({ type, variation, value }: PetnameEntry): string {
  * Provides methods for synchronizing petnames with the data source and handling changes.
  */
 export abstract class AbstractPetnamesBridge<
-  Event extends EventConstraint,
-  Action extends ActionConstraint,
+  Event extends EventConstraint = PetnamesBridgeAllowedEvents,
```
Comment (dbrans) [inline app/scripts/lib/AbstractPetnamesBridge.ts:67]: You want this to `= never` for the same reason above. See comment on line 38.

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts [hunk 9]
```diff
@@ -97,59 +90,22 @@ function createNameStateWithPetname(
...
-  });
-}
-
-function buildPetNamesBridgeMessenger(
-  messenger,
-): PetnamesBridgeMessenger<
-  AccountIdentitiesPetnamesBridgeEvents,
-  AccountIdentitiesPetnamesBridgeActions
+function createMessengerMock(): jest.Mocked<
+  PetnamesBridgeMessenger<
```
Comment (dbrans) [inline app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts:94]: If you're using this type a lot it can help to define it somewhere to avoid repetition.
```
type BridgeMessenger = PetnamesBridgeMessenger<
    AccountIdentitiesPetnamesBridgeEvents,
    AccountIdentitiesPetnamesBridgeActions
  >;
```

**Review by dbrans — CHANGES_REQUESTED** [review]

**Review by dbrans — DISMISSED** [review]

File: app/scripts/lib/AddressBookPetnamesBridge.ts [hunk 10]
```diff
@@ -11,7 +11,10 @@ import {
   PetnameEntry,
 } from './AbstractPetnamesBridge';
 
-export class AddressBookPetnamesBridge extends AbstractPetnamesBridge {
+export class AddressBookPetnamesBridge extends AbstractPetnamesBridge<
+  never,
```
Comment (matthewwalsh0) [inline app/scripts/lib/AddressBookPetnamesBridge.ts:15]: Can we remove these since we added the default templates?

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts [hunk 11]
```diff
@@ -129,24 +109,45 @@ function createNameControllerMock(
...
+      messenger,
     });
     bridge.init();
 
-    preferencesController.updateMockStateAndTriggerListener(
-      createPreferencesStateWithIdentity(ADDRESS_MOCK, NAME_MOCK),
+    // mock listAccounts call
+    messenger.call.mockReturnValue([MOCK_INTERNAL_ACCOUNT]);
+
+    const listener = messenger.subscribe.mock.calls[0][1] as (
```
Comment (matthewwalsh0) [inline app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts:138]: Minor, but as it's a bit verbose to include in each test, we'd usually make a helper function such as:

`simulateSubscribe(messenger: jest.Mocked<AccountIdentitiesPetnamesBridgeMessenger>, stateChange: AccountsControllerState, patch: any[])`

File: app/scripts/lib/AddressBookPetnamesBridge.ts (hunk 10 above)
Comment (montelaidev) [reply app/scripts/lib/AddressBookPetnamesBridge.ts]: Yes we can remove these

File: app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts (hunk 11 above)
Comment (montelaidev) [reply app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts]: Sure, that makes sense.

**Review by dbrans — APPROVED** [review]

**Comment by dbrans** [comment]
Nice work!

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by k-g-j** [comment]
Works as expected in manual testing steps in Chrome Version 122.0.6261.112

https://github.com/MetaMask/metamask-extension/assets/91970214/ad1d4957-aff7-4b34-99cf-e56736b9f578

Works as expected in manual testing steps in Firefox Version 123.0.1

https://github.com/MetaMask/metamask-extension/assets/91970214/66674f2a-b1fa-4f1d-882c-b054f411020a
