### PR TITLE
Fix sending maximum of an ERC20 token

### LINKED ISSUE #11593: Can't sed "Max" of an ERC20 token
> I’m trying to send a token from MM to another wallet on BSC. I have enough BNB for gas (although I’m not making any gas price edits, just going with the default as suggested by MM). The tx keeps failing and I see this error. 

> Ok the problem was I was sending the Max amount, and for some reason the tx failed. I reduced the max amount to remove all the decimal numbers and used a whole number instead and it worked

### PR DESCRIPTION
**Pull request by danjm**
Fixes: https://github.com/MetaMask/metamask-extension/issues/11593

With the send slice refactor, we stopped correctly re-estimating gas limit when setting "Max" in the send flow. This PR ensures that is done correctly.

### CODE REVIEW

**Review by ryanml — DISMISSED** [review]

**Review by LeHoang88 — DISMISSED** [review]

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -1326,6 +1326,7 @@ export function toggleSendMaxMode() {
       await dispatch(actions.updateAmountMode(AMOUNT_MODES.MAX));
       await dispatch(actions.updateAmountToMax());
     }
+    await dispatch(computeEstimatedGasLimit());
```
Comment (adonesky1) [inline ui/ducks/send/send.js:1329]: @danjm Do we want to do this for non-token sends?

Comment (danjm) [reply ui/ducks/send/send.js:1329]: Yes, in case custom networks like optimism need it

Comment (danjm) [reply ui/ducks/send/send.js:1329]: We could not do it for non-token sends on mainnet

Comment (adonesky1) [reply ui/ducks/send/send.js:1329]: hmmm yeah maybe... Looking a bit more through the send slice, it looks like in the updateSendAmount action creator we are not recomputing the gas limit for non-token assets when the amount is updated, which as you point out for custom networks (like optimism) may cause an issue?

Comment (adonesky1) [reply ui/ducks/send/send.js:1329]: ^^^ https://github.com/MetaMask/metamask-extension/blob/4e87069af3619db2307e08e1d577621339eab3cc/ui/ducks/send/send.js#L1167

Comment (adonesky1) [reply ui/ducks/send/send.js:1329]: @danjm this isn't a blocker. Just raising it here because you've pointed out that we shouldn't use the asset_type to decide whether or not to recompute gas

**Review by adonesky1 — DISMISSED** [review]
A nonblocking/comment question is still open. Otherwise LGTM

File: ui/ducks/send/send.js (hunk 1 above)
Comment (danjm) [reply ui/ducks/send/send.js:1329]: right, and that could also matter if the user was sending to a contract address that is something other than a token

Comment (adonesky1) [reply ui/ducks/send/send.js:1329]: Should I write up a ticket for this?

**Comment by danjm** [comment]
@adonesky1 Just pushed a change to address our comments above.

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Review by Russell4115 — APPROVED** [review]

**Review by ryanml — APPROVED** [review]

**Review by Russell4115 — APPROVED** [review]
