### PR TITLE
fix: account sorting for snap accounts that derive entropySource cp-12.18.0

### LINKED ISSUE #32653: [Bug]: SRPs are not coming in ordered with discoverAccounts method
### Describe the bug

SRPs are coming in unordered when discoveredAccounts is triggered. This leads to SRP pills + accounts being placed all throughout the list in no coherent manner. 

### Expected behavior

Accounts should be ordered sequentially with SRP

### Screenshots/Recordings

Image

### Steps to reproduce

1. Open fresh MM
2. Import random SRP that won’t trigger discoverAccounts. Notice that SRPs are ordered
3. Import an SRP where SRP will trigger discoverAccounts

Message for sample SRP if needed

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.18

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

Jira ticket https://consensyssoftware.atlassian.net/jira/software/projects/MMMULTISRP/boards/721?selectedIssue=MMMULTISRP-207

### Severity

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR fixes the account sorting order where discovered accounts are not sorted with their srp. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32690?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32653
Resolves: https://consensyssoftware.atlassian.net/browse/MMMULTISRP-207?atlOrigin=eyJpIjoiYTlhZGQ0NjMyNjQxNGRmZGEyNjAyYzI4ZGRjYjQzZDAiLCJwIjoiaiJ9

## **Manual testing steps**

1. Open fresh srp
2. Import a srp where it won't discover accounts 
3. Import a srp where it won't discover accounts 
4. See that the accounts are still sorted

### **Before**
Screenshot 2025-05-08 at 23 17 19

### **After**
Screenshot 2025-05-08 at 23 17 01

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/selectors/selectors.js [hunk 1]
```diff
@@ -536,15 +536,41 @@ export const getInternalAccountsSortedByKeyring = createDeepEqualSelector(
   getMetaMaskKeyrings,
   getMetaMaskAccounts,
   (keyrings, accounts) => {
+    const thirdpartySnaps = 'thirdpartySnaps';
+    // Create a map of entropySource map to accounts for quick lookup
+    const entropySourceToAccountsMap = Object.values(accounts).reduce(
+      (map, account) => {
+        if (account.metadata?.keyring?.type === KeyringTypes.snap) {
+          const { entropySource = thirdpartySnaps } = account.options || {};
```
Comment (gantunesr) [inline ui/selectors/selectors.js:544]: I assume we can't execute a migration to populate this data, is that right?

File: ui/selectors/selectors.js [hunk 2]
```diff
@@ -536,15 +536,41 @@ export const getInternalAccountsSortedByKeyring = createDeepEqualSelector(
...
+      if (keyring.type === KeyringTypes.hd) {
+        const snapAccounts =
+          entropySourceToAccountsMap[keyring.metadata.id] || [];
+        return [...internalAccounts, ...keyringAccounts, ...snapAccounts];
+      } else if (keyring.type === KeyringTypes.snap) {
+        const thirdpartySnapAccounts =
+          entropySourceToAccountsMap[thirdpartySnaps] || [];
+        return [...internalAccounts, ...thirdpartySnapAccounts];
+      }
+      return [...internalAccounts, ...keyringAccounts];
```
Comment (gantunesr) [inline ui/selectors/selectors.js:572]: I think it is a bit faster if you just push the new elements into internalAccounts instead of generating a new array for every iteration

```suggestion
      // If it's an HD keyring, add any snap accounts that belong to it
      if (keyring.type === KeyringTypes.hd) {
        const snapAccounts =
          entropySourceToAccountsMap[keyring.metadata.id] || [];
        internalAccounts.push(...keyringAccounts, ...snapAccounts);
        return internalAccounts;
      } else if (keyring.type === KeyringTypes.snap) {
        const thirdpartySnapAccounts =
          entropySourceToAccountsMap[thirdpartySnaps] || [];
        internalAccounts.push(...thirdpartySnapAccounts);
        return internalAccounts;
      }
      internalAccounts.push(...keyringAccounts);
      return internalAccounts;
```

**Review by gantunesr — COMMENTED** [review]
looks good! left some minor suggestions

File: ui/selectors/selectors.js (hunk 1 above)
Comment (montelaidev) [reply ui/selectors/selectors.js:544]: Correct, we currently have no way to migrate snap data.

**Review by NidhiKJha — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]
