### PR TITLE
Ensure that all networkConfiguration object in networkController state have an id

### LINKED ISSUE #18453: [Bug]: RPC Error when switching network on 10.28.1
### Describe the bug

I just updated to 10.28.1 and I get an error when trying to switch networks from various dapps, including app.aave.com. I am able to add the network, but if I have previously added the network and just try to switch to the network from the dapp the console shows the following message: `RPC Error: networkConfigurationId [object Object] does not match a configured networkConfiguration `

### Steps to reproduce

1. Install 10.28.1
2. Go to app.aave.com testnet
3. Go to a modal for a network that you aren't connected to (e.g. Fantom) and click on switch network. Add network by clicking "switch network".
4. Switch back to another network (e.g. Ethereum mainnet) and repeat step 3. This time, aave will show a cannot switch network error, and you will see aforementioned error in the developer console.

### Error messages or log output

```shell
RPC Error: networkConfigurationId [object Object] does not match a configured networkConfiguration
```

### Version

10.28.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #18509: [Bug]: wallet_switchEthereumChain no longer working after update to 10.28.2 Chrome
### Describe the bug

After the release of `10.28.2` `wallet_switchEthereumChain` is no longer working. Error in console is `{code: -32603, message: 'networkConfigurationId undefined does not match a configured networkConfiguration', data: {…}}`. `10.28.1` has an issue where user has to approve the function twice. Downgrading to `10.26.1` allowed the `wallet_switchEthereumChain` to function. (Did not try versions between 10.26.1 and 10.28.1) It appears that the issue only happens when switching to a chain other than Ethereum but can not confirm 100%

### Steps to reproduce

1. Ensure that extension version `10.28.2` is installed in Chrome Desktop. 
2. Visit a site which utilizes `wallet_switchEthereumChain`, trade.coinbook.app is an example.
3. Utilize Network dropdown on DAPP to select a chain to switch to. Metamask will open with correct chain swicth prompt. Error is logged after clicking Approve. 
4. Depending on DAPP configuration there may be a catch that calls `wallet_addEthereumChain` on error. 

### Error messages or log output

```shell
{code: -32603, message: 'networkConfigurationId undefined does not match a configured networkConfiguration', data: {…}}
```

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/18509
Fixes https://github.com/MetaMask/metamask-extension/issues/18453

## Explanation

We partially fixed the symptom of 18509 and 18453 with https://github.com/MetaMask/metamask-extension/pull/18483, but that fix was incomplete.

This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp wallet_addEthereumChain request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1

The problem is that migration 82 did not add an `id` property to each network configuration object, but we assume that `id` property exists in the `switch-ethereum-chain.js` handler. If a user adds a network on version v10.27.0 or earlier, and then updates to v10.28.x, migration 82 will create an object within `NetworkController.networkConfigurations` keyed by a random id, but that `id` will not be added to that object itself. Later, when we attempt to switch to the network using that objects `id` property, it fails. It does not fail if the network is added while on v10.28.x, because the `upsertNetworkConfiguration` method, which is called when adding a network on v10.28.x, adds an `id` property to each network.

This PR corrects the problem with a migration that ensures that the each key within `networkConfigurations` is used to set the `id` property of the respective object.

### Before

This video shows what would happen when upgrading from v10.27.0 -> v10.28.2 and then trying to switch to a previously added network:

https://user-images.githubusercontent.com/7499938/230714011-86eef63c-b54d-4b79-b51c-1903e1016a27.mp4

### After

This shows switch network working after an upgrade from v10.27.0 to the branch of this PR:

https://user-images.githubusercontent.com/7499938/230714738-16fa8e2e-be3e-4c71-94b3-01220bb618b8.mp4

## Manual Testing Steps

Do as is done in the above "After" video:

1. Build v10.27.0, from d8591d48c, install and onboard
2. Go to https://syncswap.xyz/, connect and add the suggested network
3. In MetaMask, select Ethereum Mainnet, so that the zkSync network is not selected
4. git checkout this branch, build and then reload the metamask installation that was previously built from v10.27.0
5. login to MetaMask and then go to https://syncswap.xyz/
6. click "Connect Wallet" and confirm the switch network popup
7. open MetaMask, you should now have the zksync network selected

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by danjm** [comment]
This will require https://github.com/MetaMask/metamask-extension/pull/18512#pullrequestreview-1376744678 to get the build passing.

File: app/scripts/migrations/084.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+  const newNetworkConfigurations: Record<string, object> = {};
+
+  for (const networkConfigurationId in networkConfigurations) {
+    if (
+      Object.prototype.hasOwnProperty.call(
+        networkConfigurations,
+        networkConfigurationId,
+      )
+    ) {
```
Comment (adonesky1) [inline app/scripts/migrations/084.ts:44]: I'm probably missing something here but why is this check necessary? Won't the `networkConfigurationId` necessarily be a property of `networkConfigurations` as its defined in this the for-in loop?

**Comment by adonesky1** [comment]
It probably does make sense to fix the state here but - just a thought - another lighter weight way to fix this (I think) would be to modify the `findNetworkConfigurationBy` method on `MetamaskController` like this:

```
   findNetworkConfigurationBy(rpcInfo) {
     const { networkConfigurations } = this.networkController.store.getState();
-    const networkConfiguration = Object.values(networkConfigurations).find(
-      (configuration) => {
-        return Object.keys(rpcInfo).some((key) => {
-          return configuration[key] === rpcInfo[key];
-        });
-      },
-    );
+    const [id, networkConfiguration] = Object.entries(
+      networkConfigurations,
+    ).find((configuration) => {
+      return Object.keys(rpcInfo).some((key) => {
+        return configuration[key] === rpcInfo[key];
+      });
+    });
 
-    return networkConfiguration || null;
+    return { ...networkConfiguration, id } || null;
   }
   ```

**Review by legobeat — DISMISSED** [review]
LGTM

**Review by DDDDDanica — DISMISSED** [review]

File: app/scripts/migrations/084.ts (hunk 1 above)
Comment (Gudahtt) [reply app/scripts/migrations/084.ts:44]: Nit: This check could be skipped if the look was `for (const configurationId of Object.keys(networkConfigurations)) { `instead.

File: app/scripts/migrations/084.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+  versionedData.meta.version = version;
+  versionedData.data = transformState(versionedData.data);
+  return versionedData;
+}
+
+function transformState(state: Record<string, unknown>) {
+  if (!isObject(state.NetworkController)) {
+    return state;
+  }
+  const { NetworkController }: any = state;
```
Comment (Gudahtt) [inline app/scripts/migrations/084.ts:30]: Nit: What purpose is the `: any` serving here? It seems that it's making the type less specific (it's changing it from `RuntimeObject` to `any`)

File: app/scripts/migrations/084.ts [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+  const {
+    networkConfigurations,
+  }: { networkConfigurations: Record<string, object> } = NetworkController;
+
+  const newNetworkConfigurations: Record<string, object> = {};
```
Comment (Gudahtt) [inline app/scripts/migrations/084.ts:36]: Nit: We can be more specific here than `object`:

```suggestion
  const newNetworkConfigurations: Record<string, Record<string, unknown>> = {};
```

File: app/scripts/migrations/084.ts (hunk 2 above)
Comment (Gudahtt) [reply app/scripts/migrations/084.ts:30]: Oh I see, this is disabling type checking. The object spread operator below requires us to check that each of the old network configuration entries is an object, but we skipped that check because type checking was disabled here when this was set to `any`.

File: app/scripts/migrations/084.test.js [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+      data: {},
+    };
+
+    const newStorage = await migrate(oldStorage);
+    expect(newStorage.meta).toStrictEqual({
+      version,
+    });
+  });
+
+  it('should use the key of the networkConfigurations object to set the id of each network configuration', async () => {
```
Comment (Gudahtt) [inline app/scripts/migrations/084.test.js:38]: Nit: We should have tests for the error scenarios as well (e.g. each level of state being missing, or being a non-object type)

File: app/scripts/migrations/084.ts (hunk 2 above)
Comment (danjm) [reply app/scripts/migrations/084.ts]: `any` removed in 8116d9fe46

**Review by adonesky1 — DISMISSED** [review]
LGTM!

File: app/scripts/migrations/084.ts (hunk 2 above)
Comment (Gudahtt) [reply app/scripts/migrations/084.ts]: The `any` was removed, but the required type checks have not been added yet. The type errors are the reason CI is failing

Comment (Gudahtt) [reply app/scripts/migrations/084.ts:30]: To start with, I'd recommend not adding explicit types to variable declarations if the type can be inferred instead. The error here is a result of the inferred type being incompatible with the type you've declared.

It is necessary to declare a type in cases where there is no way for it to be inferred correctly. For example, the `newNetworkConfigurations` variable below, which is assigned to an empty object initially. The inferred type would be `{}`, which isn't correct, so an explicit type was required there. But here the type can be inferred directly from the assigned value.

Putting that issue aside, if you drop both unnecessary type declarations here, then `networkConfigurations` will end up as type `RuntimeObject` (e.g. `Record<string, unknown>`). This ends up failing on this line:

```
    newNetworkConfigurations[networkConfigurationId] = {
      ...networkConfigurations[networkConfigurationId],
      id: networkConfigurationId,
    };
```
with the error "Spread types may only be created from object types".

That is, you're assuming that the value (typed as `unknown`) is an object.

This can be fixed by adding another type check inside the loop, ensuring that any pre-existing configuration used is also an object. That's what I meant here:

>The object spread operator below requires us to check that each of the old network configuration entries is an object

**Review by adonesky1 — DISMISSED** [review]

File: app/scripts/migrations/084.ts (hunk 2 above)
Comment (danjm) [reply app/scripts/migrations/084.ts]: okay, thank-you

I have attempted to make improvements in line with your above comment here affa96040e

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by adonesky1 — APPROVED** [review]
