### PR TITLE
fix: network form

### LINKED ISSUE #32085: [Bug]: GNS UI DEPENDENCY testing plan: NFT filtering in SEND flow does not work
### Describe the bug

During the SEND flow, in the NFT tab all the NFTs are visible, not just the ones of the currently selected network.

Sending an NFT on a network it doesn't exist is possible, resulting in a 0 native token transaction on that network.

### Expected behavior

To see in the SEND flow only the NFTs of the currently selected network, not all of them. 

As it happens for Tokens in the Send flow.

### Screenshots/Recordings

[Loom video](https://www.loom.com/share/7a4bba3c82c648acbcd848b944e5d659?sid=0fb4be60-949a-4828-9d23-4d8439b01d63)

### Steps to reproduce

1. Have NFTs on multiple popular networks
2. Start Send flow
3. Click on NFTs tab
4. Switch networks
5. Notice the NFTs tab always displays all NFTs of all the popular networks, and the filtering is not working

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

12.15.2

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Windows, MacOS

### Hardware wallet

_No response_

### Additional context

QA build

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

This PR addresses two issues:

- When an enabled network is deleted, its native token was still appearing in the asset list. This fix ensures the native token is properly removed when its corresponding network is deleted.
- NFT filtering was not working correctly in the Send flow. This fix restores proper filtering behavior when sending NFTs.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34070?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: #32085 #34057 

## **Manual testing steps**

1. Delete network
2. check the token list
3. native token of the deleted network should not be displayed
4. NFT of deleted network should not be able to send

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by kikiki1378 — APPROVED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: ui/components/multichain/network-manager/network-manager.tsx [hunk 1]
```diff
@@ -76,7 +81,13 @@ const NetworkManagerRouter = () => {
           ],
           defaultRpcEndpointIndex: networkFormState.rpcUrls.rpcEndpoints.length,
         });
-        history.push('/add');
+
+        // TODO: Handle edit case
```
Comment (darkwing) [inline ui/components/multichain/network-manager/network-manager.tsx]: Is this still a TODO?

File: ui/hooks/useNfts.ts [hunk 2]
```diff
@@ -38,6 +38,10 @@ export function useNfts({
       // Filter NFTs to only include those from enabled networks
       const nftsFromEnabledNetworks: Record<string, NFT[]> = {};
 
+      if (overridePopularNetworkFilter) {
+        return allUserNfts?.[chainId] ?? [];
```
Comment (darkwing) [inline ui/hooks/useNfts.ts:42]: Should we make `[]` a top level constant so we avoid this somehow triggering more rerenders?

Comment (salimtb) [reply ui/hooks/useNfts.ts:42]: emmm not sure i got what you mean here

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: ui/components/multichain/network-list-menu/select-rpc-url-modal/select-rpc-url-modal.tsx [hunk 3]
```diff
@@ -21,19 +22,28 @@ import {
...
 }) => {
   const dispatch = useDispatch();
+  const location = useLocation();
+  const chainId = location.state?.chainId;
+
+  const [, evmNetworks] = useSelector(
+    getMultichainNetworkConfigurationsByChainId,
+  );
+  const networkConfigurationToUse =
+    networkConfiguration ?? evmNetworks[chainId as keyof typeof evmNetworks];
```
Comment (bergarces) [inline ui/components/multichain/network-list-menu/select-rpc-url-modal/select-rpc-url-modal.tsx:42]: What if `networkConfiguration` and `chainId` are `undefined`?

Comment (salimtb) [reply ui/components/multichain/network-list-menu/select-rpc-url-modal/select-rpc-url-modal.tsx:42]: I don’t think this case is possible — networkConfiguration is a hardcoded list that always includes at least Ethereum, Linea, and Base, as it refers to the default networks.

**Review by bergarces — DISMISSED** [review]

**Review by bergarces — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by bergarces — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
