### PR TITLE
fix: Catch  errors from the assets controller

### LINKED ISSUE #25212: [Bug]: Import NFTs modal error handling for `getTokenStandardAndDetails`
### Describe the bug

The Import NFTs modal uses `getTokenStandardAndDetails`, but doesn't appear to handle errors when that function is called. This is problematic because `getTokenStandardAndDetails` is expected to fail for certain inputs, or if it's unable to determine the token standard for any reason. We need to handle the error case whenever this is used. 

An error thrown by `getTokenStandardAndDetails` would interrupt the process of adding the NFT without telling the user, and it would get reported to Sentry.

### Expected behavior

- Errors thrown by `getTokenStandardAndDetails` are caught and handled appropriately, not sent to Sentry
- When `getTokenStandardAndDetails` fails during the process of adding an NFT, we either:
  - Abort the operation and tell the user that it failed, or
  - Move forward with the operation without the result of `getTokenStandardAndDetails`

### Screenshots/Recordings

_No response_

### Steps to reproduce

I am unsure how to trigger the specific error cases, but the affected code paths are there. You can find impacted code paths by looking for `getTokenStandardAndDetails` calls in the codebase. All invocations of that function should either be in a `try..catch` block, or should be in a function that itself is always invoked in a `try...catch` block.

### Error messages or log output

_No response_

### Version

v12.0.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

This PR addresses a group of errors reported on Sentry that occur when `getTokenStandardAndDetails` in `assetsContractController` returns "Unable to determine contract standard". [Sentry Issue Link](https://metamask.sentry.io/issues/5660074561/?project=273505&query=is%3Aunresolved%20getTokenStandardAndDetails&referrer=issue-stream&sort=date&statsPeriod=7d&stream_index=0).

The error happens fairly often because only contracts that strictly adhere to the standard ABIs for ERC20, ERC721, and ERC1155 are correctly parsed. When a contract does not conform to these standards, the function fails and throws an error.

This PR introduces error handling to catch and silence the error when assetsContractController.getTokenStandardAndDetails fails to determine the contract standard. The control flow of the function is adjusted to ensure it continues to execute normally even when the error is caught.

### Changes

- Added a try...catch block around the assetsContractController.getTokenStandardAndDetails call to catch and log the error.

- Ensured that the function continues to execute and return appropriate details even when the error is caught.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29439?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25212

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -4518,39 +4518,46 @@ export default class MetamaskController extends EventEmitter {
...
-      );
+      try {
+        details =
+          await this.assetsContractController.getTokenStandardAndDetails(
+            address,
+            userAddress,
+            tokenId,
+          );
+      } catch (e) {
+        log.error(`Failed to get token standard and details. Error: ${e}`);
```
Comment (matthewwalsh0) [inline app/scripts/metamask-controller.js:4529]: Is it worth an error if this is common, could we also do a `warn` as below?

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by jpuri — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
