### PR TITLE
fix: DAPP initiated swaps in MetaMask

### LINKED ISSUE #24336: [Bug]: MetaMask encounters errors when processing transactions initiated from dapp
### Describe the bug

MetaMask encounters errors when processing transactions initiated from dapps.

### Expected behavior

Smooth and accurate transaction handling in scenarios involving extensive numerical data.

### Screenshots/Recordings

Ethereum mainnet, Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/4ff70c21-8a29-411f-a6e6-8a81bc6f1993

Polygon, Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/3f2442cb-ac08-4794-a37a-2ac12965e32b

Screenshot 2024-05-01 at 18 29 58

Polygon, Firefox:

https://github.com/MetaMask/metamask-extension/assets/104780023/64f61a7e-b871-461e-9982-bd3c781f4afe

Different error message for shorter number:

Screenshot 2024-05-01 at 19 32 08

https://github.com/MetaMask/metamask-extension/assets/104780023/962ad496-9d78-4994-aea2-a1e9aaf58f19

### Steps to reproduce

1. Go to Uniswap / Pancakeswap etc.
2. Start swap transaction 
3. Proceed to MetaMask confirmation screen
4. See the error

### Error messages or log output

_No response_

### Version

11.16.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Swaps initiated by DAPPS are throwing error in MetaMask.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24336

## **Manual testing steps**

1. Go to Uniswap / Pancakeswap etc.
2. Start swap transaction
3. Proceed to MetaMask confirmation screen
4. Ensure no error is there

## **Screenshots/Recordings**
Screenshot 2024-05-06 at 9 28 12 AM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
Dev build [ddf99f1](https://github.com/MetaMask/metamask-extension/pull/24382/commits/ddf99f12c8efd8caaaff1e8bd0c698a94eec9b50)

Swaps initiated from dapps can be successfully submitted:


https://github.com/MetaMask/metamask-extension/assets/104780023/0590101a-acd3-49d7-98f7-319d88746116

**Review by sleepytanya — APPROVED** [review]

File: ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts [hunk 1]
```diff
@@ -124,7 +124,9 @@ function getTokenBalanceChanges(
     };
 
     const decimals =
-      asset.standard === TokenStandard.ERC20 ? erc20Decimals[asset.address] : 0;
+      asset.standard === TokenStandard.ERC20 && erc20Decimals[asset.address]
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts:127]: Should we go deeper and ask why there is missing decimals for an address?

When we query the decimals for a single token in `fetchErc20Decimals`, we fallback to `ERC20_DEFAULT_DECIMALS` if the response is bad, or if there is an error, so I'm not sure how this could happen.

We also wouldn't want to fallback to zero decimals if the token was an ERC-20, only for any other standard.

File: ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts [hunk 2]
```diff
@@ -106,7 +106,7 @@ function getNativeBalanceChange(
   }
   const asset = NATIVE_ASSET_IDENTIFIER;
   const amount = getAssetAmount(nativeBalanceChange, NATIVE_DECIMALS);
-  const fiatAmount = amount.times(nativeFiatRate).toNumber();
+  const fiatAmount = amount?.times(nativeFiatRate).toNumber();
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts:109]: As below, do we need to ask why the amount is `null` or `undefined`?

`getAssetAmount` just appears to primarily parse the value but we return `undefined` above if it was missing.

Does this suggest the `difference` value in the `simulationData` is bad?

**Review by vinistevam — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

File: ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts (hunk 1 above)
Comment (dbrans) [reply ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts:127]: @jpuri, echoing @matthewwalsh0's point, previously we set decimals to zero only for non-ERC20 tokens, like ERC721 or ERC1155. This is because ERC721 and ERC1155 tokens are indivisible and cannot have decimals. This change, however, introduces fallback logic that sets the decimals to zero for some ERC20s, which isn't our goal. 

Matt also mentioned that it's unexpected for erc20Decimals[asset.address] to be undefined, as we're supposed to fetch decimals for all ERC20 addresses through fetchErc20Decimals, where we already have a default handling mechanism.

It would be better to look into why this is happening rather than adding more fallback logic.

File: ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts (hunk 2 above)
Comment (dbrans) [reply ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts:109]: Looking at the return type of getAssetAmount, BigNumber, this should never be undefined.
