### PR TITLE
1061 linting tests

### LINKED ISSUE #1061: tests - lint doesnt include tests
this can lead to dumb mistakes where theres a syntax error or using an undefined var (which gets swallowed by a promise?) and tests fail with no indication of why

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #1061 Added plugins for eslinting mocha and chai and linted tests

### CODE REVIEW

File: test/unit/currency-controller-test.js [hunk 1]
```diff
@@ -2,86 +2,83 @@
 global.fetch = global.fetch || require('isomorphic-fetch')
 
 const assert = require('assert')
-const extend = require('xtend')
-const rp = require('request-promise')
+// const extend = require('xtend')
+// const rp = require('request-promise')
```
Comment (kumavis) [inline test/unit/currency-controller-test.js]: please remove

File: test/unit/keyring-controller-test.js [hunk 2]
```diff
@@ -3,32 +3,31 @@ const KeyringController = require('../../app/scripts/keyring-controller')
 const configManagerGen = require('../lib/mock-config-manager')
 const ethUtil = require('ethereumjs-util')
 const BN = ethUtil.BN
-const async = require('async')
+// const async = require('async')
 const mockEncryptor = require('../lib/mock-encryptor')
-const MockSimpleKeychain = require('../lib/mock-simple-keychain')
+// const MockSimpleKeychain = require('../lib/mock-simple-keychain')
```
Comment (kumavis) [inline test/unit/keyring-controller-test.js]: please remove

File: test/unit/message-manager-test.js [hunk 3]
```diff
@@ -1,29 +1,29 @@
 const assert = require('assert')
-const extend = require('xtend')
-const EventEmitter = require('events')
+// const extend = require('xtend')
+// const EventEmitter = require('events')
```
Comment (kumavis) [inline test/unit/message-manager-test.js]: please remove

File: test/unit/notice-controller-test.js [hunk 4]
```diff
@@ -1,42 +1,42 @@
 const assert = require('assert')
-const extend = require('xtend')
-const rp = require('request-promise')
-const nock = require('nock')
+// const extend = require('xtend')
+// const rp = require('request-promise')
+// const nock = require('nock')
```
Comment (kumavis) [inline test/unit/notice-controller-test.js]: please remove

File: test/unit/personal-message-manager-test.js [hunk 5]
```diff
@@ -1,29 +1,29 @@
 const assert = require('assert')
-const extend = require('xtend')
-const EventEmitter = require('events')
+// const extend = require('xtend')
+// const EventEmitter = require('events')
```
Comment (kumavis) [inline test/unit/personal-message-manager-test.js]: please remove

File: test/unit/tx-manager-test.js [hunk 6]
```diff
@@ -1,64 +1,64 @@
 const assert = require('assert')
-const extend = require('xtend')
+// const extend = require('xtend')
 const EventEmitter = require('events')
 const ethUtil = require('ethereumjs-util')
 const EthTx = require('ethereumjs-tx')
 const ObservableStore = require('obs-store')
-const STORAGE_KEY = 'metamask-persistance-key'
+// const STORAGE_KEY = 'metamask-persistance-key'
```
Comment (kumavis) [inline test/unit/tx-manager-test.js]: please remove

**Review by kumavis — CHANGES_REQUESTED** [review]
nice work - though this PR touches a lot of files and every time that happens we have a risk of conflicts with active PRs. The timing is good bc most of the team is at IIW, but i see there are a few PRs open. Hopefully not a big issue as most changes are in tests.

Please remove the commented out requires, if we don't need them

👍

**Review by kumavis — APPROVED** [review]
looks good please get the last commented requires and merge 👍

**Review by kumavis — APPROVED** [review]
