### PR TITLE
fix: update extension-port-stream to enable chunking of large port stream messages into smaller frames to avoid chromium's Port message size limits

### LINKED ISSUE #29795: [Bug]: Infinity crashing, can't start it
### Describe the bug

I click on it, it "loads" for 10 seconds, then it crashes. First it did it in one Chrome profile, and I stopped using it there. Then it did the same in another profile.

### Expected behavior

Not this.

### Screenshots/Recordings

Image

### Steps to reproduce

I can replicate the issue by just doing 20-30 transactions in a row with a lot of calldata. Afterwads, MetaMask doesn't open anymore. 

How to clear the transaction data from the Metamask local database without losing the wallets?

### Error messages or log output

```shell
"""md
SCRIPTS IMPORT COMPLETE in Seconds: 1.8
sentry-install.js:1 MetaMask initialization complete.
sentry-install.js:1 RPC (https://metamask.github.io): metamask_getProviderState -> success
sentry-install.js:1 RPC (https://metamask.github.io): metamask_sendDomainMetadata -> success

sentry-install.js:1 **(Error#1)**
(anonymous) @ sentry-install.js:1
(anonymous) @ sentry-install.js:3
error @ runtime-lavamoat.js:7134
(anonymous) @ common-0.js:1
(anonymous) @ common-8.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ common-8.js:1
(anonymous) @ common-8.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ common-8.js:1
d @ common-8.js:1
(anonymous) @ common-5.js:13
y @ common-5.js:13
m @ common-5.js:13
(anonymous) @ sentry-install.js:1
(anonymous) @ common-7.js:1
h @ common-7.js:1
(anonymous) @ sentry-install.js:1
i @ sentry-install.js:3
**setTimeout**
(anonymous) @ sentry-install.js:1
(anonymous) @ sentry-install.js:3
(anonymous) @ runtime-lavamoat.js:12866
(anonymous) @ runtime-lavamoat.js:12866
(anonymous) @ runtime-lavamoat.js:12866
u @ common-7.js:1
(anonymous) @ common-7.js:1
C @ common-8.js:1
I @ common-8.js:1
S @ common-8.js:1
(anonymous) @ common-8.js:1
_write @ common-1.js:1
S @ common-8.js:1
(anonymous) @ common-8.js:1
(anonymous) @ common-8.js:1
l @ common-5.js:13
(anonymous) @ common-5.js:13
H @ common-5.js:13
U @ common-5.js:13
F.push @ common-5.js:13
_onMessage @ common-5.js:13
(anonymous) @ common-5.js:13Understand this errorAI

sentry-install.js:1 **Error#1: PortDuplexStream - disconnected**
(anonymous) @ sentry-install.js:1
(anonymous) @ sentry-install.js:3
logError @ runtime-lavamoat.js:7087
logSubErrors @ runtime-lavamoat.js:7030
error @ runtime-lavamoat.js:7136
(anonymous) @ common-0.js:1
(anonymous) @ common-8.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ common-8.js:1
(anonymous) @ common-8.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ common-8.js:1
d @ common-8.js:1
(anonymous) @ common-5.js:13
y @ common-5.js:13
m @ common-5.js:13
(anonymous) @ sentry-install.js:1
(anonymous) @ common-7.js:1
h @ common-7.js:1
(anonymous) @ sentry-install.js:1
i @ sentry-install.js:3
setTimeout
(anonymous) @ sentry-install.js:1
(anonymous) @ sentry-install.js:3
(anonymous) @ runtime-lavamoat.js:12866
(anonymous) @ runtime-lavamoat.js:12866
(anonymous) @ runtime-lavamoat.js:12866
u @ common-7.js:1
(anonymous) @ common-7.js:1
C @ common-8.js:1
I @ common-8.js:1
S @ common-8.js:1
(anonymous) @ common-8.js:1
_write @ common-1.js:1
S @ common-8.js:1
(anonymous) @ common-8.js:1
(anonymous) @ common-8.js:1
l @ common-5.js:13
(anonymous) @ common-5.js:13
H @ common-5.js:13
U @ common-5.js:13
F.push @ common-5.js:13
_onMessage @ common-5.js:13
(anonymous) @ common-5.js:13Understand this errorAI

sentry-install.js:1   **at o._write** (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:13:550465)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:13:611855
  at C (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:13:611923)
  at I.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:13:615291)
  at c.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:27737)
  at c.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:13:546666)
  at I (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:22542)
  at S (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:22372)
  at c.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:23159)
  at i._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:1:733016)
  at S (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:37745)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:40845
  at i.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:40872)
  at i.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:472288)
"""
```

### Detection stage

In production (default)

### Version

12.10.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Ledger

### Additional context

_No response_

### Severity

10/10 terrible

### PR DESCRIPTION
**Pull request by davidmurdoch**
## **Description**

Prevents unresponsive UI in the case where the user has more than 64MB of state that needs to be transferred from the background to the UI. The trade off here is that we now allow the state size to increase until the memory the browser has allotted for the extension process runs out (and crashes with an out of memory error).

We could potentially further improve the `extension-port-stream` code by adding a mutex (per instance or maybe even a singleton) to prevent attempting sending large amounts of state in parallel. This will slow down the application considerably, but would help prevent OOM errors. It cannot stop or prevent them all together though. This situation can happen if MM is opened in multiple tabs at the same time, or sometimes even when sending `patch`es.

I think we need to re-evaluate the "sync the whole state" idea and possibly re-imagine it from the ground up to only sync the state that is required by the current UI. I think this would be a very difficult effort.

~Depends on https://github.com/MetaMask/metamask-extension/pull/33211~

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33165?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: prevent unresponsive UI in the case where the user has more than 64MB of state; the trade off is that we now allow state size to increase until the memory the browser has allotted for the extension process runs out (and crashes).

## **Related issues**

~Extension Port Stream PR: https://github.com/MetaMask/extension-port-stream/pull/68~
Fixes: https://github.com/MetaMask/metamask-extension/issues/29795

## **Manual testing steps**

1. checkout `main`, run `yarn start` (or `yarn webpack`) to generate a build
2. add this build from step 0 to your browser
3. start ganache by running `yarn ganache -d -f -v -a 1`
4. follow the instructions at https://codepen.io/davidmurdoch/full/pvJjZww
5. checkout this branch (`update-extension-port-stream`), run `yarn start` (or `yarn webpack`) to generate a build
6. reload the extension in your browser
7. Your previously bricked MetaMask should work again!
8. Bonus: You can also keep sending even more "airdrops"!

Note: MetaMask will still be sluggish due to the large state, that issue will be fixed by a refactor of the [`TransactionController`](https://github.com/MetaMask/core/tree/main/packages/transaction-controller) by the @MetaMask/confirmations team to reduce the size of the controller's state object.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Upgrade to ExtensionPortStream and enable chunked port messaging, wire it across extension streams, track chunking via MetaMetrics, add E2E test, and update dependencies and LavaMoat policies.
> 
> - **Streams/Background & UI**:
>   - Replace `PortStream` with `ExtensionPortStream` in `app/scripts/background.js`, `app/scripts/ui.js`, and all stream modules (`provider-stream.ts`, `phishing-stream.ts`, `cookie-handler-stream.ts`).
>   - Handle `message-too-large` by emitting MetaMetrics event; set `{ chunkSize: 0 }` for phishing/cookie/externally connectable paths; simplify CAIP stream teardown.
> - **Analytics**:
>   - Add MetaMetrics constants: `MetaMetricsEventName.PortStreamChunked` and category `MetaMetricsEventCategory.PortStream`.
> - **Tests**:
>   - Add E2E `port-stream-chunking.spec.ts` to validate UI loads with huge state and that chunking event is tracked (excluding Firefox).
> - **Dependencies/Policies**:
>   - Bump `extension-port-stream` to `^5.0.0` and `readable-stream` to `^4.7.0`; update `yarn.lock`.
>   - Update LavaMoat policies to new `readable-stream` paths/globals and `extension-port-stream` allowances.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit fc5da8de0242c18570f7fb4e3d2b18a38bdc9573. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

**Comment by seaona** [comment]
hi there 👋 
I've followed the detailed instructions, and I've seen the following:
- At the main build, I successfully got the MM loading indefinetly (crashed)
- I updated to this branch and MM was working again
- I could perform 4 or 5 more transactions, but after that, I saw MM crashed and in a different way. Instead of loading indefinetly I got to this blank page:

Are you able to reproduce it?

image



https://github.com/user-attachments/assets/c2efc31d-caa3-4189-95d8-b14721429abc

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

**Comment by davidmurdoch** [comment]
> hi there 👋 I've followed the detailed instructions, and I've seen the following:
> 
> * At the main build, I successfully got the MM loading indefinetly (crashed)
> * I updated to this branch and MM was working again
> * I could perform 4 or 5 more transactions, but after that, I saw MM crashed and in a different way. Instead of loading indefinetly I got to this blank page:
> 
> Are you able to reproduce it?
> 

I was able to reproduce the crash. It is caused by chrome running out of memory for the process. I'm unsure if the port stream code is the right place to fix this.

I also noticed that we are constantly sending "patch updates" of state to the UI, once every 2-10 seconds. These patch updates contain all of our transactions, which triggers the chunking process as well. I'm not sure why this is happening; I don't think it is supposed to send what it is _already_ sent.

Additionally, once I crashed the process, I was unable to get the UI back to a usable state. It seems as though all snaps initialization was crashing - but I'm not sure if that was the _cause_ of the application not starting, or an effect of the application not starting.

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

**Comment by davidmurdoch** [comment]
@SocketSecurity ignore npm/axios@1.10.0

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

File: app/scripts/background.js [hunk 1]
```diff
@@ -1136,8 +1136,31 @@ export function setupController(
...
+      const handleMessageTooLarge = function ({ chunkSize }) {
+        /**
+         * @type {MetamaskController}
+         */
+        const theController = controller;
+        theController.metaMetricsController.trackEvent({
+          event: MetaMetricsEventName.PortStreamChunked,
+          category: MetaMetricsEventCategory.PortStream,
+          properties: { chunkSize },
+        });
```
Comment (davidmurdoch) [inline app/scripts/background.js:1160]: We want to record how often this happens, so we do that here!

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

File: app/scripts/background.js [hunk 2]
```diff
@@ -1189,7 +1212,8 @@ export function setupController(
       senderUrl.pathname === phishingPageUrl.pathname
     ) {
       const portStreamForPhishingPage =
-        overrides?.getPortStream?.(remotePort) || new PortStream(remotePort);
+        overrides?.getPortStream?.(remotePort) ||
+        new ExtensionPortStream(remotePort, { chunkSize: 0 });
```
Comment (davidmurdoch) [inline app/scripts/background.js:1219]: Setting `chunkSize: 0` turns chunking off (restoring the old way), because not all packages use this latest version. We only turn it _on_ (the default) when we know both ends can speak the "chunking protocol". I'm only turning it on for BG<->UI communications, as that's the only place we've seen the issue.

File: shared/modules/caip-stream.ts [hunk 3]
```diff
@@ -77,16 +77,11 @@ export const createCaipStream = (portStream: Duplex): Duplex => {
...
+  // A DuplexStream streams emits 'close' and/or 'end' event. If it is an ExtensionPortStream,
+  // it automatically calls `destroy` on the stream when the chrome.runtime.Port disconnects.
   portStream.once?.('close', handlePortGone);
   portStream.once?.('end', handlePortGone);
 
-  // b. chrome.runtime.Port exposes onDisconnect
-  //    (ExtensionPortStream exposes the raw Port at `._port`)
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  const rawPort: chrome.runtime.Port | undefined = (portStream as any)?._port;
-  rawPort?.onDisconnect?.addListener(handlePortGone);
```
Comment (davidmurdoch) [inline shared/modules/caip-stream.ts:88]: The rawPort's `onDisconnect` triggers the `ExtensionPortStream`'s `end` event, which is already handled above.

File: shared/constants/metametrics.ts [hunk 4]
```diff
@@ -950,6 +950,8 @@ export enum MetaMetricsEventName {
   // Delete Wallet Modal
   WalletRestored = 'Wallet Restored',
   ExtensionPinned = 'Extension Pinned',
+  // Extension Port Stream
+  PortStreamChunked = 'Port Stream Chunked',
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply shared/constants/metametrics.ts:954]: image

?

File: app/scripts/background.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/background.js:1160]: Confusingly, this `category` gets moved to `properties`.

**Comment by davidmurdoch** [comment]
@metamaskbot update-policies

File: app/scripts/background.js [hunk 5]
```diff
@@ -1136,8 +1136,31 @@ export function setupController(
...
+         * @type {MetamaskController}
+         */
+        const theController = controller;
+        theController.metaMetricsController.trackEvent({
+          event: MetaMetricsEventName.PortStreamChunked,
+          category: MetaMetricsEventCategory.PortStream,
+          properties: { chunkSize },
+        });
+      };
+      portStream.on('message-too-large', handleMessageTooLarge);
```
Comment (DDDDDanica) [inline app/scripts/background.js:1165]: Nit: Potential improvement to remove event listener is when the port disconnects
```
remotePort.onDisconnect.addListener(() => {
  portStream.off('message-too-large', handleMessageTooLarge);
});

```

File: test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+
+        const events = await getEventPayloads(driver, mockedEndpoint);
+        if (isFirefox) {
+          // Firefox will never be chunked
+          assert.strictEqual(
+            events.some((event) => event.category === 'Port Stream Chunked'),
+            false,
+          );
+        } else {
+          assert.strictEqual(events[0].event, 'Port Stream Chunked');
```
Comment (DDDDDanica) [inline test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts]: Nit: Is it possible to have other events fired first? we could improve like
```
  const chunkEvent = events.find((e) => e.event === 'Port Stream Chunked');
  assert.ok(chunkEvent, 'Port Stream Chunked event should be present');
```

File: app/scripts/background.js [hunk 7]
```diff
@@ -1136,8 +1136,31 @@ export function setupController(
...
+       * send event to sentry with details about the event
+       *
+       * @param {import("extension-port-stream").MessageTooLargeEventData} details
+       */
+      const handleMessageTooLarge = function ({ chunkSize }) {
+        /**
+         * @type {MetamaskController}
+         */
+        const theController = controller;
+        theController.metaMetricsController.trackEvent({
```
Comment (DDDDDanica) [inline app/scripts/background.js:1156]: Can be simplified? 
```suggestion
        controller.metaMetricsController.trackEvent({
```

File: app/scripts/background.js [hunk 8]
```diff
@@ -1218,14 +1242,16 @@ export function setupController(
         )
       ) {
         const portStreamForCookieHandlerPage =
-          overrides?.getPortStream?.(remotePort) || new PortStream(remotePort);
+          overrides?.getPortStream?.(remotePort) ||
+          new ExtensionPortStream(remotePort, { chunkSize: 0 });
```
Comment (DDDDDanica) [inline app/scripts/background.js:1249]: Could use some docs to explain the part of `user has more than 64MB of state`? what is 64MB chunk size chosen based on?

File: app/scripts/background.js (hunk 7 above)
Comment (davidmurdoch) [reply app/scripts/background.js:1156]: `theController` is typed, but `controller` isn't. If I add a type to `controller` directly it has to be `| undefined`, and then i'd have to update everywhere it is used. So I just did this here.

File: app/scripts/background.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/background.js:1165]: `controller` is always available at this time. The e2e is correct.

File: app/scripts/background.js (hunk 8 above)
Comment (davidmurdoch) [reply app/scripts/background.js:1249]: It is documented in `ExtensionPortStream`'s source code. It is based on a hardcoded value of exactly 64MB inside Chrome/V8.

Comment (davidmurdoch) [reply app/scripts/background.js:1249]: image

File: app/scripts/background.js (hunk 5 above)
Comment (davidmurdoch) [reply app/scripts/background.js:1165]: fixed

File: test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts (hunk 6 above)
Comment (davidmurdoch) [reply test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts]: fixed! thanks!

File: test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+        await homepage.checkExpectedBalanceIsDisplayed();
+
+        const events = await getEventPayloads(driver, mockedEndpoint);
+        if (isFirefox) {
+          // Firefox will never be chunked
+          assert.strictEqual(
+            events.some((event) => event.category === 'Port Stream Chunked'),
+            false,
+          );
+        } else {
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts:76]: fixed

**Review by MajorLift — APPROVED** [review]
LGTM!
- Test steps successfully followed on local.
- No policy additions to unexpected packages or for unrelated capabilities.

File: test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+  it('can load the wallet UI with a huge background state (~128MB)', async function () {
+    // add MOCK_TRANSACTION_BY_TYPE.HUGE to an array a bunch of times
+    const hugeTx = {
+      id: 4243712234858512,
+      time: 1589314601567,
+      status: 'confirmed',
+      chainId: '0x5',
+      loadingDefaults: false,
+      txParams: {
+        from: '0xabca64466f257793eaa52fcfff5066894b76a149',
```
Comment (seaona) [inline test/e2e/tests/port-stream-chunking/port-stream-chunking.spec.ts:37]: just as nit, if we used the fixture account here, as well as the chainId 1337, we could be able to verify this is actually present in the Activity tab (just adds an extra assert, but not essential for the test)-- however, I changed that and I still cannot see it 🤔 just wondering why might be the case

image

**Review by seaona — APPROVED** [review]
QA changes look good. I added a comment but non blocking, just wondering why I'm seeing that behaviour  🤔

**Review by DDDDDanica — APPROVED** [review]
