### PR TITLE
fix: cp-12.22.0 resubscribe notifications v2 on app startup.

### LINKED ISSUE #33801: [Bug]: Existing Users who have enabled notifications are not migrating to notifications v2
### Describe the bug

Notifications have moved to a new architecture, which requires users to subscribe to new notifications.

New users will use this new architecture when they opt-into notifications.
Existing users that have enabled notifications are not migrating to notifications v2.

### Expected behavior

We expect all users who (who will turn on notifications, and have already turned on notifications) to use the new architecture.

### Screenshots/Recordings

https://www.loom.com/share/fe1b061682c14bc3ba61a9abc23e3cfe

### Steps to reproduce

1. Select an older MM Version
2. Open up background dev tools > inspect network > inspect the `https://trigger.api.cx.metamask.io` endpoint
3. Enable notifications - EXPECTED: you should see an API call made to the `/v1/batch` endpoint
4. Install v12.22.0
5. Unlock and open extension - ACTUAL: you do not see any calls made to use the `/v2` endpoints to resubscribe notifications.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.22.0

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS

### Hardware wallet

_No response_

### Additional context

This does not impact the core wallet experience, however users will be in a weird state where the subscriptions are made in the v1 architecture, but fetching notifications/receiving push notifications are pointing to the v2 architecture.
- Users will stop receiving in-app updates and push notifications.

### Severity

Sev-2, working on a fix for this now

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

This ensures that we subscribe users to notification v2 subscriptions. Pretty nice especially when we want to ensure that users have up-to-date subscriptions.

Long term, we can think about moving this into the controller directly.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33805?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33801

## **Manual testing steps**

See issue repro steps
0. Install an older extension and enable notifications
1. Install this change, open background script to monitor network
2. Unlock app - EXPECTED, should see a call to the `https://trigger.api.cx.metamask.io/v2` endpoint 
  - this resubscribes the users notifications to the v2 architecture.

### **After**

https://www.loom.com/share/6cb1ab53c39b4ceba0420cd92358a4f0

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/contexts/metamask-notifications/metamask-notifications.tsx [hunk 1]
```diff
@@ -31,48 +32,85 @@ export const useMetamaskNotificationsContext = () => {
...
+    const run = async () => {
+      try {
+        if (
+          isBasicFunctionalityEnabled &&
+          shouldFetchNotifications &&
+          isUnlocked
+        ) {
+          // Re-enabling notifications as we need to ensure that the notification subscriptions are correctly setup
+          // NOTE - we should move this inside the controller on startup
+          await enableNotifications();
```
Comment (Prithpal-Sooriya) [inline ui/contexts/metamask-notifications/metamask-notifications.tsx]: As discussed, I think it would be good to move this into the controller.
However the controller would need some work to support this.

Comment (Prithpal-Sooriya) [reply ui/contexts/metamask-notifications/metamask-notifications.tsx]: Hmmm thinking about this more, it kinda is nice that this is fired in the UI.
The background will be a bit weird to work in (we don't want notification APIs to fire during onboarding), and there are discrepencies between extension and mobile on this.

Maybe we can keep this in the UI but have a resubscription expiry.

Comment (Prithpal-Sooriya) [reply ui/contexts/metamask-notifications/metamask-notifications.tsx]: Resolving - opted to use the effect + expiry approach.

**Review by salimtb — DISMISSED** [review]

**Review by jpsains — APPROVED** [review]

**Review by HowardBraham — APPROVED** [review]
