### PR TITLE
fix: calcTokenAmount BigNumber more than 15  digits error

### LINKED ISSUE #13738: [Sentry] [Bug] Bug/Error:  div() number type has more than 15 significant digits
- This is a previously solved bug: “MM_bug_2” but actually appears to have not gone away
- Affected users are reporting this happening upon opening the extension, and also upon executing transactions.
- Not super high volume of inquiries on this one.

### PR DESCRIPTION
**Pull request by digiwand**
#### This PR:
- Fixes a BigNumber Error on calcTokenAmount 
- Fixes Swaps destinationAmount type. '0' should take place of null occurrences 
- Adds calcTokenAmount tests

#### Explanation:
When certain large params are passed, e.g. when the decimal passed is 36, the calculation of `Math.pow(10, Number(decimals || 0))` is → 9.999999999999999e+35. Then, when we pass this to BigNumber div() we get the error:
```
BigNumber Error:
div() number type has more than 15 significant digits: 9.999999999999999e+35
```

`new BigNumber(10).pow(decimals)` does not have this rounding issue and can be passed to BigNumber div() without the error.

We can see the [bignumber.js#div code here](https://github.com/MikeMcl/bignumber.js/blob/v4.1.0/bignumber.js#L750) 

#### Other notes:
- It turns out that updating the bignumber.js package from 4.1.0 → 9.1.2 could also fix this issue
- There is another, less-used BigNumber class that exists in our code ([this BigNumber div code](https://github.com/ethers-io/ethers.js/blob/f97b92bbb1bde22fcc44100af78d7f31602863ab/packages/bignumber/src.ts/bignumber.ts#L81))

---

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25799?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/13738
Related: https://github.com/MetaMask/metamask-extension/pull/25741#issue-2400875822

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**
(divisor was previously called multiplier)
CleanShot 2024-07-16 at 01 07 09@2x

### **After**

CleanShot 2024-07-16 at 01 19 06@2x

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controllers/swaps.ts [hunk 1]
```diff
@@ -709,7 +709,7 @@ export default class SwapsController {
         : totalEthCost;
 
       const decimalAdjustedDestinationAmount = calcTokenAmount(
-        destinationAmount,
```
Comment (digiwand) [inline app/scripts/controllers/swaps.ts:712]: It's expected that the destinationAmount of a Quote is either a string or null. If it was a null, null would be passed to calcTokenAmount. If it was undefined, it would have been a number type. This fixes the type and expected null handling

File: shared/lib/transactions-controller-utils.js [hunk 2]
```diff
@@ -34,9 +34,14 @@ export function toPrecisionWithoutTrailingZeros(n, precision) {
...
 
-export function calcTokenAmount(value, decimals) {
-  const multiplier = Math.pow(10, Number(decimals || 0));
-  return new BigNumber(String(value)).div(multiplier);
+/**
+ * @param {number|string|BigNumber} value
+ * @param {number} decimals
+ * @returns {BigNumber}
+ */
+export function calcTokenAmount(value, decimals = 0) {
```
Comment (matthewwalsh0) [inline shared/lib/transactions-controller-utils.js:42]: It seems we have similar logic spread throughout the code, such as:

- `ui/ducks/send/send.js`
- `ui/components/ui/token-input/token-input.component.js`
- `ui/components/app/currency-input/currency-input.js`
- `ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx`
- `ui/pages/confirmations/components/confirm/row/dataTree.tsx`

Should we assume this could also be an issue in those other usages and have them all point to a single utility?

Also, I appreciate this was historic, but there is no `TransactionController` directly in the extension anymore, so this file feels somewhat like a collection of miscellaneous utility functions.

Should we relocate and introduce typings via a new file such as `shared/lib/[math|large-number|decimals].ts`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: shared/lib/transactions-controller-utils.js (hunk 2 above)
Comment (digiwand) [reply shared/lib/transactions-controller-utils.js:42]: re: similar logic spread throughout the code
Great callout! I mentioned in this [related PR](https://github.com/MetaMask/metamask-extension/pull/25741#issuecomment-2225556743) that we should reuse this logic there after this is merged (this would address 2 of the bullet points above). I agree it'd be a good idea to update the other code. This is out of this PR. Created a new issue for this to track:
https://github.com/MetaMask/metamask-extension/issues/25891

re: no TransactionController directly in the extension anymore
Another great callout! I also agree here that we should rename/refactor the file accordingly. As this is another refactor and out of scope from this bug fix, I've created a new ticket for this here:
https://github.com/MetaMask/metamask-extension/issues/25892

**Review by matthewwalsh0 — APPROVED** [review]

**Review by infiniteflower — APPROVED** [review]
