### PR TITLE
fix: add default enable networks state and null guards

### LINKED ISSUE #35232: TypeError: Cannot read properties of undefined (reading 'eip155')
Sentry Issue: [METAMASK-XPHD](https://metamask.sentry.io/issues/6818990880/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'eip155')
  at exports.getEnabledChainIds (ui/selectors/multichain/networks.ts:237:34)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:750)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:750)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:750)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:750)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

The redux state we are picking might not exist if accessed before state gets rehydrated.

Added a default state to enabled networks, and also a null guard for where we initially select from this state

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/40402?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: add enable networks null guards

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/35232 https://consensyssoftware.atlassian.net/browse/ASSETS-2021

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots. 

---
<p><a href="https://cursor.com/agents/bc-b208b3d7-fc4f-4cb8-a9bb-c53f4a663c60"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-web-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-web-light.png">Open in Web</picture></a>&nbsp;<a href="https://cursor.com/background-agent?bcId=bc-b208b3d7-fc4f-4cb8-a9bb-c53f4a663c60"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-cursor-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-cursor-light.png">Open in Cursor</picture></a>&nbsp;</p>

---

> [!NOTE]
> **Low Risk**
> Low risk: small selector hardening to avoid crashes when `enabledNetworkMap` or its `eip155` entry is undefined; behavior only changes in uninitialized/rehydration edge cases.
> 
> **Overview**
> Prevents selector crashes when Redux state hasn’t rehydrated by defaulting `getEnabledNetworks` to an empty map and guarding `selectAllEnabledNetworkClientIds` against a missing `eip155` namespace entry.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 499a6298b98247450458f4c39b0b45deef1d9990. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: shared/modules/selectors/multichain.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export const selectAllEnabledNetworkClientIds = createSelector(
   selectDefaultNetworkClientIdsByChainId,
   (allEnabledNetworks, defaultNetworkClientIdsByChainId) => {
     const chainIds = Object.entries(
-      allEnabledNetworks[KnownCaipNamespace.Eip155],
+      allEnabledNetworks?.[KnownCaipNamespace.Eip155] ?? {},
```
Comment (Prithpal-Sooriya) [inline shared/modules/selectors/multichain.ts]: Nice this is valid.

File: ui/selectors/multichain/networks.ts
Comment (Prithpal-Sooriya) [inline ui/selectors/multichain/networks.ts:1]: @cursor can you evaluate this change?

I think a cleaner fix would be to add the change on the `getEnabledNetworks` like this
```ts
export const getEnabledNetworks = (state: {
  metamask: {
    enabledNetworkMap: EnabledNetworksByChainId;
  };
}) => state.metamask.enabledNetworkMap ?? {}; // added ?? {}
```

That way I think most of this file can remain unchanged?

File: shared/modules/selectors/multichain.ts [hunk 2]
```diff
@@ -15,14 +15,14 @@ export const getEnabledNetworks = (state: {
   metamask: {
     enabledNetworkMap: EnabledNetworksByChainId;
   };
-}) => state.metamask.enabledNetworkMap;
+}) => state.metamask.enabledNetworkMap ?? {};
```
Comment (Prithpal-Sooriya) [inline shared/modules/selectors/multichain.ts]: Null check since this can init as undefined potentially. (looking at sentry logs)

File: ui/selectors/multichain/networks.ts [hunk 3]
```diff
@@ -376,7 +376,7 @@ export const getEnabledChainIds = createSelector(
     const { namespace } = parseCaipChainId(currentMultichainChainId);
 
     // Get enabled networks for the current namespace
-    const networksForNamespace = enabledNetworks[namespace] || {};
+    const networksForNamespace = enabledNetworks[namespace] ?? {};
```
Comment (Prithpal-Sooriya) [inline ui/selectors/multichain/networks.ts]: @cursor to keep file changes minimal can we revert this change back to using `||`?


```suggestion
    const networksForNamespace = enabledNetworks[namespace] || {};
```

File: ui/selectors/multichain/networks.ts [hunk 4]
```diff
@@ -392,7 +392,7 @@ export const getEnabledNetworkClientIds = createSelector(
     const { namespace } = parseCaipChainId(currentMultichainChainId);
 
     // Get enabled networks for the current namespace
-    const networksForNamespace = enabledNetworks[namespace as string] || {};
+    const networksForNamespace = enabledNetworks[namespace as string] ?? {};
```
Comment (Prithpal-Sooriya) [inline ui/selectors/multichain/networks.ts]: @cursor to keep file changes minimal can we revert this change back to using `||`?


```suggestion
    const networksForNamespace = enabledNetworks[namespace as string] || {};
```

**Review by bergarces — DISMISSED** [review]

**Review by bergarces — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]
