### PR TITLE
fix: ensure network deselect updates the underlying network controller to an enabled network

### LINKED ISSUE #34139: [Bug]: [Remove GNS] Balance issue when multiple networks are enabled
### Describe the bug

In the latest QA build, the total balance is incorrect when multiple networks are enabled.

It is also displayed in the native token, even though this option is not enabled

### Expected behavior

Correct balance

### Screenshots/Recordings

https://github.com/user-attachments/assets/72dc1a5d-6633-40a0-a887-3fd328746efc

### Steps to reproduce

1. Enable multiple networks
2. Notice total balance

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

12.20.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

When a user deselects a network inside the network manager, under the hood it selects that given network.
This causes some application weirdness for places that rely on the NetworkController instead of the new NetworkOrderController.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34248?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34139#issuecomment-3068568376 #34326 

## **Manual testing steps**

This issue arrises when you have the "Show native token as main balance" setting enabled and you are toggling between single networks. See after vid for a demo.
1. Select 2 network - e.g. ethereum and polygon)
2. Deselect Ethereum - does the balance show POL
3. Select Ethereum and Deselect Polygon - does balance show ETH

### **After**

https://www.loom.com/share/99c546022a7f438bb682d59b80d8f7f2?sid=82bd5056-8511-41e6-8ad3-51c78f517aff

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controllers/network-order.ts [hunk 1]
```diff
@@ -289,7 +294,14 @@ export class NetworkOrderController extends BaseController<
...
     ) {
-      this.messagingSystem.call('NetworkController:setActiveNetwork', clientId);
+      // Settimout delay to run this in a seperate 'tick'.
+      // There were some issues related to background state being updated, but persisted state not being updated.
+      setTimeout(() => {
+        this.messagingSystem.call(
+          'NetworkController:setActiveNetwork',
+          clientId,
+        );
+      }, 0);
```
Comment (Prithpal-Sooriya) [inline app/scripts/controllers/network-order.ts:304]: I'm still not entirely sure about why this does not correctly update the persisted state.
Maybe since this messenger call is `async` but the function is `sync`?

File: app/scripts/controllers/network-order.ts [hunk 2]
```diff
@@ -191,6 +189,13 @@ export class NetworkOrderController extends BaseController<
         // Append new networks to the end
         .concat(newNetworks);
     });
+
+    // The network controller can potentially update to a chain that is not selected in our enabled network map.
+    // This ensures that we fallback to a network that has been added to our network map.
+    const evmChainIds = Object.keys(
+      this.state.enabledNetworkMap[KnownCaipNamespace.Eip155],
+    );
+    this.#switchToEnabledNetworkIfNeeded(evmChainIds);
```
Comment (Prithpal-Sooriya) [inline app/scripts/controllers/network-order.ts:198]: I thought salim's fix for adding this `this.#switchToEnabledNetworkIfNeeded` would be sufficient, but it seems that some NetworkController state updates happen "after" we update the NetworkOrderController.

I'm open to opinions... part of me wants to handle this in the UI (through dispatches), but I don't have as much context on this.

**Review by salimtb — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
