### PR TITLE
Upgrade obs-store and fix memory leaks

### LINKED ISSUE #4074: Bug Bounty: High memory usage, over 2 GB taken by MetaMask
**Bounty**: MetaMask has received multiple reports of the extension running high CPU usage. This bounty is to identify the root cause of the issue and write a patch.

---
MetaMask showed high memory and CPU usage. My laptop become unresponsive. When I killed MetaMask from Google Chrome's Task Manger window, then my laptop become responsive. I was on Kovan network, could this be an issue, because blocktime for Kovan (PoA) is 5 seconds.

### Actual Behavior
I kept my laptop running overnight, and when wakeup in morning, my laptop fan was running in full throttle, when I tried to find, which process is taking that much resources. I found Chrome and when opened TaskManager in Chrome, I found MetaMask is the culprit.

### Expected Behavior
It should not take that much of memory. It should clean the memory regularly.

### Browser Used
Google Chrome 65.0.3325.181 (Official Build) (64-bit)

### Operating System Used
MacOS High Sierra 10.13.4

Here is the screen shot of the Chrome's Task Manager.
screen shot 2018-04-24 at 08 38 09

### PR DESCRIPTION
**Pull request by Coffee-Boyy**
This PR discovers and addresses two event emitter memory leaks:
* In the main metamask controller whenever the menu is opened
* When setting up the public config store whenever a new tab is opened

The memory usage before fixing these was not as high as the original issue stated but when I analyzed the heap dumps periodically, there were many objects not being garbage collected (old event emitters). And, I was not able to run the tests for very long but I do see a reduction in the live javascript memory and it's staying consistently low over time.

This fixes #4074

### CODE REVIEW

**Comment by danfinlay** [comment]
This is such a big deal, I can't thank you enough. Reviewing now.

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -177,7 +177,7 @@ module.exports = class MetamaskController extends EventEmitter {
       blockTracker: this.blockTracker,
       getGasPrice: this.getGasPrice.bind(this),
     })
-    this.txController.on('newUnapprovedTx', opts.showUnapprovedTx.bind(opts))
+    this.txController.on('newUnapprovedTx', () => opts.showUnapprovedTx())
```
Comment (danfinlay) [inline app/scripts/metamask-controller.js]: This one's just for readability, right? There isn't some issue with bind, is there?

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -1280,10 +1282,12 @@ module.exports = class MetamaskController extends EventEmitter {
    * @param {*} outStream - The stream to provide public config over.
    */
   setupPublicConfig (outStream) {
+    const configStream = asStream(this.publicConfigStore)
     pump(
-      asStream(this.publicConfigStore),
+      configStream,
       outStream,
       (err) => {
+        configStream.destroy()
```
Comment (danfinlay) [inline app/scripts/metamask-controller.js]: Oh wow, I thought the stream would clean itself up. Great subtle catch.

**Review by danfinlay — APPROVED** [review]
This looks good. I had a question, but it wasn't a criticism, just learning from it.

File: app/scripts/metamask-controller.js (hunk 1 above)
Comment (ConnorChristie) [reply app/scripts/metamask-controller.js]: So there is a lot of controversy around bind vs arrow functions with arrow functions winning the performance battle since they only bind once but the reason I switched this one was because ‘opts’ was being bound. I am not sure whether it should be like that but when I analyzed the heap, it looked like it was cloning the opts every time it bound

Comment (danfinlay) [reply app/scripts/metamask-controller.js]: Fair enough, looks like arrow functions make it harder to mess up as usual! Thanks for the improvement. Getting the tests passing, they can be a little non-deterministic :(

Should be able to merge soon!

File: app/scripts/metamask-controller.js (hunk 2 above)
Comment (kumavis) [reply app/scripts/metamask-controller.js]: this should be redundant bc `pump` destroys on close
unless this is prevented by some duplex half-open state

Comment (ConnorChristie) [reply app/scripts/metamask-controller.js]: Ahh yes, you are correct. The reason I thought I needed it was because the `obs-store` stream did not have a destroy method and when I added that, I thought I needed to manually call it.

But this call does not need to be in there, pump will call destroy automatically now that the destroy function is implemented.

**Comment by bdresser** [comment]
hey @ConnorChristie could you shoot me an email? have a question for you 😄 bobby.dresser@consensys.net
