### PR TITLE
fix: hide fee info if swap quote does not include a MetaMask fee cp-13.1.1

### LINKED ISSUE #35277: [Bug]: ETH <> WETH Swaps incorrectly showing 0.875% MetaMask fee in UI
### Describe the bug

When swapping ETH -> WETH or WETH -> ETH, the Mobile UI shows that MetaMask will apply a 0.875% fee.

### Expected behavior

When swapping ETH -> WETH or WETH -> ETH, the Mobile UI should show that MetaMask applies 0 fee.

### Screenshots/Recordings

Image
Image

### Steps to reproduce

Go to Swap UI
Enter ETH and WETH as trading pair
Fetch quote
See MetaMask 0.875% fee disclaimer in UI

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.0.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

The Swap UI inaccurately indicates that MetaMask is taking a fee on ETH wrap and unwrap transactions. This change checks whether the quote includes a MM fee, and only shows the indication if it's non-zero

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35278?quickstart=1)

## **Changelog**

CHANGELOG entry:

- fix: hide Swap fee info line if quote does not include a MetaMask fee

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/35277

## **Manual testing steps**

1. Go to Swap page
2. Request ETH -> WETH quote and verify that there are no MM fees
3. Request WETH -> ETH quote and verify that there are no MM fees
4. Request ETH -> USDC quote and verify that there are MM fees

### **Before**
Screenshot 2025-08-20 at 1 55 17 PM

### **After**

Screenshot 2025-08-20 at 1 48 50 PM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by ejwessel — DISMISSED** [review]

File: ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx [hunk 1]
```diff
@@ -323,7 +324,11 @@ export const MultichainBridgeQuoteCard = ({
               color={TextColor.textAlternative}
             >
               <Text variant={TextVariant.bodyMd}>
-                {t('rateIncludesMMFee', [BRIDGE_MM_FEE_RATE])}
+                {new BigNumber(activeQuote.quote.feeData.metabridge.amount).gt(
+                  0,
+                )
+                  ? t('rateIncludesMMFee', [BRIDGE_MM_FEE_RATE])
+                  : ''}
```
[the remark this answers is not in the document]
Comment (micaelae) [reply ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx:331]: The bridge controller validates that the value is a truthy digit (i.e `'0'`) so we know it'll always be a decimal number

**Review by infiniteflower — DISMISSED** [review]

**Review by ejwessel — APPROVED** [review]

**Comment by seaona** [comment]
:heavy_check_mark:  I also see the issue fixed.



Screenshot from 2025-08-21 15-16-18

Screenshot from 2025-08-21 15-16-03

File: ui/pages/bridge/quotes/multichain-bridge-quote-card.test.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ describe('MultichainBridgeQuoteCard', () => {
     jest.clearAllMocks();
```
Comment (seaona) [inline ui/pages/bridge/quotes/multichain-bridge-quote-card.test.tsx:18]: Do you think it might be good to also have an e2e that covers this flow @micaelae ? If so, we should create an issue for that, or add it here in this same PR. Whatever makes more sense, for you!

**Review by infiniteflower — APPROVED** [review]

File: ui/pages/bridge/quotes/multichain-bridge-quote-card.test.tsx (hunk 2 above)
Comment (micaelae) [reply ui/pages/bridge/quotes/multichain-bridge-quote-card.test.tsx:18]: Good call @seaona ! I think we already have a backlog item for ETH<>WETH (wrapped ) tests but I'll create one i we don't

Comment (seaona) [reply ui/pages/bridge/quotes/multichain-bridge-quote-card.test.tsx:18]: thank you v much @micaelae Let me know if you need support from the QA team for that :pray:
