### PR TITLE
fix: flaky test `Address Book Edit entry in address book` due to race condition with mmi menu

### LINKED ISSUE #24658: flaky test: Address Book Edit entry in address book
### What is this about?

Failure:

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/100825/workflows/cec4aacf-c4df-4e6b-bee1-41225cd15fe2/jobs/3753783

### PR DESCRIPTION
**Pull request by seaona**
## **Description**
The MMI build has a different menu than the regular MM build, which includes a button for the portoflio mmi. The problem is that the extra button takes a bit more to load. Once this happens the menu is re-rendered, making the click to the menu item (in this case, the Settings, go into a different button, causing a new page to open and not going to the expected Settings page, making the next element `Contacts` not possible to be found.

Screenshot from 2024-10-02 11-53-53

There are ~10 more tests that can have this race condition. Since each test is re-run x5 times, I'll create another PR for the remaining cases (however, once all specs implement page objects, that would already be fixed on the page object level).

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27557?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24658

## **Manual testing steps**

1. Check ci
2. Run test locally

## **Screenshots/Recordings**

image

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: test/e2e/page-objects/pages/header-navbar.ts [hunk 1]
```diff
@@ -9,28 +9,43 @@ class HeaderNavbar {
...
 
   async openSettingsPage(): Promise<void> {
     console.log('Open settings page');
     await this.driver.clickElement(this.accountOptionMenu);
+    // fix race condition with mmi build
+    if (process.env.MMI) {
+      await this.driver.waitForSelector(this.mmiPortfolioButton);
+    }
     await this.driver.clickElement(this.settingsButton);
   }
```
Comment (seaona) [inline test/e2e/page-objects/pages/header-navbar.ts:50]: this will fix all occurrences, once all e2e have adopted page objects

File: test/e2e/tests/settings/clear-activity.spec.js [hunk 2]
```diff
@@ -41,6 +41,14 @@ describe('Clear account activity', function () {
         await driver.clickElement(
           '[data-testid="account-options-menu-button"]',
         );
+
+        // fix race condition with mmi build
```
Comment (DDDDDanica) [inline test/e2e/tests/settings/clear-activity.spec.js:45]: Nit: I was thinking about extracting this condition to a separate function, and when we convert this to POM e2e tests it would be super handy to transform too. wdyt>?

Comment (seaona) [reply test/e2e/tests/settings/clear-activity.spec.js]: thank you for your great suggestion @DDDDDanica  :bowing_woman: thanks to that I've realized that we already had the `openMenuSafe` function with the race condition check, so I'm using this now in the specs
(until POM is implemented, which will already check that in the page level --see changes in the pom file)

**Review by chloeYue — APPROVED** [review]
LGTM !

**Review by hjetpoluru — APPROVED** [review]
LGTM

File: test/e2e/tests/settings/clear-activity.spec.js (hunk 2 above)
Comment (DDDDDanica) [reply test/e2e/tests/settings/clear-activity.spec.js]: That's great to hear ! nice solution !
