### PR TITLE
fix: fix scroll focus

### LINKED ISSUE #38145: [Bug]: "All popular networks" does not scroll the list to the top in network selection dialog
### Describe the bug

When tapping “All popular networks” in the drop down, the list does not scroll to the top in the network selection screen.

### Expected behavior

Tapping “All popular networks” should automatically take the user to the top of the network list within the selection dialog.

### Screenshots/Recordings

https://github.com/user-attachments/assets/f0e532e7-9e59-400b-a9ba-865b265f3adc

### Steps to reproduce

1. login to the MetaMask app
2. Tap “All popular networks”.
3. Observe that the list does not scroll back to the top.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.11.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Fix scroll issue on network modal

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38439?quickstart=1)

## **Changelog**

CHANGELOG entry: fix scroll issue on network modal.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38145

## **Manual testing steps**

1. click on network selector on main page
2. It should not be already scrolled down

### **Before**

https://github.com/user-attachments/assets/c6563970-e001-4d01-bb82-9c05f4ea75b1

### **After**

https://github.com/user-attachments/assets/b9519ce4-245b-4c77-81ce-5a23907eb4fd

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Sets `focus={false}` on `NetworkListItem` across custom and default network lists (including "All popular networks") to avoid auto-scroll on open.
> 
> - **UI – Network Manager**:
>   - Set `focus={false}` on `NetworkListItem` in:
>     - `custom-networks.tsx` for custom networks entries.
>     - `default-networks.tsx` for each default network entry.
>     - `default-networks.tsx` "allPopularNetworks" aggregate item.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 14a6151b6ce74b74548acd648a2a1245fab31631. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by Prithpal-Sooriya — APPROVED** [review]

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx [hunk 1]
```diff
@@ -287,6 +287,7 @@ const DefaultNetworks = memo(() => {
           name={network.name}
           iconSrc={iconSrc}
           iconSize={AvatarNetworkSize.Md}
+          focus={false}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:290]: good fix. Does this mean we won't have focusing/scrolling to bottom if you have a network added in the bottom of the list?
E.g. if you've only selected TRON?

I think that this might be an acceptable

**Review by salimtb — APPROVED** [review]

File: ui/components/multichain/network-manager/components/default-networks/default-networks.tsx (hunk 1 above)
Comment (sahar-fehri) [reply ui/components/multichain/network-manager/components/default-networks/default-networks.tsx:290]: Yes if you select TRON and re-open this modal; it will be already scrolled to top

**Review by DDDDDanica — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
