### PR TITLE
Increase Token Symbol length to twelve

### LINKED ISSUE #5815: Issue adding token with special characters in symbol
**Describe the bug**
Issue adding token with special characters in the symbol. 

**To Reproduce**
1. "Add Token" through metamask menu
2. Use contract address `0x10b8f6477903eb1562918d441491f1e89c360156`

**Expected behavior**
Should allow the addition of the token (or modification of the symbol).

**Screenshots**
image

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - MetaMask Version: 5.0.3

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #5815. Special characters aren't the issue, it is just the text length.

### CODE REVIEW

**Review by whymarrh — APPROVED** [review]

File: ui/app/components/pages/add-token/add-token.component.js [hunk 1]
```diff
@@ -194,8 +194,8 @@ class AddToken extends Component {
     const symbolLength = customSymbol.length
     let customSymbolError = null
 
-    if (symbolLength <= 0 || symbolLength >= 10) {
-      customSymbolError = this.context.t('symbolBetweenZeroTen')
+    if (symbolLength <= 0 || symbolLength >= 12) {
```
Comment (tmashuang) [inline ui/app/components/pages/add-token/add-token.component.js]: This could have been a smaller PR to just change the `>=` to `>` but increasing just to be safe.
