### PR TITLE
fix: replace dnode background with JSON-RPC

### LINKED ISSUE #10090: Background errors not serialized correctly when sent to UI
**Describe the bug**
When an error occurs in the background, it's not serialized correctly when sent to the UI. The error arrives as a plain object with its `stack` missing, so the resulting Sentry reports are difficult to debug.

**Expected behavior**
The error should still have a type of `Error` and should retain its `stack` when sent from the background to the UI.

### PR DESCRIPTION
**Pull request by shanejonas**
Fixes #10090

Explanation:  This replaces our internal use of `dnode` with `JSON-RPC`. 

Manual testing steps:  
  - make sure everything still works, this is a cross-cutting change that affects most (if not all) of the application

### CODE REVIEW

File: app/scripts/lib/metaRPCClient.js [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+            id,
+          });
+        };
+      },
+    });
+  }
+
+  onNotification(cb) {
+    this.notificationChannel.addListener('notification', (data) => {
+      cb(data);
```
Comment (shanejonas) [inline app/scripts/lib/metaRPCClient.js:35]: not sure if this should be `cb(null, data)` to follow nodejs callback conventions since this only listens for notifications and would never get an error

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -1986,36 +1986,28 @@ export default class MetamaskController extends EventEmitter {
...
-      }
-    });
-    dnode.on('remote', (remote) => {
-      // push updates to popup
-      const sendUpdate = (update) => remote.sendUpdate(update);
-      this.on('update', sendUpdate);
-      // remove update listener once the connection ends
-      dnode.on('end', () => this.removeListener('update', sendUpdate));
+
+    // set up postmessage transport
```
Comment (shanejonas) [inline app/scripts/metamask-controller.js:1999]:
```suggestion
    // set up postStream transport
```

File: app/scripts/lib/metaRPCClient.js [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+  }
+
+  close() {
+    this.notificationChannel.removeAllListeners();
+  }
+
+  handleResponse(data) {
+    const { id } = data;
+    const cb = this.requests.get(id);
+    if (data.params && data.id) {
```
Comment (shanejonas) [inline app/scripts/lib/metaRPCClient.js:46]:
```suggestion
    if (data.method && data.params && data.id) {
```

**Comment by brad-decker** [comment]
image

File: app/scripts/lib/metaRPCClient.js (hunk 1 above)
Comment (kumavis) [reply app/scripts/lib/metaRPCClient.js:35]: shouldn't need an error. call it a handler instead of a callback to avoid the confusion

File: app/scripts/metamask-controller.js [hunk 4]
```diff
@@ -1986,36 +1986,28 @@ export default class MetamaskController extends EventEmitter {
...
-    // it is a workaround for node v12 support
-    const dnode = Dnode(api, { weak: false });
+
     // report new active controller connection
     this.activeControllerConnections += 1;
     this.emit('controllerConnectionChanged', this.activeControllerConnections);
-    // connect dnode api to remote connection
-    pump(outStream, dnode, outStream, (err) => {
-      // report new active controller connection
-      this.activeControllerConnections -= 1;
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js:2003]: It seems like we're not tracking when connections are closed anymore. We keep track of this as part of "quiet mode" - where we stop polling the network when no UI is open.

Comment (Gudahtt) [reply app/scripts/metamask-controller.js:2003]: It looks like this plus the `controllerConnectionChanged` event could be emitted in the `end` handler for the stream, to restore this functionality.

File: app/scripts/metamask-controller.js [hunk 5]
```diff
@@ -1986,36 +1986,28 @@ export default class MetamaskController extends EventEmitter {
...
-      this.on('update', sendUpdate);
-      // remove update listener once the connection ends
-      dnode.on('end', () => this.removeListener('update', sendUpdate));
+
+    // set up postStream transport
+    outStream.on('data', createMetaRPCHandler(api, outStream));
+    const handleUpdate = (update) => {
+      // send notification to client-side
+      outStream.write({
+        method: 'sendUpdate',
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js:2004]: Should this include `jsonrpc: '2.0'`, for spec compliance? Not that it _really_ matters since this is internal, but :shrug: 

```suggestion
        jsonrpc: '2.0',
        method: 'sendUpdate',
```

Comment (Gudahtt) [reply app/scripts/metamask-controller.js:2004]: This goes for the other messages as well - I see that it's missing for all of them.

File: ui/index.js [hunk 6]
```diff
@@ -128,8 +128,10 @@ async function startApp(metamaskState, backgroundConnection, opts) {
     );
   }
 
-  backgroundConnection.on('update', function (state) {
-    store.dispatch(actions.updateMetamaskState(state));
+  backgroundConnection.onNotification((data) => {
+    if (data.method === 'sendUpdate') {
+      store.dispatch(actions.updateMetamaskState(data.params[0]));
+    }
```
Comment (Gudahtt) [inline ui/index.js:134]: Nit: might be worth adding an `else` case and throwing an error, in case we screw something up and send something else as a notification.

File: app/scripts/lib/metaRPCClient.js [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+
+class MetaRPCClient {
+  constructor(connectionStream) {
+    this.connectionStream = connectionStream;
+    this.notificationChannel = new EventEmitter();
+    this.requests = new Map();
+    this.connectionStream.on('data', this.handleResponse.bind(this));
+    this.connectionStream.on('end', this.close.bind(this));
+    // eslint-disable-next-line no-constructor-return
+    return new Proxy(this, {
```
Comment (Gudahtt) [inline app/scripts/lib/metaRPCClient.js:13]: It would be a bit more conventional to use a factory method and add the wrapping proxy there, rather than returning a proxy from a constructor. I've never even seen this done before, and I can't find any information about whether this is spec-compliant or whether it works the same on all browsers.

File: app/scripts/lib/metaRPCClient.js [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+  close() {
+    this.notificationChannel.removeAllListeners();
+  }
+
+  handleResponse(data) {
+    const { id, result, error, method, params } = data;
+    const cb = this.requests.get(id);
+
+    if (method && params && id) {
+      // dont handle server-side to client-side requests
```
Comment (Gudahtt) [inline app/scripts/lib/metaRPCClient.js:49]: Should we throw in this case? This should be unreachable, if I understand this correctly.

File: app/scripts/lib/metaRPCClient.js [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+      return;
+    }
+    if (method && params && !id) {
+      // handle servier-side to client-side notification
+      this.notificationChannel.emit('notification', data);
+      return;
+    }
+    if (!cb) {
+      // not found in request list
```
Comment (Gudahtt) [inline app/scripts/lib/metaRPCClient.js:58]: Similarly, we might want to throw here. I'm guessing that it is possible we'll hit this case, if we every reply twice for any reason. But if we're doing that, it would be a bug that we'd want to track down.

File: app/scripts/metamask-controller.js (hunk 5 above)
Comment (shanejonas) [reply app/scripts/metamask-controller.js:2004]: Yea, I don't have a preference, was hoping to get some feedback.

The current iteration: leaving it out + using params-by-position (array) gives us the least overhead. 

/cc @rekmarks

File: app/scripts/metamask-controller.js (hunk 4 above)
Comment (shanejonas) [reply app/scripts/metamask-controller.js:2003]: nice find 🙏

File: app/scripts/metamask-controller.js (hunk 5 above)
Comment (Gudahtt) [reply app/scripts/metamask-controller.js:2004]: Omitting it for internal connections seems OK to be, for the sake of saving a few bytes on each message.

File: app/scripts/lib/createMetaRPCHandler.js [hunk 10]
```diff
@@ -0,0 +1,30 @@
+import { ethErrors, serializeError } from 'eth-rpc-errors';
+
+const createMetaRPCHandler = (api, outStream) => {
+  return (data) => {
+    if (!api[data.method]) {
+      outStream.write({
+        error: ethErrors.rpc.methodNotFound({
```
[the remark this answers is not in the document]
Comment (shanejonas) [reply app/scripts/lib/createMetaRPCHandler.js:7]: I was returning something similar before using the lib, not sure there is a spec for generic Method Not Found.

I do think theres lots of helpful things in `ethErrors` that should maybe be pulled out to separate `jsonrpc-errors` lib maybe.

File: app/scripts/lib/createMetaRPCHandler.js [hunk 11]
```diff
@@ -0,0 +1,30 @@
...
+          message: `${data.method} not found`,
+        }),
+        id: data.id,
+      });
+      return;
+    }
+    api[data.method](...data.params, (err, result) => {
+      if (err) {
+        outStream.write({
+          error: serializeError(err),
```
[the remark this answers is not in the document]
Comment (shanejonas) [reply app/scripts/lib/createMetaRPCHandler.js:17]: ah didn't see it was behind this option 👍

File: app/scripts/lib/metaRPCClient.js (hunk 9 above)
Comment (shanejonas) [reply app/scripts/lib/metaRPCClient.js:58]: This could happen if you made 2 instance of this class. One of them would try to handle an id it doesn't care about.

File: app/scripts/lib/metaRPCClient.js (hunk 8 above)
Comment (shanejonas) [reply app/scripts/lib/metaRPCClient.js:49]: one of the reasons I have this is because calling `write` postMessage/websocket/portStream doesn't fire `data` on its own stream, but my testStream does and ends up here.

File: ui/app/store/actions.js [hunk 12]
```diff
@@ -2454,17 +2458,25 @@ export function rejectPermissionsRequest(requestId) {
...
  */
 export function removePermissionsFor(domains) {
-  return () => {
-    background.removePermissionsFor(domains);
+  return (dispatch) => {
+    background.removePermissionsFor(domains, (err) => {
+      if (err) {
+        dispatch(displayWarning(err.message));
+      }
+    });
```
Comment (shanejonas) [inline ui/app/store/actions.js:2466]: adding error handling to a couple places here. could be the source of some uncaught errors?

File: ui/index.js (hunk 6 above)
Comment (shanejonas) [reply ui/index.js:140]: not sure I like how prettier is breaking up this over multiple lines with the backticks :(

File: app/scripts/lib/metaRPCClientFactory.js [hunk 13]
```diff
@@ -0,0 +1,79 @@
+import { EventEmitter } from 'events';
+import { EthereumRpcError } from 'eth-rpc-errors';
+import createRandomId from '../../../shared/modules/random-id';
+
+const metaRPCClientFactory = (connectionStream) => {
```
[the remark this answers is not in the document]
Comment (shanejonas) [reply app/scripts/lib/metaRPCClientFactory.js:5]: this is the same as the `MetaRPCClient`, I just have both of them up to show side-by-side what it would look like as a Factory vs class as per @Gudahtt 's feedback

[the remark this answers is not in the document]
Comment (shanejonas) [reply app/scripts/lib/metaRPCClientFactory.js:5]: We can choose which one we like the look of better, I also have the tests up for both versions

File: app/scripts/lib/createMetaRPCHandler.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (kumavis) [reply app/scripts/lib/createMetaRPCHandler.js:7]: im fine with adopting ethErrors error codes here, if jsonrpc lacks spec for them

File: app/scripts/lib/metaRPCClientFactory.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/scripts/lib/metaRPCClientFactory.js:5]: Oops - when I suggested a factory method, I meant one that constructed the class instance for you! e.g.

```
createMetaRpcClient() {
  const metaRPCClient = new MetaRPCClient(streamTest);
  return new Proxy(metaRPCClient, {
    get: (object, property) => {
      if (object[property]) {
        return object[property];
      }
      return (...p) => {
        const cb = p[p.length - 1];
        const params = p.slice(0, -1);
        const id = createRandomId();
    
        object.requests.set(id, cb);
        object.connectionStream.write({
          method: property,
          params,
          id,
        });
      };
    },
  });
}
```

Then we could make that the only module export to ensure the constructor wasn't used directly.

This version seems a bit more difficult to read :thinking: For me at least. Using a class seemed appropriate.

File: app/scripts/lib/metaRPCClient.js [hunk 14]
```diff
@@ -0,0 +1,77 @@
...
+      return;
+    }
+
+    if (error) {
+      const e = new EthereumRpcError(error.code, error.message, error.data);
+      // preserve the stack from serializeError
+      e.stack = error.stack;
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/scripts/lib/metaRPCClient.js:65]: This code isn't wrapping an error - it's deserializing it. So I'm not sure error-cause` works here - there's nothing to wrap.
+1 to using `cause` for any wrapped errors in general though. 1000% in support of that.

**Comment by darkwing** [comment]
Removing myself as reviewer for lack of context.  I'll be following the conversation to keep up and learn, however.

File: app/scripts/lib/createMetaRPCHandler.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/scripts/lib/createMetaRPCHandler.js:8]: It'll do for now certainly. We can create a `jsonrpc-errors` lib later if we feel the need.

File: app/scripts/lib/metaRPCClient.js (hunk 8 above)
Comment (Gudahtt) [reply app/scripts/lib/metaRPCClient.js]: I played around with this today but didn't quite manage to get it to work. We can improve this later if we get around to it - I don't see any reason to block on it.

File: app/scripts/lib/metaRPCClient.js (hunk 9 above)
Comment (Gudahtt) [reply app/scripts/lib/metaRPCClient.js]: That would still be a bug, wouldn't it? At least I can't think of a case where this would be expected. Even if there were two instances, hopefully they'd be handling different sets of requests, i.e. we wouldn't have a request from one reply to the other.

File: .node-version [hunk 15]
```diff
@@ -0,0 +1 @@
+14.15.1
```
Comment (Gudahtt) [inline .node-version:1]: What is this file for :eyes:

Comment (shanejonas) [reply .node-version:1]: lol its removed now. its for `node-env` -.-

**Review by Gudahtt — COMMENTED** [review]
Everything looks good to me aside from _possibly_ the `.node-version` file, only because I don't know what that is. There is room for improvement with the error handling but I don't think that should be a blocker.

File: app/scripts/lib/metaRPCClient.js (hunk 9 above)
Comment (shanejonas) [reply app/scripts/lib/metaRPCClient.js]:
```
const client1 = metaRPCClientFactory(connectionStream);
client1.bar();
// random id: 123456

const client2 = metaRPCClientFactory(connectionStream);
client2.baz();
// random id: 54321
```

in this example, by calling `baz()` on client2 would still get a result over `connectionStream` triggering `onResponse` on `client1` which then would look for a callback (54321) it doesn't care about.

Comment (Gudahtt) [reply app/scripts/lib/metaRPCClient.js]: Ohhhhhh I see, I get it now. Thanks, I didn't realize this would broadcast each reply to all clients.

Is that how our post message stream works? :thinking:

**Review by Gudahtt — DISMISSED** [review]
LGTM!

I tried testing this, and I did confirm that the stack is present on the error in the UI, representing exactly what went wrong in the background. Not sure yet how it shows up in Sentry, but I expect that it'll work.

**Review by Gudahtt — APPROVED** [review]
