### PR TITLE
fix: cp-13.27.0 musd conversion flow selected payToken race condition

### LINKED ISSUE #41704: [Bug]: mUSD Convert tertiary CTA leads to confirmation flow with ETH as a pay with token
**Describe the bug**

As of 13.26.0 the tertiary CTA links to pay with flow with ETH token selected as an eligible pay token

**Expected behavior**

The tertiary CTA links to pay with flow with only supported conversion tokens selectable or selected as an eligible pay token

**Screenshots/Recordings**

https://www.loom.com/share/33e0251d22734db0aa62cdd46347a44c

**Steps to reproduce**

In 13.26.0 go to the tertiary cta and attempt to convert

The selected pay token is ETH

**Error messages or log output**

```shell

```

**Where was this bug found?**

Live version (from official store)

**Version**

13.26.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

**Additional context**

It seems this is a regression as it does not happen on 13.25.0

### PR DESCRIPTION
**Pull request by nickewansmith**
## Context

Users could reach the mUSD conversion confirmation with the wrong **Pay with** token (for example native ETH) when entering from certain entry points (for example a tertiary CTA). Automatic pay-token selection could run when a persisted or flow-default token should already be fixed.

## Problem

- **`updateTransactionPaymentToken`** could race with other updates, leading to the wrong token being stored or applied for the confirmation.
- **`MusdConversionInfo`** did not always disable automatic pay-token selection when a **preferred** token was already known (persisted controller state or flow default), so **Pay with** could be overwritten.

## Solution

- **Transaction pay token:** Address the race so the token written for the transaction matches the intended one (related change on this branch).
- **`MusdConversionInfo`:**
  - Build **`preferredToken`** from the persisted token first, then from **`useMusdConversionTokens`** **`defaultPaymentToken`** when nothing is persisted.
  - Set **`disablePay={Boolean(preferredToken)}`** on **`CustomAmountInfo`** so **`useAutomaticTransactionPayToken`** does not override when a preferred token exists.

## **Changelog**

CHANGELOG entry: Fixed incorrect pay token on the mUSD conversion confirmation when opening the flow from CTAs

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MUSD-662
Fixes: https://github.com/MetaMask/metamask-extension/issues/41704

## **Manual testing steps**

```
Feature: mUSD conversion confirmation — Pay with token

  Background:
    Given the user is on the mUSD conversion confirmation screen
    And the transaction is an mUSD conversion

  Scenario: Pay with stays on persisted token
    Given a payment token is already stored in TransactionPay state for this transaction
    When the confirmation screen loads
    Then automatic pay-token selection must not replace that token
    And the UI must use that token as the preferred pay token

  Scenario: Pay with uses default token when none is persisted
    Given no payment token is stored for this transaction in TransactionPay state
    And the mUSD conversion flow exposes a default payment token
    When the confirmation screen loads
    Then the default payment token must be used as the preferred pay token
    And automatic pay-token selection must not pick a different token (e.g. native ETH)

  Scenario: Automatic selection allowed when no preferred token exists
    Given no payment token is persisted for this transaction
    And there is no default payment token for this flow
    When the confirmation screen loads
    Then automatic pay-token selection may run as usual

  Scenario: Navigation trace includes payment token context
    When the mUSD conversion confirmation info mounts
    Then a MusdConversionNavigation trace ends with payment token chain and address
    And unknown placeholders are used when no token is available yet
```
### **Before**

https://www.loom.com/share/33e0251d22734db0aa62cdd46347a44c

### **After**

https://www.loom.com/share/131d3de840124939a6d5b2abaaa5b763

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Changes payment-token selection behavior for mUSD conversion confirmations and the transaction-pay controller update timing, which could affect which token is preselected/persisted in the pay flow if edge cases were missed.
> 
> **Overview**
> Fixes a race in the mUSD conversion start flow by `await`ing `updateTransactionPaymentToken` after navigation so the intended pay token is reliably persisted for the new transaction.
> 
> Updates confirmation UI token-selection logic: `CustomAmountInfo` gains `disableAutomaticToken` (disables `useAutomaticTransactionPayToken`), and `MusdConversionInfo` now derives `preferredToken` from persisted TransactionPay state or the flow’s `defaultPaymentToken` and always disables automatic selection to prevent overwrites. Tests are updated/added to cover these scenarios, including unknown-token tracing and skeleton rendering when the pay token is not yet set.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit ecda23a51e9ba9662e5c3c6affdd0993a141bb6c. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx [hunk 1]
```diff
@@ -102,7 +122,7 @@ export const MusdConversionInfo = () => {
 
   return (
     <CustomAmountInfo
-      disablePay={Boolean(existingPayToken)}
+      disablePay={Boolean(preferredToken)}
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx]: Are we not conceptually misusing `disablePay` here as we don't want to disable MetaMask Pay but just the automatic token selection.

This is only safe since you're providing overrides for the bottom and center content?

So to be explicit we'd have a new `disableAutomaticToken`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx (hunk 1 above)
Comment (nickewansmith) [reply ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx]: Added `disableAutomaticToken` and preserved existing intent

File: ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx [hunk 2]
```diff
@@ -102,7 +122,8 @@ export const MusdConversionInfo = () => {
 
   return (
     <CustomAmountInfo
-      disablePay={Boolean(existingPayToken)}
+      disableAutomaticToken={true}
+      disablePay={Boolean(preferredToken)}
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx]: Why do we still need `disablePay` at all if we're using `disableAutomaticToken`?

File: ui/pages/confirmations/components/info/custom-amount-info/custom-amount-info.tsx [hunk 3]
```diff
@@ -48,6 +48,15 @@ import { useConfirmContext } from '../../../context/confirm';
 export type CustomAmountInfoProps = {
   children?: ReactNode;
   currency?: string;
+  /**
+   * When true, passed to `useAutomaticTransactionPayToken` as `disableAutomaticToken` so automatic
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/info/custom-amount-info/custom-amount-info.tsx]: Minor, a bit low level here, could just say something like `Prevent automatic selection of payment token based on balance and feature flags`?

File: ui/pages/confirmations/components/info/custom-amount-info/custom-amount-info.tsx [hunk 4]
```diff
@@ -48,6 +48,15 @@ import { useConfirmContext } from '../../../context/confirm';
...
+   * `setPayToken` is skipped. Does not hide Pay UI; independent of `disablePay`.
+   */
+  disableAutomaticToken?: boolean;
+  /**
+   * When true, hides `PayTokenAmount` and `PayWithRow` in the default center layout and is passed to
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/info/custom-amount-info/custom-amount-info.tsx]: Minor, also pretty low level, could clarify it disables MetaMask Pay for transactions that just need custom amount input?

File: ui/pages/confirmations/hooks/pay/useAutomaticTransactionPayToken.ts [hunk 5]
```diff
@@ -10,9 +10,13 @@ import type { SetPayTokenRequest } from './types';
 
 export function useAutomaticTransactionPayToken({
   disable = false,
+  disableAutomaticToken = false,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/pay/useAutomaticTransactionPayToken.ts]: Why do we need this here if we already have `disable`? Wouldn't we just use a `||` from within `CustomAmountInfo`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/hooks/pay/useAutomaticTransactionPayToken.ts [hunk 6]
```diff
@@ -41,25 +45,28 @@ export function useAutomaticTransactionPayToken({
...
 
-    setPayToken({
-      address: automaticToken.address,
-      chainId: automaticToken.chainId,
-    });
+      setPayToken({
+        address: automaticToken.address,
+        chainId: automaticToken.chainId,
+      });
+    }
```
[the remark this answers is not in the document]
Comment (nickewansmith) [reply ui/pages/confirmations/hooks/pay/useAutomaticTransactionPayToken.ts:53]: I see, I just went back and forth with this a bit. What I did not consider is that we may update the prop arbitrarily and in that case, we should then be able to automatically set a token at that point. Will update.

File: ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx (hunk 2 above)
Comment (nickewansmith) [reply ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx]: `disablePay` does other things as well in `CustomAmountInfo`, separately from `disableAutomaticToken` from my understanding in our discussion and looking at the `CustomAmountInfo`. I am trying to avoid any sudden change I do not understand the effect of, being careful is all.

You mentioned that there are cases where we do not want to disable pay, but may want to prevent selecting a token automatically and that they are different paths. Maybe I am missing what you mean. Will send a DM.

File: ui/pages/confirmations/hooks/pay/useAutomaticTransactionPayToken.ts (hunk 5 above)
Comment (nickewansmith) [reply ui/pages/confirmations/hooks/pay/useAutomaticTransactionPayToken.ts]: Yea, that makes sense

File: ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx (hunk 2 above)
Comment (nickewansmith) [reply ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx]: I double checked this, but it might be safer to leave it imo.

Comment (nickewansmith) [reply ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx]: I understand now and will remove

File: ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx [hunk 7]
```diff
@@ -102,7 +122,7 @@ export const MusdConversionInfo = () => {
 
   return (
     <CustomAmountInfo
-      disablePay={Boolean(existingPayToken)}
+      disableAutomaticToken={true}
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/info/musd-conversion-info/musd-conversion-info.tsx:125]: Minor, but you don't need to assign if it's just a `true` boolean.

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by nickewansmith** [comment]
Thanks @matthewwalsh0 🙇🏽‍♂️

**Review by shane-t — APPROVED** [review]
