### PR TITLE
fix: issues with assets flag inside controllers

### LINKED ISSUE #42244: [Bug]: Perps, Convert - Multiple functionalities broken (Deposit, Convert to mUSD..) all throw background error `A handler for AssetsController:getStateForTransactionPay has not been registered`
**Describe the bug**
I cannot Add funds into Perps as when I land into the Deposit funds page, the buttons and UI is broken.
I also see the error `A handler for AssetsController:getStateForTransactionPay has not been registered`

Same for convert to mUSD, the page is broken with the same error and cannot convert

**Expected behavior**

No error

**Screenshots/Recordings**

https://github.com/user-attachments/assets/6b3d2577-5dc4-4d27-858b-4ab1f3252f28

https://github.com/user-attachments/assets/76bba2fc-b40e-45be-8002-f6e09e11685a

**Steps to reproduce**

1. Go to Perps tab
2. Click Add Funds
3. See error and cannot Deposit

========
1. Click on stable coing
2. Click convert to mUSD to get bonus
3. See broken page and error

**Error messages or log output**

```shell

```

**Where was this bug found?**

Internal release testing

**Version**

main - dist build 02c3f10af3cfd3bc05097286c756d766ce2e52e4 so it's going to affect 13.30.0
also nightly build

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by bergarces**
## **Description**

Fixes issue when the build-time feature flag for the new assets controller is off, but the remote feature flag is on.

It also passes the correct handler to bridge controller (up until now it was only using the old state).

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/42244

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches controller initialization and messenger action wiring used by bridge quotes and transaction pay flows; incorrect gating/handler registration could impact rate display or payment token state in some builds.
> 
> **Overview**
> Fixes feature-flag mismatches when the assets unified-state code is *not* included in the build but the remote flag is enabled.
> 
> `BridgeControllerInit` now passes `getUseAssetsControllerForRates`, which enables unified-state-backed rate fetching only when both the remote flag (`assetsUnifyState` v1) and the build-time inclusion check are true (falling back to `false` on errors); the init test is updated accordingly. `TransactionPayController` messenger now conditionally registers an `AssetsController:getStateForTransactionPay` handler when unified-state is excluded, synthesizing the expected state from existing controller states as a temporary rollout shim.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 04a6f183aed6344fb0c321b3928b906e0c3623ec. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: app/scripts/messenger-client-init/messengers/transaction-pay-controller-messenger.ts [hunk 1]
```diff
@@ -22,6 +24,12 @@ export function getTransactionPayControllerMessenger(
     parent: messenger,
   });
 
+  // TODO: Remove this once the assets unified state is fully rolled out
+  registerAssetsControllerGetStateForTransactionPayAction(
+    messenger,
+    controllerMessenger,
+  );
```
Comment (bergarces) [inline app/scripts/messenger-client-init/messengers/transaction-pay-controller-messenger.ts:31]: So this is only a problem when the build-time flag is off (which means the controller is not initialised) but the feature flag is on.

Which is an issue for nightly and CI builds, which seem to use `main-dev` launchdarkly flag instead of `main-exp` or others. We are currently only enabling the build-time flag in dev.

This shouldn't happen in rc or prod, because both of those envs have their own distinct launchdarkly feature flag.

With these changes, whenever the build-time feature flag is not on, it will register the handler. It won't register it if the build-time flag is on, so it cannot register duplicates.

Then, if the remote feature flag is off, no harm done as that handler won't be called. But if it is on, this replicates the behaviour of it when it's off.

The reason we are not passing a hook like we do for bridge, is because transaction-pay-controller would require to drill down that hook to a lot of functions.

File: app/scripts/messenger-client-init/bridge-controller-init.ts [hunk 2]
```diff
@@ -104,6 +111,27 @@ export const BridgeControllerInit: MessengerClientInitFunction<
...
+          .remoteFeatureFlags[ASSETS_UNIFY_STATE_FLAG] as
+          | AssetsUnifyStateFeatureFlag
+          | undefined;
+
+        return (
+          isAssetsUnifyStateFeatureEnabled(
+            featureFlag,
+            ASSETS_UNIFY_STATE_VERSION_1,
+          ) && getIsAssetsUnifiedStateIncludedInBuild()
+        );
```
Comment (bergarces) [inline app/scripts/messenger-client-init/bridge-controller-init.ts:130]: Only true if both the launch darkly flag and the build-time flag are on.

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by bergarces** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=metamask-extension&pullRequest=42258) **Quality Gate failed**
> Failed conditions  [7.9% Coverage on New Code](https://sonarcloud.io/component_measures?id=metamask-extension&pullRequest=42258&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=metamask-extension&pullRequest=42258)

I'm not writing a test for registering that handler.

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/scripts/messenger-client-init/bridge-controller-init.ts [hunk 3]
```diff
@@ -104,6 +111,27 @@ export const BridgeControllerInit: MessengerClientInitFunction<
     config: {
       customBridgeApiBaseUrl: BRIDGE_API_BASE_URL,
     },
+
+    getUseAssetsControllerForRates: () => {
```
Comment (bergarces) [inline app/scripts/messenger-client-init/bridge-controller-init.ts:115]: By not passing this, the controller was still using the legacy state data.

**Review by juanmigdr — APPROVED** [review]

**Review by salimtb — APPROVED** [review]
