### PR TITLE
fix: changes the logic for destination acct modal open

### LINKED ISSUE #38125: [Bug]: Swap - Cannot close the modal for the Recipient if I'm performing a Swap with a hardware wallet to another account
### Describe the bug

Cannot close the modal for the Recipient if I'm performing a Swap with a hardware wallet to another account.
Whenever I have to select the Account, clicking on the close modal does nothing.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/246edb82-00b3-4cd5-aba4-710e815eb106

### Steps to reproduce

1. Import a hardware wallet
2. Start a Swap to a non-EVM network
3. See Recipient modal appears
4. Click Close
5. See nothing happens

### Error messages or log output

```shell

```

### Detection stage

Production

### Version

13.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

When bridging to a non-EVM chain (like Bitcoin or Solana) without a matching account type, the destination account picker modal opens automatically. However, users were unable to close the modal without selecting an account first - clicking the close button did nothing.

This happened because the modal had redundant forced-open logic: `isOpen={isOpen || (isToOrFromNonEvm && !selectedAccount)}`. The OR condition prevented the modal from closing even when `isOpen` was set to false.

The fix:
1. Removes this forced-open condition from the modal component. The auto-open behavior is already handled by the `useDestinationAccount` hook.
2. Adds logic to the main action button so that if a user closes the modal without selecting an account, they can click the "Select Destination Account" button to re-open it.
3. Reorders the button label logic to prioritize user input prompts (amount, destination account) before quote-related states (loading, expired, no quotes). This ensures the button always shows actionable guidance rather than appearing blank when a destination account is needed but no quotes have been fetched yet.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38453?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed an issue where the destination account picker modal could not be closed when bridging to non-EVM chains

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38125

## **Manual testing steps**

1. Remove any Bitcoin or Solana accounts from your wallet (or use a fresh wallet with only EVM accounts)

2. Go to the Bridge page

3. Select Bitcoin or Solana as the destination chain

4. The destination account picker modal should open automatically

5. Click the X button or click outside the modal to close it

6. Verify the modal closes successfully

7. Verify the main action button displays "Select destination account" (not blank)

8. Click the main action button and verify the modal re-opens

9. Select an account and verify normal bridge flow continues

### **Before**

https://github.com/user-attachments/assets/e13022cc-4ac9-41fc-8af9-beb7ff0a643a

### **After**

https://github.com/user-attachments/assets/d511d565-3361-4c08-a267-8b06781e4b61

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Fixes destination account modal control and improves Bridge CTA behavior/labels, with related i18n cleanup across locales.
> 
> - **Bridge UI**:
>   - **Destination account modal**: Remove forced-open logic in `destination-account-picker-modal.tsx`; modal now opens via state. Wire `BridgeCTAButton` with `onOpenRecipientModal` and trigger when `needsDestinationAddress`.
>   - **CTA behavior/labels**: Reorder label logic in `bridge-cta-button.tsx` to prioritize prompts for token/amount/destination account; allow CTA to render when a destination account is needed; adjust disabled logic accordingly.
>   - **Prepare page**: Pass `onOpenRecipientModal` to open the recipient modal on CTA click.
> - **i18n**:
>   - Remove `bridgeEnterAmountAndSelectAccount` across locales; tweak English copy to "Select a destination account"; keep related bridge strings intact.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9cf0a20a8e78fa84910f244037d943b4810aff0e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/bridge/prepare/components/destination-account-picker-modal.tsx [hunk 1]
```diff
@@ -79,11 +75,9 @@ export const DestinationAccountPickerModal = ({
     [accounts, searchQuery],
   );
 
-  const isToOrFromNonEvm = useSelector(getIsToOrFromNonEvm);
-
   return (
     <Modal
-      isOpen={isOpen || (isToOrFromNonEvm && !selectedAccount)}
```
Comment (SteP-n-s) [inline ui/pages/bridge/prepare/components/destination-account-picker-modal.tsx:86]: I believe the `!selectedAccount` was done to ensure that users can't close the modal if they haven't selected a nonEVM account. cc'ing @micaelae in case she remembers the exact reason.

Comment (micaelae) [reply ui/pages/bridge/prepare/components/destination-account-picker-modal.tsx:86]: This handles an edge case where the user's selected src account is a hardware device and so we can't infer the default non-EVM destination account. This was an issue in the initial BIP-44 build

With this change, are you able to fetch quotes and can you verify that the default dest address in the quote request matches the network @ghgoodreau ?

File: ui/pages/bridge/prepare/bridge-cta-button.tsx [hunk 2]
```diff
@@ -127,7 +129,7 @@ export const BridgeCTAButton = ({
     return undefined;
   }, [wasTxDeclined, isQuoteExpired]);
 
-  return activeQuote && !secondaryButtonLabel ? (
+  return (activeQuote || needsDestinationAddress) && !secondaryButtonLabel ? (
```
[the remark this answers is not in the document]
Comment (ghgoodreau) [reply ui/pages/bridge/prepare/bridge-cta-button.tsx:132]: There will be no quote request without a destination account, so this can be discarded

**Review by micaelae — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]

File: ui/pages/bridge/prepare/components/destination-account-picker-modal.tsx (hunk 1 above)
Comment (SteP-n-s) [reply ui/pages/bridge/prepare/components/destination-account-picker-modal.tsx:86]: @ghgoodreau are we good to resolve this or are there still concerns?
