### PR TITLE
"eth_signTypedData" presents fields that do not appear in 'types' filed

### LINKED ISSUE #11457: "eth_signTypedData" presents fields that do not appear in 'types' filed
**Describe the bug**
When executing a call to 'eth_signTypedData', the expectation is that the message that is presented to the user and the data that will be signed must match exactly. In fact, what seems to happen is that MetaMask presents the entire 'message' field, including fields that do not appear in the 'types' field. If that is in fact what is happening, it seems to present some security risk as clients can be expecting to sign on some fields, such as "expirationBlock" and such, but in fact these fields are not part of EIP-712 signature created.

**Steps to reproduce (REQUIRED)**
Note that the pseudocode is a simplified version of affected production code:

1. Define an EIP-712 type structure:
```
dataToSign.type = [
  { name: 'operationA', type: 'uint256' },
  { name: 'operationB', type: 'uint256' }
]
``` 

2. Create an object:
```
dataToSign.message = {
  operationA: 123,
  operationA: 456,
  expirationBlock: 12777777
}
```
3. Execute

```
web3.currentProvider.send({
  method: 'eth_signTypedData_v4',
  params: [senderAddress, dataToSign],
  from: senderAddress
})
```

**Expected behavior**
Expectation: `expirationBlock` field does not appear in a signature popup. UPD: preferably, exception is raised indicating that structure does not match the supposed data type.
Actual: `expirationBlock` field appears as usual, but is not part of a signed data.

### PR DESCRIPTION
**Pull request by segun**
Fixes: #11457 

Explanation:  
When executing a call to 'eth_signTypedData', the expectation is that the message that is presented to the user and the data that will be signed must match exactly. In fact, what seems to happen is that MetaMask presents the entire 'message' field, including fields that do not appear in the 'types' field. If that is in fact what is happening, it seems to present some security risk as clients can be expecting to sign on some fields, such as "expirationBlock" and such, but in fact these fields are not part of EIP-712 signature created.

Manual testing steps:  
see #11457 
  - 
  - 
  -

### CODE REVIEW

File: ui/components/app/signature-request/signature-request.component.js [hunk 1]
```diff
@@ -45,9 +45,85 @@ export default class SignatureRequest extends PureComponent {
...
+    };
+
+    const sanitizeMessage = (msg, baseType) => {
+      if (version === 'V4') {
+        const sanitizedMessage = {};
+        const msgKeys = Object.keys(msg);
+        const msgTypes = Object.values(msg).map((value) => typeof value);
+        const baseTypeType = types[baseType];
+        msgKeys.forEach((msgKey, index) => {
+          const valueType = msgTypes[index];
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:77]: Please use `Object.entries` to iterate over the keys and values of an object, rather than using `Object.keys` and `Object.values` and tying them together with the index. It's much easier to read that way, and it avoids concerns of iteration order not being standardized for objects.

Comment (Gudahtt) [reply ui/components/app/signature-request/signature-request.component.js:77]: Also, what is the purpose of looking at the `typeof` of the value? The type of the value is not useful, and is entirely distinct from the type defined in the message.

File: ui/components/app/signature-request/signature-request.component.js [hunk 2]
```diff
@@ -45,9 +45,85 @@ export default class SignatureRequest extends PureComponent {
...
+          if (baseTypeType) {
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:78]: This doesn't need to be in the loop. I'd suggest checking this before the loop, and negating this condition and exiting early rather than indenting everything.

File: ui/components/app/signature-request/signature-request.component.js [hunk 3]
```diff
@@ -45,9 +45,85 @@ export default class SignatureRequest extends PureComponent {
...
+        msgType === 'string'
+      ) {
+        return true;
+      }
+
+      return false;
+    };
+
+    const sanitizeMessage = (msg, baseType) => {
+      if (version === 'V4') {
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:71]: Why only V4?

Comment (segun) [reply ui/components/app/signature-request/signature-request.component.js:60]: I thought only V4 has types...just checked test-app and saw it not.

File: ui/components/app/signature-request/signature-request.component.js [hunk 4]
```diff
@@ -45,9 +45,72 @@ export default class SignatureRequest extends PureComponent {
...
+    const solidityTypes = [
+      'bool',
+      'int',
+      'fixed',
+      'address',
+      'bytes',
+      'string',
+    ];
+    const sanitizeMessage = (msg, baseType) => {
+      let baseTypeType;
```
Comment (jpuri) [inline ui/components/app/signature-request/signature-request.component.js:60]: better name for this `baseTypeType` ?

File: ui/components/app/signature-request/signature-request.component.js [hunk 5]
```diff
@@ -45,9 +45,72 @@ export default class SignatureRequest extends PureComponent {
       hardwareWalletRequiresConnection,
     } = this.props;
     const { address: fromAddress } = fromAccount;
-    const { message, domain = {} } = JSON.parse(data);
+    const { message, domain = {}, types, primaryType } = JSON.parse(data);
     const { metricsEvent } = this.context;
```
Comment (jpuri) [inline ui/components/app/signature-request/signature-request.component.js:50]: It will be easy to understand `sanitizeMessage` if it can be extracted into a util function and test covered.

File: ui/components/app/signature-request/signature-request.component.js (hunk 4 above)
Comment (Gudahtt) [reply ui/components/app/signature-request/signature-request.component.js:60]: Maybe `baseTypeDefinition`?

File: ui/components/app/signature-request/signature-request.component.js [hunk 6]
```diff
@@ -45,9 +45,72 @@ export default class SignatureRequest extends PureComponent {
...
+        }
+      } else {
+        return msg;
+      }
+
+      const sanitizedMessage = {};
+      const msgKeys = Object.keys(msg);
+      msgKeys.forEach((msgKey) => {
+        const definedType = Object.values(baseTypeType).find(
+          (ptt) => ptt.name === msgKey,
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:74]: What does `ptt` mean? We should replace this with a better variable name. e.g. `property`

File: ui/components/app/signature-request/signature-request.component.js (hunk 1 above)
Comment (Gudahtt) [reply ui/components/app/signature-request/signature-request.component.js]: Note that this has not yet been addressed. You're still using `Object.keys` and `Object.values` instead of `Object.entries`.

File: ui/components/app/signature-request/signature-request.component.js [hunk 7]
```diff
@@ -45,9 +45,72 @@ export default class SignatureRequest extends PureComponent {
...
+              // nested object
+              sanitizedMessage[msgKey] = sanitizeMessage(
+                msg[msgKey],
+                definedType.type,
+              );
+            }
+          } else {
+            // check if it's a valid solidity type
+            const isSolidityType = solidityTypes.some(
+              (solidityType) => definedType.type.indexOf(solidityType) >= 0,
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:103]: This would allow invalid types that started with a solidity type. For example `stringfoo` would be recognized as a Solidity type here, despite not being a real type.

File: ui/components/app/signature-request/signature-request.component.js (hunk 4 above)
Comment (Gudahtt) [reply ui/components/app/signature-request/signature-request.component.js:60]: And also the below variable `nestedTypeType` could be `nestedTypeDefinition`

File: ui/components/app/signature-request/signature-request.component.js [hunk 8]
```diff
@@ -45,9 +45,72 @@ export default class SignatureRequest extends PureComponent {
...
+              const sanitizedArrayMessage = {};
+              const definedArrayType = definedType.type.replace('[]', '');
+              const arrayMsg = msg[msgKey];
+              arrayMsg.forEach((msgArray, arrIndex) => {
+                sanitizedArrayMessage[arrIndex] = sanitizeMessage(
+                  msgArray,
+                  definedArrayType,
+                );
+              });
+              sanitizedMessage[msgKey] = sanitizedArrayMessage;
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:92]: This seems overly complex. This can be done more simply with `.map`.

e.g.

```suggestion
              sanitizedMessage[msgKey] = msg[msgKey].map((value) => sanitizeMessage(value, definedArrayType));
```

File: ui/components/app/signature-request/signature-request.component.js (hunk 1 above)
Comment (Gudahtt) [reply ui/components/app/signature-request/signature-request.component.js]: I must have misunderstood; there is no longer a secondary call to `Object.values` on the same object. I was mistaking the type definition object for the message I think.

You still could use `Object.entries` here but it would be a minimal improvement to readability at best.

File: ui/helpers/utils/util.js [hunk 9]
```diff
@@ -443,3 +443,77 @@ export const toHumanReadableTime = (t, milliseconds) => {
...
+const solidityTypes = () => {
+  const types = [
+    'bool',
+    'address',
+    'string',
+    'bytes',
+    'int',
+    'uint',
+    'fixed',
+    'ufixed',
```
Comment (Gudahtt) [inline ui/helpers/utils/util.js:456]: We should also include the explicitly sized versions of `fixed` and `ufixed`, i.e. `ufixedMxN` where M is divisible by 8 and between 8 and 256 (inclusive), and N is an integer between 0 and 80.

Details: https://docs.soliditylang.org/en/latest/types.html#fixed-point-numbers

File: ui/components/app/signature-request/signature-request.component.js [hunk 10]
```diff
@@ -105,7 +106,7 @@ export default class SignatureRequest extends PureComponent {
             <LedgerInstructionField showDataInstruction />
           </div>
         ) : null}
-        <Message data={message} />
+        <Message data={sanitizeMessage(message, primaryType)} />
```
Comment (Gudahtt) [inline ui/components/app/signature-request/signature-request.component.js:109]: It looks like the third parameter, `types`, is supposed to be passed in here

File: ui/helpers/utils/util.js [hunk 11]
```diff
@@ -443,3 +443,77 @@ export const toHumanReadableTime = (t, milliseconds) => {
...
+      } else {
+        // check if it's a valid solidity type
+        const isSolidityType = solidityTypes().includes(
+          definedType.type.replace('[]', ''),
+        );
+        if (isSolidityType) {
+          sanitizedMessage[msgKey] = msg[msgKey];
+        }
+      } // endif (nestedType)
+    } // endif (definedType)
```
Comment (Gudahtt) [inline ui/helpers/utils/util.js:516]: Nit: To avoid lots of indentation, and the need for comments like this, you could invert the condition.

Rather than:

```
if (definedType) {
  ...
}
```
Do something like this:

```
if (!definedType) {
  return;
}
...
```

File: ui/helpers/utils/util.js [hunk 12]
```diff
@@ -443,3 +443,77 @@ export const toHumanReadableTime = (t, milliseconds) => {
...
+          sanitizedMessage[msgKey] = sanitizeMessage(
+            msg[msgKey],
+            definedType.type,
+            types,
+          );
+        }
+      } else {
+        // check if it's a valid solidity type
+        const isSolidityType = solidityTypes().includes(
+          definedType.type.replace('[]', ''),
```
Comment (Gudahtt) [inline ui/helpers/utils/util.js:510]: We should exclude types with `[]` at the beginning or middle as well:
```suggestion
          definedType.type.replace(\[\]$/, ''),
```

File: ui/helpers/utils/util.test.js [hunk 13]
```diff
@@ -340,4 +340,101 @@ describe('util', () => {
       expect(util.toHumanReadableTime(t, 7200000)).toStrictEqual('2 hrs');
     });
   });
+  describe('sanitizeMessage', () => {
+    const message = {
```
Comment (Gudahtt) [inline ui/helpers/utils/util.test.js:344]: Nit: Better to move these fixtures to a function, and call this function in each test to get a fresh copy, just in case one of the tests mutates the object.

If these get mutated by one of the tests, it could invalidate the test result, and it might also be very difficult to track down the issue. It could also lead to dependencies between tests.

File: ui/helpers/utils/util.test.js [hunk 14]
```diff
@@ -340,4 +340,101 @@ describe('util', () => {
...
+      EIP712Domain: [
+        { name: 'name', type: 'string' },
+        { name: 'version', type: 'string' },
+        { name: 'chainId', type: 'uint256' },
+        { name: 'verifyingContract', type: 'address' },
+      ],
+      Group: [
+        { name: 'name', type: 'string' },
+        { name: 'members', type: 'Person[]' },
+      ],
```
Comment (Gudahtt) [inline ui/helpers/utils/util.test.js:375]: This type appears to be unused :thinking: 

```suggestion
```

File: ui/helpers/utils/util.js [hunk 15]
```diff
@@ -443,3 +443,77 @@ export const toHumanReadableTime = (t, milliseconds) => {
...
+  );
+  return [...types, ...ints, ...uints, ...bytes];
+};
+
+export const sanitizeMessage = (msg, baseType, types) => {
+  let baseTypeDefinitions;
+  if (types) {
+    baseTypeDefinitions = types[baseType];
+    if (!baseTypeDefinitions) {
+      return msg;
```
Comment (Gudahtt) [inline ui/helpers/utils/util.js:476]: Is it possible for a signature request to get this far without any types, or with no primary type? I would hope this would be caught by our validation, but maybe not.

If this is possible, showing the user a message preview that could be totally wrong sounds dangerous :thinking:

Comment (segun) [reply ui/helpers/utils/util.js:476]: I agree, but not sure what to do in these instance.

File: ui/helpers/utils/util.js [hunk 16]
```diff
@@ -443,3 +443,109 @@ export const toHumanReadableTime = (t, milliseconds) => {
...
+    // key has a type. check if the definedType is also a type
+    const nestedTypeDefinition = types[definedType.type.replace('[]', '')];
+
+    if (nestedTypeDefinition) {
+      if (definedType.type.indexOf('[]') > 0) {
+        // nested array
+        const definedArrayType = definedType.type.replace('[]', '');
+        sanitizedMessage[msgKey] = msg[msgKey].map((value) =>
+          sanitizeMessage(value, definedArrayType, types),
+        );
```
Comment (Gudahtt) [inline ui/helpers/utils/util.js:531]: Same thing here re: ensuring the type ends in `[]`
```suggestion
    const nestedTypeDefinition = types[definedType.type.replace(/\[\]$/, '')];

    if (nestedTypeDefinition) {
      if (definedType.type.endsWith('[]')) {
        // nested array
        const definedArrayType = definedType.type.replace(/\[\]$/, '')];
        sanitizedMessage[msgKey] = msg[msgKey].map((value) =>
          sanitizeMessage(value, definedArrayType, types),
        );
```

Or, to cache the nested type name:

```suggestion
    const nestedType = definedType.type.replace(/\[\]$/, '');
    const nestedTypeDefinition = types[nestedType];

    if (nestedTypeDefinition) {
      if (definedType.type.endsWith('[]')) {
        // nested array
        sanitizedMessage[msgKey] = msg[msgKey].map((value) =>
          sanitizeMessage(value, nestedType, types),
        );
```

File: ui/helpers/utils/util.js (hunk 15 above)
Comment (Gudahtt) [reply ui/helpers/utils/util.js:505]: I have just confirmed that it is safe to assume here that `types` is defined, and that `primaryType` is included in `types`. So we should throw an error here for those cases.

This is guaranteed by the validation performed here: https://github.com/MetaMask/metamask-extension/blob/5e9ea9d8fad692d6b8346ccd72fc65a78e29164c/app/scripts/lib/typed-message-manager.js#L192

This is done before the message gets added to our state as an unapproved message. Validation is done [here](https://github.com/MetaMask/metamask-extension/blob/5e9ea9d8fad692d6b8346ccd72fc65a78e29164c/app/scripts/lib/typed-message-manager.js#L127), whereas the message isn't added until later ([here](https://github.com/MetaMask/metamask-extension/blob/5e9ea9d8fad692d6b8346ccd72fc65a78e29164c/app/scripts/lib/typed-message-manager.js#L143)).

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by jpuri — APPROVED** [review]
