### PR TITLE
"Cancel/reject all" for signature requests #13201

### LINKED ISSUE #13201: "Cancel/reject all" for signature requests
**Describe the bug**
When several transactions are pending user approval, there is an option to batch-reject all pending requests.

When several signature requests are pending user approval, there is NO option to batch-reject all pending requests.

**Steps to reproduce**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to https://metamask.github.io/test-dapp/ and connect an account if you have not already done so.
2. In the box labeled "Sign Typed Data" click on "Sign" several times.
3. Popups that look like this will appear each time, but don't click on anything there: 
image
4. If you click away, you'll notice there are several pending requests: 
image
5. Clicking back on that icon you see the same popup as before, with no option to cancel/reject all.
6. Manually click Cancel on all of them.
7. On the same page, in the box labeled "Send Eth" click "Send" twice.
8. The popup presents an option to reject/confirm or reject all (though you might have to scroll down within the popup to see it, due to the new 'New address detected! Click here to add to your address book.' bubble at the top): 
image

**Expected behavior**
Consistency between these two: if transactions have the Reject All option, signature requests should too.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: N/A
 - Browser: Google Chrome 96.0.4664.110 (Official Build) (64-bit) (cohort: Stable)
 - MetaMask Version: 10.8.1

**Security impact:**
Triggering a large number of signature requests from any one site could be used as a DoS attack on MetaMask users because all the bogus requests from an attacking site MUST be manually and individually handled before ANY legitimate requests can be handled.

Though this project's [Security Policy](https://github.com/MetaMask/metamask-extension/security/policy) was "Last updated 20 days ago" the primary issue with that policy, [which I reported over 60 days ago](https://github.com/MetaMask/metamask-extension/issues/12374), remains outstanding.  As the program linked is related to the NodeJS ecosystem, recent experience from attempting to report a higher-severity issue seems relevant, and the result from that was that the issue should be discussed publicly without remediation.  While the DoS attack made possible by this Issue could be spread widely by e.g. including malicious code in an advertising network, cutting it off should be a relatively easy fix as something similar already exists for transactions.

### PR DESCRIPTION
**Pull request by dragana8**
Fixes: #13201 
https://github.com/MetaMask/metamask-extension/issues/13201)
Screenshot 2022-02-28 at 13 20 29
Screenshot 2022-02-28 at 13 20 47

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

File: ui/components/app/signature-request-original/signature-request-original.component.js [hunk 1]
```diff
@@ -327,6 +354,14 @@ export default class SignatureRequestOriginal extends Component {
           </div>
         ) : null}
         {this.renderFooter()}
+        {messagesCount > 1 ? (
+          <a
```
Comment (darkwing) [inline ui/components/app/signature-request-original/signature-request-original.component.js:358]: We should use a `<button>` component for accessibility instead of the `<a>`

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/components/app/signature-request-original/signature-request-original.component.js (hunk 1 above)
Comment (dragana8) [reply ui/components/app/signature-request-original/signature-request-original.component.js]: @darkwing updated.

File: ui/components/app/signature-request-original/signature-request-original.component.js [hunk 2]
```diff
@@ -327,6 +354,15 @@ export default class SignatureRequestOriginal extends Component {
...
         {this.renderFooter()}
+        {messagesCount > 1 ? (
+          <Button
+            type="link"
+            className="request-signature__container__reject"
+            onClick={() => this.handleCancelAll()}
+          >
+            {rejectNText}
+          </Button>
+        ) : null}
```
Comment (mrbaguvix) [inline ui/components/app/signature-request-original/signature-request-original.component.js:365]:
```suggestion
        ) :<></>}
```

**Review by 0ex-d — CHANGES_REQUESTED** [review]

File: ui/components/app/signature-request-original/signature-request-original.component.js (hunk 2 above)
Comment (dragana8) [reply ui/components/app/signature-request-original/signature-request-original.component.js]: @mrbaguvix updated.

**Review by 0ex-d — DISMISSED** [review]

File: ui/components/app/signature-request-original/signature-request-original.component.js (hunk 2 above)
Comment (dragana8) [reply ui/components/app/signature-request-original/signature-request-original.component.js:365]: @brad-decker done.

Comment (mrbaguvix) [reply ui/components/app/signature-request-original/signature-request-original.component.js:365]: Oh my bad, just noticed you're using the good 'ol _class-based_ component. `null` is good.

**Review by 0ex-d — DISMISSED** [review]

File: ui/components/app/signature-request-original/signature-request-original.container.js [hunk 3]
```diff
@@ -29,6 +30,20 @@ function mapStateToProps(state, ownProps) {
...
+    unapprovedEncryptionPublicKeyMsgCount,
+    unapprovedMsgCount,
+  } = state.metamask;
+  const messagesList = unconfirmedMessagesHashSelector(state);
+  const messagesCount =
+    unapprovedTypedMessagesCount +
+    unapprovedPersonalMsgCount +
+    unapprovedDecryptMsgCount +
+    unapprovedEncryptionPublicKeyMsgCount +
+    unapprovedMsgCount;
```
Comment (adonesky1) [inline ui/components/app/signature-request-original/signature-request-original.container.js:46]: Should we make a selector that does this aggregate message count? `getTotalUnapprovedMessagesCount`?

Comment (dragana8) [reply ui/components/app/signature-request-original/signature-request-original.container.js]: @adonesky1 makes sense. Done. :)

**Review by danjm — APPROVED** [review]
LGTM, nice work

**Comment by darkwing** [comment]
Wow, tested with the following and works great!

```
Promise.all([
    ethereum.request({
        method: 'personal_sign',
        params: ['Hello!', '0x0c5ea7378986bcfaecfd81c848f41ecf24523316', 'Example password'],
    }),
    ethereum.request({
        method: 'personal_sign',
        params: ['Hello!', '0x0c5ea7378986bcfaecfd81c848f41ecf24523316', 'Example password'],
    })
])
```

**Review by darkwing — APPROVED** [review]
