### PR TITLE
Handling gas price fetch failure 

### LINKED ISSUE #10556: TypeError: Failed to fetch (gasPrices api on the confirmation page)
Sentry Issue: [METAMASK-3H10](https://sentry.io/organizations/metamask/issues/749961265/?referrer=github_integration)

```
TypeError: Failed to fetch
```

This is coming from the calls of `fetchBasicGasEstimates` and ultimately `basicGasPriceQuery` which are defined in `gas.duck.js`

The solution will require at least three pieces:
- a fallback when `fetchBasicGasEstimates` fails to `eth_gasPrice`
- ensure the UI appropriately responds to the fallback
- handle the case when both `fetchBasicGasEstimates` fails to `eth_gasPrice` fail, which will require both gas price logic and UI updates

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
Fixes: #10556 

Explanation:  Currently when the gas estimate service is unavailable, the gas row send and confirm page will go into infinite loading loop.

**Changes introduced:**
- Advanced gas input will be displayed in case the main service fails, eth_gasprice will be fetched and the submission buttons will be active.
- In cases where both main service eth_gasprice and main service fails, Advanced gas input will be displayed, gasPrice displayed will be 0 and the primary button `next` button in the send flow or `confirm` button in the confirmation flow will be disabled.

Manual testing steps:  

**Gas estimation service failing and eth_gasprice fetched:**

You can mimmic the gas price fetch failure by replacing `basicGasPriceQuery` call in `fetchExternalBasicGasEstimates` by `Promise.reject()`

**_Send Page:_**
Screen Shot 2021-04-22 at 4 37 27 PM

**_Confirmation page:_** 

https://user-images.githubusercontent.com/43930900/115785726-d7baec80-a38d-11eb-8d47-66a295280082.mov

**Both the gas estimation services failed:**

You can mimmic the gas price fetch failure by replacing `global.eth.gasPrice()` call in `fetchEthGasPriceEstimates` by `Promise.reject()`;

**_Send Page:_**
Screen Shot 2021-04-22 at 4 19 15 PM

**_Confirmation page:_**

https://user-images.githubusercontent.com/43930900/115785732-d8ec1980-a38d-11eb-9655-a8ff5c194b11.mov

### CODE REVIEW

File: ui/app/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.component.js [hunk 1]
```diff
@@ -123,19 +123,25 @@ export default class GasModalPageContainer extends Component {
...
-        name: this.context.t('basic'),
-        content: this.renderBasicTabContent(gasPriceButtonGroupProps),
-      },
-      {
-        name: this.context.t('advanced'),
-        content: this.renderAdvancedTabContent(),
-      },
-    ];
-
+    let tabsToRender;
```
Comment (brad-decker) [inline ui/app/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.component.js:126]: [Q] This change looks like a good one, as it prevents calling the render method of the basic tab content entirely when hideBasic is true. Was that the intent here? does this serve a purpose in the new error message?

File: ui/app/ducks/gas/gas.duck.js [hunk 2]
```diff
@@ -29,6 +31,7 @@ const initState = {
     fast: null,
   },
   basicEstimateIsLoading: true,
+  isEthGasPriceFetched: false,
```
Comment (brad-decker) [inline ui/app/ducks/gas/gas.duck.js:34]: It seems that this introduces a competing state flag with 'basicEstimateIsLoading'. What I mean to say here is that in order to properly update state we have to check the difference between two keys instead of referencing one key.

What if we refactored the gas slice state to be more like:
```
basicEstimateStatus: 'LOADING' | 'READY' | 'FAILED';
```

In this way we can check one key and branch from the possible states instead of storing the 'status' of the state slice across a few different keys.

Comment (brad-decker) [reply ui/app/ducks/gas/gas.duck.js:34]: As i'm reading more through the logic below I am wondering if this key doesn't actually mean what I think it does. It seems its only set to true if fetchExternalBasicGasEtimates fails and fetchEthGasPriceEstimates succeeds. Could you help me understand a little more?

File: ui/app/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.component.js (hunk 1 above)
Comment (NiranjanaBinoy) [reply ui/app/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.component.js:126]: Originally, I introduced this change because when the gas fetch fails without any backup estimate, the `basicEstimates` value will be null and calling `renderBasicTabContent` will crash the extension even if hideBasic is true. But later I removed the `Advanced option` from send page and `edit` for gas row from confirmation page in cases of failures `advanced input option` is already present in the pages , currently only the approve-token page will have the `edit ` option, which calls the gas modal. (this realization came to be when I started replying to this message 😓)

Also when the gas fetch fails without backup, we are disabling submission from the corresponding page, in our test dapp the user cannot reach the approve token page without successfully completing create token, if  that is the scenario everywhere we can maybe remove this changes and use the old one.

I think preventing the rendering of basic tab when hideBasic is true might be a better option as it will results in application crashing if in case the basicEstimates is null, unless there is any specific reason to add both the tabs and remove the `basic tab` in case `hideBasic` is true previously.

File: ui/app/ducks/gas/gas.duck.js (hunk 2 above)
Comment (NiranjanaBinoy) [reply ui/app/ducks/gas/gas.duck.js:34]: In mainnet, `isEthGasPriceFetched` flag is set to `true` only when the original [gas estimation service](https://api.metaswap.codefi.network/gasPrices) fails, but eth_gasprice is available (`fetchEthGasPriceEstimates` is called), and a warning message will be displayed based on this flag. In testnet the flag will be false, as testnets are not affected by the failure of this service.

When both the [gas estimation service](https://api.metaswap.codefi.network/gasPrices) and eth_gasprice fails, the basicEstimates being null is used to identify the condition, and the corresponding changes affects both mainnet and testnets.

Comment (brad-decker) [reply ui/app/ducks/gas/gas.duck.js:34]: Alright so I might suggest the following to avoid using `null` as a logic check:

```
basicEstimateStatus: 'LOADING' | 'READY' | 'FAILED',
estimateSource: 'MetaSwaps' | 'eth_gasprice',
```

Now you can check for failed state by `basicEstimateStatus === 'FAILED'` and the source for your error message by `estimateSource === 'eth_gasprice'` and the code will be easier to maintain going forward. Thoughts on that?

Comment (NiranjanaBinoy) [reply ui/app/ducks/gas/gas.duck.js]: I have updated the PR based on these comments.

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/app/selectors/custom-gas.js [hunk 3]
```diff
@@ -355,3 +357,20 @@ export function getRenderableEstimateDataForSmallButtonsFromGWEI(state) {
     },
   ];
 }
+
+export function getIsEthGasPriceFetched(state) {
+  const gasState = state.gas;
+  return Boolean(
+    gasState.estimateSource === 'eth_gasprice' &&
+      gasState.basicEstimateStatus === 'READY' &&
+      getIsMainnet(state),
```
[the remark this answers is not in the document]
Comment (NiranjanaBinoy) [reply ui/app/selectors/custom-gas.js:366]: My intent here was to make sure that the estimates fetched using eth_gasprice in this scenario are from Mainnet and not from the Testnets. Because we are displaying a warning to the user when we fetch gas price from eth_gasprice in Mainnet when Metaswaps service fails, this warning is not needed in the case of Testnets.

File: ui/app/selectors/custom-gas.js [hunk 4]
```diff
@@ -355,3 +357,20 @@ export function getRenderableEstimateDataForSmallButtonsFromGWEI(state) {
...
+  );
+}
+
+export function getNoGasPriceFetched(state) {
+  const gasState = state.gas;
+  return Boolean(
+    gasState.estimateSource === 'eth_gasprice' &&
+      gasState.basicEstimateStatus === 'FAILED',
```
[the remark this answers is not in the document]
Comment (NiranjanaBinoy) [reply ui/app/selectors/custom-gas.js:374]: Yea 😅

File: ui/app/pages/send/send-footer/send-footer.component.js [hunk 5]
```diff
@@ -27,6 +27,7 @@ export default class SendFooter extends Component {
     gasEstimateType: PropTypes.string,
     gasIsLoading: PropTypes.bool,
     mostRecentOverviewPage: PropTypes.string.isRequired,
+    noGasPrice: PropTypes.bool,
```
[the remark this answers is not in the document]
Comment (NiranjanaBinoy) [reply ui/app/pages/send/send-footer/send-footer.component.js:30]: 'gasIsLoading' seems to be from `state.appState` and it is based on not just the gas price estimate fetch, whereas `noGasPrice` is based on the status of gas estimation fetch alone. I am confused on why we have 'gasIsLoading' when we also had  `basicGasEstimatesLoadingStarted`  and `basicGasEstimatesLoadingFinished` from `state.gas`!! 🤔

File: ui/app/selectors/custom-gas.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (NiranjanaBinoy) [reply ui/app/selectors/custom-gas.js]: change updated in the PR

File: ui/app/pages/send/send-footer/send-footer.component.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (brad-decker) [reply ui/app/pages/send/send-footer/send-footer.component.js:30]: educating myself and will follow up with you shortly!

**Review by noncash15 — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]
LGTM! future work that I would suggest here is more of a critique of our infrastructure and not this feature.
