### PR TITLE
fix: use same logic in details page to show IPFS images

### LINKED ISSUE #30063: [Bug]: ERC1155 placeholder displayed instead of expected asset image
### Describe the bug

ERC1155 asset image is not displayed when imported in the NFT list, only if you click on the asset. Instead, a placeholder with the asset's descirption is shown. This is a regression from 12.11.0. Last working version was 12.10.3.

### Expected behavior

Asset image is displayed.

### Screenshots/Recordings

Image

Image

### Steps to reproduce

1. Load MetaMask
2. Import an ERC1155 token
3. Notice the placeholder in NFT list

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.11.0, 12.12.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

IPFS images in the grid view were not correctly identified and therefore were not fetched/displayed.

This copies the logic in the details page to ensure that we correctly show IPFS NFTs.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30091?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30063

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

main branch

### **After**

Screenshot 2025-02-04 at 11 33 34

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/assets/nfts/nft-grid/nft-grid.tsx [hunk 1]
```diff
@@ -9,8 +9,56 @@ import { NftItem } from '../../../../multichain/nft-item';
...
+  );
+
+  const isImageHosted =
+    image?.startsWith('https:') || image?.startsWith('http:');
+  const nftItemSrc = isImageHosted ? image : nftImageURL;
+
+  const nftImageAlt = getNftImageAlt(nft);
+
+  const nftSrcUrl = imageOriginal ?? image;
+  const isIpfsURL = nftSrcUrl?.startsWith('ipfs:');
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/nfts/nft-grid/nft-grid.tsx:46]: This logic now matches the NFT Details page.

NOTE - we should probably refactor and reuse this logic. But for cherry-picks, we can keep it here.

**Review by sahar-fehri — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

File: ui/components/app/assets/nfts/nft-grid/nft-grid.tsx (hunk 1 above)
Comment (Prithpal-Sooriya) [reply ui/components/app/assets/nfts/nft-grid/nft-grid.tsx:46]: The main fix was this `isIpfsURL` condition, as it seemed that the GridView before treated the IPFS url as a normal URL and attempted to fetch and display it.

Now the logic matches the details page, this has been resolved.
