### PR TITLE
Show error while allowing confirmation of tx where simulation fails

### LINKED ISSUE #4980: Confirm button is not clickable
i cannot send ether to my contract
is it relation with "MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider"??

if i change 'web3' to 'ethjs' in my dApp, not work "require()'

is there way to my contract user send ether to my contract method using metamask

this is my client script to send ether
```javascript
var Web3 = require('web3');
var web3js = new Web3(web3.currentProvider);
var myContract = web3js.eth.contract(myContractABI).at(myContractAddress);

myContract.myMethod.sendTransaction( 
    argument, 
    {from:userAccount, value...}, 
    function(error, result){
        if(error != null)
            console.log(result);
        else
            console.error(error);
});
```

### PR DESCRIPTION
**Pull request by danjm**
fixes #4980 

Before:
screenshot from 2018-08-08 21-18-18

After:
screenshot from 2018-08-08 21-24-42

### CODE REVIEW

**Review by jennypollack — APPROVED** [review]

File: ui/app/components/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 1]
```diff
@@ -124,7 +124,7 @@ export default class ConfirmTransactionBase extends Component {
 
     if (simulationFails) {
       return {
-        valid: false,
+        valid: true,
```
Comment (whymarrh) [inline ui/app/components/pages/confirm-transaction-base/confirm-transaction-base.component.js]: This makes sense, good catch

File: ui/app/constants/error-keys.js [hunk 2]
```diff
@@ -1,3 +1,3 @@
 export const INSUFFICIENT_FUNDS_ERROR_KEY = 'insufficientFunds'
 export const GAS_LIMIT_TOO_LOW_ERROR_KEY = 'gasLimitTooLow'
-export const TRANSACTION_ERROR = 'transactionError'
+export const TRANSACTION_ERROR_KEY = 'transactionError'
```
Comment (whymarrh) [inline ui/app/constants/error-keys.js]: We should expand our ESLint rules to include something like `import/no-unresolved`

**Review by whymarrh — APPROVED** [review]
LGTM
