### PR TITLE
fix: amount error in fiat mode

### LINKED ISSUE #36085: [post-launch] [bug] is fiatMode is on and user enter invalid amount like 'abc' it does not show error, create transaction with 0 amount.

### LINKED ISSUE #36191: Remove "~" from fiat conversion
**What is this about?**

We should remove the "~" from fiat conversion.

Image

**Stakeholder review needed before the work gets merged**

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### LINKED ISSUE #36203: [Bug]: App crashes with invalid input
**Describe the bug**

App crashes with invalid input on the amount field during send

**Expected behavior**

No crash and error alert displaying invalid input

**Screenshots/Recordings**

https://github.com/user-attachments/assets/678d408a-ef5d-4c50-b498-10923952660f

**Steps to reproduce**

1. Start a send
2. On the input field, start inputing a number
3. Then input a letter
4. Notice the app crash

**Error messages or log output**

```shell

```

**Detection stage**

On main branch

**Version**

13.5.0

**Build type**

None

**Browser**

Brave

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix issue with amount validation in fiat mode.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36085
Fixes: https://github.com/MetaMask/metamask-extension/issues/36131
Fixes: https://github.com/MetaMask/metamask-extension/issues/36191
Fixes: https://github.com/MetaMask/metamask-extension/issues/36203

## **Manual testing steps**

1. Go to amount page in send
2. Toggle to fiat mode and enter value "abc"
3. It should not throw

## **Screenshots/Recordings**
TODO

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/utils/send.ts [hunk 1]
```diff
@@ -240,16 +241,27 @@ export const getLayer1GasFees = async ({
   })) as Hex | undefined;
 };
 
-export function isDecimal(value: string) {
-  return Number.isFinite(parseFloat(value)) && !Number.isNaN(parseFloat(value));
+export function isValidPositiveNumericString(str: string) {
```
Comment (pedronfigueiredo) [inline ui/pages/confirmations/utils/send.ts:244]: [nit] isValidPositiveOrZeroNumericString

**Review by pedronfigueiredo — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]
