### PR TITLE
fix: fix duplicate item in search token

### LINKED ISSUE #37424: [Bug]: WETH token displayed twice in import token search
### Describe the bug

When Network Manager selection is `All popular networks`, the import token search displays WETH token on Base network twice.

When clicking on the first entry, the second one gets selected and importing the token works.

### Expected behavior

WETH token to be displayed only once on a network

### Screenshots/Recordings

https://github.com/user-attachments/assets/d05666a5-b699-4bca-bb40-b4ddf45ca020

Image

### Steps to reproduce

1. Select All popular networks in Network Manager
2. Click import token
3. Search WETH
4. Notice it is displayed twice for Base network

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.8.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Fixes duplicate items in search modal for tokens

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37568?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixes a bug that makes users see duplicate tokens in search tokens modal when on popular networks.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37424

## **Manual testing steps**

1. Click on import tokens
2. Click on popular networks
3. Search for "Weth"
4. You should not see duplicate items for Weth on base

### **Before**

Uploading Screen Recording 2025-11-06 at 11.06.05.mov…

### **After**

https://github.com/user-attachments/assets/fa3a943f-7bdb-447d-bd6f-9a067626c72b

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Use a composite unique key for token list items to prevent duplicate/incorrect rendering in the import token search results.
> 
> - **UI**
>   - **Import Token modal** (`ui/components/app/import-token/token-list/token-list.component.js`):
>     - Replace React list key with a composite `uniqueKey` built from `address`, `chainId`, index, `symbol`, and `name` for each token item, preventing key collisions and duplicate-render issues in search results.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 70f21d1f425653c28f68939429e647f24bc04e77. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/import-token/token-list/token-list.component.js [hunk 1]
```diff
@@ -85,7 +86,7 @@ export default class TokenList extends Component {
                 return (
                   Boolean(results[i]?.iconUrl || symbol || name) && (
                     <Box
-                      key={address}
```
Comment (sahar-fehri) [inline ui/components/app/import-token/token-list/token-list.component.js:88]: WETH address on base and on OP is the same `0x4200000000000000000000000000000000000006` causing the item to be rendered twice.

Comment (Prithpal-Sooriya) [reply ui/components/app/import-token/token-list/token-list.component.js:88]: TYYYYY

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by bergarces — APPROVED** [review]
