### PR TITLE
EIP-1559 - Only show radio group and gas timing when network supports 1559

### LINKED ISSUE #11649: EIP-1559 - Edit gas popover estimate and priority on custom networks
**Steps to reproduce (REQUIRED)**

1. Login to the extension
2. Click the Network drop down, Select `Binance Smart Chain Testnet`
3. Click the Account identicon, then select Settings and then Advanced
4. Toggle `Show Conversion on Testnets` to ON, then close the menu
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the Edit link in the Estimate gas fee section

**Expected behavior**
- The priority radio options are not displayed
- An estimate of the native currency is shown
Edit gas 2 - BSC

**Screenshots**
Current behavior
Edit gas - BSC

### PR DESCRIPTION
**Pull request by darkwing**
Fixes: #11649

The GasTiming fix is required or the component will error out on networks without high/medium/low

### CODE REVIEW

**Comment by darkwing** [comment]
I added another small fix to prevent merge conflicts -- hides the education button if the network doesn't support 1559.

**Review by danjm — DISMISSED** [review]

File: ui/components/app/gas-timing/gas-timing.component.js [hunk 1]
```diff
@@ -26,7 +30,8 @@ export default function GasTiming({ maxPriorityFeePerGas }) {
   };
 
   // Don't show anything if we don't have enough information
-  if (isGasEstimatesLoading) {
+  // or if the network doesn't support 1559
```
Comment (danjm) [inline ui/components/app/gas-timing/gas-timing.component.js:33]: Just realized that there is a better / more robust check that we can do here. Instead of checking whether the network supports EIP-1559, we should check if `gasEstimateType === GAS_ESTIMATE_TYPES.FEE_MARKET`

`gasEstimateType` is available from `useGasFeeEstimates()`, which is already called above, and `GAS_ESTIMATE_TYPES` will have to be imported from the shared constants.

The reason we should do this check, instead of just the network check, is that if for some reason the request for fee market type estimates failled, and the gas controller fell back to just requesting the gas price, then there will be no `low, medium and high` available on `gasFeeEstimates` and the below code will break

**Review by danjm — APPROVED** [review]
Looks good!

**Review by adonesky1 — APPROVED** [review]
LGTM!
