### PR TITLE
Do not display experimental settings tab when there are no settings to show

### LINKED ISSUE #17714: [Bug]: Experimental tab in settings is empty
### Describe the bug

In account settings, the experimental tab is empty and has no content.

Screenshot 2023-02-10 at 15 27 33

### Steps to reproduce

1. Login and go to settings.
2. Go to the experimental tab and check if it's empty.

Expected:
In Experimental tab, we should have:
- Enable enhanced gas fee UI
- Transaction security check

### Error messages or log output

_No response_

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/17714

## Screenshots/Screencaps
Screen Shot 2023-02-15 at 2 19 16 AM

Screen Shot 2023-02-15 at 2 22 05 AM

## Manual Testing Steps
1. Disable both the `NFTS_V1` and the `TRANSACTION_SECURITY_PROVIDER` feature flags
2. Ensure the experimental tab is not visible or accessible
3. Repeat steps 1 by switching 1 or both of them on and ensuring its accessibility

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by ryanml** [comment]
I’d still like to push some quick tests to this

File: ui/pages/settings/settings.container.js [hunk 1]
```diff
@@ -97,6 +97,9 @@ const mapStateToProps = (state, ownProps) => {
       : '',
   );
 
+  const shouldRenderExperimentalTab =
+    process.env.TRANSACTION_SECURITY_PROVIDER || process.env.NFTS_V1;
```
Comment (digiwand) [inline ui/pages/settings/settings.container.js:101]: is there a particular reason we are passing `shouldRenderExperimentalTab` from the container rather than adding directly to `settings.component.js`?

File: ui/pages/settings/settings.component.js [hunk 2]
```diff
@@ -353,7 +358,9 @@ class SettingsPage extends PureComponent {
           render={() => <AddNetwork />}
         />
         <Route exact path={SECURITY_ROUTE} component={SecurityTab} />
-        <Route exact path={EXPERIMENTAL_ROUTE} component={ExperimentalTab} />
+        {shouldRenderExperimentalTab ? (
+          <Route exact path={EXPERIMENTAL_ROUTE} component={ExperimentalTab} />
+        ) : null}
```
Comment (digiwand) [inline ui/pages/settings/settings.component.js:363]:
```suggestion
        {shouldRenderExperimentalTab ?? (
          <Route exact path={EXPERIMENTAL_ROUTE} component={ExperimentalTab} />
        )}
```

Comment (ryanml) [reply ui/pages/settings/settings.component.js:363]: I believe some time ago we switched to the null format return, as I think it caused some rendering issues. Correct me if I am wrong @darkwing

File: ui/pages/settings/settings.container.js (hunk 1 above)
Comment (ryanml) [reply ui/pages/settings/settings.container.js:101]: My first instinct was that it was being used in multiple places throughout the class component, and that it seemed to make sense as opposed to a header var or declared in a couple places. 

I am not opposed to the idea of the alternative at all, so if thought as to be best I can remove it from the container and shift it to the component

File: ui/pages/settings/settings.component.js (hunk 2 above)
Comment (darkwing) [reply ui/pages/settings/settings.component.js:363]: I tried promoting that practice but it isn't strictly adhered to.  I wouldn't block on it until we have a discussion as a team.

File: ui/pages/settings/settings.container.js (hunk 1 above)
Comment (ryanml) [reply ui/pages/settings/settings.container.js]: This is no longer being passed through the container

**Review by pedronfigueiredo — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]
