### PR TITLE
fix: edit button on confirmation page for send ERC-1155 token

### LINKED ISSUE #26955: [Bug]: ERC1155 does not have 'edit' button on confirmations page
### Describe the bug

ERC721s have an 'edit' button on the confirmation page
ERC1155 does not have an 'edit' button on the confirmation page

### Expected behavior

ERC1155 to have an 'edit' button on the confirmation page

### Screenshots/Recordings

      
Screenshot 2024-09-05 at 15 21 40
Screenshot 2024-09-05 at 15 21 55

### Steps to reproduce

1. click send
2. select account
3. select NFT asset
4. select ERC721/ERC1155
5. click 'continue'
6. verify there is or is not an 'edit' button for ERC1155

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.0.0 - 12.0.6

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix for bug that edit button was not visible on send ERC-1155 page.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26955

## **Manual testing steps**

1. Send an ERC-1155
2. Ensure that edit button is present on confirm send page

## **Screenshots/Recordings**
Screenshot 2024-09-10 at 10 16 18 AM

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js [hunk 1]
```diff
@@ -148,6 +148,14 @@ export default function ConfirmTokenTransactionSwitch({ transaction }) {
             decimals={decimals}
             image={tokenImage}
             tokenAddress={tokenAddress}
+            onEdit={async ({ txData }) => {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js:151]: Minor, it's a legacy pattern in the file but should we define this once as a `handleNftEdit` somewhere to avoid the duplication with the other paths?

**Review by matthewwalsh0 — DISMISSED** [review]

File: test/e2e/tests/tokens/nft/send-nft.spec.js [hunk 2]
```diff
@@ -115,13 +115,6 @@ describe('Send NFT', function () {
...
         });
 
-        // Ensure that this type of NFT is not editable for now
-        // https://github.com/MetaMask/metamask-extension/issues/24320
-        const editButtonPresent = await driver.isElementPresent(
-          '[data-testid="confirm-page-back-edit-button"]',
-        );
-        assert.equal(editButtonPresent, false);
-
         // Confirm the send
```
Comment (jpuri) [inline test/e2e/tests/tokens/nft/send-nft.spec.js:118]: I verified but this does not seems to be issue any more https://github.com/MetaMask/metamask-extension/issues/24320

Can you also plz once verify @sleepytanya

File: ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js (hunk 1 above)
Comment (jpuri) [reply ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js:151]: I would avoid getting into cleanup as this code is soon going to go away anyways,

**Review by sleepytanya — APPROVED** [review]

**Comment by sleepytanya** [comment]
'Edit' button ion the Send screen s displayed for ERC1155 and ERC721 tokens:


https://github.com/user-attachments/assets/bcd9e024-fac8-4745-9600-6ed7a2e879a3

**Review by matthewwalsh0 — APPROVED** [review]
