### PR TITLE
fix: issue with default nonce value being wrong when switching networks between transactions

### LINKED ISSUE #26979: [Bug]: When a user switches networks, the transaction created on the newly selected network adopts a nonce that is incremented by one from the transaction on the previous network
### Describe the bug

When a user switches networks, the transaction created on the newly selected network adopts a nonce that is incremented by one from the transaction on the previous network. If the user opts to reject the transaction, the correct nonce briefly appears. If transaction is confirmed by the user, it submits with the low nonce and subsequently fails, or it is submitted with the high nonce and stays in `Pending` state and seems like it can't be cancelled (I waited for ~20 mins). Upon a subsequent attempt, the transaction is then created with the accurate nonce and can be successfully submitted.

### Expected behavior

Transactions created with the correct nonce value

### Screenshots/Recordings

https://github.com/user-attachments/assets/0fe23ded-8a2b-4a56-9348-dbecd9857690

Tx with low nonce fails - popup  is not visible when screen recording is on but it is there and displays correct error message:

https://github.com/user-attachments/assets/546137c7-14ee-44e5-95c9-85627ca16955

Tx with high nonce stays in `Pending` state:

https://github.com/user-attachments/assets/f1c29012-446a-4888-9c8a-eb9fa8fec73e

### Steps to reproduce

1. Note the transaction nonce
2. Switch to another chain
3. Create a transaction
4. Notice that transaction created with incorrect nonce

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

dev build https://github.com/MetaMask/metamask-extension/pull/26433#issuecomment-2330104521

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

When submitting transactions the transaction after network switch takes custom nonce of previous network.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26979

## **Manual testing steps**

1. Enable custom nonce
2. Create a confirmation (may or may not submit) and then switch network
3. Create new transaction
4. Ensure that nonce in new transaction is correct

## **Screenshots/Recordings**
TODO

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
Build from https://github.com/MetaMask/metamask-extension/pull/27297#issuecomment-2364221677
1. Submitted Linea transaction - nonce 69
2. Switched to Sepolia with the latest transaction nonce 320
3. Transaction on Sepolia created with the nonce 69 (same as on latest Linea tx)


https://github.com/user-attachments/assets/ffe319c1-6108-4eb0-b40d-c88714bdd0a0

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 1]
```diff
@@ -155,6 +157,8 @@ const Footer = () => {
       dispatch(
         rejectPendingApproval(currentConfirmation.id, serializeError(error)),
       );
+      dispatch(updateCustomNonce(''));
+      dispatch(setNextNonce(''));
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx:161]: Not needed now and not introduced by this PR, but perhaps a future refactor could be to remove the nonce from Redux completely and instead just store the custom nonce directly in the `TransactionMeta`, or let the `TransactionController` derive it if not specified.

**Review by matthewwalsh0 — DISMISSED** [review]

**Comment by sleepytanya** [comment]
@jpuri 

Fixed:


https://github.com/user-attachments/assets/6031662b-5cc0-43b6-b0ef-1751fc998da8

**Review by pedronfigueiredo — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
