### PR TITLE
avoid mutation of state in signTransaction action

### LINKED ISSUE #17745: [Bug]: Error when updating a tx cannot proceed to Confirmation screen - `Invariant failed: A state mutation was detected between dispatches, in the path 'metamask.unapprovedTxs.`
### Describe the bug

**Problem**: when I am in the process of performing a Send tx, if I go back to Edit the tx, I can see the error `Invariant failed: A state mutation was detected between dispatches, in the path 'metamask.unapprovedTxs.` and I cannot proceed on the Confirmation screen.

This happens when updating any of these fields:
- tx recipient
- asset
- amount

https://user-images.githubusercontent.com/54408225/218739814-0d671a8c-53f1-46d3-8381-11fa28a53b4f.mp4

### Steps to reproduce

1. Click Send
2. Add recipient
3. Add amount
4. Go Next
5. Click Edit
6. Edit recipient amount or asset
7. Click Next -- error appears and cannot proceed

### Error messages or log output

_No response_

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by brad-decker**
## Explanation
Fixes #17745 

In #17508 i added store creation using reduxjs/toolkit instead of vanilla redux. One thing that comes with this is detection of mutation in state, which will throw an invariant error. This *should only be happening in dev mode* but its good to fix. This fixes the specific situation by cloning the transaction object before it used. 

## Manual Testing Steps
1. Create a transaction, but don't confirm it.
2. Edit transaction.
3. Change the recipient
4. On develop: Can't get to confirmation and invariant error in console.
5. On this branch: Confirmation.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by darkwing — APPROVED** [review]

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -2270,7 +2270,7 @@ export function signTransaction() {
       // merge in the modified txParams. Once the transaction has been modified
       // we can send that to the background to update the transaction in state.
       const unapprovedTxs = getUnapprovedTxs(state);
-      const unapprovedTx = unapprovedTxs[draftTransaction.id];
+      const unapprovedTx = cloneDeep(unapprovedTxs[draftTransaction.id]);
       // We only update the tx params that can be changed via the edit flow UX
```
Comment (jpuri) [inline ui/ducks/send/send.js:2274]: Just curious why it needs deep cloning, can something like destructuring help ?

**Review by jpuri — APPROVED** [review]

File: ui/ducks/send/send.js (hunk 1 above)
Comment (brad-decker) [reply ui/ducks/send/send.js:2274]: Because transactions have sub objects that also need cloned, not the reference to those sub objects, and if we were to do an object spread it does a shallow copy unless you specify every sub object. Destructuring to get the values we want won't work, because we attach a new key to this object later. A deeper refactor could be done to this for sure but for now this seems like the safest approach to maintain the functionality.

image
