### PR TITLE
Fix delayed loading of UI in MV3

### LINKED ISSUE #14001: MV3: It takes refreshing browser for extension UI to be loaded
We are noticing an issue in MV3 code in branch `mv3`. It takes reloading to see the wallet in browser.

Reason I found was that UI was loaded before extension was ready to send / receive RPC messages.

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #14001

At times we see extension page is blank and there is error in console that `receiving end does not exist`. It takes refreshing browser for error to go away. This issue was more evident in MV3 where extension was not loading unless we refresh the browser.

I found that reason is that UI is loaded before extension is ready for RPC method calls. The PR tries to address the issue by sending a message from extension to UI when it is ready to receive messages.

Here is a following improvement task planned: https://github.com/MetaMask/metamask-extension/issues/14050

### CODE REVIEW

File: app/scripts/background.js [hunk 1]
```diff
@@ -67,8 +67,8 @@ if (inTest || process.env.METAMASK_DEBUG) {
   global.metamaskGetState = localStore.get.bind(localStore);
 }
 
-// initialization flow
-initialize().catch(log.error);
+const initApp = initialize().catch(log.error);
+extension.runtime.onConnect.addListener(initApp);
```
Comment (jpuri) [inline app/scripts/background.js:71]: Having an event handler at top level is helpful for MV3, I found that at times in MV3 the first event was missed is user opened extension immediately after installing it.

The code above is good for MV2 also, An optimisation we should do here is, initialise the controllers outside the listeners. Reactive programming will be useful here.

**Comment by mcmire** [comment]
Could this partially address the ideas I proposed in #13606 as well?

**Comment by jpuri** [comment]
> Could this partially address the ideas I proposed in #13606 as well?

Thanks for sharing this @mcmire , yes it is related and will partially address #13606.

File: app/scripts/background.js [hunk 2]
```diff
@@ -367,7 +386,7 @@ function setupController(initState, initLangCode) {
       // communication with popup
       controller.isClientOpen = true;
       controller.setupTrustedCommunication(portStream, remotePort.sender);
-
+      remotePort.postMessage({ name: 'CONNECTION_READY' });
```
Comment (jpuri) [inline app/scripts/background.js:389]: This message is causing warning:
Screenshot 2022-03-22 at 6 22 58 AM

File: app/scripts/background.js [hunk 3]
```diff
@@ -67,8 +75,16 @@ if (inTest || process.env.METAMASK_DEBUG) {
...
+let initialState;
+let initialLangCode;
+
+const initApp = (remotePort) => initialize(remotePort).catch(log.error);
+browser.runtime.onConnect.addListener(initApp);
+
+(async () => {
+  initialState = await loadStateFromPersistence();
+  initialLangCode = await getFirstPreferredLangCode();
+})();
```
Comment (jpuri) [inline app/scripts/background.js:87]: Event handler at root level is required for mv3, otherwise in mv3 if user open UI very fast the first event to connect is missed out.

File: app/scripts/background.js [hunk 4]
```diff
@@ -67,8 +75,19 @@ if (inTest || process.env.METAMASK_DEBUG) {
...
 }
 
-// initialization flow
-initialize().catch(log.error);
+let initialState;
+let initialLangCode;
+const initApp = (remotePort) => initialize(remotePort).catch(log.error);
+
+if (process.env.ENABLE_MV3) {
+  browser.runtime.onConnect.addListener(initApp);
```
Comment (adonesky1) [inline app/scripts/background.js:83]: Can you help me understand why we would only want to do this (pass along the remotePort as an argument) in the context of MV3?  cc @jpuri

File: app/scripts/background.js [hunk 5]
```diff
@@ -291,20 +316,19 @@ function setupController(initState, initLangCode) {
     }
   }
 
+  if (process.env.ENABLE_MV3 && remoteSourcePort) {
+    connectRemote(remoteSourcePort);
```
Comment (adonesky1) [inline app/scripts/background.js:320]: same question here. Why not simply add the listener (`browser.runtime.onConnect.addListener(connectRemote);`) at the root of the file?

File: app/scripts/background.js (hunk 4 above)
Comment (jpuri) [reply app/scripts/background.js:83]: In MV3 it is better to have event listener at root level else it is possible that first event connect is lost if user open extension immediately after installing the extension.
This parameter is required for connect method to work.

File: app/scripts/background.js (hunk 5 above)
Comment (jpuri) [reply app/scripts/background.js:320]: `connectRemote` use controller object which is initialised in method containing it [here](https://github.com/MetaMask/metamask-extension/pull/14047/files/146e7efdec2f18c24441fbe2d77d44b02ddcdbf9#diff-215d2cf6fb64ee62b9f484e7bbdd33246739e39b854e3cc8c2245b026352c12aR240).

File: app/scripts/background.js (hunk 4 above)
Comment (adonesky1) [reply app/scripts/background.js:83]: > In MV3 it is better to have event listener at root level

Is there any reason not to have it at the root level in MV2 though? I'm wondering why we want to initialize without passing the `remotePort` in MV2?

Comment (adonesky1) [reply app/scripts/background.js:83]: So I tested, removing all the feature flags for MV3 
For example:
```
let initialState;
let initialLangCode;
const initApp = (remotePort) => initialize(remotePort).catch(log.error);

// if (process.env.ENABLE_MV3) {
browser.runtime.onConnect.addListener(initApp);
(async () => {
  initialState = await loadStateFromPersistence();
  initialLangCode = await getFirstPreferredLangCode();
})();
// } else {
//   initialize().catch(log.error);
// }
```
and everything seems to work quite well in MV2. I'm wondering whether we need to make these changes for only MV3 (is my point with the comments above)

**Comment by adonesky1** [comment]
I added these changes on top of the changes in https://github.com/MetaMask/metamask-extension/pull/14181 and ran as an MV3 build and am still seeing the UI fail to load on the first load. It does load after a refresh.

File: app/scripts/background.js (hunk 4 above)
Comment (jpuri) [reply app/scripts/background.js:83]: @adonesky1 : I would prefer to keep all of these changes behind flag. Then for MV3 we can have a flask release and have these features tested more throughly before enabling for everyone.
