### PR TITLE
fix: add migration for stuck transactions

### LINKED ISSUE #23361: [Bug]: all accounts on polygon network are unusable with msg: `A previous transaction is still being signed or submitted`
### Describe the bug

So in past 2 days or so, all my accounts in metamask chrome extension are unusable when trying to send a token with this msg appearing on the screen `A previous transaction is still being signed or submitted`.
this happens only on `Polygon` network and for all accounts, not just one.
I should mention other networks are fine and work as normal, and also on polygon network I was able to do a swap using metamask swap, but the issue still present even after that swap when trying to send a token.
I should also mention I already tried clearing data/reset nonce, but still no luck. also tried different providers urls, and still no luck.
Also another thing to mention is that I was able to perform a approval tx from quickswap website, but when it came to do the actual swap tx, still encountered the same error msg on metamask panel, but approval tx went through ok.

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot 2024-03-07 at 1 22 03 AM

### Steps to reproduce

1. Go to polygon network
2. try to send any token

### Error messages or log output

_No response_

### Version

11.11.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

this is critical because it has blocked me from sending any tokens on polygon network

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to add a migration which sets transaction to `failed` status if they are created before 8 December 2023 (release date of `TransactionController` migration) and they are still `approved` or `signed` status. 

The reason of this migration added is that some users had these transactions in their MM state and [after recent changes](https://github.com/MetaMask/metamask-extension/pull/22676) in the confirmation page, the transactions are blocking users to approve subsequent transactions. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24027?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23361

## **Manual testing steps**

N/A

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/migrations/115.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+  data: Record<string, unknown>;
+};
+
+export const version = 115;
+
+// Target date is December 8, 2023 - 00:00:00 UTC
+export const TARGET_DATE = new Date('2023-12-08T00:00:00Z').getTime();
+
+/**
+ * This migration updates the status of transactions that were approved or signed before December 8, 2023 to failed.
```
Comment (dbrans) [inline app/scripts/migrations/115.ts:18]: I think your PR description says it better. Something like:
```suggestion
 * This migration sets the `status` to `failed` for all transactions created before December 8, 2023 that are still `approved` or `signed`.
```

File: app/scripts/migrations/115.ts [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+        transaction.status = TransactionStatus.failed;
+      }
+
+      return {
+        ...txs,
+        [id]: transaction,
+      };
+    },
+    {},
+  );
```
Comment (dbrans) [inline app/scripts/migrations/115.ts:60]: Using the Object.fromEntries/Object.entries pattern could make this more succinct. Also, note that you don't need to clone the transactions as the cloning is handled in `migrate` above. 

```typescript
const STUCK_STATES = [TransactionStatus.approved, TransactionStatus.signed];
```

```suggestion
  const newTxs = Object.fromEntries(
    Object.entries(transactions).map(([id, tx]) => {
      if (
        tx.time < TARGET_DATE &&
        STUCK_STATES.includes(tx.status)
      ) {
        tx.status = TransactionStatus.failed;
      }
      return [id, tx];
    })
  );
```

**Review by dbrans — CHANGES_REQUESTED** [review]

**Review by dbrans — CHANGES_REQUESTED** [review]

File: app/scripts/migrations/115.ts [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+): Promise<VersionedData> {
+  const versionedData = cloneDeep(originalVersionedData);
+  versionedData.meta.version = version;
+  transformState(versionedData.data);
+  return versionedData;
+}
+
+// TODO: Replace `any` with type
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+const STUCK_STATES = [TransactionStatus.approved, TransactionStatus.signed];
```
Comment (matthewwalsh0) [inline app/scripts/migrations/115.ts:33]: Minor, but should we define this at the top so all the constants are together?

File: app/scripts/migrations/115.ts [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+
+function transformState(state: Record<string, any>) {
+  const transactions = state?.TransactionController?.transactions ?? {};
```
Comment (matthewwalsh0) [inline app/scripts/migrations/115.ts:36]: Should the fallback be `[]` since `transactions` is now an array following the migration?

File: app/scripts/migrations/115.ts [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+  
+  for (const tx of Object.values(transactions)) {
```
Comment (matthewwalsh0) [inline app/scripts/migrations/115.ts:38]: No need for `Object.values` since `transactions` should be an array.

File: app/scripts/migrations/115.ts [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+    if (
+      tx.time < TARGET_DATE &&
+      STUCK_STATES.includes(tx.status)
+    ) {
+      tx.status = TransactionStatus.failed;
```
Comment (matthewwalsh0) [inline app/scripts/migrations/115.ts:43]: Should we also set `error` to a suitable `TransactionError` object for the sake of clarity and future debug?

File: app/scripts/migrations/115.ts [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+  originalVersionedData: VersionedData,
+): Promise<VersionedData> {
+  const versionedData = cloneDeep(originalVersionedData);
+  versionedData.meta.version = version;
+  transformState(versionedData.data);
+  return versionedData;
+}
+
+// TODO: Replace `any` with type
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (matthewwalsh0) [inline app/scripts/migrations/115.ts:32]: Why is this needed if the below is a standard array of statuses?

File: app/scripts/migrations/115.test.ts [hunk 8]
```diff
@@ -0,0 +1,93 @@
+import { migrate, version, TARGET_DATE } from './115';
+
+const oldVersion = 114;
+
+const TRANSACTIONS_MOCK = {
```
Comment (matthewwalsh0) [inline app/scripts/migrations/115.test.ts:5]: Will need to be an array also.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by dbrans — APPROVED** [review]
Nice work!
