### PR TITLE
Fix issue where per dapp selected network state is enabled without the request queue experimental toggle enabled

### LINKED ISSUE #21876: [Bug]: Watch Asset request sends the response on a wrong network
### Describe the bug

Deploying contract for erc-20 on the Test Dapp while on the Sepolia network gives a successful response, but the next step, watching the asset or adding it to the wallet sends confirmation on Sepolia, but the tokens are then displayed on Goerli network, without any contract being deployed there. 

### Expected behavior

Watch Asset request should send a confirmation on Sepolia for contracts deployed on the same network and upon confirmation, the assets are displayed on the chosen network (Sepolia here). 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/34e9ffd5-6808-4bb4-be13-79f8a171f78d

### Steps to reproduce

1. Load MetaMask and the test dapp: https://metamask.github.io/test-dapp/
2. Switch to Sepolia and connect MetaMask to the test dapp
3. Switch to Goerli --> Notice that no TST tokens are displayed
4. Switch to Sepolia again
5. In the test dapp, deploy erc-20 contract
6. Confirm the request
7. Proceed to add token/watch asset 
8. Confirm the request
9. In the tokens list, notice that no TST tokens are displayed
10. Switch to Goerli network, the tokens show there.
11. Switch again to Sepolia, copy the token contract address from the test dapp and proceed to import tokens 
12. Notice that you can import manually and the tokens are displayed correctly this way. 

### Error messages or log output

_No response_

### Version

11.6.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by adonesky1**
In https://github.com/MetaMask/metamask-extension/pull/21522, the `perDomainNetwork` state was left as always enabled. This state should be toggled on and off with the `Select networks for each site` experimental setting.

Fixes: #21876

## **Manual testing steps**

Pertaining to the fix for #21876
1. Load MetaMask and the test dapp: https://metamask.github.io/test-dapp/
2. Switch to Sepolia and connect MetaMask to the test dapp
3. Switch to Goerli --> Notice that no TST tokens are displayed
4. Switch to Sepolia again
5. In the test dapp, deploy erc-20 contract
6. Confirm the request
7. Proceed to add token/watch asset 
8. Confirm the request
9. In the tokens list, see that the TST token is present on Sepolia

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -4062,6 +4055,17 @@ export default class MetamaskController extends EventEmitter {
...
   }
 
+  //=============================================================================
+  // REQUEST QUEUE
+  //=============================================================================
+
+  setUseRequestQueue = (value) => {
+    this.preferencesController.setUseRequestQueue(value);
+    this.selectedNetworkController.update((state) => {
+      state.perDomainNetwork = true;
```
Comment (shanejonas) [inline app/scripts/metamask-controller.js:4065]: shouldnt this set `perDomainNetwork` to `value` too?

```suggestion
      state.perDomainNetwork = value;
```

Comment (adonesky1) [reply app/scripts/metamask-controller.js:4065]: yes whoops

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -4062,6 +4055,17 @@ export default class MetamaskController extends EventEmitter {
     this.sendUpdate();
   }
 
+  //=============================================================================
+  // REQUEST QUEUE
+  //=============================================================================
+
+  setUseRequestQueue = (value) => {
```
Comment (shanejonas) [inline app/scripts/metamask-controller.js:4062]: this looks like it could be a static method, we should use this syntax the rest of the controller uses:

```suggestion
  setUseRequestQueue(value) {
```

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -4062,6 +4055,17 @@ export default class MetamaskController extends EventEmitter {
...
 
+  //=============================================================================
+  // REQUEST QUEUE
+  //=============================================================================
+
+  setUseRequestQueue(value) {
+    this.preferencesController.setUseRequestQueue(value);
+    this.selectedNetworkController.update((state) => {
+      state.perDomainNetwork = value;
+    });
```
Comment (jiexi) [inline app/scripts/metamask-controller.js:4066]: i think this has to be called with the current useRequestQueue value right after selectedNetworkController init

Comment (jiexi) [reply app/scripts/metamask-controller.js:4066]: actually nevermind

**Review by jiexi — APPROVED** [review]

**Review by shanejonas — APPROVED** [review]
