### PR TITLE
fix: error in navigating between transaction when one of the transaction is approve all

### LINKED ISSUE #27913: [Bug]: Navigation between unapproved transactions breaks MM with Cannot read properties of undefined (reading 'length') / Message: Should have a queue. This is likely a bug in React. errors
### Describe the bug

Navigation between two pending malicious transactions breaks MetaMask with errors:

`Cannot read properties of undefined (reading 'length') `

and 

`Message: Should have a queue. This is likely a bug in React`

At the moment, functionalities like `Malicious ERC20 Approval (BUSD)` and `Malicious Set Approval for All` are not operating as anticipated in both the develop branch and the RC 12.5.0 version on Base and BNB networks. 

https://github.com/MetaMask/metamask-extension/issues/27909

https://github.com/MetaMask/metamask-extension/issues/27905

If a user initiates two consecutive transactions where the latter is a Malicious Set Approval for All, attempting to navigate between these transactions in the popup triggers an error. However, in the Expanded view, these transactions appear as unapproved and can be successfully processed or cancelled.

### Expected behavior

No errors

### Screenshots/Recordings

Screenshot 2024-10-15 at 21 55 07

Screenshot 2024-10-15 at 22 36 52

https://github.com/user-attachments/assets/e061546a-3d62-4108-a2ba-09c90c8b1751

https://github.com/user-attachments/assets/c2920982-a210-4bf1-8079-8377a4467af8

### Steps to reproduce

1. Connect to [test dapp](https://metamask.github.io/test-dapp/)
2. Trigger any transaction, do not confirm
3. Trigger `Malicious Set Approval for All`
Alternatively, trigger `Malicious Set Approval for All` first and then any button from PPOM section - this will produce another type of error.

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

12.4.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Navigation in transaction header was broken when one of the transaction is of type Approve All

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27913

## **Manual testing steps**

1. Go to test dapp
2. Submit any re-designed transaction followed by an approve all transaction
3. Try navigating between transaction using header buttons

## **Screenshots/Recordings**

TODO

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/title/title.tsx [hunk 1]
```diff
@@ -174,11 +174,10 @@ const ConfirmTitle: React.FC = memo(() => {
 
   let isRevokeSetApprovalForAll = false;
   let revokePending = false;
+  const decodedResponse = useDecodedTransactionData(TransactionType.tokenMethodSetApprovalForAll);
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/title/title.tsx:177]: Reason for the big for that this hook was being called conditionally

File: ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts [hunk 2]
```diff
@@ -10,18 +10,23 @@ import { DecodedTransactionDataResponse } from '../../../../../../../shared/type
 import { useConfirmContext } from '../../../../context/confirm';
 import { hasTransactionData } from '../../../../../../../shared/modules/transaction.utils';
 
-export function useDecodedTransactionData(): AsyncResult<
-  DecodedTransactionDataResponse | undefined
-> {
+export function useDecodedTransactionData(
+  transactionType?: string,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts:14]: To make this more explicit and readable, could we use an object argument call this something like `transactionTypeFilter`?

We could also omit the filter completely and always decode but I appreciate this is a nice optimisation.

If we end up with many of usages of this hook, we may want to implement some kind of caching in the underlying background utils, or even move this to the `TransactionController`.

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
