### PR TITLE
fix: Limit amount of decimals on spending cap modal

### LINKED ISSUE #27618: [Bug]: ERC20 Approve - Editing the spending cap value with more decimals than expected, leaves popup loading indefinetly
### Describe the bug

With the new Approve ERC20 redesign screen, when I edit the Spending cap and I pass a value with more decimals than the token supports, the edit popup stays loading indefinitely

### Expected behavior

Same as we had before? Despite adding more decimals, those were not added on the input value

### Screenshots/Recordings

https://github.com/user-attachments/assets/abf62cc5-3bea-45f5-a305-357700664ad4

### Steps to reproduce

1. Deploy an ERC20 token
2. Trigger Approve
3. Edit Approve amount by passing more decimals than the token supports
4. See loading popup

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

If the user tries to add more decimals to the spending cap than what the token supports, the spending cap cannot be submitted and a notice is displayed.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27672?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27618

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

Screenshot 2024-10-08 at 13 40 02

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx [hunk 1]
```diff
@@ -116,10 +128,17 @@ export const EditSpendingCapModal = ({
     setCustomSpendingCapInputValue(formattedSpendingCap.toString());
   }, [customSpendingCapInputValue, formattedSpendingCap]);
 
+  const showDecimalError = useMemo(() => {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx:131]: Minor, do we need a memo for this as some basic math will have negligible performance cost?

File: ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx [hunk 2]
```diff
@@ -116,10 +128,17 @@ export const EditSpendingCapModal = ({
...
+      decimals &&
+      parseInt(decimals, 10) < countDecimalDigits(customSpendingCapInputValue)
+    );
+  }, [decimals, customSpendingCapInputValue]);
+
   return (
     <Modal
       isOpen={isOpenEditSpendingCapModal}
-      onClose={() => setIsOpenEditSpendingCapModal(false)}
+      onClose={() => handleCancel()}
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx:141]: Minor, no need for the lambda since `handleCancel` is already a function reference with no arguments?

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx [hunk 3]
```diff
@@ -32,6 +32,18 @@ import { useConfirmContext } from '../../../../../context/confirm';
...
+  const decimalPointIndex = numberString.indexOf('.');
+
+  if (decimalPointIndex === -1) {
+    return 0;
+  }
+
+  const decimalDigits = numberString.length - decimalPointIndex - 1;
+
+  return decimalDigits;
+}
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx:45]: `return numberString.split(".")[1].length || 0;`

**Review by OGPoyraz — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
