### PR TITLE
fix: issue where `wallet_addEtherumChain` was incorrectly enforcing inclusion of a blockExplorerUrls property which is not required

### LINKED ISSUE #26844: [Bug]: wallet_addEthereumChain blockExplorerUrls should be optional
### Describe the bug

When using `wallet_addEthereumChain` you are required to enter `blockExplorerUrls` this is not the case when adding a new network manually. The docs also indicate this is optional https://docs.metamask.io/wallet/reference/wallet_addethereumchain/

### Expected behavior

blockExplorerUrls should be optional

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to https://protect.flashbots.net/summary?fast=true
2. Click "Add to Metamask"
3. See popup error

### Error messages or log output

```
Error -32602: Expected null or array with at least one valid string HTTPS URL 'blockExplorerUrl'. Received: undefined
```

### Detection stage

In production (default)

### Version

12.0.6

### Browser

Firefox

### Operating system

MacOS

### PR DESCRIPTION
**Pull request by adonesky1**
Fix issue where `wallet_addEtherumChain` was incorrectly enforcing inclusion of a blockExplorerUrls property which is not required

## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26938?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26844

## **Manual testing steps**

1. Go to https://protect.flashbots.net/summary?fast=true
2. Click "Add to Metamask"
3.  You should see the add network confirmation and be able to add the network configuration successfully to the wallet

### **Before**

https://github.com/user-attachments/assets/5c5718b5-f5e7-4499-9393-307bbe5c4eaa

### **After**

https://github.com/user-attachments/assets/14d1b1aa-f2d8-4133-9056-064d7875379a

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by antonydenyer — DISMISSED** [review]

**Comment by shanejonas** [comment]
looks good, spec also says it shouldn't be required: https://github.com/MetaMask/api-specs/blob/main/openrpc.yaml#L896-L900

**Review by shanejonas — DISMISSED** [review]

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ export function validateAddEthereumChainParams(params, end) {
 
   const firstValidRPCUrl = rpcUrls.find((rpcUrl) => isLocalhostOrHttps(rpcUrl));
   const firstValidBlockExplorerUrl =
-    blockExplorerUrls !== null && Array.isArray(blockExplorerUrls)
+    blockExplorerUrls && Array.isArray(blockExplorerUrls)
```
Comment (jiexi) [inline app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js:123]:
```
> Array.isArray(null)
false
> Array.isArray(undefined)
false
> Array.isArray(undefined)
false
> Array.isArray('')
false
> Array.isArray([])
true
```

Does the first part of the check need to be there in the first place?

File: app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js [hunk 2]
```diff
@@ -120,6 +120,35 @@ describe('addEthereumChainHandler', () => {
       expect(mocks.setActiveNetwork).toHaveBeenCalledWith(123);
     });
 
+    it('creates a new networkConfiguration when called with no "blockExplorerUrls" property', async () => {
```
[the remark this answers is not in the document]
Comment (jiexi) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js:123]: nit of course

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js (hunk 1 above)
Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js:123]: Seems like we can scrap it!

File: app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js]: done here https://github.com/MetaMask/metamask-extension/pull/26938/commits/cb9d89e66c349d5eb045c23fcfb85d4ee23601d0

File: app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js (hunk 1 above)
Comment (adonesky1) [reply app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js]: done here https://github.com/MetaMask/metamask-extension/pull/26938/commits/cb9d89e66c349d5eb045c23fcfb85d4ee23601d0

**Review by jiexi — APPROVED** [review]

**Review by shanejonas — APPROVED** [review]
