### PR TITLE
fix: skip automatic gas updates for swap and bridge transactions cp-13.2.0

### LINKED ISSUE #35423: [Bug]: Gas-included swaps not working on eth mainnet
### Describe the bug

Gas-included swaps on mainnet ethereum are frequently failing. 

### Expected behavior

The swap should succeed

### Screenshots/Recordings

_No response_

### Steps to reproduce

- Have a wallet address with little or no ETH and 10 USDC
- Try to swap 0.1 USDC to USDT. Fees should be paid with the remaining USDC
- The swap fails

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.2.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

Tested on the 13.2.0 RC build https://github.com/MetaMask/metamask-extension/pull/35198#issuecomment-3220532381

### Severity

It is critical: gas-included swaps are a big revenue driver

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

Skips gas estimate polling for bridge and swap transactions to prevent overriding the `maxFeePerGas` estimated by the bridge-api for gasIncluded swaps

Mobile also made a similar change to only do auto gas updates for these transaction types: https://github.com/MetaMask/metamask-mobile/blob/main/app/core/Engine/controllers/transaction-controller/transaction-controller-init.ts#L65

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35455?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/35423

## **Manual testing steps**

1. Using an account with no native balance, execute a gasless swap on ethereum (i.e max USDC balance -> ETH )
2. Note the txFee included with the quote
3. The maxFeePerGas values for both approval and trade txs in sentinel should be equal to the quoted fee: https://tx-sentinel-ethereum-mainnet.api.cx.metamask.io/troubleshoot/27b58e9c-8777-4e12-b8ca-c31d43da8788
4. Verify that other STX bridge/swap transactions work
5. Verify that non-STX bridge/swap transactions work

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controller-init/confirmations/transaction-controller-init.ts [hunk 1]
```diff
@@ -89,7 +90,20 @@ export const TransactionControllerInit: ControllerInitFunction<
         onboardingController().state.completedOnboarding,
       updateTransactions: true,
     },
-    isAutomaticGasFeeUpdateEnabled: () => true,
+    isAutomaticGasFeeUpdateEnabled: ({ type }) => {
+      if (
```
Comment (matthewwalsh0) [inline app/scripts/controller-init/confirmations/transaction-controller-init.ts]: Minor, maybe:

```
const disabledTypes = [
        TransactionType.swap,
        TransactionType.swapApproval,
        TransactionType.bridge,
        TransactionType.bridgeApproval,
 ];
 
 return !type || !disabledTypes.includes(type);
```

**Review by matthewwalsh0 — DISMISSED** [review]

**Comment by klejeune** [comment]
This should fix https://github.com/MetaMask/metamask-extension/issues/35423

File: app/scripts/controller-init/confirmations/transaction-controller-init.ts (hunk 1 above)
Comment (micaelae) [reply app/scripts/controller-init/confirmations/transaction-controller-init.ts]: good call, just pushed an update and added a comment too

**Review by matthewwalsh0 — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]
