### PR TITLE
fix: get `supportedChains` to avoid blocking the confirmation process

### LINKED ISSUE #28255: [Bug]: Security Alerts API - GET request to get `supportedChains` blocks the Send Flow until resolved
### Describe the bug

Whenever we start a Send flow, there is a request send to the host `security-alerts.api.cx.metamask.io` to get the `supportedChains`. The problem is that the Send flow is blocked until this request is resolved (either success or failed).

### Expected behavior

We shouldn't block the Send flow until this API request is resolved. If the API is slow, this impacts the overall user experience.
We might want to have an initial value for that array, so this is non blocking, and update it when we get the response?

### Screenshots/Recordings

https://github.com/user-attachments/assets/d3d881e6-df5d-488c-a6b3-72117c4df146

### Steps to reproduce

1. Use a proxy to intercept requests (ie Burpsuite)
2. Start a Send flow
3. Intercep the request to `security-alerts.api.cx.metamask.io`
4. See send flow cannot be initiated until we have a response to this request

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**
This PR addresses the blocking behaviour in the confirmation process caused by the synchronous `supportedChains` check. Previously, the Send flow was halted until a response from the `security-alerts.api.cx.metamask.io` API was received. This created delays and negatively impacted the user experience, especially when the API response was slow.

**Key Changes:**
**Asynchronous Chain Validation:** The `supportedChains` check is now performed asynchronously within the non-awaited `validateRequestWithPPOM` function. This ensures that the Send flow is not blocked while waiting for the API response.
**Introduction of CheckingChain Result Type:** A new result type, `CheckingChain`, is introduced to represent the intermediate state before a definitive result is obtained. This state is used before the `loading` status in both middleware and transaction utility functions.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28313?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28255 https://github.com/MetaMask/metamask-extension/issues/28257

## **Manual testing steps**

1. Use a proxy to intercept requests
2. Start a Send flow
3. Intercept the request to `security-alerts.api.cx.metamask.io`
4. See send flow cannot be initiated until we have a response to this request

## **Screenshots/Recordings**

[supported-chains-.webm](https://github.com/user-attachments/assets/4e9e495a-10f3-4bb1-8d05-8045a735b655)

[unsupported-chains.webm](https://github.com/user-attachments/assets/e5767bc1-2eab-44bd-83c3-777d34c23ff6)

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/lib/ppom/ppom-util.ts [hunk 1]
```diff
@@ -37,18 +39,37 @@ type PPOMRequest = Omit<JsonRpcRequest, 'method' | 'params'> & {
...
   chainId: Hex;
+  updateSecurityAlertResponse: (
+    method: string,
+    securityAlertId: string,
+    securityAlertResponse: SecurityAlertResponse,
+  ) => void;
 }): Promise<SecurityAlertResponse> {
   try {
+    if (!(await isChainSupported(chainId))) {
+      return {
```
Comment (matthewwalsh0) [inline app/scripts/lib/ppom/ppom-util.ts:62]: We're returning this new response but should we also update so the controllers have the correct chain not supported response on them?

File: app/scripts/lib/ppom/ppom-util.ts [hunk 2]
```diff
@@ -37,18 +39,37 @@ type PPOMRequest = Omit<JsonRpcRequest, 'method' | 'params'> & {
...
+        ...SECURITY_ALERT_RESPONSE_CHAIN_NOT_SUPPORTED,
+        securityAlertId,
+      };
+    }
+
+    updateSecurityResponse(request.method, securityAlertId, {
```
Comment (matthewwalsh0) [inline app/scripts/lib/ppom/ppom-util.ts:68]: Isn't this asynchronous, should we await this before continuing?

File: shared/constants/security-provider.ts [hunk 3]
```diff
@@ -32,7 +32,7 @@ export enum BlockaidReason {
   approvalFarming = 'approval_farming',
   /** Malicious signature on Blur order  */
   blurFarming = 'blur_farming',
-  /** A known malicous site invoked that transaction  */
+  /** A known malicious site invoked that transaction  */
```
Comment (matthewwalsh0) [inline shared/constants/security-provider.ts:35]: I'm certain you have a spell checker VSCode extension to catch all these 😄

File: shared/constants/security-provider.ts [hunk 4]
```diff
@@ -117,6 +119,17 @@ export const LOADING_SECURITY_ALERT_RESPONSE: SecurityAlertResponse = {
...
+export const SECURITY_ALERT_RESPONSE_CHECKING_CHAIN: SecurityAlertResponse = {
+  result_type: BlockaidResultType.Benign,
+  reason: BlockaidReason.checkingChain,
+};
+
+export const SECURITY_ALERT_RESPONSE_CHAIN_NOT_SUPPORTED: SecurityAlertResponse =
+  {
+    result_type: BlockaidResultType.Benign,
+    reason: BlockaidReason.chainNotSupported,
+  };
```
Comment (matthewwalsh0) [inline shared/constants/security-provider.ts:131]: Minor, extra indent here?

File: test/e2e/tests/metrics/signature-approved.spec.js [hunk 5]
```diff
@@ -47,6 +52,16 @@ async function mockSegment(mockServer) {
   ];
 }
 
+const eventPropertiesBase = {
```
Comment (matthewwalsh0) [inline test/e2e/tests/metrics/signature-approved.spec.js:55]: Minor, `expectedEventPropertiesBase`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: test/e2e/tests/metrics/signature-approved.spec.js (hunk 5 above)
Comment (vinistevam) [reply test/e2e/tests/metrics/signature-approved.spec.js]: Done

File: app/scripts/lib/ppom/ppom-util.ts (hunk 2 above)
Comment (vinistevam) [reply app/scripts/lib/ppom/ppom-util.ts]: You are right, the type previous was void but because we were intentionally not awaiting. Fixed.

File: app/scripts/lib/ppom/ppom-util.ts (hunk 1 above)
Comment (vinistevam) [reply app/scripts/lib/ppom/ppom-util.ts]: That is true. I pushed a change to update it before responding.

File: app/scripts/lib/transaction/util.test.ts [hunk 6]
```diff
@@ -425,8 +425,8 @@ describe('Transaction Utils', () => {
         ).toHaveBeenCalledWith(TRANSACTION_PARAMS_MOCK, {
           ...TRANSACTION_OPTIONS_MOCK,
           securityAlertResponse: {
-            reason: BlockaidReason.inProgress,
-            result_type: BlockaidResultType.Loading,
+            reason: BlockaidReason.checkingChain,
+            result_type: BlockaidResultType.Benign,
```
[the remark this answers is not in the document]
Comment (vinistevam) [reply app/scripts/lib/transaction/util.test.ts]: It was changed to `loading`.

File: app/scripts/lib/ppom/ppom-middleware.ts [hunk 7]
```diff
@@ -122,6 +115,7 @@ export function createPPOMMiddleware<
             request: req,
             securityAlertId,
             chainId,
+            updateSecurityAlertResponse,
           }).then((securityAlertResponse) => {
             updateSecurityAlertResponse(
```
Comment (matthewwalsh0) [inline app/scripts/lib/ppom/ppom-middleware.ts:120]: As we're passing the update callback to the util, can we omit this `then` entirely plus the one in `transaction/util` since the util can own all the updates?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
