### PR TITLE
fix(snaps): Use account group name in `SnapUIAccountSelector` cp-13.23.0

### LINKED ISSUE #40996: [Bug]: Account nickname not shown in `wallet_requestExecutionPermissions` picker
### Describe the bug

When `wallet_requestExecutionPermissions` request is received, a permissions picker is displayed. The account picker at the top of the confirmation. 

The account nickname is not shown

### Expected behavior

The account nickname should be shown above the account address

### Screenshots/Recordings

Image

### Steps to reproduce

1. Go to https://jeff.dripfund.xyz
2. Click "Connect wallet"
3. Click "Donate"

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.23.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

Built from source

### Severity

_No response_

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

This PR fixes the account name not showing due to it being stored in the `AccountTreeController` now.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/41007?quickstart=1)

## **Changelog**

CHANGELOG entry: Fix `SnapUIAccountSelector` account name.

## **Related issues**

Fixes: #40996 

## **Manual testing steps**

1. Go to https://jeff.dripfund.xyz/
2. Click "Connect wallet"
3. Click "Donate"
4. Expect an account name to be displayed in the Account Selector

### **Before**

Screenshot 2026-03-18 at 11 17 12

### **After**

Screenshot 2026-03-18 at 12 01 14
Screenshot 2026-03-18 at 12 01 24

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Low Risk**
> Low risk UI-only change that adjusts display names in the Snap account selector based on account-tree group metadata, with corresponding test updates.
> 
> **Overview**
> Fixes `SnapUIAccountSelector` to display the **account group name** from the account tree when an internal account’s `metadata.name` is empty/unused. The selector now derives each displayed account name by matching the account ID to `getAllAccountGroups()` and falls back to the account’s own name if no group is found.
> 
> Updates the account selector renderer tests/snapshots to expect the new naming (e.g., `Account 1/2`) and adjusts the selection index accordingly.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit b15c4012e657f1eee04336a22818b7319d56b291. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/snaps/snap-ui-account-selector/snap-ui-account-selector.tsx [hunk 1]
```diff
@@ -86,14 +88,32 @@ export const SnapUIAccountSelector: FunctionComponent<
...
-    />
-  ));
+  const optionComponents = accounts.map((account, index) => {
+    // Get the name from the account group if it exists, otherwise use the account name
+    // This is necessary because the account name is empty now and the group name is used instead,
+    // but we still want to show the account name if the group name is not available.
+    const name =
+      accountGroups.find(({ accounts: accountGroup }) =>
+        accountGroup.includes(account.id),
+      )?.metadata.name ?? account.metadata.name;
```
Comment (FrederikBolding) [inline ui/components/app/snaps/snap-ui-account-selector/snap-ui-account-selector.tsx]: Should we move this inside the `useMemo` for accounts?

**Review by FrederikBolding — DISMISSED** [review]

File: ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts [hunk 2]
```diff
@@ -59,7 +59,7 @@ describe('SnapUIAccountSelector', () => {
 
     fireEvent.click(accountOptions[1]);
 
-    expect(getByText('Test Account 2')).toBeInTheDocument();
+    expect(getByText('Account 1')).toBeInTheDocument();
```
Comment (FrederikBolding) [inline ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts]: Shouldn't this be another account?

Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts]: There's two `Account 1` in the mocked state 😅

Comment (FrederikBolding) [reply ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts]: Can we change that for this test at least so we are sure we are testing the right thing? 😅

Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts]: Let me update this to be more useful

Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts]: Should be better now 95e99c9

**Review by FrederikBolding — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]
