### PR TITLE
fix: Missing "Unlimited" as value for the DAI permit

### LINKED ISSUE #28964: [Bug]: Missing "Unlimited" as value for the DAI permit
### Describe the bug

For DAI permit, we're currently displaying no value for DAI permits.

### Expected behavior

For DAI permit, we should display `Unlimited` as the value within estimated changes. 

### Screenshots/Recordings

image
image

### Steps to reproduce

Payload: 

```
{
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      }
    ],
    "Permit": [
      {
        "name": "holder",
        "type": "address"
      },
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "nonce",
        "type": "uint256"
      },
      {
        "name": "expiry",
        "type": "uint256"
      },
      {
        "name": "allowed",
        "type": "bool"
      }
    ]
  },
  "domain": {
    "name": "Dai Stablecoin",
    "version": "1",
    "verifyingContract": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    "chainId": "0x1"
  },
  "primaryType": "Permit",
  "message": {
    "holder": "0xD2C44F28eC4C7eF686f587FADdb204da3aEFa827",
    "spender": "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45",
    "allowed": true,
    "nonce": 0,
    "expiry": 1660916504
  }
}
```

API response:
```
{
	"stateChanges": [
		{
			"assetType": "ERC20",
			"changeType": "APPROVE",
			"address": "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45",
			"amount": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
			"contractAddress": "0x6B175474E89094C44Da98b954EedeAC495271d0F"
		}
	]
}
```

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.9.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Introduces a new logical path for displaying "Unlimited" in the permit simulation, for when the `allowed` property in the signature message is set and the permit is for the token DAI. This is as is specified in [ERC-2612](https://eips.ethereum.org/EIPS/eip-2612)'s "Backwards Compatibility" section:

> There are already a couple of permit functions in token contracts implemented in contracts in the wild, most notably the one introduced in the dai.sol.

> Its implementation differs slightly from the presentation here in that:

> instead of taking a value argument, it takes a bool allowed, setting approval to 0 or uint(-1).

This PR also fixes a bug that prevents boolean values from being displayed in the key value display in the message section of signatures.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29597?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28964

## **Manual testing steps**

1. Open the browser console and execute the following code:

```javascript
async function connectMetaMask() {
  try {
    const accounts = await window.ethereum.request({
      method: 'eth_requestAccounts',
    });
    console.log('Connected account:', accounts[0]);
    return accounts[0];
  } catch (error) {
    console.error('User rejected the request:', error);
    throw error;
  }
}
async function signPermit() {
  try {
    const fromAddress = await connectMetaMask();
    const msgParams = {
      types: {
        EIP712Domain: [
          { name: 'name', type: 'string' },
          { name: 'version', type: 'string' },
          { name: 'chainId', type: 'uint256' },
          { name: 'verifyingContract', type: 'address' },
        ],
        Permit: [
          { name: 'holder', type: 'address' },
          { name: 'spender', type: 'address' },
          { name: 'nonce', type: 'uint256' },
          { name: 'expiry', type: 'uint256' },
          { name: 'allowed', type: 'bool' },
        ],
      },
      domain: {
        name: 'Dai Stablecoin',
        version: '1',
        verifyingContract: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
        chainId: '0x1',
      },
      primaryType: 'Permit',
      message: {
        holder: '0xD2C44F28eC4C7eF686f587FADdb204da3aEFa827',
        spender: '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45',
        allowed: true,
        nonce: 0,
        expiry: 1660916504,
      },
    };

    const signature = await window.ethereum.request({
      method: 'eth_signTypedData_v4',
      params: [fromAddress, JSON.stringify(msgParams)],
    });
    console.log('Signature:', signature);
    return signature;
  } catch (error) {
    console.error('Error signing permit:', error);
  }
}
signPermit();
```

2. Change `"allowed": true` to `"allowed": false` in the aforementioned code and execute it to see the revocation screen.

### **After**

Screenshot 2025-01-08 at 18 30 35
Screenshot 2025-01-08 at 18 30 37

Screenshot 2025-01-09 at 10 22 09
Screenshot 2025-01-09 at 10 22 13

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by OGPoyraz — DISMISSED** [review]

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/permit-simulation/permit-simulation.tsx [hunk 1]
```diff
@@ -97,19 +99,29 @@ const PermitSimulation: React.FC<object> = () => {
...
     </ConfirmInfoRow>
   );
 
+  let descriptionKey;
+  if (isNFT) {
+    descriptionKey = 'simulationDetailsApproveDesc';
+  } else if (message.allowed === false) {
+    // revoke permit
+    descriptionKey = 'revokeSimulationDetailsDesc';
+  } else {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/permit-simulation/permit-simulation.tsx:116]: Minor, rather than setting the fallback with an `else`, could we assign it by default when we define `descriptionKey`?

File: ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/value-display.tsx [hunk 2]
```diff
@@ -31,6 +31,9 @@ import {
 import { TOKEN_VALUE_UNLIMITED_THRESHOLD } from '../../../shared/constants';
 import { getAmountColors } from '../../../utils';
 
+export const DAI_CONTRACT_ADDRESS =
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/value-display.tsx:34]: Minor, is this better in `ui/pages/confirmations/components/confirm/info/shared/constants.ts`?

File: ui/pages/confirmations/components/confirm/title/title.tsx [hunk 3]
```diff
@@ -136,6 +152,20 @@ const getDescription = (
         if (tokenStandard === TokenStandard.ERC721) {
           return t('confirmTitleDescApproveTransaction');
         }
+
+        const msgData = (confirmation as SignatureRequestType)?.msgParams?.data;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/title/title.tsx:156]: Should we add a utility such as `isRevokeDAIPermit` to avoid the duplication?

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
