### PR TITLE
fix: non-evm details account display name

### LINKED ISSUE #40090: [Bug]: Tx Details - Sending a non-evm tx displays `Snap Account X` in `from` and `to` fields instead of the main Account name
### Describe the bug

Sending a non-evm tx displays `Snap Account X` in `from` and `to` fields instead of the main Account name. This can be miss-leading, as the user doesn't have a way to identify the Snap Account numbers.

### Expected behavior

_No response_

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/1782e3f2-6060-4058-9315-9f732d9c82cb

### Steps to reproduce

1. Send a. nonEVM tx to an account inside the wallet
2. Confirm
3. Click tx details in the activity tab
4. See From and To are displaying Snap Account instead of the main account name ie Account 3

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.19.0 but might be already in prod

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by n3ps**
## **Description**

Render the account group display name instead of the internal name

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/40498?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: non-evm txn details account display name

## **Related issues**

Fixes: #40090 

## **Manual testing steps**

1. Complete a non-EVM send transaction
2. Go to Activity tab
3. Click for details

## **Screenshots/Recordings**

Before: "Snap Account X"
After: _User-defined name_

image

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Low Risk**
> Low risk UI/selector change that only affects how account names are resolved/displayed in the transaction details modal; primary risk is incorrect/undefined name lookup for some addresses.
> 
> **Overview**
> Updates the multichain transaction details modal to render From/To rows via a new `AccountRow` component that resolves a user-facing **account group** display name (falling back to `shortenAddress`) rather than showing the internal account name.
> 
> Adds a new selector, `selectAccountGroupNameByAddress`, plus tests, to map an address to its containing account group name (or fall back to the internal account name when no group metadata exists).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit dadb13f69489b34a7a87e32a600a86d028204e90. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx [hunk 1]
```diff
@@ -108,49 +165,6 @@ export function MultichainTransactionDetailsModal({
   };
   const statusKey = KEYRING_TRANSACTION_STATUS_KEY[status];
 
-  const accountComponent = (label: string, address?: string) => {
```
Comment (n3ps) [inline ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx:111]: 1. Just extracted as-is

File: ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx [hunk 2]
```diff
@@ -43,23 +43,74 @@ import {
...
   shortenTransactionId,
 } from './helpers';
 
+type Props = {
+  label: string;
+  address?: string;
+  chain: string;
+};
+
+const AccountRow = ({ label, address, chain }: Props) => {
```
Comment (n3ps) [inline ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx:69]: 2. Extracted from previously inline "accountComponent" for reusability

File: ui/selectors/multichain-accounts/account-tree.ts [hunk 3]
```diff
@@ -883,6 +883,42 @@ export const getWalletIdsByType = createSelector(
   },
 );
 
+/**
+ * Get the account group display name for a given address.
```
Comment (n3ps) [inline ui/selectors/multichain-accounts/account-tree.ts:887]: 3. The fix

File: ui/selectors/multichain-accounts/account-tree.ts [hunk 4]
```diff
@@ -883,6 +883,42 @@ export const getWalletIdsByType = createSelector(
...
+ * Returns the account group name (e.g., "Account 3") rather than
+ * the internal account name (e.g., "Snap Account 11").
+ *
+ * @param state - Redux state.
+ * @param address - The address to look up.
+ * @returns The account group name, internal account name, or undefined.
+ */
+export function selectAccountGroupNameByAddress(
```
Comment (gantunesr) [inline ui/selectors/multichain-accounts/account-tree.ts:895]: Lets add the unit tests to cover this selector use cases

Comment (n3ps) [reply ui/selectors/multichain-accounts/account-tree.ts:895]: @gantunesr added

File: ui/selectors/multichain-accounts/account-tree.ts [hunk 5]
```diff
@@ -883,6 +883,42 @@ export const getWalletIdsByType = createSelector(
...
+  if (!internalAccount) {
+    return undefined;
+  }
+
+  const accountGroup = accountGroups.find((group) =>
+    group.accounts.includes(internalAccount.id),
+  );
+
+  return accountGroup?.metadata.name ?? internalAccount.metadata.name;
+}
```
[the remark this answers is not in the document]
Comment (n3ps) [reply ui/selectors/multichain-accounts/account-tree.ts:920]: The selector does two [.find()] operations on every call. [getInternalAccounts] and [getAllAccountGroups] are already memoized, so those calls are cheap

The [.find()] loops are O(n) over typically small arrays (your account count)

Why it's low severity:
- Only used in one place: [multichain-transaction-details-modal.tsx]
- Modal components don't re-render constantly like list items
- Account arrays are typically <100 items - negligible cost

**Review by gantunesr — APPROVED** [review]

**Review by AndyMBridges — APPROVED** [review]
