### PR TITLE
fix: disable Solana network during onboarding

### LINKED ISSUE #32661: [Bug]: Solana - Onboarding -  I am able to add a Solana account during onboarding, leading me to the Login page and back to `Your wallet is ready page`
### Describe the bug

Whenever I am performing the Wallet Onboarding, if I click in General settings, Networks, I am able to Select Solana. This triggers the Add Solana account modal. If I proceed with that, then I land into the Login screen.
Whenever I enter my password, I land back to the `Your wallet is ready page` 

### Expected behavior

If we allow to create a Solana account from the onboarding setttings (I'm unsure we want this, or if it's also a bug), then after adding Solana account I should remain in the onboarding general settings page.

### Screenshots/Recordings

https://github.com/user-attachments/assets/ef73fe2b-2a92-49a4-9ec2-0e80ccca22a9

### Steps to reproduce

1. Import the wallet
2. Start the Onboarding
3. On the `Your Wallet is Ready` page, click General Settings
4. Click Add network
5. Click Solana
6. Click Add account
7. See you are redirected to the login page (unexpected)
8. Add password
9. See you land into the Your Wallet is Ready ` page

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32813?quickstart=1)

disables Solana network during onboarding by removing the `isUnlocked` condition

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32661

## **Manual testing steps**

1. Import the wallet
2. Start the Onboarding
3. On the Your Wallet is "Ready" page, click General Settings
4. Click Add network and then the back button
5. The Solana network should be disabled
6. Finish the onboarding
7. Go to the network picker on the main wallet page
8. Check that the Solana network is enabled

### **Before**

See https://github.com/MetaMask/metamask-extension/issues/32661

### **After**

Screenshot 2025-05-12 at 12 00 03 AM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/network-list-menu/network-list-menu.tsx [hunk 1]
```diff
@@ -453,9 +453,19 @@ export const NetworkListMenu = ({ onClose }: NetworkListMenuProps) => {
...
   const isNetworkEnabled = useCallback(
-    (network: MultichainNetworkConfiguration): boolean =>
-      network.isEvm || isUnlocked || hasAnyAccountsInNetwork(network.chainId),
-    [hasAnyAccountsInNetwork, isUnlocked],
+    (network: MultichainNetworkConfiguration): boolean => {
+      console.log({
+        isEvm: network.isEvm,
+        completedOnboarding,
+        hasAnyAccountsInNetwork: hasAnyAccountsInNetwork(network.chainId),
+      });
```
Comment (gantunesr) [inline ui/components/multichain/network-list-menu/network-list-menu.tsx:461]: remove

Comment (darkwing) [reply ui/components/multichain/network-list-menu/network-list-menu.tsx:461]: ^ Same

Comment (gantunesr) [reply ui/components/multichain/network-list-menu/network-list-menu.tsx]: https://github.com/MetaMask/metamask-extension/pull/32813/commits/63e3ea505f271c67c381c5f1490bef43bd1c71b8

**Review by vinnyhoward — APPROVED** [review]

**Review by owencraston — APPROVED** [review]
Tested and the fix seems to be working as expected. 

https://github.com/user-attachments/assets/4184c5be-5b16-46ec-8c5a-ddffe906d143

Code looks good to me too! 🐑 🇮🇹
