### PR TITLE
Fix #19941 - Correctly show network name and selection when chainIds collide

### LINKED ISSUE #19941: [Bug]: RPC requests are mixed while using different networks with same chainId
### Describe the bug

**Problem**: if you set up ganache locally with chainId 1, you can see how even if it is using ganache RPC, the top menu displays as if I was on Ethereum Mainnet, making it really confusing. If I unfold the menu I see both networks selected

[Screencast from 10-07-23 16:46:33.webm](https://github.com/MetaMask/metamask-extension/assets/54408225/f3f6921d-565d-4dd7-8687-731a8c15a632)

### Steps to reproduce

1. Run ganache locally with chainId 1 `ganache --chain.chainId 1`
2. Go to MetaMask
3. Add network
4. Add Ganache with chain id 1
5. Select Ganache network
6. Send a tx
7. See top bar menu how `Ethereum Mainnet` is displayed so there is no difference on knowing which chain you are really using

### Error messages or log output

_No response_

### Version

10.33.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

* Fixes #19941

This bug was occurring because we were selecting the first network with a given chain ID.  That means if there's a custom network with a chain ID that matches a pre-installed network (i.e. Mainnet having `0x1` and a localhost `0x1` chain, like the issue cites), we show the wrong network selected in the Network Picker *despite* switching to the correct network.  This is a labeling issue, not a functionality issue.

To fix this issue, I fork the logic for retrieving the current network by checking to see if it's a custom network (by checking for `type=rpc` and searching for the network by configuration ID.  If a pre-installed network, we use the chainId.

## Screenshots/Screencaps

https://github.com/MetaMask/metamask-extension/assets/46655/0a9883a9-ee38-4cfe-a3c3-4f0a6e6b3541

## Manual Testing Steps

1.  Add a bunch of predefined networks like Avalanche, Polygon, etc.
2. Start ganache with `ganache --chain.chainId 1` 
3. Add localhost with a chainID of 1
4. Switch between all of the networks you've added and see that networks switch properly, the network picker shows the correct label, and the correct item in the network list shows as selected.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/selectors/selectors.js [hunk 1]
```diff
@@ -1170,9 +1170,15 @@ export function getNetworkConfigurations(state) {
...
 export function getCurrentNetwork(state) {
   const allNetworks = getAllNetworks(state);
+  const providerConfig = getProviderConfig(state);
   const currentChainId = getCurrentChainId(state);
 
-  return allNetworks.find((network) => network.chainId === currentChainId);
+  const filter =
+    providerConfig.type === 'rpc'
+      ? (network) => network.id === providerConfig.id
+      : (network) => network.chainId === currentChainId;
```
Comment (Gudahtt) [inline ui/selectors/selectors.js:1179]: Thoughts on using `provider.type` instead? `chainId` works, but it makes the result order-dependent. `type` is reliably unique for built-in networks, so that should make this a little more reliable even if the order changes later.

It looks like `providerConfig.type` is available on the network list entries as `network.providerType`

```suggestion
      : (network) => network.providerType === providerConfig.type;
```

Alternatively, since you've set the `id` field to the type for all of the built-in networks, maybe this would work:

```suggestion
      : (network) => network.id === providerConfig.type;
```

Comment (darkwing) [reply ui/selectors/selectors.js]: Awesome idea!

Comment (Gudahtt) [reply ui/selectors/selectors.js]: Using `id` might be more forwards-compatible if we start introducing more custom RPC fields alongside rpc URL, making it no longer unique. We did get a request to support additional headers, where the header might determine the chain.

**Comment by Gudahtt** [comment]
The code looks good, but I'm seeing consistent e2e test failures for the test "finds all recent RPCs in history"

**Review by NidhiKJha — APPROVED** [review]

**Comment by danjm** [comment]
> The code looks good, but I'm seeing consistent e2e test failures for the test "finds all recent RPCs in history"

This was fixed with this change https://github.com/MetaMask/metamask-extension/pull/19947/files#diff-50c876d2ff4c618bf7018751413649df82021af47d93754663e8bf7522bea68fL199-L200

Previously, there were two networks in the fixtures with the same id, and one of those networks would result in a 404 if a request was sent to it. So metamask was attempting to connect to the wrong network.

**Review by danjm — APPROVED** [review]
