### PR TITLE
key tokens by chainId

### LINKED ISSUE #10518: Custom Token added appears in all custom RPC Network
**Describe the bug**
Custom Token added on a custom RPC Network appears in all custom RPC Network

**Steps to reproduce**

1. Add Custom Network RPC
   _name: xDAI Network
   url: https://rpc.xdaichain.com
   chainId: 0x64
   symbol: DAI
   explorer: https://blockscout.com/poa/xdai_

2. Add Custom Network RPC
   _name: Binance Smart Chain
   url: https://bsc-dataseed.binance.org
   chainId: 0x38
   symbol: BNB
   explorer: https://bscscan.com_

3. Select xDAI Network

4. Add a Custom Token
    _token symbol: USDC
    token contract address: 0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83_

5. Switch to Binance Smart Chaine Network

6. Token USDC still appear in list

**Expected behavior**
Custom token should only appear on the RPC network they were created

**Browser details**
 - OS: Windows 10
 - Browser: Version 1.20.108 Chromium: 88.0.4324.182 (Build officiel) (64 bits)
 - MetaMask Version: 9.0.5

### PR DESCRIPTION
**Pull request by brad-decker**
Progresses: #8668 
fixes #10518 

Explanation: Tokens are keyed by providerType which is 'rpc' for all custom networks. Adding a token to one custom network replicates it across all custom networks. This is not only inappropriate but also could lead to issues where a token doesn't exist at the same contract address across chains. 

This PR aims to replicate the user's current experience but silently move the 'rpc' tokens into keys by chainId. It also merges chainIds for the five pre-programmed chains with any custom networks that share those chainIds, so mainnet and custom network with chainId 0x1 will have the same tokens. 

after the migration, any new tokens added per chain will be specific to that chain, and removing tokens from custom networks will not remove them from all.

### CODE REVIEW

File: app/scripts/controllers/preferences.js [hunk 1]
```diff
@@ -671,8 +672,8 @@ export default class PreferencesController {
    *
    *
    */
-  _subscribeProviderType() {
-    this.network.providerStore.subscribe(() => {
+  _subscribeToNetworkDidChange() {
```
Comment (danjm) [inline app/scripts/controllers/preferences.js:675]: As far as I can tell, this change is functionally equivalent, as the NETWORK_DID_CHANGE event is only emitted at the time that the providerStore is updated.

File: app/scripts/controllers/preferences.js [hunk 2]
```diff
@@ -671,8 +672,8 @@ export default class PreferencesController {
    *
```
Comment (danjm) [inline app/scripts/controllers/preferences.js:672]: Nit: the code comment for this method could be slightly modified. `Subscription to NETWORK_DID_CHANGE events` or something like that.

File: app/scripts/migrations/052.js [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+      accountTokens,
+      accountHiddenTokens,
+      frequentRpcListDetail,
+    } = state.PreferencesController;
+
+    const newAccountTokens = {};
+    const newAccountHiddenTokens = {};
+
+    if (accountTokens && Object.keys(accountTokens).length > 0) {
+      for (const account of Object.keys(accountTokens)) {
```
Comment (danjm) [inline app/scripts/migrations/052.js:47]: Nit: I think the account variable might be more appropriately name `address` or `accountAddress`, which better conveys what that variable is.

File: app/scripts/migrations/052.js [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+              break;
+            case KOVAN:
+              newAccountTokens[account][KOVAN_CHAIN_ID] =
+                accountTokens[account][KOVAN];
+              break;
+            default:
+              break;
+          }
+        }
+        if (accountTokens[account][NETWORK_TYPE_RPC]) {
```
Comment (danjm) [inline app/scripts/migrations/052.js:75]: Any reason to put this in its own `if` block instead of add it as a `case` to the above `switch`?

Comment (danjm) [reply app/scripts/migrations/052.js:75]: Oh, because you need the above for loop to complete before the below logic can properly migrate account tokens for custom rpcs that share a chain id with one of the default networks

File: app/scripts/migrations/052.js [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+                ROPSTEN_CHAIN_ID,
+                RINKEBY_CHAIN_ID,
+                GOERLI_CHAIN_ID,
+                KOVAN_CHAIN_ID,
+              ].includes(detail.chainId) &&
+              Array.isArray(newAccountTokens[account][detail.chainId])
+            ) {
+              newAccountTokens[account][detail.chainId] = uniqBy(
+                [
+                  ...newAccountTokens[account][detail.chainId],
```
Comment (danjm) [inline app/scripts/migrations/052.js:89]: Given this logic, it seems the following could happen:

- user currently has token ABC on mainnet
- user currently has token DEF on a custom rpc X, which has the same chainId as mainnet
- user currently has tokens GHI on a custom rpc Y, which has a different chainId than mainnet
- so currently, on mainnet, the user will only see ABC, but on both X and Y the user will see both DEF and GHI (because all tokens are stored by provider type, and X and Y have the same provider type `NETWORK_TYPE_RPC`)
- after this migration, the user will continue to see ABC on mainnet and will see ABC on X (via `...newAccountTokens[account][detail.chainId]`), BUT will also see GHI on mainnet and X (via `...accountTokens[account][NETWORK_TYPE_RPC]`)

I think we should avoid this if possible, but I am not sure that it is possible...

Comment (danjm) [reply app/scripts/migrations/052.js:89]: or am I misunderstanding somehow?

Comment (danjm) [reply app/scripts/migrations/052.js:89]: If I am not misunderstanding, the only way to achieve a distinction of `NETWORK_TYPE_RPC` tokens by chainId would be to check on chain data via a network request. That is, we could check if the user has any of the token each of the networks with the chain id. Not sure if this is feasbile within our migration or desirable given network load.

Comment (danjm) [reply app/scripts/migrations/052.js:89]: Perhaps we need to add precision to what we are keying by here: key by a combination of provider type and chain id

Comment (danjm) [reply app/scripts/migrations/052.js:89]: > key by a combination of provider type and chain id

This would result in the following:
- the migration would not change the current tokens of default networks
- all custom networks would continue to have all the tokens they already do
- custom networks and default networks that share chainIds would NOT have each others tokens as a result of the migration
- post migration, newly added tokens will be added network by network, and even if two networks share a chainId, adding a token to one will not add a token to another (unless we add further code that ensures that)

File: app/scripts/migrations/052.js [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+                ROPSTEN_CHAIN_ID,
+                RINKEBY_CHAIN_ID,
+                GOERLI_CHAIN_ID,
+                KOVAN_CHAIN_ID,
+              ].includes(detail.chainId) &&
+              Array.isArray(newAccountHiddenTokens[account][detail.chainId])
+            ) {
+              newAccountHiddenTokens[account][detail.chainId] = uniqBy(
+                [
+                  ...newAccountHiddenTokens[account][detail.chainId],
```
Comment (danjm) [inline app/scripts/migrations/052.js:147]: This is subject to similar concerns that I raised above.

File: app/scripts/migrations/052.js (hunk 5 above)
Comment (brad-decker) [reply app/scripts/migrations/052.js:89]: I might suggest a simpler solution that gets more to the heart of #8668 (treating custom networks with the chainId 0x1 as mainnet) - For this migration prefer the tokens listed under mainnet for '0x1'. So the following would happen:

1. For all custom networks the user has added that don't share a chainId with a default MetaMask chain, they will continue to have all tokens listed under 'rpc' provider type.
2. For all default networks the user tokens will be unchanged.
3. For any custom network that shares a chainId with a default network, they will inherit the default network's tokens and those will be shared across them.

If we want to preserve the ability to have different tokens on different networks (which is sort of going against the spirit of #8668 in my opinion) that share the same chainId, then I'm fine with @danjm 's suggestion.

@MetaMask/extension-devs anyone else have opinions?

Comment (brad-decker) [reply app/scripts/migrations/052.js:89]: > If I am not misunderstanding, the only way to achieve a distinction of NETWORK_TYPE_RPC tokens by chainId would be to check on chain data via a network request. That is, we could check if the user has any of the token each of the networks with the chain id. Not sure if this is feasbile within our migration or desirable given network load.

i'd like to point out that we don't currently do this, any token a user adds for a custom network is added to *all* custom networks. I think it's out of scope to consider this for this migration and puts the extension in a better place to handle it in the future by isolating tokens added per chain.

Comment (danjm) [reply app/scripts/migrations/052.js:89]: @brad-decker The simpler solution you suggested sounds good. One remaining question about this case:

> For any custom network that shares a chainId with a default network, they will inherit the default network's tokens and those will be shared across them.

Will such custom networks also continue to have all other tokens that are currently under the rpc provider type. Or are you suggesting that, after the migration, these custom networks will only have the tokens that are from the default network they share a chainId with?

Comment (brad-decker) [reply app/scripts/migrations/052.js:89]: Given the following current state:
```js
const frequentRpcListDetail = [
	{
		chainId: '0x1',
        networkName: 'mainnet custom endpoint'
	},
    {
		chainId: '0xabc',
        networkName: 'non default network'
    }
];
const accounTokens = {
  '0x1111': {
    'mainnet': ['X', 'Y', 'Z'],
    'rpc': ['A', 'B', 'C', 'Z'],
   }
};
```

the resulting new structure of accountTokens would be:
```js
accounTokens = {
  '0x1111': {
    '0x1': ['X', 'Y', 'Z'],
    '0xabc': ['A', 'B', 'C', 'Z'],
   }
};
```

so previously the user connected to their custom mainnet endpoint and added 'Z' token, which is also in the default mainnet. presumably for the purposes of tracking that mainnet token on their custom network. They also added 'A', 'B', 'C' tokens for the '0xabc' chain. After the migration the custom network and mainnet will have identical token lists and will remain in sync, including hiding tokens. The custom network with a non default network chain id will remain in the same state it was in prior to the migration with the added benefit that hiding tokens on that network will not hide the tokens elsewhere and adding new tokens to it will not add them elsewhere (for custom RPCs anyways)

Comment (brad-decker) [reply app/scripts/migrations/052.js]: This logic was implemented in the latest commit

File: app/scripts/migrations/052.js (hunk 3 above)
Comment (brad-decker) [reply app/scripts/migrations/052.js]: done in the latest

File: app/scripts/controllers/preferences.js (hunk 2 above)
Comment (brad-decker) [reply app/scripts/controllers/preferences.js]: reworded comment in the latest commit

**Review by danjm — APPROVED** [review]
Latest changes look good. Tests look good. Approved.

**Comment by gigilove2001** [comment]
Probably because of the ether 2.0.
Let’s see what happens.
Cheers .
