### PR TITLE
Fix #16804 - Onboarding - Prevent odd behavior with clicks and show/hide password

### LINKED ISSUE #16804: [Bug]: Onboarding V2 Clicking on a certain area inside the form activates the Hide/Show password function
### Describe the bug

**Problem**: when performing the Create Wallet onboarding V2 process, in the Password screen, if you click around the password input fields, the password will be Shown and Hidden as if you were clicking the Show/Hide password button

https://user-images.githubusercontent.com/54408225/205690360-72974dd7-2e5c-4a95-8d94-409d7fea7502.mp4

### Steps to reproduce

1. Load MM for the first time
2. Click Create Wallet
3. Accept/Reject Metametrics
4. Insert some input on Password/Confirm password fields
5. Click around the input area - password is displayed and hidden accordingly as if you were clicking the Display/Hide button

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation
* Fixes #16804

## Screenshots/Screencaps

https://user-images.githubusercontent.com/46655/206569109-5ad661e6-9913-4998-beea-70e6476a7b1a.mp4

## Manual Testing Steps

* Start the new onboarding flow
* Add password, click around, see no change to show/hide
* Click the show/hide link, see it change

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/pages/onboarding-flow/create-password/create-password.js [hunk 1]
```diff
@@ -182,16 +182,18 @@ export default function CreatePassword({
...
-                type="button"
-                onClick={(e) => {
-                  e.preventDefault();
-                  setShowPassword(!showPassword);
-                }}
-              >
-                {showPassword ? t('hide') : t('show')}
-              </button>
+              <Typography variant={TYPOGRAPHY.H7}>
+                <a
```
Comment (darkwing) [inline ui/pages/onboarding-flow/create-password/create-password.js:186]: I loathe using an `<a>` instead of `<button>` but it appears `<button>` elements inside of a `<label>` cause some really gross behavior which led to this issue.

Comment (adonesky1) [reply ui/pages/onboarding-flow/create-password/create-password.js:186]: only thing is that now the `hide`/`show` button is showing up as blue instead of black. Maybe we can style it back?

Comment (darkwing) [reply ui/pages/onboarding-flow/create-password/create-password.js:186]: I did that on purpose, as we should users it's a clickable element.  Before it it bled in, which looked weird.

**Review by jpuri — APPROVED** [review]

File: ui/pages/onboarding-flow/create-password/create-password.js (hunk 1 above)
Comment (jpuri) [reply ui/pages/onboarding-flow/create-password/create-password.js:186]: Is using anchor tag here not against semantic use of html tags ?

Comment (darkwing) [reply ui/pages/onboarding-flow/create-password/create-password.js:186]: Do you have an alternative?  `<button>` is causing the problem.

**Review by digiwand — APPROVED** [review]
