### PR TITLE
Send metrics event from backend for on chain transaction failures

### LINKED ISSUE #6416: Track events for failed transactions
#6370 requested "Possible to add an event for failed transactions, either on-chain or off?"

To do this, we may need to come up with an elegant way to share data from the front end with the backend (e.g. route related data).

Even if we avoid route related data, we at least need to add a method in the metamask controller that utilizes some key pieces of data related to metametrics. Most importantly: id and whether the user has granted permissions to share metrics data.

### PR DESCRIPTION
**Pull request by danjm**
Resolves https://github.com/MetaMask/metamask-extension/issues/6416

Uses front end selectors and metametrics utility to send from backend on a transaction status update that includes a txReciept

### CODE REVIEW

File: app/scripts/lib/backend-metametrics.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+const inDevelopment = process.env.NODE_ENV === 'development'
+
+const METAMETRICS_TRACKING_URL = inDevelopment
+  ? 'http://www.metamask.io/metametrics'
+  : 'http://www.metamask.io/metametrics-prod'
+
+async function backEndMetaMetricsEvent (getState, eventData) {
+  const metamask = await getState()
+  const state = { metamask }
+  console.log('!!!!!!!!!!!!!!!! state', state)
```
Comment (chikeichan) [inline app/scripts/lib/backend-metametrics.js]: nuke

File: app/scripts/lib/backend-metametrics.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+} = require('../../../ui/app/helpers/utils/metametrics.util')
+
+const inDevelopment = process.env.NODE_ENV === 'development'
+
+const METAMETRICS_TRACKING_URL = inDevelopment
+  ? 'http://www.metamask.io/metametrics'
+  : 'http://www.metamask.io/metametrics-prod'
+
+async function backEndMetaMetricsEvent (getState, eventData) {
+  const metamask = await getState()
```
Comment (chikeichan) [inline app/scripts/lib/backend-metametrics.js]: i personally find it easier to pass state object around instead of `getState`, and I would create a new selector called `getMetaMetricState` to get line 23 to 29, and passed it in to `backEndMetaMetricsEvent`. Based on code here I don't think it would mess with asynchronicity. What do you think @danjm ?

Comment (danjm) [reply app/scripts/lib/backend-metametrics.js]: Thanks @chikeichan. Changes made in 6b3c8c7cf

**Review by chikeichan — APPROVED** [review]
