### PR TITLE
fix: split state across many top-level keys instead of just `data` and `meta` to reduce our db write volume

### LINKED ISSUE #33879: [Bug]: Abnormal disk writing, 5 mb/s 24/7
### Describe the bug

After fresh install chromium based browser (Opera, chrome, Edge) and installing metamask, writing on disk continuously 5 mb/s 24/7. That's about 500Gbytes per day!!  I found that writing happens in Local Extension Setting folder. 3 Files 011717.log 011719.ldb and MANIFEST-000001 renaming every 1 minute and rewriting. Also funny thing is that i installed metamask in Edge browser, but it working in background and extension logged out, Same problems with writing every second.

Writings on disk recorded with Windows Performance Recorder.

First time i noticed this problem in CrystalDiskMark (Screenshot below), Abnormal Writings 25 Terabytes in 3 months

### Expected behavior

_No response_

### Screenshots/Recordings

Image

Image

Image

Image

### Steps to reproduce

1. Fresh install Chrome or Opera or Edge and metamask
2. Create or restore wallet.

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

12.20.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by davidmurdoch**
## **Description**

Adds a new storage format we call "split state". This new format is gated behind feature flags and is **not** enabled by default for new or old users. A follow up PR will enable it for _new_ users by default. We need to first make it easy to test the migration path (see testing steps below).

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37060?quickstart=1)

## **Changelog**

CHANGELOG entry: reduce write volume to reasonable levels

## **Related issues**

Fixes: #33879

## **Manual testing steps**

1. Build an experimental build (`yarn webpack --type experimental`)
2. Onboard
3. Do some things that change state.
4. Open to `Settings` -> `Developer Settings`
5. Scroll to `Split State Migration` section (you should see `Current storage kind: data`)
6. Set `Migration Enabled flag` to `1 (On)`
7. Set `Max Accounts flag` to some number greater than the account you have.
8. Set `Max Networks flag` to some number greater than the networks you have.
9. In your browser settings, open `Manage Extensions`, then restart MetaMask.
10. Everything should be _exactly_ as it was before, but on the `Developer Settings` tab you should now see `Current storage kind: split`.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds split-state storage (per-controller keys) with migration/rollout logic, updates persistence/migrator/background to support it, and introduces developer settings and tests.
> 
> - **Storage/Persistence (core)**:
>   - Add split-state storage (`storageKind: 'data' | 'split'`) with per-controller writes via `PersistenceManager.update`/`persist` and manifest-backed `ExtensionStore.setKeyValues`/`get`.
>   - Implement migration to split-state (`migrateToSplitState`) and selective persistence using `changedKeys` from `Migrator`.
>   - Default storage kind configurable via manifest flags; backup handling narrowed to key subsets.
> - **Migrator**:
>   - Return `{ state, changedKeys }`, track changed controllers post version 186, validate shape, and include `storageKind` in `generateInitialState`.
>   - Update migration template/types/tests to mutate in place and record `changedKeys`.
> - **Background init**:
>   - Decide split-state rollout via `useSplitStateStorage`; write strategy branches on `storageKind` with gradual rollout sigil.
>   - Replace `update` with `safePersist`; add per-controller `stateChange` persistence and backup key co-persistence.
> - **Utilities**:
>   - `safe-reload` now persists appropriately for both storage kinds.
>   - `setup-initial-state-hooks` and Sentry masking include `meta.storageKind`.
>   - New `use-split-state-storage` reads remote flags and local dev overrides.
> - **UI/Dev settings**:
>   - Add Developer Options section to view current storage kind and set split-state migration flags.
> - **Tests/Build**:
>   - Add E2E state-persistence tests (data → split, attempted-migration skip), update unit tests, and enable dev options in experimental build.
>   - Minor test tweak: increase file write retries.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 12ed339b73a160816d91c17457eea10ea6534a14. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/scripts/migrations/template.ts [hunk 1]
```diff
@@ -1,28 +1,35 @@
...
 
-function transformState(state: Record<string, unknown>) {
-  const newState = state;
-  // transform state here
-  return newState;
+function transformState(
+  state: Record<string, unknown>,
+  changedKeys: Set<string>,
+): Promise<void> | void {
+  (state.ControllerKey as { newProperty: string }).newProperty = 'newValue';
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts:32]: that's fine; this just intends to show the intent of the migration template.

File: app/scripts/lib/stores/persistence-manager.ts [hunk 2]
```diff
@@ -262,6 +309,92 @@ export class PersistenceManager {
...
+          await this.#localStore.setKeyValues(clone);
+
+          const partialState = Object.create(null);
+          for (const [key, value] of clone.entries()) {
+            if (backedUpStateKeys.includes(key as BackedUpStateKey)) {
+              partialState[key] = value;
+            }
+          }
+          if (hasVault(partialState)) {
+            const backup = makeBackup(partialState, meta);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/persistence-manager.ts:390]: fixed in https://github.com/MetaMask/metamask-extension/pull/37060/commits/dfbaee516ab38e50456318aa658fc03a7c547789 by always setting all `backedUpStateKeys` whenever any change.

File: app/scripts/lib/migrator/index.js [hunk 3]
```diff
@@ -13,6 +15,8 @@ import log from 'loglevel';
  * @property {number} [defaultVersion] - The version to use in the initial state
  */
 
+const MIGRATION_V2_START_VERSION = 184;
```
Comment (davidmurdoch) [inline app/scripts/lib/migrator/index.js]: The version we choose doesn't really matter, we just need to choose a point at which we want to use the more efficient migration algo.

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 4]
```diff
@@ -0,0 +1,534 @@
...
+      `manifest key ${key} should be present in storage`,
+    );
+  }
+
+  if (typeof storage['temp-cronjob-storage'] === 'undefined') {
+    assert.fail(
+      'Yay! You removed temp-cronjob-storage from the db. Now update this test by removing this block.',
+    );
+  } else {
+    delete storage['temp-cronjob-storage']; // <- don't forget to delete this line if you remove temp-cronjob-storage
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:157]: Nope. You've got it backwards.

File: app/scripts/migrations/template.ts [hunk 5]
```diff
@@ -1,28 +1,35 @@
...
+  delete state.OldControllerKey;
+  // if you add/remove/edit a new controller key, you need to track it in
+  // changedKeys or your migration will not persist.
+  changedKeys.add('ControllerKey');
+  changedKeys.add('OldControllerKey');
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts:37]: its just an example bro, chill

File: app/scripts/migrations/template.ts [hunk 6]
```diff
@@ -1,28 +1,35 @@
...
+    meta: { version: number };
+    data: Record<string, unknown>;
+  },
+  changedKeys: Set<string>,
+): void | Promise<void> {
   versionedData.meta.version = version;
-  versionedData.data = transformState(versionedData.data);
-  return versionedData;
+  transformState(versionedData.data, changedKeys);
+  return undefined;
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts]: its just a template and is meant to be verbose

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 7]
```diff
@@ -0,0 +1,534 @@
...
+      (async () => {
+        try {
+          const output = await (${runScript});
+          callback({ result: output });
+        } catch (error) {
+          callback({ error: error?.message ?? error?.toString?.() ?? error });
+        }
+      })();
+    `);
+  }
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts]: No, `runScript` is `null`able on purpose.

File: app/scripts/lib/stores/extension-store.ts [hunk 8]
```diff
@@ -27,9 +34,90 @@ export default class ExtensionStore implements BaseStore {
...
+      // get all keys from the manifest, and load those keys
+      const data = await local.get(keys);
+      this.#manifest = new Set(keys);
+      const { meta } = data;
+      delete data.meta;
+      console.timeEnd('[ExtensionStore] Reading from local store');
+      return {
+        data,
+        meta: meta as unknown as MetaData,
+      };
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/extension-store.ts:59]: No, it does not store "manifest" in the manifest

File: app/scripts/background.js [hunk 9]
```diff
@@ -739,7 +740,33 @@ async function initialize(backup) {
...
+            if (key === controllerKey) {
+              // already updated this one
+              return;
+            }
+            const state = controller.controllerMessenger.call(
+              `${key}:getState`,
+            );
+            persistenceManager.update(key, state);
+          });
+        }
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/background.js]: No, I had to make this change because another Copilot review told me I needed to make this change.

File: app/scripts/lib/migrator/index.js [hunk 10]
```diff
@@ -30,31 +34,66 @@ export default class Migrator extends EventEmitter {
...
+            throw new Error(
+              'Migrator - migration returned value when none expected',
+            );
+          }
+          // a migration that doesn't change any controllers is valid, but it'd
+          // be nice to know
+          if (localChangedControllers.size === 0) {
+            log.debug(
+              `Migrator - migration ${migration.version} did not report any changes`,
+            );
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/migrator/index.js:88]: It's just a warning, not a failure.

File: ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx [hunk 11]
```diff
@@ -0,0 +1,218 @@
...
+            <input
+              type="radio"
+              name="split-state-migration-enabled"
+              checked={enabled === '1'}
+              onChange={() => handleEnabledChange('1')}
+            />
+            1 (On)
+          </label>
+        </div>
+      </label>
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: good catch

File: app/scripts/lib/stores/extension-store.ts [hunk 12]
```diff
@@ -27,9 +34,90 @@ export default class ExtensionStore implements BaseStore {
...
+    console.time('[ExtensionStore] Writing to local store');
+    log.info(
+      `[ExtensionStore] Writing ${Object.keys(toSet).length} keys to local store`,
+    );
+    await local.set(toSet);
+    log.info(
+      `[ExtensionStore] Removing ${toRemove.length} keys from local store`,
+    );
+    await local.remove(toRemove);
+    console.timeEnd('[ExtensionStore] Writing to local store');
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/extension-store.ts]: I'll wrap the remove in a `catch`, but once there is a set/remove failure we can't just *magically* recover from it and "revert" changes; that is likely to make things worse. It's a one-way street.

File: app/scripts/lib/stores/persistence-manager.ts [hunk 13]
```diff
@@ -262,6 +309,92 @@ export class PersistenceManager {
...
+            // save it to the backup DB
+            await this.#backupDb?.set(backup);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/persistence-manager.ts:392]: No, this `persist` code path is only executed _when the data changes_, so it is guaranteed to be different here; this is why we don't need the check

File: app/scripts/lib/stores/fixture-extension-store.ts [hunk 14]
```diff
@@ -22,13 +22,41 @@ export class FixtureExtensionStore extends ExtensionStore {
...
       const response = await fetchWithTimeout(FIXTURE_SERVER_URL);
 
       if (response.ok) {
         const state = await response.json();
-        await super.set(state);
+        if (state.meta?.storageKind === 'split') {
+          // If fixture is already in split state format, convert it properly
+          const kvs = new Map(Object.entries(state.data));
+          kvs.set('meta', state.meta);
+          await this.setKeyValues(kvs);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/fixture-extension-store.ts]: i think you fixed a bug!

File: app/scripts/lib/migrator/index.js [hunk 15]
```diff
@@ -13,6 +15,8 @@ import log from 'loglevel';
  * @property {number} [defaultVersion] - The version to use in the initial state
  */
 
+const MIGRATION_V2_START_VERSION = 185;
+
```
Comment (davidmurdoch) [inline app/scripts/lib/migrator/index.js:19]: The version we choose doesn't really matter, we just need to choose a point at which we want to use the more efficient migration algo.

File: app/scripts/background.js [hunk 16]
```diff
@@ -957,8 +996,61 @@ export async function loadStateFromPersistence(backup) {
...
+      // a sigil to mark that we *tried* to migrate to split state storage
+      versionedData.meta.platformSplitStateGradualRolloutAttempted = true;
+      persistenceManager.setMetadata(versionedData.meta);
+    }
+
+    log.debug(
+      "[Split State]: Writing data to persistence with storageKind 'data'",
+    );
+    // write to disk
+    await persistenceManager.set(versionedData.data);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/background.js:988]: it persists when we do the `await persistenceManager.set(versionedData.data);` call right after setting it to true.

File: app/scripts/lib/migrator/index.js [hunk 17]
```diff
@@ -30,31 +34,66 @@ export default class Migrator extends EventEmitter {
...
+        /** @type {{data: object, meta: {version: number}}} */
+        let migratedData;
+        if (migration.version < MIGRATION_V2_START_VERSION) {
+          migratedData = await migration.migrate(state);
+          assertValidShape(migratedData, migration);
+        } else {
+          // when we have split state we require migrations to report which
+          // controllers changed, and to directly mutate the `versionedData`
+          // object
+          migratedData = structuredClone(state);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/migrator/index.js:67]: this is just the way it was done before, but INSIDE migrations. Now I just do it here isntead.

Comment (davidmurdoch) [inline app/scripts/lib/migrator/index.js:67]: Previously, the first thing a migration would do is call `const versionedData = cloneDeep(originalVersionedData);` inside the migration. This just maintains that approach (I don't know _why_ we do this, but didn't want to change it now), but does it on the _outside_ of the migration, reducing the migration boilerplate.

File: app/scripts/lib/stores/persistence-manager.ts [hunk 18]
```diff
@@ -182,11 +199,35 @@ export class PersistenceManager {
...
+      this.storageKind === 'split' &&
+      JSON.stringify(this.#metadata) === JSON.stringify(metadata)
+    ) {
+      return;
+    }
     this.#metadata = metadata;
+    if (this.storageKind === 'split') {
+      this.#pendingPairs.set('meta', metadata);
+    }
   }
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/persistence-manager.ts:224]: No, in `data` mode it always writes all state, including the `metadata` here.

File: app/scripts/lib/stores/persistence-manager.ts [hunk 19]
```diff
@@ -262,6 +309,105 @@ export class PersistenceManager {
...
+          const partialState = Object.create(null);
+          for (const [key, value] of clone.entries()) {
+            if (backedUpStateKeys.includes(key as BackedUpStateKey)) {
+              partialState[key] = value;
+            }
+          }
+          if (hasVault(partialState)) {
+            const backup = makeBackup(partialState, meta);
+            // save it to the backup DB
+            await this.#backupDb?.set(backup);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/persistence-manager.ts:392]: I don't want to refactor the way backups are done in this PR

File: app/scripts/lib/use-split-state-storage.ts [hunk 20]
```diff
@@ -0,0 +1,117 @@
...
+      if (overrides.enabled === false) {
+        return false;
+      }
+
+      const { accountCount, networkCount } = getCounts(state);
+
+      return (
+        accountCount <= overrides.maxAccounts &&
+        networkCount <= overrides.maxNetworks
+      );
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/use-split-state-storage.ts:98]: nah, we already have a flag that enabled/disabled the whole thing at once.

File: app/scripts/migrations/template.ts [hunk 21]
```diff
@@ -1,28 +1,35 @@
...
 }
 
-function transformState(state: Record<string, unknown>) {
-  const newState = state;
-  // transform state here
-  return newState;
+function transformState(
+  state: Record<string, unknown>,
+  changedKeys: Set<string>,
+): Promise<void> | void {
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts:28]: eh, nah.

File: ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx [hunk 22]
```diff
@@ -0,0 +1,218 @@
...
+        'meta',
+      ]);
+
+      if (!isMounted) {
+        return;
+      }
+
+      setEnabled(toEnabledString(splitStateMigrationEnabled));
+      setStorageKind(
+        typeof meta?.storageKind === 'string' ? meta.storageKind : 'unknown',
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: true.

File: app/scripts/lib/safe-reload.ts [hunk 23]
```diff
@@ -29,13 +38,17 @@ export function getRequestSafeReload(persistenceManager: PersistenceManager) {
...
+     * @param params - Arguments to pass to the persistence operation. For
+     * 'data' storage, pass the state; for 'split' storage, no arguments needed.
      * @returns true if the update was queued, false if writes are not allowed.
      */
-    update: async (...params: Parameters<PersistenceManager['set']>) => {
+    persist: async (
+      ...params: Parameters<
+        PersistenceManager['set'] | PersistenceManager['persist']
+      >
+    ) => {
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/safe-reload.ts]: wat?

File: app/scripts/migrations/template.ts [hunk 24]
```diff
@@ -1,28 +1,35 @@
...
+    meta: { version: number };
+    data: Record<string, unknown>;
+  },
+  changedKeys: Set<string>,
+): void | Promise<void> {
   versionedData.meta.version = version;
-  versionedData.data = transformState(versionedData.data);
-  return versionedData;
+  transformState(versionedData.data, changedKeys);
+  return undefined;
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts]: I've refactored with better types

File: app/scripts/lib/use-split-state-storage.ts [hunk 25]
```diff
@@ -0,0 +1,117 @@
...
+        ? null
+        : splitStateMigrationEnabled === '1',
+    maxAccounts:
+      splitStateMigrationMaxAccounts === undefined
+        ? 0
+        : Number(splitStateMigrationMaxAccounts),
+    maxNetworks:
+      splitStateMigrationMaxNetworks === undefined
+        ? 0
+        : Number(splitStateMigrationMaxNetworks),
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/use-split-state-storage.ts:58]: nah. we want it to leave people out on purpose.

File: app/scripts/lib/migrator/index.js [hunk 26]
```diff
@@ -64,11 +103,21 @@ export default class Migrator extends EventEmitter {
...
+        break;
       }
     }
 
-    return versionedData;
+    const changedKeys =
+      initialData.meta.version < MIGRATION_V2_START_VERSION
+        ? // we had to run older migrations, so assume all controllers changed
+          new Set(Object.keys(state.data))
+        : new Set();
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/migrator/index.js:115]: > which can happen when migrations fail early

Migrations receive a clone of the state, they don't mutate it. If they fail early their clone doesn't get assigned to the `state` object, so it can't cause a problem.

The other issue is probably true though.

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 27]
```diff
@@ -0,0 +1,538 @@
...
+  if (typeof storage['temp-cronjob-storage'] === 'undefined') {
+    // temp-cronjob-storage is a temporary key added in a hotfix and is
+    // supposed to be removed at some point. Once it is removed from the codebase,
+    // this block should be removed, which is why removing it causes this test
+    // to fail.
+    assert.fail(
+      'Yay! You removed temp-cronjob-storage from the db. Now update this test by removing this block.',
+    );
+  } else {
+    delete storage['temp-cronjob-storage']; // <- don't forget to delete this line if you remove temp-cronjob-storage
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:157]: still no

File: app/scripts/lib/migrator/index.js [hunk 28]
```diff
@@ -64,11 +103,21 @@ export default class Migrator extends EventEmitter {
...
+
+    for (const controllerKey of changedControllers) {
+      changedKeys.add(controllerKey);
+    }
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/migrator/index.js:119]: >if no v2 migrations ran

If `initialData.meta.version < MIGRATION_V2_START_VERSION` is true then old migrations did run. its the whole point of this check.

File: app/scripts/background.js [hunk 29]
```diff
@@ -736,7 +737,38 @@ async function initialize(backup) {
     cronjobControllerStorageManager,
   );
 
-  controller.store.on('update', update);
+  if (persistenceManager.storageKind === 'split') {
+    controller.store.on(
+      'stateChange',
+      async ({ controllerKey, newState, _oldState, _patches }) => {
```
Comment (davidmurdoch) [inline app/scripts/background.js]: Note to reviewers: `stateChange` happens for any state change. So in a way it is _worse_ than before, as update only happened on persisted state changes. A "fix" for this is being done in core.

File: app/scripts/lib/use-split-state-storage.ts (hunk 25 above)
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/use-split-state-storage.ts:58]: we talked about this already. go away.

File: test/e2e/dist/vault-decryption-chrome.spec.ts [hunk 30]
```diff
@@ -103,7 +103,7 @@ async function getFileSize(filePath: string): Promise<number> {
  */
 async function waitUntilFileIsWritten({
   driver,
-  maxRetries = 5,
+  maxRetries = 10,
```
Comment (davidmurdoch) [inline test/e2e/dist/vault-decryption-chrome.spec.ts:106]: this is just a flaky test ... and this seems to fix it (for now).

File: app/scripts/lib/use-split-state-storage.ts [hunk 31]
```diff
@@ -0,0 +1,117 @@
...
+  };
+}
+
+/**
+ * Get current account and network counts from the messenger
```
Comment (MajorLift) [inline app/scripts/lib/use-split-state-storage.ts]:
```suggestion
 * Get current account and network counts from controller state
```

File: app/scripts/lib/stores/persistence-manager.ts (hunk 19 above)
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/persistence-manager.ts:392]: stop repeating yourself.  go away robot

File: app/scripts/migrations/types.ts [hunk 32]
```diff
@@ -0,0 +1,34 @@
...
+    /**
+     * The kind of storage being used.
+     */
+    storageKind?: 'data' | 'split';
+  };
+  /**
+   * The persisted MetaMask state, keyed by controller.
+   */
+  data: Record<string, unknown>;
+};
```
Comment (MajorLift) [inline app/scripts/migrations/types.ts]: nit: Deduplication?

```suggestion
import type { MetaMaskStorageStructure as VersionedData } from '../lib/stores/base-store';

```

File: app/scripts/lib/stores/extension-store.ts [hunk 33]
```diff
@@ -27,9 +36,118 @@ export default class ExtensionStore implements BaseStore {
...
+      hasProperty(response, 'manifest') &&
+      Array.isArray(response.manifest)
+    ) {
+      const keys = response.manifest;
+
+      // get all keys from the manifest, and load those keys
+      const data = await local.get(keys);
+      this.#manifest = new Set(keys);
+      const { meta } = data;
+      delete data.meta;
```
Comment (MajorLift) [inline app/scripts/lib/stores/extension-store.ts:54]: In case `keys` is invalid or corrupted? Or would it make more sense to throw?
```suggestion
      const { meta } = data ?? {};
      delete data?.meta;
```

File: app/scripts/lib/safe-reload.ts [hunk 34]
```diff
@@ -29,13 +38,17 @@ export function getRequestSafeReload(persistenceManager: PersistenceManager) {
...
+     * Safely updates the persistence manager
      *
-     * @param params - Parameters to be passed to the persistence manager's
-     * `set` method.
+     * @param params - Arguments to pass to the persistence operation. For
+     * 'data' storage, pass the state; for 'split' storage, no arguments needed.
      * @returns true if the update was queued, false if writes are not allowed.
      */
-    update: async (...params: Parameters<PersistenceManager['set']>) => {
+    persist: async (
```
Comment (MajorLift) [inline app/scripts/lib/safe-reload.ts]: nit: clarity for downstream contexts.
```suggestion
    safePersist: async (
```

File: app/scripts/lib/stores/persistence-manager.ts [hunk 35]
```diff
@@ -262,6 +309,105 @@ export class PersistenceManager {
...
+            // merge the clone with the pending pairs again
+            for (const [key, value] of clone.entries()) {
+              // we can't just overwrite because other `update` calls might have
+              // happened since we created the clone. We don't want to overwrite
+              // any new changes.
+              if (!this.#pendingPairs.has(key)) {
+                this.#pendingPairs.set(key, value);
+              }
+            }
+            throw err;
```
Comment (MajorLift) [inline app/scripts/lib/stores/persistence-manager.ts:380]: 👍 on race condition handling.

File: app/scripts/lib/stores/extension-store.ts (hunk 33 above)
Comment (davidmurdoch) [reply app/scripts/lib/stores/extension-store.ts:54]: data will always be defined here. It might be an empty object though.

File: app/scripts/migrations/types.ts (hunk 32 above)
Comment (davidmurdoch) [reply app/scripts/migrations/types.ts]: Fixed by [4da6d6a8b42ce06f1a9015eea404bc4da18752f1](https://github.com/MetaMask/metamask-extension/pull/37060/commits/4da6d6a8b42ce06f1a9015eea404bc4da18752f1)

File: app/scripts/lib/safe-reload.ts (hunk 34 above)
Comment (davidmurdoch) [reply app/scripts/lib/safe-reload.ts]: fixed in https://github.com/MetaMask/metamask-extension/pull/37060/commits/d7991cc7041956a4d8b4251df51d673fc07f1008

File: app/scripts/background.js [hunk 36]
```diff
@@ -736,7 +738,38 @@ async function initialize(backup) {
...
+            persistenceManager.update(key, state);
+          });
+        }
+        try {
+          await safePersist();
+        } catch (error) {
+          log.error('Error persisting state change:', error);
+          sentry?.captureException(error);
+        }
+      },
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/background.js]: no

File: ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx [hunk 37]
```diff
@@ -0,0 +1,218 @@
+import { Text } from '@metamask/design-system-react';
+import browser from 'webextension-polyfill';
+import React, { useEffect, useState } from 'react';
+import TextField from '../../../components/ui/text-field';
```
Comment (MajorLift) [inline ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: Looks like this import is causing the design systems fitness function fail.

> https://github.com/MetaMask/metamask-extension/actions/runs/20099444192/job/57681515341?pr=37060

```diff
diff --git a/ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx b/ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx
index 71921d1427..7086f0e7d4 100644
--- a/ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx
+++ b/ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx
@@ -1,7 +1,10 @@
 import { Text } from '@metamask/design-system-react';
 import browser from 'webextension-polyfill';
 import React, { useEffect, useState } from 'react';
-import TextField from '../../../components/ui/text-field';
+import {
+  TextField,
+  TextFieldType,
+} from '../../../components/component-library/text-field';
 
 const MigrateToSplitStateTest = () => {
   const [enabled, setEnabled] = useState<string | null>(null);
@@ -191,9 +194,8 @@ const MigrateToSplitStateTest = () => {
         <label>
           <span>Max Accounts flag:</span>
           <TextField
-            min="0"
-            max="99999999"
-            type="number"
+            maxLength={99999999}
+            type={TextFieldType.Number}
             value={maxAccounts}
             onChange={handleMaxAccountsChange}
           />
@@ -203,9 +205,8 @@ const MigrateToSplitStateTest = () => {
         <label>
           <span>Max Networks flag:</span>
           <TextField
-            min="0"
-            max="99999999"
-            type="number"
+            maxLength={99999999}
+            type={TextFieldType.Number}
             value={maxNetworks}
             onChange={handleMaxNetworksChange}
           />

```

Comment (MajorLift) [reply ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: Weird, it's still failing: https://github.com/MetaMask/metamask-extension/actions/runs/20109017580/job/57708616221?pr=37060

Updating this import fixes the check for me on local.

File: app/scripts/background.js (hunk 29 above)
Comment (Gudahtt) [reply app/scripts/background.js]: It should be the same as before I think? The guard we have to ensure that some persisted property has changed remains in-place:  https://github.com/MetaMask/metamask-extension/blob/656256b1b2f32bc67ed3d3d903ff88aa6025e8fd/app/scripts/lib/ComposableObservableStore.js#L74
And that check is _prior_ to the [`stateChange` event](https://github.com/MetaMask/metamask-extension/blob/656256b1b2f32bc67ed3d3d903ff88aa6025e8fd/app/scripts/lib/ComposableObservableStore.js#L126) we're listening to here.

For `controller.store`, this should only be emitted if _some_ persisted property has changed.

It's still non-optimal in cases where the whole state is replaced, e.g. if a controller does something like this:

```
this.update((draft) => {
  // derive new state
  return newState
}
```
i.e. if it does a complete state replacement rather than mutating the draft. _That_ will be fixed by the core changes you alluded to (which I started looking into yesterday! Still early though, no ETA yet).

But it's not obvious to me that we have a regression here.

**Review by MajorLift — DISMISSED** [review]
Beautiful. LGTM:

Screenshot 2025-12-10 at 4 23 54 PM

File: ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx (hunk 37 above)
Comment (davidmurdoch) [reply ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: all this trouble for a temporary ui. they should delete components that shouldn't be used. gah!

Comment (MajorLift) [reply ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: We could really use a TTL for deprecated stuff.. That `TextField` was deprecated in Aug 2023😂 131321af00a79a25d4e92222df82157a9ee347cf

Comment (davidmurdoch) [reply ui/pages/settings/developer-options-tab/migrate-to-split-state-test.tsx]: I'm just using `input` now.

File: app/scripts/lib/safe-reload.ts [hunk 38]
```diff
@@ -12,11 +12,20 @@ const { sentry } = global;
  * @param persistenceManager - The PersistenceManager instance to be used for
  * updates.
  */
```
Comment (Gudahtt) [inline app/scripts/lib/safe-reload.ts]: Nit: Could use documentation for the type param:

```suggestion
 * @template Type - The persistence manager type.
 */
```

**Review by MajorLift — DISMISSED** [review]

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 39]
```diff
@@ -0,0 +1,516 @@
...
+    );
+  }
+
+  if (typeof storage['temp-cronjob-storage'] === 'undefined') {
+    // temp-cronjob-storage is a temporary key added in a hotfix and is
+    // supposed to be removed at some point. Once it is removed from the codebase,
+    // this block should be removed, which is why removing it causes this test
+    // to fail.
+    assert.fail(
+      'Yay! You removed temp-cronjob-storage from the db. Now update this test by removing this block.',
```
Comment (seaona) [inline test/e2e/tests/state-persistence/state-persistence.spec.ts:154]: haha love this :P

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 40]
```diff
@@ -0,0 +1,516 @@
...
+
+/**
+ * Waits for the extension to reload and the home screen to appear.
+ *
+ * @param driver - WebDriver instance.
+ */
+async function waitForRestart(driver: Driver) {
+  await driver.waitUntil(
+    async () => {
+      await driver.navigate(PAGES.HOME, { waitForControllers: false });
```
Comment (seaona) [inline test/e2e/tests/state-persistence/state-persistence.spec.ts:264]: q: could we wait for controllers here? Once the restart is completed we should see that class right? or am I missing something 🤔

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 41]
```diff
@@ -0,0 +1,516 @@
...
+const SPLIT_FLAG = {
+  value: { enabled: 1, maxAccounts: 9999999, maxNetworks: 9999999 },
+};
+const MIGRATION_OVERRIDE_KEYS = [
+  'splitStateMigrationEnabled',
+  'splitStateMigrationMaxAccounts',
+  'splitStateMigrationMaxNetworks',
+];
+const BASE_MANIFEST_TESTING_FLAGS = { forceExtensionStore: true };
+
```
Comment (seaona) [inline test/e2e/tests/state-persistence/state-persistence.spec.ts:37]: q: how did you manage to bypass the sidepanel issue locally ? @davidmurdoch

File: app/scripts/lib/stores/persistence-manager.ts [hunk 42]
```diff
@@ -403,4 +555,42 @@ export class PersistenceManager {
...
+    this.setMetadata(metadata);
+    for (const [key, value] of Object.entries(state)) {
+      this.update(key, value);
+    }
+
+    // mark data key for deletion
+    this.update('data', undefined);
+
+    log.debug('[Split State]: Migrating to split state storage');
+    await this.persist();
```
Comment (gauthierpetetin) [inline app/scripts/lib/stores/persistence-manager.ts:594]: Here we persist everything the same `persist` operation:

1. The "split" state: each top-level controller state saved into its own key in the storage
2. The "data" state: deletion of the `data` key

Could it be safer to perform 2 distinct `persist` operations:

1. Persist each top-level controller state saved into its own key in the storage
2. If successful, persist the deletion of the `data` key

Or even:

1. Persist the "data" state AND each top-level controller state saved into its own key in the storage
2. If successful, persist the deletion of the `data` key

This ensures we still have the "data" state and we can handle the rollback smoothly in case the migration fails halfway.

File: test/e2e/tests/state-persistence/state-persistence.spec.ts (hunk 41 above)
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:37]: I set it in my own `.metamaskrc`

File: test/e2e/tests/state-persistence/state-persistence.spec.ts (hunk 40 above)
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:264]: No, `waitForControllers` will throw if the controllers aren't found. Metamask doesn't exist yet when we first start navigating to the page.

File: app/scripts/lib/stores/fixture-extension-store.ts [hunk 43]
```diff
@@ -22,13 +22,41 @@ export class FixtureExtensionStore extends ExtensionStore {
...
       const response = await fetchWithTimeout(FIXTURE_SERVER_URL);
 
       if (response.ok) {
         const state = await response.json();
-        await super.set(state);
+        if (state.meta?.storageKind === 'split') {
+          // If fixture is already in split state format, convert it properly
+          const kvs = new Map(Object.entries(state.data));
+          kvs.set('meta', state.meta);
+          await super.setKeyValues(kvs);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/lib/stores/fixture-extension-store.ts:70]: fixtures aren't.

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 44]
```diff
@@ -0,0 +1,516 @@
...
+/**
+ * Ensures the data state storage is present and valid.
+ *
+ * @param driver - WebDriver instance.
+ * @returns Parsed data state storage snapshot.
+ */
+const expectDataStateStorage = async (driver: Driver) => {
+  const storage = await readStorage(driver);
+  console.log('storage read:', storage);
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:251]: we've been over this. shut up about it.

File: app/scripts/migrations/template.ts [hunk 45]
```diff
@@ -1,28 +1,38 @@
...
 
 /**
  * Explain the purpose of the migration here.
  *
- * @param originalVersionedData - Versioned MetaMask extension state, exactly what we persist to dist.
- * @param originalVersionedData.meta - State metadata.
- * @param originalVersionedData.meta.version - The current state version.
- * @param originalVersionedData.data - The persisted MetaMask state, keyed by controller.
- * @returns Updated versioned MetaMask extension state.
+ * @param versionedData - Versioned MetaMask extension state; what we persist to dist.
```
Comment (gauthierpetetin) [inline app/scripts/migrations/template.ts]: Should this be "disk" instead of "dist"?

File: test/e2e/tests/state-persistence/state-persistence.spec.ts [hunk 46]
```diff
@@ -0,0 +1,516 @@
...
+
+  return (result?.value ?? {}) as StoredState;
+};
+
+/**
+ * Validates the expected shape of split state storage.
+ *
+ * @param storage - Parsed storage snapshot.
+ */
+const assertSplitStateStorage = (storage: SplitStateStorage) => {
```
Comment (gauthierpetetin) [inline test/e2e/tests/state-persistence/state-persistence.spec.ts:122]: Should we check that `KeyringController` is available in storage, like we do in `assertDataStateStorage`?

File: app/scripts/migrations/template.ts [hunk 47]
```diff
@@ -1,28 +1,38 @@
...
   // transform state here
-  return newState;
+
+  // Example transformation:
+  (state.ControllerKey as { newProperty: string }).newProperty = 'newValue';
+  delete state.OldControllerKey;
+  // if you add/remove/edit a new controller key, you need to track it in
+  // `changedKeys` or your migration will not persist.
+  changedKeys.add('ControllerKey');
+  changedKeys.add('OldControllerKey');
```
Comment (gauthierpetetin) [inline app/scripts/migrations/template.ts:37]: In the case where contributors forget to add controller keys to `changedKeys`, some users could end up in a situation where the change works during the first session (as the change exists in memory) but but will be lost on restart (as the change is not persisted in local state).

I wonder whether it is an acceptable risk?

I guess implementing protection mechanisms (such as linting migration files, or adding runtime validations) would be either complex or time-consuming.

File: test/e2e/tests/state-persistence/state-persistence.spec.ts (hunk 41 above)
Comment (seaona) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:37]: thank you!

**Review by gauthierpetetin — COMMENTED** [review]
Thanks for the PR @davidmurdoch it looks really great, I left a few questions in the PR comments.

Also, could we add a [Sentry tag](https://docs.sentry.io/platforms/javascript/enriching-events/tags/) called `storageKind`? It would be helpful to see if certain Sentry issues only occur with specific types of storage.

Finally, I think we should add this feature to the `beta` build and test the app upgrade on multiple wallets with pre-existing state during **MetaMask UAT Fridays**. I know we have an E2E test included in the PR, but just testing the happy/unhappy paths we’ve defined might not be enough to catch every edge case.

If we don’t test the upgrade with the `beta` build, most employees will probably only use it on a fresh install, which isn’t enough to verify whether the migration logic works as expected.

File: app/scripts/background.js (hunk 29 above)
Comment (davidmurdoch) [reply app/scripts/background.js]: ah ok. cool. thanks for the explanation!

File: app/scripts/lib/stores/persistence-manager.ts (hunk 42 above)
Comment (davidmurdoch) [reply app/scripts/lib/stores/persistence-manager.ts:594]:
```
1. Persist each top-level controller state saved into its own key in the storage
2. If successful, persist the deletion of the data key
```

That is how it works inside `persist`. Deleted keys are only removed after the `set` is successful.

File: app/scripts/migrations/template.ts (hunk 45 above)
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts]: haha. yes. good catch!

File: app/scripts/migrations/template.ts (hunk 47 above)
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts:37]: We do log a warning right now when a migration doesn't affect any keys, but it is just a waring because a migration that doesn't do anything isn't valid.

Another way is to try to use a `Proxy`, but that would be pretty complicated to get right.

@Gudahtt thoughts on alternatives to avoid re-writing all state after migrations?

File: test/e2e/tests/state-persistence/state-persistence.spec.ts (hunk 46 above)
Comment (davidmurdoch) [reply test/e2e/tests/state-persistence/state-persistence.spec.ts:122]: We check all keys in the `assertSplitStateStorage` check, but I can add an additional check

**Comment by davidmurdoch** [comment]
> First Manual Smoke Test looks good
> 
>  split-state-smoke-tzt.mov 
> Question 1: If I set the migration version to a lower version value, then migrations are performed and I get the error `Cannot read properties of undefined (reading 'captureException')`. Is it something we woudl expect?
> 
> ```
> background.js:1965 TypeError: Cannot read properties of undefined (reading 'captureException')
>     at Migrator.<anonymous> (background.js:959:12)
>     at Migrator.migrateData (index.js:104:14)
>     at async loadStateFromPersistence (background.js:973:49)
>     at async initialize (background.js:670:20)
>     at async initBackground (background.js:1948:5)
> ```
> 
> image image
> Question 2: Is it expected that if I have a split state, and I change it to data, we are still able to see normal behaviour? Would we expect something different in this case? I'm changing the value directly from the Local storage entry:
> 
>  split-to-data.mov

No, that shouldn't happen. The error appears because we forgot to do `sentry?.captureException` (I did `sentry.captureException`) in once place.

BUUUTTT, I don't think a migration error should be happening at all here. I'll look into it.

File: app/scripts/lib/stores/persistence-manager.ts (hunk 42 above)
Comment (gauthierpetetin) [reply app/scripts/lib/stores/persistence-manager.ts:594]: Ah right, I just rechecked the content of `setKeyValues` function and that's correct. Thanks for explanation.

File: app/scripts/migrations/template.ts (hunk 47 above)
Comment (gauthierpetetin) [reply app/scripts/migrations/template.ts:37]: There doesn't seem to be an easy way to eliminate that risk so I guess we'll have to accept it.
I was asking just in case someone had an idea, but feel free to ignore.

File: app/scripts/migrations/template.ts [hunk 48]
```diff
@@ -1,28 +1,38 @@
-import { cloneDeep } from 'lodash';
+import type { Migrate } from './types';
 
+/**
+ * The version number of this migration.
+ */
 export const version = 0;
```
[the remark this answers is not in the document]
Comment (davidmurdoch) [reply app/scripts/migrations/template.ts:6]: eh

**Review by MajorLift — APPROVED** [review]

**Review by gauthierpetetin — APPROVED** [review]
