### PR TITLE
Fix dropped tx detection

### LINKED ISSUE #8688: Issue with Txs being labeled as dropped but still pending
**Describe the bug**
(Needs addtional verification)

At the time of tx submission the "Safe Low" gas price from EthGasStation was 30gwei. Sent a tx with 25gwei to ensure a fairly moderate wait time, but the tx status was updated to dropped after losing focus in the extension view and reopening and/or after some time.

**Screenshots**
<details>
<summary>Screenshot of Etherscan and tx</summary>

</details>

**Additional context (Error Messages, etc.)**
Possibly widened the errors that can allow the tx status to update to dropped. 
Will updated in the comments with additional info on the issue.

Looks `eth_sendRawTransaction` is calling twice. The first will respond with the tx hash, and the second will respond with a `known transaction` error and thus will proceed to set the tx status to dropped. In prod, it seems the known transaction error does not update the status to dropped.

### PR DESCRIPTION
**Pull request by Gudahtt**
The code for checking whether a transaction was dropped or not was refactored in #8398, but in the process an off-by-one error was introduced.

The old version of `_checkIfTxWasDropped` would query for an updated transaction count from the network, and would consider the pending transaction to be dropped if the count was above the nonce. However, the version introduced in #8398 considers the transaction to be dropped if the count is above *or equal to* the nonce.

The pending transaction nonce is expected to be equal to the transaction count, because the nonce starts at zero. The transaction count is equal to the expected next nonce.

The variable name has been updated to make this more clear (`networkNextNonce` is how the `nonce-tracker` refers to this value).

`parseInt` is now called with an explicit radix of `16` as well, to ensure both nonce strings are always parsed as hex. In all cases I am aware of, these nonce strings were prefixed by `0x`, meaning that `parseInt` would default to a radix of `16`, so this likely doesn't constitute a functional change.

Fixes #8688

### CODE REVIEW

File: app/scripts/controllers/transactions/pending-tx-tracker.js [hunk 1]
```diff
@@ -209,9 +209,9 @@ export default class PendingTransactionTracker extends EventEmitter {
    */
   async _checkIfTxWasDropped (txMeta) {
     const { hash: txHash, txParams: { nonce, from } } = txMeta
-    const networkNonce = await this.query.getTransactionCount(from)
+    const networkNextNonce = await this.query.getTransactionCount(from)
 
-    if (parseInt(nonce) > parseInt(networkNonce)) {
+    if (parseInt(nonce) >= parseInt(networkNextNonce)) {
```
Comment (whymarrh) [inline app/scripts/controllers/transactions/pending-tx-tracker.js:214]: Unrelated but can we add radix values to these calls:

```suggestion
    if (parseInt(nonce, 16) >= parseInt(networkNextNonce, 16)) {
```

(I think these are hex?)

**Review by whymarrh — CHANGES_REQUESTED** [review]

File: app/scripts/controllers/transactions/pending-tx-tracker.js (hunk 1 above)
Comment (Gudahtt) [reply app/scripts/controllers/transactions/pending-tx-tracker.js:214]: `networkNextNonce` definitely is. I'll verify the other one is as well.

Comment (Gudahtt) [reply app/scripts/controllers/transactions/pending-tx-tracker.js]: This has been done. I've added this comment to the PR description and commit as explanation:

>`parseInt` is now called with an explicit radix of `16` as well, to ensure both nonce strings are always parsed as hex. In all cases I am aware of, these nonce strings were prefixed by `0x`, meaning that `parseInt` would default to a radix of `16`, so this likely doesn't constitute a functional change.

**Review by brad-decker — APPROVED** [review]

**Review by rekmarks — APPROVED** [review]

**Review by whymarrh — APPROVED** [review]
