### PR TITLE
fix: Contract Interaction - cannot read the property `text_signature`

### LINKED ISSUE #27527: [Bug]: Contract Interaction - `TypeError#5: Cannot read properties of undefined (reading 'text_signature')` when function signature cannot be decoded
### Describe the bug

Whenever I am interacting with a contract function, which there is no signature decode for, I see the background error `TypeError#5: Cannot read properties of undefined (reading 'text_signature')`

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot from 2024-10-01 10-03-10

https://github.com/user-attachments/assets/e9c8f9e7-6acc-44f0-b7ce-b0bdc05afef5

### Steps to reproduce

1. Go to Remix
2. Deploy the contract below
3. Trigger the triggerMe func
4. See console error

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Params {
    uint256 public x;
    uint256 public value;
    address public addr;
    bool public flag;
    string public text;

    function triggerMe(
        uint256 _x,
        uint256 _value,
        address _addr,
        bool _flag,
        string memory _text
    ) public returns (bool) {
        x = _x;
        value = _value;
        addr = _addr;
        flag = _flag;
        text = _text;
        return true;
    }

    receive() external payable {
    }
}

```

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**

This PR introduces a validation to handle cases where the 4byte response results are either undefined or an empty array. Instead of throwing an error, the code now safely handles these cases by returning undefined, preventing the TypeError from occurring.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27686?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27527

## **Manual testing steps**

1. Go to Remix
2. Deploy the contract below
3. Trigger the triggerMe func
4. See console error

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Params {
    uint256 public x;
    uint256 public value;
    address public addr;
    bool public flag;
    string public text;

    function triggerMe(
        uint256 _x,
        uint256 _value,
        address _addr,
        bool _flag,
        string memory _text
    ) public returns (bool) {
        x = _x;
        value = _value;
        addr = _addr;
        flag = _flag;
        text = _text;
        return true;
    }

    receive() external payable {
    }
}

```

## **Screenshots/Recordings**

[4bytes response.webm](https://github.com/user-attachments/assets/0d6d8ba9-5c43-4c65-ad34-7ea416039c6f)

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: shared/lib/four-byte.ts [hunk 1]
```diff
@@ -34,6 +34,10 @@ export async function getMethodFrom4Byte(
     functionName: 'getMethodFrom4Byte',
   })) as FourByteResponse;
 
+  if (!fourByteResponse.results || fourByteResponse.results.length === 0) {
```
Comment (matthewwalsh0) [inline shared/lib/four-byte.ts:37]: Minor, but should it be `!fourByteResponse.results?.length` as otherwise if `results` was set but was an object or invalid format without a `length`, then the below would still run?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: shared/lib/four-byte.ts (hunk 1 above)
Comment (vinistevam) [reply shared/lib/four-byte.ts]: You are right, changed [here](https://github.com/MetaMask/metamask-extension/pull/27686/commits/c48141f0fc921e5bc4e90de9839f044a9905cff3).

**Review by matthewwalsh0 — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
