### PR TITLE
Fixed accounts auto scrolling

### LINKED ISSUE #16657: [Bug]: MM popup keeps auto-scrolling to the top every some seconds
### Describe the bug

**Problem**: if I try to connect to a Dapp and I open MM popup, if I scroll down to the list of address, MM auto-scrolls to the top every some seconds, worsening user experience.

https://user-images.githubusercontent.com/54408225/203592769-605cda87-80c3-4b8c-a5e1-94c99398c458.mp4

### Steps to reproduce

1. Go to a dapp https://spruceid.github.io/test-dapp/
2. Click Connect
3. Scroll down the list of address from the MM popup
4. Wait -- see how MM scrolls you back up
5. Scroll down again
6. Wait  -- see how MM scrolls you back up

### Error messages or log output

_No response_

### Version

10.23.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by filipsekulic**
## Explanation
* Fixes #16657

### Before

https://user-images.githubusercontent.com/92310504/209935103-28365661-e083-41d3-a722-051417c53691.mov

### After

https://user-images.githubusercontent.com/92310504/209934641-6f42371b-9a46-4d9b-ad78-86249002662e.mov

## Manual Testing Steps
1. Go to the `Test Dapp`
2. Click `CONNECT`

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Review by brad-decker — APPROVED** [review]

File: ui/components/ui/account-list/account-list.js [hunk 1]
```diff
@@ -178,4 +179,6 @@ AccountList.propTypes = {
   handleAccountClick: PropTypes.func.isRequired,
 };
 
-export default AccountList;
+export default memo(AccountList, (prevProps, nextProps) => {
+  return isEqual(prevProps.selectedAccounts, nextProps.selectedAccounts);
+});
```
Comment (jpuri) [inline ui/components/ui/account-list/account-list.js:184]: Do we not need it to re-render if any other prop changes ?

**Comment by knabbed** [comment]
Hi Metamask team! Would it be possible to get another review on this to merge in? It would really help our application. Thank you!

**Review by jpuri — APPROVED** [review]
