### PR TITLE
Remove identities associated to the hardware keyring when forgetting the device

### LINKED ISSUE #21742: [Bug]: Forget this device removes account from keyring, but not the UI
### Describe the bug

When I have a hardware wallet present, and I go thru the add new hardware flow to select `Forget device` the account remains in the drop-down list.  

In the branch I was testing at the time, I found that the accounts cannot be subsequently removed as they no longer exist in the keyring after the device was forgotten.  This has been observed on both Keystone and Ledger within the changes from PR 21437, and likely impacts both Trezor and Lattice.  Was able to confirm that this behavior is present in production 11.4.0 and 11.4.1.

Note that starting with step 11 below, the inability to remove the account is limited to the branch under test.  In 11.4.0 I can still remove an address from the list after I try to forget the device (but should not actually have to).  However, that is not the case in the changes that were being tested and I am unable to remove the addresses.

### Expected behavior

When the user selects `Forget this device` any associated accounts should be removed from the keyring AND no longer displayed in the accounts list.

User should be able to remove any accounts that are not derived from the SRP.

### Screenshots/Recordings

11.4.0: ABLE to remove individual accounts after `Forget this device` fails: https://recordit.co/BV2omOAjFk 

PR 21437 commit 141b1efe6e71e12d03a064d8c2588680a7846dc3: UNABLE to remove individual accounts after `Forget this device` fails:  https://recordit.co/qhg25TCZy9

### Steps to reproduce

1. Have hardware addresses already added in a configured wallet
2. Tap accounts drop down
3. tap `Add account of hardware wallet`
4. tap `Add hardware wallet`
5. Select the hardware wallet you are testing with
6. If Ledger- you may need to tap `Connect` on HID device connection prompt
7. Tap `Continue`
8. Once account list is displayed tap `Forget this device`
9. In the branch under test the address list page will re-appear with a notification that hardware is connected.  If so, go ahead and tap `Forget this device` a second time. 
10. Tap the accounts drop down and note that hardware address that should be forgotten is displayed in the list
11. Hit the kebab next to a given hardware account
12. tap `remove account`
13. Tap `Remove`
14. Note that dialog remains open and account is not removed

### Error messages or log output

```shell
KeyringController - No keyring found. Error info: There are keyrings, but none match the address
```

### Version

11.4.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger, Keystone

### Additional context

Can remove individual addresses as long as the user does not first try to forget the device.

### Severity

Would be incredibly frustrating to land in a spot where accounts cannot be removed that do not exist in the keyring.

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This pr fixes the issue where the identities of a hardware wallet were not removed when removing the device. 

## **Related issues**

Fixes: #21742

## **Manual testing steps**

1. Connect a ledger
2. Add a ledger account
3. Go to connect a ledger again 
4. Click on forget device
5. Check to see the ledger account was removed from the UI

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controllers/preferences.js [hunk 1]
```diff
@@ -118,9 +118,6 @@ export default class PreferencesController {
     this.store.setMaxListeners(13);
     this.tokenListController = opts.tokenListController;
 
-    // subscribe to account removal
-    opts.onAccountRemoved((address) => this.removeAddress(address));
-
```
Comment (gantunesr) [inline app/scripts/controllers/preferences.js:123]: Why is necessary to remove this?

File: app/scripts/metamask-controller.test.js [hunk 2]
```diff
@@ -765,6 +765,56 @@ describe('MetaMaskController', () => {
     });
 
     describe('forgetDevice', () => {
+      let localMetaMaskController;
+
+      beforeEach(async () => {
```
Comment (gantunesr) [inline app/scripts/metamask-controller.test.js:770]: I'm wondering if this setup makes sense having in account the content of the test `should wipe all the keyring info`

**Review by gantunesr — DISMISSED** [review]
LGTM. Just left a couple of comments

Edit: I also tested the branch and the functionality is correct

File: app/scripts/controllers/preferences.js (hunk 1 above)
Comment (montelaidev) [reply app/scripts/controllers/preferences.js:123]: The `_onKeyringControllerUpdate` and `onAccountRemoved` both would be fired when an account is removed. This leads to an error in the background and also causing the test to fail. The issue was brought up here, and would be fixed in this pr as well.

https://consensys.slack.com/archives/GTQAGKY5V/p1699007928401829

File: app/scripts/metamask-controller.test.js (hunk 2 above)
Comment (gantunesr) [reply app/scripts/metamask-controller.test.js]: Maybe we consolidate the setup of both test since they are doing the same thing basically, but it can be in another PR

**Review by gantunesr — APPROVED** [review]

**Comment by plasmacorral** [comment]
Tested on Mac Sonoma 14 in Chrome  117.0.5938.92 with Ledger, Trezor and Keystone.  Also tested Firefox version 118.0.2 with both Keystone and Trezor.  Able to remove accounts, forget devices and re-add the hardware address.  Did not have access to Lattice at the time of testing.

**Review by plasmacorral — APPROVED** [review]
