### PR TITLE
fix: cleanup tokensController state for users with no tokenListContro…

### LINKED ISSUE #33420: [Sentry] Error: Migration 153: TokenListController is type 'undefined', expected object.
Sentry Issue: [METAMASK-XKBF](https://metamask.sentry.io/issues/6619999472/?referrer=github_integration)

```
Error: Migration 153: TokenListController is type 'undefined', expected object.
  at versionedData.data (app/scripts/migrations/153.ts:55:7)
  at r.migrate (app/scripts/migrations/153.ts:26:24)
  at Migrator.migrateData (app/scripts/lib/migrator/index.js:43:46)
  at loadStateFromPersistence (app/scripts/background.js:693:9)
  at initialize (app/scripts/background.js:509:11)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

For users who do not have `tokenListController` state; the migration `153.ts` ran but returned state as is because of the condition `if (!isObject(tokenListControllerState))`

This PR introduces a new migration to cleanup state for those users.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/33439?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33420

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/scripts/migrations/163.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+  return versionedData;
+}
+
+function transformState(
+  state: Record<string, unknown>,
+): Record<string, unknown> {
+  if (!hasProperty(state, 'TokensController')) {
+    global.sentry?.captureException?.(
+      new Error(`Migration ${version}: TokensController not found.`),
```
Comment (Gudahtt) [inline app/scripts/migrations/163.ts]: A missing `TokensController` is expected for some users, for the same reason that a missing `TokenListController` is expected.

This pattern of capturing an exception when data is not found in state is generally not advised. We should capture an exception of we detect _corrupted_ controller state, but not _missing_ state. Missing state is not a bug, it usually just indicates an older installation.

In this case, we can skip the migration if this state is missing.

Comment (sahar-fehri) [reply app/scripts/migrations/163.ts]: Appreciate the clarification 🙏 
I pushed a new update to the migration file where i `console.warn` if `!hasProperty` and return state as it is.
And capture the exception if `!isObject` (Which should indicate a state corruption) and return state.

File: app/scripts/migrations/163.ts [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+        `Migration ${version}: TokensController is type '${typeof tokensControllerState}', expected object.`,
+      ),
+    );
+    return state;
+  }
+
+  // If property TokenListController is not present, only log a warning and return the original state.
+  if (!hasProperty(state, 'TokenListController')) {
+    console.warn(`newState.TokenListController is not present`);
+    return state;
```
Comment (Gudahtt) [inline app/scripts/migrations/163.ts]: I thought the purpose of this migration was to delete the relevant `tokensControllerState` properties for installations where `TokenListController` is missing? If we're bailing here, then this migration seems to serve no purpose

**Comment by Gudahtt** [comment]
Note that the linked issue is that we're erroneously capturing a Sentry error for some users when migration 153 is run. We'll still need to update migration 153 (to downgrade that case from `captureException` to `console.warn`) to fix that issue.

The migration you're adding here makes sense too, I just mean it's not a complete fix until we update migration 153 as well.

File: app/scripts/migrations/163.ts (hunk 2 above)
Comment (Gudahtt) [reply app/scripts/migrations/163.ts]: Assuming I'm on the same page about the purpose of reintroducing this, then I think we could delete the `TokenListController` steps completely

Comment (sahar-fehri) [reply app/scripts/migrations/163.ts]: I think this is where i was confused; My understanding was that for users with old installations and no `tokenListController` state nor `tokensController` state we would want to `console.warn` instead of captureException.
Which is true; but i think my logic does not cover the case where users do not have TokenListController but still have tokensController state; in which case we want to cleanup state.

Comment (sahar-fehri) [reply app/scripts/migrations/163.ts]: Unless i'm misunderstanding something again ^^"; i think when you said
`Assuming I'm on the same page about the purpose of reintroducing this, then I think we could delete the TokenListController steps completely`
You meant
`Assuming I'm on the same page about the purpose of reintroducing this, then I think we could delete the TokensController steps completely`
Since we only care about the case where user does not have `tokenListController` state but still has `tokensController` state;

File: app/scripts/migrations/153.ts [hunk 3]
```diff
@@ -32,9 +32,7 @@ function transformState(
   state: Record<string, unknown>,
 ): Record<string, unknown> {
   if (!hasProperty(state, 'TokensController')) {
-    global.sentry?.captureException?.(
-      new Error(`Migration ${version}: TokensController not found.`),
-    );
+    console.warn(`newState.TokensController is not present`);
```
Comment (sahar-fehri) [inline app/scripts/migrations/153.ts:35]: Even though this was not the cause for the Sentry issue; i think it makes sense to downgrade to console.warn

File: app/scripts/migrations/153.ts [hunk 4]
```diff
@@ -48,6 +46,12 @@ function transformState(
     );
     return state;
   }
+
+  if (!hasProperty(state, 'TokenListController')) {
+    console.warn(`newState.TokenListController is not present`);
+    return state;
+  }
```
Comment (sahar-fehri) [inline app/scripts/migrations/153.ts:53]: Added a check for a missing property and did `console.warn` instead of `captureException`; 

I kept the captureException in the check `if (!isObject(tokenListControllerState))` since if it is not an object it means its corrupted state

File: app/scripts/migrations/163.ts [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+
+    if (hasProperty(tokensControllerState, 'detectedTokens')) {
+      // Remove the detectedTokens property from the TokensController state.
+      delete tokensControllerState.detectedTokens;
+    }
+
+    if (hasProperty(tokensControllerState, 'ignoredTokens')) {
+      // Remove the ignoredTokens property from the TokensController state.
+      delete tokensControllerState.ignoredTokens;
+    }
```
Comment (sahar-fehri) [inline app/scripts/migrations/163.ts]: This should cover the case that was initially reported in the [issue](https://metamask.sentry.io/issues/6619999472/?project=273505&referrer=github_integration) where users does not have `tokenListController` state but has `tokensController` state.

File: app/scripts/migrations/163.ts (hunk 2 above)
Comment (sahar-fehri) [reply app/scripts/migrations/163.ts]: Pushed a new change here [92e093e](https://github.com/MetaMask/metamask-extension/pull/33439/commits/92e093e58c051d196211040b66908b0032e10b95) 🙏

Comment (Gudahtt) [reply app/scripts/migrations/163.ts]: Ah, so what I meant is that we don't need to check for the case "where a user does not have `TokenListController` state". Worst-case, we're redundantly checking for properties that are already deleted, but which is totally fine.

On the other hand, if we restrict migration 163 just to users who ware missing `TokenListController`, then we're missing users who updated to v12.18.x from an old version of the wallet. It would only help users who upgraded from an old version directly to the one with migration 163.

Users who upgraded from "and old version without `TokenListController`" to v12.18.x and then to the version with 163, would never had had a successful run of migration 153, so the extra `TokensController` properties would remain. Then after the v12.18.x update, the `TokenListController` would get initialized as part of wallet initialization.So when they update again to get this migration 163, they'd be erroneously skipped even though they still have these extra `TokensController` properties that we wanted to delete.

Comment (sahar-fehri) [reply app/scripts/migrations/163.ts]: Oh my bad, i missed the fact that even if tokenListController does not exist it would get initialized when users upgrade to v12.18.x.
Alright almost there :p pushed a new update here [76c6bcc](https://github.com/MetaMask/metamask-extension/pull/33439/commits/76c6bcc62731a9223cfdc9464782e92f29538b98) 🙏 ^^

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by Prithpal-Sooriya — APPROVED** [review]
