### PR TITLE
When gas fees suggested by dapp is too high, show warning color and icon

### LINKED ISSUE #17313: [Bug]: No Warning appears when a Dapp sets a really high Fees for a tx, potentially loosing all user funds
### Describe the bug

**Problem**: when a Dapp triggers a transaction/contract interaction, it sets the proposed fees `maxFeePerGas` `maxPriorityFeePerGas` and `gasLimit`. MetaMask takes the values from the Dapp as they are and displayes `Site suggested` meaning that it's the Dapp who suggested the fees. Despite of that, if the Dapp sets a high value, user can loose all its money and there is no warning on MM side. 

image

https://user-images.githubusercontent.com/54408225/213667706-01f68b91-d8e7-4b4b-b5af-2e1c3006dfa9.mp4

### Steps to reproduce

1. Clone test dapp https://github.com/MetaMask/test-dapp
2. Set some high fee values on lines `637` and `638`
```
maxFeePerGas: '0x38D7EA4C68000',
maxPriorityFeePerGas: '0x38D7EA4C68000',
```
3. Start test dapp: `npm start`
4. Go to localhost:9011
5. Connect MM
6. Click Send EIP1559
7. See suggested fees and no warning

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by segun**
## Explanation

When a Dapp triggers a transaction/contract interaction, it sets the proposed fees maxFeePerGas maxPriorityFeePerGas and gasLimit. MetaMask takes the values from the Dapp as they are and displayes Site suggested meaning that it's the Dapp who suggested the fees. Despite of that, if the Dapp sets a high value, user can loose all its money and there is no warning on MM side.

This PR shows a warning icon and colour when dapp suggested fee is higher than aggressive suggested fees.

Fixes: #17313 

test

### After

Screenshot 2023-05-10 at 14 43 12

## Manual Testing Steps

1. Clone test dapp https://github.com/MetaMask/test-dapp
2. Set some high fee values on lines 637 and 638
maxFeePerGas: '0x38D7EA4C68000',
maxPriorityFeePerGas: '0x38D7EA4C68000',
3. Start test dapp: npm start
4. Go to localhost:9011
5. Connect MM
6. Click Send EIP1559
7. See suggested fees with warning colour and icon

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by seaona** [comment]
After reviewing the test and the PR, I've seen that the failure seems legit @segun 

## Issue 1
Notice that now, we do not see anymore the world icon and the `Site suggested` text, but a new text. I think this is not intended to be changed.

image

**Expected**:

image


## Issue 2
Whenever the suggested gas is very low, we should no see the `Max fee` in the warning color but in grey/black, and I believe the Unknown processing time should be in the warning color.

image

**Expected:**
image

@bschorchit could you please confirm the expectations I wrote here / clarify them if not correct.

**Comment by bschorchit** [comment]
Agree with Mariona's comments above ✅

If the "unknown processing time" in green is not a regression from this PR, it can be fixed in a different PR if preferred 😊

**Comment by seaona** [comment]
Changes look good @segun ! Great work!! Ready to merge!

Ps. I will open a separate issue for the `Unknown processing time` to be displayed in warning color.

File: ui/hooks/gasFeeInput/useGasFeeInputs.js [hunk 1]
```diff
@@ -168,6 +171,22 @@ export function useGasFeeInputs(
...
+        .times(new Numeric(transaction?.txParams?.maxFeePerGas ?? '0x0', 16))
+        .toPrefixedHexString();
+
+      console.log('maximumGas: ', maximumGas);
+      const fee = new Numeric(maximumGas, 16, EtherDenomination.WEI)
+        .toDenomination(EtherDenomination.ETH)
+        .toBase(10)
+        .toString();
+
+      console.log('fee: ', fee);
```
Comment (digiwand) [inline ui/hooks/gasFeeInput/useGasFeeInputs.js:185]:
```suggestion
```

File: ui/hooks/gasFeeInput/useGasFeeInputs.js [hunk 2]
```diff
@@ -168,6 +171,22 @@ export function useGasFeeInputs(
         setEstimateUsed(transaction?.userFeeLevel);
         setInternalEstimateToUse(transaction?.userFeeLevel);
       }
+
+      const maximumGas = new Numeric(transaction?.txParams?.gas ?? '0x0', 16)
+        .times(new Numeric(transaction?.txParams?.maxFeePerGas ?? '0x0', 16))
+        .toPrefixedHexString();
+
+      console.log('maximumGas: ', maximumGas);
```
Comment (digiwand) [inline ui/hooks/gasFeeInput/useGasFeeInputs.js:179]:
```suggestion
```

File: app/_locales/en/messages.json [hunk 3]
```diff
@@ -1033,6 +1033,12 @@
     "message": "$1 has suggested this price.",
     "description": "$1 is url for the dapp that has suggested gas settings"
   },
+  "dappSuggestedHigh": {
+    "message": "Site suggested"
+  },
```
Comment (digiwand) [inline app/_locales/en/messages.json:1038]: Q: where is `dappSuggestedHigh` being used? I see `t(title)` exists where `title` can be `dappSuggestedHighShortLabel`, but I'm having trouble finding where `dappSuggestedHigh` is used

**Review by jpuri — DISMISSED** [review]

File: shared/constants/gas.ts [hunk 4]
```diff
@@ -3,6 +3,7 @@ import { addHexPrefix } from 'ethereumjs-util';
 const ONE_HUNDRED_THOUSAND = 100000;
 const MIN_GAS_LIMIT_DEC = '21000';
 
+export const TOO_HIGH_GAS_LIMIT = '1'; // 1 ETH
```
Comment (digiwand) [inline shared/constants/gas.ts:6]: [suggestion]

rather than add the comment, we can include it in the variable name 
```suggestion
export const GAS_LIMIT_TOO_HIGH_IN_ETH = '1';
```
- too high suggests 1 ETH will trigger the warning, but the warning appears after 1 ETH

--- 

have we considered including the variable directly in the file? I wonder what the likelihood is for us reusing this

**Review by digiwand — COMMENTED** [review]
looks good! left some minor suggestions and questions

**Comment by jpuri** [comment]
Changes look good, plz get rid of console logs before merging.

File: shared/constants/gas.ts (hunk 4 above)
Comment (segun) [reply shared/constants/gas.ts:6]: Yeah not sure if we are going to re-use as well.

File: app/_locales/en/messages.json (hunk 3 above)
Comment (segun) [reply app/_locales/en/messages.json:1038]: It's used in ui/hooks/gasFeeInput/useGasFeeInputs.js:187

**Review by jpuri — APPROVED** [review]

**Review by jpuri — DISMISSED** [review]

File: ui/hooks/gasFeeInput/useGasFeeInputs.js [hunk 5]
```diff
@@ -168,6 +172,20 @@ export function useGasFeeInputs(
...
+        .toPrefixedHexString();
+
+      const fee = new Numeric(maximumGas, 16, EtherDenomination.WEI)
+        .toDenomination(EtherDenomination.ETH)
+        .toBase(10)
+        .toString();
+
+      if (Number(fee) > Number(GAS_LIMIT_TOO_HIGH_IN_ETH)) {
+        setEstimateUsed(PriorityLevels.dappSuggestedHigh);
+      }
```
Comment (digiwand) [inline ui/hooks/gasFeeInput/useGasFeeInputs.js:187]: maybe we can reorganize to avoid setting the estimate twice since setEstimateUsed may be called above if `transaction?.userFeeLevel`

File: app/_locales/en/messages.json (hunk 3 above)
Comment (digiwand) [reply app/_locales/en/messages.json:1029]: I'm still a bit confused. Those lines are
```
      if (Number(fee) > Number(GAS_LIMIT_TOO_HIGH_IN_ETH)) {
        setEstimateUsed(PriorityLevels.dappSuggestedHigh);
      } else if (transaction?.userFeeLevel) {
        setEstimateUsed(transaction?.userFeeLevel);
      }
```

I'm not seeing where the translation is used.  

I also see ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js:28-29: 
```
  } else if (priorityLevel === PriorityLevels.dappSuggestedHigh) {
    title = 'dappSuggestedHighShortLabel';
```
mentioned in the first comment which uses `dappSuggestedHighShortLabel` but not `dappSuggestedHigh`. Is there another location you could help point to?

Comment (segun) [reply app/_locales/en/messages.json:1029]: Oh sorry, I see now.

ui/components/app/edit-gas-fee-button/edit-gas-fee-button.js:40
ui/components/app/edit-gas-fee-button/edit-gas-fee-button.js:74

**Review by digiwand — APPROVED** [review]
LGTM!

File: app/_locales/en/messages.json (hunk 3 above)
Comment (digiwand) [reply app/_locales/en/messages.json:1029]: ooh, thank you! 🙏

File: ui/hooks/gasFeeInput/useGasFeeInputs.js [hunk 6]
```diff
@@ -96,6 +98,8 @@ export function useGasFeeInputs(
   minimumGasLimit = '0x5208',
   editGasMode = EditGasModes.modifyInPlace,
 ) {
+  const GAS_LIMIT_TOO_HIGH_IN_ETH = '1';
+
```
Comment (jpuri) [inline ui/hooks/gasFeeInput/useGasFeeInputs.js:102]: const can be outside hook

**Review by jpuri — APPROVED** [review]

File: ui/hooks/gasFeeInput/useGasFeeInputs.js [hunk 7]
```diff
@@ -165,9 +169,24 @@ export function useGasFeeInputs(
...
+        .toDenomination(EtherDenomination.ETH)
+        .toBase(10)
+        .toString();
+
+      if (Number(fee) > Number(GAS_LIMIT_TOO_HIGH_IN_ETH)) {
+        setEstimateUsed(PriorityLevels.dappSuggestedHigh);
+      } else if (transaction?.userFeeLevel) {
+        setEstimateUsed(transaction?.userFeeLevel);
+      }
+
```
Comment (jpuri) [inline ui/hooks/gasFeeInput/useGasFeeInputs.js:189]: Will be nice to test cover above code also.

Comment (segun) [reply ui/hooks/gasFeeInput/useGasFeeInputs.js:189]: I have another issue related to this PR: https://github.com/MetaMask/metamask-extension/issues/19305

I will like to tackle these comments on that issue and close this PR (it's taking too long and I don't think these are blocking requests)
