### PR TITLE
Edit Token Transfer displays mixed info with regular Send Tx (ETH)

### LINKED ISSUE #15362: [Bug]: Edit Token Transfer displays mixed info with regular Send Tx (ETH)
### Describe the bug

**Problem**: when I am performing an ERC20 Token Transfer and I click Edit, I see that ETH is displayed as the default token, with amount 0 on that ERC20 token. Information is mixed up between a Send and a Transfer

https://user-images.githubusercontent.com/54408225/181301057-c8bdd7a5-a210-4156-8e92-d3ad2388c064.mp4

 

### Steps to reproduce

1. Deploy [an ERC20 token](https://remix.ethereum.org/?#code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IE1JVApwcmFnbWEgc29saWRpdHkgXjAuOC40OwoKaW1wb3J0ICJAb3BlbnplcHBlbGluL2NvbnRyYWN0c0A0LjcuMS90b2tlbi9FUkMyMC9FUkMyMC5zb2wiOwoKY29udHJhY3QgTXlUb2tlbiBpcyBFUkMyMCB7CiAgICBjb25zdHJ1Y3RvcigpIEVSQzIwKCJNeVRva2VuIiwgIk1USyIpIHt9Cn0K&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js) on Rinkeby 
2. Click Send tx
3. Click Edit
4. See mixed up info with ERC20 and ETH

### Error messages or log output

_No response_

### Version

10.18.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by segun**
## Explanation

When you start a token transfer from a dapp and click edit, if the token is already added to MM, you will see the token name, but if the token is not added to MM, it will default to showing the native currency. 

This PR addresses this issue

Fixes: #15362

### Before

[](https://user-images.githubusercontent.com/54408225/181301057-c8bdd7a5-a210-4156-8e92-d3ad2388c064.mp4)

### After

[](https://user-images.githubusercontent.com/44811/214638103-c41c8bfa-2c1b-4f31-bd9b-597d2edeadb7.mov)

## Manual Testing Steps

1. On develop branch, launch MM
2. Create a token using Open Zeppelin Wizard and Remix (https://docs.openzeppelin.com/contracts/4.x/wizard)
3. Compile and deploy the token
4. Initiate a transfer
5. Click on edit, you should see the Asset Name is showing Native Token
6. Check out this branch
7. Repeat steps 1-4
8. Click on edit, you should see Asset Name is showing the correct token name

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by NiranjanaBinoy — DISMISSED** [review]
LGTM

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js [hunk 1]
```diff
@@ -150,6 +150,9 @@ export default class SendAssetRow extends Component {
       if (token) {
         return this.renderToken(token);
       }
+
+      // if token is not found in tokens list, render the details
+      return this.renderToken(details);
```
Comment (digiwand) [inline ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:155]: suggestion to reduce lines and remove comment 
```suggestion
      return token ? this.renderToken(token) : this.renderToken(details);
```

**Comment by jpuri** [comment]
Hey @segun , chages look good 👍 
Will be nice to have some test coverage also.

File: ui/pages/send/send-content/send-asset-row/send-asset-row.component.js [hunk 2]
```diff
@@ -150,6 +150,7 @@ export default class SendAssetRow extends Component {
       if (token) {
         return this.renderToken(token);
       }
+      return this.renderToken(details);
```
Comment (jpuri) [inline ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:153]: I am bit confused by code above. Why we can not always use `return this.renderToken(details);`.

Comment (segun) [reply ui/pages/send/send-content/send-asset-row/send-asset-row.component.js:153]: My best guess is when we add tokens to the store, we use API to discover more information about the token that might not be present in details. 

Of course we could remove lines 147:152 and this PR still works fine. I'm just not sure what other parts of the code might break. If we do remove those lines, we need to make sure we do proper regression.

**Review by jpuri — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
