### PR TITLE
fix: Aurora RPC deprecation message

### LINKED ISSUE #23078: [Bug]: Aurora Deprecation Message is Unclear and Annoying
### Describe the bug

I am constantly getting the Aurora deprecation message, added via [this PR](https://github.com/MetaMask/metamask-extension/pull/21933). 

Which is misleading, as there is no planned deprecation of the Aurora network by Metamask in the foreseeable future.
It also ruins the user experience and makes people worry about using Aurora products with Metamask.

### Expected behavior

I have a few suggestions about how to fix it:

1. The message inside the popup is misleading. It says, "Aurora network will be deprecated," which simply is not true. In PR devs are just saying about the removal from Popular Network List. So, let's change it to something else, like "Aurora Chain has been removed from the Popular Network List".

2. The second part of the message says, "Please add it as a custom network". But if I add it as custom network - I still see the message. How can I get rid of this then? 

3. It is also not clear how to add a Custom Network from that popup. In "Learn More" you just have a redirect to the aurora.dev site. I propose to change it to either https://aurora.dev/start or even better - https://support.metamask.io/hc/en-us/articles/360058992772-Add-a-network-using-Chainlist 

4. Allow the user not to see that message if he has closed it or has done the action you've asked him for.

### Screenshots/Recordings

It looks like this:
Screenshot 2024-02-20 at 15 23 02

### Steps to reproduce

1. Make sure you have added Aurora Mainnet (https://aurora.dev/start) and Ethereum Mainnet networks.
2. Switch to Ethereum Network.
3. Switch to Aurora Network.
4. See popup at the bottom of the screen.

### Error messages or log output

_No response_

### Version

11.9.5

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

- It is a mid-severe bug for the Aurora Users and impacts the whole ecosystem

### PR DESCRIPTION
**Pull request by bergeron**
## **Description**

Fixes the Aurora deprecation message.  It was suggesting MM no longer supports Aurora, which is not true.  It's just no longer a built-in network due to Infura no longer supporting it.

Instead, we show a warning to users who previous added it when it was a built-in network.  And give them a 1 click migration from Infura to the `mainnet.aurora.dev` RPC endpoint.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24534?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23078

## **Manual testing steps**

1. Add the Aurora network via https://chainid.network
2. Verify no deprecation warnings

The RPC migration modal is harder to test.  You'd need to have added the network on MM <= 11.6 back when the Infura RPC url was alive.  

### **Before**

Screenshot 2024-05-14 at 10 07 12 PM

### **After**

Simulating a user who previously added the Infura RPC:

https://github.com/MetaMask/metamask-extension/assets/3500406/6df7591d-284f-47bc-88a3-362174bf141f

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/ui/deprecated-networks/deprecated-networks.js [hunk 1]
```diff
@@ -1,38 +1,78 @@
...
+                imageUrl: NEAR_AURORA_MAINNET_IMAGE_URL,
+                blockExplorerUrl: 'https://aurorascan.dev',
+              },
+            },
+            { source: MetaMetricsNetworkEventSource.DeprecatedNetworkModal },
+          ),
+        );
+      },
+    };
+  }
```
Comment (salimtb) [inline ui/components/ui/deprecated-networks/deprecated-networks.js:73]: Great work !. to ensure robustness and catch any potential issues early, I recommend adding unit tests covering various if/else scenarios.

**Comment by salimtb** [comment]
linter and unit tests should be fixed as well

File: ui/components/ui/deprecated-networks/deprecated-networks.js (hunk 1 above)
Comment (bergeron) [reply ui/components/ui/deprecated-networks/deprecated-networks.js:79]: I added a storybook for aurora

Screenshot 2024-05-15 at 5 06 21 PM

**Comment by bergeron** [comment]
Not sure about those lavamoat errors

File: ui/components/ui/deprecated-networks/deprecated-networks.js [hunk 2]
```diff
@@ -1,38 +1,84 @@
...
+      actionButtonProps: {
+        href: 'https://github.com/eth-clients/goerli#goerli-goerlitzer-testnet',
+        externalLink: true,
+      },
+    };
+  } else if (DEPRECATED_NETWORKS.includes(chainId)) {
+    props = { description: t('deprecatedNetwork') };
+  } else if (
+    chainId === CHAIN_IDS.AURORA &&
+    rpcUrl.startsWith('https://aurora-mainnet.infura.io/')
```
Comment (sahar-fehri) [inline ui/components/ui/deprecated-networks/deprecated-networks.js:54]: What if a user added aurora with an RPC that is !== 'https://mainnet.aurora.dev' && !== https://aurora-mainnet.infura.io/ ?

Comment (bergeron) [reply ui/components/ui/deprecated-networks/deprecated-networks.js:54]: I don't think there's anything to warn about in that case.   Anything you're worried about?  Just targeting users who added the built-in Infura endpoint, since it would no longer work.

**Review by sahar-fehri — APPROVED** [review]

**Review by salimtb — APPROVED** [review]
