### PR TITLE
Optimism Bedrock Fix + New Gas Displays

### LINKED ISSUE #19561: [Bug]: Optimism Bedrock upgrade - issues with gas display for new EIP1559 transactions
### Describe the bug

**Problem**: the Optimism Bedrock upgrade, which adds support to EIP1559, happened on June 6th.
Now, we see some issues with the current gas displays

- whenever we send a transaction Optimism network we often display  `0` on any the suggested gas fees options. This seems to be a rounding issue - fees are so low in the L2 that we end up displaying a `0` for all the options

@bschorchit should we add decimals precision, so we actually display different values on each option?

image

- we do not display a break down of L1 and L2 fees, like we do for Legacy tx's (see below pic). What should be the expected behavior here?

Screenshot from 2023-06-11 10-56-50

### Steps to reproduce

1. Select Optimism network
2. Send EIP1559
3. Click Edit fees
4. See recommended fees are 0

### Error messages or log output

_No response_

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by segun**
### This PR has lots of changes, but most of them are i18n messages and fixes to existing e2e and unit tests. So it's not all that daunting. Thanks for the review ;) 

**Problem**: the Optimism Bedrock upgrade, which adds support to EIP1559, happened on June 6th.
Now, we see some issues with the current gas displays

- whenever we send a transaction Optimism network we often display  `0` on any the suggested gas fees options. This seems to be a rounding issue - fees are so low in the L2 that we end up displaying a `0` for all the options

The bug in code is that we always try to display the values in ETH, But the Optimism fees are sent from the backend in GWEI, the fix is to check if the ETH conversion is zero and then use GWEI conversion, if that is also zero, we then use WEI conversion.

- See: #19561 for more information and design considerations.
- Fixes: #19561

### Before

image

### After

Screenshot 2023-07-11 at 12 37 55

Screenshot 2023-07-11 at 12 38 13

Screenshot 2023-07-11 at 12 38 05

## Manual Testing Steps

1. Select Optimism network
2. Send EIP1559
3. Click Edit fees
4. See recommended fees are 0

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/hooks/useCurrencyDisplay.js [hunk 1]
```diff
@@ -53,18 +53,26 @@ export function useCurrencyDisplay(
   const isUserPreferredCurrency = currency === currentCurrency;
 
   const value = useMemo(() => {
+    let ethDisplayValue;
+    console.log('Using display value: ', displayValue);
```
Comment (darkwing) [inline ui/hooks/useCurrencyDisplay.js:57]: Console needs removal

File: ui/components/app/edit-gas-fee-icon/edit-gas-fee-icon.js [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+  };
+
+  return (
+    <button onClick={openEditGasFeeModal} data-testid="edit-gas-fee-icon">
+      <Icon
+        name={IconName.Edit}
+        color={Color.primaryDefault}
+        size={IconSize.Xs}
+      />
+    </button>
```
Comment (georgewrmarshall) [inline ui/components/app/edit-gas-fee-icon/edit-gas-fee-icon.js:36]: You could use a `ButtonIcon` here instead https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-buttonicon--docs

File: ui/components/app/edit-gas-fee-icon/edit-gas-fee-icon.js [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+  );
+}
+
+EditGasFeeIcon.propTypes = {
+  userAcknowledgedGasMissing: PropTypes.bool,
+};
```
Comment (georgewrmarshall) [inline ui/components/app/edit-gas-fee-icon/edit-gas-fee-icon.js:42]: We should ensure all new components have a story so we can edit them in isolation 

https://metamask.github.io/metamask-storybook/?path=/docs/getting-started-documentation-guidelines--docs#creating-a-story

File: ui/components/app/edit-gas-fee-icon/index.scss [hunk 4]
```diff
@@ -0,0 +1,3 @@
+button {
+  background: transparent;
+}
```
Comment (georgewrmarshall) [inline ui/components/app/edit-gas-fee-icon/index.scss:3]: Shouldn't need this if you are using `ButtonIcon`

File: ui/components/app/gas-details-item/gas-details-item-title/gas-details-item-title.js [hunk 5]
```diff
@@ -1,47 +1,13 @@
...
-                rel="noopener noreferrer"
-              >
-                {t('transactionDetailGasTooltipConversion')}
-              </a>
-            </Text>
-          </>
-        }
-        position="bottom"
-      />
+      <Box marginRight={1}>{t('estimatedFee')}</Box>
```
Comment (georgewrmarshall) [inline ui/components/app/gas-details-item/gas-details-item-title/gas-details-item-title.js:10]: Doesn't this still need to be a component if it's one line of text?

File: ui/components/app/gas-details-item/gas-details-item-title/index.scss [hunk 6]
```diff
@@ -6,4 +6,11 @@
     color: var(--color-text-muted);
     line-height: inherit;
   }
+
+  &__estimate-used {
+    font-weight: 400;
+    font-size: 12px;
```
Comment (georgewrmarshall) [inline ui/components/app/gas-details-item/gas-details-item-title/index.scss:12]: We should try to avoid using static CSS here in favour of the `Text` component https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-text--docs

File: ui/components/app/gas-timing/gas-timing.component.js [hunk 7]
```diff
@@ -3,6 +3,7 @@ import { useSelector } from 'react-redux';
 import PropTypes from 'prop-types';
 import classNames from 'classnames';
 import BigNumber from 'bignumber.js';
+import Box from '../../ui/box';
```
Comment (georgewrmarshall) [inline ui/components/app/gas-timing/gas-timing.component.js:6]: This component has been deprecated. Please use the component-library version. You should be able to identify deprecated components as they will show with a strike through. Let me know if you don't see this in VS Code and we can compare settings. Mine was turned off for the longest time 😅 

Screenshot 2023-07-24 at 1 08 34 PM

```suggestion
import { Box } from '../../component-library';
```

File: ui/components/app/gas-timing/index.scss [hunk 8]
```diff
@@ -1,18 +1,26 @@
 .typography.gas-timing {
   color: var(--color-text-alternative);
 
+  &__text {
+    font-size: 12px;
+    line-height: 16px;
+    letter-spacing: 0.4px;
+    color: var(--color-text-alternative);
```
Comment (georgewrmarshall) [inline ui/components/app/gas-timing/index.scss:8]: Intead of CSS can we use the `Text` component here?

File: ui/components/app/confirm-page-container/confirm-page-container-content/index.scss [hunk 9]
```diff
@@ -12,13 +12,32 @@
...
+      display: flex;
+      align-items: center;
+      justify-content: centers;
+      color: var(--color-primary-default);
+      background: transparent;
+      border: 0;
+      padding-inline-end: 0;
+      white-space: pre;
+    }
+  }
```
Comment (georgewrmarshall) [inline ui/components/app/confirm-page-container/confirm-page-container-content/index.scss:33]: You may be able to use `component-library` components instead of this CSS

**Review by georgewrmarshall — COMMENTED** [review]
Hey @segun, Great start! I've left a few suggestions regarding UI and using the component library components instead of writing more CSS

File: test/e2e/tests/address-book.spec.js [hunk 10]
```diff
@@ -57,6 +57,15 @@ describe('Address Book', function () {
...
 
+        await driver.clickElement({ text: 'Edit', tag: 'button' });
+
+        const [gasLimitInput, gasPriceInput] = await driver.findElements(
+          'input[type="number"]',
+        );
+        await gasPriceInput.fill('8');
+        await gasLimitInput.fill('100000');
+        await driver.clickElement({ text: 'Save', tag: 'button' });
+
```
Comment (jpuri) [inline test/e2e/tests/address-book.spec.js:68]: Not sure why is this step required for adding contact to address book.

Comment (segun) [reply test/e2e/tests/address-book.spec.js:68]: This step was not adding to address book, it's sending to an address book entry. The problem with the e2e was that the Confirm button was not enabled because of invalid gas values.
What these steps do is click Edit which opens the EditGasModal, add the correct values for price and limit and then Save, then the Confirm button is enabled and the tx can be sent.

**Review by jpuri — DISMISSED** [review]
@segun : changes look good to me. A QA will be useful before merging.

File: ui/components/app/edit-gas-fee-icon/edit-gas-fee-icon.js [hunk 11]
```diff
@@ -0,0 +1,41 @@
...
+import { useTransactionModalContext } from '../../../contexts/transaction-modal';
+import { ButtonIcon, ButtonIconSize, IconName } from '../../component-library';
+
+export default function EditGasFeeIcon({ userAcknowledgedGasMissing }) {
+  const { hasSimulationError, estimateUsed, supportsEIP1559 } =
+    useGasFeeContext();
+  const { updateTransactionEventFragment } = useTransactionEventFragment();
+  const { openModal } = useTransactionModalContext();
+  const editEnabled =
+    !hasSimulationError || userAcknowledgedGasMissing === true;
```
Comment (DDDDDanica) [inline ui/components/app/edit-gas-fee-icon/edit-gas-fee-icon.js:15]:
```suggestion
  const editEnabled =
    !hasSimulationError || userAcknowledgedGasMissing;
```

File: ui/components/app/gas-details-item/gas-details-item.js [hunk 12]
```diff
@@ -64,20 +87,29 @@ const GasDetailsItem = ({
...
   ).toString();
 
+  const getTransactionFeeTotal = () => {
+    if (isMultiLayerFeeNetwork) {
+      return sumHexes(hexMaximumTransactionFee, estimatedL1Fees || 0);
+    }
+
+    return hexMaximumTransactionFee;
+  };
+
```
Comment (DDDDDanica) [inline ui/components/app/gas-details-item/gas-details-item.js:97]: We can use `useMemo` to avoid performing expensive calculations
```suggestion
  const getTransactionFeeTotal = useMemo(() => {
    if (isMultiLayerFeeNetwork) {
      return sumHexes(hexMaximumTransactionFee, estimatedL1Fees || 0);
    }

    return hexMaximumTransactionFee;
}, [isMultiLayerFeeNetwork, hexMaximumTransactionFee, estimatedL1Fees]);
```

File: test/e2e/tests/send-eth.spec.js [hunk 13]
```diff
@@ -375,13 +378,21 @@ describe('Send ETH from dapp using advanced gas controls', function () {
...
+          xpath: "//div[contains(text(), 'Base fee')]",
+        });
+
+        const allFeeValues = await driver.findElements(
+          '.currency-display-component__text',
         );
-        assert.equal(await baseFeeValue.getText(), '0.000000025');
+
+        // In my tests, I've some of these values change between e2e runs.
+        // I think it might be better to just check if it's there and numeric
```
Comment (DDDDDanica) [inline test/e2e/tests/send-eth.spec.js:390]: Hey @segun this looks very comprehensive. 
However, can we modify the comment here a bit more formal? or you can just make a comment in this MR to explain what's the reason behind the check.

**Comment by seaona** [comment]
Some findings from QA below:

## 1. Send ERC20 or ERC721 and MetaMask Fees
Whenever I am transferring a token, I can see how MetaMask fees has a value of the token transfer + ETH fee. Shouldn't we expect 0?

Screenshot from 2023-08-18 11-20-00

Screenshot from 2023-08-18 11-27-40


## 2. Approve ERC20 and ERC721, SetApprovalForAll and Revoke
In the Approve ERC20 and ERC721, setApprovalForAll and Revoke screens I can see:
- the icon of the gas option and the name is displayed over the edit button. Clicking on it also opens the Edit Gas window. Is this expected?
- I cannot see a breakdown of the fees like in other screens

Screenshot from 2023-08-18 11-21-27

Screenshot from 2023-08-18 11-25-55

Screenshot from 2023-08-18 11-26-37

## 3. Fees with disabled conversion on test networks
MetaMask fees display doubed numbers i.e. `0 0` on test networks (i.e. Sepolia, Linea etc) whenever we have the Show conversion on test network Settings option disabled 

Screenshot from 2023-08-18 10-34-08

Maybe it's an old issue?

## 4. Edit Transaction displays incorrect Option fee
Whenever we edit the transaction fee (i.e. we set the `Slow` option) and then go back to Edit transaction, we can see how the gas values are correct but the option fee displays `Market` instead of the new selected option `Slow`

https://github.com/MetaMask/metamask-extension/assets/54408225/fead977d-20d8-4f70-aa4b-34cbdad80e1c

## 5. Speed up / Cancel transaction
Is it expected that we display the icon and gas option over the edit gas in the Speed up and Cancel transaction popover? cc @bschorchit 

Screenshot from 2023-08-18 11-12-59

Screenshot from 2023-08-18 11-14-47

**Comment by bschorchit** [comment]
> 1. Send ERC20 or ERC721 and MetaMask Fees
> Whenever I am transferring a token, I can see how MetaMask fees has a value of the token transfer + ETH fee. Shouldn't we expect 0?

MetaMask fee should be 0 and there should be a second line with the value of gas only (token transfer value should not show up there).

Screenshot 2023-08-18 at 09 39 55

File: test/e2e/tests/send-eth.spec.js (hunk 13 above)
Comment (segun) [reply test/e2e/tests/send-eth.spec.js:390]: Sure. Thanks

File: test/e2e/tests/send-eth.spec.js [hunk 14]
```diff
@@ -375,13 +378,21 @@ describe('Send ETH from dapp using advanced gas controls', function () {
...
+        assert.equal(allFeeValues.length, 6);
```
Comment (segun) [inline test/e2e/tests/send-eth.spec.js:391]:
```
Below lines check that fee values are numeric.

The reason is that in my tests, I've seen some of these values change between e2e runs.
I think it might be better to just check if it's there and numeric
```

**Comment by seaona** [comment]
## 1. Cannot Edit Fees on any EIP1559 tx
Whenever I send any EIP1559 tx (Send, Approve, etc) I don't see the Edit fee icon anymore, so I cannot Edit the fees

https://github.com/MetaMask/metamask-extension/assets/54408225/9f8f1369-0df6-4ace-b0fc-58a37e6cc659

## 2. Custom Nonce Margin
I can see how the Custom Nonce section has lost the margin and is colliding with the borders

Screenshot from 2023-09-05 10-04-02

## 3. Legacy tx Gas Section
I can see there is no `Fee details` section and no `MetaMask Gas fees` displayed on Legacy transactions. Is this expected?

Screenshot from 2023-09-05 10-08-20

## 4. Approve ERC20 Fee details section with Nonce
On the ERC20 Approve, if we have enabled the Customize Nonce, we can see how the Fee details section is under the Nonce section, instead of the Estimated fee. Is this expected?

Screenshot from 2023-09-05 10-17-46

Screenshot from 2023-09-05 10-18-03

## 5. Approve/Revoke/SetApprovalForAll ERC721 Fee details duplicated
The Fee Details section is duplicated in the Approve/Revoke/SetApprovalForAll ERC721 screen

Screenshot from 2023-09-05 10-21-52

Screenshot from 2023-09-05 10-22-28


I recommend another round of testing once this is fixed, specially issue # 1 , as I've not been able to fully test all flows since I cannot Edit Fees on EIP1559 txs

File: ui/components/app/fee-details-component/fee-details-component.js [hunk 15]
```diff
@@ -0,0 +1,180 @@
...
+        <LoadingHeartBeat estimateUsed={txData?.userFeeLevel} />
+        <UserPreferencedCurrencyDisplay
+          type={PRIMARY}
+          key="total-detail-value"
+          value={value}
+          hideLabel={!useNativeCurrencyAsPrimaryCurrency}
+        />
+      </div>
+    );
+  };
```
Comment (jpuri) [inline ui/components/app/fee-details-component/fee-details-component.js:94]: I am not sure if its best to use functions to return JSX, even if we prefer function I think useCallback will help.

**Review by jpuri — COMMENTED** [review]
Changes largely look good, I added some small comments.

I would suggest thorough dev testing before merging.

**Review by jpuri — DISMISSED** [review]

File: ui/pages/token-allowance/token-allowance.js [hunk 16]
```diff
@@ -263,13 +264,13 @@ export default function TokenAllowance({
...
-  const handleNextNonce = () => {
+  const handleNextNonce = useCallback(() => {
     dispatch(getNextNonce());
-  };
+  }, [getNextNonce, dispatch]);
 
   useEffect(() => {
     handleNextNonce();
-  }, [dispatch]);
+  }, [handleNextNonce]);
```
[the remark this answers is not in the document]
Comment (segun) [reply ui/pages/token-allowance/token-allowance.js]: handleNextNonce is used somewhere else. But we also want to getNextNonce once the page loads. I remember there was an issue with nonce that necessitated this change.

I've however changed the useEffect to call getNextNonce instead of handleNextNonce

**Comment by seaona** [comment]
Here QA summary:
- **Issue 1 - Cannot Edit Fees**: after checking with @segun , we've seen that we are able to Edit the gas fees, and it seemed a caching issue with the previous build.
However, I've tried now an Approve ERC20 / ERC721 on Optimism and I can see that the Edit fees icon is not there, so I'm not able to edit the fees in that screen with Optimism network. It does work with mainnet.

**Repro**:
- Go to this contract https://optimistic.etherscan.io/token/0x0b2c639c533813f4aa9d7837caf62653d097ff85#writeProxyContract
- Connect MetaMask
- Click Approve
- Add any address and amount
- See MM popup and cannot edit fees

https://github.com/MetaMask/metamask-extension/assets/54408225/46422ac0-81e9-43a8-957f-0540ed6b5b91

Screenshot from 2023-09-08 12-27-44

- **Issue 2 - Custom Nonce Margin**: I see this issue fixed
- **Issue 3 - Legacy tx Gas Section**: after discussion with @bschorchit , this has been left outside the scope of this PR. Do we need to create a separate ticket for that task?
- **Issue 4 -  Approve ERC20 Fee details section with Nonce**: I see this issue fixed
- **Issue 5 - Approve/Revoke/SetApprovalForAll ERC721 Fee details duplicated**:  I see this issue fixed

**Comment by jpuri** [comment]
QA feedback point 1,3 still need to be addresses and also we need to address design team feedbacks.

**Comment by seaona** [comment]
- 🔴 **Issue 1 - Cannot Edit Fees:** I am still not able to Edit fees on Optimism, now not only on Approve but also in token Transfers triggered from a dapp. Not sure if it's just me :thinking: 

Screenshot from 2023-09-25 12-29-46

Screenshot from 2023-09-25 12-27-57

- ❓ **Issue 3 - Legacy tx Gas Section:** Do we need to create a separate ticket for that? @bschorchit 

- ❓  **Issue 6** - I've noticed that on tx triggered from a dapp, we display both Layer 1 and Optimism fees, but not on Sends from inside the wallet. Is this expected? @bschorchit 

Screenshot from 2023-09-25 12-30-45

I don't want to block the PR, and maybe some of these could be fixed separately, though number 1 I think we should try to fix it in this PR if confirmed it's not only me.

**Comment by bschorchit** [comment]
> ❓ Issue 3 - Legacy tx Gas Section: Do we need to create a separate ticket for that? @bschorchit 

yes, please 🙏

**Comment by bschorchit** [comment]
> ❓ Issue 6 - I've noticed that on tx triggered from a dapp, we display both Layer 1 and Optimism fees, but not on Sends from inside the wallet. Is this expected? @bschorchit

Layer 1 fees should be displayed on send transactions as well

**Comment by bschorchit** [comment]
> I don't want to block the PR, and maybe some of these could be fixed separately, though number 1 I think we should try to fix it in this PR if confirmed it's not only me.

agree with this suggestion. Fix 1 as part of this PR and create separate issues for the other items.

**Comment by seaona** [comment]
- 🔴 **Issue 1 - Cannot Edit Fees**: I am still not able to Edit fees on Optimism, now not only on Approve but also in token Transfers triggered from a dapp.
- ✅  **Issue 3: Legacy tx Gas Section**: separated issue created here  https://github.com/MetaMask/metamask-extension/issues/21140
- ✅  **Issue 6: L1 fees on tx from inside wallet**: separated issue created here https://github.com/MetaMask/metamask-extension/issues/21139

**Comment by seaona** [comment]
- 🔴 **Issue 1 - Cannot Edit Fees**: I am still not able to Edit fees on Optimism, on an Approve, Transfer ..
Could you try with this contract @segun ?

https://optimistic.etherscan.io/token/0x0b2c639c533813f4aa9d7837caf62653d097ff85#writeProxyContractle to Edit fees in Optimism. 

Screenshot from 2023-10-10 11-55-11


- :red_circle:  **Issue 7: Fee details under Estimated fee** - in SetApprovalForAll, Revoke screens, the `Fee details` title should come right after Estimated fee section, and not after `View full transaction details ` title . Whenever we open the x2 details, then the transaction details come below fee details (having the title above fee details) cc @bschorchit @SayaGT 


image

Screenshot from 2023-10-10 11-43-44

- :red_circle:  **Issue 8: Send ERC721 token not displayed on Total** - whenever we are Sending an ERC721 token, we can see how the token is not included in the `Total` field, whereas before it was.

Now:
Screenshot from 2023-10-10 11-46-57

Before:
Screenshot from 2023-10-10 11-48-05

**Comment by segun** [comment]
@seaona for Issue 8, I had a discussion with @bschorchit and it was decided that the fee details should only show fees. So we decided to add another card below the fees that shows fees + what you're sending 

See attached picture

Screenshot 2023-10-10 at 18 56 02

**Comment by seaona** [comment]
:green_circle:  **Issue 1 - Cannot Edit Fees**: I see the issue fixed now 
:green_circle:  **Issue 7: Fee details under Estimated fee** - I see the issue fixed now
:green_circle:  **Issue 8: Send ERC721 token not displayed on Total** - I see the issue fixed now, according to the last decision you mentioned above

File: test/e2e/tests/address-book.spec.js [hunk 17]
```diff
@@ -63,6 +63,15 @@ describe('Address Book', function () {
...
         await driver.clickElement({ text: 'Next', tag: 'button' });
 
+        await driver.clickElement({ text: 'Edit', tag: 'button' });
+
+        const [gasLimitInput, gasPriceInput] = await driver.findElements(
+          'input[type="number"]',
+        );
+        await gasPriceInput.fill('8');
+        await gasLimitInput.fill('100000');
+        await driver.clickElement({ text: 'Save', tag: 'button' });
```
Comment (cryptotavares) [inline test/e2e/tests/address-book.spec.js:73]: Why is this needed? Can we not send from address book without editing gas? If much this should be a test case in the send spec, no? `Edit gas price and limit before sending`

File: test/e2e/tests/send-edit.spec.js [hunk 18]
```diff
@@ -54,12 +54,12 @@ describe('Editing Confirm Transaction', function () {
...
         // has correct updated value on the confirm screen the transaction
         await driver.waitForSelector({
-          css: '.transaction-detail-item:nth-of-type(1) h6:nth-of-type(2)',
-          text: '0.0008 ETH',
+          css: '.currency-display-component__text',
+          text: '0.0008',
         });
         await driver.waitForSelector({
-          css: '.transaction-detail-item:nth-of-type(2) h6:nth-of-type(2)',
-          text: '2.2008 ETH',
```
Comment (cryptotavares) [inline test/e2e/tests/send-edit.spec.js:62]: it seems that before we were also checking the total amount.. Is there a reason to have dropped this check?

File: test/e2e/tests/send-edit.spec.js [hunk 19]
```diff
@@ -144,12 +146,12 @@ describe('Editing Confirm Transaction', function () {
...
```
Comment (cryptotavares) [inline test/e2e/tests/send-edit.spec.js:152]: Same as above

File: test/e2e/tests/send-eth.spec.js [hunk 20]
```diff
@@ -341,13 +342,15 @@ describe('Send ETH from dapp using advanced gas controls', function () {
         await priorityFeeInput.fill('1');
 
         await driver.clickElement({ text: 'Save', tag: 'button' });
+
         await driver.waitForSelector({
-          css: '.transaction-detail-item:nth-of-type(1) h6:nth-of-type(2)',
-          text: '0.04503836 ETH',
+          css: '.currency-display-component__text',
+          text: '0.05684869',
```
Comment (cryptotavares) [inline test/e2e/tests/send-eth.spec.js:348]: Is there a reason for the different amount?

File: ui/components/app/fee-details-component/fee-details-component.js [hunk 21]
```diff
@@ -0,0 +1,186 @@
...
+            value={value}
+            hideLabel={Boolean(useNativeCurrencyAsPrimaryCurrency)}
+          />
+        </div>
+      );
+    },
+    [txData, useNativeCurrencyAsPrimaryCurrency],
+  );
+
+  const renderTotalDetailTotal = useCallback(
```
Comment (cryptotavares) [inline ui/components/app/fee-details-component/fee-details-component.js:85]: Can we get a better name for this? It is hard to grasp what `TotalDetailTotal` means..

File: ui/components/multichain/pages/send/send.test.js [hunk 22]
```diff
@@ -35,10 +35,8 @@ const render = (props = {}) => {
 describe('SendPage', () => {
   describe('render', () => {
     it('renders correctly', () => {
-      const { container, getByTestId } = render();
+      const { container } = render();
       expect(container).toMatchSnapshot();
-
-      expect(getByTestId('send-page-network-picker')).toBeInTheDocument();
```
Comment (cryptotavares) [inline ui/components/multichain/pages/send/send.test.js:41]: Why are we removing this expectation?

File: ui/pages/confirm-transaction-base/confirm-transaction-base.test.js [hunk 23]
```diff
@@ -409,6 +409,10 @@ describe('Confirm Transaction Base', () => {
         gasFeeIsCustom: true,
       },
     };
+
+    mockedStore.metamask.providerConfig.chainId = CHAIN_IDS.GOERLI;
+    mockedStore.confirmTransaction.txData.chainId = CHAIN_IDS.GOERLI;
+
```
Comment (cryptotavares) [inline ui/pages/confirm-transaction-base/confirm-transaction-base.test.js:415]: Why are we setting this to Goerli for unit tests?

Comment (segun) [reply ui/pages/confirm-transaction-base/confirm-transaction-base.test.js:415]: Not sure, I've removed the changes in this pass and the tests still passed.

Although generally, the tests in thile use GOERLI (lines 106-110)

File: ui/components/multichain/pages/send/send.test.js (hunk 22 above)
Comment (segun) [reply ui/components/multichain/pages/send/send.test.js:41]: added this back and the tests are passing too. :(

File: test/e2e/tests/send-eth.spec.js (hunk 20 above)
Comment (segun) [reply test/e2e/tests/send-eth.spec.js:348]: Not sure, but tests are not passing with old value

File: test/e2e/tests/send-edit.spec.js (hunk 18 above)
Comment (segun) [reply test/e2e/tests/send-edit.spec.js:62]: Had a chat with @bschorchit and right now we want the fee details just shows the fees, not the fees + amount.

File: test/e2e/tests/send-edit.spec.js (hunk 19 above)
Comment (segun) [reply test/e2e/tests/send-edit.spec.js:152]: Had a chat with @bschorchit and right now we want the fee details just shows the fees, not the fees + amount.

File: test/e2e/tests/address-book.spec.js (hunk 17 above)
Comment (segun) [reply test/e2e/tests/address-book.spec.js:73]: Yes we can, but I've noticed instances in the CI when this fails. I am not able to replicate these failures locally, but @seaona helped me troubleshoot CI and we found out that in the cases when this fails, the confirm button below is not enabled because the fee is too small. 

So the tests passed locally but intermittently fail on CI. But with this fix it passes everytime on CI.

File: ui/components/app/fee-details-component/fee-details-component.js (hunk 21 above)
Comment (segun) [reply ui/components/app/fee-details-component/fee-details-component.js:85]: sure

**Review by cryptotavares — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]
