### PR TITLE
Completes onboarding upon importing seed phrase

### LINKED ISSUE #8679: develop: Importing seed phrase can force user into backup mode
Reproduction steps:
1. Install fresh copy of MetaMask off `develop`
2. Select the import option
3. Paste in a seed phrase
4. On the "congratulations!" page, close the window.
5. Click the fox

Expected result:
- User should be redirected to their account.

Actual result:
- User is shown the seed phrase backup screen. The user may then click "Skip for now" and be nagged to back-up the phrase again even though it was already backed up.

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/8679

In the case we assume that the imported phrase is already backed up, onboarding should be completed so users can continue after closing out the "Congratulations!" page.

cc: @danfinlay

### CODE REVIEW

File: ui/app/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js [hunk 1]
```diff
@@ -132,6 +133,7 @@ export default class ImportWithSeedPhrase extends PureComponent {
       })
 
       setSeedPhraseBackedUp(true).then(() => {
+        completeOnboarding()
```
Comment (ryanml) [inline ui/app/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js:136]: This function is marked as `async` but I don't think there's any particular benefit to doing `await completeOnboarding()` here - I can update if it's semantically preferred.

Comment (Gudahtt) [reply ui/app/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js:136]: `await`-ing the call ensures any error is handled and shown to the user. Though admittedly this is not a great error handling pattern - such an error wouldn't exactly be relevant to users.

`await` would also give us an async stack trace if an error was thrown, ensuring we knew the `completeOnboarding` callsite. Async stack traces are supported by Chromium when using `Promise.all` or `async/await`, but not for `.then/.catch`.

I slightly prefer using `await` here, but it's not a big deal either way.

**Review by Gudahtt — COMMENTED** [review]
I noticed that `completeOnboarding` is still being called on the final page, so it's now called twice redundantly. It is still needed there for the "Create wallet" flow though I suppose, and calling `completeOnboarding` twice doesn't seem particularly harmful.

It would be nice to make this same change on the "Create wallet" flow though. Then this bug would be fixed for that flow as well, and we could remove the redundant `completeOnboarding` call.

File: ui/app/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js (hunk 1 above)
Comment (ryanml) [reply ui/app/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js]: Updated to use `await` 👍

**Comment by ryanml** [comment]
@Gudahtt - this is now done for the Create Account flow, and the now redundant call has been removed.

**Review by Gudahtt — APPROVED** [review]
LGTM, thanks!
