### PR TITLE
Align custom spending cap Max button in approve screen for multiple languages

### LINKED ISSUE #16770: [Bug]: Misaligned custom spending cap `Max` button in the approve screen (popup view)
### Describe the bug

The max button is not aligned in the custom spending cap input on the popup view when the language is switched to French

approve popup view

### Steps to reproduce

1. Change the language of MM wallet to French
2. Navigate to the [test dapp](https://metamask.github.io/test-dapp)
3. Connect your wallet
4. Deploy the erc20 token
5. Click Approve Token
6. View the popup

### Error messages or log output

_No response_

### Version

10.23.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by VSaric**
## Explanation

The max button is `aligned` in the custom spending cap input on the popup view and expand view when the language is switched to French, Spanish, German, Russian etc.

* Fixes #16770 

### Before

https://user-images.githubusercontent.com/92527393/207266270-c172bd77-69c9-4840-b912-81ff1a9eafbc.mov

### After

https://user-images.githubusercontent.com/92527393/207263608-c17fbc39-de0f-46b2-b33d-b87e714288d9.mov

## Manual Testing Steps

1. Change the language of MM wallet to French, Spanish, German, Russian etc
2. Navigate to the [test dapp](https://metamask.github.io/test-dapp)
3. `Connect` your wallet
4. In `Send Tokens` sections click `Create Token`
5. Wait for transaction to be confirmed and click on `Approve Token`
6. View the popup and expand view

### CODE REVIEW

**Comment by fejzic** [comment]
Verified by QA

File: ui/components/app/custom-spending-cap/custom-spending-cap.js [hunk 1]
```diff
@@ -190,6 +176,25 @@ export default function CustomSpendingCap({
...
             />
+            <Box
+              width={BLOCK_SIZES.MAX}
+              marginLeft="auto"
+              paddingRight={2}
+              paddingBottom={2}
+              textAlign={TEXT_ALIGN.END}
+              className="custom-spending-cap__max"
+            >
+              <button
```
Comment (darkwing) [inline ui/components/app/custom-spending-cap/custom-spending-cap.js:187]: @georgewrmarshall Do we prefer to use our custom `Button` component in all cases?

Comment (georgewrmarshall) [reply ui/components/app/custom-spending-cap/custom-spending-cap.js:187]: Yes! Looks like the intention was to use it because it has a `type="link"` prop

Comment (VSaric) [reply ui/components/app/custom-spending-cap/custom-spending-cap.js:187]: Hey @darkwing and @georgewrmarshall, I understand what you are saying, but I used `<button />` because when I used `Button` component, `type="link"` prop has his own css styles that I don't need here for `Max` button. 

You can check in `buttons.scss` file what styling is used for `.btn-link`. There are `hover`, `font-size (@include H4)` and `color` different from this that I am using here.

If I used `Button` component, then I will need to add `!important` in `.custom-spending-cap__max--button` class, because it will used styles from `.btn-link` class. I think that `!important` is not good to write in css files.

What is you opinion on this @georgewrmarshall and @darkwing?

Comment (georgewrmarshall) [reply ui/components/app/custom-spending-cap/custom-spending-cap.js:187]: I think in this case the design is breaking some design system conventions and that the button should be the primary blue color rather than the grey color? @Akatori-Design do you have thoughts on this?

**Comment by jpuri** [comment]
Design related discussion in the PR is important to be closed before we should merge this.

File: ui/components/app/custom-spending-cap/custom-spending-cap.js (hunk 1 above)
Comment (VSaric) [reply ui/components/app/custom-spending-cap/custom-spending-cap.js:187]: @georgewrmarshall I followed design from Figma. [Here](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A15726&t=KfwUH6o61gipRzey-0) is that design for `CustomSpendingCap` component and `Max` button in the input field. If @Akatori-Design thinks that the `Max` button should be the primary blue, I will make changes.

Comment (georgewrmarshall) [reply ui/components/app/custom-spending-cap/custom-spending-cap.js:187]: @VSaric yup your correct you're code follows the design very well! Nice work on that but I think in this particular instance the design is breaking some design system conventions. We should have caught this at the design stage so apologies that I am only catching it now. We don't have any grey colored buttons or links that include text. I actually mocked up this spending cap component to test some of our new design system components. In this story I used the `ButtonLink` component or `<Button type="link">` which I think follows our design system better https://metamask.github.io/metamask-storybook/?path=/story/ui-components-component-library-form-text-field-form-text-field-stories-js--custom-label-or-help-text

**Review by georgewrmarshall — APPROVED** [review]
LGTM!

**Review by jpuri — APPROVED** [review]
LGTM
