### PR TITLE
Fix gas estimate for tokens

### LINKED ISSUE #7709: Failed txs caused by gas limit set too low for erc20 tokens
**Describe the bug**

**To Reproduce**
Attempt to send any erc20 token with default gas limit/gwei set.  Most are being set with gas limit of 40 - 45,000 gas limit.  Checking back about a month ago (pre hard fork, pre MM v.7.7.1, the same tokens were being sent with 140 - 150,000 gas limit set.

**Expected behavior**
Better estimation of gas limit / gwei in order to not have failed tx.

**Screenshots**
image

**Browser details (please complete the following information):**
 - MetaMask Version 7.7.1

**Additional context**
Reference support tickets 27977, 27941, 27985, 28023

### PR DESCRIPTION
**Pull request by danjm**
fixes #7709

This PR fixes an outstanding issue with the send token screen. When advanced gas inputs were showing and token amounts where change, the newly estimated gas value would not be the submitted gas value if there was no blur event before clicking "Submit".

This PR ensures that the gas value is updated on a debounced change of the amount field so that the correct estimate is submitted.

### CODE REVIEW

File: ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 1]
```diff
@@ -608,7 +614,9 @@ export default class ConfirmTransactionBase extends Component {
     }
 
     getNextNonce()
-    tryReverseResolveAddress(toAddress)
+    if (toAddress) {
+      tryReverseResolveAddress(toAddress)
```
Comment (Gudahtt) [inline ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js]: I'm guessing these ENS resolution changes are unrelated?

**Review by Gudahtt — APPROVED** [review]
I've fixed the test failures. This should be good to merge now

**Comment by WyseNynja** [comment]
I think this is still a problem with v7.7.2. I don't want to link my name here with my address/txs, but I just had some transactions that tried to transfer some tokens revert. I manually increased the gas limit and they succeeded.

**Comment by TomAFrench** [comment]
I've had this same issue just occur. 2 DAI transfers failing with gas limits of 43k and 50k which finally went through once the gas limit was raised to 70k (although ironically only 37k of gas was used)

**Comment by Gudahtt** [comment]
Thanks for the feedback @WyseNynja and @TomAFrench ; would either of you be willing to create a separate issue to track the problem you've encountered? Any more details about browser version, MetaMask version, and circumstances of the event would be greatly appreciated as well. I suspect it's a distinct problem, unrelated to the changes in this PR, that just happens to have a similar symptom.
