### PR TITLE
fix: fix hideZeroBalance setting for asset list

### LINKED ISSUE #36764: [Bug]: Hide tokens without balance still displays tokens with 0 balance when enabled from setting
### Describe the bug

When `Hide tokens without balance` is enabled from General settings,  these tokes are still displayed in the token list

### Expected behavior

When `Hide tokens without balance` is enabled from General settings, tokens with 0 balance should not appear in the token list

### Screenshots/Recordings

https://github.com/user-attachments/assets/30bce2d1-602d-4650-acf0-baf4ed93671b

### Steps to reproduce

1. Have tokens with 0 balance in the token list
2. Enable Hide tokens without balance from General Settings
3. Notice the tokens with 0 balance are still displayed in the token list

### Error messages or log output

```shell
No error message
```

### Detection stage

During release testing

### Version

13.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

sev2

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix hiding tokens with zero balance when the setting is enabled.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36821?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed a bug causing users to still see tokens with zero balance when the setting "hideTokensWithZeroBalance" is enabled.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36764

## **Manual testing steps**

1. Import any token with zero balance
2. Notice that the balance 0.00 is displayed on the main asset list
3. Go to settings and enable setting "hide tokens with zero balance"
4. The token should now be removed from the list.

### **After**

https://github.com/user-attachments/assets/93e7075a-e284-4f58-bc81-a26d1e64107e

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Hides zero-balance tokens in the asset list when the setting is enabled, including for multichain accounts.
> 
> - **Assets list (multichain)**:
>   - Apply `getShouldHideZeroBalanceTokens` to filter out assets with `balance === '0'` before mapping/sorting in `ui/components/app/assets/token-list/token-list.tsx`.
>   - Wire up selector via `useSelector` to honor the user setting across networks.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1e071962024c4c3e08964c72e19ed9a9d082961e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/assets/token-list/token-list.tsx [hunk 1]
```diff
@@ -98,22 +102,28 @@ function TokenList({ onTokenClick, safeChains }: TokenListProps) {
...
-            secondary: null,
-            title: asset.name,
-            address:
-              'address' in asset ? asset.address : (asset.assetId as Hex),
-            chainId: asset.chainId as Hex,
-          };
-
-          return token;
-        });
+        return assets
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply ui/components/app/assets/token-list/token-list.tsx:105]: When `isMultichainAccountsState2Enabled` is enabled this will be executed
const balances = isEvm ? evmBalances : multichainAssets;
The `getTokenBalancesEvm` and `useMultiChainAssets` hook both check the setting `hideZeroBalanceTokens`

File: ui/components/app/assets/token-list/token-list.tsx [hunk 2]
```diff
@@ -98,22 +102,28 @@ function TokenList({ onTokenClick, safeChains }: TokenListProps) {
...
+              secondary: null,
+              title: asset.name,
+              address:
+                'address' in asset ? asset.address : (asset.assetId as Hex),
+              chainId: asset.chainId as Hex,
+            };
+
+            return token;
+          })
+          .filter((asset) => {
```
Comment (juanmigdr) [inline ui/components/app/assets/token-list/token-list.tsx]: Nit-pick but couldn't we filter before mapping and avoid mapping unnecessary assets?

**Review by juanmigdr — DISMISSED** [review]
Approved with comment

File: ui/components/app/assets/token-list/token-list.tsx (hunk 2 above)
Comment (sahar-fehri) [reply ui/components/app/assets/token-list/token-list.tsx]: Makes sense! Updated here [ec105b0](https://github.com/MetaMask/metamask-extension/pull/36821/commits/ec105b0c6990b42a2ce0fff467fdb58b77cc6d49) 🙏

**Review by juanmigdr — DISMISSED** [review]

**Review by bergarces — APPROVED** [review]

**Review by juanmigdr — APPROVED** [review]
Should we have a simple test?

File: ui/components/app/assets/token-list/token-list.tsx [hunk 3]
```diff
@@ -98,22 +102,28 @@ function TokenList({ onTokenClick, safeChains }: TokenListProps) {
...
-            address:
-              'address' in asset ? asset.address : (asset.assetId as Hex),
-            chainId: asset.chainId as Hex,
-          };
-
-          return token;
-        });
+        return assets
+          .filter((asset) => {
+            if (shouldHideZeroBalanceTokens && asset.balance === '0') {
```
Comment (juanmigdr) [inline ui/components/app/assets/token-list/token-list.tsx:107]: 🤔 isnt there a numeric value we can compare to? Instead of string?
