### PR TITLE
Ignore error while fetching `safeChainsList` for validation

### LINKED ISSUE #21601: [Sentry] TypeError: Failed to fetch
Sentry Issue: [METAMASK-X7F1](https://metamask.sentry.io/issues/4553894386/?referrer=github_integration)

```
TypeError: Failed to fetch
  at obj[prop] (/metamask/sentry-install.js:24:1)
  at Object.fetch (/metamask/runtime-lavamoat.js:11748:22)
  at fetchWithTimeout (shared/modules/fetch-with-timeout.ts:25:22)
  at _default (shared/lib/fetch-with-cache.ts:40:26)
  at _default.getAlerts (ui/pages/confirmation/templates/add-ethereum-chain.js:141:9)
...
(2 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

MM fetches safe chain list from https://chainid.network/chains.json and regarding to the sentry errors those calls are rarely fails and blocks the add custom eth chain flow. 

As a solution, we swallow error and put a warning for now.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/21601

## **Manual testing steps**

Manual testing not required.

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [X] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by matthewwalsh0 — APPROVED** [review]

File: ui/pages/confirmation/templates/add-ethereum-chain.js [hunk 1]
```diff
@@ -134,11 +149,18 @@ const ERROR_CONNECTING_TO_RPC = {
...
   let safeChainsList = [];
+  let providerError;
   if (state.useSafeChainsListValidation) {
-    safeChainsList = await fetchWithCache({
-      url: 'https://chainid.network/chains.json',
-      functionName: 'getSafeChainsList',
-    });
+    try {
+      safeChainsList = await fetchWithCache({
+        url: 'https://chainid.network/chains.json',
```
Comment (matthewwalsh0) [inline ui/pages/confirmation/templates/add-ethereum-chain.js:156]: Not required for a bug fix, but while we're here should we put this in a constant?

We could even split this logic and create a `validateChain` which does everything up to line 170 and returns `undefined` or the matched chain object.

**Review by vinistevam — APPROVED** [review]
