### PR TITLE
Fix for checkbox on advance gas fee modal

### LINKED ISSUE #13362: [Bug]: Checkbox to selected advance default gas is glitchy
### Describe the bug

Checking / un-checking of checkbox below looks buggy.

https://user-images.githubusercontent.com/2182307/150394420-3d8b33cd-81f9-49cf-81d8-4b7616f07e99.mov

### Steps to reproduce

1. Open advance gas editing modal
2. Try to check / uncheck default checkbox

### Error messages or log output

_No response_

### Version

10.8.2

### Build type

_No response_

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #13362

Explanation:  Checkbox on advance gas fee modal was bit glitchy. PR fixes it.

### CODE REVIEW

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js [hunk 1]
```diff
@@ -19,33 +19,41 @@ import { useI18nContext } from '../../../../hooks/useI18nContext';
...
         setAdvancedGasFee({
           maxBaseFee,
           priorityFee: maxPriorityFeePerGas,
         }),
       );
-    } else {
-      dispatch(setAdvancedGasFee(null));
+      setDefaultSettingsSelected(true);
     }
   };
```
Comment (jpuri) [inline ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js:56]: Update will now optimistically set checkbox to true without waiting for state update.

**Review by brad-decker — DISMISSED** [review]
LGTM

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/index.scss [hunk 2]
```diff
@@ -3,4 +3,8 @@
     font-size: $font-size-h4;
     margin: 0 8px 0 8px;
   }
+
+  label {
```
Comment (mcmire) [inline ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/index.scss:7]: What do you think about using `&__label`? Thinking that if AdvancedGasFeeDefaults ever uses a component that itself uses a `label` (without you knowing) it might be good to prevent this style from getting accidentally applied to that label.

Comment (jpuri) [reply ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/index.scss]: Good point, I just updated the PR with fix.

**Review by NiranjanaBinoy — APPROVED** [review]

**Review by mcmire — APPROVED** [review]
Looks good!
