### PR TITLE
fix: cp-13.8.0 ensure asset price chart does not crash and uses correct time ranges

### LINKED ISSUE #37384: [Bug]: Clicking on BTC throws an error
### Describe the bug

Clicking on BTC from the tokens list throws an error
Notice is not a consistent error. Happens sometimes

### Expected behavior

Clicking on BTC from the tokens list shows BTC token details

### Screenshots/Recordings

Image

### Steps to reproduce

1. Load your wallet
2. Click on BTC
3. Error appears

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

13.8.0 (experimental)

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

Adds try/catch logic and defaults to EVM timeranges if fails to parse CAIPAssetType.
Also ensures that we pass in CAIPAssetType into the `useChartTimeRanges` hook to prevent potential future issues (due to invalid types).

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37505?quickstart=1)

## **Changelog**

CHANGELOG entry: fix historical prices chart ranges for non-evm assets.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/37384

## **Manual testing steps**

Click BTC or SOL, observe charts - should not crash.

Testing missing chart data:
1. Click on "popular networks" filter
2. Click on BTC or SOL
3. Click 1W chart range
4. Expected - chart data should be visible

### **Before**

https://www.loom.com/share/adb371dd1bd24ca395632c28c20e02f5

### **After**

https://www.loom.com/share/1d975fed43d04b35bd1b5d7f9d84c57b

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Converts token addresses to CAIP asset types, passes them to the chart hook, and updates the hook to infer EVM via CAIP with try/catch fallbacks to default time ranges; adds corresponding tests.
> 
> - **Asset Chart (`ui/pages/asset/components/chart/asset-chart.tsx`)**:
>   - Add `convertAddressToAssetCaipType` to normalize inputs (returns CAIP as-is; builds EIP155 `erc20` from hex `address` + `chainId`; else `undefined`).
>   - Use `useMemo` to compute `caipAssetType` and pass to `useChartTimeRanges`.
> - **Hook (`ui/pages/asset/hooks/useChartTimeRanges.ts`)**:
>   - Infer EVM by parsing `caipAssetType` (namespace `eip155`); return default ranges for EVM.
>   - Wrap logic in try/catch; on errors or missing inputs, warn and return default ranges.
>   - For non-EVM, derive ranges from `historicalPrices`, filtering invalid durations and sorting by length.
>   - Remove dependency on multichain EVM selector.
> - **Tests**:
>   - Add `asset-chart.test.tsx` for `convertAddressToAssetCaipType` (CAIP passthrough, EIP155 creation, invalid inputs).
>   - Update `useChartTimeRanges.test.ts` to cover EVM defaults, missing inputs defaults, and non-EVM behaviors (derive, filter, sort).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6eec95a0eb35ca1fae1b660195cbf6674c92f5dd. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/asset/hooks/useChartTimeRanges.ts [hunk 1]
```diff
@@ -20,17 +24,27 @@ export const useChartTimeRanges = (
   currency?: string,
 ): string[] => {
   const DEFAULT_TIME_RANGES = ['P1D', 'P1W', 'P1M', 'P3M', 'P1Y', 'P1000Y'];
-  const isEvm = useSelector(getMultichainIsEvm);
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/hooks/useChartTimeRanges.ts:23]: Removed this selector, since if popular networks was selected, it would correctly/incorrectly think that evm was selected.

Meaning sol/btc assets would use the EVM time ranges.

File: ui/pages/asset/hooks/useChartTimeRanges.ts [hunk 2]
```diff
@@ -20,17 +24,27 @@ export const useChartTimeRanges = (
...
+    assert(caipAssetType, 'caipAssetType is required on non-EVM chains');
+    assert(currency, 'currency is required on non-EVM chains');
+
+    if (
+      parseCaipAssetType(caipAssetType).chain.namespace ===
+      KnownCaipNamespace.Eip155
+    ) {
+      // On EVM, time ranges are hardcoded
+      return DEFAULT_TIME_RANGES;
+    }
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/hooks/useChartTimeRanges.ts:39]: Instead of using the `getMultichainIsEvm` selector (which does not work reliably when popular networks is selected), we instead can parse the caipAssetType to see if the asset is EVM or nonEVM

**Comment by Prithpal-Sooriya** [comment]
Added 13.8.0 CP as this fixes a critical crash fix issue as well as missing chart issue.

**Review by bergarces — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]
