### PR TITLE
rpc-cap@3.0.0

### LINKED ISSUE #8919: Issue with subsquent 'eth_requestAccounts' without action to the first.
Original issue described [here](https://github.com/MetaMask/metamask-extension/issues/8918) that resulted of the reproduction below

**Describe the bug**
If `eth_requestAccounts` never resolves before calling it again, it will assume that there still is a request pending and will show `Permissions request already pending; please wait` error for subsequent calls. I think this behavior is fine, but the issue is that when connect screen will close after the second `eth_requestAccounts` not allow to confirm the first. Thus, never being able to connect to the site afterwards, even after site refresh. The solution to clear the first request is just to restart the extension.

**To Reproduce (REQUIRED)**
 - Go to any site with a manual connect button (the mm test dapp)
- Click 'Connect'
- Do not interact with the Connect popup
- Click 'Connect' again on the site

Issue
- This should close the popup to connect and provide the error `"Permissions request already pending; please wait."` to the site. Any subsequent request to connect will result in the above error providing to the site.

**Expected behavior**
Pre-v8 we would queue all subsequent connect requests and when the first request is either denied/confirmed will provide the number of responses to the site equal to the connect request notification queue.

Ideally, we should persist the request to connect popup/notification if and when subsequent calls are made before user action. Or cancel the first request, while simultaneously creating another request notification.

**Screenshots**
<details>
<summary>Subsequent Connect</summary>

</details>

### PR DESCRIPTION
**Pull request by rekmarks**
- `rpc-cap@3.0.0`
- Adapt usage of `rpc-cap` per breaking changes
- Rename `PermissionsController.requestAccountsPermission` to `requestAccountsPermissionWithId`, to highlight its purpose and distinguish it from other identically named functions

Fixes #8919

### CODE REVIEW

File: app/scripts/controllers/permissions/index.js [hunk 1]
```diff
@@ -716,7 +724,7 @@ export class PermissionsController {
        * @param {string} req - The internal rpc-cap user request object.
        */
       requestUserApproval: async (req) => {
-        const { origin, metadata: { id } } = req
+        const { metadata: { id, origin } } = req
```
Comment (Gudahtt) [inline app/scripts/controllers/permissions/index.js:727]: Isn't the `id` part of the `req` object now? Not the metadata
```suggestion
        const { id, metadata: { origin } } = req
```

Comment (rekmarks) [reply app/scripts/controllers/permissions/index.js:727]: No, it's in the `metadata`: https://github.com/MetaMask/rpc-cap/blob/master/src/@types/index.d.ts/#L23-L31

Comment (Gudahtt) [reply app/scripts/controllers/permissions/index.js:727]: Ah, I see. Different metadata object.

**Review by Gudahtt — APPROVED** [review]
LGTM!
