### PR TITLE
Validate txParams in TransactionStateManager.addTx

### LINKED ISSUE #6707: Metamask stops working if gas is passed as an object
**To Reproduce**
1. Open https://codepen.io/rstormsf/pen/qzBRBe?editors=1010
2. Click `Click me` button

```js
window.ethereum.sendAsync({
                    method: 'eth_sendTransaction',
                    params: [{
                        from: acc,
                        to: "0x0039f22efb07a647557c7c5d17854cfd6d489ef3",
                        gas: {}, // provide Gas as an Object
                        gasPrice: "0x77359400",
                        value: "0x0",
                        data: "0x0"
                    }],
                    jsonrpc: '2.0'
                }, (err, response) => {
                    window.alert(JSON.stringify(err))
                    console.log(response)
                })
```

**Expected behavior**
It should not break metamask

**Screenshots**
image

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - MetaMask Version 6.6.1

**Additional context**
metamask_big

### PR DESCRIPTION
**Pull request by akshitkrnagpal**
Fixes #6707.

### CODE REVIEW

**Comment by whymarrh** [comment]
@akshitkrnagpal thanks for this, would you mind rebase this on the latest `develop` and fixing the conflicts?

**Comment by akshitkrnagpal** [comment]
@whymarrh 
Hey
I have updated the PR. It would be great if you can review it. 😄

**Review by frankiebee — CHANGES_REQUESTED** [review]
do you mind writing tests for this?

**Comment by akshitkrnagpal** [comment]
@frankiebee 
Sure.

Would these tests cover the needs?
When txParams are invalid -
[ ] - `addTx` throws error and the `tx` is not added in the list.
[ ] - `updatedTx` throws error and `tx` is not updated in the list.

For which invalid values should I test this for? `txParams` can be invalid if any of the members is invalid and invalid values for each member can be anything other than a string (except `chainId` which can also be a number).

**Comment by frankiebee** [comment]
i would test for gas passed as an object sense that seems to be the issue in reference but yes i would test the keys in txParams 

>Would these tests cover the needs?
>When txParams are invalid -
>
>addTx throws error and the tx is not added in the list.
>updatedTx throws error and tx is not updated in the list.

this is good yes

**Comment by akshitkrnagpal** [comment]
@frankiebee 
Hey
I have added tests. Can you please review? 😄

File: app/scripts/controllers/transactions/tx-state-manager.js [hunk 1]
```diff
@@ -174,13 +179,9 @@ class TransactionStateManager extends EventEmitter {
...
   updateTx (txMeta, note) {
-    // validate txParams
+    // normalize and validate txParams if present
     if (txMeta.txParams) {
-      if (typeof txMeta.txParams.data === 'undefined') {
-        delete txMeta.txParams.data
-      }
-      txMeta.txParams = normalizeTxParams(txMeta.txParams, false)
-      this.validateTxParams(txMeta.txParams)
+      this.normalizeAndValidateTxParams(txMeta.txParams)
```
Comment (Gudahtt) [inline app/scripts/controllers/transactions/tx-state-manager.js]: It looks like this change is resulting in the normalization step being effectively skipped.

The `normalizeTxParams` function doesn't mutate the `txMeta.txParams` parameter - it creates a new object with the normalized parameters and returns it. So in this case, `txMeta.txParams` is getting normalized and then validated inside `normalizeAndValidateTxParams`, but these normalized params are never returned, so `txMeta.txParams` remains un-normalized.

You could preserve the previous behavior by returning `txParams` from `normalizeAndValidateTxParams, then setting `txMeta.txParams` to that return value here.

**Review by Gudahtt — CHANGES_REQUESTED** [review]

File: app/scripts/controllers/transactions/tx-state-manager.js (hunk 1 above)
Comment (frankiebee) [reply app/scripts/controllers/transactions/tx-state-manager.js]: Good catch

Comment (akshitkrnagpal) [reply app/scripts/controllers/transactions/tx-state-manager.js]: You are right. My Bad. 
I think it would be good to add a test to have a check if txParams are being normalized while adding or updating. Probably in another PR because this PR is not related to normalization.

Comment (Gudahtt) [reply app/scripts/controllers/transactions/tx-state-manager.js]: Sure, sounds good. Thanks!

**Review by Gudahtt — APPROVED** [review]

**Comment by akshitkrnagpal** [comment]
@Gudahtt Thanks for approving.

@frankiebee Can you take a look so this can be merged? 😄

**Review by frankiebee — APPROVED** [review]
great thank you
