### PR TITLE
Overflow primaryCurrency in tx-list-item & use primaryCurrency for tx breakdown details.

### LINKED ISSUE #9505: Tx list long token amount swap cutoff in extension view
**Describe the bug**
After setting a max amount of tokens and successfully creating the transactions the amounts that is leaving can be long with many decimals places. In the full screen view it hits the edge and looks fine, but in the extension view it gets cut off. 

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Initiate a confirmed swap with a token with more than 10-12 decimal places.

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #9505 
Set result of calculated token to base 10 string. (Don't see/know if there are any adverse side effects of this change).
Swap out `value` in tx breakdown for `primaryCurrency` from tx-list-item for more consistent information. 
Overflow hide and text overflow ellipsis on tx-list-item `primaryCurrency` for extra long  

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

<details>
<summary>Long decimal Swapped Asset </summary>

</details>

<details>
<summary>Approve spend limit</summary>

</details>

The only question I had was on the tx detail/breakdown would it make sense to show the amount of approval in the screenshot above, in prod we just show `0 ETH` as the amount for approval of spend limit?

### CODE REVIEW

**Comment by brad-decker** [comment]
Wrapping the token symbol to the next line breaks the alignment of the rest of the list item, so this is going to need some design feedback @rachelcope -- perhaps a more appropriate fix is to truncate the value of long numbers and add ellipses with a tooltip/title that shows the full amount? 

As for approvals, we don't currently display anything in the list item bc the list item does not include gas fees. I'm not sure if we should change the transaction-details yet, considering we already have new designs that I hope to get implemented soon.

Could you help me with what the .toString(10) is doing in your changes? Other than the above, I think this looks good.

File: ui/app/components/app/transaction-breakdown/transaction-breakdown.component.js [hunk 1]
```diff
@@ -17,9 +17,9 @@ export default class TransactionBreakdown extends PureComponent {
     nativeCurrency: PropTypes.string,
     showFiat: PropTypes.bool,
     nonce: PropTypes.string,
+    primaryCurrency: PropTypes.string,
     gas: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
     gasPrice: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
-    value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
```
Comment (Gudahtt) [inline ui/app/components/app/transaction-breakdown/transaction-breakdown.component.js:22]: Nit: could you remove this from the container as well? It's still used in the container but it's no longer required to get passed down to this component.

**Comment by rachelcope** [comment]
> perhaps a more appropriate fix is to truncate the value of long numbers and add ellipses with a tooltip/title that shows the full amount?

This makes sense to me. 👍 

> would it make sense to show the amount of approval in the screenshot above, in prod we just show 0 ETH as the amount for approval of spend limit

I think that makes sense. Instead of "Amount" it could be "Spend limit amount"

**Comment by tmashuang** [comment]
> Could you help me with what the .toString(10) is doing in your changes? 

That was the main issue with the long decimals from the before image, for very small values. `0.0000000001`. Would show as `1e-10`.

**Comment by tmashuang** [comment]
<details>
<summary>Conditionally render amount title to 'Spend limit amount'</summary>

<details>

**Comment by brad-decker** [comment]
@tmashuang could I get a screenshot of the ellipses overflow so that the token symbol and currency are on one line? I'm :+1: on this if that's in place.

File: ui/app/components/app/transaction-breakdown/transaction-breakdown.component.js (hunk 1 above)
Comment (tmashuang) [reply ui/app/components/app/transaction-breakdown/transaction-breakdown.component.js:22]: I did it in [3bb5bcf TxBreakdown Container L:24](https://github.com/MetaMask/metamask-extension/commit/3bb5bcff932c3d026b37903ece8d1ad58af35118#diff-79772a36e939c5b2a111313bc678686bL24).

File: ui/app/components/app/transaction-breakdown/transaction-breakdown.component.js [hunk 2]
```diff
@@ -47,13 +48,18 @@ export default class TransactionBreakdown extends PureComponent {
...
+            <TransactionBreakdownRow title={t('spendingLimitAmount')}>
+              <span className="transaction-breakdown__value">{primaryCurrency}</span>
+            </TransactionBreakdownRow>
+          )
+          : (
+            <TransactionBreakdownRow title={t('amount')}>
+              <span className="transaction-breakdown__value">{primaryCurrency}</span>
+            </TransactionBreakdownRow>
+          )
+        }
```
Comment (Gudahtt) [inline ui/app/components/app/transaction-breakdown/transaction-breakdown.component.js:62]: Minor suggestion on improving this:

```suggestion
        <TransactionBreakdownRow
          title={
            isTokenApprove
              ? t('spendingLimitAmount')
              : t('amount')
          }
        >
          <span className="transaction-breakdown__value">{primaryCurrency}</span>
        </TransactionBreakdownRow>
```

**Comment by tmashuang** [comment]
@brad-decker i updated the newest comment with an additional screenshot. 
> perhaps a more appropriate fix is to truncate the value of long numbers and add ellipses with a tooltip/title that shows the full amount?

Is the tooltip/title mostly for the user hover action? Or was it mean to swap the `h2` element for `ToolTip` component?

**Comment by brad-decker** [comment]
Just for the user's hover action.

**Review by brad-decker — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by brad-decker** [comment]
Great work, @tmashuang :D
