### PR TITLE
fix(snaps): Ensure only numbers are allowed in Inputs type `number`

### LINKED ISSUE #35941: [Bug]: Firefox send flow - Solana - unable to send decimal amount if the symbol `,` is used instead of `.`
View issue in GitHub: https://github.com/MetaMask/metamask-extension/issues/35941

**Describe the bug**

When sending an amount with decimals on Firefox, if the symbol `,` is used instead of `.`, then the amount is not visible.

Similar for Solana send: unable to send decimal amount if the symbol `,` is used instead of `.` The _Continue_ button is greyed out.

Unable to reproduce on Chrome.

**Expected behavior**

Sending amount to be visible when it's typed with `,` same as for Chrome.

**Screenshots/Recordings**

https://github.com/user-attachments/assets/45f030f1-f80d-473d-9c50-f36eae6d958c

https://github.com/user-attachments/assets/74716721-2fe0-4526-b29b-d3fda4c1ec02

**Steps to reproduce**

1. Go to send flow
2. Type decimal sending amount with the symbol `,` instead of `.`
3. Notice it's not fully visible

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.4.0

**Build type**

None

**Browser**

Firefox

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

This PR adds a `onBeforeInput` handler to `SnapUIInput` of type `number` that validates the content typed in to ensure only numbers are allowed.

On top of that, this PR also adds a formatting step to the input content to ensure that `,` are replaced with `.`.

This is necessary as Firefox doesn't handle inputs of type `number` as Chrome does, there is no content validation.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36074?quickstart=1)

## **Changelog**

CHANGELOG entry: fix issue with Snaps UI inputs of type number on Firefox

## **Related issues**

Fixes: #35941

## **Manual testing steps**

1. Open the extension on Firefox
2. Go to the Solana send flow
3. Ensure that only numbers can be used in the amount input and that `,` are replaced with `.`

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx [hunk 1]
```diff
@@ -9,6 +10,8 @@ import classnames from 'classnames';
 import { useSnapInterfaceContext } from '../../../../contexts/snaps';
 import { FormTextField, FormTextFieldProps } from '../../../component-library';
 
+const DECIMAL_INPUT_REGEX = /^\d*(\.|,)?\d*$/u;
```
Comment (GuillaumeRx) [inline ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:13]: Taken from https://github.com/MetaMask/metamask-extension/blob/b93b1f17527b7b9a9b494c25fd47b037496b7d56/ui/components/ui/unit-input/unit-input.component.js#L13

File: ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx [hunk 2]
```diff
@@ -43,9 +46,50 @@ export const SnapUIInput: FunctionComponent<
...
 
+  /**
+   * Get the input value, replacing commas with dots for number inputs.
+   *
+   * @param text - The current text input value.
+   * @returns The processed input value.
+   */
+  const getInputValue = (text: string) => {
+    if (type === 'number') {
+      // Mimic browser behaviour where commas are replaced.
```
Comment (Mrtenz) [inline ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:57]: Is this always the case, or only for certain locales? 🤔

Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:57]: I think this is always the case for Chrome. This is taken from @FrederikBolding fix on mobile: https://github.com/MetaMask/metamask-mobile/pull/15691

File: ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx [hunk 3]
```diff
@@ -61,6 +105,13 @@ export const SnapUIInput: FunctionComponent<
       })}
       id={name}
       value={value}
+      textFieldProps={{
+        ...textFieldProps,
+        inputProps: {
+          onBeforeInput: handleBeforeInput,
+          ...textFieldProps?.inputProps,
+        },
+      }}
```
[the remark this answers is not in the document]
Comment (GuillaumeRx) [reply ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx:114]: Intended

**Review by Mrtenz — APPROVED** [review]

**Review by mikesposito — APPROVED** [review]
