### PR TITLE
fix: cp-12.17.0 missing swap rates

### LINKED ISSUE #32115: [Bug]: Solana swap page crashes when there are no conversion rates in state
### Describe the bug

When the Swap page is opened before exchange rates are fetched, the bridge selectors attempt to access keys of undefined objects

### Expected behavior

The page should fallback to default conversion rates (null) and not crash

### Screenshots/Recordings

Image

### Steps to reproduce

1. Use solana swap/bridge enough to hit the Snap's rate limit
2. Close extension popup and reopen
3. Navigate to Swap page
4. Page will crash

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.17.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

Changes
- move bridge test mocks to a TS file to add type checking
- clean up exchange rate logic and add fallback behavior

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32114?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32115

## **Manual testing steps**
See ticket repro steps

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by ghgoodreau — APPROVED** [review]

File: ui/ducks/bridge/selectors.ts [hunk 1]
```diff
@@ -282,35 +294,68 @@ export const getBridgeSortOrder = (state: BridgeAppState) =>
...
-  getMarketData,
-  getAssetsRates,
-  getFromToken,
-  getUSDConversionRate,
-  getMultichainCoinRates,
-  getConversionRate,
-  (state) => state.bridge.fromTokenExchangeRate,
+  [
+    getFromChain,
+    (state: BridgeAppState) => state.metamask.marketData, // rates for non-native evm tokens
```
Comment (infiniteflower) [inline ui/ducks/bridge/selectors.ts:299]: Are there any selectors for these already?

File: ui/ducks/bridge/selectors.ts [hunk 2]
```diff
@@ -334,25 +380,27 @@ export const getFromTokenConversionRate = createSelector(
...
-  getNetworkConfigurationsByChainId,
-  (state) => ({
-    state,
-    toTokenExchangeRate: state.bridge.toTokenExchangeRate,
-    toTokenUsdExchangeRate: state.bridge.toTokenUsdExchangeRate,
-  }),
-  getMultichainCoinRates, // multichain native rates
+  [
+    getToChain,
+    (state: BridgeAppState) => state.metamask.marketData, // rates for non-native evm tokens
```
Comment (infiniteflower) [inline ui/ducks/bridge/selectors.ts:385]: Same as above

**Review by infiniteflower — APPROVED** [review]
Small comments, non blocking for me

File: ui/ducks/bridge/selectors.ts (hunk 1 above)
Comment (micaelae) [reply ui/ducks/bridge/selectors.ts:299]: There's `selectExchangeRateByChainIdAndAddress` in the bridge-controller but 12.16 hasn't been upgraded. Working on that for the next RC then we should be able to get rid of these
