### PR TITLE
Account transition fix

### LINKED ISSUE #670: Accounts screen has jumpy transition
We've worked out most of our transition bugs, and most of our transitions are smooth looking.

One that still isn't (or got bad at some point) is the accounts screen entering view.

When first entering, the entire view is pushed down a little bit, like this:

screen shot 2016-09-14 at 4 12 58 pm

What you can't tell here (but can easily see in practice) is that once it arrives in place, this view jumps up a good bit.

I just did some investigating, and the solution did not seem as obvious to me as I'd hoped it would.  Opening an issue to ensure later investigation.

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Fixes #670 for the most part, broken off from another PR for modularity.

Why this works is because css transitions do not work well when you change margins. Changing this to padding makes everything a lot smoother.

### CODE REVIEW

**Review by kumavis — APPROVED** [review]

File: ui/app/accounts/index.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ AccountsScreen.prototype.render = function () {
             style: {
               display: 'flex',
               height: '40px',
-              paddint: '10px',
```
Comment (kumavis) [inline ui/app/accounts/index.js]: lel
