### PR TITLE
fix: Prevent coercing symbols to zero in the edit spending cap modal

### LINKED ISSUE #28096: [Bug]: Editing the Spending Cap value by including symbols such as "-", "+"  or "e" activates the Remove Permission screen
### Describe the bug

Editing the Spending Cap value by including symbols such as "-", "+"  or "e" activates the Remove Permission screen. 

Related: https://github.com/MetaMask/metamask-extension/pull/27672

### Expected behavior

- Symbols should not be allowed in the field

### Screenshots/Recordings

https://github.com/user-attachments/assets/21bda6c0-8111-4e77-b696-2e8e4b49dd0b

### Steps to reproduce

1. Go to[ test dapp](https://metamask.github.io/test-dapp/)
2. Click `Approve tokens`
3. Edit Spending Cap and include symbols

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Since the `TextField` in the "edit spending cap" modal has a type `TextFieldType.Number`, it already blocks most symbols and letters. However, it does currently support `+`, `-` and `e` characters as they can be used to construe numbers.

For example, when a `-` sign is introduced in the input field, the interim value is coerced to `''`, as there is no numerical equivalent to the sign by itself. The first part of this fix was to disable the "Save" button on such cases. If the user wants to revoke the spending cap, they can introduce `0`, but `''` is not a valid response.

Furthermore, when a valid number is introduced but that uses scientific notation or `+`/`-` signs, the submission is disabled and a validation message is shown to the user: "Enter numbers only".

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28192?quickstart=1)

## **Related issues**

Fixes: [#28096](https://github.com/MetaMask/metamask-extension/issues/28096)

## **Manual testing steps**

1. Deploy an erc20 token contract in the test DApp
2. Trigger an approve confirmation
3. Attempt to edit the spending cap with -1, 10e10, or any others.
4. You should be prevented from submitting and see the validation message.

### **After**

Screenshot 2024-10-30 at 17 46 48

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx [hunk 1]
```diff
@@ -124,6 +124,8 @@ export const EditSpendingCapModal = ({
     decimals &&
     parseInt(decimals, 10) < countDecimalDigits(customSpendingCapInputValue);
 
+  const showSpecialCharacterError = /[-+e]/u.test(customSpendingCapInputValue);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx:127]: Minor, is it worth a constant for the regex such as `SPECIAL_CHARACTERS_PATTERN`?

File: ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx [hunk 2]
```diff
@@ -171,6 +173,15 @@ export const EditSpendingCapModal = ({
               {t('editSpendingCapError', [decimals])}
             </Text>
           )}
+          {showSpecialCharacterError && (
+            <Text
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx:177]: Minor, is it worth a local `Error` component to avoid the duplication with the above decimal error?

**Review by matthewwalsh0 — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Comment by sleepytanya** [comment]
@pedronfigueiredo 
User can use 0 as an input (Spending Cap request turns into Remove Permission) - expected behavior? Thank you!


https://github.com/user-attachments/assets/f26009e6-f1ee-45db-8116-d5ad3080c13f

**Comment by pedronfigueiredo** [comment]
Hey @sleepytanya, thanks for flagging this. It is expected!
