### PR TITLE
fix: wallet lock race-condition

### LINKED ISSUE #34974: [Bug]: seedless onboarding regression: "Invalid password" after wallet is locked while changing the password
### Describe the bug

If the wallet it locked while the password is being changed neither the old or new password can be used to log in. The problem persists across extension restarts.

### Expected behavior

The wallet shouldn't be bricked :-) 

### Screenshots/Recordings

https://github.com/user-attachments/assets/f36731f2-5a45-4b99-be9b-2c18723b2e51

### Steps to reproduce

See video above. Note: I've enabled a Performance slowdown of 20x in the background and set the network slowdown to 3G in the foreground and background to make it easier to hit the race condition.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lwin-kyaw**
## **Description**
**Issue:**
In the extension, users can open the multiple tabs of same wallet. 
So, user can lock the wallet while change pwd is loading in another tab
That creates an error while changing wallet and user will get locked.

**Proposed Solution:**
This PR adds the lock (mutex) to the SeedlessOnboarding controller operations, so that while one of the operations still in progress, users will not be able to lock the wallet immediately and wait for the other operations to finish.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35022?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34974

1. open wallet in two browser tabs (with same browser profile)
2. change password in one tab
3. quickly lock the wallet from another tab, while change password is loading
4. users should see the loading spinner until the change password is another tab is finished
5. Then both tabs should be locked.

### **After**

https://github.com/user-attachments/assets/7827bc82-d705-43c1-afc0-93384c987e58

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: types/await-semaphore.d.ts
Comment (lwin-kyaw) [inline types/await-semaphore.d.ts:1]: Type definitions for `await-semaphore` package, since `typedef` are not available for it.

File: app/scripts/lib/lock/custom-lock-with-status.ts
Comment (lwin-kyaw) [inline app/scripts/lib/lock/custom-lock-with-status.ts:1]: The current `lock` package, `await-semaphore` does not have a way to check if the mutex is locked, so I have to create a Custom Lock class with the `lockStatus`.

File: ui/components/app/toast-master/toast-master.js [hunk 1]
```diff
@@ -80,6 +82,7 @@
         <PermittedNetworkToast />
         <NewSrpAddedToast />
         <CopyAddressToast />
+        <LockFailureToast />
```
[the remark this answers is not in the document]
Comment (lwin-kyaw) [reply ui/components/app/toast-master/toast-master.js]: User can only lock the wallet in the home page (Global menu is only accessible in the Home page).

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -8855,8 +8866,22 @@ export default class MetamaskController extends EventEmitter {
...
+    const releaseLock = await this.seedlessOperationMutex.acquire();
+    try {
+      await this.seedlessOnboardingController.setLocked();
+      await this.keyringController.setLocked();
+    } catch (error) {
+      log.error('Error setting locked state', error);
+      throw error;
+    } finally {
+      releaseLock();
+    }
```
[the remark this answers is not in the document]
Comment (lwin-kyaw) [reply app/scripts/metamask-controller.js:8748]: That's an expected flow, if `seedlessOperationMutex` is already held (e.g while changing password, or adding new SRPs), users should not be able to lock the wallet.

File: ui/store/actions.ts [hunk 3]
```diff
@@ -2192,11 +2192,19 @@ export function lockMetamask(): ThunkAction<
       })
       .catch(() => {
         dispatch(hideLoadingIndication());
-        dispatch({ type: actionConstants.LOCK_METAMASK });
+        dispatch(setShowLockFailureToast(true));
+        log.error('failed to lock metamask');
       });
```
Comment (davidmurdoch) [inline ui/store/actions.ts]: Is there a specific error that we can catch here for the `setShowLockFailureToast`. I imagine there might be other reasons lock could fail, so we wouldn't want to show the "Password change" error for those.

File: app/scripts/metamask-controller.js [hunk 4]
```diff
@@ -8855,8 +8866,22 @@ export default class MetamaskController extends EventEmitter {
   /**
    * Locks MetaMask
    */
-  setLocked() {
-    return this.keyringController.setLocked();
+  async setLocked() {
+    if (this.seedlessOperationMutex.isLocked()) {
+      log.error('seedlessOperationMutex is locked');
+      throw new Error('seedlessOperationMutex is locked');
+    }
```
Comment (davidmurdoch) [inline app/scripts/metamask-controller.js]: An alternative here that might be better is to wait until a lock can be acquired, and then proceed with the lock once it is available.

_Ideally_, I think the UI should be locked immediately, even if the background cannot be locked yet. For security reasons I wouldn't want a user to click `Lock`, not pay attention that it didn't work, and then accidentally leave the wallet unlocked when they didn't want it to be.

To put another way. I think the best solution here is that when a user clicks `Lock` while a `seedlessOperationMutex` is being held we should:

1. set UI state to `locked` (again, I don't know the specifics on if this is easy to today), so that the UI can't be used
2. in the background process we then wait as long as we need to before _actually_ locking the vault

**Comment by LeVinhGithub** [comment]
lgtm

File: app/scripts/lib/lock/custom-lock-with-status.test.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+import LockWithStatus from './custom-lock-with-status';
+
+describe('LockWithStatus', () => {
+  it('should lock and unlock', async () => {
+    const lock = new LockWithStatus();
+    const releaseLock = await lock.acquire();
```
Comment (matthiasgeihs) [inline app/scripts/lib/lock/custom-lock-with-status.test.ts]: nit
```suggestion
    expect(lock.isLocked()).toBe(false);
    const releaseLock = await lock.acquire();
```

File: app/scripts/metamask-controller.js [hunk 6]
```diff
@@ -6548,13 +6555,19 @@ export default class MetamaskController extends EventEmitter {
...
-      );
+          bufferedPrivateKey,
+          SecretType.PrivateKey,
+        );
+      } catch (error) {
+        log.error('Error adding new private key backup', error);
+        throw error;
+      } finally {
+        releaseLock();
+      }
```
[the remark this answers is not in the document]
Comment (matthiasgeihs) [reply app/scripts/metamask-controller.js:6540]: Is this comment valid? Why are you no longer adding `keyringId`?

File: ui/store/actions.ts [hunk 7]
```diff
@@ -2192,11 +2192,19 @@ export function lockMetamask(): ThunkAction<
       })
       .catch(() => {
         dispatch(hideLoadingIndication());
-        dispatch({ type: actionConstants.LOCK_METAMASK });
+        dispatch(setShowLockFailureToast(true));
+        log.error('failed to lock metamask');
```
[the remark this answers is not in the document]
Comment (matthiasgeihs) [reply ui/store/actions.ts]: Is this comment correct?

**Review by matthiasgeihs — COMMENTED** [review]
just some minor comments.
can't judge the UI changes

File: ui/store/actions.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (lwin-kyaw) [reply ui/store/actions.ts]: Not any more. The message is updated.

File: app/scripts/lib/lock/custom-lock-with-status.test.ts (hunk 5 above)
Comment (matthiasgeihs) [reply app/scripts/lib/lock/custom-lock-with-status.test.ts]: has been addressed

**Review by matthiasgeihs — DISMISSED** [review]

**Comment by LeVinhGithub** [comment]
still lgtm

File: app/scripts/metamask-controller.js [hunk 8]
```diff
@@ -8708,9 +8720,30 @@ export default class MetamaskController extends EventEmitter {
 
   /**
    * Locks MetaMask
+   *
+   * @param {boolean} skipSeedlessOperationLock - If true, the seedless operation mutex will not be locked.
    */
-  setLocked() {
-    return this.keyringController.setLocked();
+  async setLocked(skipSeedlessOperationLock = false) {
```
Comment (himanshuchawla009) [inline app/scripts/metamask-controller.js]:
```suggestion
  async setLocked(options: {
  skipSeedlessOperationLock?: boolean
  }) {
```
```suggestion
  async setLocked(skipSeedlessOperationLock = false) {
```

**Review by himanshuchawla009 — CHANGES_REQUESTED** [review]

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Review by tuna1207 — APPROVED** [review]

**Review by chaitanyapotti — APPROVED** [review]
