### PR TITLE
Fix confirmation popup not always opening

### LINKED ISSUE #3759: Confirmation popup not always opening
I don't have solid reproduction steps here, but I've now experienced this, and had users report it, too.

Sometimes, MetaMask seems to not open the confirmation popup, and so users are forced to click the fox to get to it. We should ensure that the popup is reliable.

@woodydeck on Gitter said it never pops up for them in Brave, but tends to work in Chrome intermittently.

### PR DESCRIPTION
**Pull request by alextsg**
Fixes #3759 

Previously, the environment was split into "popup" and "notification" types, with fullscreen mode being classified as "popup". The boolean `popupIsOpen` was not accurate, as 1) if two tabs were open, and one was closed, `popupIsOpen` would be `false` even though one tab was still open (similar thing happens if a tab is open and the popup is opened+closed) and 2) it's a misleading name since it applies to both the "fullscreen" mode and "popup" mode. This PR sets the "fullscreen" state to avoid this confusion.

@bitpshr This PR slightly modifies the way `controller.isClientOpen` is set, since it now takes into account the "notification" client being open and gets set on "popup", "fullscreen", and "notification" `endOfStream`s

### CODE REVIEW

File: app/scripts/background.js [hunk 1]
```diff
@@ -191,33 +196,53 @@ function setupController (initState, initLangCode) {
...
   extension.runtime.onConnect.addListener(connectRemote)
+
+  const metamaskInternalProcessHash = {
+    [ENVIRONMENT_TYPE_POPUP]: true,
+    [ENVIRONMENT_TYPE_NOTIFICATION]: true,
+    [ENVIRONMENT_TYPE_FULLSCREEN]: true,
+  }
+
+  const isClientOpenStatus = () => {
+    return popupIsOpen || Object.keys(openMetamaskTabsIDs) || notificationIsOpen
```
Comment (bitpshr) [inline app/scripts/background.js]: This should be checking `length` on `Object.keys(openMetamaskTabsIDs)`, otherwise `isClientOpenStatus` will return an empty array when it should return `false`. It should be something like:

```js
return popupIsOpen || Object.keys(openMetamaskTabsIDs).length || notificationIsOpen
```

**Review by bitpshr — CHANGES_REQUESTED** [review]
This cleans up a lot of arbitrary string checks and I like the use of Enum-style modules. One small issue with the logic and then this looks good to me.

**Comment by alextsg** [comment]
@bitpshr Thanks. Updated PR to return a boolean.

**Review by bitpshr — APPROVED** [review]

**Comment by manoj529** [comment]
I'm facing the same issue with Firefox running on android device. I was trying to transfer ethers from one account to another and the event gets triggered with a click event of a button. When i try the same with a chrome browser in a desktop it works as expected. however it fails to get the popup in mobile device with firefox browser. I had to manually open metamask wallet extension from the menu item.  Did i missed anything to call from my application?

**Comment by whymarrh** [comment]
@manoj529 please open up a new issue with what you're running into
