### PR TITLE
fix: dont enable shield coverage if basic functionality not enabled

### LINKED ISSUE #38316: [Bug]: Transaction Shield - The tx shield banner appears in a loading state in the Confirmation screen while having Basic Functionality off
**Describe the bug**

The tx shield banner appears in a loading state in the Confirmation screen while having Basic Functionality off

**Expected behavior**

We shouldn't see the banner? Or have some indicative that it's off? 🤔

**Screenshots/Recordings**

Image

https://github.com/user-attachments/assets/6228fa47-f2b5-4c4c-b50a-25dd81457348

**Steps to reproduce**

1. Enable Shield
2. Turn off Basic functionality from Privacy settings
3. Trigger a tx from a dapp
4. See Transaction Shield banner is still displayed (in a loading sate)

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.11.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by tuna1207**
## **Description**

Previously we are still showing shield coverage footer in confirmation screen if basic functionality is off which lead to the coverage banner keep loading because of missing external api request. This PR hide shield coverage footer if basic functionality is off

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38351?quickstart=1)

## **Changelog**

CHANGELOG entry: don't show shield coverage if basic functionality is off

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38316

## **Manual testing steps**

1. subscribe to shield
2. turn basic functionality off
3. initiate a transaction
4. shield coverage footer should not show

### **After**

https://github.com/user-attachments/assets/12c9c9be-e802-4288-ba14-0c6a64793bef

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Prevents Shield coverage from enabling when Basic Functionality is off by gating both controller behavior and UI hook, and adds corresponding tests.
> 
> - **Controller (app/scripts/metamask-controller.js)**
>   - Gate Shield subscription handling on `preferences.state.useExternalServices`; skip when disabled.
>   - On external services toggle, query subscription state and `start/stop` `ShieldController` accordingly; also enable/disable related services (token detection, non-RPC gas APIs).
> - **UI Hook (useEnableShieldCoverageChecks.ts)**
>   - Require `getUseExternalServices` to be true for `isEnabled`; keep pause logic unchanged.
> - **Tests (useEnableShieldCoverageChecks.test.ts)**
>   - Update tests to pass `metamask.useExternalServices` and add case for Basic Functionality disabled; maintain env-flag scenarios.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1cf58c827ca4fc0e4c13ad4113d32ce25d3e48da. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by chaitanyapotti — DISMISSED** [review]

File: ui/pages/confirmations/hooks/transactions/useEnableShieldCoverageChecks.ts [hunk 1]
```diff
@@ -17,7 +20,7 @@ export const useEnableShieldCoverageChecks = () => {
   }, [subscriptions]);
 
   return {
-    isEnabled: isShieldSubscriptionActive,
+    isEnabled: isBasicFunctionalityEnabled && isShieldSubscriptionActive,
```
[the remark this answers is not in the document]
Comment (tuna1207) [reply ui/pages/confirmations/hooks/transactions/useEnableShieldCoverageChecks.ts:24]: isPaused is for subscription state only, not releated to `isBasicFunctionalityEnabled`

File: app/scripts/metamask-controller.js [hunk 2]
```diff
@@ -828,6 +828,35 @@ export default class MetamaskController extends EventEmitter {
         }
       },
     );
+    // on/off shield controller based on preferences useExternalServices flag (basic functionality toggle)
+    // since shield coverage use security alerts, phish detect and transaction simulations, which is only available when basic functionality is enabled
+    this.controllerMessenger.subscribe(
```
Comment (lwin-kyaw) [inline app/scripts/metamask-controller.js]: Please use [this existing method](https://github.com/MetaMask/metamask-extension/blob/main/app/scripts/metamask-controller.js#L8179)

Comment (tuna1207) [reply app/scripts/metamask-controller.js]: this one doesn't account for app start up with basic functionality off i think, in that case, the shield controller still get started by this listener
https://github.com/MetaMask/metamask-extension/pull/38351/files#diff-6fbff2cfe97ac01b77296ef2122c7e0a5b3ff6a84b584b4d1a87482f35eea3d6R807

Comment (lwin-kyaw) [reply app/scripts/metamask-controller.js]: We will also need to add the external service check there.

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -811,12 +811,21 @@ export default class MetamaskController extends EventEmitter {
         const hasActiveShieldSubscription = getIsShieldSubscriptionActive(
           state.subscriptions,
         );
-
         if (hasActiveShieldSubscription) {
```
Comment (lwin-kyaw) [inline app/scripts/metamask-controller.js:821]:
```suggestion
        const { useExternalServices } = this.preferencesController.state;
        if (hasActiveShieldSubscription && useExternalServices) {
```

We should check before we fetching claims.

**Review by lwin-kyaw — DISMISSED** [review]

**Review by chaitanyapotti — COMMENTED** [review]
We also don't start subscription controller checks if basic functionality is off..
pls correct me here.

**Comment by lwin-kyaw** [comment]
> We also don't start subscription controller checks if basic functionality is off.. pls correct me here.

Yes. We can assert the external services preference before [this](https://github.com/MetaMask/metamask-extension/pull/38351/files#diff-6fbff2cfe97ac01b77296ef2122c7e0a5b3ff6a84b584b4d1a87482f35eea3d6R811) and just return

cc: @tuna1207

**Review by chaitanyapotti — APPROVED** [review]

**Review by lwin-kyaw — APPROVED** [review]
