### PR TITLE
fix: Optimism max gas missmatch

### LINKED ISSUE #23601: [Bug]: Gas - Optimism max gas missmatch and scientific notation
### Describe the bug

**Problem:** there is a gas miss-match between max fees and max total when not sending 
Ex. in Sending an ERC20 the max fee and max amount should the same for the ETH in this case. However I see those 2 values different:

- Max fee: 0.00000146 ETH
- Max amount: 345 DAI + 0.000001336 ETH 

I've seen also occasionally scientific notation in the total max amount :thinking_face:

### Expected behavior

- Max fee and max amount should be consistent
- We should not display scientific notation

### Screenshots/Recordings

image

image

### Steps to reproduce

1. Select Optimism
2. Start a SendERC20
3. See gas

### Error messages or log output

_No response_

### Version

11.12.2 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

There is mismatch in max gas displayed for Optimism.

## **Related issues**

Fixes: MetaMask/metamask-extension#23601

## **Manual testing steps**

1. Switch to optimism test net
2. Create ERC20 token and initiate transfer
3. Check gas displayed

## **Screenshots/Recordings**
Screenshot 2024-04-29 at 12 19 38 PM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by digiwand — COMMENTED** [review]
would be nice to add supporting tests for these

File: ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js [hunk 1]
```diff
@@ -179,7 +183,10 @@ export default function ConfirmTokenTransactionSwitch({ transaction }) {
             transaction={transaction}
             ethTransactionTotal={ethTransactionTotal}
             fiatTransactionTotal={fiatTransactionTotal}
-            hexMaximumTransactionFee={hexMaximumTransactionFee}
+            hexMaximumTransactionFee={sumHexes(
+              hexMaximumTransactionFee,
+              layer1GasFee,
+            )}
```
[the remark this answers is not in the document]
Comment (jpuri) [reply ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js:189]: The bug is about send token confirmations, I found other confirmations already work well.

File: ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js [hunk 2]
```diff
@@ -59,7 +59,7 @@ export default function ConfirmTokenTransactionBase({
 
   const ethTransactionTotalMaxAmount = Number(
     hexWEIToDecETH(hexMaximumTransactionFee),
-  );
+  ).toFixed(8);
```
[the remark this answers is not in the document]
Comment (jpuri) [reply ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js:62]: I think `8` is already default value used for formatting, unless overridden https://github.com/MetaMask/metamask-extension/blob/74678b0080602a578e820befbcb15aba0dbcc1ce/ui/hooks/useUserPreferencedCurrency.js#L58

**Comment by jpuri** [comment]
> would be nice to add supporting tests for these

Bit hard to do that as these legacy components changed have no test coverage currently.

File: ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js (hunk 2 above)
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js:62]: If this is matching a standard value in that hook, is it worth exporting a constant such as `ETH_DEFAULT_DECIMALS` to keep them aligned going forward?

File: ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js [hunk 3]
```diff
@@ -179,7 +183,10 @@ export default function ConfirmTokenTransactionSwitch({ transaction }) {
             transaction={transaction}
             ethTransactionTotal={ethTransactionTotal}
             fiatTransactionTotal={fiatTransactionTotal}
-            hexMaximumTransactionFee={hexMaximumTransactionFee}
+            hexMaximumTransactionFee={sumHexes(
+              hexMaximumTransactionFee,
+              layer1GasFee,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js:188]: Does `sumHexes` handle `undefined` or `null` or do we need a fallback like `?? '0x0'` here as we do elsewhere?

File: ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (digiwand) [reply ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js:62]: interesting. we do have existing code that may show more decimals. Not finding specific reasoning as to why these numbers were chosen. That said, since this value is specifically for ETH tokens, 8 seems fine to me as it's the fallback you mentioned here and our fiat decimals are limited. Thanks for pointing this out! 

Screenshot 2024-04-30 at 10 51 59 PM

Comment (jpuri) [reply ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js]: I updated the PR.

File: ui/hooks/useUserPreferencedCurrency.js [hunk 4]
```diff
@@ -8,6 +8,7 @@ import { getNativeCurrency } from '../ducks/metamask/metamask';
 
 import { PRIMARY, SECONDARY } from '../helpers/constants/common';
 import { EtherDenomination } from '../../shared/constants/common';
+import { ETH_DEFAULT_DECIMALS } from '../pages/confirmations/constants';
```
Comment (digiwand) [inline ui/hooks/useUserPreferencedCurrency.js:11]: I was wondering about how we go about importing logic from pages/confirmations in outside files. Should we utilize the helpers or shared directories for these?

**Review by digiwand — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

File: ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js [hunk 5]
```diff
@@ -179,7 +183,10 @@ export default function ConfirmTokenTransactionSwitch({ transaction }) {
             transaction={transaction}
             ethTransactionTotal={ethTransactionTotal}
             fiatTransactionTotal={fiatTransactionTotal}
-            hexMaximumTransactionFee={hexMaximumTransactionFee}
+            hexMaximumTransactionFee={sumHexes(
+              hexMaximumTransactionFee,
+              layer1GasFee ?? 0x0,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js:188]: Minor, but should this fallback be a string since it's adding hex strings, or will it cast to zero?

**Review by matthewwalsh0 — APPROVED** [review]
