### PR TITLE
fix: cp-12.18.0 use correct networkClientId when switching account

### LINKED ISSUE #32272: [Bug]: EIP7702 - Upgrading an account from Account Details leads to incorrect network if the selected network doesn't match my choice
### Describe the bug

Whenever I try to upgrade an account from the account details modal, if I select a different network from the one I'm currently on, the created tx still refers to the current selected network, and not the one I chose to upgrade my account on

[Extra note] See comment below regarding 12.18.0 vs main

### Expected behavior

Network is switched to whichever one I chose to upgrade my account on?

### Screenshots/Recordings

https://github.com/user-attachments/assets/ce43a4aa-0c59-42ad-abdb-9a64b24ab537

### Steps to reproduce

1. Add BNB
2. Select BNB
3. Click Account Details
4. Click Upgrade Account
5. Select Sepolia
6. See the created tx is for BNB

### Error messages or log output

```shell

```

### Detection stage

On main branch -- meaning it will go on 12.18 version

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Use correct networkClientId when switching account, currently it is using globalNetworkClientId

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32272

## **Manual testing steps**

1. Go to extension
2. Change network to mainnet
3. Switch account type on sepolia - it should work as expected

## **Screenshots/Recordings**

https://github.com/user-attachments/assets/f90d07e0-c3bb-4edc-9b62-a005f04d0240

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/hooks/useNetworkClientId.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    (chainId: CaipChainId) => {
+      const { defaultRpcEndpoint } = getRpcDataByChainId(chainId, evmNetworks);
+      const { networkClientId } = defaultRpcEndpoint;
+      return networkClientId;
+    },
+    [evmNetworks],
+  );
+
+  return { getNetworkClientIdForChainId };
+}
```
Comment (OGPoyraz) [inline ui/pages/confirmations/hooks/useNetworkClientId.ts:24]: Just for my understanding - if this ultimately giving a callback to get `networkClientId` for a `chainId`, wouldn't it be simpler to create an action for `NetworkController#findNetworkClientIdByChainId` so it would just ask controller?

File: ui/pages/confirmations/hooks/useNetworkClientId.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+export function useNetworkClientId() {
+  const multichainNetworkConfigurations = useSelector(
+    getMultichainNetworkConfigurationsByChainId,
+  );
+  const evmNetworks = multichainNetworkConfigurations[1];
+
+  const getNetworkClientIdForChainId = useCallback(
+    (chainId: CaipChainId) => {
+      const { defaultRpcEndpoint } = getRpcDataByChainId(chainId, evmNetworks);
```
Comment (OGPoyraz) [inline ui/pages/confirmations/hooks/useNetworkClientId.ts:16]: Is `defaultRpcEndpoint` here the one user picked or a fixed "default"? If this is not the user picked - this could lead submitting to the wrong one

Comment (jpuri) [reply ui/pages/confirmations/hooks/useNetworkClientId.ts:16]: That was actually my initial approach, check this commit: https://github.com/MetaMask/metamask-extension/pull/32359/commits/6d5117194986be0320f107c7822ce54a55922c87

This hook above get data available in state and thus I thought it is better than async controller call.

File: ui/pages/confirmations/hooks/useNetworkClientId.ts (hunk 1 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/hooks/useNetworkClientId.ts:24]: Closing as this is already tried on this commit https://github.com/MetaMask/metamask-extension/commit/6d5117194986be0320f107c7822ce54a55922c87

**Review by OGPoyraz — DISMISSED** [review]

File: ui/pages/confirmations/hooks/useNetworkClientId.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import { CaipChainId } from '@metamask/utils';
+import { useCallback } from 'react';
+import { useSelector } from 'react-redux';
+
+import { getRpcDataByChainId } from '../../../../shared/modules/network.utils';
+import { getMultichainNetworkConfigurationsByChainId } from '../../../selectors';
+
+export function useNetworkClientId() {
+  const multichainNetworkConfigurations = useSelector(
+    getMultichainNetworkConfigurationsByChainId,
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useNetworkClientId.ts:10]: Can we instead use the existing `selectDefaultRpcEndpointByChainId` to simplify this logic?

And since it simplifies the logic so much, could we remove this hook and just the selector directly in `useEIP7702Account`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/hooks/useNetworkClientId.ts (hunk 3 above)
Comment (jpuri) [reply ui/pages/confirmations/hooks/useNetworkClientId.ts]: PR is updated

**Review by OGPoyraz — DISMISSED** [review]

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
