### PR TITLE
split advancedGasFee by network and erase previous options

### LINKED ISSUE #13800: [Bug]: Enhanced Gas Fee UI saves the same values regardless of network
### Describe the bug

Using the Enhanced Gas Fee UI and ticking the "Always use these values and advanced setting as default." option, the max base fee and priority fee values are saved regardless of blockchain used.

Expectation: values should be saved per blockchain, as different blockchains have widely different gas fees.

### Steps to reproduce

1. Start a 0 ETH transaction to your own address on Ethereum
2. Edit Max Base Fee and Priority Fee. Tick "Always use these values and advanced setting as default."
3. Reject the transaction
4. Switch to another blockchain (for example, Polygon)
5. Start a 0 ETH transaction to your own address
6. Edit gas fee. The gas values will be the same you saved on Ethereum

### Error messages or log output

_No response_

### Version

10.10.1

### Build type

_No response_

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #20573: [Bug]: When selected Advanced gas setting are getting carried over as default from L1 to L2
### Describe the bug

When Advanced settings are used for calculating gas fees on Ethereum Mainnet, they are saved as default and to be applied across all networks despite actual gas fees that are currently on the network (in this example on Linea, other networks could be affected as well).

This should be considered as a severe MM issue:
1. applying, by default, the same value to other networks can lead user to lose money by over paying for the fees
2. or to get their transactions stuck by underestimating the fees on the network

### Steps to reproduce

1. In MM; use Ethereum mainnet.
2. Start to create a tx, when setting the tx fees, go to "advanced" and check the box "save these new values as default"
3. Exit the transaction
4. Switch to Linea testnet network
5. Send a tx by just confirming everything ( no changes in the gas fees )
6. The value you will see in the explorer should be the "advanced ones" from Ethereum mainnet, and not the one that should be adjusted to the in this case Linea testnet.

Screenshot 2023-08-23 at 1 59 19 PM
Screenshot 2023-08-23 at 1 59 07 PM
Screenshot 2023-08-23 at 1 58 55 PM
Screenshot 2023-08-23 at 1 58 46 PM
Screenshot 2023-08-23 at 1 58 14 PM
Screenshot 2023-08-23 at 1 57 45 PM

[https://explorer.goerli.linea.build/tx/0xff741faa3d4f6a2e8299fa4e3f73290599ee28b0ab36ba2f683dd906e2e36775](url)

Screenshot 2023-08-23 at 2 09 50 PM

Nevertheless, this tx was processed on Linea testnet but in fact, would have been stuck on Linea Mainnet (with Max Priority Fee per Gas 0.1 Gwei) as the fas fees at the time of the transaction were the following: 
Screenshot 2023-08-23 at 2 03 43 PM

The same behavior can be reproduced on any other network when switching from Ethereum Mainnet, selecting advanced gas fees, to Polygon, Goerli..

### Error messages or log output

_No response_

### Version

10.34.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

The original discovery is outlined here:
[https://github.com/Consensys/zkevm-monorepo/issues/1214#issuecomment-1690185983](url)

### PR DESCRIPTION
**Pull request by brad-decker**
## Explanation
Splits out the advancedGasFee setting to support a per-network setting keyed by chainId. 

Fixes #13800
FIxes #20573

## Manual Testing Steps
1. Create a transaction using the send flow.
2. On the confirmation screen click "Market" (or whatever it says in the attached screenshot)
Screenshot 2023-08-23 at 3 44 25 PM

3. Click the "advanced" option
Screenshot 2023-08-23 at 3 45 20 PM

4. Set a higher priority and maxFee 
Screenshot 2023-08-23 at 3 45 27 PM

5. Click the checkbox to use these by default. 
6. save options.
7. cancel the confirmation.

Repeat the process on the same network and see that instead of market it says "advanced" and if you click on it you can see your settings applied. 

Switch network and repeat the process and see it says "market" and does not have your advanced settings. Set a DIFFERENT set of values as your advanced setting and save it. Now switch between the two networks and see that your options persist on transactions created on that network but are not applied to other networks or each other. 

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/selectors/selectors.js [hunk 1]
```diff
@@ -1326,23 +1326,26 @@ export function getIsMultiLayerFeeNetwork(state) {
...
-  return state.metamask.advancedGasFee;
-}
-
-/**
- *  To check if the user has set advanced gas fee settings as default with a non empty  maxBaseFee and priotityFee.
- *
- * @param {*} state
- * @returns Boolean
- */
-export function getIsAdvancedGasFeeDefault(state) {
```
Comment (brad-decker) [inline ui/selectors/selectors.js:1341]: This selector was dead code

File: app/scripts/migrations/097.ts
Comment (Gudahtt) [inline app/scripts/migrations/097.ts:1]: Since we're considering this for v10.35.x, could you re-number this as 92.2? Or 92.3 if #20586 gets merged first.

There are migrations on `develop` that won't be on v10.35.x, so numbering this as v97 would force us to re-order it when cherry-picking it in (and we'd have to re-number every other pending migration in the sync PR)

File: app/scripts/migrations/097.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+function changeShapeAndRemoveOldAdvancedGasFeePreference(
+  state: Record<string, any>,
+) {
+  if (isNullOrUndefined(state.PreferencesController)) {
+    return;
+  }
+
+  state.PreferencesController = {
+    ...(state.PreferencesController ?? {}),
+    advancedGasFee: {},
```
Comment (Gudahtt) [inline app/scripts/migrations/097.ts:44]: If we erase the `advancedGasFee` property completely, we lose information about whether the user had set this to something before. We may want to alert users who had used this feature that we're resetting it.

Perhaps we could set a flag somewhere (maybe in the app state controller?) to show whether a user had their advanced gas fee setting erased? Then we could use that to trigger a Whats New announcement

File: app/scripts/migrations/097.ts
Comment (brad-decker) [reply app/scripts/migrations/097.ts:1]: Will do.

Comment (brad-decker) [reply app/scripts/migrations/097.ts:1]: Changed to 92.3 so it won't conflict with 20586

File: app/scripts/migrations/097.ts (hunk 2 above)
Comment (brad-decker) [reply app/scripts/migrations/097.ts]: I also asked for copy for the whats new announcement to be added later.

File: app/_locales/en/messages.json [hunk 3]
```diff
@@ -3346,9 +3341,6 @@
   "priorityFee": {
     "message": "Priority fee"
   },
-  "priorityFeeProperCase": {
```
Comment (Gudahtt) [inline app/_locales/en/messages.json:3349]: Nit: it seems that a bunch of the changes are related to removing this message. It's not clear how this relates to the other changes though. Could this be done in a separate PR? That would help minimize the size of this hotfix.

File: app/scripts/controllers/preferences.test.js [hunk 4]
```diff
@@ -21,11 +21,11 @@ const NETWORK_CONFIGURATION_DATA = {
     rpcPrefs: {},
   },
 };
-describe('preferences controller', () => {
+describe('preferences controller', function () {
```
Comment (Gudahtt) [inline app/scripts/controllers/preferences.test.js:24]: Nit: accidental auto-formatter changes? I thought arrow functions were fine in Jest tests.

File: app/scripts/controllers/preferences.test.js [hunk 5]
```diff
@@ -243,74 +243,79 @@ describe('preferences controller', () => {
...
       expect(
         preferencesController.store.getState().openSeaEnabled,
       ).toStrictEqual(true);
     });
   });
 
-  describe('setAdvancedGasFee', () => {
-    it('should default to null', () => {
+  describe('setAdvancedGasFee', function () {
+    it('should default to null', function () {
```
Comment (Gudahtt) [inline app/scripts/controllers/preferences.test.js:262]: Updated test description:
```suggestion
    it('should default to an empty object', function () {
```

File: app/scripts/migrations/092.3.ts [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+  meta: { version: number };
+  data: Record<string, unknown>;
+};
+
+export const version = 92.3;
+
+/**
+ * This migration does the following:
+ *
+ * - Deletes currently stored advancedGasFee in preferences controller, replacing the default with an empty object
```
Comment (Gudahtt) [inline app/scripts/migrations/092.3.ts:14]: Nit: We should explain the `hadAdvancedGasFeesSetPriorToMigration92_3` flag here as well

File: app/scripts/migrations/092.3.ts [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+
+function migrateData(state: Record<string, unknown>): void {
+  changeShapeAndRemoveOldAdvancedGasFeePreference(state);
+}
+
+function changeShapeAndRemoveOldAdvancedGasFeePreference(
+  state: Record<string, any>,
+) {
+  if (isNullOrUndefined(state.PreferencesController)) {
+    return;
```
Comment (Gudahtt) [inline app/scripts/migrations/092.3.ts:39]: Nit: It'd be nice to have a warning here, so that we have this as a clue in the Sentry breadcrumbs if we're investigating an error that might be related
```suggestion
    log.warn(`Migration #${version}: preferences controller null or undefined, skipping migration`)
    return;
```

File: app/scripts/migrations/092.3.ts [hunk 8]
```diff
@@ -0,0 +1,52 @@
...
+  }
+
+  state.AppStateController = {
+    ...(state.AppStateController ?? {}),
```
Comment (Gudahtt) [inline app/scripts/migrations/092.3.ts:43]: Nit: Perhaps we should validate that `state.AppStateController` and `state.PreferencesController` are objects first? If it's some non-nullish unexpected type, this might make a mess of this state.

File: app/scripts/migrations/092.3.test.ts [hunk 9]
```diff
@@ -0,0 +1,132 @@
...
+  useAddressBarEnsResolution: true,
+  infuraBlocked: null,
+  ledgerTransportType: 'U2F',
+  snapRegistryList: {},
+  transactionSecurityCheckEnabled: false,
+  theme: 'OS',
+  isLineaMainnetReleased: false,
+};
+
+const PREFERENCES_CONTROLLER_MOCK_2 = {
```
Comment (Gudahtt) [inline app/scripts/migrations/092.3.test.ts:44]: Nit: Maybe it would be better to inline these added properties? So that it's more clear in each test what the start conditions are

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js [hunk 10]
```diff
@@ -39,7 +47,7 @@ const AdvancedGasFeeDefaults = () => {
 
   const handleUpdateDefaultSettings = () => {
     if (isDefaultSettingsSelected) {
-      dispatch(setAdvancedGasFee(null));
+      dispatch(setAdvancedGasFee({ chainId, gasFeePreferences: undefined }));
```
Comment (Gudahtt) [inline ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js:50]: Looks like the type for `setAdvancedGasFee` has changed here - we should update the type in `actions.ts` accordingly

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js [hunk 11]
```diff
@@ -82,13 +93,7 @@ const AdvancedGasFeeDefaults = () => {
...
         onChange={handleUpdateDefaultSettings}
         isDisabled={gasErrors.maxFeePerGas || gasErrors.maxPriorityFeePerGas}
-        label={
-          isDefaultSettingsSelected
-            ? t('advancedGasFeeDefaultOptOut')
-            : t('advancedGasFeeDefaultOptIn', [
-                <strong key="default-value-change">{t('newValues')}</strong>,
-              ])
-        }
+        label={t('advancedGasFeeDefaultOptIn', [capitalize(networkIdentifier)])}
```
Comment (Gudahtt) [inline ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js:96]: Good catch, this is much nicer now that the same message is used for both states

**Comment by Gudahtt** [comment]
Great work! had a few suggestions but nothing major.

The e2e tests are failing because we need an errors state snapshot update due to the new property. You can fix it by running `yarn test:e2e:single --browser chrome test/e2e/tests/errors.spec.js --update-snapshot` locally (after creating a test build, e.g. `yarn start:test`  for a quick build).

File: app/scripts/controllers/preferences.test.js (hunk 4 above)
Comment (brad-decker) [reply app/scripts/controllers/preferences.test.js:24]: Probably before my eslint restarted and realized it was a jest test now I'll fix.

**Review by pedronfigueiredo — DISMISSED** [review]

File: app/scripts/migrations/092.3.ts (hunk 8 above)
Comment (DDDDDanica) [reply app/scripts/migrations/092.3.ts:43]: We could also add validation of `advancedGasFee` property exists in `state.PreferencesController`?

File: app/_locales/en/messages.json (hunk 3 above)
Comment (brad-decker) [reply app/_locales/en/messages.json:3349]: Reverted these changes in latest.

File: app/scripts/migrations/092.3.ts (hunk 8 above)
Comment (brad-decker) [reply app/scripts/migrations/092.3.ts:43]: @Gudahtt should I just skip setting the trait entirely if its some non-nullish unexpected type?

Comment (Gudahtt) [reply app/scripts/migrations/092.3.ts:43]: I guess so, yeah. The pattern in other migrations for when we encounter invalid state is to call `captureException` and return state unchanged, halting the migration

Comment (brad-decker) [reply app/scripts/migrations/092.3.ts:43]: Unless i'm mistaken... in 094.ts we use captureException, but we still modify the meta.version number? That seems like it could cause further breakages if we make future migrations that rely upon the state that 094 migrated us to.

Comment (brad-decker) [reply app/scripts/migrations/092.3.ts:43]: captureException doesn't halt execution right?

File: app/scripts/migrations/092.3.ts (hunk 7 above)
Comment (brad-decker) [reply app/scripts/migrations/092.3.ts:48]: added in latest.

File: app/scripts/migrations/092.3.ts (hunk 6 above)
Comment (brad-decker) [reply app/scripts/migrations/092.3.ts]: done

File: app/scripts/controllers/preferences.test.js (hunk 4 above)
Comment (brad-decker) [reply app/scripts/controllers/preferences.test.js]: done

File: ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js (hunk 10 above)
Comment (brad-decker) [reply ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js:50]: Thanks for catching this, done in latest

File: app/_locales/en/messages.json (hunk 3 above)
Comment (brad-decker) [reply app/_locales/en/messages.json:3349]: or not. thought i got them all. fixing this now

Comment (brad-decker) [reply app/_locales/en/messages.json]: Now these changes have been excluded

File: app/scripts/migrations/092.3.test.ts (hunk 9 above)
Comment (brad-decker) [reply app/scripts/migrations/092.3.test.ts]: Done.

File: app/scripts/migrations/092.3.ts (hunk 8 above)
Comment (Gudahtt) [reply app/scripts/migrations/092.3.ts]: That's correct, it doesn't halt execution. And also you are correct that it could affect later migrations, but those later migrations should also perform adequate checks and bail in the same way if corruption is detected (where "corruption" might mean "a previous required migration was not run").

Comment (Gudahtt) [reply app/scripts/migrations/092.3.ts]: Oh also, the intent behind capturing this error is that usually if such a scenario would occur, we'd discover it in Sentry and fix it before much time has passed.

File: app/scripts/migrations/092.3.ts [hunk 12]
```diff
@@ -0,0 +1,92 @@
...
+  migrateData(versionedData.data);
+  return versionedData;
+}
+
+function migrateData(state: Record<string, unknown>): void {
+  changeShapeAndRemoveOldAdvancedGasFeePreference(state);
+}
+
+function changeShapeAndRemoveOldAdvancedGasFeePreference(
+  state: Record<string, any>,
```
Comment (Gudahtt) [inline app/scripts/migrations/092.3.ts:42]: The use of `any` here is disabling type checking. Could we use `unknown` here instead?

Comment (brad-decker) [reply app/scripts/migrations/092.3.ts:42]: Absolutely

File: app/scripts/migrations/092.3.ts [hunk 13]
```diff
@@ -0,0 +1,92 @@
...
+      new Error(
+        `typeof state.AppStateController is ${typeof state.AppStateController}`,
+      ),
+    );
+  } else {
+    state.AppStateController.hadAdvancedGasFeesSetPriorToMigration92_3 =
+      hadFeesSet;
+  }
+
+  if (isObject(state.PreferencesController) === false) {
```
Comment (Gudahtt) [inline app/scripts/migrations/092.3.ts:70]: Typically these "corrupted state" checks are done prior to any changes to state. Maybe that would be better here to? Seems easier to reason about the corrupted state scenario in that case, no need to worry about a partial migration. This check helps with type narrowing as well

File: ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.js [hunk 14]
```diff
@@ -142,7 +142,7 @@ const EditGasToolTip = ({
               fontWeight={FontWeight.Bold}
               className="edit-gas-tooltip__container__label"
             >
-              {t('priorityFeeProperCase')}
+              {t('priorityFee')}
```
Comment (Gudahtt) [inline ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.js:145]: Nit: This seems like another change that we could exclude from this PR, to reduce the diff of the hotfix and avoid conflicts

File: app/scripts/migrations/092.3.ts (hunk 13 above)
Comment (brad-decker) [reply app/scripts/migrations/092.3.ts]: Yeah, as I was doing the unknown change above I realized I kind of had to do this or else have fairly verbose code anyways. It doesn't make sense to have a partial migration... the key in either would be in a weird out of sync state if either of them completed successfully.

File: ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.js (hunk 14 above)
Comment (brad-decker) [reply ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.js]: Sorry, must have missed this one when I was undoing those changes. Pushed changes now

**Comment by brad-decker** [comment]
just updated branch from develop for a fresh test run

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by HowardBraham — APPROVED** [review]
