### PR TITLE
Ensure smart contract interactions are properly represented on the confirm screen

### LINKED ISSUE #15413: [Bug]: Send Amount disappears on Edit Send tx to a Contract
### Describe the bug

**Problem**: when I edit a Send tx to a Contract, if I delete the Amount and I click Next I see that no amount appears on the tx info, instead of showing a 0. It disappears the token name and it's displayed as a Contract Interaction instead of a simple Send

https://user-images.githubusercontent.com/54408225/182384599-95694e51-d49a-498f-a070-d16e5c7357a2.mp4

### Steps to reproduce

1. Click Send
2. Introduce Contract recipient. I.e. `0x48f874C1Ea87981F71E6D615D317F90c57Ccf448` on Rinkeby
3. Introduce amount and click Next
4. Click Edit Tx
5. Empty Amount value
6. Click Next
7. Check no 0 appears on tx info

### Error messages or log output

_No response_

### Version

10.18.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes: https://github.com/MetaMask/metamask-extension/issues/15413

The problem was that we were representing a contract interaction as a simple send when first arriving at the confirm screen. The solution is to ensure that if we are sending to a contract address, we apply the contract interaction type to the transaction when creating it from the send screen.

Some other changes were needed to get this fully working:
- added `TRANSACTION_TYPES.CONTRACT_INTERACTION` as a valid transaction type when adding a new unapproved transaction
- added a suffix to the currency display on the confirm screen if it is a contract interaction and no eth logo is being shown, so that the user has the information they need about what value would be sent to the contract
- fixed the `isSmartContractAddress` function which was previously broken because it was attempting to get the wrong property from the result of `readAddressAsContract()`

Before:

https://user-images.githubusercontent.com/7499938/182645886-491a74e1-aa42-4026-8823-e27e1631f3af.mp4

After:

https://user-images.githubusercontent.com/7499938/182644897-94f850d3-af66-4c5a-8dd5-be0ea41ca6df.mp4

### CODE REVIEW

File: ui/pages/send/send.constants.js [hunk 1]
```diff
@@ -47,6 +47,11 @@ const ENS_ILLEGAL_CHARACTER = 'ensIllegalCharacter';
 const ENS_UNKNOWN_ERROR = 'ensUnknownError';
 const ENS_REGISTRATION_ERROR = 'ensRegistrationError';
 
+const RECIPIENT_TYPES = {
+  SMART_CONTRACT: 'SMART_CONTRACT',
+  NON_CONTRACT: 'NON_CONTRACT',
+};
```
Comment (brad-decker) [inline ui/pages/send/send.constants.js:53]: Love this.

**Review by brad-decker — DISMISSED** [review]
Good work!

**Review by brad-decker — DISMISSED** [review]

File: ui/ducks/send/send.js [hunk 2]
```diff
@@ -1875,8 +1883,12 @@ export function updateRecipientUserInput(userInput) {
...
     const inputIsValidHexAddress = isValidHexAddress(userInput);
     let isProbablyAnAssetContract = false;
+    let smartContractAddress;
     if (inputIsValidHexAddress) {
-      const smartContractAddress = await isSmartContractAddress(userInput);
+      smartContractAddress = await isSmartContractAddress(userInput);
+      if (smartContractAddress) {
+        dispatch(actions.updateRecipientType(RECIPIENT_TYPES.SMART_CONTRACT));
+      }
       if (smartContractAddress) {
```
Comment (adonesky1) [inline ui/ducks/send/send.js:1892]: is there a reason you made a new `if (smartContractAddress)` conditional? The same if statement is right below on line 1892?

Comment (danjm) [reply ui/ducks/send/send.js:1892]: uh, no... I originally had this outside the if block two lines above, and then copy pasted it to here, will refactor

Comment (danjm) [reply ui/ducks/send/send.js]: changed in latest commit

File: ui/ducks/send/send.js [hunk 3]
```diff
@@ -1907,6 +1917,7 @@ export function updateRecipientUserInput(userInput) {
           useTokenDetection,
           tokenAddressList,
           isProbablyAnAssetContract,
+          smartContractAddress,
```
Comment (adonesky1) [inline ui/ducks/send/send.js:1920]: is this being used? Sorry If I'm missing it? `validateRecipientUserInput` doesn't appear to make use of it?

Comment (danjm) [reply ui/ducks/send/send.js:1920]: no, will remove

Comment (danjm) [reply ui/ducks/send/send.js]: removed

File: ui/ducks/send/send.js [hunk 4]
```diff
@@ -1875,9 +1883,11 @@ export function updateRecipientUserInput(userInput) {
 
     const inputIsValidHexAddress = isValidHexAddress(userInput);
     let isProbablyAnAssetContract = false;
+    let smartContractAddress;
```
Comment (adonesky1) [inline ui/ducks/send/send.js:1886]: since this is not longer passed to the validation method this can go back to being a const inside the `if (inputIsValidHexAddress) {` conditional

Comment (danjm) [reply ui/ducks/send/send.js]: done

Comment (danjm) [reply ui/ducks/send/send.js]: linting should tell me this stuff

**Review by adonesky1 — DISMISSED** [review]
Not a blocker since we're trying to get this out the door but lets note that we should make test cases for this?

**Comment by danjm** [comment]
>Not a blocker since we're trying to get this out the door but lets note that we should make test cases for this?

Absolutely. I am preparing tests for PRs I have merged over the past couple of day, and will submit another PR for those

**Review by brad-decker — DISMISSED** [review]

**Review by brad-decker — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
