### PR TITLE
fix: trezor preflight device check cp-13.29.0

### LINKED ISSUE #42269: [Bug]: Revert Trezor error handling
### Describe the bug

The trezor error handling system is adding too much friction to the signing flows. This is due to the fact that we must open the trezor suite app in a popup to perform any device state checks. We are reverting this change now. 

### Expected behavior

the user should not be warned that the device is locked or disconnected since the trezor suite app already handles these states. 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. connect a trezor wallet
2. add funds to the wallet
3. lock the trezor device
4. perfom a send
5. click on connect Trezor
6. notice it brings you to the trezor suite popup
7. the popup closes and the modal says that the device is locked
8. unlock the device
9. click connect ledger again
10. you should be able to complete the transaction

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.29.0

### Build type

None

### Browser

Brave, Firefox, Chrome, Microsoft Edge

### Operating system

MacOS, Windows

### Hardware wallet

Trezor

### Additional context

_No response_

### Severity

- high severity since we do not want this going into the release.

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This fixes the trezor preflight to skip the capabilities check that added friction to the signing. 

## **Changelog**

CHANGELOG entry: Removes the interactive check from the trezor preflight.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/42269

## **Manual testing steps**

1. Use a trezor account
2. Start a dapp transaction
3.  Disconnect the device
4. Click connect and see the hardware wallet error modal
5. Plug in and unlock the device
6. See confirm and no sdk/iframe popup appear

### **After**

https://github.com/user-attachments/assets/18981b4c-567d-4b64-9b8c-0d1e23123193

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Changes hardware-wallet preflight behavior for Trezor, which can affect when/where user-facing errors surface during signing. While the change is scoped, it alters connection/readiness assumptions in a critical flow.
> 
> **Overview**
> Simplifies Trezor preflight readiness checks so `ensureDeviceReady` only verifies a WebUSB connection (connects if needed) and no longer fetches/validates device features (lock state, initialization, session, message-size limits, or capabilities), leaving those checks to Trezor Connect during signing.
> 
> Removes the Trezor Suite model/session handling helper and rewrites tests to match the new behavior, while keeping capability validation as a standalone `validateCapabilities` method with updated coverage and metadata assertions.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 6ded58ad4282dcba57ad678a470c5cdd84fdf7dd. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts [hunk 1]
```diff
@@ -163,45 +149,13 @@ export class TrezorAdapter implements HardwareWalletAdapter {
...
-   *
-   * @param payload - The device feature payload to validate
-   */
-  #validateDeviceState(payload: TrezorFeaturesPayload): void {
-    // NOTE: Model one is always locked, it will only become unlocked when performing a transaction.
-    if (!payload.unlocked && !isTrezorModelOne(payload.model)) {
-      throw createHardwareWalletError(
-        ErrorCode.AuthenticationDeviceLocked,
-        HardwareWalletType.Trezor,
-        'Trezor is not unlocked. Please unlock your device.',
```
[the remark this answers is not in the document]
Comment (montelaidev) [reply ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:177]: Will be used in later features.

**Review by mathieuartu — COMMENTED** [review]
Looks good, but lacking context. Happy to provide the second approval after a first reviewer with more context approves (probably @david0xd ?)

**Review by gantunesr — DISMISSED** [review]

**Comment by gantunesr** [comment]
Looks good. Did not test

@montelaidev can you add videos of the fix?

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts [hunk 2]
```diff
@@ -1,39 +1,17 @@
 import { ErrorCode, HardwareWalletError } from '@metamask/hw-wallet-sdk';
-import { getTrezorFeatures } from '../../../store/actions';
```
Comment (david0xd) [inline ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:2]: This is now probably unused.

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts [hunk 3]
```diff
@@ -222,60 +144,6 @@ export class TrezorAdapter implements HardwareWalletAdapter {
...
 
-  /**
-   * Validate preflight message size for Trezor Model One devices.
-   *
-   * @param model - The device model identifier
-   * @param options - The ensureDeviceReady options containing preflightMessageBytes
-   */
-  #validateModelOneMessageSize(
-    model: string,
-    options?: EnsureDeviceReadyOptions,
```
Comment (david0xd) [inline ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:233]: Should we delete `preflightMessageBytes` from `EnsureDeviceReadyOptions`? Is there anything else using it now?

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts (hunk 2 above)
Comment (david0xd) [reply ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:2]: We should probably remove this action now and its binding in `metamask-controller` as well, if it's not needed anymore.

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts
Comment (david0xd) [inline ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:104]: Since this is now only checking the connection, we should probably update the docstring to something like this:

```typescript
  /**
   * Ensure the device is connected and ready for signing operations.
   *
   * This only verifies a USB connection is present. All other device checks
   * (lock state, initialization, session, capabilities) are handled by the
   * Trezor Connect SDK during the actual signing flow.
   *
   * @returns true if the device is connected.
   */
```

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts (hunk 3 above)
Comment (david0xd) [reply ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:233]: And if do not need this anymore, please check this as well:
https://github.com/MetaMask/metamask-extension/blob/3a864b323d045cbe9edd43463c71109e646d5fd6/ui/contexts/hardware-wallets/useHardwareWalletConnection.ts#L319

Comment (montelaidev) [reply ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:233]: It would be unused now.

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts (hunk 2 above)
Comment (montelaidev) [reply ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:2]: Yes, its dead code, but would be needed if we support multichain accounts for hw accounts.

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.test.ts [hunk 4]
```diff
@@ -213,209 +168,80 @@ describe('TrezorAdapter', () => {
...
-      await expect(adapter.ensureDeviceReady()).rejects.toMatchObject({
-        code: ErrorCode.AuthenticationDeviceLocked,
-      });
+      expect(result).toBe(true);
+      expect(mockGetConnectedTrezorDevices).not.toHaveBeenCalled();
+    });
+  });
 
-      expect(mockOptions.onDeviceEvent).toHaveBeenCalledWith(
+  describe('validateCapabilities', () => {
```
Comment (david0xd) [inline ui/contexts/hardware-wallets/adapters/TrezorAdapter.test.ts:184]: We should probably have one more test for this, testing when things are good:

```typescript
it('does not throw when all required capabilities are present', () => {
      expect(() =>
        adapter.validateCapabilities(
          ['Capability_Bitcoin', 'Capability_Solana', 'Capability_Ethereum'],
          'T',
        ),
      ).not.toThrow();
    });
```

File: ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts (hunk 2 above)
Comment (david0xd) [reply ui/contexts/hardware-wallets/adapters/TrezorAdapter.ts:2]: 🤔 

I'm not sure when that's going to happen, but it sounds like this would be unused for a while. We maybe could remove it for now.

**Review by gantunesr — APPROVED** [review]

**Review by david0xd — APPROVED** [review]

**Review by owencraston — APPROVED** [review]
