### PR TITLE
Ensure approval warning for setApprovalForAll is not shown when revoking

### LINKED ISSUE #15571: [Bug]: confirmPageDialogSetApprovalForAll dialog and red Confirm button shown on the revoke all confirmation screen
### Describe the bug

Revoke All confirmation screen also displays a `Red confirm button and confirmPageDialogSetApprovalForAll dialog`.

Before
Revoke

Develop
Revoke Develop

### Steps to reproduce

1. Navigate to https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#writeContract
2. Connect your wallet
3. Expand `9. setApprovalForAll` enter an address in the operator field and false in the approved field
4. Click write

### Error messages or log output

_No response_

### Version

develop

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/15571

Should be promptly followed by this (non-functional) code cleanup https://github.com/MetaMask/metamask-extension/issues/15805

### CODE REVIEW

File: ui/pages/confirm-approve/confirm-approve.js [hunk 1]
```diff
@@ -172,6 +172,7 @@ export default function ConfirmApprove({
           customTokenAmount={String(customPermissionAmount)}
           dappProposedTokenAmount={tokenAmount}
           currentTokenBalance={tokenBalance}
+          setApproveForAllArg={setApproveForAllArg}
```
Comment (darkwing) [inline ui/pages/confirm-approve/confirm-approve.js:175]: Nit: `setApproveForAllArg` doesn't seem meaningful in name; since it's only used for the warning at the moment, should we call it "showWarning" or something to that effect?

**Review by ryanml — APPROVED** [review]
lgtm aside from @darkwing's nit

File: ui/pages/confirm-approve/confirm-approve.js (hunk 1 above)
Comment (danjm) [reply ui/pages/confirm-approve/confirm-approve.js:175]: Oh, I commented on this in the PR description, although vaguely. "Should be promptly followed by this (non-functional) code cleanup https://github.com/MetaMask/metamask-extension/issues/15805". I wanted to resolve that in another PR because it was pre-existing and used in other places.

**Review by Gtonizuka — APPROVED** [review]

**Review by segun — APPROVED** [review]
