### PR TITLE
fix: Add optional chaining to currencyRates check for stability

### LINKED ISSUE #28750: [Bug]: Extension breaks with an error TypeError: Cannot read properties of undefined (reading 'conversion at LavaPack.loadBundle.n.useTokenFiatAmount when trying to import tokens
### Describe the bug

The issue described tends to occur when a user possesses assets across different networks, switching between networks and importing tokens.
For me It is most likely to manifest after adding a new network and attempting to import tokens while the 'Current network' option is selected. Although exact reproduction steps are not available and this bug also happened to me while importing token for 'All networks' 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/b66ca142-1a2c-4401-9a60-8d5fe23e6744

Screenshot 2024-11-26 at 17 44 05

### Steps to reproduce

1. Have non-imported tokens across different networks
2. Switch networks, import tokens

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

qa-9

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

https://github.com/MetaMask/metamask-extension/issues/28750

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28753?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28750

## **Manual testing steps**

Testing steps in issue. Behavior is inconsistent, hard to replicate consistently.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/hooks/useTokenFiatAmount.js [hunk 1]
```diff
@@ -67,8 +67,8 @@ export function useTokenFiatAmount(
   );
 
   const tokenConversionRate = chainId
-    ? currencyRates[networkConfigurationsByChainId[chainId].nativeCurrency]
-        .conversionRate
+    ? currencyRates?.[networkConfigurationsByChainId[chainId]?.nativeCurrency]
+        ?.conversionRate
     : conversionRate;
```
Comment (sahar-fehri) [inline ui/hooks/useTokenFiatAmount.js:72]: Were you able to repro the linked issue locally? 
From the error linked in the issue i think this optional chaining makes sense

**Review by sahar-fehri — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

**Comment by salimtb** [comment]
LGTM ✅ I couldn't reproduce the issue, but the safe accessor will help us prevent this error.

File: ui/hooks/useTokenFiatAmount.js (hunk 1 above)
Comment (gambinish) [reply ui/hooks/useTokenFiatAmount.js:72]: I wasn't able to reproduce exactly, but I've definitely seen similar bugs from time to time related to currencyRates not yet resolving.
