### PR TITLE
fix: Fix attribution generation

### LINKED ISSUE #28412: [Bug]: Attributions out-of-date
### Describe the bug

The `attributions.txt` file linked in v12.3.0 onwards is outdated. It still reflects the attributions in v12.2.4.

### Expected behavior

The `attributions.txt` for each release should match the dependencies in that release.

### Screenshots/Recordings

_No response_

### Steps to reproduce

The failure was unnoticed because the `attributions:check` command that we rely on can silently fail when the file fails to generate. The generation failed due to the addition of the `postinstall` script.

This problem can be demonstrated with these steps:

* Checkout v12.6.0
* Delete the `postinstall` script, so that the attribution check succeeds
* Run `yarn attributions:generate`, and see that the attributions file is different.

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.3.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

Fix the `attribution:generate` command by ensuring that it is possible to install just production dependencies.

Previously the command `yarn workspaces focus --production` (used to discard development dependencies, keeping just production dependencies installed) would fail because `rimraf` was not found. `rimraf` was a development dependency used in the `postinstall` script. This was resolved by replacing `rimraf` with a Node.js script that does the same thing without needing any dependency.

Once that failure was resolved, another was revealed. The `allow-scripts` step of the installation began failing because there was a package detected that had an install script that was missing from our configuration. This package was in our configuration already, but the `allow-scripts` configuration is sensitive to changes in the directory structure of `node_modules`, and that structure changed due to differences in which packages were hoisted in the production-only install.

That failure was resolved by updating `generate-attributions.sh` to remove the `allow-scripts` plugin while generating attributions. We don't need `postinstall` scripts to run in order to read licences from disk.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28415?quickstart=1)

## **Related issues**

Fixes #28412

## **Manual testing steps**

1. Run `yarn attributions:generate`, and see that it completes successfully
    * Locally, it should also re-install the `allow-scripts` plugin and development dependencies
    * If this command is run with `CI=true` (e.g. `CI=true yarn attributions:generate`), it will skip the step of re-installing the `allow-scripts` plugin and development dependencies. This is what would happen on CI, where the environment gets discarded after this is run so there is no point in re-installing things.

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: development/generate-attributions.sh [hunk 1]
```diff
@@ -38,7 +45,9 @@ main() {
 
   # Check if the script is running in a CI environment (GitHub Actions sets the CI variable to true)
   if [ -z "${CI:-}" ]; then
-    # If not running in CI, restore development dependencies
+    # If not running in CI, restore the allow-scripts plugin and development dependencies.
+    cd "${PROJECT_DIRECTORY}"
```
Comment (Gudahtt) [inline development/generate-attributions.sh:49]: Previously the attempt to re-install development dependencies was also failing, because `yarn` was run in the wrong directory. This is now fixed as well.

File: development/clear-webpack-cache.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+ * This is typically run in the `postinstall` npm/Yarn lifecycle script.
+ */
+async function main() {
+  await fs.rm(WEBPACK_CACHE_DIRECTORY, { force: true, recursive: true });
+}
+
+main().catch((error) => {
+  console.error(error);
+  process.exitCode = 1;
+});
```
Comment (Mrtenz) [inline development/clear-webpack-cache.js:26]: This could be simplified if it was a `.mjs` script, so we can just use top-level await:

```suggestion
/**
 * Clear the Webpack cache.
 *
 * This is typically run in the `postinstall` npm/Yarn lifecycle script.
 */
await fs.rm(WEBPACK_CACHE_DIRECTORY, { force: true, recursive: true });
```

Comment (Gudahtt) [reply development/clear-webpack-cache.js:26]: I've been avoiding the use of top-level await intentionally because I saw it raised as an obstacle for LavaMoat node, which we might at some point start using for all of our development scripts. Not sure that's a reason to avoid it altogether, but.... the CommonJS version seems fine 🤷

**Review by Mrtenz — APPROVED** [review]

**Review by danjm — APPROVED** [review]
