### PR TITLE
fix: unscrollable Remove Snap modal dialog

### LINKED ISSUE #31412: [Bug]: Remove snap modal is unscrollable
### Describe the bug

Remove snap is unscrollable.

modal-dialog-slide-up animation may get stuck causing overflow-y hidden css

### Expected behavior

_No response_

### Screenshots/Recordings

Image

### Steps to reproduce

1. Install https://metamask.github.io/snap-simple-keyring/latest/
2. Add many accounts to cause a scrollbar later (3+ accounts)
3. Go to MetaMask in popup mode or with shortened height
4. Go to Snaps > Uninstall Snaps
5. Click "Remove MetaMask Simple Snap Keyring" 
6. See Remove Snap Modal is unscrollable
7. See "mm-modal-content__dialog" element has modal-dialog-slide-up animation which overrides overflow-y with hidden value 

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.14.2-flask.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

Remove snap is unscrollable.

This is fixed by incorporating ModalBody. This PR also replaces deprecated components with current DS components

~modal-dialog-slide-up animation may get stuck causing overflow-y hidden css. As a workaround, we'll add !important to overflow-y: auto. I've created a [separate ticket](https://github.com/MetaMask/metamask-extension/issues/31405) to address the core issue which is the animation causing the unexpected overflow-y: hidden.~

Usually hidden is shown for my build:
CleanShot 2025-03-28 at 16 00 22

I have had an instance where the same selector set overflow-y auto:
CleanShot 2025-03-28 at 11 34 32@2x

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/31412
Related: https://github.com/MetaMask/metamask-extension/issues/31405 (fix core animation unexpected overflow setting) 

## **Manual testing steps**

1. Install https://metamask.github.io/snap-simple-keyring/latest/
2. Add many accounts to cause a scrollbar later (3+ accounts)
3. Go to MetaMask in popup mode or with shortened height
4. Go to Snaps > Uninstall Snaps
5. Click "Remove MetaMask Simple Snap Keyring" 
6. See Remove Snap Modal is unscrollable
7. See "mm-modal-content__dialog" element has modal-dialog-slide-up animation which overrides overflow-y with hidden value 

### **After**

CleanShot 2025-04-01 at 13 24 13

https://github.com/user-attachments/assets/6e3838ff-61d3-4080-8ba0-d9c454000807

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by montelaidev — DISMISSED** [review]

**Review by GustavoRSSilva — DISMISSED** [review]

File: ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx [hunk 1]
```diff
@@ -91,46 +91,48 @@ export default function KeyringRemovalSnapWarning({
...
+                  {t('backupKeyringSnapReminder')}
+                </BannerAlert>
+                <Box
+                  display={Display.Flex}
+                  justifyContent={JustifyContent.spaceBetween}
+                >
+                  <Text>{t('removeKeyringSnap')}</Text>
+                  <InfoTooltip
+                    contentText={t('removeKeyringSnapToolTip')}
+                    position="top"
```
Comment (georgewrmarshall) [inline ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx:114]: Refactoring to wrap the content of this modal in `ModalBody` which handles the scrolling of the modal

File: ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx [hunk 2]
```diff
@@ -91,46 +91,48 @@ export default function KeyringRemovalSnapWarning({
...
+                    />
+                  );
+                })}
+              </>
+            ) : (
+              <>
                 <BannerAlert
                   severity={BannerAlertSeverity.Warning}
                   className=""
-                  marginBottom={4}
```
Comment (georgewrmarshall) [inline ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx:129]: Removes margins in favor of the `gap={4}` property on `ModalBody`

**Review by georgewrmarshall — DISMISSED** [review]

**Comment by georgewrmarshall** [comment]
Hey @digiwand, I made a small update to refactor the `KeyringSnapRemovalWarning` modal to remove the deprecated JS components and use the `ModalBody` component which handles the scrolling of the Modal content. This should fix the scrolling issue. Let me know if this works.

**Comment by digiwand** [comment]
Hey @georgewrmarshall, this works great! Thanks for hopping in and applying the proper scroll fix + cleanup as opposed to the quick patch I created!

I made one more small update to DRY the code and move a BannerAlert out of the conditional statement (https://github.com/MetaMask/metamask-extension/pull/31413/commits/93197a78a2af6dbf8ea749ba9a13f6a5b35db765). May we get 2 more re-approval here please? cc: @montelaidev @GustavoRSSilva

**Review by georgewrmarshall — APPROVED** [review]
LGTM!

**Review by montelaidev — APPROVED** [review]

**Review by FrederikBolding — APPROVED** [review]
