### PR TITLE
Adjust 'Confirm' button color on setApprovalForAll revocations

### LINKED ISSUE #17466: [Bug]: Confirm button when revoking setApprovalForAll should not be red
### Describe the bug

For the setApprovalForAll confirmation, 
- when giving an allowance (approved(bool) parameter = true), the button should be **red**;
- while when revoking an allowance (approved(bool) parameter = false), the button should be **blue**;

### Steps to reproduce

1. Go to https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#writeContract
2. Connect your wallet
3. Go to setApprovalForAll
4. Input any address and `false` for the approved(bool) parameter
5. Click write
6. See the MM popup and notice the red button

### Error messages or log output

_No response_

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context
Screenshot 2023-01-27 at 12 55 23

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/17466

### Before
Screenshot 2023-01-27 at 12 55 23

### After
Screen Shot 2023-01-31 at 3 33 51 AM
Screen Shot 2023-01-31 at 3 34 11 AM

## Manual Testing Steps
1. Go to https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#writeContract
2. Connect your wallet
3. Go to setApprovalForAll
4. Input any address and `false` for the approved(bool) parameter
5. Click write
6. Ensure the confirm button shows up as blue

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/app/confirm-page-container/confirm-page-container.component.js [hunk 1]
```diff
@@ -277,7 +277,11 @@ const ConfirmPageContainer = (props) => {
                 : onSubmit
             }
             submitText={t('confirm')}
-            submitButtonType={isSetApproveForAll ? 'danger-primary' : 'primary'}
+            submitButtonType={
+              isSetApproveForAll && isApprovalOrRejection
```
Comment (ryanml) [inline ui/components/app/confirm-page-container/confirm-page-container.component.js:281]: Note: `isApprovalOrRejection` is `true` when it is an approval transaction, and `false` when it's a revocation. The naming of the variable seems to imply it is true in both cases. It could likely be named better.

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Review by brad-decker — APPROVED** [review]
