### PR TITLE
chore: Fix flaky snap signature insights tests

### LINKED ISSUE #29227: Fix "Test Snap Signature Insights Old confirmation screen..." flaky tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/116289/workflows/ef67b272-656e-44c1-9248-dd571268ae78/jobs/4356225/tests

### PR DESCRIPTION
**Pull request by pnarayanaswamy**
## **Description**

The sign button is sometimes not enabled after the delay, just added a better waiting condition to wait for the button to be enabled

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29437?quickstart=1)

## **Related issues**

Fixes: [#29227](https://github.com/MetaMask/metamask-extension/issues/29227)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by pedronfigueiredo — APPROVED** [review]

File: test/e2e/helpers.js [hunk 1]
```diff
@@ -724,7 +724,10 @@ async function clickSignOnSignatureConfirmation({
     // so we have to add a small delay as the last alternative to avoid flakiness.
     await driver.delay(regularDelayMs);
   }
-
+  await driver.waitForSelector(
+    { text: 'Sign', tag: 'button' },
+    { state: 'enabled' },
```
Comment (matthewwalsh0) [inline test/e2e/helpers.js:729]: Minor, can we add this argument to `clickElement` to avoid the duplication?

Assuming `clickElement` isn't checking the enabled state.

**Review by matthewwalsh0 — APPROVED** [review]
