### PR TITLE
fix: Clicking on report link does not add external_link_clicked to si…

### LINKED ISSUE #23995: [Bug]: Clicking on false positive, Blockaid link does not add external_link_clicked to signature events
### Describe the bug

Clicking to report a false positive security alerts triggers doesn't add external_link_clicked to the respective signature event. Only no-signature transactions.

Related to: https://github.com/MetaMask/MetaMask-planning/issues/1756
Discovered: https://github.com/MetaMask/metamask-extension/issues/23555#issuecomment-2050547846
[Example metric](https://mixpanel.com/project/2212883/view/2760759/app/events#aVxUP9fS65hJ)

### Expected behavior

Clicking to report a false positive security alerts triggers doesn't add external_link_clicked to the respective transaction and signature events

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Turn on Blockaid in Security Settings
2. Go to test dapp
3. Test PPOM buttons
4. Observe reports

### Error messages or log output

_No response_

### Version

11.13.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pnarayanaswamy**
…gnature events

## **Description**

Fixes the bug that the external_link_clicked property is not added to the Signature approved, signature rejected , transaction approved and transaction rejected events
Adds integration tests to verify the property is added to the metrics

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29969?quickstart=1)

## **Related issues**

Fixes: [#23995](https://github.com/MetaMask/metamask-extension/issues/23995)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/alert-system/general-alert/general-alert.tsx [hunk 1]
```diff
@@ -45,6 +45,7 @@ function ReportLink({
     <Text marginTop={1} display={Display.Flex}>
       {t('somethingDoesntLookRight', [
         <ButtonLink
+          data-testid="alert-provider-report-link"
```
Comment (jpuri) [inline ui/components/app/alert-system/general-alert/general-alert.tsx:48]: We avoid adding `data-testid` in extension, in case its possible to query using button text it may be better.

**Review by pedronfigueiredo — DISMISSED** [review]

File: test/integration/confirmations/signatures/signature-helpers.ts [hunk 2]
```diff
@@ -91,6 +91,51 @@ export const getMetaMaskStateWithUnapprovedPermitSign = (
...
+        securityAlertId: 'ba944b14-aa65-45b5-ae92-f305cdba64c1',
+      },
+    },
+  };
+
+  state.unapprovedTypedMessages = {
+    ...unapprovedTypedMessage,
+  };
+
+  console.log(state);
```
Comment (digiwand) [inline test/integration/confirmations/signatures/signature-helpers.ts:121]:
```suggestion
```

File: test/integration/confirmations/signatures/signature-helpers.ts [hunk 3]
```diff
@@ -91,6 +91,51 @@ export const getMetaMaskStateWithUnapprovedPermitSign = (
   };
 };
 
+export const getMetamaskStateWithMaliciousPermit = (accountAddress: string) => {
+  const pendingPermitId = '48a75190-45ca-11ef-9001-f3886ec2397c';
```
Comment (digiwand) [inline test/integration/confirmations/signatures/signature-helpers.ts:95]: [minor nit] we can move this out to avoid reinstantiating for each getMetamaskStateWithMaliciousPermit call 
```suggestion  
const pendingPermitId = '48a75190-45ca-11ef-9001-f3886ec2397c';

export const getMetamaskStateWithMaliciousPermit = (accountAddress: string) => {
```

**Review by digiwand — CHANGES_REQUESTED** [review]
one thing, I think we should remove the console.log before merging. other than this, Lgtm!

File: ui/components/app/alert-system/general-alert/general-alert.tsx (hunk 1 above)
Comment (digiwand) [reply ui/components/app/alert-system/general-alert/general-alert.tsx:48]: I like this suggestion. I do like using findByText to also test text expectations simultaneously

File: test/integration/confirmations/signatures/permit.test.tsx [hunk 4]
```diff
@@ -250,4 +254,75 @@ describe('Permit Confirmation', () => {
...
+              JSON.stringify({
+                properties: {
+                  external_link_clicked: 'security_alert_support_link',
+                },
+              }),
+            ),
+        );
+
+      expect(updateSignatureEventFragment).toBeDefined();
+    });
```
Comment (OGPoyraz) [inline test/integration/confirmations/signatures/permit.test.tsx:326]: Would it make sense to use Jest's matchers rather than relying on string comparisons?

```suggestion
expect(
      mockedBackgroundConnection.submitRequestToBackground,
    ).toHaveBeenCalledWith(
      'updateEventFragment',
      expect.arrayContaining([
        expect.objectContaining({
          properties: expect.objectContaining({
            external_link_clicked: 'security_alert_support_link',
          }),
        }),
      ]),
    );
```

File: test/integration/confirmations/signatures/signature-helpers.ts (hunk 2 above)
Comment (OGPoyraz) [inline test/integration/confirmations/signatures/signature-helpers.ts:121]: Guessing this is forgotten

File: ui/pages/confirmations/components/confirm/title/title.tsx [hunk 5]
```diff
@@ -23,15 +23,29 @@ import { useIsNFT } from '../info/approve/hooks/use-is-nft';
...
+  const onClickSupportLink = () => {
+    const properties = {
+      properties: {
+        external_link_clicked: 'security_alert_support_link',
+      },
+    };
+    updateSignatureEventFragment(properties);
+    updateTransactionEventFragment(properties, ownerId);
+  };
+
```
Comment (OGPoyraz) [inline ui/pages/confirmations/components/confirm/title/title.tsx:48]: Should we create this callback with `useCallback` if it has `ownerId` dependency?

```suggestion
const onClickSupportLink = useCallback(() => {
       const properties = {
         properties: {
           external_link_clicked: 'security_alert_support_link',
         },
       };
       updateSignatureEventFragment(properties);
       updateTransactionEventFragment(properties, ownerId);
     }, [ownerId]);
```

**Review by ghost — APPROVED** [review]

File: test/integration/confirmations/signatures/signature-helpers.ts (hunk 3 above)
Comment (pnarayanaswamy) [reply test/integration/confirmations/signatures/signature-helpers.ts]: done

File: ui/components/app/alert-system/general-alert/general-alert.tsx (hunk 1 above)
Comment (pnarayanaswamy) [reply ui/components/app/alert-system/general-alert/general-alert.tsx:48]: But text can change, making tests flaky and prone to failure due to content updates. Coupling tests to specific text, especially when supporting multiple languages is not recommended. Why do we not want to use test-ids? it supports testing and makes things stable.

File: ui/pages/confirmations/components/confirm/title/title.tsx (hunk 5 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/title/title.tsx]: I think only fallback is settling in the `updateTransactionEventFragment` not the given `transactionId` (in this case `ownerId`) In my opinion, it's good practice to have it right in order to prevent any side effects.

File: test/integration/confirmations/transactions/contract-interaction.test.tsx [hunk 6]
```diff
@@ -491,4 +491,52 @@ describe('Contract Interaction Confirmation', () => {
...
+                properties: {
+                  external_link_clicked: 'security_alert_support_link',
+                },
+              }),
+            ),
+        );
+
+      expect(updateTransactionEventFragment).toBeDefined();
+    });
+  });
```
Comment (OGPoyraz) [inline test/integration/confirmations/transactions/contract-interaction.test.tsx:541]: Do we want to change this to use jest matchers as well?

Comment (pnarayanaswamy) [reply test/integration/confirmations/transactions/contract-interaction.test.tsx]: done

File: ui/pages/confirmations/components/confirm/title/title.tsx (hunk 5 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/title/title.tsx]: Due to having `Rendered more hooks than during the previous render.` after using `useCallback` hook we will handle this later.

**Review by OGPoyraz — APPROVED** [review]

File: ui/components/app/alert-system/general-alert/general-alert.tsx (hunk 1 above)
Comment (digiwand) [reply ui/components/app/alert-system/general-alert/general-alert.tsx:48]: > text can change 
I think this is what the test could also test for to ensure we have the expected text. 

It is a consideration though that e.g. if we did tests for the text, would we be okay with it affecting snapshot tests that render this component. 

It is not common for us to test for multiple languages. That's a good point though to be interoperable between languages.

I don't think this is a blocker. @jpuri could you provide more details on
> We avoid adding data-testid in extension

**Review by digiwand — APPROVED** [review]
