### PR TITLE
fix: Destructure `openExtensionInBrowser` from `global` in `Routes` component cp-13.2.2

### LINKED ISSUE #35573: TypeError: Cannot read properties of undefined (reading 'getExtensionURL')
Sentry Issue: [METAMASK-XQ6Y](https://metamask.sentry.io/issues/6849515199/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'getExtensionURL')
  at exports.defaultopenExtensionInBrowser (app/scripts/platforms/extension.js:94:31)
  at h (ui/pages/routes/routes.component.tsx:450:7)
  at fn (ui/index.js:231:5)
  at tryFn (shared/lib/trace.ts:275:13)
  at tryCatchMaybePromise (shared/lib/trace.ts:418:20)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by MajorLift**
## **Description**

Fixes issue with `Routes` component incorrectly sourcing the `ExtensionPlatform` class's `openExtensionInBrowser` method from `globalThis` instead of `global`. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/35587?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: #35573 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/routes/routes.component.tsx [hunk 1]
```diff
@@ -456,13 +456,17 @@ export default function Routes() {
...
+      'openExtensionInBrowser' in global.platform &&
+      global.platform.openExtensionInBrowser &&
+      typeof global.platform.openExtensionInBrowser === 'function' &&
       showExtensionInFullSizeView &&
-      windowType === ENVIRONMENT_TYPE_POPUP &&
-      openExtensionInBrowser
+      windowType === ENVIRONMENT_TYPE_POPUP
     ) {
-      openExtensionInBrowser();
+      global.platform.openExtensionInBrowser();
```
Comment (MajorLift) [inline ui/pages/routes/routes.component.tsx]: @HowardBraham We *could* get away with just this, since `in` is only needed for narrowing by the TypeScript compiler and not at runtime, and removing the `typeof` checks doesn't affect any of the other logic. The only real edge case to guard against is `global.platform` being undefined, which I encountered at some point in CI.

edit: Added optional chaining after `openExtensionInBrowser`
```suggestion
      showExtensionInFullSizeView &&
      windowType === ENVIRONMENT_TYPE_POPUP
    ) {
      global.platform?.openExtensionInBrowser?.();
    }
```

I just wanted to be extra careful and cover all bases to prevent any other runtime errors, but I agree it's probably unnecessary. What do you think about applying the above?

Comment (HowardBraham) [reply ui/pages/routes/routes.component.tsx]: What circumstance would make the previous code error, but the new suggestion be okay?

Comment (MajorLift) [reply ui/pages/routes/routes.component.tsx]: If `global.platform` is not assigned an `ExtensionPlatform` instance, making `global.platform.openExtensionInBrowser` undefined, invoking it without the guards in the previous code would result in an uncaught error. I edited the suggestion with an additional optional chaining operator to account for this, so we still probably don't need all of the verboseness.

This appears to be a known issue. Search results for existing optional chaining usage for `global.platform`:
- `global.platform?.`
https://github.com/search?q=repo%3AMetaMask%2Fmetamask-extension+global.platform%3F.&type=code
- `global.platform.openExtensionInBrowser?.`
https://github.com/search?q=repo%3AMetaMask%2Fmetamask-extension+global.platform.openExtensionInBrowser%3F.&type=code

Comment (HowardBraham) [reply ui/pages/routes/routes.component.tsx]: Oh yeah, there we go, the second optional chaining makes it work

File: ui/pages/routes/routes.component.tsx [hunk 2]
```diff
@@ -456,13 +456,17 @@ export default function Routes() {
...
   useEffect(() => {
     const windowType = getEnvironmentType();
-    const { openExtensionInBrowser } = globalThis.platform ?? {};
     if (
+      'platform' in global &&
+      typeof global.platform === 'object' &&
+      global.platform &&
+      'openExtensionInBrowser' in global.platform &&
+      global.platform.openExtensionInBrowser &&
+      typeof global.platform.openExtensionInBrowser === 'function' &&
```
Comment (MajorLift) [inline ui/pages/routes/routes.component.tsx]:
```suggestion
```

File: ui/pages/routes/routes.component.tsx (hunk 1 above)
Comment (MajorLift) [inline ui/pages/routes/routes.component.tsx]:
```suggestion
      global.platform?.openExtensionInBrowser?.();
```

Comment (MajorLift) [reply ui/pages/routes/routes.component.tsx]: Applied here! https://github.com/MetaMask/metamask-extension/pull/35587/commits/6804ee2aa03a321b1c09280f0c22941f5b0b87c6

**Review by HowardBraham — DISMISSED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Comment by DDDDDanica** [comment]
LGTM ! Thanks for the fix ~

**Review by HowardBraham — APPROVED** [review]

**Comment by aorlovskiy** [comment]
Fix for https://github.com/MetaMask/metamask-extension/issues/35693
