### PR TITLE
fix: Fix bundle size tracking

### LINKED ISSUE #29485: [Bug]: Fix bundle size tracking
### Describe the bug

The bundle size measurement and tracking was accidentally broken in #29408. That PR intended to remove two broken performance tests, but the bundle size measurement was accidentally removed as well at the same time.

### Expected behavior

* Bundle size should be linked in each `metamaskbot` comment
* Bundle size should be tracked here over time: https://github.com/MetaMask/extension_bundlesize_stats

### Screenshots/Recordings

_No response_

### Steps to reproduce

The bug can be seen in any `metamaskbot` comment in a PR. Example: https://github.com/MetaMask/metamask-extension/pull/29408#issuecomment-2557737474

See the "mv3: [Bundle Size Stats](https://output.circle-artifacts.com/output/job/81035b14-9812-43ad-816c-716df4eeffea/artifacts/0/test-artifacts/chrome/bundle_size.json)" entry in that example. The link fails to load because the file is missing.

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

main

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

The bundle size tracking was accidentally broken in #29408. This restores the bundle size tracking.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29486?quickstart=1)

## **Related issues**

Fixes #29485

Resolves bug introduced by #29408

## **Manual testing steps**

1. Check the "mv3: Bundle Size Stats" link in the `metamaskbot` comment
2. Once this is merged, check the bundle size tracker to ensure it's working again: https://github.com/MetaMask/extension_bundlesize_stats
  * Unfortunately I am not sure how to easily test this on the PR. The tracker is only updated when commits are made to `main`.

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: test/e2e/mv3-perf-stats/bundle-size.js [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+];
+
+const BackgroundFileRegex = /background-[0-9]*.js/u;
+const CommonFileRegex = /common-[0-9]*.js/u;
+const UIFileRegex = /ui-[0-9]*.js/u;
+
+async function main() {
+  const { argv } = yargs(hideBin(process.argv)).usage(
+    '$0 [options]',
+    'Run a page load benchmark',
```
Comment (Gudahtt) [inline test/e2e/mv3-perf-stats/bundle-size.js:40]: Pre-existing erroneous description:
```suggestion
    'Capture bundle size stats',
```

**Review by ghost — APPROVED** [review]

File: test/e2e/mv3-perf-stats/bundle-size.js
Comment (Gudahtt) [inline test/e2e/mv3-perf-stats/bundle-size.js:1]: This file was restored exactly as it was before, apart from the description change here: https://github.com/MetaMask/metamask-extension/pull/29486/commits/e41b5832d71db9157875f4fa96a40dc8153aaed6

**Review by mikesposito — COMMENTED** [review]
Shouldn't we see the section again in this PR's build announce comment?

File: .circleci/config.yml [hunk 2]
```diff
@@ -1270,6 +1274,36 @@ jobs:
           paths:
             - test-artifacts
 
+  bundle-size:
```
Comment (Gudahtt) [inline .circleci/config.yml:1277]: This step used to also measure some other MV3-related stats, which have since been removed. It has been renamed to reflect that it now just measures bundle size. The steps are identical to what they were before, except with the deleted tests removed.

File: package.json [hunk 3]
```diff
@@ -28,6 +28,7 @@
     "start:test:mv2:flask": "ENABLE_MV3=false yarn start:test:flask --apply-lavamoat=false --snow=false",
     "start:test:mv2": "ENABLE_MV3=false BLOCKAID_FILE_CDN=static.cx.metamask.io/api/v1/confirmations/ppom yarn start:test --apply-lavamoat=false --snow=false",
     "benchmark:chrome": "SELENIUM_BROWSER=chrome ts-node test/e2e/benchmark.js",
+    "bundle-size": "SELENIUM_BROWSER=chrome ts-node test/e2e/mv3-perf-stats/bundle-size.js",
```
Comment (Gudahtt) [inline package.json:31]: The old version of this command ran a few different types of tests. When restoring this, I renamed it to `bundle-size` because it's now only measuring bundle size.

**Comment by Gudahtt** [comment]
>Shouldn't we see the section again in this PR's build announce comment?

We do, it is here:

>mv3: [Bundle Size Stats](https://output.circle-artifacts.com/output/job/63cec63c-9bbc-497a-b5d8-e2aa7f5c37bd/artifacts/0/test-artifacts/chrome/bundle_size.json)

**Comment by mikesposito** [comment]
Oh, I see sorry, the bundle size commitment to the external repo was also disabled, gotcha.

**Review by mikesposito — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
Oh sorry you meant the part where it says whether size has increased or not. Sorry I hadn't noticed that was missing, but you're right, it appears to be due to the lack of data on the `main` branch commit in the bundle size tracker. Seeing this error from the logs:

>Error constructing bundle size diffs results: 'TypeError: Cannot read properties of undefined (reading 'background')'

The value that is `undefined` is the merge base commit.

**Review by FrederikBolding — APPROVED** [review]

**Review by desi — APPROVED** [review]
Read through all the comments and checked that I also see the bundle size in the comment
