### PR TITLE
fix: asset picker bug

### LINKED ISSUE #25575: [Bug]: send page modal styling broken
### Describe the bug

At least three regressions have occurred to the `AssetPickerModal` component:

- The symbols no longer show for each list item (regressed by #24223)
- Blocked token symbols (e.g., BNB on Ethereum Mainnet) are no longer greyed out in the UI despite still being inert 
- Token names are not truncated

### Expected behavior

- Symbols should show on top of the token name (see: screenshots)
- Disabled item styling should be restored
- Longer token names should be truncated

### Current

Screenshot 2024-06-27 at 5 41 23 PM

### Expected

Screenshot 2024-06-27 at 5 45 39 PM

### Steps to reproduce

1. Select Ethereum Mainnet
2. Go to Send page
3. Click on destination asset picker
4. Observe that symbols are not present and names are not truncated
5. Search for "BNB"
6. Observe that it is not styled as a disabled button

### Error messages or log output

_No response_

### Version

12.1.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

Tested on `develop`

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
the goal of this PR is to fix some v12.1 bugs related to balance display and asset picker modal:
- The symbols no longer show for each list item
- Blocked token symbols (e.g., BNB on Ethereum Mainnet) are no longer greyed out in the UI despite still being inert 
- Token names are not truncated
- Token symbol is USD instead of ETH on the asset picker modal

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25601?quickstart=1)

## **Related issues**

Fixes: #25575 

## **Manual testing steps**

1. Go to the wallet view and check crypto and fiat value for native token
2. Select Ethereum Mainnet
3. Go to Send page
4. Click on destination asset picker
5. Observe that symbols are not present and names are not truncated
6. Search for "CHZ"
7. Observe that it is not styled as a disabled button

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Jellyman447** [comment]
Approved

File: ui/components/multichain/token-list-item/token-list-item.js [hunk 1]
```diff
@@ -273,15 +274,25 @@ export const TokenListItem = ({
...
                   )}
                 </Text>
               )}
 
-              {isEvm && (
+              {isEvm && hidePercentage ? (
+                <Text
+                  variant={TextVariant.bodyMd}
+                  color={TextColor.textAlternative}
+                  data-testid="multichain-token-list-item-token-name" //
```
Comment (darkwing) [inline ui/components/multichain/token-list-item/token-list-item.js:290]: Appears comments `//` need to be removed.

File: ui/hooks/useTokenFiatAmount.js [hunk 2]
```diff
@@ -49,6 +49,7 @@ export function useTokenFiatAmount(
   const tokenExchangeRate =
     overrides.exchangeRate ??
     (contractExchangeTokenKey && mergedRates[contractExchangeTokenKey]);
+
```
Comment (darkwing) [inline ui/hooks/useTokenFiatAmount.js:52]: We can avoid empty lines in PRs.

File: ui/components/multichain/token-list-item/token-list-item.js [hunk 3]
```diff
@@ -454,4 +452,9 @@ TokenListItem.propTypes = {
    * address represents the token address
    */
   address: PropTypes.string,
+
+  /**
+   * hidePercentage represents if the increase decrease percentage will be hidden
+   */
+  hidePercentage: PropTypes.bool,
```
Comment (darkwing) [inline ui/components/multichain/token-list-item/token-list-item.js:459]: Rather than use negative language `hide`, we should stay with positive (`show`)

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss [hunk 4]
```diff
@@ -37,10 +37,10 @@
...
     }
 
-    &--disabled {
-      @include disabled-token {
-        opacity: 0.4;
-      }
+    &--disabled,
+    &:disabled {
+      opacity: var(--opacity-disabled);
+      cursor: not-allowed;
```
Comment (BZahory) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss:43]: Not seeing the correct cursor here

Screenshot 2024-07-01 at 4 29 53 PM

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx [hunk 5]
```diff
@@ -37,8 +50,21 @@ export default function AssetList({
...
+  const { useNativeCurrencyAsPrimaryCurrency } = useSelector(getPreferences);
+
+  const isOriginalNativeSymbol = useIsOriginalNativeTokenSymbol(
+    chainId,
+    ticker,
+    type,
+    rpcUrl,
+  );
+
+  const selectedAccountBalance = useSelector(getSelectedAccountCachedBalance);
```
Comment (BZahory) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx:68]: Let's avoid adding new logic in a hotfix PR. Feel free to make a follow up and I can review but we initially avoided this logic altogether since it blew up that network's RPC endpoint.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx [hunk 6]
```diff
@@ -113,13 +140,29 @@ export default function AssetList({
...
+                      useNativeCurrencyAsPrimaryCurrency,
+                      primaryCurrencyDisplay,
+                      showFiat,
+                      secondaryCurrencyDisplay,
+                      isOriginalNativeSymbol,
+                    })}
                     tokenImage={token.image}
+                    isNativeCurrency
+                    isOriginalTokenSymbol={isOriginalNativeSymbol}
+                    hidePercentage
```
Comment (BZahory) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx:165]: Can we avoid this extra logic and the util functions for now? This is overscoped for this PR

**Review by BZahory — COMMENTED** [review]
Suggested a few changes. Please split up into commits and avoid creeping out of scope in the future

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx (hunk 5 above)
Comment (salimtb) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx:68]: This additional logic enables a more effective resolution of the mentioned bugs without leading to regressions in other areas, which is integral to the solution (since alterations in the wallet view typically affect the asset picker). An alternative approach could have involved completely separating the asset picker and the token list wallet view to facilitate such fixes.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx (hunk 6 above)
Comment (salimtb) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx:165]: This process will become simpler once the `useNativeCurrencyAsPrimaryCurrency` option is eliminated. However, currently, we must manage the transition between fiat and crypto on the settings. To address this, I've developed a solution in a utility file, as nested ternary expressions are prohibited. This approach also facilitates the writing of unit tests too.

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss (hunk 4 above)
Comment (salimtb) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss:43]: done

File: ui/components/multichain/token-list-item/token-list-item.js (hunk 3 above)
Comment (salimtb) [reply ui/components/multichain/token-list-item/token-list-item.js]: done

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx (hunk 5 above)
Comment (BZahory) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx:68]: The bug this addresses (i.e. not showing the user's currency code for the native asset when the user's primary currency is set to fiat) is largely unrelated to the styling regressions mentioned in #25575. While we reexpose this bug by showing the symbol again, this edge case always existed and is not part of the regressions this PR is targeting.

This is something we should address, the existing solution was known to cause a cascade of bugs (see: #24859). While #25501 aims to prevent the rate limiting that caused these bugs, I wouldn't be comfortable reintroducing the hook until we're sure it's no longer problematic. At the very least, **this should be in a separate PR.**

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx (hunk 6 above)
Comment (BZahory) [reply ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx]: https://github.com/MetaMask/metamask-extension/pull/25601#discussion_r1662706706 applies here as well – this is out of scope and too high risk for this PR

File: ui/components/multichain/token-list-item/token-list-item.js [hunk 7]
```diff
@@ -77,6 +76,7 @@ export const TokenListItem = ({
   isNativeCurrency = false,
   isStakeable = false,
   address = null,
+  showPercentage = true,
```
Comment (BZahory) [inline ui/components/multichain/token-list-item/token-list-item.js:79]: Let's default to false here to avoid having to explicitly set it to false when not used

File: ui/components/multichain/asset-picker-amount/asset-picker-modal/Asset.tsx [hunk 8]
```diff
@@ -22,6 +23,7 @@ export default function Asset({
   symbol,
   decimalTokenAmount,
   tooltipText,
+  showPercentage,
```
Comment (BZahory) [inline ui/components/multichain/asset-picker-amount/asset-picker-modal/Asset.tsx:26]: We can remove this prop since this component is exclusive to the `AssetPickerModal`

**Review by BZahory — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
