### PR TITLE
fix: check password outdated before import private key cp-13.0.0

### LINKED ISSUE #34396: [Bug]: Issue when import private key after changing password
### Describe the bug

When user changes password in another browser
In the current browser, user import the private key

First time: just show the error "Controller" but it was hidden by the prompt, click on CTA button, back to Welcome page, login again, check the list account, it show the new account with private key (Video 1)

Second time: import private key again. Cannot click Import button, close the form, there is loading and cannot stop  (Video 1)

Third time: change password on another browser again. Import the private key again, it shows prompt, but cannot click on CTA button, it's frozen (Video 2)

Then delete the extension, install and login again with same Apple account, the new private key account is disappeared

### Expected behavior

- Should not have the error "Controller ... " in the private key import popup
- Should not allow to add import account
- Should show CTA button and click and back to Welcome page every time password is changed

### Screenshots/Recordings

Video 1

https://github.com/user-attachments/assets/a2da64c8-f9d5-4416-9e29-f91b1c3ee4f5

Video 2

https://github.com/user-attachments/assets/0fcac057-b0e8-401b-a440-c096814d15a7

### Steps to reproduce

See the video

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

12.23.0

### Build type

Beta

### Browser

Firefox, Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by tuna1207**
## **Description**

1. User should not be able to import new private key if using social login and password is outdated
2. This PR check PW outdated before importing private key if PW outdated, user will be forced to log out and login again with latest global password

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34400?quickstart=1)

## **Changelog**

CHANGELOG entry: Check password outdated before import private key for social log in user

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34396

## **Manual testing steps**

1. Login social account on a device
2. on another device, log in to same account and change password
3. on the orignal device, try to import private key
4. user should be shown password outdated pop up and force log out

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/import-account/import-account.js [hunk 1]
```diff
@@ -43,6 +43,15 @@ export const ImportAccount = ({ onActionComplete }) => {
     const loadingMessage = getLoadingMessage(strategy);
 
     try {
+      if (isSocialLoginFlow) {
+        const isPasswordOutdated = await dispatch(
+          actions.checkIsSeedlessPasswordOutdated(true),
+        );
+        if (isPasswordOutdated) {
+          return false;
```
Comment (lwin-kyaw) [inline ui/components/multichain/import-account/import-account.js:51]: why returning false here? Would be nice to get some context from here?

**Review by chaitanyapotti — APPROVED** [review]

**Comment by LeVinhGithub** [comment]
lgtm

File: ui/components/multichain/import-account/import-account.js (hunk 1 above)
Comment (tuna1207) [reply ui/components/multichain/import-account/import-account.js:51]: @lwin-kyaw oh this is just returning same value as line 64 and 70, meaning the account wasn't imported

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Review by lionellbriones — APPROVED** [review]
lgtm
