### PR TITLE
fix: hide fiat on testnet

### LINKED ISSUE #31484: [Bug]: Aggregated value and percentage present on test network
### Describe the bug

Aggregated value and percentage is displayed on test network. This is not intended. 

### Expected behavior

Aggregated value and percentage is not displayed on test network. 

### Screenshots/Recordings

Image

### Steps to reproduce

1. Load MetaMask (production)
2. Enable show test networks toggle
3. Switch to Linea Sepolia or Sepolia
4. Notice aggregated value and percentage displayed in wallet overview, under account overview balance.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.14.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

Hide aggregated fiat amounts when a testnet is selected to align with issue #31484.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38683?quickstart=1)

## **Changelog**

CHANGELOG entry: hide fiat in aggregated view when selecting a testnet

## **Related issues**

Fixes: #31484

## **Manual testing steps**

1. Enable testnets in settings
2. Select linea sepolia or eth sepolia
4. See aggregated balance

### **After**

https://www.loom.com/share/ec015b5c1197443696b73fb32ad63b17

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots. 

---
<a href="https://cursor.com/background-agent?bcId=bc-e685744a-d2b9-4470-9893-04f7a7a93941"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/open-in-cursor-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/open-in-cursor-light.svg">Open in Cursor</picture></a>&nbsp;<a href="https://cursor.com/agents?id=bc-e685744a-d2b9-4470-9893-04f7a7a93941"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/open-in-web-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/open-in-web-light.svg">Open in Web</picture></a>

---

> [!NOTE]
> AccountGroupBalance now shows native token balance instead of fiat on testnets, with tests updated to cover this behavior.
> 
> - **Assets UI**:
>   - `ui/components/app/assets/account-group-balance/account-group-balance.tsx`:
>     - Use `getMultichainIsTestnet` to detect testnets.
>     - Render native token balance when `isTestnet` or `showNativeTokenAsMainBalance` is true.
>     - Update memoization dependencies to include `isTestnet`.
> - **Tests**:
>   - `account-group-balance.test.tsx`:
>     - Mock `getMultichainIsTestnet` and add test ensuring native balance renders on testnets regardless of settings.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 7aeecafe5f53259eaad2eb68ed2a03341005cd78. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/wallet-overview/coin-overview.tsx
Comment (Prithpal-Sooriya) [inline ui/components/app/wallet-overview/coin-overview.tsx:1]: @cursor revert these file changes on coin-overview - this file does not need modifying

File: ui/components/app/assets/account-group-balance/account-group-balance.tsx [hunk 1]
```diff
@@ -69,6 +72,10 @@ export const AccountGroupBalance: React.FC<AccountGroupBalanceProps> = ({
 
   const isEvm = isEvmChainId(chainId);
 
+  const isTestnet = useSelector((state) =>
+    getMultichainIsTestnet(state, selectedAccount),
```
Comment (Prithpal-Sooriya) [inline ui/components/app/assets/account-group-balance/account-group-balance.tsx]: @cursor modify please - we can write the selector as
```ts
const isTestnet = useSelector(getMultichainIsTestnet);
```

File: ui/components/app/wallet-overview/coin-overview.tsx
Comment (Prithpal-Sooriya) [reply ui/components/app/wallet-overview/coin-overview.tsx:1]: @cursor I still see the diffs on this file in the PR... please remove revert so that there are no diffs on this file pls (the PR has multiple commits)

**Review by juanmigdr — APPROVED** [review]

**Review by juanmigdr — APPROVED** [review]

**Review by salimtb — APPROVED** [review]
