### PR TITLE
fix: ignore error when getTokenStandardAndDetails fails

### LINKED ISSUE #17287: Error: Unable to determine contract standard
Sentry Issue: [METAMASK-MK2Z](https://sentry.io/organizations/metamask/issues/3038540326/?referrer=github_integration)

```
Error: Unable to determine contract standard
  at Generator.throw (<anonymous>)
```

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Fixes Sentry issue when we are not able to determine token contract standard.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28030?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/17287

## **Manual testing steps**

(I was not able to repro with my NFTs but to simulate, we can go to the core fct  `getTokenStandardAndDetails` and add 
`throw new Error('Unable to determine contract standard');` at the start of the fct;

1. Go NFT page
2. Click on any NFT
3. Click Send
4. You should be able to send the NFT

### **Before**

https://github.com/user-attachments/assets/2ef39b0e-106a-48a2-a150-82176adaf14c

### **After**

https://github.com/user-attachments/assets/f0714310-410f-4f51-b7e2-6f0bc4011027

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -2652,10 +2652,9 @@ export function updateSendAsset(
             providedDetails.address,
             sendingAddress,
             providedDetails.tokenId,
-          ).catch((error) => {
+          ).catch(() => {
             // prevent infinite stuck loading state
             dispatch(hideLoadingIndication());
-            throw error;
           })),
```
Comment (sahar-fehri) [inline ui/ducks/send/send.js:2658]: This change wont affect native transfers;
It also wont affect ERC20 transfers because for ERC20 transfers `tokenCanBeTreatedAsAnERC20` [here](https://github.com/MetaMask/metamask-extension/blob/a1a62aa33572710ec915823d52427c93979ee622/app/scripts/metamask-controller.js#L4208) should be `true` making `details` defined and skipping the call to `getTokenStandardAndDetails`.
This should only affect NFT assets; 

This is throwing because the code detects that there is a missing property which is `symbol` in the case of the nfts i have tested with ([here](https://github.com/MetaMask/metamask-extension/blob/a1a62aa33572710ec915823d52427c93979ee622/ui/ducks/send/send.js#L2616)) and because the `providedDetails` has `standard` property it will go into the [else](https://github.com/MetaMask/metamask-extension/blob/a1a62aa33572710ec915823d52427c93979ee622/ui/ducks/send/send.js#L2649) and call `getTokenStandardAndDetails`.

The code is detecting that the `symbol` is missing because the nftDetails `symbol` is inside `nft.collection`,
but this piece of [code](https://github.com/MetaMask/metamask-extension/blob/a1a62aa33572710ec915823d52427c93979ee622/ui/ducks/send/send.js#L2616)
is expecting the symbol inside the nft object;

The properties that it is checking for an NFT are basically "name, symbol, tokenId" i dnt think tokenId can undefined for an NFT.
Looking at the number of users affected by this; i would expect that most of them if not all are missing symbol;
A missing symbol should not make the transaction fail; i have tested this and my transactions were successful.

We could either remove the throw error in the catch;

Or fix this while keeping the "throw" would be to sth similar to this;

`      let missingProperty = STANDARD_TO_REQUIRED_PROPERTIES[
        providedDetails.standard
      ]?.find((property) => {
        if (providedDetails.collection && property === 'symbol') {
          return providedDetails.collection[property] === undefined;
        }
        return providedDetails[property] === undefined;
      });`

**Comment by sahar-fehri** [comment]
There are other places in codebase that call getTokenStandardAndDetails; all of them are either within a try/catch or called using `useAsyncResult` which should also catch the error

**Comment by salimtb** [comment]
can you add a unit test for this ?

**Review by gambinish — APPROVED** [review]
I wonder if we should still log the error that gets caught to make future troubleshooting easier? Do we have a logger setup for this kind of thing?

Otherwise lgtm 👍

**Review by bergeron — APPROVED** [review]
