### PR TITLE
fix: remove use of hideTokenTransactions from asset page

### LINKED ISSUE #30230: [Bug]: Discrepancy between the transactions listed under the Activity tab and those displayed in the "Your Activity" section within the token details screen for the same token
### Describe the bug

There appears to be a noticeable discrepancy between the transactions listed under the `Activity tab` and those displayed in the `Your Activity `section within the Token details screen for the same token. The `Activity tab` consistently shows a greater number of transactions compared to the `Your Activity` section.

### Expected behavior

All relevant transactions for a specific token are accurately and uniformly reflected in both the `Activity tab` and the `Your Activity` section of the token details screen

### Screenshots/Recordings

Image

Image

Image

### Steps to reproduce

1. Send several transaction involving the same token
2. Compare transactions displayed in `Your Activity` section within the token details screen and tx in the `Activity tab`

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.10.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

This PR addresses a discrepancy between the transactions displayed in the Activity tab and those shown in the Your Activity section within the Token details screen. Previously, the Activity tab was consistently showing a higher number of transactions compared to the Your Activity section for the same token.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31352?quickstart=1)

## **Related issues**

Fixes: #30230 

## **Manual testing steps**

1. Go to the activity tab
2. check the list of transactions
3. Go to token details and check the list of activities

### **Before**

Screenshot 2025-03-27 at 14 17 21

Screenshot 2025-03-27 at 14 17 30

### **After**

Screenshot 2025-03-27 at 14 11 51

Screenshot 2025-03-27 at 14 12 22

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/asset/components/asset-page.tsx [hunk 1]
```diff
@@ -479,7 +479,7 @@ const AssetPage = ({
               {t('yourActivity')}
             </Text>
             {type === AssetType.native ? (
-              <TransactionList hideTokenTransactions hideNetworkFilter />
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/components/asset-page.tsx:482]: nice fix!

Is this `hideTokenTransactions` still being used anywhere?

File: ui/pages/asset/components/asset-page.tsx [hunk 2]
```diff
@@ -479,7 +479,7 @@ const AssetPage = ({
...
+              <TransactionList hideNetworkFilter />
```
Comment (sahar-fehri) [inline ui/pages/asset/components/asset-page.tsx:482]: Curious was there a reason why we wanted to hide token transactions on the asset page? 🤔

File: ui/components/app/transaction-list/transaction-list.test.js [hunk 3]
```diff
@@ -225,6 +242,24 @@ describe('TransactionList', () => {
...
+      },
+    };
+    const store = configureStore(defaultState2);
+    const { container } = renderWithProvider(
+      <MetaMetricsContext.Provider value={mockTrackEvent}>
+        <TransactionList hideTokenTransactions />
+      </MetaMetricsContext.Provider>,
+      store,
+    );
+    expect(container).toMatchSnapshot();
```
Comment (Prithpal-Sooriya) [inline ui/components/app/transaction-list/transaction-list.test.js:260]: Nit - do we want to test that the list is filtering tokens?

Comment (Prithpal-Sooriya) [reply ui/components/app/transaction-list/transaction-list.test.js:260]: OK nice, I do see that the snapshot correctly hides tokens - awesome work.
I think this can be a future task (move away from snapshot and target specific element to see if it exists)

**Review by Prithpal-Sooriya — APPROVED** [review]

File: ui/pages/asset/components/asset-page.tsx (hunk 1 above)
Comment (Prithpal-Sooriya) [reply ui/pages/asset/components/asset-page.tsx:482]: If this is not used anywhere, I'm tempted to see if we can clean up this component and tests.

**Review by sahar-fehri — APPROVED** [review]
