### PR TITLE
fix: Hide non-zero hex data alert for contract deployment confirmations

### LINKED ISSUE #30359: [Bug]: Contract Deployment - An incorrect warning is displayed when deploying a contract: `You're sending call data to an address that isn't a contract.`
### Describe the bug

Whenever I deploy a contract, I see the warning `You're sending call data to an address that isn't a contract.`. Regular contract deployments (not using create/2) will be always flagged as "address that isn't a contract" as there's no contract address until the tx is executed. 

### Expected behavior

No warning displayed for Contract Deployments

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/b5f7668b-6619-473d-82c4-3f3b09ddfc9d

### Steps to reproduce

1. Select Mainnet
2. Go to the test dapp
3. Trigger a contract deployment
4. See warning `You're sending call data to an address that isn't a contract.`

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.13.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Previously, the non-zero hex data alert could be visible by the user if another alert was triggered for contract deployments. This PR hides it for this case.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30474?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30359

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.ts [hunk 1]
```diff
@@ -31,8 +34,13 @@ export function useNonContractAddressAlerts(): Alert[] {
...
     !pending && value?.isContractAddress === false;
 
+  const isContractDeploymentTx =
+    currentConfirmation.type === TransactionType.deployContract;
+
   const isSendingHexDataWhileInteractingWithNonContractAddress =
-    isSendingHexData && isInteractingWithNonContractAddress;
+    isSendingHexData &&
+    isInteractingWithNonContractAddress &&
+    !isContractDeploymentTx;
```
Comment (jpuri) [inline ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.ts:43]: Changes look perfect, but be nice to have test coverage also.

**Review by jpuri — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]
