### PR TITLE
Onboarding: Set SeedPhraseBackedUp when appropriate

### LINKED ISSUE #16836: [Bug]: Onboarding V2 Secret Recovery Phrase backup reminder does not show up
### Describe the bug

**Problem**: the Secret Recovery Phrase backup reminder does not show up anymore, when the new account receives some ETH. 

https://user-images.githubusercontent.com/54408225/206171737-3a43d90f-ddc3-4673-ba79-adb1e3aa5f87.mp4

**Expected**:

Screenshot from 2022-12-07 12-43-34

### Steps to reproduce

1. Go through the Onboarding V2 flow with Create new Wallet
2. Select Goerli network
3. From another MM extension, send some ETH to the new account
4. Wait until you receive the ETH -- see how no backup reminder is displayed

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

* Fixes https://github.com/MetaMask/metamask-extension/issues/16836

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by adonesky1 — DISMISSED** [review]
LGTM

**Review by jpuri — DISMISSED** [review]
Changed look good, build needs some attention it seems.

File: ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.js [hunk 1]
```diff
@@ -94,6 +97,7 @@ export default function ConfirmRecoveryPhrase({ secretRecoveryPhrase = '' }) {
           large
           className="recovery-phrase__footer__confirm--button"
           onClick={() => {
+            dispatch(setSeedPhraseBackedUp(true));
             history.push(ONBOARDING_COMPLETION_ROUTE);
           }}
```
Comment (Gudahtt) [inline ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.js:102]: This action is async, so we should be awaiting it here. Otherwise the page navigation might complete before we finish setting this background state.

```suggestion
          onClick={async () => {
            await dispatch(setSeedPhraseBackedUp(true));
            history.push(ONBOARDING_COMPLETION_ROUTE);
          }}
```

The same goes for the other component this is called in as well.

**Comment by danjm** [comment]
The most recent unit test failure looks related to these code changes
Screenshot from 2022-12-14 09-18-56

File: ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js [hunk 2]
```diff
@@ -40,7 +48,10 @@ describe('Secure Your Wallet Onboarding View', () => {
     expect(queryAllByText('Skip account security?')).toHaveLength(1);
   });
 
-  it('should not be able to click "skip" until "Skip Account Security" terms are agreed to', () => {
+  it('should not be able to click "skip" until "Skip Account Security" terms are agreed to', async () => {
+    const mockDispatch = jest.fn();
+    store.dispatch = mockDispatch;
```
Comment (adonesky1) [inline ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js:53]: can we not mock the specific action being called?

Comment (adonesky1) [reply ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js]: pushed a fix [here](https://github.com/MetaMask/metamask-extension/pull/16875/commits/2770e4c61a4b110549db7d2077ba3cd6a7d95804)

**Review by adonesky1 — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
