### PR TITLE
fix: cp-13.0.0 fix displayed price for native tokens on token details page

### LINKED ISSUE #34417: [Bug]: After enabling a network, the token details will display the same token information across all networks.
### Describe the bug

After enabling a network, the token details will display the same token information across all networks.

### Expected behavior

Correct token information is shown

### Screenshots/Recordings

https://github.com/user-attachments/assets/026c6ef0-11e2-42f0-8847-5d4bf5d091cb

### Steps to reproduce

1. Navigate to token details

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34565?quickstart=1)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: #34417 

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

https://github.com/user-attachments/assets/c2d7d607-3553-4618-b3c8-b0ff6690a48a

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/asset/hooks/useCurrentPrice.ts [hunk 1]
```diff
@@ -37,7 +42,9 @@ export const useCurrentPrice = (asset: Asset): { currentPrice?: number } => {
   })();
 
   if (type === AssetType.native) {
-    return { currentPrice: Number(nativeConversionRate) };
+    return isEvm
+      ? { currentPrice: evmConversion }
+      : { currentPrice: Number(nativeConversionRate) };
   }
```
Comment (Prithpal-Sooriya) [inline ui/pages/asset/hooks/useCurrentPrice.ts:48]: Nice fix!

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
