### PR TITLE
fix: fix NFT balance in send flow

### LINKED ISSUE #28298: [Bug]: Assets Balance - The balance for my ERC1155 token is incorrect in the Send flow screen
### Describe the bug

The balance for my ERC1155 token is incorrect on the Send flow screen. It displays a balance of `21` tokens, but I just have `15`. I can proceed by trying to send `21` tokens and then the transaction fails as expected.
This is reproduceable by deploying a test dapp ERC1155 contract and minting some tokens.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/c1d6b577-4a06-4eeb-bea6-949a05eba954

### Steps to reproduce

1. Go to the test dapp
2. Deploy an ERC1155 contract
3. Batch mint 2 tokens, one with 10 amount and the other with 15
4. Import the tokens to your wallet
5. Try to send one
6. See balance is incorrect
7. Proceed with the send
8. See tx fails, as you don't have enough tokens

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Fixes balance for NFTs in send flow.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31239?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28298

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

Please see video in issue 🙏 

### **After**

https://github.com/user-attachments/assets/eec659f1-4201-4999-9952-b76877cc365b

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/ducks/send/send.js [hunk 1]
```diff
@@ -2731,9 +2732,7 @@ export function updateSendAsset(
 
           if (isCurrentOwner) {
             asset.error = null;
-            asset.balance = details.balance
-              ? addHexPrefix(details.balance)
```
Comment (sahar-fehri) [inline ui/ducks/send/send.js:2735]: Using `addHexPrefix` is what triggered the bug in the NFT send flow.
When deploying a tokenId 1 and 2 with amount `10` and `15`
using `addHexPrefix` resulted in the balance being `0x10` and `0x15`.
In the `AssetBalanceText` component we will [calculate](https://github.com/MetaMask/metamask-extension/blob/56ca28472514fdb5141789d29744c728042b0e6c/ui/components/multichain/asset-picker-amount/asset-balance/asset-balance-text.tsx#L92) the number of tokens of nfts
`const numberOfTokens = hexToDecimal(asset.balance || '0x0');`
Which results in numberOfTokens being `16` and `21` instead of `10` and `15`

**Review by gambinish — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
