### PR TITLE
fix: Add L2 support in ConfirmLegacyGasDisplay to support Scroll Network transactions

### LINKED ISSUE #24835: [Bug]: UI regression on gas component for Scroll network
### Describe the bug

We've successfully fixed gas calculations for Scroll network with this PR https://github.com/MetaMask/metamask-extension/pull/23991, but we introduced a UI regression on how the gas component is displayed for Scroll network. 

This PR https://github.com/MetaMask/metamask-extension/pull/24264 improves the gas component UI for legacy transactions which also fixes the gas component UI for Scroll network. But from testing the build within the UI, it seems the estimated gas field only displays layer2 gas while you can correctly see both layer1 and layer2 fees within details. 

### Expected behavior

We should only display the layer 1 and layer 2 breakdown within the see details section. Estimated fee should display the sum of layer 1 and layer 2 fees.

### Screenshots/Recordings
Gas UI on Scroll on v11.14.x
Screenshot 2024-05-28 at 16 30 06

Gas UI on Scroll on v11.16.0
Screenshot 2024-05-28 at 13 42 02

Gas UI on Scroll on the build in this PR https://github.com/MetaMask/metamask-extension/pull/24264
Screenshot 2024-05-28 at 14 01 09

### Steps to reproduce

1. Go to test dapp
2. Click on "Create a token"
3. Notice the gas component and its values in each different version/build

### Error messages or log output

_No response_

### Version

11.6.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

Scroll supports legacy transactions and does not support EIP-1559. This PR adds L2 support in the ConfirmLegacyGasDisplay component

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24854?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24835
Follow-up Cherry-pick: https://github.com/MetaMask/metamask-extension/pull/24866
## **Manual testing steps**

1. Go to test dapp
2. Click on "Create a token"
3. Notice the gas component and its values in each different version/build

### **Before**

Screenshot 2024-05-28 at 14 01 09

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
@digiwand 
Estimated fee field displays the sum of layer 1 and layer 2 fees:

Screenshot 2024-05-28 at 23 16 51


Screenshot 2024-05-28 at 23 18 03

A couple of concerns:
- on Scroll Sepolia fees are too high
- fiat values are displayed while 'Show conversion on test networks' toggle(Advanced Settings) is disabled

On Firefox I see CORS, 'Failed gas fee / price estimation failed' and 'Failed prop type' errors:

Screenshot 2024-05-28 at 23 31 39


Screenshot 2024-05-28 at 23 34 39

Screenshot 2024-05-28 at 23 34 50



Screenshot 2024-05-28 at 23 33 57

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Review by sleepytanya — DISMISSED** [review]

**Comment by digiwand** [comment]
Great investigation @sleepytanya! 

These are out-of-scope of this PR. We can address them in convo here and as follow-up tasks

re: on Scroll Sepolia fees are too high
as the testnet gas fees are not expected to mirror the mainnet, I think this may be a non-issue or an internal issue with the Gas Fee Estimate API

re: fiat values are displayed while 'Show conversion on test networks' toggle (Advanced Settings) is disabled
this appears to be a separate issue. We can create a new issue ticket for this and double-check it's applied to other transaction types as well 

re: On Firefox I see CORS, 'Failed gas fee / price estimation failed' 
@matthewwalsh0:
> We've avoided using [scroll.io](http://scroll.io/) for the RPC provider in the past given its heavy rate limiting. The CORS errors are server side and look a side effect of the rate limiting as those 429 responses are missing the headers.
>
> We don't need to do anything as this is a problem of that RPC provider, but it seems to be just a side effect of their rate limiting as the CORS errors seem specific to the 429 (rate limit) error responses.
The action here is likely just to test with an alternate scroll RPC provider

re: 'Failed prop type' errors:
The invalid contentText value provided to InfoTooltip appears to be out-of-scope. We can create a new ticket for this one

File: ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js [hunk 1]
```diff
@@ -42,14 +43,22 @@ const ConfirmLegacyGasDisplay = ({ 'data-testid': dataTestId } = {}) => {
...
   const transaction = Object.keys(transactionData).length
     ? transactionData
     : unapprovedTxs[transactionId] || {};
   const { hexMinimumTransactionFee, hexMaximumTransactionFee } = useSelector(
     (state) => transactionFeeSelector(state, transaction),
   );
 
+  const estimatedHexMinFeeTotal = layer1GasFee
+    ? addHexes(hexMinimumTransactionFee, layer1GasFee ?? 0)
+    : hexMinimumTransactionFee;
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js:56]: Is this ternary needed? Would it be simpler to always call addHexes but with 0x0 as the second arg if the layer 1 fee is undefined or null?

Comment (matthewwalsh0) [reply ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js]: It may work fine as is, but should the 0x0 be strings as otherwise they will evaluate to a zero number which I don't know if that function supports.

Comment (digiwand) [reply ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js]: ah. good call since the function itself specified strings w/ TS 

Interestingly, it appears the method could support other types if it wasn't for the explicit TS specification. The Numeric constructor params accept a NumericValue which is coerced to a BigNumber
`export type NumericValue = string | number | BN | BigNumber;`

**Review by matthewwalsh0 — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
