### PR TITLE
fix: fix import tokens modal delay

### LINKED ISSUE #34868: [Bug]: Tokens on popular networks displayed multiple times in the assets list
View issue in GitHub: https://github.com/MetaMask/metamask-extension/issues/34868

View issue in GitHub: [https://github.com/MetaMask/metamask-extension/issues/34868|https://github.com/MetaMask/metamask-extension/issues/34868]

View issue in GitHub: [https://github.com/MetaMask/metamask-extension/issues/34868|https://github.com/MetaMask/metamask-extension/issues/34868]

**Describe the bug**

The USDC token seems to be displayed twice in the asset list, when Ethereum Mainnet is selected.

Update by [~accountid:618122bd327da40069919c6b] - this is an issue when importing token manually, but [~accountid:5bdc8b99653a520f925ac158] also experienced it when installing a fresh wallet.

Then, once another network is enabled, the USDC token is added again to the tokens list

Sometimes it is also displayed in the DeFi Tab

**Expected behavior**

USDC token on Ethereum Mainnet to be displayed only once

**Screenshots/Recordings**

[https://github.com/user-attachments/assets/87eb5483-c81b-4121-af9e-34c69453d0b1|https://github.com/user-attachments/assets/87eb5483-c81b-4121-af9e-34c69453d0b1]

Slack thread (including video recording): [https://consensys.slack.com/archives/C09ADJ3E81G/p1760744194590759|https://consensys.slack.com/archives/C09ADJ3E81G/p1760744194590759|smart-link]

Image

Image

**Steps to reproduce**

1. Have USDC token on Ethereum Mainnet
2. Enable/disable networks
3. Notice the USDC token is displayed multiple times in the asset list

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

13.1.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

**Additional context**

state logs

[MetaMask state logs.json]([https://github.com/user-attachments/files/21602414/MetaMask.state.logs.json|https://github.com/user-attachments/files/21602414/MetaMask.state.logs.json])

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix delay on checking if token is already imported inside the import tokens modal.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37116?quickstart=1)

## **Changelog**

CHANGELOG entry: Fixed delay checking if token is already imported inside import tokens modal.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34868

## **Manual testing steps**

1. Choose Ethereum network (Or any network where you already have tokens imported)
2. Click on import tokens
3. Choose a token that was already imported
4. Make sure you see the token already greyed out so you are not ble to import it

### **Before**

https://github.com/user-attachments/assets/e6e0846e-8e90-42c7-9127-7ad353c88529

### **After**

https://github.com/user-attachments/assets/b1398597-7389-4b03-b79f-fc5d13c983a9

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Inject `chainId` into filtered token data at search time and stop mutating it in the list, ensuring immediate already-added detection.
> 
> - **Import Tokens**:
>   - **`token-search.component.js`**: When filtering to the current network, return token data with `chainId` injected per entry to ensure each token includes its network ID.
>   - **`token-list.component.js`**: Remove mutation of `results[i].chainId`; rely on provided `chainId` for `checkExistingAllTokens` and selection/disabled state.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit cb5b43e0bf04c42043effd434dd2a5d778ba0989. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/app/import-token/token-list/token-list.component.js [hunk 1]
```diff
@@ -71,11 +70,14 @@ export default class TokenList extends Component {
...
-                const { symbol, name, address, chainId } = results[i] || {};
+                const { symbol, name, address } = results[i] || {};
+
+                const chainId = isTokenNetworkFilterEqualCurrentNetwork
+                  ? currentNetwork?.chainId
+                  : results[i]?.chainId;
+
                 let tokenAlreadyAdded = false;
-                if (isTokenNetworkFilterEqualCurrentNetwork) {
-                  results[i].chainId = currentNetwork?.chainId;
```
Comment (sahar-fehri) [inline ui/components/app/import-token/token-list/token-list.component.js:77]: This line was causing render issues;
This mutates the original results array .. React doesn't detect this, so no re-render happens. We should avoid mutating props or state directly inside render.

**Comment by Unik0rnMaggie** [comment]
Testing build from this PR:

- Unable to reproduce issue anymore: when trying to re-add an existing token using contract address, it doesn't work, button greyed out
- there is a strange token displayed on BNB chain, and on other networks as well: TangYuan
This token is not owned in [this account](https://bscscan.com/address/0x7c5dd7b02444d990c1b57c706205c8f7649aa9d2) used for testing


https://github.com/user-attachments/assets/4de9aacc-bb19-4e8b-85a5-b6b4bf612e97

**Comment by Unik0rnMaggie** [comment]
Testing the latest [build](https://github.com/MetaMask/metamask-extension/pull/37116#issuecomment-3438326631) from this PR:

1. Unable to reproduce issue anymore: when trying to re-add an existing token using contract address, it doesn't work, button greyed out
2. Unable to reproduce strange tokens displayed on BNB chain, previously reported
3. Bitcoin network displayed - is that expected?


https://github.com/user-attachments/assets/1c1fe8a8-a3ee-4b0a-bdb8-0901cd38141e

**Review by salimtb — APPROVED** [review]

**Review by juanmigdr — APPROVED** [review]
