### PR TITLE
fix: signature redesign ui_customizations metric

### LINKED ISSUE #24483: [Internal Bug] Signature Redesign - ui_customization method is not added to event for certain signature types
### Describe the bug

`ui_customization: redesigned_confirmation` is not being added to certain signature events. 

### Expected behavior

_No response_

### Screenshots/Recordings

Image
Image

### Steps to reproduce

1. set `ENABLE_CONFIRMATION_REDESIGN=true` in .metamaskrc
2. enable Experimental > Redesign Confirmation in settings
3. enable Participate in MetaMetrics in settings
4. test signatures
5. observe Signature <Rejected|Canceled|Approved> event with new ui_customization

### Error messages or log output

_No response_

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24484?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/24483

## **Manual testing steps**

1. set `ENABLE_CONFIRMATION_REDESIGN=true` in .metamaskrc
2. enable Experimental > Redesign Confirmation in settings
3. enable Participate in MetaMetrics in settings
4. test signatures
5. observe Signature <Rejected|Canceled|Approved> event with new ui_customization

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/lib/createRPCMethodTrackingMiddleware.js [hunk 1]
```diff
@@ -257,11 +267,10 @@ export default function createRPCMethodTrackingMiddleware({
             req.securityAlertResponse.description;
         }
         ///: END:ONLY_INCLUDE_IF
-
         const isConfirmationRedesign =
           isConfirmationRedesignEnabled() &&
-          [...REDESIGN_APPROVAL_TYPES, ...REDESIGN_TRANSACTION_TYPES].find(
-            (type) => type === method,
```
Comment (digiwand) [inline app/scripts/lib/createRPCMethodTrackingMiddleware.js:264]: I removed the redesign transaction types check because it does not work. We will handle this with https://github.com/MetaMask/metamask-extension/issues/24486

**Review by cryptotavares — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Comment by digiwand** [comment]
sorry I should start running yarn lint locally before requesting reviews 🤦🏼‍♀️  @cryptotavares @jpuri

**Review by pedronfigueiredo — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
