### PR TITLE
fix: reverts evm transaction ordering to preserve nonce ordering

### LINKED ISSUE #32261: [Bug]: Incorrect behavior for Transactions with Sequential Nonces
### Describe the bug

When we have 2 transactions pending (one with nonce N and another one with nonce N+1), transaction with nonce N is displayed as Queued (should be the other way around).
Because of that, transaction with nonce N can only be canceled. It should be possible to Speed up or Cancel transaction with nonce N. 

Transaction with nonce N+1 is displayed as Pending (should be displayed as Queued) and has the Cancel and Speed up button, but the Speed up button does not make much sense, since speeding up this transaction does not affect its position in the processing queue. 
The speed up function is more relevant to the transaction that is currently "Pending" (in this case, the one with nonce N).

### Expected behavior

Transactions should be processed in the order of their nonces. 
The transaction with nonce N should be displayed as "Pending" since it's the next in line to be processed.
The transaction with nonce N+1 should be displayed as "Queued" because it cannot be processed until the transaction with nonce N is completed.

### Screenshots/Recordings

https://github.com/user-attachments/assets/5b82742d-b197-4d3a-bfc7-fe2d7ccd575a

### Steps to reproduce

1. Turn off Smart Transactions setting
2. Queue multiple transactions

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.17.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

When adding multichain transactions and sorting, we incorrectly sorted EVM transactions by Timestamp after they are sorted by Nonce - this can cause an incorrect sorting of nonces which are expected to be in order for some components to display correctly.

This change reverts the sorting of EVM back to the pre-bug state and keeps Multichain transactions where they are by using props on the sorting function.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/32576?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32261

## **Manual testing steps**

1. Follow repro steps in https://github.com/MetaMask/metamask-extension/issues/32261
2. Observe the fix

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by micaelae — APPROVED** [review]

**Review by GustavoRSSilva — APPROVED** [review]

File: ui/components/app/transaction-list/transaction-list.component.js [hunk 1]
```diff
@@ -200,6 +200,7 @@ const getFilteredTransactionGroupsAllChains = (
 const groupTransactionsByDate = (
   transactionGroups,
   getTransactionTimestamp,
+  shouldSort = true,
```
Comment (digiwand) [inline ui/components/app/transaction-list/transaction-list.component.js:203]: [nit] option to make this an optional param 
```suggestion
  { shouldSort = true } = {},
```
and update below instance with shouldSort: false below

**Review by digiwand — APPROVED** [review]
