### PR TITLE
Fix currency conversion rate

### LINKED ISSUE #13736: [Bug]: Address Pet name and currency conversion unavailable in "Edit" mode in the Send flow
### Describe the bug

After initiating a transfer, if a user clicks "edit" and goes back to the screen with recipients address and token. The inputs are broken. The contact pet name gets replaced by the address and it appears twice. As well as the token fiat value is unavailable. See the video below.

https://user-images.githubusercontent.com/87030673/155383141-77b3579e-c1e8-42ad-85a0-4e21a96057be.mov

 

### Steps to reproduce

1. Start a transfer with an asset
2. Select a saved contact (with a pet name) 
3. Select a token with a fiat value
4. Click Next 
5. Click Edit and the currency conversion rate isn't shown + the pet name is replaced by the recipients address

### Error messages or log output

_No response_

### Version

10.9.3

### Build type

_No response_

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by VSaric**
## Explanation

As second part of #13736, second step for fixing is `currency conversion rate` to be shown when user click `Edit` in the tx confirmation screen.

## More Information

* Fixes #13736

### After

https://user-images.githubusercontent.com/92527393/168544977-3f8a63a5-21d1-4486-8729-161041de8fff.mov

## Manual Testing Steps

1. Start a transfer with an asset
2. Select a saved contact (with a pet name)
3. Select a token
4. Click Next
5. Click Edit

### CODE REVIEW

**Comment by VSaric** [comment]
## Screenshots/Screencaps

### Before


https://user-images.githubusercontent.com/92527393/168554191-0ab2658a-f039-4cbd-9057-b637cc96b5b5.mov

**Comment by mirjanaKukic** [comment]
Verified by QA

File: ui/components/ui/token-input/token-input.component.js [hunk 1]
```diff
@@ -34,6 +35,7 @@ export default class TokenInput extends PureComponent {
       symbol: PropTypes.string,
     }).isRequired,
     tokenExchangeRates: PropTypes.object,
+    tokens: PropTypes.array,
```
Comment (darkwing) [inline ui/components/ui/token-input/token-input.component.js:38]: I think we need this to be `required` since we're iterating over it on line 117.

**Review by darkwing — CHANGES_REQUESTED** [review]

**Review by 0ex-d — DISMISSED** [review]

File: ui/components/ui/token-input/token-input.component.js (hunk 1 above)
Comment (VSaric) [reply ui/components/ui/token-input/token-input.component.js]: @darkwing Done [here](https://github.com/MetaMask/metamask-extension/pull/14713/commits/cc0a033db731d6444af9f2d59e95c7587a5971bf)

**Review by darkwing — APPROVED** [review]

**Review by segun — APPROVED** [review]

**Comment by segun** [comment]
I closed this by mistake...re-opening.
