### PR TITLE
transactions/pending - buffer 3 blocks before dropping a tx

### LINKED ISSUE #7370: Transaction incorrectly reported as "dropped"
**Describe the bug**
I sent a transaction and MetaMask has labeled it as "dropped" although when I click through on the block explorer link the block explorer shows the tx is confirmed. Even after refreshing MetaMask the tx still shows as "dropped".

**To Reproduce**
1. Try to send DAI to a multisig address
2. See the tx is "dropped" in MetaMask
3. Click on the block explorer link to see the tx actually is confirmed

**Expected behavior**
A clear description of what you expected to happen.

I expect that the tx is shown as Confirmed in MetaMask

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser: Chromium 78.0.3904.70
 - MetaMask Version: 7.4.0

### PR DESCRIPTION
**Pull request by frankiebee**
woops miss spelled the branch just how you like it @tmashuang 

fixes #7370 

seems we might have stubbled across some out of sync nodes the average for out of sync nodes is 1 to 2 so this should buffer for that

### CODE REVIEW

File: app/scripts/controllers/transactions/pending-tx-tracker.js [hunk 1]
```diff
@@ -214,6 +224,9 @@ class PendingTransactionTracker extends EventEmitter {
     const address = txMeta.txParams.from
     const completed = this.getCompletedTransactions(address)
     const sameNonce = completed.filter((otherMeta) => {
+      if (otherMeta.id === txMeta.id) {
```
Comment (Gudahtt) [inline app/scripts/controllers/transactions/pending-tx-tracker.js]: Ohh this is tricky. I'm guessing this is here because the transaction being checked may have completed since `_checkPendingTx` was called? Unless it's possible for two txs to have the same id somehow.

File: app/scripts/controllers/transactions/pending-tx-tracker.js [hunk 2]
```diff
@@ -151,16 +155,22 @@ class PendingTransactionTracker extends EventEmitter {
...
-      if (dropped && !this.droppedBuffer[txHash]) {
-        this.droppedBuffer[txHash] = true
+      if (typeof this.droppedBuffer[txHash] !== 'number') {
+        this.droppedBuffer[txHash] = 0
+      }
+      if (dropped && this.droppedBuffer[txHash] < 3) {
         dropped = false
-      } else if (dropped && this.droppedBuffer[txHash]) {
+      }
+      ++this.droppedBuffer[txHash]
```
Comment (Gudahtt) [inline app/scripts/controllers/transactions/pending-tx-tracker.js]: Should this _always_ be incremented, even if the transaction isn't showing up as dropped?

I thought at first that this was waiting for it to be dropped on three successive checks. But currently it seems to be checking every third block instead.

Comment (Gudahtt) [reply app/scripts/controllers/transactions/pending-tx-tracker.js]: i.e. I think maybe this belongs in an `else if (dropped) { .. }` block

Comment (Gudahtt) [reply app/scripts/controllers/transactions/pending-tx-tracker.js]: Wait no, my bad, that should be `if (dropped)` not `else if (dropped)`

File: app/scripts/controllers/transactions/pending-tx-tracker.js (hunk 1 above)
Comment (frankiebee) [reply app/scripts/controllers/transactions/pending-tx-tracker.js]: yes it is because of the possibility that as this is running the tx has completed

Comment (frankiebee) [reply app/scripts/controllers/transactions/pending-tx-tracker.js]: so if we dont check the id but we get it in the list we will mark it as dropped with out this line

File: app/scripts/controllers/transactions/pending-tx-tracker.js (hunk 2 above)
Comment (frankiebee) [reply app/scripts/controllers/transactions/pending-tx-tracker.js]: hmm yeah you have a point i can move it

**Review by Gudahtt — APPROVED** [review]
LGTM 👍
