### PR TITLE
fix: remove EVM network when non-EVM network is selected

### LINKED ISSUE #30713: [Bug]: Solana - Whenever I have a Solana account selected I am able to see the netowrk `Delete` button for the EVM selected network, and when I click Delete nothing happens
### Describe the bug

Whenever I have a Solana account selected I am able to see the netowrk `Delete` button for the EVM selected network, and when I click Delete nothing happens

### Expected behavior

 I cannot delete that network because it's the currently selected one for the EVM accounts, so we shouldn't see the `Delete` option, like we normally do when we have an EVM account selected, where the current network is not deletable

### Screenshots/Recordings

https://github.com/user-attachments/assets/ef57080b-12ea-4977-8c2d-4dd621ea7e1d

### Steps to reproduce

1. Add a custom network, ie Gnosis
2. Select that network
3. Now select Solana
4. Click on the network picker
5. Click on Gnosis
6. See you can Delete Gnosis network
7. Click
8. See nothing happens afterwards, as this is the active EVM network

### Error messages or log output

```shell

```

### Detection stage

Regression RC

### Version

12.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

This PR fixes an issue regarding deleting the last selected EVM network. This solution will later be ported to the `multichain-network-controller`.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30757?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/30713

## **Manual testing steps**

1. Add a custom network, ie Gnosis
2. Select that network
3. Now select Solana
4. Click on the network picker
5. Click on Gnosis
6. See you can Delete Gnosis network
7. Click
8. See nothing happens afterwards, as this is the active EVM network

### **Before**

https://github.com/user-attachments/assets/ef57080b-12ea-4977-8c2d-4dd621ea7e1d

### **After**

https://github.com/user-attachments/assets/14fd660b-363e-440a-b869-d5e04f6729ef

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js [hunk 1]
```diff
@@ -7,18 +7,42 @@ export default class ConfirmDeleteNetwork extends PureComponent {
...
+    } = this.props;
+
+    // An implicit auto-switch in the network-controller should occur
+    // to mainnet when the network being deleted is the current selected
+    // EVM network and the active network is a non-EVM network.
+    //
+    // This logic must be ported to the multichain-network-controller
+    // so the remove use case can be properly handled
+    if (chainId === currentChainId) {
+      await switchEvmNetwork(ethereumMainnetClientId);
```
[the remark this answers is not in the document]
Comment (gantunesr) [reply ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js:40]: No, this is only for the case that Solana is selected. If an EVM network is selected, it can't be deleted

**Review by 1atAlcone — COMMENTED** [review]
test/e2e/flask/solana/solana-eth-networks.spec.ts

**Review by aganglada — DISMISSED** [review]

File: test/e2e/flask/solana/solana-networks.spec.ts [hunk 2]
```diff
@@ -0,0 +1,60 @@
+import { Suite } from 'mocha';
+import { switchToNetworkFlow } from '../../page-objects/flows/network.flow';
+import HeaderNavbar from '../../page-objects/pages/header-navbar';
+import AccountListPage from '../../page-objects/pages/account-list-page';
+import { withSolanaAccountSnap } from './common-solana';
+
+describe('Solana network', function (this: Suite) {
+  it.skip('keeps the network selector enabled when the Solana network is selected', async function () {
```
Comment (ccharly) [inline test/e2e/flask/solana/solana-networks.spec.ts:8]: Is it intended to `skip` this one?

```suggestion
  it('keeps the network selector enabled when the Solana network is selected', async function () {
```

File: test/e2e/flask/solana/solana-networks.spec.ts [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        await headerNavbar.openAccountMenu();
+        const accountMenu = new AccountListPage(driver);
+        await accountMenu.switchToAccount('Account 1');
+        await headerNavbar.check_currentSelectedNetwork('Localhost 8545');
+        await headerNavbar.check_ifNetworkPickerClickable(true);
+      },
+    );
+  });
+
+  it('deletes previously selected EVM network when Solana network is selected', async function () {
```
Comment (ccharly) [inline test/e2e/flask/solana/solana-networks.spec.ts:26]: Feels like the current wording is misleading, like if "selecting the Solana network will delete the previously selected EVM network" 😅 WDYT about this?

```suggestion
  it('can delete the previously selected EVM network when Solana network is selected', async function () {
```

**Comment by ccharly** [comment]
Code LGTM + Tested locally! 👍

Just waiting for my comments to be addressed/rejected on the E2E tests before approving.

**Review by zone-live — APPROVED** [review]

**Review by ccharly — APPROVED** [review]
