### PR TITLE
fix: display of reverse string in signature request message

### LINKED ISSUE #23691: [Bug]: Confirmations Re-design - Reverse String not properly Handled
### Describe the bug

We are re-introducing a security issue where reverse strings are not properly handled.

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot from 2024-03-25 10-18-52

### Steps to reproduce

For reproducing, open the console and paste this (changing the address to your connected address)

`await window.ethereum.request({"method":"personal_sign","params":["0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B", "Sign into \u202E EVIL"],"id":1})`

### Error messages or log output

_No response_

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Fix display of reverse string in signature request message.

## **Related issues**

Fixes: MetaMask/metamask-extension#23691

## **Manual testing steps**
For reproducing, open the console and paste this (changing the address to your connected address)

await window.ethereum.request({"method":"personal_sign","params":["0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B", "Sign into \u202E EVIL"],"id":1})

## **Screenshots/Recordings**
Screenshot 2024-03-27 at 11 54 17 AM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/row/dataTree.tsx [hunk 1]
```diff
@@ -34,7 +34,7 @@ export const DataTree = ({ data }: { data: Record<string, TreeData> }) => (
           }) ? (
             <ConfirmInfoRowAddress address={value} />
           ) : (
-            <ConfirmInfoRowText text={value} />
+            <ConfirmInfoRowText text={sanitizeString(value)} />
```
Comment (jpuri) [inline ui/pages/confirmations/components/confirm/row/dataTree.tsx:37]: I need to do some fixes in this component to be able to unit test cover it. It will be in a followup PR for this issue: https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/23689

**Review by pedronfigueiredo — APPROVED** [review]

**Review by segun — APPROVED** [review]
