### PR TITLE
fix: Remove obsolete network controller state properties

### LINKED ISSUE #20574: Error: No metadata found for 'network'
Sentry Issue: [METAMASK-X62M](https://metamask.sentry.io/issues/4344650755/?referrer=github_integration)

```
Error: No metadata found for 'network'
  at Array.reduce (<anonymous>)
  at handler (app/scripts/lib/ComposableObservableStore.js:69:30)
  at Generator.next (<anonymous>)
...
(6 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## Explanation

There have been user reports and Sentry monitoring errors regarding invalid network controller states.

Implements a new migration that removes any top-level properties on the network controller state object that are not expected, as per the latest `NetworkState` type [on the core repository](https://github.com/MetaMask/core/blob/5a3e28fc2e00cb4ce3db2c6b4bed298c495f28de/packages/network-controller/src/NetworkController.ts#L336-L342):

Currently, this migration makes no changes to obsolete properties at deeper levels of the state object of that controller.

Fixes: #20574

### CODE REVIEW

**Comment by Gudahtt** [comment]
Actually could you make this migration 92.2 instead? We're going to include this in v10.35.1, so it'd be easiest to make it a version that comes before the v10.36 migrations.

File: app/scripts/migrations/096.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+  const updatedState =
+    filterOutObsoleteNetworkControllerStateProperties(originalState);
+
+  return updatedState;
+}
+
+function filterOutObsoleteNetworkControllerStateProperties(
+  state: MetaMaskState,
+): MetaMaskState {
+  // See https://github.com/MetaMask/core/blob/35d887664189110554df1516950424de4171b036/packages/network-controller/src/NetworkController.ts#L360
```
Comment (Gudahtt) [inline app/scripts/migrations/096.ts:41]: Great idea to include this comment! I think we'll want to use this link instead though:

```suggestion
  // See https://github.com/MetaMask/core/blob/%40metamask/network-controller%4010.3.1/packages/network-controller/src/NetworkController.ts#L336
```

That's the type for `@metamask/network-controller@10.3.1`, which is what v10.35.0 is using.

Comment (Gudahtt) [reply app/scripts/migrations/096.ts:41]: Some of the properties differ from that commit as well - we'll want to ensure the migration is written for this version of the network controller. These newer properties won't be in v10.35.1

File: app/scripts/migrations/092.2.test.ts [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  },
+  networksMetadata: {
+    'test-network-client-id': {
+      status: NetworkStatus.Available,
+      EIPS: {},
+    },
+  },
+};
+
+const anyPreviousStateVersion = Math.floor(
```
Comment (Gudahtt) [inline app/scripts/migrations/092.2.test.ts:32]: Nit: Perhaps we could use a static version here instead? I can see how a random version might cover a wider range, but it would be frustrating if this did cause a failure because the error message likely wouldn't include the chosen version anyway.

File: app/scripts/migrations/092.2.ts [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+    'networkDetails',
+    'networkConfigurations',
+  ];
+
+  const networkControllerState: Record<string, any> =
+    state.NetworkController || {};
+  const networkControllerStateProps = Object.keys(networkControllerState);
+
+  // delete network state properties that are not currently in use
+  for (let p = 0; p < networkControllerStateProps.length; p++) {
```
Comment (Gudahtt) [inline app/scripts/migrations/092.2.ts:55]: I see that this line is triggering a lint error because we could use a simpler `for..of` loop here instead.

Another alternative to consider would be using `pick` from `lodash`:

```
return {
  ...state,
  NetworkController: pick(networkControllerState, CURRENT_NETWORK_CONTROLLER_STATE_PROPS),
}
```

File: app/scripts/migrations/092.2.test.ts [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+  it('should return state unaltered if there is no network controller state', async () => {
+    const originalMetaMaskState = {
+      anotherController: 'another-controller-state',
+    };
+    const originalVersionedState = {
+      meta: { version: anyPreviousStateVersion },
+      data: originalMetaMaskState,
+    };
+
+    const updatedVersionedState = await migrate(originalVersionedState);
```
Comment (Gudahtt) [inline app/scripts/migrations/092.2.test.ts:54]: Nit: If we're comparing the inputs here to the outputs, we should deep clone them before passing them in. Otherwise the migration might still mutate the input, and the test wouldn't catch it.

In our case we deep clone the inputs anyway, but better for the test to catch that mistake if we ever make it.

e.g.
```suggestion
    const updatedVersionedState = await migrate(cloneDeep(originalVersionedState));
```

**Review by Gudahtt — DISMISSED** [review]
LGTM! Just one pending minor suggestion

**Comment by Gudahtt** [comment]
Whoops, just noticed that this migration isn't listed in the migration idnex (e.g. `app/scripts/migrations/index.js`)

File: app/scripts/migrations/092.2.test.ts (hunk 4 above)
Comment (Gudahtt) [reply app/scripts/migrations/092.2.test.ts:55]: I see that this was done for the first test, but the remaining tests still don't use it yet

**Review by Gudahtt — DISMISSED** [review]
LGTM! Just one pending minor suggestion to improve the tests

**Review by DDDDDanica — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
