### PR TITLE
fix: toast avatar icon

### LINKED ISSUE #37049: [Bug]: Maskicon different in the dapp connection message versus the Account list
### Describe the bug

While connected to a dapp and switching accounts, there is a message in MetaMask stating that `Account isn't connected to dapp`

The Maskicon in this message is different from the Maskicon in the Account list, even though it's the same account.

Image

### Expected behavior

Same Maskicon to be displayed for the same account

### Screenshots/Recordings

https://github.com/user-attachments/assets/cbe7e858-0d73-4211-84d1-a93b82b42fd5

### Steps to reproduce

1. Connect to a dapp with Account 1
2. While being on dapp page switch to Account 2 in MetaMask
3. Notice message `Account 2 isn't connected to dapp`
4. Notice Maskicon in this message is different than Maskicon in the Accounts list for Account 2

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by n3ps**
## **Description**

Fixes #37049

## **Changelog**

CHANGELOG entry: fix: toast avatar icon

## **Related issues**

Fixes:

## **Manual testing steps**

1. Connect to a dapp
2. Switch to a different account that isn't connected
3. Observe toast

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Connect account group toast now uses a seed address for the avatar and the icon seed selector returns an empty string when no accounts exist, with tests updated accordingly.
> 
> - **UI**:
>   - `ConnectAccountGroupToast` in `ui/components/app/toast-master/toast-master.js` now derives `seedAddress` via `getIconSeedAddressByAccountGroupId` and uses it for `PreferredAvatar`; early-returns if missing.
> - **Selectors**:
>   - `getIconSeedAddressByAccountGroupId` in `ui/selectors/multichain-accounts/account-tree.ts` returns `''` when no accounts are found (instead of throwing).
> - **Tests**:
>   - Update `getIconSeedAddressByAccountGroupId` tests to expect empty string for non-existent group IDs; keep existing seed address expectations.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit d1cd56400266f38867de3be87f41b165f2f5e775. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by montelaidev — DISMISSED** [review]

**Review by AndyMBridges — DISMISSED** [review]

File: ui/selectors/multichain-accounts/account-tree.ts [hunk 1]
```diff
@@ -858,9 +858,7 @@ export const getIconSeedAddressByAccountGroupId = createDeepEqualSelector(
   [getInternalAccountsFromGroupById],
   (accounts: InternalAccount[]): string => {
     if (!accounts || accounts.length === 0) {
-      throw new Error(
-        'Error in getIconSeedAddressByAccountGroupId: No accounts found in the specified group',
-      );
+      return '';
```
Comment (n3ps) [inline ui/selectors/multichain-accounts/account-tree.ts:861]: Make more robust and fallback gracefully. No account -> no icon address

**Review by ccharly — APPROVED** [review]
LGTM (not tested though).

I'm ok with not throwing an exception anymore mainly because groups SHOULD ALWAYS have at least 1 account. That's a strong guarantee we provide at controller-level:
- https://github.com/MetaMask/core/blob/main/packages/account-tree-controller/src/group.ts#L78-L79
- https://github.com/MetaMask/core/blob/main/packages/account-tree-controller/src/group.ts#L93-L94

**Review by ameliejyc — APPROVED** [review]
