### PR TITLE
fix: cp-12.22.3 Fix frequent writes from CronjobController

### LINKED ISSUE #33879: [Bug]: Abnormal disk writing, 5 mb/s 24/7
### Describe the bug

After fresh install chromium based browser (Opera, chrome, Edge) and installing metamask, writing on disk continuously 5 mb/s 24/7. That's about 500Gbytes per day!!  I found that writing happens in Local Extension Setting folder. 3 Files 011717.log 011719.ldb and MANIFEST-000001 renaming every 1 minute and rewriting. Also funny thing is that i installed metamask in Edge browser, but it working in background and extension logged out, Same problems with writing every second.

Writings on disk recorded with Windows Performance Recorder.

First time i noticed this problem in CrystalDiskMark (Screenshot below), Abnormal Writings 25 Terabytes in 3 months

### Expected behavior

_No response_

### Screenshots/Recordings

Image

Image

Image

Image

### Steps to reproduce

1. Fresh install Chrome or Opera or Edge and metamask
2. Create or restore wallet.

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

12.20.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

Prevent frequent high-volume writes caused by state updates from the CronjobController. The controller state includes an event with a timestamp that can be updated very frequently if the user has a snap installed with a scheduled recurring event with a short interval. It can even run while the wallet is otherwise idle, causing the entirety of wallet state to be written to disk repeatedly.

We have temporarily mitigated the problem by moving the CronjobController state to a new top-level storage key, so that it can be written to independently of other state. This controller's state is very small and should not cause any significant amount of write volume.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34413?quickstart=1)

## **Changelog**

CHANGELOG entry: Prevent frequent writes while the wallet UI is closed

## **Related issues**

Fixes: #33879

## **Manual testing steps**

To test that cronjobs work correctly:
1. Go to [test-snaps](https://metamask.github.io/snaps/test-snaps/latest/)
2. Install "Cronjobs Snap".
3. Check if dialog is triggered every 10(?)s. We should update this to send notifications :sweat_smile:
4. Install "Cronjob Duration Snap".
5. Check if notification is sent every 10(?)s.
6. Install "Background Events Snap".
7. Schedule a background event with a certain date or duration.
8. Check if dialog is triggered after the expected duration.

You can restart the client in between steps to ensure persistence works

To test that write volume has been reduced:
* Monitor disk usage while UI is closed
* Add breakpoint in background console in persistence manager to confirm there are no writes

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Mrtenz — DISMISSED** [review]

**Review by Mrtenz — DISMISSED** [review]

File: app/scripts/lib/CronjobControllerStorageManager.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  }
+
+  /**
+   * Get the initial CronjobController state.
+   *
+   * @returns The initial CronjobController state.
+   */
+  getInitialState() {
+    if (!this.#initialized) {
+      throw new Error('CronjobStorageManager not yet initialized');
```
Comment (Gudahtt) [inline app/scripts/lib/CronjobControllerStorageManager.ts]: Strange, I saw Cursor complain about this message using the wrong class name, but now the comment is edited to no longer mention it 🤔 
The mismatch was a mistake, but I'll leave it for now unless I need to commit something else, for the sake of not triggering another CI run. It's fine, we know what the message means anyway.

**Review by Mrtenz — APPROVED** [review]

**Comment by DDDDDanica** [comment]
Tested and LGTM !

**Review by DDDDDanica — APPROVED** [review]
