### PR TITLE
UX Multichain: updated border top for activity list

### LINKED ISSUE #19142: [Bug]: Solid top border still present in Activity and Assets tabs.
### Describe the bug

Original Issue #18917
Unsolved from https://github.com/MetaMask/metamask-extension/pull/18959

https://github.com/MetaMask/metamask-extension/assets/13376180/46c515c9-4840-430d-ba04-c2ccb13d88cd

Seems that `.list-item` has priority over `.transaction-list-item` [list-item/index.scss#L10](https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/ui/list-item/index.scss#L10) 

### Steps to reproduce

1. Open the app to the home page
2. Navigate to Assets tab and see the top grey border of the first asset
3. Navigate to Activity tab and see a top grey border of the first activity (need to have sent/received txs and have incoming tx preferences on)

### Error messages or log output

_No response_

### Version

Current

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
With the ListItem as the parent, the border-top in the transaction list item was not removed. This PR fixes that

I have rendered the style conditionally since this component is not using Box internally, once we update the TransactionListItem for Multichain work, I will remove this inline styling.

Fixes #19142 

### Before

https://github.com/MetaMask/metamask-extension/assets/39872794/784187f5-e1fb-4618-9e66-1adccdb50052

### After

https://github.com/MetaMask/metamask-extension/assets/39872794/3f1a7282-aed2-4346-8512-313990323f78

### Before

https://github.com/MetaMask/metamask-extension/assets/39872794/a588f909-1582-4948-97dd-20e7ee8410c7

### After

https://github.com/MetaMask/metamask-extension/assets/39872794/e575ec98-c419-487e-9dfb-369dfd54561c

## Manual Testing Steps

- Go to this home screen
- Check there is no border after Assets, Activity and NFTs Tab heading in MULTICHAIN Work

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/ui/list-item/list-item.component.js [hunk 1]
```diff
@@ -19,6 +19,8 @@ export default function ListItem({
     className,
     subtitle || children ? '' : 'list-item--single-content-row',
   );
+  const showBorderTop =
```
Comment (darkwing) [inline ui/components/ui/list-item/list-item.component.js:22]: What if instead we add to the primaryClassName?

```
const primaryClassName = classnames(
    'list-item',
    className,
    subtitle || children ? '' : 'list-item--single-content-row',
    { 'list-item-border': process.env.MULTICHAIN && className === 'transaction-list-item'  }
  );
```

Comment (darkwing) [reply ui/components/ui/list-item/list-item.component.js:22]: And better yet, can we make this a prop instead of checking `className === 'transaction-list-item'` since we're passing `transaction-list-item` in when it's used.

File: ui/components/ui/list-item/list-item.component.js [hunk 2]
```diff
@@ -32,6 +34,11 @@ export default function ListItem({
           onClick();
         }
       }}
+      style={
```
Comment (darkwing) [inline ui/components/ui/list-item/list-item.component.js:37]: See comments above about avoiding this.

**Review by darkwing — DISMISSED** [review]

File: ui/components/ui/list-item/list-item.component.js (hunk 1 above)
Comment (NidhiKJha) [reply ui/components/ui/list-item/list-item.component.js]: Nice suggestion 😄  Updated here https://github.com/MetaMask/metamask-extension/pull/19176/commits/3dc160b178053dfda4f054a475b10d67e7e5240d

**Review by darkwing — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]
