### PR TITLE
fix: Fix `navigateNext` logic on multiple confirmations

### LINKED ISSUE #36989: [Bug]: New confirmation types failing to navigate existing confirmations
### Describe the bug

This PR adds "addEthereumChain" into new confirmation architecture https://github.com/MetaMask/metamask-extension/pull/36640 

"addEthereumChain" will be new confirmation under extension redesigned confirmation after signatures and transactions.

While testing we noticed that any confirmation other than signature and transaction it fails to navigate. With this task we will fix that.

More context is here: https://consensys.slack.com/archives/C03ETQA9EPK/p1760574251348019

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Switch to the branch noted above
2. Go to test dapp - trigger a transaction
3. Don't confirm/cancel or close that transaction
4. Then go to https://chainid.network/ and try to add any network to trigger this new confirmation
5. Then navigate into "addEthereumChain" confirmation from confirmation navigation (top of the view)

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

main

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to strengthen `navigateNext` logic in confirmation navigation.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37121?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36989

## **Manual testing steps**

1. Multiple confirmations on https://github.com/MetaMask/metamask-extension/pull/36640 should work

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Refines confirmation navigation by passing the current confirmation ID to `navigateNext` and updating logic to route to the next pending item; updates footer and tests accordingly.
> 
> - **Hooks**:
>   - Update `useConfirmationNavigation.navigateNext` to accept `confirmationId` and navigate to the next pending confirmation excluding the given ID.
>   - Adjust navigation flow to compute next index via `getIndex` and `navigateToIndex`.
> - **UI**:
>   - In `confirm/footer`, pass `currentConfirmation.id` to `navigateNext` on both confirm and cancel actions.
> - **Tests**:
>   - Update tests to call `navigateNext` with the current approval ID and assert correct routing.
>   - Add assertion that footer passes the correct ID to `navigateNext` (e.g., `addEthereumChainApproval.id`).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2554fefd3bb89af3cab3caf5b193ddf533e17617. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/hooks/useConfirmationNavigation.ts [hunk 1]
```diff
@@ -69,11 +69,18 @@ export function useConfirmationNavigation() {
...
   );
 
-  const navigateNext = useCallback(() => {
-    if (count > 1) {
-      navigateToIndex(1);
-    }
-  }, [count, navigateToIndex]);
+  const navigateNext = useCallback(
+    (confirmationId: string) => {
+      const pendingConfirmations = confirmations.filter(
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useConfirmationNavigation.ts:74]: How is this different to just checking `count`, assuming one of the confirmations is always the current one?

File: ui/pages/confirmations/hooks/useConfirmationNavigation.ts [hunk 2]
```diff
@@ -69,11 +69,18 @@ export function useConfirmationNavigation() {
...
+        (confirmation) => confirmation.id !== confirmationId,
+      );
+      if (pendingConfirmations.length >= 1) {
+        const index = getIndex(pendingConfirmations[0].id);
+        navigateToIndex(index);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/hooks/useConfirmationNavigation.ts:79]: Wouldn't we want to go to the new zero always / the first one? What is the current behaviour with the navigation?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/hooks/useConfirmationNavigation.ts (hunk 1 above)
Comment (matthewwalsh0) [reply ui/pages/confirmations/hooks/useConfirmationNavigation.ts:74]: Makes sense, we want to identify all the remaining confirmations, and get the first of those.

File: ui/pages/confirmations/hooks/useConfirmationNavigation.ts (hunk 2 above)
Comment (matthewwalsh0) [reply ui/pages/confirmations/hooks/useConfirmationNavigation.ts:79]: I read this as `getIndex(confirmationId)`, this makes sense also.

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/pages/confirmations/hooks/useConfirmationNavigation.ts (hunk 1 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/hooks/useConfirmationNavigation.ts:74]: Exactly - nothing different than `count`, I just didn't want to overload passing arguments since we can derive that

**Review by n3ps — DISMISSED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by n3ps — APPROVED** [review]
