### PR TITLE
Set a default value for code in _determineTransactionCategory

### LINKED ISSUE #6602: Unable to call ERC20::approve on the Ropsten Test Network
Unable to call ERC20::approve on the Ropsten Test Network.

Getting error `ALERT: Trying to call a function on a non-contract address.`

**To Reproduce**
1. Go to https://ropsten.etherscan.io/address/0x603bc175a26c8f74eaf9bc6ef5dd288afb6fc4b8#writeContract
2. Set _sender to 0xfd2288b96643fe5f75917df6d846998d197bbcdb
3. Set _value to 100000000
4. Applying transaction fails

### PR DESCRIPTION
**Pull request by danjm**
Replaces https://github.com/MetaMask/metamask-extension/pull/6603

Fixes #6602.

In cases where token method calls were being created without specifying `gas` , our `estimateTxGas` method was throwing an error because it is expecting `code` to be truthy. This PR defaults `code` to truthy and only sets it otherwise when necessary.

### CODE REVIEW

File: app/scripts/controllers/transactions/index.js [hunk 1]
```diff
@@ -582,7 +582,7 @@ class TransactionController extends EventEmitter {
     ].find(tokenMethodName => tokenMethodName === name && name.toLowerCase())
 
     let result
-    let code
+    let code = 'default'
```
Comment (frankiebee) [inline app/scripts/controllers/transactions/index.js]: will this have issues when calculating gas in tx-gas-utils?

Comment (frankiebee) [reply app/scripts/controllers/transactions/index.js]: for simple sends

Comment (danjm) [reply app/scripts/controllers/transactions/index.js]: good catch, I think so...

Comment (danjm) [reply app/scripts/controllers/transactions/index.js]: @frankiebee What do you think of the approach in the latest commit? aaca727d7349adb6d3f321582865467dd0a15cde

**Comment by tmashuang** [comment]
Doesn't cover `transferFrom`.

**Review by frankiebee — DISMISSED** [review]
looks good with a QA and test pass: good to merge

**Review by tmashuang — APPROVED** [review]

**Comment by loriopatrick** [comment]
Tested build against merklex.io/trade. Issue resolved. Thanks all!
