### PR TITLE
Enhance approval screen title logic

### LINKED ISSUE #15377: [Bug]:  How can I know which NFT(contract) I am approving in the new confirm panel?
### Describe the bug

Can not know which contract I am interacting with. That's terrible!

### Steps to reproduce

1. trigger `setApproveForAll` function of NFT contracts

### Error messages or log output

_No response_

### Version

10.18.0

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adonesky1**
Fixes: https://github.com/MetaMask/metamask-extension/issues/15377

A minor refactor/enhancement of some of the logic introduced in the [`setApprovalForAll` screen PR](https://github.com/MetaMask/metamask-extension/pull/15010).

Changes:
1. I realized it probably doesn't make sense to only make the title contain a link to the blockExplorer if we don't know the name or symbol of the token, so this makes the name, symbol, or generic "NFT" or "Token" title a link if there is a block explorer available:
          -**setApprovalForAll** : https://user-images.githubusercontent.com/34557516/182232491-e3b9cd7f-6ff7-4acc-8608-f28c977266e0.mov
          -**approve**: https://user-images.githubusercontent.com/34557516/182249887-7d72b514-42e0-4597-b5ea-c136bf4a9c95.mov
2. Fixes a bug where for NFTs (ERC721 or ERC1155) we showed the title (the name, symbol or "NFT") as a link even when we didn't have a block explorer available - meaning the link didn't work.
Before:
https://user-images.githubusercontent.com/34557516/182234026-910793c6-0a75-4ce6-81d8-d1d692e195d6.mov
After:
https://user-images.githubusercontent.com/34557516/182248156-b8852ccb-f3a0-4901-9c42-f111d999c6b5.mov

3. In the case where no block explorer is available, makes the contract address copy to the clipboard when the name/symbol/"NFT" or "Token" label is clicked in the title (cc @SayaGT @rachelcope, not sure if there is some better pattern for making it clear this will copy, tried adding the copy icon, but it looked wrong in this context) :
https://user-images.githubusercontent.com/34557516/182231811-abf183ea-1c0b-4e54-8983-ffe84b19826b.mov

4. Makes the contract address show on hover over the name/symbol/"NFT" or "Token" label in the title (whether or not there is a block explorer link). (Depicted in videos above)

### CODE REVIEW

**Comment by bschorchit** [comment]
This is awesome, Alex ❤️

3. We have this (screenshot) pattern of telling the users that they can click to copy to clipboard, but just the other day a team member shared he didn't know that was a feature so many users might not be aware of it too and it might not be worth to spend time on this. 
Screen Shot 2022-08-01 at 18 27 56
 
In anyway, I wonder if in the case we're displaying "NFT" if a lot of users might not think of hovering over it since it looks like a word within a text (what usually doesn't carry any tooltip). As a fix for this, could we display by default under Permission request and below the "Approved asset" line a new line "Asset contract: 0x..."?

**Comment by adonesky1** [comment]
> As a fix for this, could we display by default under Permission request and below the "Approved asset" line a new line "Asset contract: 0x..."?

I'm all for this, I've suggested something like this to design before but have generally been told that we're going to be moving on to new designs for this screen soon and that it's already too busy, so most of my efforts have been to try and figure out ways to make it work without adding more text...

**Review by danjm — DISMISSED** [review]
I'm good with this from a code perspective if @bschorchit is good with this from a product/UX perspective

**Comment by bschorchit** [comment]
> I'm all for this, I've suggested something like this to design before but have generally been told that we're going to be moving on to new designs for this screen soon and that it's already too busy, so most of my efforts have been to try and figure out ways to make it work without adding more text...

Yes, I understand this push back. I'm good with the proposed solution from the product perspective :)
We'll be indeed further working on this screen in the close future.

File: ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js [hunk 1]
```diff
@@ -512,24 +500,35 @@ export default class ConfirmApproveContent extends Component {
...
-        titleTokenDescription = unknownNFTLink;
+        return blockExplorerElement;
       }
     }
 
-    return titleTokenDescription;
+    return (
+      <span
+        className="confirm-approve-content__approval-asset-title"
+        onClick={() => {
```
Comment (darkwing) [inline ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js:524]: This wouldn't be accessible from a keyboard perspective; could this be a `button`?

File: ui/pages/confirm-approve/confirm-approve-content/index.scss [hunk 2]
```diff
@@ -9,10 +9,14 @@
     padding: 0 24px 16px 24px;
   }
 
-  &__unknown-asset {
+  &__approval-asset-link {
     color: var(--color-primary-default);
   }
 
+  &__approval-asset-title {
+    cursor: pointer;
```
Comment (digiwand) [inline ui/pages/confirm-approve/confirm-approve-content/index.scss:17]: for case #2, when the title does not have a link, can we disable the pointer?

Comment (digiwand) [inline ui/pages/confirm-approve/confirm-approve-content/index.scss:17]: for case # 2, when the title does not have a link, can we disable the pointer?

Comment (adonesky1) [reply ui/pages/confirm-approve/confirm-approve-content/index.scss:17]: My thinking hear was to make the fact that you can click to copy the address (when there isn't a link) somewhat apparent. Probably could/should do the on-hover dropdown as well that Barbara highlights [here](https://github.com/MetaMask/metamask-extension/pull/15406#issuecomment-1201750793)

Comment (adonesky1) [reply ui/pages/confirm-approve/confirm-approve-content/index.scss:17]: Implementing the drop down is going to be a real pain... as noted in the comment linked above we are avoiding putting to much into this since we are going to implement a whole new design very soon?

**Review by brad-decker — APPROVED** [review]

File: ui/pages/confirm-approve/confirm-approve-content/index.scss (hunk 2 above)
Comment (digiwand) [reply ui/pages/confirm-approve/confirm-approve-content/index.scss:17]: oh okay. I was confused by the various cases listed above. Sounds good to me to leave the pointer in and revisit this with the new redesign 👍

File: ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js [hunk 3]
```diff
@@ -519,15 +519,18 @@ export default class ConfirmApproveContent extends Component {
...
+        <span
+          className="confirm-approve-content__approval-asset-title"
+          onClick={() => {
+            copyToClipboard(tokenAddress);
+          }}
+          title={tokenAddress}
+        >
+          {titleTokenDescription}
+        </span>
+        {tokenIdWrapped && <span>{tokenIdWrapped}</span>}
```
Comment (digiwand) [inline ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js:532]: I think we want to check for the length of `tokenIdWrapped` here since it will always be a string

Comment (adonesky1) [reply ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js:532]: an empty string (as `tokenIdWrapped` is set if `tokenId` is undefined) is falsy though so this won't be rendered.

**Review by digiwand — APPROVED** [review]

File: ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js (hunk 3 above)
Comment (digiwand) [reply ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js:532]: oops, yes you're right
