### PR TITLE
Show token symbol when token amount string is long

### LINKED ISSUE #9318: Always show name of Token
I didn't find open issue, so I am posting.

**Describe the bug**
token name is sometimes hidden, which makes extension not really usable

**Expected behavior**
always show token name

**Screenshots**
example of BAT token.
image

example of wETH:
image

**Browser details (please complete the following information):**
- OS X
- Brave with latest Metamask 8.0.8

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes #9318

This essentially separates the token cell list item title/token amount and the token symbol.

I do request advice/recomendations on how to better handle the new `subTitle` which I set the token symbol to and the `subtitle` https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/app/asset-list-item/asset-list-item.js#L99.

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

<div>note the 1234 is the token symbol, wasnt thinking about that confusing aspect that when creating the token</div>
</details>

### CODE REVIEW

File: ui/app/components/ui/list-item/list-item.component.js [hunk 1]
```diff
@@ -57,6 +61,7 @@ export default function ListItem ({
 
 ListItem.propTypes = {
   title: PropTypes.string.isRequired,
```
Comment (brad-decker) [inline ui/app/components/ui/list-item/list-item.component.js:63]: What if, instead of having a new prop, we upgrade title to be ```PropTypes.oneOf([PropTypes.string, PropTypes.node])```

then we could do something like
```js
{React.isValidElement(title) ? title : <h2>title</h2>}
```

then you can move the styles and creation of the subtitle to the asset-list-item instead of the list-item.

Comment (brad-decker) [reply ui/app/components/ui/list-item/list-item.component.js:63]:
```
title={(
 <>
   <h2 className="asset-list-item__title">{value}</h2>
   <h2 className="asset-list-item__subTitle">{symbol}</h2>
</>
)}
```

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/app/components/ui/list-item/list-item.component.js (hunk 1 above)
Comment (brad-decker) [reply ui/app/components/ui/list-item/list-item.component.js:63]: you could also use more descriptive names for the classes then and avoid the double usage of 'subtitle' surrounding list-item.

Comment (tmashuang) [reply ui/app/components/ui/list-item/list-item.component.js]: 82fc160

File: ui/app/components/ui/list-item/index.scss [hunk 2]
```diff
@@ -44,11 +44,6 @@
     display: flex;
     align-items: center;
 
-    > h2 {
```
Comment (brad-decker) [inline ui/app/components/ui/list-item/index.scss:47]: We'll still need this for other instances of the list-item, but you can put a specific class on this so you can override the behavior in `asset-list-item`.

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/app/components/ui/list-item/index.scss (hunk 2 above)
Comment (tmashuang) [reply ui/app/components/ui/list-item/index.scss:47]: 8a3306f

**Review by brad-decker — APPROVED** [review]
LGTM
