### PR TITLE
I938 uri validation

### LINKED ISSUE #938: Handle case when user enters custom RPC url with no prefix
If you just enter `0.0.0.0:8545`, metamask will silently fail, even though we know it's the lack of an http/https prefix.

Either we should try to find the right protocol, or we should warn the user.

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Fixes #938 with some basic validations: it'll check if the URI is a valid one and warn users to append an http prefix if that's the only issue.

### CODE REVIEW

**Comment by flyswatter** [comment]
Could you include a screenshot of what the warning looks like when entering an invalid URI, like our sample `0.0.0.0:8545`?

File: app/scripts/notice-controller.js [hunk 1]
```diff
@@ -27,36 +27,36 @@ module.exports = class NoticeController extends EventEmitter {
...
     var data = this.configManager.getData()
     data.noticesList = list
     this.configManager.setData(data)
     return Promise.resolve(true)
   }
 
-  markNoticeRead(notice, cb) {
-    cb = cb || function(err){ if (err) throw err }
+  markNoticeRead (notice, cb) {
+    cb = cb || function (err) { if (err) throw err }
```
Comment (flyswatter) [inline app/scripts/notice-controller.js]: Furthermore, all this linting is interfering with my ability to easily see what you actually changed in this PR.

Maybe we should just update the lintfile and all outlying instances of this stuff at once, in its own PR.

File: ui/app/config.js [hunk 2]
```diff
@@ -34,6 +37,14 @@ ConfigScreen.prototype.render = function () {
         h('h2.page-subtitle', 'Settings'),
       ]),
 
+      h('.error', {
+        style: {
+          display: warning ? 'block' : 'none',
```
Comment (flyswatter) [inline ui/app/config.js]: This is a clean way to conditionally include the element, not bad!

File: ui/app/config.js [hunk 3]
```diff
@@ -99,6 +110,19 @@ ConfigScreen.prototype.render = function () {
   )
 }
 
+function rpcValidation (newRpc, state) {
+  if (validUrl.isWebUri(newRpc)) {
+    state.dispatch(actions.setRpcTarget(newRpc))
+  } else {
+    var appendedRpc = `http://${newRpc}`
+    if (validUrl.isWebUri(appendedRpc)) {
+      state.dispatch(actions.displayWarning('URIs require the appropriate HTTP/HTTPS prefix.'))
```
Comment (flyswatter) [inline ui/app/config.js]: I actually don't think we should bother trying any prefix, since we don't know what protocol the actual address should refer to.  Showing a warning should be sufficient.

**Review by danfinlay — CHANGES_REQUESTED** [review]
A few things:
- I'd like a screenshot of the warning
- I don't want us to coerce the URIs, just warn.

**Comment by flyswatter** [comment]
Fixes #941

File: ui/app/config.js (hunk 3 above)
Comment (Zanibas) [inline ui/app/config.js]: My reasoning for this is that if the URI validator works the first time, then we're cool. If the URI validator works when we append a simple http:// prefix, then we warn users to use it (we don't automatically append it because we are unsure of whether they want to use an HTTP or HTTPS protocol). If the URI doesn't even work with that, then we just throw a general warning.

So unless we want to just do a simple URI validation, this is a fairly clean way to check if they're just missing an http:// without making too many assumptions.

Comment (flyswatter) [inline ui/app/config.js]: I think it's ok to warn them that it's definitely a prefix problem, but it's less ok to auto-fill a prefix, since we may have misled them that we fixed it.  Not 100% on that, though...

**Comment by Zanibas** [comment]
screenshot from 2016-12-21 12-01-55

screenshot from 2016-12-21 12-02-18

File: ui/app/config.js (hunk 3 above)
Comment (flyswatter) [inline ui/app/config.js]: Oh I see, you aren't changing what they typed, you're just telling them the type of error. Yeah, that's ok with me.  Thanks for clarifying.

**Review by danfinlay — APPROVED** [review]
