### PR TITLE
fix: Fix multiple confirmation navigation

### LINKED ISSUE #36989: [Bug]: New confirmation types failing to navigate existing confirmations
### Describe the bug

This PR adds "addEthereumChain" into new confirmation architecture https://github.com/MetaMask/metamask-extension/pull/36640 

"addEthereumChain" will be new confirmation under extension redesigned confirmation after signatures and transactions.

While testing we noticed that any confirmation other than signature and transaction it fails to navigate. With this task we will fix that.

More context is here: https://consensys.slack.com/archives/C03ETQA9EPK/p1760574251348019

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Switch to the branch noted above
2. Go to test dapp - trigger a transaction
3. Don't confirm/cancel or close that transaction
4. Then go to https://chainid.network/ and try to add any network to trigger this new confirmation
5. Then navigate into "addEthereumChain" confirmation from confirmation navigation (top of the view)

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

main

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to force navigation to next confirmation when current confirmation is not signature/transaction.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36990?quickstart=1)

## **Changelog**

CHANGELOG entry: Fix a bug when multiple confirmation exist but navigation fails to when approving

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36989

## **Manual testing steps**

1. Switch to the branch noted in task
2. Go to test dapp - trigger a transaction
3. Don't confirm/cancel or close that transaction
4. Then go to https://chainid.network/ and try to add any network to trigger this new confirmation
5. Then navigate into "addEthereumChain" confirmation from confirmation navigation (top of the view)

### **Before**

https://github.com/user-attachments/assets/987dff57-5e9a-45bd-afaf-681089c8aea6

### **After**

https://github.com/user-attachments/assets/3e89c061-f6f6-4e0b-9bde-ebe18b1d0e29

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds navigation to the next confirmation after confirming or canceling, via a new navigateNext hook method, with corresponding tests.
> 
> - **Confirmations UI**:
>   - `ui/pages/confirmations/components/confirm/footer/footer.tsx`: Integrates `useConfirmationNavigation`; invokes `navigateNext()` after submit and cancel; precomputes `isTransactionConfirmation`.
> - **Navigation Hook**:
>   - `ui/pages/confirmations/hooks/useConfirmationNavigation.ts`: Adds `navigateNext()` (jumps to index 1 when multiple), exposes `count` and navigation helpers.
>   - Tests (`useConfirmationNavigation.test.ts`): Adds test for `navigateNext()`.
> - **Tests**:
>   - `footer.test.tsx`: Mocks `useConfirmationNavigation`, adds cases asserting navigation on Confirm/Cancel when multiple approvals exist.
>   - `test/data/confirmations/helper.ts`: Adds `addEthereumChainApproval` fixture for `wallet_addEthereumChain`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 26b81b24f160a1445155e7b458eecdd97ed24447. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 1]
```diff
@@ -224,17 +230,34 @@ const Footer = () => {
...
+    const isNavigationNeeded =
+      hasPendingApprovalRequests && !isTransactionConfirmation && !isSignature;
+
     if (isTransactionConfirmation) {
       onTransactionConfirm();
     } else {
       dispatch(resolvePendingApproval(currentConfirmation.id, undefined));
     }
+
+    if (isNavigationNeeded) {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx]: Do we also need this for reject?

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 2]
```diff
@@ -224,17 +230,34 @@ const Footer = () => {
...
+      const nextIndex = getIndex(pendingApprovalRequests[0]?.id);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx]: If we've only just approved in this same function, won't this reference the current confirmation?

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 3]
```diff
@@ -224,17 +230,34 @@ const Footer = () => {
       currentConfirmation?.type,
     );
 
+    const pendingApprovalRequests = approvalRequests.filter(
+      (approval) => approval.id !== currentConfirmation.id,
+    );
+    const hasPendingApprovalRequests = pendingApprovalRequests.length > 0;
+    const isNavigationNeeded =
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx]: Could we just check `count` from `useConfirmationNavigation` and always call `navigateToIndex(1) if the count is greater than 1`?

Would it cause any harm, even if the parent component is redirecting for transaction and signature?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/components/confirm/footer/footer.tsx (hunk 2 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/footer/footer.tsx]: I was filtering the current confirmation by id just couple lines above - so it was referencing the next one. But I removed that code as suggested below because it was unnecessary - now it will always navigate to `1`

File: ui/pages/confirmations/components/confirm/footer/footer.tsx (hunk 1 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/footer/footer.tsx]: Added that

File: ui/pages/confirmations/components/confirm/footer/footer.tsx (hunk 3 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/footer/footer.tsx]: Done - now navigation happens in `useConfirmationNavigation`.

I didn't encounter any issues on local tests so assuming it's not harmful

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 4]
```diff
@@ -220,19 +226,23 @@ const Footer = () => {
...
-      currentConfirmation?.type,
-    );
-
     if (isTransactionConfirmation) {
       onTransactionConfirm();
     } else {
       dispatch(resolvePendingApproval(currentConfirmation.id, undefined));
     }
+
+    if (isNavigationNeeded) {
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx]: Regarding the risk, I was meaning can we omit the `isNavigationNeeded` logic here and always call `navigateNext`?

If we plan to remove `confirm-transaction` in future, will this cause any harm if we navigate to the same place anyway?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: ui/pages/confirmations/components/confirm/footer/footer.tsx (hunk 4 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/footer/footer.tsx]: I added `isNavigationNeeded` to specifically fix the case for "addEthereumChain" and let current logic work as is since we don't have an issue with signatures and transactions. But of course we can omit and do the navigation here all the time, removed it.

I think it will be fine as we did it in the "confirm" or "cancel" callbacks but don't want to speak upfront 🙂 Navigation is the essential feature - it will be tested well if we do deletion in future anyway.

File: ui/pages/confirmations/components/confirm/footer/footer.tsx [hunk 5]
```diff
@@ -209,6 +211,9 @@ const Footer = () => {
   });
 
   const isSignature = isSignatureTransactionType(currentConfirmation);
+  const isTransactionConfirmation = isCorrectDeveloperTransactionType(
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/footer/footer.tsx:214]: Is this unused now?

**Review by matthewwalsh0 — APPROVED** [review]

File: ui/pages/confirmations/components/confirm/footer/footer.tsx (hunk 5 above)
Comment (OGPoyraz) [reply ui/pages/confirmations/components/confirm/footer/footer.tsx:214]: It's still in-use for `onTransactionConfirm` - just left outside of the hook after recent changes but can put back in

**Review by vinistevam — APPROVED** [review]
