### PR TITLE
Increase friction to bypass estimated revert

### LINKED ISSUE #11966: Increase friction to bypass estimated revert
Cross posted as https://github.com/MetaMask/metamask-mobile/issues/3077

[A twitter user comments](https://twitter.com/0xfoobar/status/1431805767003230209?s=21) that many new users are confused by having an estimated gas as well as a "transaction expected to fail" warning, because it implies that maybe this is what the transaction would cost to execute normally.

One possible improvement:
- If the transaction would revert/fail, hide the gas estimate info at first, as well as maybe disabling the confirm button.
- Need to still provide a way for pro users to override this. Something like "I want to submit this anyway", which would reveal the gas estimate and the confirm button.

This would need design, and then be a cross-product change.

Rating this as a sev2, but it's probably a high sev2, since it scares new users.

### PR DESCRIPTION
**Pull request by segun**
Fixes: #11966 

Explanation:      If a transaction would revert/fail,
        1. hide the gas estimate info.
        2. Disable the confirm button.
        3. All user to enable the confirm button anyways.
        4. Do not show the default Transaction error message
        
**Before**
Screenshot 2021-11-04 at 02 02 48

**After - Before I will try is clicked**
Screenshot 2021-11-05 at 01 02 49

**After - After I will try is clicked**
Screenshot 2021-11-05 at 01 03 02

### CODE REVIEW

**Comment by danjm** [comment]
The screen shot looks different from the proposed design, is that intentional?

I am referring to the design posted here https://github.com/MetaMask/metamask-extension/issues/11966#issuecomment-957696132

File: ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js [hunk 1]
```diff
@@ -91,12 +106,42 @@ export default class ConfirmPageContainerContent extends Component {
...
         {warning ? <ConfirmPageContainerWarning warning={warning} /> : null}
         {ethGasPriceWarning && (
           <ConfirmPageContainerWarning warning={ethGasPriceWarning} />
         )}
+        {hasSimulationError && (
+          <div className="confirm-page-container-content__error-container">
+            <ActionableMessage
+              type="danger"
+              message={this.context.t('simulationErrorMessage', [
+                <Button
```
Comment (danjm) [inline ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js:124]: The button does not need to be a child of the translation string. See `metamask-extension/ui/components/ui/actionable-message/actionable-message.stories.js` for how you can use the `primaryAction` property of the `ActionableMessage` component to specify the label and action for the button

File: ui/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 2]
```diff
@@ -403,119 +410,125 @@ export default class ConfirmTransactionBase extends Component {
...
+        />
+      ) : (
+        ''
+      );
+    };
+
     return (
       <div className="confirm-page-container-content__details">
         <TransactionDetail
           onEdit={() => this.handleEditGas()}
```
Comment (danjm) [inline ui/pages/confirm-transaction-base/confirm-transaction-base.component.js:529]: The "Edit" button will also need to be hidden if simulation has failed

File: ui/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 3]
```diff
@@ -403,119 +410,125 @@ export default class ConfirmTransactionBase extends Component {
...
+                  maxFeePerGas={hexWEIToDecGWEI(
+                    maxFeePerGas || txData.txParams.maxFeePerGas,
+                  )}
+                />
+              )}
+            </>
+          }
+        />
+      ) : (
+        ''
```
Comment (danjm) [inline ui/pages/confirm-transaction-base/confirm-transaction-base.component.js:522]: We usually use `null` instead of an empty string if we want to hide something

File: ui/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 4]
```diff
@@ -228,20 +228,23 @@ export default class ConfirmTransactionBase extends Component {
     if (insufficientBalance) {
       return {
         valid: false,
+        hasSimulationError: false,
```
Comment (danjm) [inline ui/pages/confirm-transaction-base/confirm-transaction-base.component.js:231]: Instead of adding `hadSimulationError` to the return of `getErrorKey`, we could just use `const hasSimulationError = Boolean(txData.simulationFails);` on line 321

File: ui/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 5]
```diff
@@ -313,6 +318,8 @@ export default class ConfirmTransactionBase extends Component {
     } = this.props;
     const { t } = this.context;
 
+    const { hasSimulationError } = this.getErrorKey();
```
Comment (danjm) [inline ui/pages/confirm-transaction-base/confirm-transaction-base.component.js:321]: See comment here https://github.com/MetaMask/metamask-extension/pull/12576/files#r742574729

File: ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js (hunk 1 above)
Comment (segun) [reply ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js:124]: HI Dan, I tried that, but I had 2 issues with it

1.  I couldn't get the primary action to fire the event correctly. Basically the state is not changing on click.
2. I couldn't get the button to be in red :(

I saw another component use this method though.

Comment (segun) [reply ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js:124]: okay, got it working

File: app/_locales/en/messages.json [hunk 6]
```diff
@@ -1106,6 +1106,9 @@
   "history": {
     "message": "History"
   },
```
Comment (jpuri) [inline app/_locales/en/messages.json:1108]: May be key here can be improved `iWillTryAnyway`

**Review by jpuri — DISMISSED** [review]
LGTM 👍

File: ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+        'This transaction is expected to fail. Trying to execute it is expected to be expensive but fail, and is not recommended.',
+      ),
+    ).toBeInTheDocument();
+    expect(queryByText('I will try anyway')).toBeInTheDocument();
+
+    const confirmButton = getByText('Confirm');
+    expect(getByText('Confirm').closest('button')).toBeDisabled();
+    fireEvent.click(confirmButton);
+    await tick();
+    expect(props.onSubmit).toHaveBeenCalledTimes(0);
```
Comment (jpuri) [inline ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js:63]: I am not sure if `await tick();` should be needed.

File: ui/pages/confirm-transaction-base/confirm-transaction-base.component.js [hunk 8]
```diff
@@ -965,8 +989,9 @@ export default class ConfirmTransactionBase extends Component {
         lastTx={lastTx}
         ofText={ofText}
         requestsWaitingText={requestsWaitingText}
+        hideConfirmAnyways={!isDisabled()}
         disabled={
-          !valid ||
+          isDisabled() ||
           submitting ||
```
Comment (mcmire) [inline ui/pages/confirm-transaction-base/confirm-transaction-base.component.js:995]: [nit] What do you think about placing the rest of these in `isDisabled` as well? It might be easier from a maintenance perspective if these were all in one place rather than split up.

**Review by jpuri — DISMISSED** [review]

**Review by mcmire — DISMISSED** [review]
A couple of minor things, but looks good to me regardless.

**Review by jpuri — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

File: ui/pages/confirm-transaction-base/confirm-transaction-base.component.js (hunk 8 above)
Comment (segun) [reply ui/pages/confirm-transaction-base/confirm-transaction-base.component.js:1017]: isDisabled() is used elsewhere that doesn't require the extra checks.

File: ui/components/app/transaction-detail/transaction-detail.component.js [hunk 9]
```diff
@@ -17,7 +17,11 @@ const GasLevelIconMap = {
   custom: '⚙',
```
Comment (danjm) [inline ui/components/app/transaction-detail/transaction-detail.component.js:17]: The changes in this file are no longer needed because we hide the edit button now https://github.com/MetaMask/metamask-extension/pull/12576/files#diff-a6209b43f1af7f5cf53ecdaba18ee1e22d0bdc774bc369daaefa4583a9d25fb2R573-R575

**Review by danjm — CHANGES_REQUESTED** [review]
Only one more change needed in my opinion

**Review by mcmire — DISMISSED** [review]
One small nit, but honestly I'm good with this 👍🏻

File: ui/components/ui/actionable-message/actionable-message.js [hunk 10]
```diff
@@ -35,6 +36,9 @@ export default function ActionableMessage({
     { 'actionable-message--with-icon': useIcon },
   );
 
+  const onlyOneAction =
+    (primaryAction || secondaryAction) && (!primaryAction || !secondaryAction);
```
[the remark this answers is not in the document]
Comment (danjm) [reply ui/components/ui/actionable-message/actionable-message.js]: yeah, I like `(primaryAction && !secondaryAction) || (!primaryAction && secondaryAction)`

**Review by mcmire — DISMISSED** [review]
Looks good!

**Review by danjm — APPROVED** [review]
LGTM

**Review by mcmire — APPROVED** [review]
