### PR TITLE
Fix 3box replacement for MV3

### LINKED ISSUE #15969: Data backup does not work in MV3
> The 3box replacement is calling some window functions in backup controller. In MV3, these functions are not available in service worker, so we need to move the functions to the ui and backup controller should just return the data to be backed up and the actual backup (where the window functions are used should happen in the UI

### PR DESCRIPTION
**Pull request by segun**
Fixes #15969

## Explanation

The 3box replacement is calling some `window` functions in backup controller. In MV3, these functions are not available in service worker, so we need to move the functions to the ui and backup controller should just return the data to be backed up and the actual backup (where the `window` functions are used should happen in the UI

## More Information

* See: [more details](https://github.com/MetaMask/metamask-extension/issues/14888#issuecomment-1241330206)

## Manual Testing Steps

**Before this change**
Start extension using `yarn start:mv3` 
Go to Advanced Settings -> Backup your data
Open console
Click Backup
You should see error in the console saying window.xxx is undefined and the backup should fail

**Apply this change**
Start extension using `yarn start:mv3` 
Go to Advanced Settings -> Backup your data
Open console
Click Backup
You should **NOT** see error in the console saying window.xxx is undefined and the backup should succeed

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

File: ui/pages/settings/advanced-tab/advanced-tab.component.js [hunk 1]
```diff
@@ -256,8 +256,14 @@ export default class AdvancedTab extends PureComponent {
             <Button
               type="secondary"
               large
-              onClick={() => {
-                this.props.backupUserData();
+              onClick={async () => {
+                const { fileName, data } = await this.props.backupUserData();
+                exportAsFile(fileName, data);
+
+                this._trackMetaMetricsEvent({
```
Comment (brad-decker) [inline ui/pages/settings/advanced-tab/advanced-tab.component.js:263]: This method doesn't exist, and seems to be the background method name, you'll need to use the context to get access to the frontend tracking method.

**Review by brad-decker — CHANGES_REQUESTED** [review]

File: ui/pages/settings/advanced-tab/advanced-tab.component.js (hunk 1 above)
Comment (segun) [reply ui/pages/settings/advanced-tab/advanced-tab.component.js:263]: Oh shoot. Yes. Thanks.

**Review by jpuri — DISMISSED** [review]
Looks good to me except for small feedback.

**Review by danjm — DISMISSED** [review]

**Comment by seaona** [comment]
LGTM @segun

Just as extra info, at the moment, when I terminate the service worker in the middle of the Restore action, I am logged out and I am still able to upload a backup file but it has no effect into the state. 
I will test this again once your PR and David's PR about keeping the user logged in are merged. So we can see both actions combined.

[restore-backup.webm](https://user-images.githubusercontent.com/54408225/192240460-ff4cb89a-b970-4361-bad3-5b7d4d67d81a.webm)

**Review by danjm — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]
