### PR TITLE
Fix #20184 - Prevent overflow within the activity list

### LINKED ISSUE #20184: [Bug]: Long contract method enables horizontal scrolling
### Describe the bug

When interacting with a long contract method name the row goes out of the extension/popup views borders and enables horizontal scrolling.

### Steps to reproduce

1. Deploy and mint nft from [test dapp](https://metamask.github.io/test-dapp/) on a testnet (Goerli)
2. Add newly created nft .
3. Send nft to self.
4. Ensure that the contract method is similar to `Send Test Dapp Collectibles #1` or as long as it.

https://github.com/MetaMask/metamask-extension/assets/13376180/8b3d79f4-b1fb-413a-9374-0358e8b63207

### Error messages or log output

_No response_

### Version

10.35.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

* Fixes #20184

This PR prevents the activity list from overflowing in small widths with long activity events.

## Screenshots/Screencaps

SCR-20230725-pncq

## Manual Testing Steps

Follow steps in issue.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/components/multichain/activity-list-item/activity-list-item.js [hunk 1]
```diff
@@ -66,7 +66,11 @@ export const ActivityListItem = ({
         gap={4}
       >
         {icon && <Box display={Display.InlineFlex}>{icon}</Box>}
-        <Box display={Display.InlineFlex} width={BlockSize.Full}>
+        <Box
+          display={Display.InlineFlex}
+          width={BlockSize.Full}
+          style={{ overflow: 'hidden' }}
```
Comment (georgewrmarshall) [inline ui/components/multichain/activity-list-item/activity-list-item.js:72]: I know it's a little more overhead on the engineering side but I'm hesitant to recommend inline styles because I think classNames are in general more scalable, performant and have a better developer experience.

**Review by georgewrmarshall — COMMENTED** [review]
I would suggest using a className to handle any additional styles outside of the style utility props unless it's a dynamic value that we can't generate classNames for. I think this is probably something we could add to the contributor docs

**Review by vthomas13 — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

File: ui/components/multichain/activity-list-item/activity-list-item.js (hunk 1 above)
Comment (vthomas13) [reply ui/components/multichain/activity-list-item/activity-list-item.js]: added in db62a525f0884a768bd2e5d066241b7cfcf6f10d

**Review by vthomas13 — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]
