### PR TITLE
fix(accounts): prevent crash when account tree references orphaned account IDs

### LINKED ISSUE #41141: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
Sentry Issue: [METAMASK-YH74](https://metamask.sentry.io/issues/7231863018/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
  at find (ui/selectors/multichain-accounts/account-tree.ts:197:32)
  at Array.find (<anonymous>)
  at exports.getWalletIdAndNameByAccountAddress (ui/selectors/multichain-accounts/account-tree.ts:196:40)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
  at e.<computed> (/metamask/scripts/sentry-install.js:1:760)
...
(40 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

When state corruption occurs (e.g. after a wallet reset or Snap keyring reset), the `accountTree` can contain account IDs that no longer exist in `internalAccounts`. In `getWalletsWithAccounts`, spreading `undefined` via `{ ...accountsById[missingId] }` produces an empty object with no `address` property. Downstream, `getWalletIdAndNameByAccountAddress` then calls `.toLowerCase()` on `undefined`, crashing with:

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
  at getWalletIdAndNameByAccountAddress (ui/selectors/multichain-accounts/account-tree.ts)
```

**Root cause:** The account tree references entropy source IDs that no longer exist in the actual keyrings — typically after a user forgets their password and uses the wallet reset flow, or after using Snaps.

**Fix:**
1. **`getWalletsWithAccounts`** — added a `.filter()` before `.map()` to skip any account ID that has no entry in `accountsById`. This prevents orphaned entries from ever entering the consolidated wallet data structure.
2. **`getWalletIdAndNameByAccountAddress`** — added optional chaining `acc.address?.toLowerCase()` as a defensive guard.
3. Three regression tests added to prevent future regressions.

## **Changelog**

CHANGELOG entry: Fixed a crash that could occur for users with corrupted wallet state after a password reset or Snap keyring usage.

## **Related issues**

Fixes: #41141
Fixes: https://consensyssoftware.atlassian.net/browse/MUL-1633

## **Manual testing steps**

This bug is triggered by corrupted state, which is hard to reproduce manually. The fix is covered by unit tests. To verify:

1. Run `yarn test:unit ui/selectors/multichain-accounts/account-tree.test.ts` — all 75 tests should pass.
2. Load the extension normally and verify the account list renders without errors.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

Made with [Cursor](https://cursor.com)

---

> [!NOTE]
> **Low Risk**
> Low risk defensive change in selectors: it only filters out account IDs that cannot be resolved to `internalAccounts`, preventing crashes in downstream lookups. Main impact is that corrupted/stale entries will no longer appear in consolidated wallet/group account lists.
> 
> **Overview**
> Prevents crashes when `accountTree` contains stale/orphaned account IDs by filtering unresolved IDs out of `getWalletsWithAccounts` before building the consolidated wallets/groups structure.
> 
> Adds regression tests covering: filtering orphaned IDs from groups, `getWalletIdAndNameByAccountAddress` not throwing with corrupted state, and returning `null` when all referenced accounts are orphaned.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit d7796094e9afb31cc34daa65c7173006c7b5f3d1. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/selectors/multichain-accounts/account-tree.ts [hunk 1]
```diff
@@ -208,7 +210,7 @@ export const getWalletIdAndNameByAccountAddress = createParameterizedSelector(
     for (const [walletId, wallet] of Object.entries(walletsWithAccounts)) {
       for (const group of Object.values(wallet.groups)) {
         const account = group.accounts.find(
-          (acc) => acc.address.toLowerCase() === address.toLowerCase(),
+          (acc) => acc.address?.toLowerCase() === address.toLowerCase(),
```
Comment (hmalik88) [inline ui/selectors/multichain-accounts/account-tree.ts]: Is this needed considering we're filtering out undefined?

Comment (gantunesr) [reply ui/selectors/multichain-accounts/account-tree.ts]: good point https://github.com/MetaMask/metamask-extension/pull/41405/commits/b72ce5d1896be01771805974705c2c48ee6fa984

**Review by hmalik88 — APPROVED** [review]

**Review by montelaidev — APPROVED** [review]
