### PR TITLE
Transaction-list-item-details pop up to display the correct token information on token approve item

### LINKED ISSUE #17228: [Bug]: Spend Limit amount from an Approve transaction points to ETH instead of the ERC20 token
### Describe the bug

**Problem**: when you have performed an Approve transaction, if you check the transaction details you will see a field for `spend limit amount` which is pointing to the incorrect value (ETH) instead of the ERC20 token limit.

spend-limit

### Steps to reproduce

1. Go to test dapp
2. Connect to test dapp
3. Click Create Token - accept on MM
4. Click Approve - accept on MM
5. Wait until tx is confirmed
6. Click on the tx, to see tx details
7. Check that `spend amount limit` indicates ETH and the ETH value you send along that call, instead of the ERC20 token where you made the approval and the token limit you set on the approval screen

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
## Explanation
Fixes #17228 
Currently, for approve token pop up `Transaction-list-item-details` displays the details of only those tokens that are added to the wallet, if not a generic detail is displayed as shown in the ticket. With this fix, we are comparing the token address to the tokens available in detected tokens, tokens list, and custom tokens.

## Manual Testing Steps

1. Create a token from the test-dapp
2. Click approve token in the test-dapp
3. Once the token is approved, go to the activity tab and click Approve Token spending Cap and verify the amount in `spending cap`.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

File: ui/hooks/useTransactionDisplayData.js [hunk 1]
```diff
@@ -121,18 +128,33 @@ export function useTransactionDisplayData(transactionGroup) {
...
+    token =
+      knownTokens.find(({ address }) =>
+        isEqualCaseInsensitive(address, recipientAddress),
+      ) ||
+      detectedTokens.find(({ address }) =>
+        isEqualCaseInsensitive(address, recipientAddress),
+      ) ||
+      tokenList[recipientAddress.toLowerCase()] ||
+      customToken;
+  }
```
Comment (jpuri) [inline ui/hooks/useTransactionDisplayData.js:158]: Will be nice to have test coverage for above hook.

File: ui/hooks/useAssetDetails.js [hunk 2]
```diff
@@ -60,6 +66,7 @@ export function useAssetDetails(tokenAddress, userAddress, transactionData) {
     collectibles,
     tokensWithBalances,
     prevTokenBalance,
+    isTokenCategory,
   ]);
 
   if (currentAsset) {
```
Comment (jpuri) [inline ui/hooks/useAssetDetails.js:72]: Does this hook has existing other usages also ?

Comment (NiranjanaBinoy) [reply ui/hooks/useAssetDetails.js:72]: Yes, it is used in <ConfirmTokenTransactionSwitch/>  as well. Since `useTransactionDisplayData` hook is not token-specific, it was throwing an error `'Unable to detect valid token data` while calling `getAssetDetails` from `useAssetDetails` while parsing the txData. So I added an `isTokenCategory` check to ensure only token approve and token transfer activities will call `getAssetDetails`.

File: ui/hooks/useTransactionDisplayData.js (hunk 1 above)
Comment (NiranjanaBinoy) [reply ui/hooks/useTransactionDisplayData.js:158]: Test is added by adding a new set of data to transaction-data.json

File: test/e2e/metamask-ui.spec.js [hunk 3]
```diff
@@ -403,6 +402,7 @@ describe('MetaMask', function () {
         },
         { timeout: 10000 },
       );
+      await driver.waitForElementNotPresent('.loading-overlay');
```
Comment (jpuri) [inline test/e2e/metamask-ui.spec.js:405]: 👍

**Review by jpuri — DISMISSED** [review]
👍

**Review by digiwand — DISMISSED** [review]
tested on macOS x Chrome - LGTM! 

left one minor suggestion above

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by jpuri** [comment]
Hey @NiranjanaBinoy , @seaona : I am curious why some much e2e fixes were needed in this PR. Does it introduces delay at some point ?

**Comment by NiranjanaBinoy** [comment]
> Hey @NiranjanaBinoy , @seaona : I am curious why some much e2e fixes were needed in this PR. Does it introduces delay at some point ?
Hi @jpuri,
The tests are failing only on firefox Circle CI. 

In this PR, we are introducing `useAssetDetails` to `useTransactionDisplayData`, which will be called when the transaction lists are displayed in the activity tab. This means `useAssetDetails` will be getting called for all the transactions, but inside the `useAssetDetails`, we are restricting the `getAssetDetails` calls based on the `isTokenCategory` so the `getAssetDetails` will get executed only for token approvals and transfers. I am not exactly sure, but I am suspecting that calling `useAssetDetails` for the transactions in the list might have introduced a slight delay but the functionalities inside the hook are not fully executed for any transaction other than token transfer or approval.

**Review by Katew212 — DISMISSED** [review]
How

File: ui/hooks/useTransactionDisplayData.js [hunk 4]
```diff
@@ -121,18 +129,53 @@ export function useTransactionDisplayData(transactionGroup) {
...
+        recipientAddress,
+        senderAddress,
+        initialTransaction?.txParams?.data,
+        knownNfts,
+      );
+      setCurrentAssetDetails(assetDetails);
+    }
+    if (isTokenCategory && !token) {
+      getAndSetAssetDetails();
+    }
```
Comment (jpuri) [inline ui/hooks/useTransactionDisplayData.js:163]: Hey @NiranjanaBinoy : any reason for preferring above approach. May be this:

```
if (isTokenCategory && !token) {
      const assetDetails = await getAssetDetails(
        recipientAddress,
        senderAddress,
        initialTransaction?.txParams?.data,
        knownNfts,
      );
      setCurrentAssetDetails(assetDetails);
}
```

**Review by jpuri — DISMISSED** [review]
LGTM, just a small feedback added.

File: ui/hooks/useTransactionDisplayData.js (hunk 4 above)
Comment (NiranjanaBinoy) [reply ui/hooks/useTransactionDisplayData.js:162]: Updated the changes

**Review by jpuri — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
