### PR TITLE
fix: Fix ens domain name resolution in confirmation after send flow

### LINKED ISSUE #36966: [Bug]: Missing ENS name on send confirmation
### Describe the bug

If the user sends to an ENS we don't show the icon and ENS name within the confirmation.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/76a71ddc-3d4b-425d-b173-95c968dd9413

### Steps to reproduce

1. Start a send
2. Input an ENS name
3. Continue to the confirmation
4. Notice how the recipient is shown as unknown address

This is a regression compared prod.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/37047?quickstart=1)

## **Changelog**

CHANGELOG entry: Fix showing ENS recipient if it's typed in the send flow

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/36966

## **Manual testing steps**

1. Go to send flow
2. Pick ENS recipient
3. Proceed into confirmation - you should be able to see ENS in the confirmation now

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> On EVM sends, dispatch a domain reverse lookup to populate store for ENS display in confirmation; `lookupDomainName` now accepts an explicit `chainId` and tests updated accordingly.
> 
> - **Hooks (send confirmations)**:
>   - In `useNameValidation`, after a successful name resolution, dispatch `lookupDomainName(to, chainId)` when `useSendType().isEvmSendType` is true to populate store for ENS display.
>   - Add `useDispatch` and `useSendType` usage; update hook dependencies.
> - **State (domains duck)**:
>   - Update `lookupDomainName(domainName, chainId)` to accept optional `chainId`, defaulting to `getCurrentChainId(state)`; compute `chainIdInt` from the final value.
> - **Tests**:
>   - Mock `useDispatch`, `lookupDomainName`, and `useSendType` in `useNameValidation.test.ts`.
>   - Add test asserting `lookupDomainName` is called with `('test.eth', chainId)` on EVM send after resolution.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0478753e000860ff90e06816fc05a5bc4c97cec4. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/ducks/domains.js [hunk 1]
```diff
@@ -187,8 +187,8 @@ export function lookupDomainName(domainName) {
     state = getState();
     log.info(`Resolvers attempting to resolve name: ${trimmedDomainName}`);
     let error;
-    const chainId = getCurrentChainId(state);
-    const chainIdInt = parseInt(chainId, 16);
+    const finalChainId = chainId || getCurrentChainId(state);
+    const chainIdInt = parseInt(finalChainId, 16);
     const resolutions = await fetchResolutions({
       domain: trimmedDomainName,
       chainId: `eip155:${chainIdInt}`,
```
Comment (jpuri) [inline ui/ducks/domains.js:193]: We are avoiding use of redux in redesigned confirmations, we should try to avoid it here also.

**Comment by jpuri** [comment]
If user is using a different snap in name resolution for ens, above fix will not work.

File: ui/ducks/domains.js (hunk 1 above)
Comment (OGPoyraz) [reply ui/ducks/domains.js:193]: This is already in use unfortunately and it's not redesigned confirmation but `Name` component. 

There is no other fix in order to show reverse lookup ENS domain in the `Name` component unless we always want `Name` component to resolve name resolutions by default but that is not the case.

**Comment by OGPoyraz** [comment]
@jpuri default ENS snap is not removable and the matcher we have it on `Name` component will always get the first pick as it's using `find` to match here: https://github.com/MetaMask/metamask-extension/blob/main/ui/hooks/useDisplayName.ts#L212

If you still think that the fix wont work - can you provide a recording with repro steps? Thanks in advance.

**Review by jpuri — DISMISSED** [review]
We need to re-think the approach as it will not resolve name from different resolver snaps.

**Review by pedronfigueiredo — DISMISSED** [review]

**Comment by OGPoyraz** [comment]
Fixed conflict

**Review by pedronfigueiredo — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
