### PR TITLE
fix: swap overestimates gas on EVM networks cp-13.13.0

### LINKED ISSUE #38646: [Bug]: Extension is using an over-estimated gas value to gate submission of a Swap txn
### Describe the bug

The Swaps team has identified an issue where the Mobile and Extension clients are overestimating gas costs in the Swap UI.

On Mobile, this should only require a backend change to resolve, but on Extension, we need to make a small change to the logic that determines which gas estimation is used to deactivate the Swap button/CTA.
[@micaela.estabillo](https://consensys.slack.com/team/U0349D9HQ2E) has prepared a very small PR [here](https://github.com/MetaMask/metamask-extension/pull/38642) (in review), which we will likely need to CP into the 13.13.0 RC tomorrow.

### Expected behavior

Swap CTA/button should be deactivated only when the user's amount of native gas tokens held is less than required to submit the transaction. 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to swap and fetch a quote on Ethereum/an EVM
2. Notice higher than required gas estimation in the Network Fee line in the quote card

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

13.12.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

Sev1

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

- Changes network fee amount in quote card to display `quote.gasFee.effective` instead of totalNetworkFees
- Updates balance validation to check totalNetworkFees instead of `totalMaxNetworkFees`
- Patches gas calculation bug in the bridge-controller

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38642?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: swap experience incorrectly estimates gas required for EVM trades

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38646

## **Manual testing steps**

1. Turn off STX
2. Request a swap quote
3. Compare Network fees to mobile (should be close or equal)
4. Submission should be enabled if user has enough gas funds

### **After vs Before vs Mobile**

|| Screenshots|
|-|-|
|stx OFF, insufficientBal=FALSE, ERC20 | Screenshot 2025-12-09 at 9 42 17 AM|
|stx OFF, insufficientBal=FALSE, NATIVE | Screenshot 2025-12-09 at 9 44 18 AM|
|stx OFF, insufficientBal=TRUE, ERC20 | Screenshot 2025-12-09 at 9 45 31 AM|
|stx OFF, insufficientBal=TRUE, NATIVE |Screenshot 2025-12-09 at 9 44 57 AM |
|stx ON, gasIncluded=TRUE, ERC20 | Screenshot 2025-12-09 at 9 46 34 AM|
|stx ON, gasIncluded=TRUE, NATIVE |Screenshot 2025-12-09 at 9 55 43 AM |

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Displays effective gas fee in quotes, updates insufficient-gas validation to use total fees, and patches bridge-controller gas calculations; updates tests, policies, and deps.
> 
> - **Bridge controller (patched `@metamask/bridge-controller@64.0.0`)**:
>   - `dist/selectors.cjs`: replace `maxPriorityFeePerGasInDecGwei` with `feePerGasInDecGwei` using `suggestedMaxFeePerGas`.
>   - `dist/utils/quote.cjs`:
>     - `calcTotalGasFee`: remove priority fee component; multiply by `feePerGasInDecGwei` only.
>     - `calcEstimatedAndMaxTotalGasFee`: use provided `feePerGasInDecGwei` for effective/estimated/max; drop priority fee args.
>     - `calcTotalEstimatedNetworkFee`: read from `total` instead of `effective`.
> - **UI**:
>   - `ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx`: show network fee from `quote.gasFee.effective` instead of `totalNetworkFee`.
>   - `ui/ducks/bridge/selectors.ts`: `isInsufficientGasForQuote` now compares against `totalNetworkFee` (not `totalMaxNetworkFee`).
> - **Tests**:
>   - Update snapshots and expectations in bridge selector and quote card tests to new fee values.
>   - E2E: comment out strict `usd_quoted_gas` assertions and adjust expected values/providers.
> - **Deps/Build**:
>   - `package.json`/`yarn.lock`: add patch mapping for `@metamask/bridge-controller@64.0.0`; update dependent versions.
>   - LavaMoat policies: adjust package paths/references to `@metamask/bridge-controller` and remove nested entries.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 7d50dbfa687c9da3abc58bb0df0526916bf66966. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx [hunk 1]
```diff
@@ -342,7 +342,7 @@ export const MultichainBridgeQuoteCard = ({
                         currency,
                       )
                     : formatNetworkFee(
-                        activeQuote.totalNetworkFee?.valueInCurrency,
+                        activeQuote.gasFee.effective?.valueInCurrency,
```
Comment (micaelae) [inline ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx:345]: If the quote includes a relayer fee or other fees paid in native asset, this displayed value won't include it

File: .yarn/patches/@metamask-bridge-controller-npm-64.0.0-956740f7c8.patch [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+-        priorityFeePerGasInDecGwei: maxPriorityFeePerGasInDecGwei,
+         nativeToDisplayCurrencyExchangeRate,
+         nativeToUsdExchangeRate,
+     });
+@@ -214,7 +210,7 @@ exports.calcEstimatedAndMaxTotalGasFee = calcEstimatedAndMaxTotalGasFee;
+  * @param relayerFee - The relayer fee paid to bridge providers
+  * @returns The total estimated network fee for the bridge transaction, including the relayer fee paid to bridge providers
+  */
+-const calcTotalEstimatedNetworkFee = ({ effective: gasFeeToDisplay, }, relayerFee) => {
++const calcTotalEstimatedNetworkFee = ({ total: gasFeeToDisplay, }, relayerFee) => {
```
Comment (micaelae) [inline .yarn/patches/@metamask-bridge-controller-npm-64.0.0-956740f7c8.patch:79]: Changes `quote.totalNetworkFee` to use `total` amount instead of `effective`. Clients need to show `gasFee.effective`

File: .yarn/patches/@metamask-bridge-controller-npm-64.0.0-956740f7c8.patch [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+index 3afe13e4fc960c87f98c85d323dd992c5d5ac7f2..0d585efbbd5043ae092a1a8cb497f772ebd4b548 100644
+--- a/dist/selectors.cjs
++++ b/dist/selectors.cjs
+@@ -135,8 +135,8 @@ exports.selectIsAssetExchangeRateInState = selectIsAssetExchangeRateInState;
+  */
+ const selectBridgeFeesPerGas = createStructuredBridgeSelector({
+     estimatedBaseFeeInDecGwei: ({ gasFeeEstimates }) => gasFeeEstimates?.estimatedBaseFee,
+-    maxPriorityFeePerGasInDecGwei: ({ gasFeeEstimates }) => gasFeeEstimates?.[bridge_1.BRIDGE_PREFERRED_GAS_ESTIMATE]
+-        ?.suggestedMaxPriorityFeePerGas,
++    feePerGasInDecGwei: ({ gasFeeEstimates }) => gasFeeEstimates?.[bridge_1.BRIDGE_PREFERRED_GAS_ESTIMATE]
```
Comment (micaelae) [inline .yarn/patches/@metamask-bridge-controller-npm-64.0.0-956740f7c8.patch:11]: Fixes medium fee per gas used for calculations

**Review by ghgoodreau — DISMISSED** [review]

**Review by ghgoodreau — APPROVED** [review]

File: lavamoat/browserify/experimental/policy.json [hunk 4]
```diff
@@ -945,35 +945,6 @@
...
       }
     },
-    "@metamask/transaction-pay-controller>@metamask/bridge-controller": {
-      "globals": {
-        "AbortController": true,
-        "TextDecoder": true,
-        "URLSearchParams": true,
-        "console.error": true,
-        "console.log": true,
-        "console.warn": true
```
Comment (micaelae) [inline lavamoat/browserify/experimental/policy.json:955]: @MetaMask/policy-reviewers these policies were removed after I patched the bridge-controller. There are no breaking changes from bridge-controller v63 to v64 that affect the transaction-pay controller

**Comment by micaelae** [comment]
@metamaskbot update-policies

**Review by GeorgeGkas — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
Policy changes LGTM!

**Review by ghgoodreau — APPROVED** [review]
