### PR TITLE
fix: add loader for onboarding unlock page cp-13.0.0

### LINKED ISSUE #34532: [Bug]: There is no loader when Unlock the wallet
### Describe the bug

When user unlock the wallet, it does not show the loader 

### Expected behavior

Should show the loader when clicking Unlock button, to make more sense

### Screenshots/Recordings

https://github.com/user-attachments/assets/abe73810-839e-45a2-98f4-d8ff5bfc7fe3

### Steps to reproduce

1. Login with social account with existing wallet
2. Unlock the wallet
3. Check if there is a loader showing when entering password

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

Beta

### Browser

Firefox, Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by lionellbriones**
## **Description**
Add loader for onboarding unlock. Use this loader for create-account page also so there will be one loader which can be used for onboarding flow.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34518?quickstart=1)

## **Changelog**

CHANGELOG entry: Added loader for onboarding unlock

## **Related issues**

Fixes:

## **Manual testing steps**

1. Login with social account with existing wallet
2. Unlock the wallet
3. Check if there is a loader showing when entering password

### **Before**
Importing a social account unlock page does not show loader on form submit
https://github.com/user-attachments/assets/f6a88fe0-6fa6-4ee9-8616-4a15a18ab92b

### **After**
**Added a loader**
https://github.com/user-attachments/assets/1cf888af-b87e-42fb-b23c-557e4df202a9
**Use the same loader for create-password for new account**
https://github.com/user-attachments/assets/954c8db3-a752-4752-84fd-9d16d62ef513

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/onboarding-flow/create-password/create-password.js [hunk 1]
```diff
@@ -422,7 +421,6 @@ export default function CreatePassword({
           data-testid="create-password-iframe"
         />
       ) : null}
-      {newAccountCreationInProgress && <LoadingScreen />}
```
Comment (lwin-kyaw) [inline ui/pages/onboarding-flow/create-password/create-password.js:425]: May I know why this is removed?
I thought this was added coz redux loading state isn't working properly here?

Comment (lwin-kyaw) [reply ui/pages/onboarding-flow/create-password/create-password.js:425]: Oh, I see. Loading state is applied from the onboarding-flow page.

May I know why we can't rely on the redux state here?

Comment (lionellbriones) [reply ui/pages/onboarding-flow/create-password/create-password.js:425]: Screenshot 2025-07-23 at 2 07 06 AM
I think it's better to use one loader for onboarding because if i remove `completedOnboarding` or add more logic here. it might introduce issue on other loaders (like two loaders showing). I think that's also the reason why it's commented here to use loader per component

i also removed setting redux-loader on this comment since it will not work on before `completedOnboarding`
https://github.com/MetaMask/metamask-extension/pull/34518/commits/b6a871f4fbedc50f44aecd89ddb666526c5f5d7c

File: ui/store/actions.ts [hunk 2]
```diff
@@ -621,8 +612,6 @@ export function createNewVaultAndGetSeedPhrase(
       } else {
         throw error;
       }
-    } finally {
-      dispatch(hideLoadingIndication());
```
Comment (lwin-kyaw) [inline ui/store/actions.ts:625]: May I know why this is removed?

File: ui/store/actions.ts [hunk 3]
```diff
@@ -609,7 +601,6 @@ export function createNewVaultAndGetSeedPhrase(
   // TODO: Fix in https://github.com/MetaMask/metamask-extension/issues/31879
   // eslint-disable-next-line @typescript-eslint/no-misused-promises
   return async (dispatch: MetaMaskReduxDispatch) => {
-    dispatch(showLoadingIndication());
```
Comment (lwin-kyaw) [inline ui/store/actions.ts:612]: iirc, removing these will affect other operations.

**Comment by LeVinhGithub** [comment]
lgtm

File: ui/store/actions.ts (hunk 3 above)
Comment (lionellbriones) [reply ui/store/actions.ts:612]: this is used to show app loader from `routes.component.js`. for this case it's useless because that loader only shows when onboarding is completed.

File: ui/store/actions.ts (hunk 2 above)
Comment (lionellbriones) [reply ui/store/actions.ts:625]: this is used to hide app loader from routes.component.js. for this case it's useless because that loader only shows when onboarding is completed.

File: ui/store/actions.ts (hunk 3 above)
Comment (lionellbriones) [reply ui/store/actions.ts:612]: this action is only called at one place onboarding. so it won't affect other operation.

**Review by lwin-kyaw — APPROVED** [review]

**Review by chaitanyapotti — APPROVED** [review]
