### PR TITLE
fix: updated assets based on enabled networks in send

### LINKED ISSUE #39121: [Bug]: 'NATIVE' displayed in the Send Flow token list for native tokens of additional networks and custom networks, when the network is not added or deleted
### Describe the bug

The native tokens of additional networks are displayed in the token list in the send flow, when the network is not added to the Network Manager or after it's deleted.

Similar for custom networks: if the custom network is deleted, then 'NATIVE' is displayed in the token list.

When they are displayed as 'NATIVE' in the token list, they cannot be sent, as the continue button is unresponsive. 

### Expected behavior

Tokens from additional networks that are not added or deleted, not to be displayed in the Send flow 

### Screenshots/Recordings

https://github.com/user-attachments/assets/f651d9ae-fc2f-4a2c-9f9e-21fa4cd374bb

Image

Image

### Steps to reproduce

1. Have assets on additional networks 
2. Import SRP
3. Go to Send flow
4. Notice 'NATIVE' in the token list 
5. Go to Network manage 
6. Add an additional network or a custom network
7. Delete it
8. Go to Send flow
9. Notice 'NATIVE' in the token list 
10. Send 'NATIVE' token
11. Notice it does not work

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.14.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR ensures that assets in send flow are filtered based on enabled networks.

The `useSendTokens` and `useSendNfts` hooks were returning all assets from `getAssetsBySelectedAccountGroup` without filtering by which networks are actually enabled in the Network Manager. This meant:
Assets from deleted networks would still appear
Network name/image couldn't be resolved for deleted networks, causing "NATIVE" to be displayed
The continue button didn't work because the send flow couldn't find the network configuration

## **Changelog**

CHANGELOG entry: updated asset list for send flow

## **Related issues**

Fixes: #39121 

## **Manual testing steps**

1. Have assets on additional networks
2. Import SRP
3. Go to Send flow
4. assets should be filtered based on enabled networks

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Enforces network-aware asset selection in the send flow and aligns URL param parsing with the filtered asset set.
> 
> - Filters `useSendAssets` results by `getAllEnabledNetworksForAllNamespaces`; excludes NFTs with undefined `chainId` and, when external services are off, filters non-EVM assets via `isEvmChainId`.
> - Updates `useSendQueryParams` to consume combined `tokens`+`nfts` from `useSendAssets` and select the asset from this filtered list using `assetId`/`address` and optional `tokenId`.
> - Adds/updates tests for network filtering, EVM-only behavior with BFT off, undefined `chainId` handling, and query param asset/amount/recipient/hexData syncing.
> - Memo deps updated to include `enabledNetworks`; removes direct selectors from query params hook.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e0b72a1baf030285cdcf1c2d3a8b30c676977985. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/pages/confirmations/hooks/send/useSendTokens.ts [hunk 1]
```diff
@@ -7,21 +7,29 @@ import {
...
 
   const flatAssets = useMemo(() => Object.values(assets).flat(), [assets]);
 
   const assetsWithBalance = useMemo(() => {
     return flatAssets.filter((asset) => {
+      // Only include assets from networks that are in the Network Manager
+      const isNetworkEnabled = enabledNetworks.includes(asset.chainId);
+      if (!isNetworkEnabled) {
+        return false;
+      }
```
Comment (OGPoyraz) [inline ui/pages/confirmations/hooks/send/useSendTokens.ts]: Similar filtering (when basic functionality is off) is implemented in `useSendAssets`, instead of doing it on both `useSendTokens` and `useSendNfts`, shall we do it on `useSendAssets` to keep this change scoped with send flow?

Comment (ameliejyc) [reply ui/pages/confirmations/hooks/send/useSendTokens.ts]: ➕

File: ui/pages/confirmations/hooks/send/useSendNfts.ts [hunk 2]
```diff
@@ -32,15 +34,23 @@ export const useSendNfts = () => {
...
       selectedAccountGroupWithInternalAccounts as InternalAccount[],
       chainNetworkNAmeAndImageMap,
     );
+
+    // Filter out NFTs from networks that are not in the Network Manager
+    return allNfts.filter(
+      (nft) =>
+        nft.chainId !== undefined &&
+        enabledNetworks.includes(nft.chainId as string),
+    );
```
[the remark this answers is not in the document]
Comment (ameliejyc) [reply ui/pages/confirmations/hooks/send/useSendNfts.ts]: @NidhiKJha let's double check how chainIds are returned for nfts?

File: ui/pages/confirmations/hooks/send/useSendQueryParams.ts [hunk 3]
```diff
@@ -27,9 +24,8 @@ export const useSendQueryParams = () => {
   const navigate = useNavigate();
   const { pathname } = useLocation();
   const [searchParams] = useSearchParams();
-  const nfts = useSendNfts();
-  const assets = useSelector(getAssetsBySelectedAccountGroup);
```
Comment (OGPoyraz) [inline ui/pages/confirmations/hooks/send/useSendQueryParams.ts:31]: Very good catch @NidhiKJha , I totally missed `useSendQueryParams` was using standalone hooks, thanks for the fix

**Review by OGPoyraz — APPROVED** [review]
LGTM

File: ui/pages/confirmations/hooks/send/useSendNfts.ts [hunk 4]
```diff
@@ -32,11 +32,13 @@ export const useSendNfts = () => {
         (accountGroup) => accountGroup.id === selectedAccountGroup,
       )?.accounts;
 
-    return transformNftsToAssets(
+    const allNfts = transformNftsToAssets(
```
Comment (ameliejyc) [inline ui/pages/confirmations/hooks/send/useSendNfts.ts:35]: [nit] could revert this change but no big deal

**Review by ameliejyc — APPROVED** [review]
