### PR TITLE
Fix decrypt message confirmation UI crash

### LINKED ISSUE #10247: Sending eth_decrypt throws "Cannot read property 'name' of undefined" error
**Describe the bug**
After upgrading metamask to version 9, the `eth_decrypt` method returns an error: `Message: Cannot read property 'name' of undefined.
`
**Steps to reproduce (REQUIRED)**

I have built a small [demo application](http://test.dementev.tech/) to demo the error, with the code published here. The implementation code is in the [App.js](https://github.com/nikdementev/issue/blob/main/src/App.js) file. 

1. **Click** to connect account
2. Enter text message.
3. **Click** encrypt message
4. **Click** decrypt message

I expected metamask to decode the message.

error message
image

### encrypt message

` const encryptionPublicKey = await provider.request({
      method: 'eth_getEncryptionPublicKey',
      params: [address]
    })`

`const encryptedMessage = bufferToHex(
      Buffer.from(
        JSON.stringify(
          encrypt(
            encryptionPublicKey,
            { data: message },
            'x25519-xsalsa20-poly1305'
          )
        ),
        'utf8'
      )
    );`

### decrypt message
`await provider.request({
      method: 'eth_decrypt',
      params: [encryptedMessage, address]
    })`

**Browser details (please complete the following information):**
 - OS: Mac BigSure 11.1 (20C69)
 - Browser: Version 87.0.4280.141 (Official Build) (x86_64)
 - MetaMask Version: 9.0.1

On metamask version 8, it worked, but after the update it stopped

### PR DESCRIPTION
**Pull request by Gudahtt**
Fixes: #10247

Explanation:  
The decrypt message confirmation UI will crash if the origin metadata is not present. This PR makes the UI tolerant of that metadata being missing. It was always intended to be optional anyway.

Manual testing steps:  
  - Initiate a decrypt confirmation
  - See that it does not crash

### CODE REVIEW

**Review by rekmarks — APPROVED** [review]
LGTM!

File: ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js [hunk 1]
```diff
@@ -191,15 +192,15 @@ export default class ConfirmDecryptMessage extends Component {
         {this.renderAccountInfo()}
         <div className="request-decrypt-message__visual">
           <section>
-            {origin.icon ? (
+            {originMetadata.icon ? (
```
Comment (rekmarks) [inline ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js:195]: Wait, does this need optional chaining?

**Review by rekmarks — CHANGES_REQUESTED** [review]

File: ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js (hunk 1 above)
Comment (Gudahtt) [reply ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js]: Hah, good catch! This was the mistake I had just mentioned finding - it has been fixed

File: ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js [hunk 2]
```diff
@@ -191,15 +192,15 @@ export default class ConfirmDecryptMessage extends Component {
         {this.renderAccountInfo()}
         <div className="request-decrypt-message__visual">
           <section>
-            {origin.icon ? (
+            {originMetadata?.icon ? (
               <img
                 className="request-decrypt-message__visual-identicon"
-                src={origin.icon}
+                src={originMetadata?.icon}
```
Comment (rekmarks) [inline ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js:198]: nit: useless optional chaining

**Review by rekmarks — APPROVED** [review]

File: ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js (hunk 2 above)
Comment (Gudahtt) [reply ui/app/pages/confirm-decrypt-message/confirm-decrypt-message.component.js:198]: Thanks! This is fixed here: https://github.com/MetaMask/metamask-extension/pull/10256
