### PR TITLE
fix: 31266 qr device sign transaction issue

### LINKED ISSUE #31266: [Bug] QR signTransaction throwing an invalid json format error
Build: 12.15.0
Chrome

1. Install MM
2. Recover from SRP
3. Add hardware wallet (Keystone)
4. Import 3x Keystone accounts
5. Launch Test dApp and connect using Keystone account
6. Deploy ERC721 - (out of memory error displayed on device)
7. Send EIP 1559 txn - (invalid error) 

Expected: Both txns to be successful

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**
This PR will fix #31266 issue. 

The main cause of this issue is still the upgrade of [ethereumjs] upgrade, which change the parameter type to buffer,

This PR will upgrade most of QR relative library to latest to support ethereumjs/tx 5.x.x . 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31366?quickstart=1)

## **Related issues**

Fixes: #31266 

## **Manual testing steps**

1. Install MM
2. Recover from SRP
3. Add hardware wallet (Keystone)
4. Import 3x Keystone accounts
5. Launch Test dApp and connect using Keystone account
6. Send EIP 1559 txn

regarding to the out of memory issue, creating ERC 20 or ERC ERC 1155 may occasionally happen. but if you restart keystone and rescan, the transaction will go throught.

Also need a full regression to QR wallet features due to the impact of fix.
## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by dawnseeker8** [comment]
@metamaskbot update-policies

**Comment by MajorLift** [comment]
@metamaskbot update-policies

**Review by Akaryatrh — APPROVED** [review]

File: ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js [hunk 1]
```diff
@@ -12,18 +12,22 @@ import {
...
 import { Text, Box } from '../../../component-library';
 
+// QR code configuration constants to help with memory optimization
+const QR_FRAGMENT_SIZE = 400;
+const QR_REFRESH_RATE = 250;
+const QR_CODE_SIZE = 225;
 const Player = ({ type, cbor, cancelQRHardwareSignRequest, toRead }) => {
   const t = useI18nContext();
   const urEncoder = useMemo(
-    // For NGRAVE ZERO support please keep to a maximum fragment size of 200
```
Comment (montelaidev) [inline ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js:18]: Is this comment no longer relevant? The fragment size is now 400

Comment (dawnseeker8) [reply ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js:18]: This line will cause Keystone throw out of memory issue, and to increase fragment size is the only way to optimise the memory usage for keystone, that is why this size has been 400, i have tested the difference fragment size and QR_REFRESH_RATE and the fragment size have bigger impact to blocked keystone out of work. and 400 is robust for keystone.any value smaller will force  keystone crash for token and EIP712 deployment.

Comment (montelaidev) [reply ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js:18]: I think we need to test on a Ngrave device as well. This could break the support for Ngrave, i think we need to check the connected hardware and dynamically set the fragment size.

**Review by mikesposito — COMMENTED** [review]
Tested on a Keystone 3 Pro device:

- Paired
- Sign transaction
- Deploy ERC721 token
- Sign typed data

No issues experienced.
I do think we should make sure not to break Ngrave devices

**Review by MajorLift — APPROVED** [review]
Policy changes look safe.
