### PR TITLE
fix: Update max gas limit with value returned from eth_estimateGas api if present

### LINKED ISSUE #27089: [Bug]: Gas - Save Advanced Gas button is disabled without any error
### Describe the bug

Whenever I'm trying to send a transaction, if the value of the `eth_estimateGas` rpc call returns a value outside the gas limit range, I see that if I try to Edit the Gas, clicking Advanced gas fees, the button for Save is always disabled, without displaying any error.

### Expected behavior

The gas form is currently split into 2 pieces, which doesn't seem ideal, as it leads to this kind of problem to arise. We have 3 input values for edit:
- Max base fee
- Priority fee 
- Gas limit input

but there is only validation on the first 2, unless you click explicitly Edit the Gas limit, then there will be validation for the 3rd one, otherwise there isn't. 
This way of constructing the form (into 2 separate pieces) makes that if the Gas limit value is not correct, but you don't explicitly click Edit, you won't be able to change any value as Save button will always be disabled, without any error displayed.

### Screenshots/Recordings

https://github.com/user-attachments/assets/eb6d5feb-4b9e-4350-b4f2-e3eb7883e24f

### Steps to reproduce

1. Import a Tenderly Mainnet work (seed your account with an ERC20 token and ETH)
2. Start a Send ERC20 token
3. Add recipient and value
4. In the last confirmation screen, click Edit gas
5. Try to change gas values--> see Save button is always disabled without any error displayed

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.2.3

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Update max gas limit with value returned from eth_estimateGas api if present

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27089

## **Manual testing steps**
1. Import a Tenderly Mainnet work (seed your account with an ERC20 token and ETH)
2. Start a Send ERC20 token
3. Add recipient and value
4. In the last confirmation screen, click Edit gas
5. Try to change gas values--> see Save button is always disabled without any error displayed

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js [hunk 1]
```diff
@@ -41,24 +47,35 @@ const AdvancedGasFeeGasLimit = () => {
...
+    t,
   ]);
 
+  useEffect(() => {
+    if (originalGasEstimateDec) {
+      setMaxGasLimit(Math.max(MAX_GAS_LIMIT_DEC, originalGasEstimateDec));
+    }
+  }, [minimumGasLimitDec, originalGasEstimateDec, setMaxGasLimit]);
+
+  console.log('**', minimumGasLimitDec - 1, maxGasLimit);
```
Comment (pedronfigueiredo) [inline ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js:71]: remove?

**Review by pedronfigueiredo — DISMISSED** [review]

File: ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js [hunk 2]
```diff
@@ -26,8 +25,15 @@ const AdvancedGasFeeGasLimit = () => {
...
     gasLimit: gasLimitInTransaction,
     minimumGasLimitDec,
-    transaction: { chainId },
+    transaction: { chainId, originalGasEstimate },
   } = useGasFeeContext();
+  const originalGasEstimateDec =
+    originalGasEstimate !== undefined && hexToDecimal(originalGasEstimate);
+  const [maxGasLimit, setMaxGasLimit] = useState(
+    originalGasEstimateDec
+      ? Math.max(MAX_GAS_LIMIT_DEC, originalGasEstimateDec)
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js:34]: If we're dynamically pushing the limit to what the estimate suggests, then do we need an upper bound at all?

Won't the UX still be awkward since the user won't be able to increase it and only reduce it?

**Review by matthewwalsh0 — DISMISSED** [review]

File: ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js (hunk 2 above)
Comment (jpuri) [reply ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js:34]: We update to what estimate suggest only if it is above `MAX_GAS_LIMIT_DEC`. IMHO `MAX_GAS_LIMIT_DEC` is `7920027` and is reasonable for any network.

The [issue](https://github.com/MetaMask/metamask-extension/issues/27089) has been reported in testnet, I donot expect any real use case of this high gas.

File: ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js (hunk 1 above)
Comment (jpuri) [reply ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js:71]: Done 👍

**Review by matthewwalsh0 — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
