### PR TITLE
Updating nft autodetection toggle text, css fix

### LINKED ISSUE #16494: Update copy - NFT autodetection toggle
Screen Shot 2022-11-14 at 5 58 04 PM

Problem: the autodetection toggle doesn't mention anything about the NFT scams phishing risks if you opt into it. 

Solution: Update copy to reflect the risk. 

- Anyone can airdrop NFTs to your account including offensive content, and some of these may get auto-displayed into your wallet if this toggle is turned on.
- The NFT metadata is pulled via the APIs, and this metadata may contain phishing or scam links.

Definition of done:
Replace current copy for Autodetect NFTs to the following:
(insert final copy by @coreyjanssen)

### PR DESCRIPTION
**Pull request by vthomas13**
## Explanation
Adjusting setting description to better reflect the risks of using the "Autodetect NFTs" setting.

Fixes #16494 
See: [Zenhub](https://app.zenhub.com/workspaces/extension-client-team-63529dce65cbb100265a3842/issues/gh/metamask/metamask-extension/16494), [Github](https://github.com/MetaMask/metamask-extension/issues/16494)

### Before

autodetectnft-before

### After

image

## Manual Testing Steps

- Install a MetaMask extension build from this branch 
- Install dependencies with `yarn`
- Run with: `NFTS_V1=1 COLLECTIBLES=1 COLLECTABLES=1 yarn start`
- Go to Settings >  Experimental > Autodetect NFTs
- Ensure the updated text reflects the [statement](https://github.com/MetaMask/metamask-extension/issues/16494#issuecomment-1315702812) from @coreyjanssen 

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by darkwing — DISMISSED** [review]

**Comment by darkwing** [comment]
Looks like this may need a rebase?

**Review by darkwing — DISMISSED** [review]

**Review by NidhiKJha — DISMISSED** [review]

File: ui/pages/settings/security-tab/security-tab.component.js [hunk 1]
```diff
@@ -447,12 +447,13 @@ export default class SecurityTab extends PureComponent {
...
           <div className="settings-page__content-description">
             {t('useCollectibleDetectionDescription')}
-            <br />
-            {t('useCollectibleDetectionDescriptionLine2')}
             <ul className="settings-page__content-unordered-list">
+              <li>{t('useCollectibleDetectionDescriptionLine2')}</li>
               <li>{t('useCollectibleDetectionDescriptionLine3')}</li>
               <li>{t('useCollectibleDetectionDescriptionLine4')}</li>
             </ul>
+            <br />
```
Comment (darkwing) [inline ui/pages/settings/security-tab/security-tab.component.js:455]: Rather than using `<br />`, could we use `<Typography>` around `{t('useCollectibleDetectionDescriptionLine5')}` instead, adding `paddingTop={3}` or something to that effect?

**Review by darkwing — CHANGES_REQUESTED** [review]

File: ui/pages/settings/security-tab/security-tab.component.js (hunk 1 above)
Comment (NidhiKJha) [reply ui/pages/settings/security-tab/security-tab.component.js:455]: `Text` is the new component we have in the `component-library` as a replacement for Typography. I think we should use that

Comment (vthomas13) [reply ui/pages/settings/security-tab/security-tab.component.js]: Ended up using the Text component, thanks for the suggestions

**Review by brad-decker — DISMISSED** [review]

**Review by darkwing — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]

**Comment by adonesky1** [comment]
Do we want the `autodetect` preference to be indented beneath the OpenSea API preference (as we did previously) to indicate the parent/child relationship?

**Comment by vthomas13** [comment]
I think we were talking about it, and the idea makes sense. I'll have to check and see if there's another issue addressing the dependency and logic around that.
