### PR TITLE
fix: (dev-only) ensure NetworkOrderController isn't reset when extension is reloaded

### LINKED ISSUE #34322: [Bug]: [Remove GNS] When an RPC fails and the extension is reloaded MM tries to connect to the failed network, even though Sepolia is enabled
### Describe the bug

When an RPC fails and the extension is reloaded MM tries to connect to the failed network, even though Sepolia is enabled

### Expected behavior

Possibly intended behavior connect to Sepolia?

### Screenshots/Recordings

https://github.com/user-attachments/assets/1ff7c82d-7f70-48db-be4f-fcb7bff7c307

### Steps to reproduce

1. Connect to a network that will fail
2. Don't switch networks
3. Reload the extension
4. Notice enabled network is Sepolia but extension is trying to connect to the failed network

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

12.22.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

This is a development only bug, when the extension was reloaded, it reset the NetworkOrderController back to sepolia.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34320?quickstart=1)

## **Changelog**

CHANGELOG entry: fix: ensure NetworkOrderController is not reset on extension reload.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34322 https://github.com/MetaMask/metamask-extension/issues/34318

## **Manual testing steps**

1. Set enabled networks
2. Refresh & Open extension
3. See if enabled networks have not changed. 

### **After**

https://www.loom.com/share/20540d2dc2ae4b4596c669812f88b7e7?sid=0d4c6941-b54d-4ec2-93d5-9a60a43d200e

https://www.loom.com/share/e27e6ffa34d94e39a7525f88bb645211?sid=0b4cbe4d-2bdc-4ab2-a3e2-d343ff927e89

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -1051,8 +1051,9 @@ export default class MetamaskController extends EventEmitter {
       ],
     });
 
-    let initialNetworkOrderControllerState;
+    let initialNetworkOrderControllerState = initState.NetworkOrderController;
     if (
+      !initialNetworkOrderControllerState &&
```
Comment (Prithpal-Sooriya) [inline app/scripts/metamask-controller.js:1056]: Nit - (long term) when we migrate to use the CORE version of this controller, I would like us to move this logic into the `init` pattern. That way we can test this is isolation.

**Review by salimtb — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
