### PR TITLE
fix: cp-12.15.0 Prevent fullscreen UI from opening every startup

### LINKED ISSUE #30924: [Bug]: The extension starts automatically after restart / reload
### Describe the bug

The extension starts automatically after restart / reload when user is already onboarded.

### Expected behavior

Extension automatically starts only for the onboarding.

### Screenshots/Recordings

https://github.com/user-attachments/assets/e5f8f174-9460-4b3e-a9e1-347cee9d73ce

### Steps to reproduce

1. Install the extension
2. Reload / restart the extension

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.14.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

Prevent tab from opening upon every browser startup.

A [recent PR](https://github.com/MetaMask/metamask-extension/pull/29826) updated the logic for how we determine whether the extension was just installed or not; we used to check state, but now we use the `runtime.onInstalled` event instead to store a flag in session storage indicating whether the extension was just installed.

Unfortunately this PR had a couple of bugs; the condition using this flag was accidentally reversed, and the read from session storage was never successful because of a race condition (the write had not finished yet).

To address both problems, the logic for detecting first install was refactored to use a global variable instead of session storage. Globals can be accessed and written synchronously, preventing any possibility of a race condition.

The solution was complicated by the fact that MV3 builds must add an `onInstalled` listener in the root service worker module, otherwise the listener is never called (we tested this experimentally). It was also unclear whether the listener would always run before or after the `background.js` script loading, and we need to trigger an action in `background.js` on install. But we've accounted for both possibilities in this solution.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/31332?quickstart=1)

## **Related issues**

Fixes: #30924

## **Manual testing steps**

* Create a production-like build (`yarn dist` and `yarn dist:mv2`), or download the builds from the `metamaskbot` comment
* Test that the window opens only on first install, not on later browser restarts.

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Gudahtt** [comment]
I haven't written any tests for this yet. This is a bit trick to test because we can't really unit test these integrations with the extension/service worker API. We won't know that the integration works without a real browser. And we can't test this using a standard E2E test build because the behavior we're testing (opening a new tab on install) is disabled.

We should be able to write an E2E test that uses a production build though, similar to the vault decryption build. Given the urgency of fixing this problem, I'd prefer to use manual testing for now. I'll follow up with the E2E test in a later PR.

File: app/scripts/background.js [hunk 1]
```diff
@@ -1286,24 +1284,18 @@ const addAppInstalledEvent = () => {
...
-
-  if (process.env.IN_TEST) {
-    addAppInstalledEvent();
-  } else if (!isFirstTimeInstall && !process.env.METAMASK_DEBUG) {
+/**
+ * Trigger actions that should happen only upon initial install (e.g. open tab for onboarding).
+ */
+function onInstall() {
+  log.debug('First install detected');
+  addAppInstalledEvent();
```
Comment (Gudahtt) [inline app/scripts/background.js:1292]: Previously this was never called in non-test debug builds (e.g. with `IN_TEST` is false and `METAMASK_DEBUG` is true), so this is technically a change in behavior. But it's not one that matters.

It's OK for this to be called in debug builds, it'll just use the mock Segment instance. In fact it's better this way for ease of debugging.

File: app/scripts/background.js [hunk 2]
```diff
@@ -1286,24 +1284,18 @@ const addAppInstalledEvent = () => {
...
+  if (!process.env.METAMASK_DEBUG) {
     // If storeAlreadyExisted is true then this is a fresh installation
     // and an app installed event should be tracked.
     addAppInstalledEvent();
     platform.openExtensionInBrowser();
   }
-  onNavigateToTab();
```
Comment (Gudahtt) [inline app/scripts/background.js:1306]: I'm not sure why this function was here, it's not really related to the install event. This was being called irrespective if this session was the first after install as well, which is confusing.

I've moved it down to `initBackground`, so it should get called as part of initialization the same way it always was before.

File: app/scripts/app-init.js [hunk 3]
```diff
@@ -184,11 +184,22 @@ const registerInPageContentScript = async () => {
...
 
+// On MV3 builds we must listen for this event in `app-init`, otherwise we found that the listener
+// is never called.
+// For MV2 builds, the listener is added in `background.js` instead.
 chrome.runtime.onInstalled.addListener(function (details) {
   if (details.reason === 'install') {
-    chrome.storage.session.set({ isFirstTimeInstall: true });
-  } else if (details.reason === 'update') {
-    chrome.storage.session.set({ isFirstTimeInstall: false });
+    // This condition is for when `background.js` was loaded before the `onInstalled` listener was
```
Comment (davidmurdoch) [inline app/scripts/app-init.js:192]: since we don't handle `update` case now, is it worth uninstalling these listeners after we detect an `install`?

File: app/scripts/background.js [hunk 4]
```diff
@@ -141,22 +141,26 @@ const PHISHING_WARNING_PAGE_TIMEOUT = ONE_SECOND_IN_MILLISECONDS;
...
+  // This condition is for when the `onInstalled` listener in `app-init` was called before
+  // `background.js` was loaded.
+} else if (globalThis.__metamaskWasJustInstalled) {
+  onInstall();
+  // Delete just to clean up global namespace
+  delete globalThis.__metamaskWasJustInstalled;
+  // This condition is for when `background.js` was loaded before the `onInstalled` listener was
+  // called.
+} else {
+  globalThis.__metamaskTriggerOnInstall = () => onInstall();
```
Comment (davidmurdoch) [inline app/scripts/background.js:163]: neat!

File: app/scripts/app-init.js [hunk 5]
```diff
@@ -184,11 +184,22 @@ const registerInPageContentScript = async () => {
...
+    // called.
+    if (globalThis.__metamaskTriggerOnInstall) {
```
Comment (davidmurdoch) [inline app/scripts/app-init.js:194]: do you think adding types to our `types/global.d.ts` (or even a new `types/*.d.ts` file) is worthwhile for these global vars?

**Review by davidmurdoch — COMMENTED** [review]
Looks great! Solution is a maybe bit non-idiomatic, but still much easier to reason about than the async storage complexity.

Left only some nits/questions, nothing that must be changed.

I'll give it a few runs locally tomorrow before give it the ✅

**Comment by Gudahtt** [comment]
Not quite sure why the "App Installed Event" E2E tests are failing.

File: app/scripts/app-init.js (hunk 3 above)
Comment (Gudahtt) [reply app/scripts/app-init.js:192]: Good idea

File: app/scripts/app-init.js (hunk 5 above)
Comment (Gudahtt) [reply app/scripts/app-init.js:194]: Couldn't hurt!

File: app/scripts/background.js (hunk 1 above)
Comment (davidmurdoch) [reply app/scripts/background.js:1292]: I think this is now being called twice in some cases (here, and two lines down)

Comment (Gudahtt) [reply app/scripts/background.js:1292]: Good catch, removed here: https://github.com/MetaMask/metamask-extension/pull/31332/commits/2f3b1e395f3789d2ad2182a7abd168f2604e0a61

File: app/scripts/app-init.js (hunk 3 above)
Comment (Gudahtt) [reply app/scripts/app-init.js:199]: Done here: 01c3b34430

File: app/scripts/app-init.js (hunk 5 above)
Comment (Gudahtt) [reply app/scripts/app-init.js:201]: Done here: https://github.com/MetaMask/metamask-extension/pull/31332/commits/8d0dbcd3a2df3815837fe3c6cc218f89de6e45e9

File: app/scripts/app-init.js [hunk 6]
```diff
@@ -184,12 +184,33 @@ const registerInPageContentScript = async () => {
...
-chrome.runtime.onInstalled.addListener(function (details) {
+/**
+ * `onInstalled` event handler.
+ *
+ * On MV3 builds we must listen for this event in `app-init`, otherwise we found that the listener
+ * is never called.
+ * For MV2 builds, the listener is added in `background.js` instead.
+ *
+ * @param {object} details - Event details.
+ * @param {string} details.reason - The reason that this event was dispatched.
```
Comment (davidmurdoch) [inline app/scripts/app-init.js:195]: very non blocking nit: we have types for (most of) the extension apis. `chrome.runtime.InstalledDetails` should do the trick in this case.

**Review by davidmurdoch — APPROVED** [review]
On Firefox I was automatically greeted with the "Welcome back" login screen, not the "Let's get started" screen, in _fullscreen_ after installing the extension as a "Temporary Add-on".

My hunch is that this is because I had previously installed it this way, so this was a new install, but firefox persisted the database from the last time I installed MM as a Temporary add-on.

If I manually remove MM (instead of waiting for it to expire and get automatically removed by FF) and then install it again it opens in full screen with the "Let's get started" screen, as expected.

I think this behavior is fine, it is a change from the original way we did this (check if we had written to storage before), so I just wanted to mention it.

**Review by HowardBraham — APPROVED** [review]
