### PR TITLE
Fix gas estimation when sending to contracts.

### LINKED ISSUE #5894: Metamask incorrectly estimates gas if destination address is entered first, but estimates correctly if amount is entered before address.
**Describe the bug**
When sending to a contract with a fallback payable function, Metamask incorrectly estimates gas if destination address is entered first, but estimates correctly if amount is entered before address.

**To Reproduce**
1. Open metamask on mainnet
2. Click on Send
3. Paste this in as the recipient address: 0x77B6fB0cC1022bD7838023211F4dcDdC385856F5
4. Enter an amount (any amount should work but I use 0.01)
5. **Observe** that gas limit is now ridiculously high (7600027)
6. Now close metamask and open it again
7. Click on Send
8. Enter an amount (any amount should work but I use 0.01)
9. Paste this in as the recipient address: 0x77B6fB0cC1022bD7838023211F4dcDdC385856F5
10. **Observe** that gas limit is now correct (88516)

**Expected behavior**
Metamask should set the gas limit correctly regardless of whether the user enters the address or amount first.

**Browser details (please complete the following information):**
 - OS: OS X 10.13.6
 - Browser: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
 - MetaMask Version: 5.1.0

**Additional context**
Here's the contract source for reference https://github.com/deconet/DeconetPaymentsSplitting/blob/master/contracts/DeconetPaymentsSplitting.sol

### PR DESCRIPTION
**Pull request by danjm**
fixes #5894

When estimating gas limit for a send to a contract and with a 0 value, the methods we rely on for estimation default to provided gas limits. To get an estimate that is based on the contract itself, the estimation method needs to be passed a non-zero value.

### CODE REVIEW

File: ui/app/components/send/send-content/send-gas-row/send-gas-row.container.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ function mapStateToProps (state) {
   const balance = getCurrentEthBalance(state)
 
   const insufficientBalance = !isBalanceSufficient({
-    amount: getSendAmount(state),
+    amount: getSelectedToken(state) ? '0x0' : getSendAmount(state),
```
Comment (whymarrh) [inline ui/app/components/send/send-content/send-gas-row/send-gas-row.container.js]: Should we be casting the result to a boolean to be more explicit?

```suggestion
    amount: Boolean(getSelectedToken(state)) ? '0x0' : getSendAmount(state),
```

**Review by whymarrh — CHANGES_REQUESTED** [review]
1 quick suggestion

**Review by whymarrh — APPROVED** [review]
