### PR TITLE
fix: Support dynamic native token name on gas component

### LINKED ISSUE #28001: [Bug]: Incorrect token being shown on the gas component on redesigned confirmations
### Describe the bug

We're showing ETH as the gas token when doing a transaction on another network (e.g. Polygon or BNB) on the redesigned confirmations. Legacy confirmations show the correct token within the gas component for the same transaction. 

This is happening for both contract interactions and contract deployments on prod. 

### Expected behavior

Show the correct token for the respective network.

### Screenshots/Recordings

With "improved transaction requests" toggle **enabled**:
Screenshot 2024-10-21 at 18 11 53

With "improved transaction requests toggle **disabled**:
Screenshot 2024-10-21 at 18 19 15

### Steps to reproduce
1. Go to test dapp on Polygon or BNB
2. Trigger "Malicious contract interaction"
3. Notice the network as Polygon or BNB but the gas component showing ETH instead POL or BNB 

or

1. Go to https://app.layer3.xyz/quests?modal=lootbox (you might need to create an account on layer3 first)
4. Click continue
5. Notice the network as Polygon but the gas component showing ETH instead POL 

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

12.4.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Uses the multinetwork ticker.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28048?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28001

## **Manual testing steps**

See original ticket linked above.

### **After**

Screenshot 2024-10-23 at 16 16 19

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

File: ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.ts [hunk 1]
```diff
@@ -32,14 +32,18 @@ export function useFeeCalculations(transactionMeta: TransactionMeta) {
   const conversionRate = useSelector(getConversionRate);
   const fiatFormatter = useFiatFormatter();
 
+  const multichainNetwork = useSelector(getMultichainNetwork);
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.ts:35]: This is okay in the context of a fix, but long-term this is ultimately still using `getProviderConfig` where as we'll want to pass in our transaction chain ID somehow.
