### PR TITLE
fix: cp-12.18.0 duplicate accounts on srp select

### LINKED ISSUE #32984: [Bug]: Duplicate ETH Accounts in the SRP Picker
### Describe the bug

ETH Accounts are being doubled in the SRP Picker. See screenshot

Image

### Expected behavior

We shouldn't be repeating ETH accounts in the SRP picker. 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Open fresh MM
2. Import second SRP
3. Notice that ETH Accounts are doubled

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.18

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by PatrykLucka**
## **Description**

This PR fixes duplicate account returned by some selectors. `entropySource` has been added to hd keyring accounts, but several selectors and tests have not beed updated.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/32984

## **Manual testing steps**

1. Open fresh MM
2. Import second SRP
3. Notice that ETH Accounts are doubled

### **Before**
Screenshot 2025-05-16 at 11 40 13

### **After**
Screenshot 2025-05-16 at 11 42 06

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/hooks/multi-srp/useHdKeyringsWithSnapAccounts.ts [hunk 1]
```diff
@@ -18,11 +18,13 @@ export const useHdKeyringsWithSnapAccounts = () => {
     getMetaMaskHdKeyrings,
   );
   const internalAccounts = useSelector(getInternalAccounts);
+
   return useMemo(() => {
     return hdKeyrings.map((keyring) => {
       const firstPartySnapAccounts = internalAccounts
         .filter(
           (account: InternalAccount) =>
+            account.metadata.snap?.id &&
```
Comment (ccharly) [inline ui/hooks/multi-srp/useHdKeyringsWithSnapAccounts.ts:27]: IMO, we should also check for `isSnapPreinstalled` here: https://github.com/MetaMask/metamask-extension/blob/6f29663a2feba884b477014d30c453eaafeeed16/shared/lib/snaps/snaps.ts#L19-L21

Given that we're looking for 1st party Snaps, they have to be preinstalled.

File: ui/selectors/multi-srp/multi-srp.ts [hunk 2]
```diff
@@ -109,6 +109,7 @@ export const getSnapAccountsByKeyringId = createDeepEqualSelector(
   (accounts, keyringId) => {
     return accounts.filter(
       (account: InternalAccount) =>
+        account.metadata.snap?.id &&
```
Comment (ccharly) [inline ui/selectors/multi-srp/multi-srp.ts:112]: Same here probably? Also, couldn't we use this selector in the `usHdKeyringsWithSnapAccounts` hook? That would avoid this kind of duplicated logic IMO.

File: ui/selectors/multi-srp/multi-srp.ts [hunk 3]
```diff
@@ -109,6 +110,7 @@ export const getSnapAccountsByKeyringId = createDeepEqualSelector(
   (accounts, keyringId) => {
     return accounts.filter(
       (account: InternalAccount) =>
+        isSnapPreinstalled(account.metadata.snap?.id as SnapId) &&
```
Comment (ccharly) [inline ui/selectors/multi-srp/multi-srp.ts:113]:
```suggestion
        account.metadata.snap &&
        isSnapPreinstalled(account.metadata.snap.id as SnapId) &&
```

File: ui/hooks/multi-srp/useHdKeyringsWithSnapAccounts.test.ts [hunk 4]
```diff
@@ -67,6 +77,9 @@ describe('useHdKeyringsWithSnapAccounts', () => {
       mockFirstPartySnapAccount,
       mockSnapAccount2,
     ]);
+    mockIsSnapPreinstalled.mockImplementation(
+      (prop: string) => Boolean(prop) !== undefined,
```
Comment (ccharly) [inline ui/hooks/multi-srp/useHdKeyringsWithSnapAccounts.test.ts:81]: IMO, we could just go with `true` for now, we don't need the `!== undefined` anymore if we go with my other suggestion.

```suggestion
      () => true,
```

**Review by shane-t — DISMISSED** [review]

**Review by ccharly — APPROVED** [review]
LGTM + Tested, no duplicates 🎉

Screenshot 2025-05-16 at 14 40 03

**Review by shane-t — APPROVED** [review]

**Review by zone-live — APPROVED** [review]

**Review by aganglada — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
LGTM
