### PR TITLE
fix: fix network name displayed on confirmation page header

### LINKED ISSUE #23686: [Bug]: Confirmations Re-design - Network Name not correct in signature headers
### Describe the bug

Whenever I am using a custom network, I don't see the correct name displayed in the network header. There are 2 cases:

- Using an RPC with a chainId that was not previously in the wallet: here we don't display any network name and a question mark

Screenshot from 2024-03-25 10-29-42

- Using an RPC with a chanId already existing in the wallet: here I will display the network name of the default wallet network

Screenshot from 2024-03-25 10-27-49

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Build the re-design
2. Add a custom RPC (do the 2 variants: with a network which has a chain id already in the wallet, and with a network with a new chain id)
3. Trigger a typed signature
4. See network

### Error messages or log output

_No response_

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
fix network name displayed on confirmation page header. network name are displayed wrong in 2 cases:

1. custom network
2. custom network with chain_id same as already defined network

## **Related issues**

Fixes: MetaMask/metamask-extension#23686

## **Manual testing steps**

1. Enable redesign locally
2. Add custom network
3. Submit a personal sign on custom network and check header

## **Screenshots/Recordings**
Screenshot 2024-03-25 at 9 42 50 PM
Screenshot 2024-03-25 at 9 42 32 PM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts [hunk 1]
```diff
@@ -29,11 +29,16 @@ function useConfirmationNetworkInfo() {
     const currentChainId =
       currentConfirmation?.chainId ?? providerConfig.chainId;
     confirmationNetwork = allNetworks.find(
-      ({ chainId }) => chainId === currentChainId,
+      ({ id, chainId }) =>
+        chainId === currentChainId &&
+        (providerConfig.type === 'rpc'
```
Comment (digiwand) [inline ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts:34]: [nit] 
```suggestion
        (providerConfig.type === NETWORK_TYPES.RPC
```

File: ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts [hunk 2]
```diff
@@ -29,11 +29,16 @@ function useConfirmationNetworkInfo() {
...
+          ? id === providerConfig.id
+          : id === providerConfig.type),
     );
+
     if (confirmationNetwork) {
-      const { nickname, providerType, type } = confirmationNetwork;
-      if (providerType === NETWORK_TYPES.RPC || type === NETWORK_TYPES.RPC) {
+      const { nickname } = confirmationNetwork;
+      if (providerConfig.type === NETWORK_TYPES.RPC) {
         networkDisplayName = nickname ?? t('privateNetwork');
```
Comment (digiwand) [inline ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts:42]: [double-checking] if there wasn't confirmationNetwork found and if `providerConfig.type === NETWORK_TYPES.RPC)`, would we want to set networkDisplayName to `t('privateNetwork')`

Comment (jpuri) [reply ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts:42]: Yep, `providerConfig.type === NETWORK_TYPES.RPC)` is true for custom networks.

**Review by pedronfigueiredo — APPROVED** [review]

**Review by segun — APPROVED** [review]
