### PR TITLE
Fix AddAccount not updating UI

### LINKED ISSUE #961: Dev: AddAccount not updating UI

### PR DESCRIPTION
**Pull request by danfinlay**
Fixed by finally making a function generator for a pattern we use frequently, communicating to the background process.

Fixes #961

Also applies this new pattern to other methods that followed it.

### CODE REVIEW

**Review by 2-am-zzz — APPROVED** [review]
:+1:

File: ui/app/actions.js [hunk 1]
```diff
@@ -857,3 +833,24 @@ function shapeShiftRequest (query, options, cb) {
...
+// We hide loading indication.
+// If it errored, we show a warning.
+// If it didn't, we update the state.
+function callBackgroundThenUpdate (method, ...args) {
+  return (dispatch) => {
+    dispatch(actions.showLoadingIndication())
+    method.call(background, ...args, (err, newState) => {
+      dispatch(actions.hideLoadingIndication())
+      if (err) {
+        return dispatch(actions.displayWarning(err.message))
```
Comment (Zanibas) [inline ui/app/actions.js]: There may be a problem here with using displayWarning instead of this.showWarning?

Comment (flyswatter) [inline ui/app/actions.js]: Good catch, a number of methods were using `showWarning`, which wasn't a real function!
