### PR TITLE
fix: Properly handle registry update promise

### LINKED ISSUE #38431: Error: The Snaps platform requires basic functionality to be used. Enable basic functionality in the settings to use the Snaps platform.
Sentry Issue: [METAMASK-Y5DJ](https://metamask.sentry.io/issues/7067652425/?referrer=github_integration)

```
Error: The Snaps platform requires basic functionality to be used. Enable basic functionality in the settings to use the Snaps platform.
  at MetamaskController.postOnboardingInitialization (app/scripts/metamask-controller.js:1408:29)
  at new MetamaskController (app/scripts/metamask-controller.js:1308:12)
  at setupController (app/scripts/background.js:1126:16)
  at initialize (app/scripts/background.js:731:3)
  at initBackground (app/scripts/background.js:1970:3)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by FrederikBolding**
## **Description**

Use `.catch` instead of a try-catch block since `updateRegistry` returns a promise.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/38480?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/38431

---

> [!NOTE]
> Use a promise catch for `snapController.updateRegistry()` and log only unexpected errors during post-onboarding snap registry updates.
> 
> - **Controller**
>   - Post-onboarding: replace try/catch with `.catch(...)` for `snapController.updateRegistry()`; ignore the expected "requires basic functionality" error and log other errors.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1c8cd40b64a8b69679662a4f22742398d25ae235. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by GuillaumeRx — DISMISSED** [review]

File: app/scripts/metamask-controller.js [hunk 1]
```diff
@@ -1445,11 +1445,9 @@ export default class MetamaskController extends EventEmitter {
         (snap) => !snap.preinstalled,
       )
     ) {
-      try {
-        this.snapController.updateRegistry();
-      } catch {
+      this.snapController.updateRegistry().catch(() => {
         // Ignore
```
Comment (Gudahtt) [inline app/scripts/metamask-controller.js]: Should we at least log the error here, so that we know the registry did not update?

What types of errors are expected here?

Comment (FrederikBolding) [reply app/scripts/metamask-controller.js]: It only throws if the registry could not be updated due to user settings, e.g. if basic functionality is off. In that case we don't really care about the thrown error.

Comment (Gudahtt) [reply app/scripts/metamask-controller.js]: It looks like it could fail for other reasons as well 🤔 There are lots of `await`s in the function.

Suppressing altogether seems sub-optimal to me, as it would hide any unexpected errors. Agreed that the basic functionalities error isn't useful to throw (or even log) though.

Maybe we could check whether the error is the basic functionalities error (or an assertion error, if you'd prefer avoiding matching on the message), and re-throw or log otherwise?

Comment (FrederikBolding) [reply app/scripts/metamask-controller.js]: There are lots of async functions for sure, but none of them should be possible to throw. They should all be handling their own errors, some of them also log failures on their own

Comment (Gudahtt) [reply app/scripts/metamask-controller.js]: "Should be" is one thing, but if they aren't (i.e. if something unexpected happens), this approach will make us miserable. I've done this to myself enough times that I don't want to do it again 😅

Comment (FrederikBolding) [reply app/scripts/metamask-controller.js]: Well none of them _can_ throw today, at least from my brief look to validate my assumption. Are you worried that it may change in the future?

Comment (Gudahtt) [reply app/scripts/metamask-controller.js]: Yeah exactly. And also I'm not totally convinced they can't throw today, in the right circumstances (e.g. if somehow some variable with an unexpected type sneaks in, past an innocent-looking type cast)

Comment (FrederikBolding) [reply app/scripts/metamask-controller.js]: Fixed: https://github.com/MetaMask/metamask-extension/pull/38480/commits/1c8cd40b64a8b69679662a4f22742398d25ae235

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Review by GuillaumeRx — APPROVED** [review]
