### PR TITLE
fix: 25457 firefox extension not work for trezor connect

### LINKED ISSUE #25457: [Bug]: Cannot connect Trezor on Firefox on version 11.16.10-11.6.7 or earlier. (After 11.16,0)
### Describe the bug

"continue" button is inactive

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/home.html#new-account/connect
here

### Error messages or log output

```shell
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
SES_UNHANDLED_REJECTION: (TypeError#1) sentry-install.js:1:693
TypeError#1: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (TypeError#2) sentry-install.js:1:693
TypeError#2: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (TypeError#3) sentry-install.js:1:693
TypeError#3: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (TypeError#4) sentry-install.js:1:693
TypeError#4: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (TypeError#5) sentry-install.js:1:693
TypeError#5: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (TypeError#6) sentry-install.js:1:693
TypeError#6: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (TypeError#7) sentry-install.js:1:693
TypeError#7: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
Uncaught (in promise) TypeError: window.navigator.usb is undefined
ui-7.js:1:274106
SES_UNHANDLED_REJECTION: (TypeError#8) sentry-install.js:1:693
TypeError#8: window.navigator.usb is undefined sentry-install.js:1:693
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
m@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1548
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
_@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1691
setupProxy/n/e[t]@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/scripts/sentry-install.js:1:693
k/<@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1837
k@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:1923
j@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2372
P@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2184
C@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:2533
Tr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29575
le@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:115153
jr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30191
Rr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:31148
Cr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:30436
r.unstable_runWithPriority@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:3:15370
Qi@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:46222
se@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:114920
Pr@moz-extension://15f7aa63-94ca-44f4-adfe-add6a14ae297/common-5.js:1:29859
sentry-install.js:1:693
```

### Version

11.16.10

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Hardware wallet

Trezor

### Additional context

_No response_

### Severity

critical, cannot access funds.

### PR DESCRIPTION
**Pull request by dawnseeker8**
#25457 Because firefox doesn't support usb api, which cause the `window.navigator.usb` is undefined in firefox, which break the trezor connection.

This PR will check whether window.navigator.usb is undefined or not. if yes, then select-hardware will fall back to use trezor bridge to connect.

## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25487?quickstart=1)

## **Related issues**

Fixes: #25457 

## **Manual testing steps**

1. Open `metamask` in firefox
2. select `account drop down` in home page and then select `Add Account and hardware wallet`
3. select `trezor` in hardware select screen.
4. approve at trezor screen
5. you should be able to select `accounts` from trezor.

### **After**

https://github.com/MetaMask/metamask-extension/assets/7315988/980c6c78-2765-4f97-8781-8250eeec1f9b

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by danjm — DISMISSED** [review]

**Review by itsyoboieltr — DISMISSED** [review]

File: ui/pages/create-account/connect-hardware/select-hardware.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ export default class SelectHardware extends Component {
 
   connect = async () => {
     if (this.state.selectedDevice) {
-      if (this.state.selectedDevice === 'trezor') {
+      if (this.state.selectedDevice === 'trezor' && window.navigator.usb) {
```
Comment (davidmurdoch) [inline ui/pages/create-account/connect-hardware/select-hardware.js:59]: can you throw in a comment about why this check is necessary? something about firefox support and maybe even link to https://mozilla.github.io/standards-positions/#webusb ?

Comment (danjm) [reply ui/pages/create-account/connect-hardware/select-hardware.js:68]: I have added a comment in 93cfd69fda

**Review by danjm — APPROVED** [review]

**Review by davidmurdoch — APPROVED** [review]
🚀
