### PR TITLE
fix: cp-13.0.0 improve perf for network checkbox

### LINKED ISSUE #34490: [Bug]: Performance degradation: certain flows / actions taking several seconds to complete
### Describe the bug

Performance degradation has been observed, with certain flows or actions taking several seconds to complete.
For me, the most noticeable slowdown occurs when using the Network Manager to enable or disable networks.

Additionally, the Send flow and switching accounts can also feel slow enough to be noticeable. Initiating a Send transaction can take 2-3 seconds, and opening the Accounts list on the home screen or within the Send flow also feels noticeably slow.

### Expected behavior

- 

### Screenshots/Recordings

https://github.com/user-attachments/assets/661e580a-bbb5-4d2c-bd1f-fda00816e7d2

https://github.com/user-attachments/assets/e0e3d021-cb82-4e90-8839-bf638bc921fe

### Steps to reproduce

1. Start Send transaction
2. Open Network manager 
3. Enable / disable networks

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34450?quickstart=1)

## **Changelog**

CHANGELOG entry: defer network manager selection logic to prevent blocking toggles.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34490

## **Manual testing steps**

1. Go to network manager
2. Enable/disable network
3. check latency

### **Before**

https://github.com/user-attachments/assets/35e59cea-447f-47ac-a3e9-260d0324a569

### **After**

https://github.com/user-attachments/assets/e68b5904-6dba-4121-ba95-d52c185a50f2

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts [hunk 1]
```diff
@@ -91,6 +87,19 @@ export const useNetworkChangeHandlers = () => {
...
+  useEffect(() => {
+    // Fire and forget async operations for better performance
+    // setTimeout with 0 delay pushes these operations to the next event loop tick,
+    // preventing them from blocking the current execution stack and improving UI responsiveness.
+    // This technique is called "yielding to the event loop" - it allows higher priority
+    // tasks (like UI updates) to execute first before these background operations run.
+    setTimeout(() => {
+      dispatch(updateCustomNonce(''));
+      dispatch(setNextNonce(''));
+      dispatch(detectNfts(allChainIds));
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts:99]: v nice!

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts (hunk 1 above)
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts:99]: Discussion - do we _really_ need to detect NFTs on every network select?
Future perf - we can remove this since we have a refresh button, and when you navigate to the nft tab we fetch.

**Comment by Unik0rnMaggie** [comment]
- Performance improved when selecting and deselecting networks in the Portfolio Network Manager; using device Apple M4 Pro, 24 GB RAM
Should test also on device with 16GB RAM or less.

- Console errors when selecting and deselecting networks, not present in the current RC build for 13.0.0

https://github.com/user-attachments/assets/2488815f-00b7-41be-89db-14d787f37cff

**Review by Prithpal-Sooriya — APPROVED** [review]

**Comment by Prithpal-Sooriya** [comment]
Thanks @Unik0rnMaggie these errors seem to be unrelated, but will do a fast follow through to resolve em in a separate PR.

**Review by NidhiKJha — APPROVED** [review]
