### PR TITLE
fix: cp-12.12.0 bring back exception if invalid address passed in eth_accounts

### LINKED ISSUE #30202: [Bug]: Permissions - Wallet breaks with error `Message: Value must be a hexadecimal string, starting with "0x".`
### Describe the bug

Whenever I pass a non-address (ie `seaona.eth`) into the `restrictReturnedAccounts` value,, the wallet breaks with the error `Message: Value must be a hexadecimal string, starting with "0x".`

### Expected behavior

Handle this error like we do in prod? (returning an error and not opening MM dialog)

### Screenshots/Recordings

12.12.0

Image

Current prod

Image

### Steps to reproduce

1. Unlock MM
2. Open test dapp console
3. Paste the following command

```
await window.ethereum.request({
  method: 'wallet_requestPermissions',
  params: [
    {
      'eth_accounts': {
        'caveats': [
        	{
        		'type': 'restrictReturnedAccounts',
        		'value': [ 'seaona.eth']
        	}
        ]
      },
      'endowment:permitted-chains': {
      	'caveats': [
      		{
      			'type': 'restrictNetworkSwitching',
      			'value': ['0x1']
      		}
      	]
    }
    }
  ]
});
```

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.12.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ffmcgee725**
This commit fixes the following [issue](https://github.com/MetaMask/metamask-extension/issues/30202) which is currently a release blocker for [v12.12.0](https://github.com/MetaMask/metamask-extension/pull/30020)

The eth accounts and permitted chains caveat validation in this PR was originally removed as part of the CAIP-25 Permission Migration PR [here](https://github.com/MetaMask/metamask-extension/pull/27847/files#diff-2089a51d7dedef741fa281f38739b24373ef16a7c04901ae3fee4329e3b32ec6L251-L317), but is being restored in order to fix a regression in the API behavior. Originally, making a wallet_requestPermissions request with invalid caveat values for eth_accounts or endowment:permitted-chains would result in an immediate error returned back to the dapp specifying which value was invalid, i.e. not found in the wallet. This PR restores that behavior.
Additionally, the changes in this PR are temporary and will be removed as part of a [follow up refactor that cleans up the CAIP-25 approval/request permission flow](https://github.com/MetaMask/metamask-extension/pull/30042).

## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/30213?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

Unlock MM
Open test dapp console
Paste the following command
See error

### **After**

https://github.com/user-attachments/assets/9344d6de-2602-4a66-beff-2692f9b68241

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/scripts/controllers/permissions/specifications.js [hunk 1]
```diff
@@ -192,3 +192,72 @@ export const unrestrictedMethods = Object.freeze([
...
+
+/**
+ * Validates the accounts associated with a caveat. In essence, ensures that
+ * the accounts value is an array of non-empty strings, and that each string
+ * corresponds to a PreferencesController identity.
+ *
+ * @param {string[]} accounts - The accounts associated with the caveat.
+ * @param {() => Record<string, import('@metamask/keyring-internal-api').InternalAccount>} getInternalAccounts -
+ * Gets all AccountsController InternalAccounts.
+ * TODO: Remove this function once permission refactor/factory differ work is merged into main
```
Comment (jiexi) [inline app/scripts/controllers/permissions/specifications.js:204]:
```suggestion
 * TODO: Remove this function once the CAIP-25 permission refactor/factory differ work is merged into main
```

File: app/scripts/controllers/permissions/specifications.js [hunk 2]
```diff
@@ -192,3 +192,72 @@ export const unrestrictedMethods = Object.freeze([
...
+}
+
+/**
+ * Validates the networks associated with a caveat. Ensures that
+ * the networks value is an array of valid chain IDs.
+ *
+ * @param {string[]} chainIdsForCaveat - The list of chain IDs to validate.
+ * @param {function(string): string} findNetworkClientIdByChainId - Function to find network client ID by chain ID.
+ * @throws {Error} If the chainIdsForCaveat is not a non-empty array of valid chain IDs.
+ * TODO: Remove this function once permission refactor/factory differ work is merged into main
```
Comment (jiexi) [inline app/scripts/controllers/permissions/specifications.js:241]:
```suggestion
 * TODO: Remove this function once the CAIP-25 permission refactor/factory differ work is merged into main
```

File: app/scripts/metamask-controller.js [hunk 3]
```diff
@@ -5292,6 +5294,18 @@ export default class MetamaskController extends EventEmitter {
         (caveat) => caveat.type === CaveatTypes.restrictReturnedAccounts,
       )?.value ?? [];
 
+    validateCaveatAccounts(
+      requestedAccounts,
+      this.accountsController.listAccounts.bind(this.accountsController),
+    );
+    console.log('i passed here');
```
Comment (jiexi) [inline app/scripts/metamask-controller.js:5301]:
```suggestion
```

File: app/scripts/metamask-controller.test.js [hunk 4]
```diff
@@ -960,668 +968,753 @@ describe('MetaMaskController', () => {
...
-            caveats: [
-              {
-                type: 'restrictNetworkSwitching',
-                value: ['0x1', '0x5'],
-              },
-            ],
-          },
-        });
+          afterEach(() => {
+            PermissionSpecifications.validateCaveatAccounts.mockClear();
```
Comment (jiexi) [inline app/scripts/metamask-controller.test.js:1653]: i think all mocks are actually reset automatically in every test now. Do you mind removing this afterEach and seeing if these still pass?

File: app/scripts/metamask-controller.test.js [hunk 5]
```diff
@@ -960,668 +968,753 @@ describe('MetaMaskController', () => {
...
-                      optionalScopes: {},
-                      isMultichainOrigin: false,
-                    },
-                  },
-                ],
+        describe('unrecognized chain id requested', () => {
+          beforeEach(() => {
+            PermissionSpecifications.validateCaveatAccounts.mockImplementation(
+              () => ({}),
+            );
```
Comment (jiexi) [inline app/scripts/metamask-controller.test.js:1678]: do we need to specify anything at all for validateCaveatAccounts? The default mock already does not throw

File: app/scripts/metamask-controller.test.js [hunk 6]
```diff
@@ -960,668 +968,753 @@ describe('MetaMaskController', () => {
...
 
-        jest
-          .spyOn(metamaskController.permissionController, 'grantPermissions')
-          .mockReturnValue({
-            [Caip25EndowmentPermissionName]: {
-              foo: 'bar',
-            },
+          afterEach(() => {
+            PermissionSpecifications.validateCaveatAccounts.mockClear();
+            PermissionSpecifications.validateCaveatNetworks.mockClear();
```
Comment (jiexi) [inline app/scripts/metamask-controller.test.js:1690]: same Q re mockClear

File: app/scripts/metamask-controller.js (hunk 3 above)
Comment (ffmcgee725) [reply app/scripts/metamask-controller.js:5301]: thank god this wasn't one of those ones 😆

File: app/scripts/metamask-controller.test.js (hunk 5 above)
Comment (ffmcgee725) [reply app/scripts/metamask-controller.test.js:1678]: in this case we do, otherwise the mock from the previous block persists and we throw the accounts error instead of the chains one

File: app/scripts/metamask-controller.test.js (hunk 6 above)
Comment (ffmcgee725) [reply app/scripts/metamask-controller.test.js]: resolved in https://github.com/MetaMask/metamask-extension/pull/30213/commits/c9df79b148c085ba949bcf7974ba8f7216595c3a

File: app/scripts/metamask-controller.test.js (hunk 4 above)
Comment (ffmcgee725) [reply app/scripts/metamask-controller.test.js]: resolved in https://github.com/MetaMask/metamask-extension/pull/30213/commits/c9df79b148c085ba949bcf7974ba8f7216595c3a

File: app/scripts/metamask-controller.js (hunk 3 above)
Comment (ffmcgee725) [reply app/scripts/metamask-controller.js]: resolved in https://github.com/MetaMask/metamask-extension/pull/30213/commits/c9df79b148c085ba949bcf7974ba8f7216595c3a

File: app/scripts/controllers/permissions/specifications.js (hunk 2 above)
Comment (ffmcgee725) [reply app/scripts/controllers/permissions/specifications.js]: resolved in https://github.com/MetaMask/metamask-extension/pull/30213/commits/c9df79b148c085ba949bcf7974ba8f7216595c3a

File: app/scripts/controllers/permissions/specifications.js (hunk 1 above)
Comment (ffmcgee725) [reply app/scripts/controllers/permissions/specifications.js]: resolved in https://github.com/MetaMask/metamask-extension/pull/30213/commits/c9df79b148c085ba949bcf7974ba8f7216595c3a

File: app/scripts/metamask-controller.test.js (hunk 5 above)
Comment (jiexi) [reply app/scripts/metamask-controller.test.js:1675]: odd... well being extra explicit in tests is fine with me. can we make this return undefined instead of empty object? (nit)

Comment (ffmcgee725) [reply app/scripts/metamask-controller.test.js]: resolved in https://github.com/MetaMask/metamask-extension/pull/30213/commits/7a9a4a310577d7fa318fdca0ace2e4689a419682

**Comment by jiexi** [comment]
Manually validated

**Review by jiexi — APPROVED** [review]

**Review by itsyoboieltr — APPROVED** [review]
