### PR TITLE
fix: Created new migration to remove disabledUpgradeAccountByChain from preferences controller state as old migration had error

### LINKED ISSUE #33305: [Bug]: Errors in background when disabling smart transactions after extension update
### Describe the bug

When disabling STX, a few errors are thrown in the background:
- No metadata found for "disabledUpgradeAccountByChain"
- No metadata found for "bitcoinTestnetSupportEnabled"
- No metadata found for "bitcoinSupportEnabled"

### Expected behavior

No errors thrown in the background

### Screenshots/Recordings

https://www.loom.com/share/45f62fabf4014a8397e71394943a865d

### Steps to reproduce

1. Disable STX
2. Check background

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.20.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Created new migration to remove disabledUpgradeAccountByChain from preferences controller state as old migration had error

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33305

## **Manual testing steps**

1. Update extension and disable smart transactions
2. You should not see any error in background as
     > No metadata found for "disabledUpgradeAccountByChain"

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by OGPoyraz — DISMISSED** [review]

**Review by OGPoyraz — DISMISSED** [review]

File: app/scripts/migrations/170.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+function transformState(state: Record<string, unknown>) {
+  const preferencesControllerState = state?.PreferencesController as
+    | Record<string, unknown>
+    | undefined;
+
+  const preferences = preferencesControllerState?.preferences as
+    | Record<string, unknown>
+    | undefined;
+
+  delete preferences?.disabledUpgradeAccountByChain;
```
Comment (matthewwalsh0) [inline app/scripts/migrations/170.ts]: I understood the issue was that we were deleting from inside `preferences` but it was instead in the root of the state?

Plus the field was `disabledUpgradeAccountsByChain` with the plural on `Accounts`.

https://github.com/MetaMask/metamask-extension/pull/31774/files#diff-4da47dd4fbf457f67b024cb7ed574b864bc936dafe9ecd5711bf0c7069f13eb9R153

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: app/scripts/migrations/170.ts (hunk 1 above)
Comment (matthewwalsh0) [inline app/scripts/migrations/170.ts]: And I think the same issue was present for `accountUpgradeDisabledChains` so should we also delete that from the root here too?

Comment (jpuri) [reply app/scripts/migrations/170.ts]: Oh I missed this, thanks.
Let me fix.

Comment (jpuri) [reply app/scripts/migrations/170.ts]: PR is updated

Comment (jpuri) [reply app/scripts/migrations/170.ts]: PR is updated

**Review by OGPoyraz — DISMISSED** [review]

File: app/scripts/migrations/170.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+  transformState(versionedData.data);
+  return versionedData;
+}
+
+function transformState(state: Record<string, unknown>) {
+  const preferencesControllerState = state?.PreferencesController as
+    | Record<string, unknown>
+    | undefined;
+
+  delete preferencesControllerState?.disabledUpgradeAccountByChain;
```
Comment (matthewwalsh0) [inline app/scripts/migrations/170.ts]:
```suggestion
  delete preferencesControllerState?.disabledUpgradeAccountsByChain;
```

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by jpuri** [comment]
@matthewwalsh0 : reason for removing an `s` here `disabledUpgradeAccountsByChain` is that it is this is the spelling reported in the bug and thus I was bit confused:

> No metadata found for "disabledUpgradeAccountByChain"

**Comment by matthewwalsh0** [comment]
> @matthewwalsh0 : reason for removing an `s` here `disabledUpgradeAccountsByChain` is that it is this is the spelling reported in the bug and thus I was bit confused:
> 
> > No metadata found for "disabledUpgradeAccountByChain"

That is a typo on the bug description, in the attached video it includes the `s`, plus on the original PR we added the `s` 👍

**Review by OGPoyraz — APPROVED** [review]
