### PR TITLE
fix: network manager modal views cp-13.24.0

### LINKED ISSUE #41042: [Bug]: Add Custom Network triggers "MetaMask encountered an error" with empty error message
### Describe the bug

When trying to add a manual custom network through the "Select network" modal, an error appears.
`MetaMask encountered an error`
`Your information can’t be shown. Don’t worry, your wallet and funds are safe.`
`<empty message>`

### Expected behavior

_No response_

### Screenshots/Recordings

Image

Image

### Steps to reproduce

- Open MetaMask Extension
- Click on current network dropdown to open the "Select network" modal
- Go to "custom" tab" of the modal
- Scroll down to click on "+ Add custom network"
- The error appears

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

13.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by n3ps**
## **Description**

Replace the Network Manager component's internal `<Routes>` view switching with conditional rendering. This is used for the add/edit custom networks views.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: #41042 

## **Manual testing steps**

1. Click Network Manager dropdown
2. Click Edit on any popular, custom or test network

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Moderate UI routing refactor: replaces `react-router` path-based `<Routes>` with `useSearchParams` state, which can affect in-modal navigation/back behavior and any callers relying on prior sub-routes.
> 
> **Overview**
> Refactors the Network Manager modal to **stop using internal `<Routes>`/sub-paths** and instead drive its view state via the `view` query param (`useSearchParams`). Navigation actions in `AddNetwork`, `CustomNetworks`, and `useNetworkItemCallbacks` now update `view` (and clear it to return home) rather than calling `navigate()` to `/add`, `/edit`, etc.
> 
> Updates Network Manager logic that derives the `editedNetwork` and post-submit transitions (RPC/block explorer URL add flows) to use the query-param view, and extends `network-manager.test.tsx` with coverage for switching back to `add`/`edit` after submitting RPC or block explorer URLs from the corresponding `view` states.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 559efb726b7db355761d1be72e1407059a628be3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/multichain/network-manager/network-manager.tsx [hunk 1]
```diff
@@ -142,142 +143,119 @@ export const NetworkManager = () => {
       isClosedOnOutsideClick
     >
       <ModalContent size={ModalContentSize.Md}>
-        <Routes>
```
Comment (n3ps) [inline ui/components/multichain/network-manager/network-manager.tsx:145]: Replace Routes within Routes in a modal with simple conditional rendering

**Review by NidhiKJha — APPROVED** [review]

**Review by itsyoboieltr — APPROVED** [review]
