### PR TITLE
fix: Updated snap header in review permissions screen

### LINKED ISSUE #30088: Missing Snap origin as part of permission request copy
"[blank] is asking for your approval to:". The intention is to have the Snap name visible, but currently it is not displayed at all.

Image

### PR DESCRIPTION
**Pull request by NidhiKJha**
In the review permissions screen for snaps, the origin of the snap was missing. This PR fix that

## **Related issues**

Fixes: #30088 

## **Manual testing steps**

1. Connect extension to Snap 
2. Click on getAccounts
3. The review permissions screen should show Dapp Origin

### **Before**
Screenshot 2025-02-04 at 11 40 35 AM

### **After**
Screenshot 2025-02-04 at 11 42 43 AM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js [hunk 1]
```diff
@@ -56,7 +57,8 @@ export default class PermissionPageContainerContent extends PureComponent {
       });
       return accumulator;
     }, []);
-
+    const { origin } = subjectMetadata;
+    const dappOrigin = isSnapId(origin) ? origin : getURLHost(origin);
```
Comment (FrederikBolding) [inline ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js:61]:
```suggestion
    const { origin, subjectType } = subjectMetadata;
    const displayOrigin = subjectType === SubjectType.Website ? getURLHost(origin) ? : origin;
```
How about we use the subject metadata for this? Something like this?

Comment (NidhiKJha) [reply ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js]: Updated here https://github.com/MetaMask/metamask-extension/pull/30092/commits/a0d34adefd30f919334a66861628acd1aedd2e1d

File: ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js [hunk 2]
```diff
@@ -102,7 +105,7 @@ export default class PermissionPageContainerContent extends PureComponent {
         >
           <PermissionsConnectPermissionList
             permissions={selectedPermissions}
-            subjectName={subjectMetadata.origin}
+            subjectName={displayOrigin}
```
Comment (FrederikBolding) [inline ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js:108]: Why was this changed?

Comment (NidhiKJha) [reply ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js]: My bad! Reverted https://github.com/MetaMask/metamask-extension/pull/30092/commits/7abb5f844a3728a4cd4892764acc02606e813364

**Review by FrederikBolding — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
