### PR TITLE
fix: Return to send page with different asset types

### LINKED ISSUE #28316: [Bug]: Native Send - Clicking Edit/Back arrow doesn't work on the Dialog window if the tx is initiated in the full window
### Describe the bug

Whenever I am sending a native token, once I land into the last confirmation screen, if I use the MM dialog and click the Back/Edit arrow, it doesn't work and I remain in the same page.

This happens if I initiate the Send from the full view, and then try to click the Back/Edit on the Dialog view

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/d082f1c0-45ff-4879-8b01-752e9fb88e1b

### Steps to reproduce

1. Start a native send from the MM full view
2. Once on the last confirmation screen, open the popup (ie click on the MM icon, or trigger a tx from a dapp)
3. Try to click the Back/Edit arrow from the dialog
4. See nothing happens

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

This bug was reproducible by opening a new wallet initiated send confirmation with a Native token ("simple send") from the extension full screen view, and then triggering a dApp initiated confirmation, and trying to return back to the send flow stepper.

The bug was provoked due to having the `editExistingTransaction` action dispatched on back button click hardcoded for asset of type token. The fix involves dynamically determining the asset type.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28382?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28316

## **Manual testing steps**

See above or check video on the bug report ticket.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx [hunk 1]
```diff
@@ -38,7 +41,26 @@ export const WalletInitiatedHeader = () => {
   const handleBackButtonClick = useCallback(async () => {
     const { id } = currentConfirmation;
 
-    await dispatch(editExistingTransaction(AssetType.token, id.toString()));
+    const isNativeSend =
+      currentConfirmation.type === TransactionType.simpleSend;
+    const isERC20TokenSend =
+      currentConfirmation.type === TransactionType.tokenMethodTransfer;
+    const isNFTTokenSend =
```
Comment (matthewwalsh0) [inline ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx:48]: Minor, if these booleans only exist to support the if below, would it be cleaner to use a `switch`:

```
let assetType: AssetType;

switch(currentConfirmation.type) {
    case TransactionType.simpleSend:
        assetType = AssetType.native;
        break;

    ...
```

**Review by matthewwalsh0 — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
Will be nice to test cover also, may be in following PR.
