### PR TITLE
fix: replicate network change actions in rpc modal

### LINKED ISSUE #29260: [Bug]: Following a network switch, the token list does not update accordingly
### Describe the bug

There are instances where, following a network switch, the token list does not update accordingly, leading to a mismatch between the network icon and the token icons displayed. Additionally, during such occurrences, the 'Current Network' view automatically switches to the 'Popular Networks' view.

### Expected behavior

Tokens updated accordingly, network view selector doesn't switch automaically.

### Screenshots/Recordings

https://github.com/user-attachments/assets/6ad99fd0-fd6d-432f-8247-15652f357671

https://github.com/user-attachments/assets/36177df3-2df2-439b-8d3f-21fc652e292b

Image

### Steps to reproduce

1. Switch between 'Current network' and 'Popular networks' view and between networks

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

v12.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bergarces**
## **Description**

The issue occurred because switching networks from the RPC selector, which is only available when there's a network with at least 2 RPCs, was not performing the same actions as switching networks from clicking the network list item directly.

I have created a handler for the actions that need to be performed and passed it down to both the network list item and the rpc selector modal, that way it ensures that the same actions occur.

A test has been added to the rpc modal to validate the new handler is being called. Tests already exist in the network list to validate that those actions are taking place, and they are still passing.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29943?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/29260

## **Manual testing steps**

1. Ensure at least one of your networks has more than one RPC, so that the RPC selector appears.
2. Set any network and, in the Tokens tab, select "Current network" as the option.
3. Open the network selector and select another network by clicking in the rpc url, which will open an rpc selector modal.
4. Select any of the RPCs and check that the tokens from the new network appear and that "Current network" is still 

### **Before**

https://github.com/user-attachments/assets/3ac163d3-4f2e-4170-81f4-f3b4ccc8e3d3

### **After**

https://github.com/user-attachments/assets/7dc02f85-42e0-449e-a419-cc74fc936de7

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: ui/components/multichain/network-list-menu/network-list-menu.tsx [hunk 1]
```diff
@@ -252,17 +252,59 @@ export const NetworkListMenu = ({ onClose }: { onClose: () => void }) => {
     ...searchedTestNetworks,
   ].some((network) => network.rpcEndpoints.length > 1);
 
+  const handleNetworkChange = (network: NetworkConfiguration) => {
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-list-menu/network-list-menu.tsx:255]: Nice function lift. There is no new logic here.

File: ui/components/multichain/network-list-menu/network-list-menu.tsx [hunk 2]
```diff
@@ -559,6 +563,7 @@ export const NetworkListMenu = ({ onClose }: { onClose: () => void }) => {
       return (
         <SelectRpcUrlModal
           networkConfiguration={networkConfigurations[editedNetwork.chainId]}
+          onNetworkChange={handleNetworkChange}
```
Comment (Prithpal-Sooriya) [inline ui/components/multichain/network-list-menu/network-list-menu.tsx:566]: OK nice! So this performs the same set of actions for when you click in the network list. Yep this is valid!

**Review by Prithpal-Sooriya — APPROVED** [review]
LGTM.

**Review by NidhiKJha — APPROVED** [review]
LGTM
