### PR TITLE
Remove ETH badge from NetworkAccountBalanceHeader when on non-ETH net…

### LINKED ISSUE #16082: [Bug]: Hardcoded ETH badge in NetworkAccountBalanceHeader component
### Describe the bug

ETH badge shown on networks that are not Ethereum

RC nftapproval 15727

### Steps to reproduce

1. login to the extension
2. Switch networks to a custom network (e.g. Fantom)
3. navigate to the test dapp
4. deploy collectibles
5. mint collectibles
6. set approval for all

### Error messages or log output

_No response_

### Version

10.21.0

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/16082

This removes the ETH badge in the account balance header when ETH is not the default currency for the current network.

## Test Plan
1. login to the extension
2. Switch networks to a custom network (e.g. Fantom)
3. navigate to the test dapp
4. deploy collectibles
5. mint collectibles
6. set approval for all
7. Confirm the ETH badge is not shown
8. Switch networks to mainnet or a local ETH network
9. Repeat steps 3 - 7
10. Confirm the ETH badge is shown

### CODE REVIEW

**Comment by danjm** [comment]
Instead of this approach, can we show the current networks icon if it is available, and our icon default (first letter of name) if not available

File: ui/components/app/network-account-balance-header/network-account-balance-header.js [hunk 1]
```diff
@@ -45,13 +46,15 @@ export default function NetworkAccountBalanceHeader({
...
-            imageBorder
-            image="./images/eth_badge.svg"
-            className="network-account-balance-header__network-account__ident-icon-ethereum"
-          />
+          {tokenName === CURRENCY_SYMBOLS.ETH ? (
+            <Identicon
+              address={accountAddress}
+              diameter={16}
+              imageBorder
+              image="./images/eth_badge.svg"
```
Comment (danjm) [inline ui/components/app/network-account-balance-header/network-account-balance-header.js:54]: Use `CHAIN_ID_TO_NETWORK_IMAGE_URL_MAP` to show the custom image

File: ui/components/app/network-account-balance-header/network-account-balance-header.js [hunk 2]
```diff
@@ -45,13 +46,15 @@ export default function NetworkAccountBalanceHeader({
...
           <Identicon address={accountAddress} diameter={32} />
-          <Identicon
-            address={accountAddress}
-            diameter={16}
-            imageBorder
-            image="./images/eth_badge.svg"
-            className="network-account-balance-header__network-account__ident-icon-ethereum"
-          />
+          {tokenName === CURRENCY_SYMBOLS.ETH ? (
+            <Identicon
```
Comment (danjm) [inline ui/components/app/network-account-balance-header/network-account-balance-header.js:50]: I think `IconWithFallback` will achieve the desired UX if there is no icon image for the network

File: ui/components/ui/icon-with-fallback/icon-with-fallback.component.js [hunk 3]
```diff
@@ -17,21 +18,28 @@ const IconWithFallback = ({
...
+          {...props}
+        />
+      ) : (
+        <span
+          className={classnames(
+            'icon-with-fallback__fallback',
+            fallbackClassName,
+          )}
+        >
+          {name && name.length ? name.charAt(0).toUpperCase() : ''}
```
Comment (darkwing) [inline ui/components/ui/icon-with-fallback/icon-with-fallback.component.js:39]: Could this be: `name?.charAt(0).toUpperCase() || ''`?

File: ui/components/ui/icon-with-fallback/icon-with-fallback.component.js [hunk 4]
```diff
@@ -17,21 +18,28 @@ const IconWithFallback = ({
...
-    </span>
+  return (
+    <div className={classnames(wrapperClassName)}>
+      {!iconError && icon ? (
+        <img
+          onError={handleOnError}
+          src={icon}
+          style={style}
+          className={className}
+          alt={name || 'icon'}
```
Comment (darkwing) [inline ui/components/ui/icon-with-fallback/icon-with-fallback.component.js:29]: Should the `name` param default to `icon` instead of `""`?  i..e in the fn signature: `name = 'icon',`

File: ui/components/ui/icon-with-fallback/icon-with-fallback.component.js (hunk 3 above)
Comment (danjm) [reply ui/components/ui/icon-with-fallback/icon-with-fallback.component.js:39]: this code was like the before, it is just the indenting that is changing

File: ui/components/ui/icon-with-fallback/icon-with-fallback.component.js (hunk 4 above)
Comment (danjm) [reply ui/components/ui/icon-with-fallback/icon-with-fallback.component.js:29]: this code was like the before, it is just the indenting that is changing

Comment (danjm) [reply ui/components/ui/icon-with-fallback/icon-with-fallback.component.js:29]: no, because that would mess with the `name?.charAt(0).toUpperCase() || ''` code on line 39

File: ui/components/ui/icon-with-fallback/icon-with-fallback.component.js (hunk 3 above)
Comment (danjm) [reply ui/components/ui/icon-with-fallback/icon-with-fallback.component.js]: done in 541c568749

**Review by danjm — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
LGTM
