### PR TITLE
fix: slippage update on unified cp-13.1.0

### LINKED ISSUE #34820: [Bug]: Default slippage values affecting tx success
### Describe the bug

Currently, slippage for all swap/bridge transactions is set to 0.5%. This will result in transactions being dropped due to the small value.

### Expected behavior

Default slippage values should be the following for swaps/bridges:

Swap:

0.5% default slippage on every Solana token pair

0.5% default slippage on stablecoin pairs on EVM

2% default slippage on everything else on EVM

Bridge:

0.5% default slippage on all routes

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to Swaps screen
2. Open the cog icon
3. See that all swaps have 0.5% as default slippage

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ghgoodreau**
## **Description**

This PR implements smart slippage defaults for swap and bridge transactions to reduce failed transactions due to insufficient slippage tolerance. The solution introduces a service-based architecture that dynamically determines the slippage type based on the below parameters

> Swap:
> 
> 'Auto' default slippage on every Solana token pair
> 
> 0.5% default slippage on stablecoin pairs on EVM
> 
> 2% default slippage on everything else on EVM
> 
> Bridge:
> 
> 0.5% default slippage on all routes

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/34821?quickstart=1)

## **Changelog**

CHANGELOG entry: Improved default slippage values for swaps and bridges to reduce transaction failures - now uses 0.5% for Solana swaps, stablecoin pairs, and bridges, while using 2% for other EVM token swaps

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/34820

## **Manual testing steps**

> Swap:
> 
> 'Auto' default slippage on every Solana token pair
> 
> 0.5% default slippage on stablecoin pairs on EVM
> 
> 2% default slippage on everything else on EVM
> 
> Bridge:
> 
> 0.5% default slippage on all routes

1. Test the slippage value in each of the above cases.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by SteP-n-s — DISMISSED** [review]

File: shared/constants/stablecoins.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+import { CHAIN_IDS } from './network';
+
+/**
+ * A map of chain IDs to sets of known stablecoin contract addresses with deep liquidity.
+ * Used to determine if a pair qualifies for lower default slippage to avoid frontrunning.
+ * Just using USDC and USDT for now, but can add more as needed.
+ */
+export const StablecoinsByChainId: Partial<Record<string, Set<string>>> = {
+  [CHAIN_IDS.MAINNET]: new Set([
```
Comment (micaelae) [inline shared/constants/stablecoins.ts]: Nit: use constant case

```suggestion
export const STABLECOINS_BY_CHAIN_ID: Partial<Record<string, Set<string>>> = {
  [CHAIN_IDS.MAINNET]: new Set([
```

File: ui/hooks/bridge/useSmartSlippage.ts [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+    dispatch(setSlippage(newSlippage));
+    lastSetSlippageRef.current = newSlippage;
+    isUserOverrideRef.current = false;
+  }, [calculateCurrentSlippage, dispatch]);
+
+  return {
+    slippage: currentSlippage,
+    isUserOverride: isUserOverrideRef.current,
+    resetToDefault,
+  };
```
Comment (micaelae) [inline ui/hooks/bridge/useSmartSlippage.ts:135]: Are these values used?

File: shared/lib/bridge/slippage-service.ts [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+  toChain: { chainId: string } | null | undefined;
+  fromToken: BridgeToken | null;
+  toToken: BridgeToken | null;
+  isSwap: boolean;
+};
+
+/**
+ * Service for calculating smart default slippage values based on transaction context
+ */
+export class SlippageService {
```
Comment (micaelae) [inline shared/lib/bridge/slippage-service.ts]: If this is not needed by other experiences, can you move this and stablecoins.ts to the bridge ui directory? I'm planning to deprecate the `lib/bridge` dir eventually when all the shared logic is moved to the controllers

File: ui/hooks/bridge/useSmartSlippage.ts [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+    fromToken,
+    toToken,
+    isSwap,
+    enabled,
+    calculateCurrentSlippage,
+    dispatch,
+  ]);
+
+  return {
+    slippage: currentSlippage,
```
Comment (micaelae) [inline ui/hooks/bridge/useSmartSlippage.ts]: Are these values used?

File: ui/pages/bridge/utils/slippage-service.ts [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+  toChain: { chainId: string } | null | undefined;
+  fromToken: BridgeToken | null;
+  toToken: BridgeToken | null;
+  isSwap: boolean;
+};
+
+/**
+ * Service for calculating smart default slippage values based on transaction context
+ */
+export class SlippageService {
```
Comment (micaelae) [inline ui/pages/bridge/utils/slippage-service.ts]: Not blocking, but is there a reason to put these methods in a class? Seems like they can all be exported as util functions since they only read the passed-in args

File: ui/pages/bridge/utils/slippage-service.ts [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+
+    // For swaps, we need both chains to be set
+    if (!toChain?.chainId) {
+      return SlippageValue.EvmDefault;
+    }
+
+    // Cross-chain swaps are treated as bridges (0.5%)
+    if (fromChain.chainId !== toChain.chainId) {
+      return SlippageValue.BridgeDefault;
+    }
```
Comment (micaelae) [inline ui/pages/bridge/utils/slippage-service.ts]: Does this duplicate lines 95-97?

File: ui/hooks/bridge/useSmartSlippage.ts [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+  toToken,
+  isSwap,
+  enabled = true,
+}: UseSmartSlippageParams): void {
+  const dispatch = useDispatch();
+
+  // Calculate the appropriate slippage for current context
+  const calculateCurrentSlippage = useCallback(() => {
+    // Need at least fromChain to make any determination
+    if (!enabled || !fromChain?.chainId) {
```
Comment (micaelae) [inline ui/hooks/bridge/useSmartSlippage.ts]: I think you only need to check fromChain here. I'd recommend removing the enabled param for readability since it can be derived

**Review by SteP-n-s — APPROVED** [review]

**Review by micaelae — APPROVED** [review]
