### PR TITLE
fix: updated appActiveTab to check dapp url

### LINKED ISSUE #38859: [Bug]: Wallet API / Wallet UX - Side Panel - Connected Site displays my previous tab URL when I've opened a new browser tab
**Describe the bug**

Connected Site displays my previous tab URL when I've opened a new browser tab

**Screenshots/Recordings**

https://github.com/user-attachments/assets/6166eb1c-b7b0-4da4-b89c-5bcd27d8b33a

**Steps to reproduce**

1. Open MM on the side panel
2. Open test dapp
3. Click on the Connected site icon
4. See test dapp url
5. Open a new browser tab
6. Click on the Connected site icon
7. See the url is not updated, and still displays test dapp url

**Error messages or log output**

```shell

```

**Where was this bug found?**

Internal release testing

**Version**

13.14.0

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR ensures that the active tab url is updated correctly when the tabs are changed. This issue is specific to sidepanel since the side panel stays open and relies on `browser.tabs.onActivated` and `browser.tabs.onUpdated` listeners to keep appActiveTab updated in real-time. When those listeners didn't properly clear the state for `chrome://newtab`, the side panel showed stale data from the previous tab.

## **Changelog**

CHANGELOG entry:null

## **Related issues**

Fixes: #38859

## **Manual testing steps**

1. Open MM on the side panel
2. Open test dapp
3. Click on the Connected site icon
4. See test dapp url
5. Open a new browser tab
6. If it's not a dapp, connected site popover would render `URL unknown `in the title 

### **Before**

NA
### **After**

https://github.com/user-attachments/assets/4d31ffbd-dd67-4518-afce-65f1cc1127e7

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Improves correctness of sidepanel/app active tab tracking and UI messaging for non-web pages.
> 
> - Adds `isWebOrigin` util and tests; uses it in background listeners to ignore/clear `appActiveTab` for `chrome://`, `about:`, extension, etc.
> - Initializes and refreshes `appActiveTab` on startup and when the sidepanel opens; refines `tabs.onUpdated` handling (use `changeInfo`, guard on active tab, avoid stale updates).
> - Adds `clearAppActiveTab` to `AppStateController`.
> - Updates selectors and actions to derive origin via `getOriginOfCurrentTab`; adjusts connected accounts and permissions selectors with tests.
> - UI: `ConnectedSitePopover` now shows host only for web origins, otherwise displays `"URL unknown"`; connected status visibility logic simplified.
> - Localization: adds `urlUnknown` string for en/en_GB.
> - Test updates: snapshot expectations, ignored state keys, and state-logs schema adjustments to accommodate new behavior.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 229be250aa9e1a99056e0e11e89c48d6b2cce94d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ui/components/multichain/connected-site-popover/connected-site-popover.tsx [hunk 1]
```diff
@@ -44,7 +44,13 @@ export const ConnectedSitePopover: React.FC<ConnectedSitePopoverProps> = ({
 }) => {
   const t = useContext(I18nContext);
   const activeTabOrigin = useSelector(getOriginOfCurrentTab);
-  const siteName = getURLHost(activeTabOrigin);
+
+  // Only show the host for valid web URLs (http/https), otherwise show "URL unknown"
+  const isWebOrigin =
+    activeTabOrigin?.startsWith('http://') ||
+    activeTabOrigin?.startsWith('https://');
```
Comment (ameliejyc) [inline ui/components/multichain/connected-site-popover/connected-site-popover.tsx:51]: We write this function twice, let's make it reusable and add a test?

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx [hunk 2]
```diff
@@ -146,7 +146,6 @@ export const AppHeaderUnlockedContent = ({
   const showConnectedStatus =
     (getEnvironmentType() === ENVIRONMENT_TYPE_POPUP ||
       getEnvironmentType() === ENVIRONMENT_TYPE_SIDEPANEL) &&
-    origin &&
```
[the remark this answers is not in the document]
Comment (ameliejyc) [reply ui/components/multichain/app-header/app-header-unlocked-content.tsx:149]: `origin !== browser.runtime.id` when `origin` is `undefined` evaluates to true, looks like this could be a valid bug?

File: ui/components/multichain/connected-site-popover/connected-site-popover.tsx (hunk 1 above)
Comment (NidhiKJha) [reply ui/components/multichain/connected-site-popover/connected-site-popover.tsx:51]: Updated here https://github.com/MetaMask/metamask-extension/pull/39040/commits/17e37a787bb4f944432caa894b39a8c6f14df0d2

File: app/scripts/controllers/app-state-controller.ts [hunk 3]
```diff
@@ -1651,6 +1651,16 @@ export class AppStateController extends BaseController<
     });
   }
 
+  /**
+   * Clears the active tab information when switching to a non-web page
+   * (e.g., chrome://, about:, extension pages, or blank tabs)
+   */
```
Comment (ameliejyc) [inline app/scripts/controllers/app-state-controller.ts:1656]: [nit] the comment is a bit misleading - this function just sets the `appActiveTab` to undefined. The details about non-web pages relate to the context of where this function is being called (currently).

File: app/scripts/background.js [hunk 4]
```diff
@@ -1976,28 +2064,56 @@ browser.tabs.onUpdated.addListener(async (tabId) => {
...
 
-    // Update subject metadata for permission system
-    controller.subjectMetadataController.addSubjectMetadata({
-      origin,
-      name: title || host || origin,
-      iconUrl: favIconUrl || null,
-      subjectType: 'website',
-    });
+    // Also check if this tab is actually the active tab in the current window
+    let isActuallyActive = false;
```
Comment (ameliejyc) [inline app/scripts/background.js]: Can you add more info about why this extra check is needed?

File: app/scripts/background.js [hunk 5]
```diff
@@ -1976,28 +2064,56 @@ browser.tabs.onUpdated.addListener(async (tabId) => {
...
-      url,
-      host,
-      href,
-      favIconUrl,
-    });
+    // Only update if this is the currently active tab
+    // This prevents updating with stale data from background tabs
+    const currentAppActiveTab =
+      controller.appStateController.state.appActiveTab;
+    const isActiveTab = currentAppActiveTab?.id === id;
```
Comment (ameliejyc) [inline app/scripts/background.js]: `currentAppActiveTab` and `currentAppActiveTab?.id === id` are used multiple times, maybe let's bring these two constants further up so we don't have to keep repeating them.

File: test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json [hunk 6]
```diff
@@ -349,18 +349,18 @@
...
   },
   "SnapInsightsController": { "insights": "object" },
   "SnapInterfaceController": { "interfaces": "object" },
   "SnapsRegistry": {
     "database": "object",
+    "signature": "string",
     "lastUpdated": "number",
-    "databaseUnavailable": "boolean",
-    "signature": "string"
+    "databaseUnavailable": "boolean"
```
Comment (ameliejyc) [inline test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json:368]: [nit] a few of these have moved out of alphabetical order

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx [hunk 7]
```diff
@@ -146,7 +146,6 @@ export const AppHeaderUnlockedContent = ({
...
     origin !== browser.runtime.id;
```
Comment (ameliejyc) [inline ui/components/multichain/app-header/app-header-unlocked-content.tsx:149]: Should we add the check for origin back in so this doesn't evaluate to `true` when `origin` is undefined?

File: app/scripts/background.js [hunk 8]
```diff
@@ -1952,18 +2024,34 @@ browser.tabs.onActivated.addListener(async ({ tabId }) => {
...
+  const statusComplete = changeInfo.status === 'complete';
+
+  if (!urlChanged && !statusComplete) {
+    return {};
+  }
+
   try {
-    const tabInfo = await browser.tabs.get(tabId);
+    // Use tab from parameter if available, otherwise fetch it
+    const tabInfo = tab || (await browser.tabs.get(tabId));
```
Comment (ameliejyc) [inline app/scripts/background.js:2056]: Is `tab` ever undefined here? It looks like it should always be an object? I'm not sure that `(await browser.tabs.get(tabId))` would ever be reached

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx (hunk 7 above)
Comment (NidhiKJha) [reply ui/components/multichain/app-header/app-header-unlocked-content.tsx:149]: We want to show connected status when  origin is undefined. For those scenarios, we added unknown URL

File: test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json (hunk 6 above)
Comment (NidhiKJha) [reply test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json:368]: Hmm... I have ran lint:fix command on it. So, I am not sure if it's an issue

File: app/scripts/background.js (hunk 8 above)
Comment (NidhiKJha) [reply app/scripts/background.js:2056]: Added comment for tab parameter here https://github.com/MetaMask/metamask-extension/pull/39040/commits/3617f9f90e742577a853b2d373152b08ea670bb7

File: app/scripts/background.js (hunk 5 above)
Comment (NidhiKJha) [reply app/scripts/background.js]: Good shout, updated here https://github.com/MetaMask/metamask-extension/pull/39040/commits/3617f9f90e742577a853b2d373152b08ea670bb7

File: app/scripts/background.js (hunk 4 above)
Comment (NidhiKJha) [reply app/scripts/background.js]: Yes, here https://github.com/MetaMask/metamask-extension/pull/39040/commits/3617f9f90e742577a853b2d373152b08ea670bb7

File: ui/components/multichain/app-header/app-header-unlocked-content.tsx (hunk 7 above)
Comment (ameliejyc) [reply ui/components/multichain/app-header/app-header-unlocked-content.tsx:149]: Oh does connected status mean showing the globe icon?

File: ui/selectors/selectors.js [hunk 9]
```diff
@@ -3988,10 +3988,11 @@ export function getOrderedConnectedAccountsForConnectedDapp(state, activeTab) {
 }
 
 export function getPermissionsForActiveTab(state) {
-  const { activeTab, metamask } = state;
+  const { metamask } = state;
```
[the remark this answers is not in the document]
Comment (NidhiKJha) [reply ui/selectors/selectors.js:3991]: updated here https://github.com/MetaMask/metamask-extension/pull/39040/commits/40844dee99d8f34cf00b3750e53e16644f955875

**Review by seaona — APPROVED** [review]
QA files LGTM (note the rest of the PR is not reviewed)

File: ui/components/multichain/connected-site-popover/connected-site-popover.tsx [hunk 10]
```diff
@@ -44,7 +44,13 @@ export const ConnectedSitePopover: React.FC<ConnectedSitePopoverProps> = ({
 }) => {
   const t = useContext(I18nContext);
   const activeTabOrigin = useSelector(getOriginOfCurrentTab);
-  const siteName = getURLHost(activeTabOrigin);
+
+  // Only show the host for valid web URLs (http/https), otherwise show "URL unknown"
+  const isWebOrigin =
```
Comment (n3ps) [inline ui/components/multichain/connected-site-popover/connected-site-popover.tsx:49]: @NidhiKJha can this use the same isWebOrigin in util?

File: test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json [hunk 11]
```diff
@@ -355,6 +353,7 @@
     "orderedTransactionHistory": "object",
     "claimsConfigurations": "object",
     "claims": "object",
+    "drafts": "object",
```
Comment (n3ps) [inline test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json:356]: nit: not a blocker but I wonder why these fields moved

Comment (NidhiKJha) [reply test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json:356]: Happened because of lint update. I ran `lint:fix` to fix the linting issues and they were updated

**Review by n3ps — APPROVED** [review]
